# -*- coding: utf-8 -*-
"""
Question bank for subject 17: OS102 - Memory, Storage & File Systems.
Category: Operating Systems & System Programming.

Topics:
   81: Virtual Memory & Paging
   82: Segmentation
   83: File Systems
   84: Disk Scheduling
   85: I/O Systems & DMA

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    81: [
        ("BEGINNER", "What is the purpose of virtual memory?",
         ["To let processes use more memory than physically exists by moving pages between RAM and secondary storage", "To double the CPU speed", "To compress files", "To remove the need for RAM"], "A",
         "Virtual memory extends the apparent size of memory by keeping parts of the address space on disk and swapping them in as needed."),
        ("BEGINNER", "What is a page in the context of paging?",
         ["A fixed-size block of physical memory", "A fixed-size block of virtual address space", "A variable-length chunk of a program", "A sector of the hard disk"], "B",
         "A page is a fixed-size unit of virtual memory that can be mapped to an equal-sized physical frame."),
        ("BEGINNER", "What event occurs when a program references a virtual address that is not currently in physical memory?",
         ["cache hit", "deadlock", "page fault", "segmentation fault"], "C",
         "A page fault happens when the referenced page is not resident in physical memory and must be brought in from disk."),
        ("BEGINNER", "What is a frame in a paging system?",
         ["A fixed-size block of virtual memory", "A unit of file storage", "A page table entry", "A fixed-size block of physical memory"], "D",
         "A frame is a fixed-size block of physical memory that a page can be loaded into."),
        ("BEGINNER", "What is the purpose of a page table?",
         ["It maps virtual page numbers to physical frame numbers", "It stores the contents of every page", "It schedules processes for the CPU", "It allocates space on the disk"], "A",
         "The page table holds one entry per virtual page, recording which frame (if any) each page currently maps to."),
        ("BEGINNER", "What does the abbreviation MMU stand for?",
         ["Main Memory Utility", "Memory Management Unit", "Multiple Memory Unit", "Modular Memory Update"], "B",
         "The MMU is the hardware component that translates virtual addresses to physical addresses during every memory reference."),
        ("BEGINNER", "Which of the following is an example of secondary storage?",
         ["RAM", "CPU register", "hard disk", "L2 cache"], "C",
         "A hard disk is secondary storage, which is slower and larger than primary memory and is used to back the virtual address space."),
        ("BEGINNER", "What does demand paging mean?",
         ["All pages are loaded when a process starts", "Pages are prefetched in large batches", "Pages are never loaded from disk", "Pages are loaded only when they are first referenced"], "D",
         "Demand paging brings a page into memory only when it is actually referenced, reducing initial load time and memory use."),
        ("BEGINNER", "What is a typical page size in modern operating systems?",
         ["4 kilobytes", "4 bytes", "4 megabytes", "512 bytes"], "A",
         "Most modern systems use a page size of 4 KB, although larger sizes such as 2 MB are also available for huge pages."),
        ("BEGINNER", "What happens during a TLB miss?",
         ["The page table is consulted to obtain the correct address translation", "The CPU stops permanently", "The entire disk is scanned", "The process is terminated"], "A",
         "On a TLB miss the MMU must walk the page table to find the mapping, because the needed translation was not found in the cache."),
        ("INTERMEDIATE", "A system uses 4 KB pages and a logical address of 12292. Which page number does this address belong to?",
         ["2", "3", "1", "4"], "B",
         "Dividing 12292 by the 4096-byte page size gives 3 pages, with the remainder 4 being the offset within page 3."),
        ("INTERMEDIATE", "A page table maps page 2 to frame 7. With 4 KB pages, what is the physical address for a virtual address of 2 pages plus offset 100?",
         ["28868", "28676", "28772", "29204"], "C",
         "The physical address is the frame number times the page size plus the offset, so 7 * 4096 + 100 = 28772."),
        ("INTERMEDIATE", "Three page frames hold pages 1, 2, 3 initially. Reference order is 4, 2, 3, 1. How many page faults occur with FIFO replacement?",
         ["3", "4", "2", "5"], "D",
         "Page 4 faults and evicts page 1, pages 2 and 3 are already present, then page 1 faults and evicts page 2, giving 2 faults."),
        ("INTERMEDIATE", "Three frames contain pages 1, 2, 3 and references arrive as 1, 3, 2, 4. Using LRU replacement, which page is evicted when page 4 arrives?",
         ["page 1", "page 3", "page 2", "page 4"], "A",
         "After referencing 1, 3 and 2, page 1 has the oldest access time, so LRU evicts page 1 when page 4 arrives."),
        ("INTERMEDIATE", "A system has 8 KB pages. How many bits are needed to represent the offset within a page?",
         ["10", "13", "12", "8"], "B",
         "An 8 KB page holds 8192 bytes and 8192 = 2^13, so 13 bits are required for the offset."),
        ("INTERMEDIATE", "Memory access takes 100 ns and a page fault takes 8 ms. If the page fault rate is 0.1 percent, what is the approximate effective access time?",
         ["100 ns", "8000 ns", "8100 ns", "900 ns"], "C",
         "Effective access time is 0.999 * 100 ns plus 0.001 * 8000000 ns, which is roughly 8100 ns."),
        ("INTERMEDIATE", "Which page replacement algorithm suffers from Belady's anomaly, where more frames can cause more faults?",
         ["LRU", "Optimal", "Clock", "FIFO"], "D",
         "FIFO is known to exhibit Belady's anomaly, where increasing the number of frames can increase the number of page faults."),
        ("INTERMEDIATE", "A process has a virtual address space of 4 GB and uses 4 KB pages. How many page table entries does its address space require?",
         ["1,048,576", "1024", "4,194,304", "262,144"], "A",
         "4 GB divided by 4 KB equals 1,048,576 pages, so that many page table entries are needed for the full address space."),
        ("INTERMEDIATE", "What does the valid-invalid bit in a page table entry indicate?",
         ["whether the page is executable", "whether the page is present in physical memory", "whether the page is shared", "whether the page is clean"], "B",
         "The valid-invalid bit tells whether the entry maps to a real frame; a cleared bit causes a page fault on access."),
        ("INTERMEDIATE", "Why are multi-level page tables used for large address spaces?",
         ["to speed up memory access", "to make pages smaller", "to avoid allocating the full page table when most of the address space is unused", "to store page contents in the table"], "C",
         "Multi-level tables are sparse, so only the portions of the hierarchy actually needed are allocated, saving a great deal of memory."),
        ("ADVANCED", "A TLB has a hit ratio of 99 percent, TLB lookup costs 2 ns and memory access costs 100 ns. What is the effective address translation time?",
         ["4 ns", "2 ns", "3 ns", "100 ns"], "C",
         "The effective time is 0.99 * 2 ns plus 0.01 * 102 ns, which equals about 3 ns."),
        ("ADVANCED", "Which mechanism does a fork system call commonly use to avoid copying the entire parent address space?",
         ["eager copying", "memory compaction", "swap prefetching", "copy-on-write"], "D",
         "Copy-on-write lets the child and parent share pages and copies a page only when one of them tries to write to it."),
        ("ADVANCED", "The working set model of a process is the set of pages it currently needs. What does tracking the working set enable an OS to do?",
         ["decide how many frames to allocate to avoid thrashing", "shrink the page size", "eliminate the TLB", "remove the need for swapping"], "A",
         "If the working set of all processes exceeds physical memory, the OS knows thrashing will occur and can suspend a process."),
        ("ADVANCED", "What is the main benefit of using large (huge) pages on modern systems?",
         ["smaller physical memory frames", "fewer TLB misses for large contiguous memory regions", "faster page fault handling", "reduced swap space usage"], "B",
         "Huge pages let a single TLB entry cover a much larger region, dramatically cutting TLB misses for big workloads."),
        ("ADVANCED", "What is a memory-mapped file?",
         ["a file stored entirely in RAM", "a file that can only be read once", "a file whose contents are mapped into a process virtual address space so reads and writes use normal memory instructions", "a compressed image of a disk"], "C",
         "Memory-mapped files allow a file to be accessed through the virtual memory system, so paging handles moving data to and from the disk."),
        ("ADVANCED", "Which page replacement algorithm uses a reference bit plus a second chance hand to approximate LRU cheaply?",
         ["Optimal", "FIFO with no bits", "Second-in-first-out", "clock algorithm"], "D",
         "The clock algorithm walks the frames in a circular list and uses the reference bit to give pages a second chance before eviction."),
        ("ADVANCED", "What is the key advantage of a reverse (inverted) page table?",
         ["it needs only one entry per physical frame, so its size scales with physical memory instead of virtual address space", "it stores pages in reverse order on disk", "it eliminates page faults", "it speeds up disk writes"], "A",
         "An inverted page table has one entry per frame, keeping it compact even for huge virtual address spaces, at the cost of slower lookup."),
        ("ADVANCED", "Why must the TLB be flushed when switching between processes that do not share an address space?",
         ["the TLB would overflow", "stale mappings from the previous process would translate the new process's virtual addresses incorrectly", "the new process needs more frames", "the MMU would be powered off"], "B",
         "Because TLB entries map to the previous process's frames, they must be invalidated so the new process does not reuse wrong translations."),
        ("ADVANCED", "Which situation makes demand paging most beneficial?",
         ["a program that touches every page immediately", "a program with no disk access", "a program that uses only a small fraction of its address space during a run", "a program that fits entirely in the cache"], "C",
         "Demand paging shines when much of a program's address space is rarely touched, so only the used pages are ever brought in."),
        ("ADVANCED", "Which of the following is a reason to use swap space that is separate from regular file storage?",
         ["swap space holds user documents", "swap space backs up the hard disk", "swap space removes the need for RAM", "swap files can be allocated as raw blocks with no file system overhead, giving faster paging"], "D",
         "Raw swap partitions or preallocated swap files avoid file system metadata overhead, making page-out and page-in faster."),
    ],
    82: [
        ("BEGINNER", "What is a segment in segmentation-based memory management?",
         ["a variable-sized logical unit of a program such as code, data or stack", "a fixed-size block of memory", "a physical disk partition", "a type of cache line"], "A",
         "Segmentation divides a program into variable-sized logical units that correspond to natural parts like functions, data or the stack."),
        ("BEGINNER", "A logical address in a segmented system consists of which two parts?",
         ["page number and frame", "segment number and offset", "base and limit register", "track and sector"], "B",
         "A segmented logical address is a pair containing a segment selector and an offset within that segment."),
        ("BEGINNER", "What does a segment table entry primarily contain?",
         ["the contents of the segment", "the disk block number", "the base address and limit of the segment", "the process priority"], "C",
         "Each segment table entry stores the starting (base) address of the segment in memory and its length (limit)."),
        ("BEGINNER", "What is the purpose of the segment limit field?",
         ["to record the segment name", "to store the segment contents", "to count page faults", "to detect when an offset exceeds the segment size, preventing illegal access"], "D",
         "The limit defines the maximum valid offset; an offset beyond it causes a trap, preventing access outside the segment."),
        ("BEGINNER", "Which memory management scheme allocates memory in variable-sized chunks and suffers from external fragmentation?",
         ["segmentation", "paging", "caching", "segmented paging"], "A",
         "Because segments have variable sizes, holes of odd sizes accumulate between them, causing external fragmentation."),
        ("BEGINNER", "Which field in a segment descriptor restricts what operations a process may perform on a segment?",
         ["base address", "protection bits", "limit", "segment number"], "B",
         "Protection bits such as read, write and execute permissions control what access is allowed to the segment."),
        ("BEGINNER", "What does the base address of a segment represent?",
         ["the end of the segment", "the segment number", "the starting physical address where the segment is placed in memory", "the size of the segment"], "C",
         "The base address is the physical location where the segment begins, and the offset is added to it to form a physical address."),
        ("BEGINNER", "In an x86 system, which table holds descriptors that describe the segments visible to a process?",
         ["the page table", "the file allocation table", "the interrupt vector table", "the Global Descriptor Table or Local Descriptor Table"], "D",
         "Segments are described by descriptors stored in the GDT (global) and LDT (local per-process) tables."),
        ("BEGINNER", "Which statement about segments is true?",
         ["segments can be different sizes and represent logical program units", "all segments must be the same size", "segments are stored on the stack", "segments never share memory"], "A",
         "Segments are variable-sized and correspond to logical units, which is the defining idea of segmentation."),
        ("BEGINNER", "What is external fragmentation?",
         ["memory wasted inside pages", "memory wasted because the leftover free spaces are too small and scattered to be useful", "memory used by the kernel", "memory lost during a reboot"], "B",
         "External fragmentation occurs when many small non-contiguous holes exist, none large enough to satisfy a request even though total free memory is sufficient."),
        ("INTERMEDIATE", "A segment has a base of 8000 and a limit of 500. An access to offset 200 is requested. What is the resulting physical address?",
         ["8500", "8200", "7800", "8000"], "B",
         "The offset 200 is within the limit of 500, so the physical address is base 8000 plus offset 200, which is 8200."),
        ("INTERMEDIATE", "A segment has a base of 4000 and a limit of 300. What happens when an access with offset 400 is attempted?",
         ["the access proceeds normally", "the segment grows automatically", "a trap is raised because the offset exceeds the limit", "the offset is truncated to 300"], "C",
         "Since 400 exceeds the limit of 300, the hardware raises a protection trap (segment fault) rather than allowing the access."),
        ("INTERMEDIATE", "Which property of segmentation makes it easier than paging to share code libraries between processes?",
         ["segments are fixed size", "segments are copied on write", "segments are always private", "segments are logical units that can be shared at segment granularity with protection"], "D",
         "Code segments can be shared whole with read-only protection, whereas paging shares at a coarser and less meaningful page granularity."),
        ("INTERMEDIATE", "A segment table maps segment 1 to base 5000 with limit 2000. What is the physical address for logical address (1, 1500)?",
         ["6500", "5000", "3500", "8000"], "A",
         "Offset 1500 is within the limit of 2000, so the address is base 5000 plus 1500, which equals 6500."),
        ("INTERMEDIATE", "Which scheme combines the protection and sharing of segmentation with the non-fragmented memory allocation of paging?",
         ["pure segmentation", "segmented paging", "pure paging", "contiguous allocation"], "B",
         "Segmented paging divides segments into pages, so segment-level sharing is kept while memory is allocated in fixed-size pages."),
        ("INTERMEDIATE", "Which kind of fragmentation is segmentation vulnerable to?",
         ["internal fragmentation", "TLB fragmentation", "external fragmentation", "frame fragmentation"], "C",
         "Variable-size segments create scattered holes, i.e. external fragmentation, rather than wasted space inside fixed blocks."),
        ("INTERMEDIATE", "Two processes want to share the same read-only code. In a segmented system, what is the cleanest way to support this?",
         ["copy the code into each process", "store the code on the swap disk", "allocate the code on the stack", "map both segment tables to the same base and limit with read-only protection"], "D",
         "Pointing both processes' segment table entries at the same physical base with read-only protection gives safe shared code."),
        ("INTERMEDIATE", "A stack segment grows downward from its limit toward its base. What happens to the offset compared with the limit as the stack grows?",
         ["the offset decreases while the limit stays fixed", "the offset increases past the limit", "the base changes", "the segment disappears"], "A",
         "For a growing-downward segment, the hardware compares the offset to the limit and traps when the offset crosses it."),
        ("INTERMEDIATE", "In segmented paging, what does the segment table entry hold?",
         ["the physical contents of the segment", "the base address and length of the page table for that segment", "the disk block of the segment", "the segment name"], "B",
         "Each segment in segmented paging points to its own page table, described by a base and length in the segment table."),
        ("INTERMEDIATE", "Which component performs the base-plus-offset check and raises a trap on violation in a segmented system?",
         ["the file system", "the scheduler", "the memory management unit (MMU)", "the device controller"], "C",
         "The MMU compares the offset against the limit and traps if the offset is out of range, giving hardware protection."),
        ("ADVANCED", "Which design combines segmentation's logical view with paging's physical allocation while adding only modest hardware complexity?",
         ["pure segmentation", "pure paging", "segmented paging where segments are divided into pages", "relocation registers only"], "C",
         "Segmented paging keeps segment-level sharing and protection while allocating memory in fixed pages, avoiding external fragmentation."),
        ("ADVANCED", "Which protection configuration is appropriate for a shared read-only code segment?",
         ["write permission only", "read and execute permission, no write permission", "no permissions", "read, write and execute"], "B",
         "Read and execute without write prevents any process from corrupting the shared code while still allowing it to run."),
        ("ADVANCED", "How can an OS eliminate external fragmentation in a pure segmentation system?",
         ["compaction by moving segments together during idle time", "increasing the page size", "disabling the MMU", "using only the stack segment"], "A",
         "Compaction relocates segments so all free space is contiguous, but it is costly because segments must be moved and bases updated."),
        ("ADVANCED", "Why does a flat memory model simplify system software compared with a segmented model?",
         ["segments are larger", "the TLB is not needed", "compilation is impossible in segmented models", "all addresses refer to a single linear address space, removing the need to manage segment boundaries"], "D",
         "A flat model treats the whole address space as one linear range, so compilers and linkers do not have to manage segment relocation."),
        ("ADVANCED", "In x86 protected mode, what do privilege levels (rings) in segment descriptors control?",
         ["which operations and resources code running at that level may access", "the segment's size", "the disk block used", "the process priority"], "A",
         "The 2-bit privilege field gives four rings; higher rings protect the OS from less privileged application code."),
        ("ADVANCED", "Which statement best describes why segmented addressing fell out of favor in most general-purpose OSes?",
         ["segments cannot be shared", "paging with protection provides similar benefits with fixed-size allocation and simpler management", "segments are too large", "the hardware does not support segments"], "B",
         "Pure segmentation's variable sizes cause external fragmentation, while paging achieves protection and sharing with far simpler management."),
        ("ADVANCED", "For a process that reserves a huge virtual address space but touches little of it, which scheme is more memory-efficient?",
         ["pure segmentation", "contiguous allocation", "paging with sparse multi-level page tables", "fixed partitions"], "C",
         "Sparse paging only allocates the page table levels that are actually used, so a large but mostly empty address space costs little memory."),
        ("ADVANCED", "Which hardware feature is minimally required for a system to implement segmentation protection?",
         ["a second CPU core", "a large cache", "a hardware interrupt timer", "registers or table entries holding base and limit that the MMU checks on every access"], "D",
         "Base and limit values plus hardware checks allow every memory access to be validated against the segment bounds."),
        ("ADVANCED", "Two processes share a segment, then one writes to it. If the segment descriptor only allows read access, what occurs?",
         ["the write traps with a protection fault", "the write silently succeeds", "the segment is duplicated", "the process is paused"], "A",
         "The read-only protection bit causes the hardware to raise a protection fault on the attempted write, preventing corruption."),
        ("ADVANCED", "What is the main trade-off of using an LDT per process in addition to the GDT?",
         ["it doubles the RAM size", "it isolates each process's segment descriptors, but adds context-switch and lookup overhead", "it removes the need for paging", "it makes segments unwritable"], "B",
         "An LDT gives each process its own descriptor table for isolation, but must be loaded and validated on every context switch."),
    ],
    83: [
        ("BEGINNER", "What is a file in an operating system?",
         ["a named collection of related data stored on secondary storage", "a running program", "a hardware device", "a segment of memory"], "A",
         "A file is a named, addressable collection of data that the OS stores persistently on secondary storage."),
        ("BEGINNER", "What is a directory in a file system?",
         ["a type of memory", "a structure that organizes and names files", "a disk sector", "a hardware cache"], "B",
         "A directory maps file names to their file metadata, giving the file system a hierarchical naming structure."),
        ("BEGINNER", "What is file metadata?",
         ["the data contained in the file", "the name of the disk", "information about a file such as size, owner and timestamps", "a copy of the file"], "C",
         "Metadata describes the file itself, including its size, owner, permissions and creation and modification times."),
        ("BEGINNER", "What is the root directory in a hierarchical file system?",
         ["the first file created on a disk", "a directory that holds deleted files", "a hidden system file", "the top-level directory from which all paths begin"], "D",
         "The root is the highest-level directory, and every absolute path starts from it."),
        ("BEGINNER", "What is an absolute path?",
         ["a path that begins at the root directory", "a path relative to the current directory", "a path that never changes", "a path containing no directories"], "A",
         "An absolute path starts from the root directory and identifies a file unambiguously regardless of the current directory."),
        ("BEGINNER", "What is a relative path?",
         ["a path from the root directory", "a path interpreted from the current working directory", "a path that cannot fail", "a path on a different disk"], "B",
         "A relative path locates a file by starting from the current working directory rather than the root."),
        ("BEGINNER", "Which system call is used to remove a file from the file system?",
         ["write", "mount", "unlink", "sync"], "C",
         "The unlink call removes a file's directory entry and, when the last link is gone, frees its blocks."),
        ("BEGINNER", "What does a file name extension such as .txt typically indicate?",
         ["the file's size", "the disk the file is stored on", "the owner of the file", "the type or intended format of the file contents"], "D",
         "Extensions are a convention used to hint at a file's format, although the OS itself may not rely on them."),
        ("BEGINNER", "What is a file system?",
         ["A set of structures and rules that organizes how files are named, stored and retrieved on a storage device", "A physical hard disk", "A type of memory", "A program that edits files"], "A",
         "A file system imposes naming and layout rules so the operating system can persistently store, locate and manage files."),
        ("BEGINNER", "What does a directory entry mainly contain?",
         ["the complete file contents", "a file name and a reference to the file's metadata", "the file's permissions only", "a backup of the file"], "B",
         "A directory entry binds a name to an inode or similar metadata record, not to the file's data itself."),
        ("INTERMEDIATE", "In an inode-based file system, which of the following is stored in the inode?",
         ["the full file contents", "the file's size and pointers to its data blocks", "the directory listing", "the file name"], "B",
         "The inode holds metadata such as size and block pointers, while the file name lives in a directory entry."),
        ("INTERMEDIATE", "Which allocation method suffers from external fragmentation and requires files to be placed in contiguous runs?",
         ["linked allocation", "contiguous allocation", "indexed allocation", "extent allocation"], "C",
         "Contiguous allocation needs a single continuous run of blocks per file, leaving scattered holes and requiring compaction."),
        ("INTERMEDIATE", "What is the main drawback of linked (chained) allocation for files?",
         ["it wastes disk space", "it cannot share files", "it corrupts metadata", "random access is slow because blocks must be followed one by one"], "D",
         "In linked allocation, reaching block n requires walking the pointers from the start, so random access is inefficient."),
        ("INTERMEDIATE", "What is the primary advantage of indexed allocation?",
         ["it supports fast random access without external fragmentation", "it needs no disk space for indexes", "it cannot grow files", "it stores all data contiguously"], "A",
         "An index block holds all the file's block pointers, so any block can be located directly while blocks can be scattered freely."),
        ("INTERMEDIATE", "What does the File Allocation Table (FAT) store for a FAT file system?",
         ["the contents of each file", "the next block in the chain for every block on the disk", "the file names", "the user passwords"], "B",
         "FAT keeps a per-block entry that points to the next block in a file's chain, so there is no scattered pointer per block."),
        ("INTERMEDIATE", "Two hard links to the same file share what property?",
         ["the same file name", "the same creation time only", "the same inode number", "the same directory"], "C",
         "Hard links are additional directory entries pointing to the same inode, so they share the inode number and data."),
        ("INTERMEDIATE", "If the target of a symbolic link is deleted, what happens to the symbolic link?",
         ["it is updated automatically", "it keeps a copy of the data", "it becomes a hard link", "it becomes a dangling link that no longer resolves"], "D",
         "A symbolic link stores the target's path, so when the target is removed the link still exists but cannot be followed."),
        ("INTERMEDIATE", "Which structure is commonly used to track free blocks so new blocks can be found quickly?",
         ["a bitmap or free list", "the root directory", "the superblock copy", "the journal"], "A",
         "A bitmap marks each block as free or used, allowing the allocator to locate free blocks in constant search time."),
        ("INTERMEDIATE", "Which allocation method provides fast random access and eliminates external fragmentation while using one extra block per file?",
         ["contiguous allocation", "indexed allocation", "linked allocation", "none of these"], "B",
         "Indexed allocation puts all block pointers in an index block, enabling direct access to any block with no fragmentation."),
        ("INTERMEDIATE", "In a typical Unix-like file system, what does a directory actually contain?",
         ["the data of every file", "a copy of the disk bitmap", "name-to-inode mappings for the files in it", "the free block list"], "C",
         "Directories store pairs of file names and inode numbers, while all data and metadata live elsewhere."),
        ("ADVANCED", "What is the purpose of journaling in a file system?",
         ["to compress file contents", "to encrypt the disk", "to keep the file system consistent by logging metadata updates before they are applied", "to speed up disk reads"], "C",
         "A journal records pending metadata changes so that after a crash the file system can replay or discard them and remain consistent."),
        ("ADVANCED", "Which of these is a journaling file system?",
         ["FAT32", "ISO 9660", "UDF", "ext4"], "D",
         "ext4 is a journaling file system, whereas FAT32 has no journal and relies on scandisk-style repair."),
        ("ADVANCED", "Why do log-structured file systems perform well for many small writes?",
         ["writes are batched into large sequential segments instead of scattered small updates", "they never write to disk", "they use a smaller block size", "they keep data only in RAM"], "A",
         "Log-structured designs accumulate writes into large contiguous segments, turning many random small I/Os into efficient sequential ones."),
        ("ADVANCED", "What does a copy-on-write file system such as ZFS or Btrfs gain from never overwriting live data in place?",
         ["a smaller disk footprint", "cheap snapshots and crash safety because old versions of blocks remain intact", "faster random reads", "no need for a directory"], "B",
         "Since blocks are written to new locations, prior versions remain valid, enabling snapshots and robust recovery after crashes."),
        ("ADVANCED", "After an unclean shutdown, what is the purpose of a file system check (fsck)?",
         ["to delete user files", "to defragment the disk", "to detect and repair inconsistencies in metadata such as block counts and links", "to reset user passwords"], "C",
         "fsck scans metadata structures and fixes inconsistencies like lost blocks or wrong link counts left by a crash."),
        ("ADVANCED", "What is an extent in modern file systems like ext4?",
         ["a single 4 KB block", "a directory entry", "a disk partition", "a contiguous run of blocks allocated as a unit and recorded with just start and length"], "D",
         "An extent records a starting block and its length, so large contiguous allocations need only one entry instead of many."),
        ("ADVANCED", "Why do flash-based file systems and log-structured designs favor large sequential writes?",
         ["flash erases in large blocks, so sequential writes reduce write amplification and wear", "flash reads are slow", "flash cannot be overwritten", "flash stores data on tape"], "A",
         "Because erasing flash happens in large units, aligning writes into large sequential segments minimizes erase overhead and wear."),
        ("ADVANCED", "What does the FUSE framework allow a developer to do?",
         ["overclock the CPU", "implement a custom file system in user space without modifying the kernel", "encrypt the disk permanently", "replace the boot loader"], "B",
         "FUSE exports file system calls to a user-space daemon, letting custom file systems run as ordinary processes."),
        ("ADVANCED", "Which file system feature is most important for avoiding long fsck times on very large disks?",
         ["a larger block size", "a bigger directory cache", "journaling so only recent updates need replaying after a crash", "more disk partitions"], "C",
         "With a journal, recovery after a crash only replays a bounded log of recent updates instead of scanning the whole disk."),
        ("ADVANCED", "For an SSD, why is it beneficial to leave free space in a partition?",
         ["the disk becomes faster with age", "it improves read speed", "it creates larger files", "the controller needs spare blocks for garbage collection and wear leveling"], "D",
         "Free (over-provisioned) blocks give the flash controller room to relocate data during garbage collection without stalling writes."),
    ],
    84: [
        ("BEGINNER", "What is a track on a magnetic hard disk?",
         ["a concentric ring of sectors on a platter surface", "a single sector", "a group of platters", "a cache line"], "A",
         "A track is one circular ring of recorded data on a platter, subdivided into sectors."),
        ("BEGINNER", "What is seek time?",
         ["the time to transfer a sector", "the time to move the read-write head to the required track", "the time the disk spins", "the time to power on the disk"], "B",
         "Seek time is the time spent positioning the disk arm at the cylinder holding the desired track."),
        ("BEGINNER", "What is rotational latency?",
         ["the time to move the arm", "the time to format the disk", "the time for the disk to rotate so the desired sector reaches the head", "the time to boot the system"], "C",
         "Rotational latency is the delay while the platter rotates until the requested sector arrives under the head."),
        ("BEGINNER", "What is a sector on a disk?",
         ["a whole platter", "a cache block", "a cylinder", "the smallest addressable unit of storage on a disk"], "D",
         "A sector is the fixed-size, smallest addressable unit of a disk, traditionally 512 bytes."),
        ("BEGINNER", "What does FCFS stand for in disk scheduling?",
         ["First Come, First Served", "Fastest Cylinder First Served", "First Cylinder, First Seek", "Full Cycle First Serve"], "A",
         "FCFS serves requests in the exact order they arrive, without reordering to reduce head movement."),
        ("BEGINNER", "What is the disk arm?",
         ["the motor that spins the platters", "the mechanical assembly that moves the read-write heads across the platters", "the disk controller chip", "a cache buffer"], "B",
         "The disk arm carries the read-write heads and moves radially to position them over the requested track."),
        ("BEGINNER", "What is a cylinder on a hard disk?",
         ["a single sector", "the whole disk", "the set of tracks at the same radial position across all platters", "a cache line"], "C",
         "A cylinder consists of all tracks with the same radius on every platter, so the arm reaches them together."),
        ("BEGINNER", "What does transfer time measure?",
         ["the time to move the arm", "the time between requests", "the disk spin-up time", "the time to read or write the actual data once the head is positioned"], "D",
         "Transfer time is how long it takes to move the data between the disk surface and the host once positioned."),
        ("BEGINNER", "What is average access time for a disk made up of?",
         ["average seek time plus average rotational latency plus transfer time", "only the transfer time", "only the seek time", "the power-up time"], "A",
         "Access time is the total of seek, rotational latency and transfer, and its average is reported as the disk's access time."),
        ("BEGINNER", "Which disk scheduling algorithm serves requests strictly in the order they arrive?",
         ["SSTF", "FCFS", "SCAN", "C-SCAN"], "B",
         "FCFS is the simplest scheduler, processing requests in arrival order with no reordering."),
        ("INTERMEDIATE", "Requests arrive for tracks 30, 70, 10, 50 and the head starts at 40. In which order does SSTF serve them?",
         ["10, 30, 50, 70", "30, 50, 10, 70", "30, 10, 70, 50", "50, 70, 30, 10"], "B",
         "From 40 the nearest is 30, then 50, then 10, then 70, so SSTF picks 30, 50, 10, 70."),
        ("INTERMEDIATE", "Requests at tracks 55, 20, 90 and the head starts at 50 moving upward. In what order does SCAN serve them?",
         ["20, 55, 90", "55, 20, 90", "55, 90, 20", "90, 55, 20"], "C",
         "SCAN keeps moving in one direction until it reaches the end, serving 55 then 90 on the way up, then reverses and serves 20."),
        ("INTERMEDIATE", "With C-SCAN the head starts at 50 moving upward toward track 200 and requests are 55, 20, 90. What is the service order?",
         ["20, 55, 90", "90, 55, 20", "55, 20, 90", "55, 90, 20"], "D",
         "C-SCAN sweeps to the outermost track, serving 55 then 90, then jumps back to the innermost track and serves 20."),
        ("INTERMEDIATE", "With LOOK, the head starts at 50 moving upward and requests are 20, 90, 55. What is the service order?",
         ["55, 90, 20", "20, 55, 90", "90, 55, 20", "55, 20, 90"], "A",
         "LOOK reverses at the last request in the direction rather than at the end of the disk, so it serves 55 and 90 upward, then 20."),
        ("INTERMEDIATE", "The head starts at track 30 and FCFS requests arrive as 50, 20, 70. What is the total head movement?",
         ["120", "100", "90", "70"], "B",
         "The head moves 30 to 50 (20), back to 20 (30), then to 70 (50), totaling 20 + 30 + 50 = 100."),
        ("INTERMEDIATE", "Which disk scheduling algorithm can cause starvation of requests that are far from the head?",
         ["FCFS", "C-SCAN", "SSTF", "LOOK"], "C",
         "SSTF always picks the nearest request, so distant requests may wait forever while closer ones keep arriving."),
        ("INTERMEDIATE", "A disk spins at 6000 RPM. What is the average rotational latency in milliseconds?",
         ["10 ms", "2 ms", "1 ms", "5 ms"], "D",
         "One full rotation takes 60 / 6000 = 10 ms, and average rotational latency is half a rotation, so 5 ms."),
        ("INTERMEDIATE", "Which of the following best describes SCAN (elevator) disk scheduling?",
         ["the head moves back and forth across the disk serving requests along the way", "requests are served in arrival order", "the head serves the nearest request first", "the head never changes direction"], "A",
         "SCAN sweeps the arm from one end of the disk to the other and back, servicing all requests encountered on each pass."),
        ("INTERMEDIATE", "With C-LOOK the head starts at 40 moving upward and requests are 30, 90, 60. What is the service order?",
         ["30, 60, 90", "60, 90, 30", "90, 60, 30", "30, 90, 60"], "B",
         "Moving upward it serves 60 then 90, then wraps directly to the lowest outstanding request 30, giving 60, 90, 30."),
        ("INTERMEDIATE", "The head is at track 10 and must serve tracks 20, 50, 100 with SCAN moving upward. What is the total seek distance?",
         ["120", "140", "90", "160"], "C",
         "Moving upward SCAN serves 20, 50 and 100, covering (20-10) + (50-20) + (100-50) = 10 + 30 + 50 = 90 tracks."),
        ("ADVANCED", "Which disk scheduling policy gives the most uniform waiting time to all pending requests?",
         ["SSTF", "FCFS", "C-SCAN", "none of these"], "C",
         "C-SCAN treats all cylinders equally on each sweep and resets after the high end, so wait times are far more uniform than SSTF or FCFS."),
        ("ADVANCED", "The head is at track 40 moving upward toward 200; requests are 60, 20, 180. What is the total movement for C-SCAN up to track 200 and back to track 0?",
         ["440", "300", "360", "380"], "D",
         "C-SCAN moves from 40 up to 200 (160), then jumps from 200 back to 0 (200), then serves 20 (20), for a total of 160 + 200 + 20 = 380."),
        ("ADVANCED", "Why do modern SSDs usually not need classical seek-optimizing schedulers like SCAN?",
         ["SSDs have no moving head and access any block in similar time", "SSDs are slower at seek", "SSD controllers never reorder", "SSDs store data on magnetic platters"], "A",
         "Without mechanical seek, access time is nearly uniform, so reordering for head movement is unnecessary; wear-leveling and write scheduling matter instead."),
        ("ADVANCED", "What is the purpose of Native Command Queuing (NCQ) in modern storage?",
         ["to prevent the drive from overheating", "to let the drive reorder and pipeline queued commands to improve performance", "to reduce disk capacity", "to encrypt all data"], "B",
         "NCQ allows the drive to reorder outstanding commands and pipeline transfers, maximizing utilization and reducing overall latency."),
        ("ADVANCED", "What does the Linux deadline I/O scheduler guarantee to each request?",
         ["the shortest possible seek", "zero latency", "a bounded service deadline, so no request is starved indefinitely", "a fixed queue depth"], "C",
         "Deadline keeps both read and write queues with expiration times, guaranteeing starvation-free service while still reordering for throughput."),
        ("ADVANCED", "What is the main idea of anticipatory scheduling?",
         ["the scheduler never waits", "the scheduler only serves writes", "the scheduler favors far cylinders", "the scheduler briefly pauses after a read in expectation of a nearby next request from the same process"], "D",
         "Anticipatory scheduling inserts a short idle wait after a read to catch the process's next nearby request, improving locality."),
        ("ADVANCED", "Which term is another name for the SCAN disk scheduling algorithm?",
         ["elevator algorithm", "round robin", "shortest job first", "priority queue"], "A",
         "SCAN behaves like an elevator moving up and down, so it is commonly called the elevator algorithm."),
        ("ADVANCED", "For a workload mixing a few urgent reads with many bulk writes, which scheduler property is most desirable?",
         ["always maximizing seek distance", "strict priority for reads to bound their latency", "never reordering requests", "serving all writes before reads"], "B",
         "Reads block the requesting process, so schedulers like deadline prioritize reads while still batching writes efficiently."),
        ("ADVANCED", "How does the flash translation layer (FTL) change how scheduling and addressing work on an SSD?",
         ["the FTL removes the need for a file system", "the FTL makes access times vary with cylinder", "the FTL maps logical blocks to physical pages internally, so the OS sees a normal block device", "the FTL ignores wear leveling"], "C",
         "The FTL hides flash's erase/write constraints by mapping logical addresses to physical pages and performing garbage collection."),
        ("ADVANCED", "In which workload is plain FCFS disk scheduling actually a reasonable choice?",
         ["a heavily loaded database", "a continuous video recorder writing at full speed", "a system with constant request queues", "a light, low-utilization system where seeking overhead is small and fairness matters"], "D",
         "When the disk is lightly loaded and queues rarely build, FCFS provides simple fairness without meaningful performance loss."),
    ],
    85: [
        ("BEGINNER", "What is an I/O device?",
         ["Hardware such as a keyboard, monitor or disk that exchanges data with the computer", "A type of CPU instruction", "A software library", "A memory cell"], "A",
         "An I/O device is hardware that transfers data between the computer and the outside world, such as input, output or storage peripherals."),
        ("BEGINNER", "What is an input/output port?",
         ["A dedicated address used by the CPU to communicate with a device", "A type of memory module", "A file on the hard disk", "A scheduling algorithm"], "A",
         "An I/O port is a special address the CPU uses to exchange data and control signals with a specific device."),
        ("BEGINNER", "What is polling in device communication?",
         ["the device sends an interrupt", "the CPU transfers data in a burst", "the CPU repeatedly checks a device status register until it signals readiness", "the device ignores the CPU"], "C",
         "Polling has the CPU actively check a device's status register in a loop until the device reports it is ready."),
        ("BEGINNER", "What is programmed I/O (PIO)?",
         ["the device transfers data alone", "the DMA controller copies memory", "the CPU sleeps during I/O", "the CPU transfers each piece of data to or from the device by executing instructions"], "D",
         "In PIO the CPU is fully responsible for moving every byte or word between memory and the device."),
        ("BEGINNER", "Which component transfers data between memory and devices without using the CPU for each byte?",
         ["the DMA controller", "the ALU", "the scheduler", "the file system"], "A",
         "The DMA controller moves data directly between a device and memory, interrupting the CPU only when done."),
        ("BEGINNER", "What is a device controller?",
         ["a software program for users", "hardware that manages the operation of a device and exchanges data with the CPU", "a type of memory", "a file system driver only"], "B",
         "A device controller is hardware between the CPU and the device that handles low-level operation and status."),
        ("BEGINNER", "What is an interrupt service routine (ISR)?",
         ["a device driver install script", "a type of system call", "the code the OS runs to handle a particular interrupt", "a DMA transfer"], "C",
         "An ISR is the handler function invoked by the OS when the matching interrupt is delivered."),
        ("BEGINNER", "What is a peripheral device?",
         ["A device such as a printer, keyboard or scanner that attaches to the computer", "The main CPU", "The power supply", "A software program"], "A",
         "A peripheral device is external hardware attached to the computer that provides input, output or auxiliary storage."),
        ("BEGINNER", "What is the main purpose of a buffer between a device and the CPU?",
         ["to hold data temporarily so the CPU and device can work at different speeds", "to make the device faster", "to increase memory size", "to compress data"], "A",
         "Buffers smooth the speed mismatch between fast CPUs and slower devices by staging data temporarily."),
        ("BEGINNER", "What is a bus in a computer system?",
         ["a type of disk", "a shared communication path that transfers data between components", "a memory cell", "a scheduling algorithm"], "B",
         "A bus is the shared electrical and protocol pathway used to move data between the CPU, memory and devices."),
        ("INTERMEDIATE", "Which technique is best for transferring large blocks of data such as a disk read, to keep the CPU free?",
         ["programmed I/O", "DMA", "polling", "interrupt-driven byte transfer"], "B",
         "DMA moves entire blocks with minimal CPU work, making it ideal for bulk transfers like disk reads."),
        ("INTERMEDIATE", "What does an interrupt vector contain?",
         ["the data being transferred", "the device status", "the address of the interrupt handler for a given interrupt number", "the DMA channel number"], "C",
         "An interrupt vector table maps each interrupt number to the address of its corresponding ISR."),
        ("INTERMEDIATE", "What is cycle stealing in the context of DMA?",
         ["the CPU steals data from the device", "the DMA controller crashes the system", "the device refuses transfers", "the DMA controller borrows bus cycles from the CPU one at a time to transfer data"], "D",
         "Cycle stealing lets DMA transfer a word using a bus cycle now and then, slightly slowing the CPU but avoiding large block transfers."),
        ("INTERMEDIATE", "What is interrupt latency?",
         ["The delay between an interrupt request and the CPU beginning to execute its handler", "The time a device spends transferring data", "The speed of the memory bus", "The number of devices on a system"], "A",
         "Interrupt latency measures the time from when an interrupt is raised until the CPU saves state and starts running the corresponding handler."),
        ("INTERMEDIATE", "What is spooling used for in a print system?",
         ["printing without a printer", "queuing output to a disk file so the printer and applications run at their own speeds", "compressing documents", "encrypting print jobs"], "B",
         "Spooling writes jobs to a queue on disk so the slow printer can drain the queue while applications continue."),
        ("INTERMEDIATE", "What does double buffering achieve?",
         ["two copies of all data", "slower processing", "one buffer fills while the other is processed, overlapping I/O and computation", "less memory usage"], "C",
         "With two buffers the producer fills one while the consumer processes the other, hiding transfer latency."),
        ("INTERMEDIATE", "Which I/O model returns control to the calling process immediately even though the operation is not finished?",
         ["blocking I/O", "synchronous I/O", "spooled I/O", "non-blocking I/O"], "D",
         "Non-blocking I/O lets a process issue the request and continue, checking later for completion."),
        ("INTERMEDIATE", "For reading a 4 MB file from disk into memory, which transfer method is most efficient?",
         ["DMA with a single interrupt at completion", "byte-by-byte programmed I/O", "continuous polling", "interrupt per byte"], "A",
         "DMA handles the whole block and interrupts once when done, whereas per-byte interrupt or PIO would consume enormous CPU time."),
        ("INTERMEDIATE", "What handshake must occur before a DMA controller can move data?",
         ["the CPU stops permanently", "the controller requests and is granted the bus, then transfers and signals completion", "the device writes a file", "the kernel is rebooted"], "B",
         "The DMA controller requests the bus, gains ownership, transfers the data, then interrupts the CPU when finished."),
        ("INTERMEDIATE", "For a device that produces data only rarely, which method wastes the least CPU time while waiting?",
         ["busy-wait polling", "continuous polling", "interrupt-driven I/O", "polling every nanosecond"], "C",
         "Interrupts let the CPU do useful work until the device signals, avoiding the waste of constant polling."),
        ("ADVANCED", "What cache coherency problem can DMA introduce?",
         ["DMA deletes cache lines", "DMA corrupts the cache tags", "the CPU's cache may hold stale data if DMA writes to memory behind its back", "cache makes DMA slower"], "C",
         "If the CPU caches a location that DMA updates in main memory, the cache can become stale unless it is invalidated."),
        ("ADVANCED", "What is scatter-gather DMA?",
         ["DMA that copies files", "DMA that uses no memory", "a single contiguous transfer", "a DMA transfer that reads or writes a list of non-contiguous memory regions with one request"], "D",
         "Scatter-gather DMA uses a descriptor list of addresses and lengths, letting one transfer span many scattered buffers."),
        ("ADVANCED", "What is the purpose of interrupt coalescing in high-speed networking?",
         ["it batches interrupts so the CPU is not overwhelmed by millions of interrupts per second", "it delays all interrupts forever", "it increases interrupt frequency", "it disables the NIC"], "A",
         "Under heavy load, coalescing groups many completed packets into a few interrupts, drastically cutting CPU overhead."),
        ("ADVANCED", "What does a zero-copy I/O path achieve?",
         ["no data is ever copied", "data is transferred between kernel buffers and the network without redundant copying through user space", "the CPU is bypassed entirely", "memory is compressed"], "B",
         "Zero-copy lets DMA move data directly between devices or kernel buffers, avoiding extra copies through user space."),
        ("ADVANCED", "Why does the kernel typically buffer small writes before sending them to a device?",
         ["buffers delete the data", "buffering compresses files", "batching small writes reduces per-request overhead and lets the device handle larger efficient transfers", "the kernel must delay all writes"], "C",
         "Aggregating small writes into larger ones cuts the fixed cost per I/O and improves device efficiency."),
        ("ADVANCED", "What is the benefit of mmap-based file I/O over explicit read and write calls?",
         ["it requires no memory", "it is always faster", "it cannot fail", "pages are paged in on demand and the kernel manages the transfer automatically"], "D",
         "With mmap, the virtual memory system fetches and writes pages lazily, removing explicit system calls and copies."),
        ("ADVANCED", "Why do NVMe SSDs outperform SATA SSDs by a wide margin?",
         ["NVMe uses PCIe with many high-speed queues and low latency, unlike SATA's older narrower bus", "NVMe has more mechanical parts", "SATA is encrypted", "NVMe is larger"], "A",
         "NVMe exploits PCIe lanes with thousands of deep queues and lower latency, far exceeding the single-queue SATA interface."),
        ("ADVANCED", "What does IRQ affinity (pinning an interrupt to a specific CPU) achieve in a multicore system?",
         ["it disables the interrupt", "it keeps the interrupt handler and the data it touches on the same CPU, improving cache locality and reducing contention", "it spreads the kernel across all CPUs", "it slows the device"], "B",
         "Pinning an IRQ to a CPU lets its handler reuse warm caches and avoids the cost of bouncing interrupts between cores."),
        ("ADVANCED", "What is the trade-off of using direct (unbuffered) I/O with the O_DIRECT flag?",
         ["it is always faster", "it encrypts data", "it bypasses the page cache, avoiding double buffering but losing the benefit of caching and read-ahead", "it disables DMA"], "C",
         "O_DIRECT transfers straight to user buffers, avoiding cache copies, but forfeits kernel caching and prefetching that help many workloads."),
        ("ADVANCED", "In which condition does polling beat interrupts for a device?",
         ["when events are very rare", "when the device is off", "when the CPU is idle", "when the device produces events at an extremely high rate and interrupt cost dominates"], "D",
         "If events arrive so frequently that interrupt handling itself overwhelms the CPU, polling the device at fixed intervals is more efficient."),
    ],
}
