# -*- coding: utf-8 -*-
"""
Question bank for subject 34: CLD104 - Cloud & Network Security.
Category: Cloud, Cybersecurity & DevOps.

Topics:
  166: Cloud Security
  167: Secure Communication
  168: Security Tools & Scanning
  169: Incident Response
  170: Data Protection & Privacy

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    166: [
        ("BEGINNER", "Which cloud service model provides customers with the most direct control over the underlying infrastructure?",
         ["Infrastructure as a Service (IaaS)", "Platform as a Service (PaaS)", "Software as a Service (SaaS)", "Function as a Service (FaaS)"], "A",
         "IaaS gives customers control over virtualized compute, storage and networking resources, while the provider manages only the physical infrastructure."),
        ("BEGINNER", "What does the shared responsibility model define?",
         ["how cloud service bills are calculated", "which security duties belong to the cloud provider and which belong to the customer", "how virtual machines are migrated between regions", "the uptime guarantee in a service level agreement"], "B",
         "The shared responsibility model clearly maps the security obligations of the provider against those that remain with the customer."),
        ("BEGINNER", "Under the shared responsibility model, which of the following is typically the cloud customer's responsibility?",
         ["physical security of the data center", "patching the underlying hypervisor", "managing access to its own data and identities", "maintaining the storage hardware"], "C",
         "Customers control and remain responsible for their own data, identities and access configuration, regardless of the service model."),
        ("BEGINNER", "What does the abbreviation CSP stand for in the context of cloud computing?",
         ["Cloud Security Protocol", "Centralized Service Platform", "Certified Security Practitioner", "Cloud Service Provider"], "D",
         "CSP is the standard abbreviation for Cloud Service Provider, the organization that delivers cloud services over the internet."),
        ("BEGINNER", "What is a multi-tenant cloud environment?",
         ["a single customer renting several cloud regions", "shared infrastructure securely isolated so that multiple customers use it simultaneously", "a cloud account with many administrator users", "a network with multiple virtual firewalls"], "A",
         "Multi-tenancy lets many customers share the same physical resources while keeping their workloads and data logically isolated."),
        ("BEGINNER", "Which term describes data that is stored and not currently moving across a network?",
         ["data in motion", "data at rest", "data in use", "data in transit"], "B",
         "Data at rest refers to data stored on disks, databases or backups, and it needs encryption and access controls to stay protected."),
        ("BEGINNER", "Which term describes data that is actively moving between systems over a network?",
         ["data at rest", "data on disk", "data in transit", "data archived"], "C",
         "Data in transit is information traveling across networks, which should be protected with protocols such as TLS."),
        ("BEGINNER", "What is a security group in a cloud virtual network?",
         ["a physical firewall appliance in the data center", "a group of users with shared permissions", "a backup schedule for virtual machines", "a virtual firewall that controls inbound and outbound traffic for resources"], "D",
         "A security group acts as a virtual firewall, allowing or denying traffic to and from cloud resources based on rules."),
        ("BEGINNER", "Which of the following is a common benefit of cloud computing?",
         ["on-demand scalability of resources", "guaranteed immunity to all attacks", "elimination of all security responsibilities", "permanent storage that can never fail"], "A",
         "Cloud platforms can scale resources up and down on demand, which is a core advantage over fixed on-premises capacity."),
        ("BEGINNER", "What is a virtual machine (VM) in the cloud?",
         ["a physical server purchased by the customer", "a software emulation of a computer running on shared physical hardware", "a type of container that shares the host kernel", "a managed database service"], "B",
         "A virtual machine is a software-emulated computer that runs its own operating system on top of virtualized physical hardware."),
        ("INTERMEDIATE", "A company uses a SaaS application and a user account is compromised. Under the shared responsibility model, who is primarily responsible for responding?",
         ["the SaaS provider, because it owns the software", "the hardware vendor", "the customer, because account and access management is its responsibility", "nobody, because SaaS is automatically secure"], "C",
         "With SaaS the provider secures the application platform, but the customer is responsible for its own accounts, credentials and user access."),
        ("INTERMEDIATE", "Under an IaaS deployment, which security task typically remains the responsibility of the cloud provider?",
         ["patching the guest operating system", "hardening the customer's application", "managing user passwords", "protecting the physical hosts and the hypervisor"], "D",
         "In IaaS the provider owns the physical data center and hypervisor layer, while the customer secures the guest OS and everything above it."),
        ("INTERMEDIATE", "A web server VM only needs to accept HTTPS traffic from the internet. Which change reduces its attack surface most directly?",
         ["restrict the security group to allow inbound port 443 only", "increase the number of CPUs", "enlarge the boot disk", "enable the admin console for the VM"], "A",
         "Restricting inbound rules to only port 443 removes all other exposed services, shrinking the VM's attack surface."),
        ("INTERMEDIATE", "What is the purpose of cloud identity and access management (IAM) policies?",
         ["to allocate more storage to users", "to define which users and roles can perform which actions on which resources", "to monitor billing for the account", "to encrypt data in transit"], "B",
         "IAM policies are JSON documents that grant or deny specific actions on specific cloud resources to identities."),
        ("INTERMEDIATE", "A developer asks for permissions to only the buckets she manages. Granting exactly those permissions demonstrates which principle?",
         ["defense in depth", "separation of duties", "least privilege", "non-repudiation"], "C",
         "Least privilege means granting only the minimum permissions required to perform a job, limiting the damage of a compromise."),
        ("INTERMEDIATE", "Which control is most effective at preventing unauthorized access when a cloud user's password has been stolen?",
         ["a longer username", "stronger password storage", "disabling the account", "multi-factor authentication (MFA)"], "D",
         "MFA requires a second factor in addition to the password, so a stolen password alone is no longer sufficient to sign in."),
        ("INTERMEDIATE", "What does a virtual private cloud (VPC) provide within a public cloud?",
         ["an isolated virtual network where resources are launched with private addressing", "a public web address for every server", "a managed antivirus service", "a dedicated physical server"], "A",
         "A VPC gives customers their own logically isolated section of the cloud network with full control over subnets and routing."),
        ("INTERMEDIATE", "An organization must encrypt objects stored in a cloud object storage bucket. Which term describes this requirement?",
         ["encryption in transit", "encryption at rest", "encryption of logs", "encryption of metadata"], "B",
         "Encrypting stored objects protects data at rest, ensuring that even stolen storage media cannot be read without the keys."),
        ("INTERMEDIATE", "A team deploys a virtual machine from a public image that still has the vendor's default password. What is the most serious consequence if not changed?",
         ["the VM runs slower", "the VM cannot connect to the network", "anyone who knows the default password may gain full access", "the VM automatically encrypts its own data"], "C",
         "Default credentials are publicly documented, so leaving them in place allows attackers to log in and compromise the instance."),
        ("INTERMEDIATE", "A security engineer needs to log every API call that changes cloud resources. Which service capability should be enabled?",
         ["load balancing", "auto scaling", "content delivery network", "cloud audit logging"], "D",
         "Cloud audit logging records every API action, providing the trail needed to detect and investigate unauthorized changes."),
        ("ADVANCED", "A large enterprise manages many cloud accounts. Which architecture best reduces risk around the administrative accounts?",
         ["a centralized management account with strong MFA, short-lived credentials and central logging", "one shared admin account used by every team", "giving every developer owner access", "storing admin passwords in a shared spreadsheet"], "A",
         "Centralizing privileged access in a dedicated account with MFA, short-lived credentials and logging limits exposure and improves auditability."),
        ("ADVANCED", "An incident reveals that a cloud storage bucket was configured as publicly readable and contained customer data. What is the first remediation?",
         ["delete the billing account", "block public access and remove the overly permissive bucket policy", "reboot the object storage service", "increase the bucket's storage class"], "B",
         "Immediately restricting public access and fixing the bucket policy stops the ongoing exposure of customer data."),
        ("ADVANCED", "What is the primary purpose of a cloud access security broker (CASB)?",
         ["to encrypt the physical hard drives in data centers", "to replace the cloud provider's firewalls", "to enforce security policies between users and cloud applications", "to back up virtual machines nightly"], "C",
         "A CASB sits between users and cloud services to enforce access, data and visibility policies across SaaS, PaaS and IaaS."),
        ("ADVANCED", "A company must allow staff to use the same identities across on-premises Active Directory and cloud services. Which approach best supports this securely?",
         ["recreate every account manually in the cloud", "share password hashes publicly", "email the on-premises password to each user", "use federated identity with single sign-on (SSO)"], "D",
         "Federation with SSO lets the on-premises directory authenticate users and issue trusted tokens for cloud services."),
        ("ADVANCED", "A business stores customer PII in a cloud database. Which combination provides defense in depth for data at rest?",
         ["encryption with managed keys, strict access policies and monitoring of data access", "storing data in plaintext for speed", "removing all database backups", "granting every employee database access"], "A",
         "Layering encryption, access control and monitoring protects stored data even if one control fails."),
        ("ADVANCED", "An application is vulnerable to a server-side request forgery (SSRF). In a public cloud, what is the most dangerous capability this gives an attacker?",
         ["reading the hypervisor firmware", "retrieving temporary credentials from the instance metadata service", "changing the machine's IP address", "deleting the security group"], "B",
         "SSRF can make the server query the instance metadata endpoint, which may leak temporary IAM credentials that grant broader cloud access."),
        ("ADVANCED", "Which practice is the strongest alternative to embedding long-lived static access keys in cloud applications?",
         ["hardcoding the keys in source code", "putting the keys in environment variables only", "using short-lived tokens or IAM roles assumed by the application", "sharing one key among all teams"], "C",
         "IAM roles and short-lived tokens expire and auto-rotate, so leaked credentials are far less valuable than static keys."),
        ("ADVANCED", "Cloud audit logs show a new administrator account was created from an unknown external IP during the night. What is the first step?",
         ["ignore it because admins work late", "notify the whole company", "restart the management console", "disable the suspicious account and investigate the full audit trail"], "D",
         "Disabling the unauthorized account immediately stops further abuse while the audit trail is used to determine how it was created."),
        ("ADVANCED", "In many cloud platforms, security groups are described as stateful. What does that mean?",
         ["return traffic for an allowed connection is automatically permitted", "rules must be configured separately for replies", "security groups automatically encrypt traffic", "security groups only inspect outbound traffic"], "A",
         "A stateful security group automatically allows the reply traffic for an outbound or inbound connection that was already permitted."),
        ("ADVANCED", "What is the primary risk of assigning an IAM role a wildcard policy that grants * on all resources?",
         ["the role becomes read-only", "any compromise of that role gives the attacker unrestricted control", "the role can no longer be used by services", "wildcards are always safer than specific grants"], "B",
         "A wildcard grant means a single compromised identity can perform any action on any resource, maximizing blast radius."),
    ],
    167: [
        ("BEGINNER", "What is the primary purpose of TLS (Transport Layer Security) for web traffic?",
         ["to provide confidentiality and integrity of data in transit", "to speed up web page loading", "to block all pop-up advertisements", "to compress images for download"], "A",
         "TLS encrypts the connection and detects tampering, protecting the confidentiality and integrity of data as it travels."),
        ("BEGINNER", "What does HTTPS add to normal HTTP?",
         ["a faster compression algorithm", "a TLS-encrypted layer for secure communication", "a second domain name", "automatic page translation"], "B",
         "HTTPS is HTTP layered over TLS, so all requests and responses are encrypted between client and server."),
        ("BEGINNER", "What is the role of a digital certificate in a TLS connection?",
         ["to store the user's browsing history", "to increase the server's processing speed", "to verify the server's identity and carry its public key", "to translate web pages into other languages"], "C",
         "A digital certificate binds a public key to an identity, letting the client verify who it is really talking to."),
        ("BEGINNER", "What does a certificate authority (CA) do?",
         ["hosts web servers for small businesses", "blocks malicious websites for all browsers", "encrypts the public internet backbone", "issues and digitally signs certificates that vouch for identity"], "D",
         "A CA signs certificates so clients can trust the identity claims they contain through the chain of trust."),
        ("BEGINNER", "Which protocol is the standard method for secure remote command-line access to a server?",
         ["SSH", "FTP", "Telnet", "SMTP"], "A",
         "SSH encrypts the session and authenticates both ends, making it the standard for secure remote administration."),
        ("BEGINNER", "What is a virtual private network (VPN)?",
         ["a public Wi-Fi hotspot", "an encrypted tunnel that carries traffic securely over a public network", "a firewall that blocks all traffic", "a backup of a private network"], "B",
         "A VPN encrypts and tunnels traffic between endpoints across an untrusted network such as the internet."),
        ("BEGINNER", "What is encryption?",
         ["deleting data to save space", "compressing data for storage", "transforming readable plaintext into unreadable ciphertext", "making data available to everyone"], "C",
         "Encryption converts plaintext into ciphertext using an algorithm and key so only authorized parties can recover it."),
        ("BEGINNER", "In symmetric-key cryptography, how many keys are needed?",
         ["one private key for each user and one public key", "a key pair per user", "at least three keys", "a single shared key used for both encryption and decryption"], "D",
         "Symmetric encryption uses one shared key for both encrypting and decrypting, so all parties must keep it secret."),
        ("BEGINNER", "What is the defining feature of asymmetric (public-key) cryptography?",
         ["a key pair in which the public key encrypts and the private key decrypts", "using the same key for every operation", "no keys are required", "keys that never expire"], "A",
         "Asymmetric cryptography uses a mathematically linked public and private key pair for encryption and digital signatures."),
        ("BEGINNER", "What is a cryptographic hash primarily used for?",
         ["encrypting large files", "detecting changes to data through a fixed-length digest", "compressing video streams", "authenticating users with passwords only"], "B",
         "A hash produces a fixed-size digest, and any change in the input changes the digest, enabling integrity checks."),
        ("INTERMEDIATE", "During a TLS handshake, which item does the server send first to prove its identity?",
         ["the session encryption key", "the user's password", "its digital certificate", "its IP address"], "C",
         "The server presents its certificate so the client can verify its identity and obtain the public key for key exchange."),
        ("INTERMEDIATE", "Why does perfect forward secrecy improve the security of a TLS session?",
         ["it makes the handshake faster", "it removes the need for certificates", "it lets the server see all plaintext", "ephemeral session keys mean past sessions stay secret even if the long-term key leaks"], "D",
         "Perfect forward secrecy derives each session key with ephemeral parameters, so leaking a long-term key does not decrypt past traffic."),
        ("INTERMEDIATE", "A user visits a site whose certificate has expired. What is the main risk?",
         ["the client cannot reliably verify the server's identity, enabling possible impersonation", "the site will load faster", "the site's content becomes unreadable to everyone", "the connection becomes unencrypted but still verified"], "A",
         "An expired certificate fails validation, so the client cannot confirm who operates the site, raising man-in-the-middle risk."),
        ("INTERMEDIATE", "Which method is the most appropriate for securely copying files between two servers?",
         ["plain FTP", "SFTP or SCP over SSH", "emailing the files", "sharing a public file server"], "B",
         "SFTP and SCP run over SSH, encrypting both the data and authentication during transfer."),
        ("INTERMEDIATE", "An attacker captures and modifies an email while it travels between mail servers. Which security property of the message has been violated?",
         ["confidentiality", "availability", "integrity", "non-repudiation"], "C",
         "Integrity is violated because the content was altered in transit without detection by the recipient."),
        ("INTERMEDIATE", "Which mechanism can protect email in transit between two mail servers?",
         ["HTTPS on the web", "DNSSEC", "IPSec site-to-site tunnels", "STARTTLS to upgrade the SMTP connection to TLS"], "D",
         "STARTTLS upgrades an SMTP connection to an encrypted TLS channel between mail servers."),
        ("INTERMEDIATE", "What does DNSSEC provide for DNS traffic?",
         ["authenticity and integrity of DNS responses", "encryption of all web traffic", "faster DNS resolution", "blocking all malicious domains"], "A",
         "DNSSEC signs DNS records so resolvers can verify they were not tampered with in transit."),
        ("INTERMEDIATE", "A user connects to an open Wi-Fi hotspot where an attacker can capture traffic. What protects the user's web traffic?",
         ["HTTP links", "TLS-encrypted HTTPS connections", "the browser's cache", "the hotspot's login page"], "B",
         "HTTPS/TLS encrypts the traffic, so an eavesdropper on the network cannot read the content."),
        ("INTERMEDIATE", "After the TLS handshake, what is the shared session key used for?",
         ["for the certificate validation only", "to compress the web page", "to encrypt the application data symmetrically and efficiently", "to sign the server's certificate"], "C",
         "Once both sides agree on a session key, it is used with symmetric ciphers for fast bulk data encryption."),
        ("INTERMEDIATE", "Which cipher family is commonly used for bulk data encryption in modern TLS, such as TLS 1.3?",
         ["DES", "RC4", "SHA-256", "AES-GCM"], "D",
         "AES-GCM is an authenticated encryption cipher widely used in modern TLS deployments, including TLS 1.3."),
        ("ADVANCED", "A security engineer must ensure a web server only negotiates strong TLS. Which configuration change achieves this best?",
         ["disable legacy protocols and weak ciphers and require TLS 1.2 or 1.3", "allow all ciphers for compatibility", "turn off certificate validation", "use HTTP for all internal pages"], "A",
         "Disabling old protocols and weak ciphers forces clients to use modern, secure TLS versions and algorithms."),
        ("ADVANCED", "An attacker presents a self-signed certificate to intercept a session. Which client-side control most directly defeats the attack?",
         ["disabling the browser's certificate checks", "proper certificate validation against a trusted certificate store", "adding the site to the browser's cache", "using a shared password for the site"], "B",
         "Validating the certificate against trusted roots rejects the self-signed certificate and blocks the impersonation."),
        ("ADVANCED", "Why is TLS 1.0 now widely considered unsafe?",
         ["it encrypts traffic too strongly", "it requires hardware tokens", "it relies on weak ciphers and known weaknesses such as BEAST and weak CBC modes", "it does not use certificates at all"], "C",
         "TLS 1.0 supports outdated ciphers and has documented cryptographic weaknesses, so modern standards require TLS 1.2 or newer."),
        ("ADVANCED", "What is a man-in-the-middle (MITM) attack against TLS primarily mitigated by?",
         ["stronger passwords", "larger file uploads", "faster internet connections", "verifying the server's identity through trusted certificates"], "D",
         "Certificate validation lets the client confirm the server's identity, making it impossible for the interceptor to pose as the server."),
        ("ADVANCED", "A team must transfer a very large database backup securely between two data centers while verifying the file is unchanged. Which approach best meets both goals?",
         ["SFTP/SCP transfer followed by comparing SHA-256 hashes", "plain HTTP download", "FTP with no encryption", "sending the file by email"], "A",
         "SSH-based transfer provides encryption, and comparing cryptographic hashes verifies integrity of the transferred file."),
        ("ADVANCED", "Two branch offices must communicate securely across the public internet. Which solution is most appropriate?",
         ["public DNS", "a site-to-site VPN between the offices' gateways", "a shared email account", "open telnet sessions"], "B",
         "A site-to-site VPN encrypts all traffic flowing between the two office networks over the untrusted internet."),
        ("ADVANCED", "What is the purpose of the Online Certificate Status Protocol (OCSP)?",
         ["to encrypt the certificate", "to generate new certificates", "to check in real time whether a certificate has been revoked", "to assign IP addresses"], "C",
         "OCSP lets clients query a responder to confirm a certificate is still valid and has not been revoked."),
        ("ADVANCED", "Why is the HTTP Strict Transport Security (HSTS) header recommended for secure websites?",
         ["it speeds up page rendering", "it adds extra storage", "it logs all user activity", "it forces browsers to use HTTPS and prevents protocol downgrade attacks"], "D",
         "HSTS instructs browsers to only ever use HTTPS for a domain, blocking downgrades to insecure HTTP."),
        ("ADVANCED", "The private key of a widely trusted certificate authority is compromised. What is the most serious consequence?",
         ["attackers can issue fraudulent certificates that clients will trust", "all web traffic becomes unreadable", "browsers permanently lose all connectivity", "the CA can no longer be hacked again"], "A",
         "With the CA's private key, an attacker can mint valid certificates for any domain, breaking the chain of trust."),
        ("ADVANCED", "What is the main benefit of TLS session resumption?",
         ["it weakens encryption for speed", "it skips part of the handshake so repeated connections are faster while remaining secure", "it lets servers see plaintext traffic", "it removes the need for certificates"], "B",
         "Session resumption reuses agreed session parameters, reducing handshake latency for repeat connections without weakening security."),
    ],
    168: [
        ("BEGINNER", "What is the primary function of the Nmap tool?",
         ["network discovery and port scanning", "compiling C programs", "managing database backups", "rendering web pages"], "A",
         "Nmap scans networks to discover hosts and open ports, revealing what services are exposed."),
        ("BEGINNER", "Which type of tool is designed to discover open ports and running services on a host?",
         ["a packet analyzer", "a port scanner", "a source code editor", "a load balancer"], "B",
         "A port scanner probes a target's ports to identify which services are listening and reachable."),
        ("BEGINNER", "Which tool is commonly used to intercept and modify web application traffic during testing?",
         ["Wireshark", "Nmap", "Burp Suite", "Ping"], "C",
         "Burp Suite acts as an intercepting proxy, letting testers view and modify HTTP requests and responses."),
        ("BEGINNER", "What does a vulnerability scanner do?",
         ["encrypts the hard drive", "automatically detects known vulnerabilities and misconfigurations in systems", "blocks all incoming email", "speeds up the network"], "D",
         "A vulnerability scanner checks systems against a database of known weaknesses and reports the findings."),
        ("BEGINNER", "What is Wireshark primarily used for?",
         ["capturing and analyzing network packets", "performing SQL queries", "backing up files to the cloud", "testing CPU speed"], "A",
         "Wireshark captures packets on a network interface and lets analysts inspect their contents."),
        ("BEGINNER", "Why do attackers and defenders perform port scans?",
         ["to increase network bandwidth", "to identify which network services are open and potentially exposed", "to fix hardware failures", "to compress log files"], "B",
         "Port scans reveal listening services, which are the entry points that may be probed for weaknesses."),
        ("BEGINNER", "Which tool is commonly used to audit password strength by attempting to crack password hashes?",
         ["John the Ripper", "Nmap", "Wireshark", "Netstat"], "C",
         "John the Ripper tests password hashes against wordlists and attack modes to reveal weak passwords."),
        ("BEGINNER", "What does a Security Information and Event Management (SIEM) system do?",
         ["detects physical intruders", "manages virtual machines", "performs port scans", "collects and correlates logs and events from many sources"], "D",
         "A SIEM aggregates security logs and events so analysts can detect patterns and respond to threats."),
        ("BEGINNER", "Which Linux command-line tool is most commonly used to scan for open ports?",
         ["nmap", "grep", "ls", "mkdir"], "A",
         "nmap is the standard command-line port scanner available on Linux and other platforms."),
        ("BEGINNER", "What does an intrusion detection system (IDS) do?",
         ["encrypts all traffic", "monitors network or system activity for suspicious behavior and alerts", "rebuilds operating systems", "allocates disk space"], "B",
         "An IDS inspects activity for signs of attack and raises alerts when suspicious behavior is detected."),
        ("INTERMEDIATE", "A scan reports that port 22 is open on a server. Which service most likely runs on it?",
         ["HTTP", "DNS", "SSH", "SMTP"], "C",
         "Port 22 is the well-known port for SSH, used for secure remote administration."),
        ("INTERMEDIATE", "A web application test indicates a possible SQL injection. Which tool is designed to confirm and automate exploitation of such flaws in a controlled lab?",
         ["John the Ripper", "Wireshark", "Nessus", "sqlmap"], "D",
         "sqlmap automates detection and exploitation of SQL injection vulnerabilities against database-backed applications."),
        ("INTERMEDIATE", "Which Nmap scan is used to discover which hosts on a subnet are up?",
         ["a ping sweep such as nmap -sP", "a full database scan", "an SSL cipher check", "a source code review"], "A",
         "A ping sweep probes hosts for responses, quickly identifying which addresses are alive on the network."),
        ("INTERMEDIATE", "Which framework provides a standard severity score for vulnerabilities found during scanning?",
         ["TCP/IP", "CVSS", "OWASP Top 10", "Wireshark"], "B",
         "The Common Vulnerability Scoring System (CVSS) assigns numerical scores that rank vulnerability severity."),
        ("INTERMEDIATE", "An analyst captured traffic and wants to view only HTTP requests. Which Wireshark display filter achieves this?",
         ["tcp.port == 443", "dns", "http", "ip.addr == 192.168.1.1"], "C",
         "The display filter http shows only packets belonging to HTTP application traffic."),
        ("INTERMEDIATE", "Which tool is commonly used to test SSH logins by trying many username and password combinations?",
         ["Wireshark", "Hydra", "Nmap", "OpenSSL"], "D",
         "Hydra is a network login cracker that can brute-force credentials for protocols such as SSH."),
        ("INTERMEDIATE", "A SIEM raises an alert because a host logged many failed password attempts in a few minutes. What is this pattern called?",
         ["a brute-force attack", "a denial of service", "a phishing campaign", "an SQL injection"], "A",
         "Rapid repeated login failures are the classic signature of a brute-force attack guessing credentials."),
        ("INTERMEDIATE", "Which scan sends a SYN packet and only completes the handshake if the port is open?",
         ["a full TCP connect scan", "a SYN or half-open scan", "an XMAS scan of UDP", "a ping sweep"], "B",
         "A SYN scan sends SYN and watches for SYN-ACK, never finishing the handshake, which is stealthier and faster."),
        ("INTERMEDIATE", "What is the key difference between an IDS and an IPS?",
         ["they are identical in function", "an IDS can block traffic", "an IDS detects and alerts while an IPS can actively block malicious traffic", "an IPS only records traffic"], "C",
         "An IDS is passive and alerts, while an IPS sits inline and can block or drop malicious packets in real time."),
        ("INTERMEDIATE", "Which category of tool analyzes source code for security flaws without running the program?",
         ["dynamic application security testing (DAST)", "fuzzing", "port scanning", "static application security testing (SAST)"], "D",
         "SAST tools parse source code and look for patterns that indicate vulnerabilities before the application runs."),
        ("ADVANCED", "An enterprise must continuously identify unpatched vulnerabilities across 5000 endpoints. Which approach is most scalable and reliable?",
         ["deploy agent-based vulnerability scanning with centralized reporting", "ask each employee to run manual scans monthly", "scan the endpoints only once a year", "rely on antivirus signatures alone"], "A",
         "Agent-based scanners report continuously to a central console, giving complete, up-to-date coverage across thousands of endpoints."),
        ("ADVANCED", "A scanner flags a service whose version has no known CVE. What is the best next step?",
         ["ignore the finding permanently", "verify the version and configuration manually and monitor for future advisories", "uninstall the service immediately", "decrease scan frequency to once a year"], "B",
         "Without a CVE, the finding needs manual verification and ongoing monitoring because new vulnerabilities may be disclosed later."),
        ("ADVANCED", "A vulnerability scanner produces many false positives. How should the team respond?",
         ["delete the scanner", "triple the scan frequency", "triage each alert, verify findings manually and tune the scanner's rules", "block all traffic from the scanner"], "C",
         "Triaging and verifying alerts reduces false positives, and tuning scanner configuration improves future accuracy."),
        ("ADVANCED", "Which scanning technique can help evade a network firewall that filters complete packets?",
         ["scanning during business hours only", "using only TCP connect scans", "scanning a single port", "sending fragmented packets that the firewall fails to inspect completely"], "D",
         "Fragmentation splits packets into pieces that some firewalls cannot reassemble and inspect, helping the scan slip through."),
        ("ADVANCED", "A tester wants to verify an insecure direct object reference (IDOR) in a web application. Which approach is most effective?",
         ["manual testing with two accounts and a proxy such as Burp Suite", "running a port scan", "checking TLS certificates", "measuring network latency"], "A",
         "IDOR testing compares responses across two accounts while manipulating object identifiers, which a proxy makes easy."),
        ("ADVANCED", "What is the primary purpose of a honeypot?",
         ["to speed up production traffic", "to deceive attackers and collect intelligence about their methods", "to replace the company firewall", "to store backups"], "B",
         "A honeypot is a decoy system designed to attract attackers so defenders can observe their techniques."),
        ("ADVANCED", "Which type of tool continuously checks cloud configurations for risky misconfigurations such as publicly open buckets?",
         ["a CASB only", "a web application firewall", "a cloud security posture management (CSPM) tool", "a network load balancer"], "C",
         "CSPM tools assess cloud accounts against best-practice benchmarks and flag misconfigurations and compliance drift."),
        ("ADVANCED", "How does DAST differ from SAST in application security testing?",
         ["DAST analyzes source code, SAST tests the running app", "they are the same", "DAST is only for mobile apps", "DAST tests the running application over its interfaces while SAST analyzes source code"], "D",
         "DAST exercises a deployed application like an attacker would, whereas SAST reviews code statically without execution."),
        ("ADVANCED", "Which framework is commonly used by red teams to develop, test and deliver exploits against targets?",
         ["Metasploit", "Wireshark", "OpenVPN", "Tripwire"], "A",
         "Metasploit provides modules and payloads that red teams use to simulate realistic attacks during authorized testing."),
        ("ADVANCED", "A team's scans overload the network during business hours. Which mitigation balances coverage and stability?",
         ["stop scanning entirely", "schedule scans during maintenance windows and throttle scan rate", "scan only one endpoint", "run scans every hour at full speed"], "B",
         "Scheduling scans in off-peak windows and throttling the rate reduces impact while still providing coverage."),
    ],
    169: [
        ("BEGINNER", "What is a security incident?",
         ["a security event that harms or threatens the confidentiality, integrity or availability of an asset", "any routine system update", "a scheduled maintenance task", "a normal user login"], "A",
         "A security incident is an event with negative impact, such as an intrusion or breach, that requires a response."),
        ("BEGINNER", "Which phase comes first in the incident response lifecycle?",
         ["eradication", "recovery", "preparation", "containment"], "B",
         "Preparation comes first: policies, tools and trained teams are readied before any incident occurs."),
        ("BEGINNER", "What does containment mean during incident response?",
         ["deleting all logs", "preventing the incident from spreading further", "shutting down the business", "hiding the incident from management"], "C",
         "Containment limits the scope and damage of an incident by isolating affected systems and stopping the spread."),
        ("BEGINNER", "What does eradication involve?",
         ["restoring backups", "removing the threat and its root cause from the environment", "notifying the press", "archiving logs"], "D",
         "Eradication removes malware, backdoors and the root cause so the environment is clean."),
        ("BEGINNER", "What is the goal of the recovery phase?",
         ["returning systems to normal, verified operation", "finding who caused the incident", "deleting evidence", "rewriting the security policy"], "A",
         "Recovery restores affected services and verifies they operate normally and safely before going back into production."),
        ("BEGINNER", "What is a security event?",
         ["an incident that always causes damage", "any observable occurrence that is relevant to the security of a system", "a scheduled backup", "a hardware purchase"], "B",
         "A security event is any observable occurrence that might relate to security, which may or may not become an incident."),
        ("BEGINNER", "What is the purpose of an incident response plan?",
         ["to increase network speed", "to document employee salaries", "to define roles, procedures and communication for handling incidents", "to replace the firewall"], "C",
         "An IR plan lays out who does what, the steps to follow and how to communicate during an incident."),
        ("BEGINNER", "What is an incident response playbook?",
         ["a list of employee holidays", "a hardware inventory", "a marketing strategy", "a predefined procedure for handling a specific type of incident"], "D",
         "Playbooks give responders repeatable step-by-step procedures tailored to incident types such as phishing or ransomware."),
        ("BEGINNER", "During an incident, who should typically be notified first?",
         ["the designated incident response team or on-call contact", "every employee at once", "the company's social media followers", "external attackers"], "A",
         "The IR team must be engaged first so a trained group can triage and coordinate the response."),
        ("BEGINNER", "Why is preserving evidence important during an incident?",
         ["to make the systems faster", "to keep evidence intact for analysis and any legal proceedings", "to hide the incident", "to reduce storage costs"], "B",
         "Preserving evidence in a defensible way ensures analysis is accurate and evidence may be admissible in court."),
        ("INTERMEDIATE", "An alert shows malware running on a production server. What is the first action the responder should take?",
         ["format the entire server immediately", "announce the breach publicly", "isolate the host to contain the spread", "delete the company firewall logs"], "C",
         "Isolating the infected host stops the malware from moving to other systems while evidence is preserved."),
        ("INTERMEDIATE", "Why must an incident responder maintain a documented chain of custody?",
         ["to improve network speed", "to track who pays for tools", "to shorten the investigation", "to prove that evidence was not altered or mishandled"], "D",
         "A documented chain of custody shows who handled evidence and that it remained unchanged, which is essential if it is used in court."),
        ("INTERMEDIATE", "For a compromised Linux server, which evidence is most valuable for understanding the attack while it may still be running?",
         ["a memory image and system logs", "only the marketing files", "the screen resolution settings", "a list of installed fonts"], "A",
         "A memory image captures running processes and connections, and logs record system activity, together revealing attacker behavior."),
        ("INTERMEDIATE", "Ransomware begins encrypting files on several shared drives. Which immediate action best limits the damage?",
         ["pay the ransom immediately", "disconnect affected systems and shares from the network", "continue working to watch what happens", "email every employee asking them to click attachments"], "B",
         "Disconnecting the affected systems stops the encryption from spreading to additional files and shares."),
        ("INTERMEDIATE", "What is the key difference between a security event and a security incident?",
         ["an event never involves security", "an incident is always caused by an insider", "an incident is an event with a negative impact that requires a response", "they are identical terms"], "C",
         "Every incident is an event, but an incident specifically has adverse security impact requiring a formal response."),
        ("INTERMEDIATE", "A phishing email leads to a user's credentials being stolen. What is the most direct containment step?",
         ["buy a new laptop", "change nothing and wait", "train only new employees", "reset the credentials and revoke active sessions"], "D",
         "Resetting the password and terminating active sessions invalidates the stolen credentials immediately."),
        ("INTERMEDIATE", "What is the purpose of a lessons learned review after an incident?",
         ["to identify improvements to processes and prevent recurrence", "to assign blame publicly", "to delete incident data", "to increase system load"], "A",
         "Lessons learned capture what worked and what failed so future detection and response improve."),
        ("INTERMEDIATE", "Which metric measures how long it takes to restore service after an incident begins?",
         ["MTTD", "MTTR", "CPU usage", "Uptime of the firewall"], "B",
         "Mean Time To Recover (MTTR) tracks the duration from incident start to restored service."),
        ("INTERMEDIATE", "When should an organization notify affected customers about a breach?",
         ["never, to avoid attention", "after deleting all evidence", "according to its incident plan and legal or regulatory obligations after assessing the impact", "only if a reporter asks"], "C",
         "Notification timing follows the organization's plan and applicable laws, which often require prompt, accurate disclosure."),
        ("INTERMEDIATE", "Which artifact most directly reveals when a file was created, modified or accessed on a compromised workstation?",
         ["the printer queue", "file system timestamps", "the wallpaper image", "the keyboard language"], "D",
         "File system timestamps record creation, modification and access times, which help reconstruct attacker activity."),
        ("ADVANCED", "An organization fears an advanced persistent threat (APT) and wants to improve its response capability. Which preparation is most effective?",
         ["develop detection playbooks, consume threat intelligence and run a trained, rehearsed IR team", "buy more monitors for the SOC", "increase the number of coffee machines", "keep a single expert on call 24/7 with no plan"], "A",
         "Playbooks, threat intel and rehearsed teams let responders detect and react to APT activity quickly and consistently."),
        ("ADVANCED", "A cloud instance has been compromised to mine cryptocurrency. What is the most appropriate response?",
         ["keep the instance running to watch it", "make a forensic snapshot, terminate the instance and rotate any credentials it used", "simply reboot the instance", "leave the mining process running"], "B",
         "Preserving a snapshot for forensics, terminating the infected instance and rotating credentials removes the compromise and secures the account."),
        ("ADVANCED", "An attacker is actively operating inside a network during incident response. Why might the team deliberately avoid immediately killing the attacker's process?",
         ["to reduce electric bills", "to keep the network slow", "to observe the attacker's techniques and gather intelligence before eviction", "because process names cannot be stopped"], "C",
         "Observing the attacker's tools and movements reveals their TTPs, improving detection and preventing recurrence after eviction."),
        ("ADVANCED", "A worm is spreading laterally between network segments. Which containment priority is correct?",
         ["eradicate first, then isolate", "isolate infected segments first to stop the spread, then eradicate the worm", "leave all segments connected", "disable all monitoring"], "D",
         "Stopping the spread through network isolation comes first, because eradication is far harder while the worm keeps infecting."),
        ("ADVANCED", "An insider is suspected of stealing customer data. Which evidence is most probative for confirming the exfiltration?",
         ["access logs showing downloads of large volumes of sensitive files", "the employee's meeting schedules", "the color of the employee's badge", "the number of years of employment"], "A",
         "Access logs that link the insider's account to bulk downloads of sensitive files directly demonstrate the exfiltration."),
        ("ADVANCED", "A legitimate user account is used in a phishing campaign to send malicious internal emails. How should the team detect and contain this?",
         ["ask employees to forward the emails to everyone", "disable the account, inspect mailbox rules and look for auto-forwarding or abuse", "delete all mailboxes", "do nothing because the sender is legitimate"], "B",
         "Disabling the account and checking for forwarding rules stops the abuse and reveals how the attacker controls the mailbox."),
        ("ADVANCED", "In cloud incident response, why are immutable snapshots particularly valuable?",
         ["they cost nothing", "they speed up the network", "they preserve evidence in a state that cannot be altered", "they replace the need for logs"], "C",
         "Immutable snapshots cannot be modified, so they provide trustworthy evidence that attackers cannot tamper with."),
        ("ADVANCED", "Before an organization can declare recovery complete after containing a breach, which step must happen?",
         ["delete the forensic images", "rehire the IR team", "turn off all monitoring", "verify eradication, restore from clean backups and monitor for signs of reinfection"], "D",
         "Recovery is complete only after the threat is confirmed gone, systems are restored cleanly and monitoring confirms no reinfection."),
        ("ADVANCED", "How does the MITRE ATT&CK framework assist incident responders?",
         ["it maps observed attacker actions to known tactics, techniques and procedures", "it encrypts all logs", "it assigns IP addresses", "it predicts the stock market"], "A",
         "ATT&CK catalogs adversary behavior so responders can classify activity, detect patterns and plan responses by technique."),
        ("ADVANCED", "Logs show an attacker reached a database using an application account with far more privileges than needed. What is the most likely root cause?",
         ["the database was too fast", "over-privileged application credentials were exposed and used", "the network had too much bandwidth", "the database had no indices"], "B",
         "An over-privileged app account means a single credential compromise yields excessive access, which is the root cause to fix."),
    ],
    170: [
        ("BEGINNER", "What does the abbreviation PII stand for?",
         ["Personally Identifiable Information", "Private Internet Infrastructure", "Public Identity Index", "Personal Identity Image"], "A",
         "PII is information that can identify an individual, such as a name, email address or national ID number."),
        ("BEGINNER", "What does encrypting data at rest primarily protect against?",
         ["slow internet speeds", "unauthorized access to stored data such as disks or backups", "losing the encryption key", "users forgetting passwords"], "B",
         "Encryption at rest ensures that even if storage media are stolen, the data cannot be read without the key."),
        ("BEGINNER", "What is a data breach?",
         ["a scheduled backup", "a routine software update", "unauthorized access, disclosure or theft of data", "a normal database query"], "C",
         "A data breach occurs when protected data is accessed or exposed without authorization."),
        ("BEGINNER", "Which regulation is the main law governing personal data protection in the European Union?",
         ["SOX", "HIPAA", "PCI DSS", "GDPR"], "D",
         "The General Data Protection Regulation (GDPR) governs how personal data of EU individuals is processed."),
        ("BEGINNER", "What is data classification?",
         ["assigning sensitivity labels such as public, internal or confidential to data", "compressing data to save space", "deleting old data automatically", "transferring data between servers"], "A",
         "Data classification groups data by sensitivity and criticality, guiding how it should be protected."),
        ("BEGINNER", "What is data masking?",
         ["deleting production data", "replacing sensitive data with realistic but fictitious substitutes", "encrypting data with a public key", "storing data on tape"], "B",
         "Data masking hides the original values by substituting fake values, allowing safe use in non-production environments."),
        ("BEGINNER", "What is tokenization in data protection?",
         ["breaking data into small packets", "encrypting data twice", "replacing sensitive values with non-sensitive placeholders called tokens", "storing data in the cloud"], "C",
         "Tokenization swaps sensitive data for tokens; the original values are stored separately and securely."),
        ("BEGINNER", "What is the role of a key management service (KMS)?",
         ["managing user passwords", "monitoring network traffic", "backing up virtual machines", "centrally creating, storing and rotating encryption keys"], "D",
         "A KMS centralizes the lifecycle of encryption keys, including creation, storage, rotation and revocation."),
        ("BEGINNER", "What does the principle of data minimization require?",
         ["collecting only the data that is necessary for a stated purpose", "collecting as much data as possible", "deleting all data immediately", "sharing data with all partners"], "A",
         "Data minimization means an organization collects and keeps only what it genuinely needs, reducing risk."),
        ("BEGINNER", "What is a privacy policy?",
         ["a firewall rule", "a document that explains how an organization collects, uses and protects personal data", "an encryption algorithm", "a backup schedule"], "B",
         "A privacy policy informs individuals about data collection, usage, storage and their rights."),
        ("INTERMEDIATE", "Under GDPR, what must an organization establish before processing personal data?",
         ["a marketing budget", "a data center", "a lawful basis such as consent or legitimate interest", "permission from competitors"], "C",
         "GDPR requires every processing activity to rely on a lawful basis, such as consent, contract or legal obligation."),
        ("INTERMEDIATE", "How long should an organization keep personal data under GDPR?",
         ["forever", "for ten years minimum", "as long as the employee wants", "no longer than necessary for the purpose it was collected"], "D",
         "GDPR's storage limitation principle requires deletion once data is no longer needed for its original purpose."),
        ("INTERMEDIATE", "A data loss prevention (DLP) tool blocks an email that contains a credit card number. What type of control is this?",
         ["a data loss prevention control that stops sensitive data leaving the network", "a firewall rule that blocks websites", "an antivirus signature", "a password policy"], "A",
         "DLP monitors and blocks transmissions of sensitive data such as card numbers to prevent exfiltration."),
        ("INTERMEDIATE", "A developer needs realistic data for testing without exposing real customer PII. Which technique is appropriate?",
         ["use real production data", "data masking or desensitization", "generate random names only", "store data in plaintext"], "B",
         "Data masking substitutes realistic fake values, so testers work with useful data while real PII stays protected."),
        ("INTERMEDIATE", "What is the main difference between encryption and hashing?",
         ["they are identical", "hashing is reversible with a key", "encryption is reversible with the correct key while hashing is one-way", "encryption is only for passwords"], "C",
         "Encryption can be reversed with the key, but hashing is a one-way function that cannot be reversed to recover the input."),
        ("INTERMEDIATE", "Which practice is the correct way to store user passwords?",
         ["store them in plaintext", "store them encrypted with a reversible cipher", "store unsalted hashes only", "store salted, slow hashes such as bcrypt or argon2"], "D",
         "Salted adaptive hashes resist brute force and rainbow tables, protecting passwords even if the database leaks."),
        ("INTERMEDIATE", "What does the GDPR 'right to be forgotten' allow a data subject to do?",
         ["request deletion of their personal data", "request free hosting", "change their email address", "object to receiving marketing once per year"], "A",
         "The right to erasure lets individuals ask organizations to delete their personal data under specified conditions."),
        ("INTERMEDIATE", "Why is it a best practice to rotate encryption keys periodically?",
         ["to make the system slower", "to limit the amount of data compromised if a key leaks", "to consume more storage", "to avoid using KMS"], "B",
         "Rotation limits the exposure window of a leaked key, since newer data is protected by fresh keys."),
        ("INTERMEDIATE", "A laptop containing customer data is stolen. Which control could have prevented exposure of that data?",
         ["a longer boot password for the user", "full-disk encryption on the laptop", "a privacy policy document", "an email disclaimer"], "C",
         "Full-disk encryption ensures the stolen drive's data remains unreadable without the encryption key."),
        ("INTERMEDIATE", "What is the purpose of an audit log for data access?",
         ["to speed up queries", "to hide who accessed data", "to record who accessed what data and when", "to compress the database"], "D",
         "Audit logs capture a record of data access, enabling accountability and investigation of misuse."),
        ("ADVANCED", "An organization must encrypt data in a database while keeping the encryption keys separate from the database administrators. Which approach achieves this?",
         ["client-side encryption using keys managed by a KMS", "letting the DB store keys next to the data", "encrypting only the backups", "storing keys in the application config file"], "A",
         "Client-side encryption with KMS-managed keys keeps encryption separate from the DB, so DBAs cannot read the data or keys."),
        ("ADVANCED", "A company must keep customer data within a specific country to satisfy legal requirements. Which concept does this reflect?",
         ["data masking", "data sovereignty or data residency", "data tokenization", "data analytics"], "B",
         "Data sovereignty requires data to remain within the borders of a jurisdiction in line with local laws."),
        ("ADVANCED", "A company discovers a breach affecting 200 EU customers' personal data. Under GDPR, what must it do?",
         ["nothing unless asked", "delete the affected accounts and stop", "notify the supervisory authority within 72 hours if the risk is significant", "publicly name every customer"], "C",
         "GDPR mandates notifying the supervisory authority within 72 hours when a breach poses a risk to individuals."),
        ("ADVANCED", "How does envelope encryption work in a KMS?",
         ["the same key encrypts everything forever", "each file is stored without a key", "keys are printed on paper", "a data key encrypts the data and a master key encrypts that data key"], "D",
         "Envelope encryption wraps a data key with a master key, so large data uses efficient data keys while the master key protects them."),
        ("ADVANCED", "Which password storage scheme is the strongest for a large user database?",
         ["a slow adaptive hash such as bcrypt or argon2 with a unique salt per user", "MD5 with no salt", "a reversible cipher", "plaintext in a hidden file"], "A",
         "Slow adaptive hashes with unique salts are deliberately expensive to crack, even with large-scale offline attacks."),
        ("ADVANCED", "A retailer that stores or processes cardholder data must comply with which industry standard?",
         ["ISO 27001", "PCI DSS", "HIPAA", "COBIT"], "B",
         "The Payment Card Industry Data Security Standard (PCI DSS) governs how cardholder data must be protected."),
        ("ADVANCED", "Data that has been de-identified but could be re-linked to individuals with additional information is called what?",
         ["anonymized data", "public data", "pseudonymized data", "aggregated data"], "C",
         "Pseudonymization replaces identifiers with codes that can be re-linked using separate information, so it is not truly anonymous."),
        ("ADVANCED", "An analyst must compute statistics on sensitive data without ever viewing individual values. Which privacy technique enables this?",
         ["publishing the raw dataset", "sending the raw data by email", "dropping the analysis entirely", "differential privacy applied to the analysis"], "D",
         "Differential privacy adds calibrated noise so aggregate results are useful while individual records remain hidden."),
        ("ADVANCED", "Which control most effectively prevents a cloud storage bucket containing PII from being accidentally exposed publicly?",
         ["blocking public access at the bucket and organizational level plus enforcing policies", "naming the bucket with an unusual string", "storing data in a nested folder", "setting the bucket to a lower storage tier"], "A",
         "Blocking public access at the organization level, combined with policies, stops accidental public exposure of sensitive buckets."),
        ("ADVANCED", "What is the purpose of a data retention policy?",
         ["to store everything forever", "to define how long data is kept and when it must be deleted, supporting compliance", "to make backups fail", "to share data with third parties"], "B",
         "Retention policies specify retention periods and deletion schedules so the organization meets legal and business requirements."),
    ],
}
