# -*- coding: utf-8 -*-
"""
Question bank for subject 16: OS101 - Operating System Fundamentals.
Category: Operating Systems & System Programming.

Topics:
  76: Processes & Threads
  77: CPU Scheduling
  78: Process Synchronization
  79: Deadlocks
  80: Memory Management

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    76: [
        ("BEGINNER", "What is a process in an operating system?",
         ["A program in execution", "A hardware device", "A file stored on disk", "A programming language"], "A",
         "A process is an instance of a program that is currently being executed by the CPU, including its code, data and resources."),
        ("BEGINNER", "Which is the smallest unit of CPU utilization that can be independently scheduled?",
         ["Process Control Block", "Thread", "Device driver", "System call"], "B",
         "A thread is the smallest unit of execution that the operating system scheduler assigns to the CPU."),
        ("BEGINNER", "Which data structure holds the state, registers and scheduling information of a process?",
         ["Page table", "File allocation table", "Process Control Block", "System call table"], "C",
         "The Process Control Block stores all metadata about a process, including its identifier, state, registers and scheduling information."),
        ("BEGINNER", "A process that is waiting for an I/O event to complete is in which state?",
         ["Ready", "Running", "New", "Waiting"], "D",
         "A process moves to the waiting (blocked) state when it needs an event such as I/O completion before it can continue."),
        ("BEGINNER", "What does the abbreviation PCB stand for?",
         ["Process Control Block", "Processor Cache Buffer", "Program Compile Block", "Process Code Base"], "A",
         "PCB is the Process Control Block, the kernel data structure that represents a process and holds its state and resources."),
        ("BEGINNER", "Which system call is used to create a new process in a Unix-like operating system?",
         ["exec", "fork", "clone", "spawn"], "B",
         "fork creates a nearly identical copy of the calling process, from which the new child process begins execution."),
        ("BEGINNER", "Which of the following is NOT a typical process state?",
         ["Ready", "Running", "Registered", "Terminated"], "C",
         "Typical process states are new, ready, running, waiting and terminated, and Registered is not among them."),
        ("BEGINNER", "What is a context switch?",
         ["Rebooting the system", "Switching keyboard layouts", "Copying files between directories", "Saving the current process state and loading the state of another"], "D",
         "A context switch saves the state of the currently running process and loads the saved state of another so the CPU can resume it."),
        ("BEGINNER", "Threads belonging to the same process share which of the following?",
         ["The code and data sections", "Individual register sets", "Separate address spaces", "Their own page tables"], "A",
         "Threads share the code, data and heap of their parent process while keeping their own registers and stacks."),
        ("BEGINNER", "Which of the following is often called a light-weight process?",
         ["A child process", "A thread", "A daemon", "A zombie process"], "B",
         "Threads are called light-weight processes because they share the address space of their parent and are cheaper to create and switch than full processes."),
        ("INTERMEDIATE", "A process calls fork() and the child immediately calls exec(). What is the effect of exec()?",
         ["The child continues from the fork point", "The child's memory image is replaced by a new program", "The parent terminates", "A second fork is created"], "B",
         "exec replaces the calling process's memory image with a new program, so the child begins executing a different program."),
        ("INTERMEDIATE", "Which scenario best describes a zombie process?",
         ["A process that uses all CPU time", "A process waiting for I/O", "A terminated process whose exit status has not yet been collected by its parent", "A process with no memory"], "C",
         "A zombie (defunct) process has terminated but still holds an entry in the process table until its parent calls wait() to collect its exit status."),
        ("INTERMEDIATE", "Which statement best describes an orphan process?",
         ["A process that runs in the background", "A process holding no resources", "A process that cannot be killed", "A process whose parent terminated before the child"], "D",
         "An orphan process is adopted by the init process after its original parent dies, so its parent-child link is reassigned."),
        ("INTERMEDIATE", "Which event moves a process from the Ready queue to the Running state?",
         ["The scheduler dispatches it to the CPU", "It finishes its I/O", "It calls exit()", "It is first created"], "A",
         "A ready process is dispatched by the CPU scheduler, which assigns it the processor and transitions it to the running state."),
        ("INTERMEDIATE", "A process with three threads calls fork() on Linux. What is the result?",
         ["One new process with one thread", "Three new processes", "Two processes, each with three threads", "One process with six threads"], "C",
         "fork duplicates the entire process including all of its threads, so the result is two processes each with three threads."),
        ("INTERMEDIATE", "Which of the following is an advantage of threads over processes?",
         ["Threads have isolated address spaces", "Threads are more secure", "Threads cannot crash", "Threads share memory and are cheaper to create"], "D",
         "Threads share the address space of their process, making inter-thread communication and thread creation faster than separate processes."),
        ("INTERMEDIATE", "A web server handles many clients by assigning one thread per client. This model is called:",
         ["Thread-per-request", "One process per client", "Single-threaded polling", "Event-free execution"], "A",
         "The thread-per-request model handles each client with its own thread, allowing concurrent service while threads share server data."),
        ("INTERMEDIATE", "Which of the following is stored in a thread control block (TCB) rather than shared with other threads?",
         ["Open file table", "Program counter and register set", "Memory limits", "Signal handlers"], "B",
         "The program counter and register set are per-thread and kept in the TCB, while resources such as files and memory belong to the process."),
        ("INTERMEDIATE", "When does a very small time quantum combined with frequent context switching hurt performance?",
         ["Never", "Only at boot time", "When no processes are ready", "When so much time is spent switching that useful work is reduced"], "D",
         "Frequent context switching with a tiny quantum wastes CPU time saving and restoring state instead of doing useful work."),
        ("INTERMEDIATE", "After a process calls fork(), how does the child know it is the child?",
         ["The parent sends a message", "The child reads its PID", "fork() returns 0 to the child and the child's PID to the parent", "The child checks the parent's state"], "C",
         "fork returns the child's PID to the parent and returns 0 to the child, which is how the two code paths are distinguished."),
        ("ADVANCED", "In a copy-on-write system, when is a page actually duplicated after fork()?",
         ["Immediately at fork", "At the child's termination", "When either parent or child writes to the shared page", "Never"], "C",
         "With copy-on-write, pages are shared read-only after fork and duplicated only when a process attempts a write."),
        ("ADVANCED", "Which thread model keeps all scheduling in a user-space library, giving very low context-switch cost?",
         ["One-to-one", "Many-to-many", "Kernel threads only", "User-level threads (many-to-one)"], "D",
         "User-level threads are managed entirely by a library in user space without kernel involvement, so their switches are very cheap."),
        ("ADVANCED", "In the one-to-one thread model, what is a major disadvantage?",
         ["Every thread operation needs a kernel system call, adding overhead", "Threads cannot share data", "Only one thread can run", "Threads cannot access files"], "A",
         "The one-to-one model gives good parallelism but each thread creation and switch requires a kernel call, which is expensive."),
        ("ADVANCED", "How is a real-time thread typically scheduled differently from a normal thread?",
         ["It has lower priority", "It is scheduled by priority or deadline rather than a fair time slice", "It never blocks", "It always stays on one core"], "B",
         "Real-time scheduling uses priorities or deadlines so time-critical threads meet their timing requirements instead of sharing equal time slices."),
        ("ADVANCED", "Which statement correctly describes the relationship between a process and its threads?",
         ["A process is always single-threaded", "Threads are independent processes", "Threads cannot be terminated", "Threads are execution streams within a process sharing its resources"], "D",
         "Threads are execution streams that run within a process, sharing its resources while having individual program counters and stacks."),
        ("ADVANCED", "Why does a server use a thread pool instead of creating a new thread per request?",
         ["Creating and destroying threads is expensive, so reusing threads reduces overhead", "Thread pools increase disk usage", "Thread pools remove concurrency", "A pool forces single-threading"], "A",
         "Reusing idle threads from a pool avoids the cost of repeatedly creating and destroying threads for each request."),
        ("ADVANCED", "What does gang scheduling do for cooperating threads on multicore systems?",
         ["Runs them on random cores", "Schedules all threads of a group simultaneously on different cores", "Runs only one thread at a time", "Prevents preemption entirely"], "B",
         "Gang scheduling runs all threads of a cooperating group at the same time on different processors, helping parallel applications progress together."),
        ("ADVANCED", "Which condition describes a process suffering from CPU starvation?",
         ["It is always running", "It never enters the ready queue", "It is ready but the scheduler never dispatches it", "It holds the CPU forever"], "C",
         "A ready process that is never selected by the scheduler suffers starvation when the scheduler keeps choosing other processes."),
        ("ADVANCED", "Why is fork() nearly free for a large parent process with copy-on-write?",
         ["Pages are shared read-only and duplicated only on first write", "The whole memory is copied instantly", "The process table is emptied", "The TLB is flushed only"], "A",
         "Copy-on-write defers actual page duplication until a write occurs, making fork fast even for very large address spaces."),
        ("ADVANCED", "How does a multithreaded process terminate all of its threads?",
         ["Kill only the main thread", "Exit when the first thread finishes", "Suspend the process", "Exit the process; all its threads end with it"], "D",
         "Terminating a process terminates all of its threads; individual threads cannot continue once the owning process exits."),
    ],

    77: [
        ("BEGINNER", "Which scheduling algorithm serves processes in the order in which they arrive?",
         ["First-Come, First-Served (FCFS)", "Shortest Job First", "Round Robin", "Priority"], "A",
         "FCFS dispatches the process that arrived earliest, using a simple FIFO queue."),
        ("BEGINNER", "Which algorithm gives each ready process an equal time slice called a quantum?",
         ["FCFS", "Round Robin", "Shortest Job First", "Priority"], "B",
         "Round Robin cycles through the ready queue, granting each process one time quantum before preempting it."),
        ("BEGINNER", "When the running process blocks on I/O, what does the scheduler do?",
         ["Nothing", "Suspends all processes", "Selects another ready process to run", "Kills the blocked process"], "C",
         "When the running process blocks, the dispatcher picks the next ready process so the CPU remains busy."),
        ("BEGINNER", "Which of the following is a scheduling decision?",
         ["Choosing a process to run", "Deciding whether to preempt", "Tuning the time quantum", "All of the above"], "D",
         "Scheduling involves selecting which process runs, deciding when to preempt and tuning the time quantum."),
        ("BEGINNER", "What is the turnaround time of a process?",
         ["Completion time minus arrival time", "Waiting time minus arrival", "Burst time minus waiting", "Arrival time minus completion"], "A",
         "Turnaround time measures the total time from a process's arrival until its completion."),
        ("BEGINNER", "What is the waiting time of a process?",
         ["Only the time from arrival to first dispatch", "Total time the process spends in the ready queue", "The burst time", "Completion time"], "B",
         "Waiting time is the total time a process spends in the ready queue, excluding time spent executing."),
        ("BEGINNER", "Which algorithm is theoretically optimal for average waiting time?",
         ["FCFS", "Round Robin", "Shortest Job First (SJF)", "None of them"], "C",
         "SJF provably gives the minimum average waiting time for a given set of burst times."),
        ("BEGINNER", "What is preemption in CPU scheduling?",
         ["Never interrupting a process", "Waiting for user input", "Letting a process run forever", "Forcibly removing the CPU from a running process"], "D",
         "Preemption lets the scheduler take the CPU away from a running process to give it to another."),
        ("BEGINNER", "Which criterion measures the time from submission until the first response?",
         ["Throughput", "Response time", "Turnaround time", "Burst time"], "B",
         "Response time is the time from submission of a request until the first response is produced."),
        ("BEGINNER", "What is throughput in CPU scheduling?",
         ["Processes completed per unit time", "Time for one process", "CPU utilization percent", "Ready queue length"], "A",
         "Throughput counts how many processes are completed in a given time interval."),
        ("INTERMEDIATE", "Processes P1(3), P2(6), P3(4), P4(7) arrive at time 0 and run under FCFS in that order. What is the average waiting time?",
         ["5.5", "6.25", "7.0", "6.75"], "B",
         "FCFS waiting times are 0, 3, 9 and 13, summing to 25, which averages to 6.25."),
        ("INTERMEDIATE", "Under non-preemptive SJF with P1(6), P2(8), P3(7), P4(3), what is the average turnaround time?",
         ["14", "12.5", "13", "15"], "C",
         "SJF runs jobs in ascending burst order giving completion times 3, 9, 16 and 24, which average to 13."),
        ("INTERMEDIATE", "With Round Robin, quantum 4, and bursts P1(6), P2(8), P3(7), P4(3), what is P1's waiting time?",
         ["7", "9", "13", "11"], "D",
         "P1 runs at 0-4 and again at 15-17, completing at 17, so its waiting time is 17 - 6 = 11."),
        ("INTERMEDIATE", "Which is a major drawback of FCFS in time-sharing systems?",
         ["The convoy effect and poor response for short jobs", "It is too complex", "It cannot preempt at all", "It needs a quantum"], "A",
         "FCFS lets long jobs block short ones behind them (the convoy effect) and gives poor response times."),
        ("INTERMEDIATE", "In priority scheduling, what does aging do?",
         ["Decreases priority", "Keeps priority fixed", "Gradually increases priority to prevent starvation", "Resets priority to zero"], "C",
         "Aging gradually raises the priority of waiting processes so that low-priority ones eventually get the CPU."),
        ("INTERMEDIATE", "Which scheduling algorithm can suffer from starvation?",
         ["Round Robin", "FCFS", "Highest Response Ratio Next", "Priority scheduling"], "D",
         "In pure priority scheduling, low-priority processes may wait indefinitely if higher-priority work keeps arriving."),
        ("INTERMEDIATE", "A process arrives at time 0 with burst 10 and completes at time 10. Its waiting time is:",
         ["0", "5", "10", "20"], "A",
         "Waiting time is completion minus arrival minus burst, which is 10 - 0 - 10 = 0."),
        ("INTERMEDIATE", "Which statement about non-preemptive SJF is correct?",
         ["It always gives optimal response", "A short job that arrives while a long job runs can be delayed", "It never causes delay", "It cannot be implemented"], "B",
         "Non-preemptive SJF can delay a short job that arrives while a long job is running, so it is not always optimal."),
        ("INTERMEDIATE", "In Round Robin, a very small time quantum causes:",
         ["Less context switching", "Higher throughput", "Lower overhead", "Excessive context-switch overhead"], "D",
         "A tiny quantum forces the scheduler to switch processes too often, wasting CPU time on context switches."),
        ("INTERMEDIATE", "How does Highest Response Ratio Next (HRRN) choose the next process?",
         ["Picks the shortest job", "Picks the lowest priority job", "Picks the job with the highest (waiting + service) / service ratio", "Uses a fixed quantum"], "C",
         "HRRN computes a response ratio of (wait + service) / service and runs the job with the highest ratio, balancing SJF and FCFS."),
        ("ADVANCED", "Which mechanism is required to enforce preemptive Round Robin?",
         ["A non-preemptive scheduler", "A batch dispatcher", "A timer interrupt that returns control to the scheduler each quantum", "A user-level lock"], "C",
         "Preemption relies on the timer interrupt firing each quantum so the scheduler can take the CPU back from the running process."),
        ("ADVANCED", "Why is SJF usually unsuitable for hard real-time systems?",
         ["It uses too much memory", "It ignores priorities", "It cannot run on modern CPUs", "It optimizes average time instead of meeting deadlines"], "D",
         "SJF minimizes average waiting time but does not guarantee that each task meets its deadline, so real-time schedulers like EDF are preferred."),
        ("ADVANCED", "With Round Robin (quantum 4) and bursts P1(9), P2(4), P3(9), what is the average turnaround time?",
         ["15", "16", "17", "14"], "A",
         "Round Robin gives completion times P2=8, P1=16 and P3=21, so the average turnaround time is (8 + 16 + 21) / 3 = 15."),
        ("ADVANCED", "In a multilevel feedback queue, what happens to a CPU-bound process?",
         ["It stays in the highest queue", "It sinks to lower-priority queues over time", "It is never preempted", "It is terminated"], "B",
         "Multilevel feedback queues move processes down to lower-priority queues when they use their full quantum, so CPU-bound jobs sink over time."),
        ("ADVANCED", "Which combination gives near-optimal average waiting time without starvation?",
         ["FCFS alone", "Round Robin with quantum 100", "Random scheduling", "SJF with aging"], "D",
         "Aging added to SJF keeps the optimal average waiting time while guaranteeing that every process eventually runs."),
        ("ADVANCED", "Why is mixing CPU-bound and I/O-bound processes beneficial?",
         ["It keeps both the CPU and devices busy, improving utilization", "It simplifies the scheduler", "It avoids context switches", "It prevents all waiting"], "A",
         "Interleaving CPU-bound and I/O-bound processes keeps both the CPU and I/O devices busy, improving overall utilization."),
        ("ADVANCED", "What is the specific job of the dispatcher?",
         ["Sorting the ready queue", "Performing the context switch to start the selected process", "Handling page faults", "Updating the process table"], "B",
         "The dispatcher is the module that switches context and hands control of the CPU to the process selected by the scheduler."),
        ("ADVANCED", "Which setting makes Round Robin feel most responsive to interactive users?",
         ["A very large quantum", "No preemption", "A small quantum that gives every process a quick turn", "FCFS ordering"], "C",
         "A small quantum lets every process get the CPU quickly, giving fast first responses to interactive users despite more overhead."),
        ("ADVANCED", "In periodic scheduling, if a task's worst-case execution time exceeds its period, what follows?",
         ["The task cannot be feasibly scheduled and deadlines will be missed", "It runs twice per period", "It is automatically migrated", "It never runs"], "A",
         "If the worst-case execution time of a periodic task is greater than its period, even a perfect scheduler cannot meet every deadline."),
        ("ADVANCED", "What does guaranteed scheduling do?",
         ["Uses SJF ordering", "Uses a random quantum", "Prevents context switches", "Tracks actual CPU use and gives the next quantum to the process furthest below its guaranteed share"], "D",
         "Guaranteed scheduling monitors how much CPU each process has consumed and allocates the next quantum to the one furthest below its guaranteed share."),
    ],

    78: [
        ("BEGINNER", "What is a race condition?",
         ["Two processes reading different files", "Concurrent access to shared data whose outcome depends on timing", "A hardware failure", "A slow-running program"], "A",
         "A race condition occurs when concurrent access to shared data makes the outcome depend on the unpredictable timing of the operations."),
        ("BEGINNER", "Which section of code accesses shared resources and must not be entered by two processes at once?",
         ["Entry section", "Critical section", "Exit section", "Remainder section"], "B",
         "The critical section is the code segment where a process accesses shared variables and mutual exclusion must be enforced."),
        ("BEGINNER", "What does mutual exclusion guarantee?",
         ["All processes run at once", "No process ever runs", "At most one process is in its critical section at a time", "Processes always run in order"], "C",
         "Mutual exclusion means at most one process may execute in its critical section at any given moment."),
        ("BEGINNER", "Which of the following is a synchronization primitive for controlling access to shared resources?",
         ["Compiler", "Scheduler queue", "Page table", "Semaphore"], "D",
         "A semaphore is a synchronization primitive whose wait and signal operations control access to shared resources."),
        ("BEGINNER", "What does the wait() (P) operation do on a semaphore?",
         ["Decrements the value and blocks the caller when it becomes negative", "Increments the value", "Resets it to zero", "Never changes it"], "A",
         "wait() decrements the semaphore and blocks the caller when the value becomes negative, enforcing mutual exclusion."),
        ("BEGINNER", "What does the signal() (V) operation do on a semaphore?",
         ["Decrements the value", "Increments the value and may wake a waiting process", "Deletes the semaphore", "Blocks the caller"], "B",
         "signal() increments the semaphore and wakes one waiting process if any, allowing it to proceed."),
        ("BEGINNER", "What is a mutex lock?",
         ["A file lock", "A page table entry", "A lock providing mutual exclusion for a critical section", "A scheduling queue"], "C",
         "A mutex is a lock that a process acquires before entering the critical section and releases after leaving, giving mutual exclusion."),
        ("BEGINNER", "What is busy waiting?",
         ["Sleeping for a long time", "Waiting for I/O", "Using the CPU for real work", "Spinning in a loop while checking a condition instead of blocking"], "D",
         "Busy waiting wastes CPU cycles by spinning and repeatedly testing a condition instead of yielding the processor."),
        ("BEGINNER", "Which classic problem involves producers and consumers sharing a bounded buffer?",
         ["Dining philosophers", "Producer-consumer", "Readers-writers", "Banker's algorithm"], "B",
         "The producer-consumer problem requires producers and consumers to cooperate on a bounded buffer without overfilling or underreading it."),
        ("BEGINNER", "Which requirement ensures that when the critical section is free and some processes want to enter, one is chosen in finite time?",
         ["Progress", "Mutual exclusion", "Bounded waiting", "Atomicity"], "A",
         "Progress guarantees that when the critical section is free, one of the processes requesting entry will be selected within a finite time."),
        ("INTERMEDIATE", "Two threads both execute counter = counter + 1 after reading counter as 10. What can the final value be?",
         ["12", "11", "20", "9"], "B",
         "Both threads read 10 and write back 11, losing one increment; this is a classic race condition."),
        ("INTERMEDIATE", "Peterson's algorithm is correct for two processes under which assumption?",
         ["Round Robin scheduling", "Strict alternation required", "Strictly interleaved execution with no simultaneous writes to shared variables", "A time quantum"], "C",
         "Peterson's algorithm assumes strictly interleaved execution, so simultaneous writes to shared variables must not occur."),
        ("INTERMEDIATE", "In the bounded buffer problem, why does the producer call wait(empty) before adding an item?",
         ["To enlarge the buffer", "To ensure mutual exclusion", "To sleep forever", "To block when no free slot remains, preventing overflow"], "D",
         "The producer decrements the empty semaphore first so it blocks when the buffer has no free slots, preventing overflow."),
        ("INTERMEDIATE", "A binary semaphore starts at 1. Two processes both call wait(). What happens?",
         ["The first enters and the second blocks", "Both enter", "Both block", "The system crashes"], "A",
         "The first wait() makes the value 0 and the process enters; the second wait() makes it -1 and that process blocks until signal() is called."),
        ("INTERMEDIATE", "Which problem shows how grabbing two resources at once can deadlock?",
         ["Producer-consumer", "Bounded buffer", "Dining philosophers", "Readers-writers"], "C",
         "The dining philosophers problem demonstrates how picking up both forks can lead to deadlock when every philosopher waits for a neighbour."),
        ("INTERMEDIATE", "In the readers-writers solution, why is the readcount variable protected by a mutex?",
         ["So readers can write", "To speed up readers", "To block all writers", "Because multiple readers must update it atomically"], "D",
         "The readcount variable is shared by all readers, so a mutex is needed to update it atomically and avoid a race."),
        ("INTERMEDIATE", "A counting semaphore starts at 3 and five processes call wait(). What is its final value?",
         ["-2", "2", "5", "-5"], "A",
         "Each wait() decrements the semaphore, so 3 - 5 = -2, meaning two processes are waiting."),
        ("INTERMEDIATE", "Which primitive avoids busy waiting?",
         ["Spinlock", "A blocking semaphore that suspends processes in a wait queue", "Test-and-set lock", "Compare-and-swap lock"], "B",
         "A blocking semaphore suspends the process and places it in a wait queue instead of spinning in a loop."),
        ("INTERMEDIATE", "What does the test-and-set instruction do?",
         ["Sets the value to the new one only", "Returns nothing", "Returns a random number", "Atomically reads the old value and sets the target to true"], "D",
         "Test-and-set atomically reads the old value and writes 1, returning the old value so locks can be acquired safely."),
        ("INTERMEDIATE", "Why does the producer-consumer solution need a mutex in addition to the semaphores?",
         ["To count empty slots", "To count full items", "To protect the buffer and its pointers from concurrent modification", "To prevent deadlock"], "C",
         "The mutex ensures only one process modifies the buffer and its pointers at a time, while the semaphores manage capacity."),
        ("ADVANCED", "When is a spinlock preferable to a blocking mutex?",
         ["When the critical section is held for a long time", "When waiting processes should sleep", "When the critical section is very short on a multicore system", "When there is a single CPU"], "C",
         "If the lock is held briefly, spinning wastes less time than a context switch, so spinlocks fit short critical sections on multicore systems."),
        ("ADVANCED", "Why can Peterson's algorithm fail on modern hardware?",
         ["It is too slow", "It needs three processes", "It requires preemption", "Compilers and CPUs reorder memory operations, breaking its ordering assumptions"], "D",
         "Compilers and CPUs reorder loads and stores, so Peterson's ordering assumptions fail without memory barriers."),
        ("ADVANCED", "Which guarantee does a monitor provide?",
         ["Mutual exclusion plus condition variables for synchronization", "Only mutual exclusion", "Only bounded waiting", "Faster execution"], "A",
         "A monitor encapsulates shared data and procedures, guaranteeing mutual exclusion and offering condition variables for waiting and signaling."),
        ("ADVANCED", "In a monitor, what does wait() on a condition variable do?",
         ["Continues executing", "Atomically releases the monitor lock and sleeps until signaled", "Raises the process priority", "Restarts the process"], "B",
         "wait() atomically releases the monitor lock and suspends the caller until another procedure calls signal() on the same condition."),
        ("ADVANCED", "Which condition makes a blocking bounded-buffer solution correct?",
         ["The producer never blocks", "The buffer is infinite", "Only one producer exists", "The producer blocks when the buffer is full and the consumer blocks when it is empty"], "D",
         "Blocking on the empty and full semaphores prevents overflow and underflow when the buffer is bounded."),
        ("ADVANCED", "Which software-only algorithm solves mutual exclusion for two processes?",
         ["Peterson's algorithm", "Round Robin", "Banker's algorithm", "Optimal replacement"], "A",
         "Peterson's algorithm uses shared turn and flag variables to achieve mutual exclusion, progress and bounded waiting for two processes in software."),
        ("ADVANCED", "What is a lock-free data structure?",
         ["One that disables interrupts", "One whose operations guarantee progress using atomic instructions without blocking locks", "One with no elements", "One used only by the kernel"], "B",
         "Lock-free algorithms use atomic instructions like compare-and-swap so that at least one thread always makes progress without acquiring locks."),
        ("ADVANCED", "Which design avoids both busy waiting and the convoy effect on multicore systems?",
         ["Pure spinlocks", "Pure mutexes", "Spinning briefly, then blocking if the lock is still held", "Disabling interrupts"], "C",
         "Spinning briefly and then blocking balances low latency for short holds with no wasted CPU for long holds."),
        ("ADVANCED", "Why can disabling interrupts cause priority inversion in real-time systems?",
         ["It delays high-priority work and a low-priority task holding a lock can block higher-priority ones", "It uses too much memory", "It cannot be implemented", "It always causes deadlock"], "A",
         "Disabling interrupts blocks important events, and without priority inheritance, a low-priority task holding a lock can invert priorities."),
        ("ADVANCED", "Which statement about priority inversion is correct?",
         ["It never happens with mutexes", "It affects only batch systems", "It makes high-priority tasks faster", "A low-priority task holding a lock delays a high-priority task that needs it"], "D",
         "Priority inversion is the situation where a high-priority task is blocked by a low-priority task holding a resource; priority inheritance reduces its impact."),
    ],

    79: [
        ("BEGINNER", "What is a deadlock?",
         ["A set of processes each waiting for an event only another process in the set can cause", "A process that runs forever", "A hardware failure", "A slow I/O operation"], "A",
         "Deadlock occurs when every process in a set waits for a resource held by another, so none can proceed."),
        ("BEGINNER", "Which of the following is NOT one of the four necessary conditions for deadlock?",
         ["Mutual exclusion", "Preemption", "Hold and wait", "Circular wait"], "B",
         "No preemption (resources cannot be forcibly taken) is a necessary condition; preemption actually helps break deadlock."),
        ("BEGINNER", "Which necessary condition requires a process to hold a resource while waiting for another?",
         ["Mutual exclusion", "Circular wait", "Hold and wait", "No preemption"], "C",
         "Hold and wait means a process already holds resources while requesting additional ones."),
        ("BEGINNER", "What does a resource allocation graph represent?",
         ["CPU usage over time", "Memory layout", "File sizes", "Which processes hold and request which resources"], "D",
         "The resource allocation graph shows processes and resources as nodes, with request and assignment edges depicting their relationships."),
        ("BEGINNER", "Which of the following is a deadlock prevention strategy?",
         ["Breaking one of the four necessary conditions", "Ignoring deadlocks", "Overheating the CPU", "Increasing context switches"], "A",
         "Deadlock prevention eliminates at least one necessary condition, such as allowing preemption of resources."),
        ("BEGINNER", "Which algorithm determines whether a system is in a safe state?",
         ["Round Robin", "Banker's algorithm", "First-Come, First-Served", "Shortest Job First"], "B",
         "The Banker's algorithm simulates resource allocation to see if all processes can complete without deadlock."),
        ("BEGINNER", "What is a safe state?",
         ["A state with no processes", "A state where the CPU is idle", "A state from which resources can be allocated so every process can finish without deadlock", "A state with unlimited memory"], "C",
         "A safe state has a sequence of allocations allowing every process to finish, guaranteeing no deadlock occurs."),
        ("BEGINNER", "Which is a valid deadlock recovery method?",
         ["Adding more RAM", "Speeding up the CPU", "Rebooting only the display", "Preempting resources or terminating a process"], "D",
         "Recovery from deadlock can involve preempting resources from some process or terminating processes to release their resources."),
        ("BEGINNER", "Which condition states that each resource instance can be held by only one process at a time?",
         ["Hold and wait", "Mutual exclusion", "Circular wait", "No preemption"], "B",
         "Mutual exclusion means each resource instance can be used by only one process at a time."),
        ("BEGINNER", "What does a wait-for graph show?",
         ["Only which processes are waiting on which other processes", "All resource assignments", "The scheduling order", "Memory allocations"], "A",
         "The wait-for graph condenses the resource allocation graph by showing only which processes are waiting on which other processes."),
        ("INTERMEDIATE", "Total resources are 10 units. A holds 4 (max 7) and B holds 4 (max 7). A requests 2 more. What happens?",
         ["Granted and still safe", "Granted but the state becomes unsafe", "The request is ignored", "B is terminated"], "B",
         "After the grant, available becomes 0 while A still needs 1 and B needs 3, so neither process can finish and the system enters an unsafe state."),
        ("INTERMEDIATE", "Requiring a process to release its held resources before requesting more breaks which condition?",
         ["Mutual exclusion", "Circular wait", "Hold and wait", "No preemption"], "C",
         "Requiring a process to release its held resources before requesting more removes the hold-and-wait condition."),
        ("INTERMEDIATE", "In a resource allocation graph, an edge from resource R to process P means:",
         ["P requests R", "R is being deleted", "R is free", "R is allocated to P"], "D",
         "An assignment edge from a resource node to a process node means that resource is currently held by that process."),
        ("INTERMEDIATE", "Requesting all resources in a fixed global order prevents deadlock by eliminating which condition?",
         ["Circular wait", "Mutual exclusion", "Hold and wait", "No preemption"], "A",
         "If every process requests resources in a fixed global order, a circular chain of waiting becomes impossible."),
        ("INTERMEDIATE", "In the Banker's algorithm, what does the Need matrix contain?",
         ["Total system resources", "Resources currently allocated", "Resources each process may still need to reach its maximum", "Resources released"], "C",
         "Need equals Maximum minus Allocation, the additional units each process may still request."),
        ("INTERMEDIATE", "With a single instance of each resource type, which statement is correct?",
         ["Both waiting processes proceed", "The system crashes", "Resources duplicate", "Deadlock is impossible because a cycle cannot form"], "D",
         "With one instance per resource type, the wait-for graph is a chain and can never contain a cycle, so deadlock cannot happen."),
        ("INTERMEDIATE", "How is deadlock detected with a wait-for graph?",
         ["A cycle in the graph indicates deadlock", "The number of processes indicates it", "RAM usage indicates it", "CPU load indicates it"], "A",
         "If the wait-for graph contains a cycle, the processes on that cycle are deadlocked."),
        ("INTERMEDIATE", "What is the main advantage of deadlock avoidance over prevention?",
         ["It is always optimal", "It is less restrictive while still preventing deadlock", "It ignores worst cases", "It never rejects requests"], "B",
         "Avoidance permits requests that keep the system in a safe state, so it is less restrictive than prevention while guaranteeing no deadlock."),
        ("INTERMEDIATE", "When recovering from deadlock by preemption, which process should be rolled back?",
         ["The first to finish", "The one with the shortest code", "The one holding the fewest resources", "The one whose rollback costs the least"], "D",
         "Choosing the process with the lowest rollback cost minimizes the expense of breaking the deadlock."),
        ("INTERMEDIATE", "Which everyday scenario is a classic deadlock?",
         ["Two students sharing one printer at different times", "A full mailbox blocking its sender", "Two cars on a narrow bridge, each waiting for the other to move", "A process waiting for user input"], "C",
         "Each car holds one side of the bridge and waits for the other to move, creating a circular wait that is a classic deadlock."),
        ("ADVANCED", "Which statement correctly contrasts starvation and deadlock?",
         ["They are identical", "Deadlock resolves itself", "Starvation can occur without deadlock and a starved process may eventually run", "Starvation requires all four conditions"], "C",
         "Starvation is indefinite postponement of a ready process, which can happen without a circular wait, while deadlock is a permanent blocked state."),
        ("ADVANCED", "In a database, what is the most reasonable first deadlock recovery action?",
         ["Reboot the whole machine", "Add memory", "Terminate all user processes", "Roll back the cheapest transaction in the cycle"], "D",
         "Rolling back the least-expensive transaction breaks the cycle with minimal loss of work and is the standard recovery step."),
        ("ADVANCED", "Why is a cycle in a resource allocation graph not always fatal when resources have multiple instances?",
         ["The remaining free instances may satisfy the outstanding requests in the cycle", "Cycles are impossible", "Resources preempt automatically", "Only one process can wait"], "A",
         "With multiple instances per resource type, a cycle in the graph does not guarantee deadlock, so the detection algorithm must check availability."),
        ("ADVANCED", "What is the main practical limitation of the Banker's algorithm?",
         ["It is too slow", "Each process must declare its maximum resource need in advance", "It cannot detect deadlock", "It uses too much memory"], "B",
         "Banker's needs a priori knowledge of each process's maximum claim, which is rarely available in practice."),
        ("ADVANCED", "Granting a request only if the resulting state stays safe is known as:",
         ["Deadlock prevention", "Deadlock detection", "The ostrich approach", "Deadlock avoidance"], "D",
         "Deadlock avoidance, the Banker's approach, checks each request against safety and only grants it if the state remains safe."),
        ("ADVANCED", "Ordering resources and requiring increasing-order requests prevents deadlock by breaking:",
         ["Circular wait", "Mutual exclusion", "Hold and wait", "Preemption"], "A",
         "A total ordering of resource types with strictly increasing request order makes circular waiting impossible."),
        ("ADVANCED", "With one instance per resource type, which wait-for graph indicates deadlock?",
         ["Only cycles including multi-instance resources", "Any cycle, because each edge is a wait on a held resource", "Only self-loops", "No cycles"], "B",
         "With one instance per type, every edge in the cycle is a wait on a held resource, so any cycle means deadlock."),
        ("ADVANCED", "Preempting a resource from a holding process directly violates which condition?",
         ["Mutual exclusion", "Circular wait", "No preemption", "Hold and wait"], "C",
         "Preempting a resource from a holding process violates the no-preemption condition, which is how the deadlock is resolved."),
        ("ADVANCED", "Why do many operating systems prefer the ostrich approach to deadlocks?",
         ["Deadlocks are rare and handling them is often more costly than occasional restarts", "Deadlocks never occur", "It is the only option", "It improves CPU speed"], "A",
         "Because deadlocks occur rarely and cost little to fix manually, many systems prefer the simple ostrich approach over expensive avoidance or detection."),
        ("ADVANCED", "Which request can lead to a deadlock the Banker's algorithm did not anticipate?",
         ["A request within the declared maximum", "A process that never requests resources", "A system with no resources", "A process requesting more than its declared maximum"], "D",
         "The Banker's algorithm assumes processes never exceed their declared maximums; a request above the maximum breaks that assumption and can cause deadlock."),
    ],

    80: [
        ("BEGINNER", "What is the main purpose of memory management?",
         ["Allocating and tracking memory for processes and the kernel", "Compiling programs", "Scheduling the CPU", "Handling network packets"], "A",
         "Memory management tracks and allocates memory so processes and the kernel get the space they need."),
        ("BEGINNER", "What is a page fault?",
         ["A hardware crash", "An access to a page not currently in main memory", "A CPU error", "A disk error"], "B",
         "A page fault occurs when a program references a page that is not resident in physical memory."),
        ("BEGINNER", "Which technique maps virtual addresses to physical addresses using fixed-size blocks?",
         ["Segmentation", "Contiguous allocation", "Paging", "Fragmentation"], "C",
         "Paging divides memory into fixed-size pages and frames and maps virtual pages to physical frames."),
        ("BEGINNER", "What does virtual memory allow a program to do?",
         ["Run without a CPU", "Use memory as if it were far larger than physical RAM", "Skip disk access", "Share nothing"], "D",
         "Virtual memory lets programs address more space than physical RAM by swapping pages between RAM and disk."),
        ("BEGINNER", "In a paged system, what is the smallest unit of allocation?",
         ["A page (frame)", "A byte", "A bit", "A segment"], "A",
         "Memory is divided into fixed-size pages in virtual space and frames in physical space, the smallest allocation unit."),
        ("BEGINNER", "What is a TLB?",
         ["A disk buffer", "A fast cache of recent page table entries", "A CPU register", "A memory compiler"], "B",
         "The translation look-aside buffer caches recent virtual-to-physical mappings to speed up address translation."),
        ("BEGINNER", "Which of the following causes external fragmentation?",
         ["Paging", "Contiguous fixed partitions", "Segmentation without paging", "TLB caching"], "C",
         "Segmentation allocates variable-sized segments that leave small unusable holes between them, causing external fragmentation."),
        ("BEGINNER", "What is internal fragmentation?",
         ["Holes between segments", "Unused space inside an allocated block or page", "A memory leak", "Slow paging"], "B",
         "Internal fragmentation is unused space inside an allocated region, such as leftover bytes at the end of a frame."),
        ("BEGINNER", "Which page replacement policy evicts the page unused for the longest time?",
         ["FIFO", "LRU", "Random", "Second chance"], "B",
         "Least Recently Used (LRU) evicts the page whose last use is furthest in the past."),
        ("BEGINNER", "What is thrashing?",
         ["Excessive paging that consumes more time than useful work", "Very fast execution", "A disk failure", "A short process"], "A",
         "Thrashing occurs when a system spends more time swapping pages in and out than executing instructions."),
        ("INTERMEDIATE", "A 32-bit virtual address uses 4 KB pages. How many bits form the page number?",
         ["10", "20", "12", "32"], "B",
         "The offset uses log2(4096) = 12 bits, so the page number uses 32 - 12 = 20 bits."),
        ("INTERMEDIATE", "With 16 KB pages and a 20-bit virtual address, how many page table entries are possible?",
         ["128", "32", "64", "256"], "C",
         "With a 16 KB page the offset needs 14 bits, leaving 6 bits for the page number, so at most 2^6 = 64 pages."),
        ("INTERMEDIATE", "How many page faults does FIFO (3 frames) produce for reference string 1,2,3,4,1,2,5,1,2,3,4,5?",
         ["7", "8", "9", "10"], "D",
         "FIFO produces 10 page faults for this reference string with 3 frames, evicting pages in arrival order."),
        ("INTERMEDIATE", "A page table maps virtual pages to what?",
         ["Physical frames", "Files", "Threads", "Segments"], "A",
         "The page table translates each virtual page number into the physical frame where it currently resides."),
        ("INTERMEDIATE", "What happens on a page fault, in correct order?",
         ["The CPU continues and the page loads later", "The process is terminated", "The kernel traps, loads the page from disk, updates the page table, and resumes the process", "The TLB is cleared and nothing else happens"], "C",
         "A page fault traps into the kernel, which fetches the missing page, updates the page table, and restarts the instruction."),
        ("INTERMEDIATE", "Which of the following best reduces the cost of page faults?",
         ["A larger TLB only", "A faster CPU", "More registers", "Fast storage or enough frames so few faults occur"], "D",
         "Page faults are slow because of disk I/O, so faster storage or keeping pages in memory reduces the penalty."),
        ("INTERMEDIATE", "If a page table entry has a valid bit of 0, what does it mean?",
         ["The page is not in memory and a reference causes a page fault", "The page is in the TLB", "The page is valid", "The page is cached"], "A",
         "A zero valid bit means the mapping is not current, so the hardware triggers a page fault to load the page."),
        ("INTERMEDIATE", "Belady's anomaly shows that:",
         ["More frames always reduce faults", "Adding frames can increase page faults under FIFO", "LRU can increase faults", "Frames have no effect"], "B",
         "Belady's anomaly demonstrates that, with FIFO, adding more frames can paradoxically increase the number of page faults."),
        ("INTERMEDIATE", "What is the working set of a process?",
         ["Its page table size", "Its stack size", "Its code size", "The pages it is actively using in a recent window"], "D",
         "The working set is the collection of pages referenced during a recent time window; it guides how many frames a process needs."),
        ("INTERMEDIATE", "Which statement about segmentation is correct?",
         ["All segments are equal in size", "Segments cannot be shared", "Segments are variable-sized logical units that can cause external fragmentation", "Segmentation replaces paging"], "C",
         "Segmentation uses variable-sized logical units that fit the program's structure but leaves external fragmentation."),
        ("ADVANCED", "Why do modern systems combine paging with segmentation?",
         ["To save disk space", "To remove virtual memory", "To get paging's fixed-size management with segmentation's protection and sharing", "To simplify the TLB"], "C",
         "Combined schemes page each segment, giving protection and sharing with paging's fixed-size management."),
        ("ADVANCED", "A 64-bit virtual space cannot keep a full flat page table in memory. What solves this?",
         ["Adding RAM", "Larger pages only", "Faster CPUs", "Multilevel page tables that keep only used portions resident"], "D",
         "Multilevel (hierarchical) page tables page the page table itself, so only the portions in use need to be in memory."),
        ("ADVANCED", "Which algorithm is the practical approximation of LRU used in real systems?",
         ["Clock (second chance) with a reference bit", "Optimal", "Random", "Pure FIFO"], "A",
         "The clock algorithm uses a reference bit and a circular pointer to approximate LRU with low overhead, making it practical."),
        ("ADVANCED", "What limits the Optimal page replacement algorithm to benchmark use?",
         ["It is too slow", "It requires future knowledge of the reference string", "It needs too many frames", "It cannot handle FIFO"], "B",
         "Optimal replacement evicts the page used furthest in the future, which requires knowing future references, so it serves only as a comparison standard."),
        ("ADVANCED", "On a TLB miss, what happens next?",
         ["The instruction resumes", "The system reboots", "A disk swap occurs", "The translation is found by walking the page table, then loaded into the TLB"], "D",
         "On a TLB miss the translation must be located by walking the page table, then inserted into the TLB before the instruction resumes."),
        ("ADVANCED", "Which scenario is thrashing, and what is the best remedy?",
         ["The working set exceeds the frames allocated, so increase frames or reduce multiprogramming", "Too many files are open", "The TLB is full with no remedy", "The disk is slow with no remedy"], "A",
         "When the working set does not fit in the frames given, the process faults continuously; giving it enough frames or reducing multiprogramming stops the thrashing."),
        ("ADVANCED", "Which allocation strategy uses the smallest hole large enough for a process?",
         ["First fit", "Best fit", "Worst fit", "Random fit"], "B",
         "Best fit searches all holes and uses the smallest one large enough, leaving the smallest leftover gap."),
        ("ADVANCED", "Where does internal fragmentation most often appear in a paged system?",
         ["Inside variable segments", "Across TLB entries", "In the partially filled last page of a process", "In the page table"], "C",
         "Internal fragmentation occurs in the final page of a process, which is rarely fully utilized."),
        ("ADVANCED", "What is the main benefit of copy-on-write during fork()?",
         ["Read-only pages are shared and copied only on first write, making fork fast and memory-efficient", "Everything is copied immediately", "Paging is disabled", "The TLB shrinks"], "A",
         "Copy-on-write shares pages read-only and only copies on first write, making fork fast and memory-efficient."),
        ("ADVANCED", "How does page size relate to TLB coverage?",
         ["Larger pages increase needed entries", "Smaller pages cover more memory per entry", "Page size does not matter", "Larger pages give each TLB entry more coverage, improving hit rates"], "D",
         "A single TLB entry maps one full page, so larger pages mean each entry covers more memory, raising the hit ratio."),
    ],
}

