# -*- coding: utf-8 -*-
"""
Question bank for subject 36: CORE101 - Data Structures & Algorithms.
Category: Core Computer Science & Emerging Technologies.

Topics:
  176: Arrays & Linked Lists
  177: Stacks & Queues
  178: Trees & Graphs
  179: Sorting & Searching
  180: Algorithm Analysis & Design

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    176: [
        ("BEGINNER", "What is the index of the first element in a zero-based array?",
         ["0", "1", "2", "-1"], "A",
         "Arrays in most languages are zero-based, so the first element is stored at index 0."),
        ("BEGINNER", "Which structure stores elements in nodes connected by pointers to the next node?",
         ["array", "singly linked list", "hash table", "binary tree"], "B",
         "A singly linked list organizes data into nodes that each hold a reference to the next node."),
        ("BEGINNER", "In a singly linked list, what does the head pointer point to?",
         ["the last node", "the node count", "the first node", "a dummy node"], "C",
         "The head pointer references the first node of the list, giving a starting point for traversal."),
        ("BEGINNER", "Which of these can an array access directly by index in constant time?",
         ["the head pointer", "the previous node", "the node before the tail", "any element via its index"], "D",
         "Array indexing uses address arithmetic, so any element is reached in O(1) time using its index."),
        ("BEGINNER", "How many pointers does a node in a doubly linked list hold?",
         ["two", "one", "three", "four"], "A",
         "A doubly linked list node stores two pointers, one to the previous node and one to the next node."),
        ("BEGINNER", "What does the tail of a linked list represent?",
         ["the first node", "the last node", "a sentinel node", "the middle node"], "B",
         "The tail is the last node of the list, whose next pointer typically points to null."),
        ("BEGINNER", "In a garbage-collected language, what happens to the memory of a node that is removed and no longer referenced?",
         ["it is erased immediately", "it is reused by the compiler", "it becomes eligible for garbage collection", "it is moved to the stack"], "C",
         "When no references remain, the node becomes unreachable and is reclaimed by the garbage collector later."),
        ("BEGINNER", "Which array operation is O(n) in the worst case because elements must be shifted?",
         ["reading arr[i]", "inserting at the very end when capacity remains", "updating arr[i]", "inserting an element in the middle"], "D",
         "Inserting into the middle forces every following element to shift right, taking linear time."),
        ("BEGINNER", "What is a circular linked list?",
         ["a list whose last node points back to the first node", "a list with two heads", "a list stored contiguously", "a list that sorts itself"], "A",
         "In a circular linked list the last node points back to the first, forming a loop with no null tail."),
        ("BEGINNER", "Which statement about a static array is true?",
         ["its size can change at runtime freely", "its size is fixed at creation time", "it is always stored on the heap", "it cannot hold integers"], "B",
         "A static array has a fixed size determined when it is created and cannot grow or shrink."),
        ("INTERMEDIATE", "Given a singly linked list with n nodes, what is the time complexity of finding the last node when only the head is available?",
         ["O(n)", "O(log n)", "O(1)", "O(n^2)"], "A",
         "Without a tail pointer, reaching the last node requires walking through all n nodes."),
        ("INTERMEDIATE", "Consider an array with 5 elements. How many elements must be shifted to insert a new value at index 0 in a fixed array?",
         ["0", "5", "1", "4"], "B",
         "Inserting at the front shifts all 5 existing elements one position to the right."),
        ("INTERMEDIATE", "In a doubly linked list, how many pointer fields must be updated to insert a new node after a given node (not counting the new node's own initialization)?",
         ["two", "three", "four", "one"], "C",
         "The operation updates the next pointer of the given node, the previous and next of its neighbor, and the new node's fields, totaling four updates."),
        ("INTERMEDIATE", "Which data structure offers O(1) access by index but O(n) insertion in the middle?",
         ["singly linked list", "doubly linked list", "array", "binary tree"], "D",
         "Arrays give constant-time random access, but inserting in the middle requires shifting elements."),
        ("INTERMEDIATE", "What happens if a linked-list traversal loop forgets to advance the current pointer?",
         ["the loop becomes infinite, visiting the same node repeatedly", "the list is sorted", "the traversal stops early", "the head is deleted"], "A",
         "Without advancing the pointer, the same node is visited forever and the loop never terminates."),
        ("INTERMEDIATE", "Which scenario best favors a linked list over an array?",
         ["frequent random access by index", "frequent insertions and deletions at arbitrary positions where the node is known", "needing cache-friendly iteration", "storing a fixed-size grid"], "B",
         "Linked lists avoid shifting by relinking pointers, making known-node insertions and deletions cheap."),
        ("INTERMEDIATE", "How can a cycle in a singly linked list be detected using only O(1) extra space?",
         ["counting the nodes", "using two pointers moving at different speeds", "reversing the list twice", "sorting the list"], "C",
         "Floyd's tortoise-and-hare technique uses a fast and a slow pointer; if they meet, a cycle exists."),
        ("INTERMEDIATE", "Why is deleting a given node in a singly linked list O(1) only when its predecessor is already known?",
         ["the tail must be updated", "the list must be re-sorted", "the predecessor's next pointer must be updated to bypass the node", "the node count must be recalculated"], "D",
         "Removing a node requires rewiring the predecessor, so knowing that predecessor avoids a traversal."),
        ("INTERMEDIATE", "What is the worst-case time to search for a value in an unsorted singly linked list of n nodes?",
         ["O(n)", "O(log n)", "O(1)", "O(n log n)"], "A",
         "An unsorted list offers no ordering shortcuts, so the target may require checking every node."),
        ("INTERMEDIATE", "After unlinking a node from a C linked list, what should be done to avoid a memory leak?",
         ["leave it referenced", "free the node's memory", "reallocate the list", "copy it to the stack"], "B",
         "Calling free on the removed node returns its memory to the heap, preventing a leak."),
        ("ADVANCED", "You must frequently add and remove elements at both ends of a collection. Which structure is ideal?",
         ["a doubly linked list with head and tail pointers", "a singly linked list with only a head", "a fixed array", "a binary search tree"], "A",
         "Head and tail pointers make push and pop at either end O(1) in a doubly linked list."),
        ("ADVANCED", "Why are linked lists often cache-unfriendly compared with arrays?",
         ["they store fewer elements", "their nodes are scattered in memory, hurting spatial locality", "they are always slower to build", "they require more arithmetic per access"], "B",
         "Heap-allocated nodes are spread across memory, so iterating them causes frequent cache misses."),
        ("ADVANCED", "What is the main benefit of an XOR linked list in a memory-constrained setting?",
         ["it sorts itself", "it needs no head pointer", "it stores each pair of links as one XORed pointer, halving pointer storage", "it guarantees O(log n) search"], "C",
         "By storing next XOR previous in a single field, an XOR linked list uses half the pointer space of a normal doubly linked list."),
        ("ADVANCED", "Which operation is O(1) in a doubly linked list with a tail pointer but O(n) in a singly linked list with only a head?",
         ["reading the head", "searching for a value", "inserting after the head", "removing the last node"], "D",
         "The tail pointer gives direct access to the last node and its predecessor, while a singly linked list must traverse to find them."),
        ("ADVANCED", "Which capacity-growth strategy for a dynamic array amortizes appends to O(1)?",
         ["doubling the capacity when full", "growing by one slot each time", "shrinking by half each time", "never growing"], "A",
         "Doubling makes each copy cost O(k) but amortizes across k appends, giving O(1) amortized per append."),
        ("ADVANCED", "What is the running time of merging two already sorted singly linked lists of sizes m and n?",
         ["O(m * n)", "O(m + n)", "O(log(m + n))", "O(m^2)"], "B",
         "Merging walks each list once, taking at most one pointer per element, so the total is O(m + n)."),
        ("ADVANCED", "When reversing a singly linked list iteratively, how many pointers does the classic implementation maintain?",
         ["one", "two", "three", "five"], "C",
         "Three pointers (previous, current and next) allow the list to be rewired in a single pass."),
        ("ADVANCED", "A music player needs instant access to any track by its playlist position and rarely adds or removes tracks. Which is best?",
         ["a singly linked list", "a doubly linked list", "an array indexed by position", "a stack"], "D",
         "An array provides O(1) random access by index, which suits the instant-jump requirement."),
        ("ADVANCED", "Why is a dummy (sentinel) head node useful when deleting nodes from a singly linked list?",
         ["it doubles the list size", "it makes the list circular", "it removes the special case of deleting the head", "it stores the node count"], "C",
         "With a dummy head, every deletion treats the same uniform case, eliminating separate head handling."),
        ("ADVANCED", "A memory manager keeps free blocks in a singly linked list and searches for the first block large enough for a request. What is this policy called?",
         ["best fit", "first fit", "worst fit", "buddy system"], "B",
         "First fit scans from the head and selects the earliest block that satisfies the requested size."),
    ],
    177: [
        ("BEGINNER", "Which principle describes how a stack stores and retrieves items?",
         ["Last In, First Out (LIFO)", "First In, First Out (FIFO)", "Shortest Job First", "Random Order"], "A",
         "A stack removes the most recently added item first, which is the LIFO discipline."),
        ("BEGINNER", "Which principle does a queue follow?",
         ["Last In, First Out (LIFO)", "First In, First Out (FIFO)", "Largest In, First Out", "Priority Order"], "B",
         "A queue removes the earliest added item first, following the FIFO discipline."),
        ("BEGINNER", "Which operation adds an element to the top of a stack?",
         ["enqueue", "pop", "push", "dequeue"], "C",
         "Push places a new element on the top of the stack, making it the next to be popped."),
        ("BEGINNER", "Which operation removes the element that has been in a queue the longest?",
         ["push", "pop", "enqueue", "dequeue"], "D",
         "Dequeue removes the front element, which is the one that has waited the longest."),
        ("BEGINNER", "What does the pop operation do on a stack?",
         ["removes and returns the top element", "adds an element", "counts the elements", "sorts the stack"], "A",
         "Pop takes the top element off the stack and returns it to the caller."),
        ("BEGINNER", "Which data structure is most naturally used to reverse the order of a sequence?",
         ["queue", "stack", "array", "hash table"], "B",
         "Because a stack is LIFO, pushing a sequence and then popping it yields the reversed order."),
        ("BEGINNER", "What does the front of a queue represent?",
         ["the newest element", "a sentinel", "the element that will be removed next", "the element just added"], "C",
         "The front holds the oldest element, which is the next one dequeued."),
        ("BEGINNER", "What does peek (or top) do on a stack without modifying it?",
         ["removes the top element", "returns the top element without removing it", "adds an element", "clears the stack"], "D",
         "Peek reads the top element while leaving the stack unchanged."),
        ("BEGINNER", "A queue supports which two main operations?",
         ["push and pop", "enqueue and dequeue", "insert and delete at any index", "sort and search"], "A",
         "The two fundamental queue operations are enqueue, which adds at the rear, and dequeue, which removes from the front."),
        ("BEGINNER", "Which real-world scenario best matches the behavior of a queue?",
         ["a stack of plates", "a printer processing print jobs in arrival order", "an undo history", "a browser back button"], "B",
         "Print jobs are handled in the order they arrive, exactly matching FIFO queue behavior."),
        ("INTERMEDIATE", "If you push 1, 2 and 3 onto a stack in that order, in what order are they popped?",
         ["3, 2, 1", "1, 2, 3", "1, 3, 2", "2, 1, 3"], "A",
         "LIFO means the last pushed value 3 comes out first, followed by 2 and then 1."),
        ("INTERMEDIATE", "If you enqueue 1, 2 and 3 into a queue in that order, what is the dequeue order?",
         ["3, 2, 1", "1, 2, 3", "2, 3, 1", "1, 3, 2"], "B",
         "FIFO preserves arrival order, so values leave in the same order they were enqueued."),
        ("INTERMEDIATE", "When using a stack to check balanced parentheses, what do you do when you encounter a closing bracket?",
         ["push it onto the stack", "pop the top and check it matches the closing bracket", "ignore it", "clear the stack"], "C",
         "The top of the stack holds the most recent opening bracket, which must match the closing one."),
        ("INTERMEDIATE", "What should happen when you pop from an empty array-based stack?",
         ["it becomes 0", "it becomes -1", "it wraps to the last index", "the operation underflows and should be reported"], "D",
         "Popping an empty stack is an underflow, so the implementation should signal an error rather than modify the stack."),
        ("INTERMEDIATE", "What is the amortized time complexity of push and pop in a stack backed by a dynamically growing array?",
         ["O(1) amortized", "O(n) amortized", "O(log n)", "O(n^2)"], "A",
         "Although resizing occasionally copies all elements, the cost spreads evenly over pushes, giving O(1) amortized."),
        ("INTERMEDIATE", "When implementing a queue with two stacks, what happens during a dequeue operation?",
         ["all elements stay put", "elements are transferred from the first stack to the second stack, then the top of the second stack is popped", "the queue is reversed", "only the first stack is used"], "B",
         "Transferring pushes elements into the second stack, so its top becomes the queue front, enabling FIFO order."),
        ("INTERMEDIATE", "In a circular queue of capacity N, which expression advances the rear index with wrap-around?",
         ["rear = rear + 1", "rear = rear * 2", "rear = (rear + 1) % N", "rear = rear - 1"], "C",
         "The modulo operator makes the index wrap back to 0 after reaching the end, reusing free slots."),
        ("INTERMEDIATE", "What does stack overflow refer to in an array-based stack?",
         ["the stack is empty", "an attempt to push onto a full stack", "the top pointer is negative", "the stack is circular"], "D",
         "Pushing onto a stack whose array has no free slots is an overflow condition."),
        ("INTERMEDIATE", "Using a stack, what is the result of evaluating the postfix expression 5 3 + 2 *?",
         ["15", "10", "11", "16"], "A",
         "5 3 + gives 8, then 8 2 * gives 16, so the postfix expression evaluates to 16."),
        ("INTERMEDIATE", "When implementing a queue with a singly linked list, why enqueue at the tail?",
         ["the tail is always empty", "with a tail pointer, enqueue becomes O(1)", "order does not matter", "the head is faster to access"], "B",
         "Keeping a tail pointer lets new nodes be appended in constant time without traversing the list."),
        ("ADVANCED", "Which pair of applications is a classic use of a stack?",
         ["function call management and undo operations", "printer spooling and scheduling", "cache eviction and sorting", "graph coloring and hashing"], "A",
         "Recursion frames and undo histories both follow the LIFO pattern that a stack provides."),
        ("ADVANCED", "Why is a circular buffer used for a bounded queue?",
         ["it automatically sorts elements", "it reuses array slots by wrapping indices, avoiding element shifts", "it doubles memory usage", "it never overflows"], "B",
         "Wrapping the head and rear indices reuses freed slots, so no shifting is ever required."),
        ("ADVANCED", "In the shunting-yard algorithm for converting infix to postfix, what does the stack hold?",
         ["operands", "operators waiting for their operands", "output tokens", "parentheses counts only"], "C",
         "The operator stack temporarily parks operators until their operands and precedence resolve the order."),
        ("ADVANCED", "What is the minimum number of stacks needed to implement a queue that supports enqueue and dequeue in O(1) amortized time?",
         ["one", "two", "three", "four"], "D",
         "Two stacks suffice: one for enqueueing and one that is filled to serve dequeue operations in FIFO order."),
        ("ADVANCED", "A web browser's back button maintains the pages visited earlier. Which structure is the best fit?",
         ["a queue", "a circular buffer", "a stack of visited URLs", "a binary tree"], "A",
         "Going back returns to the most recently visited page, which is exactly LIFO stack behavior."),
        ("ADVANCED", "Which statement correctly describes a deque (double-ended queue)?",
         ["it only allows access at one end", "elements can be added or removed from both ends", "it must be circular", "it is the same as a stack"], "B",
         "A deque permits efficient insertion and removal at both its front and rear."),
        ("ADVANCED", "What must you check before each pop on an array-based stack to stay safe?",
         ["whether the stack is full", "whether the stack is empty", "whether the array is circular", "whether the top is negative only"], "D",
         "Checking emptiness prevents an underflow, which would otherwise read memory past the stack's data."),
        ("ADVANCED", "A stack uses an array that doubles in size when full. What is the amortized cost of each push?",
         ["O(n)", "O(log n)", "O(n^2)", "O(1)"], "D",
         "The rare copying cost is spread over the many pushes between resizes, yielding O(1) amortized per push."),
        ("ADVANCED", "Which structure best models a task scheduler that always processes the most recently submitted job first?",
         ["a stack", "a queue", "an array", "a min-heap"], "A",
         "Processing the newest job first is LIFO behavior, which a stack implements directly."),
        ("ADVANCED", "During recursion, what happens to the call stack each time a recursive call begins?",
         ["a new frame is pushed and the stack grows", "the stack shrinks", "the stack is cleared", "the top frame is overwritten"], "B",
         "Every recursive invocation pushes a new activation frame, so the stack grows with each call."),
    ],
    178: [
        ("BEGINNER", "What is the topmost node of a tree called?",
         ["root", "leaf", "branch", "child"], "A",
         "The root is the highest node in a tree, with no parent and every other node reachable below it."),
        ("BEGINNER", "What do you call a node that has no children?",
         ["root", "leaf", "internal node", "sibling"], "B",
         "A leaf is a node with zero children, sitting at the bottom of the tree."),
        ("BEGINNER", "In a binary tree, how many children can each node have at most?",
         ["one", "three", "two", "unlimited"], "C",
         "A binary tree restricts every node to at most two children, typically called left and right."),
        ("BEGINNER", "Using the standard definition where a leaf has height 0, what is the height of a leaf node?",
         ["1", "-1", "2", "0"], "D",
         "By convention the height of a leaf is 0, and the height of a tree is the longest path from root to a leaf."),
        ("BEGINNER", "What is the node directly above a given node in a tree called?",
         ["parent", "child", "sibling", "ancestor"], "A",
         "The parent is the immediate node one level above, connected by a single edge."),
        ("BEGINNER", "What is an undirected graph?",
         ["a graph whose edges have no direction", "a graph with only one vertex", "a graph stored in a tree", "a graph with weighted edges only"], "B",
         "In an undirected graph every edge connects two vertices symmetrically with no notion of direction."),
        ("BEGINNER", "Which of these is a graph traversal algorithm?",
         ["binary search", "bubble sort", "breadth-first search", "linear probing"], "C",
         "Breadth-first search systematically explores a graph level by level from a starting vertex."),
        ("BEGINNER", "In a binary search tree, where do the values in the left subtree of a node lie relative to the node's key?",
         ["greater than the key", "less than the key", "equal to the key", "anywhere"], "D",
         "The BST property requires every value in the left subtree to be smaller than the node's key."),
        ("BEGINNER", "What is a complete binary tree?",
         ["a tree with no leaves", "a tree where all levels are filled except possibly the last, which is filled left to right", "a tree with exactly two levels", "a tree with only root and one child"], "A",
         "A complete binary tree packs nodes densely so all levels are full except the final one, which fills from left to right."),
        ("BEGINNER", "How many edges does a tree with n nodes have?",
         ["n", "n - 1", "n + 1", "2n"], "B",
         "A tree with n nodes always has exactly n - 1 edges, since it is a connected acyclic graph."),
        ("INTERMEDIATE", "What is the time complexity of searching for a key in a balanced binary search tree containing n nodes?",
         ["O(log n)", "O(n)", "O(1)", "O(n log n)"], "A",
         "Each comparison halves the search space in a balanced BST, so the search takes O(log n) time."),
        ("INTERMEDIATE", "In which order does an in-order traversal visit the nodes of a binary search tree?",
         ["root, left, right", "left subtree, root, right subtree, yielding sorted order", "right, left, root", "random order"], "B",
         "In-order traversal visits left, then root, then right, which reproduces the keys in ascending sorted order."),
        ("INTERMEDIATE", "What is the height of a perfectly balanced binary tree containing exactly 7 nodes?",
         ["3", "4", "2", "1"], "C",
         "Seven nodes fill three full levels (1 + 2 + 4), so the height measured as longest edge path is 2."),
        ("INTERMEDIATE", "Which data structure is a binary heap most commonly used to implement?",
         ["a stack", "a linked list", "a priority queue", "a hash map"], "D",
         "A binary heap gives O(log n) insertion and extraction, which is exactly what a priority queue needs."),
        ("INTERMEDIATE", "What is the worst-case time complexity of searching a BST that has degenerated into a chain of n nodes?",
         ["O(n)", "O(log n)", "O(1)", "O(n^2)"], "A",
         "A degenerate BST behaves like a linked list, so a search may visit every node in O(n) time."),
        ("INTERMEDIATE", "During breadth-first search on a graph, which data structure manages the frontier of nodes waiting to be visited?",
         ["a stack", "a queue", "a min-heap", "an array"], "B",
         "BFS explores nodes in FIFO order, so a queue holds the frontier of nodes to process next."),
        ("INTERMEDIATE", "During depth-first search on a graph, which mechanism manages the nodes to visit next?",
         ["a queue", "a hash table", "a stack or the recursion call stack", "a sorted array"], "C",
         "DFS dives deep before backtracking, which a stack (or implicit recursion stack) supports naturally."),
        ("INTERMEDIATE", "For a graph with n vertices stored as an adjacency matrix, how much space is required?",
         ["O(n)", "O(log n)", "O(n^2)", "O(2n)"], "D",
         "An adjacency matrix uses an n by n table, giving O(n^2) space regardless of the edge count."),
        ("INTERMEDIATE", "What is the time complexity of inserting a new key into a balanced AVL tree with n nodes?",
         ["O(log n)", "O(n)", "O(1)", "O(n^2)"], "A",
         "An AVL tree stays balanced, so the insertion path plus rebalancing rotations run in O(log n)."),
        ("INTERMEDIATE", "Which traversal visits the root first, then the left subtree, then the right subtree?",
         ["in-order", "pre-order", "post-order", "level-order"], "B",
         "Pre-order processes the root before either subtree, giving the order root, left, right."),
        ("ADVANCED", "Which algorithm finds the shortest paths from a single source in a graph with non-negative edge weights?",
         ["Dijkstra's algorithm", "Bellman-Ford", "Kruskal's algorithm", "Prim's algorithm"], "A",
         "Dijkstra's algorithm greedily settles the nearest unprocessed vertex and is correct when weights are non-negative."),
        ("ADVANCED", "When a graph has negative edge weights but no negative cycles, which algorithm computes the shortest paths?",
         ["Dijkstra's algorithm", "Bellman-Ford", "binary search", "DFS"], "B",
         "Bellman-Ford relaxes all edges repeatedly and can handle negative weights, which Dijkstra cannot."),
        ("ADVANCED", "What is the time complexity of Dijkstra's algorithm when a binary heap implements the priority queue, with V vertices and E edges?",
         ["O(V^2)", "O((V + E) log V)", "O(E log V + V)", "O(V + E)"], "C",
         "Each edge triggers a heap operation and each vertex an extract-min, giving O((V + E) log V)."),
        ("ADVANCED", "Which algorithm builds a minimum spanning tree by repeatedly adding the cheapest edge that does not create a cycle?",
         ["Dijkstra's algorithm", "Bellman-Ford", "Floyd-Warshall", "Kruskal's algorithm"], "D",
         "Kruskal's algorithm sorts edges by weight and unions their endpoints unless they already lie in the same component."),
        ("ADVANCED", "Which traversal processes vertices in order of edge-distance from the source, making it ideal for unweighted shortest paths?",
         ["depth-first search", "breadth-first search", "in-order traversal", "pre-order traversal"], "A",
         "BFS reaches all vertices at distance d before any at distance d + 1, so the first visit is shortest in unweighted graphs."),
        ("ADVANCED", "In a binary heap stored as an array with 0-based indexing, where are the children of the node at index i?",
         ["at i - 1 and i + 1", "at 2i + 1 and 2i + 2", "at 2i and 2i + 1", "at i/2 and i/3"], "B",
         "The standard array layout places the left child at 2i + 1 and the right child at 2i + 2."),
        ("ADVANCED", "What are the running times for inserting into and extracting the minimum from a binary heap with n elements?",
         ["O(n) for both", "O(1) for both", "O(log n) for both", "O(n log n) for both"], "C",
         "Sifting up or down follows a root-to-leaf path, so both operations cost O(log n)."),
        ("ADVANCED", "Which property must hold for a valid max-heap?",
         ["every parent is smaller than its children", "the tree is sorted in level order", "every parent is greater than or equal to its children", "all leaves are at the same level"], "D",
         "The max-heap property requires each parent to be at least as large as each of its children."),
        ("ADVANCED", "To detect cycles with DFS, what three states do the nodes need?",
         ["red, green, blue", "unvisited, in the current path, finished", "pushed, popped, empty", "low, medium, high"], "B",
         "A cycle is found when DFS reaches a node still in the current exploration path (gray), with finished nodes marked black."),
        ("ADVANCED", "Why is an adjacency list usually preferred over an adjacency matrix for large sparse graphs?",
         ["it is easier to sort", "it uses O(V + E) space and iterates a vertex's neighbors in degree time", "it is always faster for dense graphs", "it stores edge weights automatically"], "B",
         "An adjacency list stores only existing edges, so space and neighbor iteration scale with the actual edge count."),
    ],
    179: [
        ("BEGINNER", "Which sorting algorithm repeatedly swaps adjacent elements that are out of order?",
         ["bubble sort", "merge sort", "radix sort", "counting sort"], "A",
         "Bubble sort makes adjacent passes, swapping neighboring pairs whenever they are inverted."),
        ("BEGINNER", "Which searching algorithm requires the input array to be sorted first?",
         ["linear search", "binary search", "hashing", "brute force"], "B",
         "Binary search relies on sorted order to eliminate half of the remaining elements each step."),
        ("BEGINNER", "Which sorting algorithm is based on divide and conquer, splitting the array in half recursively?",
         ["bubble sort", "selection sort", "merge sort", "insertion sort"], "C",
         "Merge sort divides the array into two halves, sorts each recursively, and merges the results."),
        ("BEGINNER", "What does a stable sorting algorithm guarantee?",
         ["the array is sorted in descending order", "equal elements keep their original relative order", "the sort uses O(1) extra space", "the sort never uses recursion"], "D",
         "Stability preserves the relative order of records that compare as equal, which matters for multi-key sorting."),
        ("BEGINNER", "Which sorting algorithm repeatedly selects the smallest remaining element and places it at the front?",
         ["selection sort", "merge sort", "quick sort", "heap sort"], "A",
         "Selection sort scans the unsorted portion for the minimum and swaps it into the next sorted position."),
        ("BEGINNER", "In linear search over an array of n elements, what is the worst-case number of comparisons?",
         ["log n", "n", "n/2", "1"], "B",
         "If the target is the last element or absent, linear search compares against all n elements."),
        ("BEGINNER", "Which sorting algorithm inserts each element into its correct position among already sorted elements?",
         ["selection sort", "bubble sort", "insertion sort", "radix sort"], "C",
         "Insertion sort builds the sorted portion one element at a time by placing each new item in order."),
        ("BEGINNER", "What is the time complexity of binary search on a sorted array of n elements?",
         ["O(n)", "O(n^2)", "O(n log n)", "O(log n)"], "D",
         "Each comparison halves the search interval, so binary search requires about log2(n) steps."),
        ("BEGINNER", "For an already sorted array, what is the best-case time of bubble sort if the implementation stops when a pass makes no swaps?",
         ["O(n)", "O(n log n)", "O(n^2)", "O(1)"], "A",
         "After one swap-free pass the algorithm detects the array is sorted and exits, taking only O(n) time."),
        ("BEGINNER", "Which of these is a comparison-based sorting algorithm?",
         ["counting sort", "radix sort", "merge sort", "bucket sort with known range"], "B",
         "Merge sort orders elements by comparing pairs, unlike counting and radix sorts which use key arithmetic."),
        ("INTERMEDIATE", "What is the worst-case time complexity of quicksort?",
         ["O(n^2)", "O(n log n)", "O(n)", "O(log n)"], "A",
         "When the pivot is always the extreme element, quicksort degrades to O(n^2) comparisons."),
        ("INTERMEDIATE", "What is the average-case time complexity of quicksort?",
         ["O(n)", "O(n log n)", "O(n^2)", "O(log n)"], "B",
         "With a reasonable pivot, quicksort partitions and recurses logarithmically deep, giving O(n log n) on average."),
        ("INTERMEDIATE", "What is the time complexity of merge sort in both the best and worst cases?",
         ["O(n^2) in both", "O(n log n) in both", "O(n) in both", "O(log n) in both"], "C",
         "Merge sort always splits and merges the same way, so it runs in O(n log n) regardless of input order."),
        ("INTERMEDIATE", "Which sorting algorithm achieves its O(n) best case on nearly sorted data?",
         ["merge sort", "heap sort", "quick sort", "insertion sort"], "D",
         "Insertion sort makes few comparisons when each new element belongs near the end of the sorted prefix, running in O(n)."),
        ("INTERMEDIATE", "What is the extra space complexity of merge sort due to the merging step?",
         ["O(n)", "O(log n)", "O(1)", "O(n^2)"], "A",
         "Merging requires a temporary buffer proportional to the array size, so the auxiliary space is O(n)."),
        ("INTERMEDIATE", "Starting from [5, 3, 8, 1], after one complete bubble-sort pass bubbling the largest value to the end, what is the array?",
         ["[1, 3, 5, 8]", "[3, 5, 1, 8]", "[5, 8, 3, 1]", "[8, 5, 3, 1]"], "B",
         "The pass swaps 5 with 3, then 5 with 8 stops, and finally 8 with 1, yielding [3, 5, 1, 8]."),
        ("INTERMEDIATE", "After one pass of selection sort on [5, 3, 8, 1], which value ends up in the first position?",
         ["5", "3", "1", "8"], "C",
         "Selection sort finds the overall minimum 1 in the first pass and swaps it into index 0."),
        ("INTERMEDIATE", "Which sorting algorithm chooses a pivot, partitions the array around it, and recurses?",
         ["merge sort", "bubble sort", "insertion sort", "quicksort"], "D",
         "Quicksort partitions elements into those below and above a pivot, then sorts each side recursively."),
        ("INTERMEDIATE", "When binary searching a sorted array of one million elements, roughly how many comparisons are needed in the worst case?",
         ["about 20", "about 100", "about one million", "about 1000"], "A",
         "Since 2^20 exceeds one million, binary search needs at most about 20 comparisons."),
        ("INTERMEDIATE", "What condition must be met for binary search to produce correct results?",
         ["the array must have no duplicates", "the collection must be sorted", "the array must be of integers", "the collection must be small"], "B",
         "Binary search only works correctly when the collection is sorted, because it relies on ordered elimination."),
        ("ADVANCED", "Which sorting algorithm runs in O(n + k) time when all keys are small integers in the range 0 to k?",
         ["counting sort", "merge sort", "heapsort", "quicksort"], "A",
         "Counting sort tallies key frequencies and computes positions, avoiding comparisons and achieving O(n + k)."),
        ("ADVANCED", "Which stable sorting algorithm is commonly used as the per-digit sort inside radix sort?",
         ["quicksort", "counting sort", "heapsort", "selection sort"], "B",
         "Radix sort needs a stable linear-time inner sort, and counting sort fits that requirement perfectly."),
        ("ADVANCED", "For n numbers each with d digits in base b, what is the time complexity of radix sort?",
         ["O(d * (n + b))", "O(n log n)", "O(d * n log n)", "O(n^2)"], "C",
         "Radix sort processes each of the d digit passes in O(n + b) time, giving O(d * (n + b)) overall."),
        ("ADVANCED", "Which of these sorting algorithms is NOT comparison-based?",
         ["merge sort", "quicksort", "heapsort", "counting sort"], "D",
         "Counting sort uses value frequencies rather than comparisons between elements to place them."),
        ("ADVANCED", "What is the information-theoretic lower bound on the worst-case time of any comparison-based sort of n elements?",
         ["Omega(n log n)", "O(n)", "Omega(n)", "O(n log log n)"], "A",
         "With n! possible permutations and binary comparisons, at least log2(n!) comparisons are needed, which is Omega(n log n)."),
        ("ADVANCED", "You need O(1) extra space, stability is not required, and good worst-case guarantees. Which sort is the best fit?",
         ["merge sort", "quicksort", "heapsort", "counting sort"], "C",
         "Heapsort sorts in place using O(1) auxiliary space and guarantees O(n log n) time in every case."),
        ("ADVANCED", "For a small array that is already almost sorted, which algorithm is usually fastest in practice?",
         ["quicksort", "merge sort", "insertion sort", "radix sort"], "D",
         "Insertion sort performs few moves on nearly sorted data, often beating more complex algorithms for small inputs."),
        ("ADVANCED", "What is the worst-case time complexity of quicksort when the pivot is always the first element of an already sorted array?",
         ["O(n log n)", "O(n)", "O(log n)", "O(n^2)"], "D",
         "The pivot splits the array into one empty side and the rest, producing n levels of recursion and O(n^2) total work."),
        ("ADVANCED", "When sorting data too large to fit in memory, which algorithm is the standard approach?",
         ["quicksort", "insertion sort", "counting sort", "merge sort with multi-way merging"], "A",
         "Merge sort processes data in runs and merges them on disk, making it the backbone of external sorting."),
        ("ADVANCED", "Compared with linear search, what does binary search guarantee on a sorted array of n elements?",
         ["it is stable", "O(log n) worst-case comparisons instead of O(n)", "it requires no comparisons", "it works on any array"], "B",
         "Binary search halves the search space each step, guaranteeing at most O(log n) comparisons in the worst case."),
    ],
    180: [
        ("BEGINNER", "What does Big-O notation describe?",
         ["the exact runtime in seconds", "the asymptotic growth rate of a function, usually the worst case", "the memory used by one variable", "the number of lines of code"], "A",
         "Big-O characterizes how an algorithm's resource use grows as the input size approaches infinity."),
        ("BEGINNER", "Which of the following represents linear time complexity?",
         ["O(n)", "O(n^2)", "O(log n)", "O(1)"], "B",
         "O(n) means the work grows in direct proportion to the input size n."),
        ("BEGINNER", "Which complexity grows slowest for large inputs?",
         ["O(n)", "O(n^2)", "O(log n)", "O(2^n)"], "C",
         "Logarithmic growth increases very slowly, so O(log n) is the smallest of the listed classes."),
        ("BEGINNER", "What is the time complexity of accessing an array element by its index?",
         ["O(n)", "O(log n)", "O(1)", "O(n^2)"], "D",
         "Array indexing computes the address directly, so accessing any element takes constant time."),
        ("BEGINNER", "Which of these growth rates is the slowest for large n?",
         ["O(n!)", "O(2^n)", "O(n^3)", "O(n log n)"], "A",
         "Factorial growth O(n!) is the largest, hence the slowest, among these options."),
        ("BEGINNER", "What does it mean for an algorithm to run in O(n^2) time?",
         ["runtime is exactly n^2 seconds", "runtime grows proportional to the square of the input size", "the algorithm uses n^2 memory", "the input must be squared"], "B",
         "O(n^2) indicates the dominant cost scales quadratically with the input size."),
        ("BEGINNER", "Which complexity class describes exponential growth?",
         ["O(n)", "O(n^2)", "O(2^n)", "O(log n)"], "C",
         "O(2^n) doubles the work for each additional unit of input, which is exponential growth."),
        ("BEGINNER", "What is the definition of an algorithm?",
         ["a random sequence of steps", "a finite sequence of well-defined steps that solves a problem", "a programming language", "a type of hardware"], "D",
         "An algorithm is a precise, finite procedure that always terminates and produces a correct result."),
        ("BEGINNER", "What is the time complexity of a loop that runs n iterations doing O(1) work each time?",
         ["O(n)", "O(n^2)", "O(log n)", "O(1)"], "A",
         "The n iterations each cost constant time, so the total work is linear in n."),
        ("BEGINNER", "Which of these is an example of a greedy algorithm?",
         ["merge sort", "Dijkstra's algorithm", "binary search", "depth-first search"], "B",
         "Dijkstra's algorithm makes the locally optimal choice at each step, which is the greedy strategy."),
        ("INTERMEDIATE", "What is the time complexity of the naive recursive Fibonacci function computing fib(n)?",
         ["O(2^n)", "O(n)", "O(n^2)", "O(log n)"], "A",
         "The naive recursion recomputes the same subproblems repeatedly, branching exponentially into O(2^n) calls."),
        ("INTERMEDIATE", "What is the time complexity of computing Fibonacci numbers iteratively with a table of size n?",
         ["O(n^2)", "O(2^n)", "O(log n)", "O(n)"], "D",
         "The iterative approach fills the table once, computing each Fibonacci number in constant time."),
        ("INTERMEDIATE", "Which technique reuses the solutions of overlapping subproblems by storing them in a table?",
         ["divide and conquer", "backtracking", "dynamic programming", "brute force"], "C",
         "Dynamic programming caches subproblem results so overlapping computations are not repeated."),
        ("INTERMEDIATE", "What is the time complexity of finding the largest element in an unsorted array of n elements?",
         ["O(n)", "O(log n)", "O(n log n)", "O(1)"], "A",
         "Every element must be examined at least once, so the scan requires O(n) comparisons."),
        ("INTERMEDIATE", "Which design technique solves a problem by breaking it into independent subproblems, solving each, and combining the results?",
         ["divide and conquer", "greedy selection", "randomization", "iteration only"], "B",
         "Divide and conquer splits the problem, solves the pieces recursively, and merges their solutions."),
        ("INTERMEDIATE", "What is the recurrence relation for the running time of merge sort?",
         ["T(n) = T(n - 1) + O(1)", "T(n) = 2T(n/2) + O(n)", "T(n) = T(n/2) + O(1)", "T(n) = nT(n - 1)"], "B",
         "Merge sort solves two halves of size n/2 and does O(n) merging work, giving T(n) = 2T(n/2) + O(n)."),
        ("INTERMEDIATE", "What is the complexity of two nested loops where each runs n times?",
         ["O(n)", "O(log n)", "O(n^2)", "O(2n)"], "C",
         "The inner loop runs n times for each of the n outer iterations, giving n * n = n^2 operations."),
        ("INTERMEDIATE", "What is the running time of binary search?",
         ["O(n)", "O(n^2)", "O(log n)", "O(n log n)"], "D",
         "Each step discards half of the search interval, so at most about log2(n) steps are needed."),
        ("INTERMEDIATE", "In dynamic programming, what does memoization mean?",
         ["solving the largest subproblem first", "caching the results of subproblems to avoid recomputation", "sorting the subproblems", "using random guesses"], "A",
         "Memoization stores each subproblem's answer so later calls retrieve it instantly instead of recomputing."),
        ("INTERMEDIATE", "What is the space complexity of a memoized recursive Fibonacci that stores results for indices 0 to n?",
         ["O(n^2)", "O(2^n)", "O(1)", "O(n)"], "B",
         "The memo table holds n + 1 values and the recursion stack stays O(n) deep, so the space is O(n)."),
        ("ADVANCED", "What is the time complexity of the classic 0/1 knapsack dynamic-programming solution with n items and capacity W?",
         ["O(nW)", "O(n^2)", "O(2^n)", "O(W)"], "A",
         "The DP table has n by W cells and each is filled in constant time, giving O(nW)."),
        ("ADVANCED", "The longest common subsequence of two strings of lengths m and n is solved in what time with dynamic programming?",
         ["O(m * n)", "O(m + n)", "O(2^n)", "O(n log m)"], "B",
         "The classic DP fills an m by n table in constant time per cell, so it runs in O(mn)."),
        ("ADVANCED", "What is the time complexity of the dynamic-programming solution for matrix-chain multiplication of n matrices?",
         ["O(n)", "O(n^2)", "O(n^3)", "O(2^n)"], "C",
         "The algorithm considers O(n^2) intervals and tries O(n) split points each, totaling O(n^3)."),
        ("ADVANCED", "What is the time complexity of the Held-Karp dynamic-programming solution to the traveling salesman problem with n cities?",
         ["O(n^2)", "O(n * 2^n)", "O(n^2 * 2^n)", "O(n!)"], "D",
         "Held-Karp stores a state for each subset of cities and each end city, requiring O(n^2 * 2^n) time."),
        ("ADVANCED", "What is the time complexity of the Floyd-Warshall all-pairs shortest-path algorithm for a graph with n vertices?",
         ["O(n^3)", "O(n^2)", "O(n log n)", "O(n * E)"], "A",
         "Floyd-Warshall runs three nested loops over the n vertices, giving a cubic O(n^3) running time."),
        ("ADVANCED", "Which technique solves the fractional knapsack problem optimally?",
         ["dynamic programming over weight", "greedy, sorting items by value-to-weight ratio", "divide and conquer", "randomized rounding"], "B",
         "Because fractions are allowed, taking items in descending value-to-weight order is provably optimal."),
        ("ADVANCED", "What is the asymptotic time complexity of Strassen's matrix multiplication algorithm?",
         ["O(n^3)", "O(n^2)", "O(n^2.807)", "O(n log n)"], "C",
         "Strassen's seven recursive multiplications yield a running time of O(n^log2 7), approximately O(n^2.807)."),
        ("ADVANCED", "Why can a greedy approach fail for the general coin-change problem?",
         ["it never produces any solution", "a locally optimal coin choice may not lead to the globally optimal combination", "it uses too much memory", "it requires sorted coins always"], "D",
         "Greedy picks the largest coin that fits, but that can force more coins overall than an optimal combination would."),
        ("ADVANCED", "Which problem is solved by repeatedly selecting the activity that finishes earliest?",
         ["matrix-chain multiplication", "fractional knapsack", "activity selection", "0/1 knapsack"], "A",
         "Sorting activities by finish time and greedily choosing the earliest finishing compatible one yields the maximum count."),
        ("ADVANCED", "For what purpose is the master theorem used?",
         ["to prove an algorithm is optimal", "to solve recurrences of the form T(n) = aT(n/b) + f(n) and derive asymptotic bounds", "to generate test data", "to compute the factorial of n"], "B",
         "The master theorem gives closed-form bounds for divide-and-conquer recurrences in one step."),
    ],
}
