# -*- coding: utf-8 -*-
"""
Question bank for subject 18: OS103 - Linux & Shell Scripting.
Category: Operating Systems & System Programming.

Topics:
  86: Linux Basics & Commands
  87: Permissions & Ownership
  88: Shell Scripting
  89: Process Management in Linux
  90: Networking & Package Mgmt

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    86: [
        ("BEGINNER", "Which command prints the current working directory?",
         ["pwd", "ls", "cd", "cat"], "A",
         "pwd (print working directory) displays the absolute path of the directory you are currently in."),
        ("BEGINNER", "Which command lists the files and directories in the current directory?",
         ["ls", "cp", "mv", "mkdir"], "B",
         "The ls command lists the contents of a directory, showing files and subdirectories."),
        ("BEGINNER", "Which command creates a new directory?",
         ["rmdir", "rm", "mkdir", "touch"], "C",
         "mkdir creates a new directory, and the -p option lets you create nested paths at once."),
        ("BEGINNER", "Which command is used to copy files or directories?",
         ["mv", "cp", "rm", "ln"], "D",
         "cp copies a source file or directory to a destination, leaving the original in place."),
        ("BEGINNER", "Which command moves or renames a file?",
         ["mv", "cp", "find", "grep"], "A",
         "mv both moves a file to a new location and renames it by giving a new name in the same directory."),
        ("BEGINNER", "Which command permanently deletes a file?",
         ["cat", "rm", "touch", "cp"], "B",
         "rm removes files, or directories with -r, and the data is not placed in a trash folder."),
        ("BEGINNER", "Which command opens the online manual page for another command?",
         ["help", "man", "whatis", "apropos"], "C",
         "man displays the manual pages that describe a command's options and usage."),
        ("BEGINNER", "Which command displays the contents of a file on the terminal?",
         ["mkdir", "rm", "grep", "cat"], "D",
         "cat writes the full contents of a file to standard output."),
        ("BEGINNER", "Which command searches for matching lines of text inside files?",
         ["grep", "find", "sort", "sed"], "A",
         "grep scans files for lines that match a given pattern and prints the lines that match."),
        ("BEGINNER", "Which command changes the current working directory?",
         ["ls", "cd", "pwd", "mv"], "B",
         "cd changes the shell's working directory to the specified path."),
        ("INTERMEDIATE", "What additional information does ls -l show for each file?",
         ["permissions, owner, group, size and modification time", "only the file size", "the full file contents", "the file checksum"], "A",
         "The long listing format displays metadata such as permissions, owner, group, size and modification time."),
        ("INTERMEDIATE", "Which command finds files by name or other attributes inside a directory tree?",
         ["grep", "find", "diff", "which"], "B",
         "find walks a directory tree and matches files by name, type, size and other criteria."),
        ("INTERMEDIATE", "What does the command rm -r do?",
         ["removes an empty directory", "removes a file without confirmation", "removes directories and their contents recursively", "renames a directory"], "C",
         "The -r option makes rm delete a directory together with everything inside it, recursively."),
        ("INTERMEDIATE", "Which command prints only the first 10 lines of a file?",
         ["tail", "sed", "wc", "head"], "D",
         "head outputs the beginning of a file, 10 lines by default."),
        ("INTERMEDIATE", "Which command prints only the last 10 lines of a file?",
         ["tail", "head", "more", "less"], "A",
         "tail outputs the end of a file, and the -f option makes it follow a growing file such as a log."),
        ("INTERMEDIATE", "What does the pipe symbol | do between two commands?",
         ["runs them at exactly the same time", "sends the output of the first command as input to the second", "compares their outputs", "joins their arguments into one list"], "B",
         "A pipe connects the standard output of one command to the standard input of the next."),
        ("INTERMEDIATE", "Which command counts lines, words and characters in a file?",
         ["sort", "uniq", "wc", "awk"], "C",
         "wc (word count) reports the number of lines, words and bytes in its input."),
        ("INTERMEDIATE", "Which command shows how much disk space each file or directory uses?",
         ["df", "free", "du", "mount"], "D",
         "du reports the disk usage of files and directories, whereas df shows space on whole filesystems."),
        ("INTERMEDIATE", "Which command creates an empty file or updates the timestamp of an existing one?",
         ["touch", "mkdir", "newfile", "create"], "A",
         "touch creates a new empty file if it does not exist, or updates the access and modification times."),
        ("INTERMEDIATE", "Which command sorts the lines of text in a file into order?",
         ["grep", "sort", "uniq", "cut"], "B",
         "sort orders lines alphabetically or numerically, and uniq then removes adjacent duplicates."),
        ("ADVANCED", "Which command lists every regular file larger than 100 megabytes under /var/log?",
         ["find /var/log -type f -size +100M", "ls -R /var/log | grep 100M", "du -h /var/log", "locate /var/log 100M"], "A",
         "find with -type f and -size +100M locates regular files over 100 MB anywhere in the tree."),
        ("ADVANCED", "What is the difference between > and >> when redirecting output?",
         ["> overwrites the file while >> appends to it", "> appends while >> overwrites", "> redirects errors while >> redirects normal output", "they behave identically"], "B",
         "The > operator truncates the file and writes fresh output, whereas >> adds to the existing contents."),
        ("ADVANCED", "Which command prints all current environment variables and their values?",
         ["alias", "set-only", "env", "export-all"], "C",
         "env, like printenv, lists every environment variable with its value in the current session."),
        ("ADVANCED", "What happens when a command is followed by an ampersand & ?",
         ["it waits for completion before returning to the prompt", "it runs the command in the background and returns to the prompt immediately", "it cancels the command", "it repeats the command"], "D",
         "A trailing & starts the command as a background job, so the shell returns to the prompt right away."),
        ("ADVANCED", "How do you substitute the output of a command into another command's arguments?",
         ["wrap it in $(command)", "prefix it with a dollar sign like $command", "pipe it to echo", "use a here-document"], "A",
         "Command substitution with $(command) runs the command and places its output into the surrounding line."),
        ("ADVANCED", "Which command identifies the actual type of a file regardless of its extension?",
         ["type", "file", "stat-name", "info"], "B",
         "file inspects the content's magic bytes and reports whether it is text, an image, an archive and so on."),
        ("ADVANCED", "Which shell feature lets you recall and re-run commands you typed earlier?",
         ["alias", "auto-complete", "history", "prompt"], "C",
         "The history mechanism stores prior commands so you can view and re-run them without retyping."),
        ("ADVANCED", "How do you copy an entire directory tree while preserving permissions and timestamps?",
         ["cp --links", "cp -R -l", "cp -r only", "cp -r -p"], "D",
         "cp -r -p recursively copies while preserving mode, ownership and timestamps, and cp -a does even more."),
        ("ADVANCED", "Which redirection directs both standard output and standard error into the same file?",
         ["cmd > file 2>&1", "cmd 2> file", "cmd < file 2>&1", "cmd >> file 2<&1"], "A",
         "The 2>&1 suffix makes file descriptor 2 follow descriptor 1, so stderr goes to the same file as stdout."),
        ("ADVANCED", "Which command shows the path of the executable a command name would run?",
         ["where", "which", "locate", "type-builtin"], "B",
         "which searches the PATH and prints the absolute path of the executable for a command name."),
    ],
    87: [
        ("BEGINNER", "In an ls -l listing, what does the leading character d indicate?",
         ["a directory", "a regular file", "a symbolic link", "a block device"], "A",
         "The first character of the permission string shows the file type, and d stands for directory."),
        ("BEGINNER", "Which permission letter allows reading a file's contents?",
         ["w", "r", "x", "s"], "B",
         "The r (read) permission grants the ability to open and view the contents of a file."),
        ("BEGINNER", "Which permission letter allows modifying a file?",
         ["x", "r", "w", "t"], "C",
         "The w (write) permission grants the ability to change or delete a file's contents."),
        ("BEGINNER", "Which permission letter allows running a file as a program?",
         ["r", "w", "d", "x"], "D",
         "The x (execute) permission is required to run a file as a command or program."),
        ("BEGINNER", "Which command changes the permission bits of a file?",
         ["chmod", "chown", "chgrp", "umask"], "A",
         "chmod (change mode) modifies the read, write and execute permissions of a file or directory."),
        ("BEGINNER", "Which command changes the owner of a file?",
         ["chmod", "chown", "chgrp", "chattr"], "B",
         "chown (change owner) transfers ownership of a file to a specified user."),
        ("BEGINNER", "Which command changes the group associated with a file?",
         ["chown", "chmod", "chgrp", "usermod"], "C",
         "chgrp (change group) changes the group ownership of a file."),
        ("BEGINNER", "In numeric permissions, what value does read permission have?",
         ["1", "2", "8", "4"], "D",
         "Read maps to the numeric value 4 in the octal permission scheme."),
        ("BEGINNER", "In numeric permissions, what value does write permission have?",
         ["2", "1", "4", "8"], "A",
         "Write maps to the numeric value 2 in the octal permission scheme."),
        ("BEGINNER", "In numeric permissions, what value does execute permission have?",
         ["4", "1", "2", "8"], "B",
         "Execute maps to the numeric value 1 in the octal permission scheme."),
        ("INTERMEDIATE", "What permissions result from chmod 755 on a regular file?",
         ["rwxr-xr-x", "rw-r--r--", "r-xr-x---", "rwxrwxrwx"], "A",
         "755 sets rwx for the owner and r-x for the group and others."),
        ("INTERMEDIATE", "What permissions result from chmod 644 on a regular file?",
         ["rwxr--r--", "rw-r--r--", "rw-rw-r--", "r--r--r--"], "B",
         "644 sets rw- for the owner and r-- for group and others, typical for ordinary text files."),
        ("INTERMEDIATE", "What does chmod u+x script.sh do?",
         ["adds execute permission for everyone", "adds execute permission for the group", "adds execute permission for the file owner", "removes execute permission for the owner"], "C",
         "The u target refers to the user (owner), and +x adds the execute bit for them."),
        ("INTERMEDIATE", "What does chmod o-w file do?",
         ["removes write for the owner", "adds write for others", "removes write for the group", "removes write permission for others"], "D",
         "The o target refers to others, and -w removes the write bit for them."),
        ("INTERMEDIATE", "What does chmod a+r file do?",
         ["adds read permission for everyone", "adds read permission for the owner only", "removes read for everyone", "adds write for everyone"], "A",
         "The a target stands for all users, so +r grants read to the user, the group and others."),
        ("INTERMEDIATE", "In the permission string rwxr-xr--, which three classes are shown in order?",
         ["owner, group, others", "root, admin, users", "read, write, execute", "primary, secondary, tertiary"], "B",
         "The nine characters are three triples representing the user, group and others in that order."),
        ("INTERMEDIATE", "What does chown alice:dev file do?",
         ["changes only the group to alice", "changes only the owner to dev", "changes the owner to alice and the group to dev", "removes ownership entirely"], "C",
         "A user:group argument sets both the owner and the group in a single chown command."),
        ("INTERMEDIATE", "What does chmod +x file do when no target letter is given?",
         ["adds execute for the owner only", "adds execute for the group only", "removes execute for everyone", "adds execute for the user, group and others"], "D",
         "Without a target letter the change applies to all classes, so +x grants execute to everyone."),
        ("INTERMEDIATE", "What does the -R option do when used with chmod?",
         ["applies the change recursively through subdirectories", "removes the file", "runs read-only", "reverts to default permissions"], "A",
         "chmod -R recurses into subdirectories and applies the same permission change to everything inside."),
        ("INTERMEDIATE", "Which numeric mode represents the permissions rw------- ?",
         ["700", "600", "644", "640"], "B",
         "600 grants read and write only to the owner and nothing to the group or others."),
        ("ADVANCED", "What does the setuid bit do when set on an executable file?",
         ["runs the program with the file owner's privileges", "makes the file read-only", "locks the file from deletion", "hides the file from ls"], "A",
         "The setuid bit makes the process run with the effective user ID of the file owner, as with /usr/bin/passwd."),
        ("ADVANCED", "With a typical umask of 022, what permissions are newly created directories given?",
         ["rw-r--r--", "rwxr-xr-x", "rwxrwxrwx", "r--r--r--"], "B",
         "umask 022 strips write from the group and others, so directories get rwxr-xr-x (755)."),
        ("ADVANCED", "What is the effect of the sticky bit on a shared directory such as /tmp?",
         ["only root can read files there", "all files inside are encrypted", "a user can only delete files they own even when others can write the directory", "files inside expire automatically"], "C",
         "The sticky bit on a world-writable directory prevents users from deleting files owned by others."),
        ("ADVANCED", "What is the numeric value used to set the setuid bit, as in chmod 4755?",
         ["1000", "2000", "6000", "4000"], "D",
         "Setuid is encoded as 4000, so chmod 4755 combines the setuid bit with the normal 755 permissions."),
        ("ADVANCED", "Why does /etc/shadow normally have no read or write permission for normal users?",
         ["it stores hashed password data that must not be readable by ordinary users", "it is a temporary cache", "it contains only boot configuration", "it must be kept empty for security"], "A",
         "The shadow file holds password hashes, so restricting access prevents offline password cracking."),
        ("ADVANCED", "What happens when the setgid bit is set on a directory?",
         ["new files inherit the directory's group instead of the creator's", "new files become world-writable", "only the owner can create files", "files are deleted automatically after use"], "B",
         "With setgid on a directory, files created inside it belong to the directory's group, which helps team directories."),
        ("ADVANCED", "What can a user do in a directory where they have only execute (x) permission?",
         ["list the directory contents", "read every file inside", "traverse into it if they know a filename, but not list its entries", "delete files inside it"], "C",
         "Execute-only on a directory allows entering it by name but blocks listing its entries."),
        ("ADVANCED", "Which command sets the default permission mask applied to every file a user creates?",
         ["chmod", "chattr", "chown", "umask"], "D",
         "umask sets the default permissions for new files by subtracting its bits from the base mode."),
        ("ADVANCED", "What does chattr +i config.conf do?",
         ["makes the file immutable so even the owner cannot modify or delete it", "marks the file as index-only", "adds interactive mode", "sets read-only for others only"], "A",
         "The immutable attribute prevents any modification, deletion or renaming until it is removed with chattr -i."),
        ("ADVANCED", "Why would an administrator use POSIX ACLs on a file instead of only chmod?",
         ["to compress the file", "to grant different permissions to many named users and groups beyond owner/group/others", "to speed up disk access", "to hide the file from ls"], "B",
         "ACLs extend the three-class model by assigning specific permissions to many named users and groups."),
    ],
    88: [
        ("BEGINNER", "Which line at the top of a script tells the kernel to run it with the Bash interpreter?",
         ["#!/bin/bash", "#include bash", "%bash", "declare bash"], "A",
         "The shebang #!/bin/bash instructs the kernel to execute the script using /bin/bash."),
        ("BEGINNER", "What must you do before you can run a script by name?",
         ["rename it to end in .sh", "make it executable with chmod +x", "compile it", "move it to /tmp"], "B",
         "chmod +x adds the execute bit so the kernel permits the file to be run directly."),
        ("BEGINNER", "What does a line beginning with # mean inside a shell script?",
         ["an error", "a command to execute", "a comment that is ignored by the shell", "a variable declaration"], "C",
         "Lines starting with # are comments and are ignored when the script runs."),
        ("BEGINNER", "Which of the following correctly declares a variable in Bash?",
         ["set x = 5", "int x = 5", "var x 5", "x=5"], "D",
         "A variable is assigned with name=value and no spaces around the equals sign."),
        ("BEGINNER", "How do you read the value of a variable named count inside a script?",
         ["echo $count", "echo count", "read count", "print count"], "A",
         "Prefixing the variable name with a dollar sign expands it to its current value."),
        ("BEGINNER", "Which builtin command prints text to the terminal?",
         ["print", "echo", "printf-only", "output"], "B",
         "echo writes its arguments to standard output, usually followed by a newline."),
        ("BEGINNER", "Which builtin command reads a line of input from the user into a variable?",
         ["input", "get", "read", "scan"], "C",
         "read captures a line from standard input and stores it in the named variable."),
        ("BEGINNER", "Which comparison operator inside a [ ] test checks whether two strings are equal?",
         ["-eq", "-ne", "-f", "="], "D",
         "Within test brackets, = compares strings for equality, while -eq compares numbers."),
        ("BEGINNER", "Which loop repeats a block once for each item in a list such as 1 2 3?",
         ["for", "while", "until", "repeat"], "A",
         "A for loop iterates over each word in the given list, running its body for every item."),
        ("BEGINNER", "Which builtin ends a script immediately and returns a status code?",
         ["return", "exit", "stop", "quit"], "B",
         "exit terminates the script and passes its numeric argument back as the exit status."),
        ("INTERMEDIATE", "Which special variable holds the exit status of the last executed command?",
         ["$?", "$#", "$!", "$*"], "A",
         "$? expands to the exit code of the most recent command, with 0 usually meaning success."),
        ("INTERMEDIATE", "Which special variable contains the number of positional parameters passed to a script?",
         ["$@", "$#", "$?", "$$"], "B",
         "$# holds the count of command-line arguments passed to the script or function."),
        ("INTERMEDIATE", "Which special variable refers to all of the positional parameters of a script?",
         ["$0", "$@", "$!", "$?"], "C",
         "$@ expands to all positional parameters, each treated as a separately quoted argument."),
        ("INTERMEDIATE", "How does $@ differ from $* when arguments contain spaces?",
         ["they are identical", "$* is invalid syntax", "$@ only counts arguments", "$@ preserves each argument separately while $* joins them into one string"], "D",
         "$@ keeps every argument distinct, whereas $* merges all arguments into a single word."),
        ("INTERMEDIATE", "What does the construct $(ls) do inside a script?",
         ["runs ls and substitutes its output into the command line", "lists files in the background", "defines a function named ls", "prints the variable ls"], "A",
         "Command substitution executes the command and replaces the whole construct with its output."),
        ("INTERMEDIATE", "Which loop keeps running as long as its condition remains true?",
         ["for", "while", "case", "select"], "B",
         "A while loop repeats its body while the test command exits successfully."),
        ("INTERMEDIATE", "What effect does set -e at the top of a script have?",
         ["makes the script echo every command", "disables comments", "exits the script immediately if any command returns a non-zero status", "ignores all arguments"], "C",
         "set -e turns on errexit, so the script aborts on the first failing command instead of continuing."),
        ("INTERMEDIATE", "Which test option checks whether a given path is a regular file?",
         ["test -d", "test -x", "test -r", "test -f"], "D",
         "test -f returns true only when the argument exists and is a regular file, not a directory."),
        ("INTERMEDIATE", "Which test option checks whether a given path is a directory?",
         ["test -d", "test -f", "test -s", "test -e"], "A",
         "test -d succeeds only when the argument exists and is a directory."),
        ("INTERMEDIATE", "Which syntax correctly defines a function named greet in Bash?",
         ["function = greet()", "greet() { echo hi; }", "def greet:", "greet => { }"], "B",
         "A function is defined with the name, parentheses and a brace-delimited body, such as greet() { ... }."),
        ("ADVANCED", "What does a case statement do in a shell script?",
         ["matches a value against multiple patterns and runs the first matching branch", "loops over a range of numbers", "defines a new variable", "sorts a list of arguments"], "A",
         "case compares a word to several patterns and executes the statements of the first pattern that matches."),
        ("ADVANCED", "What does trap 'cleanup' EXIT do in a script?",
         ["runs the cleanup command every second", "runs cleanup whenever the script exits", "prevents the script from exiting", "renames the script"], "B",
         "trap registers a handler that runs when the named signal or the EXIT event occurs."),
        ("ADVANCED", "How do you run a long command so it keeps running after the terminal session closes?",
         ["nohup command", "fg command", "kill -TERM command", "background it with disown only"], "C",
         "nohup ignores the hangup signal so the command survives the terminal closing."),
        ("ADVANCED", "What does the special variable $RANDOM provide in Bash?",
         ["the current process id", "the last exit status", "the number of arguments", "a random integer between 0 and 32767"], "D",
         "$RANDOM expands to a pseudo-random integer in the range 0 through 32767."),
        ("ADVANCED", "What does exec replace the current shell process with a new command mean?",
         ["it is a syntax error", "the shell is replaced by the given program and control never returns", "the command runs in a subshell", "input is read from a file"], "B",
         "exec replaces the current shell process image with the specified program, so control never returns."),
        ("ADVANCED", "Which command marks an existing variable so it can no longer be changed?",
         ["export var", "readonly var", "declare -i var", "local var"], "B",
         "readonly makes a variable immutable, so any later attempt to assign it fails."),
        ("ADVANCED", "What does ${var:-default} expand to when var is unset or empty?",
         ["an error", "nothing at all", "the word default", "the value of var regardless of whether it is set"], "C",
         "The :- operator substitutes the fallback text only when the variable is unset or empty."),
        ("ADVANCED", "What does ${path##*/} produce from the path /home/user/report.txt ?",
         ["/home/user", "report.txt", "/home/user/report.txt", "home"], "D",
         "The ##*/ pattern strips the longest prefix ending in a slash, leaving only the final component."),
        ("ADVANCED", "Why is set -u recommended in robust scripts?",
         ["it makes the script fail when an unset variable is referenced", "it uppercases all output", "it prevents background jobs", "it disables filename globbing"], "A",
         "set -u (nounset) aborts the script if a referenced variable has not been defined, catching typos."),
        ("ADVANCED", "Which feature does the [[ ]] test offer that the single-bracket [ ] does not?",
         ["only numeric comparisons", "regular-expression matching with =~ and && || operators", "automatic backgrounding", "variable assignment"], "B",
         "The extended [[ ]] supports regex matching with =~ and boolean && and || logic."),
    ],
    89: [
        ("BEGINNER", "Which command prints a snapshot of the currently running processes?",
         ["ps", "ls", "mkdir", "du"], "A",
         "ps reports the current processes and their PIDs, CPU and memory usage at the moment it runs."),
        ("BEGINNER", "What does PID stand for?",
         ["program installation date", "process identifier", "primary input device", "physical interface driver"], "B",
         "PID is the process identifier, a unique number assigned to each running process."),
        ("BEGINNER", "Which command shows processes updating continuously in real time?",
         ["ps", "cat", "top", "tree"], "C",
         "top refreshes its process display every few seconds so you can watch activity as it changes."),
        ("BEGINNER", "Which command sends a signal to a process using its PID?",
         ["kill", "chmod", "mv", "echo"], "D",
         "kill delivers a signal, by default SIGTERM, to the process identified by its PID."),
        ("BEGINNER", "Which signal forcefully kills a process and cannot be caught or ignored?",
         ["SIGKILL (9)", "SIGTERM (15)", "SIGHUP (1)", "SIGINT (2)"], "A",
         "SIGKILL is handled directly by the kernel and terminates the process immediately without cleanup."),
        ("BEGINNER", "Which signal requests a process to terminate gracefully so it can clean up?",
         ["SIGKILL", "SIGTERM", "SIGCHLD", "SIGSTOP"], "B",
         "SIGTERM asks the process to exit cleanly so it can close files and release resources."),
        ("BEGINNER", "What does appending & to a command do?",
         ["runs it in the foreground", "deletes it", "runs it as a background job", "locks it"], "C",
         "A trailing ampersand launches the command in the background, freeing the terminal for other work."),
        ("BEGINNER", "Which builtin lists the background jobs of the current shell?",
         ["jobs", "list", "ps bg", "tasks"], "D",
         "jobs shows the running and suspended background jobs belonging to the current shell session."),
        ("BEGINNER", "What is a daemon process?",
         ["a background service that runs without user interaction", "a computer virus", "an error log file", "a temporary cache file"], "A",
         "Daemons are long-lived background processes that provide services such as web serving or logging."),
        ("BEGINNER", "Which process is normally the first started at boot and becomes the parent of all other processes?",
         ["bash", "systemd (or init)", "cron", "login"], "B",
         "On modern Linux systems systemd is PID 1, the ancestor of all other processes."),
        ("INTERMEDIATE", "What does kill -9 1234 do?",
         ["sends SIGKILL to PID 1234, terminating it immediately", "pauses PID 1234", "renames PID 1234", "prints PID 1234"], "A",
         "The -9 option sends SIGKILL, which force-terminates the process without giving it a chance to clean up."),
        ("INTERMEDIATE", "What does ps aux display?",
         ["only the current user's foreground jobs", "all processes from all users with detailed columns", "only systemd services", "a live updating screen"], "B",
         "With the a, u and x options, ps shows every user's processes in a detailed format including CPU and memory."),
        ("INTERMEDIATE", "How does SIGTERM differ from SIGKILL?",
         ["SIGTERM is uncatchable", "they are identical", "SIGTERM allows cleanup while SIGKILL forces immediate termination", "SIGKILL pauses the process"], "C",
         "SIGTERM can be caught so a program can save state, whereas SIGKILL ends the process at once."),
        ("INTERMEDIATE", "What does the command kill %2 do?",
         ["kills the process with PID 2", "sends a signal to job number 2", "lists job 2", "reloads job 2"], "D",
         "The %n form refers to the nth job of the shell, so kill %2 signals that job."),
        ("INTERMEDIATE", "What does kill -STOP 1234 do?",
         ["pauses the process while keeping its memory intact", "deletes the process", "restarts the process", "changes its priority"], "A",
         "SIGSTOP suspends execution of the process, which can later be resumed with SIGCONT."),
        ("INTERMEDIATE", "What does jobs -l show that plain jobs does not?",
         ["the exit statuses", "the PID of each background job", "the command history", "the memory usage"], "B",
         "jobs -l adds the process IDs to the usual job listings."),
        ("INTERMEDIATE", "What does the builtin fg do?",
         ["forgets a job", "sends a job to the background", "brings a background job into the foreground", "terminates a job"], "C",
         "fg resumes a suspended or background job so it runs interactively in the foreground."),
        ("INTERMEDIATE", "What is a zombie process?",
         ["a process that is running slowly", "a process that cannot be killed", "a process that has terminated but whose parent has not yet collected its exit status", "a process waiting for input"], "D",
         "A zombie is a finished process whose entry stays in the process table until its parent calls wait() to reap it."),
        ("INTERMEDIATE", "What does the nice command do?",
         ["starts a program with an adjusted CPU priority", "polishes the terminal output", "cleans up zombie processes", "counts processes"], "A",
         "nice launches a process with a lower priority (higher niceness) so it yields the CPU to others."),
        ("INTERMEDIATE", "What does renice do?",
         ["deletes a running process", "changes the priority of a process that is already running", "renames a process", "restarts a process"], "B",
         "renice adjusts the niceness of a running process, and lowering it requires appropriate privileges."),
        ("ADVANCED", "In top output, what does the load average indicate?",
         ["the average number of processes ready to run or waiting to run over 1, 5 and 15 minutes", "the total memory in megabytes", "the number of zombies", "the disk input rate"], "A",
         "Load average counts runnable and uninterruptible processes, averaged over one, five and fifteen minutes."),
        ("ADVANCED", "What does sending SIGHUP (kill -HUP) to a daemon commonly achieve?",
         ["forces it to crash", "tells it to reload its configuration and keep running", "reboots the machine", "logs the current user out"], "B",
         "Many daemons treat SIGHUP as a request to reread configuration files and reopen log files."),
        ("ADVANCED", "What is a process group in Linux?",
         ["a group of processes all sharing one priority", "a collection of processes that can be signaled together, such as a pipeline", "a set of systemd unit files", "a list of daemons"], "C",
         "A process group lets the kernel and the shell send signals to every member at once, as a pipeline does."),
        ("ADVANCED", "Which command finds the PID of a process purely by its name?",
         ["ps find", "pgrep", "pid", "top -n"], "D",
         "pgrep searches the process table and prints the PIDs of processes matching the given name."),
        ("ADVANCED", "What does ps -ef provide?",
         ["a full listing of every process including its parent PID and command line", "a live refresh of processes", "only foreground jobs", "a process tree for one user"], "A",
         "The -e and -f options show every process with a detailed column set including PPID and the full command."),
        ("ADVANCED", "A script launches several jobs with & and then runs wait. What does wait do?",
         ["terminates all the jobs", "blocks until all background jobs finish before continuing", "pauses the script forever", "prints the job numbers"], "B",
         "wait pauses the script until every launched background job has completed, collecting their exit statuses."),
        ("ADVANCED", "What is a fork bomb?",
         ["a script that restarts itself slowly", "a process that repeatedly forks copies of itself until the system runs out of processes", "a program that fills the disk with files", "a network attack on port 22"], "C",
         "A fork bomb rapidly creates child processes, exhausting the process table and making the system unusable."),
        ("ADVANCED", "What does htop provide that plain top does not?",
         ["load average only", "a smaller process list", "interactive scrolling, a tree view and mouse support", "no color output"], "D",
         "htop offers an interactive scrollable display, a hierarchical tree view, colors and mouse interaction."),
        ("ADVANCED", "What is SIGCHLD used for?",
         ["notifying a parent when one of its children has stopped or terminated", "shutting down the machine", "resuming a paused process", "suspending a child"], "A",
         "The kernel sends SIGCHLD to a parent when a child changes state so the parent can call wait() and reap it."),
        ("ADVANCED", "Which command shows the current status of a service managed by systemd?",
         ["systemctl status service", "service --info", "init status", "ps service"], "B",
         "systemctl status service reports whether the unit is active, its main PID and its recent logs."),
    ],
    90: [
        ("BEGINNER", "Which command tests whether a remote host is reachable by sending ICMP echo packets?",
         ["ping", "cat", "ls", "mkdir"], "A",
         "ping sends ICMP echo requests and reports whether replies come back and how fast."),
        ("BEGINNER", "Which command displays the IP addresses assigned to the machine's network interfaces?",
         ["ip addr", "ls ip", "chmod", "hostname"], "B",
         "ip addr, like ifconfig, lists each interface and the IPv4 and IPv6 addresses configured on it."),
        ("BEGINNER", "Which command downloads a file from the web using the HTTP protocol?",
         ["cp", "mv", "wget", "tar"], "C",
         "wget retrieves remote files over HTTP, HTTPS or FTP and saves them locally."),
        ("BEGINNER", "Which command shows the system's IP routing table?",
         ["ip route", "echo", "lsmod", "uptime"], "D",
         "ip route, like the older route command, lists the network routes the kernel uses to forward packets."),
        ("BEGINNER", "Which command resolves a hostname into an IP address using DNS?",
         ["nslookup", "ping only", "ip addr", "hostname"], "A",
         "nslookup queries a DNS server to translate a domain name into its address records."),
        ("BEGINNER", "Which package manager is used by Debian and Ubuntu systems?",
         ["dnf", "apt", "pacman", "zypper"], "B",
         "apt (Advanced Package Tool) is the package manager used on Debian-derived distributions."),
        ("BEGINNER", "Which package manager is the default on modern Fedora and RHEL systems?",
         ["apt", "dpkg", "dnf", "rpm-only"], "C",
         "dnf is the default package manager on recent Fedora and RHEL releases, replacing yum."),
        ("BEGINNER", "Which command installs a new package such as curl on a Debian-based system?",
         ["apt install curl", "pip install curl", "dnf install curl", "tar curl"], "D",
         "apt install resolves dependencies and installs the named package from the configured repositories."),
        ("BEGINNER", "Which command refreshes the list of available packages and their versions?",
         ["apt update", "apt upgrade", "apt install", "apt remove"], "A",
         "apt update downloads the latest package index so apt knows which versions are available."),
        ("BEGINNER", "Which command upgrades all currently installed packages on a Debian system?",
         ["apt update", "apt upgrade", "apt search", "apt list"], "B",
         "apt upgrade installs newer versions of the installed packages using the refreshed index."),
        ("INTERMEDIATE", "What does apt upgrade do compared with apt update?",
         ["installs newer versions of installed packages, while update only refreshes the index", "is identical to update", "removes old packages", "reinstalls every package"], "A",
         "apt update refreshes the package index, and apt upgrade then applies the available upgrades to installed packages."),
        ("INTERMEDIATE", "What does ping -c 4 8.8.8.8 do?",
         ["pings forever", "sends exactly four ICMP requests and then stops", "sends four bytes of data", "pings four packets per second"], "B",
         "The -c option limits the number of echo requests, so ping stops after the four replies."),
        ("INTERMEDIATE", "What does curl -O https://example.com/file.zip do?",
         ["prints headers only", "uploads file.zip", "downloads the file and saves it with its remote filename", "opens an interactive shell"], "C",
         "curl -O downloads the URL and writes it to a local file named after the remote file."),
        ("INTERMEDIATE", "What does the command ip a summarize?",
         ["DNS settings", "the routing table", "active network sockets", "all network interfaces and their addresses"], "D",
         "ip a is shorthand for ip address and shows each interface with its configured addresses and state."),
        ("INTERMEDIATE", "What does ss -t list?",
         ["only TCP sockets", "only UDP sockets", "only DNS records", "only routed interfaces"], "A",
         "ss -t filters its socket listing to TCP connections."),
        ("INTERMEDIATE", "What does apt remove do to an installed package?",
         ["deletes it and all its configuration files", "removes it but keeps its configuration files", "only disables it", "downgrades it"], "B",
         "apt remove uninstalls the package's binaries while preserving its configuration files."),
        ("INTERMEDIATE", "What does apt purge do that apt remove does not?",
         ["removes dependent packages", "also deletes the package's configuration files", "keeps the log files", "reinstalls the package"], "C",
         "apt purge removes the package and additionally deletes its configuration files from the system."),
        ("INTERMEDIATE", "What does wget -c do when a download is interrupted?",
         ["cancels the file", "restarts from scratch", "resumes the download from where it stopped", "deletes the partial file"], "D",
         "The -c (continue) option makes wget resume a partial download from the point where it stopped."),
        ("INTERMEDIATE", "Which command queries the DNS records for a domain such as example.com?",
         ["nslookup example.com", "ip example.com", "route example.com", "ping example.com"], "A",
         "nslookup sends DNS queries and prints the returned address or MX records for the name."),
        ("INTERMEDIATE", "Which command shows the ports a machine is currently listening on?",
         ["ss -l", "ip -p", "ls /dev", "ping -l"], "B",
         "ss -l, like netstat -l, lists sockets in the listening state, showing open ports and their services."),
        ("ADVANCED", "What does apt-get dist-upgrade do beyond a regular upgrade?",
         ["also installs or removes packages to satisfy changed dependencies", "downgrades every package", "only updates the kernel", "removes all unused packages"], "A",
         "dist-upgrade handles dependency changes intelligently, installing and removing packages as needed."),
        ("ADVANCED", "What is a package repository?",
         ["a local backup directory", "a server or collection that provides packages and metadata for the package manager", "a directory of system logs", "a firewall rule"], "B",
         "Repositories publish packages and index metadata so tools like apt can discover, download and update software."),
        ("ADVANCED", "What does dpkg -i package.deb do?",
         ["removes a package", "searches for a package", "installs a package directly from a .deb file without dependency resolution", "downgrades a package"], "C",
         "dpkg -i installs the given .deb file at the low level, applying dependencies only if they are already present."),
        ("ADVANCED", "What does rpm -ivh package.rpm do?",
         ["removes an rpm", "queries an rpm", "upgrades all rpms", "installs the rpm with verbose and hash progress output"], "D",
         "rpm -ivh installs the package verbosely with progress hashes, short for install verbose hash."),
        ("ADVANCED", "What does SSH local port forwarding achieve?",
         ["tunnels traffic from a local port through the SSH connection to a remote destination", "blocks local ports", "shares files between machines", "copies SSH keys"], "A",
         "Local forwarding binds a port on the local machine and relays its traffic through the encrypted SSH tunnel."),
        ("ADVANCED", "What is the purpose of the file /etc/resolv.conf?",
         ["to list network interfaces", "to configure the DNS resolver with name servers and search domains", "to set the hostname", "to store firewall rules"], "B",
         "resolv.conf tells the resolver which nameservers to query and which search domains to append."),
        ("ADVANCED", "What does the iptables tool manage?",
         ["DNS resolution", "package downloads", "the kernel's firewall rules and packet filtering", "process priorities"], "C",
         "iptables configures the netfilter tables that filter, forward and translate packets in the kernel."),
        ("ADVANCED", "What does ss -tnlp display?",
         ["DNS servers", "routing entries", "ARP tables", "listening TCP sockets together with the owning process"], "D",
         "ss -tnlp shows TCP sockets in numeric form, including listening ports and the PID of each bound process."),
        ("ADVANCED", "What is the main difference between apt and dpkg?",
         ["dpkg is a low-level tool that does not resolve dependencies, while apt manages dependency resolution", "apt is older than dpkg", "dpkg only removes packages", "they are identical"], "A",
         "dpkg installs and removes individual .deb files, whereas apt consults repositories and resolves dependencies."),
        ("ADVANCED", "What does ufw provide to an administrator?",
         ["a graphical package browser", "a simplified interface for configuring firewall rules", "a DNS server", "a load balancer"], "B",
         "ufw (uncomplicated firewall) offers an easy front end over iptables for opening and closing ports."),
    ],
}
