# -*- coding: utf-8 -*-
"""
Question bank for subject 37: CORE102 - Discrete Mathematics.
Category: Core Computer Science & Emerging Technologies.

Topics:
  181: Sets & Logic
  182: Relations & Functions
  183: Combinatorics
  184: Graph Theory
  185: Number Theory & Algebra

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    181: [
        ("BEGINNER", "Which symbol denotes the empty set?",
         ["{}", "∈", "∪", "∩"], "A",
         "The empty set is written as {} and contains no elements."),
        ("BEGINNER", "Which symbol represents the union of two sets?",
         ["∩", "∪", "∈", "⊆"], "B",
         "The ∪ symbol collects all elements of both sets into one set."),
        ("BEGINNER", "What is A ∩ ∅ for any set A?",
         ["A", "U", "∅", "A'"], "C",
         "Intersecting any set with the empty set leaves no elements, so the result is empty."),
        ("BEGINNER", "Which symbol means 'is an element of'?",
         ["⊂", "⊆", "∉", "∈"], "D",
         "The ∈ symbol states that an object belongs to a set."),
        ("BEGINNER", "In a Venn diagram, the region where two circles overlap represents:",
         ["the intersection", "the union", "the complement", "the difference"], "A",
         "The overlapping region contains elements common to both sets, which is the intersection."),
        ("BEGINNER", "Which law states that A ∩ (B ∪ C) = (A ∩ B) ∪ (A ∩ C)?",
         ["De Morgan's law", "the distributive law", "the commutative law", "the associative law"], "B",
         "Distributing intersection over union is the distributive law."),
        ("BEGINNER", "Within a universal set U, the complement of A consists of:",
         ["elements of A", "elements common to A and U", "all elements of U that are not in A", "the empty set"], "C",
         "The complement A' holds exactly the members of U absent from A."),
        ("BEGINNER", "If A = {1, 2, 3} and B = {3, 4}, what is A ∪ B?",
         ["{1, 2}", "{3}", "{1, 2, 3, 4}", "{1, 2, 3, 4, 3}"], "D",
         "The union gathers every element from both sets without repetition, giving {1, 2, 3, 4}."),
        ("BEGINNER", "If A = {1, 2, 3} and B = {3, 4}, what is A ∩ B?",
         ["{1, 2}", "{3}", "{1, 2, 3, 4}", "{}"], "A",
         "Only the element 3 appears in both sets, so the intersection is {3}."),
        ("BEGINNER", "Which statement about a universal set is true?",
         ["it contains every set under discussion", "it is always empty", "it contains only numbers", "it is the complement of everything"], "B",
         "The universal set U includes all objects considered in a given problem."),
        ("INTERMEDIATE", "If |A| = 5 and |B| = 3 with A and B disjoint, what is |A ∪ B|?",
         ["8", "2", "15", "5"], "A",
         "For disjoint sets the sizes add directly, so |A ∪ B| = 5 + 3 = 8."),
        ("INTERMEDIATE", "In a class of 30 students, 18 play football, 12 play cricket and 5 play both. How many play neither?",
         ["10", "5", "8", "15"], "B",
         "The union is 18 + 12 - 5 = 25, leaving 30 - 25 = 5 students who play neither."),
        ("INTERMEDIATE", "Which of the following propositions is a tautology?",
         ["p ∧ ¬p", "p → q", "p ∨ ¬p", "p ∧ q"], "C",
         "By the law of the excluded middle, p ∨ ¬p is true for every truth value of p."),
        ("INTERMEDIATE", "What is the truth value of p → q when p is false and q is true?",
         ["false", "undefined", "0", "true"], "D",
         "A conditional with a false antecedent is vacuously true."),
        ("INTERMEDIATE", "Which of the following is the negation of the statement 'All students passed'?",
         ["At least one student did not pass", "No student passed", "All students failed", "Some students passed"], "A",
         "Negating a universal claim asserts the existence of a counterexample."),
        ("INTERMEDIATE", "The expression ¬(p ∧ q) is logically equivalent to:",
         ["¬p ∧ ¬q", "¬p ∨ ¬q", "p ∨ q", "¬p → q"], "B",
         "De Morgan's law turns the negation of a conjunction into a disjunction of negations."),
        ("INTERMEDIATE", "A set has 4 elements. How many subsets does it have?",
         ["8", "12", "16", "32"], "C",
         "A set with n elements has 2^n subsets, so 2^4 = 16."),
        ("INTERMEDIATE", "If p is true and q is false, what is the value of p ↔ q?",
         ["true", "undefined", "cannot be determined", "false"], "D",
         "A biconditional is true only when both propositions have the same truth value."),
        ("INTERMEDIATE", "If |A ∪ B| = 12, |A| = 8 and |B| = 7, what is |A ∩ B|?",
         ["3", "5", "15", "27"], "A",
         "By inclusion-exclusion, |A ∩ B| = 8 + 7 - 12 = 3."),
        ("INTERMEDIATE", "Given A = {x | x is a positive integer less than 6} and B = {2, 4, 6}, what is A ∩ B?",
         ["{2, 4}", "{2, 4, 6}", "{1, 3, 5}", "{6}"], "B",
         "A is {1, 2, 3, 4, 5}, and its intersection with B contains 2 and 4."),
        ("ADVANCED", "An access control policy grants entry only when the card is valid AND the PIN matches. Which expression models this rule?",
         ["p ∧ q", "p ∨ q", "¬p → q", "p ⊕ q"], "A",
         "Both conditions must hold, which is the logical conjunction p ∧ q."),
        ("ADVANCED", "A program validates input with if (x > 0 && x < 10). Which set of values is accepted?",
         ["(0, 10)", "[0, 10]", "(0, 10]", "(0, 100)"], "B",
         "Both inequalities are strict, so x lies in the open interval (0, 10)."),
        ("ADVANCED", "An email is flagged as spam if it matches filter F OR contains known virus V. Which form describes the flag?",
         ["F ∧ V", "F ∨ V", "¬F", "F → V"], "C",
         "Either condition alone triggers the flag, which is the inclusive OR."),
        ("ADVANCED", "Which statement is logically equivalent to 'If it rains, the match is cancelled'?",
         ["If it does not rain, the match is not cancelled", "If the match is cancelled, it rained", "It rained or the match was cancelled", "If the match is not cancelled, it did not rain"], "D",
         "The contrapositive of p → q is ¬q → ¬p, which is logically equivalent."),
        ("ADVANCED", "In a digital circuit, two switches wired in series conduct current only when both are closed. This implements which logical gate?",
         ["AND", "OR", "NAND", "XOR"], "A",
         "Series wiring requires both switches to close, matching the AND behaviour."),
        ("ADVANCED", "How many rows must a full truth table for n boolean variables have?",
         ["n", "2^n", "n^2", "2n"], "B",
         "Each variable has two possible values, giving 2^n distinct combinations."),
        ("ADVANCED", "A system must be in exactly one of the states ON or OFF at any moment. The relation between the two conditions is that they are:",
         ["complements", "equal", "independent", "implied by each other"], "C",
         "Exactly one of them holding at a time makes the conditions logical complements."),
        ("ADVANCED", "Which set identity simplifies A ∩ (A ∪ B)?",
         ["identity law", "domination law", "involution law", "absorption law"], "D",
         "By the absorption law, A ∩ (A ∪ B) reduces to A."),
        ("ADVANCED", "A biometric lock opens when the fingerprint OR the face matches, so at least one match suffices. This is best modelled with which operator?",
         ["OR", "AND", "NOT", "XOR"], "A",
         "Requiring at least one match is exactly the inclusive OR."),
        ("ADVANCED", "A service stays up while at least one of two independent detectors survives. Which expression models the service being alive?",
         ["F1 ∨ F2", "F1 ∧ F2", "¬(F1 ∨ F2)", "F1 → F2"], "B",
         "At least one survivor is needed, so the survival condition is F1 ∨ F2."),
    ],
    182: [
        ("BEGINNER", "A relation R from set A to set B is best defined as:",
         ["a subset of A × B", "a subset of A", "a set of single elements of B", "the complement of A"], "A",
         "A relation is a set of ordered pairs drawn from the cartesian product A × B."),
        ("BEGINNER", "Which operation builds the set of all ordered pairs (a, b) with a in A and b in B?",
         ["A ∪ B", "A × B", "A ∩ B", "A - B"], "B",
         "The cartesian product A × B contains every ordered pair whose first part is from A and second from B."),
        ("BEGINNER", "A relation R on a set is reflexive if:",
         ["no element relates to itself", "every pair (a, b) also has (b, a)", "every element a satisfies aRa", "the relation contains no pairs"], "C",
         "Reflexivity requires that every element relates to itself."),
        ("BEGINNER", "A function from set A to set B assigns to each element of A:",
         ["several elements of B", "at least two elements of B", "no elements of B", "exactly one element of B"], "D",
         "A function must pair each input with exactly one well-defined output."),
        ("BEGINNER", "Which diagram represents a valid function?",
         ["every input has exactly one outgoing arrow", "an input has two outgoing arrows", "an input has no outgoing arrow", "arrows point only to a single input"], "A",
         "Each input mapping to exactly one output is the defining property of a function."),
        ("BEGINNER", "The set of all first components of the ordered pairs of a function is called its:",
         ["range", "domain", "codomain", "inverse"], "B",
         "The domain is the set of inputs, the first components of the ordered pairs."),
        ("BEGINNER", "The set of all actual output values produced by a function is its:",
         ["domain", "codomain", "range", "relation"], "C",
         "The range is the set of values the function actually produces."),
        ("BEGINNER", "If a function f maps x to y, which notation is standard?",
         ["f → y", "x = f", "y ∘ x", "f(x) = y"], "D",
         "The standard notation f(x) = y states that f applied to x yields y."),
        ("BEGINNER", "Which of the following is an example of a relation that is NOT a function?",
         ["one input mapping to two outputs", "every input mapping to one output", "a relation with a single pair", "a mapping of numbers to numbers"], "A",
         "A single input producing two outputs violates the function definition."),
        ("BEGINNER", "For a function f: A → B, the set B is called the:",
         ["domain", "codomain", "range", "preimage"], "B",
         "The codomain B is the set in which all outputs are declared to lie."),
        ("INTERMEDIATE", "Given f(x) = 2x + 3, what is f(4)?",
         ["11", "9", "14", "24"], "A",
         "Substituting 4 gives 2(4) + 3 = 11."),
        ("INTERMEDIATE", "Given g(x) = x^2 + 1, what is g(-3)?",
         ["-8", "10", "9", "7"], "B",
         "(-3)^2 + 1 = 9 + 1 = 10."),
        ("INTERMEDIATE", "Given h(x) = x + 2 and k(x) = 3x, what is h(k(2))?",
         ["6", "12", "8", "10"], "C",
         "k(2) = 6 and then h(6) = 6 + 2 = 8."),
        ("INTERMEDIATE", "Which property must a relation satisfy to be symmetric?",
         ["if aRb and bRc then aRc", "aRa for all a", "aRb only when a equals b", "if aRb then bRa"], "D",
         "Symmetry requires that whenever a is related to b, b is also related to a."),
        ("INTERMEDIATE", "A relation that is reflexive, symmetric and transitive is called:",
         ["an equivalence relation", "a partial order", "a function", "an antisymmetric relation"], "A",
         "Together the three properties define an equivalence relation."),
        ("INTERMEDIATE", "The equivalence classes of an equivalence relation on a set:",
         ["overlap partially", "partition the set", "are all empty", "form the codomain"], "B",
         "Equivalence classes are disjoint and cover the whole set, forming a partition."),
        ("INTERMEDIATE", "For f: R → R given by f(x) = x^3, which statement is true?",
         ["it is not one-to-one", "it is not onto", "it is a bijection", "it is constant"], "C",
         "The cube function is both one-to-one and onto on the reals, hence a bijection."),
        ("INTERMEDIATE", "If a function is one-to-one but not onto, what can be said about its inverse?",
         ["the inverse is defined everywhere on B", "the inverse maps to two values", "the inverse does not exist", "the inverse is defined on the range of f"], "D",
         "An injective function can be inverted on its range, giving an inverse on the range only."),
        ("INTERMEDIATE", "The inverse of f(x) = x + 5 is:",
         ["f^-1(x) = x - 5", "f^-1(x) = 5 - x", "f^-1(x) = x + 5", "f^-1(x) = 5x"], "A",
         "Solving y = x + 5 for x gives x = y - 5."),
        ("INTERMEDIATE", "The composition f ∘ g means:",
         ["apply f first and then g", "apply g first and then f", "add the outputs of f and g", "multiply the outputs of f and g"], "B",
         "In f ∘ g, the function g is applied first and then f is applied to its result."),
        ("ADVANCED", "A primary key assigns a unique identifier to every database record. As a relation property, it behaves like:",
         ["a function", "an equivalence class", "a partial order", "a cartesian product"], "A",
         "A primary key assigns exactly one identifier per record, matching the function rule."),
        ("ADVANCED", "A hashing function h(x) = x^2 mod p is used for passwords. The security weakness is that h is:",
         ["one-to-one", "not injective, so distinct inputs can collide", "always injective", "a bijection"], "B",
         "Many inputs produce the same square modulo p, so collisions are unavoidable."),
        ("ADVANCED", "Task A may run before task B, and the relation is reflexive, antisymmetric and transitive. This relation is:",
         ["an equivalence relation", "a function", "a partial order", "a bijection"], "C",
         "Reflexive, antisymmetric and transitive relations are partial orders."),
        ("ADVANCED", "On the integers, aRb if a - b is even. This relation:",
         ["is not reflexive", "is only symmetric", "is only transitive", "is an equivalence relation"], "D",
         "Parity of the difference is reflexive, symmetric and transitive, making it an equivalence relation."),
        ("ADVANCED", "A cache maps each memory address to exactly one cache line. This mapping is best modelled as:",
         ["a function from addresses to lines", "a symmetric relation", "a partial order", "an equivalence class"], "A",
         "Every address is assigned a single line, so it is a function."),
        ("ADVANCED", "For f: A → B to be onto, which condition must hold?",
         ["every element of A has an image", "every element of B is the image of some element of A", "f is injective", "A has more elements than B"], "B",
         "Onto (surjective) means the range equals the codomain B."),
        ("ADVANCED", "Mapping an employee to their manager and then to the manager's manager uses:",
         ["the identity function", "the inverse function", "a composed function", "a constant function"], "C",
         "Applying the manager function twice composes it into a two-level chain."),
        ("ADVANCED", "The relation 'a divides b' on positive integers is:",
         ["an equivalence relation", "symmetric for all pairs", "a bijection", "a partial order"], "D",
         "Divisibility is reflexive, antisymmetric and transitive, so it is a partial order."),
        ("ADVANCED", "For lossless data encoding, the encoding function must be:",
         ["injective", "surjective only", "constant", "symmetric"], "A",
         "An injective encoding ensures distinct messages map to distinct codes that decode uniquely."),
        ("ADVANCED", "An RFID reader produces one signal per tag. Modelling the read operation as a mapping, each tag maps to a single signal, so the read is:",
         ["one-to-many", "a function from tag to signal", "a symmetric relation", "an equivalence relation"], "B",
         "Since every tag yields exactly one signal, the mapping is a function."),
    ],
    183: [
        ("BEGINNER", "Which principle states that if one task can be done in m ways and another in n ways, both can be done in m × n ways?",
         ["the multiplication principle", "the addition principle", "the pigeonhole principle", "the principle of inclusion-exclusion"], "A",
         "The product rule multiplies the number of ways to perform independent tasks."),
        ("BEGINNER", "Which principle is used when the available choices are mutually exclusive?",
         ["the multiplication principle", "the addition principle", "the product rule", "the factorial rule"], "B",
         "The sum rule adds the counts when the options cannot happen together."),
        ("BEGINNER", "A permutation of a set is:",
         ["a selection where order does not matter", "an arrangement where order matters", "a choice with repetition only", "a random subset"], "C",
         "Permutations are ordered arrangements of the elements of a set."),
        ("BEGINNER", "A combination is best described as:",
         ["an ordered arrangement", "a selection where order does not matter", "an arrangement of all elements", "a choice requiring repetition"], "D",
         "Combinations select subsets without regard to the order of selection."),
        ("BEGINNER", "How many ways can 3 distinct books be arranged on a shelf?",
         ["6", "3", "9", "12"], "A",
         "The three books can be ordered in 3! = 6 ways."),
        ("BEGINNER", "The value of 5! (5 factorial) is:",
         ["20", "120", "25", "60"], "B",
         "5! = 5 × 4 × 3 × 2 × 1 = 120."),
        ("BEGINNER", "The number of ways to choose 2 items from 4 distinct items is:",
         ["12", "4", "6", "8"], "C",
         "C(4, 2) = 4! / (2!2!) = 6."),
        ("BEGINNER", "What does the notation n! represent?",
         ["the product of the integers from 1 to n", "the sum of the integers from 1 to n", "the square of n", "the nth prime number"], "D",
         "n! is the product 1 × 2 × 3 × ... × n."),
        ("BEGINNER", "The pigeonhole principle states that if n + 1 objects are placed in n boxes, then:",
         ["at least one box holds at least two objects", "every box holds exactly two objects", "some box is always empty", "exactly one box is full"], "A",
         "With more objects than boxes, some box must contain at least two objects."),
        ("BEGINNER", "The number of distinct arrangements of the letters of the word CAT is:",
         ["3", "6", "9", "12"], "B",
         "All three letters are distinct, so there are 3! = 6 arrangements."),
        ("INTERMEDIATE", "How many ways can 5 students be arranged in a line?",
         ["120", "25", "60", "720"], "A",
         "Ordered arrangements of 5 distinct students number 5! = 120."),
        ("INTERMEDIATE", "How many distinct arrangements of the letters of the word BALL are there?",
         ["24", "12", "6", "4"], "B",
         "The repeated L means the count is 4! / 2! = 12."),
        ("INTERMEDIATE", "From a club of 10 members, how many committees of 3 can be formed?",
         ["720", "30", "120", "1000"], "C",
         "Choosing 3 of 10 members gives C(10, 3) = 120."),
        ("INTERMEDIATE", "How many 2-letter codes can be formed from the 5 vowels if repetition is allowed?",
         ["20", "10", "15", "25"], "D",
         "Each position has 5 choices, giving 5 × 5 = 25 codes."),
        ("INTERMEDIATE", "A 4-character password uses distinct letters from the 26 of the alphabet. How many passwords exist?",
         ["26 × 26 × 26 × 26", "26 × 25 × 24 × 23", "26 + 25 + 24 + 23", "26 × 4"], "B",
         "Without repetition the choices shrink each time, giving 26 × 25 × 24 × 23."),
        ("INTERMEDIATE", "In how many ways can a president and a secretary be chosen from 8 people?",
         ["16", "56", "28", "64"], "B",
         "The two roles are distinct, so the ordered count is 8 × 7 = 56."),
        ("INTERMEDIATE", "In how many ways can 4 identical red balls and 3 identical blue balls be arranged in a row?",
         ["7!", "5040", "35", "24"], "C",
         "The multinomial count is 7! / (4!3!) = 35."),
        ("INTERMEDIATE", "How many subsets does a set with 6 elements have?",
         ["32", "12", "36", "64"], "D",
         "A 6-element set has 2^6 = 64 subsets."),
        ("INTERMEDIATE", "How many ways can 5 distinct prizes be distributed among 3 students?",
         ["243", "125", "60", "15"], "A",
         "Each prize has 3 possible recipients, so there are 3^5 = 243 ways."),
        ("INTERMEDIATE", "From 4 boys and 5 girls, how many groups of 2 boys and 2 girls can be chosen?",
         ["6", "60", "120", "36"], "B",
         "C(4, 2) × C(5, 2) = 6 × 10 = 60 groups."),
        ("ADVANCED", "A courier must visit 6 distinct stops, visiting each exactly once. How many possible routes exist?",
         ["720", "36", "6", "120"], "A",
         "Ordered arrangements of the 6 stops give 6! = 720 routes."),
        ("ADVANCED", "A 10-digit phone number must start with a nonzero digit and digits may repeat. How many such numbers exist?",
         ["10^10", "9 × 10^9", "9^10", "10 × 9^9"], "B",
         "The first digit has 9 choices and each of the remaining nine has 10, giving 9 × 10^9."),
        ("ADVANCED", "A team of 11 is selected from 15 players, then one member is named captain. How many outcomes exist?",
         ["C(15, 11)", "15 × C(14, 10)", "11 × C(15, 11)", "C(15, 10) × 10"], "C",
         "Choose the team in C(15, 11) ways and then select its captain in 11 ways."),
        ("ADVANCED", "If n people are in a room and everyone shakes hands once, the number of handshakes is:",
         ["n!", "n(n - 1)", "n(n - 1) / 2", "n^2"], "D",
         "Every pair shakes hands exactly once, giving C(n, 2) = n(n - 1) / 2."),
        ("ADVANCED", "A coupon code uses 2 distinct letters followed by 3 digits with repetition allowed. How many codes exist?",
         ["26 × 25 × 10^3", "26^2 × 10^3", "26 × 25 × 10 × 9 × 8", "26^5"], "A",
         "The letters are distinct (26 × 25) and the three digits may repeat (10^3)."),
        ("ADVANCED", "In a round-robin tournament with 8 teams where every pair plays once, how many matches are played?",
         ["64", "28", "56", "16"], "B",
         "Each pair of teams meets once, so the count is C(8, 2) = 28."),
        ("ADVANCED", "A 4-character password uses exactly 2 digits and 2 letters, with the digit positions chosen first. The number of passwords is:",
         ["4 × 10 × 26", "C(4, 2) × 26^2", "C(4, 2) × 10^2 × 26^2", "10^2 × 26^2 × 2"], "C",
         "Pick the two digit positions in C(4, 2) ways, fill them in 10^2 ways and the letters in 26^2 ways."),
        ("ADVANCED", "A data center has 12 identical servers and 5 racks that must each hold at least one server. The number of valid distributions is:",
         ["C(12, 5)", "C(12, 4)", "C(11, 5)", "C(11, 4)"], "D",
         "Giving each rack one server leaves 7 to distribute among 5, giving C(7 + 4, 4) = C(11, 4)."),
        ("ADVANCED", "A feature vector has 10 binary features and 3 categorical features with 4 values each. How many distinct input combinations exist?",
         ["2^10 × 4^3", "2^10 + 4^3", "10 × 2 × 3 × 4", "(2 × 10) × (4 × 3)"], "A",
         "Each binary feature has 2 choices and each categorical feature has 4, giving 2^10 × 4^3."),
        ("ADVANCED", "A device code uses 4 symbols drawn from 26 letters and 10 digits without repetition. How many codes exist?",
         ["36^4", "36 × 35 × 34 × 33", "C(36, 4)", "26^4 × 10^4"], "B",
         "Ordered selection without repetition from 36 symbols gives 36 × 35 × 34 × 33."),
    ],
    184: [
        ("BEGINNER", "A graph G = (V, E) consists of:",
         ["a set of vertices V and a set of edges E", "a set of edges only", "a matrix of numbers", "a sequence of values"], "A",
         "A graph is formally a pair made of a vertex set and an edge set."),
        ("BEGINNER", "In a graph, a vertex is also commonly called a:",
         ["edge", "node", "loop", "weight"], "B",
         "Vertices are interchangeably referred to as nodes."),
        ("BEGINNER", "A simple graph is one that has:",
         ["multiple edges and loops", "no loops and at most one edge between any two vertices", "only directed edges", "weighted edges only"], "C",
         "Simple graphs forbid loops and duplicate edges between the same vertices."),
        ("BEGINNER", "An edge that joins a vertex to itself is called a:",
         ["bridge", "loop", "pendant edge", "parallel edge"], "D",
         "A loop is an edge whose two endpoints are the same vertex."),
        ("BEGINNER", "The degree of a vertex is:",
         ["the number of edges incident to it", "the number of vertices in the graph", "the weight of its longest edge", "the depth of the graph"], "A",
         "Degree counts the edges that touch a vertex."),
        ("BEGINNER", "In graph terms, a path is:",
         ["a sequence of distinct vertices joined by edges", "any single edge repeated twice", "a set of isolated vertices", "a vertex with a loop"], "B",
         "A path visits vertices in order, each consecutive pair joined by an edge, without repetition."),
        ("BEGINNER", "A graph in which every vertex is joined to every other by exactly one edge is called:",
         ["a bipartite graph", "a tree", "a complete graph", "a planar graph"], "C",
         "In a complete graph every pair of vertices is joined by an edge."),
        ("BEGINNER", "How many vertices does a tree with 5 edges have?",
         ["5", "4", "10", "6"], "D",
         "A tree with e edges always has e + 1 vertices, so 5 edges give 6 vertices."),
        ("BEGINNER", "A cycle in a graph is:",
         ["a closed path with distinct vertices", "any single edge", "a path with no edges", "two parallel edges"], "A",
         "A cycle is a closed route returning to its start with distinct vertices."),
        ("BEGINNER", "A bipartite graph has its vertices split into two sets such that:",
         ["every edge joins vertices within the same set", "every edge joins a vertex from each set", "no edges exist", "each vertex has degree one"], "B",
         "In a bipartition all edges cross between the two parts."),
        ("INTERMEDIATE", "A graph has 6 vertices, each of degree 3. How many edges does it have?",
         ["9", "18", "12", "6"], "A",
         "By the handshake lemma 2E = 6 × 3 = 18, so E = 9."),
        ("INTERMEDIATE", "How many edges does the complete graph K_6 have?",
         ["12", "15", "36", "30"], "B",
         "K_n has n(n - 1) / 2 edges, so K_6 has 15."),
        ("INTERMEDIATE", "A tree with 10 vertices has how many edges?",
         ["10", "11", "9", "20"], "C",
         "A tree with n vertices always has n - 1 = 9 edges."),
        ("INTERMEDIATE", "The shortest path between two vertices in an unweighted graph is found using:",
         ["depth-first search", "topological sort", "prim's algorithm", "breadth-first search"], "D",
         "BFS explores level by level and therefore finds the shortest unweighted path."),
        ("INTERMEDIATE", "A connected acyclic graph is called a:",
         ["tree", "cycle", "complete graph", "forest"], "A",
         "A connected graph with no cycles is exactly a tree."),
        ("INTERMEDIATE", "A graph has an Euler circuit if and only if:",
         ["every vertex has even degree", "every vertex has degree 2", "the graph is complete", "there are no bridges"], "B",
         "An Euler circuit exists exactly when every vertex has even degree."),
        ("INTERMEDIATE", "A connected graph with exactly two vertices of odd degree and all others even has:",
         ["an Euler circuit", "no trail using every edge", "an Euler trail but no Euler circuit", "a Hamiltonian cycle"], "C",
         "Two odd vertices allow an open Euler trail that starts and ends at those vertices."),
        ("INTERMEDIATE", "In a directed graph, the in-degree of a vertex is:",
         ["the number of edges leaving it", "its total degree", "its depth", "the number of edges entering it"], "D",
         "In-degree counts the incoming edges of a vertex."),
        ("INTERMEDIATE", "Kruskal's algorithm is used to find:",
         ["a minimum spanning tree", "the shortest path", "a Hamiltonian cycle", "the graph diameter"], "A",
         "Kruskal's greedily adds the lightest safe edges to build a minimum spanning tree."),
        ("INTERMEDIATE", "How many edges does the complete bipartite graph K_3,3 have?",
         ["6", "9", "3", "18"], "B",
         "K_m,n has m × n edges, so K_3,3 has 3 × 3 = 9."),
        ("ADVANCED", "A social network models friendships with an undirected graph. To find clusters of friends connected to each other, you would:",
         ["find the connected components", "find a minimum spanning tree", "run a topological sort", "compute the graph diameter"], "A",
         "Connected components group vertices reachable from one another, revealing friend clusters."),
        ("ADVANCED", "A navigation app must find the fastest route when roads have travel-time delays. Which algorithm fits best?",
         ["Kruskal's algorithm", "Dijkstra's algorithm", "breadth-first search", "topological sort"], "B",
         "Dijkstra's algorithm finds shortest paths in graphs with nonnegative edge weights."),
        ("ADVANCED", "A project has tasks with dependencies that must run in order. Which technique produces a valid execution order?",
         ["prim's algorithm", "BFS on a complete graph", "topological sort", "Floyd-Warshall"], "C",
         "Topological sorting orders tasks so every dependency appears before its dependents."),
        ("ADVANCED", "A city must connect all districts with fibre at minimum total cable length. This is:",
         ["a shortest path problem", "a Hamiltonian cycle problem", "a max-flow problem", "a minimum spanning tree problem"], "D",
         "Connecting all nodes at minimum total cost is exactly the MST problem."),
        ("ADVANCED", "A network must push the maximum amount of data from a source to a sink through capacitated links. This is:",
         ["a maximum flow problem", "a minimum spanning tree problem", "a graph colouring problem", "a topological sort problem"], "A",
         "Maximum flow finds the largest feasible throughput between two vertices subject to capacities."),
        ("ADVANCED", "An exam scheduler assigns time slots so that no two courses with shared students share a slot. This is the problem of:",
         ["finding a spanning tree", "graph colouring", "finding bridges", "computing vertex degrees"], "B",
         "Colouring the course-conflict graph with different colours per adjacent vertex minimizes required slots."),
        ("ADVANCED", "The seven bridges of Königsberg question asks for a route crossing each bridge exactly once and returning to the start. This asks for:",
         ["a Hamiltonian cycle", "an Euler circuit", "a spanning tree", "a perfect matching"], "C",
         "Crossing each edge exactly once and returning is the definition of an Euler circuit."),
        ("ADVANCED", "Dijkstra's algorithm can give incorrect shortest paths when the graph contains:",
         ["unweighted edges", "self loops only", "zero-weight edges", "negative weight edges"], "D",
         "Negative edges can break Dijkstra because an already-settled vertex is not revisited with better paths."),
        ("ADVANCED", "To guarantee a network stays connected even if any single link fails, an engineer studies:",
         ["edge connectivity and bridges", "the handshake lemma", "the four colour theorem", "complete graph enumeration"], "A",
         "Edge connectivity and bridges measure resilience to single-link failures."),
        ("ADVANCED", "The theorem guaranteeing that four colours always suffice to colour regions of a planar map is:",
         ["Euler's formula", "the four colour theorem", "Kuratowski's theorem", "Tutte's theorem"], "B",
         "The four colour theorem states that four colours are always enough for planar maps."),
    ],
    185: [
        ("BEGINNER", "A prime number is a natural number greater than 1 that has:",
         ["exactly two distinct positive divisors", "no divisors at all", "only itself as a divisor", "at least three positive divisors"], "A",
         "A prime has exactly the two divisors 1 and itself."),
        ("BEGINNER", "Which of the following numbers is prime?",
         ["1", "2", "4", "9"], "B",
         "2 is prime because its only divisors are 1 and 2."),
        ("BEGINNER", "The greatest common divisor of 12 and 18 is:",
         ["36", "3", "6", "216"], "C",
         "The largest integer that divides both 12 and 18 is 6."),
        ("BEGINNER", "The least common multiple of 4 and 6 is:",
         ["2", "10", "24", "12"], "D",
         "The smallest common multiple of 4 and 6 is 12."),
        ("BEGINNER", "An even integer is one that is divisible by:",
         ["2", "3", "5", "7"], "A",
         "Even numbers leave a remainder of 0 when divided by 2."),
        ("BEGINNER", "The value of 7 mod 3 is:",
         ["2", "1", "3", "0"], "B",
         "7 divided by 3 leaves a remainder of 1."),
        ("BEGINNER", "The set of integers is conventionally denoted by:",
         ["N", "Z", "Q", "R"], "C",
         "Z is the standard symbol for the set of integers."),
        ("BEGINNER", "Which of the following numbers is odd?",
         ["2", "4", "9", "12"], "D",
         "9 is not divisible by 2, so it is odd."),
        ("BEGINNER", "A composite number is a natural number greater than 1 that:",
         ["has more than two positive divisors", "has exactly two divisors", "has no divisors", "is negative"], "A",
         "Composite numbers have additional divisors besides 1 and themselves."),
        ("BEGINNER", "The identity element for addition in the integers is:",
         ["1", "0", "-1", "10"], "B",
         "Adding 0 to any integer leaves it unchanged."),
        ("INTERMEDIATE", "What is gcd(48, 36)?",
         ["12", "6", "24", "18"], "A",
         "The largest common divisor of 48 and 36 is 12."),
        ("INTERMEDIATE", "What is lcm(8, 12)?",
         ["4", "24", "96", "48"], "B",
         "The smallest common multiple of 8 and 12 is 24."),
        ("INTERMEDIATE", "The value of 17 mod 5 is:",
         ["3", "5", "2", "1"], "C",
         "17 divided by 5 leaves a remainder of 2."),
        ("INTERMEDIATE", "Which of the following numbers is divisible by 3?",
         ["14", "17", "21", "25"], "D",
         "21 is divisible by 3 because its digit sum 2 + 1 = 3 is a multiple of 3."),
        ("INTERMEDIATE", "How many prime numbers lie between 1 and 10?",
         ["4", "5", "6", "3"], "A",
         "The primes below 10 are 2, 3, 5 and 7, giving four."),
        ("INTERMEDIATE", "The modular inverse of 3 modulo 7 is:",
         ["1", "5", "3", "6"], "B",
         "3 × 5 = 15 ≡ 1 (mod 7), so 5 is the inverse of 3."),
        ("INTERMEDIATE", "Which number is divisible by both 2 and 5?",
         ["13", "25", "10", "7"], "C",
         "10 ends in 0, so it is divisible by both 2 and 5."),
        ("INTERMEDIATE", "The prime factorization of 60 is:",
         ["2 × 3 × 5", "2 × 5 × 6", "3 × 4 × 5", "2^2 × 3 × 5"], "D",
         "60 = 4 × 15 = 2^2 × 3 × 5."),
        ("INTERMEDIATE", "What is 7^2 mod 5?",
         ["4", "2", "3", "1"], "A",
         "49 divided by 5 leaves a remainder of 4."),
        ("INTERMEDIATE", "The sum of all the divisors of 6 is:",
         ["6", "12", "9", "18"], "B",
         "The divisors 1, 2, 3 and 6 add up to 12."),
        ("ADVANCED", "In RSA, the public exponent e must satisfy gcd(e, φ(n)) = 1. This condition guarantees:",
         ["a modular inverse of e modulo φ(n) exists", "n is prime", "e is larger than n", "φ(n) is even"], "A",
         "Coprime values of e and φ(n) ensure the private key can be derived as the modular inverse."),
        ("ADVANCED", "A cryptographic hash must be hard to invert. This property relies on functions built from:",
         ["the commutative law", "hard-to-invert modular arithmetic", "the associative law", "the distributive law"], "B",
         "One-way functions based on modular arithmetic make finding a preimage infeasible."),
        ("ADVANCED", "Euler's theorem states that if gcd(a, n) = 1, then:",
         ["a^n ≡ 1 (mod n)", "n^(φ(a)) ≡ 1 (mod a)", "a^(φ(n)) ≡ 1 (mod n)", "a × n ≡ 1 (mod φ(n))"], "C",
         "Euler's theorem states a^(φ(n)) ≡ 1 (mod n) whenever gcd(a, n) = 1."),
        ("ADVANCED", "Using Fermat's little theorem, 7^100 mod 5 simplifies to:",
         ["7", "2", "3", "1"], "D",
         "Since 5 is prime and coprime to 7, 7^4 ≡ 1 (mod 5) and 100 is a multiple of 4, so the result is 1."),
        ("ADVANCED", "A cache uses the last 4 bits of an address as an index. How many distinct index values exist?",
         ["16", "4", "8", "15"], "A",
         "Four bits encode 2^4 = 16 distinct index values."),
        ("ADVANCED", "A checksum is the sum of data words modulo 256. An error goes undetected when the corrupted sum equals the original modulo 256. This relates to:",
         ["graph connectivity", "collisions in modular arithmetic", "Euler's formula", "the binomial theorem"], "B",
         "Two different sums agreeing modulo 256 produce an undetected checksum collision."),
        ("ADVANCED", "Tasks are assigned to worker t mod 5. If all task ids are multiples of 5, which worker is overloaded?",
         ["worker 4", "all workers equally", "worker 0", "worker 2"], "C",
         "Every multiple of 5 leaves remainder 0, so all tasks go to worker 0."),
        ("ADVANCED", "In RSA decryption, the private key d recovers the plaintext from ciphertext c using:",
         ["c^e mod n", "e^d mod c", "d^c mod n", "c^d mod n"], "D",
         "RSA decrypts by computing m = c^d mod n with the private exponent d."),
        ("ADVANCED", "A cyclic group generated by g has order 12. The number of distinct elements in the group is:",
         ["12", "6", "24", "11"], "A",
         "A cyclic group of order 12 contains exactly 12 distinct powers of its generator."),
        ("ADVANCED", "An ISBN-13 check digit makes the weighted sum of its digits divisible by 10. This validation is an example of:",
         ["graph colouring", "modular arithmetic error detection", "exponentiation", "the pigeonhole principle"], "B",
         "Checking a weighted sum modulo 10 is a modular arithmetic error-detection scheme."),
    ],
}
