# -*- coding: utf-8 -*-
"""
Question bank for Subject 10: DBMS105 - MongoDB (Category: Database Management).

Topics:
  46 - NoSQL & MongoDB Basics
  47 - Documents & CRUD
  48 - Aggregation Pipeline
  49 - Indexing & Performance
  50 - Replication & Sharding

Each topic has exactly 30 questions: 10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED.
"""

QUESTIONS = {
    46: [
        ("BEGINNER", "Which data model does MongoDB use to store records?",
         ["Relational model", "Document model", "Key-value model only", "Graph model"], "B",
         "MongoDB is a document database that stores each record as a document with named fields."),
        ("BEGINNER", "What does the acronym BSON stand for?",
         ["Binary JSON", "Basic Simple Object Notation", "Binary Structured Object Network", "Big Serialized Object Node"], "A",
         "BSON is short for Binary JSON, a binary-encoded serialization of JSON-like documents."),
        ("BEGINNER", "In MongoDB, where are documents stored?",
         ["In tables and rows", "In key-value buckets", "In collections", "In object graphs"], "C",
         "Documents are grouped and stored inside collections, which are analogous to tables in SQL."),
        ("BEGINNER", "What is the name of the required primary key field that every MongoDB document has?",
         ["id", "_id", "key", "pk"], "B",
         "Every document contains an _id field which serves as its primary key."),
        ("BEGINNER", "What is the default BSON type generated for the _id field when it is not supplied?",
         ["String", "Integer", "UUID", "ObjectId"], "D",
         "MongoDB generates an ObjectId as the default _id value when none is provided."),
        ("BEGINNER", "Which of the following is true about MongoDB collections?",
         ["They do not enforce a fixed schema", "Every document must have identical fields", "Fields cannot be added later", "Schemas must be declared before insert"], "A",
         "Collections are schema-less, so documents in the same collection can have different fields."),
        ("BEGINNER", "Which category of NoSQL database does MongoDB belong to?",
         ["Wide-column store", "Graph database", "Document store", "Pure key-value store"], "C",
         "MongoDB is a document store that organizes data as BSON documents."),
        ("BEGINNER", "What is a single MongoDB server instance able to hold?",
         ["Multiple databases", "Only one database", "Only collections, no databases", "One database and one collection"], "A",
         "A MongoDB deployment can host multiple independent databases, each containing collections."),
        ("BEGINNER", "Compared to JSON, what advantage does BSON provide for MongoDB?",
         ["It is human readable text", "It supports fewer data types", "It cannot store binary data", "It stores more data types and is binary-encoded"], "D",
         "BSON adds extra types such as ObjectId, Date and binary data, and is compact and fast to scan."),
        ("BEGINNER", "Which MongoDB shell command switches to or selects a database?",
         ["use", "select", "open", "cd"], "B",
         "In the mongo shell, the 'use' command selects a database, creating it lazily if needed."),
        ("INTERMEDIATE", "What does an ObjectId consist of?",
         ["Only a random number", "A UUID and a checksum", "A 12-byte value with timestamp, machine ID, process ID and counter", "A 16-byte MD5 hash"], "C",
         "An ObjectId is 12 bytes combining a 4-byte timestamp, 5-byte random/machine value, 2-byte process ID and a 3-byte counter."),
        ("INTERMEDIATE", "A document has a date field. Which BSON type should store it so that date-range queries work correctly?",
         ["Date", "String", "Integer", "Boolean"], "A",
         "The BSON Date type stores millisecond timestamps since the Unix epoch, enabling correct range comparisons."),
        ("INTERMEDIATE", "If you insert a document without an _id field, what does MongoDB do?",
         ["Rejects the document", "Stores it with a null _id", "Throws a duplicate key error", "Automatically generates an ObjectId"], "D",
         "MongoDB automatically generates and inserts an ObjectId for the _id field when it is missing."),
        ("INTERMEDIATE", "Two documents in the same collection have completely different fields. Is this valid?",
         ["No, all documents must match the collection schema", "Yes, collections are schema-less", "Only if both have an _id of the same type", "Only during the development phase"], "B",
         "Because collections are schema-less, documents with differing field sets are perfectly valid."),
        ("INTERMEDIATE", "What is an embedded (nested) document?",
         ["A reference to a document in another collection", "A document stored in a separate file", "A document stored as a value of a field inside another document", "A copy of the _id field"], "C",
         "An embedded document is a sub-document stored as a field value, which suits one-to-one and one-to-many data."),
        ("INTERMEDIATE", "What is the maximum size of a single BSON document in MongoDB?",
         ["16 megabytes", "1 megabyte", "64 megabytes", "4 gigabytes"], "A",
         "The MongoDB document size limit is 16 MB, with larger data stored via GridFS."),
        ("INTERMEDIATE", "What is a 'database' in MongoDB from a filesystem perspective?",
         ["A single .db file", "A directory of JSON files", "A single collection file", "A set of collection data files managed by the server"], "D",
         "Each database maps to data files managed by the MongoDB server, typically in the dbpath directory."),
        ("INTERMEDIATE", "When is a new collection actually created?",
         ["When the server starts", "Lazily, on the first insert into it", "When a database is created", "Only when explicitly created with a schema"], "B",
         "Collections are created lazily on first write, so no explicit creation command is required."),
        ("INTERMEDIATE", "Which shell command shows the name of the current database?",
         ["db", "show dbs", "list db", "current"], "A",
         "Typing 'db' in the shell prints the name of the current database being used."),
        ("INTERMEDIATE", "Which BSON data type represents a true/false value?",
         ["Integer", "NumberLong", "Boolean", "ObjectId"], "C",
         "BSON includes a Boolean type for true and false values."),
        ("ADVANCED", "A user stores ISO strings for dates instead of the BSON Date type. What is the most likely consequence?",
         ["Queries become faster", "Range and sort queries may behave incorrectly and waste storage", "The _id can no longer be indexed", "Documents exceed the 16 MB limit"], "B",
         "Storing dates as strings prevents correct chronological ordering, making range and sort queries inaccurate."),
        ("ADVANCED", "Why does MongoDB prefer BSON over plain JSON for storage?",
         ["JSON is binary and faster", "JSON supports ObjectId natively", "JSON documents cannot be nested", "BSON is binary-encoded and supports extra types for efficient traversal"], "D",
         "BSON's binary encoding and extra types (ObjectId, Date, Decimal128) make reads and writes faster and storage more compact."),
        ("ADVANCED", "When would an embedded (denormalized) document be a better choice than a reference?",
         ["When the child data is always fetched with the parent and changes rarely", "When child documents grow without bound", "When data must never be duplicated", "When children are shared by many parents"], "A",
         "Embedding is best for data that is accessed together with the parent and has bounded size, avoiding joins."),
        ("ADVANCED", "A legacy feature is accessed only during a migration. Why should the application still use the BSON type that matches the data?",
         ["It has no impact on the database", "It only matters for _id values", "Wrong types break indexing and query matching", "Strings are never comparable"], "C",
         "Query operators and indexes match values by BSON type, so inconsistent types can hide documents from queries."),
        ("ADVANCED", "What is the main reason ObjectId values are roughly sortable by creation time?",
         ["They include a UUID", "The leading 4 bytes are a Unix timestamp", "They are sequential integers", "They contain a machine hash"], "B",
         "Because the first 4 bytes of an ObjectId are the creation timestamp, ObjectIds are generally increasing over time."),
        ("ADVANCED", "Which approach would you choose to model a many-to-many relationship like 'student enrolled in many courses'?",
         ["Embed all course details inside each student", "Store all students inside every course", "Use a single field with the whole course", "Store references in an array on either side"], "D",
         "For many-to-many relationships, storing an array of references (course _ids) on the student avoids unbounded duplication."),
        ("ADVANCED", "Which field should hold a globally unique identifier for an entity that spans multiple collections?",
         ["_id", "name", "createdAt", "type"], "A",
         "The _id field is the primary key and is guaranteed unique within a collection, so it should store the stable identifier."),
        ("ADVANCED", "Why would you store an audit log document with a large growing array?",
         ["It improves read performance", "It avoids write amplification", "It is usually a poor design because arrays can outgrow the 16 MB limit", "It simplifies sharding"], "C",
         "Unbounded arrays embedded in one document risk exceeding the 16 MB size cap, so logs are better stored as separate documents."),
        ("ADVANCED", "A business rule requires atomic updates across two collections. What should be considered?",
         ["It is always supported by a single update", "Only read operations can be atomic", "Embedding removes the need for transactions", "Multi-document transactions may be needed"], "D",
         "Updates spanning multiple documents require multi-document transactions rather than single-document atomicity."),
        ("ADVANCED", "What role does the 3-byte counter play inside an ObjectId?",
         ["It stores the server location", "It ensures uniqueness for ObjectIds generated in the same second and machine", "It stores the collection number", "It is the checksum of the document"], "B",
         "The counter distinguishes multiple ObjectIds generated within the same second by the same machine and process."),
    ],
    47: [
        ("BEGINNER", "Which MongoDB method inserts a single document into a collection?",
         ["insertOne", "insertMany", "addOne", "pushDoc"], "A",
         "insertOne inserts exactly one document into the collection."),
        ("BEGINNER", "Which method inserts multiple documents in a single call?",
         ["insertOne", "insertMany", "insertAll", "batchAdd"], "B",
         "insertMany accepts an array of documents and inserts them in one operation."),
        ("BEGINNER", "Which update operator sets the value of a field?",
         ["$inc", "$push", "$set", "$unset"], "C",
         "$set sets or overwrites the value of a specified field."),
        ("BEGINNER", "Which update operator removes a field from a document?",
         ["$delete", "$drop", "$remove", "$unset"], "D",
         "$unset removes the specified field entirely from matching documents."),
        ("BEGINNER", "Which update operator increments a numeric field by a given amount?",
         ["$add", "$inc", "$plus", "$increase"], "B",
         "$inc increases (or decreases with a negative value) a numeric field by the given amount."),
        ("BEGINNER", "Which update operator appends a value to an array field?",
         ["$add", "$append", "$concat", "$push"], "D",
         "$push adds an element to the end of an array field."),
        ("BEGINNER", "Which method removes all documents that match a filter?",
         ["deleteMany", "deleteOne", "removeAll", "dropMany"], "A",
         "deleteMany deletes every document matching the filter, and with an empty filter deletes all documents."),
        ("BEGINNER", "Which comparison operator selects documents where a field is greater than a value?",
         ["$gte", "$lt", "$gt", "$max"], "C",
         "$gt matches documents where the field value is strictly greater than the given value."),
        ("BEGINNER", "Which operator matches documents where a field value is in a given list?",
         ["$like", "$any", "$within", "$in"], "D",
         "$in selects documents where the field equals any value in the supplied array."),
        ("BEGINNER", "Which operator selects documents where a field is not equal to a value?",
         ["$notEqual", "$ne", "$neq", "$diff"], "B",
         "$ne matches documents where the field value is not equal to the given value."),
        ("INTERMEDIATE", "Given db.orders.insertOne({item: 'pen', qty: 5}), what is the value of qty in the stored document?",
         ["0", "null", "5", "an array"], "C",
         "The insert stores the document exactly as given, so qty remains 5 and an ObjectId is added to _id."),
        ("INTERMEDIATE", "After running db.books.updateMany({price: 10}, {$inc: {price: 2}}), what is the new price of every matched book?",
         ["12", "8", "10", "20"], "A",
         "$inc adds 2 to each matched price, turning 10 into 12."),
        ("INTERMEDIATE", "What does db.products.updateOne({name: 'milk'}, {$set: {stock: 0}}) do to the matching document?",
         ["Deletes the name field", "Adds 0 to the stock field", "Replaces the whole document", "Sets the stock field to 0"], "D",
         "$set writes the stock field to 0 without touching the rest of the document."),
        ("INTERMEDIATE", "What does db.users.deleteMany({status: 'inactive'}) do?",
         ["Deletes the first inactive user only", "Deletes every inactive user", "Deactivates all users", "Returns an error"], "B",
         "deleteMany removes all documents whose status field equals 'inactive'."),
        ("INTERMEDIATE", "Which find query returns documents whose age is between 18 and 30 inclusive of endpoints?",
         ["{age: {$between: [18, 30]}}", "{age: {$eq: [18, 30]}}", "{age: {$gte: 18, $lte: 30}}", "{age: {$range: 18, 30}}"], "C",
         "Combining $gte: 18 and $lte: 30 matches ages from 18 through 30 inclusive."),
        ("INTERMEDIATE", "Which query finds documents where the name field starts with 'Al'?",
         ["{name: /^Al/}", "{name: {$starts: 'Al'}}", "{name: $prefix('Al')}", "{name: {$begin: 'Al'}}"], "A",
         "The regular expression /^Al/ matches strings beginning with 'Al'."),
        ("INTERMEDIATE", "What does the projection db.users.find({}, {name: 1, _id: 0}) return?",
         ["Only the _id field", "All fields", "name and all other fields except _id", "Only the name field"], "D",
         "Setting name:1 includes name while _id:0 excludes _id, so only the name field is returned."),
        ("INTERMEDIATE", "What does {$or: [{price: {$lt: 5}}, {stock: 0}]} as a filter return?",
         ["Documents that satisfy both conditions", "Documents satisfying at least one condition", "Documents that fail both conditions", "Only documents with price less than 5"], "B",
         "$or returns documents matching any one of the listed conditions."),
        ("INTERMEDIATE", "When you call db.coll.find({}, {qty: 1, _id: 0}).sort({qty: -1}), how are results ordered?",
         ["Alphabetically", "Randomly", "By qty descending", "By insertion order"], "C",
         "sort({qty: -1}) orders the projected results by qty from highest to lowest."),
        ("INTERMEDIATE", "Which operator checks whether a field exists and is not null?",
         ["$exists", "$present", "$defined", "$has"], "A",
         "$exists: true matches documents where the field is present, and it also matches null values unless combined with $ne: null."),
        ("ADVANCED", "Given db.items.find({qty: {$in: [1, 5, 9]}}), which documents are returned?",
         ["Only documents with qty equal to 1", "Documents whose qty is 1, 5 or 9", "Documents with qty greater than 1", "Documents with qty in an array"], "B",
         "$in matches any document whose qty value equals any element in the array [1, 5, 9]."),
        ("ADVANCED", "What is the effect of an upsert when no document matches the filter?",
         ["Nothing happens", "An error is returned", "The filter is ignored", "A new document is inserted combining the filter and update"], "D",
         "With upsert: true, MongoDB inserts a new document built from the query filter and the update operators when no match exists."),
        ("ADVANCED", "What happens if you use $push on a field that holds a scalar number?",
         ["The update fails with an error", "The number is converted to an array", "The number is ignored", "A new document is created"], "A",
         "$push requires an array field; applying it to a scalar produces an update error."),
        ("ADVANCED", "Given db.logs.deleteMany({}), what does this operation accomplish?",
         ["Deletes only the first log", "Returns an error", "Deletes every document in the collection", "Deletes the database"], "C",
         "An empty filter matches all documents, so deleteMany({}) removes every document from the collection."),
        ("ADVANCED", "db.students.updateOne({id: 7}, {$setOnInsert: {enrolled: true}}, {upsert: true}) - when is enrolled set?",
         ["Only when a match already exists", "Only when the document is newly inserted", "Always, on every call", "Never"], "B",
         "$setOnInsert applies its fields only during an insert triggered by upsert, never on updates of existing documents."),
        ("ADVANCED", "Which filter finds documents where the embedded field 'address.city' equals 'Lagos'?",
         ["{address: 'Lagos'}", "{city: 'Lagos'}", "{$embed: {city: 'Lagos'}}", "{'address.city': 'Lagos'}"], "D",
         "Dot notation 'address.city' targets the city field inside the embedded address document."),
        ("ADVANCED", "How would you match documents where the 'total' field is greater than the 'tax' field using $expr?",
         ["{$expr: {$gt: ['$total', '$tax']}}", "{$gt: {total: '$tax'}}", "{$where: 'total > tax'}", "{$expr: total > tax}"], "A",
         "$expr with $gt: ['$total', '$tax'] compares the values of the two fields inside each document."),
        ("ADVANCED", "Why might insertMany with ordered: false be preferred for bulk loading?",
         ["It is the only valid option", "It always fails fast", "It continues inserting other documents when one fails", "It bypasses the 16 MB limit"], "C",
         "With ordered: false, MongoDB continues processing remaining documents even if some inserts fail."),
        ("ADVANCED", "db.c.updateOne({_id: 1}, {$set: {tags: ['red', 'blue']}}); what is the type of tags?",
         ["A string", "An array", "A nested document", "A set"], "B",
         "The $set operator stores the array literal ['red', 'blue'] as an array field."),
        ("ADVANCED", "Given db.parts.find({sku: {$exists: true, $ne: null}}), which documents match?",
         ["Only documents where sku equals null", "Only documents where sku is missing", "Documents with any sku value including null", "Documents where sku exists and is not null"], "D",
         "Combining $exists: true with $ne: null selects documents that have the sku field with a non-null value."),
    ],
    48: [
        ("BEGINNER", "Which aggregation stage filters documents before they are passed to the next stage?",
         ["$match", "$group", "$filter", "$where"], "A",
         "$match filters the stream of documents using a query condition, similar to find filters."),
        ("BEGINNER", "Which stage groups documents together to compute aggregate values?",
         ["$sort", "$group", "$collect", "$bucket"], "B",
         "$group accumulates documents sharing the same _id key and computes values with accumulators."),
        ("BEGINNER", "Which stage controls which fields appear in the output documents?",
         ["$select", "$pick", "$project", "$fields"], "C",
         "$project includes, excludes or computes fields in each output document."),
        ("BEGINNER", "Which stage orders the documents in the pipeline?",
         ["$order", "$arrange", "$rank", "$sort"], "D",
         "$sort orders documents by the specified field and direction."),
        ("BEGINNER", "Which stage limits the number of documents passed through the pipeline?",
         ["$limit", "$cap", "$max", "$cut"], "A",
         "$limit passes only the first N documents to the next stage."),
        ("BEGINNER", "Which stage performs a left outer join between two collections?",
         ["$join", "$union", "$lookup", "$merge"], "C",
         "$lookup adds fields from another collection based on a matching local and foreign field."),
        ("BEGINNER", "Which stage deconstructs an array field into multiple documents?",
         ["$split", "$array", "$flatten", "$unwind"], "D",
         "$unwind outputs one document per element of the array field."),
        ("BEGINNER", "Which accumulator computes the sum of numeric field values in $group?",
         ["$sum", "$total", "$add", "$count"], "A",
         "$sum adds together the numeric values of a field (or the value 1 for each document)."),
        ("BEGINNER", "Which accumulator computes the average of numeric values in $group?",
         ["$mean", "$avg", "$average", "$mid"], "B",
         "$avg returns the arithmetic mean of the numeric values for the group."),
        ("BEGINNER", "Which accumulator collects field values into an array within a $group stage?",
         ["$toArray", "$collect", "$push", "$array"], "C",
         "$push appends the value of the specified field for each document into an array."),
        ("INTERMEDIATE", "Why should $match be placed as early as possible in a pipeline?",
         ["It removes duplicate documents", "It reduces the number of documents the later stages must process", "It is required to be first", "It creates indexes"], "B",
         "Early $match minimizes the document count flowing through later stages, improving efficiency."),
        ("INTERMEDIATE", "What does db.coll.aggregate([{$group: {_id: null, total: {$sum: 1}}}]) return?",
         ["One document per input document", "An error", "A single document with a count of all documents", "A list of unique ids"], "C",
         "Grouping by _id: null puts all documents in one group and $sum: 1 counts them."),
        ("INTERMEDIATE", "What does {$group: {_id: '$category', n: {$sum: 1}}} produce for each category?",
         ["One document per distinct category with a count", "A count of all categories in one document", "A sorted list of categories", "An array of documents"], "A",
         "Grouping on $category creates one output document per distinct category, with n equal to the number of documents in it."),
        ("INTERMEDIATE", "How do you include the _id field as well as other fields in a $project?",
         ["Write all fields with 0", "Only use $addFields", "Use {$include: all}", "List fields with 1 and exclude _id with 0 if not wanted"], "D",
         "$project includes fields set to 1; _id is included by default and must be set to 0 to exclude it."),
        ("INTERMEDIATE", "Which pipeline would return the 3 most expensive products?",
         ["[{$sort: {price: 1}}, {$limit: 3}]", "[{$sort: {price: -1}}, {$limit: 3}]", "[{$limit: 3}, {$sort: {price: 1}}]", "[{$match: {price: -1}}, {$limit: 3}]"], "B",
         "Sorting price descending with $sort: -1 then limiting to 3 keeps the three highest-priced products."),
        ("INTERMEDIATE", "In {$lookup: {from: 'orders', localField: '_id', foreignField: 'custId', as: 'orders'}}, what is 'orders'?",
         ["The foreign collection name", "The join key", "The output array field added to each input document", "A database name"], "C",
         "The 'as' field names the array added to each input document, containing the matched foreign documents."),
        ("INTERMEDIATE", "db.arr.aggregate([{$unwind: '$items'}]) - how many output documents are produced from a document with a 4-element items array?",
         ["4", "1", "0", "8"], "A",
         "$unwind creates one output document per array element, so a 4-element array yields 4 documents."),
        ("INTERMEDIATE", "What is the output of {$group: {_id: '$dept', avgSal: {$avg: '$salary'}}}?",
         ["The total salary per department", "The number of employees per department", "The maximum salary per department", "The average salary per department"], "D",
         "$avg computes the mean of salary values for each dept group and labels it avgSal."),
        ("INTERMEDIATE", "Which stage computes a new field without removing existing fields?",
         ["$project", "$addFields", "$compute", "$setField"], "B",
         "$addFields adds or overwrites fields while preserving all existing fields in the output."),
        ("INTERMEDIATE", "What does placing $sort after $group do to the group output?",
         ["Nothing", "Sorts the input before grouping", "Orders the grouped result documents", "Limits the groups"], "C",
         "$sort after $group reorders the documents produced by the grouping stage."),
        ("ADVANCED", "Predict the result of db.orders.aggregate([{$match: {status: 'shipped'}}, {$group: {_id: '$customer', total: {$sum: '$amount'}}}]).",
         ["One document per shipped customer with the sum of their shipped amounts", "One document per order with its amount", "A single total for all shipped orders", "Only orders that are not shipped"], "A",
         "The pipeline first keeps only shipped orders, then groups by customer summing the amount of each."),
        ("ADVANCED", "In a $lookup, what does the foreignField reference?",
         ["A field in the local collection", "An output field name", "A field in the foreign collection", "A database name"], "C",
         "foreignField names the field in the 'from' collection that is matched against localField."),
        ("ADVANCED", "What does {$group: {_id: {year: {$year: '$date'}, month: {$month: '$date'}}, sales: {$sum: '$amount'}}} group by?",
         ["Only the year", "Only the month", "The exact date", "The combined year and month pair"], "D",
         "A compound _id with year and month groups documents by the distinct (year, month) combination."),
        ("ADVANCED", "Given db.scores.aggregate([{$project: {name: 1, doubled: {$multiply: ['$score', 2]}}}]), what is 'doubled'?",
         ["The original score", "The score multiplied by 2", "An array of scores", "The sum of all scores"], "B",
         "$multiply computes score times 2, producing a new computed field named doubled."),
        ("ADVANCED", "What does $unwind: {path: '$tags', preserveNullAndEmptyArrays: true} do for documents with no tags field?",
         ["Keeps them as-is with tags absent", "Drops them", "Creates tags: null for them", "Returns an error"], "A",
         "preserveNullAndEmptyArrays: true keeps documents whose array is missing or empty instead of dropping them."),
        ("ADVANCED", "Which pipeline computes a global rank of customers by total spend then adds it to each order?",
         ["A single $group stage", "A $sort followed by $group", "A $group, then $sort, then $setWindowFields (rank)", "Only a $match"], "C",
         "$setWindowFields with rank computes the ranking across groups after aggregation."),
        ("ADVANCED", "Predict db.sales.aggregate([{$match: {region: 'EU'}}, {$sort: {amount: -1}}, {$limit: 2}]).",
         ["All EU sales sorted ascending", "Only the largest EU sale", "Two random EU sales", "The two highest-amount EU sales"], "D",
         "$match keeps EU sales, $sort orders by amount descending, and $limit keeps the top 2."),
        ("ADVANCED", "db.events.aggregate([{$unwind: '$hits'}]) followed by {$group: {_id: '$hits', count: {$sum: 1}}} - what is the output?",
         ["Total hits across all events", "A count per distinct hit value", "The average hits per event", "One document per event"], "B",
         "After unwinding, grouping on $hits counts how often each hit value occurs across all events."),
        ("ADVANCED", "Which output does {$project: {total: {$add: ['$base', '$tax']}, _id: 0}} produce?",
         ["Documents with only a computed total field", "All fields plus total", "Only base and tax", "An empty document"], "A",
         "$add sums base and tax into the new field total and _id: 0 removes the default _id."),
        ("ADVANCED", "In a pipeline joining orders to customers, which stage pairing effectively flattens the joined arrays?",
         ["$group then $match", "$lookup then $limit", "$lookup then $unwind", "$sort then $lookup"], "C",
         "$lookup produces an array field, and $unwind on that field flattens each joined document into its own output document."),
    ],
    49: [
        ("BEGINNER", "What is the main purpose of an index in MongoDB?",
         ["To speed up query and sort operations", "To encrypt documents", "To compress data", "To validate schemas"], "A",
         "Indexes let MongoDB avoid full collection scans by providing efficient paths to matching documents."),
        ("BEGINNER", "Which method creates an index on a collection?",
         ["addIndex", "createIndex", "makeIndex", "newIndex"], "B",
         "createIndex defines an index on the specified field(s) with the given options."),
        ("BEGINNER", "What does a single-field index {price: 1} mean?",
         ["Price is indexed in descending order", "Only one document can have a price", "Price is indexed in ascending order", "Price cannot be changed"], "C",
         "The value 1 indicates an ascending index on the price field."),
        ("BEGINNER", "What is a compound index?",
         ["An index on two or more fields", "An index that combines two collections", "An index on an array", "Two separate indexes on one field"], "A",
         "A compound index is a single index covering multiple fields, such as {lastName: 1, firstName: 1}."),
        ("BEGINNER", "What type of index is created with createIndex({content: 'text'})?",
         ["A unique index", "A TTL index", "A sparse index", "A text index"], "D",
         "The 'text' type builds a text index that enables $text search on the content field."),
        ("BEGINNER", "What does a unique index enforce?",
         ["Only one index per collection", "That values are sorted", "That indexed field values are unique across the collection", "That the index never changes"], "C",
         "A unique index rejects any insert or update that would create a duplicate indexed value."),
        ("BEGINNER", "Which index exists by default on every collection?",
         ["A text index", "The _id index", "A compound index", "A TTL index"], "B",
         "MongoDB automatically creates a unique index on the _id field of every collection."),
        ("BEGINNER", "What does the explain() method provide?",
         ["A list of collections", "A backup plan", "A schema snapshot", "The query plan chosen for a query"], "D",
         "explain() reports how MongoDB executed a query, including the index used and documents examined."),
        ("BEGINNER", "What is a TTL index used for?",
         ["Automatically deleting documents after a set time", "Speeding up text search", "Storing time series data", "Encrypting date fields"], "A",
         "A TTL index lets MongoDB expire and remove documents whose date field is older than a specified interval."),
        ("BEGINNER", "What is a downside of adding many indexes?",
         ["Queries become slower", "Indexes take no space", "Writes become slower and storage grows", "Indexes cannot be removed"], "C",
         "Each index must be maintained on every write and consumes disk space, slowing inserts and updates."),
        ("INTERMEDIATE", "Given the index {a: 1, b: 1}, which of these queries can use the index for equality on both fields?",
         ["Only queries on b", "Queries filtering on a, and on both a and b", "Queries sorting only on b", "Queries using $or on a"], "B",
         "A compound index supports queries that match on its leftmost prefix, i.e., a alone or a followed by b."),
        ("INTERMEDIATE", "What happens when you insert a document that violates a unique index?",
         ["The document is stored and the index drops it", "The whole collection is dropped", "The document replaces an existing one", "The insert fails with a duplicate key error"], "D",
         "A unique index violation causes the insert or update to fail with a duplicate key error."),
        ("INTERMEDIATE", "Without a suitable index, what must MongoDB do to answer a large find()?",
         ["Scan every document in the collection", "Skip half the documents", "Return no results", "Use a text index"], "A",
         "Without an index MongoDB performs a collection scan, reading each document to check the filter."),
        ("INTERMEDIATE", "What does a covered query mean?",
         ["The query matches no documents", "The query uses a text index", "All needed fields come from the index alone, without reading documents", "The query is hidden from the profiler"], "C",
         "A covered query can be satisfied entirely from index entries, so MongoDB never reads the documents themselves."),
        ("INTERMEDIATE", "Which field type is required for a TTL index to work?",
         ["A string date", "A BSON Date or array of dates", "A timestamp stored as text", "An integer"], "B",
         "TTL indexes require a BSON Date field (or an array of dates) whose earliest value determines expiration."),
        ("INTERMEDIATE", "How do you create a unique index on the email field?",
         ["db.coll.unique('email')", "db.coll.index('email', {unique: true})", "db.coll.addUnique('email')", "db.coll.createIndex({email: 1}, {unique: true})"], "D",
         "createIndex with the unique option set to true enforces uniqueness on the indexed field."),
        ("INTERMEDIATE", "Which query operator can prevent an index from being used efficiently?",
         ["$regex with a leading wildcard", "$gte on an indexed field", "$in on an indexed field", "$eq on an indexed field"], "A",
         "A $regex that begins with a wildcard cannot use the index and forces a scan, unlike anchored patterns."),
        ("INTERMEDIATE", "What is index selectivity?",
         ["The order of index creation", "The storage size of an index", "How many distinct values an indexed field has relative to documents", "The speed of index creation"], "C",
         "High selectivity means the index values narrow results to few documents, making the index more effective."),
        ("INTERMEDIATE", "Which command shows the statistics and keys of an existing index?",
         ["db.coll.indexesInfo()", "db.coll.getIndexes()", "db.coll.listIndexNames()", "db.coll.showIndex()"], "B",
         "getIndexes returns details of every index on a collection, including key patterns and options."),
        ("INTERMEDIATE", "An index on an array field is called what?",
         ["A compound index", "A text index", "A sparse index", "A multikey index"], "D",
         "Indexing an array field creates a multikey index with one entry per array element."),
        ("ADVANCED", "Why does field order matter in a compound index like {a: 1, b: 1}?",
         ["Order affects only the index name", "Equality on a then range on b is supported, but a range on a prevents efficient use of b", "It only matters for unique indexes", "Order never matters"], "B",
         "Compound index order determines which prefix queries can use; a range on the leading field limits the rest."),
        ("ADVANCED", "What does the winningPlan vs rejectedPlans in explain() output show?",
         ["The number of indexes", "The database size", "The query time", "Which index plan was chosen and which were considered but rejected"], "D",
         "explain() compares candidate plans, showing the winning plan and the rejected ones for the query."),
        ("ADVANCED", "What is a partial index?",
         ["An index that only includes documents matching a filter", "An index on part of a field", "An index that is partially built", "An index with missing keys"], "A",
         "A partial index indexes only documents satisfying a filter expression, saving space and speeding writes."),
        ("ADVANCED", "When might MongoDB intentionally choose a collection scan even with an index available?",
         ["Never", "When the index is unique", "When the collection is very small or the index has low selectivity", "When using only $eq"], "C",
         "For tiny collections or low-selectivity indexes, scanning may be cheaper than using the index."),
        ("ADVANCED", "What is the difference between a sparse and a partial index?",
         ["They are identical", "A sparse index includes only documents with the indexed field; a partial index uses a filter expression", "Sparse indexes are faster", "Partial indexes cannot be unique"], "B",
         "Sparse indexes skip documents missing the indexed field, while partial indexes include documents matching an explicit filter."),
        ("ADVANCED", "Why should a sort field be indexed for large result sets?",
         ["It makes the sort random", "It is never needed", "It reduces memory only", "It avoids an in-memory sort that may exceed the 100 MB limit"], "D",
         "With an index matching the sort order, MongoDB streams results in order instead of sorting in memory, avoiding the 100 MB cap."),
        ("ADVANCED", "How would you create a text index on the 'title' and 'description' fields for $text search?",
         ["db.coll.createIndex({title: 'text', description: 'text'})", "db.coll.createIndex({title: 1, description: 1})", "db.coll.createTextIndex('title')", "db.coll.index({title: 'string'})"], "A",
         "Creating a text index requires the 'text' type on each field; then $text searches them together."),
        ("ADVANCED", "Which command removes an index from a collection?",
         ["deleteIndex", "removeIndex", "dropIndex", "clearIndex"], "C",
         "dropIndex removes a single index by name or key pattern."),
        ("ADVANCED", "What causes 'jumbo chunks' to become a problem in sharded collections?",
         ["Too many collections", "Low cardinality or unevenly distributed shard key values create chunks too large to split", "Text indexes in sharded clusters", "The number of mongos routers"], "B",
         "Jumbo chunks are chunks that cannot be split or migrated because their shard key range has grown too large."),
        ("ADVANCED", "Why are indexes with high cardinality preferred as the leading field of a compound index?",
         ["They consume less memory", "They are easier to create", "They can be used for text search", "They narrow the result set more effectively"], "D",
         "A leading field with many distinct values lets the index eliminate most documents early, improving query performance."),
    ],
    50: [
        ("BEGINNER", "What is a MongoDB replica set?",
         ["A group of mongod processes that maintain the same data set", "A single server holding all data", "A backup tape", "A collection of indexes"], "A",
         "A replica set is a cluster of mongod nodes that replicate the same data for high availability."),
        ("BEGINNER", "Which node in a replica set accepts all write operations?",
         ["Secondary", "Primary", "Arbiter", "Config server"], "B",
         "The primary is the only member that accepts writes; secondaries replicate from it."),
        ("BEGINNER", "What role do secondary nodes play in a replica set?",
         ["They reject all traffic", "They only store config metadata", "They replicate the primary's data and can serve reads", "They compress the database"], "C",
         "Secondaries copy the primary's oplog and can serve read operations depending on read preference."),
        ("BEGINNER", "What is an arbiter in a replica set?",
         ["A node that holds a full copy of data", "A node that acts as primary", "A mongos router", "A node that votes in elections but stores no data"], "D",
         "An arbiter participates in elections by voting but holds no data, so it cannot become primary."),
        ("BEGINNER", "What happens when the primary of a replica set fails?",
         ["An automatic election promotes a secondary to primary", "The cluster stops forever", "Writes are lost", "An arbiter takes over data"], "A",
         "When the primary becomes unreachable, the remaining nodes hold an election and promote one secondary to primary."),
        ("BEGINNER", "What is sharding in MongoDB?",
         ["Encrypting data at rest", "Distributing data across multiple servers", "Backing up the database", "Compressing documents"], "B",
         "Sharding partitions a collection's data across many mongod servers so it can scale horizontally."),
        ("BEGINNER", "What is a mongos process responsible for?",
         ["Storing all data", "Voting in elections", "Routing queries and writes to the correct shard", "Expiring documents"], "C",
         "mongos is the router that presents a unified view and forwards operations to the appropriate shards."),
        ("BEGINNER", "What is a shard key?",
         ["The encryption key for data", "The index of the _id field", "A mongos password", "A field MongoDB uses to distribute documents across shards"], "D",
         "The shard key determines how documents are distributed among shards via its value ranges."),
        ("BEGINNER", "What is a chunk in a sharded cluster?",
         ["A replica set member", "A contiguous range of shard key values stored on a shard", "A group of databases", "An index entry"], "B",
         "Chunks are ranges of shard key values; MongoDB balances them across shards as data grows."),
        ("BEGINNER", "What does a write concern specify?",
         ["How many members must acknowledge a write before it succeeds", "Which shard receives the write", "The encryption of the write", "The index used for the write"], "A",
         "Write concern defines the level of acknowledgment required, such as majority or a number of nodes."),
        ("INTERMEDIATE", "Which read preference directs all reads to secondary members of a replica set?",
         ["primary", "secondary", "nearest", "primaryPreferred"], "C",
         "readPreference 'secondary' sends reads to secondary members only, reducing primary load but risking stale data."),
        ("INTERMEDIATE", "What is the minimum recommended number of data-bearing members for a replica set?",
         ["1", "3", "5", "7"], "B",
         "Three members (or two plus an arbiter) provide redundancy and can still elect a primary if one fails."),
        ("INTERMEDIATE", "What does a write concern of w: 'majority' require?",
         ["Acknowledgment from a majority of voting members", "Acknowledgment from the primary only", "Acknowledgment from every member", "Acknowledgment from the arbiter"], "A",
         "w: 'majority' requires that more than half of the voting members acknowledge the write before it is confirmed."),
        ("INTERMEDIATE", "When a primary fails and a secondary is elected, what is this process called?",
         ["Sharding", "Compaction", "Failback", "Failover"], "D",
         "Failover is the automatic transfer of primary status to another member following a primary outage."),
        ("INTERMEDIATE", "Why is a high-cardinality shard key preferred?",
         ["It reduces index size", "It spreads data evenly across shards", "It speeds up mongos routing", "It prevents the need for indexes"], "B",
         "A shard key with many distinct values distributes documents evenly, preventing hotspots on one shard."),
        ("INTERMEDIATE", "What is a hashed shard key useful for?",
         ["Evenly distributing data when natural ranges would create hotspots", "Ordered range scans", "Text search", "TTL expiry"], "A",
         "Hashing the shard key randomizes ranges so writes spread evenly, at the cost of efficient range scans."),
        ("INTERMEDIATE", "What role do config servers play in a sharded cluster?",
         ["They store actual data", "They route queries", "They store cluster metadata such as chunk ranges", "They vote for primary"], "C",
         "Config servers store metadata describing shards, databases and chunk distributions."),
        ("INTERMEDIATE", "Which components make up a minimal sharded cluster?",
         ["One mongod", "A replica set only", "A mongos only", "Shards, a mongos router and config servers"], "D",
         "A sharded cluster needs shards (replica sets), at least one mongos router and config servers."),
        ("INTERMEDIATE", "What happens to a chunk when it exceeds the configured chunk size?",
         ["It is deleted", "It is split into smaller chunks and balanced", "It moves to the config server", "It is compressed"], "B",
         "Chunks that outgrow the size threshold are split, and the balancer migrates them across shards."),
        ("INTERMEDIATE", "What is the maximum number of members in a replica set and the maximum voting members?",
         ["50 members with up to 7 voting", "30 members with 10 voting", "100 members with 5 voting", "7 members with 50 voting"], "A",
         "A replica set supports at most 50 members, of which no more than 7 may vote in elections."),
        ("ADVANCED", "A write is acknowledged with w: 'majority' and j: true. What does j: true add?",
         ["Faster acknowledgment", "That the write is flushed to the journal before acknowledgment", "That every secondary must write to disk", "That the write is sharded"], "B",
         "j: true requires the write to be durably recorded in the journal before the write is acknowledged."),
        ("ADVANCED", "What is the difference between read concern and write concern?",
         ["They are identical", "Read concern controls failover speed", "Write concern controls which index is used", "Read concern controls read consistency and visibility; write concern controls write acknowledgment"], "D",
         "Read concern governs how current the data read must be, while write concern governs write acknowledgment and durability."),
        ("ADVANCED", "Which read preference prefers the primary but falls back to secondaries if it is unavailable?",
         ["primaryPreferred", "secondary", "secondaryPreferred", "nearest"], "A",
         "primaryPreferred reads from the primary when possible and otherwise from secondaries."),
        ("ADVANCED", "During a failover, roughly how long does it typically take for a new primary to be elected?",
         ["Instantly with no delay", "About 60 seconds minimum", "A few seconds, often up to the electionTimeoutMillis setting", "Several hours"], "C",
         "The default electionTimeoutMillis of 10 seconds bounds how long the cluster takes to detect a primary failure and elect a new one."),
        ("ADVANCED", "What problem arises when a shard key has very low cardinality (few distinct values)?",
         ["Queries become slower", "Chunks become large and uneven, causing hotspots", "Indexes stop working", "mongos cannot route"], "B",
         "With few distinct key values, only a few chunks exist, so data concentrates on one shard and creates hotspots."),
        ("ADVANCED", "Why is a monotonically increasing shard key (like a timestamp) a poor choice?",
         ["It is hard to index", "It cannot be hashed", "It uses too much memory", "New writes always target the same high-end chunk, creating a hotspot"], "D",
         "Monotonic keys concentrate inserts at the end of the key range, overloading the shard holding that chunk."),
        ("ADVANCED", "What are zone-based sharding (tags) used for?",
         ["Pinning ranges of shard key values to specific shards for locality", "Encrypting shard data", "Reducing replica set size", "Replacing config servers"], "A",
         "Tags and zones let you associate shard key ranges with specific shards, e.g., keeping a region's data close to its users."),
        ("ADVANCED", "What does the balancer do in a sharded cluster?",
         ["It votes for primaries", "It compresses data", "It migrates chunks between shards to keep them balanced", "It routes queries"], "C",
         "The balancer continually moves chunks so that no shard holds a disproportionate share of data."),
        ("ADVANCED", "A company runs a 3-member replica set with two data nodes and one arbiter. What is a key trade-off?",
         ["Arbiters hold full data copies", "If a data node fails, availability is lower and the surviving node is a single point of failure", "Arbiters become primary", "Writes are automatically durable"], "B",
         "Two data nodes plus an arbiter gives only one copy of data after a failure, reducing redundancy compared with three data nodes."),
        ("ADVANCED", "Why does MongoDB write to the oplog on the primary?",
         ["To compress data", "To vote in elections", "To balance chunks", "So secondaries can replicate the same operations"], "D",
         "The primary records every operation in the oplog, which secondaries tail and replay to keep data in sync."),
    ],
}
