# -*- coding: utf-8 -*-
"""
Question bank for subject 59: WEB106 - Advanced Web Technologies.
Category: Web & Mobile Development.

Topics:
  291: Microservices & Containerization
  292: GraphQL & API Design
  293: WebSockets & Real-time
  294: Progressive Web Apps
  295: Edge Computing & Deployment

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    291: [
        ("BEGINNER", "How would you define a microservice in a distributed system?",
         ["A small, independently deployable service that handles one business capability", "A giant monolithic application", "A database index", "A single HTML file"], "A",
         "Microservices are small, focused services that can be developed, deployed and scaled independently."),
        ("BEGINNER", "Which approach is the opposite of microservices architecture?",
         ["Monolithic architecture", "Serverless architecture", "Edge computing", "CDN caching"], "B",
         "A monolith packages all functionality into one application, the opposite of a decomposed microservice design."),
        ("BEGINNER", "Which containerisation tool bundles an app together with everything it needs to run?",
         ["Docker", "Notepad", "Excel", "Paint"], "A",
         "Docker packages apps and dependencies into containers that run consistently in any environment."),
        ("BEGINNER", "What is a container image?",
         ["A lightweight, executable package containing the app and its dependencies", "A screenshot of the app", "A backup of the database", "A network packet"], "A",
         "A container image is a static snapshot of an app with everything it needs to run."),
        ("BEGINNER", "Which tool orchestrates and manages many containers at scale?",
         ["Kubernetes", "A text editor", "A spreadsheet", "A file manager"], "A",
         "Kubernetes coordinates containers, handling scheduling, scaling and networking."),
        ("BEGINNER", "Which file defines how a Docker image is built?",
         ["Dockerfile", "README.md", "style.css", "package-lock.json only"], "A",
         "A Dockerfile contains instructions for building a container image."),
        ("BEGINNER", "What does the term 'service discovery' mean in a microservice system?",
         ["Finding where each service is running so they can talk to each other", "Searching for bugs", "Finding free disk space", "Locating the database backup"], "A",
         "Service discovery resolves how services locate each other's network addresses dynamically."),
        ("BEGINNER", "Which of the following is a benefit of microservices?",
         ["Independent scaling of individual services", "One big deployment every year", "Tight coupling of all teams", "A single shared database schema"], "A",
         "Microservices allow each service to scale, deploy and evolve independently."),
        ("BEGINNER", "What is an API gateway in a microservice architecture?",
         ["A single entry point that routes client requests to the right services", "A firewall only", "A database", "A caching layer only"], "A",
         "An API gateway fronts the services, routing, authenticating and aggregating requests."),
        ("BEGINNER", "Which term describes running multiple instances of a service to handle more load?",
         ["Horizontal scaling", "Vertical scaling", "Downsizing", "Code obfuscation"], "A",
         "Horizontal scaling adds more instances of a service to spread the load."),
        ("INTERMEDIATE", "A request in a microservice system calls service A, which calls service B. Which concern becomes important?",
         ["Managing latency, failure and timeout propagation across the call chain", "The size of the HTML", "The colour of the buttons", "The font family"], "A",
         "Chained calls introduce latency and failure modes that must be handled with timeouts and retries."),
        ("INTERMEDIATE", "Which pattern prevents a failing service from cascading failures to its callers?",
         ["Circuit breaker", "Monolithic rebuild", "Full replication", "Static caching"], "A",
         "A circuit breaker stops calls to a failing service, protecting callers from timeouts and overload."),
        ("INTERMEDIATE", "Which practice is essential for debugging distributed microservices?",
         ["Centralised logging and tracing with request IDs", "Reading logs one service at a time on paper", "Deleting all logs", "Rebooting services randomly"], "A",
         "Centralised logs and distributed tracing correlate requests across services."),
        ("INTERMEDIATE", "Two services both read and write the same customer table. Which design problem does this indicate?",
         ["Shared data ownership that couples the services and makes scaling hard", "Too much logging", "Missing CSS", "Slow internet"], "A",
         "Microservices should own their data; sharing tables couples them and breaks independence."),
        ("INTERMEDIATE", "Which deployment unit best matches the microservice principle of deploy independently?",
         ["Each service packaged and deployed on its own", "All services in one jar", "Every service in one HTML page", "All code in one branch"], "A",
         "Independent packaging and deployment per service is what makes microservices agile."),
        ("INTERMEDIATE", "Which architecture concern arises when teams deploy services on different release schedules?",
         ["Versioning and compatibility between service contracts", "The office layout", "The coffee machine", "The meeting length"], "A",
         "Different release cadences require careful versioning so services stay compatible."),
        ("INTERMEDIATE", "Which approach most improves resilience when one microservice is overloaded?",
         ["Backpressure and graceful degradation in dependent services", "Adding more HTML", "Disabling logging", "Doubling the database"], "A",
         "Backpressure lets services signal overload and degrade gracefully instead of failing hard."),
        ("INTERMEDIATE", "Which tooling practice helps teams share standard microservice building blocks?",
         ["Shared base images and service templates across teams", "Each team reinventing everything", "Hiding all configuration", "Deleting shared libraries"], "A",
         "Shared images and templates standardise security, logging and startup across services."),
        ("INTERMEDIATE", "What is the main advantage of containerising a microservice?",
         ["It runs identically on a developer laptop and in production", "It makes code longer", "It hides all bugs", "It removes the need for tests"], "A",
         "Containers eliminate environment differences so behaviour is consistent everywhere."),
        ("INTERMEDIATE", "Which design most effectively handles a long-running job in a microservice without blocking the request?",
         ["Queueing the job and returning immediately, with a worker consuming it", "Holding the HTTP request open for an hour", "Rebooting the server", "Duplicating the job"], "A",
         "Async job queues decouple request handling from long work, keeping services responsive."),
        ("ADVANCED", "Which strategy best prevents an API gateway from becoming a single point of failure?",
         ["Running multiple gateway instances behind a load balancer", "Running one gateway", "Disabling the gateway", "Hard-coding the gateway address"], "A",
         "Redundant gateway instances behind a load balancer keep the entry point highly available."),
        ("ADVANCED", "Which service-communication pattern reduces coupling between producer and consumer?",
         ["Event-driven messaging through a broker", "Direct synchronous calls to a hard-coded URL", "Shared global variables", "One big database trigger"], "A",
         "Event-driven messaging decouples producers from consumers through a durable broker."),
        ("ADVANCED", "A microservice system suffers from distributed transactions across services. Which pattern best addresses it?",
         ["Saga pattern with compensating actions", "Two-phase commit across all services", "One giant transaction", "Deleting transactions"], "A",
         "Sagas break large transactions into local transactions with compensating rollback steps."),
        ("ADVANCED", "Which practice best ensures a microservice can be debugged in production?",
         ["Structured logs, metrics and distributed trace IDs on every request", "No logging at all", "Logs only on the developer's machine", "Random console prints"], "A",
         "Structured observability with trace IDs lets engineers reconstruct requests across services."),
        ("ADVANCED", "Why might a small project still choose a monolith over microservices?",
         ["The operational overhead of many services exceeds the benefits for a small team", "Monoliths are always slower", "Microservices are illegal", "Monoliths need no code"], "A",
         "Microservices bring significant operational complexity that only pays off at a certain scale."),
        ("ADVANCED", "Which container security practice is essential in a multi-tenant cluster?",
         ["Running containers with least-privilege user accounts and read-only filesystems", "Running every container as root", "Sharing all secrets", "Disabling namespaces"], "A",
         "Least-privilege containers limit the damage if a container is compromised."),
        ("ADVANCED", "Which deployment strategy lets a new service version be validated before receiving full traffic?",
         ["Canary release of the new version to a small slice of users", "Deleting the old version", "Switching everyone instantly", "Skipping validation"], "A",
         "Canary releases expose new versions gradually, catching problems before full rollout."),
        ("ADVANCED", "Which design best keeps microservice teams autonomous?",
         ["Each team owning its service, its data and its deployment pipeline", "One team controlling everything", "A shared global database", "Monorepo-only development"], "A",
         "Full ownership of service, data and pipeline is what enables team autonomy."),
        ("ADVANCED", "Which metric best indicates the health of the whole microservice ecosystem?",
         ["The error rate and latency of end-to-end user requests across services", "The number of microservices", "The lines of code", "The number of Docker files"], "A",
         "End-to-end request health reflects the real user experience regardless of internal structure."),
        ("ADVANCED", "Which contract-testing practice best prevents integration breaks between services?",
         ["Consumer-driven contract tests that each service validates against", "Testing services only in production", "No contract at all", "Random testing"], "A",
         "Consumer-driven contracts let providers test against consumer expectations, catching breaks early."),
    ],
    292: [
        ("BEGINNER", "What is GraphQL?",
         ["A query language and runtime for APIs that lets clients request exactly what they need", "A CSS framework", "A database engine", "A hosting service"], "A",
         "GraphQL is a query language where clients specify exactly the data they want in a single request."),
        ("BEGINNER", "In GraphQL, which operation retrieves data?",
         ["Query", "Mutation", "Subscription", "Delete"], "A",
         "The query operation is used to read data in GraphQL."),
        ("BEGINNER", "Which GraphQL operation modifies data?",
         ["Mutation", "Query", "Fragment", "Scalar"], "A",
         "Mutations are the GraphQL operations used to create, update or delete data."),
        ("BEGINNER", "What does a GraphQL schema define?",
         ["The types, queries and mutations the API exposes", "The colour of the UI", "The server location", "The login page"], "A",
         "The schema is the contract describing what data and operations the API supports."),
        ("BEGINNER", "What is a GraphQL resolver?",
         ["The function that fetches data for a field", "A CSS selector", "A DNS record", "A load balancer"], "A",
         "Resolvers tell GraphQL how to obtain the value for each field."),
        ("BEGINNER", "Which GraphQL concept lets a client request only the fields it needs?",
         ["Field selection", "Fixed responses", "Server-defined projections", "URL parameters"], "A",
         "Clients select exactly which fields they want returned."),
        ("BEGINNER", "What is the single endpoint typically used by a GraphQL API?",
         ["One /graphql endpoint for all operations", "A different URL for every field", "A random port", "An FTP server"], "A",
         "GraphQL serves all queries and mutations from a single endpoint."),
        ("BEGINNER", "What is an API contract?",
         ["The agreed format and behaviour clients can rely on", "A legal employment contract", "A service-level invoice", "A server certificate"], "A",
         "An API contract defines request and response shapes that clients and servers must honour."),
        ("BEGINNER", "Which HTTP method is most commonly used for a GraphQL query?",
         ["POST", "DELETE", "PUT", "HEAD"], "A",
         "GraphQL typically uses POST, even for queries, because the query lives in the request body."),
        ("BEGINNER", "What does REST stand for?",
         ["Representational State Transfer", "Rapid Electronic Software Transfer", "Realtime Entity Storage", "Remote Execution Service Tool"], "A",
         "REST is an architectural style for building APIs around resources and HTTP verbs."),
        ("INTERMEDIATE", "A mobile client needs only three fields but the REST endpoint returns fifty. Which API design problem is this?",
         ["Over-fetching, which wastes bandwidth and battery", "Under-fetching", "Caching", "Authentication"], "A",
         "Over-fetching occurs when an API returns more data than the client needs."),
        ("INTERMEDIATE", "A client needs a user and all their posts in one round trip. Which GraphQL feature helps?",
         ["Nested queries that traverse the relationship in one request", "Multiple separate HTTP calls", "CSS animations", "Server-side rendering only"], "A",
         "GraphQL lets clients request related data in one nested query, avoiding round trips."),
        ("INTERMEDIATE", "Which GraphQL feature reduces duplication by allowing a reusable set of fields?",
         ["Fragments", "Enums", "Scalars", "Directives"], "A",
         "Fragments define reusable field sets that queries can spread to avoid repetition."),
        ("INTERMEDIATE", "How does a GraphQL schema protect clients from unknown field names?",
         ["Validation against the schema rejects unknown fields at request time", "Clients get a blank screen", "The server guesses the field", "Extra fields are ignored silently"], "A",
         "GraphQL validates queries against the schema, so unknown fields fail immediately."),
        ("INTERMEDIATE", "Which design concern is a downside of allowing arbitrarily deep GraphQL queries?",
         ["Malicious clients can create expensive, deeply nested queries", "It is too fast", "It uses too little memory", "It cannot be cached"], "A",
         "Deep nested queries can cause expensive server work, so depth and complexity limits are often needed."),
        ("INTERMEDIATE", "Which API design choice helps a versioned REST API avoid breaking existing clients?",
         ["Backwards-compatible additions such as new optional fields or new endpoints", "Deleting old endpoints", "Renaming all fields", "Changing response formats randomly"], "A",
         "Adding optional fields and new endpoints keeps existing clients working while evolving the API."),
        ("INTERMEDIATE", "Which tool is commonly used to document a REST API?",
         ["OpenAPI/Swagger", "A text file with no structure", "A whiteboard", "An email thread"], "A",
         "OpenAPI provides a standard, machine-readable description of a REST API."),
        ("INTERMEDIATE", "Which HTTP status code signals a client error such as a missing resource?",
         ["404", "200", "302", "500"], "A",
         "404 Not Found indicates the requested resource does not exist, a client-side error."),
        ("INTERMEDIATE", "Which practice helps API consumers understand pagination?",
         ["Returning next/prev cursor tokens or page metadata", "Returning all records in one response", "Hiding the page count", "Returning random slices"], "A",
         "Explicit pagination metadata lets clients navigate large collections predictably."),
        ("INTERMEDIATE", "Which GraphQL feature helps solve the N+1 query problem when resolving lists?",
         ["Data loaders that batch and deduplicate per-request queries", "Increasing the database size", "Adding more resolvers", "Disabling caching"], "A",
         "Data loaders batch field resolution, collapsing many small queries into fewer efficient ones."),
        ("ADVANCED", "Which design best protects a public GraphQL API from resource-exhaustion attacks?",
         ["Query depth, complexity and rate limits enforced at the gateway", "Unlimited queries", "No schema validation", "A single shared resolver"], "A",
         "Complexity analysis and limits prevent expensive queries from overloading the server."),
        ("ADVANCED", "Which API design decision best supports clients with heterogeneous screen sizes?",
         ["Designing endpoints to return minimal, flexible data that clients shape as needed", "Returning one giant fixed payload", "Returning only image files", "Ignoring mobile clients"], "A",
         "Flexible, minimal responses let each client fetch only what its form factor needs."),
        ("ADVANCED", "Which trade-off must a team weigh when choosing GraphQL over REST?",
         ["Flexible client queries versus added gateway complexity and caching difficulty", "REST is always worse", "GraphQL has no schema", "GraphQL cannot handle reads"], "A",
         "GraphQL's flexibility comes at the cost of more complex caching and operations."),
        ("ADVANCED", "How should a team evolve a GraphQL schema without breaking existing clients?",
         ["Add new fields and types while keeping old fields, using deprecation directives before removal", "Delete old fields immediately", "Rename everything", "Disable the schema"], "A",
         "Additive evolution with deprecation lets clients migrate gradually."),
        ("ADVANCED", "Which practice best secures a GraphQL API's sensitive fields?",
         ["Per-field authorisation checks inside resolvers", "Trusting the client to filter", "Serving all data publicly", "Hiding the schema"], "A",
         "Field-level authorisation prevents unauthorised access to sensitive data even within valid queries."),
        ("ADVANCED", "Which caching strategy works best with a typical GraphQL API?",
         ["Persisted queries and edge caching keyed on the query hash", "Disabling all caching", "Caching the entire schema", "Caching only mutations"], "A",
         "Persisted queries give cacheable identifiers, making GraphQL caching practical."),
        ("ADVANCED", "Which design best handles a REST API that must support both batch and single-item requests?",
         ["Separate collection and item endpoints with consistent semantics", "One endpoint that behaves randomly", "No endpoints", "A single POST that guesses"], "A",
         "Distinct collection and item endpoints keep the API predictable and easy to use."),
        ("ADVANCED", "Which approach best communicates API errors to clients consistently?",
         ["A structured error object with code, message and field details", "Random error strings", "Returning HTML error pages", "Silent failures"], "A",
         "Structured error responses let clients handle failures programmatically and reliably."),
        ("ADVANCED", "Which concern is most important when opening a REST API to third-party developers?",
         ["Rate limiting, quotas and clear documentation", "The number of colours", "The server's hostname", "The repository name"], "A",
         "Rate limits and documentation protect the API and make it usable by external developers."),
        ("ADVANCED", "Which measure most improves the developer experience of an API?",
         ["Interactive documentation with live examples and try-it tools", "No documentation", "Obfuscated endpoints", "Vague error messages"], "A",
         "Interactive, well-exampled documentation reduces integration time and errors."),
    ],
    293: [
        ("BEGINNER", "What does the WebSocket protocol provide?",
         ["Full-duplex communication over a single TCP connection", "A one-way email service", "A static file server", "A database query language"], "A",
         "WebSockets keep a single connection open for two-way, real-time messaging."),
        ("BEGINNER", "Which HTTP protocol upgrade initiates a WebSocket connection?",
         ["The WebSocket handshake via the Upgrade header", "A POST request", "A DNS lookup", "A TLS handshake only"], "A",
         "The client sends an HTTP Upgrade request that the server accepts to switch to WebSockets."),
        ("BEGINNER", "Which use case is best suited to WebSockets?",
         ["Live chat and real-time notifications", "Serving static images", "Search engine indexing", "Printing documents"], "A",
         "WebSockets excel at low-latency, bidirectional real-time applications like chat."),
        ("BEGINNER", "Which JavaScript API opens a WebSocket connection?",
         ["new WebSocket(url)", "fetch(url)", "XMLHttpRequest", "document.querySelector"], "A",
         "The WebSocket constructor creates a connection to the given URL."),
        ("BEGINNER", "What does 'full-duplex' mean?",
         ["Both client and server can send messages simultaneously", "Only the client can send", "Only the server can send", "Messages alternate one at a time"], "A",
         "Full-duplex means data flows in both directions at the same time on the connection."),
        ("BEGINNER", "Which event fires when a WebSocket message arrives?",
         ["onmessage", "onload", "onresize", "onclick"], "A",
         "The message event delivers incoming WebSocket data to the client."),
        ("BEGINNER", "Which statement best contrasts WebSockets with regular HTTP polling?",
         ["WebSockets keep one connection open instead of repeatedly requesting updates", "Polling is always faster", "WebSockets only work offline", "Polling needs no server"], "A",
         "WebSockets avoid the overhead of constant polling by maintaining a persistent connection."),
        ("BEGINNER", "Which protocol do WebSockets use for the initial handshake?",
         ["HTTP", "FTP", "SMTP", "DNS"], "A",
         "WebSocket connections begin with an HTTP handshake that upgrades the connection."),
        ("BEGINNER", "What is a chat message broadcast to all connected users called?",
         ["Broadcast", "Unicast only", "A join query", "A compile step"], "A",
         "Broadcasting sends a message to every connected client, common in group chat."),
        ("BEGINNER", "Which of the following is a real-time web technology similar to WebSockets?",
         ["Server-Sent Events", "FTP", "SMTP", "BitTorrent"], "A",
         "Server-Sent Events push updates one-way from server to client, another real-time option."),
        ("INTERMEDIATE", "A chat app sends a message but the user sees it twice. What is the most likely cause?",
         ["Duplicate delivery because the message was sent without an idempotency key", "The server was offline", "The font was wrong", "The screen was small"], "A",
         "Reconnect or retry logic can resend messages; idempotency keys prevent duplicates."),
        ("INTERMEDIATE", "Which challenge arises when a WebSocket server must scale across many machines?",
         ["Sticky sessions or a shared message bus so clients reach the right server", "Bigger monitors", "More colours", "Longer URLs"], "A",
         "Horizontal scaling of WebSockets needs shared state or sticky routing so sessions stay consistent."),
        ("INTERMEDIATE", "Which practice handles a dropped WebSocket connection gracefully?",
         ["Automatic reconnection with exponential backoff", "Freezing the page", "Showing a crash screen", "Uninstalling the browser"], "A",
         "Reconnection logic with backoff restores real-time updates after transient drops."),
        ("INTERMEDIATE", "Which technology helps a WebSocket server broadcast to clients connected to different nodes?",
         ["A pub/sub message broker such as Redis Pub/Sub or Kafka", "A single shared file", "Email", "A printer"], "A",
         "Pub/sub brokers relay messages between server nodes so every connected client receives broadcasts."),
        ("INTERMEDIATE", "Which message pattern lets only clients subscribed to a topic receive updates?",
         ["Publish/subscribe on a topic", "Broadcast to everyone", "Unicast to nobody", "Sending to a random client"], "A",
         "Pub/sub delivers each message only to subscribers of that topic."),
        ("INTERMEDIATE", "Which statement about the WebSocket close handshake is correct?",
         ["Either side can initiate a graceful close with a status code and reason", "Only the server can close", "Closing requires a full HTTP request", "Connections never close"], "A",
         "The close frame lets either peer end the connection cleanly with a status code."),
        ("INTERMEDIATE", "Which message type is a lightweight control frame used to keep connections alive?",
         ["Ping/pong heartbeat frames", "HTTP GET", "CSS rules", "SQL queries"], "A",
         "Ping/pong frames keep the connection alive and detect dead peers."),
        ("INTERMEDIATE", "Which problem is common when mixing WebSockets with classic load balancers?",
         ["Idle connection timeouts that close long-lived sockets", "Too much disk space", "Slow keyboards", "Dark mode issues"], "A",
         "Load balancers may time out idle connections, so settings must tolerate long-lived WebSockets."),
        ("INTERMEDIATE", "Which security concern is specific to WebSocket-based chat?",
         ["Message-level sanitisation to prevent script injection in chat content", "The screen resolution", "The login button colour", "The footer text"], "A",
         "Chat content can carry XSS payloads, so it must be sanitised before display."),
        ("INTERMEDIATE", "Which design best delivers real-time game state to thousands of players?",
         ["Sharded WebSocket gateways with a low-latency pub/sub backbone", "One giant WebSocket for everyone", "HTTP polling every second", "Email updates"], "A",
         "Sharded gateways plus a fast pub/sub backbone scale real-time broadcasting."),
        ("ADVANCED", "How should a system guarantee at-most-once or exactly-once delivery semantics over WebSockets?",
         ["By assigning message IDs and deduplicating on the receiving side", "By sending messages faster", "By using only UDP", "By ignoring duplicates"], "A",
         "Message IDs and receiver-side deduplication enforce delivery guarantees over unreliable networks."),
        ("ADVANCED", "Which strategy best recovers client state after a WebSocket reconnect?",
         ["Replaying missed messages from the last acknowledged sequence number", "Resetting all state", "Reconnecting forever", "Deleting the chat history"], "A",
         "Sequence-number replay lets clients resume exactly where they left off."),
        ("ADVANCED", "Which design decision most reduces the cost of keeping millions of connections idle?",
         ["Long-lived connections with efficient heartbeats and shared infrastructure", "More servers per connection", "Polling more often", "Sending larger frames"], "A",
         "Efficient heartbeats and pooled infrastructure keep idle connections cheap."),
        ("ADVANCED", "Which concern is critical when WebSocket traffic carries financial order data?",
         ["End-to-end encryption and ordering guarantees", "The chart colours", "The page background", "The button labels"], "A",
         "Financial data demands integrity, ordering and confidentiality over the socket."),
        ("ADVANCED", "Which approach best authenticates WebSocket connections?",
         ["Authenticating in the HTTP handshake with a token or cookie", "Trusting all connections", "Sending passwords in chat", "Disabling auth"], "A",
         "Authenticating at the upgrade handshake prevents unauthorised socket access."),
        ("ADVANCED", "Which metric best indicates the health of a real-time system?",
         ["Message delivery latency percentiles such as p95 and p99", "The number of CSS files", "The screen width", "The logo size"], "A",
         "Latency percentiles reveal the real-time experience most users actually get."),
        ("ADVANCED", "Which approach best handles backpressure when a slow client lags behind fast broadcasts?",
         ["Dropping or coalescing messages for the slow client with a reconnect path", "Sending unlimited buffers", "Stopping all traffic", "Restarting the client"], "A",
         "Backpressure strategies prevent slow clients from exhausting server memory."),
        ("ADVANCED", "Which technology choice most improves real-time collaboration in a document editor?",
         ["Operational transformation or CRDTs over the socket channel", "Saving files only at the end", "Manual copy-paste", "Reloading the page"], "A",
         "OT and CRDTs resolve concurrent edits to keep collaborators consistent in real time."),
        ("ADVANCED", "Why should a production WebSocket service be tested under network interruption?",
         ["To validate reconnection, resync and ordering behaviour under real failures", "To make tests slower", "To consume bandwidth", "To check the logo"], "A",
         "Chaos-style tests confirm clients recover cleanly when networks drop."),
        ("ADVANCED", "Which pattern best separates real-time infrastructure from business logic?",
         ["Gateway connections handling transport while an event-driven core processes messages", "Putting all logic in the socket handler", "Hard-coding chat rules", "Skipping validation"], "A",
         "Separating transport from business logic keeps the system maintainable and testable."),
    ],
    294: [
        ("BEGINNER", "What is a Progressive Web App (PWA)?",
         ["A web app that uses modern capabilities to feel like a native app", "A native iOS app", "A desktop program", "A PDF file"], "A",
         "PWAs combine web reach with native-like features such as offline support and installability."),
        ("BEGINNER", "Which technology gives a PWA offline capability?",
         ["Service workers", "CSS grids", "Cookies", "Server-side includes"], "A",
         "Service workers intercept requests and serve cached content when offline."),
        ("BEGINNER", "What is a web app manifest?",
         ["A JSON file describing the app's name, icons and display mode", "A database dump", "A CSS file", "A server config"], "A",
         "The manifest lets the browser present the PWA as an installable app."),
        ("BEGINNER", "Which property of a PWA makes it installable on a device home screen?",
         ["A valid manifest and service worker with an HTTPS context", "A long URL", "A large logo", "Many pages"], "A",
         "Installability requires a manifest, a service worker and a secure context."),
        ("BEGINNER", "Which protocol is required to register a service worker?",
         ["HTTPS", "HTTP", "FTP", "SMTP"], "A",
         "Service workers require a secure HTTPS context to work."),
        ("BEGINNER", "Which component caches assets for offline use in a PWA?",
         ["The service worker's cache API", "The HTML parser", "The DNS resolver", "The compiler"], "A",
         "The Cache API inside the service worker stores responses for offline reuse."),
        ("BEGINNER", "What is the main benefit of a PWA over a native app for many businesses?",
         ["A single codebase that works across platforms and stores", "Guaranteed higher performance", "Automatic revenue", "No internet needed ever"], "A",
         "PWAs reach every platform with one codebase, avoiding separate native builds."),
        ("BEGINNER", "Which feature does the Push API enable in a PWA?",
         ["Server-to-client notifications even when the app is closed", "Sending emails", "Database backups", "File compression"], "A",
         "The Push API delivers server messages that display as notifications."),
        ("BEGINNER", "Which lifecycle event fires when a service worker is first installed?",
         ["install", "fetch", "message", "error"], "A",
         "The install event lets the worker precache the app shell."),
        ("BEGINNER", "Which event lets a service worker intercept network requests?",
         ["fetch", "click", "scroll", "resize"], "A",
         "The fetch event handler can serve cached responses or modify requests."),
        ("INTERMEDIATE", "Which caching strategy serves a cached copy immediately and updates it from the network in the background?",
         ["Stale-while-revalidate", "Network only", "Cache only", "No caching"], "A",
         "Stale-while-revalidate returns the cache instantly and refreshes it quietly."),
        ("INTERMEDIATE", "Which strategy is best for API data that must always be fresh, such as a user's balance?",
         ["Network-first with a cache fallback", "Cache-first always", "Never cache", "Store everything in HTML"], "A",
         "Network-first gives fresh data when online while still working offline via the cache."),
        ("INTERMEDIATE", "A PWA update ships but users still see the old version. What is the most likely cause?",
         ["The old service worker controls the page until the new one activates", "The browser is broken", "The server is down", "The cache is empty"], "A",
         "New service workers only take control after install and activation, so the old one keeps serving first."),
        ("INTERMEDIATE", "Which practice best refreshes a cached PWA after a new release?",
         ["Versioning the cache and calling skipWaiting and clients.claim on activation", "Clearing cookies", "Renaming files randomly", "Rebooting the phone"], "A",
         "Versioned caches and immediate activation ensure users get the new release promptly."),
        ("INTERMEDIATE", "Which concern must a PWA handle for a good offline experience?",
         ["Gracefully showing offline state and queuing user actions", "Showing a blank screen", "Displaying errors", "Disabling the UI"], "A",
         "Good PWAs communicate offline state and buffer user actions for later sync."),
        ("INTERMEDIATE", "Which technique keeps a PWA fast by splitting code into chunks loaded on demand?",
         ["Code splitting and lazy loading", "Loading everything at once", "Using larger images", "Disabling caching"], "A",
         "Code splitting loads only what each screen needs, shrinking initial download."),
        ("INTERMEDIATE", "Which best practice ensures the app shell loads quickly on repeat visits?",
         ["Precaching the app shell HTML, CSS and JS in the service worker", "Precaching nothing", "Reloading everything from the network", "Using only inline styles"], "A",
         "Precaching the app shell gives near-instant repeat loads even offline."),
        ("INTERMEDIATE", "Which API lets a PWA store structured data offline beyond simple cache?",
         ["IndexedDB", "Cookies", "localStorage only", "URL fragments"], "A",
         "IndexedDB stores large structured data for offline, queryable access."),
        ("INTERMEDIATE", "Which audit tool helps developers verify a PWA meets installability and performance criteria?",
         ["Lighthouse", "A text counter", "A spell checker", "A screensaver"], "A",
         "Lighthouse audits PWA, performance and accessibility criteria."),
        ("INTERMEDIATE", "Which design most effectively handles offline writes that must sync later?",
         ["Queueing mutations in IndexedDB and replaying them when connectivity returns", "Dropping the writes", "Showing an error", "Storing writes in memory"], "A",
         "Offline write queues with replay preserve user actions until sync."),
        ("ADVANCED", "Which trade-off must be managed when using cache-first strategies for dynamic content?",
         ["Speed versus freshness, so content can go stale", "Speed versus security", "Freshness versus code size", "No trade-off exists"], "A",
         "Cache-first responses are fast but can serve outdated dynamic content."),
        ("ADVANCED", "Which approach best ensures a PWA receives push notifications on reconnection?",
         ["Handling push events in the service worker even when the app tab is closed", "Ignoring the push", "Only checking in-app", "Requiring the user to open the app"], "A",
         "Service worker push handlers display notifications without a foreground tab."),
        ("ADVANCED", "Which security control is essential for serving a PWA over production?",
         ["HTTPS with a valid certificate and no mixed content", "HTTP everywhere", "Trusting all certs", "No encryption"], "A",
         "A secure context is required for service workers, push and other PWA features."),
        ("ADVANCED", "Which strategy best minimises data usage for PWAs on mobile networks?",
         ["Compressing assets, cache-first policies and image optimisation", "Sending full-size videos", "Disabling compression", "Loading all images eagerly"], "A",
         "Compression and caching cut bandwidth, crucial on metered mobile connections."),
        ("ADVANCED", "Which measure best prevents stale caches from consuming unlimited storage?",
         ["Cache versioning and pruning old caches on activation", "Never deleting caches", "Storing everything forever", "Disabling the cache"], "A",
         "Versioned caches with cleanup keep storage bounded."),
        ("ADVANCED", "Which pattern best delivers an instant first paint for a PWA?",
         ["Precaching the app shell and serving it from the service worker immediately", "Waiting for the full bundle", "Showing a blank screen", "Loading fonts last"], "A",
         "An immediate shell render from the cache creates the illusion of native launch speed."),
        ("ADVANCED", "Which testing approach is essential for a PWA's offline claims?",
         ["Testing the app with the network disabled across flows", "Testing only online", "Screenshots only", "Never testing"], "A",
         "Offline-mode testing verifies the claimed offline behaviour actually works."),
        ("ADVANCED", "Which design consideration most affects a PWA's cross-device consistency?",
         ["Responsive layouts and touch-friendly interactions across screen sizes", "Fixing one layout", "Using only desktop", "Ignoring small screens"], "A",
         "Responsive, touch-friendly design keeps the PWA usable on every device."),
        ("ADVANCED", "Which practice best keeps a PWA's notifications relevant and non-abusive?",
         ["Asking for permission in context and respecting user opt-out", "Sending constant alerts", "Forcing notifications", "Hiding the unsubscribe"], "A",
         "Respectful permission and opt-out handling protect the user experience."),
        ("ADVANCED", "Which metric best reflects the real-world performance of a PWA for returning users?",
         ["Repeat-visit load time served from the service worker cache", "First-visit download only", "The number of screens", "The logo size"], "A",
         "Repeat-visit shell loads measure the cached, offline-capable experience users get most."),
    ],
    295: [
        ("BEGINNER", "How is edge computing best described?",
         ["Processing data closer to the user or device rather than in a central cloud", "Storing data on the moon", "Using only mainframes", "Removing all servers"], "A",
         "Edge computing moves computation near the data source to cut latency and bandwidth."),
        ("BEGINNER", "Which technology caches static content at servers near users?",
         ["CDN", "A database", "A compiler", "An email server"], "A",
         "Content Delivery Networks replicate content to edge servers close to users."),
        ("BEGINNER", "Which of the following is a benefit of serving content from the edge?",
         ["Lower latency for users", "Higher electricity bills", "More server downtime", "Slower page loads"], "A",
         "Edge servers reduce the physical distance data travels, lowering latency."),
        ("BEGINNER", "What is a CDN edge node?",
         ["A server placed near users to serve cached content", "A central mainframe", "A local printer", "A network cable"], "A",
         "Edge nodes are distributed servers that cache and serve content close to users."),
        ("BEGINNER", "Which static site pattern deploys the built site to edge CDN servers?",
         ["JAMstack-style static deployment", "A giant dynamic app", "A database cluster", "An email blast"], "A",
         "Static site generation plus a CDN is a classic edge deployment pattern."),
        ("BEGINNER", "Which problem does edge caching help solve?",
         ["Slow response times for geographically distant users", "Too much RAM", "Broken keyboards", "Small screens"], "A",
         "Caching at the edge brings content physically closer to users, speeding delivery."),
        ("BEGINNER", "What does 'origin server' mean in a CDN setup?",
         ["The source server that holds the canonical content", "A backup tape", "The user's browser", "The DNS server"], "A",
         "The origin is the authoritative source from which edge nodes fetch content."),
        ("BEGINNER", "Which response header helps a CDN cache a resource?",
         ["Cache-Control", "Content-Length", "Host", "User-Agent"], "A",
         "Cache-Control instructs CDNs and browsers how long a resource may be cached."),
        ("BEGINNER", "Which type of workload is least suitable for edge execution?",
         ["Huge batch analytics over petabytes in one place", "Low-latency feature flags", "Localised content delivery", "Fast API responses"], "A",
         "Massive centralised data processing is better suited to large cloud data centres than the edge."),
        ("BEGINNER", "Which deployment benefit does edge computing bring to IoT devices?",
         ["Reduced need to send all raw data to a central cloud", "Larger screens", "More batteries", "Longer cables"], "A",
         "Processing at the edge filters and reduces what must travel to the cloud."),
        ("INTERMEDIATE", "A CDN serves stale content after a deploy. Which practice forces immediate refresh?",
         ["Busting cache by purging or versioning the resource URL", "Waiting for expiry", "Disabling the CDN", "Renaming the domain"], "A",
         "Cache purging or versioned URLs ensures the new content reaches users immediately."),
        ("INTERMEDIATE", "Which edge function pattern lets developers run small bits of code near users?",
         ["Edge functions or serverless at the edge", "A single VM", "An FTP server", "A cron job on a laptop"], "A",
         "Edge functions execute small, event-driven logic at edge locations."),
        ("INTERMEDIATE", "Which technique adapts content to each user's device and network at the edge?",
         ["Device detection and dynamic delivery at the edge", "Sending the same giant file", "Ignoring device type", "Using only desktop layouts"], "A",
         "Edge delivery can tailor images and responses to each client's capabilities."),
        ("INTERMEDIATE", "Which trade-off must be considered when moving compute to the edge?",
         ["Limited resources on edge devices versus lower latency", "Unlimited resources", "Higher latency always", "No security concerns"], "A",
         "Edge devices have constrained CPU and memory compared with cloud data centres."),
        ("INTERMEDIATE", "Which concern is critical for a globally distributed edge deployment?",
         ["State consistency and where user state is stored across regions", "The logo colour", "The font size", "The email signature"], "A",
         "Distributed state must be reconciled so users see consistent data across edge regions."),
        ("INTERMEDIATE", "Which strategy most reduces bandwidth when many clients request the same popular video?",
         ["Edge caching the video at regional CDN nodes", "Streaming from one origin every time", "Emailing the video", "Disabling caching"], "A",
         "Edge caches serve popular content locally, dramatically cutting origin bandwidth."),
        ("INTERMEDIATE", "Which deployment approach lets a team change routing rules without redeploying applications?",
         ["Edge-configurable routing and feature flags", "Rewriting the whole app", "Rebooting servers", "Changing hardware"], "A",
         "Edge-level configuration provides instant, low-risk traffic and behaviour changes."),
        ("INTERMEDIATE", "Which benefit does edge rendering provide for dynamically personalised pages?",
         ["Generating personalised HTML near the user for fast delivery", "Storing one generic page", "Delaying rendering", "Disabling personalisation"], "A",
         "Edge rendering personalises pages close to the user, keeping them fast and unique."),
        ("INTERMEDIATE", "Which measure protects the origin server from being overwhelmed by traffic?",
         ["Edge caching and rate limiting at the CDN layer", "Sending all traffic to origin", "Removing rate limits", "Disabling caching"], "A",
         "Edge caching absorbs repeat requests and rate limiting protects the origin."),
        ("INTERMEDIATE", "Which architecture best serves a global audience with sub-second page loads?",
         ["A static or SSR site fronted by a CDN with edge caching", "One server in one region", "An FTP server", "A peer-to-peer email system"], "A",
         "A CDN-fronted site puts content near every user, delivering consistent low latency."),
        ("ADVANCED", "Which strategy keeps an edge deployment consistent during a live deploy?",
         ["Rolling updates across edge regions with health checks", "Switching all regions at once", "Deploying to one node only", "Skipping health checks"], "A",
         "Progressive region-by-region rollouts with health verification limit blast radius."),
        ("ADVANCED", "Which consideration most affects the choice between edge and cloud compute for a function?",
         ["The function's latency budget and the data it needs access to", "The function's colour", "The developer's location", "The repository name"], "A",
         "Latency requirements and data locality determine whether edge or cloud fits better."),
        ("ADVANCED", "Which pattern handles personalisation while still leveraging edge caching?",
         ["Caching the shell and personalising via client-side or edge logic", "Caching personalised pages for everyone", "No caching", "Serving everyone identical pages"], "A",
         "Splitting cached shells from personalised data preserves both speed and uniqueness."),
        ("ADVANCED", "Which measure most effectively mitigates a DDoS against a CDN-fronted site?",
         ["Edge-level traffic filtering and absorption by the CDN", "Letting traffic reach the origin", "Closing the website", "Disabling security"], "A",
         "CDNs absorb and filter large attack volumes before they reach the origin."),
        ("ADVANCED", "Which deployment principle most improves resilience across edge regions?",
         ["Designing regions to fail independently with automatic failover", "Tying everything to one region", "Using no failover", "Deploying once"], "A",
         "Independent, redundant regions let the system survive regional failures."),
        ("ADVANCED", "Which metric best captures the benefit of edge deployment?",
         ["Time to first byte and end-user latency measured worldwide", "The number of servers", "The code size", "The domain length"], "A",
         "Global latency metrics directly show the edge's impact on real users."),
        ("ADVANCED", "Which strategy keeps stale data from being served at the edge after a data change?",
         ["Cache invalidation triggered by origin updates", "Never invalidating", "Restarting the CDN", "Ignoring updates"], "A",
         "Origin-triggered invalidation clears stale edge copies when data changes."),
        ("ADVANCED", "Which trade-off arises when edge functions use short CPU and memory limits?",
         ["Heavy processing must be moved back to the cloud", "Processing becomes unlimited", "Latency increases everywhere", "Security improves automatically"], "A",
         "Edge functions are limited, so compute-heavy work still belongs in the cloud."),
        ("ADVANCED", "Which approach best secures edge function code and secrets?",
         ["Keeping secrets in edge-provider secret stores and validating all inputs", "Hard-coding secrets", "Shipping secrets publicly", "No validation"], "A",
         "Secret stores and input validation protect edge code from exposure and injection."),
        ("ADVANCED", "Which testing strategy best validates a global edge deployment?",
         ["Synthetic tests from multiple geographic locations measuring performance", "Testing from one office", "Screenshots only", "No monitoring"], "A",
         "Multi-region synthetic monitoring verifies real-world edge performance everywhere."),
    ],
}
