# -*- coding: utf-8 -*-
"""
Question bank for subject 56: CORE110 - Capstone Project.
Category: Core Computer Science & Emerging Technologies.
Semester: 8.

Topics:
  276: Project Planning & Scope
  277: Implementation & Development
  278: Testing & Quality Assurance
  279: Deployment & Demo
  280: Defense & Report

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    276: [
        ("BEGINNER", "Which document formally defines the objectives, deliverables and boundaries of a capstone project?",
         ["Project scope statement", "Test report", "User manual", "Bug log"], "A",
         "The project scope statement defines what the project will deliver and its boundaries, guiding all planning."),
        ("BEGINNER", "What is the term for breaking a project down into smaller manageable units of work?",
         ["Work breakdown structure", "Database schema", "Compiler pass", "Memory dump"], "A",
         "A work breakdown structure (WBS) decomposes a project into smaller, assignable deliverables and tasks."),
        ("BEGINNER", "Which planning technique identifies the shortest possible project duration through critical activities?",
         ["Critical path method", "Random scheduling", "Lazy evaluation", "Trial and error"], "A",
         "The critical path method finds the longest chain of dependent tasks that determines the shortest completion time."),
        ("BEGINNER", "What does SMART stand for in the context of setting project goals?",
         ["Specific, Measurable, Achievable, Relevant, Time-bound", "Simple, Manual, Automated, Real, Testable", "Slow, Medium, Average, Rapid, Timely", "Scope, Model, Analysis, Review, Test"], "A",
         "SMART goals are Specific, Measurable, Achievable, Relevant and Time-bound, giving clear planning targets."),
        ("BEGINNER", "Which type of project constraint typically competes directly with scope and time?",
         ["Cost or resources", "Number of users", "Screen resolution", "Font choice"], "A",
         "Cost and resources trade off against scope and schedule, forming the classic project triangle."),
        ("BEGINNER", "Which item is usually estimated first when creating a project schedule?",
         ["Task duration and dependencies", "The final grade", "The presentation theme", "The report cover"], "A",
         "A schedule is built by estimating how long each task takes and how tasks depend on each other."),
        ("BEGINNER", "What is a milestone in project planning?",
         ["A significant checkpoint marking progress", "A type of software bug", "A hardware failure", "A database index"], "A",
         "Milestones are key checkpoints that mark the completion of important phases or deliverables."),
        ("BEGINNER", "Which planning tool visually lists tasks against a timeline of bars?",
         ["Gantt chart", "Pie chart", "Scatter plot", "Word cloud"], "A",
         "A Gantt chart displays tasks as horizontal bars along a calendar timeline, making schedules easy to read."),
        ("BEGINNER", "What is a project deliverable?",
         ["A tangible output produced by the project", "A programming language", "A network protocol", "A CPU register"], "A",
         "Deliverables are concrete outputs such as code, documents or prototypes produced during the project."),
        ("BEGINNER", "Which team role is responsible for tracking tasks and keeping the project on schedule?",
         ["Project lead or manager", "Compiler", "Router", "Firewall"], "A",
         "The project lead coordinates tasks, tracks progress and keeps the team aligned with the schedule."),
        ("INTERMEDIATE", "A feature was cut from the original scope but a stakeholder insists it is added back. Which practice best handles this?",
         ["Formal change control that assesses impact before approving the change", "Silently adding it without updating the plan", "Deleting all documentation", "Refusing to talk to stakeholders"], "A",
         "Formal change control evaluates how a scope change affects cost, time and quality before approval."),
        ("INTERMEDIATE", "A task on the critical path is delayed by three days. What is the most likely effect on the project?",
         ["The overall project finish date is delayed unless the path can be compressed", "No effect on the schedule at all", "Only the documentation changes", "The budget automatically shrinks"], "A",
         "Critical path tasks have no float, so delaying one directly delays the project unless crashing or fast-tracking is used."),
        ("INTERMEDIATE", "Which estimate would be most reliable for a task very similar to one your team built last year?",
         ["Analogous estimation using the previous similar project as a baseline", "A random number guess", "Asking the shortest answer", "The number of lines of code divided by 10"], "A",
         "Analogous estimation leverages historical data from similar past work to forecast effort and duration."),
        ("INTERMEDIATE", "A team must reduce the project duration by two weeks. Which technique overlaps dependent tasks to save time?",
         ["Fast tracking", "Adding more documentation", "Deleting the test plan", "Doubling the font size"], "A",
         "Fast tracking runs normally sequential activities in parallel, trading risk for shorter schedule."),
        ("INTERMEDIATE", "Which activity belongs to the defining phase of a project rather than execution?",
         ["Writing the project plan and obtaining approval", "Compiling the final code", "Fixing last-minute bugs", "Writing the user manual"], "A",
         "Planning activities like drafting the plan and securing approval occur before execution begins."),
        ("INTERMEDIATE", "A student creates a project with a clear goal but no measurable success criteria. What is the main risk?",
         ["Success cannot be objectively verified at the end", "The code will not compile", "The database will overflow", "The network will slow down"], "A",
         "Without measurable criteria, neither the team nor evaluators can objectively judge whether the project met its goal."),
        ("INTERMEDIATE", "Which resource estimation is most useful when two team members must share one laptop?",
         ["Identifying the resource as a shared constraint in the plan", "Ignoring the constraint entirely", "Assuming everyone has infinite machines", "Buying software licences"], "A",
         "Recording resource availability and constraints lets the scheduler avoid over-allocation conflicts."),
        ("INTERMEDIATE", "What does a project risk register typically contain?",
         ["Identified risks, their likelihood, impact and mitigation plans", "A list of compiler flags", "The source code of all modules", "The password of every account"], "A",
         "A risk register logs each risk with its probability, impact and a plan to mitigate or accept it."),
        ("INTERMEDIATE", "Which of the following is a legitimate reason to revise the project plan mid-course?",
         ["A discovered dependency on an external service that changes the schedule", "Because the team is bored", "To make the document longer", "To avoid writing code"], "A",
         "Plans are living documents that should be updated when new facts, such as external dependencies, emerge."),
        ("INTERMEDIATE", "How does a good project plan help during the final evaluation?",
         ["It provides a baseline to compare actual progress against planned progress", "It replaces the need for a demo", "It hides missing features", "It guarantees a perfect score"], "A",
         "A plan acts as the baseline so evaluators can see whether the project achieved what was originally committed."),
        ("ADVANCED", "A key dependency that your whole schedule relies on is delivered two weeks late. Which action best recovers the plan?",
         ["Re-baseline the schedule, crash or fast-track remaining tasks, and inform stakeholders", "Pretend the date never changed", "Delete the dependency from records", "Ask for double credit"], "A",
         "Re-baselining with compression techniques and transparent stakeholder communication restores a realistic, defensible plan."),
        ("ADVANCED", "Which scheduling approach is most resilient when the effort for research-heavy tasks is highly uncertain?",
         ["A probabilistic method such as PERT or Monte Carlo that models optimistic, likely and pessimistic durations", "A single fixed estimate with no buffer", "Assuming every task takes exactly one day", "Never planning in advance"], "A",
         "Probabilistic techniques explicitly model uncertainty so the plan reflects the real spread of possible durations."),
        ("ADVANCED", "A sponsor requests a scope reduction to cut cost. Which aspect should you re-negotiate or review first?",
         ["The project charter and baseline scope statement", "The colour of the logo", "The number of keyboards", "The meeting room size"], "A",
         "Any scope change must be reconciled against the charter and baseline so goals, deliverables and acceptance stay aligned."),
        ("ADVANCED", "Which practice best prevents 'scope creep' in a capstone project?",
         ["A formal change control board and traceability from requirements to deliverables", "Allowing anyone to add features freely", "Never documenting decisions", "Merging all features at the last minute"], "A",
         "Change control with requirement traceability makes unapproved additions visible and prevents silent expansion of scope."),
        ("ADVANCED", "A milestone review reveals you have spent 60 percent of the budget but completed 30 percent of the work. What does this indicate?",
         ["Cost performance is over budget and the earned value is behind plan", "The project is running ahead of schedule", "The budget is under-used", "The scope grew but that is fine"], "A",
         "Earned value analysis shows that spending exceeds the value of work completed, signalling a cost and schedule problem."),
        ("ADVANCED", "Which buffer placement is most effective in a critical chain plan?",
         ["A project buffer at the end of the chain plus feeding buffers at converging paths", "Buffers at random points", "No buffers at all", "One huge buffer in the middle"], "A",
         "Critical chain methods place a project buffer at the chain end and feeding buffers at merging paths to absorb delay."),
        ("ADVANCED", "A stakeholder demands a feature that conflicts with your stated objectives. What is the best professional response?",
         ["Discuss the conflict against the scope statement and seek an agreed amendment", "Implement it secretly", "Ignore the stakeholder", "Quit the project"], "A",
         "Professionally surfacing the conflict and negotiating an amendment protects the project from uncontrolled scope change."),
        ("ADVANCED", "Which tool best supports tracking dependencies and resource assignments across a multi-module capstone?",
         ["A project management tool with a WBS, Gantt view and resource levelling", "A single sticky note", "A voice memo", "A spreadsheet with no structure"], "A",
         "Project management software tracks task dependencies and resource allocation centrally, making the plan auditable."),
        ("ADVANCED", "Why is a risk-based contingency plan superior to promising zero risk in a project plan?",
         ["It prepares the team for plausible failures and defines pre-agreed responses", "It eliminates all risk", "It removes the need for testing", "It guarantees approval"], "A",
         "Contingency planning acknowledges uncertainty and defines responses, so the team reacts quickly when risks materialise."),
        ("ADVANCED", "When compressing a schedule, which trade-off is most common when adding team members to a task?",
         ["Communication overhead grows and may slow progress beyond a point", "Cost automatically decreases", "Quality always improves", "Scope doubles"], "A",
         "Adding people adds coordination cost, so beyond a point it can slow a task rather than speed it up."),
    ],
    277: [
        ("BEGINNER", "Which version control tool is most commonly used to track changes to project source code?",
         ["Git", "Word", "Paint", "Calculator"], "A",
         "Git tracks source code changes, enabling branching, merging and a full history of edits."),
        ("BEGINNER", "Which development model builds the system in small repeating cycles with user feedback?",
         ["Agile or iterative development", "Waterfall without reviews", "Random coding", "Copy-paste development"], "A",
         "Agile development delivers in short iterations, incorporating feedback continuously."),
        ("BEGINNER", "What is a commit in version control?",
         ["A recorded snapshot of changes to the repository", "A type of SQL join", "A network packet", "A CPU cache line"], "A",
         "A commit stores a snapshot of the project files with a message describing the changes made."),
        ("BEGINNER", "Which file lists the Python packages and their versions needed by a project?",
         ["requirements.txt", "index.html", "style.css", "config.ini for network only"], "A",
         "requirements.txt declares dependencies so the project can be reproduced on other machines."),
        ("BEGINNER", "What is the main purpose of a README file in a project repository?",
         ["To explain what the project does and how to set it up", "To store the database passwords", "To replace the source code", "To log compiler errors"], "A",
         "A README introduces the project, its purpose and basic setup instructions for new users."),
        ("BEGINNER", "Which term describes a separate copy of code that can be developed independently and merged later?",
         ["A branch", "A stack frame", "A heap block", "A network segment"], "A",
         "Branches let developers work on features in isolation before merging changes back into the main line."),
        ("BEGINNER", "Which practice keeps each feature or fix small, tested and integrated frequently?",
         ["Continuous integration", "Writing all code at the end", "Never committing", "Working without backups"], "A",
         "Continuous integration merges small, frequent, tested changes to detect conflicts early."),
        ("BEGINNER", "Which term refers to writing code in small steps and checking it runs at each step?",
         ["Incremental development", "Single-shot development", "Deferred testing", "Last-minute coding"], "A",
         "Incremental development builds and verifies the system piece by piece, reducing risk."),
        ("BEGINNER", "What is a pull request used for in a typical Git workflow?",
         ["Proposing changes to be reviewed and merged", "Deleting the repository", "Rebooting the server", "Creating a database backup"], "A",
         "A pull request packages proposed changes for review, discussion and eventual merge."),
        ("BEGINNER", "Which tool is designed to manage the packages a project depends on in Python?",
         ["pip", "git", "docker compose", "cron"], "A",
         "pip installs and manages Python packages declared in a project's requirements."),
        ("INTERMEDIATE", "Two teammates edited the same file and now the merge reports conflicts. What is the correct next step?",
         ["Open the conflicted file, resolve the overlapping lines and commit the merge", "Delete the repository and restart", "Pick either version blindly", "Ignore the conflict message"], "A",
         "Merge conflicts must be resolved by editing the affected lines to a correct combined version before committing."),
        ("INTERMEDIATE", "Which Git command records the current state of changes with a descriptive message?",
         ["git commit", "git fetch", "git remote", "git rebase only"], "A",
         "git commit saves the staged changes into the repository history with a message."),
        ("INTERMEDIATE", "A feature branch has diverged from main. Which command integrates main's changes into the feature branch?",
         ["git merge main or git rebase main", "git push origin main", "git clone", "git status"], "A",
         "Merging or rebasing the feature branch onto main brings in the latest shared changes to resolve divergence."),
        ("INTERMEDIATE", "Which development practice most reduces the pain of a last-minute integration failure?",
         ["Integrating and testing changes several times per day", "Waiting for the demo day", "Coding in isolation for weeks", "Disabling all tests"], "A",
         "Frequent integration keeps the codebase in a working state and surfaces conflicts while they are still small."),
        ("INTERMEDIATE", "A teammate reports the app crashes only on their machine. Which debugging step should come first?",
         ["Compare the environment, versions and configuration between machines", "Reinstall the operating system", "Rewrite the entire app", "Blame the hardware"], "A",
         "Environment differences such as dependency versions or OS settings are the most common cause of machine-specific crashes."),
        ("INTERMEDIATE", "Which of the following is a defensive coding practice?",
         ["Validating inputs before processing them", "Ignoring error returns", "Using global variables everywhere", "Hard-coding all credentials"], "A",
         "Input validation rejects malformed or malicious data early, preventing crashes and vulnerabilities."),
        ("INTERMEDIATE", "A reviewer sees the same block of code copied into ten places. Which refactor improves it?",
         ["Extract the repeated logic into a single reusable function", "Copy it eleven times", "Delete the file", "Rename the variables randomly"], "A",
         "Extracting duplicated logic into one function removes duplication and makes maintenance easier."),
        ("INTERMEDIATE", "Which version control action uploads local commits to the shared remote repository?",
         ["git push", "git clone", "git diff", "git stash"], "A",
         "git push transfers local commits to the remote so teammates can pull and integrate them."),
        ("INTERMEDIATE", "Which practice is most effective for ensuring new code does not break existing functionality?",
         ["Running an automated test suite on every change", "Testing only on demo day", "Reviewing nothing", "Deleting old features"], "A",
         "An automated test suite run on each change catches regressions immediately after integration."),
        ("INTERMEDIATE", "A feature is complete but depends on a library version not yet approved. Which approach best reduces risk?",
         ["Pin the exact version, document it and review compatibility before merging", "Upgrade every dependency blindly", "Remove the dependency by rewriting everything", "Ignore the issue"], "A",
         "Pinning and reviewing dependency versions keeps the build reproducible and avoids surprise breakage."),
        ("ADVANCED", "A developer keeps committing generated build artifacts that cause noisy diffs. Which practice solves this cleanly?",
         ["Add the artifact paths to .gitignore and remove them from the repository", "Commit them faster", "Disable version control", "Zip them into the source tree"], "A",
         "Ignoring generated files keeps the repository clean and avoids meaningless merge conflicts."),
        ("ADVANCED", "Which Git workflow gives each feature its own branch, opens a pull request and requires reviews before merge?",
         ["GitHub Flow or a fork-and-branch workflow with mandatory reviews", "Committing directly to main", "No branching at all", "Deleting branches after every commit"], "A",
         "Branch-per-feature with reviewed pull requests protects the main branch and improves code quality."),
        ("ADVANCED", "A refactor changes internal APIs used by several modules. Which technique catches the breakage earliest?",
         ["Run the full automated test suite and fix failures before committing", "Refactor without compiling", "Announce the change on a poster", "Ask users to adapt later"], "A",
         "Running the complete test suite right after a refactor exposes broken callers while the change is fresh."),
        ("ADVANCED", "Which choice most improves the long-term maintainability of a capstone codebase?",
         ["Consistent naming, small functions and clear separation of responsibilities", "One giant file with everything", "No comments or structure", "Copying code from random sources"], "A",
         "Readable, well-structured code with clear responsibilities is far easier to debug and extend."),
        ("ADVANCED", "A critical bug found on Thursday must be fixed by Friday's demo. Which approach is most responsible?",
         ["Fix it with a targeted patch, add a regression test and verify the fix", "Remove the demo", "Hide the bug", "Rewrite the whole app overnight"], "A",
         "A minimal fix verified by a regression test resolves the issue without introducing new risk."),
        ("ADVANCED", "Which practice best demonstrates that your implementation matches the planned architecture?",
         ["Maintaining a mapping from design components to actual modules in code", "Deleting the design documents", "Renaming modules after the demo", "Hard-coding every decision"], "A",
         "Traceability between design and code lets evaluators see the architecture was actually followed."),
        ("ADVANCED", "Why is automated testing valuable when many developers contribute to one capstone project?",
         ["It gives fast, consistent feedback that manual retesting cannot match", "It removes the need for code review", "It writes the features for you", "It prevents all bugs"], "A",
         "Automated tests give every contributor immediate feedback, keeping integration quality high as the team grows."),
        ("ADVANCED", "A teammate wants to merge a large change without any tests. Which professional action is best?",
         ["Require tests and review before merging the large change", "Merge it instantly", "Approve it without looking", "Restart the repository"], "A",
         "Demanding tests and review before merging big changes protects the shared codebase from regressions."),
        ("ADVANCED", "Which technique helps trace a subtle bug that only appears after the app has run for hours?",
         ["Add structured logging with timestamps and inspect the timeline", "Reboot repeatedly", "Remove all logging", "Blindly change variables"], "A",
         "Good logging reveals the sequence of events leading to the failure, making long-running bugs reproducible."),
        ("ADVANCED", "Which metric best indicates whether the team is developing at a steady, honest pace?",
         ["Velocity measured from completed, accepted features per iteration", "Total lines of code written", "Hours spent in meetings", "Number of pull requests opened"], "A",
         "Velocity from finished, accepted work reflects real progress better than code volume or activity counts."),
    ],
    278: [
        ("BEGINNER", "Which level of testing verifies individual functions or components in isolation?",
         ["Unit testing", "Load testing", "Usability testing", "Deployment testing"], "A",
         "Unit tests exercise single functions or classes to confirm each piece works correctly on its own."),
        ("BEGINNER", "Which testing level checks that integrated modules work together?",
         ["Integration testing", "Unit testing", "Smoke testing only", "Compile checking"], "A",
         "Integration testing verifies that combined modules interact correctly through their interfaces."),
        ("BEGINNER", "What does a test case consist of in software testing?",
         ["A set of inputs, conditions and expected results used to validate a function", "A compiler warning", "A database table", "A network cable"], "A",
         "A test case defines specific inputs, preconditions and the expected outcome to validate behaviour."),
        ("BEGINNER", "Which tool is commonly used for writing unit tests in Python?",
         ["pytest or unittest", "git", "grep", "curl"], "A",
         "pytest and unittest provide frameworks to define, run and report unit tests in Python."),
        ("BEGINNER", "What does a regression test verify?",
         ["That previously fixed functionality still works after changes", "That the network is fast", "That the battery is charged", "That the font is correct"], "A",
         "Regression tests re-run past scenarios to ensure new changes did not break existing behaviour."),
        ("BEGINNER", "Which term describes testing done by the actual end users in a real environment?",
         ["Acceptance testing", "Compiler testing", "Static type checking", "Linker validation"], "A",
         "Acceptance testing lets users confirm the system meets their needs in realistic conditions."),
        ("BEGINNER", "What does a code coverage metric measure?",
         ["The percentage of code executed by the test suite", "The speed of compilation", "The number of bugs hidden", "The size of the repository"], "A",
         "Coverage measures how much of the codebase is exercised by tests, highlighting untested paths."),
        ("BEGINNER", "Which test aims to verify that the most critical user journey works after a build?",
         ["Smoke testing", "Alpha testing only", "Penetration testing only", "Database indexing"], "A",
         "Smoke tests run the key paths quickly to catch build-breaking failures before deeper testing."),
        ("BEGINNER", "Which type of test checks how the system behaves under high user load?",
         ["Load or performance testing", "Unit testing", "Code style checking", "Documentation review"], "A",
         "Load testing measures response times and stability when many users access the system at once."),
        ("BEGINNER", "What is the primary goal of testing a capstone project before submission?",
         ["To find defects and verify the system meets its requirements", "To make the demo longer", "To consume extra time", "To replace documentation"], "A",
         "Testing exists to uncover defects and confirm that the implementation satisfies the stated requirements."),
        ("INTERMEDIATE", "A test suite passes but a user still sees an error in the browser. What is the most likely gap?",
         ["Missing end-to-end or browser-level tests that cover the real user flow", "The unit tests are too many", "The code is too fast", "The database is too big"], "A",
         "Unit tests alone miss integration and browser issues, so end-to-end tests covering real flows are needed."),
        ("INTERMEDIATE", "Which testing approach should you use when two modules exchange data through a JSON API?",
         ["Integration tests that call the real API and verify the exchanged payloads", "Only UI colour checks", "Only database backups", "Only code comments"], "A",
         "Integration testing exercises the actual API boundary, catching contract mismatches between modules."),
        ("INTERMEDIATE", "Why is it important to write a test before fixing a bug?",
         ["The failing test reproduces the bug and later proves the fix", "It makes the bug disappear", "It avoids running the program", "It deletes the code"], "A",
         "A failing test captures the exact defect so the fix can be verified and future regressions caught."),
        ("INTERMEDIATE", "A test depends on a live third-party service that is sometimes down. Which practice makes the tests reliable?",
         ["Mock or stub the external service so tests run deterministically", "Run tests only on sunny days", "Ignore the failures", "Unplug the service"], "A",
         "Mocking external dependencies makes tests fast and deterministic instead of flaky."),
        ("INTERMEDIATE", "Which scenario best describes a boundary value test?",
         ["Testing values just inside and just outside a valid input range", "Testing values chosen randomly", "Testing only the middle value", "Testing no inputs at all"], "A",
         "Boundary value analysis focuses on edge cases at the edges of valid ranges where bugs cluster."),
        ("INTERMEDIATE", "A feature passes all unit tests but is slow. Which test type should be added to quantify the problem?",
         ["Performance or timing tests that measure response times under load", "More colour tests", "More comment lines", "More unit tests for speed of typing"], "A",
         "Performance tests measure timing and throughput, exposing the slowness unit tests cannot detect."),
        ("INTERMEDIATE", "Which step is essential when a test fails during a sprint?",
         ["Investigate the failure, decide if it is a code or test bug, and fix the root cause", "Mark the test as ignored forever", "Delete the test", "Reboot the machine"], "A",
         "Failing tests must be diagnosed to their root cause rather than disabled or deleted."),
        ("INTERMEDIATE", "Which metric helps decide whether enough tests have been written?",
         ["Coverage plus review of the critical paths that remain untested", "The number of test files alone", "The size of the test folder", "How tired the team is"], "A",
         "Coverage combined with a review of important untested paths gives a balanced picture of test adequacy."),
        ("INTERMEDIATE", "Which is the best order to run tests in a typical CI pipeline?",
         ["Fast unit tests first, then integration and end-to-end tests", "End-to-end first, then unit tests", "No tests at all", "Tests after release"], "A",
         "Running fast tests first gives quick feedback and catches most failures cheaply before slower tests run."),
        ("INTERMEDIATE", "A change to a shared helper breaks three unrelated modules. What testing practice would have caught this?",
         ["A comprehensive regression suite covering all dependent modules", "Testing only the helper", "No tests", "Testing only on demo day"], "A",
         "A regression suite covering dependents catches the ripple effects of shared-code changes immediately."),
        ("ADVANCED", "A flaky test passes sometimes and fails sometimes with no code change. Which is the most professional response?",
         ["Reproduce it, find the nondeterminism such as timing or shared state, and make the test deterministic", "Ignore it because it passes often", "Delete it silently", "Retry it in a loop"], "A",
         "Flaky tests must be diagnosed to their source of nondeterminism so they give trustworthy signals."),
        ("ADVANCED", "Which testing strategy best balances speed and confidence for a capstone with limited time?",
         ["A test pyramid: many fast unit tests, fewer integration tests and a small set of end-to-end tests", "Only end-to-end tests", "Only unit tests", "No tests because time is short"], "A",
         "The test pyramid concentrates on fast, reliable unit tests with a smaller layer of slower end-to-end checks."),
        ("ADVANCED", "A security-sensitive feature stores user tokens. Which test type is essential in addition to functional tests?",
         ["Security tests that attempt token theft, injection and unauthorised access", "Only layout tests", "Only speed tests", "Only backup tests"], "A",
         "Security testing attacks the feature's boundaries to reveal vulnerabilities functional tests miss."),
        ("ADVANCED", "Which practice proves the quality process itself was followed during the project?",
         ["Keeping test reports, coverage records and traceability from requirements to tests", "Deleting test logs", "Testing only in memory", "Narrating tests verbally"], "A",
         "Artifacts such as test reports and traceability matrices document that testing was systematic and verifiable."),
        ("ADVANCED", "Which defect-tracking data best helps the team decide what to fix before the demo?",
         ["Defects ranked by severity and impact on the demo-critical user journey", "The total number of typos", "The number of git branches", "The font size of logs"], "A",
         "Prioritising by severity and impact focuses scarce remaining time on what matters most to evaluators."),
        ("ADVANCED", "A heavy load test reveals the app crashes at 500 concurrent users although the target is 200. What is the correct conclusion?",
         ["The system meets its stated target and the crash point is above it, but a margin is still worth investigating", "The app is perfect", "Load testing is useless", "The target must be raised to 500"], "A",
         "Meeting the target with headroom is acceptable; the crash at 500 should still be logged and ideally improved."),
        ("ADVANCED", "Which technique isolates a bug that only appears when two test cases run together?",
         ["Check for shared mutable state and reset it between tests", "Randomise the order", "Run tests one by one forever", "Increase parallelism blindly"], "A",
         "Shared state leaking between tests is the usual cause; isolated, independent tests eliminate the interference."),
        ("ADVANCED", "Why is it valuable to automate regression tests rather than rely on manual retesting?",
         ["Automated suites run consistently and frequently, catching regressions far earlier", "Manual tests are never wrong", "Automation removes the need for design", "Automation guarantees zero bugs"], "A",
         "Automated regression suites give repeatable, fast feedback on every change, unlike manual spot checks."),
        ("ADVANCED", "A new developer asks which test to write first for an unfamiliar module. What is the best guidance?",
         ["Write a test for the module's most important public behaviour and expected edge cases", "Write a test for every private method", "Write no tests", "Copy tests from another project"], "A",
         "Focusing on critical public behaviour and its edge cases gives the best protection per unit of effort."),
        ("ADVANCED", "Which outcome indicates the testing phase is genuinely complete rather than just time-expired?",
         ["All planned tests executed, critical defects resolved and coverage targets met", "The calendar says the deadline passed", "The team is tired", "All tests are skipped"], "A",
         "Completion is defined by executed tests, resolved critical defects and coverage targets, not by the clock."),
    ],
    279: [
        ("BEGINNER", "Which activity makes a finished application ready for users to access?",
         ["Deployment", "Compilation only", "Code formatting", "Password guessing"], "A",
         "Deployment places the built application into a production environment where users can reach it."),
        ("BEGINNER", "Which tool packages an application and its dependencies into a portable unit?",
         ["Docker", "Text editor", "Spreadsheet", "Calculator"], "A",
         "Docker bundles the app and its dependencies into containers that run consistently anywhere."),
        ("BEGINNER", "What is a staging environment?",
         ["A replica of production used for final verification before release", "The developer's laptop", "A test question bank", "A backup tape"], "A",
         "A staging environment mirrors production so releases can be verified before going live."),
        ("BEGINNER", "Which term describes the running application in the environment real users access?",
         ["Production", "Development sandbox", "Compiler cache", "Source folder"], "A",
         "Production is the live environment that serves the real user base."),
        ("BEGINNER", "What is the purpose of a live demonstration?",
         ["To show the working features of the project to evaluators or stakeholders", "To hide the project", "To compile the code", "To format the drive"], "A",
         "A demo walks through working features to prove the project's functionality to the audience."),
        ("BEGINNER", "Which practice keeps application secrets out of the source code repository?",
         ["Using environment variables or a secrets manager", "Writing them in comments", "Storing them in public files", "Emailing them to everyone"], "A",
         "Environment variables and secret managers keep credentials outside the codebase where they could leak."),
        ("BEGINNER", "Which type of deployment releases the application to all users at once?",
         ["Big bang or rolling full deployment", "Canary release", "Blue-green swap", "Shadow release"], "A",
         "A big bang deployment replaces the old version with the new one for everyone simultaneously."),
        ("BEGINNER", "What is a rollback plan in deployment?",
         ["A defined procedure to return to the previous working version if a release fails", "A plan to delete the project", "A way to speed up the demo", "A method to restart the laptop"], "A",
         "A rollback plan restores the last known-good version quickly if the new release misbehaves."),
        ("BEGINNER", "Which file typically defines how a Docker container should be built?",
         ["Dockerfile", "README.txt", "style.css", "database.sql"], "A",
         "A Dockerfile contains the instructions for building a container image."),
        ("BEGINNER", "Which platform hosts containerised applications for easy deployment and scaling?",
         ["Kubernetes", "Notepad", "Paint", "File Explorer"], "A",
         "Kubernetes orchestrates containers, handling deployment, scaling and networking."),
        ("INTERMEDIATE", "Which deployment strategy gradually shifts a small percentage of users to the new version to limit risk?",
         ["Canary release", "Shutdown and restart", "Uninstall everything", "Delete the old version"], "A",
         "A canary release exposes the new version to a small subset first, expanding only if it behaves well."),
        ("INTERMEDIATE", "Which deployment strategy runs two identical environments and switches traffic between them instantly?",
         ["Blue-green deployment", "Cold backup", "Manual copying", "Rebooting the server"], "A",
         "Blue-green deployment keeps both an active and a standby environment, enabling instant, reversible switches."),
        ("INTERMEDIATE", "A demo runs on the student's laptop but fails on the evaluator's machine. What is the likely cause?",
         ["Environment differences such as dependency versions or missing services", "The evaluator's screen size", "The mouse brand", "The room lighting"], "A",
         "Environment drift is the classic reason demos fail on other machines; containers and documented setup prevent it."),
        ("INTERMEDIATE", "Which practice best ensures the demo data does not contain real user information?",
         ["Using sanitised or synthetic demo data", "Using real passwords on screen", "Showing production logs", "Streaming live user records"], "A",
         "Synthetic or anonymised demo data avoids privacy issues while still demonstrating the features."),
        ("INTERMEDIATE", "Which deployment artefact should be verified right before the final demo?",
         ["The exact build that will be shown, tested end to end in a clean environment", "A build from six months ago", "A screenshot of the code", "A verbal description"], "A",
         "Verifying the actual demo build in a clean environment prevents last-second surprises."),
        ("INTERMEDIATE", "Which step is most important when deploying to a public cloud for the first time?",
         ["Securing access, configuring firewalls and keeping credentials secret", "Disabling all security", "Making the instance world-writable", "Sharing the admin password"], "A",
         "Initial cloud deployments must lock down access and protect credentials to avoid compromise."),
        ("INTERMEDIATE", "A deployment pipeline uploads a new build, runs migrations and restarts services. What is this series of steps called?",
         ["A release pipeline or CI/CD workflow", "A unit test", "A code review", "A commit message"], "A",
         "CI/CD pipelines automate the build, test and release steps so deployments are repeatable."),
        ("INTERMEDIATE", "Which approach minimises downtime when updating a database schema during deployment?",
         ["Backwards-compatible migrations that can run without breaking the old version", "Dropping all tables first", "Stopping the app forever", "Deleting the database"], "A",
         "Forward-compatible migrations let old and new versions coexist, keeping the app available during rollout."),
        ("INTERMEDIATE", "What is the purpose of running a final dry-run demo for a teammate before the real one?",
         ["To catch technical glitches and rehearse the narrative", "To hide the project", "To waste time", "To delete the build"], "A",
         "A rehearsal surfaces glitches and smooths the presentation before the actual evaluation."),
        ("INTERMEDIATE", "Which checklist item is essential before going live with a web app?",
         ["HTTPS enabled and a valid certificate", "Removing all security", "Using HTTP for everything", "Sharing server credentials"], "A",
         "HTTPS with a valid certificate protects traffic and is a baseline requirement for production web apps."),
        ("ADVANCED", "Which deployment technique lets you run the new version in production but route only test traffic to it first?",
         ["Shadow deployment", "Deleting the old version", "Shutting everything down", "Restarting the router"], "A",
         "Shadow deployment sends a copy of real traffic to the new version to validate behaviour without user impact."),
        ("ADVANCED", "A blue-green deployment fails after traffic switches. What is the fastest safe recovery?",
         ["Switch traffic back to the previous green environment using the prepared rollback", "Rewrite the whole app", "Delete the database", "Reboot the office network"], "A",
         "The standby environment enables instant rollback, which is exactly why blue-green is chosen."),
        ("ADVANCED", "Which deployment concern most affects a capstone that must keep running for the entire demo hour?",
         ["Stability and resource limits so the app does not crash or throttle mid-demo", "The presenter's voice", "The background music", "The projector model"], "A",
         "Resource limits and stability matter because a crash mid-demo undermines the presentation."),
        ("ADVANCED", "Which practice lets a team prove deployment success objectively rather than by guesswork?",
         ["Health checks and metrics that confirm the service responds correctly", "Fixing the screen brightness", "Calling the demo 'good enough'", "Disabling monitoring"], "A",
         "Automated health checks and metrics verify a deployment actually works in the environment."),
        ("ADVANCED", "Why is a containerised deployment more reproducible than manual server setup?",
         ["The same image yields the same environment everywhere, removing configuration drift", "Containers are always faster", "Containers need no operating system", "Containers hide all bugs"], "A",
         "Reproducible container images eliminate environment drift between development and production."),
        ("ADVANCED", "A critical fix must reach production immediately without waiting for the next scheduled release. Which practice enables this?",
         ["A hotfix pipeline with automated tests that deploys the fix quickly and safely", "Waiting a month", "Emailing the database", "Deleting the production instance"], "A",
         "A hotfix pipeline lets urgent fixes go through a fast, tested path to production with controlled risk."),
        ("ADVANCED", "Which design makes a demo resilient to a failure in one backend component?",
         ["Graceful degradation and error handling so the app keeps working partially", "Crashing with a blue screen", "Hiding the error", "Disconnecting the backend"], "A",
         "Graceful degradation keeps the app usable when a component fails, making demos robust."),
        ("ADVANCED", "Which artefact most helps a future maintainer reproduce the production deployment?",
         ["Deployment scripts or IaC templates stored in the repository", "A verbal description", "A sticky note", "A password list"], "A",
         "Infrastructure-as-code and deployment scripts make the exact environment reproducible and auditable."),
        ("ADVANCED", "Why should the demo machine be prepared in advance with all services pre-started?",
         ["Avoiding cold-start delays and network timeouts that waste demo time", "Because it looks professional", "To drain the battery", "To skip the presentation"], "A",
         "Pre-warming services avoids slow cold starts and flaky network calls eating into the demo."),
        ("ADVANCED", "Which measurement tells you the deployed app actually serves users with acceptable performance?",
         ["Latency and error-rate metrics collected from the live environment", "The number of commits", "The font of the dashboard", "The length of the code"], "A",
         "Live latency and error-rate metrics reveal real user experience far better than static code measures."),
    ],
    280: [
        ("BEGINNER", "Which session lets evaluators ask questions and verify the project in person?",
         ["Project defense or viva", "A coffee break", "A code review only", "A social media post"], "A",
         "A defense is a question-and-answer session where evaluators probe the team's understanding of the project."),
        ("BEGINNER", "Which document gives a complete written account of the project's work and outcomes?",
         ["Final project report", "A text message", "A receipt", "A playlist"], "A",
         "The final report documents objectives, methodology, results and conclusions of the project."),
        ("BEGINNER", "What is the typical purpose of the presentation slides in a project defense?",
         ["To summarise the project's goals, approach and results clearly", "To display all source code", "To hide the project", "To list personal hobbies"], "A",
         "Slides structure the narrative of the defense, summarising what was built and why it matters."),
        ("BEGINNER", "Which section of a report states what the project set out to achieve?",
         ["Objectives or introduction", "Bibliography only", "Appendix of fonts", "Back cover"], "A",
         "The introduction and objectives section define the problem and the project's intended achievements."),
        ("BEGINNER", "What is plagiarism in the context of a project report?",
         ["Presenting someone else's work as your own", "Using diagrams", "Writing your own conclusions", "Citing your sources"], "A",
         "Plagiarism is taking others' work without attribution, which is an academic offence."),
        ("BEGINNER", "Which report section lists all the books, papers and websites the project used?",
         ["References or bibliography", "Table of contents", "Index of figures", "Glossary"], "A",
         "The references section credits every external source cited in the report."),
        ("BEGINNER", "Which technique helps a presenter stay on time during the defense?",
         ["Rehearsing with a timer", "Reading every slide verbatim", "Speaking without a plan", "Adding more slides at the last minute"], "A",
         "Timed rehearsals help the presenter fit the narrative into the allotted slot."),
        ("BEGINNER", "What is the role of the project guide in the defense process?",
         ["To mentor the project and often sit in the evaluation panel", "To write the report for the team", "To present in place of the team", "To grade only the slides"], "A",
         "The guide mentors the team throughout and commonly participates in evaluation discussions."),
        ("BEGINNER", "Which of the following is a key part of a good presentation opening?",
         ["A clear statement of the problem and the project's aim", "The full code listing", "A random meme", "Ten minutes of silence"], "A",
         "A strong opening states the problem and aim so the audience knows the context immediately."),
        ("BEGINNER", "Which action is most appropriate if an evaluator asks a question you cannot answer?",
         ["Admit the limitation honestly and explain what you tried or would try", "Fabricate an answer", "Stay silent forever", "Blame a teammate"], "A",
         "Honesty about limitations is respected; guessing or blame damages credibility."),
        ("INTERMEDIATE", "An evaluator asks how a particular design decision was made. Which answer is most convincing?",
         ["Explain the alternatives considered and the trade-offs that led to the choice", "Say 'it just seemed right'", "Change the topic", "Read from the source code"], "A",
         "Showing you weighed alternatives and trade-offs demonstrates genuine design thinking."),
        ("INTERMEDIATE", "Which report section best demonstrates that you validated your solution against user needs?",
         ["Testing and evaluation results tied back to the requirements", "The list of installed software", "The word count", "The cover page"], "A",
         "Testing and evaluation sections show evidence that the solution meets its requirements."),
        ("INTERMEDIATE", "Which presentation practice is most effective when discussing complex technical work?",
         ["Using simple diagrams and live demos to make the work tangible", "Reading code aloud line by line", "Using dense paragraphs", "Skipping the details entirely"], "A",
         "Diagrams and demos make technical concepts concrete and memorable for the audience."),
        ("INTERMEDIATE", "A reviewer points out a flaw in your testing approach. What is the professional response?",
         ["Acknowledge it, explain any constraints and describe how you would improve it", "Deny the flaw exists", "Ignore the comment", "Argue aggressively"], "A",
         "Constructively acknowledging weaknesses and showing how to improve shows maturity and learning."),
        ("INTERMEDIATE", "Which section of the final report should honestly discuss limitations of the work?",
         ["Conclusion and future work", "The acknowledgements", "The bibliography", "The table of contents"], "A",
         "Honest discussion of limitations and future work strengthens the report's credibility."),
        ("INTERMEDIATE", "Which practice helps the team handle tough questions during the viva?",
         ["Preparing anticipated questions and practising answers in advance", "Avoiding eye contact", "Speaking only about hobbies", "Bringing no notes"], "A",
         "Preparing for likely questions reduces surprise and improves calm, confident answers."),
        ("INTERMEDIATE", "What is the main reason to include a system architecture diagram in the report?",
         ["It shows evaluators how the components fit together at a glance", "It fills page space", "It looks decorative", "It replaces the abstract"], "A",
         "An architecture diagram communicates the overall structure clearly and efficiently."),
        ("INTERMEDIATE", "Which format best presents project results such as performance measurements?",
         ["Clear tables and charts with captions and interpretations", "A wall of raw numbers", "No results at all", "Screenshots of errors"], "A",
         "Tables and charts with interpretation make results understandable and persuasive."),
        ("INTERMEDIATE", "An evaluator asks what you learned from the project. Which answer is strongest?",
         ["A concrete reflection on technical skills and project-management lessons", "A list of course names", "A random fact", "A joke"], "A",
         "Concrete reflections on real lessons show evaluators the experience had genuine value."),
        ("INTERMEDIATE", "Which element makes a project demo compelling rather than merely functional?",
         ["A narrative that connects the feature being shown to the problem being solved", "Rapid clicking without context", "Showing only error messages", "Skipping the demo entirely"], "A",
         "A narrative linking features to the original problem makes the demo meaningful to the audience."),
        ("ADVANCED", "Which report practice best demonstrates that all claimed features are genuine?",
         ["Traceability between stated features, their implementation and the tests that verify them", "Bold claims with no evidence", "Screenshots of other apps", "Vague descriptions"], "A",
         "Traceability proves every claimed feature is implemented and verified, which is hard to fake."),
        ("ADVANCED", "An evaluator asks why the project's approach is better than an existing open-source alternative. Which answer is strongest?",
         ["A comparison of measurable trade-offs such as accuracy, cost, latency and usability", "A claim that it is better because we built it", "A shrug", "Silence"], "A",
         "Concrete, measurable comparison with existing tools shows honest, informed evaluation."),
        ("ADVANCED", "Which defense strategy best handles a question that exposes a genuine project shortcoming?",
         ["Acknowledge it, relate it to documented limitations, and explain the planned future work", "Invent a feature that fixes it", "Deflect to another topic", "End the presentation early"], "A",
         "Owning a real shortcoming and linking it to planned improvements is far more credible than deflection."),
        ("ADVANCED", "What makes the conclusion of a final report persuasive to a technical evaluator?",
         ["It restates findings supported by evidence and ties them to the original objectives", "It repeats the abstract word for word", "It lists every minor task", "It ends abruptly"], "A",
         "An evidence-backed conclusion that returns to the objectives gives a strong, coherent finish."),
        ("ADVANCED", "Which citation practice protects the team from plagiarism accusations in a technical report?",
         ["Citing every external source with an accepted referencing style such as IEEE or APA", "Copying text and adding a link", "Naming sources verbally", "Omitting all references"], "A",
         "Consistent, standard citations properly attribute all external work, preventing plagiarism claims."),
        ("ADVANCED", "A teammate cannot attend the defense at the last minute. Which preparation makes the remaining team ready?",
         ["Every member rehearsed all sections and can cover the missing person's part", "Only one member knows anything", "The slides are read-only for one person", "The missing person was the only presenter"], "A",
         "Cross-training all members on every section makes the team resilient to last-minute changes."),
        ("ADVANCED", "Which answer best demonstrates depth when an evaluator asks 'how would you scale this system?'",
         ["Discuss concrete bottlenecks such as database load and describe partitioning, caching or queues", "Say it would never need scaling", "Name a technology randomly", "Decline to answer"], "A",
         "Identifying real bottlenecks and proposing specific scaling techniques shows architectural understanding."),
        ("ADVANCED", "Why is a well-written executive summary valuable in the final report?",
         ["It lets busy evaluators grasp the project's contribution quickly and accurately", "It replaces the whole report", "It is only for decoration", "It hides the findings"], "A",
         "An executive summary conveys the essence of the project at a glance, helping evaluators orient quickly."),
        ("ADVANCED", "Which practice most strengthens the credibility of measured results in the defense?",
         ["Explaining the methodology, sample size and conditions under which the results were obtained", "Presenting results without any context", "Rounding numbers up", "Showing only the best run"], "A",
         "Transparent methodology lets evaluators judge whether the measured results are trustworthy."),
        ("ADVANCED", "During the viva an evaluator challenges your choice of tech stack. Which reply shows the strongest reasoning?",
         ["Justify the choice against the project requirements, team skills and trade-offs measured during the project", "Say the technology is popular", "Blame the guide", "Admit you never thought about it"], "A",
         "Tying the stack to requirements and measured trade-offs shows deliberate, defensible engineering decisions."),
    ],
}
