# -*- coding: utf-8 -*-
"""
Question bank for subject 24: AI104 - Data Science.
Category: Artificial Intelligence & Data Science.

Topics:
  116: Data Collection & Cleaning
  117: Data Visualization
  118: Statistical Analysis
  119: Exploratory Data Analysis
  120: Big Data & MLOps

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    116: [
        ("BEGINNER", "What is raw data?",
         ["data that has already been analyzed", "unprocessed data collected directly from a source", "data stored only in a database", "data that contains no errors"], "A",
         "Raw data refers to unprocessed, original data exactly as it was collected from its source before any transformation."),
        ("BEGINNER", "What is data cleaning primarily concerned with?",
         ["creating brand new datasets from scratch", "detecting and correcting errors and inconsistencies in data", "designing charts for a report", "training machine learning models"], "B",
         "Data cleaning focuses on fixing or removing errors, inconsistencies, and inaccuracies so the dataset is reliable for analysis."),
        ("BEGINNER", "What is a missing value in a dataset?",
         ["a value that equals zero", "a value recorded outside its expected range", "a field for which no data was recorded", "a value stored as text"], "C",
         "A missing value means no observation was recorded for that field, often represented as NaN or a blank cell."),
        ("BEGINNER", "What does the acronym CSV stand for?",
         ["Comma Separated Values", "Common Standard Values", "Character Sequence Vector", "Compressed System Variables"], "D",
         "CSV stands for Comma Separated Values, a plain-text format where each line is a record and fields are separated by commas."),
        ("BEGINNER", "Which of the following is an example of a data source?",
         ["an API endpoint that returns JSON records", "a line chart", "a decision tree", "a pivot table"], "A",
         "An API endpoint that returns JSON records is a live data source, whereas charts and trees are derived outputs."),
        ("BEGINNER", "What is data preprocessing?",
         ["the final presentation of results", "the series of steps that transform raw data into a clean usable format", "the storage of data in the cloud", "the training of a model"], "B",
         "Data preprocessing covers the steps such as cleaning, transforming, and encoding that turn raw data into a usable form."),
        ("BEGINNER", "What is a duplicate record?",
         ["a record identical to another record in the dataset", "a record with many missing fields", "a record outside the normal range", "a record encrypted for security"], "C",
         "A duplicate record is an exact or near-exact copy of another row, which can bias summaries if not removed."),
        ("BEGINNER", "Which of the following best describes structured data?",
         ["data stored in free-form paragraphs", "data organized in a predefined tabular format with rows and columns", "data collected from images", "data streamed in real time only"], "D",
         "Structured data fits neatly into a tabular format with defined rows and columns, such as a relational table."),
        ("BEGINNER", "What does it mean when a dataset has inconsistent formatting?",
         ["values representing the same thing appear in different formats", "the data contains no errors", "the data is encrypted", "the data is sorted alphabetically"], "A",
         "Inconsistent formatting means the same information appears in multiple formats, so it cannot be compared directly."),
        ("BEGINNER", "What is data imputation commonly used to address?",
         ["outlier removal", "missing values", "data encryption", "feature selection"], "B",
         "Imputation fills in missing values using statistics such as the mean, median, or mode."),
        ("INTERMEDIATE", "A sales dataset stores prices as 'USD', '$', and plain numbers. What is the best first cleaning step?",
         ["standardize the currency format to a single representation", "delete every row containing '$'", "convert the price column to text", "ignore the column in all analysis"], "A",
         "Standardizing the currency format to one representation lets every price be compared and aggregated correctly."),
        ("INTERMEDIATE", "A dataset has 5% of the age column missing. Which imputation approach is most reasonable?",
         ["delete the entire dataset", "replace missing ages with the column median", "replace every missing age with 100", "leave the missing values blank in all analysis"], "B",
         "The median is robust to skew and outliers, making it a sensible choice for imputing a numeric column like age."),
        ("INTERMEDIATE", "A date column mixes '2024-01-05', '05/01/2024', and 'January 5, 2024'. What data quality problem is this?",
         ["duplicate detection", "outlier removal", "inconsistent date formatting", "missing value handling"], "C",
         "Multiple date formats for the same concept mean the column cannot be parsed or sorted consistently until normalized."),
        ("INTERMEDIATE", "A customer table has 10,000 rows and 1,200 are exact duplicates. Which strategy is best?",
         ["keep one copy of each duplicate group after verifying they are truly identical", "keep all duplicates to preserve volume", "delete the entire table", "randomly remove 1,200 rows"], "D",
         "After confirming rows are genuinely identical, keeping one copy removes redundancy without losing information."),
        ("INTERMEDIATE", "A weight column contains negative values such as -5 kg. What should you do?",
         ["investigate whether the negatives are valid measurements or entry errors before deciding", "average them with the positive values", "convert negatives to text", "leave them untouched in every analysis"], "A",
         "The correct action is to determine the cause of the negatives, since valid negatives differ from entry errors."),
        ("INTERMEDIATE", "Which scenario is best handled by a LEFT JOIN rather than an inner join?",
         ["you only want rows present in both tables", "you want to keep all rows from the left table even without matches", "you want to merge tables without any key", "you want to remove all missing values"], "B",
         "A LEFT JOIN preserves every row of the left table, filling unmatched right-table fields with NULL."),
        ("INTERMEDIATE", "City names contain trailing spaces like 'New York   '. Which cleaning step removes them?",
         ["trimming whitespace", "normalizing case", "removing duplicates", "scaling the values"], "C",
         "Trimming removes leading and trailing whitespace so identical city names compare equal."),
        ("INTERMEDIATE", "A survey column has values 'Y', 'yes', and '1' meaning the same response. What is recommended?",
         ["keep them as three separate categories", "standardize all values to one binary representation", "delete the column", "convert all values to uppercase only"], "D",
         "Standardizing all spellings to one representation makes the column a clean binary variable for analysis."),
        ("INTERMEDIATE", "When loading a large CSV with pandas, which argument most consistently handles missing data markers?",
         ["na_values so blanks and markers are parsed as NaN", "index_col to set the index", "skipfooter to ignore footer rows", "engine to change parsing speed only"], "A",
         "The na_values argument tells pandas which strings should be treated as missing values on load."),
        ("INTERMEDIATE", "A dataset mixes temperatures in Celsius and Fahrenheit. What is the proper cleaning step?",
         ["average the two units together", "convert all values to one consistent unit before analysis", "keep both units exactly as they are", "delete the temperature data"], "B",
         "Analysis is only valid when all measurements share one unit, so every value must be converted to a single scale."),
        ("ADVANCED", "A team drops every row with missing values and the model gets worse. What is the most likely cause?",
         ["dropping rows introduced selection bias by removing a non-random subset", "models always prefer fewer rows", "missing values always improve performance", "the data no longer fits in memory"], "A",
         "Missing values are rarely missing at random, so dropping those rows can bias the remaining sample and hurt generalization."),
        ("ADVANCED", "You must clean a stream of 1 million records per hour with a strict latency budget. Which design is best?",
         ["run all cleaning as one monthly batch", "incrementally clean and validate records in the streaming pipeline as they arrive", "skip cleaning entirely to save time", "store raw data and never transform it"], "B",
         "Incremental streaming cleaning keeps latency low because each record is processed as it arrives rather than in large batches."),
        ("ADVANCED", "A column has 98% missing values. What is the most defensible decision?",
         ["impute the column with its mean", "impute the column with its mode", "drop the column because it carries almost no information and risks adding noise", "fill every value with zero"], "C",
         "A column with 98% missingness carries almost no signal and imputing it would mostly inject noise, so dropping it is defensible."),
        ("ADVANCED", "Which approach best handles outliers in a salary dataset published in a public report?",
         ["silently remove all outliers", "report both raw and outlier-adjusted statistics so the impact is visible", "replace outliers with the maximum value", "round all salaries to the nearest thousand"], "D",
         "Reporting both versions lets readers see how outliers influence the statistics instead of hiding the decision."),
        ("ADVANCED", "A pipeline fails at 2am because of malformed records. Which practice prevents silent data corruption?",
         ["schema validation that rejects malformed records early with clear alerts", "swallowing all parse errors", "writing everything to one log without checks", "increasing parallelism"], "A",
         "Early schema validation rejects malformed records at the source and raises alerts before bad data propagates downstream."),
        ("ADVANCED", "You must merge data from three legacy systems with no shared primary key. Which technique is most appropriate?",
         ["join on the name field alone", "fuzzy matching on multiple identifying fields with a confidence threshold and manual review", "random sampling of rows", "concatenating all rows into one table"], "B",
         "Without a shared key, fuzzy matching on several identifiers with a confidence threshold and human review is the standard robust approach."),
        ("ADVANCED", "A regression target has 40% missing rows that are simply dropped. Why is this a concern?",
         ["dropping target rows is always safe", "the remaining rows may not be representative, biasing the coefficient estimates", "more rows always make models worse", "missing targets cannot affect any analysis"], "C",
         "If missingness relates to the outcome, dropping those rows creates a biased sample and skews the regression estimates."),
        ("ADVANCED", "Which data quality dimension is violated when one customer appears with three different name spellings?",
         ["timeliness", "accuracy", "completeness", "consistency"], "D",
         "Consistency requires that the same entity is represented the same way; different spellings violate this dimension."),
        ("ADVANCED", "A medical dataset contains birth dates in the future. What is the best response?",
         ["flag them as invalid and investigate the root cause of the entry error before correcting", "replace them with today's date", "ignore them entirely", "subtract one year from each value"], "A",
         "Future birth dates are invalid values, so the source of the entry error must be found and corrected."),
        ("ADVANCED", "An income column mixes hourly wages and annual salaries. What is the correct cleaning strategy?",
         ["treat every value as annual income", "convert all values to a single comparable unit such as annual income", "drop the column", "sort the column and keep only the median"], "B",
         "Mixing units makes income incomparable, so all values must be converted to one unit before analysis."),
    ],
    117: [
        ("BEGINNER", "Which chart type is best for showing the distribution of a single continuous variable?",
         ["histogram", "pie chart", "line chart", "scatter plot"], "A",
         "A histogram bins the range of a continuous variable and shows how often values fall in each bin."),
        ("BEGINNER", "What is the x-axis of a standard bar chart usually called?",
         ["the legend", "the category axis", "the value axis", "the series title"], "B",
         "In a bar chart the categories are placed along the category axis, which is usually the x-axis."),
        ("BEGINNER", "Which plot is best for showing the relationship between two continuous variables?",
         ["scatter plot", "bar chart", "pie chart", "histogram"], "C",
         "A scatter plot places each observation by its two numeric coordinates, revealing relationships and patterns."),
        ("BEGINNER", "What is the purpose of a chart legend?",
         ["to identify what each series or color represents", "to display the raw data values", "to set the scale of the axes", "to compress the image size"], "D",
         "The legend maps colors, symbols, or patterns to the categories they represent so readers can decode the chart."),
        ("BEGINNER", "Which Python library is the most widely used for creating static plots?",
         ["Matplotlib", "NumPy", "SciPy", "Requests"], "A",
         "Matplotlib is the foundational plotting library in Python, and most other plotting tools build on it."),
        ("BEGINNER", "What does a pie chart divide a whole into?",
         ["bars of equal length", "segments proportional to the parts of a whole", "points along a line", "bins of equal width"], "B",
         "A pie chart slices a circle into wedges whose sizes are proportional to each category's share of the total."),
        ("BEGINNER", "What is the purpose of axis labels in a plot?",
         ["to make the plot more colorful", "to describe what each axis measures", "to store the underlying data", "to resize the figure"], "C",
         "Axis labels tell the reader what quantity and unit each axis represents."),
        ("BEGINNER", "Which chart is most appropriate for showing a trend over time?",
         ["pie chart", "histogram", "bar chart", "line chart"], "D",
         "A line chart connects observations in time order, making trends and changes easy to follow."),
        ("BEGINNER", "In a box plot, which line inside the box represents the median?",
         ["the middle line inside the box", "the top whisker end", "the bottom whisker end", "the mean point"], "A",
         "The line inside the box marks the median, the middle value of the sorted data."),
        ("BEGINNER", "What do the whiskers of a box plot show?",
         ["the exact values of all points", "the spread of data beyond the box up to typical extremes", "the number of records", "the chart title"], "B",
         "Whiskers extend from the box to the furthest data points that are not considered outliers."),
        ("INTERMEDIATE", "A bar chart with 40 categories is too cluttered to read. Which approach is best?",
         ["group rare categories into an Other bucket", "make the bars smaller", "add a 3D effect", "sort the categories randomly"], "A",
         "Binning rare categories into an Other bucket reduces clutter while preserving the important structure."),
        ("INTERMEDIATE", "A scatter plot of two variables shows a tight diagonal band. What does this suggest?",
         ["the variables are unrelated", "there is a strong linear relationship between them", "both variables are categorical", "the date encoding is wrong"], "B",
         "Points lying close to a straight diagonal indicate a strong linear association between the two variables."),
        ("INTERMEDIATE", "You need to compare the medians and spreads of five groups. Which plot is best?",
         ["a pie chart", "a single bar chart", "grouped box plots", "a histogram of all groups combined"], "C",
         "Box plots show median, quartiles, and whiskers for each group, making side-by-side comparison easy."),
        ("INTERMEDIATE", "A line chart plots monthly points at equal spacing even though the real time gaps differ. What is wrong?",
         ["the time axis should reflect the true time intervals", "line charts cannot display time", "the y-axis must be logarithmic", "nothing is wrong"], "D",
         "Equal spacing misrepresents the actual timing, so the axis must be scaled to the real intervals."),
        ("INTERMEDIATE", "Two series on one chart have very different scales. What is recommended?",
         ["use two y-axes with clear labels or separate panels", "multiply one series by a hidden constant", "plot only the larger series", "round all values to integers"], "A",
         "Dual axes or separate panels let each series use an appropriate scale without flattening the other."),
        ("INTERMEDIATE", "Sorting the bars of a bar chart from tallest to shortest makes what easier?",
         ["computing the mean", "comparing ranks", "detecting missing values", "fitting a regression line"], "B",
         "Ordered bars let the reader instantly compare which categories rank highest and lowest."),
        ("INTERMEDIATE", "Which visual encoding is most accurate for reading numeric magnitudes?",
         ["color hue", "area", "position along a common scale", "opacity"], "C",
         "Humans judge positions along a shared scale far more accurately than areas, colors, or opacity."),
        ("INTERMEDIATE", "A histogram with far too many bins shows what problem?",
         ["the bars become wide and hide detail", "the shape becomes noisy with little clear structure", "the median is removed", "the data is deleted"], "D",
         "Too many bins fragment the counts so the underlying shape is obscured by noise."),
        ("INTERMEDIATE", "In a stacked bar chart, what does the height of one segment represent?",
         ["the contribution of that category to the total of the bar", "the median of all bars", "the overall total", "the number of bins"], "A",
         "Each segment's height shows how much that category contributes to the stacked total of its bar."),
        ("INTERMEDIATE", "Which plot best shows the joint distribution of two categorical variables?",
         ["a line chart", "a heatmap of counts or proportions", "a box plot", "a single bar chart"], "B",
         "A heatmap displays the count or proportion for every combination of the two categories in a grid."),
        ("ADVANCED", "A dashboard encodes a continuous value with a rainbow colormap. Why is this a problem?",
         ["rainbow colormaps are not perceptually uniform and can mislead ordering and magnitude", "they use too few colors", "they only work for discrete data", "they cannot be rendered by browsers"], "A",
         "Perceptually non-uniform colormaps distort how differences in value are perceived, so the rainbow is discouraged."),
        ("ADVANCED", "You must show 12 months of revenue for 30 product lines on one chart. Which design is best?",
         ["a single pie chart", "small multiples with one panel per product line", "one stacked bar with 30 segments", "a 3D pie chart"], "B",
         "Small multiples let each series have its own readable panel while keeping a consistent scale for comparison."),
        ("ADVANCED", "Which chart choice is considered deceptive when comparing proportions of a whole?",
         ["a simple bar chart", "a horizontal bar chart", "a 3D pie chart", "a heatmap"], "C",
         "The 3D effect distorts segment sizes and angles, making proportions hard to compare accurately."),
        ("ADVANCED", "An analyst starts a bar chart's y-axis at 80 instead of 0 to emphasize small differences. Why is this criticized?",
         ["it makes the bars taller", "it exaggerates small differences and can mislead readers", "it always hides important data", "it changes the colors used"], "D",
         "Truncating the y-axis exaggerates visual differences, which can mislead readers about the true magnitude of change."),
        ("ADVANCED", "A time series has 50,000 points and plotting all of them produces a black mass. What is the best fix?",
         ["bin or downsample the data and plot aggregate trends", "increase the point size", "use a pie chart", "remove the time axis"], "A",
         "Downsampling or binning reduces overplotting while still conveying the overall trend and variability."),
        ("ADVANCED", "For a colorblind audience, which practice is essential in a chart?",
         ["use red and green only", "use shape or pattern in addition to color", "rely exclusively on color hue", "remove the legend"], "B",
         "Adding shapes or patterns means the chart is readable even without color distinction."),
        ("ADVANCED", "Two series have wildly different units, millions and cents. What is recommended?",
         ["merge them into one average", "use dual axes with clearly labeled scales or separate subplots", "plot only the cents series", "use a pie chart"], "C",
         "Dual axes with explicit labels or separate subplots keep each series legible on its own scale."),
        ("ADVANCED", "Which practice is the strongest guard against chartjunk and misleading visuals?",
         ["minimize non-data ink and follow the data-ink ratio", "add as many decorations as possible", "use 3D effects everywhere", "animate every chart"], "D",
         "Removing unnecessary ink keeps the focus on the data, following the data-ink ratio principle."),
        ("ADVANCED", "Why is a static chart library that saves images still valuable in an automated reporting pipeline?",
         ["it integrates easily with scheduled batch scripts and document generation", "it cannot produce any charts", "it is always slower than interactive tools", "it requires a web browser"], "A",
         "Static images are simple to embed into scheduled reports and documents without interactive infrastructure."),
        ("ADVANCED", "A map encodes a metric with bubble area, but many small values make comparison hard. What is better?",
         ["use filled regions colored by the value rather than bubble area", "make all bubbles the same size", "double the legend size", "remove the map"], "B",
         "Colored regions encode value by color intensity, avoiding the perceptual bias of comparing areas."),
    ],
    118: [
        ("BEGINNER", "What is the mean of a dataset?",
         ["the sum of all values divided by the number of values", "the middle value when the data is sorted", "the most frequently occurring value", "the largest value in the data"], "A",
         "The mean is the arithmetic average, computed by dividing the total of all values by the count."),
        ("BEGINNER", "What is the median of a dataset?",
         ["the average of all values", "the middle value when the data is sorted", "the most frequent value", "the maximum value"], "B",
         "The median is the middle value of the ordered data, splitting the dataset into two equal halves."),
        ("BEGINNER", "What is the mode of a dataset?",
         ["the mean of the data", "the middle value of the sorted data", "the value that occurs most frequently", "the difference between the largest and smallest"], "C",
         "The mode is the value that appears most often in the dataset."),
        ("BEGINNER", "What does the standard deviation measure?",
         ["the most frequent value", "the number of data points", "the middle value", "the average distance of values from the mean"], "D",
         "Standard deviation summarizes how spread out the values are around the mean."),
        ("BEGINNER", "What is the range of a dataset?",
         ["the difference between the largest and smallest values", "the average of all values", "the middle value", "the most frequent value"], "A",
         "The range is computed as the maximum minus the minimum value."),
        ("BEGINNER", "What is a population in statistics?",
         ["a small subset chosen for a study", "the entire group of individuals or items being studied", "the median value", "a sample of the data"], "B",
         "A population is the complete set of entities that the analysis is concerned with."),
        ("BEGINNER", "What is a sample in statistics?",
         ["the entire population", "the average of the data", "a subset of the population used to draw inferences", "a histogram of the data"], "C",
         "A sample is a subset drawn from the population that is used to make inferences about it."),
        ("BEGINNER", "What is the variance of a dataset?",
         ["the square root of the standard deviation", "the range divided by two", "the sum of all values", "the square of the standard deviation"], "D",
         "Variance is the average squared deviation from the mean, which equals the standard deviation squared."),
        ("BEGINNER", "What is a histogram used to estimate?",
         ["the shape of the distribution of a continuous variable", "the relationship between two variables", "the exact count of records", "the total sum of all values"], "A",
         "A histogram shows how a continuous variable is distributed across bins of values."),
        ("BEGINNER", "What is the standard error of the mean?",
         ["the mean of the sample", "the standard deviation of the sampling distribution of the mean", "the range of the sample", "the mode of the sample"], "B",
         "The standard error measures how much the sample mean varies across repeated samples."),
        ("INTERMEDIATE", "What is the mean of the values 4, 8, 6, 10, and 7?",
         ["7", "8", "6", "9"], "A",
         "The sum is 35 and there are 5 values, so 35 / 5 equals 7."),
        ("INTERMEDIATE", "What is the median of 3, 7, 1, 9, and 5?",
         ["5", "3", "7", "1"], "B",
         "Sorted as 1, 3, 5, 7, 9, the middle value is 5."),
        ("INTERMEDIATE", "What is the mode of 2, 3, 3, 5, 5, 5, and 8?",
         ["5", "3", "2", "8"], "C",
         "The value 5 occurs three times, more than any other value."),
        ("INTERMEDIATE", "A hypothesis test returns a p-value of 0.03 at the 0.05 significance level. What is the correct decision?",
         ["fail to reject the null hypothesis", "accept the null hypothesis", "declare the data invalid", "reject the null hypothesis because 0.03 is less than 0.05"], "D",
         "Because the p-value of 0.03 is below the 0.05 threshold, the result is significant and the null hypothesis is rejected."),
        ("INTERMEDIATE", "What is the range of 12, 7, 19, 3, and 21?",
         ["18", "19", "21", "12"], "A",
         "The maximum is 21 and the minimum is 3, so the range is 21 - 3 = 18."),
        ("INTERMEDIATE", "A dataset has a mean of 50 and a standard deviation of 4. How many standard deviations above the mean is the value 58?",
         ["1.5", "2", "3", "0.5"], "B",
         "The z-score is (58 - 50) / 4 = 8 / 4 = 2 standard deviations above the mean."),
        ("INTERMEDIATE", "If the standard deviation of a dataset is 5, what is its variance?",
         ["5", "10", "25", "2.5"], "C",
         "Variance is the standard deviation squared, so 5 squared equals 25."),
        ("INTERMEDIATE", "A 95% confidence interval for a mean is reported as 10 +/- 2. What does this mean?",
         ["there is a 95% chance the sample mean equals 10", "the estimation procedure will capture the population mean in about 95% of repeated samples", "95% of the data lies between 8 and 12", "the population mean is certainly 10"], "D",
         "A confidence interval describes the long-run success rate of the estimation procedure, not the probability for one specific interval."),
        ("INTERMEDIATE", "What is the interquartile range of a dataset?",
         ["the difference between the third quartile and the first quartile", "the difference between the maximum and the minimum", "the mean minus the median", "the square of the standard deviation"], "A",
         "The IQR measures the spread of the middle 50% of the data as Q3 minus Q1."),
        ("INTERMEDIATE", "A study finds a correlation of 0.9 between ice cream sales and temperature. What conclusion is justified?",
         ["ice cream sales cause higher temperatures", "there is a strong positive linear relationship between the two variables", "there is no relationship at all", "the data must be invalid"], "B",
         "A correlation of 0.9 indicates a strong positive linear association, but correlation alone does not imply causation."),
        ("ADVANCED", "A trial reports a p-value of 0.04 but a tiny effect size. Why might a statistician question the practical importance?",
         ["statistical significance does not imply practical significance, and a tiny effect may be meaningless", "p-values are always the final word", "effect sizes are irrelevant to interpretation", "a p-value below 0.05 guarantees a large effect"], "A",
         "Significance only shows the result is unlikely under the null; a tiny effect may have no real-world importance."),
        ("ADVANCED", "Which distribution best models the count of rare, independent defects in a large batch?",
         ["the uniform distribution", "the Poisson distribution", "the normal distribution", "the chi-square distribution"], "B",
         "The Poisson distribution models counts of rare events occurring independently over a fixed interval or batch."),
        ("ADVANCED", "To compare the means of two independent samples with unknown but assumed equal variances, which test is most appropriate?",
         ["the paired t-test", "the chi-square test of independence", "the independent samples t-test", "ANOVA"], "C",
         "The independent samples t-test compares two group means under the equal-variance assumption."),
        ("ADVANCED", "Why is running three separate t-tests to compare three group means worse than a single ANOVA?",
         ["t-tests run slower", "ANOVA always rejects the null", "multiple comparisons inflate the family-wise Type I error rate", "t-tests cannot be computed on groups"], "D",
         "Each t-test carries a chance of a false positive, so several tests together inflate the overall Type I error rate."),
        ("ADVANCED", "An income dataset is right-skewed with one enormous outlier. Which measure of central tendency is most robust?",
         ["the median", "the mean", "the range", "the variance"], "A",
         "The median depends only on the middle of the data, so extreme outliers barely affect it."),
        ("ADVANCED", "Which assumption is most important before running a standard t-test?",
         ["the data must be categorical", "the data should be approximately normally distributed", "the variance must be zero", "the sample size must exceed 1000"], "B",
         "The t-test assumes the data are roughly normal, especially for small samples, so the sampling distribution of the mean is well behaved."),
        ("ADVANCED", "A regression coefficient has a 95% confidence interval from 0.02 to 0.04. What does this indicate?",
         ["the effect is exactly 0.03", "the effect is definitely large", "the effect is statistically significant but small in magnitude", "the model is invalid"], "C",
         "Since the interval excludes zero the effect is significant, but the small values show the effect is weak."),
        ("ADVANCED", "According to the Central Limit Theorem, the sampling distribution of the mean becomes approximately what as the sample size grows?",
         ["normal", "uniform", "binomial", "exponential"], "D",
         "Regardless of the population's shape, the distribution of sample means approaches normality for large samples."),
        ("ADVANCED", "To compare observed and expected counts in a contingency table, which test is used?",
         ["the chi-square test of independence", "the z-test for a single mean", "the paired t-test", "linear regression"], "A",
         "The chi-square test compares observed frequencies against expected frequencies under independence."),
        ("ADVANCED", "A model has an R-squared of 0.9 in training but 0.4 on held-out data. What is the most likely explanation?",
         ["the model is underfit", "overfitting: the model memorized the training data", "R-squared always drops on test sets", "the test set is corrupted"], "B",
         "A large gap between training and test R-squared is the classic signature of overfitting."),
    ],
    119: [
        ("BEGINNER", "What is exploratory data analysis (EDA)?",
         ["the process of analyzing datasets to summarize their main characteristics, often with visuals", "the process of deploying models to production", "the process of writing user documentation", "the process of collecting data from APIs"], "A",
         "EDA is the initial investigation that uses summaries and plots to understand the structure and quirks of the data."),
        ("BEGINNER", "Which of the following is a common tool used during EDA?",
         ["summary statistics and plots", "only SQL database indexes", "only cloud storage buckets", "only network firewalls"], "B",
         "EDA relies on summary statistics and visualizations to inspect the data."),
        ("BEGINNER", "Which pandas method produces summary statistics for the numeric columns of a DataFrame?",
         ["describe()", "print()", "head()", "rename()"], "C",
         "describe() returns count, mean, standard deviation, minimum, quartiles, and maximum for numeric columns."),
        ("BEGINNER", "What does the pandas head() method return?",
         ["the last few rows of the DataFrame", "a summary of missing values", "the column names", "the first few rows of the DataFrame"], "D",
         "head() shows the first n rows, which is a quick way to peek at the data."),
        ("BEGINNER", "What is the purpose of a correlation matrix in EDA?",
         ["to show pairwise correlations between numeric variables", "to list every missing value", "to delete irrelevant columns", "to sort the rows of the data"], "A",
         "A correlation matrix displays the strength and direction of linear association between each pair of numeric variables."),
        ("BEGINNER", "Which pandas attribute shows the data type of every column?",
         ["shape", "dtypes", "sample", "dropna"], "B",
         "The dtypes attribute reports the type, such as int64 or object, for each column."),
        ("BEGINNER", "What does the shape attribute of a DataFrame return?",
         ["the sum of all values", "the mean of each column", "the number of rows and columns as a tuple", "the first row as a Series"], "C",
         "shape returns a tuple (rows, columns) describing the dimensions of the DataFrame."),
        ("BEGINNER", "What is a pair plot used for?",
         ["showing pairwise relationships between several numeric variables at once", "drawing a single pie chart", "removing outliers", "renaming columns"], "D",
         "A pair plot grids scatter plots and histograms for every pair of selected numeric variables."),
        ("BEGINNER", "What does the pandas info() method show?",
         ["a concise summary including column names, non-null counts, and data types", "the first plot", "the correlation matrix only", "the index values only"], "A",
         "info() prints a compact overview that quickly reveals missing counts and column types."),
        ("BEGINNER", "What is value_counts() most commonly used for in EDA?",
         ["computing the mean of a column", "counting the occurrences of each unique value in a column", "filling missing values", "standardizing a column"], "B",
         "value_counts() tallies how often each distinct value appears, which is essential for categorical columns."),
        ("INTERMEDIATE", "During EDA a histogram of a column shows two distinct peaks. What does this suggest?",
         ["the data may combine two subgroups or populations", "the data is perfectly uniform", "the column has zero variance", "every value is an error"], "A",
         "A bimodal distribution usually signals that the data mixes two underlying groups with different centers."),
        ("INTERMEDIATE", "Two features have a correlation of -0.95. What does this imply for modeling?",
         ["the features are independent", "one feature must be deleted at random", "the features are strongly negatively related and may cause multicollinearity", "the data cannot be modeled"], "B",
         "A correlation near -1 means the features move in opposite directions and are nearly redundant, which can inflate model variance."),
        ("INTERMEDIATE", "You find 30% of a key column is missing. Which EDA step should come first?",
         ["investigate whether the missingness is random or systematic", "delete the entire dataset", "fill the column with random numbers", "ignore the missingness"], "C",
         "Determining how and why values are missing guides whether imputation, deletion, or a model for missingness is appropriate."),
        ("INTERMEDIATE", "A scatter plot of two features shows a clear U-shaped relationship. What does this imply for a linear model?",
         ["a linear model will be perfect", "a linear model may fit poorly and a transformation could help", "the features are exact duplicates", "no analysis is possible"], "D",
         "A curved pattern violates linearity, so a linear fit is weak and transformations or nonlinear models may capture the relationship."),
        ("INTERMEDIATE", "Which visualization is most efficient for spotting outliers in many numeric columns at once?",
         ["a grid of box plots", "a single pie chart", "a line chart", "a histogram of one column"], "A",
         "Box plots mark points beyond the whiskers, so a grid of them reveals outliers across columns quickly."),
        ("INTERMEDIATE", "A categorical column has 100 distinct values. Which EDA summary is most useful first?",
         ["the mean of the column", "value_counts() to examine the frequency distribution", "a correlation matrix", "a pair plot"], "B",
         "value_counts() shows how common each category is and reveals imbalanced or near-constant categories."),
        ("INTERMEDIATE", "A column is constant across every row. What is the main implication?",
         ["it is the most important feature", "it must be one-hot encoded", "it carries no information for prediction and is often dropped", "it causes all values to be missing"], "C",
         "A constant column has zero variance, so it cannot help distinguish any outcome and is typically removed."),
        ("INTERMEDIATE", "A log transformation is most helpful for which type of variable discovered during EDA?",
         ["a right-skewed variable with a long tail", "a binary variable", "a perfectly normal variable", "a categorical variable"], "D",
         "Log transforms compress a long right tail and make strongly skewed data more symmetric."),
        ("INTERMEDIATE", "Which EDA finding best indicates a potential data leakage problem?",
         ["a feature that would not be available at prediction time", "a feature with many missing values", "a highly skewed feature", "a numeric feature with a large mean"], "A",
         "If a feature encodes future or target information, the model would look great in training but fail in production."),
        ("INTERMEDIATE", "A box plot for transaction amounts shows many points above the upper whisker. What is most appropriate?",
         ["delete them all immediately", "investigate whether they are genuine large transactions or errors", "divide them all by 1000", "leave them untouched forever"], "B",
         "High-value outliers may be legitimate, so they must be examined before any removal or transformation decision."),
        ("ADVANCED", "You have 500 features and a small dataset. Which EDA approach best identifies which features matter before modeling?",
         ["univariate and bivariate analysis combined with correlation checks and domain review", "randomly select 10 features", "train a model on all features immediately", "delete every numeric feature"], "A",
         "Systematic univariate and bivariate exploration narrows down useful features while domain knowledge validates relevance."),
        ("ADVANCED", "An anomaly in a feature appears only on certain dates. Which EDA technique would reveal this?",
         ["grouping the data by date and comparing distributions per group", "a single histogram of all data", "a correlation matrix", "dropping the date column"], "B",
         "Grouping by date lets you compare per-day distributions and spot when the anomaly appears."),
        ("ADVANCED", "To compare the distribution of a numeric feature across four customer segments, which visualization is most informative?",
         ["grouped box plots or violin plots", "a single pie chart", "one line chart", "an ungrouped scatter plot"], "C",
         "Grouped box or violin plots display the full distribution for each segment side by side."),
        ("ADVANCED", "When EDA reveals heavy multicollinearity, which downstream design decision is most justified?",
         ["keep all correlated features unchanged", "use feature selection or regularization to reduce redundant predictors", "double the number of features", "remove the target variable"], "D",
         "Reducing redundant predictors stabilizes estimates, and regularization can also handle correlated features."),
        ("ADVANCED", "House prices show a strong seasonal pattern in sales volume. How should this be captured during EDA?",
         ["plot the time series and decompose it into trend and seasonality", "ignore the date column", "convert all dates to text", "combine all dates into one group"], "A",
         "Decomposing the series separates the seasonal component so it can be modeled explicitly."),
        ("ADVANCED", "For a credit risk model, the default rate in your sample is 1%. Which key consideration arises?",
         ["the sample is too large", "class imbalance must be handled, for example with resampling or class weights", "defaults should be deleted", "no modeling is possible"], "B",
         "With 1% positives the model can trivially predict the majority class, so imbalance must be addressed explicitly."),
        ("ADVANCED", "Which set of EDA outputs most directly supports scaling one feature with MinMax but not another?",
         ["inspecting the ranges and distributions of each feature", "the correlation matrix only", "the value counts of the target", "the number of missing rows"], "C",
         "Features with very different ranges or with bounds may need scaling, which is decided by examining each distribution."),
        ("ADVANCED", "A derived feature correlates 0.999 with the target. What is the most important concern?",
         ["the feature is useless", "leakage, because the feature may encode information unavailable at prediction time", "the data is too small", "the model will underfit"], "D",
         "A near-perfect correlation often means the feature was derived from the target or future information, causing leakage."),
        ("ADVANCED", "Which ordered EDA checklist is the most sensible first pass over a dataset?",
         ["shape and dtypes, missing values, duplicates, distributions, correlations", "correlations, then everything else", "plotting everything at once", "deleting columns first"], "A",
         "Starting from structure and quality checks, then moving to distributions and relationships, catches problems early."),
        ("ADVANCED", "When preparing an EDA report for non-technical stakeholders, what is the best practice?",
         ["dump every raw table and code output", "focus on a few clear, annotated visualizations that answer their questions", "show every correlation coefficient", "skip visuals entirely"], "B",
         "Clear annotated visuals communicate findings far better than raw output for a non-technical audience."),
    ],
    120: [
        ("BEGINNER", "What three characteristics are most often used to describe big data?",
         ["volume, velocity, and variety", "speed, size, and color", "schema, index, and key", "rows, columns, and cells"], "A",
         "Big data is classically defined by volume, velocity, and variety, sometimes extended with veracity and value."),
        ("BEGINNER", "In the context of big data, what does velocity refer to?",
         ["the total amount of data", "the speed at which data is generated and processed", "the range of data types", "the accuracy of the data"], "B",
         "Velocity captures how quickly data is produced and must be processed."),
        ("BEGINNER", "Which tool is commonly used for distributed processing of very large datasets?",
         ["Apache Spark", "Microsoft Word", "Notepad", "VLC Media Player"], "C",
         "Apache Spark runs computations in parallel across a cluster, which is how very large datasets are processed."),
        ("BEGINNER", "What is a data warehouse primarily designed for?",
         ["streaming video", "rendering graphics", "compiling source code", "storing cleaned structured data for analysis and reporting"], "D",
         "A data warehouse organizes structured, often cleansed data to support business intelligence and reporting."),
        ("BEGINNER", "What does MLOps stand for?",
         ["machine learning operations", "multi-layer optimization", "matrix learning protocols", "machine logic production"], "A",
         "MLOps is the practice of applying DevOps principles to build, deploy, and maintain machine learning systems."),
        ("BEGINNER", "What is model versioning in MLOps?",
         ["deleting old models automatically", "tracking and managing different versions of a trained model", "renaming models to shorter names", "training models more quickly"], "B",
         "Model versioning records which model produced which outputs, enabling rollback and audit."),
        ("BEGINNER", "What is a batch job in data processing?",
         ["processing a single record in real time", "processing a collection of records together at scheduled intervals", "saving a file to disk", "loading a web page"], "C",
         "A batch job processes a group of records at once, typically on a schedule rather than in real time."),
        ("BEGINNER", "Which of the following is an example of unstructured data?",
         ["a table of sales records", "a CSV file with fixed columns", "a relational database table", "free-form text documents and images"], "D",
         "Unstructured data has no predefined format, such as emails, images, and free-form text."),
        ("BEGINNER", "What is the purpose of an ML pipeline?",
         ["to automate the sequence of steps from raw data to a deployed model", "to draw charts", "to clean only one column", "to store passwords"], "A",
         "An ML pipeline chains stages such as ingestion, preprocessing, training, and evaluation into an automated workflow."),
        ("BEGINNER", "What is model drift in MLOps?",
         ["when the model is retrained", "when the model is deleted", "when the performance of a deployed model degrades as the data changes", "when the model is too large to load"], "B",
         "Model drift occurs when the real-world data diverges from the training distribution, degrading predictions over time."),
        ("INTERMEDIATE", "A system must analyze millions of log lines arriving every second. Which approach is most appropriate?",
         ["stream processing that handles records as they arrive", "a nightly batch job", "manual analysis in a spreadsheet", "printing all logs to a text file"], "A",
         "Stream processing keeps up with the rate of arrival, while batch jobs would lag behind the live data."),
        ("INTERMEDIATE", "A model is retrained weekly but nobody knows which version produced last month's predictions. What is missing?",
         ["more GPUs", "model versioning and experiment tracking", "a faster internet connection", "manual retraining every day"], "B",
         "Experiment tracking and versioning record exactly which model and data produced each result."),
        ("INTERMEDIATE", "Which concept describes splitting a large dataset across many machines to process parts in parallel?",
         ["single-threaded computing", "manual copying", "distributed computing", "serial processing"], "C",
         "Distributed computing partitions data and work across nodes so large jobs finish in parallel."),
        ("INTERMEDIATE", "A model works in training but fails in production because the input format changed. Which practice prevents this?",
         ["training for more epochs", "removing all logs", "renaming the model", "input validation and monitoring in the serving layer"], "D",
         "Validating and monitoring inputs at serving time catches format changes before they corrupt predictions."),
        ("INTERMEDIATE", "What is the main difference between a data lake and a data warehouse?",
         ["a lake stores raw data in native format while a warehouse stores processed structured data", "a lake is always faster", "a warehouse stores only images", "there is no difference"], "A",
         "Data lakes preserve raw data of any type, whereas warehouses hold transformed, schema-defined data for analytics."),
        ("INTERMEDIATE", "Which component continuously delivers a trained model to a serving environment?",
         ["a text editor", "a CI/CD pipeline with automated model deployment", "a spreadsheet", "a web browser"], "B",
         "A CI/CD pipeline automates the build, test, and deployment of models to production environments."),
        ("INTERMEDIATE", "An organization has 5 TB of customer data. What benefit does Apache Spark provide over a single-machine pandas workload?",
         ["automatic data cleaning", "distributed in-memory processing across a cluster for scalability", "better looking charts", "a built-in relational database"], "C",
         "Spark scales by distributing computation across a cluster, so datasets far larger than one machine can be processed."),
        ("INTERMEDIATE", "A production model's accuracy drops from 90% to 75% over three months. Which monitoring concept applies?",
         ["overfitting during training", "underfitting", "model drift, requiring retraining with recent data", "data normalization"], "D",
         "Gradual performance decay as the world changes is model drift, which retraining on fresh data addresses."),
        ("INTERMEDIATE", "What is the purpose of a feature store in MLOps?",
         ["to provide a shared, consistent repository of engineered features for training and serving", "to host webpages", "to store raw logs only", "to compile models"], "A",
         "A feature store ensures training and serving use identical feature definitions, preventing train-serve skew."),
        ("INTERMEDIATE", "Which practice is most important for reproducible model training runs?",
         ["pinning the versions of code, data, and libraries for each run", "training on random data", "deleting old runs", "running every job manually"], "B",
         "Pinning dependencies and data snapshots means any run can be exactly reproduced later."),
        ("ADVANCED", "A bank must explain every credit decision to regulators. Which MLOps design decision is most important?",
         ["model explainability and audit trails that record inputs, outputs, and versions", "training the largest possible model", "removing all logging", "deploying only on one server"], "A",
         "Regulatory requirements demand that each decision be explainable and traceable to a specific model and inputs."),
        ("ADVANCED", "Training and serving compute a feature differently, silently corrupting predictions. What is the industry-standard fix?",
         ["compute features once in a shared feature store used by both sides", "duplicate the code by hand", "disable all validation", "use different features in each"], "B",
         "A shared feature store guarantees identical feature values in training and serving, eliminating train-serve skew."),
        ("ADVANCED", "Kafka delivers events with at-least-once semantics. Which concern follows?",
         ["duplicate events may occur and downstream logic must be idempotent", "no events ever arrive", "events are always perfectly ordered", "processing becomes impossible"], "C",
         "At-least-once delivery can replay events, so consumers must tolerate or deduplicate duplicates idempotently."),
        ("ADVANCED", "Which strategy best handles sudden spikes in inference traffic without paying for idle capacity?",
         ["buying one permanently large server", "queueing all requests forever", "rejecting all requests", "horizontal autoscaling that adds replicas based on load"], "D",
         "Horizontal autoscaling adds serving instances during spikes and removes them when load drops."),
        ("ADVANCED", "A model is retrained nightly. Why is automated drift detection with rollback important?",
         ["a bad retraining run is caught quickly and the previous model is restored", "retraining should never be monitored", "rollback is technically impossible", "drift never affects deployed models"], "A",
         "Automated monitoring flags bad runs and rollback restores the last good model to protect production users."),
        ("ADVANCED", "To guarantee a pipeline rerun from the same snapshot produces identical results, what must be controlled?",
         ["random seeds, dependency versions, and the ordering of operations", "only the file size", "the number of clusters", "the dashboard color"], "B",
         "Controlling randomness, dependency versions, and deterministic ordering makes a rerun reproducible."),
        ("ADVANCED", "Which architecture is best for a low-latency real-time recommendation service?",
         ["a nightly batch scoring job", "a precomputed model served through an optimized inference endpoint with cached features", "manual lookups in a spreadsheet", "training a new model per request"], "C",
         "Serving a prepared model through an optimized endpoint with cached features keeps response latency very low."),
        ("ADVANCED", "A platform serves models for several teams. Which practice best isolates failures and resource use?",
         ["per-team namespaces with quotas, separate services, and centralized monitoring", "one shared container with no limits", "running everything on a single process", "disabling all logging"], "D",
         "Isolated namespaces and quotas contain a team's failures and usage so they cannot affect others."),
        ("ADVANCED", "During canary deployment of a new model version, what is the purpose of routing a small fraction of traffic to it?",
         ["to compare its behavior with the stable version on live traffic before full rollout", "to save bandwidth", "to hide the model from users", "to increase overall latency"], "A",
         "A canary exposes the new model to a small slice of traffic so its live behavior can be validated before full rollout."),
        ("ADVANCED", "An organization collects unbounded IoT sensor data. Which storage choice best separates hot analysis from cold archival?",
         ["keep everything in memory", "tiered storage with fast access for recent data and cheaper storage for archives", "delete old data immediately", "store all data on tape only"], "B",
         "Tiered storage balances cost and access speed by keeping hot data fast and cold data cheap."),
    ],
}
