# -*- coding: utf-8 -*-
"""
Question bank for subject 50: CORE108 - Computer Graphics.
Category: Core Computer Science & Emerging Technologies.
Semester: 6.

Topics:
  246: Graphics Primitives & Output
  247: 2D Transformations
  248: 3D Transformations & Projections
  249: Shading & Illumination
  250: Rendering & Animation

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    246: [
        ("BEGINNER", "What is the smallest addressable unit of a display image?",
         ["A pixel", "A graphics card", "A color model", "A rendering API"], "A",
         "Pixels are the smallest elements that compose a digital image."),
        ("BEGINNER", "What does the term 'resolution' describe?",
         ["The number of pixels in a display or image", "The color depth", "The refresh rate only", "The graphics card memory"], "A",
         "Resolution refers to the pixel dimensions of a display or image."),
        ("BEGINNER", "Which of the following is a basic graphics primitive?",
         ["Line", "Spreadsheet", "Database", "Font file"], "A",
         "Lines, points, circles, and polygons are fundamental graphics primitives."),
        ("BEGINNER", "What does the DDA algorithm do?",
         ["Digitizes a line into pixel positions", "Compresses images", "Applies shading", "Renders 3D models"], "A",
         "DDA (Digital Differential Analyzer) computes pixel coordinates along a line."),
        ("BEGINNER", "What is a frame buffer?",
         ["Memory that holds the image to be displayed", "A video cable", "A monitor setting", "A graphics file format"], "A",
         "The frame buffer stores pixel data for the display."),
        ("BEGINNER", "Which device displays graphics output?",
         ["Monitor", "Keyboard", "Mouse", "Scanner"], "A",
         "Monitors render the graphical output of the computer."),
        ("BEGINNER", "What is the standard color model for displays?",
         ["RGB", "CMYK", "HSI", "YUV"], "A",
         "Displays use the additive RGB (red, green, blue) color model."),
        ("BEGINNER", "What does a raster display use to form an image?",
         ["A grid of pixels", "Continuous lines", "Only text", "Vector paths"], "A",
         "Raster displays draw images as a grid of pixels."),
        ("BEGINNER", "What is a vector graphic?",
         ["An image defined by mathematical shapes and lines", "An image made of pixels", "A video frame", "A font"], "A",
         "Vector graphics use geometric primitives that scale without quality loss."),
        ("BEGINNER", "Which of the following is a graphics API?",
         ["OpenGL", "SQL", "HTML", "HTTP"], "A",
         "OpenGL is a widely used graphics programming API."),
        ("INTERMEDIATE", "Which line algorithm uses integer arithmetic and is efficient for rasterization?",
         ["Bresenham's line algorithm", "DDA only", "Random sampling", "Recursive subdivision"], "A",
         "Bresenham's algorithm uses only integer operations, making it fast."),
        ("INTERMEDIATE", "What is aliasing in computer graphics?",
         ["The jagged staircase effect on diagonal lines", "Smooth rendering", "Color blending", "Hidden surface removal"], "A",
         "Aliasing appears as jagged edges because pixels are discrete."),
        ("INTERMEDIATE", "What is anti-aliasing used for?",
         ["To smooth jagged edges by blending pixel intensities", "To increase resolution", "To remove colors", "To speed up rendering"], "A",
         "Anti-aliasing shades edge pixels to reduce the staircase effect."),
        ("INTERMEDIATE", "What does scan conversion of a primitive mean?",
         ["Converting a geometric primitive into pixel positions", "Converting pixels to vectors", "Compressing a frame", "Rendering 3D objects"], "A",
         "Scan conversion rasterizes shapes into display pixels."),
        ("INTERMEDIATE", "Which circle algorithm is efficient because it uses only integer arithmetic?",
         ["Midpoint circle algorithm", "Random point plotting", "Exhaustive sampling", "DDA circle only"], "A",
         "The midpoint algorithm draws circles using integer decisions."),
        ("INTERMEDIATE", "What is color depth?",
         ["The number of bits used to represent each pixel's color", "The number of pixels", "The screen size", "The refresh rate"], "A",
         "Higher color depth allows more distinct colors per pixel."),
        ("INTERMEDIATE", "Which of the following is a common polygon fill technique?",
         ["Scanline filling", "Random filling", "Pixel doubling", "Vector compression"], "A",
         "Scanline algorithms fill polygons row by row."),
        ("INTERMEDIATE", "What does a refresh rate of 60 Hz mean?",
         ["The display redraws 60 times per second", "The screen has 60 colors", "The resolution is 60 pixels", "The GPU runs at 60 watts"], "A",
         "Refresh rate measures how often the display updates per second."),
        ("INTERMEDIATE", "Which operation clips a primitive to a viewport boundary?",
         ["Clipping", "Scaling", "Translation", "Rotation"], "A",
         "Clipping removes portions of primitives outside the clipping region."),
        ("INTERMEDIATE", "What is the purpose of the Cohen-Sutherland algorithm?",
         ["To clip lines against a rectangular region", "To fill polygons", "To shade surfaces", "To rasterize circles"], "A",
         "Cohen-Sutherland efficiently clips lines using region codes."),
        ("ADVANCED", "What is the main disadvantage of the DDA line algorithm?",
         ["It uses floating-point arithmetic and rounding", "It cannot draw lines", "It is too complex", "It only draws vertical lines"], "A",
         "DDA relies on floating-point increments, which are slower and accumulate error."),
        ("ADVANCED", "Why is Bresenham's algorithm preferred on many hardware platforms?",
         ["It uses only integer arithmetic, avoiding floating-point cost", "It draws perfect curves", "It needs no memory", "It works for 3D only"], "A",
         "Integer-only computation is faster and simpler to implement in hardware."),
        ("ADVANCED", "What is supersampling anti-aliasing?",
         ["Sampling at higher resolution and averaging down to reduce aliasing", "Deleting pixels", "Increasing frame rate", "Reducing color depth"], "A",
         "Supersampling computes multiple samples per pixel and averages them."),
        ("ADVANCED", "What does the Liang-Barsky algorithm improve over Cohen-Sutherland?",
         ["It computes parametric clipping more efficiently", "It fills polygons", "It shades models", "It animates objects"], "A",
         "Liang-Barsky uses the parametric line form for faster clipping."),
        ("ADVANCED", "Which problem does the midpoint circle algorithm exploit for efficiency?",
         ["Symmetry of the circle across its axes", "Random sampling", "Brute-force plotting", "Floating-point evaluation"], "A",
         "Circle symmetry reduces computation to one octant."),
        ("ADVANCED", "What is the purpose of z-buffering in rasterization?",
         ["To store depth values for hidden surface removal", "To store colors only", "To compress the frame", "To adjust brightness"], "A",
         "The z-buffer compares depths to determine which surfaces are visible."),
        ("ADVANCED", "What is the difference between rasterization and vector rendering?",
         ["Rasterization converts to pixels; vector rendering draws mathematical primitives", "They are identical", "Rasterization never uses pixels", "Vector rendering always blurs"], "A",
         "Raster displays need pixel conversion while vector output uses shapes."),
        ("ADVANCED", "Which technique reduces the memory needed for a frame buffer?",
         ["Using indexed colors with a color lookup table", "Increasing color depth", "Doubling resolution", "Storing raw RGB only"], "A",
         "Indexed color stores a palette index per pixel instead of full RGB."),
        ("ADVANCED", "What does 'double buffering' prevent in graphics?",
         ["Flickering by drawing to an off-screen buffer before swapping", "Aliasing", "Color loss", "Slow rendering"], "A",
         "Double buffering builds the next frame off-screen and swaps it in cleanly."),
        ("ADVANCED", "Which scan conversion issue causes overlapping polygons to flicker?",
         ["Inconsistent fill rules and ordering", "Too much color", "High resolution", "Small pixels"], "A",
         "Proper polygon ordering and fill rules prevent render artifacts."),
    ],
    247: [
        ("BEGINNER", "What is translation in 2D graphics?",
         ["Moving an object by adding offsets to its coordinates", "Rotating an object", "Scaling an object", "Shearing an object"], "A",
         "Translation shifts an object by constant x and y offsets."),
        ("BEGINNER", "What is rotation in 2D graphics?",
         ["Turning an object about a point by an angle", "Moving an object", "Resizing an object", "Reflecting an object"], "A",
         "Rotation changes the orientation of an object about a pivot."),
        ("BEGINNER", "What is scaling in 2D graphics?",
         ["Changing the size of an object by multiplying coordinates", "Moving an object", "Rotating an object", "Clipping an object"], "A",
         "Scaling multiplies coordinates by scale factors."),
        ("BEGINNER", "Which transformation flips an object across an axis?",
         ["Reflection", "Translation", "Rotation", "Shearing"], "A",
         "Reflection mirrors an object across a line."),
        ("BEGINNER", "What is a transformation matrix?",
         ["A matrix that encodes a geometric transformation", "A color palette", "A pixel array", "A rendering buffer"], "A",
         "Transformation matrices apply translations, rotations, and scaling."),
        ("BEGINNER", "What does homogeneous coordinates add to 2D coordinates?",
         ["An extra coordinate used to represent transformations uniformly", "A color channel", "A depth value", "A texture id"], "A",
         "Homogeneous coordinates allow translation to be represented as a matrix multiplication."),
        ("BEGINNER", "What is shearing in 2D graphics?",
         ["Slanting an object by shifting one axis proportionally to another", "Moving an object", "Scaling an object", "Rotating an object"], "A",
         "Shearing distorts an object by shifting coordinates along an axis."),
        ("BEGINNER", "Which transformation changes an object's orientation?",
         ["Rotation", "Translation", "Scaling", "Reflection"], "A",
         "Rotation changes orientation while preserving size and shape."),
        ("BEGINNER", "Which transformation changes an object's size?",
         ["Scaling", "Rotation", "Translation", "Reflection"], "A",
         "Scaling changes dimensions along axes."),
        ("BEGINNER", "What is the identity matrix in transformations?",
         ["The transformation that leaves coordinates unchanged", "A scaling matrix", "A rotation matrix", "A shear matrix"], "A",
         "The identity matrix produces no change when applied."),
        ("INTERMEDIATE", "What is the result of applying translation by (3, 2) to the point (1, 1)?",
         ["(4, 3)", "(2, 3)", "(3, 1)", "(1, 2)"], "A",
         "Adding offsets gives (1+3, 1+2) = (4, 3)."),
        ("INTERMEDIATE", "Which matrix operation allows combining several transformations?",
         ["Matrix multiplication", "Matrix addition", "Matrix division", "Element-wise sum"], "A",
         "Sequential transformations multiply into a single combined matrix."),
        ("INTERMEDIATE", "What is the order effect of matrix multiplication for transformations?",
         ["Order matters; different orders give different results", "Order never matters", "Only scaling commutes", "Rotations always cancel"], "A",
         "Transformations generally do not commute, so order changes the outcome."),
        ("INTERMEDIATE", "Which transformation can be represented with a 2x2 matrix but not translation?",
         ["Translation requires homogeneous 3x3 representation", "Rotation", "Reflection", "Scaling"], "A",
         "Translation needs an extra dimension because it uses addition, not just linear mapping."),
        ("INTERMEDIATE", "What is the effect of scaling with a negative factor?",
         ["It flips the object while scaling it", "It has no effect", "It rotates the object 90 degrees", "It only changes color"], "A",
         "Negative scale factors reflect the object."),
        ("INTERMEDIATE", "Rotation by 90 degrees clockwise about the origin maps (x, y) to:",
         ["(y, -x)", "(-y, x)", "(x, -y)", "(-x, y)"], "A",
         "Clockwise 90-degree rotation sends (x, y) to (y, -x)."),
        ("INTERMEDIATE", "What does a composite transformation represent?",
         ["A single matrix combining multiple transformations", "A color conversion", "A pixel filter", "A frame buffer"], "A",
         "Composite matrices apply several transforms in one step."),
        ("INTERMEDIATE", "Which of these transformations is linear in 2D?",
         ["Rotation", "Translation", "All of them are always linear", "Perspective projection"], "A",
         "Rotation is a linear transformation representable by a 2x2 matrix."),
        ("INTERMEDIATE", "What is the inverse of a rotation matrix?",
         ["The rotation matrix by the negative angle", "Its transpose scaled by 2", "The identity always", "A translation matrix"], "A",
         "Rotating back by the opposite angle reverses the rotation."),
        ("INTERMEDIATE", "Which transformation preserves the shape of an object?",
         ["Rigid (translation and rotation)", "Non-uniform scaling", "Shearing", "Projection"], "A",
         "Rigid transformations preserve distances and shape."),
        ("ADVANCED", "Why are homogeneous coordinates used in 2D graphics?",
         ["To represent translation as matrix multiplication and unify all transforms", "To add color depth", "To store textures", "To speed the refresh rate"], "A",
         "Homogeneous coordinates let every affine transform be a single matrix multiply."),
        ("ADVANCED", "To rotate an object about an arbitrary point, the correct sequence is:",
         ["Translate to origin, rotate, translate back", "Rotate then translate only", "Scale then rotate", "Translate then scale"], "A",
         "Moving the pivot to the origin, rotating, and translating back rotates about the point."),
        ("ADVANCED", "What is the difference between an affine and a perspective transformation?",
         ["Affine preserves parallelism; perspective does not", "Perspective preserves size", "Affine uses 4D", "They are identical"], "A",
         "Affine maps preserve parallel lines, while perspective changes them."),
        ("ADVANCED", "The composition order 'T then R' versus 'R then T' typically:",
         ["Produces different resulting positions", "Produces identical results", "Only affects color", "Cancels the transformations"], "A",
         "Applying translation before rotation differs from rotating before translating."),
        ("ADVANCED", "Which matrix represents a 2D scaling by factors (2, 3)?",
         ["[[2,0],[0,3]]", "[[3,0],[0,2]]", "[[1,2],[3,1]]", "[[2,3],[0,0]]"], "A",
         "A diagonal scaling matrix has the scale factors on its diagonal."),
        ("ADVANCED", "What is the purpose of a composite matrix for animation?",
         ["To compute an object's position from its components each frame", "To store textures", "To compress frames", "To remove colors"], "A",
         "Composite matrices efficiently update object transforms per frame."),
        ("ADVANCED", "What is a transformation matrix's determinant sign indicating?",
         ["Whether the transformation includes a reflection", "The rotation angle", "The scaling value", "The translation offset"], "A",
         "A negative determinant signals a reflection or orientation change."),
        ("ADVANCED", "Which of these is a rigid body transformation?",
         ["Rotation", "Non-uniform scaling", "Shearing", "Perspective projection"], "A",
         "Rotation preserves shape and size, making it rigid."),
        ("ADVANCED", "What does the last row [0 0 1] of a 2D homogeneous matrix encode?",
         ["The affine structure that preserves the w coordinate", "A color channel", "The depth", "The texture id"], "A",
         "The bottom row keeps the transformation affine."),
        ("ADVANCED", "Which transformation cannot be undone by a simple inverse for 3D rendering?",
         ["Perspective projection, which loses depth information", "Rotation", "Translation", "Uniform scaling"], "A",
         "Projection discards depth, so it cannot be exactly inverted."),
    ],
    248: [
        ("BEGINNER", "How many coordinates does a 3D point have?",
         ["Three (x, y, z)", "Two (x, y)", "Four (x, y, z, w)", "One"], "A",
         "3D space is described by x, y, and z coordinates."),
        ("BEGINNER", "Which axis typically represents depth in 3D graphics?",
         ["Z axis", "X axis", "Y axis", "No axis"], "A",
         "The z-axis commonly represents depth in a 3D scene."),
        ("BEGINNER", "What is perspective projection?",
         ["Projecting 3D points to a 2D plane simulating depth and distance", "Removing an object", "Rotating a scene", "Scaling uniformly"], "A",
         "Perspective projection makes far objects appear smaller."),
        ("BEGINNER", "What is orthographic projection?",
         ["Projecting 3D points to 2D without perspective foreshortening", "Adding depth effects", "Applying textures", "Shading surfaces"], "A",
         "Orthographic projection preserves parallel lines and sizes."),
        ("BEGINNER", "What is the 'viewing plane'?",
         ["The 2D plane onto which a 3D scene is projected", "The GPU", "The frame buffer", "The color depth"], "A",
         "The viewing plane is where the projected image is formed."),
        ("BEGINNER", "Which of the following is a 3D transformation?",
         ["3D rotation", "Scan conversion", "Anti-aliasing", "Clipping only"], "A",
         "3D rotation turns objects about a 3D axis."),
        ("BEGINNER", "What is the role of a camera in 3D graphics?",
         ["To define the viewpoint from which the scene is rendered", "To store textures", "To compress frames", "To shade objects"], "A",
         "The camera sets the position and orientation of the view."),
        ("BEGINNER", "What does a projection matrix do?",
         ["Maps 3D coordinates onto the 2D view plane", "Adds color", "Deletes polygons", "Increases resolution"], "A",
         "Projection matrices transform 3D vertices into screen space."),
        ("BEGINNER", "Which object is defined by vertices, edges, and faces?",
         ["A 3D polygonal mesh", "A pixel", "A color model", "A frame buffer"], "A",
         "Polygonal meshes represent 3D surfaces using vertices and faces."),
        ("BEGINNER", "What is a vertex in 3D graphics?",
         ["A point in 3D space defining part of a model", "A color channel", "A texture file", "A display device"], "A",
         "Vertices are the corner points of 3D geometry."),
        ("INTERMEDIATE", "Which projection shows objects with true size regardless of distance?",
         ["Orthographic projection", "Perspective projection", "Fish-eye projection", "Oblique only"], "A",
         "Orthographic projection preserves measurements by ignoring distance."),
        ("INTERMEDIATE", "What happens to objects farther from the camera in perspective projection?",
         ["They appear smaller", "They appear larger", "They disappear", "They stay the same size"], "A",
         "Perspective divides by depth, shrinking distant objects."),
        ("INTERMEDIATE", "Which 3D rotation matrix rotates about the X axis?",
         ["A matrix that changes y and z while keeping x", "A matrix that keeps z", "A translation matrix", "A scaling matrix"], "A",
         "X-axis rotation alters the y and z coordinates of points."),
        ("INTERMEDIATE", "What is a normal vector used for in 3D graphics?",
         ["To determine surface orientation for lighting", "To store position", "To define color", "To set resolution"], "A",
         "Normals point perpendicular to surfaces and drive shading."),
        ("INTERMEDIATE", "Which sequence transforms object coordinates to screen coordinates?",
         ["Model, view, projection transformations", "Only projection", "Only translation", "Random reordering"], "A",
         "The model-view-projection pipeline maps objects to the screen."),
        ("INTERMEDIATE", "What does the frustum define in viewing?",
         ["The visible region between near and far planes", "The GPU cache", "The color palette", "The frame rate"], "A",
         "The viewing frustum clips objects to the visible depth range."),
        ("INTERMEDIATE", "Which is a perspective depth cue?",
         ["Objects farther away appear smaller", "All objects appear equal", "Objects have no color", "Depth is ignored"], "A",
         "Size shrinking with distance is a key perspective cue."),
        ("INTERMEDIATE", "What does the viewport transformation do?",
         ["Maps normalized device coordinates to screen pixels", "Adds lighting", "Creates textures", "Sorts polygons"], "A",
         "The viewport maps the projected image to actual display pixels."),
        ("INTERMEDIATE", "Which of the following is a common 3D model file operation?",
         ["Loading a mesh into memory", "Refreshing the monitor", "Compressing audio", "Encoding video"], "A",
         "Mesh loading brings 3D models into the graphics pipeline."),
        ("INTERMEDIATE", "What is a quaternion often used for?",
         ["Rotation interpolation that avoids gimbal lock", "Color conversion", "Texture mapping", "Depth testing"], "A",
         "Quaternions provide smooth, stable 3D rotation."),
        ("ADVANCED", "What is the 'w' coordinate used for in homogeneous 3D coordinates?",
         ["To enable perspective division and affine transforms", "To store texture IDs", "To hold color", "To count frames"], "A",
         "Dividing by w performs perspective projection."),
        ("ADVANCED", "Why does perspective division by w cause distant objects to shrink?",
         ["Coordinates are divided by a larger depth value", "Objects are scaled up", "Colors fade", "Polygons are removed"], "A",
         "The larger w for distant points reduces the projected coordinates."),
        ("ADVANCED", "What is the main purpose of the near and far clipping planes?",
         ["To limit the depth range and avoid depth precision problems", "To add colors", "To speed up the monitor", "To store textures"], "A",
         "Clipping planes define the visible depth range and stabilize z-buffering."),
        ("ADVANCED", "Which transformation changes from camera space to clip space?",
         ["The projection transformation", "The model transformation", "The color transform", "The viewport transform"], "A",
         "Projection moves vertices into clip coordinates for clipping."),
        ("ADVANCED", "What is a key limitation of orthographic projection?",
         ["It does not show realistic depth foreshortening", "It is too slow", "It cannot render", "It distorts colors"], "A",
         "Orthographic views lack the depth perspective of the real world."),
        ("ADVANCED", "Which technique converts a view frustum into clip space?",
         ["The perspective projection matrix", "The translation matrix", "The model matrix", "The color matrix"], "A",
         "The projection matrix encodes the frustum transformation."),
        ("ADVANCED", "What is 'gimbal lock' in 3D rotation?",
         ["Loss of a rotation degree of freedom due to Euler angle ordering", "A GPU error", "A texture artifact", "A depth conflict"], "A",
         "Euler rotations can align axes and lose a degree of freedom."),
        ("ADVANCED", "Which representation avoids gimbal lock?",
         ["Quaternions", "Euler angles", "2x2 matrices", "Translation vectors"], "A",
         "Quaternions rotate in four dimensions without gimbal lock."),
        ("ADVANCED", "What does the model-view matrix combine?",
         ["The object's transformation and the camera's transformation", "The color and depth", "The texture and shading", "The resolution and refresh"], "A",
         "Model-view transforms objects into camera space."),
        ("ADVANCED", "Which step in the 3D pipeline determines which surfaces are visible?",
         ["Hidden surface removal such as z-buffering", "Color conversion", "Vertex skinning", "UV mapping"], "A",
         "Depth testing removes hidden surfaces during rasterization."),
    ],
    249: [
        ("BEGINNER", "What is a light source in graphics?",
         ["An emitter that illuminates the scene", "A texture", "A polygon", "A depth buffer"], "A",
         "Light sources provide illumination for shading surfaces."),
        ("BEGINNER", "What does ambient light represent?",
         ["Uniform background illumination that is not directional", "A bright spotlight", "A colored flash", "A shadow"], "A",
         "Ambient light adds a constant baseline illumination to all surfaces."),
        ("BEGINNER", "What is diffuse reflection?",
         ["Light scattered equally in all directions from a surface", "Light reflected in one direction", "Light absorbed", "No reflection"], "A",
         "Diffuse reflection depends on the angle of incidence and scatters evenly."),
        ("BEGINNER", "What is specular reflection?",
         ["Bright, directional highlight that mirrors the light source", "Uniform scattering", "Absorption", "Ambient glow"], "A",
         "Specular reflection produces shiny highlights on surfaces."),
        ("BEGINNER", "Which color model uses red, green, and blue?",
         ["RGB", "CMYK", "HSV", "HSL"], "A",
         "RGB is the additive color model for displays."),
        ("BEGINNER", "What does the term 'shading' refer to?",
         ["Computing surface colors based on lighting", "Deleting polygons", "Moving vertices", "Storing textures"], "A",
         "Shading calculates the color of each surface using lighting models."),
        ("BEGINNER", "What is a texture map?",
         ["An image applied to a 3D surface to add detail", "A light source", "A depth buffer", "A normal vector"], "A",
         "Textures give surfaces detailed appearance without extra geometry."),
        ("BEGINNER", "What is a normal in shading?",
         ["A vector perpendicular to a surface used in lighting", "A color value", "A pixel", "A light ray"], "A",
         "Normals determine how light interacts with a surface."),
        ("BEGINNER", "Which of the following is a light type in graphics?",
         ["Point light", "Texture light", "Normal light", "Pixel light"], "A",
         "Point, directional, and spot lights are common light types."),
        ("BEGINNER", "What does a material define in rendering?",
         ["How a surface reflects and absorbs light", "The camera position", "The frame rate", "The viewport"], "A",
         "Material properties control the appearance under light."),
        ("INTERMEDIATE", "Which lighting model adds ambient, diffuse, and specular terms?",
         ["Phong reflection model", "Lambert only", "Gouraud only", "No model"], "A",
         "The Phong model combines ambient, diffuse, and specular components."),
        ("INTERMEDIATE", "What is the difference between Gouraud and Phong shading?",
         ["Gouraud interpolates colors; Phong interpolates normals", "Phong is cheaper", "They are identical", "Gouraud uses no lights"], "A",
         "Phong computes per-pixel lighting by interpolating normals."),
        ("INTERMEDIATE", "What does diffuse shading depend on?",
         ["The angle between the light and the surface normal", "The viewer position only", "The texture color only", "Ambient level"], "A",
         "Diffuse intensity follows Lambert's cosine law."),
        ("INTERMEDIATE", "Which surface produces strong specular highlights?",
         ["A shiny surface", "A rough surface", "A dark surface", "An invisible surface"], "A",
         "Glossy surfaces reflect light directionally, creating highlights."),
        ("INTERMEDIATE", "What is a bump map used for?",
         ["Simulating surface detail by altering normals", "Storing colors", "Changing the light", "Reducing polygons"], "A",
         "Bump mapping perturbs normals to fake surface relief."),
        ("INTERMEDIATE", "What is the purpose of a shadow?",
         ["To show where light is blocked by an object", "To add brightness", "To change colors", "To increase resolution"], "A",
         "Shadows give depth and realism by indicating occlusion."),
        ("INTERMEDIATE", "Which term describes light reflected off other surfaces onto a scene?",
         ["Indirect illumination", "Direct light", "Ambient occlusion only", "Specular only"], "A",
         "Indirect lighting accounts for light bouncing between surfaces."),
        ("INTERMEDIATE", "What does a normal map store?",
         ["Perturbed normal directions to fake detail", "Pixel colors", "Depth values", "Light intensities"], "A",
         "Normal maps encode surface orientation for detailed shading."),
        ("INTERMEDIATE", "Which shading model is computationally simplest per vertex?",
         ["Gouraud shading", "Phong shading", "Ray tracing", "Radiosity"], "A",
         "Gouraud computes lighting per vertex and interpolates across faces."),
        ("INTERMEDIATE", "What is a specular exponent (shininess) controlling?",
         ["The size and sharpness of the highlight", "The ambient level", "The texture size", "The depth range"], "A",
         "Higher shininess produces smaller, sharper highlights."),
        ("ADVANCED", "Why is Phong shading more accurate than Gouraud?",
         ["It computes lighting per pixel using interpolated normals", "It uses more lights", "It ignores specular", "It is faster"], "A",
         "Per-pixel normal interpolation captures highlights Gouraud misses."),
        ("ADVANCED", "What is the Blinn-Phong model's advantage over Phong?",
         ["It uses the half-vector, which is cheaper to compute", "It adds ambient", "It removes specular", "It needs no normals"], "A",
         "The half-vector simplifies specular computation with similar results."),
        ("ADVANCED", "What is physically based rendering (PBR) based on?",
         ["Energy-conserving material models and real light behavior", "Simple flat colors", "Fixed shadows", "No textures"], "A",
         "PBR models materials using physically accurate reflectance."),
        ("ADVANCED", "What does ambient occlusion approximate?",
         ["How occluded geometry reduces indirect light", "Direct sunlight", "Specular highlights", "Texture detail"], "A",
         "Ambient occlusion darkens crevices where light is blocked."),
        ("ADVANCED", "Which technique computes global illumination by simulating light transport?",
         ["Path tracing", "Flat shading", "Gouraud shading", "No shading"], "A",
         "Path tracing follows light paths for realistic global illumination."),
        ("ADVANCED", "What is a BRDF?",
         ["A function describing how light reflects from a surface", "A frame buffer", "A color model", "A light source"], "A",
         "The bidirectional reflectance distribution function defines surface reflectance."),
        ("ADVANCED", "Which method approximates soft shadows realistically?",
         ["Area lights with penumbra calculations", "Hard point shadows", "No shadows", "Ambient only"], "A",
         "Area lights create soft shadows with gradual penumbra."),
        ("ADVANCED", "What is the main limitation of flat shading?",
         ["It produces faceted surfaces with no smooth gradients", "It is too slow", "It ignores colors", "It removes polygons"], "A",
         "Flat shading uses one normal per face, showing hard facets."),
        ("ADVANCED", "Which rendering quality technique improves anti-aliasing of shading?",
         ["Multisample anti-aliasing (MSAA)", "Flat shading", "Gouraud only", "Increasing brightness"], "A",
         "MSAA samples shading at multiple positions to smooth edges."),
        ("ADVANCED", "What does a shadow map store?",
         ["Depth values from the light's perspective", "Surface colors", "Vertex positions", "Light intensities"], "A",
         "Shadow mapping compares depths to determine occluded fragments."),
    ],
    250: [
        ("BEGINNER", "What is rendering?",
         ["Generating an image from a 3D scene", "Storing a model", "Compressing audio", "Editing text"], "A",
         "Rendering converts 3D scene data into a 2D image."),
        ("BEGINNER", "What is animation in graphics?",
         ["Displaying a sequence of frames to create motion", "A single image", "A texture", "A light source"], "A",
         "Animation shows successive frames over time to simulate movement."),
        ("BEGINNER", "What is a frame in animation?",
         ["A single image in a sequence", "A color palette", "A 3D model", "A depth buffer"], "A",
         "Each frame is one image in the animated sequence."),
        ("BEGINNER", "What is a keyframe?",
         ["A frame that defines a crucial position in an animation", "Any random frame", "The last frame only", "A texture frame"], "A",
         "Keyframes mark important poses that interpolation fills between."),
        ("BEGINNER", "What is interpolation in animation?",
         ["Computing intermediate frames between keyframes", "Deleting frames", "Compressing frames", "Coloring frames"], "A",
         "Interpolation generates smooth motion between key positions."),
        ("BEGINNER", "Which of the following is a rendering technique?",
         ["Ray tracing", "Text editing", "Database design", "Network routing"], "A",
         "Ray tracing is a rendering method that simulates light rays."),
        ("BEGINNER", "What is hidden surface removal?",
         ["Discarding surfaces not visible to the camera", "Adding surfaces", "Brightening the scene", "Scaling models"], "A",
         "Hidden surface removal avoids drawing occluded geometry."),
        ("BEGINNER", "What does the z-buffer store?",
         ["Depth values of each pixel", "Colors of pixels", "Texture coordinates", "Light positions"], "A",
         "The z-buffer records depth to resolve visibility."),
        ("BEGINNER", "What is a 3D model?",
         ["A mathematical representation of an object's shape", "A photo", "A sound file", "A spreadsheet"], "A",
         "3D models describe geometry using vertices, edges, and faces."),
        ("BEGINNER", "What is a scene in computer graphics?",
         ["The collection of objects, lights, and camera to be rendered", "A single polygon", "A color", "A frame buffer"], "A",
         "A scene contains all the elements rendered together."),
        ("INTERMEDIATE", "Which algorithm removes hidden surfaces using depth comparison?",
         ["Z-buffering", "Flood fill", "Scan conversion", "Anti-aliasing"], "A",
         "Z-buffering keeps the closest depth at each pixel."),
        ("INTERMEDIATE", "What is the painter's algorithm?",
         ["Drawing polygons from back to front to resolve visibility", "Painting textures", "Filling colors", "Sorting lights"], "A",
         "The painter's algorithm sorts surfaces by depth and draws them in order."),
        ("INTERMEDIATE", "What is a limitation of the painter's algorithm?",
         ["It fails for overlapping and intersecting polygons", "It is too accurate", "It needs no sorting", "It renders nothing"], "A",
         "Ambiguous depth order breaks the painter's algorithm."),
        ("INTERMEDIATE", "Which technique traces light rays from the camera into the scene?",
         ["Ray tracing", "Flat shading", "Gouraud shading", "Scan conversion"], "A",
         "Ray tracing follows rays backward from the eye to compute color."),
        ("INTERMEDIATE", "What is temporal interpolation in animation?",
         ["Computing frames between keyframes over time", "Deleting old frames", "Increasing resolution", "Changing colors"], "A",
         "Temporal interpolation produces smooth motion over time."),
        ("INTERMEDIATE", "What is tweening in 2D animation?",
         ["Generating intermediate frames between keyframes", "Applying textures", "Rendering shadows", "Storing models"], "A",
         "Tweening fills the frames between key poses automatically."),
        ("INTERMEDIATE", "What is a skeleton used for in character animation?",
         ["A hierarchy of bones that drives mesh deformation", "A 3D model", "A texture", "A light rig"], "A",
         "Skeletons define bones that deform the character mesh."),
        ("INTERMEDIATE", "What does rasterization convert?",
         ["Primitives into pixel fragments", "Pixels into vectors", "Audio into video", "Text into images"], "A",
         "Rasterization turns geometric primitives into pixel fragments."),
        ("INTERMEDIATE", "What is a frame rate?",
         ["The number of frames displayed per second", "The image resolution", "The color depth", "The file size"], "A",
         "Frame rate measures smoothness, such as 60 frames per second."),
        ("INTERMEDIATE", "Which of these is a real-time rendering API?",
         ["DirectX", "MS Word", "MySQL", "HTTP"], "A",
         "DirectX enables real-time graphics rendering."),
        ("ADVANCED", "What is the main quality advantage of ray tracing over rasterization?",
         ["It produces physically accurate reflections and shadows", "It is always faster", "It needs no geometry", "It has no colors"], "A",
         "Ray tracing simulates light paths for realistic effects."),
        ("ADVANCED", "What is the main performance drawback of ray tracing?",
         ["It is computationally expensive", "It uses no memory", "It renders too fast", "It cannot show shadows"], "A",
         "Tracing many light paths per pixel is costly."),
        ("ADVANCED", "Which data structure accelerates ray-object intersection tests?",
         ["Bounding volume hierarchies (BVH)", "Linked lists", "Hash tables only", "Flat arrays"], "A",
         "BVHs organize geometry to speed ray traversal."),
        ("ADVANCED", "What is a motion blur effect caused by?",
         ["The motion of objects between shutter openings", "High resolution", "Low color depth", "More polygons"], "A",
         "Motion blur mimics the smearing of moving objects over time."),
        ("ADVANCED", "What is inverse kinematics (IK) used for in animation?",
         ["Computing joint angles to reach a target position", "Rendering shadows", "Texturing surfaces", "Removing polygons"], "A",
         "IK solves joint configurations from a desired end-effector pose."),
        ("ADVANCED", "Which technique reduces shimmering of animated far-away textures?",
         ["Mipmapping", "Flat shading", "Double buffering", "Z-buffering"], "A",
         "Mipmaps provide prefiltered texture levels to reduce aliasing."),
        ("ADVANCED", "What is the purpose of level of detail (LOD)?",
         ["Using simpler geometry for distant objects to save cost", "Adding detail to all objects", "Removing colors", "Increasing frame rate by dropping frames"], "A",
         "LOD adapts mesh complexity to distance from the camera."),
        ("ADVANCED", "What is a particle system commonly used for?",
         ["Simulating effects such as fire, smoke, and rain", "Storing models", "Sorting polygons", "Coloring lights"], "A",
         "Particle systems animate large numbers of small elements."),
        ("ADVANCED", "What does the term 'frustum culling' do?",
         ["Skips objects outside the view frustum", "Adds shadows", "Applies textures", "Increases resolution"], "A",
         "Culling discards off-screen geometry to speed rendering."),
        ("ADVANCED", "What is the purpose of a physics engine in animation?",
         ["To simulate realistic motion such as collisions and gravity", "To render images", "To store textures", "To manage colors"], "A",
         "Physics engines compute believable object dynamics."),
    ],
}


