# -*- coding: utf-8 -*-
"""
Question bank for subject 27: WEB102 - Frontend JavaScript Frameworks.
Category: Web & Mobile Development.

Topics:
  131: DOM Manipulation
  132: React Fundamentals
  133: Components & Props
  134: State & Hooks
  135: Routing & Performance

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    131: [
        ("BEGINNER", "Which object represents the HTML document loaded in the browser and is the entry point to the DOM?",
         ["window", "document", "navigator", "location"], "B",
         "The document object is the root of the DOM and gives access to all elements of the page."),
        ("BEGINNER", "Which method returns the first element that matches a CSS selector in the document?",
         ["getElementByTag", "querySelectorAll", "querySelector", "getElementsByClassName"], "C",
         "querySelector returns the first matching element for the given CSS selector."),
        ("BEGINNER", "Which property lets you change the text content of an element?",
         ["textContent", "innerHTML", "value", "style"], "A",
         "textContent reads and writes the text inside an element without parsing HTML markup."),
        ("BEGINNER", "Which method creates a new HTML element such as a div in the DOM?",
         ["createElement", "appendChild", "createNode", "newElement"], "D",
         "document.createElement returns a new element node that is not yet attached to the page."),
        ("BEGINNER", "What does the property nodeName return for a p element?",
         ["p", "P", "paragraph", "element"], "B",
         "nodeName returns the tag name in uppercase, so a paragraph element reports P."),
        ("BEGINNER", "Which method adds an event listener to an element?",
         ["addEventListener", "onEvent", "listen", "attach"], "C",
         "addEventListener registers a handler function to be invoked when the given event fires."),
        ("BEGINNER", "What does the DOM stand for?",
         ["Document Object Model", "Data Object Management", "Document Oriented Module", "Dynamic Output Mechanism"], "A",
         "The Document Object Model is the browser's tree representation of the HTML document."),
        ("BEGINNER", "Which property of the event object identifies the element on which the event was fired?",
         ["target", "source", "element", "node"], "B",
         "The target property of an event points to the element that triggered the event."),
        ("BEGINNER", "Which method removes an element from the DOM?",
         ["remove()", "delete()", "hide()", "detach()"], "C",
         "Calling remove() on an element detaches it from its parent in the DOM."),
        ("BEGINNER", "How do you select an element by its unique id in plain JavaScript?",
         ["getElementById", "getElementsById", "querySelectorAll('#id')", "findById"], "D",
         "document.getElementById returns the single element bearing the matching id attribute."),
        ("INTERMEDIATE", "Which property returns a live collection of all child elements of a node?",
         ["children", "childNodes", "descendants", "childList"], "A",
         "children returns only element children, unlike childNodes which also includes text and comment nodes."),
        ("INTERMEDIATE", "What is the difference between innerHTML and textContent when reading an element?",
         ["both return the same value", "innerHTML returns markup while textContent returns plain text", "textContent includes comments", "innerHTML returns only text"], "B",
         "innerHTML exposes the raw HTML markup inside the element while textContent returns only the visible text."),
        ("INTERMEDIATE", "Which attribute method should be preferred to set the class of an element without wiping out other classes?",
         ["setAttribute('class', value)", "className = value", "classList.add(value)", "style.classList"], "C",
         "classList.add adds a single class while preserving existing classes on the element."),
        ("INTERMEDIATE", "Consider a button inside a div. Clicking the button triggers the button handler then the div handler. What is this behavior called?",
         ["bubbling", "capturing", "propagation stop", "delegation"], "A",
         "In event bubbling the event travels from the target up through its ancestors after being handled."),
        ("INTERMEDIATE", "Which event is fired when the page and all its resources have finished loading?",
         ["DOMContentLoaded", "load", "ready", "render"], "B",
         "The load event fires after the document and all external resources have fully loaded."),
        ("INTERMEDIATE", "Given <ul id='list'></ul>, which code appends a new <li> with the text Item?",
         ["const li = document.createElement('li'); li.textContent = 'Item'; list.appendChild(li);", "list.innerHTML = '<li>Item</li>';", "list.add('<li>Item</li>');", "document.append(list, 'Item');"], "A",
         "Building the element with createElement and textContent then appending it avoids repeated innerHTML parsing."),
        ("INTERMEDIATE", "Which method stops the event from reaching handlers on parent elements?",
         ["stopPropagation()", "preventDefault()", "stopImmediatePropagation() only", "return false"], "C",
         "stopPropagation prevents the event from continuing to bubble up to ancestor elements."),
        ("INTERMEDIATE", "What does event.preventDefault() do?",
         ["stops the event from bubbling", "cancels the browser default action", "removes the element", "pauses event listeners"], "D",
         "preventDefault cancels the browser's default action, such as navigating when a link is clicked."),
        ("INTERMEDIATE", "Which approach is most efficient when adding event handlers to 100 list items?",
         ["attach a listener to each item", "use one listener on the parent container and inspect event.target", "use inline onclick attributes", "attach a window listener per item"], "A",
         "Event delegation attaches a single listener to a common ancestor, reducing listener count."),
        ("INTERMEDIATE", "After moving an element with appendChild from one parent to another, what happens to the original location?",
         ["the element exists in both places", "the element is removed from the original location", "a copy is made", "the original location keeps a clone"], "B",
         "appendChild moves an existing node, so the element appears only in the new parent location."),
        ("ADVANCED", "You build a large table by setting innerHTML repeatedly in a loop. Which is the best performance fix?",
         ["use createDocumentFragment and append once", "call innerHTML more often", "use document.write", "increase the loop delay"], "A",
         "Building nodes in a DocumentFragment and appending it once causes a single reflow instead of many."),
        ("ADVANCED", "Which technique reduces layout thrashing when reading and then writing element sizes in a loop?",
         ["batch reads before writes or use requestAnimationFrame", "read and write on every iteration", "use innerHTML instead", "disable CSS transitions"], "B",
         "Batching reads and writes minimizes forced synchronous reflows, which cause layout thrashing."),
        ("ADVANCED", "A click handler on the document must know whether a link was clicked and ignore clicks elsewhere. What is the cleanest check?",
         ["compare event.target with the link node using closest", "check event.button", "compare event.currentTarget", "test event.keyCode"], "C",
         "event.target.closest('a') reveals whether the click originated inside a link, including nested children."),
        ("ADVANCED", "Why is using MutationObserver preferable to polling with setInterval for detecting DOM changes?",
         ["it is synchronous and blocks the UI", "it fires callbacks asynchronously only when changes occur, avoiding constant work", "it requires no callbacks", "it is deprecated"], "A",
         "MutationObserver delivers a batch of changes asynchronously, so no work happens when the DOM is idle."),
        ("ADVANCED", "Which approach best preserves accessibility when toggling the visibility of a dialog?",
         ["toggle display via style plus manage aria-hidden and focus", "set textContent to empty", "remove the dialog node entirely", "use opacity only"], "B",
         "Managing ARIA state and focus keeps screen readers and keyboard users aware of the dialog's visibility."),
        ("ADVANCED", "Shadow DOM is most useful for which goal?",
         ["encapsulating styles and markup so page CSS cannot interfere", "increasing event bubbling", "replacing the document root", "making all selectors global"], "C",
         "Shadow DOM scopes styles and markup to a component, preventing leaks from global styles."),
        ("ADVANCED", "While adding many classes, which call avoids unnecessary style recalculations?",
         ["element.classList.add('a', 'b', 'c') in one call", "three separate classList.add calls", "writing className repeatedly", "adding classes with style.setProperty"], "A",
         "classList accepts multiple tokens in one call, so the style is recalculated once."),
        ("ADVANCED", "A page has an input that must trigger a search request only after the user stops typing. Which technique is appropriate?",
         ["debounce the input event with a timeout", "fire a request on every keystroke", "use blur only", "poll the value"], "B",
         "Debouncing delays the handler until typing pauses, so requests are not fired on every keystroke."),
        ("ADVANCED", "Why does removing and recreating a large subtree via innerHTML often beat updating it node by node?",
         ["the browser can parse the HTML once and avoid many individual updates", "innerHTML is always faster than any update", "it preserves event listeners", "it never causes reflows"], "C",
         "Replacing the subtree parses markup once, whereas per-node updates trigger many incremental reflows."),
        ("ADVANCED", "Which toolset is recommended for debugging DOM state in modern browsers?",
         ["the browser DevTools Elements and Console panels", "console.log with JSON.stringify", "alert dialogs", "view-source of the page"], "D",
         "DevTools lets you inspect, edit and watch the live DOM, far more powerful than printing snapshots."),
    ],
    132: [
        ("BEGINNER", "What is React primarily used for?",
         ["building user interfaces with components", "styling web pages", "database management", "server configuration"], "A",
         "React is a JavaScript library for composing user interfaces from reusable components."),
        ("BEGINNER", "Which command creates a new React application with create-react-app?",
         ["npx create-react-app my-app", "npm init react", "react new my-app", "npm start my-app"], "B",
         "npx create-react-app my-app scaffolds a complete React project in the my-app folder."),
        ("BEGINNER", "What file extension do React components typically use when written with JSX?",
         [".jsx", ".html", ".css", ".json"], "C",
         "JSX components live in .jsx files, although .js files are also commonly used."),
        ("BEGINNER", "Which syntax allows JavaScript expressions inside JSX?",
         ["{{ }}", "${ }", "{ }", "<% %>"], "D",
         "Wrapping an expression in a single pair of braces evaluates it inside JSX markup."),
        ("BEGINNER", "Which function is the entry point that mounts the app into the DOM in React 18?",
         ["ReactDOM.createRoot(root).render(<App />)", "React.render(<App />)", "ReactDOM.render(<App />, root)", "mount(<App />)"], "A",
         "React 18 uses createRoot followed by render to attach the component tree to the DOM node."),
        ("BEGINNER", "What is JSX?",
         ["a syntax extension that looks like HTML but compiles to JavaScript", "a new HTML version", "a CSS framework", "a database query language"], "B",
         "JSX is a syntax extension that is transpiled into React.createElement calls."),
        ("BEGINNER", "Which keyword is used to import a component from another file?",
         ["import", "require", "include", "use"], "C",
         "ES modules use the import statement to bring in named or default exports."),
        ("BEGINNER", "In JSX, how do you write an HTML comment?",
         ["/* comment */ in the markup", "<!-- comment -->", "// comment", "comments are not allowed in JSX"], "D",
         "HTML-style comments are not valid JSX; JavaScript comments inside braces must be used instead."),
        ("BEGINNER", "Which rule about JSX classes is correct?",
         ["you must use className instead of class", "class is fine in JSX", "use classname", "classes are not supported"], "A",
         "class is a reserved word in JavaScript, so JSX uses className for the CSS class attribute."),
        ("BEGINNER", "How is a component named Greeting rendered in JSX?",
         ["<Greeting />", "<greeting>", "<greeting />", "<Greeting></greeting> only"], "B",
         "A component is rendered with a capitalised tag, so <Greeting /> creates that component."),
        ("INTERMEDIATE", "What does the expression 2 + 2 produce when written as {2 + 2} inside JSX?",
         ["4", "22", "2 + 2", "an error"], "C",
         "Braces evaluate the JavaScript expression, so the rendered output is the number 4."),
        ("INTERMEDIATE", "What does React render for a component function that returns several sibling elements without a wrapper?",
         ["all siblings render directly", "it throws an error without a single parent element", "only the first renders", "the last sibling renders"], "D",
         "A component must return a single root element, so siblings need a wrapper or fragment."),
        ("INTERMEDIATE", "Which syntax renders the array ['a', 'b', 'c'] as three list items?",
         ["items.map(item => <li key={item}>{item}</li>)", "items.forEach(item => <li>{item}</li>)", "<li>{items}</li>", "items.join('<li>')"], "A",
         "map transforms each item into a li element, and a key helps React track the items."),
        ("INTERMEDIATE", "What is the purpose of the key prop on list items?",
         ["it gives each element a stable identity for efficient updates", "it styles the item", "it orders the list alphabetically", "it prevents rendering"], "B",
         "Keys let React match items across renders so it can update the DOM efficiently."),
        ("INTERMEDIATE", "Why must custom components have names starting with a capital letter?",
         ["React treats lowercase tags as HTML elements", "it is a performance optimisation", "the linter requires it", "it enables hot reload"], "C",
         "Lowercase names are treated as native DOM tags, so capital letters distinguish components."),
        ("INTERMEDIATE", "What does conditional rendering with {condition && <p>Hi</p>} show when condition is false?",
         ["nothing", "false", "null", "an error"], "A",
         "The logical AND short-circuits and renders nothing when the left operand is falsy."),
        ("INTERMEDIATE", "Which approach correctly renders either Yes or No based on a boolean prop?",
         ["{flag ? 'Yes' : 'No'}", "{if (flag) 'Yes' else 'No'}", "<div if={flag}>Yes</div>", "{flag || 'No'}"], "B",
         "The ternary operator picks one of the two expressions to render based on the flag value."),
        ("INTERMEDIATE", "Which tool detects common mistakes and keeps the JSX style consistent?",
         ["ESLint", "npm", "webpack", "Babel"], "C",
         "ESLint analyses the code and flags errors and stylistic issues during development."),
        ("INTERMEDIATE", "What does a StrictMode component do in a development build?",
         ["enables additional checks and warnings about unsafe practices", "speeds up production", "disables all hooks", "removes console logs"], "D",
         "StrictMode double-invokes functions in development to surface bugs such as impure render logic."),
        ("INTERMEDIATE", "Which statement correctly describes what Babel does in a React project?",
         ["it transpiles JSX and modern JavaScript into browser-compatible code", "it bundles CSS", "it runs the dev server", "it minifies images"], "A",
         "Babel transforms JSX and newer JS syntax into forms supported by older browsers."),
        ("ADVANCED", "When a component renders the same output for the same props and state, what is the benefit of wrapping it in memo?",
         ["React skips re-rendering it when its props have not changed", "it compiles to native code", "it forces re-renders", "it makes props immutable"], "B",
         "memo performs a shallow prop comparison and skips the render when nothing changed."),
        ("ADVANCED", "Which pattern is the recommended way to handle a component that renders conditionally but must keep its state when toggled away?",
         ["keep it mounted and toggle visibility with CSS or a display flag", "conditionally unmount it", "reset its state", "duplicate the component"], "A",
         "Keeping the component mounted preserves its state; unmounting destroys it."),
        ("ADVANCED", "What is the danger of using an array index as a key when list items are reordered?",
         ["React may mismatch elements and preserve the wrong state", "it slows rendering", "it causes a syntax error", "the keys become strings"], "C",
         "Index keys tie identity to position, so reordering can cause React to reuse the wrong component state."),
        ("ADVANCED", "Why are pure components recommended in React?",
         ["a pure render makes output predictable and enables optimisations like memo", "pure components run faster natively", "they can use class syntax only", "they never re-render"], "A",
         "Pure functions give the same output for the same inputs, which makes rendering and optimisation reliable."),
        ("ADVANCED", "Which approach is best for rendering a large list that only part is visible?",
         ["use windowing or virtualisation so only visible rows render", "render all rows at once", "split the list into many small components", "use innerHTML"], "B",
         "Virtualisation renders only the visible rows, drastically reducing DOM nodes for huge lists."),
        ("ADVANCED", "A component must avoid re-running an expensive computation on every render even when the input has not changed. Which hook is appropriate?",
         ["useMemo", "useEffect", "useRef", "useState"], "C",
         "useMemo caches the result of the computation until its dependencies change."),
        ("ADVANCED", "Why should side effects such as network requests not run directly inside the render body?",
         ["rendering should be pure and side effects belong in effects or event handlers", "side effects are forbidden by JSX", "they always crash", "they break the bundler"], "D",
         "Putting side effects in render makes output unpredictable and causes duplicates in strict mode."),
        ("ADVANCED", "Which factor most commonly causes an unexpected re-render of many unrelated components in a large app?",
         ["passing new object or function references on every parent render", "using inline styles", "having too many files", "using keys on every element"], "A",
         "New references to props each render defeat memo comparison and cascade re-renders to children."),
        ("ADVANCED", "What is the main advantage of co-locating a component's styles, logic and markup in one folder?",
         ["related code stays together, making the component self-contained and easier to maintain", "it reduces bundle size automatically", "it enables server-side rendering", "it disables CSS"], "B",
         "Co-location groups everything a component needs in one place, improving maintainability."),
        ("ADVANCED", "Which statement best describes reconciliation in React?",
         ["React diffing old and new trees to apply the minimal DOM updates", "converting JSX to HTML", "compressing the bundle", "persisting state to storage"], "A",
         "Reconciliation is React's algorithm for computing the minimal set of DOM changes between renders."),
    ],
    133: [
        ("BEGINNER", "What is a React component?",
         ["a reusable piece of UI defined as a function or class", "a CSS class", "an HTML file", "a database table"], "A",
         "A component is a reusable, isolated building block that renders part of the interface."),
        ("BEGINNER", "What do we call the data passed from a parent component to a child component?",
         ["props", "state", "hooks", "stores"], "B",
         "Props are the read-only values a parent passes down to a child component."),
        ("BEGINNER", "How does a function component receive its props?",
         ["as an argument to the function", "from the DOM", "through global variables", "from the file system"], "C",
         "The function receives a single props object as its first parameter."),
        ("BEGINNER", "Can a child component modify the props it receives?",
         ["no, props are read-only", "yes, by reassignment", "only inside event handlers", "yes, with useState"], "D",
         "Props are immutable, so a component must treat them as read-only input."),
        ("BEGINNER", "Which syntax destructures the name prop in a function signature?",
         ["function Greeting({ name })", "function Greeting(props.name)", "function Greeting(props => name)", "function Greeting(): name"], "A",
         "Destructuring the props object in the signature pulls name out directly."),
        ("BEGINNER", "What is the children prop used for?",
         ["accessing the elements nested inside a component", "counting children elements", "styling the component", "naming the component"], "B",
         "children holds whatever content is placed between a component's opening and closing tags."),
        ("BEGINNER", "Which code renders the prop title inside a p element?",
         ["<p>{title}</p>", "<p>title</p>", "<p>props.title</p>", "<p>{this.title}</p>"], "C",
         "Wrapping the title variable in braces inserts its value into the JSX paragraph."),
        ("BEGINNER", "What type of value can be passed as a prop?",
         ["any JavaScript value, including objects and functions", "only strings", "only numbers", "only elements"], "D",
         "Props can carry any value, from primitives to objects, arrays and functions."),
        ("BEGINNER", "Which pattern allows a child to pass information up to a parent?",
         ["the parent passes a callback function that the child invokes", "the child edits its props", "the child uses window.postMessage", "the child re-renders the parent"], "A",
         "Parent-provided callbacks let children report events upward without mutating props."),
        ("BEGINNER", "What does propTypes help a developer check?",
         ["that props match expected types", "that props are immutable", "that components render", "that props are styled"], "B",
         "propTypes validates the type of each prop, catching mistakes during development."),
        ("INTERMEDIATE", "What happens when a parent passes a new object literal to a child on every render?",
         ["the child sees a new reference each time, which can break memo comparisons", "the object is frozen", "nothing changes", "the child crashes"], "A",
         "A fresh object literal creates a new reference, so shallow equality checks fail each render."),
        ("INTERMEDIATE", "Given function Welcome({ name }) { return <h1>{name}</h1>; }, what renders for <Welcome name='Ada' />?",
         ["an h1 containing Ada", "Welcome", "an error", "an empty h1"], "B",
         "The name prop is passed in and the component renders an h1 with its value Ada."),
        ("INTERMEDIATE", "Which snippet forwards all props of parent to child?",
         ["<Child {...props} />", "<Child props />", "<Child {...this} />", "<Child children={props} />"], "C",
         "Spreading props with {...props} forwards every prop to the Child component."),
        ("INTERMEDIATE", "How do you set a default value for the color prop in a function component?",
         ["use defaultProps or destructure with a default in the parameter list", "set it in state", "use a global variable", "assign it in render"], "D",
         "Destructuring defaults such as ({ color = 'blue' }) apply when no color prop is given."),
        ("INTERMEDIATE", "What is a controlled component?",
         ["an input whose value is driven by React state", "an input without an onChange", "a component that never re-renders", "a component with no props"], "A",
         "A controlled input gets its value from state and updates state through onChange."),
        ("INTERMEDIATE", "Which statement about prop drilling is correct?",
         ["it is passing props through many intermediate components that do not need them", "it is a React error", "it is passing props directly to the DOM", "it is storing props on the window"], "B",
         "Prop drilling describes threading data through layers of components just to reach a deep consumer."),
        ("INTERMEDIATE", "Given <Card><h1>Hello</h1></Card>, what does {children} render inside Card?",
         ["the h1 element Hello", "an empty box", "Card", "an array"], "C",
         "The children prop holds the h1 element passed between the tags, so it renders Hello."),
        ("INTERMEDIATE", "Which best describes a composable component design?",
         ["building larger features by combining small, focused components", "putting all logic in one file", "using only class components", "avoiding props entirely"], "D",
         "Composition assembles small focused components into larger ones, improving reuse and clarity."),
        ("INTERMEDIATE", "Why does changing a parent prop trigger a re-render of the child?",
         ["React re-renders children when their props change", "the child changes its own props", "the DOM forces it", "the child subscribes to the parent"], "A",
         "When the parent re-renders with new props, React re-renders the child to reflect the new values."),
        ("INTERMEDIATE", "What does the spread operator do when passing props as {...person}?",
         ["passes each property of person as a separate prop", "deep copies person", "freezes person", "deletes person"], "B",
         "Spreading an object sends every property as an individual prop to the child."),
        ("ADVANCED", "A deeply nested component needs the same data many levels below. Which pattern best avoids prop drilling?",
         ["use context or a state management library", "pass props through every level", "store data on the DOM", "duplicate data in each component"], "A",
         "Context lets a component supply data that any descendant can consume without prop drilling."),
        ("ADVANCED", "When a memoized child always receives a new inline arrow function, what is the practical result?",
         ["the memo check fails each render and the child still re-renders", "the child never re-renders", "the function is cached automatically", "the app crashes"], "B",
         "A new function reference on every render defeats memo's shallow comparison."),
        ("ADVANCED", "Which approach is most appropriate for passing a callback that must always see fresh state?",
         ["use useCallback with the right dependencies, or the functional update form", "define the function inline", "use a global variable", "disable the linter"], "C",
         "useCallback with correct dependencies keeps the callback stable while staying in sync with state."),
        ("ADVANCED", "Why is it a code smell for a child to reach directly into the DOM to change text written by props?",
         ["the child should derive its UI from props instead of mutating the DOM", "the DOM is read-only", "it makes the app slower", "it only works in production"], "A",
         "Direct DOM mutation bypasses React's model, so the UI can drift out of sync with props."),
        ("ADVANCED", "Which pattern best describes a compound component such as <Select.Option>?",
         ["a parent component exposing sub-components that share implicit context", "a component with many props", "a component that uses innerHTML", "a native HTML select"], "D",
         "Compound components pair a parent with sub-components that communicate through shared context."),
        ("ADVANCED", "To reuse layout that wraps different content across pages, which component pattern is ideal?",
         ["a layout component that accepts children and renders them inside shared markup", "a HOC that clones every element", "duplicating the layout per page", "a render-less component"], "A",
         "A layout component receives children and wraps them with shared chrome such as headers and footers."),
        ("ADVANCED", "What is a high-order component (HOC)?",
         ["a function that takes a component and returns a new enhanced component", "a component higher in the tree", "a component with many hooks", "an element that overlays the page"], "B",
         "An HOC is a function that wraps a component to add props or behaviour without changing its internals."),
        ("ADVANCED", "When is the children-as-a-function (render prop) pattern valuable?",
         ["when a component must expose internal data so callers can decide how to render it", "when props are strings", "when the component has no state", "when using class syntax"], "A",
         "Render props let the parent control the markup while the component controls the data."),
        ("ADVANCED", "Why should props always be considered public API of a component?",
         ["changing their meaning breaks every place that uses the component", "props are stored in the database", "props are hard to read", "props are automatically deleted"], "C",
         "Consumers depend on the props contract, so changing semantics or names can break callers."),
        ("ADVANCED", "Which solution best shares an authenticated user object with the whole app without prop drilling?",
         ["an AuthProvider that supplies the user via context", "passing user through every component", "a global window.user", "saving user in localStorage and reading everywhere"], "B",
         "A context provider gives the user to all descendants cleanly and re-renders them when it changes."),
    ],
    134: [
        ("BEGINNER", "Which hook adds local state to a function component?",
         ["useState", "useEffect", "useRef", "useMemo"], "A",
         "useState returns a state value and a setter function to update it."),
        ("BEGINNER", "What does the useState hook return?",
         ["an array with the current value and a function to update it", "an object with the value only", "the DOM node", "a promise"], "B",
         "useState returns a pair: the current state value and an updater function."),
        ("BEGINNER", "How do you update a piece of state named count that was created with const [count, setCount] = useState(0)?",
         ["setCount(5)", "count = 5", "count += 1", "this.count = 5"], "C",
         "The updater setCount(5) schedules the state change and triggers a re-render."),
        ("BEGINNER", "Which hook runs a side effect after the component renders?",
         ["useEffect", "useState", "useLayoutEffect only", "useCallback"], "D",
         "useEffect lets you run side effects such as fetching or subscribing after render."),
        ("BEGINNER", "What is the second argument of useEffect called?",
         ["the dependency array", "the callback", "the cleanup", "the initial value"], "A",
         "The dependency array controls when the effect re-runs."),
        ("BEGINNER", "What does a ref created with useRef allow a component to do?",
         ["hold a mutable value that does not trigger re-renders", "change props", "create a new component", "persist data to a server"], "B",
         "useRef gives a mutable object whose changes do not cause the component to re-render."),
        ("BEGINNER", "Which rule about hooks is correct?",
         ["hooks must be called at the top level, not inside loops or conditions", "hooks can be called anywhere", "hooks require class syntax", "hooks only work in Node.js"], "A",
         "Calling hooks unconditionally at the top level keeps their order stable across renders."),
        ("BEGINNER", "How many times does state in useState(0) change when setCount(1) is called twice in a row?",
         ["once, because the second call sets the same value", "twice", "zero times", "three times"], "C",
         "React batches the updates and bails out when the new value equals the current state."),
        ("BEGINNER", "Which hook is used to derive a cached value from state or props?",
         ["useMemo", "useEffect", "useState", "useRef"], "D",
         "useMemo recomputes its value only when the listed dependencies change."),
        ("BEGINNER", "What does the updater returned by useState return when called?",
         ["nothing useful; it schedules an update and triggers a re-render", "the new state value", "a promise", "the old value"], "A",
         "The setter schedules the update and returns undefined; the new value is applied on re-render."),
        ("INTERMEDIATE", "Given const [count, setCount] = useState(0); what is the final value of count after setCount(count + 1) runs twice?",
         ["1, because both closures see the stale count 0", "2", "0", "an error"], "B",
         "Both updaters close over the same stale count, so both schedule 0 + 1 and the result is 1."),
        ("INTERMEDIATE", "Which snippet correctly increments a counter using a functional update?",
         ["setCount(c => c + 1)", "setCount(count + 1)", "count = count + 1", "setCount(count += 1)"], "A",
         "The functional form receives the latest state, making it safe under batching."),
        ("INTERMEDIATE", "Why do multiple state updates in one event handler get batched into a single render?",
         ["React batches state updates for better performance", "the DOM can only render once per second", "state is immutable", "the handler runs twice"], "B",
         "React 18 batches updates automatically, so the component re-renders once with both changes."),
        ("INTERMEDIATE", "What is the purpose of the cleanup function returned by useEffect?",
         ["it cleans up subscriptions or timers before the effect re-runs or the component unmounts", "it resets state", "it cancels props", "it deletes the component"], "C",
         "The cleanup prevents memory leaks by undoing resources set up by the effect."),
        ("INTERMEDIATE", "Given useEffect(() => {}, [deps]), when does the effect re-run?",
         ["only when an item in deps changes", "after every render", "never", "only on mount"], "A",
         "With a dependency array, the effect re-runs only when a listed dependency changes."),
        ("INTERMEDIATE", "How do you read a DOM node stored in a ref created with const myRef = useRef(null)?",
         ["myRef.current", "myRef.value", "myRef.node", "myRef()"], "B",
         "Refs expose their current value through the current property."),
        ("INTERMEDIATE", "What is the risk of running a data fetch inside render instead of useEffect?",
         ["the fetch runs on every render and can loop indefinitely, causing repeated requests", "fetch is forbidden in React", "the data is cached forever", "the DOM blocks requests"], "A",
         "Side effects in render run repeatedly and may trigger more renders, creating an infinite loop."),
        ("INTERMEDIATE", "Which scenario is a good fit for useRef rather than useState?",
         ["tracking an interval id that must not cause re-renders", "displaying a counter", "storing form values to render", "showing a modal"], "C",
         "Interval ids are mutable values whose changes should not trigger renders, so useRef fits."),
        ("INTERMEDIATE", "What does the empty dependency array [] mean for useEffect?",
         ["the effect runs once after the first render", "the effect never runs", "the effect runs on every render", "the effect runs twice per mount"], "D",
         "An empty array means the effect has no dependencies, so it runs only after mount."),
        ("INTERMEDIATE", "Why does stale state happen when a click handler reads state from a closure?",
         ["the handler captured the state value from the render in which it was created", "state is stored in the DOM", "the browser freezes state", "props override state"], "A",
         "Each render creates closures that capture that render's state, so old handlers see old values."),
        ("ADVANCED", "Why is it incorrect to skip a dependency in useEffect even when the linter cannot tell?",
         ["the effect may use stale values and behave incorrectly, so dependencies must match usage", "the effect runs slower", "it duplicates state", "it disables rendering"], "B",
         "Missing dependencies let the effect capture stale values, producing bugs that are hard to trace."),
        ("ADVANCED", "What is the recommended way to avoid an effect that re-runs just because an inline object changes each render?",
         ["memoise the object with useMemo so its reference stays stable between renders", "put the object in state", "create the object in useEffect", "use a global object"], "A",
         "useMemo keeps the object reference stable so the effect's dependency comparison passes."),
        ("ADVANCED", "When multiple setState calls depend on the previous state, why is the functional form essential?",
         ["the functional form always receives the latest queued state, avoiding lost updates", "the direct form is faster", "the direct form is deprecated", "the functional form never re-renders"], "B",
         "Functional updates chain correctly, so each update builds on the latest scheduled value."),
        ("ADVANCED", "A component fetches user data based on an id prop. Which code structure correctly handles the id changing?",
         ["a useEffect that re-fetches whenever id changes and cancels stale requests in cleanup", "one fetch on mount only", "fetching in render", "a global fetch"], "A",
         "Depending on id and cleaning up stale responses avoids showing data for the wrong user."),
        ("ADVANCED", "What problem does useCallback solve compared to defining functions inline?",
         ["it keeps the function reference stable so memoised children skip re-renders", "it makes functions faster", "it converts functions to strings", "it runs functions immediately"], "B",
         "useCallback memoises the function so its reference changes only when dependencies change."),
        ("ADVANCED", "Why can reading state inside useEffect and setting state directly lead to extra renders?",
         ["setting state triggers another render, so deriving data during render may be better", "effects cannot set state", "state is immutable in effects", "the DOM blocks it"], "A",
         "State set in an effect causes an additional render cycle, so it is best avoided when unnecessary."),
        ("ADVANCED", "How does React StrictMode help reveal broken effects in development?",
         ["it mounts components twice so missing cleanups become visible", "it disables hooks", "it removes re-renders", "it caches all effects"], "C",
         "Double-invoking effects surfaces effects that are not idempotent or lack proper cleanup."),
        ("ADVANCED", "A timer updates a value every second. Which effect setup prevents the timer from multiplying after re-renders?",
         ["create the interval once with [] deps and clear it in the cleanup", "create a new interval on every render", "use setInterval without cleanup", "store the interval in state"], "D",
         "With an empty dependency array the interval is created once and its cleanup clears it."),
        ("ADVANCED", "Why is storing derived values in state a common mistake?",
         ["it duplicates data that can drift out of sync, so derive it during render or with useMemo", "state cannot store numbers", "derived values are slower in state", "state is destroyed on update"], "A",
         "Storing derived data duplicates source-of-truth state and risks inconsistency, so compute it instead."),
        ("ADVANCED", "Which hook is most appropriate to run layout measurements that must complete before the browser paints?",
         ["useLayoutEffect", "useEffect", "useState", "useRef"], "B",
         "useLayoutEffect runs synchronously after DOM mutations but before paint, avoiding flicker."),
    ],
    135: [
        ("BEGINNER", "What is a router in a single-page application?",
         ["a component that maps URLs to rendered components", "a networking library", "a database", "a bundler"], "A",
         "A router reads the URL and renders the component associated with that route."),
        ("BEGINNER", "Which package is the standard routing library for React?",
         ["react-router-dom", "express", "axios", "redux"], "B",
         "react-router-dom is the widely used routing library for React applications."),
        ("BEGINNER", "Which component wraps all route definitions in react-router?",
         ["<Routes>", "<Router>", "<Route>", "<Link>"], "C",
         "The Routes container holds Route definitions and matches them against the current location."),
        ("BEGINNER", "What does the <Link> component do?",
         ["creates a navigation link without reloading the page", "fetches remote data", "renders an image", "uploads files"], "D",
         "Link performs client-side navigation, updating the URL without a full page reload."),
        ("BEGINNER", "Which hook gives access to the current location object in react-router?",
         ["useLocation", "useState", "useParams", "useNavigate"], "A",
         "useLocation returns the current location, including its pathname and search."),
        ("BEGINNER", "Which hook reads dynamic segments from the URL?",
         ["useParams", "useState", "useRoute", "useMatch"], "B",
         "useParams returns the dynamic parameters captured in the matched route pattern."),
        ("BEGINNER", "What does code splitting do in a React app?",
         ["splits the JavaScript bundle into smaller chunks loaded on demand", "divides CSS into files", "separates HTML from JS", "splits the server"], "C",
         "Code splitting loads only the code needed for the current route, reducing the initial download."),
        ("BEGINNER", "Which feature of React.lazy is used together with it?",
         ["React.Suspense", "React.memo", "StrictMode", "Fragment"], "A",
         "React.lazy components are wrapped in Suspense to show a fallback while they load."),
        ("BEGINNER", "What is the virtual DOM?",
         ["an in-memory representation of the UI that React diffs before updating the real DOM", "a real DOM clone in the browser", "a headless browser", "a template engine"], "B",
         "The virtual DOM is a lightweight JavaScript tree React uses to compute minimal DOM updates."),
        ("BEGINNER", "Which button type navigates the user back one step in history with useNavigate?",
         ["navigate(-1)", "back()", "goBack", "history.back()"], "C",
         "Calling navigate(-1) moves one step back in the browser history stack."),
        ("INTERMEDIATE", "Which Route path matches both /users and /users/123?",
         ["/users/:id", "/users/*id", "/users+", "/users?"], "D",
         "The :id parameter matches a dynamic segment, so /users/123 satisfies the path."),
        ("INTERMEDIATE", "What is the correct way to render a 404 fallback inside <Routes>?",
         ["<Route path='*' element={<NotFound />} />", "<Route path='404' element={<NotFound />} />", "<NotFound path='*' />", "<ErrorPage />"], "A",
         "A route with path '*' catches any unmatched path and renders the fallback."),
        ("INTERMEDIATE", "Which hook replaces the current entry in history instead of pushing a new one?",
         ["navigate(to, { replace: true })", "navigate(to)", "useLocation()", "window.history.pushState"], "B",
         "Passing { replace: true } swaps the current history entry rather than adding one."),
        ("INTERMEDIATE", "What does React.lazy(() => import('./Page')) return?",
         ["a component that loads Page on demand", "an HTML element", "a promise wrapper for data", "a context object"], "A",
         "React.lazy wraps a dynamic import so the component is loaded only when first needed."),
        ("INTERMEDIATE", "What happens inside React.Suspense while a lazy component is loading?",
         ["the fallback prop is rendered", "the page crashes", "a blank screen appears", "the browser reloads"], "B",
         "Suspense renders the fallback element until the lazy component has loaded."),
        ("INTERMEDIATE", "Why does navigating between routes with Link avoid a full page refresh?",
         ["the router intercepts the click and updates the history state client-side", "the browser caches the page", "Link uses an iframe", "the server responds instantly"], "C",
         "The router prevents the default navigation and swaps the rendered view without reloading."),
        ("INTERMEDIATE", "Which element type is preferred for links to external sites?",
         ["a plain <a> tag", "a <Link>", "a <NavLink>", "a <Route>"], "A",
         "Plain anchors handle external URLs, while Link is intended for in-app navigation."),
        ("INTERMEDIATE", "What is the main benefit of route-based code splitting?",
         ["each route downloads only its own chunk, shrinking the initial bundle", "routes are rendered faster by the server", "CSS is removed", "cookies are smaller"], "B",
         "Route-based splitting loads a chunk only when its route is visited, cutting the initial download."),
        ("INTERMEDIATE", "Which React tool profiles where rendering time is spent in production builds?",
         ["the React DevTools Profiler", "the browser view-source", "console.log", "npm audit"], "C",
         "The Profiler tab records renders and shows which components cost the most time."),
        ("INTERMEDIATE", "What does the <Navigate> component do when rendered?",
         ["redirects the user to another route immediately", "renders an image", "logs the user out", "refreshes the page"], "A",
         "Rendering <Navigate to='...' /> performs an immediate client-side redirect."),
        ("ADVANCED", "Which pattern is best for lazy-loading a route only after authentication succeeds?",
         ["guard the route and conditionally render the lazy component after auth resolves", "load all routes eagerly", "hide the router", "disable code splitting"], "A",
         "Conditionally rendering the lazy route after auth avoids loading protected code for unauthorised users."),
        ("ADVANCED", "Why can React.lazy fail to load on refresh when code splitting is combined with server-rendered routes?",
         ["the chunk URL may 404 if the server does not serve hashed chunks, so a SPA fallback is needed", "React.lazy is unstable", "the browser disables imports", "bundlers forbid lazy loading"], "B",
         "Without a proper SPA fallback, the server may not know the new chunk filename and return 404."),
        ("ADVANCED", "What is the benefit of prefetching a lazy chunk on hover before navigation?",
         ["the chunk starts loading early so navigation feels instant", "it makes the bundle smaller", "it disables the router", "it caches API data"], "A",
         "Prefetching on hover overlaps download time with the user's decision to navigate."),
        ("ADVANCED", "Which strategy most reduces Time to Interactive for a landing page?",
         ["load critical content and defer non-critical chunks and heavy libraries", "bundle everything into one file", "increase animation speed", "use inline styles only"], "B",
         "Deferring non-critical code shortens the main thread work required before interactivity."),
        ("ADVANCED", "Why should route transitions avoid unmounting the previous view before the new one is ready?",
         ["showing a fallback or shared shell prevents layout jumps and keeps the UI responsive", "the old view must always stay", "React forbids it", "it wastes memory"], "A",
         "Keeping a stable shell and swapping content avoids sudden blank screens during navigation."),
        ("ADVANCED", "When navigating, what is the purpose of passing a state object to navigate('...', { state: {...} })?",
         ["carrying non-serialisable or transient data to the next route without putting it in the URL", "styling the target page", "sizing the browser", "hiding the URL bar"], "B",
         "Location state transports extra data to the destination route without exposing it in the URL."),
        ("ADVANCED", "Which approach best prevents a query-only navigation from recreating the component?",
         ["treat query changes as a reason to update, not unmount, and read them via hooks", "remount the component", "reload the page", "duplicate the route"], "A",
         "Reading query params with hooks keeps the component mounted and updates derived data in place."),
        ("ADVANCED", "Why is splitting vendor libraries like lodash and React into separate chunks usually beneficial?",
         ["their hashes change rarely, so browsers can cache them across deploys", "it increases requests", "it disables caching", "it removes code"], "B",
         "Stable vendor chunks stay cached even when app code changes, improving repeat-load performance."),
        ("ADVANCED", "Which metric best measures whether a route becomes usable quickly after navigation?",
         ["time to render the route's content and have it responsive, not just first paint", "the number of routes", "bundle size alone", "the page title length"], "A",
         "Usable-interaction time reflects the experience better than raw first-paint timing."),
        ("ADVANCED", "What is the recommended way to handle scroll restoration when navigating between long pages?",
         ["call window.scrollTo(0, 0) on route change or use router scroll-restoration support", "do nothing and let the browser decide", "reload the page", "keep all content on one page"], "A",
         "Explicitly resetting scroll on navigation keeps users at the top of the new page consistently."),
    ],
}
