# -*- coding: utf-8 -*-
"""
Question bank for subject 52: CLD106 - Blockchain & Cryptocurrency.
Category: Cloud & Distributed Computing.

Topics:
  256: Blockchain Fundamentals
  257: Cryptography & Hashing
  258: Consensus Mechanisms
  259: Smart Contracts & Platforms
  260: Cryptocurrency & DApps

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    256: [
        ("BEGINNER", "Which best describes the nature of a blockchain?",
         ["A distributed, append-only ledger of records stored across many nodes", "A single spreadsheet held by one bank", "A type of antivirus software", "A web browser plugin"], "A",
         "A blockchain is a shared, tamper-evident ledger maintained by a decentralised network of nodes."),
        ("BEGINNER", "Which term describes the linked structure of blocks in a blockchain?",
         ["Each block references the hash of the previous block", "Blocks are random and unordered", "Blocks are stored only on one server", "Blocks cannot be verified"], "A",
         "Chaining via the previous block's hash gives the chain its name and links all history in order."),
        ("BEGINNER", "Which property describes that records on a blockchain cannot be easily altered once written?",
         ["Immutability", "Volatility", "Opacity", "Reversibility"], "A",
         "Immutability means confirmed blocks are practically impossible to change without redoing enormous work."),
        ("BEGINNER", "Which characteristic means no single authority controls a public blockchain?",
         ["Decentralisation", "Centralisation", "Monopolisation", "Orchestration"], "A",
         "Decentralisation spreads control and validation across many independent participants."),
        ("BEGINNER", "What is the main purpose of a transaction on a blockchain?",
         ["To transfer value or data from one party to another in a verifiable way", "To delete previous records", "To rename the chain", "To speed up web pages"], "A",
         "Transactions carry value or data between addresses and are recorded permanently on the ledger."),
        ("BEGINNER", "Which of the following is a public blockchain?",
         ["Bitcoin", "A company's private ledger in Excel", "A password manager", "A print spooler"], "A",
         "Bitcoin is a well-known public blockchain open to anyone to read and participate in."),
        ("BEGINNER", "Which term describes a record of all confirmed transactions in a blockchain?",
         ["The distributed ledger", "The API key", "The boot sector", "The cookie file"], "A",
         "The ledger is the complete, replicated record of transactions shared across the network."),
        ("BEGINNER", "Which component lets users interact with a blockchain using a set of public and private keys?",
         ["A wallet", "A compiler", "A router", "A printer driver"], "A",
         "A wallet stores keys and manages addresses used to send and receive blockchain assets."),
        ("BEGINNER", "What is a node in a blockchain network?",
         ["A computer running software that validates and stores the ledger", "A single transaction", "A type of coin", "A web page"], "A",
         "Nodes are the participants that run blockchain software, maintain copies of the ledger and relay data."),
        ("BEGINNER", "Which of the following is an example of a permissioned blockchain?",
         ["Hyperledger Fabric deployed by a consortium", "Bitcoin mainnet", "Ethereum mainnet", "Litecoin"], "A",
         "Permissioned blockchains restrict participation to approved members, unlike open public networks."),
        ("INTERMEDIATE", "Why does changing one block require recomputing all subsequent blocks in a chain?",
         ["Each block's hash includes the previous block's hash, propagating the change", "Blocks are sorted alphabetically", "Blocks store no data", "Only the genesis block matters"], "A",
         "Because each block commits to the previous hash, altering any block invalidates every later block."),
        ("INTERMEDIATE", "Which problem does the distributed ledger solve compared with a single trusted database?",
         ["It removes reliance on one central authority for record keeping", "It guarantees instant deletion", "It removes the need for storage", "It makes data invisible"], "A",
         "A shared, verified ledger lets independent parties agree on records without trusting a single intermediary."),
        ("INTERMEDIATE", "A bank wants its partners to share a ledger but only allow approved firms to join. Which blockchain type fits?",
         ["Permissioned/private blockchain", "Public permissionless blockchain", "No blockchain can help", "A plain text file"], "A",
         "Permissioned chains restrict membership and roles, suiting consortia that need controlled access."),
        ("INTERMEDIATE", "Which mechanism makes a public blockchain 'trustless' between strangers?",
         ["Cryptographic validation and consensus instead of personal trust", "Legal contracts signed offline", "Central bank guarantees", "Shared passwords"], "A",
         "Users rely on cryptography and consensus rules rather than on trusting any counterparty."),
        ("INTERMEDIATE", "Which of these correctly identifies the genesis block?",
         ["The very first block in a blockchain", "The latest confirmed block", "A failed transaction", "The block with the most transactions"], "A",
         "The genesis block is block zero, the root from which all other blocks descend."),
        ("INTERMEDIATE", "Which concept refers to the number of copies of the ledger across nodes?",
         ["Replication", "Compression", "Encryption only", "Indexing"], "A",
         "Each full node keeps its own copy of the ledger, and replication makes tampering detectable."),
        ("INTERMEDIATE", "Why can a blockchain be described as 'append-only'?",
         ["New blocks are added to the end, but existing records are not removed or rewritten", "Old records are deleted weekly", "Only the start changes", "Records expire automatically"], "A",
         "The ledger only grows by appending new blocks; existing confirmed content stays put."),
        ("INTERMEDIATE", "Which statement about a block's contents is true?",
         ["A block contains a batch of transactions plus a header with hashes and metadata", "A block contains only images", "A block is one single transaction only", "A block stores no data"], "A",
         "Blocks bundle many transactions together with a header carrying the hash links and metadata."),
        ("INTERMEDIATE", "What does it mean for a blockchain to be 'tamper-evident'?",
         ["Unauthorised changes break hash links and are detectable by any node", "Changes are invisible to everyone", "Only the owner can see changes", "Changes erase the whole chain"], "A",
         "Any alteration breaks the hash chain, so nodes immediately detect divergence from the agreed history."),
        ("INTERMEDIATE", "Which scenario best explains why two nodes must agree on a single chain?",
         ["Otherwise the ledger would fork into conflicting versions of history", "Otherwise the chain would delete itself", "Otherwise coins would multiply infinitely", "Otherwise the network slows the internet"], "A",
         "Consensus keeps every honest node aligned on one canonical chain instead of competing histories."),
        ("ADVANCED", "A regulator demands the right to see and audit all transactions but not to approve them. Which design fits a permissioned network?",
         ["Give the regulator read-only access with cryptographic audit of the ledger", "Give the regulator the private keys of all users", "Let the regulator approve every transaction", "Remove the regulator from the network"], "A",
         "Role-based permissions in permissioned chains allow read-only oversight while preserving operational roles."),
        ("ADVANCED", "Why is the 51% attack dangerous for a public blockchain?",
         ["A majority of hashing power can reorder or censor transactions and double-spend", "It reduces block rewards to zero", "It reveals private keys instantly", "It deletes the genesis block"], "A",
         "Control of majority hash power lets an attacker rewrite recent history and spend the same coins twice."),
        ("ADVANCED", "Which property most directly limits the throughput of permissionless blockchains like Bitcoin?",
         ["Every full node must validate every transaction and block", "Transactions are never validated", "Nodes store only hashes", "Blocks are unlimited in size"], "A",
         "Requiring every node to verify everything caps throughput, trading scalability for decentralisation."),
        ("ADVANCED", "A consortium of banks needs privacy between members while sharing a common ledger. Which feature is essential?",
         ["Channel isolation or private data collections so only relevant members see records", "Publishing all records to everyone", "Storing data off-ledger without any audit", "Sharing all private keys"], "A",
         "Channels and private data collections restrict visibility to authorised members while keeping shared consensus."),
        ("ADVANCED", "Which trade-off does a larger block size typically introduce?",
         ["Higher throughput but greater centralisation pressure because full nodes need more resources", "Lower throughput but better privacy", "Guaranteed immutability forever", "No effect on nodes"], "A",
         "Bigger blocks increase throughput but raise storage and bandwidth needs, which can centralise validation."),
        ("ADVANCED", "Why might an enterprise choose a permissioned chain over a public one for GDPR compliance?",
         ["It can enforce access controls, data segregation and governance policies", "Permissioned chains have no data", "Public chains fully comply by default", "GDPR only applies to cloud storage"], "A",
         "Governance and access control in permissioned networks help satisfy regulatory obligations such as GDPR."),
        ("ADVANCED", "Which scenario most strongly threatens the long-term security of a proof-of-work chain?",
         ["One miner accumulating a majority of the total hashing power", "Users holding coins in hardware wallets", "A slow block time", "A small transaction fee"], "A",
         "A single actor controlling the majority of hash power can subvert consensus and rewrite history."),
        ("ADVANCED", "Which property best explains why public blockchains are considered more censorship-resistant than centralised ledgers?",
         ["No single authority can freeze or erase records without the network's agreement", "Governments cannot read them", "They are invisible to search engines", "They cannot be copied"], "A",
         "Distributed control means censoring or altering records requires cooperation (or overwhelming power) across the network."),
        ("ADVANCED", "A firm must prove a document existed at a given time. Which blockchain technique records the proof cheaply?",
         ["Timestamping a hash of the document into a transaction", "Storing the entire document on every node", "Encrypting the document with the miner's key", "Printing the document on paper"], "A",
         "Committing a hash anchors the document's existence without revealing or duplicating its full content."),
        ("ADVANCED", "What is the primary reason a blockchain node verifies the full history before trusting new blocks?",
         ["To ensure the new block extends a valid chain and spends only valid outputs", "To speed up the internet", "To collect transaction fees twice", "To match the logo colour"], "A",
         "Full validation checks that transactions follow the rules and that history is consistent, preventing double spending."),
    ],
    257: [
        ("BEGINNER", "Which branch of mathematics underpins most blockchain cryptography?",
         ["Number theory and discrete logarithms", "Geometry", "Probability of weather", "Statistics of heights"], "A",
         "Blockchain relies on number-theoretic problems such as discrete logarithms for digital signatures."),
        ("BEGINNER", "What is the primary purpose of a hash function?",
         ["A function that maps arbitrary input to a fixed-size output", "A sorting algorithm", "A compression tool for videos", "A database index"], "A",
         "A hash function takes input of any length and produces a fixed-length digest."),
        ("BEGINNER", "Which property of a good hash function means different inputs should give different outputs?",
         ["Collision resistance", "Linearity", "Reversibility", "Idempotence"], "A",
         "Collision resistance makes it computationally infeasible to find two distinct inputs with the same hash."),
        ("BEGINNER", "Which hash function is famously used by Bitcoin?",
         ["SHA-256", "MD5", "CRC-32", "BASE64"], "A",
         "Bitcoin uses SHA-256 for proof-of-work and address generation."),
        ("BEGINNER", "Which algorithm is commonly used to create a digital signature in blockchain?",
         ["ECDSA (Elliptic Curve Digital Signature Algorithm)", "AES in CBC mode", "ZIP compression", "XOR encryption"], "A",
         "ECDSA is used by Bitcoin and many chains to sign transactions with a private key."),
        ("BEGINNER", "Which key must be kept secret by its owner?",
         ["The private key", "The public key", "The block hash", "The genesis timestamp"], "A",
         "The private key signs transactions, so its secrecy is essential; loss means loss of control."),
        ("BEGINNER", "Which of the following can anyone safely share?",
         ["The public key or address", "The private key", "The mnemonic seed phrase", "The wallet password"], "A",
         "Public keys and addresses are meant to be shared so others can send to you and verify signatures."),
        ("BEGINNER", "What does 'hashing the previous block' provide in a chain?",
         ["A link that ties every block to its predecessor", "A way to compress blocks", "A method to mine faster", "An encryption of the coin"], "A",
         "The previous block's hash in each header creates the immutable link between blocks."),
        ("BEGINNER", "Which term describes converting plain text into cipher text?",
         ["Encryption", "Printing", "Formatting", "Indexing"], "A",
         "Encryption transforms readable data into an unreadable form using a key."),
        ("BEGINNER", "Which concept guarantees that a signed message could only have come from the holder of the private key?",
         ["Non-repudiation", "Bandwidth", "Caching", "Compression"], "A",
         "Non-repudiation means the signer cannot deny having signed, since only they possess the private key."),
        ("INTERMEDIATE", "Why can a password not be recovered by reversing a stored hash?",
         ["Hash functions are one-way, so reversing them is computationally infeasible", "Hashes are always random letters", "Passwords are stored in plain text", "Hashes lose their length"], "A",
         "One-way functions make preimage attacks impractical, which is why systems store password hashes."),
        ("INTERMEDIATE", "An attacker finds two distinct documents with the same hash. Which security property is broken?",
         ["Collision resistance", "Confidentiality", "Availability", "Ordering"], "A",
         "Two colliding inputs violate collision resistance, undermining integrity guarantees."),
        ("INTERMEDIATE", "How does adding a random 'nonce' to input affect a hash?",
         ["It produces an unpredictable different digest each time, used in mining", "It makes hashing impossible", "It shortens the digest", "It encrypts the output"], "A",
         "Varying the nonce changes the hash unpredictably, which is how miners search for a valid proof of work."),
        ("INTERMEDIATE", "Which pair of operations do asymmetric keys perform?",
         ["The private key signs; the public key verifies", "Both keys encrypt", "Both keys hash", "The public key signs; the private key verifies"], "A",
         "In signing, the private key creates the signature and the public key verifies it."),
        ("INTERMEDIATE", "What is a digital signature mainly used for in a transaction?",
         ["Proving the sender authorised the transfer of funds", "Hiding the amount", "Speeding up blocks", "Adding interest"], "A",
         "A valid signature proves the holder of the private key authorised the transaction."),
        ("INTERMEDIATE", "Which operation creates an address commonly shown to receive funds?",
         ["Hashing the public key into a shorter address", "Encrypting the private key", "Multiplying two hashes", "Concatenating block times"], "A",
         "Most chains hash the public key to derive a shorter, human-friendly address."),
        ("INTERMEDIATE", "Why is SHA-256 preferred over MD5 for new blockchain designs?",
         ["SHA-256 has much stronger collision resistance and security margins", "MD5 produces longer hashes", "MD5 is a symmetric cipher", "SHA-256 is faster to reverse"], "A",
         "MD5's collisions are practical to find, so modern systems choose the stronger SHA-256."),
        ("INTERMEDIATE", "Which statement about public-key cryptography is correct?",
         ["It uses a mathematically related key pair, one public and one private", "It uses the same key to encrypt and decrypt", "It has no keys at all", "It relies on a shared password"], "A",
         "Asymmetric cryptography pairs a public key for verification and a private key for signing."),
        ("INTERMEDIATE", "What does the integrity property of a hash detect?",
         ["Any change to the input, no matter how small, alters the digest", "The length of the input", "The age of the data", "The file's owner"], "A",
         "Even a single flipped bit changes the digest, so tampering is immediately detectable."),
        ("INTERMEDIATE", "Which term describes an attacker trying every possible input to guess a hash's preimage?",
         ["Brute force attack", "Fishing trip", "Rebooting the node", "Compiling the chain"], "A",
         "Brute force exhaustively searches inputs, which strong hashes make impractical."),
        ("ADVANCED", "Why is ECDSA preferred over older RSA for many blockchains?",
         ["Elliptic curves give equivalent security with much shorter keys, saving space", "RSA cannot sign messages", "ECDSA is a hash function", "RSA keys never expire"], "A",
         "Shorter ECDSA keys offer equal or better security, which matters on space-constrained ledgers."),
        ("ADVANCED", "What is the main weakness of a weak random number generator when creating a private key?",
         ["Two users may derive the same or predictable keys, compromising funds", "Keys become too long", "Hashes get shorter", "The wallet cannot encrypt"], "A",
         "Predictable randomness lets attackers reproduce keys, a known cause of stolen cryptocurrency."),
        ("ADVANCED", "How does a Merkle tree reduce the data a light client must download?",
         ["It lets clients verify one transaction using only a few hashes instead of the whole block", "It deletes old blocks", "It compresses all coins into one", "It removes signatures"], "A",
         "Merkle proofs authenticate a single leaf with a short path of hashes, enabling light verification."),
        ("ADVANCED", "Which attack does a timestamp or randomness from a future block mitigate in hash-based schemes?",
         ["Front-running or manipulation of order by validators", "Collision of public keys", "Shorter addresses", "Mining speed variance"], "A",
         "Committing to a future, unpredictable value blinds validators from manipulating outcome order."),
        ("ADVANCED", "Why must blockchain nodes verify that a signature's r and s values are in valid ranges?",
         ["To avoid malleability where a third party can alter the transaction's signature representation", "To shorten the signature", "To speed up mining", "To hide the sender"], "A",
         "Malleability lets attackers change the signature encoding without invalidating it, which can break higher-level logic."),
        ("ADVANCED", "What cryptographic property is threatened if an attacker can perform a chosen-prefix collision?",
         ["Trusted setups and commitments can be forged, breaking consensus assumptions", "The chain becomes faster", "Addresses become longer", "Fees double"], "A",
         "Chosen-prefix collisions enable crafted duplicates that break commitment and identity schemes."),
        ("ADVANCED", "Which design decision reduces the risk of quantum attacks on public-key signatures?",
         ["Planning for post-quantum signature schemes or adding them as a transition path", "Reusing the same key forever", "Using only symmetric keys", "Storing keys in plain text"], "A",
         "Quantum computers threaten classical signatures, so post-quantum algorithms are the forward-looking mitigation."),
        ("ADVANCED", "Why is iterating a hash many times (key stretching) valuable for wallet encryption?",
         ["It makes brute-force guessing far slower for an attacker", "It produces longer keys", "It makes the hash reversible", "It removes the salt"], "A",
         "Repeated hashing multiplies the cost of each password guess, deterring offline attacks."),
        ("ADVANCED", "What is the role of a cryptographic commitment in a fair coin-flip on-chain?",
         ["It hides a choice until all parties commit, then reveals it verifiably", "It doubles the coins", "It encrypts the block reward", "It deletes the previous block"], "A",
         "Commitments hide values first and reveal them later, preventing one party from learning and changing the outcome."),
        ("ADVANCED", "Which property is required for a hash function used in proof-of-work mining?",
         ["Finding a valid preimage must require effort but verifying it must be cheap", "The output must be reversible", "The output must equal the input", "Mining must need no randomness"], "A",
         "Proof of work relies on asymmetry: hard to find, trivial to verify."),
    ],
    258: [
        ("BEGINNER", "What is the purpose of a consensus mechanism in a blockchain?",
         ["To make distributed nodes agree on one valid version of the ledger", "To encrypt transactions", "To shorten the chain", "To delete old blocks"], "A",
         "Consensus lets independent nodes settle on a single canonical history."),
        ("BEGINNER", "Which consensus mechanism uses computational work to secure the network?",
         ["Proof of Work", "Proof of Trust", "Proof of Favour", "Proof of Speed"], "A",
         "Proof of Work requires miners to solve a costly computational puzzle to add blocks."),
        ("BEGINNER", "Which consensus mechanism requires validators to lock up coins as collateral?",
         ["Proof of Stake", "Proof of Work", "Proof of Ownership", "Proof of Time"], "A",
         "In Proof of Stake, validators stake cryptocurrency and risk losing it if they misbehave."),
        ("BEGINNER", "Which of the following is a classic proof-of-work blockchain?",
         ["Bitcoin", "A school gradebook", "A paper ledger", "A chat server"], "A",
         "Bitcoin is the canonical example of a proof-of-work blockchain."),
        ("BEGINNER", "What does 'mining' refer to in proof-of-work blockchains?",
         ["Finding a valid block by solving a cryptographic puzzle", "Digging for physical gold", "Compiling application code", "Deleting old transactions"], "A",
         "Miners race to find a hash below the target difficulty to earn the right to add a block."),
        ("BEGINNER", "Which term describes how hard it is to find a valid proof-of-work block?",
         ["Difficulty", "Latency", "Bandwidth", "Ping"], "A",
         "Difficulty adjusts the puzzle so block production stays near a target average time."),
        ("BEGINNER", "Which token do validators typically receive as an incentive in proof of work?",
         ["New coins and transaction fees", "Free electricity", "Discount vouchers", "Stock options"], "A",
         "Successful miners earn the block subsidy plus fees, motivating honest participation."),
        ("BEGINNER", "What is a blockchain fork?",
         ["A divergence into two competing chains or versions of history", "A software update to a wallet", "A coin being split into cents", "A copy of the codebase"], "A",
         "A fork occurs when nodes disagree about which blocks are valid, splitting the chain."),
        ("BEGINNER", "Which consensus mechanism is generally far more energy-efficient than proof of work?",
         ["Proof of Stake", "Proof of Work", "Proof of Burn only", "Proof of Compute"], "A",
         "Proof of Stake replaces wasteful computation with staked capital, cutting energy use dramatically."),
        ("BEGINNER", "Which of the following is an example of a proof-of-stake network?",
         ["Ethereum after the merge", "Bitcoin", "Litecoin", "Monero"], "A",
         "Ethereum moved to proof of stake in the Merge, becoming its flagship example."),
        ("INTERMEDIATE", "Why does proof of work discourage double-spending by an attacker?",
         ["Rewriting history requires redoing the costly work for every later block", "Blocks are free to create", "Only banks can double-spend", "The chain is hidden"], "A",
         "The cost of re-mining all blocks after a fork makes deep reorganisations economically punishing."),
        ("INTERMEDIATE", "Which problem do both PoW and PoS address?",
         ["Sybil attacks where a user creates many fake identities to dominate voting", "Slow internet connections", "Small block sizes", "High transaction fees only"], "A",
         "Both mechanisms tie power to scarce resources (work or stake), defeating identity spam."),
        ("INTERMEDIATE", "In proof of stake, what happens to a validator who proposes an invalid block?",
         ["Their stake can be slashed as a penalty", "They win more rewards", "Their keys are copied", "They are given extra blocks"], "A",
         "Slashing burns part of the misbehaving validator's stake to punish dishonest behaviour."),
        ("INTERMEDIATE", "Which statement best describes 'difficulty adjustment'?",
         ["It retargets the puzzle so blocks arrive at a stable average interval", "It lowers transaction fees", "It deletes old blocks", "It reduces the number of miners"], "A",
         "Adjustment keeps block time steady as hashing power grows or shrinks."),
        ("INTERMEDIATE", "Why do competing blockchain consensus algorithms exist?",
         ["Each trades off security, speed, energy and decentralisation differently", "There is only one perfect algorithm", "Algorithms are interchangeable", "Consensus is not needed"], "A",
         "Different designs balance throughput, finality, cost and resilience for varied use cases."),
        ("INTERMEDIATE", "Which term describes a chain division caused by a permanent change in the rules?",
         ["A hard fork", "A soft reboot", "A cache flush", "A DNS lookup"], "A",
         "A hard fork changes the protocol so nodes following old rules can no longer agree with new ones."),
        ("INTERMEDIATE", "In PoS, which factor most directly determines a validator's voting weight?",
         ["The amount of cryptocurrency they have staked", "Their computer's clock speed", "Their location", "Their internet provider"], "A",
         "Voting influence scales with staked amount and often the duration of the stake."),
        ("INTERMEDIATE", "What is the main advantage of a delegated proof of stake design?",
         ["Voters elect a small set of block producers, giving speed at the cost of some decentralisation", "It needs no stake", "It is purely proof of work", "It has no validators"], "A",
         "DPoS uses elected delegates to produce blocks quickly while token holders retain voting power."),
        ("INTERMEDIATE", "Which consensus property means once a block is confirmed it will never be reverted?",
         ["Finality", "Reversibility", "Volatility", "Redundancy"], "A",
         "Finality guarantees that confirmed blocks cannot be undone without exceptional conditions."),
        ("INTERMEDIATE", "Why can a very short block time hurt a PoW chain?",
         ["It increases the chance of simultaneous blocks and wasted orphaning", "It always improves security", "It lowers difficulty", "It deletes transactions"], "A",
         "Tiny block intervals raise orphan rates as miners race and produce competing blocks."),
        ("ADVANCED", "Which attack involves a miner mining blocks in secret to later release a longer chain?",
         ["A selfish mining attack that can outperform honest miners", "A DDoS on the mempool only", "A phishing email", "A dictionary attack"], "A",
         "Selfish mining withholds blocks strategically to gain extra reward and occasionally rewrite history."),
        ("ADVANCED", "Under which condition can a proof-of-work attacker reliably double-spend?",
         ["When they control a majority of the total hash power for longer than the merchant waits", "When they use a hardware wallet", "When fees are zero", "When the chain is private"], "A",
         "Majority hash power lets an attacker outpace honest miners and rewrite recent history."),
        ("ADVANCED", "Why is 'nothing at stake' a concern in some proof-of-stake designs?",
         ["Validators have no cost to vote on every fork, creating instability", "Validators can never be penalised", "Staking always fails", "Blocks produce themselves"], "A",
         "Without slashing, validators lose nothing by supporting multiple forks, threatening consensus."),
        ("ADVANCED", "Which mechanism prevents proof-of-stake 'grinding' where a validator influences future randomness?",
         ["Using unpredictable randomness from later blocks or VRF (verifiable random functions)", "Letting validators choose random numbers freely", "Disabling randomness", "Using only the block height"], "A",
         "VRFs and delayed randomness stop validators from manipulating which of them is selected."),
        ("ADVANCED", "What is the primary economic argument that slashing penalties secure a PoS network?",
         ["The potential loss of stake outweighs any profit from attacking", "Penalties are always zero", "Attackers are immune to loss", "Fines are paid in fiat"], "A",
         "Rationally, a validator will not risk losing more than they could ever gain from an attack."),
        ("ADVANCED", "Which property distinguishes BFT-style consensus such as Tendermint or HotStuff?",
         ["It requires a fixed set of validators and reaches deterministic finality quickly", "It works with no validators", "It needs heavy computation", "It is a proof-of-work puzzle"], "A",
         "PBFT-family algorithms reach fast, deterministic agreement among known validators."),
        ("ADVANCED", "Which trade-off does increasing the number of consensus validators introduce?",
         ["More decentralisation but slower agreement due to more communication", "Faster agreement always", "Less security", "No effect on latency"], "A",
         "Agreement messages grow with validator count, so larger sets are slower but harder to capture."),
        ("ADVANCED", "Why would an attacker prefer a reorg that is deep but short enough to avoid detection?",
         ["Shallow reorgs are cheap but visible, so the depth is a cost-versus-detection trade-off", "Deep reorgs always succeed", "Reorgs need no hash power", "Detection is impossible"], "A",
         "Longer rewrites cost more work and are easier to notice, so attackers balance cost and stealth."),
        ("ADVANCED", "Which consensus scenario creates an irreversible social dispute that requires a hard fork?",
         ["A security flaw or community disagreement that old-rule nodes will not accept as fixed", "A change in transaction fees", "A new block hash", "A longer block time"], "A",
         "When the network cannot agree on fixing a flaw or changing rules, the chain splits permanently."),
        ("ADVANCED", "What is the purpose of a finality gadget attached to a longest-chain PoW protocol?",
         ["It adds deterministic finality so honest nodes agree a block cannot be reverted", "It removes block rewards", "It doubles the difficulty", "It encrypts the ledger"], "A",
         "Finality gadgets like Casper FFG layer irreversible checkpoints onto probabilistic chains."),
    ],
    259: [
        ("BEGINNER", "Which statement best defines a smart contract?",
         ["A program that executes automatically when predefined conditions are met", "A paper legal agreement", "A type of antivirus", "A database index"], "A",
         "Smart contracts are self-executing code stored and run on a blockchain."),
        ("BEGINNER", "Which blockchain platform is best known for general-purpose smart contracts?",
         ["Ethereum", "Bitcoin", "Dogecoin", "Litecoin"], "A",
         "Ethereum popularised programmable smart contracts with the Ethereum Virtual Machine."),
        ("BEGINNER", "Which programming language is most commonly used to write Ethereum smart contracts?",
         ["Solidity", "COBOL", "Prolog", "Fortran"], "A",
         "Solidity is the primary language for Ethereum smart contracts."),
        ("BEGINNER", "Where does smart contract code actually execute?",
         ["On the blockchain nodes via a virtual machine", "On the user's web browser", "On a single central server", "On the accountant's spreadsheet"], "A",
         "Smart contracts run deterministically on the network's nodes through the EVM or similar VM."),
        ("BEGINNER", "What does 'gas' measure in Ethereum?",
         ["The computational cost of executing operations", "The physical fuel of servers", "The chain's bandwidth", "The number of nodes"], "A",
         "Gas prices execution effort, with users paying fees in the network's native token."),
        ("BEGINNER", "Which term describes a program running on a blockchain that is visible to all?",
         ["A DApp (decentralised application)", "A compiled binary hidden on disk", "A proprietary API", "A firewall rule"], "A",
         "DApps are applications whose logic runs on-chain and is publicly verifiable."),
        ("BEGINNER", "Which EVM concept is a persistent piece of data stored by a contract?",
         ["State variables", "CPU registers", "Browser cookies", "DNS records"], "A",
         "State variables persist contract data on-chain between transactions."),
        ("BEGINNER", "What happens when a smart contract function is called with insufficient gas?",
         ["The transaction reverts and gas is consumed", "The contract still runs", "The chain restarts", "The fee is refunded in full"], "A",
         "Out-of-gas transactions revert their effects but the spent gas is not refunded."),
        ("BEGINNER", "Which component describes the account that owns and can deploy a contract?",
         ["The deploying address, often the contract owner", "The mempool", "The blockchain explorer", "The genesis block"], "A",
         "Deployment is done from an address that typically retains special ownership privileges."),
        ("BEGINNER", "Which of the following is a blockchain platform focused on smart contracts?",
         ["Ethereum", "WordPress", "Apache", "MySQL"], "A",
         "Ethereum is a leading smart-contract platform, alongside others like Solana and Cardano."),
        ("INTERMEDIATE", "Why is determinism critical for smart contract execution?",
         ["Every node must compute the identical result for consensus to hold", "Results can differ per node", "Randomness is required", "Nodes skip verification"], "A",
         "If nodes produced different results, they could not agree on the same state."),
        ("INTERMEDIATE", "Which design problem does a reentrancy attack exploit?",
         ["A contract calling an external contract before updating its own state", "A contract with no state", "A very large block size", "A slow internet connection"], "A",
         "Reentrancy happens when external calls re-enter the contract before state is updated, enabling repeated withdrawals."),
        ("INTERMEDIATE", "Which pattern prevents reentrancy in a token contract?",
         ["Updating balances before making the external transfer (checks-effects-interactions)", "Making all external calls first", "Using more gas", "Disabling logs"], "A",
         "Finishing all state changes before interacting externally blocks recursive re-entry."),
        ("INTERMEDIATE", "What is the main purpose of the checks-effects-interactions pattern?",
         ["To prevent state corruption and reentrancy by ordering operations safely", "To make contracts faster", "To hide the contract bytecode", "To reduce block rewards"], "A",
         "Updating state before external calls prevents contracts from being exploited mid-execution."),
        ("INTERMEDIATE", "Which unit is the smallest denomination of Ether?",
         ["Wei", "Ether", "Gwei", "Shard"], "A",
         "Wei is 10^-18 Ether, the base integer unit used internally."),
        ("INTERMEDIATE", "How does a contract typically send tokens to another address?",
         ["By calling a transfer or a transferFrom function on the token contract", "By printing a cheque", "By emailing a password", "By copying the address"], "A",
         "Token movement happens through the token contract's transfer functions, not raw coin sends."),
        ("INTERMEDIATE", "Which standard defines a common interface for fungible tokens such as ERC-20?",
         ["ERC-20", "ERC-721", "ERC-1155", "ERC-999"], "A",
         "ERC-20 specifies the fungible token interface adopted by most Ethereum tokens."),
        ("INTERMEDIATE", "Which standard defines non-fungible tokens (NFTs)?",
         ["ERC-721", "ERC-20", "ERC-404", "ERC-1"], "A",
         "ERC-721 defines unique, non-fungible tokens, each identified by its own token ID."),
        ("INTERMEDIATE", "Which mechanism limits how much gas a transaction can consume and protects the network?",
         ["The gas limit set by the sender", "The block timestamp", "The token name", "The node's CPU count"], "A",
         "Senders set a gas limit so runaway loops cannot drain their funds or stall nodes."),
        ("INTERMEDIATE", "Why do smart contracts need to be thoroughly audited before deployment?",
         ["Deployed bytecode is immutable and bugs cannot be patched without redeploying", "Audits speed up mining", "Audits add randomness", "Audits delete old code"], "A",
         "Because deployed contracts cannot be changed, vulnerabilities can permanently trap or lose funds."),
        ("ADVANCED", "Which upgrade pattern allows a contract's logic to be changed after deployment?",
         ["A proxy contract that delegates calls to a swappable implementation", "Editing the bytecode directly", "Restarting the blockchain", "Deleting and recreating the address"], "A",
         "Proxy contracts keep storage in one place and delegate logic to an addressable implementation that can be updated."),
        ("ADVANCED", "Why must upgradeable proxies carefully manage storage slot layout?",
         ["Delegated calls share the same storage, so slot mismatches corrupt state", "Storage is temporary", "Slots hold no data", "Proxies cannot store data"], "A",
         "Because delegatecall runs implementation logic on the proxy's storage, conflicting layouts overwrite critical state."),
        ("ADVANCED", "Which Oracle problem do price-feeding contracts face?",
         ["Off-chain data must be trusted or manipulated without a single source of truth", "On-chain data is always wrong", "Oracles are free", "Prices never change"], "A",
         "Contracts cannot fetch off-chain prices themselves, so they rely on trusted oracles that can be gamed."),
        ("ADVANCED", "Which approach best mitigates price-manipulation risk in a lending protocol?",
         ["Using time-weighted average prices (TWAP) instead of a single spot price", "Taking the latest trade price instantly", "Letting users set their own prices", "Disabling oracles"], "A",
         "TWAP averages out flash crashes and manipulation spikes, stabilising collateral valuations."),
        ("ADVANCED", "What is the purpose of a timelock in a governance contract?",
         ["To delay execution so users can review and react to dangerous proposals", "To speed up voting", "To hide proposals", "To add interest to funds"], "A",
         "Timelocks give the community a window to intervene before a risky change takes effect."),
        ("ADVANCED", "Why can a 'create2' address be a problem for fund recovery?",
         ["Contracts deployed via create2 can later be re-deployed at the same address, potentially with different logic", "create2 addresses are random", "create2 has no addresses", "create2 deletes the chain"], "A",
         "Create2 lets the same address host different code later, which can surprise protocols holding funds at that address."),
        ("ADVANCED", "Which scenario best describes a 'rug pull' vulnerability in a DApp?",
         ["Developers retain a backdoor that lets them drain user funds at any time", "The app is too slow", "The token name is long", "Users pay high gas"], "A",
         "Hidden admin powers in contracts let creators withdraw funds, a common scam pattern."),
        ("ADVANCED", "What does a flash loan attack exploit to manipulate price oracles?",
         ["Massive uncollateralised borrowing within one transaction to move market prices", "Long-term staking", "High withdrawal fees", "Slow block times"], "A",
         "Flash loans concentrate enormous capital in one transaction, letting attackers distort prices before normalising them."),
        ("ADVANCED", "Which property of the EVM makes cross-chain contracts hard to port?",
         ["Different VMs and storage models between chains", "All chains use identical EVMs", "Contracts run on laptops", "Chains share one VM"], "A",
         "Different chains have distinct execution environments, so contracts must be adapted or bridged."),
        ("ADVANCED", "Why do protocols often pause or 'circuit-break' during an attack?",
         ["Halting withdrawals contains the damage until the vulnerability is fixed", "Pausing speeds up mining", "Pausing deletes attacker funds", "Pausing increases token price"], "A",
         "An emergency pause freezes funds and buys time, limiting exploit losses."),
    ],
    260: [
        ("BEGINNER", "Which option best defines a cryptocurrency?",
         ["A digital asset that uses cryptography and blockchain to work as money", "A type of paper bond", "A loyalty card", "A stock certificate"], "A",
         "Cryptocurrencies are digital currencies secured by cryptography and recorded on distributed ledgers."),
        ("BEGINNER", "Which of the following is the first and most well-known cryptocurrency?",
         ["Bitcoin", "Litecoin", "Ethereum", "Tether"], "A",
         "Bitcoin launched in 2009 as the first decentralised cryptocurrency."),
        ("BEGINNER", "What is a wallet seed phrase used for?",
         ["Recovering wallet keys if the device is lost", "Speeding up transactions", "Buying more coins", "Encrypting the blockchain"], "A",
         "The seed phrase regenerates all wallet keys, so it must be stored safely."),
        ("BEGINNER", "What is a DApp?",
         ["A decentralised application running on a blockchain", "A desktop word processor", "A database backup", "A domain name"], "A",
         "DApps run their logic on-chain through smart contracts instead of a central server."),
        ("BEGINNER", "Which term describes sending cryptocurrency from one wallet to another?",
         ["A transaction", "A recompile", "A defragmentation", "A reboot"], "A",
         "Transactions move value between blockchain addresses and are recorded on the ledger."),
        ("BEGINNER", "What is a transaction fee primarily for?",
         ["Paying network participants who process and secure the transaction", "Buying insurance", "Purchasing tokens", "Funding a website"], "A",
         "Fees compensate miners or validators for including transactions in blocks."),
        ("BEGINNER", "Which of the following is a popular tool for viewing blockchain transactions?",
         ["A block explorer", "A text editor", "A calculator", "A media player"], "A",
         "Block explorers index and display blocks, transactions and balances on-chain."),
        ("BEGINNER", "What does a stablecoin aim to do?",
         ["Maintain a stable value, usually pegged to a fiat currency", "Grow 100% every day", "Disappear after use", "Pay dividends in shares"], "A",
         "Stablecoins peg their value to assets like the US dollar to reduce volatility."),
        ("BEGINNER", "Which action is most important for keeping cryptocurrency safe?",
         ["Never sharing your private key or seed phrase", "Posting keys in a group chat", "Writing the password on the wall", "Emailing the seed to support"], "A",
         "Anyone with the private key controls the funds, so secrecy is essential."),
        ("BEGINNER", "Which of the following describes the total number of bitcoins that will ever exist?",
         ["Capped at 21 million", "Unlimited", "One trillion", "No limit applies"], "A",
         "Bitcoin's supply is hard-capped at 21 million, enforced by its protocol."),
        ("INTERMEDIATE", "Which scenario best describes how a cryptocurrency wallet sends a payment?",
         ["It signs a transaction with the private key and broadcasts it to the network", "It emails the recipient the coins", "It edits the ledger directly", "It calls the bank"], "A",
         "Wallets create and sign transactions, which miners or validators then confirm into blocks."),
        ("INTERMEDIATE", "Why do transaction confirmation times vary on a congested network?",
         ["Miners prioritise transactions paying higher fees when blocks are full", "Confirmations are random", "Nodes delete waiting transactions", "Fees are fixed"], "A",
         "When the mempool is full, higher-fee transactions get included first, lengthening waits for low fees."),
        ("INTERMEDIATE", "Which factor makes Bitcoin's supply predictable and disinflationary?",
         ["The block reward halves roughly every four years", "Mining costs nothing", "New coins are minted on demand", "The supply resets yearly"], "A",
         "Halvings cut the new-coin issuance in half periodically, approaching the 21 million cap."),
        ("INTERMEDIATE", "Which category does Bitcoin's UTXO model belong to?",
         ["Unspent transaction outputs that act as discrete coins", "A single shared account balance", "A central ledger of IOUs", "A points system"], "A",
         "Bitcoin tracks unspent outputs that a new transaction consumes, unlike account-balance models."),
        ("INTERMEDIATE", "Which mechanism lets users interact with a smart-contract DApp without running a full node?",
         ["A wallet that signs transactions and talks to an RPC provider", "A full node on every phone", "Editing the ledger directly", "Using a block explorer only"], "A",
         "Light wallets sign locally and send signed transactions through RPC endpoints."),
        ("INTERMEDIATE", "Why are custodial exchanges considered risky for long-term storage?",
         ["The exchange controls the keys, so user funds can be lost if it fails", "Exchanges always double balances", "Exchanges are offline", "Custodial storage is free"], "A",
         "Custodians hold users' private keys, creating counterparty risk from hacks or insolvency."),
        ("INTERMEDIATE", "Which term describes moving tokens between a main chain and a second layer?",
         ["Bridging or layer-2 transfer", "Defragmentation", "Mining", "Compiling"], "A",
         "Bridges lock or wrap assets so they can be used across chains and layers."),
        ("INTERMEDIATE", "Which concept lets users verify a transaction without downloading the entire blockchain?",
         ["Merkle proofs and light client verification", "Full sync only", "Guesswork", "Printing the chain"], "A",
         "Light clients use Merkle proofs to verify data against block headers alone."),
        ("INTERMEDIATE", "Which popular crypto application lets users borrow and lend without a bank?",
         ["Decentralised finance (DeFi) protocols", "A local savings club", "A stockbroker", "A payroll system"], "A",
         "DeFi platforms automate lending, borrowing and trading through smart contracts."),
        ("INTERMEDIATE", "Which practice best protects against losing funds to a fake website?",
         ["Double-checking the exact URL and verifying signatures before signing", "Typing the seed into any popup", "Trusting links in emails", "Sharing the key with support"], "A",
         "Phishing sites steal keys, so verifying domains and rejecting unsolicited key requests is vital."),
        ("ADVANCED", "Which economic consequence does a 'token burn' typically produce?",
         ["A reduction in circulating supply, often raising scarcity", "A doubling of supply", "A permanent price cap", "A deletion of the chain"], "A",
         "Burning removes tokens from circulation, increasing scarcity under otherwise constant demand."),
        ("ADVANCED", "Which risk does a decentralised exchange (DEX) reduce compared with a centralised one?",
         ["Counterparty risk because users keep custody of funds in their own wallets", "Network latency", "Gas costs", "Wallet addresses"], "A",
         "DEXs let users trade directly from self-custodied wallets, avoiding exchange custody risk."),
        ("ADVANCED", "Why are governance tokens valuable beyond speculation?",
         ["They grant holders voting power over protocol decisions and fee settings", "They are always backed by gold", "They control node hardware", "They replace fiat cash"], "A",
         "Governance tokens give holders a voice in protocol parameter and policy changes."),
        ("ADVANCED", "Which vulnerability can a malicious token contract exploit in an integration?",
         ["Returning false or misreporting balances to trick automated logic", "Increasing block time", "Lowering gas", "Shortening addresses"], "A",
         "Non-compliant tokens can lie about balances or transfers, breaking integrations that assume ERC-20 behaviour."),
        ("ADVANCED", "What is the main purpose of a hardware wallet?",
         ["Keeping private keys offline so malware and hacks cannot extract them", "Mining faster", "Boosting transaction speed", "Storing keys in plain text"], "A",
         "Hardware wallets isolate keys in secure elements, dramatically reducing remote theft risk."),
        ("ADVANCED", "Which trade-off do users accept when choosing a very low transaction fee?",
         ["Long confirmation wait or being dropped during congestion", "Immediate finality", "Guaranteed inclusion", "Higher rewards"], "A",
         "Low-fee transactions wait longer in the mempool and may be left out of blocks entirely."),
        ("ADVANCED", "Why does a rollup-based layer 2 improve scalability?",
         ["It executes transactions off-chain and posts compressed proofs to the main chain", "It deletes main-chain data", "It needs no consensus", "It disables transactions"], "A",
         "Rollups batch computations off-chain and settle minimal proof data on-chain, easing congestion."),
        ("ADVANCED", "Which scenario best describes a 'dust' attack?",
         ["Sending tiny amounts to many addresses to cluster and trace their owners", "Deleting the chain", "Doubling a token supply", "Rewriting the genesis block"], "A",
         "Dust attacks de-anonymise users by linking their addresses through microscopic transfers."),
        ("ADVANCED", "Why should users rotate addresses rather than reuse one for all payments?",
         ["Address reuse links transactions and erodes pseudonymity", "Addresses expire monthly", "Rotation doubles balances", "Reuse speeds up mining"], "A",
         "Fresh addresses keep transaction histories separate, preserving more privacy."),
        ("ADVANCED", "Which combination best describes a robust self-custody setup?",
         ["Hardware wallet plus paper backup of the seed stored securely", "Keys kept only in a browser password manager", "Seed stored in an email draft", "One password for all exchanges"], "A",
         "Cold storage with a physical backup balances security and recovery if devices fail."),
    ],
}
