# -*- coding: utf-8 -*-
"""
Question bank for subject 39: CORE104 - Computer Architecture.
Category: Core Computer Science & Emerging Technologies.

Topics:
  191: CPU & Instruction Cycle
  192: Memory Hierarchy
  193: Pipelining & Hazards
  194: I/O & Peripherals
  195: Parallel & Multicore

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    191: [
        ("BEGINNER", "Which component of the CPU performs arithmetic and logical operations?",
         ["the arithmetic and logic unit (ALU)", "the control unit", "the memory management unit", "the floating point unit"], "A",
         "The ALU is dedicated to performing the arithmetic and logical computations inside the CPU."),
        ("BEGINNER", "Which register holds the memory address of the next instruction to be executed?",
         ["the accumulator", "the program counter (PC)", "the stack pointer", "the instruction register"], "B",
         "The program counter stores the address of the next instruction the CPU will fetch and execute."),
        ("BEGINNER", "What is the purpose of the control unit in a CPU?",
         ["to store the results of calculations", "to cache frequently used data", "to direct and coordinate the operations of the CPU", "to hold the current instruction being executed"], "C",
         "The control unit decodes instructions and issues the control signals that direct all CPU activity."),
        ("BEGINNER", "What is the correct order of the classic instruction cycle phases?",
         ["decode, execute, fetch, write-back", "execute, fetch, decode, store", "store, decode, fetch, execute", "fetch, decode, execute, write-back"], "D",
         "The classic cycle begins by fetching the instruction, decoding it, executing it, and then writing any result back."),
        ("BEGINNER", "What does an instruction set architecture (ISA) define?",
         ["the interface between software and hardware, including the supported instructions", "the physical layout of the silicon die", "the speed of the system clock", "the size of the cache memory"], "A",
         "An ISA specifies which instructions the processor supports and how programs communicate with it."),
        ("BEGINNER", "What is the role of the instruction register (IR) inside the CPU?",
         ["it holds the address of the next instruction", "it holds the currently fetched instruction while it is decoded and executed", "it stores the result of the last ALU operation", "it counts the number of executed instructions"], "B",
         "The instruction register stores the fetched instruction while the control unit decodes and executes it."),
        ("BEGINNER", "Which clock event triggers state transitions in a synchronous CPU?",
         ["a cache miss", "an interrupt request", "the rising or falling edge of the clock signal", "a page fault"], "C",
         "Synchronous CPUs change state on the edges of the periodic clock signal that paces all operations."),
        ("BEGINNER", "What is the role of the accumulator register?",
         ["it temporarily holds the operands and results of arithmetic operations", "it stores the address of the next instruction", "it decodes instructions", "it manages interrupts"], "A",
         "The accumulator is the register where arithmetic and logical results are temporarily kept during computation."),
        ("BEGINNER", "Which part of the CPU performs the decode stage of an instruction?",
         ["the control unit", "the ALU", "the L2 cache", "the system bus"], "A",
         "The control unit examines the opcode and determines which operations the instruction requires."),
        ("BEGINNER", "What is the function of the stack pointer (SP) register?",
         ["it points to the next instruction to execute", "it points to the top of the current call stack", "it stores the flags of the last operation", "it holds the base address of the data segment"], "B",
         "The stack pointer tracks the top of the call stack used for function calls, returns, and local storage."),
        ("INTERMEDIATE", "A program executes 1 billion instructions and consumes 4 billion clock cycles. What is the CPI?",
         ["4", "0.25", "1", "2"], "A",
         "CPI is cycles divided by instructions, so 4 billion divided by 1 billion gives a CPI of 4."),
        ("INTERMEDIATE", "On a 2 GHz processor, a program with CPI 2 runs for exactly 1 second. How many instructions does it execute?",
         ["5 billion", "1 billion", "2 billion", "4 billion"], "B",
         "The CPU runs 2 billion cycles per second and with CPI 2 it completes 1 billion instructions."),
        ("INTERMEDIATE", "A program has 500 instructions, each 4 bytes long. How many bytes of instruction memory does it occupy?",
         ["500", "1000", "2000", "4000"], "C",
         "Multiplying 500 instructions by 4 bytes each gives 2000 bytes of instruction storage."),
        ("INTERMEDIATE", "Which of the following changes the program counter to a non-sequential value?",
         ["an add instruction", "a nop instruction", "a load instruction", "a branch instruction"], "D",
         "A branch instruction overwrites the program counter with a target address instead of continuing sequentially."),
        ("INTERMEDIATE", "An interrupt is detected between instructions. What is saved before the interrupt handler runs?",
         ["the program counter and processor state", "the entire memory contents", "the cache contents", "nothing is saved"], "A",
         "The CPU saves the program counter and status so execution can resume exactly where it left off."),
        ("INTERMEDIATE", "If the clock period is 1 nanosecond, what is the clock frequency?",
         ["1 MHz", "1 GHz", "100 MHz", "10 GHz"], "B",
         "Frequency is the inverse of the period, so 1 divided by 1 nanosecond equals 1 GHz."),
        ("INTERMEDIATE", "A load instruction reads data from memory. Which pipeline stage typically performs the memory read?",
         ["the instruction decode stage", "the write-back stage", "the execute or memory access stage", "the fetch stage"], "C",
         "The execute or memory access stage computes the effective address and performs the actual memory read."),
        ("INTERMEDIATE", "Which register contains the result of the most recent ALU operation in many simple architectures?",
         ["the program counter", "the stack pointer", "the instruction register", "the accumulator"], "D",
         "The accumulator is a single register that holds the result of arithmetic and logical operations in simple CPUs."),
        ("INTERMEDIATE", "A program's execution time is 10 seconds at a 1 GHz clock. What is the total number of clock cycles used?",
         ["10 billion", "1 billion", "100 billion", "10 million"], "A",
         "At 1 GHz the CPU runs 1 billion cycles per second, so 10 seconds consume 10 billion cycles."),
        ("INTERMEDIATE", "What is the effect of the zero flag being set after an ALU operation?",
         ["the operation was signed", "the result of the operation was zero", "the CPU is idle", "the operation overflowed"], "B",
         "The zero flag is set whenever the result of the last ALU operation equals zero."),
        ("ADVANCED", "A CPU completes at most one instruction per cycle ideally, but a workload achieves only 0.25 IPC. What is the CPI?",
         ["4", "0.25", "2", "8"], "A",
         "IPC and CPI are reciprocals, so a CPI of 1 divided by 0.25 gives 4 cycles per instruction."),
        ("ADVANCED", "Why do superscalar CPUs need a register renaming unit?",
         ["to remove false data dependencies caused by register name reuse", "to increase the clock frequency", "to reduce the cache size", "to implement virtual memory"], "B",
         "Register renaming maps architectural registers to many physical registers to break false dependencies and enable more parallelism."),
        ("ADVANCED", "In out-of-order execution, why is a reorder buffer used?",
         ["to hold results and commit them in program order to preserve the architectural state", "to store decoded instructions for the front end", "to cache branch targets", "to schedule memory operations"], "C",
         "The reorder buffer lets instructions complete out of order yet retire in program order so exceptions stay precise."),
        ("ADVANCED", "An exception occurs during the execute stage of a load instruction. What must the CPU ensure before jumping to the handler?",
         ["that all earlier instructions have committed and the pipeline is flushed of younger instructions", "that the cache is flushed", "that the clock frequency is reduced", "that the stack pointer is zeroed"], "D",
         "Precise exceptions require the CPU to retire all older instructions and discard younger ones so state is consistent."),
        ("ADVANCED", "A variable-length ISA like x86 requires extra work in which part of the pipeline compared with a fixed-length ISA like MIPS?",
         ["instruction decode, because boundaries and lengths must be determined", "the ALU, because operands are wider", "write-back, because results are larger", "the register file, because more registers exist"], "A",
         "Finding the start and length of each variable-length instruction makes x86 decode substantially harder than fixed-width decode."),
        ("ADVANCED", "Why might a CPU move from a von Neumann single-bus design to a Harvard-like design?",
         ["to allow simultaneous access to instruction and data memory, reducing fetch stalls", "to reduce the number of registers", "to simplify the compiler", "to eliminate the need for interrupts"], "B",
         "Separate instruction and data paths let the fetch unit read the next instruction while another unit accesses data in the same cycle."),
        ("ADVANCED", "A game console uses a high-clock pipelined CPU while a server CPU uses a lower clock with more cores. What principle explains this trade-off?",
         ["latency versus throughput: a higher clock cuts per-instruction latency while more cores increase total throughput", "endianness matters more than clock speed", "cache size has no effect on performance", "clock speed is irrelevant to performance"], "C",
         "Latency-focused workloads benefit from a high clock, while throughput workloads benefit from more parallel cores at a lower clock."),
        ("ADVANCED", "Which component in a modern CPU predicts the target of a branch before it is executed?",
         ["the arithmetic unit", "the register file", "the store buffer", "the branch prediction unit"], "D",
         "The branch prediction unit guesses branch direction and target so the pipeline can keep fetching without stalling."),
        ("ADVANCED", "Why must a load and a later store to the same address be handled in order even on out-of-order machines?",
         ["to preserve memory ordering and prevent reading stale data, which requires memory disambiguation", "to keep the cache warm", "to reduce register pressure", "to allow the ALU to run faster"], "A",
         "Without knowing addresses are unrelated, the machine must assume the store could conflict, so ordered handling prevents stale reads."),
        ("ADVANCED", "A microarchitecture supports macro-op fusion. What is its main benefit?",
         ["it merges two simple instructions into one fused operation, reducing front-end throughput demands", "it doubles the clock speed", "it removes the need for a program counter", "it increases the ISA's instruction count"], "B",
         "Fusing common instruction pairs lets the front end deliver more work per cycle and reduces the number of pipeline slots consumed."),
    ],
    192: [
        ("BEGINNER", "Which is the fastest type of memory in a typical computer?",
         ["registers", "main memory", "a solid-state drive", "a magnetic disk"], "A",
         "Registers sit inside the CPU and are accessed in a single cycle, making them the fastest memory available."),
        ("BEGINNER", "Which type of memory is used as the main working memory and loses its contents when power is lost?",
         ["ROM", "DRAM", "flash storage", "EEPROM"], "B",
         "DRAM is volatile, so the data it holds disappears when the power is removed."),
        ("BEGINNER", "What is a cache in a computer system?",
         ["a small, fast memory that stores copies of frequently used data from main memory", "a large, slow backup disk", "a type of read-only memory", "a network device"], "C",
         "A cache keeps recently used data close to the CPU so most accesses are served faster than main memory."),
        ("BEGINNER", "Which storage device is typically the slowest in the memory hierarchy?",
         ["registers", "L2 cache", "main memory", "a magnetic hard disk"], "D",
         "A spinning magnetic disk has mechanical seek delays, making it the slowest level of the hierarchy."),
        ("BEGINNER", "What happens on a cache hit?",
         ["the requested data is found in the cache and served quickly", "the cache is flushed", "the data is read from the disk", "the cache doubles in size"], "A",
         "On a hit the cache already holds the data, so it is delivered to the CPU without a slower memory access."),
        ("BEGINNER", "What is a cache miss?",
         ["the requested data is not in the cache and must be fetched from a slower level", "the cache is empty forever", "the CPU stops working", "the cache is replaced by a register"], "A",
         "A cache miss means the requested block is absent from the cache, so it must be fetched from main memory at a higher cost."),
        ("BEGINNER", "Which level of the memory hierarchy is usually located directly on the CPU chip closest to the cores?",
         ["L3 cache shared by many cores", "DRAM modules", "L1 cache", "a solid-state disk"], "C",
         "The L1 cache is the smallest and fastest cache and is placed on the chip adjacent to each core."),
        ("BEGINNER", "What does the acronym RAM stand for?",
         ["read-only memory", "random access memory", "rapid access memory", "recursive allocation memory"], "D",
         "RAM stands for random access memory, meaning any byte can be read or written in roughly equal time."),
        ("BEGINNER", "Which of the following is a non-volatile memory?",
         ["NAND flash", "DRAM", "SRAM", "a CPU register"], "A",
         "NAND flash retains its data without power, making it non-volatile unlike the other choices."),
        ("BEGINNER", "What is the purpose of the memory hierarchy in a computer?",
         ["to give the CPU fast access to data at a reasonable cost", "to make memory slower", "to reduce the number of cores", "to eliminate the need for registers"], "B",
         "Combining fast but small memory near the CPU with slow but large memory far away balances speed and cost."),
        ("INTERMEDIATE", "A cache has a hit time of 2 ns and a miss penalty of 100 ns, with a 95% hit rate. What is the average access time?",
         ["6.9 ns", "10 ns", "7.0 ns", "2.1 ns"], "C",
         "The average is 2 + (0.05 times 100), giving 7.0 nanoseconds when the miss penalty is included."),
        ("INTERMEDIATE", "An L1 cache has a 90% hit rate, a hit time of 1 cycle, and a miss penalty of 10 cycles. What is the average memory access time in cycles?",
         ["2.5 cycles", "10 cycles", "1.9 cycles", "2.0 cycles"], "D",
         "The AMAT is 1 plus (0.10 times 10), which equals 2.0 cycles on average."),
        ("INTERMEDIATE", "A 32 KB cache uses 64-byte blocks. How many blocks does it hold?",
         ["512", "1024", "64", "256"], "A",
         "Dividing 32768 bytes by 64 bytes per block gives 512 blocks."),
        ("INTERMEDIATE", "In a fully associative cache, where can a block be placed?",
         ["only in one specific location", "anywhere in the cache", "only at even addresses", "only in the first slot"], "B",
         "A fully associative cache lets any block occupy any slot, so only the tag must be searched on lookup."),
        ("INTERMEDIATE", "Which cache mapping scheme divides the cache into sets where each set can hold several blocks?",
         ["fully associative", "direct mapped", "set-associative", "sector mapping"], "C",
         "Set-associative caches group blocks into sets, giving each block several possible slots to reduce conflicts."),
        ("INTERMEDIATE", "The locality principle states that programs tend to reuse data and instructions that are what?",
         ["used recently and located nearby", "stored only on the disk", "chosen at random", "from the very start of the program"], "D",
         "Temporal and spatial locality mean programs repeatedly touch recent items and nearby addresses."),
        ("INTERMEDIATE", "What is a write-back cache policy?",
         ["writes update only the cache, and main memory is updated when the block is evicted", "every write updates main memory immediately", "writes go only to the disk", "writes are discarded"], "A",
         "Write-back delays main memory updates until eviction, reducing memory traffic for repeated writes."),
        ("INTERMEDIATE", "A TLB (translation lookaside buffer) caches what?",
         ["recent virtual-to-physical address translations", "machine instructions", "file system metadata", "network packets"], "B",
         "The TLB is a small cache of page table entries that speeds up virtual-to-physical address translation."),
        ("INTERMEDIATE", "When a page fault occurs, what does the operating system do?",
         ["reduces the clock frequency", "erases the page table", "loads the missing page from secondary storage into physical memory", "deletes the process"], "C",
         "On a page fault the OS fetches the requested page from disk into a physical frame and resumes the faulting process."),
        ("INTERMEDIATE", "A loop repeatedly reads the same element of an array. Which form of locality does this exploit?",
         ["temporal locality", "spatial locality", "no locality", "sequential locality"], "A",
         "Reusing the same data item again is temporal locality, because the item is referenced close together in time."),
        ("ADVANCED", "Why does a write-allocate cache typically fetch the entire block from memory even on a write miss?",
         ["because the rest of the block will likely be accessed soon and partial-block writes complicate coherence", "because it reduces the tag size", "because memory writes are faster", "because the CPU requires it"], "A",
         "Fetching the full block keeps it coherent and exploits the fact that nearby bytes are usually touched next."),
        ("ADVANCED", "An application streams once through a huge array and never revisits data. What cache behavior should be expected?",
         ["high hit rate due to temporal locality", "mostly compulsory misses with little reuse, so cache size matters mainly through spatial locality", "no misses because caches are infinite", "a hit on every access"], "B",
         "Because each item is read once, there is almost no reuse and performance depends on pulling in useful neighbors in each block."),
        ("ADVANCED", "Two processes share a last-level cache, and a researcher wants to infer secrets. Which attack studies this resource?",
         ["a side-channel that measures cache access timing and contention to reveal data-dependent access patterns", "a denial of service that deletes files", "a buffer overflow in the ALU", "an attack on the clock generator"], "C",
         "Cache side-channel attacks observe how a victim's secret-dependent accesses affect timing and shared cache state."),
        ("ADVANCED", "How many elements of an 8-byte integer array fit in one 64-byte cache line?",
         ["16", "32", "4", "8"], "D",
         "Dividing 64 bytes by 8 bytes per element shows that exactly 8 elements share a cache line."),
        ("ADVANCED", "When a program has poor spatial locality, which cache design change most directly targets that weakness?",
         ["larger cache blocks up to a point, which pull in more neighboring data per miss", "smaller blocks", "removing the cache", "more TLB entries only"], "A",
         "Bigger blocks bring in more adjacent data on each miss, which directly improves performance for spatially local streams."),
        ("ADVANCED", "Why can a set-associative cache reduce conflict misses compared with a direct-mapped cache?",
         ["several blocks can share a set, giving each block multiple candidate locations so conflicts are less likely", "it stores data on the disk", "it uses larger tags", "it increases the clock"], "B",
         "Providing more than one way per set means a block is not forced into a single slot that another block also needs."),
        ("ADVANCED", "On a NUMA (non-uniform memory access) machine, why does the placement of a thread matter?",
         ["accessing memory attached to a remote node costs higher latency than local memory", "remote memory is larger", "local memory is read-only", "NUMA has no effect on performance"], "C",
         "In NUMA systems each node owns part of memory, and cross-node accesses are slower than local ones."),
        ("ADVANCED", "A database performs random 512-byte reads over a 1 TB dataset. Why does a huge last-level cache give surprisingly little benefit?",
         ["the working set vastly exceeds the cache and random access destroys temporal locality, so the hit rate stays tiny", "cache does not store disk data", "SSDs are faster than RAM", "the database uses no memory"], "D",
         "With random access over a dataset far larger than the cache, almost every request misses regardless of cache size."),
        ("ADVANCED", "Why are TLBs typically kept small but extremely fast even though page tables are large?",
         ["a TLB hit avoids a multi-level page table walk, so it must be very fast even if it covers little memory", "page tables are stored in ROM", "TLBs store data rather than addresses", "virtual memory is optional"], "A",
         "Since a TLB miss triggers an expensive page walk, the TLB is optimized for speed and placed close to the core."),
        ("ADVANCED", "An engineer sees the last-level cache hit rate fall sharply when a program is given more cores. What is a likely cause?",
         ["the shared LLC is partitioned among cores and contention or false sharing across cores increases misses", "the cache hardware failed", "more cores always reduce hit rate", "the clock speed dropped"], "B",
         "Multiple cores sharing and invalidating lines in the last-level cache raises conflict and coherence misses."),
    ],
    193: [
        ("BEGINNER", "What is instruction pipelining?",
         ["overlapping the execution of multiple instructions by dividing processing into stages", "running instructions one at a time", "storing instructions on disk", "executing all instructions in parallel on one core"], "A",
         "A pipeline splits instruction processing into stages that work on different instructions at the same time."),
        ("BEGINNER", "In steady state, how many instructions does an ideal single-issue pipeline complete per clock cycle?",
         ["one per stage per second", "exactly one instruction per cycle", "one per program", "none"], "B",
         "In a full ideal pipeline one instruction finishes every cycle, giving a CPI of 1."),
        ("BEGINNER", "Which of the following is a typical stage of a five-stage pipeline?",
         ["fetch, decode, execute, memory, write-back", "compile, link, run, debug, test", "read, write, delete, copy, move", "begin, middle, end, halt, exit"], "C",
         "The classic five-stage pipeline is fetch, decode, execute, memory, and write-back."),
        ("BEGINNER", "What is a pipeline hazard?",
         ["a situation that prevents the next instruction from executing in the next clock cycle", "a bug in the compiler", "a hardware crash", "an empty pipeline"], "D",
         "A hazard is any condition that forces the pipeline to stall so an instruction cannot proceed on schedule."),
        ("BEGINNER", "When does a data hazard occur?",
         ["when an instruction needs a value produced by a still-unfinished earlier instruction", "when two instructions fetch from the same cache", "when the clock is too slow", "when the pipeline is empty"], "A",
         "A data hazard arises when a later instruction depends on a result that an earlier instruction has not produced yet."),
        ("BEGINNER", "What causes a control hazard?",
         ["branch instructions that change the flow of the program", "load instructions", "write-back operations", "cache hits"], "B",
         "Because branch targets are not known until later stages, branches make it unclear which instruction to fetch next."),
        ("BEGINNER", "What causes a structural hazard?",
         ["hardware resources needed by more than one instruction in the same cycle", "compiler errors", "data dependencies", "branch mispredictions"], "C",
         "A structural hazard happens when two pipeline stages need the same hardware unit at the same time."),
        ("BEGINNER", "What is forwarding (bypassing) in a pipeline?",
         ["routing a computed result directly to a later instruction that needs it without waiting for write-back", "sending instructions to the printer", "copying data to the disk", "delaying every instruction"], "D",
         "Forwarding wires a result from an earlier stage straight to the stage that needs it, avoiding the wait for write-back."),
        ("BEGINNER", "A bubble inserted into a pipeline represents what?",
         ["a stall cycle where no useful work is done", "an error in the ALU", "an extra instruction", "a cache flush"], "A",
         "A bubble is an empty slot inserted when a stage must wait, during which no real work completes."),
        ("BEGINNER", "What does a branch predictor try to do?",
         ["guess the outcome of a branch so the pipeline does not stall", "fix data hazards", "increase cache size", "simplify the ISA"], "B",
         "By predicting whether a branch is taken, the fetch unit can keep supplying instructions without stalling."),
        ("INTERMEDIATE", "In a five-stage pipeline with no stalls, how many cycles does it take to complete 5 instructions?",
         ["5 cycles", "25 cycles", "9 cycles", "10 cycles"], "C",
         "The first instruction finishes after 5 cycles and each later one takes one more cycle, so 5 plus 4 equals 9."),
        ("INTERMEDIATE", "A filled five-stage pipeline is in steady state. What is its ideal CPI?",
         ["5", "0.5", "2", "1"], "D",
         "In steady state a full single-issue pipeline retires one instruction per cycle, so the ideal CPI is 1."),
        ("INTERMEDIATE", "A load is followed immediately by an add that uses the loaded value in a five-stage pipeline with forwarding. How many stall cycles are needed?",
         ["1", "3", "4", "0"], "A",
         "Forwarding resolves most data hazards, but a load-use still requires one stall because the value only exists after the memory stage."),
        ("INTERMEDIATE", "The pipeline predicts a branch as not-taken, but the branch is actually taken. What happens?",
         ["the pipeline continues normally", "the pipeline is flushed and refilled from the branch target, wasting several cycles", "the program crashes", "the clock stops"], "B",
         "On a misprediction every instruction fetched after the branch is discarded and fetching restarts from the target."),
        ("INTERMEDIATE", "A program is 20% branches with 90% prediction accuracy, and each misprediction costs 15 cycles. What is the average branch penalty per instruction?",
         ["0.3 cycles", "1.5 cycles", "3 cycles", "15 cycles"], "C",
         "Only 10% of the 20% branches mispredict, so 0.2 times 0.1 times 15 equals 0.3 cycles on average."),
        ("INTERMEDIATE", "What is the distinguishing feature of a superscalar pipeline?",
         ["it can issue multiple instructions per cycle", "it has no cache", "it uses a single stage", "it runs at a lower clock speed"], "D",
         "A superscalar machine has multiple execution units and issues more than one instruction per cycle."),
        ("INTERMEDIATE", "Which hazard typically still requires at least one stall even with full forwarding?",
         ["a load-use hazard", "an ALU-to-ALU dependency", "a register write hazard", "a structural hazard"], "A",
         "A load produces its data only at the end of the memory stage, so the consuming instruction must wait at least one cycle."),
        ("INTERMEDIATE", "A 10,000,000-instruction program runs on a five-stage pipeline with an average CPI of 1.2. How many cycles does it take?",
         ["2,000,000", "12,000,000", "50,000,000", "6,000,000"], "B",
         "Multiplying 10 million instructions by a CPI of 1.2 gives 12 million cycles."),
        ("INTERMEDIATE", "What causes a control hazard in a pipeline?",
         ["a branch whose outcome is unknown until later stages", "a divide instruction", "an empty cache", "too many registers"], "C",
         "Until the branch is evaluated, the pipeline cannot know which instruction to fetch, creating a control hazard."),
        ("INTERMEDIATE", "In the classic five-stage pipeline, in which stage is the branch outcome and target typically determined?",
         ["the fetch stage", "the write-back stage", "the decode stage", "the execute stage"], "D",
         "The condition and target of a branch are computed in the execute stage, after several instructions are already in flight."),
        ("ADVANCED", "Why is it hard to design a good branch predictor for branches whose outcome depends on data that changes unpredictably?",
         ["no predictor can achieve high accuracy when the branch pattern is random or data-dependent, so prediction is fundamentally limited", "predictors cannot run at a high clock speed", "branch predictors only work in software", "data-dependent branches are illegal"], "A",
         "Prediction relies on pattern, so a genuinely unpredictable data-dependent branch defeats any history-based scheme."),
        ("ADVANCED", "A CPU has 20 pipeline stages. Why does a mispredicted branch cost more there than on a five-stage machine?",
         ["the deeper the pipeline, the more in-flight instructions must be flushed on a mispredict", "deeper pipelines have no branch predictor", "deeper pipelines run slower", "mispredictions are cheaper on deeper pipelines"], "B",
         "Each stage holds extra instructions, so a 20-stage design discards far more work than a five-stage one on a mispredict."),
        ("ADVANCED", "Which technique records recent branch outcomes to predict the next one and handles both taken and not-taken patterns?",
         ["an n-bit history-based branch predictor using a branch history table", "a cache of ALU results", "a register renaming table", "a store buffer"], "C",
         "An n-bit saturating counter on the branch history table tracks recent outcomes to forecast the next branch direction."),
        ("ADVANCED", "What is the main danger of allowing a store to write to memory before an earlier load reads the same address?",
         ["memory ordering violations and stale reads, so memory disambiguation is required", "the pipeline becomes slower", "the ALU is unused", "the cache grows too large"], "D",
         "If addresses match, reordering the store ahead of the load makes the load return stale data, so the machine must detect this."),
        ("ADVANCED", "IPC drops from 3.0 to 0.9 after enabling a new feature. Which effect best explains the large drop?",
         ["a rise in expensive stalls such as cache misses, branch mispredictions, or long dependency chains", "the clock speed doubling", "the ISA changing", "the compiler emitting fewer instructions"], "A",
         "IPC reflects how many instructions retire per cycle, so new stall sources directly cut the rate of completions."),
        ("ADVANCED", "Why do out-of-order cores separate the issue stage from the commit stage using a reorder buffer?",
         ["so instructions can complete out of order while state is retired in program order, preserving precise exceptions", "to reduce the number of registers", "to increase cache bandwidth", "to run at a lower voltage"], "B",
         "Completing out of order improves performance, while committing in order keeps the architectural state and exceptions precise."),
        ("ADVANCED", "A 40-stage design reaches a higher clock but needs better branch prediction and deeper speculation. What is the fundamental trade-off?",
         ["higher clock rate versus higher misprediction penalty and longer pipeline-fill latency", "larger caches versus fewer registers", "more cores versus more threads", "less power versus more heat"], "C",
         "Deep pipelines shorten the cycle time but amplify the cost of any mistake, since many instructions are in flight."),
        ("ADVANCED", "Two instructions write to the same register in consecutive cycles in an out-of-order core. Why is this a hazard that renaming solves?",
         ["write-after-write hazards are removed by giving each instruction a distinct physical register", "the register file has too few ports", "the ALU is busy", "the branch predictor fails"], "D",
         "Register renaming lets each writer target a different physical register, so the false WAW dependency disappears."),
        ("ADVANCED", "Why do modern CPUs often combine global-history and local-history branch predictors?",
         ["different branch patterns are predicted better by different histories, so a hybrid improves overall accuracy", "it doubles the cache size", "it lowers the clock", "it reduces the number of registers"], "A",
         "Some branches correlate with nearby branches while others have their own regular pattern, so a hybrid captures both."),
        ("ADVANCED", "A service has a high ratio of branch mispredictions in a switch-heavy parser. Which change most directly reduces mispredictions?",
         ["restructuring code so frequently taken paths are more predictable, such as using branch tables or reordering conditions", "increasing the L1 cache size", "adding more cores", "reducing the clock speed"], "B",
         "Making hot paths predictable, for example with jump tables or sorted conditions, lets the predictor succeed far more often."),
    ],
    194: [
        ("BEGINNER", "What is an input/output (I/O) device?",
         ["a device that lets the computer exchange data with the outside world", "a part of the ALU", "a memory module", "an operating system"], "A",
         "I/O devices move data into and out of the computer, connecting it to users and other systems."),
        ("BEGINNER", "Which bus transfers data between the CPU, memory, and peripherals?",
         ["the power supply", "the system bus", "the keyboard bus", "the video cable"], "B",
         "The system bus connects the CPU, memory, and I/O controllers so they can exchange data and addresses."),
        ("BEGINNER", "What is polling in the context of I/O?",
         ["the CPU repeatedly checks the status of a device to see if it is ready", "the device sends an email", "the CPU waits forever", "the device is removed"], "C",
         "Polling means the processor repeatedly reads a device's status register until the device signals readiness."),
        ("BEGINNER", "What is a buffer in the context of I/O?",
         ["a temporary storage area that holds data while it is transferred between the device and the CPU", "a type of CPU core", "a power supply", "a network cable"], "A",
         "A buffer smooths the speed difference between a slow device and the CPU by holding data temporarily during transfer."),
        ("BEGINNER", "Which of the following is an input device?",
         ["a keyboard", "a printer", "a monitor", "a speaker"], "A",
         "A keyboard sends data into the computer, so it is an input device."),
        ("BEGINNER", "What is the role of a device driver?",
         ["software that lets the operating system communicate with a specific hardware device", "a physical cable", "a power supply", "a cooling fan"], "B",
         "A device driver translates generic OS requests into the commands understood by one particular piece of hardware."),
        ("BEGINNER", "Which of the following is an output device?",
         ["a mouse", "a scanner", "a monitor", "a microphone"], "C",
         "A monitor displays data produced by the computer, making it an output device."),
        ("BEGINNER", "What is the role of an I/O controller?",
         ["it manages the communication between the CPU, memory, and a specific device", "it stores the operating system", "it generates electricity", "it renders graphics"], "A",
         "An I/O controller handles the details of transferring data between a device and the rest of the computer system."),
        ("BEGINNER", "What is the advantage of using DMA for I/O?",
         ["data transfers happen without the CPU copying every byte", "it speeds up the keyboard", "it increases the clock", "it makes memory read-only"], "A",
         "With DMA the device controller transfers blocks directly to and from memory, freeing the CPU for other work."),
        ("BEGINNER", "What is the main job of an interrupt handler?",
         ["it runs the routine that responds to the interrupt and then returns control to the interrupted program", "it deletes the cache", "it powers off the device", "it doubles the clock speed"], "A",
         "The interrupt handler is a small routine that services the device's request and then returns control to whatever program was running."),
        ("INTERMEDIATE", "A CPU polls a printer every 1 ms, and each poll takes 100 cycles at 1 GHz. What is the CPU time used per poll?",
         ["100 ns", "10 ms", "1 ms", "100 us"], "C",
         "At 1 GHz each cycle is 1 nanosecond, so 100 cycles take 100 nanoseconds."),
        ("INTERMEDIATE", "Which transfer method is best when a high-speed device must move large blocks of data with minimal CPU involvement?",
         ["interrupt-driven polling", "DMA", "memory-mapped I/O", "programmed I/O with polling"], "D",
         "DMA lets the controller move whole blocks directly to memory, so the CPU is only involved at setup and completion."),
        ("INTERMEDIATE", "An interrupt handler takes 200 cycles and 1000 interrupts arrive per second. What fraction of CPU time is spent handling interrupts at 1 GHz?",
         ["0.02%", "2%", "20%", "0.2%"], "A",
         "The handler uses 200,000 cycles per second, which is 0.02% of the 1 billion cycles available."),
        ("INTERMEDIATE", "Why are interrupts generally preferred over polling for slow or asynchronous devices?",
         ["the CPU is idle until the device signals readiness, avoiding wasted polling cycles", "interrupts are always faster than DMA", "interrupts use no hardware", "polling cannot read data"], "B",
         "Interrupts let the CPU do useful work and only stop when the device needs attention, eliminating busy waiting."),
        ("INTERMEDIATE", "What does the interrupt vector table contain?",
         ["the addresses of the interrupt service routines for each interrupt", "the cache block sizes", "the list of I/O devices", "the OS kernel code"], "C",
         "Each interrupt number maps to the address of its service routine through the interrupt vector table."),
        ("INTERMEDIATE", "A USB 3.2 Gen 2 port transfers at 10 Gbps. Roughly how many bytes per second is that?",
         ["1.25 gigabytes per second", "10 megabytes per second", "100 bytes per second", "1 megabyte per second"], "D",
         "Dividing 10 billion bits per second by 8 bits per byte gives about 1.25 billion bytes per second."),
        ("INTERMEDIATE", "What is the purpose of a device's status register?",
         ["to report whether the device is busy, ready, or has an error", "to store the OS kernel", "to cache data", "to schedule threads"], "A",
         "The status register holds flags the CPU or driver reads to learn the device's current condition."),
        ("INTERMEDIATE", "When a device completes an operation and needs CPU attention, which signal does it raise?",
         ["a clock edge", "an interrupt request", "a reset line", "a page fault"], "B",
         "The device asserts an interrupt request line so the CPU suspends its current work and runs the handler."),
        ("INTERMEDIATE", "What is the main disadvantage of programmed I/O for large transfers?",
         ["the CPU must move each byte, consuming significant processor time", "it is too fast for the device", "it requires no drivers", "it uses too much power"], "C",
         "In programmed I/O the CPU transfers every byte itself, so large transfers consume large amounts of CPU time."),
        ("INTERMEDIATE", "A controller uses port-mapped I/O with dedicated IN and OUT instructions. What distinguishes this from memory-mapped I/O?",
         ["devices live in a separate address space accessed by dedicated instructions", "devices are stored on the disk", "it is slower than the cache", "it uses no addresses"], "D",
         "Port-mapped I/O keeps device registers in a distinct space reached only through special I/O instructions."),
        ("ADVANCED", "A network card receives a million packets per second, each triggering an interrupt. Why might this overwhelm the CPU, and what is a common solution?",
         ["interrupt overhead per packet becomes huge, so interrupt coalescing and polling-based drivers reduce the load", "the CPU is too slow to read packets", "the network card is broken", "the packets are too large"], "A",
         "A million interrupts per second drown the CPU in context switching, so drivers batch interrupts or poll in bursts."),
        ("ADVANCED", "Why is memory-mapped I/O preferred for devices needing low-latency register access, such as GPUs?",
         ["the CPU reaches device registers with ordinary loads and stores at near-cache latency", "it avoids all interrupts", "it uses DMA exclusively", "it makes the device invisible"], "B",
         "Mapping device registers into the address space lets the CPU poke them with fast, ordinary memory instructions."),
        ("ADVANCED", "A driver must stream video at 60 fps where each frame is 8 MB. What sustained bandwidth does the frame stream alone require?",
         ["480 MB/s", "60 MB/s", "8 MB/s", "4.8 GB/s"], "C",
         "Multiplying 60 frames per second by 8 MB per frame gives 480 MB/s of sustained throughput."),
        ("ADVANCED", "Why do high-speed NVMe SSDs use a queue-based command submission model rather than simple programmed I/O?",
         ["the host submits many commands without waiting per transfer, and the device completes them with DMA to hide latency", "NVMe drives have no controller", "queue models are slower", "programmed I/O is forbidden"], "D",
         "Queueing lets many commands be in flight at once and DMA moves the data, keeping the fast flash pipeline busy."),
        ("ADVANCED", "A real-time audio device cannot tolerate lost samples. Which I/O mechanism is most appropriate?",
         ["DMA into a fixed buffer with precise interrupts that keep the buffer filled at a constant rate", "random polling by the CPU", "programmed I/O with occasional retries", "storing audio on disk"], "A",
         "Continuous DMA streaming with carefully timed interrupts keeps the sample buffer full so no data underruns."),
        ("ADVANCED", "Why do operating systems place the interrupt descriptor table and handlers in memory that user processes cannot modify?",
         ["to protect kernel exception and interrupt handling from malicious or buggy user code", "to speed up the GPU", "to make the table larger", "to allow DMA access"], "B",
         "If user code could alter the descriptor table, it could hijack interrupt handling and take over the system."),
        ("ADVANCED", "Why might a design use an MMIO doorbell instead of DMA for command notification in some systems?",
         ["for small latency-critical commands, an MMIO write can notify the device faster than a DMA round trip", "MMIO supports more bandwidth", "DMA cannot move data", "doorbells use no addresses"], "C",
         "A posted MMIO write travels quickly to the device, so tiny high-priority commands skip the DMA setup overhead."),
        ("ADVANCED", "How does a device using message-signaled interrupts (MSI) interrupt the CPU compared with a legacy interrupt line?",
         ["it sends a small memory write over the bus instead of asserting a physical wire", "it does not interrupt at all", "it uses DMA", "it polls the CPU"], "D",
         "MSI delivers an interrupt as a posted write to a specific address, avoiding a shared physical interrupt pin."),
        ("ADVANCED", "For a warehouse of many mostly-idle sensors, why might an engineer choose interrupt-driven I/O over constant polling?",
         ["the CPU can sleep and wake only on real events, saving power while sensors are quiet", "polling is forbidden in modern systems", "interrupts transfer more data", "sensors cannot be polled"], "A",
         "Idle sensors rarely need attention, so letting them interrupt only when data arrives keeps the CPU asleep and efficient."),
        ("ADVANCED", "A storage benchmark shows write throughput limited by CPU time spent in the driver. Which change most likely improves throughput?",
         ["moving from programmed I/O to DMA and cutting per-command CPU overhead", "increasing the screen resolution", "adding more RAM only", "disabling the cache"], "B",
         "Reducing CPU work per command, such as with DMA and batched submission, removes the processor as the bottleneck."),
    ],
    195: [
        ("BEGINNER", "What is a multicore processor?",
         ["a single chip containing multiple CPU cores that can execute programs in parallel", "a processor with one core", "a GPU only", "a type of memory"], "A",
         "A multicore chip places several independent cores on one die so threads can truly run in parallel."),
        ("BEGINNER", "What is a thread?",
         ["a single sequence of instructions that can run concurrently on a core", "a cable", "a cache line", "a memory address"], "B",
         "A thread is one flow of execution that the operating system can schedule onto a core."),
        ("BEGINNER", "What is the difference between a process and a thread?",
         ["a process has its own address space while threads in a process share it", "threads have separate address spaces", "processes are always faster", "there is no difference"], "C",
         "Each process gets an isolated address space, but the threads of one process share that same memory."),
        ("BEGINNER", "What is parallelism?",
         ["executing multiple tasks at the same time to increase throughput", "executing tasks one at a time", "a type of memory", "a single-core design"], "D",
         "Parallelism uses multiple processing resources simultaneously to get more work done in less time."),
        ("BEGINNER", "What does the speedup of a parallel program compare?",
         ["its execution time versus the best sequential version", "its clock speed", "its memory size", "the number of bugs"], "A",
         "Speedup is the sequential execution time divided by the parallel execution time."),
        ("BEGINNER", "What is Amdahl's law used for?",
         ["estimating the maximum speedup given the fraction of code that is serial", "measuring cache size", "designing keyboards", "predicting battery life"], "B",
         "Amdahl's law bounds speedup using the fraction of the program that cannot be parallelized."),
        ("BEGINNER", "What is the purpose of mutual exclusion in parallel programming?",
         ["to ensure only one thread accesses a shared resource at a time", "to make all threads run faster", "to increase the number of cores", "to delete shared data"], "A",
         "Mutual exclusion guarantees that only one thread can enter a critical section at a time, preventing interference over shared data."),
        ("BEGINNER", "What is a mutex?",
         ["a synchronization primitive that allows only one thread into a critical section at a time", "a type of cache", "a network cable", "an interrupt"], "D",
         "A mutex guarantees mutual exclusion, so only one thread can hold it inside a critical section at a time."),
        ("BEGINNER", "Why is thread synchronization needed?",
         ["to coordinate access to shared data and avoid races", "to make threads faster", "to reduce the number of cores", "to print output"], "A",
         "Synchronization orders thread access to shared state, preventing the interleavings that cause races."),
        ("BEGINNER", "What is a lock-free or atomic operation?",
         ["an operation that completes without acquiring a lock, typically using hardware atomics", "a lock that is always free", "an operation that crashes", "a compiler optimization"], "B",
         "Atomic operations are implemented in hardware so they complete indivisibly without needing a software lock."),
        ("INTERMEDIATE", "A program is 90% parallelizable and runs on 10 cores with perfect scaling of the parallel part. What is the theoretical maximum speedup?",
         ["9", "10", "5.26", "1.9"], "C",
         "Amdahl's law gives 1 divided by (0.1 plus 0.9/10), which equals about 5.26 times."),
        ("INTERMEDIATE", "If a parallel program has a 5% serial fraction, what is the absolute maximum speedup on infinitely many cores?",
         ["20", "95", "infinite", "5"], "D",
         "Amdahl's law shows speedup can never exceed 1 divided by 0.05, which is 20 times."),
        ("INTERMEDIATE", "Two threads increment the same shared integer without synchronization. Why might the final value be wrong?",
         ["the increment compiles to multiple read-modify-write operations that can interleave and lose updates", "the integer is too small", "increments are forbidden", "the cache is too small"], "A",
         "A non-atomic increment is several steps, and interleaving threads can each read the same old value and both write it back."),
        ("INTERMEDIATE", "What is false sharing?",
         ["two threads updating unrelated variables that share a cache line, forcing unnecessary coherence traffic", "two threads reading the same variable", "a deadlock", "a kernel panic"], "B",
         "Even independent data placed on one cache line is invalidated together, so the cores exchange the line needlessly."),
        ("INTERMEDIATE", "What are the four Coffman conditions that must all hold for a deadlock to occur?",
         ["mutual exclusion, hold and wait, no preemption, and circular wait", "race, delay, retry, and restart", "lock, unlock, fork, and join", "read, write, allocate, and free"], "A",
         "A deadlock can only happen when all four Coffman conditions are satisfied at once: mutual exclusion, hold and wait, no preemption, and circular wait."),
        ("INTERMEDIATE", "What does the term embarrassingly parallel mean?",
         ["a workload whose tasks have almost no dependencies and can be split with little communication", "a workload that cannot be parallelized", "a workload that always deadlocks", "a sequential workload"], "D",
         "Embarrassingly parallel problems are easy to split because their pieces are nearly independent."),
        ("INTERMEDIATE", "A machine has 8 cores with hyper-threading giving 2 threads per core. How many logical CPUs does the OS typically see?",
         ["16", "8", "4", "64"], "A",
         "Hyper-threading presents two logical processors per physical core, so 8 times 2 gives 16 logical CPUs."),
        ("INTERMEDIATE", "What is the purpose of a barrier in parallel programming?",
         ["to make all threads wait until every thread has reached the same point", "to protect a critical section", "to allocate memory", "to speed up a single thread"], "B",
         "A barrier synchronizes threads so none continues until all have arrived at the same stage of the computation."),
        ("INTERMEDIATE", "What is data parallelism?",
         ["applying the same operation to many data elements at once", "running different programs at the same time", "storing data in parallel", "reading data sequentially"], "C",
         "Data parallelism splits a large dataset across workers that all run the same operation on their portion."),
        ("INTERMEDIATE", "Which is an example of task-level parallelism?",
         ["two different functions running on two cores simultaneously", "the same loop running on one core", "a single-threaded program", "a cache"], "D",
         "Task parallelism runs independent, distinct functions concurrently rather than splitting one dataset."),
        ("ADVANCED", "A GPU has thousands of small cores at a lower clock than a CPU. Why can it still beat a CPU for matrix math?",
         ["matrix math is massively data-parallel, so many simple cores running the same operation on many elements give huge aggregate throughput", "GPU cores are faster individually", "GPUs have more cache", "GPUs avoid all memory access"], "A",
         "The GPU trades per-thread speed for massive width, which suits the regular, parallel structure of matrix arithmetic."),
        ("ADVANCED", "In a shared-memory program, why is scaling beyond a certain core count usually disappointing?",
         ["serial portions, synchronization overhead, and memory bandwidth limits dominate as cores grow", "cores are too fast", "the compiler removes parallelism", "threads always run serially"], "B",
         "The serial fraction and communication costs grow relative to useful work, capping real speedup well below the core count."),
        ("ADVANCED", "What is a transactional memory approach?",
         ["executing critical sections speculatively and committing only if no conflicts occurred, with rollback on conflict", "using locks for everything", "a type of cache", "a disk format"], "C",
         "Transactions let threads race through sections and only roll back when two conflict, avoiding lock overhead in easy cases."),
        ("ADVANCED", "A lock protects a critical section that lasts 2 microseconds, and 1000 threads contend for it. Why does the lock become the bottleneck?",
         ["the lock serializes the section, so throughput is bounded by the section duration regardless of core count", "locks make code faster", "threads are too small", "the CPU is too fast"], "D",
         "Because only one thread can be inside at a time, the maximum completion rate is one section per 2 microseconds."),
        ("ADVANCED", "Why do servers use NUMA-aware thread scheduling and memory allocation?",
         ["matching threads to memory-local nodes reduces remote memory latency and cross-node traffic", "it makes the OS simpler", "it reduces the number of cores", "it eliminates cache coherence"], "A",
         "Keeping a thread's data on its own node avoids slow remote accesses that would otherwise dominate performance."),
        ("ADVANCED", "In cache-coherent multicore systems, why is read-only sharing cheap while frequent writes to a shared variable are expensive?",
         ["reads are served from shared cache copies, but writes invalidate copies across cores and generate coherence traffic", "reads are slower than writes", "writes never leave the core", "coherence only handles reads"], "B",
         "Readers can share a clean line freely, but every write must invalidate other copies and eventually move the line."),
        ("ADVANCED", "A parallel hash table uses one global lock, and throughput stops growing after 4 cores. Which redesign most directly fixes the bottleneck?",
         ["sharding the table so each partition has its own lock, reducing contention", "removing the locks entirely", "using more memory", "increasing the clock"], "C",
         "Per-bucket locks spread contention across partitions so different threads can update different parts in parallel."),
        ("ADVANCED", "What is the key advantage of a work-stealing scheduler used in many parallel runtimes?",
         ["idle threads steal tasks from busy queues, balancing load dynamically without a central coordinator", "it uses a single thread", "it never preempts", "it disables the cache"], "D",
         "Work stealing keeps all cores busy by redistributing tasks to idle workers as the computation proceeds."),
        ("ADVANCED", "A compute job scales from 4 to 64 cores but speedup plateaus at 30 times. What serial fraction does Amdahl's law imply?",
         ["about 1.8%", "about 30%", "about 50%", "about 5%"], "A",
         "Solving 1 over (s plus (1-s)/64) equals 30 gives a serial fraction near 1.8%."),
        ("ADVANCED", "Why do cloud providers charge more for dedicated vCPUs than for shared ones?",
         ["a dedicated vCPU guarantees predictable, isolated performance while shared cores suffer noise from neighbors", "dedicated cores are physically faster", "shared cores have no cache", "dedicated cores only use more power"], "B",
         "Dedicated vCPUs are pinned to unshared hardware, so a tenant's performance is not hurt by other tenants' load."),
    ],
}
