# -*- coding: utf-8 -*-
"""
Question bank for subject 41: MTH101 - Engineering Mathematics I.
Category: Core Computer Science & Emerging Technologies.

Topics:
  201: Limits & Continuity
  202: Differentiation
  203: Integration
  204: Matrices & Linear Systems
  205: Differential Equations

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    201: [
        ("BEGINNER", "What is the value of the limit of f(x) = x as x approaches 5?",
         ["5", "0", "10", "Infinity"], "A",
         "Since f(x) = x is continuous everywhere, the limit equals the value of the function at 5, which is 5."),
        ("BEGINNER", "For a function f(x), the limit as x approaches c exists only when which condition holds?",
         ["The left-hand limit and right-hand limit both exist and are equal", "The function is defined at c", "The derivative at c is zero", "The function is increasing near c"], "B",
         "A two-sided limit exists only when the left-hand and right-hand limits agree at the point."),
        ("BEGINNER", "What is the value of the standard limit of sin(x)/x as x tends to 0?",
         ["0", "Infinity", "1", "Undefined"], "C",
         "The standard limit sin(x)/x approaches 1 as x tends to 0, a result used throughout calculus."),
        ("BEGINNER", "A function f(x) is continuous at x = c when which set of conditions holds?",
         ["Only the limit at c exists", "Only f(c) is defined", "f(c) is defined, the limit exists, and both are equal", "The derivative f'(c) exists everywhere"], "D",
         "Continuity at a point requires the function value, the limit, and their equality to all hold."),
        ("BEGINNER", "What is the limit of the constant function f(x) = 7 as x approaches any point c?",
         ["7", "0", "c", "Undefined"], "A",
         "The limit of any constant function is that same constant, regardless of the point approached."),
        ("BEGINNER", "Which term describes a discontinuity that can be removed by redefining a single value of the function?",
         ["Jump discontinuity", "Removable discontinuity", "Infinite discontinuity", "Oscillating discontinuity"], "B",
         "A removable discontinuity occurs where the limit exists but differs from the function value or the value is undefined."),
        ("BEGINNER", "What is the limit of (x^2 - 9)/(x - 3) as x approaches 3?",
         ["0", "3", "6", "9"], "C",
         "Factoring (x - 3)(x + 3) cancels the (x - 3) term, leaving x + 3, which approaches 6."),
        ("BEGINNER", "Which notation correctly represents 'the limit of f(x) as x approaches a is L'?",
         ["f(a) = L", "d/dx f(x) = L", "integral of f(x) dx = L", "lim(x->a) f(x) = L"], "D",
         "The standard notation lim(x->a) f(x) = L states that f(x) approaches L as x approaches a."),
        ("BEGINNER", "A function is called discontinuous at a point when which statement is true?",
         ["It fails to be continuous at that point", "Its derivative is negative", "Its graph is a straight line", "It is increasing at that point"], "A",
         "Discontinuous means the function is not continuous, so one of the continuity conditions fails at the point."),
        ("BEGINNER", "What is the limit of 1/x as x tends to positive infinity?",
         ["Infinity", "0", "1", "-Infinity"], "B",
         "As x grows without bound, the fraction 1/x shrinks toward 0."),
        ("INTERMEDIATE", "Evaluate the limit of (1 - cos(x))/x as x approaches 0.",
         ["1", "1/2", "0", "Does not exist"], "C",
         "Using 1 - cos(x) = 2 sin^2(x/2), the ratio simplifies to a multiple of sin(x/2), which tends to 0."),
        ("INTERMEDIATE", "Evaluate the limit of sin(2x)/x as x approaches 0.",
         ["1", "0", "Undefined", "2"], "D",
         "Rewriting as 2 times sin(2x)/(2x), the inner ratio tends to 1, so the limit is 2."),
        ("INTERMEDIATE", "For which value of the constant k is the piecewise function f(x) = x + 1 for x < 2 and f(x) = k for x >= 2 continuous at x = 2?",
         ["3", "1", "2", "4"], "A",
         "The left-hand limit as x approaches 2 is 3, so k must equal 3 for the function to be continuous."),
        ("INTERMEDIATE", "Which statement correctly describes the behaviour of f(x) = 1/(x - 2) as x approaches 2 from the right?",
         ["The function tends to negative infinity", "The function tends to positive infinity", "The function tends to 0", "The function tends to 2"], "B",
         "For x slightly greater than 2 the denominator is a small positive number, so the fraction grows to positive infinity."),
        ("INTERMEDIATE", "What is the horizontal asymptote of the function f(x) = (2x + 1)/(x - 3) as x tends to infinity?",
         ["y = 0", "y = 3", "y = 2", "y = 1/3"], "C",
         "Dividing numerator and denominator by x gives the leading ratio 2, so the horizontal asymptote is y = 2."),
        ("INTERMEDIATE", "What is the limit of tan(x)/x as x approaches 0?",
         ["0", "Infinity", "Undefined", "1"], "D",
         "Since tan(x) = sin(x)/cos(x), the ratio becomes sin(x)/x divided by cos(x), which tends to 1."),
        ("INTERMEDIATE", "Using the squeeze theorem, what is the limit of x*sin(1/x) as x approaches 0?",
         ["0", "1", "Undefined", "Infinity"], "A",
         "Since -|x| <= x*sin(1/x) <= |x| and both bounds tend to 0, the squeezed limit is 0."),
        ("INTERMEDIATE", "A function is continuous on the interval [1, 4] with f(1) = 2 and f(4) = 8. By the Intermediate Value Theorem, which value must the function attain?",
         ["1", "5", "9", "4"], "B",
         "The theorem guarantees every value between f(1) = 2 and f(4) = 8 is attained, and 5 lies in that range."),
        ("INTERMEDIATE", "For which value of c is the function f(x) = (x^2 - 1)/(x - 1) continuous if we define f(1) = c?",
         ["1", "0", "2", "3"], "C",
         "After cancellation the expression reduces to x + 1, whose value at x = 1 is 2, so c must be 2."),
        ("INTERMEDIATE", "What is the limit of f(x) = (x^2 + 3x)/(x^2 + 1) as x approaches infinity?",
         ["3", "0", "Infinity", "1"], "D",
         "Dividing numerator and denominator by x^2 leaves a ratio that tends to 1, since the extra terms vanish."),
        ("ADVANCED", "Which theorem allows evaluation of a 0/0 indeterminate limit by differentiating numerator and denominator separately?",
         ["L'Hopital's rule", "Rolle's theorem", "The squeeze theorem", "The mean value theorem"], "A",
         "L'Hopital's rule differentiates the numerator and denominator and then takes the limit to resolve 0/0 or infinity/infinity forms."),
        ("ADVANCED", "A function f(x) jumps from value 3 to value 8 at x = 2. Which type of discontinuity does it exhibit at x = 2?",
         ["Removable discontinuity", "Jump discontinuity", "Oscillating discontinuity", "No discontinuity"], "B",
         "A jump discontinuity occurs when the left-hand and right-hand limits are different finite values."),
        ("ADVANCED", "For what value of k is f(x) = (x^2 - 4)/(x - 2) for x != 2 and f(x) = k for x = 2 continuous at x = 2?",
         ["2", "0", "4", "6"], "C",
         "Simplifying the expression to x + 2 shows the limiting value at x = 2 is 4, so k must be 4."),
        ("ADVANCED", "Which statement about the function f(x) = sin(1/x) near x = 0 is correct?",
         ["Its limit is 1", "Its limit is 0", "It is continuous at 0", "It oscillates infinitely often and has no limit at 0"], "D",
         "As x approaches 0 the argument 1/x grows without bound, making sin(1/x) oscillate so fast that no limit exists."),
        ("ADVANCED", "What is the value of the limit of (1 - cos(x))/x^2 as x approaches 0?",
         ["1/2", "0", "1", "2"], "A",
         "Using 1 - cos(x) = 2 sin^2(x/2), the ratio tends to (1/2) times 1, giving the well-known limit 1/2."),
        ("ADVANCED", "Evaluate the limit of (3x^3 + 2x)/(5x^3 - 4) as x approaches infinity.",
         ["5/3", "3/5", "Infinity", "0"], "B",
         "The leading cubic terms dominate, so the limit is the ratio of the x^3 coefficients, 3/5."),
        ("ADVANCED", "Which choice is the correct epsilon-delta restatement of the limit of f(x) equal to L as x approaches c?",
         ["For every delta > 0 there exists epsilon > 0 such that |f(x) - L| < epsilon implies |x - c| < delta", "The value f(c) must equal L", "For every epsilon > 0 there exists a delta > 0 such that 0 < |x - c| < delta implies |f(x) - L| < epsilon", "The derivative f'(c) must be zero"], "C",
         "The formal definition binds delta to epsilon: within a small neighbourhood of c the outputs stay within epsilon of L."),
        ("ADVANCED", "Which condition is NOT required for a function to be continuous at a point c?",
         ["f(c) is defined", "The limit of f(x) as x approaches c exists", "The limit equals f(c)", "The derivative f'(c) exists"], "D",
         "Continuity requires the value, the limit and their equality; differentiability is a stronger, separate requirement."),
        ("ADVANCED", "A continuous function f satisfies f(0) = -1 and f(2) = 3 on [0, 2]. Which conclusion follows from the Intermediate Value Theorem?",
         ["f has at least one root in (0, 2)", "f is strictly increasing", "f has no roots", "f'(x) = 2 for some x"], "A",
         "Since 0 lies between -1 and 3, the IVT guarantees some c in (0, 2) with f(c) = 0, that is, a root."),
        ("ADVANCED", "Evaluate the limit of (x - sin(x))/x^3 as x approaches 0.",
         ["1", "1/6", "0", "Undefined"], "B",
         "Expanding sin(x) in a Taylor series shows the cubic term contributes 1/6, a classic advanced limit result."),
    ],
    202: [
        ("BEGINNER", "Which rule is used to differentiate a product of two functions?",
         ["Product rule", "Quotient rule", "Chain rule", "Power rule"], "A",
         "The product rule states that the derivative of u*v is u'*v + u*v', covering products of functions."),
        ("BEGINNER", "What is the derivative of a constant function f(x) = k?",
         ["k", "0", "1", "k*x"], "B",
         "A constant function has zero rate of change, so its derivative is 0."),
        ("BEGINNER", "What is the derivative of x^n with respect to x?",
         ["x^(n-1)", "x^n", "n*x^(n-1)", "n*x^(n+1)"], "C",
         "The power rule lowers the exponent by one and multiplies by the original exponent n."),
        ("BEGINNER", "What is the derivative of sin(x)?",
         ["-cos(x)", "-sin(x)", "sec^2(x)", "cos(x)"], "D",
         "The derivative of sin(x) is cos(x), the standard result from the definition of the derivative."),
        ("BEGINNER", "What is the derivative of cos(x)?",
         ["-sin(x)", "sin(x)", "tan(x)", "-cos(x)"], "A",
         "The derivative of cos(x) is -sin(x), since the cosine function decreases as sine grows."),
        ("BEGINNER", "What is the derivative of e^x?",
         ["x*e^(x-1)", "e^x", "ln(x)", "1"], "B",
         "The exponential function e^x is its own derivative, a defining property of the natural exponential."),
        ("BEGINNER", "What is the derivative of ln(x)?",
         ["x", "1/x", "ln(x)", "1"], "C",
         "The derivative of the natural logarithm is 1/x for x > 0."),
        ("BEGINNER", "Which rule states that the derivative of f(g(x)) is f'(g(x)) times g'(x)?",
         ["Product rule", "Quotient rule", "Power rule", "Chain rule"], "D",
         "The chain rule differentiates composite functions by multiplying the outer derivative by the inner derivative."),
        ("BEGINNER", "What is the derivative of tan(x)?",
         ["sec^2(x)", "sin(x)", "cot(x)", "cos(x)"], "A",
         "The derivative of tan(x) is sec^2(x), obtained from the quotient rule on sin(x)/cos(x)."),
        ("BEGINNER", "What does the derivative of f at a point geometrically represent?",
         ["The area under the curve", "The slope of the tangent line", "The y-intercept", "The x-intercept"], "B",
         "The derivative gives the slope of the tangent line to the graph at that point."),
        ("INTERMEDIATE", "What is the derivative of f(x) = x^3 + 2x - 5?",
         ["3x^2 + x", "3x^2 - 2", "3x^2 + 2", "3x^2 + 5"], "C",
         "Applying the power rule to each term gives 3x^2 for x^3, 2 for 2x, and 0 for the constant."),
        ("INTERMEDIATE", "What is the derivative of f(x) = (3x + 2)^4?",
         ["4(3x + 2)^3", "3(3x + 2)^3", "12(3x + 2)^3", "12(3x + 2)^4"], "D",
         "The chain rule gives 4(3x + 2)^3 times the inner derivative 3, which is 12(3x + 2)^3."),
        ("INTERMEDIATE", "What is the derivative of the product f(x) = x^2 * e^x using the product rule?",
         ["2x*e^x + x^2*e^x", "2x*e^x", "x^2*e^x", "2x*e^x - x^2*e^x"], "A",
         "The product rule gives (x^2)'*e^x + x^2*(e^x)' = 2x*e^x + x^2*e^x."),
        ("INTERMEDIATE", "Using the quotient rule, what is the derivative of f(x) = (x^2 + 1)/x?",
         ["(x^2 + 1)/x^2", "(x^2 - 1)/x^2", "(2x^2 - 1)/x^2", "(x^2 - 1)/x"], "B",
         "The quotient rule gives (2x*x - (x^2 + 1)*1)/x^2, which simplifies to (x^2 - 1)/x^2."),
        ("INTERMEDIATE", "What is the slope of the tangent line to the curve y = x^2 at x = 3?",
         ["3", "9", "6", "12"], "C",
         "The derivative 2x gives the slope, and 2 times 3 equals 6 at the point x = 3."),
        ("INTERMEDIATE", "What is the second derivative of f(x) = x^4?",
         ["4x^3", "12x^3", "4x^2", "12x^2"], "D",
         "The first derivative is 4x^3, and differentiating again gives 12x^2."),
        ("INTERMEDIATE", "At which x-value is the tangent to y = x^2 - 4x horizontal?",
         ["x = 2", "x = 4", "x = 0", "x = -2"], "A",
         "A horizontal tangent means the derivative 2x - 4 equals zero, which happens at x = 2."),
        ("INTERMEDIATE", "If the position of a particle is s(t) = 5t^2, what is its velocity at t = 3?",
         ["15", "30", "45", "10"], "B",
         "Velocity is the derivative 10t, so at t = 3 the velocity is 10 times 3 equals 30."),
        ("INTERMEDIATE", "What is the derivative of f(x) = x*ln(x)?",
         ["x + ln(x)", "ln(x) - 1", "ln(x) + 1", "x*ln(x)"], "C",
         "The product rule gives 1*ln(x) + x*(1/x), which simplifies to ln(x) + 1."),
        ("INTERMEDIATE", "Which statement correctly relates differentiability and continuity?",
         ["Continuity implies differentiability everywhere", "They are unrelated", "Differentiability implies the function is constant", "A function can be continuous but not differentiable at a corner"], "D",
         "Differentiability is stronger than continuity: a continuous function can fail to be differentiable at a corner or cusp."),
        ("ADVANCED", "What is the equation of the tangent line to y = x^3 at x = 1?",
         ["y = 3x - 2", "y = 3x + 2", "y = x - 1", "y = 3x"], "A",
         "At x = 1 the point is (1, 1) and the slope is 3, so the tangent line is y - 1 = 3(x - 1), or y = 3x - 2."),
        ("ADVANCED", "Using linear approximation about x = 4, what is the approximate value of sqrt(4.01)?",
         ["2.0001", "2.0025", "2.01", "2.025"], "B",
         "The tangent line gives 2 + (1/4)*0.01 = 2.0025, the best linear estimate of the square root."),
        ("ADVANCED", "A farmer fences a rectangular field on three sides using 100 m of fencing, with one side along a river needing no fence. What length along the river maximises the area?",
         ["25 m", "75 m", "50 m", "100 m"], "C",
         "With x + 2y = 100 the area is x*y = 100y - 2y^2; setting its derivative to zero gives y = 25 and x = 50."),
        ("ADVANCED", "Which iteration formula does Newton's method use to approximate a root of f(x) = 0?",
         ["x_(n+1) = x_n + f(x_n)/f'(x_n)", "x_(n+1) = f(x_n)/f'(x_n)", "x_(n+1) = x_n * f'(x_n)/f(x_n)", "x_(n+1) = x_n - f(x_n)/f'(x_n)"], "D",
         "Newton's method moves each iterate along the tangent line, subtracting f(x_n)/f'(x_n) from the current estimate."),
        ("ADVANCED", "A balloon's radius grows at 2 cm/s. How fast is the volume increasing when the radius is 3 cm?",
         ["72*pi cm^3/s", "36*pi cm^3/s", "18*pi cm^3/s", "24*pi cm^3/s"], "A",
         "Differentiating V = (4/3)*pi*r^3 gives dV/dt = 4*pi*r^2*dr/dt = 4*pi*9*2, which is 72*pi cm^3/s."),
        ("ADVANCED", "Which condition is required for Rolle's theorem to apply to a function f on [a, b]?",
         ["f is differentiable but not continuous", "f(a) != f(b)", "f is continuous on [a, b], differentiable on (a, b), and f(a) = f(b)", "f is never zero"], "B",
         "Rolle's theorem needs continuity on the closed interval, differentiability on the open interval, and equal endpoint values."),
        ("ADVANCED", "For f(x) = x^2 on [1, 3], what value of c satisfies the Mean Value Theorem?",
         ["c = 1", "c = 4", "c = 2", "c = 3"], "C",
         "The average slope is (9 - 1)/2 = 4, and f'(x) = 2x equals 4 at x = 2, so c = 2."),
        ("ADVANCED", "Which function has derivative 1/x for all x > 0?",
         ["x", "e^x", "1", "ln(x)"], "D",
         "The derivative of ln(x) is 1/x, making it the antiderivative of 1/x on the positive domain."),
        ("ADVANCED", "Using implicit differentiation, what is dy/dx for the circle x^2 + y^2 = 25?",
         ["-x/y", "x/y", "-y/x", "y/x"], "A",
         "Differentiating both sides gives 2x + 2y*dy/dx = 0, so dy/dx = -x/y."),
        ("ADVANCED", "For the second derivative test, which condition indicates that f has a local maximum at a critical point c?",
         ["f''(c) > 0", "f''(c) < 0", "f''(c) = 0", "f''(c) is undefined"], "B",
         "A negative second derivative means the function is concave down at c, signalling a local maximum."),
    ],
    203: [
        ("BEGINNER", "What is the antiderivative of x^n for n not equal to -1?",
         ["x^(n+1)/(n+1) + C", "n*x^(n-1) + C", "x^(n-1)/(n-1) + C", "ln(x) + C"], "A",
         "The power rule for integration raises the exponent by one and divides by the new exponent, adding the constant C."),
        ("BEGINNER", "Which symbol conventionally represents the constant of integration in an indefinite integral?",
         ["e", "C", "Pi", "D"], "B",
         "The letter C denotes an arbitrary constant because differentiation erases any constant term."),
        ("BEGINNER", "What is the indefinite integral of sin(x) dx?",
         ["-cos(x) + C", "cos(x) + C", "-sin(x) + C", "tan(x) + C"], "C",
         "Since the derivative of -cos(x) is sin(x), the integral of sin(x) dx is -cos(x) + C."),
        ("BEGINNER", "What is the indefinite integral of 1/x dx?",
         ["x + C", "1/x^2 + C", "e^x + C", "ln|x| + C"], "D",
         "The antiderivative of 1/x is ln|x| plus a constant, valid for all x except zero."),
        ("BEGINNER", "What is the indefinite integral of e^x dx?",
         ["e^x + C", "x*e^x + C", "e^(x+1) + C", "ln(x) + C"], "A",
         "The exponential function e^x is its own antiderivative, so the integral is e^x + C."),
        ("BEGINNER", "For a non-negative function f(x), what does the definite integral from a to b compute?",
         ["The slope of the curve", "The area under the curve between a and b", "The derivative at b", "The average of a and b"], "B",
         "The definite integral measures the signed area between the curve and the x-axis over the interval [a, b]."),
        ("BEGINNER", "What is the indefinite integral of cos(x) dx?",
         ["-sin(x) + C", "-cos(x) + C", "sin(x) + C", "cos(x) + C"], "C",
         "Since the derivative of sin(x) is cos(x), the integral of cos(x) dx is sin(x) + C."),
        ("BEGINNER", "Which theorem links differentiation and integration as inverse operations?",
         ["Pythagoras' theorem", "Binomial theorem", "Cauchy-Schwarz inequality", "The Fundamental Theorem of Calculus"], "D",
         "The Fundamental Theorem of Calculus connects antiderivatives with definite integrals, uniting the two operations."),
        ("BEGINNER", "What is the value of the definite integral of x dx from 0 to 2?",
         ["4", "2", "0", "8"], "B",
         "The antiderivative x^2/2 evaluated from 0 to 2 gives 4/2 minus 0, which equals 2."),
        ("BEGINNER", "What is the value of the definite integral of 3 dx from 0 to 4?",
         ["12", "3", "7", "64"], "A",
         "The constant function 3 over an interval of length 4 gives an area of 3 times 4 equals 12."),
        ("INTERMEDIATE", "Using the substitution u = x^2, what is the integral of 2x*cos(x^2) dx?",
         ["-sin(x^2) + C", "cos(x^2) + C", "sin(x^2) + C", "2 sin(x^2) + C"], "C",
         "With du = 2x dx the integral becomes the integral of cos(u) du, which is sin(u), or sin(x^2) + C."),
        ("INTERMEDIATE", "What is the value of the definite integral of (3x + 2) dx from 0 to 1?",
         ["1/2", "5/2", "3/2", "7/2"], "D",
         "The antiderivative (3/2)x^2 + 2x evaluated from 0 to 1 gives 3/2 + 2 = 7/2."),
        ("INTERMEDIATE", "Which formula expresses integration by parts?",
         ["integral of u dv = uv - integral of v du", "integral of u dv = uv + integral of v du", "integral of u dv = integral of v du", "integral of u dv = uv"], "A",
         "Integration by parts reverses the product rule, transferring the derivative from u to v."),
        ("INTERMEDIATE", "What is the indefinite integral of sec^2(x) dx?",
         ["sin(x) + C", "tan(x) + C", "cot(x) + C", "sec(x) + C"], "B",
         "The derivative of tan(x) is sec^2(x), so the antiderivative of sec^2(x) is tan(x) + C."),
        ("INTERMEDIATE", "What is the area between the curves y = x^2 and y = x from x = 0 to x = 1?",
         ["1/3", "1/2", "1/6", "1"], "C",
         "The area is the integral of (x - x^2) from 0 to 1, which is 1/2 - 1/3 = 1/6."),
        ("INTERMEDIATE", "What is the indefinite integral of 1/(1 + x^2) dx?",
         ["arcsin(x) + C", "ln(1 + x^2) + C", "x + C", "arctan(x) + C"], "D",
         "The derivative of arctan(x) is 1/(1 + x^2), so the integral is arctan(x) + C."),
        ("INTERMEDIATE", "Using the substitution u = x^2, what is the integral of x*e^(x^2) dx?",
         ["(1/2)e^(x^2) + C", "e^(x^2) + C", "2 e^(x^2) + C", "x*e^(x^2) + C"], "A",
         "Since du = 2x dx, the integral becomes (1/2) times the integral of e^u du, giving (1/2)e^(x^2) + C."),
        ("INTERMEDIATE", "By the Fundamental Theorem of Calculus, what is d/dx of the integral of t^2 dt from 0 to x?",
         ["x^3/3", "x^2", "x^3", "2x"], "B",
         "The derivative of the integral returns the integrand evaluated at the upper limit, which is x^2."),
        ("INTERMEDIATE", "What is the indefinite integral of sqrt(x) dx?",
         ["(1/2)x^(3/2) + C", "2 x^(1/2) + C", "(2/3)x^(3/2) + C", "x^(3/2) + C"], "C",
         "Writing sqrt(x) as x^(1/2), the power rule gives x^(3/2) divided by 3/2, which is (2/3)x^(3/2) + C."),
        ("INTERMEDIATE", "Which formula computes the average value of f(x) on the interval [a, b]?",
         ["The integral of f(x) dx", "f(b) - f(a)", "f(a) + f(b)", "(1/(b - a)) times the integral of f(x) from a to b"], "D",
         "The average value divides the definite integral by the length of the interval, (b - a)."),
        ("ADVANCED", "Using integration by parts, what is the integral of x*e^x dx?",
         ["x e^x - e^x + C", "x e^x + e^x + C", "e^x + C", "(x^2/2) e^x + C"], "A",
         "Choosing u = x and dv = e^x dx gives x e^x minus the integral of e^x dx, which is x e^x - e^x + C."),
        ("ADVANCED", "What is the integral of ln(x) dx?",
         ["x ln(x) + C", "x ln(x) - x + C", "ln(x)/x + C", "1/x + C"], "B",
         "Integration by parts with u = ln(x) and dv = dx yields x ln(x) - x + C."),
        ("ADVANCED", "What is the value of the improper integral of 1/x^2 dx from 1 to infinity?",
         ["Infinity", "0", "1", "2"], "C",
         "The antiderivative -1/x from 1 to infinity tends to 0 - (-1) = 1, so the integral converges to 1."),
        ("ADVANCED", "Which substitution is the standard choice for the integral of sqrt(1 - x^2) dx?",
         ["x = tan(theta)", "x = e^theta", "x = theta^2", "x = sin(theta)"], "D",
         "Setting x = sin(theta) turns 1 - x^2 into cos^2(theta), simplifying the radical for trigonometric substitution."),
        ("ADVANCED", "To integrate 1/(x^2 - 1), which partial fraction form is appropriate?",
         ["A/(x - 1) + B/(x + 1)", "A/(x^2) + B", "Ax + B", "A/x + B/x^2"], "A",
         "The denominator factors as (x - 1)(x + 1), so the integrand decomposes into A/(x - 1) plus B/(x + 1)."),
        ("ADVANCED", "Which formula gives the volume of a solid of revolution using the disc method about the x-axis?",
         ["The integral of f(x) dx", "pi times the integral of [f(x)]^2 from a to b", "2*pi times f(x)", "f(b) - f(a)"], "B",
         "Each disc has area pi*[f(x)]^2, so the volume is pi times the integral of the squared radius over the interval."),
        ("ADVANCED", "Which formula computes volume by cylindrical shells, using radius r(x) and height f(x)?",
         ["The integral of f(x) dx", "pi times the integral of f(x)^2 dx", "2*pi times the integral of r(x)*f(x) over the interval", "f(b) - f(a)"], "C",
         "The shell method wraps shells of radius r and height f, so volume is 2*pi times the integral of r*f."),
        ("ADVANCED", "What is the value of the definite integral of sin(x) dx from 0 to pi/2?",
         ["0", "2", "pi/2", "1"], "D",
         "The antiderivative -cos(x) evaluated from 0 to pi/2 gives 0 - (-1) = 1."),
        ("ADVANCED", "For an odd function f(x) on the symmetric interval [-a, a], what is the value of its definite integral?",
         ["0", "Twice the integral from 0 to a", "Undefined", "a"], "A",
         "Symmetry makes the positive and negative areas cancel exactly, so the integral of an odd function over [-a, a] is 0."),
        ("ADVANCED", "Which numerical integration rule approximates a definite integral by summing trapezoid areas?",
         ["Simpson's rule only", "The trapezoidal rule", "Euler's method", "Newton's method"], "B",
         "The trapezoidal rule approximates each strip as a trapezoid, giving a simple linear estimate of the area."),
    ],
    204: [
        ("BEGINNER", "What is the order (dimension) of a matrix with 3 rows and 4 columns?",
         ["3 x 4", "4 x 3", "3 x 3", "4 x 4"], "A",
         "A matrix dimension is written as rows by columns, so 3 rows and 4 columns is a 3 x 4 matrix."),
        ("BEGINNER", "Which type of matrix has the same number of rows and columns?",
         ["Row matrix", "Square matrix", "Diagonal matrix", "Identity matrix"], "B",
         "A square matrix has equal numbers of rows and columns, such as a 3 x 3 matrix."),
        ("BEGINNER", "What is the transpose of a matrix?",
         ["Rows and columns are interchanged", "The matrix is multiplied by itself", "The diagonal is removed", "All entries change sign"], "C",
         "The transpose A^T swaps rows and columns, so entry a_ij moves to position a_ji."),
        ("BEGINNER", "Which matrix results from multiplying a matrix A by an identity matrix of compatible size?",
         ["The zero matrix", "The transpose", "The original matrix A", "A scalar multiple of A"], "D",
         "The identity matrix acts as the multiplicative identity, so A times I equals A."),
        ("BEGINNER", "Which of the following is the 2 x 2 identity matrix?",
         ["[1 0; 0 1]", "[1 1; 1 1]", "[0 0; 0 0]", "[1 0; 1 0]"], "A",
         "The identity matrix has 1s on the main diagonal and 0s elsewhere."),
        ("BEGINNER", "Which condition must hold for two matrices A and B to be multiplied as AB?",
         ["Both matrices must be square", "The number of columns of A must equal the number of rows of B", "The number of rows of A must equal the number of rows of B", "A and B must have identical dimensions"], "B",
         "Matrix multiplication requires the inner dimensions to match: columns of A equal rows of B."),
        ("BEGINNER", "What is the determinant of the 2 x 2 matrix [a b; c d]?",
         ["ac - bd", "ab + cd", "ad - bc", "a + d"], "C",
         "The determinant of a 2 x 2 matrix is ad - bc, the difference of the diagonal products."),
        ("BEGINNER", "Which matrix is formed by interchanging rows and columns and is written as A^T?",
         ["Inverse", "Adjoint", "Cofactor", "Transpose"], "D",
         "The transpose A^T is created by swapping the rows and columns of the original matrix."),
        ("BEGINNER", "What is a square matrix called if all entries off the main diagonal are zero?",
         ["Diagonal matrix", "Upper triangular matrix", "Symmetric matrix", "Zero matrix"], "A",
         "A diagonal matrix has nonzero entries only on the main diagonal and zeros elsewhere."),
        ("BEGINNER", "Which of the following is the 2 x 2 zero matrix?",
         ["[0 0; 0 0]", "[1 1; 1 1]", "[0 1; 1 0]", "[1 0; 0 1]"], "B",
         "The zero matrix contains only zero entries and acts as the additive identity for matrices."),
        ("INTERMEDIATE", "If A is a 2 x 3 matrix and B is a 3 x 4 matrix, what is the order of the product AB?",
         ["2 x 4", "3 x 3", "4 x 2", "2 x 3"], "C",
         "The product takes the row count of A and the column count of B, so AB is 2 x 4."),
        ("INTERMEDIATE", "What is the determinant of the diagonal matrix [2 0; 0 5]?",
         ["0", "7", "25", "10"], "D",
         "For a diagonal matrix the determinant is the product of its diagonal entries, 2 times 5 equals 10."),
        ("INTERMEDIATE", "For which value of x is the determinant of the matrix [x 1; 2 4] equal to zero?",
         ["1/2", "2", "4", "1"], "A",
         "The determinant 4x - 2 equals zero when x = 1/2."),
        ("INTERMEDIATE", "What is the inverse of the 2 x 2 matrix [a b; c d] with determinant D?",
         ["(1/D) * [d -b; -c a]", "(1/D) * [a -b; -c d]", "D * [d b; c a]", "[d -b; -c a]"], "B",
         "The inverse swaps a and d, negates b and c, and divides the whole matrix by the determinant D."),
        ("INTERMEDIATE", "What is the rank of the 2 x 2 identity matrix?",
         ["0", "1", "2", "Undefined"], "C",
         "The identity matrix has two linearly independent rows, so its rank is 2."),
        ("INTERMEDIATE", "Which method solves a system of linear equations using ratios of determinants?",
         ["Gauss elimination", "Cramer's rule", "Matrix inversion", "Substitution only"], "D",
         "Cramer's rule expresses each unknown as a ratio of determinants built from the coefficient matrix."),
        ("INTERMEDIATE", "For the system 2x + 3y = 7 and 4x + 6y = 14, what type of solution set exists?",
         ["No solution", "Exactly one solution", "Two solutions", "Infinitely many solutions"], "D",
         "The second equation is exactly twice the first, so the lines coincide and every point on the line is a solution."),
        ("INTERMEDIATE", "What does it mean for a linear system Ax = b to be consistent?",
         ["It has at least one solution", "It has no solution", "The matrix A is singular", "The determinant is zero"], "A",
         "A consistent system has at least one solution, meaning the equations do not contradict each other."),
        ("INTERMEDIATE", "If the determinant of a square matrix A is zero, what is A called?",
         ["Invertible", "Diagonal", "Upper triangular", "Singular"], "C",
         "A square matrix with zero determinant is singular, so it has no inverse."),
        ("INTERMEDIATE", "What is the result of multiplying a matrix by a scalar k?",
         ["Each entry is multiplied by k", "Only the diagonal entries are multiplied", "The matrix is squared", "The matrix is transposed"], "D",
         "Scalar multiplication multiplies every entry of the matrix by the scalar k."),
        ("ADVANCED", "Which elimination method converts a matrix to row echelon form to solve a linear system?",
         ["Gaussian elimination", "Cramer's rule", "Determinant expansion", "Trace computation"], "A",
         "Gaussian elimination uses elementary row operations to reach row echelon form, then back-substitutes to find solutions."),
        ("ADVANCED", "For which value of k does the system x + y = 3 and kx + y = 4 have no solution?",
         ["k = 2", "k = 1", "k = 0", "k = 3"], "B",
         "When k = 1, subtracting the equations gives 0 = 1, a contradiction, so no solution exists."),
        ("ADVANCED", "What is the determinant of the 3 x 3 identity matrix?",
         ["0", "3", "1", "6"], "C",
         "The determinant of any identity matrix is 1, regardless of its order."),
        ("ADVANCED", "For an invertible matrix A, which equation correctly relates A and its inverse?",
         ["A + A^(-1) = I", "A - A^(-1) = I", "A * A^(-1) = I", "A * A = I"], "D",
         "By definition the inverse satisfies A * A^(-1) = A^(-1) * A = I, the identity matrix."),
        ("ADVANCED", "How many solutions does the homogeneous system Ax = 0 have when A is a square nonsingular matrix?",
         ["Exactly one, the trivial solution", "Infinitely many", "No solution", "Two solutions"], "A",
         "A nonsingular coefficient matrix is invertible, so Ax = 0 has only the trivial solution x = 0."),
        ("ADVANCED", "Which operation is NOT an elementary row operation on a matrix?",
         ["Swapping two rows", "Multiplying a row by a nonzero scalar", "Adding a multiple of one row to another", "Interchanging two columns and two rows simultaneously"], "B",
         "Elementary row operations act on single rows; mixing columns into a row operation is not permitted."),
        ("ADVANCED", "For matrices A and B of compatible sizes, which identity is always true?",
         ["(AB)^T = A^T B^T", "(AB)^T = B^T A^T", "(AB)^T = A B", "(AB)^T = B A"], "C",
         "The transpose of a product reverses the factor order, so (AB)^T = B^T A^T."),
        ("ADVANCED", "Which property of determinants holds for an n x n matrix A and a scalar c?",
         ["det(cA) = c^n det(A)", "det(cA) = c det(A)", "det(cA) = det(A)", "det(cA) = c^(2n) det(A)"], "D",
         "Multiplying one row by c multiplies the determinant by c, and there are n rows, giving c^n det(A)."),
        ("ADVANCED", "Which condition guarantees that a linear system has infinitely many solutions?",
         ["The rank of A exceeds the rank of the augmented matrix", "A free variable exists and the rank of A equals the rank of the augmented matrix", "The system has equal numbers of equations and unknowns", "The determinant is nonzero"], "A",
         "A free variable with consistent ranks means some unknowns are free, producing infinitely many solutions."),
        ("ADVANCED", "What is the trace of a square matrix?",
         ["The sum of the diagonal entries", "The product of the diagonal entries", "The determinant of the matrix", "The number of rows"], "B",
         "The trace is defined as the sum of the entries on the main diagonal of a square matrix."),
    ],
    205: [
        ("BEGINNER", "What is the order of the differential equation y' + y = 0?",
         ["1", "2", "3", "0"], "A",
         "The order is the highest derivative present, and here the highest is the first derivative y'."),
        ("BEGINNER", "What is the degree of the differential equation (y')^2 + y = 0?",
         ["1", "2", "3", "4"], "B",
         "The degree is the power of the highest order derivative, which here is squared, so the degree is 2."),
        ("BEGINNER", "Which of the following is a solution of dy/dx = 0?",
         ["y = x", "y = x^2", "y = 5", "y = e^x"], "C",
         "Any constant function has zero derivative, so y = 5 satisfies dy/dx = 0."),
        ("BEGINNER", "What is the general solution of dy/dx = 1?",
         ["y = 1", "y = C", "y = x^2 + C", "y = x + C"], "D",
         "Integrating 1 with respect to x gives x plus an arbitrary constant C."),
        ("BEGINNER", "What is the general solution of dy/dx = 2x?",
         ["y = x^2 + C", "y = 2x^2 + C", "y = x + C", "y = 2 + C"], "A",
         "Integrating 2x with respect to x gives x^2 plus an arbitrary constant C."),
        ("BEGINNER", "A first-order differential equation is called separable when it can be written in which form?",
         ["dy/dx = x + y", "dy/dx = g(x) h(y)", "dy/dx = 0", "y = mx + c"], "B",
         "A separable equation factors into a product of a function of x and a function of y."),
        ("BEGINNER", "What is a particular solution of a differential equation?",
         ["A solution obtained by applying initial conditions to the general solution", "The derivative of the general solution", "Any random function", "The highest order derivative"], "C",
         "Applying initial conditions to the general solution fixes the constant and yields one particular solution."),
        ("BEGINNER", "Which type of differential equation has y and its derivatives only to the first power?",
         ["Nonlinear", "Separable only", "Homogeneous only", "Linear"], "D",
         "A linear ODE contains no products or powers of y and its derivatives beyond the first power."),
        ("BEGINNER", "What does the initial condition y(0) = 3 specify?",
         ["The value of y when x = 0", "The derivative at zero", "The order of the equation", "The degree of the equation"], "A",
         "An initial condition gives the value of the dependent variable at a starting point, here y = 3 at x = 0."),
        ("BEGINNER", "What is the characteristic equation of y'' - 5y' + 6y = 0?",
         ["m^2 + 5m + 6 = 0", "m^2 - 5m + 6 = 0", "m - 5 = 0", "m^2 - 6m + 5 = 0"], "B",
         "Substituting y = e^(mx) turns the equation into m^2 - 5m + 6 = 0, the characteristic equation."),
        ("INTERMEDIATE", "What is the general solution of dy/dx = e^x?",
         ["x e^x + C", "ln(x) + C", "e^x + C", "e^x"], "C",
         "Integrating e^x with respect to x gives e^x plus the arbitrary constant C."),
        ("INTERMEDIATE", "What is the general solution of the separable equation dy/dx = x/y?",
         ["y = x + C", "y^2 = x^2 + C", "y = x^2 + C", "y^2 = x + C"], "D",
         "Separating gives y dy = x dx; integrating both sides yields y^2/2 = x^2/2 + C, so y^2 = x^2 + C."),
        ("INTERMEDIATE", "For the initial value problem dy/dx = 2x with y(0) = 3, what is the particular solution?",
         ["y = x^2 + 3", "y = x^2 - 3", "y = 2x + 3", "y = x^2 + 2"], "A",
         "The general solution is y = x^2 + C, and y(0) = 3 forces C = 3, giving y = x^2 + 3."),
        ("INTERMEDIATE", "What is the general solution of y'' + y = 0?",
         ["y = C1 cos(x) + C2 sin(x)", "y = C1 e^x + C2 e^(-x)", "y = C1 + C2 x", "y = C1 e^(ix)"], "B",
         "The characteristic roots are complex, m = ±i, so the solution is a combination of sine and cosine."),
        ("INTERMEDIATE", "Which substitution reduces a Bernoulli equation y' + P(x)y = Q(x)y^n to a linear equation?",
         ["u = y^n", "u = y^(1 - n)", "u = x^2", "u = y/(n)"], "C",
         "Setting u = y^(1 - n) turns the Bernoulli equation into a first-order linear equation in u."),
        ("INTERMEDIATE", "What is the integrating factor for the linear equation y' + P(x)y = Q(x)?",
         ["e raised to the integral of Q(x) dx", "P(x)", "The integral of Q(x)", "e raised to the integral of P(x) dx"], "D",
         "Multiplying by e to the integral of P(x) dx makes the left side an exact derivative."),
        ("INTERMEDIATE", "What is the general solution of the differential equation y'' = 0?",
         ["y = C1 x + C2", "y = C1 e^x + C2", "y = C1 x^2 + C2", "y = C1 + C2"], "A",
         "Integrating twice gives y' = C1 and then y = C1 x + C2, a straight line family."),
        ("INTERMEDIATE", "Which method finds a particular solution of a nonhomogeneous equation when the forcing term is a polynomial?",
         ["Method of undetermined coefficients", "Separation of variables", "Substitution u = y/x", "Laplace transform only"], "B",
         "The method of undetermined coefficients guesses a polynomial trial solution matching the forcing term."),
        ("INTERMEDIATE", "For the initial value problem dy/dx = y with y(0) = 2, what is the solution?",
         ["y = e^(2x)", "y = 2x", "y = 2 ln(x)", "y = 2e^x"], "C",
         "Separating and integrating gives y = C e^x, and y(0) = 2 sets C = 2."),
        ("INTERMEDIATE", "What is the order of the differential equation y''' + y'' + y = 0?",
         ["1", "2", "3", "4"], "D",
         "The highest derivative present is y''', the third derivative, so the order is 3."),
        ("ADVANCED", "An RL circuit with inductance L, resistance R and constant voltage E satisfies L di/dt + R i = E. Which form does the current take?",
         ["A polynomial in t", "A purely sinusoidal term", "A constant steady-state term plus an exponential decay term", "A random function"], "A",
         "The solution combines the steady-state value E/R with a decaying exponential term from the transient response."),
        ("ADVANCED", "For a homogeneous second-order ODE with distinct real characteristic roots r1 and r2, what is the general solution?",
         ["y = C1 e^(r1 x) + C2 e^(r2 x)", "y = (C1 + C2 x) e^(r x)", "y = e^(a x)(C1 cos(b x) + C2 sin(b x))", "y = C1 + C2 x"], "B",
         "Distinct real roots produce two independent exponential solutions combined with two constants."),
        ("ADVANCED", "For a repeated characteristic root r, what is the general solution of the homogeneous ODE?",
         ["y = C1 e^(r1 x) + C2 e^(r2 x)", "y = C1 cos(x) + C2 sin(x)", "y = C1 x + C2", "y = (C1 + C2 x) e^(r x)"], "D",
         "A repeated root requires the extra factor x to generate a second linearly independent solution."),
        ("ADVANCED", "For complex characteristic roots a ± ib, what is the general solution of the homogeneous ODE?",
         ["y = e^(a x)(C1 cos(b x) + C2 sin(b x))", "y = C1 e^(a x) + C2 e^(b x)", "y = (C1 + C2 x) e^(a x)", "y = C1 x + C2"], "A",
         "Complex roots pair into damped oscillations, with e^(a x) governing growth and the trig terms the oscillation."),
        ("ADVANCED", "What does the Wronskian of two solutions of a second-order ODE reveal?",
         ["Whether the two solutions are linearly independent", "The order of the equation", "The degree of the equation", "The particular solution only"], "B",
         "A nonzero Wronskian at a point proves the two solutions are linearly independent."),
        ("ADVANCED", "Which approach converts a high-order ODE into a system of first-order equations for numerical solution?",
         ["Multiplying the equation by an integrating factor", "Introducing state variables to reduce the order", "Applying separation of variables", "Using only Cramer's rule"], "C",
         "Defining the derivatives as new state variables rewrites the ODE as a system of first-order equations."),
        ("ADVANCED", "A damped mass-spring system follows m x'' + c x' + k x = 0. What happens when c^2 < 4mk?",
         ["The system is overdamped and never oscillates", "The system is critically damped", "The system is underdamped and oscillates with decaying amplitude", "The system has no motion"], "D",
         "When the damping is weak, the discriminant is negative and the solution oscillates with a decaying envelope."),
        ("ADVANCED", "Which numerical method approximates y' = f(x, y) using y_(n+1) = y_n + h f(x_n, y_n)?",
         ["Euler's method", "Newton's method", "Bisection method", "Gaussian elimination"], "A",
         "Euler's method advances each step along the current slope, giving the simplest explicit scheme."),
        ("ADVANCED", "For the initial value problem y' = y with y(0) = 1, what is the exact value of y at x = 1?",
         ["e", "1", "2", "ln(2)"], "B",
         "The solution is y = e^x, so at x = 1 the value is the natural constant e."),
        ("ADVANCED", "Which technique solves a nonhomogeneous second-order ODE by integrating the fundamental solutions against the forcing term?",
         ["Separation of variables", "Variation of parameters", "Undetermined coefficients for any forcing", "Numerical quadrature"], "C",
         "Variation of parameters replaces the arbitrary constants with functions and integrates them against the forcing term."),
    ],
}
