# -*- coding: utf-8 -*-
"""
Question bank for subject 35: CLD105 - Infrastructure & Automation.
Category: Cloud, Cybersecurity & DevOps.

Topics:
  171: Infrastructure as Code
  172: Terraform & CloudFormation
  173: Configuration Management
  174: CI/CD Pipelines
  175: SRE & Reliability

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    171: [
        ("BEGINNER", "What is the core idea behind Infrastructure as Code (IaC)?",
         ["defining and provisioning infrastructure using machine-readable definition files", "manually configuring each server through a terminal", "using a GUI console to click through server setup", "purchasing physical hardware for data centers"], "A",
         "IaC treats infrastructure as software by describing it in machine-readable definition files that can be versioned, reviewed, and applied consistently."),
        ("BEGINNER", "Which of the following tools is primarily used for Infrastructure as Code?",
         ["MySQL", "Terraform", "Windows Notepad", "Microsoft Excel"], "B",
         "Terraform is a dedicated IaC tool that lets teams define cloud resources in declarative configuration files and apply them automatically."),
        ("BEGINNER", "Which of the following is a major benefit of Infrastructure as Code?",
         ["slower environment provisioning", "more manual steps per deployment", "repeatable and consistent infrastructure provisioning", "hardware costs always decrease"], "C",
         "IaC makes provisioning repeatable and consistent because the same definition produces the same environment every time it is applied."),
        ("BEGINNER", "How does version control help with Infrastructure as Code?",
         ["it is not used with IaC", "it only stores passwords", "it replaces the need for any tooling", "it allows infrastructure changes to be reviewed, tracked, and rolled back"], "D",
         "Storing IaC definitions in version control records every change, supports peer review, and makes rollbacks straightforward."),
        ("BEGINNER", "What does it mean for IaC to be declarative?",
         ["you state the desired end state and the tool makes it happen", "you list every exact command to run in order", "you must reboot servers manually after each step", "you describe how tasks run instead of what to build"], "A",
         "Declarative IaC focuses on the desired end state, leaving the tool to figure out the steps needed to reach that state."),
        ("BEGINNER", "Which property ensures that running the same IaC definition again produces the same result?",
         ["mutability", "idempotency", "latency", "locality"], "B",
         "Idempotency means applying the same configuration multiple times converges to the same state without duplicating resources or side effects."),
        ("BEGINNER", "In IaC, what is an execution plan?",
         ["a printed hardware budget", "a backup of the database", "a preview of the changes the tool will make before applying them", "a list of employees on the operations team"], "C",
         "An execution plan shows the actions a tool such as Terraform will take so teams can review and approve changes before they happen."),
        ("BEGINNER", "What is the advantage of treating infrastructure definitions as code?",
         ["they can only be read by senior engineers", "they become unreadable and unmaintainable", "they cannot be shared across teams", "they can be tested, reviewed, and automatically validated like application code"], "D",
         "Infrastructure definitions gain the same benefits as application code, including automated testing, review, and validation."),
        ("BEGINNER", "What is the purpose of a state file in IaC tools?",
         ["it records the current deployed resources so the tool can plan changes accurately", "it stores only the billing history", "it logs every employee login", "it replaces the need for a cloud account"], "A",
         "The state file tracks what has actually been deployed so the tool can compute the difference between real infrastructure and the desired configuration."),
        ("BEGINNER", "Which practice is commonly used with IaC to reduce differences between environments?",
         ["deploying only in production", "using the same configuration modules across development, staging, and production", "manually changing servers after deployment", "keeping every environment definition separate with no reuse"], "B",
         "Reusing shared configuration modules across environments reduces drift and keeps environments consistent with one another."),
        ("INTERMEDIATE", "A developer manually edits a production server to fix a bug. What is the immediate concern with this practice?",
         ["the fix is automatically documented", "the change will not be captured in version control and may be overwritten by the next IaC run", "the server will reboot automatically", "the change is applied to all environments at once"], "C",
         "Manual server edits create configuration drift because they bypass the IaC definition, and a later apply may revert them."),
        ("INTERMEDIATE", "Your team needs to provision 50 identical EC2 instances. Which IaC approach is most appropriate?",
         ["creating each instance manually through the console", "writing a document describing how to create each one", "rebuilding the network every time", "using a single declarative configuration with a count or for_each construct"], "D",
         "A declarative configuration with count or for_each expresses the full set of 50 instances in one place and provisions them consistently."),
        ("INTERMEDIATE", "A change is rejected in review because it would recreate a database. What IaC feature could avoid this risk?",
         ["lifecycle rules that prevent destruction of the resource", "changing the password every day", "deleting the state file", "running apply without a plan"], "A",
         "Lifecycle rules such as prevent_destroy block destructive operations on critical resources like databases during a plan and apply."),
        ("INTERMEDIATE", "After a manual change to a resource, Terraform apply reverts it. Why?",
         ["Terraform prefers manual changes", "the configuration no longer matches the deployed state, so the tool corrects it", "the state file was deleted", "the cloud account has insufficient permissions"], "B",
         "Terraform compares the configuration to the state and corrects any drift, which is why manual edits get reverted."),
        ("INTERMEDIATE", "You store IaC definitions in git. What is the recommended workflow for a change?",
         ["commit directly to main and apply immediately", "edit production files on the server", "merge and delete the branch", "make a branch, submit a pull request, review, then merge and apply"], "C",
         "Branches, pull requests, and review make infrastructure changes auditable and let teams catch mistakes before applying."),
        ("INTERMEDIATE", "A team wants to reuse a VPC definition in three projects. Which approach follows IaC best practices?",
         ["copying the block into each project", "recreating it by hand each time", "ignoring the duplication", "refactoring it into a shared module with input parameters"], "D",
         "Refactoring reusable pieces into a parameterized module reduces duplication and keeps the source of truth in one place."),
        ("INTERMEDIATE", "During an IaC migration, the tool cannot delete a resource it no longer manages. What does this usually indicate?",
         ["the resource was created outside the tool and must be imported", "the tool is broken", "the cloud provider is down", "the state file is too large"], "A",
         "Resources created out of band need to be imported into the state so the tool can begin managing them properly."),
        ("INTERMEDIATE", "Which team practice reduces the chance of destructive mistakes when using IaC?",
         ["running apply directly in production with no review", "always planning and reviewing the diff before applying", "deleting old state files often", "using the same credentials everywhere"], "B",
         "Reviewing the plan output before applying lets teams spot destructive or unwanted changes such as resource recreation."),
        ("INTERMEDIATE", "An environment is failing because it was built with an outdated module version. How could this have been avoided?",
         ["pin and upgrade module versions deliberately", "always use the newest version instantly", "never use modules", "deploy only in production"], "C",
         "Pinning module versions and upgrading them intentionally through review keeps environments reproducible and predictable."),
        ("INTERMEDIATE", "What should you do when a teammate changed infrastructure directly in the cloud instead of editing the IaC code?",
         ["keep the manual change and update no files", "delete the cloud account", "ignore it completely", "revert the manual change and represent it properly in the IaC definition"], "D",
         "The manual change should be reconciled with the code, either by importing it or reverting it, so the code remains the source of truth."),
        ("ADVANCED", "Your IaC pipeline failed because a module fetched from a remote registry changed without notice. Which mitigation best addresses supply chain risk?",
         ["pin the module to an exact version and checksum, and review upgrades", "disable the internet on build servers", "recreate the state file daily", "store all modules on a local desktop"], "A",
         "Pinning exact versions and checksums protects against unexpected upstream changes and is a core IaC supply chain control."),
        ("ADVANCED", "A team needs different infrastructure in production versus development but shared logic. Which design is best?",
         ["write entirely separate definitions with copied logic", "use a single module with variables that parameterize the differences", "maintain two states with no shared code", "deploy development using production settings"], "B",
         "Parameterized modules let one source of truth serve multiple environments while variables express environment-specific values."),
        ("ADVANCED", "Applying IaC recreates your app instances during every deploy, causing downtime. Which strategy avoids this?",
         ["stop using IaC", "delete the instance definitions", "use rolling updates or blue-green deployment patterns", "apply only at midnight"], "C",
         "Rolling updates and blue-green patterns replace instances without a full cutover, keeping the service available during changes."),
        ("ADVANCED", "Your team stores state files in a local folder shared over email. What is the most important reason this is dangerous?",
         ["it makes plans slower", "it uses too much disk", "it is against cloud provider terms", "state can become stale and corrupted without locking, and it may expose sensitive values"], "D",
         "Shared state without locking causes corruption and data races, and state often contains sensitive values that need protected remote storage."),
        ("ADVANCED", "A senior engineer wants to codify security guardrails so developers cannot create publicly open buckets. Which IaC approach is most effective?",
         ["enforce policy as code with automated checks in the pipeline", "ask developers politely to be careful", "rotate the API keys weekly", "review every bucket manually once a month"], "A",
         "Policy as code runs automated checks against every change, blocking violations at merge time rather than relying on manual vigilance."),
        ("ADVANCED", "During a disaster recovery test, the team discovers recovery takes eight hours. How should IaC help improve this?",
         ["it cannot help with recovery", "versioned, tested IaC definitions let teams rebuild infrastructure in minutes instead of manually", "delete the disaster recovery plan", "increase server RAM"], "B",
         "Because environments are defined as code, teams can rebuild them quickly and consistently, drastically reducing recovery time."),
        ("ADVANCED", "Your IaC definition works in staging but fails in production because a resource name already exists globally. Which practice best prevents this class of error?",
         ["ignore the error", "create resources manually in production", "rename nothing", "use deterministic, environment-scoped naming conventions and unique suffixes"], "C",
         "Environment-scoped naming with unique suffixes avoids global collisions and makes environments identifiable."),
        ("ADVANCED", "Which change control approach gives the strongest assurance before applying IaC in production?",
         ["apply changes without review", "ask two teammates after applying", "apply and then check logs", "run the plan in production and approve it in a change management process with the plan diff"], "D",
         "Producing and reviewing the plan as part of change management makes the exact impact visible and approvable before anything runs."),
        ("ADVANCED", "The pipeline cannot apply IaC because the deployment credential has read-only permissions. What does this indicate about least privilege?",
         ["least privilege is correctly configured for normal operation but the deploy role needs the specific write permissions the automation requires", "the credential is fine", "permissions should never be granted", "least privilege only applies to humans"], "A",
         "Least privilege still allows automation to receive the specific write scopes it needs, and the credential was mis-scoped, not over-privileged."),
        ("ADVANCED", "A vendor drops an entire cloud region and your IaC is spread across three regions. Which reliability outcome does this design support?",
         ["everything fails together", "workloads can fail over to other regions because infrastructure is reproducible there", "backups are unnecessary", "recovery is always instant"], "B",
         "Multi-region, code-defined infrastructure lets teams rebuild or re-provision workloads in surviving regions during an outage."),
    ],
    172: [
        ("BEGINNER", "Which tool is HashiCorp's open-source Infrastructure as Code tool?",
         ["Terraform", "Ansible", "Puppet", "CloudFormation"], "A",
         "Terraform is HashiCorp's IaC tool that provisions resources across many cloud and service providers."),
        ("BEGINNER", "What is the file extension of Terraform configuration files?",
         ["yaml", "tf", "json5", "ini"], "B",
         "Terraform configuration files use the .tf extension and are written in the HashiCorp Configuration Language."),
        ("BEGINNER", "Which AWS service provides infrastructure as code for AWS resources?",
         ["S3", "Lambda", "CloudFormation", "Route 53"], "C",
         "AWS CloudFormation is AWS's native IaC service that models and provisions AWS resources from templates."),
        ("BEGINNER", "What are Terraform configuration files written in?",
         ["YAML", "XML", "JSON only", "HashiCorp Configuration Language (HCL)"], "D",
         "Terraform uses HCL, a declarative language purpose-built for describing infrastructure."),
        ("BEGINNER", "What does the terraform init command do?",
         ["initializes the working directory and downloads required providers", "destroys all resources", "deploys resources immediately", "starts a web server"], "A",
         "terraform init prepares the working directory by downloading the provider plugins the configuration needs."),
        ("BEGINNER", "What does the terraform plan command produce?",
         ["a summary of costs", "an execution plan showing what will change", "the IP addresses of servers", "a list of users"], "B",
         "terraform plan computes and displays an execution plan describing the exact changes apply would make."),
        ("BEGINNER", "Which command applies the changes described in a Terraform plan?",
         ["terraform init", "terraform destroy", "terraform apply", "terraform fmt"], "C",
         "terraform apply carries out the changes and provisions or updates the resources defined in the configuration."),
        ("BEGINNER", "In CloudFormation, what is a template?",
         ["a virtual machine image", "a Python script", "a database backup", "a JSON or YAML document describing resources and their properties"], "D",
         "A CloudFormation template is a JSON or YAML text file that declares the AWS resources and their configuration."),
        ("BEGINNER", "What is a Terraform provider?",
         ["a plugin that manages resources for a specific platform or cloud", "a virtual machine", "a type of network", "a file format"], "A",
         "Providers are plugins that translate Terraform's generic requests into the API calls of a specific platform such as AWS, Azure, or GCP."),
        ("BEGINNER", "Which command removes the resources managed by a Terraform configuration?",
         ["terraform apply", "terraform destroy", "terraform validate", "terraform graph"], "B",
         "terraform destroy tears down all resources tracked in the current Terraform state and configuration."),
        ("INTERMEDIATE", "Why must a team not delete the Terraform state file by accident?",
         ["state is only needed for billing", "it stores log files", "the state file records deployed resources, and losing it can make Terraform unable to manage them", "it is the same as the configuration"], "C",
         "The state file maps configuration to real resources, so losing it makes it difficult for Terraform to update or destroy what it manages."),
        ("INTERMEDIATE", "What does the terraform state list command do?",
         ["deletes all resources", "installs new providers", "formats the code", "shows the resources currently tracked in the state file"], "D",
         "terraform state list prints the addresses of all resources tracked in the state so you can see what Terraform manages."),
        ("INTERMEDIATE", "A resource already exists in AWS and you want Terraform to manage it. Which feature should you use?",
         ["terraform import", "terraform destroy", "terraform plan", "terraform graph"], "A",
         "terraform import brings an existing resource into Terraform's state so it can be managed by the configuration."),
        ("INTERMEDIATE", "Which command checks a Terraform configuration for syntax and internal consistency?",
         ["terraform init", "terraform validate", "terraform apply", "terraform refresh"], "B",
         "terraform validate checks configuration syntax and consistency without connecting to providers or making changes."),
        ("INTERMEDIATE", "In CloudFormation, what is a stack?",
         ["a collection of containers", "a single EC2 instance", "a collection of AWS resources that are created, updated, or deleted as a unit", "a type of template editor"], "C",
         "A CloudFormation stack is the set of resources created from a template, managed together as a single unit."),
        ("INTERMEDIATE", "A resource in Terraform no longer exists in the configuration. What happens on the next apply?",
         ["nothing changes", "the resource is kept forever", "Terraform prints an error", "Terraform plans to destroy the resource that is no longer defined"], "D",
         "When a resource is removed from the configuration, Terraform plans to destroy it unless a lifecycle rule or moved block says otherwise."),
        ("INTERMEDIATE", "You need to create slightly different VPCs for dev and prod from one Terraform module. What should the module accept?",
         ["input variables", "new providers", "extra state files", "hard-coded CIDRs"], "A",
         "Input variables let one module be reused with different values for different environments without copying the code."),
        ("INTERMEDIATE", "Which command sets or updates the value of an input variable for a run?",
         ["terraform plan -var 'env=prod'", "terraform apply -var 'env=prod'", "terraform init -var 'env=prod'", "terraform destroy -var 'env=prod'"], "B",
         "The -var flag on terraform apply supplies or overrides input variable values for that run."),
        ("INTERMEDIATE", "In CloudFormation, what happens when you update a stack's template?",
         ["the stack is deleted", "the stack is duplicated", "CloudFormation computes a change set and applies resource updates", "AWS stops the account"], "C",
         "Updating a template lets CloudFormation create a change set describing resource updates, which can then be applied."),
        ("INTERMEDIATE", "What is the purpose of Terraform remote state storage such as an S3 backend?",
         ["it speeds up apply", "it removes the need for providers", "it makes code prettier", "it provides safe, shared, locked state storage for teams"], "D",
         "A remote backend stores state centrally with locking so multiple engineers can apply changes safely without corrupting the state."),
        ("ADVANCED", "Your team accidentally corrupts the shared remote state. Which action is the safest recovery?",
         ["restore the state from the most recent healthy backup and investigate the cause before re-applying", "run destroy immediately", "delete the state and start over", "keep applying until it works"], "A",
         "A healthy backup of the state is the safest way to restore management, and root-cause analysis prevents the corruption from recurring."),
        ("ADVANCED", "How do you share outputs such as database endpoints between Terraform configurations?",
         ["copy values into emails", "use remote state data sources or outputs from one state in another", "rebuild the database in each config", "hard-code the endpoint"], "B",
         "Remote state data sources and outputs let one configuration read values such as endpoints from another's stored state."),
        ("ADVANCED", "A production apply unexpectedly plans to replace a database instance. What is the most likely cause?",
         ["a variable was not used", "too many providers", "a change in an immutable attribute, forcing replacement", "the state file is missing"], "C",
         "Replacement happens when an immutable attribute changes, because the resource cannot be updated in place and must be recreated."),
        ("ADVANCED", "Which strategy best handles secrets needed by Terraform without storing them in the configuration?",
         ["paste them into .tf files", "hard-code them in variables", "share them in chat", "reference secrets from a secret manager or environment variables"], "D",
         "Referencing secrets from a vault or environment variables keeps them out of version-controlled configuration files."),
        ("ADVANCED", "A state file with the same resource is locked by two engineers. What does remote locking prevent?",
         ["two applies writing conflicting state at the same time", "network downtime", "billing overruns", "slow plans"], "A",
         "Remote locking prevents concurrent applies from corrupting state by ensuring only one write happens at a time."),
        ("ADVANCED", "Your configuration uses the same module for dev and prod but prod must never be destroyed by a stray destroy. What is the strongest guard?",
         ["keep prod resources in the same state as dev", "add prevent_destroy lifecycle rules and protect the prod stack", "delete the prod state", "use only default values"], "B",
         "prevent_destroy lifecycle rules and stack protection give hard guards against accidental destruction of critical environments."),
        ("ADVANCED", "Why do many teams generate CloudFormation templates with a tool rather than writing them by hand?",
         ["tools make them slower", "AWS requires a tool", "code-generation reduces verbosity and errors in large, complex templates", "hand-written templates are illegal"], "C",
         "Generating templates reduces the boilerplate and error rate of large CloudFormation documents and makes them easier to maintain."),
        ("ADVANCED", "During a migration, some resources in a CloudFormation stack must move to a new stack. What is the recommended approach?",
         ["delete everything and recreate", "leave them in place forever", "keep duplicate stacks running", "use resource import and refactor the stacks carefully with change sets"], "D",
         "Resource import plus careful change-set review lets teams move resources between stacks without disrupting them."),
        ("ADVANCED", "Which practice prevents different engineers from applying Terraform with divergent provider versions?",
         ["use version constraints and a lock file committed to the repository", "let everyone install the latest provider", "never pin versions", "remove providers from the config"], "A",
         "Version constraints plus a committed dependency lock file ensure every run uses the same provider versions."),
        ("ADVANCED", "Your terraform apply is slow because a huge module always rebuilds its resources. Which feature helps make this incremental?",
         ["running destroy first", "refactoring to expose only changed inputs and using partial configuration changes", "deleting the state", "using more RAM"], "B",
         "Smaller modules with fewer changed inputs let apply only touch what actually changed, keeping runs incremental and fast."),
    ],
    173: [
        ("BEGINNER", "What is the main purpose of configuration management tools like Ansible and Puppet?",
         ["to keep systems in a desired, consistent state across many machines", "to compile application code", "to design user interfaces", "to print logs"], "A",
         "Configuration management tools enforce a declared desired state so servers stay consistent and reproducible."),
        ("BEGINNER", "Which of the following is a configuration management tool?",
         ["Photoshop", "Ansible", "Apache Kafka", "Nginx"], "B",
         "Ansible is a popular agentless configuration management and automation tool."),
        ("BEGINNER", "What is a playbook in Ansible?",
         ["a virtual machine", "a compiled binary", "a YAML file describing tasks and hosts to configure", "a database schema"], "C",
         "Ansible playbooks are YAML documents that define the hosts and tasks for a configuration run."),
        ("BEGINNER", "What does it mean for a configuration management tool to be idempotent?",
         ["it always changes files", "it requires root access every run", "it only works once", "running the same play repeatedly produces the same end state"], "D",
         "Idempotent operations only make the changes needed to reach the desired state, so repeated runs are safe and consistent."),
        ("BEGINNER", "Which file in an Ansible project lists the hosts that playbooks manage?",
         ["inventory", "playbook", "module", "role"], "A",
         "The Ansible inventory file defines the hosts and groups that playbooks target."),
        ("BEGINNER", "What does the ansible command with the -m flag specify?",
         ["the inventory file", "the module to execute on the hosts", "the playbook to run", "the log directory"], "B",
         "The -m flag selects which module ansible runs ad hoc against hosts."),
        ("BEGINNER", "In Puppet, what is a manifest?",
         ["a backup file", "a network config", "a file that declares the desired state of resources", "a log file"], "C",
         "Puppet manifests declare resources such as packages, files, and services and their desired state."),
        ("BEGINNER", "What is the default state that Ansible assumes when connecting to remote hosts?",
         ["reboot each host first", "install a full agent", "use only FTP", "connect over SSH using the agentless model"], "D",
         "Ansible is agentless by default, connecting over SSH to push and execute tasks on managed hosts."),
        ("BEGINNER", "What does the ping module do in Ansible?",
         ["it verifies that the managed host is reachable and responding", "it checks network speed", "it sends email", "it deletes files"], "A",
         "The ping module tests connectivity to a managed host, confirming it is reachable and able to run Ansible tasks."),
        ("BEGINNER", "What is the purpose of Ansible roles?",
         ["they slow down playbooks", "they organize playbooks, handlers, templates, and variables into reusable structures", "they replace the inventory", "they encrypt all files"], "B",
         "Roles package reusable configuration content so it can be shared and reused across many playbooks and projects."),
        ("INTERMEDIATE", "A playbook fails on a task but the change was already partially applied. What best practice prevents this?",
         ["ignore the error", "run tasks out of order", "make tasks idempotent so re-running completes the work safely", "delete the playbook"], "C",
         "Idempotent tasks can simply be re-run, so a partial failure is recovered by running the playbook again to completion."),
        ("INTERMEDIATE", "You must install a package only if a file exists on the host. Which Ansible feature selects this behavior?",
         ["handlers", "facts", "tags", "conditions with when clauses"], "D",
         "The when clause evaluates a condition so tasks only run when it is true."),
        ("INTERMEDIATE", "What are Ansible handlers used for?",
         ["running actions only when a task reports a change, such as restarting a service", "gathering facts", "defining inventories", "encrypting variables"], "A",
         "Handlers run once at the end of the play only when a notifying task made a change, such as restarting a service."),
        ("INTERMEDIATE", "What do Ansible facts describe?",
         ["the price of hosts", "discovered details about a managed host such as OS and IP addresses", "playbook history", "user passwords"], "B",
         "Facts are automatically gathered details about hosts, such as operating system and network addresses, usable in tasks and templates."),
        ("INTERMEDIATE", "How do you keep secrets such as API keys safe inside an Ansible project?",
         ["write them in plain playbooks", "store them in the inventory", "use ansible-vault to encrypt them", "email them to the team"], "C",
         "ansible-vault encrypts sensitive variables and files so they are not readable as plain text in the repository."),
        ("INTERMEDIATE", "Which module restarts a service on a managed host in Ansible?",
         ["ping", "service", "fetch", "copy"], "D",
         "The service module manages services, including starting, stopping, and restarting them."),
        ("INTERMEDIATE", "You want to apply a playbook only to web servers in the inventory. What should you use?",
         ["a group name in the hosts line of the playbook", "the ping module", "a handler", "ansible-vault"], "A",
         "The hosts line can target a group, so the play only runs against hosts in that group."),
        ("INTERMEDIATE", "What is configuration drift?",
         ["when hardware fails", "when servers slowly deviate from their defined, documented configuration", "when a network cable is unplugged", "when billing changes"], "B",
         "Drift is the gradual difference between a server's actual state and the state defined in configuration management."),
        ("INTERMEDIATE", "Which Ansible feature turns a static list of hosts into a dynamically discovered set?",
         ["handlers", "dynamic inventory", "facts", "roles"], "C",
         "Dynamic inventory plugins query cloud providers or other sources at runtime to build the host list."),
        ("INTERMEDIATE", "What is the recommended way to test an Ansible playbook without touching real servers?",
         ["run it in production", "skip testing", "delete the playbook", "run it against localhost in check mode or a disposable VM"], "D",
         "Check mode and disposable environments let you test playbook behavior safely before applying it to production."),
        ("ADVANCED", "An engineer notices a managed server drifted from its defined state. What does a well-configured CM system do about it?",
         ["it detects drift and can automatically converge the server back to the desired state on the next run", "it ignores the change forever", "it deletes the server", "it emails a monthly report"], "A",
         "Continuous enforcement tools detect differences and bring servers back to the declared state on each scheduled run."),
        ("ADVANCED", "Which approach is best for configuring a fleet of 5,000 servers while keeping secrets secure and runs auditable?",
         ["store passwords in playbooks", "use centralized secrets management, signed code review, and encrypted vaults in the CM pipeline", "configure each server by hand", "copy configs over FTP"], "B",
         "Centralized secret handling, code review, and vault encryption keep a large automation fleet both secure and auditable."),
        ("ADVANCED", "A sensitive value appears in plain text in the Ansible logs. What is the best fix?",
         ["delete the logs", "ignore it", "make the playbook faster", "mark the variable as a secret so values are masked in output and rotate the leaked secret"], "C",
         "Marking sensitive variables as no_log and secret hides their values in output, and the leaked value must still be rotated."),
        ("ADVANCED", "How should configuration management handle a service whose package must differ between Red Hat and Ubuntu hosts?",
         ["install both packages everywhere", "skip configuration", "use a single manual process", "write one task with platform conditions or separate role tasks per family"], "D",
         "Conditionals or per-family role tasks let the same playbook choose the right package and service name for each OS."),
        ("ADVANCED", "Which practice is most important for reliability when a CM run partially fails mid-way through a large playbook?",
         ["design tasks to be idempotent and rerunnable so the run can simply be re-executed", "rebuild the host from scratch", "run the playbook only at midnight", "disable the CM agent"], "A",
         "Idempotent, rerunnable tasks make failed runs recoverable by simply re-running the playbook to completion."),
        ("ADVANCED", "Your team has 50 playbooks with duplicated logic. Which refactor improves maintainability the most?",
         ["keep the duplication", "extract shared logic into reusable roles and shared task files", "delete the extra playbooks", "merge them into one giant playbook"], "B",
         "Roles and shared task files remove duplication, making the configuration base consistent and easier to update."),
        ("ADVANCED", "An urgent security patch must go to all servers immediately. How should the CM system be used safely?",
         ["skip testing and apply everywhere", "deploy the change directly by hand", "roll it out through the CM pipeline in waves with monitoring after each wave", "wait a month"], "C",
         "Wave-based rollout with monitoring balances urgency with safety, catching failures before they reach the whole fleet."),
        ("ADVANCED", "What is the main reason to gather and use facts before running configuration tasks?",
         ["it looks impressive", "it makes playbooks longer", "it speeds up the network", "it lets tasks adapt their behavior to each host's characteristics such as OS and IP"], "D",
         "Facts give playbooks per-host context so tasks can adapt to the actual environment instead of assuming it."),
        ("ADVANCED", "A compliance auditor requires proof that the fleet matches the declared state. What capability does your CM tool need?",
         ["reporting and drift detection that produce audit evidence", "faster provisioning", "fewer servers", "manual sign-offs"], "A",
         "Reporting and drift-detection outputs provide the concrete evidence auditors need that systems match policy."),
        ("ADVANCED", "Which design prevents one badly written playbook from breaking every server at once?",
         ["run everything at the same second", "use a single global playbook", "segment rollout with canary groups and staged environments before broad deployment", "never use CM"], "B",
         "Canaries and staged rollouts contain the blast radius of a bad change before it reaches the whole fleet."),
    ],
    174: [
        ("BEGINNER", "What does CI stand for in CI/CD?",
         ["Continuous Integration", "Continuous Index", "Central Installation", "Code Integrity"], "A",
         "CI stands for Continuous Integration, the practice of frequently merging code changes into a shared branch with automated builds and tests."),
        ("BEGINNER", "What does CD stand for in CI/CD?",
         ["Code Development", "Continuous Deployment", "Central Deployment", "Continuous Data"], "B",
         "CD stands for Continuous Delivery or Continuous Deployment, automating the release of code to environments."),
        ("BEGINNER", "What is a CI/CD pipeline?",
         ["a physical network cable", "a database query", "an automated series of steps that build, test, and deploy code", "a chat channel"], "C",
         "A pipeline chains automated stages such as build, test, and deploy that run whenever code changes."),
        ("BEGINNER", "Which stage typically comes first in a CI/CD pipeline?",
         ["production deploy", "deployment", "deleting logs", "building and testing the code"], "D",
         "Building and testing are the early stages that validate the code before it can be deployed."),
        ("BEGINNER", "What is the main benefit of automated tests in CI?",
         ["catching bugs early before they reach production", "making the code longer", "reducing the need for tests", "slowing the pipeline"], "A",
         "Automated tests in CI catch regressions immediately after a merge, before the change can reach production."),
        ("BEGINNER", "What triggers a CI pipeline in most modern systems?",
         ["a scheduled coffee break", "a push or pull request event on the repository", "a manual reboot", "a weekly backup"], "B",
         "Webhooks on push or pull request events start the pipeline automatically whenever code changes."),
        ("BEGINNER", "Which of the following is an artifact in CI/CD?",
         ["the source code repository", "the built application package produced by a pipeline stage", "the team chat", "the server room temperature"], "C",
         "Artifacts are the outputs of pipeline stages, such as compiled binaries or container images, passed to later stages."),
        ("BEGINNER", "What is the purpose of a build stage in a pipeline?",
         ["to delete the repository", "to send emails", "to slow down releases", "to compile source code into runnable artifacts"], "D",
         "The build stage compiles and packages the source into an artifact that tests and deployments can use."),
        ("BEGINNER", "What is Continuous Delivery, in contrast to Continuous Deployment?",
         ["code is always in a releasable state but releases to production may require manual approval", "every change goes to production with no tests", "deployments are always manual forever", "there are no pipelines"], "A",
         "Continuous Delivery keeps every change releasable, with the final production release gated by an approval step."),
        ("BEGINNER", "Which tool is commonly used as a CI/CD server?",
         ["VLC Media Player", "Jenkins", "Microsoft Word", "Adobe Photoshop"], "B",
         "Jenkins is a widely used open-source CI/CD server that runs pipeline jobs."),
        ("INTERMEDIATE", "A build is flaky and passes only sometimes. What is the best practice?",
         ["ignore it since it sometimes passes", "rerun the pipeline until it passes", "treat flaky tests as failures and fix the root cause", "delete the test"], "C",
         "Flaky tests destroy pipeline trust, so they must be fixed at the root cause rather than retried or ignored."),
        ("INTERMEDIATE", "Which practice makes CI faster while still validating every change?",
         ["run all builds sequentially on one agent", "skip tests", "build only at the end of the month", "cancel builds for outdated commits and use caching and parallelism"], "D",
         "Cancelling superseded builds, caching dependencies, and running stages in parallel cut CI time without losing coverage."),
        ("INTERMEDIATE", "Your pipeline deploys directly to production on every merge. What is missing before you can claim Continuous Delivery?",
         ["a manual approval gate and reliable release process", "a bigger server", "more commits", "a faster network"], "A",
         "Continuous Delivery includes a release gate, so production deployment is an approved step rather than automatic."),
        ("INTERMEDIATE", "A change passes tests in CI but breaks production because environments differ. What fixes this?",
         ["deploy faster", "use parity between environments, e.g., identical container images and configuration", "skip staging", "test only locally"], "B",
         "Environment parity using identical images and config removes the differences that cause changes to pass in CI but fail in production."),
        ("INTERMEDIATE", "Why should secrets be injected into pipeline jobs rather than committed to the repository?",
         ["they are faster that way", "they are easier to type", "committed secrets leak into version history and are accessible to anyone with repo access", "the pipeline refuses to run"], "C",
         "Storing secrets in the pipeline's secret store keeps them out of version control and limits who can access them."),
        ("INTERMEDIATE", "Which approach ensures a container image is safe to deploy?",
         ["skip scanning", "deploy without review", "use any public image", "scan images for vulnerabilities in the pipeline before release"], "D",
         "Scanning images in the pipeline catches known vulnerabilities before the image is ever deployed."),
        ("INTERMEDIATE", "A deployment succeeds but monitoring shows errors afterward. What is the correct next step?",
         ["automatically roll back to the last healthy version", "ignore the errors", "delete the logs", "restart the whole cluster blindly"], "A",
         "Automated rollback returns the service to the last known-good version when a release shows error spikes."),
        ("INTERMEDIATE", "Which feature lets a new version receive a fraction of traffic before full release?",
         ["a full cutover", "canary release or progressive delivery", "a rollback", "a cache flush"], "B",
         "Canary releases send a small fraction of traffic to the new version so problems surface before full rollout."),
        ("INTERMEDIATE", "Why is it important that pipeline stages run in a clean, isolated environment?",
         ["it is cheaper", "it looks professional", "it prevents issues caused by leftover state or hidden dependencies on the runner", "it makes logs shorter"], "C",
         "Clean, isolated runners ensure builds are reproducible and not affected by stale state from previous jobs."),
        ("INTERMEDIATE", "What is a build cache used for in a pipeline?",
         ["to hide build errors", "to store old releases forever", "to bypass security", "to reuse unchanged dependencies and intermediate outputs so subsequent builds are faster"], "D",
         "Caching unchanged dependencies and intermediates speeds up builds by avoiding redundant work."),
        ("ADVANCED", "A critical production release was deployed with no way to verify it worked. What is the most important capability to add?",
         ["deployment monitoring with health checks, metrics, and automated rollback", "a larger team", "more frequent commits", "a faster build server"], "A",
         "Monitoring and health checks provide the feedback loop that proves a release is working or triggers an automated rollback."),
        ("ADVANCED", "Your pipeline builds the same code twice with different results in different environments. Which practice fixes reproducibility?",
         ["run builds on developer laptops", "use containerized, pinned build environments so every run is identical", "build only at night", "delete the lock file"], "B",
         "Containerized build environments with pinned dependency versions make every pipeline run deterministic and reproducible."),
        ("ADVANCED", "Which approach safely allows frequent releases with zero-downtime for a database-backed application?",
         ["deploy the code and schema in one atomic step", "stop the database during every release", "use backward-compatible changes and expand-contract migrations that support rolling deploys", "release only once a year"], "C",
         "Backward-compatible schema changes and expand-contract migrations let old and new code run together during a rolling release."),
        ("ADVANCED", "A merge goes straight through CI to production because the pipeline has no security checks. Which control should be added first?",
         ["a faster runner", "a prettier dashboard", "more tests", "a security gate such as SAST, dependency and image scanning blocking merges"], "D",
         "Security gates block vulnerable code from reaching production by failing the pipeline during CI."),
        ("ADVANCED", "You must release a hotfix without skipping the CI quality gates. How should the pipeline be configured?",
         ["allow the hotfix branch to run the same required stages but with expedited review and a bypassable but audited approval", "disable all tests for the hotfix", "deploy directly with no tracking", "merge without building"], "A",
         "Fast-track hotfixes still run required checks, with expedited review, so speed does not sacrifice quality or auditability."),
        ("ADVANCED", "How does CI/CD reduce the risk of a large release failing?",
         ["it hides the changes", "it ships small, frequent changes so failures are small, isolated, and quick to diagnose", "it merges everything at once", "it removes all tests"], "B",
         "Small frequent releases reduce blast radius because each change is minimal and its failure easy to isolate and revert."),
        ("ADVANCED", "A compliance requirement says every production change must be traceable to a code change. How does a pipeline support this?",
         ["by deleting old builds", "by speeding up builds", "by capturing the commit, build, and artifact metadata for every deployment", "by running builds only in production"], "C",
         "Recording commit-to-artifact-to-deployment metadata gives full traceability for every production change."),
        ("ADVANCED", "What is the purpose of a deployment freeze during high-traffic periods?",
         ["to make developers work harder", "to save money", "to reduce network traffic", "to reduce risk by avoiding changes when the cost of failure is highest"], "D",
         "Freezes avoid risky changes during critical windows, shifting releases to lower-risk times."),
        ("ADVANCED", "How do you safely test a new feature against real users without exposing it to everyone?",
         ["use feature flags to enable the feature for a subset of users", "release it to everyone", "disable monitoring", "delete the feature"], "A",
         "Feature flags let teams toggle features per user or group, enabling gradual rollout and instant disablement."),
        ("ADVANCED", "A release broke the API and support could not identify the failing version quickly. Which improvement prevents this?",
         ["release less often", "tag each deployment with its version and correlate errors to release versions", "disable error logs", "use a single long-running process"], "B",
         "Version-tagged deployments and release correlation let teams instantly map an incident back to the release that caused it."),
    ],
    175: [
        ("BEGINNER", "What does SLO stand for in SRE practice?",
         ["Service Level Objective", "Service Logging Operation", "System Level Output", "Secure Login Operation"], "A",
         "SLO stands for Service Level Objective, a target for a service's availability or performance."),
        ("BEGINNER", "What is a Service Level Indicator (SLI)?",
         ["a type of firewall", "a measurable metric that reflects a service's performance or reliability", "a backup policy", "a team role"], "B",
         "An SLI is a concrete, measurable metric such as request success rate or latency that indicates how the service is doing."),
        ("BEGINNER", "What is the difference between an SLA and an SLO?",
         ["they are the same thing", "an SLA is internal only", "an SLO is an internal target while an SLA is a contractual commitment with external consequences", "an SLO is a budget"], "C",
         "SLOs are internal engineering targets, whereas SLAs are contractual commitments to customers that may carry penalties."),
        ("BEGINNER", "What is an error budget?",
         ["the amount of money a company earns", "the number of engineers on call", "the time a service is down", "the acceptable amount of unavailability a service may have within an SLO window"], "D",
         "The error budget is the amount of unreliability allowed by an SLO, typically 100% minus the SLO percentage."),
        ("BEGINNER", "What does MTTR stand for?",
         ["Mean Time To Recovery", "Maximum Time To Release", "Minimum Time To Restart", "Maintenance Time To Repair"], "A",
         "MTTR is Mean Time To Recovery, the average time it takes to restore service after a failure."),
        ("BEGINNER", "What does MTBF measure?",
         ["the number of users", "the average time between two consecutive failures", "the size of the database", "the cost of the service"], "B",
         "MTBF is Mean Time Between Failures, the average uptime between failures of a system."),
        ("BEGINNER", "What is a runbook?",
         ["a financial report", "a network diagram", "a documented set of procedures for handling operations tasks or incidents", "a user manual for end customers"], "C",
         "Runbooks document the steps operators follow to handle common tasks and incidents consistently."),
        ("BEGINNER", "What is on-call rotation in SRE?",
         ["a daily meeting", "a backup disk rotation", "a load-balancing algorithm", "a schedule where engineers take turns responding to alerts and incidents"], "D",
         "On-call rotation assigns engineers to respond to alerts and incidents in shifts, so coverage exists around the clock."),
        ("BEGINNER", "What is a blameless postmortem?",
         ["a review of an incident that focuses on system and process improvements instead of blaming people", "a report that fires an engineer", "a way to hide mistakes", "a list of user complaints"], "A",
         "A blameless postmortem analyzes what happened and how to improve, recognizing that complex systems fail in complex ways."),
        ("BEGINNER", "What is the goal of redundancy in system design?",
         ["to slow the system down", "to eliminate single points of failure so the system survives component failures", "to increase latency", "to reduce the number of servers"], "B",
         "Redundancy provides backup components or paths so that a failure in one part does not take the whole system down."),
        ("INTERMEDIATE", "A service has an SLO of 99.9% availability for one month. What is its error budget for that month?",
         ["10 days", "1 day", "about 43 minutes", "about 8 hours"], "C",
         "0.1% of a 30-day month is roughly 43 minutes, which is the allowed downtime before the SLO is breached."),
        ("INTERMEDIATE", "The team spends the entire month on feature work and uses up all its error budget. What should happen next?",
         ["ignore it and keep shipping", "ship more features", "delete the SLO", "freeze risky changes and focus on reliability until the budget recovers"], "D",
         "When the error budget is exhausted, SRE practice says to halt risky changes and invest in reliability to protect users."),
        ("INTERMEDIATE", "Which alert is most useful for operators during an incident?",
         ["an alert with a clear title, severity, and runbook link", "an alert with only a metric number", "an alert sent to everyone in the company", "an alert that fires on every tiny fluctuation"], "A",
         "Actionable alerts include context such as severity and a runbook, so on-call engineers can respond quickly."),
        ("INTERMEDIATE", "A system cannot reach its availability SLO because a single database is a single point of failure. What is the most direct fix?",
         ["keep the single database", "add replication or failover so the database is no longer a single point of failure", "reboot the database", "reduce the SLO"], "B",
         "Replication and failover remove the database as a single point of failure, improving achievable availability."),
        ("INTERMEDIATE", "What is the purpose of load testing a service before a major release?",
         ["to make the release slower", "to reduce costs", "to verify the service can handle expected and peak traffic without failing", "to make the team busier"], "C",
         "Load testing confirms the service stays within its SLO under expected and peak load before users depend on it."),
        ("INTERMEDIATE", "What is a capacity plan in SRE?",
         ["a budget for servers", "a list of engineers", "a backup schedule", "a process to ensure enough capacity exists to handle forecast demand while keeping costs reasonable"], "D",
         "Capacity planning matches predicted demand to infrastructure so the service does not run out of resources."),
        ("INTERMEDIATE", "Which metric best indicates whether users can successfully use a service?",
         ["the ratio of successful requests to total requests (success rate)", "the total number of servers", "the number of alerts", "the size of the codebase"], "A",
         "Success rate is a direct SLI of user experience, showing the fraction of requests that succeed."),
        ("INTERMEDIATE", "Why do SRE teams define SLOs instead of just aiming for 100% availability?",
         ["100% is impossible to measure", "100% availability is impractical and extremely costly, while an SLO sets a realistic target and an error budget", "customers always want less", "SLOs make the team smaller"], "B",
         "Realistic SLOs trade cost against reliability and give teams a defined target and error budget instead of chasing impossible perfection."),
        ("INTERMEDIATE", "During an incident, what is the primary job of the incident commander?",
         ["to write the postmortem", "to fix the code", "to coordinate the response, assign tasks, and communicate status", "to answer customer emails"], "C",
         "The incident commander owns coordination, task assignment, and communication so responders can focus on fixing the issue."),
        ("INTERMEDIATE", "A team measures only error rates but not latency. What part of reliability is missing from its SLIs?",
         ["cost", "security", "team size", "performance, since slow responses are also user-facing failures"], "D",
         "Latency is part of reliability because very slow responses are experienced by users as failures even if they succeed."),
        ("ADVANCED", "A payment service has a 99.95% SLO. Which decision is most consistent with SRE practice?",
         ["spend error budget on controlled experiments and release velocity while protecting the SLO with gates", "always aim for 100%", "ignore the SLO during sales season", "remove monitoring"], "A",
         "The error budget allows deliberate risk-taking within the defined budget, balancing reliability against feature velocity."),
        ("ADVANCED", "During an incident, on-call engineers cannot identify the root cause because dashboards are disorganized. What investment addresses this?",
         ["more servers", "improved observability with correlated metrics, logs, and traces", "a bigger team", "longer shifts"], "B",
         "Correlated metrics, logs, and traces give engineers the signal needed to find root causes quickly during incidents."),
        ("ADVANCED", "Your on-call engineers are constantly woken by alerts that never need action. Which SLO-relevant practice fixes this?",
         ["turn off all alerts", "add more alerts", "review alert noise, silence or tune non-actionable alerts, and keep only those tied to SLOs", "page the manager instead"], "C",
         "Reducing alert noise by tuning or removing non-actionable alerts keeps on-call effective and alerts meaningful."),
        ("ADVANCED", "A multi-region service still fails a 99.99% SLO because failover is manual and slow. What automation improves this?",
         ["manual runbooks", "weekly meetings", "larger disks", "automated failover and health-based traffic steering"], "D",
         "Automated failover and traffic steering respond to failures in seconds rather than the minutes a manual process needs."),
        ("ADVANCED", "A team must choose metrics for a new service. Which set forms a good SLI hierarchy?",
         ["availability, latency, throughput, and durability for the critical user journeys", "only server CPU usage", "the number of commits", "the size of the database"], "A",
         "Good SLIs are based on the user's critical journey, covering availability, latency, throughput, and durability where relevant."),
        ("ADVANCED", "Your SLO is breached every month in a recurring pattern. What is the most effective response?",
         ["delete the SLO", "treat the root cause as a reliability investment with a dedicated improvement project", "add more on-call shifts", "accept it and move on"], "B",
         "Recurring breaches show a systemic root cause that needs dedicated reliability work rather than more firefighting."),
        ("ADVANCED", "A new feature is risky but the team wants to ship it. How does the error budget inform this decision?",
         ["ship it no matter what", "refuse everything", "if the error budget is healthy, ship it while protecting the SLO; if exhausted, delay it", "ask the CEO"], "C",
         "A healthy error budget signals room for risk, so the feature can ship, while an exhausted budget says reliability first."),
        ("ADVANCED", "Which measure best indicates whether a change to the system is safe to roll out gradually?",
         ["releasing to everyone at once", "checking disk space", "waiting a day", "comparing error rates and latency between the canary and baseline before widening the rollout"], "D",
         "Canary comparison against baseline metrics proves the new version meets its SLO before traffic is widened."),
        ("ADVANCED", "After a major outage, the postmortem finds the incident was caused by a misconfigured change that bypassed review. Which follow-up is most in line with SRE?",
         ["add automated validation and a change review gate so the mistake cannot recur", "blame the engineer who made the change", "rewrite the runbook only", "hold no meetings"], "A",
         "Blameless follow-ups focus on automated controls and process changes that prevent the failure from recurring."),
        ("ADVANCED", "Your reliability budget is constant but the service grows tenfold in traffic. What must be revisited to keep SLOs meaningful?",
         ["the team's office hours", "capacity planning and SLO targets, since cost and risk scales with traffic", "the chat tool", "the company name"], "B",
         "Growth in traffic changes the economics of reliability, so capacity plans and SLO trade-offs must be recalculated."),
    ],
}
