# -*- coding: utf-8 -*-
"""
Question bank for subject 42: PHY101 - Applied Physics & Basic Electronics.
Category: Core Computer Science & Emerging Technologies.

Topics:
  206: Semiconductors & Diodes
  207: Transistors & Amplifiers
  208: Digital Logic & Number Systems
  209: Sequential Circuits & Memories
  210: Microprocessor Fundamentals

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    206: [
        ("BEGINNER", "What is the majority charge carrier in an n-type semiconductor?",
         ["Electrons", "Holes", "Ions", "Protons"], "A",
         "Doping with pentavalent impurities such as phosphorus donates free electrons, which become the majority carriers."),
        ("BEGINNER", "What type of impurity creates holes as majority carriers in a semiconductor?",
         ["Pentavalent", "Trivalent", "Tetravalent", "Hexavalent"], "B",
         "Trivalent impurities such as boron accept electrons and leave holes, producing p-type material."),
        ("BEGINNER", "Which element is most commonly used as the base semiconductor material in electronics?",
         ["Copper", "Silicon", "Germanium only", "Gallium"], "B",
         "Silicon dominates the industry because of its abundance, stable oxide, and good thermal properties."),
        ("BEGINNER", "What is the energy gap in a semiconductor?",
         ["The region between two conductors", "The forbidden energy band between the valence and conduction bands", "The space between two atoms in the lattice", "The width of the depletion layer"], "B",
         "The energy gap is the forbidden band of energies that electrons must cross to move from the valence to the conduction band."),
        ("BEGINNER", "What is a p-n junction?",
         ["A connection of two wires", "The boundary formed between p-type and n-type semiconductor regions", "A resistor made of two materials", "A battery terminal"], "B",
         "A p-n junction is formed where p-type and n-type regions meet in a single crystal."),
        ("BEGINNER", "When a diode is forward biased, which terminal is connected to the positive supply?",
         ["Cathode", "Anode", "Base", "Emitter"], "B",
         "Forward bias connects the anode to positive so the barrier is reduced and current flows."),
        ("BEGINNER", "In reverse bias, what happens to the depletion region?",
         ["It disappears", "It shrinks", "It widens", "It conducts"], "C",
         "Reverse bias pulls charge carriers away from the junction, widening the depletion region and blocking current."),
        ("BEGINNER", "What is the typical voltage drop of a forward-biased silicon diode?",
         ["0.3 V", "0.7 V", "1.4 V", "2.0 V"], "B",
         "Silicon diodes have a forward voltage drop of about 0.7 V; germanium is about 0.3 V."),
        ("BEGINNER", "Which diode characteristic shows the relationship between voltage and current?",
         ["Load line", "Transfer characteristic", "V-I characteristic", "Bode plot"], "C",
         "The V-I characteristic curve plots diode current against the applied voltage."),
        ("BEGINNER", "Which of the following is an application of a diode?",
         ["Rectification", "Amplification", "Oscillation of radio waves", "Magnetic storage"], "A",
         "Diodes convert alternating current into direct current, which is rectification."),
        ("INTERMEDIATE", "A half-wave rectifier passes which part of the AC input?",
         ["Both half cycles", "Only the positive half cycle", "Only the negative half cycle", "The zero crossings only"], "B",
         "A single diode conducts during only one half cycle, so a half-wave rectifier passes one half of the AC waveform."),
        ("INTERMEDIATE", "What is the peak inverse voltage (PIV) rating of a diode?",
         ["The maximum forward current", "The maximum reverse voltage a diode can withstand without breakdown", "The power dissipated in the diode", "The switching frequency limit"], "B",
         "PIV is the maximum reverse voltage the diode can tolerate; exceeding it causes breakdown."),
        ("INTERMEDIATE", "A full-wave bridge rectifier uses how many diodes?",
         ["One", "Two", "Four", "Eight"], "C",
         "A bridge rectifier uses four diodes arranged so both half cycles produce output in the same direction."),
        ("INTERMEDIATE", "What is the ripple in a rectifier output?",
         ["A constant DC voltage", "The residual AC variation superimposed on the DC output", "The loss due to heat", "The forward voltage drop"], "B",
         "Ripple is the small AC fluctuation left after rectification and filtering of the DC output."),
        ("INTERMEDIATE", "A capacitor filter across the rectifier output serves which purpose?",
         ["To reduce ripple", "To increase frequency", "To rectify the signal", "To block DC"], "A",
         "The capacitor charges to the peak voltage and discharges between peaks, smoothing the output and reducing ripple."),
        ("INTERMEDIATE", "What is the breakdown voltage of a diode?",
         ["The forward conduction voltage", "The reverse voltage at which reverse current rises sharply", "The knee voltage of the curve", "The saturation current"], "B",
         "Breakdown is the reverse voltage where the diode suddenly conducts a large reverse current."),
        ("INTERMEDIATE", "A Zener diode is designed to operate in which region?",
         ["Forward conduction region", "Reverse breakdown region", "Cut-off region", "Saturation region"], "B",
         "Zener diodes are doped to break down at a precise, stable voltage and are used as voltage regulators."),
        ("INTERMEDIATE", "What does a light-emitting diode (LED) produce when forward biased?",
         ["Radio waves", "Heat only", "Light due to recombination of carriers", "X-rays"], "C",
         "Electrons recombine with holes in the junction and release energy as photons, producing light."),
        ("INTERMEDIATE", "A photodiode operates when illuminated; its resistance typically:",
         ["Increases with light", "Decreases with light", "Remains constant", "Becomes infinite"], "B",
         "Light generates electron-hole pairs that increase conductivity, so resistance falls with illumination."),
        ("INTERMEDIATE", "In a silicon diode, the knee voltage is approximately:",
         ["0.1 V", "0.7 V", "3.0 V", "6.8 V"], "B",
         "The knee voltage of silicon is about 0.7 V, where forward current begins to rise rapidly."),
        ("ADVANCED", "Why does the reverse saturation current of a diode approximately double for every 10 C rise in temperature?",
         ["Because resistance falls with temperature", "Because the number of thermally generated minority carriers increases exponentially with temperature", "Because the band gap widens", "Because the diode becomes forward biased"], "B",
         "Thermally generated minority carriers increase roughly exponentially with temperature, doubling reverse saturation current for about every 10 C rise."),
        ("ADVANCED", "Which type of diode is used as a variable capacitor in tuning circuits?",
         ["Zener diode", "Schottky diode", "Varactor diode", "Tunnel diode"], "C",
         "A varactor diode's junction capacitance varies with the reverse voltage applied, allowing electronic tuning."),
        ("ADVANCED", "What is a characteristic of a Schottky diode compared with a standard p-n diode?",
         ["Higher forward drop and slower switching", "Lower forward drop and faster switching", "Higher breakdown voltage only", "It cannot rectify"], "B",
         "The metal-semiconductor junction of a Schottky diode has a low forward drop and very fast switching."),
        ("ADVANCED", "In a tunnel diode, the current decreases as voltage increases over a certain range. This is called:",
         ["Negative resistance region", "Saturation region", "Breakdown region", "Cut-off region"], "A",
         "Quantum tunnelling produces a region where an increase in voltage reduces current, which is negative resistance."),
        ("ADVANCED", "A bridge rectifier output has a peak of 20 V. What is the approximate DC voltage with negligible ripple after full-wave rectification?",
         ["5 V", "10 V", "12.7 V", "20 V"], "C",
         "The average DC value of a full-wave rectified sine is 2*Vpk/pi = 2*20/3.14 = 12.7 V."),
        ("ADVANCED", "Why is silicon preferred over germanium for most power rectifier applications?",
         ["It has a narrower band gap", "It has lower leakage current and higher temperature tolerance", "It has fewer carriers", "It is cheaper to dope"], "B",
         "Silicon's wider band gap gives much lower leakage current and higher operating temperature limits than germanium."),
        ("ADVANCED", "What limits the maximum reverse recovery time in high-speed switching diodes?",
         ["The depletion width", "The storage of minority charge carriers in the junction", "The package size", "The knee voltage"], "B",
         "Stored minority carriers must recombine before the diode stops conducting, and this storage time sets the reverse recovery limit."),
        ("ADVANCED", "In a zener regulator, the series resistor mainly:",
         ["Limits the zener current to a safe value", "Doubles the output voltage", "Rectifies the input", "Filters the ripple completely"], "A",
         "The series resistor drops the excess voltage and limits current so the zener operates within its safe range."),
        ("ADVANCED", "A diode is used to clamp a signal. What is a common clamping application?",
         ["Shifting a waveform's DC level", "Amplifying weak signals", "Generating oscillations", "Storing charge"], "A",
         "Clampers shift a waveform up or down by adding a DC level, useful for protecting inputs or restoring DC offsets."),
        ("ADVANCED", "Which factor determines the maximum safe forward current of a diode?",
         ["The color of the package", "The power dissipation limit and thermal resistance", "The number of pins", "The cathode marking"], "B",
         "The allowable power dissipation divided by the thermal resistance sets the maximum safe forward current."),
    ],
    207: [
        ("BEGINNER", "What are the three terminals of a bipolar junction transistor (BJT)?",
         ["Anode, cathode, gate", "Emitter, base, collector", "Source, drain, gate", "Base, source, drain"], "B",
         "A BJT has three terminals: the emitter, base, and collector."),
        ("BEGINNER", "Which transistor type uses both electrons and holes as carriers?",
         ["Field-effect transistor", "Bipolar junction transistor", "Unijunction transistor", "Phototransistor"], "B",
         "BJT operation involves both electron and hole current, hence 'bipolar'."),
        ("BEGINNER", "In an NPN transistor, the majority carriers flowing from emitter to collector are:",
         ["Holes", "Electrons", "Ions", "Protons"], "B",
         "In an NPN transistor electrons are injected from the emitter and collected by the collector."),
        ("BEGINNER", "Which is the control terminal of a BJT?",
         ["Collector", "Emitter", "Base", "Source"], "C",
         "A small base current controls the much larger collector current in a BJT."),
        ("BEGINNER", "What is the minimum number of terminals a field-effect transistor has?",
         ["Two", "Three", "Four", "Five"], "B",
         "A FET has three terminals: gate, drain, and source."),
        ("BEGINNER", "In a FET, the gate-to-channel voltage controls which current?",
         ["Base current", "Emitter current", "Drain current", "Gate current"], "C",
         "The gate voltage modulates the channel resistance, which controls the drain current."),
        ("BEGINNER", "Which FET terminal is analogous to the emitter of a BJT?",
         ["Gate", "Drain", "Source", "Base"], "C",
         "The source supplies charge carriers just as the emitter does in a BJT."),
        ("BEGINNER", "A common-emitter amplifier provides:",
         ["No voltage gain", "Voltage gain with phase inversion", "Only current gain", "Unity gain"], "B",
         "The common-emitter configuration gives both voltage and current gain and inverts the signal 180 degrees."),
        ("BEGINNER", "What is the function of the coupling capacitor in an amplifier stage?",
         ["To block DC while passing the AC signal", "To increase the DC supply", "To short the output", "To store electrical energy only"], "A",
         "Coupling capacitors isolate the DC bias of stages while letting the AC signal pass between them."),
        ("BEGINNER", "Which operating region is used for linear amplification in a BJT?",
         ["Cut-off", "Saturation", "Active region", "Breakdown"], "C",
         "In the active region the transistor operates as a linear amplifier because collector current follows base current."),
        ("INTERMEDIATE", "In an NPN BJT amplifier, an increase in base current causes the collector current to:",
         ["Decrease", "Increase proportionally", "Stay constant", "Reverse direction"], "B",
         "The collector current is the base current multiplied by the current gain beta, so it rises proportionally."),
        ("INTERMEDIATE", "The current gain of a common-emitter configuration is denoted by:",
         ["Alpha", "Beta", "Gamma", "Delta"], "B",
         "Beta is the ratio of collector current to base current in common-emitter configuration."),
        ("INTERMEDIATE", "If a BJT has beta = 100 and base current is 20 microamperes, what is the collector current?",
         ["0.2 mA", "2 mA", "20 mA", "200 mA"], "B",
         "Ic = beta * Ib = 100 * 20 uA = 2000 uA = 2 mA."),
        ("INTERMEDIATE", "The input impedance of a common-emitter amplifier is:",
         ["Very low", "Moderate, around a few kilohms", "Very high like a FET", "Infinite"], "B",
         "A CE stage has moderate input impedance of a few kilohms determined mainly by the base bias resistors."),
        ("INTERMEDIATE", "Which amplifier configuration has no voltage inversion and near-unity voltage gain?",
         ["Common emitter", "Common base", "Emitter follower (common collector)", "Differential pair only"], "C",
         "The common-collector or emitter follower has voltage gain near unity and no phase inversion."),
        ("INTERMEDIATE", "What is the main advantage of a common-base amplifier?",
         ["Very high voltage gain", "Low input impedance and good high-frequency response", "Very high input impedance", "Current gain greater than one"], "B",
         "The common-base stage has low input impedance and excellent high-frequency performance."),
        ("INTERMEDIATE", "Biasing of a transistor is required mainly to:",
         ["Set a stable operating point in the active region", "Reduce the number of pins", "Increase the supply voltage", "Convert it into a diode"], "A",
         "Biasing establishes a stable Q-point in the active region so the transistor amplifies without distortion."),
        ("INTERMEDIATE", "What happens to the Q-point if the operating temperature rises?",
         ["It stays fixed", "It shifts due to increased leakage current", "It goes to cut-off permanently", "The transistor becomes a diode"], "B",
         "Leakage current grows with temperature and shifts the Q-point, which is why stabilized bias circuits are used."),
        ("INTERMEDIATE", "A transistor acting as a switch in saturation has:",
         ["High collector-emitter voltage", "Very low collector-emitter voltage", "Infinite resistance", "No current flow"], "B",
         "In saturation the transistor is fully on, giving a very low collector-emitter saturation voltage."),
        ("INTERMEDIATE", "What is the effect of connecting a large emitter capacitor in a CE amplifier?",
         ["It blocks the AC signal", "It bypasses the emitter resistor, increasing voltage gain", "It shorts the collector", "It reduces beta"], "B",
         "The bypass capacitor removes the AC feedback of the emitter resistor, restoring full voltage gain."),
        ("ADVANCED", "Why does a common-source MOSFET amplifier offer much higher input impedance than a common-emitter BJT amplifier?",
         ["MOSFET gate is separated by an insulating oxide layer", "MOSFETs have a larger beta", "The source terminal is grounded", "MOSFETs operate in saturation"], "A",
         "The gate of a MOSFET is insulated from the channel by a thin oxide, so almost no DC current flows into the gate."),
        ("ADVANCED", "In a differential amplifier, what is the common-mode rejection ratio (CMRR)?",
         ["The ratio of differential gain to common-mode gain", "The ratio of base current to collector current", "The supply voltage divided by output voltage", "The ratio of bandwidth to gain"], "A",
         "CMRR = Adiff/Acm, and a high value means the amplifier rejects common-mode noise well."),
        ("ADVANCED", "Which feedback type reduces both gain and distortion while increasing bandwidth in an amplifier?",
         ["Positive feedback", "Negative feedback", "Open loop", "Regenerative feedback"], "B",
         "Negative feedback trades gain for lower distortion, wider bandwidth, and improved stability."),
        ("ADVANCED", "A Darlington pair is formed by two transistors and provides:",
         ["Very high current gain", "Very low current gain", "Higher cutoff frequency", "Rectification"], "A",
         "Two transistors connected as a Darlington pair multiply their betas, giving very high overall current gain."),
        ("ADVANCED", "What is the principal cause of distortion in a poorly biased class-B push-pull amplifier?",
         ["Saturation clipping", "Crossover distortion at the zero crossing", "Overheating", "Noise from the power supply"], "B",
         "Each transistor conducts for only half the cycle, so at the crossover both are off and distortion occurs."),
        ("ADVANCED", "In MOSFET amplifier design, the term 'saturation region' for a MOSFET corresponds to which BJT region?",
         ["Cut-off", "Active region", "Saturation", "Breakdown"], "B",
         "The MOSFET saturation region, where drain current is constant for drain voltage, is analogous to the BJT active region."),
        ("ADVANCED", "The -3 dB bandwidth of an amplifier is the frequency where the gain:",
         ["Becomes infinite", "Drops to 70.7 percent of the mid-band gain", "Becomes negative", "Reaches its maximum"], "B",
         "At the cutoff frequencies the power gain drops to half (about -3 dB), so voltage gain falls to 0.707 of mid-band."),
        ("ADVANCED", "Why does an emitter-degeneration resistor improve amplifier stability?",
         ["It increases gain without limit", "It provides negative feedback that stabilizes the Q-point against temperature and beta changes", "It removes the collector resistor", "It converts the stage to common base"], "B",
         "The emitter resistor senses output current and feeds back negatively, stabilizing the operating point."),
        ("ADVANCED", "In a Class-AB push-pull amplifier, the two transistors are biased slightly into conduction to:",
         ["Eliminate crossover distortion", "Increase gain to infinity", "Reduce supply voltage", "Convert to single-ended operation"], "A",
         "A small idle bias keeps both devices conducting near zero crossing, removing crossover distortion."),
        ("ADVANCED", "A cascode amplifier uses a common-emitter stage followed by a common-base stage to:",
         ["Reduce gain", "Improve isolation and high-frequency bandwidth", "Double the input impedance", "Eliminate the power supply"], "B",
         "The common-base stage isolates the collector of the CE stage from the load, reducing the Miller effect and improving bandwidth."),
    ],
    208: [
        ("BEGINNER", "In the binary number system, how many distinct digits are used?",
         ["Two", "Eight", "Ten", "Sixteen"], "A",
         "Binary uses only the digits 0 and 1, so it is a base-2 system."),
        ("BEGINNER", "What is the decimal value of the binary number 1010?",
         ["8", "10", "12", "14"], "B",
         "1010 in binary is 8 + 0 + 2 + 0 = 10 in decimal."),
        ("BEGINNER", "The hexadecimal number system has a base of:",
         ["8", "10", "16", "2"], "C",
         "Hexadecimal is a base-16 system using digits 0-9 and letters A-F."),
        ("BEGINNER", "Which logic gate produces an output of 1 only when all inputs are 1?",
         ["OR gate", "AND gate", "NOT gate", "XOR gate"], "B",
         "The AND gate output is high only when every input is high."),
        ("BEGINNER", "Which logic gate inverts its input?",
         ["AND gate", "OR gate", "NOT gate", "NAND gate"], "C",
         "The NOT gate, or inverter, outputs the complement of its single input."),
        ("BEGINNER", "The OR gate outputs 1 when:",
         ["At least one input is 1", "All inputs are 0", "Exactly one input is 1 and the other is 0", "The inputs are equal"], "A",
         "The OR gate produces 1 whenever any of its inputs is 1."),
        ("BEGINNER", "What is the decimal equivalent of binary 1111?",
         ["8", "12", "15", "16"], "C",
         "1111 = 8 + 4 + 2 + 1 = 15."),
        ("BEGINNER", "Which gate is the complement of the AND gate?",
         ["OR gate", "XOR gate", "NAND gate", "NOR gate"], "C",
         "The NAND gate is an AND gate followed by a NOT, so it outputs the inversion of AND."),
        ("BEGINNER", "How many bits are in a byte?",
         ["4", "8", "16", "32"], "B",
         "A byte consists of exactly 8 bits."),
        ("BEGINNER", "The Boolean expression for an XOR gate is:",
         ["A AND B", "A OR B", "A XOR B", "NOT A"], "C",
         "XOR output is 1 when the inputs differ, expressed as A XOR B."),
        ("INTERMEDIATE", "What is the 2's complement representation of the number -5 using 4 bits?",
         ["0101", "1011", "1001", "1101"], "B",
         "5 is 0101; invert to 1010 and add 1 to get 1011, which is -5 in 2's complement."),
        ("INTERMEDIATE", "Which adder circuit produces both sum and carry outputs?",
         ["Half adder", "Demultiplexer", "Decoder", "Encoder"], "A",
         "A half adder adds two bits and produces a sum and a carry output."),
        ("INTERMEDIATE", "How many bits are needed to represent 8 distinct values?",
         ["2", "3", "4", "8"], "B",
         "2^3 = 8, so 3 bits can represent 8 distinct values."),
        ("INTERMEDIATE", "The 1's complement of the binary number 1100 is:",
         ["0011", "1101", "0100", "1011"], "A",
         "Inverting each bit of 1100 gives 0011."),
        ("INTERMEDIATE", "A decoder with 3 inputs can produce a maximum of how many outputs?",
         ["3", "8", "4", "16"], "B",
         "A 3-to-8 decoder activates one of eight outputs for each 3-bit input combination."),
        ("INTERMEDIATE", "Which circuit selects one of several data inputs and routes it to a single output?",
         ["Decoder", "Encoder", "Multiplexer", "Register"], "C",
         "A multiplexer uses select lines to pass one of many inputs to the output."),
        ("INTERMEDIATE", "The Boolean expression AB + AB' simplifies to:",
         ["A", "B", "AB", "A+B"], "A",
         "By the consensus and absorption laws, AB + AB' = A(B + B') = A."),
        ("INTERMEDIATE", "What is the output of a NAND gate when both inputs are 1?",
         ["0", "1", "Undefined", "High impedance"], "A",
         "NAND is AND followed by NOT, so 1 NAND 1 = 0."),
        ("INTERMEDIATE", "A Karnaugh map is used mainly to:",
         ["Simplify Boolean expressions", "Generate random numbers", "Convert analog to digital", "Amplify signals"], "A",
         "Karnaugh maps provide a visual method for minimizing Boolean logic expressions."),
        ("INTERMEDIATE", "How is the decimal number 9 represented in binary?",
         ["1001", "1010", "1100", "0111"], "A",
         "9 = 8 + 1 = 1001 in binary."),
        ("ADVANCED", "A 4-to-1 multiplexer requires how many select lines?",
         ["1", "2", "3", "4"], "B",
         "Four inputs require 2 select lines because 2^2 = 4."),
        ("ADVANCED", "In 2's complement arithmetic, which statement about addition is true?",
         ["Sign and magnitude must be treated separately", "Subtraction can be performed by adding the 2's complement of the subtrahend", "Overflow never occurs", "Results are always positive"], "B",
         "2's complement represents negative numbers so subtraction reduces to addition of complements."),
        ("ADVANCED", "Which of the following logic families has the lowest power consumption per gate?",
         ["TTL", "ECL", "CMOS", "RTL"], "C",
         "CMOS gates draw significant power only during switching, giving very low static power consumption."),
        ("ADVANCED", "Propagation delay of a logic gate is defined as:",
         ["The time to fully charge the power supply", "The time between the input transition and the corresponding output transition", "The clock period", "The refresh interval of a DRAM"], "B",
         "Propagation delay measures how long an input change takes to produce the output change."),
        ("ADVANCED", "The Gray code is primarily used to:",
         ["Minimize errors during state transitions because consecutive codes differ by one bit", "Increase the number of bits", "Simplify arithmetic", "Encode ASCII"], "A",
         "Consecutive Gray codes differ in exactly one bit, reducing transition errors in counters and encoders."),
        ("ADVANCED", "A half adder cannot handle which input?",
         ["Two data bits", "A carry-in from a previous stage", "A clock signal", "An enable signal"], "B",
         "The half adder adds only two bits; a full adder adds the carry-in as well."),
        ("ADVANCED", "What is the fan-out of a logic gate?",
         ["The number of gate inputs it can drive reliably", "The number of its pins", "Its propagation delay", "The supply voltage it needs"], "A",
         "Fan-out is the maximum number of inputs the gate output can drive without degrading the levels."),
        ("ADVANCED", "In TTL logic, the unconnected (floating) input typically behaves as:",
         ["A logic 0", "A logic 1", "An open circuit with no defined state", "A high impedance analog value"], "B",
         "Unused TTL inputs float high because of the input structure's pull-up transistor."),
        ("ADVANCED", "Which of these gates is universal, meaning any logic function can be built using only this gate?",
         ["AND only", "OR only", "NAND", "XOR"], "C",
         "NAND is universal; combinations of NAND gates can implement AND, OR, NOT, and any other function."),
        ("ADVANCED", "A full adder for one bit position produces which two outputs?",
         ["Sum and carry", "Product and quotient", "Data and clock", "Enable and strobe"], "A",
         "A full adder outputs the sum bit and the carry-out for the next stage."),
    ],
    209: [
        ("BEGINNER", "Which device can store one bit of data and is the basic building block of sequential circuits?",
         ["Logic gate", "Flip-flop", "Resistor", "Multiplexer"], "B",
         "A flip-flop is a bistable circuit that stores a single bit of binary data."),
        ("BEGINNER", "The output of a sequential circuit depends on:",
         ["Only current inputs", "Only past outputs", "Current inputs and the present state", "The clock frequency only"], "C",
         "Sequential circuits have memory, so outputs depend on both inputs and stored state."),
        ("BEGINNER", "What is the fundamental difference between combinational and sequential circuits?",
         ["Sequential circuits have memory", "Combinational circuits use transistors", "Sequential circuits use resistors", "Combinational circuits are always faster"], "A",
         "Sequential circuits store state, while combinational outputs depend only on present inputs."),
        ("BEGINNER", "Which flip-flop has the 'toggle' behavior?",
         ["SR flip-flop", "JK flip-flop", "D flip-flop", "T flip-flop"], "D",
         "The T flip-flop toggles its output whenever the clock triggers while T is high."),
        ("BEGINNER", "The D flip-flop captures the value of D:",
         ["Continuously", "Only at the clock edge", "Only when reset", "Never"], "B",
         "A D flip-flop samples its D input at the clock edge and holds it until the next edge."),
        ("BEGINNER", "What does the clock signal provide in synchronous sequential circuits?",
         ["Power", "A timing reference to coordinate state changes", "Ground", "A reset signal"], "B",
         "The clock synchronizes when flip-flops update their states in a synchronous design."),
        ("BEGINNER", "A register is a group of:",
         ["Flip-flops used to store multiple bits", "Resistors", "Capacitors", "Logic gates in series"], "A",
         "Registers are arrays of flip-flops that hold multi-bit data."),
        ("BEGINNER", "Which of the following is a memory element?",
         ["AND gate", "Flip-flop", "Diode", "Transistor alone"], "B",
         "Flip-flops are memory elements because they retain state, unlike purely combinational gates."),
        ("BEGINNER", "A counter is a sequential circuit that:",
         ["Counts clock pulses", "Only amplifies signals", "Rectifies AC", "Regulates voltage"], "A",
         "Counters advance through a sequence of states on each clock pulse to count events."),
        ("BEGINNER", "What is the output of an SR flip-flop when both S and R are 1?",
         ["Set to 1", "Reset to 0", "Invalid or restricted state", "Toggles"], "C",
         "The S=1, R=1 condition in a basic SR latch is undefined or restricted because both outputs try to go low."),
        ("INTERMEDIATE", "How many flip-flops are needed to build a mod-8 counter?",
         ["2", "3", "4", "8"], "B",
         "A mod-8 counter counts 0 to 7 and needs 3 flip-flops because 2^3 = 8."),
        ("INTERMEDIATE", "What is the maximum count of a 4-bit binary counter?",
         ["8", "15", "16", "4"], "B",
         "A 4-bit counter counts from 0 to 15, a maximum value of 15 before wrapping to 0."),
        ("INTERMEDIATE", "Which shift register can accept data in parallel and output it serially?",
         ["SISO", "SIPO", "PISO", "Only a memory cell"], "C",
         "PISO (parallel in, serial out) loads all bits at once and shifts them out one at a time."),
        ("INTERMEDIATE", "A ring counter of n flip-flops has how many distinct states?",
         ["2^n", "n", "n/2", "n^2"], "B",
         "A ring counter has exactly n states because a single 1 circulates through the n stages."),
        ("INTERMEDIATE", "What is the function of a presettable counter?",
         ["It can be loaded with a starting value", "It cannot count", "It only decrements", "It doubles the frequency"], "A",
         "Presettable counters allow loading an initial value before counting begins."),
        ("INTERMEDIATE", "The flip-flop characteristic table shows the relationship between:",
         ["Inputs, current state, and next state", "Voltage and current", "Frequency and phase", "Delay and area"], "A",
         "A characteristic table defines the next state for each combination of inputs and present state."),
        ("INTERMEDIATE", "In a JK flip-flop, the condition J=1, K=1 causes the output to:",
         ["Reset", "Set", "Toggle", "Remain unchanged"], "C",
         "Setting both J and K to 1 makes the JK flip-flop toggle on each clock edge."),
        ("INTERMEDIATE", "Why are master-slave flip-flops used?",
         ["To avoid the race condition by using two latches", "To increase the number of outputs", "To reduce supply current", "To store analog values"], "A",
         "Master-slave construction uses two latches clocked in sequence to prevent output changes during the clock pulse."),
        ("INTERMEDIATE", "Static RAM stores data using:",
         ["Capacitors that must be refreshed", "Flip-flops that retain state as long as power is applied", "Magnetic domains", "Charge on floating gates"], "B",
         "SRAM cells are built from flip-flop-like cross-coupled inverters that hold data without refresh."),
        ("INTERMEDIATE", "A decade counter counts how many states?",
         ["8", "10", "12", "16"], "B",
         "A decade counter cycles through 0 to 9, giving 10 states."),
        ("ADVANCED", "What is the key disadvantage of asynchronous (ripple) counters?",
         ["High speed", "Propagation delay accumulates across flip-flops", "They use too many flip-flops", "They cannot count"], "B",
         "In ripple counters each flip-flop is clocked by the previous stage, so delays add up and limit speed."),
        ("ADVANCED", "Synchronous counters are preferred over asynchronous ones because:",
         ["All flip-flops are clocked simultaneously, reducing cumulative delay", "They use fewer flip-flops", "They need no clock", "They cannot overflow"], "A",
         "A common clock drives all stages at once, avoiding the accumulated delay of ripple counters."),
        ("ADVANCED", "A 4-bit bidirectional shift register can shift data in which directions?",
         ["Only left", "Only right", "Both left and right depending on the mode control", "Only in parallel"], "C",
         "A bidirectional register uses mode control lines to shift left or right."),
        ("ADVANCED", "A Johnson counter with n flip-flops produces how many states?",
         ["n", "2n", "2^n", "n^2"], "B",
         "The twisted-ring or Johnson counter has 2n states using n flip-flops."),
        ("ADVANCED", "What is the main purpose of an edge-triggered flip-flop?",
         ["To respond to a level continuously", "To sample inputs only at the clock transition, avoiding multiple changes within a pulse", "To store analog voltages", "To generate the clock itself"], "B",
         "Edge triggering samples inputs at the clock edge, so the output changes only once per edge."),
        ("ADVANCED", "In designing a counter, unused states that create invalid sequences are handled by:",
         ["Ignoring them", "Ensuring self-correction so unused states return to the valid sequence", "Adding more flip-flops", "Removing the clock"], "B",
         "Proper design forces every unused state to lead back into the valid counting sequence, avoiding lock-up."),
        ("ADVANCED", "A D flip-flop's behavior can be described as:",
         ["Q next = D", "Q next = NOT Q", "Q next = Q", "Q next = D XOR Q"], "A",
         "The D flip-flop simply copies the input to the output at each clock edge: Q_next = D."),
        ("ADVANCED", "Why does DRAM require periodic refreshing?",
         ["Its data is stored on capacitors that leak charge", "Its flip-flops are unstable", "It uses magnetic storage", "Its output needs amplification only"], "A",
         "DRAM cells store charge on tiny capacitors that gradually leak, so the data must be refreshed periodically."),
        ("ADVANCED", "Race-around condition in a JK flip-flop is avoided primarily by:",
         ["Increasing supply voltage", "Using a master-slave or edge-triggered design", "Adding a resistor", "Using only SR flip-flops"], "B",
         "Master-slave and edge-triggered designs prevent the output from racing during a long clock pulse."),
        ("ADVANCED", "A sequence detector built with a finite state machine outputs 1 when:",
         ["A specific pattern is detected in the input stream", "The clock frequency is high", "The input is always 1", "The counter overflows"], "A",
         "A sequence detector recognizes a predefined pattern in the serial input and flags it with a 1."),
    ],
    210: [
        ("BEGINNER", "Which unit of the CPU fetches and executes instructions?",
         ["Control unit and ALU together", "Only the ALU", "The memory controller", "The bus interface"], "A",
         "The control unit fetches instructions and coordinates the ALU, which performs arithmetic and logic."),
        ("BEGINNER", "What does ALU stand for?",
         ["Automatic Logic Unit", "Arithmetic Logic Unit", "Advanced Load Unit", "Application Link Unit"], "B",
         "ALU stands for Arithmetic Logic Unit, which performs arithmetic and logical operations."),
        ("BEGINNER", "Which register holds the address of the next instruction to be executed?",
         ["Accumulator", "Program counter (PC)", "Stack pointer", "Status register"], "B",
         "The program counter holds the memory address of the next instruction to be fetched."),
        ("BEGINNER", "The accumulator is primarily used to:",
         ["Store intermediate arithmetic results", "Store the memory address of data", "Count interrupts", "Hold the clock frequency"], "A",
         "The accumulator holds one operand and the result of arithmetic operations."),
        ("BEGINNER", "Which bus carries data between the CPU, memory, and I/O devices?",
         ["Address bus", "Data bus", "Control bus", "Power bus"], "B",
         "The data bus transfers actual data between components."),
        ("BEGINNER", "The address bus is used to:",
         ["Transfer data values", "Carry memory or I/O addresses", "Deliver power", "Carry the clock"], "B",
         "The address bus carries the addresses that select a memory location or I/O device."),
        ("BEGINNER", "A machine cycle consists of:",
         ["Fetch, decode, and execute", "Only the fetch", "Only the execute", "Compile and link"], "A",
         "The fetch-decode-execute sequence forms one machine cycle."),
        ("BEGINNER", "Which of the following is an instruction set operation category?",
         ["Data transfer, arithmetic, and control transfer", "Only data transfer", "Only arithmetic", "Only I/O"], "A",
         "Instruction sets include data movement, arithmetic/logic, and control transfer operations."),
        ("BEGINNER", "What role does the opcode play in a machine instruction?",
         ["The part of an instruction that specifies the operation to perform", "The data being processed", "The memory address", "The clock speed"], "A",
         "The opcode identifies the operation, while operands provide the data or addresses."),
        ("BEGINNER", "The microprocessor is often called the:",
         ["Brain of the computer", "Storage unit", "Power supply", "Output device"], "A",
         "The microprocessor coordinates and executes all processing tasks, acting as the computer's brain."),
        ("INTERMEDIATE", "If the data bus is 16 bits wide, the largest value it can transfer in one operation is:",
         ["8 bits", "16 bits", "32 bits", "1 byte"], "B",
         "The data bus width determines the maximum bits transferred at once, here 16 bits."),
        ("INTERMEDIATE", "An 8-bit microprocessor can address up to how many memory locations with a 16-bit address bus?",
         ["256", "65536", "4096", "1 million"], "B",
         "A 16-bit address bus can address 2^16 = 65536 distinct locations."),
        ("INTERMEDIATE", "Which addressing mode uses the operand's address directly in the instruction?",
         ["Immediate", "Direct", "Indirect", "Register"], "B",
         "In direct addressing the instruction contains the memory address of the operand."),
        ("INTERMEDIATE", "In immediate addressing mode, the operand is:",
         ["A memory address", "Part of the instruction itself", "Stored in a register", "Fetched from disk"], "B",
         "Immediate mode embeds the constant value directly within the instruction."),
        ("INTERMEDIATE", "What is the stack used for during subroutine calls?",
         ["Storing the return address and saved registers", "Storing the program data permanently", "Holding the clock", "Buffering the display"], "A",
         "The stack pushes the return address and context so execution can resume after the subroutine."),
        ("INTERMEDIATE", "Which register pair is commonly used as the stack pointer in 8-bit microprocessors?",
         ["The SP register", "The program counter", "The accumulator", "The flag register"], "A",
         "The stack pointer (SP) tracks the top of the stack in memory."),
        ("INTERMEDIATE", "What is an interrupt in microprocessor terminology?",
         ["A signal that suspends normal execution to service an urgent event", "A permanent halt of the CPU", "A memory refresh", "A data transfer error"], "A",
         "Interrupts temporarily divert the CPU to an interrupt service routine, then return to normal execution."),
        ("INTERMEDIATE", "The flag register in a microprocessor stores:",
         ["Condition flags such as carry, zero, and sign", "Memory addresses", "The clock value", "Interrupt vectors"], "A",
         "Flags record outcomes of operations, such as carry, zero, sign, and parity."),
        ("INTERMEDIATE", "Which bus is bidirectional?",
         ["Address bus", "Data bus", "Control bus only", "Clock line"], "B",
         "The data bus transfers data in both directions between CPU, memory, and I/O."),
        ("INTERMEDIATE", "In 8085 microprocessor, how many address lines does it have?",
         ["8", "16", "20", "32"], "B",
         "The 8085 has 16 address lines, addressing 64 KB of memory."),
        ("ADVANCED", "What is the main purpose of the stack pointer in interrupt handling?",
         ["To save the full CPU context so execution can resume after the ISR", "To store the operating system", "To replace the program counter", "To double the clock"], "A",
         "The stack saves registers and the return address, allowing clean resumption after the interrupt service routine."),
        ("ADVANCED", "Pipelining improves performance by:",
         ["Overlapping the execution of successive instructions", "Increasing the clock speed", "Using more memory", "Reducing the address bus"], "A",
         "Pipelining lets fetch, decode, and execute of different instructions overlap, increasing throughput."),
        ("ADVANCED", "Which instruction type causes the processor to jump to a subroutine and remember the return address?",
         ["CALL", "HALT", "NOP", "MOV"], "A",
         "CALL transfers control to a subroutine and pushes the return address onto the stack."),
        ("ADVANCED", "The Memory-Mapped I/O technique treats:",
         ["I/O devices as memory locations accessed with normal memory instructions", "All memory as I/O ports", "Registers as memory", "Only DMA as valid"], "A",
         "Memory-mapped I/O assigns addresses to ports so ordinary memory instructions can access devices."),
        ("ADVANCED", "What is the advantage of isolated (port) I/O over memory-mapped I/O?",
         ["It frees the full memory address space", "It uses no instructions", "It is always faster", "It needs no control bus"], "A",
         "Separate I/O space preserves the entire memory range for actual memory."),
        ("ADVANCED", "Which of these is a RISC characteristic?",
         ["Fixed-length, simple instructions executed in few cycles", "Complex instructions with many addressing modes", "Microcoded control", "Very long variable-length instructions"], "A",
         "RISC designs use simple, fixed-size instructions and a load-store model, enabling pipelining."),
        ("ADVANCED", "In a microprocessor, 'clock frequency' determines:",
         ["The rate at which instructions and operations are synchronized", "The memory capacity", "The number of registers", "The bus width"], "A",
         "The clock drives each step of the fetch-execute cycle, so a higher frequency speeds operations."),
        ("ADVANCED", "What happens during a DMA transfer?",
         ["A DMA controller moves data between memory and I/O without CPU intervention", "The CPU copies each byte", "Memory is erased", "The clock stops"], "A",
         "DMA lets a controller transfer blocks of data directly, freeing the CPU for other work."),
        ("ADVANCED", "The control unit generates timing and control signals to:",
         ["Coordinate the operation of all units in the processor", "Supply power to the RAM", "Increase the address space", "Refresh the display"], "A",
         "The control unit decodes instructions and issues the signals that coordinate fetch, decode, and execute."),
        ("ADVANCED", "When the microprocessor executes a HALT instruction, it:",
         ["Stops fetching and executing until an interrupt or reset occurs", "Reboots the system", "Clears all memory", "Increases clock speed"], "A",
         "HALT suspends the fetch-execute cycle until an interrupt or hardware reset resumes operation."),
    ],
}
