# -*- coding: utf-8 -*-
"""
Question bank for subject 28: WEB103 - Backend Development.
Category: Web & Mobile Development.

Topics:
  136: Node.js Basics
  137: Express & REST APIs
  138: Authentication & Authorization
  139: Middleware & Error Handling
  140: Backend Security & Scaling

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    136: [
        ("BEGINNER", "Which runtime lets JavaScript run outside the browser on a server?",
         ["Node.js", "jQuery", "Bootstrap", "React"], "A",
         "Node.js is a JavaScript runtime built on Chrome V8 that executes JS outside the browser."),
        ("BEGINNER", "What is the command to initialize a new Node.js project with a package.json file?",
         ["npm install", "npm init", "node init", "npm start"], "B",
         "npm init walks through creating a package.json, the manifest that stores project metadata and dependencies."),
        ("BEGINNER", "Which of the following is a core Node.js module for working with files?",
         ["http", "fs", "path", "os"], "C",
         "The fs module provides filesystem operations such as reading and writing files."),
        ("BEGINNER", "What does the 'npm' in npm install stand for?",
         ["Node Process Manager", "Node Package Manager", "Network Process Manager", "Node Project Manager"], "D",
         "npm stands for Node Package Manager and is used to install and manage packages for Node.js projects."),
        ("BEGINNER", "Which method is used to listen for an incoming HTTP request on a server created with http.createServer?",
         ["server.listen()", "server.start()", "server.run()", "server.bind()"], "A",
         "The listen() method starts the server and makes it begin accepting connections on a port."),
        ("BEGINNER", "Which event fires when a Node.js EventEmitter emits an event?",
         ["callback", "listener", "handler", "promise"], "B",
         "A listener, registered with on(), is called when the corresponding event is emitted."),
        ("BEGINNER", "What file lists the dependencies required by a Node.js project?",
         ["package.json", "app.js", "server.js", "index.html"], "C",
         "package.json lists the project dependencies, scripts, and metadata."),
        ("BEGINNER", "Which symbol does require() use to reference a module's exported value?",
         ["module.exports", "exports.default", "return", "this.export"], "D",
         "module.exports is the CommonJS mechanism for exposing a module's public API to consumers."),
        ("BEGINNER", "Which of the following is NOT a built-in core module in Node.js?",
         ["fs", "http", "path", "jquery"], "A",
         "jQuery is a browser-side library and is not a core Node.js module."),
        ("BEGINNER", "What does the fs.readFile() function primarily do?",
         ["reads a file from disk", "deletes a file", "renames a file", "creates a directory"], "B",
         "fs.readFile() reads the contents of a file asynchronously from the filesystem."),
        ("INTERMEDIATE", "Consider const f = () => Promise.resolve(5); what does f() return?",
         ["5", "a resolved Promise wrapping 5", "undefined", "NaN"], "B",
         "An async arrow function that returns a value wraps it in a resolved Promise, so f() yields a Promise."),
        ("INTERMEDIATE", "What is the purpose of the 'require' function in CommonJS modules?",
         ["to import another module into the current module", "to define a new global variable", "to parse JSON data", "to start the event loop"], "A",
         "require() loads and returns the exports of another module so its API can be used locally."),
        ("INTERMEDIATE", "Which of the following is the correct way to export a single function from a CommonJS module?",
         ["module.exports = myFunction", "exports.fn = myFunction and import via require()", "export default myFunction", "this.myFunction = myFunction"], "C",
         "module.exports = myFunction replaces the default export with the single function so it can be required directly."),
        ("INTERMEDIATE", "What happens when an uncaught exception is thrown inside a Node.js HTTP request handler?",
         ["the server stays healthy and continues serving", "the process crashes unless handled", "the request returns 500 automatically", "the event loop pauses"], "D",
         "An uncaught exception in a Node.js process typically crashes the process, which is why try/catch and process-level handlers are needed."),
        ("INTERMEDIATE", "Which Node.js feature allows running code in a separate process to avoid blocking the main thread?",
         ["worker_threads", "http.Server", "module.exports", "process.env"], "A",
         "worker_threads spawns additional threads so CPU-heavy work does not block the main event loop."),
        ("INTERMEDIATE", "What does process.env do in a Node.js application?",
         ["provides access to environment variables", "lists all loaded modules", "returns the current working directory", "holds command-line arguments"], "B",
         "process.env exposes the environment variables of the current process as an object."),
        ("INTERMEDIATE", "Consider this code: setTimeout(() => console.log('A'), 0); console.log('B'); What order prints?",
         ["A then B", "B then A", "A and B together", "only B prints"], "C",
         "The synchronous console.log('B') runs first, and the timer callback A is deferred to the next tick of the event loop."),
        ("INTERMEDIATE", "Which module would you use to build a minimal TCP server in Node.js?",
         ["net", "fs", "path", "os"], "D",
         "The net module provides APIs for creating TCP servers and clients."),
        ("INTERMEDIATE", "Which API is used to read a file synchronously in Node.js?",
         ["fs.readFileSync()", "fs.readFile()", "fs.read()", "fs.readAsync()"], "A",
         "fs.readFileSync() performs a synchronous file read, blocking the event loop until complete."),
        ("INTERMEDIATE", "Consider const p = new Promise((resolve) => setTimeout(() => resolve('done'), 1000)); what does await p produce?",
         ["'done'", "a Promise", "undefined", "an error"], "D",
         "await p resolves the Promise and yields its fulfilled value, which is the string 'done'."),
        ("ADVANCED", "A Node.js service is CPU-bound and its request latency is rising. Which fix most directly improves throughput?",
         ["spawning worker threads for the heavy computation", "adding more console.log statements", "switching all callbacks to promises", "increasing the HTTP keep-alive timeout"], "A",
         "Moving CPU-intensive work to worker threads frees the main event loop so it can handle more requests concurrently."),
        ("ADVANCED", "Which of these is the main benefit of using the cluster module for a Node.js web server?",
         ["spawning multiple processes to utilize multiple CPU cores", "compressing HTTP responses", "caching database queries", "minifying JavaScript files"], "B",
         "The cluster module forks worker processes so a Node app can use multiple CPU cores behind a single shared port."),
        ("ADVANCED", "A Node.js app reads a huge file to memory with fs.readFile() on every request, causing high memory use. What is the best alternative?",
         ["stream the file with fs.createReadStream()", "read it with fs.readFileSync()", "increase the heap size", "cache the file in a global variable"], "C",
         "Streaming reads the file in chunks, keeping memory usage flat instead of loading the entire file at once."),
        ("ADVANCED", "Why does blocking the event loop with a long synchronous loop hurt a Node.js server the most?",
         ["it prevents other connections from being processed during that time", "it uses more RAM than async code", "it causes the process to exit", "it increases the server's security risk"], "D",
         "The single-threaded event loop can only process one operation at a time, so blocking it stalls every other request."),
        ("ADVANCED", "A package.json has 'type': 'module'. How do you import a function named build from './util.js'?",
         ["import { build } from './util.js';", "const build = require('./util.js');", "define build from './util.js';", "include('./util.js').build();"], "A",
         "With 'type': 'module', files use ES module syntax, so named imports use the import statement."),
        ("ADVANCED", "What is the purpose of the --experimental-* flags commonly seen in Node.js releases?",
         ["to opt into features that are not yet stable", "to speed up the compiler", "to disable strict mode", "to reduce memory usage"], "B",
         "Experimental flags let developers test in-development features before they reach stable status."),
        ("ADVANCED", "You need to gracefully shut down a Node server, finish in-flight requests, and close the DB pool. Which approach is best?",
         ["listen to SIGTERM/SIGINT and call server.close() plus cleanup", "call process.exit() immediately", "throw an exception to stop the process", "delete the server reference and wait"], "C",
         "Handling shutdown signals lets the app stop accepting new connections, finish active work, and release resources cleanly."),
        ("ADVANCED", "Why does Node.js prefer asynchronous I/O over blocking I/O for web servers?",
         ["so the thread can run other tasks while waiting for I/O", "because synchronous code is slower on V8", "to avoid garbage collection", "to guarantee requests arrive in order"], "D",
         "Async I/O lets the event loop continue processing other tasks while waiting, keeping the single thread busy and the server responsive."),
        ("ADVANCED", "In a multi-instance deployment behind a load balancer, why should you avoid storing session state in the Node process memory?",
         ["each instance would have a separate session store, breaking sessions across requests", "process memory is slower than a database", "Node cannot persist memory to disk", "memory sessions expire too quickly"], "A",
         "In-memory sessions are isolated per process, so a request routed to another instance would not see the session; a shared store is required."),
        ("ADVANCED", "Which statement best describes the difference between process.nextTick and setImmediate?",
         ["nextTick runs before I/O callbacks while setImmediate runs after them", "nextTick is a browser API", "setImmediate runs synchronously", "they are identical aliases"], "B",
         "nextTick callbacks run in the current phase before I/O processing resumes, while setImmediate defers to the check phase after I/O."),
    ],
    137: [
        ("BEGINNER", "Which framework is built on top of Node.js to simplify building web servers and APIs?",
         ["Express", "React", "Vue", "Bootstrap"], "A",
         "Express is a minimalist Node.js web framework used to build servers and REST APIs."),
        ("BEGINNER", "Which HTTP method is used to fetch data from a REST API?",
         ["GET", "POST", "DELETE", "PUT"], "B",
         "GET is the HTTP method designed to retrieve a resource without side effects."),
        ("BEGINNER", "Which HTTP method is typically used to create a new resource?",
         ["GET", "POST", "PUT", "DELETE"], "C",
         "POST is the convention for submitting a new resource to the server."),
        ("BEGINNER", "What does the acronym REST stand for?",
         ["Representational State Transfer", "Remote Endpoint Service Transfer", "Representational Source Transfer", "Remote State Transfer"], "D",
         "REST stands for Representational State Transfer, an architectural style for distributed systems."),
        ("BEGINNER", "Which Express function registers a route handler for GET requests to a path?",
         ["app.get(path, handler)", "app.send(path, handler)", "app.route(path, handler)", "app.fetch(path, handler)"], "A",
         "app.get() binds a callback that responds to GET requests for the given path."),
        ("BEGINNER", "Which method is used to send a JSON response in Express?",
         ["res.json()", "res.sendFile()", "res.render()", "res.redirect()"], "B",
         "res.json() serializes the given value to JSON and sends it with the JSON content type."),
        ("BEGINNER", "What status code does a successful GET request usually return?",
         ["200 OK", "404 Not Found", "500 Internal Server Error", "302 Found"], "C",
         "A 200 status indicates the request succeeded and the response body contains the resource."),
        ("BEGINNER", "Which status code means the requested resource was not found?",
         ["404", "200", "201", "401"], "D",
         "404 Not Found signals that the server could not locate the requested resource."),
        ("BEGINNER", "In Express, what is the second argument passed to app.get()?",
         ["a route handler function", "the port number", "a middleware array", "the response body"], "A",
         "The second argument is the handler callback that receives req and res to produce the response."),
        ("BEGINNER", "Which HTTP method is used to update an entire existing resource?",
         ["PUT", "POST", "GET", "OPTIONS"], "B",
         "PUT replaces a resource entirely at a known URL, following REST conventions."),
        ("INTERMEDIATE", "Consider app.post('/users', handler). When is this handler invoked?",
         ["when an HTTP POST request is made to /users", "when any request is made to /users", "when a GET request is made to /users", "when a POST request is made to any path"], "A",
         "The handler runs only for POST requests whose path matches /users."),
        ("INTERMEDIATE", "Which Express object holds the URL parameters defined like app.get('/users/:id', ...)?",
         ["req.params", "req.query", "req.body", "req.headers"], "C",
         "Route parameters like :id are exposed on the req.params object."),
        ("INTERMEDIATE", "How do you read a query string value like ?page=2 in Express?",
         ["req.query.page", "req.params.page", "req.body.page", "req.url.page"], "D",
         "Query string values are parsed and made available on req.query, so page is req.query.page."),
        ("INTERMEDIATE", "Which Express method sends a 302 redirect to /home?",
         ["res.redirect('/home')", "res.send('/home')", "res.location('/home') and res.end()", "res.go('/home')"], "A",
         "res.redirect() issues a redirect response with the given location."),
        ("INTERMEDIATE", "Consider the route app.put('/items/:id', handler). Which REST resource does it update?",
         ["the item identified by :id", "all items", "the item at /items", "a query parameter named id"], "B",
         "The :id segment identifies which item the PUT request should replace."),
        ("INTERMEDIATE", "What does app.use('/api', router) accomplish in Express?",
         ["mounts a router at the /api prefix", "creates an API endpoint named /api", "sends a response to /api", "defines a GET route at /api"], "C",
         "app.use() mounts the router so all of its routes are available under the /api path prefix."),
        ("INTERMEDIATE", "Which HTTP method and route best represents deleting a resource in a REST API?",
         ["DELETE /users/42", "GET /users/42", "POST /users/42/delete", "PATCH /users/42"], "D",
         "DELETE with the resource identifier is the idiomatic REST way to remove a resource."),
        ("INTERMEDIATE", "What is the most common reason an Express API returns status 400?",
         ["the request is malformed or fails validation", "the resource was not found", "the user is unauthorized", "the server crashed"], "A",
         "400 Bad Request indicates the client sent an invalid or unprocessable request."),
        ("INTERMEDIATE", "Which Express method is used to respond with a specific HTTP status code and a body?",
         ["res.status(code).send(body)", "res.body(code).status(send)", "res.sendCode(code)", "res.response(code)"], "D",
         "res.status() sets the status code and can be chained with .send() to include a body."),
        ("INTERMEDIATE", "Consider app.delete('/posts/:id', (req, res) => { ... }). What does req.params.id hold?",
         ["the value of the id segment from the URL", "the request body", "the query string", "the HTTP header"], "A",
         "req.params.id holds the value captured by the :id route parameter."),
        ("ADVANCED", "An API uses POST /orders/approve instead of POST /orders/:id/approve. Which REST design issue is most relevant?",
         ["the route does not clearly identify which order is being approved", "POST cannot be used with subresources", "approve is not a valid verb", "the route violates HTTP 1.1 specs"], "B",
         "Without the :id, the endpoint cannot express which order to approve, so the URL is ambiguous and non-idiomatic."),
        ("ADVANCED", "Why is versioning an API (for example /v1/users) recommended when multiple clients consume it?",
         ["so breaking changes can be introduced without breaking existing clients", "to make routes shorter", "to reduce HTTP request size", "to allow the server to use more ports"], "C",
         "Versioning lets the API evolve with breaking changes while old clients keep using a stable version."),
        ("ADVANCED", "A mobile client keeps sending the full user object on every PUT when only one field changed. Which method is more appropriate?",
         ["PATCH", "PUT", "POST", "OPTIONS"], "D",
         "PATCH sends only the partial change, reducing payload size and matching the intended semantics."),
        ("ADVANCED", "What is the primary benefit of using HTTP status codes correctly rather than returning 200 with an error flag?",
         ["clients and tooling can interpret failures programmatically", "responses become smaller", "the server runs faster", "it removes the need for HTTPS"], "A",
         "Proper status codes let clients, proxies, and monitoring tools detect and handle errors without parsing the body."),
        ("ADVANCED", "Which approach best prevents an API endpoint from being abused by a single client?",
         ["rate limiting per client/IP", "sending all errors as 500", "disabling caching", "using GET for mutations"], "B",
         "Rate limiting caps how many requests a client can make, protecting the service from overload."),
        ("ADVANCED", "An Express API needs to expose data to third parties. What is the most important documentation practice?",
         ["publishing an OpenAPI/API reference", "adding more comments in code", "using POST for all endpoints", "removing the version number"], "C",
         "An OpenAPI-style reference documents endpoints, parameters, and schemas so third-party developers can integrate reliably."),
        ("ADVANCED", "Why is HATEOAS considered a good practice in strictly RESTful APIs?",
         ["the response includes links that guide the client through the API", "it makes responses JSON instead of XML", "it removes the need for authentication", "it allows the server to be stateless"], "D",
         "HATEOAS embeds discoverable links in responses so clients can navigate related actions dynamically."),
        ("ADVANCED", "Your API endpoint returns sensitive data over plain HTTP in production. What is the correct fix?",
         ["enforce HTTPS/TLS on the server", "obfuscate the JSON keys", "split the data across endpoints", "return the data as a string"], "A",
         "Encrypting traffic with TLS prevents interception of sensitive data in transit."),
        ("ADVANCED", "What is the main reason REST APIs should be stateless on the server side?",
         ["any server instance can serve any request, enabling horizontal scaling", "stateless APIs are always faster", "it removes the need for a database", "it prevents SQL injection"], "B",
         "Statelessness lets any instance handle any request, making it trivial to scale out behind a load balancer."),
        ("ADVANCED", "An API accepts GET /users?fields=id,name to return only some properties. This pattern is known as:",
         ["field selection / sparse fields", "pagination", "filtering", "sorting"], "C",
         "Field selection lets clients request only the properties they need, reducing bandwidth and processing."),
    ],
    138: [
        ("BEGINNER", "What is the process of verifying that a user is who they claim to be?",
         ["Authentication", "Authorization", "Encryption", "Hashing"], "A",
         "Authentication confirms a user's identity, such as through credentials or tokens."),
        ("BEGINNER", "What is the process of determining what an authenticated user is allowed to do?",
         ["Authorization", "Authentication", "Validation", "Serialization"], "B",
         "Authorization decides which resources and actions a verified user may access."),
        ("BEGINNER", "Which token format is commonly used for stateless authentication in web APIs?",
         ["JWT", "CSRF", "SSL", "DNS"], "C",
         "JWTs (JSON Web Tokens) are compact, signed tokens widely used for stateless API authentication."),
        ("BEGINNER", "Which of the following is a password hashing library commonly used in Node.js?",
         ["bcrypt", "crypto-js encryption", "jquery", "lodash"], "D",
         "bcrypt is a popular library for safely hashing and comparing passwords."),
        ("BEGINNER", "What does the Authorization HTTP header commonly carry?",
         ["a credential or token proving the user is authorized", "the user's IP address", "the requested resource name", "the server's version"], "A",
         "The Authorization header carries credentials such as a Bearer token that proves identity."),
        ("BEGINNER", "Which package is most commonly used to create and verify JWTs in Node.js?",
         ["jsonwebtoken", "jwt-express", "express-session", "passport-local"], "B",
         "The jsonwebtoken package provides sign() and verify() for creating and validating JWTs."),
        ("BEGINNER", "What does the 'iat' claim in a JWT represent?",
         ["issued-at timestamp", "expiration time", "subject", "issuer"], "C",
         "iat records when the token was issued, helping clients and servers check token age."),
        ("BEGINNER", "Which HTTP method is used to log in and obtain a session?",
         ["POST", "GET", "PUT", "DELETE"], "D",
         "POST is used to submit credentials to a login endpoint that returns a session or token."),
        ("BEGINNER", "What does OAuth 2.0 primarily provide?",
         ["a framework for delegated authorization", "a password hashing scheme", "an encryption cipher", "a caching layer"], "A",
         "OAuth 2.0 lets third-party apps obtain limited access to a user's resources without sharing passwords."),
        ("BEGINNER", "Which mechanism stores the user's login state on the server in a traditional web app?",
         ["session cookies", "client-side JavaScript", "localStorage", "a query string"], "B",
         "Server-side sessions keep login state on the server and track it with a cookie holding a session ID."),
        ("INTERMEDIATE", "Consider a JWT signed with HS256. What is required to verify the signature?",
         ["the same secret key that was used to sign", "the user's password", "the public key of the server", "the token's audience claim"], "A",
         "HS256 is symmetric, so verification requires the exact same secret key used to sign the token."),
        ("INTERMEDIATE", "Which part of a JWT contains the user claims like sub and roles?",
         ["the payload", "the header", "the signature", "the footer"], "B",
         "The payload is the middle segment of a JWT and holds the claims about the subject."),
        ("INTERMEDIATE", "What is the typical purpose of the 'exp' claim in a JWT?",
         ["to define when the token expires", "to identify the token issuer", "to store the user id", "to mark the token as revoked"], "C",
         "The exp claim sets an expiration timestamp after which the token must be rejected."),
        ("INTERMEDIATE", "Why should JWT secret keys be stored in environment variables rather than committed to source control?",
         ["so the secret is not exposed to anyone who reads the repo", "so the token can be decoded faster", "because JWT cannot work with hardcoded strings", "to reduce token size"], "D",
         "Committing secrets in the repo leaks them to anyone with access, so they belong in secure environment configuration."),
        ("INTERMEDIATE", "Consider a route that requires the user to be an admin. What step is this enforcing?",
         ["Authorization", "Authentication", "Hashing", "Encryption"], "A",
         "Requiring a specific role or permission is an authorization check performed after authentication."),
        ("INTERMEDIATE", "Which strategy does Passport.js use to authenticate with a username and password?",
         ["LocalStrategy", "BearerStrategy", "JWTStrategy", "AnonymousStrategy"], "B",
         "Passport's LocalStrategy verifies a username and password against stored credentials."),
        ("INTERMEDIATE", "What is the safest way to store passwords in a database?",
         ["store a salted, slow hash like bcrypt", "store them in plain text", "store an MD5 hash", "store them encrypted with a shared key"], "C",
         "Salted, computationally expensive hashes like bcrypt resist brute-force and rainbow-table attacks."),
        ("INTERMEDIATE", "What happens if a JWT signature fails verification on the server?",
         ["the request is rejected as unauthorized", "the payload is ignored but the request continues", "the token is refreshed automatically", "the server signs it again"], "D",
         "A failed signature check means the token was tampered with or forged, so the request must be rejected."),
        ("INTERMEDIATE", "Which header format is standard for sending a JWT in a REST API?",
         ["Authorization: Bearer <token>", "Cookie: JWT=<token>", "X-Token: <token>", "Accept: <token>"], "A",
         "Bearer tokens are transmitted in the Authorization header in the form Authorization: Bearer <token>."),
        ("INTERMEDIATE", "What is the main reason to store a session ID in a cookie with the HttpOnly flag?",
         ["to prevent client-side JavaScript from reading the cookie", "to make the cookie expire sooner", "to encrypt the session data", "to allow cross-site requests"], "B",
         "HttpOnly keeps cookies inaccessible to JavaScript, reducing the risk of theft via XSS."),
        ("ADVANCED", "Your API uses JWT stored in localStorage, and an XSS vulnerability has been found. What is the safest mitigation?",
         ["move tokens to HttpOnly, Secure cookies", "store tokens in a global variable", "use a shorter secret", "disable CORS entirely"], "A",
         "HttpOnly cookies keep tokens out of JavaScript's reach so even successful XSS cannot steal them."),
        ("ADVANCED", "A user logs out but their JWT remains valid for hours. Which token strategy best solves this?",
         ["maintain a server-side revocation list for tokens", "re-issue a new token on every request", "delete the user account", "shorter token signatures"], "C",
         "A revocation list or short-lived tokens with refresh rotation lets the server invalidate tokens before expiry."),
        ("ADVANCED", "Why is it risky to trust a 'role' claim inside a client-provided JWT without verifying its signature?",
         ["an attacker could forge a token and gain admin access", "it makes tokens larger", "it slows down verification", "roles cannot be encoded in JSON"], "D",
         "Without signature verification, a client can modify the role claim and escalate privileges."),
        ("ADVANCED", "What is the primary reason bcrypt is preferred over plain SHA-256 for passwords?",
         ["bcrypt is deliberately slow, resisting brute-force attacks", "SHA-256 is reversible", "bcrypt produces shorter hashes", "SHA-256 is not supported on servers"], "A",
         "bcrypt's configurable cost factor makes each hash expensive, dramatically slowing password cracking."),
         ("ADVANCED", "In a microservices architecture, which approach avoids each service needing to verify JWT signatures independently against a shared secret?",
          ["having a central auth service issue tokens that all services validate via a shared public key", "storing sessions in each service's memory", "sending passwords with every request", "disabling authorization in most services"], "B",
          "A central auth service signs tokens with a private key while services verify them with a shared public key, avoiding one shared secret everywhere."),
         ("ADVANCED", "Why should access tokens be short-lived while refresh tokens have longer lifetimes?",
         ["short-lived tokens limit the damage if they leak, while refresh tokens can be rotated and revoked", "short tokens are easier to sign", "refresh tokens are always stored in memory", "access tokens cannot expire"], "C",
         "Short access tokens minimize exposure on compromise, while refresh tokens enable rotation and revocation."),
        ("ADVANCED", "Your app sends a JWT in a URL query string. What is the security problem with this practice?",
         ["tokens in URLs can be leaked via logs, history, and referer headers", "query strings are too short for JWTs", "JWT is a binary format", "URLs cannot contain dots"], "D",
         "URLs are commonly logged and shared, so tokens in query strings risk accidental exposure."),
        ("ADVANCED", "What does the 'aud' (audience) claim in a JWT help prevent?",
         ["a token issued for one service being used against another service", "the token from expiring", "the server from restarting", "the payload from being decoded"], "A",
         "The audience claim binds a token to a specific intended service, blocking token reuse elsewhere."),
        ("ADVANCED", "Which best practice mitigates CSRF attacks on cookie-based session authentication?",
         ["use CSRF tokens or SameSite=Strict cookies", "store sessions in localStorage", "log in via GET requests", "disable HTTPS"], "D",
         "SameSite cookies and CSRF tokens prevent malicious sites from making authenticated requests on the user's behalf."),
        ("ADVANCED", "A single-sign-on system lets users authenticate once with an identity provider and then use many apps. Which token mechanism best supports this?",
         ["short-lived access tokens plus refresh tokens issued by the identity provider", "a per-app password", "the user's raw password in a cookie", "a fixed API key per browser"], "A",
         "SSO providers issue access and refresh tokens so apps can authenticate users without handling passwords directly."),
    ],
    139: [
        ("BEGINNER", "What is middleware in Express?",
         ["a function that runs between receiving a request and sending a response", "a database connector", "a front-end component", "a build tool"], "A",
         "Middleware functions intercept requests to perform logic before the final route handler responds."),
        ("BEGINNER", "Which Express function is used to register global middleware?",
         ["app.use()", "app.listen()", "app.route()", "app.set()"], "B",
         "app.use() mounts middleware so it runs for every matching request."),
        ("BEGINNER", "Which argument does Express middleware receive to continue to the next middleware?",
         ["next", "continue", "move", "done"], "C",
         "Calling next() hands control to the next middleware or route handler in the stack."),
        ("BEGINNER", "What are the three arguments of a standard Express middleware function?",
         ["req, res, next", "req, res, end", "request, response, done", "url, method, handler"], "D",
         "Standard middleware receives the request, response, and next callback."),
        ("BEGINNER", "Which status code class indicates a client-side error in Express?",
         ["4xx", "2xx", "3xx", "5xx"], "A",
         "4xx codes mean the client sent an invalid request, such as 400 or 404."),
        ("BEGINNER", "What is the purpose of Express error-handling middleware?",
         ["to catch and respond to errors thrown in routes", "to parse JSON bodies", "to log incoming requests", "to serve static files"], "B",
         "Error-handling middleware receives errors and sends an appropriate response instead of crashing."),
        ("BEGINNER", "How is Express error-handling middleware recognized from regular middleware?",
         ["it has four arguments: err, req, res, next", "it is named error()", "it uses async/await", "it returns a Promise"], "C",
         "Express identifies error middleware by its four-parameter signature starting with err."),
        ("BEGINNER", "Which built-in Express middleware parses incoming JSON request bodies?",
         ["express.json()", "express.urlencoded()", "express.static()", "express.cors()"], "D",
         "express.json() parses JSON bodies and populates req.body."),
        ("BEGINNER", "What happens if a middleware never calls next() and never sends a response?",
         ["the request hangs until the client times out", "Express returns a 500", "the server crashes", "the response is sent automatically"], "A",
         "Without next() or a terminating response, the request stalls because no handler completes it."),
        ("BEGINNER", "Which middleware would you add to serve static files like images and CSS?",
         ["express.static()", "express.json()", "express.urlencoded()", "express.logger()"], "B",
         "express.static() serves files from a directory for direct browser access."),
        ("INTERMEDIATE", "Consider app.use((req, res, next) => { console.log('A'); next(); }); app.get('/', handler); What prints before handler runs?",
         ["A", "nothing", "the route path", "an error"], "C",
         "The middleware logs 'A' first, then calls next() to continue to the route handler."),
        ("INTERMEDIATE", "What does calling next('route') do inside a route-level middleware in Express?",
         ["skips to the next route that matches", "sends a 404", "stops all processing", "re-runs the current handler"], "D",
         "next('route') passes control to the next matching route, skipping the remaining handlers of the current route."),
        ("INTERMEDIATE", "Consider the middleware order: [auth, logging, cache]. Which middleware runs first for a request?",
         ["auth", "logging", "cache", "they all run at once"], "A",
         "Express executes middleware in the order they were registered, so auth runs first."),
        ("INTERMEDIATE", "Why does the body-parsing middleware like express.json() need to be registered before routes that read req.body?",
         ["routes read req.body only after middleware has populated it", "it speeds up JSON parsing", "it validates the URL", "it sets response headers"], "B",
         "Middleware runs first, so the parser must execute before the route handler to populate req.body."),
        ("INTERMEDIATE", "What is the purpose of a 404 handler placed at the end of an Express app?",
         ["to catch requests that matched no route", "to speed up responses", "to handle database errors", "to enforce authentication"], "C",
         "A trailing handler that returns 404 catches any request no earlier route or middleware matched."),
        ("INTERMEDIATE", "Consider an error-handling middleware (err, req, res, next) that does not send a response and does not call next(). What occurs?",
         ["the request hangs and the client times out", "Express sends a 500 automatically", "the error is logged and ignored", "the server restarts"], "D",
         "Like any uncompleted handler, the request stalls because nothing terminates the response."),
        ("INTERMEDIATE", "Which middleware would you add first to log the method and URL of every incoming request?",
         ["app.use((req, res, next) => { console.log(req.method, req.url); next(); })", "a route handler on GET /", "express.json()", "a database middleware"], "A",
         "A global middleware registered first logs each request before any route logic runs."),
        ("INTERMEDIATE", "What is the main difference between application-level and router-level middleware?",
         ["router-level middleware only applies to routes under that router", "application middleware runs only in production", "router middleware cannot use next()", "application middleware can only parse JSON"], "D",
         "Router-level middleware scopes its effect to the router's path prefix, unlike global app.use()."),
        ("INTERMEDIATE", "Which of the following is the correct signature for an Express error handler?",
         ["function(err, req, res, next)", "function(req, res)", "function(err)", "function(req, res, err, next)"], "A",
         "Express recognizes error handlers by the four arguments in the exact order err, req, res, next."),
        ("INTERMEDIATE", "Consider app.use('/admin', adminRouter). Which requests does this middleware affect?",
         ["all requests whose path starts with /admin", "only POST /admin", "only GET /admin", "every request to the server"], "B",
         "Mounting at '/admin' restricts the middleware to requests under that path prefix."),
        ("ADVANCED", "Why is it a problem to place an error-handling middleware before the routes in an Express app?",
         ["it never sees errors because routes run after it", "it slows down the server", "it cannot be async", "it breaks JSON parsing"], "C",
         "Errors are forwarded to error handlers only after routes run, so an error handler placed first never triggers."),
        ("ADVANCED", "An async route handler rejects a Promise and no error middleware exists. What happens to the request?",
         ["the process may crash and the client never gets a response", "Express auto-sends a 200", "the request is retried", "the client receives a blank page"], "D",
         "Rejected promises in async handlers are unhandled unless caught or forwarded to error middleware, which can crash the server."),
        ("ADVANCED", "What is the recommended structure of a centralized error-handling strategy in Express?",
         ["a single error middleware that maps error types to status codes and responses", "hundreds of try/catch blocks in every route", "silently swallowing errors", "sending every error as a 500"], "A",
         "Central error middleware normalizes errors, logs them, and returns consistent responses in one place."),
        ("ADVANCED", "Which of the following best describes the optimal ordering of middleware in a typical Express app?",
         ["body parsing, then auth, then routes, then 404, then error handler", "routes first, then auth, then parsing", "error handler first, then routes", "all middleware after routes"], "C",
         "Parse request data early, guard with auth, run business routes, catch unmatched with 404, and handle errors last."),
        ("ADVANCED", "A logging middleware wraps res.json() to measure response time. What must it do after recording?",
         ["restore or call the original method and let the response continue", "stop the response from being sent", "call next() twice", "return a new status code"], "D",
         "The wrapper must still produce the original behavior so the client receives the real response."),
        ("ADVANCED", "Which pattern lets a route handler share a heavy computation across all requests in Express?",
         ["a singleton module cached after first use", "recomputing in every route", "inline code duplication", "creating a new database each request"], "A",
         "A singleton module caches the result once and reuses it across requests, avoiding repeated heavy work."),
         ("ADVANCED", "Why should a request-rate-limiting middleware be registered early in the middleware chain?",
         ["it rejects abusive traffic before expensive handlers run", "it makes logs prettier", "it requires the response body", "it replaces authentication"], "B",
         "Early registration ensures excessive requests are blocked before they consume route processing resources."),
        ("ADVANCED", "In Express 4 and later, which mechanism must you use to handle errors from an async/await route handler?",
         ["catch the promise and call next(err)", "ignore the rejection", "return the error as JSON", "restart the event loop"], "C",
         "Since Express 4 does not auto-catch async rejections, you must catch them and forward via next(err)."),
        ("ADVANCED", "An app returns the raw stack trace to clients on every error. Why is this a security risk?",
         ["it leaks internal paths and implementation details to attackers", "it makes responses slower", "it breaks JSON parsing", "it exposes user passwords"], "D",
         "Stack traces reveal server internals that help attackers map the application, so they should only be logged server-side."),
        ("ADVANCED", "Which middleware approach best enforces that only the API prefix uses JSON parsing?",
         ["mount express.json() on the /api router instead of globally", "parse JSON in every route manually", "disable all parsing", "use a global catch-all parser"], "A",
         "Scoping the parser to the API router keeps it from processing other paths unnecessarily."),
    ],
    140: [
        ("BEGINNER", "Which practice protects passwords at rest in a database?",
         ["hashing with salt", "storing plain text", "encoding in base64", "duplicating across tables"], "A",
         "Salted hashing makes stored passwords unreadable and resistant to reverse lookup attacks."),
        ("BEGINNER", "Which HTTP header enables encrypted communication between browser and server?",
         ["HTTPS/TLS", "Content-Type", "Accept-Language", "User-Agent"], "B",
         "HTTPS uses TLS to encrypt traffic in transit between client and server."),
        ("BEGINNER", "What does CORS stand for?",
         ["Cross-Origin Resource Sharing", "Common Origin Resource System", "Cross-Origin Request Security", "Central Origin Routing Service"], "C",
         "CORS is a browser security mechanism controlling which origins may access a resource."),
        ("BEGINNER", "What is the main purpose of an SQL injection prevention technique?",
         ["to prevent attackers from injecting malicious SQL into queries", "to speed up database lookups", "to reduce disk usage", "to encrypt the database"], "D",
         "Parameterized queries and input validation stop attackers from altering SQL statements."),
        ("BEGINNER", "Which attack involves tricking a user's browser into sending unwanted authenticated requests?",
         ["CSRF", "XSS", "DDoS", "MITM"], "A",
         "CSRF (Cross-Site Request Forgery) makes a victim's browser perform unwanted actions on an authenticated site."),
         ("BEGINNER", "What is a Web Application Firewall (WAF) designed to do?",
          ["inspect and filter HTTP traffic to block web attacks", "compile the backend source code", "manage database backups", "optimize CSS files"], "A",
          "A WAF sits in front of a web application and filters malicious HTTP requests, blocking common attacks such as SQL injection and XSS."),
        ("BEGINNER", "Which security header prevents a browser from MIME-sniffing responses?",
         ["X-Content-Type-Options", "Content-Length", "ETag", "Connection"], "C",
         "X-Content-Type-Options: nosniff stops browsers from guessing content types."),
        ("BEGINNER", "What is the main goal of rate limiting?",
         ["to cap how many requests a client can make in a period", "to increase server memory", "to change HTTP status codes", "to compress responses"], "D",
         "Rate limiting restricts request volume, protecting services from abuse and brute force."),
        ("BEGINNER", "What does a horizontal scaling strategy add to handle more traffic?",
         ["more server instances", "a faster CPU on one machine", "more RAM on a single server", "a larger hard drive"], "A",
         "Horizontal scaling adds more instances to distribute load across machines."),
        ("BEGINNER", "Which HTTP header must be present for cross-origin requests to be allowed by CORS?",
         ["Access-Control-Allow-Origin", "X-CSRF-Token", "Referer", "Content-Disposition"], "B",
         "Access-Control-Allow-Origin tells the browser which origins are permitted to access the resource."),
        ("INTERMEDIATE", "Which security header is specifically designed to block a page from being loaded inside an iframe?",
         ["X-Frame-Options", "X-Content-Type-Options", "Cache-Control", "Accept-Encoding"], "A",
         "X-Frame-Options prevents clickjacking by forbidding framing of the page."),
        ("INTERMEDIATE", "Which statement best describes the difference between scaling up and scaling out?",
         ["scaling up adds resources to one machine while scaling out adds more machines", "they are identical", "scaling up adds more machines", "scaling out upgrades the CPU"], "B",
         "Vertical scaling (up) strengthens a single machine; horizontal scaling (out) adds more instances."),
        ("INTERMEDIATE", "Consider an API query built by concatenating user input directly into SQL. What attack is most likely?",
         ["SQL injection", "XSS", "CSRF", "session fixation"], "C",
         "Concatenating unsanitized input into SQL lets attackers break out of the query and inject their own statements."),
        ("INTERMEDIATE", "Which tool would you use in front of a Node.js service to handle load balancing?",
         ["nginx", "bcrypt", "jsonwebtoken", "nodemon"], "D",
         "nginx is a reverse proxy that can distribute requests across multiple app instances."),
        ("INTERMEDIATE", "Which approach ensures secrets like API keys are not exposed in the front-end code?",
         ["keep them only on the server", "embed them in HTML comments", "hardcode them in a public JS file", "put them in a data attribute"], "A",
         "Anything shipped to the browser is visible to users, so secrets must live server-side only."),
        ("INTERMEDIATE", "What does a Content Security Policy (CSP) header help prevent?",
         ["XSS attacks by restricting allowed scripts and resources", "SQL injection", "server crashes", "slow network requests"], "B",
         "CSP restricts which scripts and sources can run, blocking many injected script attacks."),
        ("INTERMEDIATE", "Which strategy helps a stateless API survive the loss of any single server?",
         ["running multiple instances behind a load balancer", "storing sessions in process memory", "using only one server", "disabling replication"], "C",
         "Multiple interchangeable instances behind a load balancer keep the service available if one fails."),
        ("INTERMEDIATE", "Which approach best protects sensitive fields in a JWT payload?",
         ["do not put secrets in the payload and keep the token's scope minimal", "store the password in the payload", "repeat claims many times", "use a longer username"], "D",
         "JWTs are base64-encoded, not encrypted, so sensitive data must be kept out of the payload."),
        ("INTERMEDIATE", "What is the primary benefit of using parameterized queries over string interpolation in SQL?",
         ["they separate query structure from user data, preventing injection", "they make queries faster", "they return more rows", "they disable indexing"], "A",
         "Parameterized queries treat input as data, never as executable SQL, eliminating injection."),
        ("INTERMEDIATE", "Which header, when set, tells browsers not to cache sensitive responses?",
         ["Cache-Control: no-store", "Content-Length", "Keep-Alive", "Last-Modified"], "B",
         "Cache-Control: no-store prevents browsers and proxies from persisting sensitive responses."),
        ("ADVANCED", "Your Node service is stateless and scaled horizontally. Which is the best session strategy?",
         ["store sessions in a shared store like Redis", "store sessions in each instance's memory", "rely on process variables", "disable sessions entirely"], "A",
         "A shared store lets any instance read the same session, preserving state across instances."),
        ("ADVANCED", "An attacker floods the login endpoint with many requests to guess passwords. Which countermeasure is most effective?",
         ["rate limiting plus account lockout after failed attempts", "increasing the bcrypt rounds", "shortening passwords", "logging every attempt"], "D",
         "Rate limiting and lockout throttle and stop brute-force guessing at the source."),
        ("ADVANCED", "Why is it important to validate input length and format before storing user data?",
         ["it prevents buffer overflows, injection, and storage abuse", "it speeds up the database", "it makes passwords optional", "it removes the need for HTTPS"], "A",
         "Strict validation reduces attack surface and prevents malformed data from harming the system."),
        ("ADVANCED", "Which deployment practice provides the strongest defense against a single compromised server being fully controlled?",
         ["run each service with least-privilege and isolate workloads in containers", "run everything as root", "open all firewall ports", "share one database password"], "B",
         "Least-privilege accounts and container isolation limit the blast radius of a compromise to a single workload."),
         ("ADVANCED", "A sudden traffic spike comes from a few IPs. Which response best protects availability?",
         ["apply aggressive rate limiting and block anomalous sources", "remove all limits", "double server memory", "disable HTTPS"], "C",
         "Limiting anomalous sources prevents a single abusive client from exhausting the service."),
        ("ADVANCED", "Why should a production service be behind HTTPS termination at the load balancer?",
         ["so traffic is encrypted before it reaches the backend", "to expose plaintext traffic", "to speed up decryption", "to remove authentication"], "D",
         "Terminating TLS at the edge ensures all client traffic is encrypted in transit."),
        ("ADVANCED", "Which approach is the best defense-in-depth combination for a production API?",
         ["TLS, input validation, rate limiting, CSP, parameterized queries, and least privilege", "only using HTTPS", "only using a secret header", "only adding more servers"], "A",
         "Defense in depth layers independent controls so a failure in any one is covered by the others."),
        ("ADVANCED", "What is the best practice for handling dependency vulnerabilities in a Node project?",
         ["run npm audit regularly and update vulnerable packages", "ignore the warnings", "disable all dependencies", "remove package-lock.json"], "D",
         "npm audit flags known vulnerabilities, and updating packages patches them promptly."),
        ("ADVANCED", "Which statement best describes vertical scaling for a database?",
         ["buying a more powerful machine, which has a hard upper limit", "adding more database replicas", "sharding data across clusters", "running multiple app instances"], "A",
         "Vertical scaling improves one machine until a hardware ceiling, unlike horizontal options."),
        ("ADVANCED", "Why does a reverse proxy like nginx improve the security of a Node.js service?",
         ["it can terminate TLS, filter malicious traffic, and hide backend details", "it removes the need for authentication", "it makes the app code smaller", "it replaces the database"], "B",
         "A reverse proxy adds a hardened edge that handles TLS, access control, and traffic filtering."),
    ],
}
