# -*- coding: utf-8 -*-
"""
Question bank for subject 25: AI105 - NLP & Computer Vision.
Category: Artificial Intelligence & Data Science.

Topics:
  121: NLP Basics & Tokenization
  122: Text Processing & Features
  123: Computer Vision Basics
  124: Image Processing & Features
  125: CV & NLP Applications

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    121: [
        ("BEGINNER", "What does NLP stand for in artificial intelligence?",
         ["Natural Language Processing", "Neural Language Programming", "Natural Logic Processing", "Neural Linear Programming"], "A",
         "NLP is the branch of AI concerned with understanding and generating human language."),
        ("BEGINNER", "What is tokenization in NLP?",
         ["removing stop words", "splitting text into smaller units called tokens", "translating text between languages", "tagging words with their parts of speech"], "B",
         "Tokenization breaks a text into smaller units such as words, which are then analyzed."),
        ("BEGINNER", "What is a token in natural language processing?",
         ["a whole document", "a list of documents", "a single word or subword unit extracted from text", "a punctuation mark only"], "C",
         "A token is a meaningful unit, typically a word or subword, produced by splitting text."),
        ("BEGINNER", "Which of the following is an example of a corpus in NLP?",
         ["a single sentence", "a tokenizer", "a word embedding vector", "a large collection of documents used for training models"], "D",
         "A corpus is a large, structured collection of texts used for training and evaluation."),
        ("BEGINNER", "What are stop words in NLP?",
         ["common words like 'the' and 'and' that are often removed before analysis", "rare technical terms kept for analysis", "punctuation marks used to split sentences", "numbers that must be normalized to words"], "A",
         "Stop words are very frequent, low-information words that are usually filtered out."),
        ("BEGINNER", "Which step typically comes first in a basic NLP pipeline?",
         ["object detection", "tokenization", "image segmentation", "speech synthesis"], "B",
         "Tokenization is the first step because every later analysis operates on the tokens."),
        ("BEGINNER", "Which of the following is a basic NLP task?",
         ["edge detection", "image classification", "word tokenization", "motion tracking"], "C",
         "Word tokenization is a fundamental NLP task, unlike the vision tasks listed."),
        ("BEGINNER", "What is a document in NLP terminology?",
         ["a binary pixel array", "a single character", "a neural network layer", "a body of text treated as a single unit of analysis"], "D",
         "A document is any self-contained unit of text that is analyzed as a whole."),
        ("BEGINNER", "Which character is most commonly used to separate words during tokenization?",
         ["a space", "a comma", "a semicolon", "a tab"], "A",
         "Whitespace tokenization splits text on space characters, the most common word delimiter."),
        ("BEGINNER", "What is the output of a basic word tokenizer?",
         ["a single token", "a sequence of tokens", "a labeled image", "a sorted list of characters"], "B",
         "A tokenizer returns an ordered sequence of tokens derived from the input text."),
        ("INTERMEDIATE", "How many tokens does whitespace tokenization produce for the sentence 'The quick brown fox jumps'?",
         ["3", "4", "6", "5"], "D",
         "There are exactly five words separated by spaces, so five tokens are produced."),
        ("INTERMEDIATE", "The sentence 'She said, Hello!' with punctuation removed contains how many word tokens?",
         ["4", "5", "3", "2"], "C",
         "After removing the comma and exclamation mark the tokens are She, said and Hello, which is three."),
        ("INTERMEDIATE", "What is a subword tokenizer such as BPE mainly used for?",
         ["to merge sentences into paragraphs", "to split words into smaller meaningful pieces to handle rare and out-of-vocabulary words", "to remove all punctuation from the text", "to count how many documents exist in a corpus"], "B",
         "Subword tokenizers break words into smaller pieces so that rare and unseen words can still be represented."),
        ("INTERMEDIATE", "What is the difference between stemming and lemmatization?",
         ["stemming chops endings without a vocabulary, while lemmatization uses a dictionary to return base forms", "lemmatization is faster than stemming", "stemming always produces valid English words", "they are two names for the same operation"], "A",
         "Stemming applies crude rules, while lemmatization consults a lexicon to produce real base forms."),
        ("INTERMEDIATE", "For the string 'New York is a city', if 'New York' is kept as a single token, how many tokens result?",
         ["2", "3", "5", "4"], "D",
         "The tokens are New York, is, a and city, giving four tokens in total."),
        ("INTERMEDIATE", "A corpus has 1000 documents and each document averages 120 tokens. Approximately how many tokens are in the corpus?",
         ["100000", "120000", "1200", "1000"], "B",
         "Multiplying 1000 documents by 120 tokens gives about 120000 tokens."),
        ("INTERMEDIATE", "What is a common problem with whitespace tokenization of text like 'can't' or 'U.S.A.'?",
         ["it splits words into characters", "it is extremely slow on short text", "contractions and abbreviations are split into fragments that lose meaning", "it always merges multiple words together"], "C",
         "Whitespace tokenization leaves apostrophes and periods attached, breaking contractions and abbreviations incorrectly."),
        ("INTERMEDIATE", "What does the choice between word-level and subword-level tokenization mainly affect?",
         ["the vocabulary size and the handling of rare or unseen words", "the color depth of the image", "the length of the document in characters only", "the number of sentences in the document"], "A",
         "Subword tokenization shrinks the vocabulary and gives a way to represent words that were never seen in training."),
        ("INTERMEDIATE", "Why might lowercase normalization be applied during tokenization?",
         ["to increase model accuracy for named entities", "to keep proper nouns distinct", "to preserve punctuation", "to reduce the vocabulary size by treating words case-insensitively"], "D",
         "Lowercasing collapses 'The' and 'the' into one token, shrinking the vocabulary."),
        ("INTERMEDIATE", "Which of the following is a widely used multilingual subword tokenization algorithm?",
         ["ImageNet", "Eigenfaces", "Byte Pair Encoding (BPE)", "K-means clustering"], "C",
         "BPE learns a subword vocabulary from byte statistics and works across many languages."),
        ("ADVANCED", "Why is standard whitespace tokenization problematic when building a tokenizer for Twitter data?",
         ["the whitespace is always reliable on Twitter", "tweets contain hashtags, mentions, emojis and URLs that need special handling", "tweets are too short to tokenize", "tokenizers cannot run on social media text"], "B",
         "Social media text is full of hashtags, mentions, emojis and URLs that require custom rules."),
        ("ADVANCED", "How many sentences should a correct sentence tokenizer output for 'Dr. Smith went to Washington. He met Sen. Adams.'?",
         ["2", "3", "4", "5"], "A",
         "There are two real sentences because the periods in 'Dr.' and 'Sen.' are abbreviations, not sentence boundaries."),
        ("ADVANCED", "What is a key advantage of subword tokenization such as WordPiece over plain word-level tokenization for neural models?",
         ["it removes all ambiguity from text", "it makes every token a full dictionary word", "it always increases the sequence length", "it balances a fixed vocabulary with the ability to represent rare and unseen words"], "D",
         "Subword tokenization keeps the vocabulary bounded while still covering rare and unknown words."),
        ("ADVANCED", "At a scale of 10 million documents, which factor most limits the throughput of a Python regex-based tokenizer on a single CPU?",
         ["the color of the corpus text", "the output file format", "the sequential regex processing speed on a single CPU", "the length of the tokenizer source code"], "C",
         "Regex matching runs sequentially on one CPU and becomes a bottleneck for very large corpora."),
        ("ADVANCED", "In Byte Pair Encoding, what does the merge step do?",
         ["it removes the rarest characters from the text", "it repeatedly merges the most frequent adjacent pairs of tokens into new tokens", "it translates the text to another language", "it sorts the vocabulary in alphabetical order"], "B",
         "BPE iteratively merges the most frequent adjacent token pairs to grow its subword vocabulary."),
        ("ADVANCED", "Why might a tokenizer that strips all punctuation hurt a sentiment analysis model?",
         ["punctuation like '!!!' carries sentiment information and emojis may be lost", "punctuation is always neutral in meaning", "stripping punctuation speeds up the model", "punctuation never appears in reviews"], "A",
         "Exclamation marks and emojis encode strong sentiment, so removing them destroys signal."),
        ("ADVANCED", "What is the key algorithmic difference between BPE and WordPiece?",
         ["they are identical algorithms", "WordPiece merges random pairs", "BPE works only on English text", "BPE merges the most frequent byte pair, while WordPiece merges the pair that maximizes language-model likelihood"], "D",
         "BPE is driven by raw pair frequency, whereas WordPiece chooses pairs that best improve the model likelihood."),
        ("ADVANCED", "When tokenizing source code identifiers like 'user_id' or 'camelCase', which preprocessing helps the most?",
         ["lowercasing every character", "removing all letters", "splitting on underscores and detecting camel-case boundaries", "translating identifiers to English words"], "C",
         "Splitting on underscores and detecting case transitions recovers the meaningful word components."),
        ("ADVANCED", "An out-of-vocabulary word appears during inference that the model never saw in training. With subword tokenization, how is it typically handled?",
         ["the word is dropped from the output", "it is represented by composing its known subword pieces", "the model must be retrained", "the whole sentence is discarded"], "B",
         "The word is covered by combining its subword units, which is exactly why subword tokenization is used."),
        ("ADVANCED", "What trade-off must be made when choosing the vocabulary size of a BPE tokenizer?",
         ["a larger vocabulary gives shorter sequences but needs more parameters and memory", "a larger vocabulary always improves accuracy without cost", "a smaller vocabulary gives shorter sequences", "vocabulary size has no effect on the model"], "A",
         "Bigger vocabularies encode text more compactly but require a larger embedding table and more memory."),
    ],
    122: [
        ("BEGINNER", "What does TF stand for in the TF-IDF weighting scheme?",
         ["image frequency", "inverse feature map", "term frequency, how often a term appears in a document", "tensor flow"], "C",
         "Term frequency counts how many times a term occurs within a single document."),
        ("BEGINNER", "What does IDF stand for in the TF-IDF weighting scheme?",
         ["a deep network", "a pooling layer", "a token", "inverse document frequency, how rare a term is across the corpus"], "D",
         "Inverse document frequency measures how rare a term is across all documents in the corpus."),
        ("BEGINNER", "Which of the following is a bag-of-words representation of a text?",
         ["a vector counting how many times each vocabulary word appears in a text", "a list of all sentences", "an image of pixel intensities", "a sorted set of unique characters"], "A",
         "The bag-of-words model represents text as a vector of word counts without regard to order."),
        ("BEGINNER", "What is an n-gram?",
         ["a machine learning model", "a contiguous sequence of n items from a text", "a type of neural network", "a database index"], "B",
         "An n-gram is any contiguous sequence of n tokens drawn from a piece of text."),
        ("BEGINNER", "Which of the following is a unigram feature?",
         ["a paragraph", "a chapter", "the word 'cat' in a sentence", "an entire corpus"], "C",
         "A unigram is a single word, so the word 'cat' is an example of a unigram feature."),
        ("BEGINNER", "What is a document-term matrix?",
         ["a matrix of pixel values", "a confusion matrix", "a covariance matrix", "a matrix where rows are documents and columns are vocabulary terms"], "D",
         "A document-term matrix records the weight of each vocabulary term for each document."),
        ("BEGINNER", "What is TF-IDF weighting used for?",
         ["to weight the importance of a term for a document relative to the corpus", "to compress images", "to detect faces", "to translate languages"], "A",
         "TF-IDF assigns higher weights to terms that are frequent in a document but rare across the corpus."),
        ("BEGINNER", "What does stemming do in text processing?",
         ["removes all vowels", "reduces words to their root form, such as 'running' to 'run'", "adds prefixes to words", "sorts words alphabetically"], "B",
         "Stemming strips affixes so that inflected forms collapse to a common root."),
        ("BEGINNER", "Which of the following is a bigram of the sentence 'I love NLP'?",
         ["I love NLP", "love NLP", "NLP I", "I NLP love"], "C",
         "A bigram is a sequence of two adjacent words, and 'love NLP' fits that definition."),
        ("BEGINNER", "What is text normalization?",
         ["training a neural network", "compressing images", "parsing a web page", "converting text to a standard form such as lowercasing and removing punctuation"], "D",
         "Normalization brings text into a consistent form so that later features are cleaner."),
        ("INTERMEDIATE", "In a 15-word document, the word 'cat' appears 3 times. What is the raw term frequency of 'cat'?",
         ["3", "4", "15", "0"], "A",
         "Term frequency is simply the count of the term in the document, which is 3."),
        ("INTERMEDIATE", "A term appears in 2 of 10 documents. What is its document frequency?",
         ["1", "2", "10", "8"], "B",
         "Document frequency is the number of documents containing the term, which is 2."),
        ("INTERMEDIATE", "Which term will TF-IDF weight higher for a document: 'the' appearing many times or a rare domain term appearing once?",
         ["the word 'the'", "both equally", "the rare domain term, because IDF rewards rarity", "neither, because TF-IDF ignores frequency"], "C",
         "The rare term has a high IDF, so TF-IDF rewards it even though it appears only once."),
        ("INTERMEDIATE", "What are the bigrams of the sentence 'the cat sat on the mat'?",
         ["cat, mat, sat, the", "the cat sat on the mat", "the, cat", "the cat, cat sat, sat on, on the, the mat"], "D",
         "Each adjacent pair forms a bigram, giving five bigrams for this six-word sentence."),
        ("INTERMEDIATE", "With TF-IDF, what happens to terms that appear in every document, such as 'the'?",
         ["their IDF becomes near zero, so they receive low weight", "their IDF becomes very large", "their TF is set to zero", "they are removed from the vocabulary permanently"], "A",
         "A term in all documents has a document frequency equal to the corpus size, making its IDF near zero."),
        ("INTERMEDIATE", "How many unigrams does the string 'I love NLP' produce after whitespace tokenization?",
         ["1", "3", "5", "2"], "B",
         "The string splits into the three words I, love and NLP, giving three unigrams."),
        ("INTERMEDIATE", "What information does the bag-of-words representation lose?",
         ["the total word count", "the document length", "word order and grammar", "the encoding used"], "C",
         "Bag-of-words only keeps counts, so the order in which words appear is discarded."),
        ("INTERMEDIATE", "What is the difference between term frequency and document frequency?",
         ["they are identical", "document frequency counts within a document", "term frequency counts across documents", "term frequency counts within a document; document frequency counts across documents"], "D",
         "Term frequency is per-document, while document frequency is a count of documents containing the term."),
        ("INTERMEDIATE", "Why is stop word removal often applied before building TF-IDF features?",
         ["to remove very common words that carry little discriminative value", "to keep every word in the vocabulary", "to shorten the documents", "to improve spelling"], "A",
         "Stop words are common and uninformative, so removing them reduces noise in the feature space."),
        ("INTERMEDIATE", "In the IDF formula log(N/df), what happens to the value as df approaches N?",
         ["the value approaches infinity", "the value approaches 0", "the value stays at 1", "the value becomes negative"], "B",
         "When a term appears in nearly all N documents, N/df approaches 1 and its log approaches 0."),
        ("ADVANCED", "When building TF-IDF vectors for 50k documents with a large vocabulary, why is a sparse matrix preferred over a dense one?",
         ["sparse matrices are always slower", "dense matrices are always smaller", "documents cannot be stored in matrices", "most entries are zero and a sparse representation saves memory"], "D",
         "Each document uses only a few of the vocabulary terms, so a sparse matrix avoids storing mostly zero entries."),
        ("ADVANCED", "A corpus has 1000 documents and the term 'data' appears in 250 of them. Ignoring smoothing, what is the IDF term for 'data'?",
         ["log(250)", "log(1000)", "log(4)", "250"], "C",
         "The IDF is log(1000/250), which simplifies to log(4)."),
        ("ADVANCED", "Why are character n-grams preferred over word n-grams for noisy social media text?",
         ["they capture long-range syntax perfectly", "they are robust to spelling variations and abbreviations", "they ignore all meaning", "they always produce exactly one feature per sentence"], "B",
         "Character n-grams tolerate misspellings and shorthand because they match on character substrings."),
        ("ADVANCED", "Which normalization of TF-IDF document vectors often improves the performance of text classifiers?",
         ["L2 (Euclidean) normalization of each document vector", "removing all numeric features", "increasing the vocabulary size randomly", "using only the first character of each word"], "A",
         "L2 normalization makes all documents unit-length, which stabilizes similarity and many classifiers."),
        ("ADVANCED", "After computing TF-IDF vectors, which similarity measure is most commonly used to compare two documents?",
         ["Euclidean distance only", "Manhattan distance only", "Hamming distance", "cosine similarity"], "D",
         "Cosine similarity measures the angle between vectors and is standard for TF-IDF comparisons."),
        ("ADVANCED", "A term appears frequently in every document of a corpus. How is its TF-IDF weight best described?",
         ["very high, because it appears often", "exactly zero, always", "very low, because IDF approaches zero", "undefined"], "C",
         "Because the term is in all documents its IDF is near zero, pulling the whole weight down."),
        ("ADVANCED", "With 1 million documents and a vocabulary of 100k terms, what is the memory concern with a dense document-term matrix?",
         ["it would fit in a few megabytes", "a dense matrix would need 100 billion entries, which is infeasible", "sparse matrices cannot store 1 million documents", "the vocabulary must be reduced to 100 terms"], "B",
         "A dense matrix would hold 1 million times 100k, or 100 billion, entries, which is far too large."),
        ("ADVANCED", "What is a serious problem with pure bag-of-words features for sentiment analysis?",
         ["it ignores negation, so 'not good' looks like 'good'", "it always knows the word order", "it cannot count words", "it only uses nouns"], "A",
         "Without word order, the phrase 'not good' is reduced to the positive word 'good'."),
        ("ADVANCED", "What is the effect of using sublinear term-frequency scoring such as 1 + log(tf)?",
         ["it boosts rare terms more", "it removes all terms", "it doubles every term frequency", "it dampens the effect of very high term frequencies"], "D",
         "The log transform compresses large counts so that very frequent terms do not dominate."),
        ("ADVANCED", "A TF-IDF model trained on English news is applied to code-mixed Hindi-English text. What is the most likely problem?",
         ["English is easier to tokenize", "news text has no punctuation", "the vocabulary and IDF statistics do not match the target domain", "code-mixed text is always perfectly tokenized"], "C",
         "Domain mismatch means the learned vocabulary and IDF weights do not fit the new data."),
    ],
    123: [
        ("BEGINNER", "How is an image represented for a computer vision system?",
         ["a list of words", "a 2D grid of pixel intensity values", "a graph of characters", "a collection of audio samples"], "B",
         "A digital image is stored as a two-dimensional grid of pixel values."),
        ("BEGINNER", "What is a pixel?",
         ["the smallest unit of an image, holding a brightness or color value", "a line of text", "a neural network", "a whole photo"], "A",
         "A pixel is the smallest addressable element of an image, storing intensity or color."),
        ("BEGINNER", "What does RGB stand for?",
         ["Random, Gray, Black", "Red, Gray, Blue", "Green, Red, Binary", "Red, Green, Blue"], "D",
         "RGB is the color model built from the three additive primary colors red, green and blue."),
        ("BEGINNER", "A grayscale image typically has how many color channels?",
         ["three", "two", "one", "four"], "C",
         "Grayscale images use a single channel that holds the intensity of each pixel."),
        ("BEGINNER", "What is image classification?",
         ["finding the subject's age", "assigning a label to an entire image", "predicting the next word", "translating speech to text"], "B",
         "Image classification assigns one class label to the whole image."),
        ("BEGINNER", "What is object detection?",
         ["locating objects in an image and classifying them", "converting text to speech", "summarizing a document", "clustering documents"], "A",
         "Object detection finds bounding boxes around objects and labels each one."),
        ("BEGINNER", "Which dataset is most commonly used for image classification benchmarks?",
         ["LibriSpeech", "MSP-IMPROV", "CoNLL-2003", "ImageNet"], "D",
         "ImageNet is the standard benchmark for image classification research."),
        ("BEGINNER", "How is an RGB image of height H and width W stored?",
         ["a single integer", "a string of characters", "a three-channel array of shape (H, W, 3)", "a binary decision tree"], "C",
         "An RGB image is a three-dimensional array with one channel per color."),
        ("BEGINNER", "What is image segmentation?",
         ["assigning one label to the whole image", "classifying each pixel of an image into a category", "finding the nearest image in a database", "ranking documents by relevance"], "B",
         "Segmentation labels every pixel so that different regions belong to different classes."),
        ("BEGINNER", "In a grayscale image, what does a pixel value of 0 represent?",
         ["black", "white", "red", "transparent"], "A",
         "In 8-bit grayscale, a value of 0 corresponds to the darkest intensity, black."),
        ("INTERMEDIATE", "A 640x480 RGB image stored as unsigned 8-bit integers contains how many bytes?",
         ["307200", "640", "921600", "480"], "C",
         "640 times 480 pixels times 3 channels gives 921600 bytes."),
        ("INTERMEDIATE", "A 512x512 grayscale image contains how many pixels?",
         ["512", "1024", "51200", "262144"], "D",
         "512 multiplied by 512 equals 262144 pixels."),
        ("INTERMEDIATE", "What does a kernel or filter in a convolutional layer do?",
         ["slides over the image to detect local features", "labels each pixel manually", "compresses the image to one byte", "generates captions for the image"], "A",
         "A filter slides across the image and computes weighted sums to detect local patterns."),
        ("INTERMEDIATE", "What is stride in a convolutional operation?",
         ["the number of filters", "the step size by which the filter moves across the image", "the number of channels", "the learning rate"], "B",
         "Stride controls how far the filter moves at each step across the input."),
        ("INTERMEDIATE", "Why is padding used in convolution?",
         ["to increase the number of classes", "to remove noise entirely", "to preserve spatial dimensions and use edge pixels", "to double the image size always"], "C",
         "Padding adds a border of zeros so the output size is preserved and edge pixels are included."),
        ("INTERMEDIATE", "A 5x5 image convolved with a 3x3 filter using stride 1 and no padding gives an output of what size?",
         ["5x5", "4x4", "7x7", "3x3"], "D",
         "Without padding, the output is (5-3+1) by (5-3+1), which is 3x3."),
         ("INTERMEDIATE", "What is global average pooling commonly used for at the end of a classification CNN?",
          ["replacing the flatten-and-fully-connected block to produce a class score vector", "blurring the input image", "increasing the spatial resolution", "reducing the number of classes"], "A",
          "Global average pooling averages each feature map into a single value, creating a compact vector for classification while reducing parameters and overfitting."),
        ("INTERMEDIATE", "What does max pooling do?",
         ["averages all values in the image", "takes the maximum value in each pooling window", "takes the minimum value of the whole image", "sums the pixel values"], "B",
         "Max pooling keeps the largest value inside each small window of the feature map."),
        ("INTERMEDIATE", "What is a convolution in image terms?",
         ["a bitwise OR of pixels", "a random shuffle of pixels", "an element-wise product and sum between a filter and an image patch", "a simple pixel value swap"], "C",
         "Convolution multiplies a filter elementwise with an image patch and sums the result."),
        ("INTERMEDIATE", "What does a larger receptive field allow a convolutional network to perceive?",
         ["a smaller output", "fewer parameters", "better color accuracy", "more context from a larger region of the image"], "D",
         "A larger receptive field lets deeper layers aggregate information from a wider image region."),
        ("ADVANCED", "Why do CNN feature maps typically increase in channels while shrinking in spatial size across layers?",
         ["to extract more abstract high-level features while keeping computation manageable", "to preserve the original pixel values", "to reduce the number of classes", "to make the model smaller by removing layers"], "A",
         "Deep layers encode richer abstractions in more channels while the smaller spatial size controls cost."),
        ("ADVANCED", "What is the receptive field of two stacked 3x3 filters compared with a single larger filter?",
         ["3x3", "5x5", "9x9", "1x1"], "B",
         "Two 3x3 filters cover a 5x5 region, matching one 5x5 filter with fewer parameters."),
        ("ADVANCED", "Why are 1x1 convolutions useful in modern CNNs?",
         ["they blur the image", "they detect edges only", "they mix channels cheaply to change the number of feature maps", "they increase spatial resolution"], "C",
         "A 1x1 convolution performs a linear combination of channels without changing spatial size."),
        ("ADVANCED", "What training problem does batch normalization primarily address?",
         ["overfitting", "class imbalance", "memory leaks", "internal covariate shift by normalizing layer inputs to stabilize training"], "D",
         "Batch normalization normalizes activations to keep layer inputs stable and training faster."),
        ("ADVANCED", "Which architecture introduced residual (skip) connections to combat vanishing gradients?",
         ["ResNet", "LeNet-1", "AlexNet without skip connections", "a linear regression"], "A",
         "ResNet's skip connections let gradients flow directly through identity paths, enabling very deep networks."),
        ("ADVANCED", "What is transfer learning in computer vision?",
         ["training from scratch each time", "fine-tuning a pretrained model on a new, often smaller dataset", "removing all pretrained weights", "using only random weights"], "B",
         "Transfer learning reuses features learned on a large dataset and adapts them to a new task."),
        ("ADVANCED", "When fine-tuning a pretrained network on a small dataset, what should typically be done with the early layers?",
         ["reinitialize them randomly", "delete them", "freeze them since they capture generic features such as edges and textures", "train them with a higher learning rate than the head"], "C",
         "Early layers learn generic low-level features that transfer well, so they are usually frozen."),
        ("ADVANCED", "What does data augmentation do for a vision model?",
         ["labels each image by hand", "compresses the model", "removes the need for a test set", "creates variations of the training images to improve generalization"], "D",
         "Augmentation applies transforms like flips and crops to enlarge the training distribution."),
        ("ADVANCED", "Which of the following is an example of data augmentation for images?",
         ["random horizontal flip", "random string replacement", "random document merging", "random audio mixing"], "A",
         "Flipping an image horizontally is a classic augmentation that creates a new training sample."),
        ("ADVANCED", "What is the role of the final fully connected layer in a classification CNN?",
         ["applies a blur kernel", "maps the learned features into class scores", "detects corners only", "reduces the number of images"], "B",
         "The last layer projects the feature vector into a score for each class, which softmax then normalizes."),
    ],
    124: [
        ("BEGINNER", "What is image resizing?",
         ["changing the file name", "adding a watermark", "converting to text", "changing the width and height of an image"], "D",
         "Resizing scales an image to new width and height dimensions."),
        ("BEGINNER", "What is an image filter?",
         ["a type of neural network", "a file format", "an operation that transforms pixel values, such as blur or sharpen", "a list of class labels"], "C",
         "A filter is an operation that transforms pixel values, for example to blur or sharpen."),
        ("BEGINNER", "What does image thresholding do?",
         ["detects faces", "converts pixels into two classes based on an intensity threshold", "merges two images", "compresses the image into a zip file"], "B",
         "Thresholding maps each pixel to one of two classes according to an intensity cutoff."),
        ("BEGINNER", "What is edge detection used for in image processing?",
         ["highlighting boundaries where intensity changes sharply", "removing the background color", "adding a caption", "blurring the whole image"], "A",
         "Edge detection locates boundaries where pixel intensity changes sharply."),
        ("BEGINNER", "What is an image histogram?",
         ["a sorted list of filenames", "a matrix of gradients", "a set of labels", "a distribution of pixel intensity values"], "D",
         "An image histogram shows how often each intensity value occurs."),
        ("BEGINNER", "What is contrast in an image?",
         ["the file size", "the resolution", "the difference in brightness between regions of an image", "the number of colors in the RGB model"], "C",
         "Contrast describes how much brightness differs between the light and dark areas of an image."),
        ("BEGINNER", "What is grayscale conversion?",
         ["adding a blue channel", "converting a color image to a single intensity channel", "rotating the image", "splitting the image into two files"], "B",
         "Grayscale conversion reduces an RGB image to a single luminance channel."),
        ("BEGINNER", "What is image cropping?",
         ["removing the region of the image outside a chosen rectangle", "increasing the contrast", "adding noise", "converting to grayscale"], "A",
         "Cropping keeps only the part of the image inside a selected rectangle."),
        ("BEGINNER", "What is brightness in image processing?",
         ["the number of edges", "the image format", "the resolution", "the overall light intensity of an image"], "D",
         "Brightness is the overall level of light intensity across an image."),
        ("BEGINNER", "What is the effect of applying a blur filter?",
         ["it sharpens every edge", "it adds random noise", "it smooths the image by averaging nearby pixels", "it removes color entirely"], "C",
         "Blurring averages neighboring pixel values, which smooths and softens the image."),
        ("INTERMEDIATE", "An image is downsampled from 2000x2000 to 1000x1000. What happens to its spatial resolution?",
         ["the resolution stays the same", "the resolution halves", "the resolution doubles", "the image becomes binary"], "B",
         "Both dimensions are halved, so the spatial resolution is cut in half."),
        ("INTERMEDIATE", "When a 3x3 average blur kernel is applied, what value is assigned to each output pixel?",
         ["the average of the 3x3 neighborhood", "the maximum of the 3x3 neighborhood", "the center pixel unchanged", "the sum of all pixels in the image"], "A",
         "The average filter replaces each pixel with the mean of its 3x3 neighborhood."),
        ("INTERMEDIATE", "What does histogram equalization do to an image?",
         ["removes all low values", "converts to binary", "adds noise", "redistributes intensities to improve contrast"], "D",
         "Histogram equalization spreads out intensity values to enhance contrast."),
        ("INTERMEDIATE", "Why is a low-pass filter (blur) applied before edge detection?",
         ["to increase the resolution", "to add color", "to reduce noise that would create false edges", "to speed up edge detection by removing pixels"], "C",
         "Blurring suppresses high-frequency noise that would otherwise create spurious edges."),
        ("INTERMEDIATE", "Applying a binary threshold at 128 to a grayscale image produces how many distinct output intensity levels?",
         ["256", "two", "128", "one"], "B",
         "A binary threshold maps every pixel to one of two values, typically 0 or 255."),
        ("INTERMEDIATE", "What does the Sobel operator compute?",
         ["image gradients used for edge detection", "a histogram of colors", "a machine learning classifier", "a type of image compression"], "A",
         "Sobel filters estimate the image gradient magnitude and direction for edge detection."),
        ("INTERMEDIATE", "Which morphological operation would you use to remove small white specks of noise from a binary image?",
         ["histogram equalization", "gamma correction", "color quantization", "morphological opening"], "D",
         "Opening applies erosion followed by dilation, which removes small bright specks."),
        ("INTERMEDIATE", "What does dilation do to a binary image?",
         ["shrinks white regions", "removes all white pixels", "expands white regions", "converts to grayscale"], "C",
         "Dilation grows the white regions by adding pixels to their boundaries."),
        ("INTERMEDIATE", "Why is the HSV color space often used instead of RGB for color thresholding?",
         ["to add more channels", "to separate color hue from intensity for easier thresholding", "to reduce the image to one pixel", "to increase the file size"], "B",
         "HSV isolates hue from illumination, so color regions can be selected by hue alone."),
        ("INTERMEDIATE", "In the Canny edge detector, what does non-maximum suppression do?",
         ["thins edges by keeping only local maxima of gradient magnitude", "blurs the gradient image", "doubles the edge width", "removes all edges"], "A",
         "Non-maximum suppression keeps only the strongest gradient response along each edge direction."),
        ("ADVANCED", "A photograph has very poor contrast in the shadowed areas. Which technique best improves visibility?",
         ["grayscale conversion only", "increasing brightness", "histogram equalization or CLAHE", "edge detection"], "C",
         "CLAHE enhances local contrast, making details in dark regions visible."),
        ("ADVANCED", "For OCR of scanned documents, which preprocessing sequence typically helps the most?",
         ["color inversion and rotation", "random cropping", "adding noise", "grayscale conversion, binarization and deskewing"], "D",
         "Grayscale conversion, thresholding and correcting skew give a clean binary text image."),
        ("ADVANCED", "Among thousands of frames, which statistic is a good indicator that a frame is blurry?",
         ["low variance of the Laplacian", "high saturation", "high average brightness", "large file size"], "A",
         "A blurry image has weak high-frequency content, giving a low-variance Laplacian response."),
        ("ADVANCED", "A Gaussian filter with a larger sigma produces what effect?",
         ["sharper edges", "more smoothing and a wider neighborhood influence", "no change", "a smaller image"], "B",
         "Larger sigma widens the Gaussian, blending more distant pixels and smoothing more."),
        ("ADVANCED", "What is morphological erosion useful for?",
         ["expanding white regions", "adding bright noise", "removing small bright noise and shrinking white regions", "doubling the resolution"], "C",
         "Erosion shrinks white regions and removes small bright artifacts from binary images."),
        ("ADVANCED", "In a 60 fps video pipeline running on embedded hardware, which operation should be minimized to keep up with real time?",
         ["image saving", "frame indexing", "reading the frame counter", "expensive full-image convolutions with large kernels"], "D",
         "Large-kernel full-image convolutions are computationally heavy and strain real-time throughput."),
        ("ADVANCED", "Why is the L*a*b* color space sometimes preferred over RGB for image segmentation?",
         ["L*a*b* separates luminance from perceptually meaningful color channels", "RGB is smaller than LAB", "LAB cannot represent colors", "LAB has fewer channels than grayscale"], "A",
         "L*a*b* isolates lightness so that color distances match human perception better."),
        ("ADVANCED", "What is the purpose of Otsu's method in image thresholding?",
         ["detecting faces", "automatically choosing a threshold that minimizes within-class variance", "converting to HSV", "adding contrast"], "B",
         "Otsu picks the threshold that best separates two intensity classes by minimizing within-class variance."),
        ("ADVANCED", "A camera produces 8-bit images but the useful intensities occupy only the 50-150 range. Which operation expands this range?",
         ["erosion", "dilation", "histogram stretching (min-max normalization)", "binary opening"], "C",
         "Min-max stretching rescales intensities so the full 0-255 range is used."),
        ("ADVANCED", "When merging several camera exposures into one HDR image, what is required before combining the frames?",
         ["downsampling each image", "removing color", "combining them randomly", "aligning the images before merging to avoid ghosting"], "D",
         "The frames must be aligned so that moving objects do not create ghost artifacts."),
    ],
    125: [
        ("BEGINNER", "What is machine translation?",
         ["automatically translating text from one language to another", "detecting faces in photos", "compressing videos", "generating music"], "A",
         "Machine translation converts text from a source language into a target language automatically."),
        ("BEGINNER", "What is named entity recognition (NER)?",
         ["counting pixels", "identifying entities such as persons, places and organizations in text", "blurring images", "recognizing speech"], "B",
         "NER locates and classifies named entities such as people, places and organizations."),
        ("BEGINNER", "What is sentiment analysis?",
         ["detecting edges", "predicting stock prices", "determining the emotion or opinion expressed in text", "classifying images"], "C",
         "Sentiment analysis classifies the opinion or emotion expressed in a piece of text."),
        ("BEGINNER", "What is a chatbot?",
         ["a virus scanner", "an image editor", "a database", "a program that holds a conversation with a user"], "D",
         "A chatbot is a system designed to converse with users in natural language."),
        ("BEGINNER", "What is facial recognition?",
         ["identifying or verifying a person from their face", "translating documents", "tokenizing text", "summarizing news"], "A",
         "Facial recognition identifies or verifies individuals using features of their face."),
        ("BEGINNER", "What is image captioning?",
         ["converting speech to text", "generating a natural language description of an image", "detecting spam emails", "clustering documents"], "B",
         "Image captioning generates a natural language sentence describing an image's content."),
        ("BEGINNER", "What is optical character recognition (OCR)?",
         ["recognizing faces", "translating audio", "extracting text from images or scanned documents", "predicting movie ratings"], "C",
         "OCR converts text embedded in images or scans into machine-readable characters."),
        ("BEGINNER", "What is the primary computer vision task in autonomous driving?",
         ["summarizing traffic reports", "translating signs", "playing chess", "detecting and tracking objects such as cars and pedestrians"], "D",
         "Self-driving systems rely heavily on detecting and tracking objects around the vehicle."),
        ("BEGINNER", "How can text be used in a recommendation system?",
         ["suggesting items using textual features such as reviews", "rendering 3D scenes", "detecting motion", "encoding audio"], "A",
         "Text like reviews and product descriptions provides features for recommending items."),
        ("BEGINNER", "What is text summarization?",
         ["converting a document to images", "producing a shorter version that preserves the main points", "translating a document", "printing a document"], "B",
         "Summarization condenses a document while keeping its most important information."),
        ("INTERMEDIATE", "Which architecture is most commonly used for modern neural machine translation?",
         ["the Perceptron", "Naive Bayes", "K-means", "the Transformer"], "D",
         "Transformer-based models dominate state-of-the-art machine translation systems."),
        ("INTERMEDIATE", "A review says 'The battery lasts long'. Which NLP task best extracts 'battery' as the product aspect being discussed?",
         ["named entity recognition", "machine translation", "aspect-based sentiment analysis", "text-to-speech"], "C",
         "Aspect-based sentiment analysis identifies the specific product aspect and its sentiment."),
        ("INTERMEDIATE", "For recognizing handwritten digits such as in the MNIST dataset, which model type is standard?",
         ["a decision tree on raw pixels", "a CNN", "a logistic regression on pixels only", "an A* search"], "B",
         "CNNs learn spatial features and achieve the best accuracy on handwritten digit recognition."),
        ("INTERMEDIATE", "What is the primary input to a Transformer model for translation?",
         ["token embeddings plus positional encodings", "only raw pixel values", "only random numbers", "a sorted list of words"], "A",
         "Transformers take token embeddings combined with positional encodings to preserve word order."),
        ("INTERMEDIATE", "In a visual question answering (VQA) system, what are the two inputs?",
         ["two images", "an audio clip and a video", "a single text prompt", "an image and a question in natural language"], "D",
         "VQA takes an image and a natural language question and produces an answer."),
        ("INTERMEDIATE", "What is zero-shot image classification using text descriptions?",
         ["detecting faces only", "generating audio", "classifying an image into classes never seen during training, using text descriptions", "translating speech"], "C",
         "A zero-shot model uses text descriptions of classes to recognize categories it never saw in training."),
        ("INTERMEDIATE", "What does a CLIP-style multimodal model align?",
         ["audio and video embeddings", "image and text embeddings in a shared space", "two text embeddings", "graph and tree embeddings"], "B",
         "CLIP learns to place images and their text descriptions close together in one embedding space."),
        ("INTERMEDIATE", "Which application benefits most from object detection rather than whole-image classification?",
         ["counting vehicles in a traffic image", "assigning one label to a whole photo", "translating a sign", "summarizing a news article"], "A",
         "Counting requires locating each vehicle, which object detection provides."),
        ("INTERMEDIATE", "Which feature representation is commonly used for text spam filtering?",
         ["raw audio samples", "pixel brightness values", "edge maps", "TF-IDF word vectors"], "D",
         "TF-IDF word vectors convert message text into features that classifiers can use."),
        ("INTERMEDIATE", "What is the output of a standard speech-to-text system?",
         ["an image caption", "a translation", "a text transcript of spoken audio", "a video file"], "C",
         "Speech-to-text transcribes audio into a written text transcript."),
        ("ADVANCED", "In a multimodal model with an image encoder and a text decoder, how are image features injected into the decoder?",
         ["by converting them to audio", "by projecting them into the same embedding space as the text tokens", "by averaging them with random noise", "by encoding them as ASCII text"], "B",
         "Projecting image features into the token embedding space lets the decoder attend to them like text tokens."),
        ("ADVANCED", "For real-time pedestrian detection in a car driving at 30 fps, which design trade-off dominates?",
         ["accuracy versus inference latency on embedded hardware", "the color of the dashboard", "the number of developers", "the size of the training videos"], "A",
         "The system must balance detection accuracy with the strict latency budget of the embedded platform."),
        ("ADVANCED", "Why does OCR frequently fail on low-contrast, rotated receipts?",
         ["OCR never fails", "the camera is too expensive", "receipts are too short", "lack of preprocessing like binarization and deskewing hurts recognition"], "D",
         "Poor contrast and rotation degrade recognition without binarization and deskewing."),
        ("ADVANCED", "A deployed sentiment model performs well in testing but accuracy drops on live customer reviews. What is the most likely cause?",
         ["the model is too large", "the vocabulary is too small", "domain shift, because the training reviews differ from live reviews", "the reports are printed in color"], "C",
         "Distribution shift between training and production data is the classic cause of this failure."),
        ("ADVANCED", "A system reads chest X-rays and produces a written finding. What is this task called?",
         ["speech recognition", "report generation, an image captioning task applied to medicine", "machine translation", "tokenization"], "B",
         "Generating textual findings from images is report generation, an image captioning application."),
        ("ADVANCED", "To support 50 languages with a single translation model, which approach is most efficient?",
         ["a multilingual transformer with a shared vocabulary", "a separate model per word", "an OCR system", "a single language bag-of-words model"], "A",
         "A multilingual transformer shares parameters and a vocabulary across all languages."),
        ("ADVANCED", "Why is retrieval-augmented generation (RAG) preferred over pure generation for factual chatbot answers?",
         ["it ignores the documents", "it is always deterministic", "it trains on images", "it retrieves relevant documents to ground answers and reduce hallucination"], "D",
         "RAG grounds answers in retrieved evidence, reducing hallucinated content."),
        ("ADVANCED", "A hate-speech detector has many false positives on sarcastic posts. Which improvement helps most?",
         ["using more stop words", "removing all punctuation", "including context and discourse features to capture sarcasm", "labeling every post as positive"], "C",
         "Sarcasm is often signaled by context, so discourse features help the model avoid false positives."),
        ("ADVANCED", "What is the purpose of attention in a translation Transformer?",
         ["to increase the sequence length", "to let each output word focus on the most relevant input words", "to translate without training", "to remove all nouns"], "B",
         "Attention weights let each generated word look at the most relevant source words."),
        ("ADVANCED", "When building an image search engine from product photos and text queries, what does the system embed?",
         ["both images and queries into a shared vector space for similarity search", "only the text queries", "only the product prices", "a single hash of the catalog"], "A",
         "Embedding both modalities in one space allows image and text similarity to be compared directly."),
    ],
}
