# -*- coding: utf-8 -*-
"""
Question bank for subject 40: CORE105 - Emerging Technologies.
Category: Core Computer Science & Emerging Technologies.

Topics:
  196: Blockchain
  197: Internet of Things (IoT)
  198: Quantum Computing
  199: Edge & 5G
  200: AR/VR & Metaverse

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    196: [
        ("BEGINNER", "What is a blockchain?",
         ["a decentralized, distributed digital ledger of records", "a centralized database owned by one company", "a type of antivirus software", "a physical chain of computers"], "A",
         "A blockchain is a decentralized and distributed ledger in which records are shared across many participants and are difficult to alter."),
        ("BEGINNER", "What is a block in a blockchain?",
         ["a single cryptocurrency coin", "a network router", "a unit of data containing transactions and a header with a hash", "an encryption algorithm"], "C",
         "Each block stores a batch of valid transactions plus a header that includes a cryptographic hash linking it to the previous block."),
        ("BEGINNER", "What is the role of a cryptographic hash in a blockchain?",
         ["to compress image files", "to link blocks together and make tampering detectable", "to increase transaction speed", "to store private keys"], "B",
         "Each block stores the hash of the previous block, so changing any record breaks the chain and is immediately noticeable."),
        ("BEGINNER", "What is a distributed ledger?",
         ["a notebook shared by one user", "a hard drive backup", "a printed record of sales", "a database replicated and synchronized across many participants"], "D",
         "A distributed ledger is a shared database that is synchronized across multiple nodes, each holding a copy of the records."),
        ("BEGINNER", "What is a cryptocurrency?",
         ["a digital asset that uses cryptography to secure transactions", "a physical coin made of metal", "a bank deposit certificate", "a stock market index"], "A",
         "Cryptocurrencies are digital currencies whose transactions are secured by cryptography and typically recorded on a blockchain."),
        ("BEGINNER", "What is a smart contract?",
         ["a paper agreement signed digitally", "a lawyer reviewing code", "a program that runs automatically when predefined conditions are met", "a password-protected file"], "C",
         "A smart contract is self-executing code stored on a blockchain that runs automatically when its conditions are satisfied."),
        ("BEGINNER", "What is consensus in a blockchain?",
         ["an agreement between two banks", "the process by which network participants agree on the valid state of the ledger", "a type of encryption", "a miner reward"], "B",
         "Consensus lets otherwise untrusted nodes agree on which transactions are valid and on the canonical order of blocks."),
        ("BEGINNER", "What is a miner in proof-of-work blockchains?",
         ["someone who digs physical metals", "an accountant at a bank", "a hacker who steals coins", "a participant who validates transactions and creates new blocks"], "D",
         "Miners compete to solve a computational puzzle to propose the next block and are rewarded for validating transactions."),
        ("BEGINNER", "What is a blockchain transaction?",
         ["a transfer of ownership of assets recorded on the ledger", "an email between users", "a text message about prices", "a bank loan application"], "A",
         "A transaction records the transfer of an asset or data from one address to another and is permanently stored in a block."),
        ("BEGINNER", "Which property makes blockchain records difficult to alter after they are added?",
         ["they are printed on paper", "they are stored in one central server", "each block contains the hash of the previous block", "they are password protected"], "C",
         "Because every block depends on the hash of the one before it, changing any older record invalidates the whole chain."),
        ("INTERMEDIATE", "What is the genesis block?",
         ["a block that contains no transactions", "the first block of a blockchain, with no previous block", "the block that pays miners", "the last block ever mined"], "B",
         "The genesis block is block zero, the very first block that starts the chain, and it has no parent block."),
        ("INTERMEDIATE", "What is a Merkle tree used for in a blockchain block?",
         ["to store private keys", "to route network traffic", "to compress video files", "to efficiently summarize all transactions in a block with a single root hash"], "D",
         "A Merkle tree hashes pairs of transaction hashes into a single root hash, letting a node verify data without downloading everything."),
        ("INTERMEDIATE", "What is a 51% attack?",
         ["an attack where a malicious miner controls more than half of the network mining power", "a bug in the wallet app", "a tax on miners", "a phishing email about crypto"], "A",
         "If one party controls over half of the hashing power, it can reorganize the chain and potentially double-spend coins."),
        ("INTERMEDIATE", "What is a private key in a blockchain wallet?",
         ["a public email address", "a shared database password", "a secret value used to sign transactions and prove ownership", "the hash of the latest block"], "C",
         "The private key signs transactions, and whoever holds it controls the associated funds, so it must be kept secret."),
        ("INTERMEDIATE", "What is a public address in a blockchain?",
         ["the user telephone number", "a hashed form of the public key that others use to send funds to a user", "a network router IP", "the miner location"], "B",
         "A public address is a hashed form of the public key, published so others can send assets to that account."),
        ("INTERMEDIATE", "A hospital wants an unchangeable record of when medical results were issued. Which blockchain property is most useful?",
         ["faster internet speeds", "lower electricity costs", "visual aesthetics", "immutability of the append-only ledger"], "D",
         "The append-only and tamper-evident nature of a blockchain provides a strong audit trail of when records were created."),
        ("INTERMEDIATE", "What is a sidechain?",
         ["a separate blockchain pegged to the main chain with its own rules and assets", "the chain of custody in a court", "a physical cable", "the wallet backup file"], "A",
         "A sidechain is a separate blockchain pegged to the main chain, allowing different features while assets move between them."),
        ("INTERMEDIATE", "What problem does blockchain double-spend protection solve?",
         ["avoiding double encryption of data", "stopping two miners finding a block", "preventing the same digital asset from being spent more than once", "reducing transaction fees to zero"], "C",
         "Digital assets can be copied easily, so consensus rules ensure only the first valid spend is recorded on the ledger."),
        ("INTERMEDIATE", "What is a nonce in proof-of-work mining?",
         ["the private key", "an adjustable number changed until the block hash meets a target", "the transaction fee", "the block size"], "B",
         "Miners vary the nonce until the block hash satisfies the difficulty target, which requires repeated trial and error."),
        ("INTERMEDIATE", "Why is altering an old block in a blockchain extremely difficult?",
         ["the chain is too short", "blocks are printed on paper", "the network forbids edits by law", "changing one block changes its hash and breaks the chain of links to later blocks"], "D",
         "Each block contains the hash of the prior block, so altering any block invalidates the hash chain and is rejected by consensus."),
        ("ADVANCED", "A bank wants blockchain privacy with known participants and fast throughput. Which ledger type fits best?",
         ["a fully public permissionless ledger", "a paper ledger", "a permissioned, private ledger with restricted read and write access", "a public forum"], "C",
         "Permissioned private ledgers restrict who can transact and read, giving controlled access while maintaining a shared audit record."),
        ("ADVANCED", "How does proof of stake differ from proof of work?",
         ["stake selects block validators based on the value they lock up rather than computational work", "stake uses electricity to mine blocks", "stake is used only for voting", "stake makes blocks free to create"], "A",
         "Proof of stake picks validators in proportion to the cryptocurrency they stake, avoiding the energy-intensive puzzle solving of proof of work."),
        ("ADVANCED", "What is gas in the Ethereum network?",
         ["a type of fuel for miners", "compressed transaction data", "a smart contract bug", "a fee unit that prices computation and rewards validators"], "D",
         "Gas charges per computational step, so running out of gas halts execution and prevents abusive or infinite computations."),
        ("ADVANCED", "What is the main difference between a hard fork and a soft fork?",
         ["a hard fork deletes the chain", "a hard fork is a backwards-incompatible chain split while a soft fork remains compatible with old nodes", "a soft fork always doubles the supply", "a soft fork changes the cryptocurrency name"], "B",
         "A hard fork creates a new incompatible chain requiring upgrades, while a soft fork tightens rules so old nodes still accept new blocks."),
        ("ADVANCED", "In a permissioned enterprise blockchain, why is Byzantine fault tolerance consensus preferred over proof of work?",
         ["BFT is the same as mining", "BFT requires more electricity", "BFT reaches finality quickly with known validators while PoW is slow and energy heavy", "BFT produces more coins"], "C",
         "With known validators, BFT protocols reach consensus and finality in a few rounds, which suits high-throughput enterprise needs."),
        ("ADVANCED", "Which cryptographic technique lets a user prove knowledge of data without revealing the data itself?",
         ["zero-knowledge proofs", "symmetric key exchange over email", "QR codes", "video compression"], "A",
         "Zero-knowledge proofs allow a prover to convince a verifier that a statement is true without disclosing the underlying secret."),
        ("ADVANCED", "What is sharding in a blockchain context?",
         ["cutting block sizes in half", "deleting old transactions", "hiding transactions from auditors", "splitting the network data and processing across partitions to raise throughput"], "D",
         "Sharding partitions the ledger and validation work across groups of nodes, enabling many transactions to be processed in parallel."),
        ("ADVANCED", "What is a cross-chain bridge?",
         ["a physical internet cable", "a mechanism that transfers assets and data between different blockchain networks", "a consensus algorithm", "a type of wallet"], "B",
         "Bridges lock assets on one chain and mint equivalents on another, enabling interoperability between separate networks."),
        ("ADVANCED", "Which token standard on Ethereum represents a non-fungible unique asset rather than a fungible currency?",
         ["ERC-20", "HTTP", "ERC-721", "SQL"], "C",
         "ERC-721 defines non-fungible tokens where each token is unique, unlike the fungible and interchangeable ERC-20 standard."),
        ("ADVANCED", "A supply-chain consortium must reject invalid transactions immediately. Which property should the design emphasize?",
         ["immediate finality and a single agreed chain state", "maximum energy consumption", "anonymous mining", "unlimited transaction fees"], "A",
         "Finality guarantees that a committed block cannot be reversed, which is critical for trustworthy supply-chain records."),
    ],
    197: [
        ("BEGINNER", "What does IoT stand for?",
         ["Internet of Things", "Internet of Technologies", "Institute of Telecommunications", "Interface of Tools"], "A",
         "IoT stands for Internet of Things, the network of physical objects embedded with sensors and software."),
        ("BEGINNER", "What is a sensor in an IoT system?",
         ["a power supply", "a mobile app", "a device that measures a physical quantity and converts it into a signal", "a type of antenna"], "C",
         "Sensors gather data about the environment, such as temperature or motion, and convert it into a readable signal."),
        ("BEGINNER", "What is an actuator in an IoT device?",
         ["a memory chip", "a component that performs an action such as opening a valve or turning a motor", "a network cable", "a screen saver"], "B",
         "Actuators translate control commands into physical movement or action, closing the loop between sensing and doing."),
        ("BEGINNER", "What is the role of an IoT gateway?",
         ["to charge device batteries", "to render 3D graphics", "to compile code", "to connect edge devices to the cloud and translate between protocols"], "D",
         "A gateway bridges local IoT devices and the internet, aggregating data and handling protocol translation."),
        ("BEGINNER", "Which protocol is a lightweight publish-subscribe messaging protocol widely used in IoT?",
         ["MQTT", "FTP", "SMTP", "SNMP"], "A",
         "MQTT is designed for low-bandwidth, high-latency IoT networks using a lightweight publish-subscribe model."),
        ("BEGINNER", "Which of the following is an example of a smart home IoT device?",
         ["a traditional light switch", "a paper calendar", "a thermostat that adjusts temperature automatically", "a wooden door"], "C",
         "Smart thermostats connect to the internet and adjust heating based on learned patterns and remote commands."),
        ("BEGINNER", "What does a microcontroller provide in an IoT device?",
         ["a physical lock", "a small computer to run the device program and manage its sensors", "a network router", "a backup generator"], "B",
         "Microcontrollers are low-power chips that run the logic of embedded IoT devices."),
        ("BEGINNER", "What is a wearable IoT device?",
         ["a piece of clothing with no electronics", "a desktop computer", "a wall-mounted router", "a device worn on the body that collects and transmits data"], "D",
         "Wearables such as smartwatches are worn on the body and track health metrics and activity data."),
        ("BEGINNER", "What role does the cloud play in many IoT architectures?",
         ["storage and analysis of data collected from many devices", "physically connecting devices", "replacing sensors", "generating electricity"], "A",
         "The cloud stores device data at scale and runs analytics and machine learning over the aggregated information."),
        ("BEGINNER", "What is a device identifier in an IoT network?",
         ["a type of sensor", "a network password", "a unique ID that distinguishes each connected device", "a battery type"], "C",
         "Each IoT device gets a unique identifier so the platform can route data and manage it individually."),
        ("INTERMEDIATE", "In MQTT, what is the role of a broker?",
         ["to encrypt the internet", "to route messages between publishers and subscribers", "to store sensor data in the cloud forever", "to power the devices"], "B",
         "The broker receives published messages and forwards them to all clients that subscribed to the matching topic."),
        ("INTERMEDIATE", "Why is edge processing often used in IoT systems?",
         ["to increase the number of sensors", "to make devices larger", "to eliminate the need for batteries", "to reduce latency and bandwidth by processing data close to the source"], "D",
         "Analyzing data near the device avoids round trips to the cloud, cutting latency and network usage."),
        ("INTERMEDIATE", "Why does battery life matter so much for many IoT sensors?",
         ["devices are often deployed in remote locations where replacing batteries is costly", "batteries produce more data", "batteries are always rechargeable", "sensors cannot run on batteries"], "A",
         "Many sensors are placed in hard-to-reach places, so minimizing power consumption and transmission frequency is critical."),
        ("INTERMEDIATE", "What do MQTT Quality of Service levels guarantee?",
         ["higher video resolution", "faster battery charging", "different levels of message delivery assurance between sender and receiver", "stronger Wi-Fi signals"], "C",
         "MQTT QoS levels 0, 1 and 2 provide increasing guarantees about whether and how messages are delivered."),
        ("INTERMEDIATE", "A smart refrigerator sends a temperature reading every minute to a monitoring app. What type of communication is this?",
         ["peer-to-peer file sharing", "device-to-cloud, where the device publishes data for remote viewing", "satellite broadcasting", "paper-based reporting"], "B",
         "The device sends readings to the cloud platform, where the app subscribes to receive the updates."),
        ("INTERMEDIATE", "Why are default passwords a serious IoT security risk?",
         ["default passwords are too long", "passwords change the color of lights", "default passwords drain the battery", "many devices ship with weak known credentials that attackers exploit"], "D",
         "Default credentials are publicly known, so unsecured devices are easily hijacked by automated attack tools."),
        ("INTERMEDIATE", "Compared with HTTP, why is CoAP suited to constrained IoT devices?",
         ["CoAP is a lightweight UDP-based protocol designed for low-power nodes", "CoAP runs only on desktop servers", "CoAP encrypts with heavier TLS", "CoAP requires constant high bandwidth"], "A",
         "CoAP runs over UDP with small message overhead, making it practical for memory-limited devices."),
        ("INTERMEDIATE", "What is an over-the-air (OTA) update for an IoT device?",
         ["a software installation via USB", "a physical upgrade of the circuit board", "wireless delivery of firmware and security patches to deployed devices", "an aerial survey of the building"], "C",
         "OTA updates let organizations remotely patch devices in the field, fixing bugs and vulnerabilities without physical access."),
        ("INTERMEDIATE", "Which lightweight data format is most commonly used for IoT payloads?",
         ["JPEG", "JSON", "MP3", "PDF"], "B",
         "JSON is a compact, human-readable key-value format widely used to serialize IoT telemetry."),
        ("INTERMEDIATE", "Which wireless technology is designed for long-range, low-power IoT sensors?",
         ["Bluetooth audio streaming", "HDMI", "USB-C", "LPWAN such as LoRaWAN"], "D",
         "LPWAN technologies cover several kilometers at low bit rates, ideal for battery-powered remote sensors."),
        ("ADVANCED", "An industrial plant must detect a failing motor within milliseconds. Which IoT design decision is most appropriate?",
         ["stream all data to a distant cloud and wait for analysis", "disable all sensors", "run predictive analytics locally at the edge for instant reaction", "record data on paper"], "C",
         "Local edge processing gives the millisecond response needed for time-critical industrial monitoring."),
        ("ADVANCED", "For a device with 64 KB of RAM sending one reading per hour, which protocol is the best fit?",
         ["MQTT-SN or CoAP, optimized for constrained devices", "full HTTP over TCP with heavy headers", "a desktop database driver", "sending emails"], "A",
         "Lightweight UDP-based protocols with tiny headers fit devices with very limited memory and infrequent traffic."),
        ("ADVANCED", "What is a digital twin in an IoT context?",
         ["a second physical device", "a copy of the database", "a remote control", "a virtual model of a physical system updated with live sensor data"], "D",
         "A digital twin mirrors a physical asset in software, fed by live telemetry so operators can simulate and predict behavior."),
        ("ADVANCED", "Why might an edge gateway buffer data locally when its internet connection drops?",
         ["to reduce the number of sensors", "so no readings are lost and they can be uploaded once connectivity returns", "to charge the devices", "to improve the camera resolution"], "B",
         "Local buffering preserves telemetry during outages and syncs the backlog to the cloud when the link recovers."),
        ("ADVANCED", "Which approach provides strong mutual authentication between a constrained IoT device and its platform?",
         ["sharing one password among all devices", "hiding the device IP", "X.509 certificates with mutual TLS", "using an open Wi-Fi network"], "C",
         "Mutual TLS with per-device certificates verifies both ends, preventing spoofed devices and rogue servers."),
        ("ADVANCED", "A city deploys sensors from several vendors that each use proprietary formats. What does this create?",
         ["an interoperability challenge that requires a standard data model and API", "improved battery life", "stronger signal strength", "no management burden"], "A",
         "Vendor lock-in and divergent formats demand standardization and adapters so the platform can ingest all devices."),
        ("ADVANCED", "Why are time-series databases often chosen for IoT telemetry storage?",
         ["they store only images", "they replace the sensors", "they run on the devices", "they optimize ingestion and queries of timestamped sensor readings"], "D",
         "Time-series stores efficiently handle the high write rates and time-range queries typical of sensor data."),
        ("ADVANCED", "A company rolls out 10,000 devices. Which practice best supports secure onboarding?",
         ["assigning everyone the same admin password", "automatic provisioning with per-device credentials issued securely", "sending credentials by postcard", "skipping registration entirely"], "B",
         "Automated provisioning issues unique, securely delivered credentials so each device authenticates individually at scale."),
        ("ADVANCED", "To respect user privacy while collecting health data, which principle should an IoT system apply?",
         ["collecting everything including location always", "selling raw data openly", "data minimization, collecting only what is needed with consent", "ignoring user consent"], "C",
         "Collecting only necessary data with explicit consent reduces privacy risk and regulatory exposure."),
        ("ADVANCED", "A logistics tracker reports location every 5 seconds, but the customer only needs hourly updates. Which optimization is best?",
         ["adaptive reporting with local buffering and scheduled uploads", "keeping the radio on permanently", "always sending at 4G speed", "deleting all stored data"], "A",
         "Batching and adaptive duty cycling slash power consumption while still providing the required update frequency."),
    ],
    198: [
        ("BEGINNER", "What is a qubit?",
         ["the basic unit of quantum information that can exist in superposition", "a cable connector", "a classical bit with only one value", "a type of quantum computer brand"], "A",
         "A qubit is the fundamental unit of quantum information and can be in a superposition of states rather than only 0 or 1."),
        ("BEGINNER", "What is superposition in quantum computing?",
         ["two computers side by side", "a qubit being in a combination of the 0 and 1 states at once", "data being copied twice", "a memory error"], "B",
         "Superposition lets a qubit represent a blend of basis states simultaneously until it is measured."),
        ("BEGINNER", "What is quantum entanglement?",
         ["a type of hard drive", "a wireless network", "a link where qubits are correlated so measuring one affects the other", "an encryption key"], "C",
         "Entangled qubits share a correlation such that the measurement outcome of one instantly constrains the other."),
        ("BEGINNER", "What is quantum computing?",
         ["using many classic laptops together", "adding more RAM to a server", "compressing files with a small unit of data", "computation that uses quantum mechanical phenomena like superposition and entanglement"], "D",
         "Quantum computers exploit superposition, entanglement and interference to perform calculations in fundamentally new ways."),
        ("BEGINNER", "How does a qubit differ from a classical bit?",
         ["a classical bit is 0 or 1 while a qubit can be in a superposition of both", "a qubit is always larger in size", "a bit is quantum and a qubit is classical", "there is no difference at all"], "A",
         "Classical bits are exclusively 0 or 1, whereas qubits can occupy a continuous superposition until measured."),
        ("BEGINNER", "What is a quantum gate?",
         ["a physical gate in a data center", "a basic operation that transforms the state of qubits", "a firewall rule", "a password manager"], "B",
         "Quantum gates manipulate qubit states in controlled ways, and combinations of gates form quantum circuits."),
        ("BEGINNER", "What happens to a qubit when it is measured?",
         ["it duplicates itself", "it becomes entangled with the computer", "its superposition collapses to a definite 0 or 1 outcome", "it is erased forever"], "C",
         "Measurement forces the superposition to collapse, yielding a single classical outcome of 0 or 1."),
        ("BEGINNER", "What is decoherence?",
         ["a software crash", "a network slowdown", "an increase in computing speed", "the loss of quantum state due to interaction with the environment"], "D",
         "Decoherence destroys the fragile quantum state through unwanted environmental interaction, causing errors."),
        ("BEGINNER", "What is a quantum circuit?",
         ["a sequence of quantum gates applied to qubits to perform a computation", "an electrical cable", "a round trip between servers", "a cooling fan"], "A",
         "A quantum circuit is an ordered series of gates and measurements that implements a quantum algorithm."),
        ("BEGINNER", "What is a Bloch sphere?",
         ["a type of quantum memory chip", "a geometric representation of a single qubit state", "a circular database", "a qubit cooler"], "B",
         "The Bloch sphere visualizes all possible states of a single qubit as points on the surface of a sphere."),
        ("INTERMEDIATE", "What does applying a Hadamard gate to a qubit in state |0> produce?",
         ["the state |1>", "no change at all", "a superposition of |0> and |1>", "an entangled pair by itself"], "C",
         "The Hadamard gate maps |0> to an equal superposition of |0> and |1>, a key step in creating superposition."),
        ("INTERMEDIATE", "What is the function of a CNOT gate?",
         ["it deletes a qubit", "it copies a qubit exactly", "it measures the energy", "it flips a target qubit when the control qubit is in state |1>, enabling entanglement"], "D",
         "The controlled-NOT gate conditions a flip of the target on the control, and combinations with Hadamard create entanglement."),
        ("INTERMEDIATE", "If a qubit is measured and found to be |0>, what does this mean?",
         ["the superposition collapsed to the |0> outcome with the associated probability", "the qubit is guaranteed to have been |0> all along", "the qubit becomes |1>", "the measurement was invalid"], "A",
         "Measurement samples the probability distribution, and observing |0> means that outcome occurred while the other was suppressed."),
        ("INTERMEDIATE", "Why do many quantum computers operate at temperatures near absolute zero?",
         ["to reduce thermal noise that destroys qubit coherence", "to make the chips faster to read", "to save electricity", "to make the machines quieter"], "A",
         "Cryogenic cooling suppresses thermal fluctuations that would rapidly cause decoherence in superconducting qubits."),
        ("INTERMEDIATE", "A qubit is put into superposition and then measured repeatedly without resetting. What is observed?",
         ["the same superposition is preserved forever", "each measurement returns a probabilistic outcome that collapses the superposition", "the qubit becomes stronger", "the result doubles each time"], "B",
         "Once measured the qubit is no longer in superposition; later measurements only re-sample the collapsed state."),
        ("INTERMEDIATE", "What is quantum parallelism?",
         ["running two laptops at once", "installing more memory sticks", "using two quantum gates in sequence", "processing many states simultaneously through superposition of the input"], "D",
         "Superposition lets a single computation act on many computational states at once, giving parallel processing of states."),
        ("INTERMEDIATE", "What does the Pauli-X gate do to a qubit?",
         ["it adds energy", "it flips the basis state, mapping |0> to |1> and |1> to |0>", "it measures the qubit", "it creates a classical copy"], "B",
         "The Pauli-X gate is the quantum analogue of a classical NOT gate, flipping the qubit between basis states."),
        ("INTERMEDIATE", "What is a bit-flip error in a qubit?",
         ["the qubit loses charge", "the network drops a message", "the quantum gate is deleted", "the qubit basis state 0 or 1 randomly changes due to noise"], "D",
         "Environmental noise can flip a qubit computational basis state, one of the main error types quantum error correction addresses."),
        ("INTERMEDIATE", "What is a quantum register?",
         ["a storage shelf for cables", "a classical file", "a collection of qubits treated as a unit for computation", "a single gate"], "C",
         "A quantum register is an ordered group of qubits, and a register of n qubits can represent 2 to the power n states."),
        ("INTERMEDIATE", "With n qubits, how many classical states can be represented in superposition?",
         ["n squared states", "n states", "2 to the power of n states", "10 times n states"], "C",
         "An n-qubit register can hold a superposition over all 2^n basis states, which underlies quantum parallelism."),
        ("ADVANCED", "Which algorithm is known for factoring large integers exponentially faster than the best classical algorithms, threatening RSA?",
         ["Shor algorithm", "Bubble sort", "Binary search", "Boyer-Moore search"], "A",
         "Shor algorithm uses quantum period finding to factor integers efficiently, which breaks RSA-based cryptography at scale."),
        ("ADVANCED", "Which quantum algorithm provides a quadratic speedup for searching an unsorted database?",
         ["Dijkstra algorithm", "Grover algorithm", "Merge sort", "Linear regression"], "B",
         "Grover algorithm searches N unordered items in about the square root of N steps, versus N classically."),
        ("ADVANCED", "Why are surface codes used in quantum error correction?",
         ["they speed up gates", "they reduce the number of qubits", "they encode logical qubits across many physical qubits to correct errors fault-tolerantly", "they run classical code"], "C",
         "Surface codes spread a logical qubit over a 2D grid of physical qubits so errors can be detected and corrected without destroying the state."),
        ("ADVANCED", "What characterizes the NISQ era of quantum computing?",
         ["perfect fault-tolerant universal quantum computers", "classical supercomputers", "quantum networks only", "noisy intermediate-scale quantum devices without full error correction"], "D",
         "NISQ machines have tens to thousands of noisy qubits lacking full error correction, limiting useful computation depth."),
        ("ADVANCED", "Which protocol uses quantum states to detect eavesdropping during key exchange?",
         ["BB84 quantum key distribution", "TLS over Ethernet", "MD5 hashing", "XOR encryption"], "A",
         "BB84 encodes key bits in quantum states, and any measurement by an eavesdropper disturbs the states and is detected."),
        ("ADVANCED", "Why does the no-cloning theorem limit quantum cryptography and computing?",
         ["an unknown quantum state cannot be perfectly duplicated", "qubits are too large to copy", "gates cannot be repeated", "classical copying is forbidden"], "A",
         "Quantum states cannot be cloned, which underpins QKD security but also prevents simple backup of unknown quantum data."),
        ("ADVANCED", "What is quantum advantage or quantum supremacy?",
         ["when a quantum computer uses less electricity", "a demonstration where a quantum computer solves a task that practical classical computers cannot", "the point where qubits are entangled", "the fastest clock speed"], "B",
         "Quantum advantage is demonstrated when a quantum processor outperforms the best available classical computation on a specific task."),
        ("ADVANCED", "To run a useful algorithm on today hardware, what must a quantum circuit account for above all?",
         ["the color of the qubits", "the brand of the computer", "the length of the cables", "limited coherence times and high error rates"], "D",
         "Short coherence and noisy gates mean circuits must be shallow and error-mitigated to finish before decoherence."),
        ("ADVANCED", "What is the main difference between quantum annealing and the gate model?",
         ["annealing evolves a system to a low-energy solution of an optimization problem while gates run programmable circuits", "annealing uses classical bits", "the gate model needs no cooling", "annealing cannot solve problems"], "A",
         "Quantum annealers minimize an energy function for optimization, whereas gate-model computers run universal quantum circuits."),
        ("ADVANCED", "What does quantum teleportation actually transfer between two parties?",
         ["a physical object through space", "a complete copy of all data", "the quantum state of a qubit using entanglement and classical communication", "the qubit hardware"], "C",
         "Teleportation moves the state of a qubit to a distant qubit using shared entanglement plus classical bits, without moving the particle."),
    ],
    199: [
        ("BEGINNER", "What is edge computing?",
         ["processing data near the source instead of only in a distant cloud", "computing at the very edge of a table", "using the oldest computers", "storing data in a warehouse"], "A",
         "Edge computing moves computation closer to where data is generated, reducing latency and bandwidth use."),
        ("BEGINNER", "What does 5G stand for?",
         ["five gigabytes of memory", "the fifth generation of cellular network technology", "five network towers", "a five-second connection"], "B",
         "5G is the fifth generation of mobile network standards, succeeding 4G with faster speeds and lower latency."),
        ("BEGINNER", "What is latency in a network?",
         ["the size of the data", "the number of users", "the delay between sending a message and receiving a response", "the cost of the connection"], "C",
         "Latency measures the time it takes for data to travel from source to destination, affecting responsiveness."),
        ("BEGINNER", "What is a base station in a cellular network?",
         ["a power plant", "a home router for one house", "a data cable", "a fixed radio transceiver that connects mobile devices to the network"], "D",
         "Base stations are the cellular towers that relay signals between mobile devices and the core network."),
        ("BEGINNER", "What is cloud computing?",
         ["delivering computing services like storage and processing over the internet", "storing data on a laptop only", "drawing weather clouds", "using floppy disks"], "A",
         "Cloud computing offers on-demand IT resources over the internet, such as compute, storage and databases."),
        ("BEGINNER", "What is an edge device?",
         ["the fastest server in a data center", "a device like a sensor or gateway that produces and processes data at the network edge", "the outermost router of a home", "a type of antenna"], "B",
         "Edge devices sit close to data sources and often perform local processing before data reaches the cloud."),
        ("BEGINNER", "What is bandwidth?",
         ["the physical width of a cable", "the voltage of a signal", "the number of antennas", "the maximum data transfer rate of a connection"], "D",
         "Bandwidth is the capacity of a connection, measured as the maximum amount of data transmitted per second."),
        ("BEGINNER", "What is fog computing?",
         ["an intermediate layer between the cloud and edge devices that distributes processing", "weather-based computing", "computing that runs only in clouds", "a computer cooling system"], "A",
         "Fog computing places processing and storage nodes between cloud data centers and the edge to reduce latency."),
        ("BEGINNER", "What is a data center?",
         ["a room with printers", "a database backup", "a facility housing servers and networking equipment", "a network cable"], "C",
         "Data centers centralize large numbers of servers, storage systems and network gear that power cloud services."),
        ("BEGINNER", "Which benefit does 5G offer compared with 4G?",
         ["higher data rates and much lower latency", "lower data rates", "longer phone batteries", "no need for base stations"], "A",
         "5G delivers multi-gigabit throughput and latency in the low milliseconds, enabling new real-time applications."),
        ("INTERMEDIATE", "Why does processing data at the edge reduce latency for a self-driving car?",
         ["the car has more antennas", "decisions happen near the vehicle instead of travelling to a distant cloud", "edge servers are always faster", "the cloud is disabled"], "B",
         "Local processing avoids the round trip to a remote data center, giving the milliseconds a vehicle needs to react."),
        ("INTERMEDIATE", "What is network slicing in 5G?",
         ["cutting cables", "dividing one physical network into multiple virtual networks tuned for different services", "segmenting the radio frequencies", "turning off towers at night"], "B",
         "Network slicing creates isolated virtual networks with tailored latency, bandwidth and reliability for each use case."),
        ("INTERMEDIATE", "An autonomous vehicle needs to brake within milliseconds. Where should the safety-critical decision run?",
         ["on the vehicle itself or an edge node nearby", "on a cloud server in another country", "on a scheduled nightly batch job", "on a printer"], "A",
         "Time-critical safety decisions must run close to the vehicle to meet millisecond deadlines regardless of cloud latency."),
        ("INTERMEDIATE", "What is mmWave in 5G?",
         ["high-frequency spectrum offering huge bandwidth but shorter range", "a type of microphone", "a low-frequency signal with long range", "a cable standard"], "A",
         "Millimeter-wave bands carry enormous capacity over short distances, needing dense small-cell deployments."),
        ("INTERMEDIATE", "When is it better to process data in the cloud rather than at the edge?",
         ["when the device has no cloud access", "for millisecond emergency responses", "for heavy offline analytics over large accumulated datasets", "when the network is down"], "C",
         "Cloud processing suits complex analytics over large data sets where latency is not critical and compute is heavy."),
        ("INTERMEDIATE", "What is multi-access edge computing (MEC)?",
         ["connecting computers with multiple cables", "a multi-site data center", "putting cloud-like compute at the network edge, close to base stations", "a type of router"], "C",
         "MEC hosts applications at the edge of the mobile network, delivering low latency for nearby users."),
        ("INTERMEDIATE", "Compared with 4G, what key 5G capability enables massive IoT deployments?",
         ["larger smartphone screens", "stronger passwords", "wider headphones", "support for a very large number of low-power devices per cell"], "D",
         "5G massive machine-type communication supports hundreds of thousands of low-power devices in one cell."),
        ("INTERMEDIATE", "Which scenario best suits processing at the edge rather than the cloud?",
         ["a bank runs a yearly tax report", "a factory needs real-time vibration analysis of machines", "a university archives old emails", "a library scans books offline"], "B",
         "Real-time local analysis fits the edge, while infrequent heavy batch jobs fit the cloud."),
        ("INTERMEDIATE", "Why is latency more important than bandwidth for a live video game stream?",
         ["the video is always tiny", "bandwidth is irrelevant", "latency only affects downloads", "responses must arrive quickly, even if the data volume is moderate"], "D",
         "Interactive experiences depend on quick round trips, so low latency matters more than raw throughput."),
        ("INTERMEDIATE", "What is edge caching?",
         ["storing frequently requested content at edge nodes to serve users faster", "saving files on the phone only", "compressing videos", "deleting old content"], "A",
         "Edge caching keeps popular content near users, cutting download times and network traffic."),
        ("ADVANCED", "An OEM designs a self-driving car. Which architecture best balances safety and cost?",
         ["send every frame to a distant cloud for decisions", "on-vehicle real-time control plus edge for map updates and fleet analytics", "no local processing at all", "store all data on paper"], "B",
         "Critical control stays on board while edge nodes handle bandwidth-hungry tasks like map refresh and analytics."),
        ("ADVANCED", "Which 5G feature is designed for ultra-reliable low-latency communication (URLLC)?",
         ["higher download speeds only", "better video compression", "deterministic, low-latency links for mission-critical applications", "longer battery standby"], "C",
         "URLLC guarantees end-to-end latency in the low milliseconds with high reliability, for uses like remote surgery and industrial control."),
        ("ADVANCED", "How does federated learning improve privacy in edge AI?",
         ["models train on edge devices and only updates are shared, not raw data", "all data is uploaded to one server", "models are deleted", "data is published openly"], "A",
         "Federated learning keeps personal data local, sharing only model gradients or parameters to a central server."),
        ("ADVANCED", "What is the difference between 5G standalone (SA) and non-standalone (NSA)?",
         ["SA uses a full 5G core while NSA reuses the 4G core", "SA has no antennas", "NSA is slower than 3G", "SA stands for the fastest phones"], "A",
         "Non-standalone 5G was an early deployment sharing the LTE core, while standalone uses a dedicated 5G core for full features."),
        ("ADVANCED", "An AR app requires under 20 ms of end-to-end latency. How would you meet this budget?",
         ["host everything in a faraway data center", "stream over satellite", "queue all frames for night processing", "run rendering and tracking at the edge or on-device and use a nearby MEC"], "D",
         "Keeping compute near the user and on short paths keeps round-trip time within the strict latency budget."),
        ("ADVANCED", "An edge gateway fails while a factory depends on it. What design minimizes downtime?",
         ["a single gateway with no backup", "redundant edge nodes with automatic failover to a standby", "restarting only once a month", "relying on luck"], "B",
         "Hot standby edge nodes detect failure and take over instantly, keeping the industrial process uninterrupted."),
        ("ADVANCED", "What is massive MIMO in 5G?",
         ["using arrays with many antennas to serve many users simultaneously on the same spectrum", "a single giant antenna", "a faster battery", "a type of fiber"], "A",
         "Massive MIMO exploits many antenna elements to spatially multiplex users, boosting capacity and efficiency."),
        ("ADVANCED", "When should an AI inference run at the edge rather than the cloud?",
         ["when the model is huge and untrained", "when cloud credits are free", "when low latency or offline operation is required for the decision", "when the network is reliable and fast"], "C",
         "Edge inference matters where real-time decisions or operation without connectivity are required."),
        ("ADVANCED", "Why is security isolation critical for 5G network slices sharing one physical network?",
         ["a breach in one slice must not compromise the other tenants slices", "isolation slows the network", "slices are not networks", "isolation removes base stations"], "A",
         "Strong isolation ensures a compromised slice cannot expose data or disrupt the other virtual networks."),
        ("ADVANCED", "A user moves between 5G cells during a video call. What must the network handle smoothly?",
         ["resetting the phone", "handover, transferring the active connection to the next base station without drops", "deleting the call", "slowing the video"], "B",
         "Seamless handover maintains the session as the device moves between coverage areas, which is critical for mobility."),
    ],
    200: [
        ("BEGINNER", "What does AR stand for?",
         ["Augmented Reality", "Advanced Routing", "Automatic Rendering", "Artificial Robotics"], "A",
         "AR stands for Augmented Reality, which overlays digital content onto the real world."),
        ("BEGINNER", "What does VR stand for?",
         ["Visual Range", "Virtual Reality", "Video Rendering", "Variable Rate"], "B",
         "VR stands for Virtual Reality, which immerses the user in a fully synthetic environment."),
        ("BEGINNER", "What is the Metaverse?",
         ["a single video game", "a type of router", "a collective virtual shared space formed by virtual worlds and persistent online environments", "a social media app only"], "C",
         "The Metaverse refers to interconnected, persistent virtual worlds where people can interact and transact."),
        ("BEGINNER", "What is a VR headset?",
         ["a pair of glasses for reading", "a microphone", "a gaming controller", "a head-mounted display that shows a virtual environment"], "D",
         "A VR headset contains displays and tracking that replace the wearer view with a virtual world."),
        ("BEGINNER", "What is an avatar in a virtual world?",
         ["a digital representation of a user", "a type of aircraft", "a video file", "a network protocol"], "A",
         "An avatar is the user graphical identity inside virtual environments and the metaverse."),
        ("BEGINNER", "What is mixed reality (MR)?",
         ["a mix of two video games", "blending real and virtual content that interact in real time", "a hybrid laptop", "a combination of audio files"], "B",
         "MR combines real and digital worlds so virtual objects coexist and interact with the physical environment."),
        ("BEGINNER", "What is a digital twin in the context of virtual worlds?",
         ["a virtual replica of a physical object or system", "a second account", "a duplicate screen", "a backup of the phone"], "A",
         "A digital twin is a live virtual model that mirrors a physical asset, often updated with real-time data."),
        ("BEGINNER", "What does HMD stand for in AR/VR hardware?",
         ["High-Memory Device", "Hardware Media Disk", "Head-Mounted Display", "Hand Motion Detector"], "C",
         "An HMD is a display worn on the head, the core hardware of most VR and many AR systems."),
        ("BEGINNER", "What is an immersive experience?",
         ["a very long movie", "a loud concert", "a fast internet download", "an experience that fully engages the senses and makes users feel present"], "D",
         "Immersion makes users feel physically present in the virtual or mixed environment through sensory engagement."),
        ("BEGINNER", "What is a virtual world?",
         ["a computer-simulated environment that multiple users can explore and interact with", "a paper map", "a physics simulation on paper", "a single spreadsheet"], "A",
         "Virtual worlds are simulated spaces, often persistent and shared, where users navigate avatars and objects."),
        ("INTERMEDIATE", "Why do VR headsets target high refresh rates like 90 Hz or 120 Hz?",
         ["higher refresh reduces perceived flicker and motion sickness", "high rates drain no power", "low rates make images sharper", "refresh only affects audio"], "A",
         "Higher refresh rates give smoother motion and reduce the visual lag that triggers discomfort."),
        ("INTERMEDIATE", "What is inside-out tracking in VR?",
         ["tracking from external base stations", "tracking the user pulse", "tracking internet usage", "tracking using cameras on the headset to observe the environment"], "D",
         "Inside-out tracking uses on-headset cameras and sensors to compute position without external beacons."),
        ("INTERMEDIATE", "A technician must see part numbers floating over machines. Which technology fits this maintenance task?",
         ["AR overlays on the real equipment", "fully immersive VR worlds", "a plain spreadsheet", "audio-only calls"], "A",
         "AR projects instructions onto the physical machine, keeping the worker aware of the real environment."),
        ("INTERMEDIATE", "What is field of view in a headset?",
         ["the size of the screen", "the angular extent of the world visible at once", "the weight of the headset", "the battery capacity"], "B",
         "Field of view is the visual angle a headset covers, and wider fields increase immersion."),
        ("INTERMEDIATE", "What is motion-to-photon latency in VR?",
         ["the time to boot the headset", "the charging time", "the delay between a user movement and the updated image appearing on screen", "the download time of an app"], "C",
         "Low motion-to-photon latency is essential, since high delays make the virtual world lag behind the user."),
        ("INTERMEDIATE", "What do haptic feedback devices provide in VR?",
         ["visual overlays", "tactile sensations that simulate touch and force", "sound effects only", "network connections"], "B",
         "Haptics add touch and force feedback so users feel virtual objects instead of only seeing them."),
        ("INTERMEDIATE", "What is SLAM used for in AR systems?",
         ["simultaneous localization and mapping of the device in its environment", "sending sound messages", "loading large maps", "compressing textures"], "A",
         "SLAM builds a map of the surroundings while tracking the device position, enabling AR content to stay anchored."),
        ("INTERMEDIATE", "What is the uncanny valley?",
         ["a valley in a virtual landscape", "a drop in frame rate", "the discomfort users feel with avatars that look nearly but not quite human", "a low-resolution texture"], "C",
         "Avatars approaching human realism but not perfectly can look eerie, which reduces acceptance and engagement."),
        ("INTERMEDIATE", "Why do many VR apps use teleport-based locomotion?",
         ["it avoids the nausea caused by simulated continuous walking", "it makes the game shorter", "it uses less memory", "it disables tracking"], "A",
         "Instant teleportation removes the conflicting visual and vestibular motion cues that cause simulator sickness."),
        ("INTERMEDIATE", "How do NFTs relate to the metaverse economy?",
         ["they speed up rendering", "they represent provable ownership of unique digital assets such as virtual items", "they are the network hardware", "they replace avatars"], "B",
         "Non-fungible tokens on blockchains give verifiable ownership and transfer of unique virtual goods."),
        ("ADVANCED", "A hospital wants surgeons to practice operations. Which VR design factor matters most for effectiveness?",
         ["high-fidelity physics and precise hand tracking for realistic procedural practice", "the loudest possible audio", "the cheapest headset available", "the largest marketplace"], "A",
         "Realistic interactions and accurate tracking make the simulation transferable to real surgical skills."),
        ("ADVANCED", "What causes cybersickness, and how is it typically reduced?",
         ["too much battery", "high polygon counts", "a mismatch between visual motion and the body vestibular sense, reduced by matching latency and opt-in comfort modes", "low screen brightness"], "C",
         "When the eyes see motion the body does not feel, discomfort follows, and minimizing lag with comfort modes reduces it."),
        ("ADVANCED", "What is foveated rendering?",
         ["rendering every pixel at maximum quality", "rendering only audio", "rendering in grayscale", "rendering full detail only where the eye is looking and lower detail elsewhere"], "D",
         "Eye tracking lets the renderer concentrate resolution on the fovea, cutting the GPU load massively."),
        ("ADVANCED", "A metaverse platform must keep avatars synchronized for 10,000 concurrent users. What is essential?",
         ["dedicated state servers and interest management so users only receive relevant updates", "sending every user every update", "no server at all", "a single shared save file"], "A",
         "Interest management and server-authoritative state keep bandwidth manageable while preserving consistency."),
        ("ADVANCED", "In AR, why is correct occlusion of virtual objects by real objects difficult?",
         ["it needs brighter screens", "the system must build a depth map of the scene in real time to hide virtual pixels behind real surfaces", "it needs more speakers", "it needs faster menus"], "B",
         "Occlusion requires understanding real-world depth so virtual content appears behind physical objects correctly."),
        ("ADVANCED", "Which open standard helps metaverse assets move between platforms?",
         ["MP3 audio", "glTF, a royalty-free 3D asset format", "a private file format", "a proprietary video codec"], "B",
         "glTF is the open standard for transmitting and loading 3D scenes, supporting interoperability across engines."),
        ("ADVANCED", "Why is volumetric video extremely bandwidth-hungry?",
         ["it is always in grayscale", "it has no audio", "it is compressed forever", "it streams full 3D geometry and textures instead of a flat 2D frame"], "D",
         "Volumetric content encodes depth and shape per frame, requiring far more data than a conventional 2D stream."),
        ("ADVANCED", "What security risk arises from avatar identity in the metaverse?",
         ["improved battery life", "higher resolution", "impersonation and phishing, since visual identity is not proof of real identity", "faster rendering"], "C",
         "Avatars are easily copied, so without strong verification users can be tricked by look-alike impostors."),
        ("ADVANCED", "For cloud-streamed VR, what is the strict latency budget requirement?",
         ["end-to-end latency must stay near 20 ms or below for comfort and responsiveness", "latency can be several seconds", "latency only affects audio", "latency is irrelevant"], "A",
         "Cloud VR must compress, transmit and render within a few tens of milliseconds to avoid motion sickness."),
        ("ADVANCED", "A metaverse platform struggles with harassment. Which governance approach is most robust?",
         ["removing all moderation", "clear code of conduct with moderation, reporting tools and identity consequences", "only banning bots", "ignoring reports"], "B",
         "Effective governance combines explicit rules, reporting, active moderation and accountability to keep spaces safe."),
    ],
}
