# -*- coding: utf-8 -*-
"""
Question bank for subject 07 - DBMS102 - Structured Query Language (SQL).
Covers topics 31-35, each with 10 BEGINNER, 10 INTERMEDIATE, and 10 ADVANCED
questions (30 per topic, 150 total).

Sample schema used across questions:
    employees(id, name, dept_id, salary)
    departments(id, name)
"""

QUESTIONS = {
    31: [
        ("BEGINNER", "Which SQL command is used to create a new database table?",
         ["CREATE TABLE", "INSERT INTO", "ALTER TABLE", "DROP TABLE"], "A",
         "CREATE TABLE is the DDL statement that defines a new table and its columns in the database."),
        ("BEGINNER", "Which SQL command removes all rows from a table but keeps the table structure itself?",
         ["DROP TABLE", "TRUNCATE", "DELETE", "REMOVE"], "B",
         "TRUNCATE deletes every row while preserving the table definition, which is exactly what keeps the structure intact."),
        ("BEGINNER", "Which clause is used to filter rows in a SELECT query?",
         ["GROUP BY", "ORDER BY", "WHERE", "HAVING"], "C",
         "WHERE filters individual rows before any grouping or aggregation takes place."),
        ("BEGINNER", "What does the * symbol mean in a query such as SELECT * FROM employees?",
         ["The average value", "A single column", "The primary key", "All columns"], "D",
         "The asterisk is shorthand that selects all columns of the table in the order they were defined."),
        ("BEGINNER", "Which data type would you use to store a whole number such as an employee id?",
         ["INT", "VARCHAR", "DATE", "TEXT"], "A",
         "INT stores integer values, which is exactly what an employee id represents."),
        ("BEGINNER", "Which SQL command adds a new column to an existing table?",
         ["ADD TABLE", "ALTER TABLE", "MODIFY TABLE", "UPDATE TABLE"], "B",
         "ALTER TABLE is used to change the structure of a table, including adding new columns."),
        ("BEGINNER", "Which clause sorts the results of a SELECT query?",
         ["SORT BY", "GROUP BY", "ORDER BY", "ARRANGE BY"], "C",
         "ORDER BY sorts the result rows by one or more columns in ascending or descending order."),
        ("BEGINNER", "Which SQL command permanently removes a table along with its structure and all data?",
         ["DELETE", "TRUNCATE", "REMOVE", "DROP TABLE"], "D",
         "DROP TABLE deletes the entire table definition and all of its data, so it removes the structure permanently."),
        ("BEGINNER", "Which clause limits the number of rows returned by a query?",
         ["LIMIT", "BOUND", "STOP", "RANGE"], "A",
         "LIMIT (called TOP in some databases) restricts how many result rows are returned."),
        ("BEGINNER", "Which of the following is a Data Definition Language (DDL) command?",
         ["SELECT", "CREATE", "INSERT", "UPDATE"], "B",
         "CREATE defines or modifies database structure, so it is classified as a DDL command."),
        ("INTERMEDIATE", "Which statement creates a table named departments with a primary key on the id column?",
         ["CREATE departments (id INT PRIMARY KEY, name VARCHAR(100));",
          "MAKE TABLE departments (id INT, name VARCHAR(100));",
          "CREATE TABLE departments (id INT PRIMARY KEY, name VARCHAR(100));",
          "CREATE TABLE departments (id INT, name VARCHAR(100), PRIMARY FOREIGN KEY id);"], "C",
         "CREATE TABLE followed by column definitions marks id with PRIMARY KEY so it uniquely identifies each row."),
        ("INTERMEDIATE", "Which query returns only the distinct department ids from the employees table?",
         ["SELECT DISTINCT dept_id FROM employees;",
          "SELECT dept_id DIFFERENT FROM employees;",
          "SELECT DISTINCT dept_id FROM employees WHERE DISTINCT;",
          "SELECT UNIQUE dept_id FROM employees;"], "A",
         "DISTINCT removes duplicate values so each department id appears only once in the result."),
        ("INTERMEDIATE", "You need to add a column named email to the employees table. Which statement is correct?",
         ["ADD COLUMN email TO employees;",
          "ALTER TABLE employees ADD COLUMN email VARCHAR(100);",
          "UPDATE employees SET email = email;",
          "CREATE COLUMN email IN employees;"], "B",
         "ALTER TABLE employees ADD COLUMN adds the new column to the existing table definition."),
        ("INTERMEDIATE", "Which query selects all employees earning more than 50000 sorted by name in descending order?",
         ["SELECT * FROM employees WHERE salary > 50000 SORT BY name DESC;",
          "SELECT * FROM employees WHERE salary > 50000 GROUP BY name;",
          "SELECT * FROM employees WHERE salary < 50000 ORDER BY name DESC;",
          "SELECT * FROM employees WHERE salary > 50000 ORDER BY name DESC;"], "D",
         "WHERE filters on the salary, and ORDER BY name DESC sorts alphabetically in reverse order."),
        ("INTERMEDIATE", "What is the main purpose of a primary key constraint on a table?",
         ["To allow duplicate rows",
          "To speed up SELECT * queries",
          "To enforce that all columns are not null",
          "To uniquely identify each row in the table"], "D",
         "A primary key guarantees each row has a unique, non-null identifier, which is its main purpose."),
        ("INTERMEDIATE", "Which query returns employees whose names start with the letter 'A'?",
         ["SELECT * FROM employees WHERE name = 'A';",
          "SELECT * FROM employees WHERE name LIKE 'A';",
          "SELECT * FROM employees WHERE name LIKE 'A%';",
          "SELECT * FROM employees WHERE name LIKE '%A';"], "C",
         "The LIKE pattern 'A%' matches any name that begins with 'A' followed by any number of characters."),
        ("INTERMEDIATE", "In a CREATE TABLE statement, what does the UNIQUE constraint guarantee?",
         ["The column is automatically sorted",
          "The column must be numeric",
          "All values in the column are distinct",
          "The column cannot be indexed"], "C",
         "UNIQUE ensures no two rows can have the same value in that column, though NULLs are still typically allowed."),
        ("INTERMEDIATE", "Which command removes the primary key constraint named pk_emp from the employees table?",
         ["ALTER TABLE employees DROP PRIMARY KEY pk_emp;",
          "ALTER TABLE employees DROP CONSTRAINT pk_emp;",
          "DROP CONSTRAINT pk_emp FROM employees;",
          "DELETE CONSTRAINT pk_emp FROM employees;"], "B",
         "ALTER TABLE ... DROP CONSTRAINT removes the named constraint from the table structure."),
        ("INTERMEDIATE", "Which data type is most appropriate for storing a salary such as 52500.75?",
         ["INT", "VARCHAR", "BOOLEAN", "DECIMAL(10,2)"], "D",
         "DECIMAL(10,2) stores exact numbers with two decimal places, which is ideal for money values without rounding errors."),
        ("INTERMEDIATE", "Which query correctly finds employees whose name column is NULL?",
         ["SELECT * FROM employees WHERE name = NULL;",
          "SELECT * FROM employees WHERE name == NULL;",
          "SELECT * FROM employees WHERE name IS NULL;",
          "SELECT * FROM employees WHERE name IS EMPTY;"], "C",
         "NULL cannot be compared with =, so the IS NULL operator is required to test for NULL values."),
        ("ADVANCED", "Why can a TRUNCATE operation usually not be rolled back in many databases while a DELETE can?",
         ["TRUNCATE removes only rows matching a WHERE clause",
          "TRUNCATE deallocates data pages and is not row-logged, so it usually cannot be rolled back while DELETE can",
          "TRUNCATE cannot be used on a table with an index",
          "DELETE never writes to the transaction log"], "B",
         "TRUNCATE is a DDL-like operation that deallocates data pages and is not row-logged, whereas DELETE logs each row so it can be rolled back."),
        ("ADVANCED", "Which SQL statement correctly defines a composite primary key on (id, course_id) in a table named enrollments?",
         ["CREATE TABLE enrollments (PRIMARY KEY id AND course_id);",
          "CREATE TABLE enrollments (id INT PRIMARY KEY, course_id INT PRIMARY KEY);",
          "CREATE TABLE enrollments (id INT, course_id INT, grade CHAR, PRIMARY KEY (id, course_id));",
          "CREATE TABLE enrollments (id, course_id) PRIMARY KEY;"], "C",
         "A composite key is declared with PRIMARY KEY listing both columns, which uniquely identifies a row only by the pair together."),
        ("ADVANCED", "Which statement is TRUE about a NOT NULL constraint?",
         ["NOT NULL allows NULLs but blocks duplicates",
          "NOT NULL creates a unique index automatically",
          "NOT NULL requires a default value",
          "NOT NULL only prevents NULL values but still allows duplicate entries"], "D",
         "NOT NULL only forbids NULL entries; it does nothing about duplicate values, which is why NOT NULL and UNIQUE are combined for identifier columns."),
        ("ADVANCED", "Which of the following correctly classifies the SQL statements?",
         ["CREATE and ALTER are DDL; INSERT and DELETE are DML",
          "SELECT and INSERT are DDL; CREATE and DROP are DML",
          "TRUNCATE and UPDATE are DDL; SELECT is DML",
          "All SQL statements are DDL"], "A",
         "DDL covers CREATE, ALTER, and DROP (structure), while DML covers INSERT, UPDATE, and DELETE (data)."),
        ("ADVANCED", "If table departments has a foreign key referencing employees, what happens by default when you drop the employees table?",
         ["Both tables are dropped automatically",
          "The drop fails because departments depends on the employees table",
          "Only departments is dropped",
          "NULLs are inserted into departments"], "B",
         "Dropping a parent table referenced by a foreign key violates referential integrity, so the database rejects the DROP."),
        ("ADVANCED", "Which statement correctly adds a foreign key to an existing table?",
         ["ALTER TABLE employees ADD COLUMN dept_id;",
          "CREATE INDEX FOREIGN KEY dept_id;",
          "ALTER TABLE employees ADD FOREIGN KEY (dept_id) REFERENCES departments(id);",
          "ALTER TABLE departments ADD FOREIGN KEY dept_id;"], "C",
         "ALTER TABLE ... ADD FOREIGN KEY links dept_id in employees to the primary key id in departments."),
        ("ADVANCED", "What is the effect of declaring a column with DEFAULT 0?",
         ["All existing rows are updated to 0",
          "The column cannot store any other value",
          "NULL is never allowed in the column",
          "New rows get 0 when no value is supplied"], "D",
         "A DEFAULT value is used only when an INSERT does not provide a value for that column, so missing values become 0."),
        ("ADVANCED", "Which approach lets you run the expression SELECT 2 * 3 AS result without any table?",
         ["Databases such as MySQL allow a SELECT with no FROM clause for literal expressions",
          "It is only possible in PostgreSQL",
          "You must first create a dummy table",
          "It always raises a syntax error"], "A",
         "Databases such as MySQL and PostgreSQL allow SELECT over expressions without a FROM clause for computing literal values."),
        ("ADVANCED", "Which difference between a CHECK constraint and a NOT NULL constraint is correct?",
         ["They are identical constraints",
          "CHECK validates an arbitrary boolean condition while NOT NULL only bans NULLs",
          "CHECK is used only on foreign keys",
          "NOT NULL can enforce ranges of values"], "B",
         "CHECK enforces an arbitrary boolean condition on column values, while NOT NULL only rejects NULL entries."),
        ("ADVANCED", "You want to remove the salary column from the employees table. Which statement achieves this?",
         ["DELETE COLUMN salary FROM employees;",
          "UPDATE employees REMOVE salary;",
          "DROP COLUMN salary ALTER employees;",
          "ALTER TABLE employees DROP COLUMN salary;"], "D",
         "ALTER TABLE ... DROP COLUMN removes the column definition and all of its data from the table."),
    ],
    32: [
        ("BEGINNER", "Which SQL statement is used to insert new rows into a table?",
         ["INSERT", "SELECT", "UPDATE", "DELETE"], "A",
         "INSERT INTO is the DML statement that adds new rows to a table."),
        ("BEGINNER", "Which statement is used to change the values of existing data in a table?",
         ["INSERT", "UPDATE", "DELETE", "CREATE"], "B",
         "UPDATE modifies the values of existing rows in a table."),
        ("BEGINNER", "Which statement removes rows from a table?",
         ["INSERT", "UPDATE", "DELETE", "ALTER"], "C",
         "DELETE removes one or more rows from a table based on its WHERE condition."),
        ("BEGINNER", "What does the acronym CRUD stand for?",
         ["Copy, Read, Update, Delete",
          "Create, Read, Unlock, Delete",
          "Create, Remove, Update, Drop",
          "Create, Read, Update, Delete"], "D",
         "CRUD stands for Create, Read, Update, and Delete, the four basic operations on persistent data."),
        ("BEGINNER", "Which keyword in an UPDATE statement controls exactly which rows get changed?",
         ["WHERE", "SET", "HAVING", "GROUP BY"], "A",
         "WHERE restricts the UPDATE so only the rows matching the condition are modified."),
        ("BEGINNER", "What happens if you run DELETE FROM employees without a WHERE clause?",
         ["An error is raised",
          "All rows in the table are deleted",
          "Only the first row is deleted",
          "The table structure is removed"], "B",
         "Without a WHERE clause every row in the table is deleted, although the table structure remains."),
        ("BEGINNER", "Which statement correctly inserts the name 'Ann' and a salary of 50000 into the employees table?",
         ["INSERT employees (name, salary) VALUES 'Ann', 50000;",
          "ADD INTO employees (name, salary) (Ann, 50000);",
          "INSERT INTO employees (name, salary) VALUES ('Ann', 50000);",
          "UPDATE employees SET name = 'Ann', salary = 50000;"], "C",
         "INSERT INTO followed by column names and a VALUES list is the correct syntax for adding a new row."),
        ("BEGINNER", "When inserting into a table with an auto-increment primary key, which column is usually filled in automatically?",
         ["name", "dept_id", "salary", "id"], "D",
         "An auto-increment column such as id is generated by the database automatically during the INSERT."),
        ("BEGINNER", "Which statement changes Ann's salary to 60000?",
         ["UPDATE employees SET salary = 60000 WHERE name = 'Ann';",
          "UPDATE employees SET name = 'Ann' WHERE salary = 60000;",
          "UPDATE employees VALUES salary = 60000 WHERE name = 'Ann';",
          "INSERT INTO employees (salary) VALUES (60000);"], "A",
         "UPDATE employees SET salary = 60000 with a WHERE on name changes only Ann's salary value."),
        ("BEGINNER", "Which is the correct syntax for inserting several rows in one statement?",
         ["INSERT INTO employees VALUES (1, 'Ann'); (2, 'Bob');",
          "INSERT INTO employees (id, name) VALUES (1, 'Ann'), (2, 'Bob');",
          "INSERT INTO employees (1, 'Ann') AND (2, 'Bob');",
          "INSERT MULTIPLE INTO employees (id, name) VALUES (1, 'Ann'), (2, 'Bob');"], "B",
         "A multi-row insert lists each row's values as a separate tuple separated by commas after VALUES."),
        ("INTERMEDIATE", "INSERT INTO employees (dept_id, salary) VALUES (3, 45000); is run and name has no NOT NULL constraint. What is the value of the omitted name column?",
         ["An empty string",
          "The previous row's name",
          "NULL (or its declared default value)",
          "The statement fails"], "C",
         "Columns not listed in the INSERT are set to NULL or to their declared default value."),
        ("INTERMEDIATE", "Which statement increases every employee's salary by 10 percent?",
         ["UPDATE employees SET salary = salary * 1.10;",
          "UPDATE employees SET salary = 10;",
          "UPDATE employees ADD salary * 1.10;",
          "UPDATE employees SET salary = salary + 10;"], "A",
         "Multiplying salary by 1.10 adds ten percent to every current salary value."),
        ("INTERMEDIATE", "Which statement updates both the name and the salary of employee id 1 in one UPDATE?",
         ["UPDATE employees SET name = 'Ann' AND salary = 60000 WHERE id = 1;",
          "UPDATE employees SET name = 'Ann', salary = 60000 WHERE id = 1;",
          "UPDATE employees SET (name, salary) = ('Ann', 60000);",
          "UPDATE employees name = 'Ann' salary = 60000 WHERE id = 1;"], "B",
         "Multiple assignments in UPDATE are separated by commas in the SET clause."),
        ("INTERMEDIATE", "Which query deletes employees whose names start with 'Temp'?",
         ["DELETE FROM employees WHERE name = 'Temp';",
          "DELETE FROM employees WHERE name IN 'Temp';",
          "DELETE FROM employees WHERE name LIKE 'Temp';",
          "DELETE FROM employees WHERE name LIKE 'Temp%';"], "D",
         "The LIKE pattern 'Temp%' matches any name that begins with 'Temp', so those rows are deleted."),
        ("INTERMEDIATE", "Which statement copies all rows from old_employees into the existing employees table?",
         ["INSERT INTO employees SELECT * FROM old_employees;",
          "INSERT INTO employees VALUES (SELECT * FROM old_employees);",
          "COPY old_employees TO employees;",
          "INSERT INTO employees FROM old_employees;"], "A",
         "INSERT INTO ... SELECT reads rows from old_employees and adds them to employees in one statement."),
        ("INTERMEDIATE", "What happens when you INSERT a row whose id already exists in a primary key column?",
         ["The new row silently replaces the old one",
          "The new row is skipped",
          "The insert fails with a duplicate key error",
          "Both rows are stored"], "C",
         "A primary key requires unique values, so inserting a duplicate id raises a duplicate key error."),
        ("INTERMEDIATE", "Which statement deletes employees in department 5 whose salary is below 30000?",
         ["DELETE FROM employees WHERE dept_id = 5 OR salary < 30000;",
          "DELETE FROM employees WHERE dept_id = 5 AND salary < 30000;",
          "DELETE FROM employees WHERE dept_id = 5, salary < 30000;",
          "DELETE FROM employees WHERE dept_id = 5 AND salary > 30000;"], "B",
         "AND combines both conditions so only rows meeting both are deleted, matching the requirement."),
        ("INTERMEDIATE", "You run UPDATE employees SET dept_id = NULL WHERE id = 4; on a row that exists. What is TRUE afterwards?",
         ["The whole row is deleted",
          "The row is moved to another table",
          "The database rejects the UPDATE",
          "The row keeps existing with NULL in dept_id"], "D",
         "UPDATE only changes the listed column, so the row remains with dept_id set to NULL."),
        ("INTERMEDIATE", "Which statement deletes orders rows that have no matching employee in the employees table?",
         ["DELETE FROM orders WHERE emp_id NOT IN (SELECT id FROM employees);",
          "DELETE FROM orders WHERE emp_id IN (SELECT id FROM employees);",
          "DELETE FROM employees WHERE id NOT IN (SELECT emp_id FROM orders);",
          "DELETE FROM orders JOIN employees ON orders.emp_id = employees.id;"], "A",
         "NOT IN with a subquery selects orders whose emp_id does not appear among valid employee ids, deleting only those."),
        ("INTERMEDIATE", "Which statement sets a NULL salary to 0 for all employees?",
         ["UPDATE employees SET salary = 0 WHERE salary IS NOT NULL;",
          "UPDATE employees SET salary = NULL WHERE salary = 0;",
          "UPDATE employees SET salary = 0 WHERE salary IS NULL;",
          "UPDATE employees SET salary = 0 WHERE salary != 0;"], "C",
         "WHERE salary IS NULL targets only the rows whose salary is NULL, and SET salary = 0 writes the new value."),
        ("ADVANCED", "Which statement is TRUE about INSERT ... ON DUPLICATE KEY UPDATE in MySQL?",
         ["It always inserts a new row",
          "It updates the existing row when a unique key collision occurs, otherwise inserts a new row",
          "It is invalid syntax in MySQL",
          "It deletes the colliding row and inserts a new one"], "B",
         "ON DUPLICATE KEY UPDATE performs an UPDATE of the conflicting row on a unique-key collision and otherwise inserts."),
        ("ADVANCED", "What is a key difference between REPLACE INTO and INSERT ... ON DUPLICATE KEY UPDATE?",
         ["There is no difference between them",
          "ON DUPLICATE KEY UPDATE deletes the old row first",
          "REPLACE deletes the conflicting row and inserts a new one, while ON DUPLICATE KEY UPDATE changes only specified columns",
          "REPLACE only works on MyISAM tables"], "C",
         "REPLACE removes the conflicting row and inserts a fresh one, whereas ON DUPLICATE KEY UPDATE only modifies the listed columns."),
        ("ADVANCED", "Inside a transaction you run an UPDATE and then issue a ROLLBACK. What is the result?",
         ["The UPDATE is kept",
          "Only half the rows keep the update",
          "The statement fails at rollback time",
          "The table returns to its state before the UPDATE"], "D",
         "ROLLBACK undoes all uncommitted changes in the transaction, restoring the table to its prior state."),
        ("ADVANCED", "If a foreign key between orders and employees is defined with ON DELETE CASCADE, what happens when you delete an employee?",
         ["Deleting an employee automatically deletes their orders",
          "Deleting an employee is blocked",
          "Orders keep the deleted employee id",
          "The database repairs the orders"], "A",
         "ON DELETE CASCADE propagates the deletion so that referencing rows in orders are removed automatically."),
        ("ADVANCED", "Which UPDATE modifies only employees who have a matching record in the departments table?",
         ["UPDATE employees SET bonus = 100 WHERE dept_id = 1;",
          "UPDATE employees SET bonus = 100 WHERE dept_id IN (SELECT id FROM departments);",
          "UPDATE employees SET bonus = 100 FOR ALL ROWS;",
          "UPDATE employees SET bonus = 100 WHERE dept_id NOT IN (SELECT id FROM departments);"], "B",
         "The IN subquery restricts the UPDATE to dept_id values that actually exist in departments."),
        ("ADVANCED", "What does an upsert operation such as PostgreSQL INSERT ... ON CONFLICT achieve?",
         ["Deletes the conflicting row",
          "Only inserts rows, never updates",
          "Inserts a new row or updates the conflicting row in one statement",
          "Is only valid inside stored procedures"], "C",
         "An upsert inserts a new row when there is no conflict and updates the existing row when a conflict occurs, all in one statement."),
        ("ADVANCED", "Which approach cleanly deletes the employee with the highest salary?",
         ["DELETE FROM employees WHERE salary > ALL;",
          "TRUNCATE employees;",
          "DELETE TOP 1 FROM employees;",
          "DELETE FROM employees WHERE salary = (SELECT MAX(salary) FROM employees);"], "D",
         "The scalar subquery computes the maximum salary, and the DELETE removes exactly the row holding that value."),
        ("ADVANCED", "Which statement is TRUE about a multi-table DELETE in MySQL, such as DELETE t1 FROM t1 JOIN t2 ON ...?",
         ["MySQL supports deleting rows from one table using a multi-table DELETE with JOIN syntax",
          "You can never use a join inside a DELETE statement",
          "Joins are only allowed in SELECT statements",
          "Multi-table DELETE is exclusive to Oracle"], "A",
         "MySQL allows a multi-table DELETE where rows of one table are deleted based on a JOIN with another table."),
        ("ADVANCED", "After running UPDATE employees SET dept_id = dept_id + 1 WHERE dept_id < 3; twice in a row, which rows change in the second run?",
         ["The same rows are updated again",
          "Only rows that still satisfy dept_id < 3 are updated again",
          "All rows are updated again",
          "The statement fails the second time"], "B",
         "The second run only affects rows whose dept_id is still less than 3, since the first run shifted some rows out of range."),
        ("ADVANCED", "Which statement sets bonus to 500 only for employees in department 4 while leaving all other rows unchanged?",
         ["UPDATE employees SET bonus = 500 FOR dept_id = 4;",
          "UPDATE employees SET bonus = 500 WHERE dept_id != 4;",
          "INSERT INTO employees (bonus) VALUES (500);",
          "UPDATE employees SET bonus = 500 WHERE dept_id = 4;"], "D",
         "The WHERE dept_id = 4 condition restricts the bonus change to exactly the employees in department 4."),
    ],
    33: [
        ("BEGINNER", "Which join returns only the rows that have matching values in both tables?",
         ["INNER JOIN", "LEFT JOIN", "FULL OUTER JOIN", "CROSS JOIN"], "A",
         "INNER JOIN keeps only the rows where the join condition matches in both tables."),
        ("BEGINNER", "Which join returns all rows from the left table and the matching rows from the right table?",
         ["RIGHT JOIN", "LEFT JOIN", "FULL OUTER JOIN", "INNER JOIN"], "B",
         "LEFT JOIN keeps every row of the left table and fills unmatched right-side columns with NULL."),
        ("BEGINNER", "Which join returns all rows from both tables, filling in NULLs for the sides without a match?",
         ["INNER JOIN", "LEFT JOIN", "FULL OUTER JOIN", "SELF JOIN"], "C",
         "FULL OUTER JOIN returns every row from both tables, using NULLs where no match exists on either side."),
        ("BEGINNER", "Which keyword specifies how two tables are related in a JOIN?",
         ["SET", "USING IN", "HAVING", "ON"], "D",
         "The ON clause supplies the join condition that describes how rows from the two tables correspond."),
        ("BEGINNER", "A CROSS JOIN between two tables produces what kind of result?",
         ["The Cartesian product of the two tables",
          "Only the exact matching rows",
          "A single summary row",
          "An error"], "A",
         "A CROSS JOIN pairs every row of the first table with every row of the second, forming the Cartesian product."),
        ("BEGINNER", "Which join returns all rows from the right table and the matching rows from the left table?",
         ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "OUTER LEFT"], "B",
         "RIGHT JOIN keeps every row of the right table and uses NULLs for unmatched left-side columns."),
        ("BEGINNER", "What is a self join?",
         ["Joining two unrelated tables",
          "Joining three tables at once",
          "Joining a table to itself",
          "Joining a table to its stored backup"], "C",
         "A self join joins a table to itself, usually with different aliases, to compare rows within the same table."),
        ("BEGINNER", "employees(id, name, dept_id) is INNER JOINed to departments(id, name) on employees.dept_id = departments.id. How many rows result if 3 employees match and 1 employee has a department id that does not exist?",
         ["1", "4", "2", "3"], "D",
         "INNER JOIN keeps only matching rows, so the 3 employees whose department exists appear and the unmatched employee is dropped."),
        ("BEGINNER", "In a LEFT JOIN, what appears in the result for an employee whose department does not exist?",
         ["The department columns are NULL",
          "The employee row is dropped",
          "A new department is created",
          "The query fails"], "A",
         "LEFT JOIN preserves every employee row and fills the missing department columns with NULL when there is no match."),
        ("BEGINNER", "Which join would you use to list every department even if it has no employees?",
         ["INNER JOIN",
          "A LEFT JOIN where departments is the left table",
          "CROSS JOIN",
          "A LEFT JOIN where employees is the left table"], "B",
         "Putting departments on the left of a LEFT JOIN guarantees every department appears, with NULLs for empty ones."),
        ("INTERMEDIATE", "employees(id, name, dept_id): rows (1,'Ann',1),(2,'Bob',1),(3,'Cid',4). departments(id, name): (1,'Sales'),(2,'IT'),(3,'HR'). How many rows does an INNER JOIN on employees.dept_id = departments.id produce?",
         ["3", "5", "2", "9"], "C",
         "Ann and Bob match department 1, but Cid's department 4 does not exist, so only 2 matching rows remain."),
        ("INTERMEDIATE", "Using the same employees and departments tables, how many rows does a LEFT JOIN with employees as the left table produce?",
         ["3", "4", "2", "5"], "A",
         "LEFT JOIN returns all 3 employee rows, with Cid's department columns filled as NULL because dept 4 is missing."),
        ("INTERMEDIATE", "Using the same tables, what department name does employee Ann get in the INNER JOIN result?",
         ["Sales", "IT", "HR", "NULL"], "A",
         "Ann has dept_id 1 which matches the department named 'Sales', so her joined row shows Sales."),
        ("INTERMEDIATE", "If employees has 3 rows and departments has 4 rows, how many rows does a CROSS JOIN produce?",
         ["7", "4", "3", "12"], "D",
         "A CROSS JOIN produces the Cartesian product, which is 3 multiplied by 4, giving 12 rows."),
        ("INTERMEDIATE", "Which query lists each employee together with the name of their department?",
         ["SELECT e.name, d.name FROM employees e INNER JOIN departments d ON e.dept_id = d.id;",
          "SELECT e.name, d.name FROM employees e, departments d WHERE e.id = d.id;",
          "SELECT e.name, d.name FROM employees e FULL JOIN departments d ON e.dept_id = d.id;",
          "SELECT e.name, d.name FROM employees e CROSS JOIN departments d;"], "A",
         "The INNER JOIN on dept_id = id connects each employee to the correct department so both names can be listed."),
        ("INTERMEDIATE", "Which query finds the employees who work in the 'Sales' department using a join?",
         ["SELECT e.* FROM employees e JOIN departments d ON e.dept_id = d.id;",
          "SELECT e.* FROM employees e JOIN departments d ON e.dept_id = d.id WHERE d.id = 1;",
          "SELECT e.* FROM employees e JOIN departments d ON e.dept_id = d.id WHERE d.name = 'Sales';",
          "SELECT e.* FROM employees e JOIN departments d ON e.name = d.name WHERE d.name = 'Sales';"], "C",
         "Joining on dept_id and filtering with WHERE d.name = 'Sales' returns exactly the employees of that department."),
        ("INTERMEDIATE", "A self join on employees using manager_id is most useful for finding what?",
         ["Employees in different departments",
          "Employees together with their manager's name from the same table",
          "Department names for each employee",
          "Only employees without managers"], "B",
         "A self join pairs each employee row with the manager row from the same table, revealing the manager's name."),
        ("INTERMEDIATE", "Which join is equivalent to RIGHT JOIN departments d ON ... with employees as the other table?",
         ["INNER JOIN",
          "CROSS JOIN",
          "FULL OUTER JOIN",
          "A LEFT JOIN with the tables swapped"], "D",
         "Reversing the table order and using LEFT JOIN produces the same rows as a RIGHT JOIN on the original order."),
        ("INTERMEDIATE", "Which join shows every employee, and for employees in no department the department name appears as NULL?",
         ["LEFT JOIN employees.dept_id = departments.id",
          "INNER JOIN",
          "RIGHT JOIN",
          "CROSS JOIN"], "A",
         "LEFT JOIN keeps all employee rows and uses NULL for department columns of employees without a matching department."),
        ("INTERMEDIATE", "Which query counts the number of employees in each department, including departments with zero employees?",
         ["SELECT d.name, COUNT(*) FROM employees e JOIN departments d GROUP BY e.dept_id;",
          "SELECT d.name, COUNT(e.id) FROM departments d JOIN employees e ON d.id = e.dept_id ORDER BY d.name;",
          "SELECT d.name, COUNT(e.id) FROM departments d LEFT JOIN employees e ON d.id = e.dept_id GROUP BY d.id, d.name;",
          "SELECT COUNT(*) FROM employees JOIN departments;"], "C",
         "The LEFT JOIN preserves all departments, and GROUP BY d.id, d.name lets COUNT(e.id) count employees per department including zeros."),
        ("ADVANCED", "MySQL does not natively support FULL OUTER JOIN. Which construct emulates it?",
         ["A single INNER JOIN",
          "A UNION of a LEFT JOIN result and a RIGHT JOIN result",
          "A CROSS JOIN",
          "A self join"], "B",
         "Combining a LEFT JOIN and a RIGHT JOIN with UNION yields every row from both tables, which is the effect of FULL OUTER JOIN."),
        ("ADVANCED", "In LEFT JOIN employees e LEFT JOIN departments d ON e.dept_id = d.id, what happens if you add WHERE d.name = 'Sales'?",
         ["It still returns all employees",
          "It returns only the unmatched rows",
          "The WHERE clause filters out rows with NULL department columns, so unmatched employees disappear",
          "It raises an error"], "C",
         "The WHERE filter runs after the join and removes rows where d.name is NULL, effectively turning the LEFT JOIN into an INNER JOIN."),
        ("ADVANCED", "What is a non-equi join?",
         ["A join on primary keys",
          "A join without the ON clause",
          "A join between unrelated tables",
          "A join using a comparison operator other than equals, such as < or >"], "D",
         "A non-equi join uses operators like <, >, BETWEEN, or <> in the join condition instead of a plain equality."),
        ("ADVANCED", "To make the join employees.dept_id = departments.id run as fast as possible, what should you index?",
         ["The dept_id column in employees and the id primary key in departments",
          "Only the name columns",
          "No index helps a join",
          "The salary column"], "A",
         "An index on the join columns, especially the foreign key dept_id and the referenced primary key id, lets the database find matches quickly."),
        ("ADVANCED", "Which query correctly joins employees to itself to pair each employee with their manager's name?",
         ["SELECT e.name, m.name FROM employees e JOIN employees m ON e.manager_id = m.name;",
          "SELECT e.name AS emp, m.name AS mgr FROM employees e LEFT JOIN employees m ON e.manager_id = m.id;",
          "SELECT e.name FROM employees e INNER JOIN employees m ON e.id = m.id;",
          "SELECT e.name, m.name FROM employees e, departments m;"], "B",
         "The self join matches each employee's manager_id to the manager's id in the same table, and LEFT JOIN keeps employees without managers."),
        ("ADVANCED", "Which query returns the departments that have no employees at all?",
         ["SELECT d.name FROM departments d INNER JOIN employees e ON d.id = e.dept_id;",
          "SELECT d.name FROM departments d LEFT JOIN employees e ON d.id = e.dept_id;",
          "SELECT d.name FROM departments d LEFT JOIN employees e ON d.id = e.dept_id WHERE e.id IS NULL;",
          "SELECT d.name FROM departments d CROSS JOIN employees e WHERE d.id IS NULL;"], "C",
         "The LEFT JOIN keeps all departments, and WHERE e.id IS NULL isolates those departments where no employee matched."),
        ("ADVANCED", "What is the result of a CROSS JOIN between employees, which has 3 rows, and departments, which has 4 rows?",
         ["7 rows", "4 rows", "3 rows", "12 rows"], "D",
         "A CROSS JOIN multiplies the row counts, so 3 times 4 equals 12 rows in the result."),
        ("ADVANCED", "In which situation does a LEFT JOIN return MORE rows than an INNER JOIN on the same condition?",
         ["When the left table has rows with no match in the right table",
          "When every row has a match",
          "Never",
          "When the right table has duplicate rows"], "A",
         "LEFT JOIN keeps all left-table rows, so any left row without a right-side match adds a row that the INNER JOIN would drop."),
        ("ADVANCED", "Which query returns employees who work in departments whose name contains 'Tech'?",
         ["SELECT e.name FROM employees e JOIN departments d ON e.dept_id = d.id WHERE d.name = 'Tech';",
          "SELECT e.name FROM employees e JOIN departments d ON e.dept_id = d.id WHERE d.name LIKE '%Tech%';",
          "SELECT e.name FROM employees e JOIN departments d ON e.dept_id = d.id WHERE e.name LIKE '%Tech%';",
          "SELECT e.name FROM employees e LEFT JOIN departments d ON e.dept_id = d.id;"], "B",
         "The LIKE '%Tech%' filter on the department name matches any department containing 'Tech' after the join."),
        ("ADVANCED", "What distinguishes a join condition in the ON clause from one in the WHERE clause for an OUTER join?",
         ["There is no difference between them",
          "ON is always faster than WHERE",
          "WHERE can only use equality comparisons",
          "ON controls which rows join and preserves unmatched rows; WHERE filters the joined result and removes unmatched rows"], "D",
         "ON determines the join and preserves unmatched outer rows, while a WHERE condition filters the final result and can discard those rows."),
    ],
    34: [
        ("BEGINNER", "What is a subquery?",
         ["A query nested inside another query",
          "A query run after the main query",
          "A table that is joined twice",
          "A stored procedure"], "A",
         "A subquery is a complete query written inside another query, such as in the WHERE or FROM clause."),
        ("BEGINNER", "Which operator checks whether a value appears in the result of a subquery?",
         ["BETWEEN", "IN", "LIKE", "IS"], "B",
         "The IN operator returns TRUE when the value matches any value in the subquery result list."),
        ("BEGINNER", "Which set operator combines two result sets and removes duplicate rows?",
         ["JOIN", "MERGE", "UNION", "COMBINE"], "C",
         "UNION combines two queries and removes duplicate rows from the final result."),
        ("BEGINNER", "Which set operator returns only the rows that are present in both result sets?",
         ["UNION", "EXCEPT", "MINUS", "INTERSECT"], "D",
         "INTERSECT returns the rows that appear in both of the combined queries."),
        ("BEGINNER", "A scalar subquery returns how many values?",
         ["Exactly one value",
          "A list of many values",
          "A whole table",
          "No value"], "A",
         "A scalar subquery returns a single row and a single column, i.e., exactly one value."),
        ("BEGINNER", "Which set operator returns the rows from the first result set that do NOT appear in the second?",
         ["INTERSECT",
          "EXCEPT (or MINUS)",
          "UNION",
          "INNER JOIN"], "B",
         "EXCEPT (called MINUS in Oracle) returns rows that are in the first query but not in the second."),
        ("BEGINNER", "What does UNION ALL do differently compared to UNION?",
         ["It removes all rows",
          "It is slower than INTERSECT",
          "It keeps all rows including duplicates",
          "It sorts the output automatically"], "C",
         "UNION ALL keeps every row from both queries, including duplicates, instead of removing them like UNION."),
        ("BEGINNER", "Where can a subquery be placed in a SQL statement?",
         ["Only in the WHERE clause",
          "Only in the FROM clause",
          "Only in the ORDER BY clause",
          "In the WHERE, FROM, or SELECT clause"], "D",
         "Subqueries are commonly used in WHERE, FROM (as a derived table), and SELECT clauses."),
        ("BEGINNER", "Which keyword tests whether a subquery returns at least one row?",
         ["EXISTS", "ANY", "ALL", "IN"], "A",
         "EXISTS returns TRUE if the subquery produces one or more rows, regardless of their values."),
        ("BEGINNER", "Which operator checks that a value is less than ALL values returned by a subquery?",
         ["ANY", "ALL", "SOME", "EVERY"], "B",
         "The ALL operator requires the comparison to hold for every value returned by the subquery."),
        ("INTERMEDIATE", "Which query finds employees who earn more than the average salary of all employees?",
         ["SELECT * FROM employees WHERE salary > AVG(salary);",
          "SELECT * FROM employees HAVING salary > AVG(salary);",
          "SELECT * FROM employees WHERE salary > (SELECT AVG(salary) FROM employees);",
          "SELECT * FROM employees WHERE salary > (SELECT MAX(salary) FROM employees);"], "C",
         "The scalar subquery computes the overall average, and the WHERE clause keeps employees above it."),
        ("INTERMEDIATE", "Which query returns employees who work in the 'Sales' or 'IT' departments using IN with a subquery?",
         ["SELECT * FROM employees WHERE dept_id IN (SELECT id FROM departments WHERE name IN ('Sales', 'IT'));",
          "SELECT * FROM employees WHERE dept_id = (SELECT id FROM departments WHERE name = 'Sales');",
          "SELECT * FROM employees WHERE dept_id IN (SELECT name FROM departments);",
          "SELECT * FROM employees WHERE name IN ('Sales', 'IT');"], "A",
         "The subquery returns the ids of the Sales and IT departments, and IN keeps employees whose dept_id matches one of them."),
        ("INTERMEDIATE", "Which query lists each employee's name together with the overall maximum salary as a column?",
         ["SELECT name, MAX(salary) FROM employees;",
          "SELECT name, (SELECT MAX(salary) FROM employees) AS max_sal FROM employees;",
          "SELECT name, SUM(salary) FROM employees;",
          "SELECT name FROM employees WHERE salary = MAX(salary);"], "B",
         "A scalar subquery in the SELECT list adds the overall maximum salary to every row without grouping the result."),
        ("INTERMEDIATE", "Which query finds the second-highest salary in the employees table?",
         ["SELECT MAX(salary) FROM employees WHERE salary = MAX(salary);",
          "SELECT salary FROM employees LIMIT 1, 1;",
          "SELECT MAX(salary) FROM employees ORDER BY salary DESC;",
          "SELECT MAX(salary) FROM employees WHERE salary < (SELECT MAX(salary) FROM employees);"], "D",
         "The inner subquery gets the highest salary, and the outer MAX finds the largest salary below it."),
        ("INTERMEDIATE", "What is a correlated subquery?",
         ["A subquery that references columns of the outer query and runs once per outer row",
          "A subquery that runs exactly once",
          "A subquery that cannot use EXISTS",
          "A subquery placed in the FROM clause"], "A",
         "A correlated subquery refers to columns of the enclosing query, so it is evaluated once for each outer row."),
        ("INTERMEDIATE", "A UNION combines the employees of department 1 (3 people) with the employees of department 2 (2 people), and no person belongs to both. How many rows does the UNION return?",
         ["2", "6", "5", "3"], "C",
         "Since the two sets do not overlap, UNION keeps all 3 plus all 2 rows for a total of 5."),
        ("INTERMEDIATE", "What is a key difference between UNION ALL and UNION?",
         ["UNION ALL sorts the rows, UNION does not",
          "UNION ALL keeps duplicate rows, UNION removes them",
          "UNION ALL only works on numeric columns",
          "UNION is faster than UNION ALL"], "B",
         "UNION applies a distinct pass to remove duplicates, while UNION ALL returns every row as produced by the queries."),
        ("INTERMEDIATE", "Which query finds the departments that have at least one employee using EXISTS?",
         ["SELECT id FROM departments WHERE id IN (SELECT id FROM departments);",
          "SELECT id FROM departments WHERE EXISTS (SELECT 1 FROM employees);",
          "SELECT DISTINCT d.id FROM departments d, employees e;",
          "SELECT id FROM departments d WHERE EXISTS (SELECT 1 FROM employees e WHERE e.dept_id = d.id);"], "D",
         "The correlated EXISTS checks each department for at least one employee with that dept_id, returning only populated departments."),
        ("INTERMEDIATE", "The employees table has dept_id values (1, 2, 3) and the departments table has ids (1, 2, 4). Which dept_id value appears in employees but is not a department id?",
         ["3", "1", "2", "4"], "A",
         "The value 3 exists in employees but is absent from the departments ids, so it is the difference of the two sets."),
        ("INTERMEDIATE", "Which query finds employees who have the same salary as at least one other employee?",
         ["SELECT * FROM employees WHERE salary = salary;",
          "SELECT * FROM employees e1 WHERE salary > (SELECT MAX(salary) FROM employees e2 WHERE e1.id = e2.id);",
          "SELECT * FROM employees e1 WHERE EXISTS (SELECT 1 FROM employees e2 WHERE e1.salary = e2.salary AND e1.id != e2.id);",
          "SELECT * FROM employees WHERE salary IN (SELECT dept_id FROM departments);"], "C",
         "The correlated EXISTS finds another employee with the same salary but a different id, so only duplicated salaries qualify."),
        ("ADVANCED", "Which query lists employees who earn more than their own department's average salary?",
         ["SELECT * FROM employees WHERE salary > (SELECT AVG(salary) FROM employees);",
          "SELECT * FROM employees e WHERE salary > (SELECT AVG(salary) FROM employees WHERE dept_id = e.dept_id);",
          "SELECT * FROM employees WHERE salary > AVG(salary) OVER ();",
          "SELECT * FROM employees WHERE salary > ALL (SELECT salary FROM employees);"], "B",
         "The correlated subquery computes the average per the outer row's dept_id, so each employee is compared to their own department average."),
        ("ADVANCED", "employees: (1,'Ann',4000,d1),(2,'Bob',8000,d1),(3,'Cid',9000,d2),(4,'Dee',9500,d2). How many employees earn more than their department average in a correlated subquery comparison?",
         ["3", "1", "2", "0"], "C",
         "Department d1 averages 6000 and Bob qualifies, while d2 averages 9250 and Dee qualifies, so exactly 2 employees qualify."),
        ("ADVANCED", "Which statement is TRUE about using NOT IN with a subquery that returns NULL values?",
         ["NOT IN ignores NULL values entirely",
          "NOT IN is always faster than NOT EXISTS",
          "NULL values make NOT IN return all rows",
          "If the subquery result contains any NULL, NOT IN may return zero rows"], "D",
         "Because NULL compares to UNKNOWN, NOT IN can produce no rows at all when the subquery contains any NULL, which is why NOT EXISTS is safer."),
        ("ADVANCED", "Which query uses a subquery in the FROM clause (derived table) to show departments with more than 2 employees?",
         ["SELECT dept_id, cnt FROM (SELECT dept_id, COUNT(*) AS cnt FROM employees GROUP BY dept_id) AS t WHERE cnt > 2;",
          "SELECT dept_id, COUNT(*) FROM employees WHERE COUNT(*) > 2 GROUP BY dept_id;",
          "SELECT dept_id FROM employees WHERE dept_id IN (SELECT 1);",
          "SELECT dept_id, COUNT(*) FROM employees HAVING cnt > 2;"], "A",
         "The derived table aggregates the counts, and the outer query filters on the cnt column to keep only groups above 2."),
        ("ADVANCED", "Which is a valid way to rank each employee's salary within their own department using a correlated subquery?",
         ["SELECT name, COUNT(*) FROM employees;",
          "SELECT e1.name, (SELECT COUNT(*) + 1 FROM employees e2 WHERE e2.dept_id = e1.dept_id AND e2.salary > e1.salary) AS rnk FROM employees e1;",
          "SELECT name, RANK() FROM employees;",
          "SELECT name, salary FROM employees WHERE salary > ALL (SELECT salary);"], "B",
         "The correlated subquery counts how many colleagues in the same department earn more, and adding 1 produces a rank."),
        ("ADVANCED", "INTERSECT returns which rows from two queries A and B?",
         ["Rows in A but not B",
          "All rows of A and B combined",
          "Rows that appear in both A and B",
          "Rows in B but not A"], "C",
         "INTERSECT keeps only the rows that exist in both result sets of A and B."),
        ("ADVANCED", "Set operations like UNION require what about the two queries involved?",
         ["The same table name",
          "Identical column names",
          "At least one common key",
          "The same number of columns with compatible data types"], "D",
         "Set operations line up columns positionally, so both queries must return the same number of columns with compatible types."),
        ("ADVANCED", "Which query finds the employees in the Sales department who are NOT in the IT department using set operators on the employees table?",
         ["SELECT id FROM employees WHERE dept_id IN (SELECT id FROM departments WHERE name = 'Sales') EXCEPT SELECT id FROM employees WHERE dept_id IN (SELECT id FROM departments WHERE name = 'IT');",
          "SELECT id FROM employees WHERE dept_id IN ('Sales') UNION SELECT id FROM employees;",
          "SELECT id FROM employees WHERE name = 'Sales' INTERSECT SELECT id FROM employees WHERE name = 'IT';",
          "SELECT id FROM employees WHERE dept_id NOT IN (SELECT id FROM departments);"], "A",
         "EXCEPT removes the IT employees from the Sales set, leaving exactly the employees in Sales but not in IT."),
        ("ADVANCED", "Which statement is TRUE about how a correlated subquery is executed?",
         ["It is evaluated once total",
          "It is evaluated once for each row processed by the outer query",
          "It can only be used in the SELECT list",
          "It is always slower than a join"], "B",
         "Because a correlated subquery depends on the current outer row, the database evaluates it once for each outer row."),
        ("ADVANCED", "Query A returns employee ids (1, 2) and query B returns employee ids (2, 3). How many rows does INTERSECT return?",
         ["3", "2", "0", "1"], "D",
         "Only id 2 appears in both result sets, so INTERSECT returns exactly 1 row."),
    ],
    35: [
        ("BEGINNER", "Which aggregate function counts the number of rows in a result set?",
         ["COUNT", "SUM", "AVG", "MAX"], "A",
         "COUNT returns the number of rows that satisfy the query, which is what counting requires."),
        ("BEGINNER", "Which aggregate function returns the average value of a numeric column?",
         ["SUM", "AVG", "MIN", "MEDIAN"], "B",
         "AVG computes the arithmetic mean of the numeric values in a column."),
        ("BEGINNER", "Which aggregate function returns the largest value in a column?",
         ["MIN", "COUNT", "MAX", "TOTAL"], "C",
         "MAX returns the largest value found in the column being aggregated."),
        ("BEGINNER", "Which clause groups rows that share the same column values into summary rows?",
         ["ORDER BY", "WHERE", "HAVING", "GROUP BY"], "D",
         "GROUP BY collects rows with equal values in the listed columns so aggregates can be computed per group."),
        ("BEGINNER", "Which aggregate function adds up all the values in a numeric column?",
         ["SUM", "AVG", "COUNT", "MAX"], "A",
         "SUM totals the numeric values of the column across the grouped rows."),
        ("BEGINNER", "Which clause is used to filter groups after aggregation has taken place?",
         ["WHERE", "HAVING", "GROUP BY", "ORDER BY"], "B",
         "HAVING filters grouped results based on aggregate values, unlike WHERE which filters individual rows."),
        ("BEGINNER", "Which aggregate function returns the smallest value in a column?",
         ["MAX", "AVG", "MIN", "COUNT"], "C",
         "MIN returns the smallest value found in the column being aggregated."),
        ("BEGINNER", "What does COUNT(*) count?",
         ["Only rows with no NULLs",
          "Only distinct values",
          "Non-null columns only",
          "Every row including rows with NULLs"], "D",
         "COUNT(*) counts every row regardless of NULL values in any particular column."),
        ("BEGINNER", "Which aggregate functions typically IGNORE NULL values in their calculations?",
         ["SUM and AVG", "COUNT(*)", "MAX and MIN always ignore NULLs", "None of the aggregate functions"], "A",
         "SUM and AVG skip NULL entries during computation, while COUNT(*) includes all rows."),
        ("BEGINNER", "Which query counts the total number of employees in the employees table?",
         ["SELECT COUNT(name) FROM employees WHERE name = 'Ann';",
          "SELECT COUNT(*) FROM employees;",
          "SELECT COUNT FROM employees;",
          "SELECT * FROM employees GROUP BY COUNT;"], "B",
         "COUNT(*) counts all rows in the employees table, giving the total number of employees."),
        ("INTERMEDIATE", "Which query counts how many employees are in each department?",
         ["SELECT dept_id, COUNT(*) FROM employees;",
          "SELECT dept_id FROM employees HAVING COUNT(*);",
          "SELECT dept_id, COUNT(*) FROM employees GROUP BY dept_id;",
          "SELECT dept_id, COUNT(*) FROM employees WHERE COUNT(*) > 1;"], "C",
         "GROUP BY dept_id creates one group per department, and COUNT(*) tallies the employees in each group."),
        ("INTERMEDIATE", "Which statement correctly describes WHERE versus HAVING?",
         ["WHERE filters rows before grouping; HAVING filters groups after aggregation",
          "HAVING filters rows before grouping takes place",
          "They are interchangeable in every query",
          "WHERE cannot be used together with GROUP BY"], "A",
         "WHERE removes individual rows first, while HAVING removes entire groups after the aggregates are computed."),
        ("INTERMEDIATE", "Which query finds the average salary in each department?",
         ["SELECT dept_id, salary FROM employees GROUP BY salary;",
          "SELECT dept_id, AVG(salary) FROM employees GROUP BY dept_id;",
          "SELECT AVG(dept_id) FROM employees GROUP BY salary;",
          "SELECT dept_id, AVG(salary) FROM employees;"], "B",
         "GROUP BY dept_id groups employees by department and AVG(salary) computes each group's average salary."),
        ("INTERMEDIATE", "Which query returns only the departments that have more than 5 employees?",
         ["SELECT dept_id FROM employees WHERE COUNT(*) > 5 GROUP BY dept_id;",
          "SELECT dept_id, COUNT(*) FROM employees WHERE COUNT(*) > 5;",
          "SELECT dept_id, COUNT(*) FROM employees GROUP BY dept_id WHERE COUNT(*) > 5;",
          "SELECT dept_id, COUNT(*) FROM employees GROUP BY dept_id HAVING COUNT(*) > 5;"], "D",
         "HAVING COUNT(*) > 5 filters the grouped departments, keeping only groups with more than 5 employees."),
        ("INTERMEDIATE", "Which query sums the salaries of all employees?",
         ["SELECT SUM(salary) FROM employees;",
          "SELECT salary FROM employees SUM;",
          "SELECT SUM(salary) FROM employees GROUP BY name;",
          "SELECT COUNT(salary) FROM employees;"], "A",
         "SUM(salary) adds up the salary column across all rows in the employees table."),
        ("INTERMEDIATE", "Which query finds the highest salary in each department?",
         ["SELECT dept_id, salary FROM employees GROUP BY dept_id, salary;",
          "SELECT dept_id, MAX(salary) FROM employees WHERE MAX(salary) GROUP BY dept_id;",
          "SELECT dept_id, MAX(salary) FROM employees GROUP BY dept_id;",
          "SELECT dept_id, salary FROM employees ORDER BY salary DESC;"], "C",
         "GROUP BY dept_id creates per-department groups and MAX(salary) returns the top salary of each group."),
        ("INTERMEDIATE", "Which query counts the number of distinct departments that appear in the employees table?",
         ["SELECT COUNT(dept_id) FROM employees;",
          "SELECT COUNT(DISTINCT dept_id) FROM employees;",
          "SELECT DISTINCT COUNT(dept_id) FROM employees;",
          "SELECT COUNT(*) FROM departments;"], "B",
         "COUNT(DISTINCT dept_id) counts each department id only once, giving the number of unique departments."),
        ("INTERMEDIATE", "GROUP BY dept_id, grade produces summary rows for what combination?",
         ["Each distinct dept_id only",
          "Each distinct grade only",
          "One row per employee",
          "Each distinct combination of dept_id and grade"], "D",
         "Grouping by two columns forms one group for every distinct pair of dept_id and grade values."),
        ("INTERMEDIATE", "Which query returns departments sorted by the number of employees from most to least?",
         ["SELECT dept_id, COUNT(*) AS c FROM employees GROUP BY dept_id ORDER BY c DESC;",
          "SELECT dept_id, COUNT(*) FROM employees ORDER BY COUNT(*) DESC GROUP BY dept_id;",
          "SELECT dept_id, COUNT(*) AS c FROM employees GROUP BY dept_id ORDER BY COUNT;",
          "SELECT dept_id FROM employees ORDER BY COUNT(*) DESC;"], "A",
         "The COUNT(*) alias c is sorted with ORDER BY c DESC, listing the largest groups first."),
        ("INTERMEDIATE", "Which query finds the average salary of the employees in department 2?",
         ["SELECT AVG(salary) FROM employees GROUP BY dept_id;",
          "SELECT dept_id, AVG(salary) FROM employees HAVING dept_id = 2;",
          "SELECT AVG(salary) FROM employees WHERE dept_id = 2;",
          "SELECT AVG(dept_id) FROM employees WHERE salary = 2;"], "C",
         "WHERE dept_id = 2 restricts the rows before the aggregation, so AVG(salary) covers only department 2."),
        ("ADVANCED", "Given employees: (1,'Ann',5000,d1),(2,'Bob',6000,d1),(3,'Cid',7000,d2). What does ROW_NUMBER() OVER (ORDER BY salary DESC) assign to the three rows?",
         ["The same number to all rows",
          "1, 2, 3 based on the ordered position",
          "The average of the salaries",
          "NULL for the top row"], "B",
         "ROW_NUMBER assigns sequential integers 1, 2, 3 according to the order established by ORDER BY salary DESC."),
        ("ADVANCED", "What is the difference between RANK() and DENSE_RANK() when ties occur?",
         ["RANK never produces ties",
          "DENSE_RANK leaves gaps after ties",
          "RANK leaves gaps after ties; DENSE_RANK does not",
          "They are identical functions"], "C",
         "RANK skips the next numbers after a tie, while DENSE_RANK assigns consecutive numbers without gaps."),
        ("ADVANCED", "Which query computes a running total of salary ordered by id?",
         ["SELECT id, salary, SUM(salary) AS rt FROM employees ORDER BY id;",
          "SELECT id, salary, SUM(salary) OVER (PARTITION BY id) FROM employees;",
          "SELECT id, salary, SUM(salary) FROM employees GROUP BY id;",
          "SELECT id, salary, SUM(salary) OVER (ORDER BY id) AS running_total FROM employees;"], "D",
         "The window function SUM(salary) OVER (ORDER BY id) cumulatively adds each row's salary in id order."),
        ("ADVANCED", "employees: (1,'Ann',5000,d1),(2,'Bob',6000,d1),(3,'Cid',7000,d2),(4,'Dee',8000,d2). What value does SUM(salary) OVER (PARTITION BY dept_id) return for row 1?",
         ["11000", "15000", "5000", "26000"], "A",
         "The partition for d1 contains Ann and Bob with salaries 5000 and 6000, whose sum is 11000."),
        ("ADVANCED", "What is the key difference between an aggregate function and a window function?",
         ["Window functions collapse many rows into one",
          "Aggregates collapse rows into one; window functions compute a value per row without collapsing",
          "They are identical in behaviour",
          "Aggregates cannot be used with GROUP BY"], "B",
         "An aggregate like SUM reduces the group to one row, while a window function computes a value for each row while keeping all rows."),
        ("ADVANCED", "Which query returns the top 2 salaries in each department using ROW_NUMBER?",
         ["SELECT * FROM employees WHERE ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) <= 2;",
          "SELECT TOP 2 FROM employees GROUP BY dept_id;",
          "SELECT * FROM (SELECT e.*, ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rn FROM employees e) t WHERE rn <= 2;",
          "SELECT * FROM employees ORDER BY salary DESC LIMIT 2;"], "C",
         "The window function must be computed in a subquery because window functions cannot be referenced directly in WHERE."),
        ("ADVANCED", "Which query returns the departments whose total salary exceeds 100000?",
         ["SELECT dept_id FROM employees WHERE SUM(salary) > 100000 GROUP BY dept_id;",
          "SELECT dept_id, SUM(salary) FROM employees WHERE SUM(salary) > 100000;",
          "SELECT dept_id FROM employees GROUP BY dept_id WHERE SUM(salary) > 100000;",
          "SELECT dept_id, SUM(salary) FROM employees GROUP BY dept_id HAVING SUM(salary) > 100000;"], "D",
         "HAVING SUM(salary) > 100000 filters the grouped departments based on the computed total salary."),
        ("ADVANCED", "What does GROUP BY dept_id WITH ROLLUP add to the result set?",
         ["A grand-total row for the whole group",
          "A row for every single employee",
          "It deletes all NULL rows",
          "It has no effect on the result"], "A",
         "WITH ROLLUP appends extra summary rows, including a grand-total row that aggregates across all groups."),
        ("ADVANCED", "Which query computes a three-row moving average of salary ordered by id?",
         ["SELECT id, AVG(salary) OVER (ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) FROM employees;",
          "SELECT id, AVG(salary) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS mov_avg FROM employees;",
          "SELECT id, AVG(salary) FROM employees GROUP BY id;",
          "SELECT id, SUM(salary) OVER () FROM employees;"], "B",
         "The frame from 1 PRECEDING to 1 FOLLOWING includes the current row plus one before and one after, averaging three rows."),
        ("ADVANCED", "Why must a window function in the SELECT list be placed inside a subquery if you want to filter on its result?",
         ["Window functions cannot be computed at all",
          "Subqueries are always required for aggregation",
          "GROUP BY must always be used first",
          "Window functions are evaluated after WHERE, so you cannot reference them directly in WHERE"], "D",
         "Since window functions are computed after WHERE filtering, their results can only be used in outer filters, requiring a subquery."),
    ],
}
