# -*- coding: utf-8 -*-
"""
Question bank for subject 58: CLD108 - Cloud Security & Governance.
Category: Cloud, Cybersecurity & DevOps.
Semester: 8.

Topics:
  286: Shared Responsibility Model
  287: Identity & Access Management
  288: Compliance & Auditing
  289: Zero Trust & Network Security
  290: Cloud Incident & Forensics

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    286: [
        ("BEGINNER", "In cloud computing, what does the shared responsibility model describe?",
         ["How security duties are divided between the provider and the customer", "How to share a single server", "How cloud bills are split", "How office space is divided"], "A",
         "The shared responsibility model clarifies which security controls the provider owns and which the customer owns."),
        ("BEGINNER", "In IaaS, which security aspect is typically the customer's responsibility?",
         ["Securing the operating system and applications they run", "Securing the physical data center", "Cooling the servers", "Repairing the network cables"], "B",
         "Under IaaS the provider secures the physical layer while the customer secures the OS, apps and data."),
        ("BEGINNER", "In SaaS, which layer is usually the provider's responsibility?",
         ["The customer's office network", "The application, runtime and underlying infrastructure", "The customer's laptops", "The customer's user accounts"], "B",
         "With SaaS, the provider manages the application and stack while the customer manages usage and data access."),
        ("BEGINNER", "Which of the following is generally the CUSTOMER's responsibility in all cloud models?",
         ["Patching the provider's servers", "Securing the cloud region building", "Managing their own data and user access", "Maintaining the hypervisor"], "C",
         "Customers are always responsible for their data, identities and access configurations."),
        ("BEGINNER", "Which layer is almost always the cloud PROVIDER's responsibility?",
         ["The customer's application code", "The customer's firewall rules", "The customer's encryption keys", "Physical infrastructure such as servers and data centers"], "D",
         "The provider owns the physical data center, hardware and global network."),
        ("BEGINNER", "In PaaS, which component does the customer typically manage?",
         ["The physical racks", "The electricity supply", "The application code and its configuration", "The cooling systems"], "C",
         "With PaaS the provider manages the runtime and platform while the customer manages the application and data."),
        ("BEGINNER", "What is the main reason the shared responsibility model matters to security teams?",
         ["It removes ambiguity about who must fix or configure which controls", "It reduces all cloud costs", "It deletes the firewall", "It removes the need for passwords"], "A",
         "Clear division of duties prevents security controls from being assumed covered by the other party."),
        ("BEGINNER", "Which of the following is the customer responsible for when using a managed database service?",
         ["Patching the database engine automatically", "Access control over who can read the data in the database", "Hardware redundancy", "The data center cooling"], "B",
         "Even with a managed DB, the customer controls access and permissions over their data."),
        ("BEGINNER", "What is the 'security of the cloud' versus 'security in the cloud' distinction?",
         ["Provider-managed protection versus customer-managed protection of their workloads", "Free versus paid security", "Hardware versus software only", "Internal versus external networks"], "A",
         "Security of the cloud is the provider's protection of infrastructure; security in the cloud is the customer's responsibility for workloads."),
        ("BEGINNER", "Which cloud deployment model gives the customer the most control over security configuration?",
         ["A fully managed SaaS app", "A serverless function", "A managed email service", "IaaS on dedicated or private infrastructure"], "D",
         "IaaS exposes compute and network layers that the customer configures directly, offering the most control."),
        ("INTERMEDIATE", "A customer deploys a VM in IaaS and leaves the default admin password unchanged. Whose responsibility is the resulting breach?",
         ["The provider, because they built the VM", "The customer, because securing the OS and accounts is their duty under IaaS", "The network vendor", "No one"], "B",
         "Under IaaS the customer owns OS and account security, so weak credentials are the customer's failure."),
        ("INTERMEDIATE", "Which scenario is an example of a provider-side responsibility failure?",
         ["A customer misconfigured storage bucket", "A customer shares a password", "A provider's hypervisor vulnerability that lets tenants escape their VM boundaries", "A customer opens a firewall port"], "C",
         "Hypervisor isolation is provider-owned, so a tenant-escape flaw is the provider's responsibility."),
        ("INTERMEDIATE", "A customer uses a managed Kubernetes service. Which task remains the customer's?",
         ["Patching the control-plane nodes", "Securing the workloads, namespaces and RBAC policies they define", "Repairing the cluster's physical hosts", "Managing the hypervisor"], "B",
         "Managed Kubernetes handles the control plane while customers secure their workloads, namespaces and access policies."),
        ("INTERMEDIATE", "Which statement correctly maps responsibility for encryption?",
         ["The provider offers encryption options, but enabling and managing keys is largely the customer's duty", "The provider automatically encrypts and owns all keys", "Encryption is optional everywhere", "Customers cannot encrypt in the cloud"], "A",
         "Providers supply encryption features, but customers must enable them and manage their keys and scope."),
        ("INTERMEDIATE", "A customer finds a public storage bucket holding sensitive files. Which best explains the root cause?",
         ["A provider data-center outage", "A provider network upgrade", "A hypervisor patch", "A misconfiguration on the customer's side of the shared responsibility boundary"], "D",
         "Access-control misconfiguration of customer-owned resources is a customer-side responsibility failure."),
        ("INTERMEDIATE", "Which responsibility is shared between provider and customer in most cloud models?",
         ["The physical building security", "The electricity grid", "Network and access-layer controls such as firewall and identity configuration", "The storage media destruction"], "C",
         "Network and identity controls sit at the boundary and are jointly managed by both parties."),
        ("INTERMEDIATE", "Which of the following should a customer do to meet its part of the model for a serverless app?",
         ["Patch the serverless runtime", "Harden the function code and validate its inputs", "Replace the function's physical host", "Cool the server room"], "B",
         "With serverless, the provider runs the platform but the customer must secure code, inputs and dependencies."),
        ("INTERMEDIATE", "When a customer builds a VPC, which aspect is within the provider's responsibility?",
         ["The subnets and routing tables", "The security groups", "The VPC peering decisions", "The underlying physical network infrastructure"], "D",
         "The provider owns physical networking; logical constructs like subnets and security groups are customer-managed."),
        ("INTERMEDIATE", "Which practice best demonstrates a customer understanding the shared model?",
         ["Assuming the provider secures everything", "Mapping each control to the responsible party in a responsibility matrix", "Disabling all provider security features", "Ignoring the model entirely"], "B",
         "A documented responsibility matrix makes coverage explicit and auditable."),
        ("INTERMEDIATE", "In a hybrid cloud, which layer is unambiguously the customer's responsibility on-premises?",
         ["The cloud region's cooling", "The provider's global backbone", "The cloud console", "The on-premises physical and application layers"], "D",
         "The customer owns everything in its own data center, while the cloud parts follow provider boundaries."),
        ("ADVANCED", "Which configuration error most commonly causes customer-side cloud breaches?",
         ["The provider patching servers", "Overly permissive storage or identity policies left public by default", "The provider upgrading DNS", "The customer buying more RAM"], "B",
         "Excessive permissions and public exposure of customer-managed resources are the leading causes of cloud breaches."),
        ("ADVANCED", "Which audit finding would correctly be blamed on the PROVIDER under the shared model?",
         ["A customer's open database port", "A customer's lost key", "A documented failure of the provider's stated multi-tenant isolation guarantee", "A customer's outdated SDK"], "C",
         "Provider failures occur where the provider owns the control, such as multi-tenant isolation guarantees."),
        ("ADVANCED", "A compliance team must prove the customer fulfilled its side of the model. Which evidence is most relevant?",
         ["The provider's marketing pages", "Configuration baselines, access reviews and patching records for customer-managed resources", "The provider's facility photos", "The provider's stock price"], "B",
         "Evidence of customer-managed controls proves compliance where the customer owns the duty."),
        ("ADVANCED", "Which strategy best reduces risk in the 'shared' boundary of network controls?",
         ["Relying only on the provider's default firewall", "Disabling all network controls", "Using flat unsegmented networks", "Defense-in-depth combining provider-native controls with customer-defined network policies"], "D",
         "Layered controls at the shared network boundary cover gaps each party might otherwise leave open."),
        ("ADVANCED", "A customer stores encryption keys in the provider's KMS. How does the model apply if the provider is breached?",
         ["The customer is always fully to blame", "If the provider's KMS was the agreed control, the provider bears the failure, but the customer still chose that control", "The provider is never involved", "Keys are irrelevant"], "B",
         "Using a provider-managed key service shifts key custody to the provider while the customer remains responsible for choosing the right control."),
        ("ADVANCED", "Which approach most effectively closes responsibility gaps in a large multi-cloud estate?",
         ["Different teams inventing rules per cloud", "No documentation", "A cloud security governance team with a unified control framework across all providers", "Relying on a single vendor"], "C",
         "A central governance team with one framework prevents each cloud from having different, overlapping or missing controls."),
        ("ADVANCED", "Why is it dangerous to assume the provider's default security settings are sufficient?",
         ["Defaults are always perfect", "Providers never change defaults", "Customers have no settings", "Defaults prioritise availability and usability, not the customer's specific risk posture"], "D",
         "Default settings are generic; customers must align them with their own threat model and compliance needs."),
        ("ADVANCED", "Which statement about customer data in the shared model is correct?",
         ["The provider owns customer data", "Data is exempt from the model", "The customer retains responsibility for their data regardless of provider infrastructure duties", "Only the provider can delete data"], "C",
         "Data ownership and protection duties always stay with the customer under every cloud model."),
        ("ADVANCED", "A regulated customer runs workloads on shared public cloud infrastructure. Which control is most important to demonstrate?",
         ["A bigger monitor", "Faster internet", "More users", "Strong tenant isolation, encryption and compliance evidence at both responsibility layers"], "D",
         "Regulated customers must prove isolation and protection across both provider and customer-controlled layers."),
        ("ADVANCED", "Which governance practice most improves accountability under the shared responsibility model?",
         ["Assigning no owners", "Verbal handovers", "Deleting control documents", "Documenting RACI-style ownership of every security control and reviewing it regularly"], "D",
         "Explicit control ownership with regular reviews ensures every duty has an accountable party."),
    ],
    287: [
        ("BEGINNER", "What does IAM stand for in cloud security?",
         ["Internet and Application Model", "Identity and Access Management", "Integrated Account Maintenance", "Infrastructure Automation Module"], "B",
         "IAM governs digital identities and the access they are granted to resources."),
        ("BEGINNER", "Which cloud IAM component defines what actions an identity may perform on which resources?",
         ["A policy", "A password reset", "A reboot", "A backup"], "A",
         "IAM policies grant permissions, specifying allowed actions on specific resources."),
        ("BEGINNER", "What does MFA add to a login?",
         ["A faster connection", "More disk space", "An extra verification factor beyond the password", "A new colour theme"], "C",
         "Multi-factor authentication requires two or more independent credentials to verify identity."),
        ("BEGINNER", "Which principle states users should get only the minimum permissions they need?",
         ["Principle of least privilege", "Principle of maximum access", "Principle of open doors", "Principle of shared accounts"], "A",
         "Least privilege grants the minimal permissions required for a role to function."),
        ("BEGINNER", "What is a role in RBAC?",
         ["A physical badge", "A named collection of permissions assignable to users", "A password", "A firewall rule"], "B",
         "Roles bundle permissions so they can be assigned consistently to users or groups."),
        ("BEGINNER", "Which mechanism lets a user sign in once and access multiple services?",
         ["Single sign-on (SSO)", "Rebooting twice", "Multiple passwords", "Guest accounts"], "A",
         "SSO authenticates the user once and shares the session with connected services."),
        ("BEGINNER", "What does a service principal or service account represent?",
         ["An identity used by an application rather than a human", "A human employee", "A conference room", "A network cable"], "A",
         "Service principals give applications their own identity and permissions in the cloud."),
        ("BEGINNER", "Which of the following is an example of an authentication factor?",
         ["Something you know such as a password", "The office address", "The company name", "The building floor"], "A",
         "Knowledge factors such as passwords are one class of authentication credential."),
        ("BEGINNER", "What is federation in identity management?",
         ["Trusting identities issued by another organisation's identity provider", "Combining two databases", "Joining two cables", "Merging two VMs"], "A",
         "Federation lets organisations accept identities authenticated by trusted external providers."),
        ("BEGINNER", "Which IAM action grants a user access to a specific cloud resource?",
         ["Deleting the resource", "Attaching a policy that allows the needed action", "Restarting the resource", "Renaming the resource"], "B",
         "Policies define the allowed actions, so attaching the right policy grants access."),
        ("INTERMEDIATE", "A developer needs read access to one bucket but is granted admin to the whole account. Which IAM principle is violated?",
         ["The principle of least privilege", "The principle of high availability", "The principle of portability", "The principle of elasticity"], "A",
         "Granting far more access than needed violates least privilege and expands the blast radius."),
        ("INTERMEDIATE", "Which scenario is the strongest argument for enforcing MFA?",
         ["A single compromised password then gives full access to the account", "MFA slows the login slightly", "MFA costs extra disk", "MFA changes the UI"], "A",
         "MFA blocks attackers who obtain only one credential, so a stolen password alone is insufficient."),
        ("INTERMEDIATE", "A contractor leaves the company. Which IAM task is most urgent?",
         ["Updating their profile photo", "Revoking their credentials and removing their access", "Renaming their account", "Copying their files"], "B",
         "Revoking access immediately prevents a departed user from still reaching resources."),
        ("INTERMEDIATE", "Which identity setup best lets employees use their corporate account to log into cloud apps?",
         ["Separate passwords for every app", "A shared guest password", "SSO with a federated identity provider", "Posting credentials on the wall"], "C",
         "Federated SSO reuses the corporate identity, simplifying login and centralising control."),
        ("INTERMEDIATE", "Which practice prevents a single leaked key from exposing an entire application?",
         ["Giving every component its own narrowly scoped service principal", "Sharing one admin key across all services", "Storing keys in the repository", "Disabling logging"], "A",
         "Narrowly scoped, per-service identities limit what a leaked credential can access."),
        ("INTERMEDIATE", "A user is in two groups with conflicting policies, one allowing and one denying an action. What happens in most cloud IAM systems?",
         ["The deny overrides the allow", "The allow overrides the deny", "The action is randomly chosen", "The account is locked"], "A",
         "Explicit denies take precedence over allows in most cloud IAM evaluation models."),
        ("INTERMEDIATE", "Which of the following best protects service account credentials at runtime?",
         ["Hard-coding them in source", "Storing them in a managed secrets service and rotating them", "Emailing them to the team", "Putting them in public docs"], "B",
         "Managed secret stores plus rotation reduce the risk that long-lived static keys leak."),
        ("INTERMEDIATE", "Why are access reviews important for a growing organisation?",
         ["Permissions accumulate over time and stale access becomes a risk", "Reviews slow everyone down", "Reviews change the UI", "Reviews increase costs only"], "A",
         "Regular access reviews prune stale or excessive permissions that accumulate as people change roles."),
        ("INTERMEDIATE", "Which condition-based policy example is a common cloud IAM control?",
         ["Allowing access only from a corporate IP range", "Allowing access from anywhere", "Allowing access only after 2 AM", "Allowing all users"], "A",
         "Conditional policies can restrict access by network, time or device context."),
        ("INTERMEDIATE", "What is the main risk of a root or admin account being used for daily work?",
         ["It cannot be revoked for that user", "Every action it takes has maximum privilege and impact", "It is slow", "It is read-only"], "B",
         "Using a full-privilege account for routine work means any compromise yields total control."),
        ("ADVANCED", "Which control most directly limits the damage of a stolen short-term credential?",
         ["Short credential lifetime plus continuous re-authentication and anomaly detection", "Never rotating keys", "Long-lived static passwords", "Ignoring session activity"], "A",
         "Short-lived credentials shrink the window in which a stolen token is usable."),
        ("ADVANCED", "An organisation must give a partner team temporary access to one project. Which IAM pattern fits best?",
         ["A scoped role with a time-bound trust relationship and audit trail", "Adding them to the root group", "Sharing the admin password", "Giving them a permanent admin key"], "A",
         "Time-bound, scoped, auditable access grants the partner exactly what is needed without permanent exposure."),
        ("ADVANCED", "Which design best reduces the impact of an over-privileged service account in a microservice mesh?",
         ["Each service using its own identity with mesh-native policy enforcement", "All services sharing one account", "Root access for every pod", "No authentication between services"], "A",
         "Per-service identities with granular policy enforcement contain any single compromised service."),
        ("ADVANCED", "Why is just-in-time (JIT) access useful for highly privileged roles?",
         ["It grants elevated privileges only when needed and for a limited window", "It grants permanent admin to everyone", "It removes all authentication", "It disables all audits"], "A",
         "JIT elevation reduces the standing privilege that attackers could otherwise exploit."),
        ("ADVANCED", "Which measure best detects a credential being used from an unexpected location?",
         ["Anomaly detection and conditional access that challenge unusual sign-ins", "Ignoring geography", "Accepting all logins", "Disabling alerts"], "A",
         "Risk-based conditional access flags and blocks sign-ins that deviate from normal behaviour."),
        ("ADVANCED", "A security review finds hundreds of unused users with admin rights. Which remediation is most appropriate?",
         ["A phased deprovisioning that disables stale admin accounts and documents the review", "Leaving them as they are", "Granting everyone more rights", "Deleting all users"], "A",
         "Phased, documented deprovisioning removes risky accounts without breaking legitimate workflows."),
        ("ADVANCED", "Which IAM architecture best supports an organisation using multiple cloud providers?",
         ["A central identity provider federated into each cloud", "Separate password books per cloud", "One root account per cloud shared by all", "No central directory"], "A",
         "A federated central identity provider gives consistent control across all clouds."),
        ("ADVANCED", "Which practice is most effective against credential-stuffing attacks?",
         ["MFA combined with breach-password screening and rate limiting", "Longer usernames", "More screen readers", "Disabled password policies"], "A",
         "MFA, screening against known-breached passwords and rate limiting defeat reused-credential attacks."),
        ("ADVANCED", "What does an identity 'blast radius' analysis help an organisation decide?",
         ["How much damage each identity could cause if compromised, guiding least privilege", "Which colour scheme to use", "How many meetings to schedule", "Which region to pick for latency"], "A",
         "Blast radius analysis quantifies compromise impact so permissions can be trimmed accordingly."),
        ("ADVANCED", "Which audit evidence best demonstrates proper IAM governance?",
         ["Current access reviews, policy change logs and approved role assignments", "A list of passwords", "Screenshots of dashboards", "The number of logins per day"], "A",
         "Documented reviews and change logs prove access was governed, not merely granted."),
    ],
    288: [
        ("BEGINNER", "What is compliance in a cloud context?",
         ["Following laws, regulations and standards that apply to your data and workloads", "Compiling code faster", "Reducing storage cost", "Choosing a cloud region"], "A",
         "Compliance means meeting the legal and regulatory requirements applicable to the organisation."),
        ("BEGINNER", "Which of the following is a widely used information security management standard?",
         ["A cooking recipe", "A bus timetable", "ISO/IEC 27001", "A football league table"], "C",
         "ISO/IEC 27001 specifies requirements for an information security management system."),
        ("BEGINNER", "What is an audit trail?",
         ["A record of who did what and when on the systems", "A list of fire extinguishers", "A backup schedule", "A network diagram"], "A",
         "Audit trails log actions and events, enabling review and accountability."),
        ("BEGINNER", "Which cloud compliance concern is most relevant for health data in the United States?",
         ["The periodic table", "A cooking standard", "A road sign", "HIPAA"], "D",
         "HIPAA governs the protection of health information in the US."),
        ("BEGINNER", "What is the purpose of a compliance report such as SOC 2?",
         ["Proof of delivery speed", "Independent verification that a provider meets security and availability criteria", "A tax receipt", "A licence to sell food"], "B",
         "SOC 2 reports independently attest to a provider's security, availability and related controls."),
        ("BEGINNER", "Which activity helps an organisation verify it actually follows its security policies?",
         ["Internal audits", "Renaming folders", "Buying more monitors", "Holding fewer meetings"], "A",
         "Audits compare actual practice against stated policies and controls."),
        ("BEGINNER", "What does a control gap mean?",
         ["A gap between two buildings", "A missing cable", "A requirement that has no compensating control in place", "A short meeting"], "C",
         "A control gap is a missing or ineffective control that leaves a requirement unmet."),
        ("BEGINNER", "Which term describes the process of proving to a third party that controls are in place?",
         ["Compilation", "Serialization", "Compression", "Attestation"], "D",
         "Attestation is an independent party's formal confirmation that controls meet criteria."),
        ("BEGINNER", "What is the main purpose of logging configuration changes in the cloud?",
         ["To slow down the system", "To fill disk space", "To detect unauthorised modifications and support investigations", "To increase costs"], "C",
         "Change logs reveal unauthorised or erroneous modifications and feed audits and forensics."),
        ("BEGINNER", "Which principle requires that duties such as approving and executing be split across people?",
         ["Load balancing", "Separation of duties", "Data sharding", "Auto scaling"], "B",
         "Separation of duties prevents one person from having unchecked power over a process."),
        ("INTERMEDIATE", "A customer using a compliant cloud provider still gets fined for a data breach. Which is the most likely reason?",
         ["The provider's certificate expired", "The customer did not implement its own compliance controls on the workloads", "The cloud was too fast", "The region was too small"], "B",
         "Provider compliance does not cover the customer's own responsibilities; fines can still result from customer-side failures."),
        ("INTERMEDIATE", "Which activity best prepares an organisation for a third-party audit?",
         ["Deleting old logs", "Denying access to auditors", "Postponing all reviews", "Gathering evidence of implemented controls ahead of the audit window"], "D",
         "Preparing control evidence in advance makes the audit smoother and more accurate."),
        ("INTERMEDIATE", "Which cloud practice supports the auditability of a compliance requirement?",
         ["Disabling all logging", "Rotating logs daily with no archive", "Centralised, immutable logging with access to the logs preserved", "Logging only in memory"], "C",
         "Immutable, centralised logs preserve evidence that auditors can rely on."),
        ("INTERMEDIATE", "A security team must prove that encryption was enabled on all storage. Which evidence is most useful?",
         ["A verbal promise", "Configuration reports and scans showing encryption flags on every resource", "A single screenshot", "The provider's homepage"], "B",
         "Automated configuration scanning yields verifiable proof across the whole estate."),
        ("INTERMEDIATE", "Which approach best detects drift from a compliant configuration baseline?",
         ["Checking once a year", "Trusting developers to follow rules", "Ignoring configuration", "Continuously scanning and alerting when resources deviate from the baseline"], "D",
         "Continuous monitoring catches drift promptly instead of discovering it at the next audit."),
        ("INTERMEDIATE", "Which of the following is an example of a compensating control?",
         ["Removing all controls", "Ignoring a missing control", "Strong MFA where the original control was physically impossible", "Hiring more accountants"], "C",
         "Compensating controls substitute an equivalent protection when a direct control cannot be implemented."),
        ("INTERMEDIATE", "Why do cloud providers share compliance reports with customers?",
         ["To advertise discounts", "So customers can reuse provider attestations for their own audits", "To replace their own controls", "To increase bandwidth"], "B",
         "Customer-side auditors can leverage provider attestations to cover the provider-owned layer."),
        ("INTERMEDIATE", "Which scenario indicates an access-control compliance failure?",
         ["An intern holding administrator rights for a year with no review", "A quarterly access review", "RBAC in place", "MFA enabled"], "A",
         "Standing, unreviewed admin access for a low-privilege role violates least-privilege expectations."),
        ("INTERMEDIATE", "What is the main value of a cloud 'security posture' score?",
         ["It measures internet speed", "It tracks uptime only", "It counts users", "It quantifies how well the cloud estate matches best-practice baselines"], "D",
         "Posture scores summarise configuration and compliance health so teams can prioritise fixes."),
        ("INTERMEDIATE", "Which step is essential when a control deficiency is found during an audit?",
         ["Wait for the next audit", "Hide the finding", "Delete the evidence", "Create a corrective action plan with owners and deadlines"], "D",
         "A tracked remediation plan closes the gap and demonstrates accountability."),
        ("ADVANCED", "Which combination best sustains compliance in a continuously changing cloud environment?",
         ["Annual manual reviews", "Written policies only", "Infrastructure-as-code baselines with automated policy enforcement and drift detection", "A single audit per year"], "C",
         "IaC and automated enforcement keep the live estate aligned with compliant baselines at all times."),
        ("ADVANCED", "An auditor requests evidence for a control that spans several teams. Which practice makes this easy?",
         ["Scattered emails", "Verbal recollections", "No documentation", "A control ownership matrix with evidence stored in one place"], "D",
         "Centralised control ownership and evidence reduces audit effort and ambiguity."),
        ("ADVANCED", "Which data would an auditor most value for proving segregation of duties?",
         ["The number of employees", "Role assignments that show no single user can both approve and execute a critical action", "The office floor plan", "The payroll size"], "B",
         "Role-assignment evidence demonstrates that conflicting duties are separated."),
        ("ADVANCED", "Why is it dangerous for a compliance team to rely solely on the provider's compliance certifications?",
         ["Certifications are always fake", "Providers never change", "Certifications cover the provider layer, not the customer's configurations and data handling", "Compliance does not matter"], "C",
         "The customer must still satisfy the portion of requirements that fall on its own side."),
        ("ADVANCED", "Which design best supports a forensic audit after an insider incident?",
         ["Mutable logs anyone can edit", "No logs at all", "Logs stored with the attacker", "Immutable audit logs with strict access controls and tamper detection"], "D",
         "Immutable, access-controlled logs preserve trustworthy evidence for investigation."),
        ("ADVANCED", "Which approach most effectively maps cloud controls to regulatory requirements?",
         ["A marketing brochure", "A generic list of buzzwords", "A control framework mapping each regulation to specific technical controls", "Word-of-mouth advice"], "C",
         "Explicit mappings let teams see exactly which control satisfies which requirement."),
        ("ADVANCED", "An auditor finds a finding from last year still open. What does this indicate about governance?",
         ["Remediation tracking and accountability are weak", "The finding was minor", "The auditor is wrong", "Nothing"], "A",
         "Unresolved audit findings signal a failure to close gaps, undermining the compliance programme."),
        ("ADVANCED", "Which evidence best demonstrates continuous compliance rather than audit-time compliance?",
         ["A single annual snapshot", "Continuous monitoring dashboards and automated policy checks with historical records", "A screenshot taken on audit day", "A promise to be compliant"], "B",
         "Continuous, automated evidence proves controls hold between audits, not just during them."),
        ("ADVANCED", "Which trade-off must a compliance team manage when enabling verbose logging?",
         ["The colour of the dashboard", "The office size", "Cost and storage growth versus the investigative value of detailed logs", "The number of coffee machines"], "C",
         "Verbose logging improves forensics but raises storage cost, so teams must balance both."),
        ("ADVANCED", "Which technology most reduces the chance that a non-compliant resource silently drifts into production?",
         ["Automated guardrails and policy-as-code that block non-compliant deploys", "Trusting developers to self-review", "A weekly email reminder", "A poster on the wall"], "A",
         "Automated guardrails reject non-compliant infrastructure before it ever reaches production."),
    ],
    289: [
        ("BEGINNER", "What is the core assumption of a zero trust security model?",
         ["That no user or device is trusted by default, even inside the network", "That everything inside the network is safe", "That passwords are enough", "That firewalls are obsolete"], "A",
         "Zero trust assumes every access request must be verified regardless of where it originates."),
        ("BEGINNER", "Which principle means granting access only after verifying identity and context?",
         ["Default-deny and verify explicitly", "Default-allow inside the LAN", "Trust by location", "Open access for staff"], "A",
         "Zero trust verifies each request explicitly instead of trusting based on network location."),
        ("BEGINNER", "What is micro-segmentation?",
         ["Splitting the network into small isolated zones with their own policies", "Making one big flat network", "Segmenting the code into functions", "Splitting storage into volumes"], "A",
         "Micro-segmentation isolates workloads into small segments so a compromise cannot spread laterally."),
        ("BEGINNER", "What does 'least privilege' mean in a zero trust context?",
         ["Giving users only the access required for their tasks", "Giving everyone admin rights", "Giving no one any access", "Giving access based on friendship"], "A",
         "Least privilege limits each identity to the minimal access necessary, shrinking attack surface."),
        ("BEGINNER", "Which of the following is a zero trust access decision factor?",
         ["Device health, user identity and context", "The colour of the office walls", "The day of the week only", "The building address"], "A",
         "Zero trust evaluates identity, device posture and context before granting access."),
        ("BEGINNER", "What is the role of a device trust score in zero trust?",
         ["It reflects how secure and compliant a device appears before granting access", "It measures screen brightness", "It ranks games", "It counts installed apps only"], "A",
         "Device posture signals such as patching and encryption feed the access decision."),
        ("BEGINNER", "Which network security device filters traffic based on rules at the network boundary?",
         ["A firewall", "A printer", "A monitor", "A router only"], "A",
         "Firewalls enforce boundary policies by filtering traffic according to defined rules."),
        ("BEGINNER", "What does lateral movement refer to in an attack?",
         ["An attacker moving across systems within the network after initial entry", "Moving data to the cloud", "Changing office desks", "Upgrading the network cables"], "A",
         "Lateral movement is how attackers extend from an initial foothold to other systems."),
        ("BEGINNER", "Which of the following is an example of a zero trust network control?",
         ["Identity-aware access policies applied per request", "Trusting all internal IP addresses", "Open VPN for everyone", "No authentication"], "A",
         "Identity-aware, per-request policy is a hallmark of zero trust enforcement."),
        ("BEGINNER", "What is the main goal of network segmentation in security?",
         ["To contain a breach to a small zone instead of the whole network", "To make the network faster", "To reduce the number of routers", "To simplify cabling"], "A",
         "Segmentation contains attackers by blocking movement between zones."),
        ("INTERMEDIATE", "A company adopts zero trust but keeps a full VPN that grants LAN-wide access. Which gap remains?",
         ["The VPN bypasses per-request verification once a user is connected", "The VPN is too slow", "The VPN changes the IP address", "The VPN is free"], "A",
         "Traditional full-tunnel VPNs hand out broad network access, contradicting zero trust's per-request model."),
        ("INTERMEDIATE", "Which scenario best illustrates a zero trust access decision?",
         ["A request is allowed only if identity, device and risk signals all pass", "Any user with a valid password is allowed from any device", "All staff are trusted inside the office", "IP-based allow rules grant access"], "A",
         "Zero trust evaluates multiple signals together instead of trusting a single factor."),
        ("INTERMEDIATE", "How does micro-segmentation help stop ransomware spread?",
         ["It blocks the lateral movement ransomware needs to reach many hosts", "It makes backups faster", "It encrypts the network", "It deletes all files"], "A",
         "By isolating segments, micro-segmentation cuts off the paths ransomware uses to propagate."),
        ("INTERMEDIATE", "Which control most directly verifies a device's security posture before access?",
         ["Endpoint compliance checks that require patching and encryption", "A longer password", "A bigger monitor", "More bandwidth"], "A",
         "Endpoint posture checks gate access to devices that fail minimum security requirements."),
        ("INTERMEDIATE", "A finance app should be reachable only by finance staff from managed laptops. Which zero trust mechanism fits?",
         ["A conditional access policy combining group membership and device compliance", "A public URL with no auth", "Opening the port to everyone", "Trusting all laptops"], "A",
         "Conditional access enforces multiple conditions, matching zero trust's verify-every-request approach."),
        ("INTERMEDIATE", "Which practice reduces the trust placed in a single compromised workstation?",
         ["Device health checks and per-device credentials that limit what a stolen laptop can do", "Giving every laptop admin rights", "Trusting the office Wi-Fi", "Disabling endpoint agents"], "B",
         "Per-device controls ensure a single compromised machine cannot roam the network freely."),
        ("INTERMEDIATE", "Why are identity-centric policies better than pure IP-based allow lists?",
         ["Identities and context are far harder to spoof than IP addresses", "IP addresses are never spoofed", "Identity policies are simpler to write", "IP lists are impossible to maintain"], "C",
         "IP addresses can be spoofed and change frequently, while identity and context are stronger signals."),
        ("INTERMEDIATE", "Which of the following best describes the 'verify explicitly' zero trust principle?",
         ["Denying access unless every required signal is positively verified", "Allowing access until something fails", "Trusting all known devices", "Checking only the password"], "B",
         "Zero trust defaults to deny and explicitly verifies signals before allowing each request."),
        ("INTERMEDIATE", "Which network architecture most reduces the risk of a compromised internal server reaching others?",
         ["Flat network with one trust zone", "Micro-segmented zones with per-zone policies", "No network at all", "One giant VLAN for everything"], "D",
         "Micro-segmentation confines compromise to the zone where it starts, blocking broader reach."),
        ("ADVANCED", "Which design best implements zero trust for a cloud application without a legacy VPN?",
         ["An identity-aware proxy that brokers every connection with granular policies", "A site-to-site VPN granting full network access", "Open security groups", "Public databases"], "C",
         "Identity-aware proxies apply per-request policy at the application layer, a modern zero trust pattern."),
        ("ADVANCED", "A legacy system cannot enforce MFA. Which compensating control best reduces its zero trust exposure?",
         ["Network isolation, strict allow lists and monitoring around that system", "Trusting it because it is old", "Giving it public access", "Disabling its logging"], "D",
         "Isolating and tightly monitoring legacy systems limits the risk their weak auth creates."),
        ("ADVANCED", "Which metric best indicates that micro-segmentation is working?",
         ["Measured reduction in east-west traffic between workloads that should not communicate", "Total bandwidth increase", "Fewer users", "More firewalls installed"], "B",
         "Fewer unexpected east-west flows shows that segmentation is blocking lateral movement."),
        ("ADVANCED", "Why is device posture verification important even for users who already passed MFA?",
         ["A compromised device can abuse the user's valid session to spread attack", "Posture checks speed the network", "Posture checks replace identity", "MFA is never bypassed"], "C",
         "A trusted user's session is dangerous on an untrusted device, so posture is verified too."),
        ("ADVANCED", "Which implementation detail most often breaks a zero trust rollout?",
         ["Legacy applications that assume direct network reachability", "Too many users", "Fast networks", "Small teams"], "D",
         "Legacy apps that rely on direct network paths resist the broker model zero trust introduces."),
        ("INTERMEDIATE", "Which control best prevents an attacker from using a stolen session token from a foreign location?",
         ["Risk-based conditional access that challenges unusual sessions", "Longer token strings", "More logging", "Rebooting the server"], "C",
         "Risk-based access flags and blocks anomalous session usage, limiting stolen-token abuse."),
        ("ADVANCED", "What is the primary benefit of replacing network trust with identity and context trust?",
         ["Security no longer depends on where the user connects from", "Passwords become optional", "The network becomes invisible", "Latency always drops"], "D",
         "Identity-centric security keeps working even when the network perimeter dissolves, such as in the cloud."),
        ("ADVANCED", "Which architecture most effectively contains a cloud misconfiguration that exposes one service?",
         ["Service-to-service policy enforcement with per-application credentials", "One shared service account", "Public service endpoints", "No identity between services"], "B",
         "Per-application identities and policy enforcement contain the blast radius of a single exposed service."),
        ("ADVANCED", "How does zero trust change how a security team treats a compromised internal device?",
         ["It is treated as already compromised, so all its requests are still verified", "It is given more trust", "It is ignored", "It is removed from logging"], "C",
         "Zero trust never assumes an internal device is safe, so compromise of one device cannot be assumed clean."),
        ("ADVANCED", "Which practice best aligns network policy with zero trust during a migration?",
         ["Defining access by identity and workload labels rather than by IP subnets", "Keep trusting subnets", "Using only static IP rules", "Removing all policies"], "D",
         "Identity- and label-based policy migrates the estate toward zero trust without the brittle IP assumptions."),
        ("ADVANCED", "Which outcome proves a zero trust programme reduced real risk rather than just passing an audit?",
         ["Fewer successful lateral movements and faster containment in incident exercises", "More compliance certificates", "More VPN users", "Longer passwords"], "A",
         "Measured improvements in lateral-movement resistance and containment demonstrate genuine risk reduction."),
    ],
    290: [
        ("BEGINNER", "What is an incident response plan?",
         ["A documented procedure for detecting and responding to security incidents", "A backup schedule", "A marketing plan", "A password list"], "A",
         "An IR plan defines roles, steps and communication for handling security incidents."),
        ("BEGINNER", "Which phase comes first in a typical incident response lifecycle?",
         ["Preparation", "Recovery", "Lessons learned", "Eradication"], "A",
         "Preparation builds the team, tools and procedures before incidents happen."),
        ("BEGINNER", "What is the purpose of detection in incident response?",
         ["To identify that a security incident has occurred", "To delete all files", "To restart servers", "To upgrade the network"], "A",
         "Detection activities such as monitoring and alerts uncover incidents early."),
        ("BEGINNER", "Which term describes keeping evidence intact and properly documented for legal use?",
         ["Chain of custody", "Load balancing", "Auto scaling", "Failover"], "A",
         "Chain of custody records who handled evidence and when, preserving its integrity."),
        ("BEGINNER", "What does containment mean in incident response?",
         ["Limiting the damage and stopping the attacker from spreading", "Deleting all backups", "Increasing permissions", "Opening more ports"], "A",
         "Containment isolates the affected systems to prevent the incident from expanding."),
        ("BEGINNER", "Which cloud resource is most useful for capturing forensic images of a compromised VM?",
         ["Snapshots and volume copies", "A load balancer", "A CDN", "A domain name"], "A",
         "Snapshots and volume copies preserve the VM state for analysis without disturbing the live system."),
        ("BEGINNER", "What is the main value of cloud audit logs during an incident?",
         ["They record the actions and events that reveal how the incident occurred", "They speed up the CPU", "They reduce storage cost", "They replace backups"], "A",
         "Audit logs reconstruct the timeline of actions that led to and followed the incident."),
        ("BEGINNER", "Which step comes AFTER containment in the IR lifecycle?",
         ["Eradication and recovery", "Preparation", "First detection", "Writing the plan"], "A",
         "After containing, teams eradicate the root cause and then recover systems to normal operation."),
        ("BEGINNER", "What is the purpose of a lessons-learned review?",
         ["To improve the response process for future incidents", "To blame someone", "To delete the logs", "To close the case silently"], "A",
         "Lessons learned turn every incident into process improvement."),
        ("BEGINNER", "Which of the following is a cloud-native detection signal?",
         ["Anomalous API call volumes from an identity", "The weather", "The time zone", "The building floor"], "A",
         "Unusual API activity and sign-in anomalies are prime cloud detection signals."),
        ("INTERMEDIATE", "A compromised key starts launching many compute instances. Which containment action is most appropriate first?",
         ["Disable the key and revoke the identity's permissions immediately", "Wait for the bill to arrive", "Delete the whole account", "Ignore the instances"], "A",
         "Revoking the credential stops the attacker's control at its source before other steps."),
        ("INTERMEDIATE", "Which evidence is most important to preserve before taking a compromised cloud instance offline?",
         ["Memory and disk evidence captured while the instance still runs", "A screenshot of the dashboard", "The instance name", "The billing amount"], "A",
         "Volatile evidence such as memory is lost on shutdown, so capture it before powering down."),
        ("INTERMEDIATE", "Which cloud feature best supports rapid containment of a misbehaving deployment?",
         ["Automated rollback to a known-good configuration", "Rebooting the office router", "Buying more instances", "Disabling logging"], "A",
         "Automated rollback quickly restores a safe state, containing the incident's impact."),
        ("INTERMEDIATE", "How does a security team distinguish a real incident from a false alarm?",
         ["Correlating multiple signals and validating against known-good baselines", "Assuming every alert is real", "Ignoring alerts", "Asking the developer"], "A",
         "Correlating signals and validating against baselines separates genuine incidents from noise."),
        ("INTERMEDIATE", "Which of the following is a containment advantage of infrastructure-as-code?",
         ["Environments can be rebuilt exactly and safely after an incident", "It hides incidents", "It makes rollback impossible", "It removes the need for logs"], "A",
         "IaC lets teams rebuild clean environments quickly, aiding containment and recovery."),
        ("INTERMEDIATE", "Which detection tool helps identify misconfigurations that often precede cloud incidents?",
         ["Continuous security posture scanning of cloud resources", "A manual walk-through", "Annual audits", "Screenshots"], "A",
         "Posture scanning catches risky configurations before attackers exploit them."),
        ("INTERMEDIATE", "Which action is part of eradication rather than containment?",
         ["Removing the attacker's persistence mechanisms such as backdoor accounts", "Isolating the affected subnet", "Notifying users", "Backing up evidence"], "A",
         "Eradication removes the root cause and attacker foothold after containment."),
        ("INTERMEDIATE", "Why must cloud forensic evidence include timestamps from a consistent time source?",
         ["To build an accurate, defensible timeline across many services", "To make logs longer", "To reduce storage", "To hide anomalies"], "A",
         "Consistent timestamps let investigators reconstruct the incident sequence reliably."),
        ("INTERMEDIATE", "Which cloud practice makes recovery faster after a ransomware incident?",
         ["Immutable, versioned backups with tested restore procedures", "Deleting old backups", "Storing backups on the same disk", "Never testing restores"], "A",
         "Immutable, tested backups restore data even when production systems are encrypted."),
        ("INTERMEDIATE", "A defender must prove which identity performed a destructive action. Which evidence set is decisive?",
         ["Cloud audit logs correlating the API call with the authenticated identity and IP", "The instance hostname", "The billing account name", "A support ticket"], "A",
         "Audit trails linking each API action to an identity are the decisive evidence for attribution."),
        ("ADVANCED", "Which design most limits the impact of a single stolen cloud key?",
         ["Short-lived credentials with scoped permissions and rapid rotation", "Long-lived admin keys", "Shared root keys", "Keys stored in source code"], "A",
         "Short-lived, scoped credentials shrink both the chance of theft and its blast radius."),
        ("ADVANCED", "Why is memory forensics valuable for cloud workloads even though disks are often ephemeral?",
         ["Memory reveals running processes, injected code and live attacker activity", "Memory is easier to copy", "Memory lasts longer than disk", "Memory stores the whole database"], "A",
         "Volatile memory captures live attacker behaviour that disk-only analysis misses."),
        ("ADVANCED", "Which procedure best preserves forensic value when rebuilding a compromised environment?",
         ["Snapshot the old environment and lock it before rebuilding with IaC", "Overwrite the old disks immediately", "Delete the evidence", "Rebuild without documenting"], "A",
         "Preserving and locking the old state lets investigators analyse it after the rebuild."),
        ("ADVANCED", "Which issue most complicates attribution in cloud forensics?",
         ["Attackers often operate through stolen credentials, proxies and shared infrastructure", "Clouds have no logs", "There is only one attacker", "Evidence is never volatile"], "A",
         "Stolen credentials and anonymising layers make identifying the true actor difficult."),
        ("ADVANCED", "Which integration most improves mean time to detect a cloud incident?",
         ["Automated alert correlation and threat intelligence feeds into a SIEM", "Manual log review once a week", "Checking the console occasionally", "Ignoring alerts"], "A",
         "Automated correlation and intelligence cut detection time by surfacing real threats fast."),
        ("ADVANCED", "Which containment decision is most appropriate for a service hosting customer data during an active breach?",
         ["Isolate the service while preserving forensic evidence, then notify affected users", "Keep it running with no action", "Delete the customer data", "Disable all logging"], "A",
         "Isolation preserves evidence and stops damage while notification meets legal duties."),
        ("ADVANCED", "What is the main reason a cloud IR team tests incident response playbooks regularly?",
         ["To ensure the documented steps work in the real environment before a crisis", "To fill time", "To increase log volume", "To reduce the team's workload"], "A",
         "Regular exercises validate that playbooks work and the team knows its roles."),
        ("ADVANCED", "Which evidence preservation practice is most important when an incident spans multiple cloud accounts?",
         ["Preserving logs and snapshots from every affected account with a central index", "Saving logs from only one account", "Deleting shared evidence", "Preserving only billing records"], "A",
         "A centralised, complete evidence index supports a coherent investigation across accounts."),
        ("ADVANCED", "Which outcome best demonstrates that a cloud incident was truly resolved?",
         ["Root cause eliminated, affected systems restored and validation shows no remaining foothold", "The alert stopped firing", "A month passed without changes", "The attacker apologised"], "A",
         "Resolution requires eradicated root cause, restored systems and validated cleanup, not just quiet alerts."),
        ("ADVANCED", "Which approach best preserves forensic evidence when a cloud incident also involves a data deletion event?",
         ["Enable object versioning and point-in-time recovery before incidents so deleted data can be restored and examined", "Rely on the attacker's logs", "Disable versioning to save cost", "Recreate the data from memory"], "A",
         "Versioning and point-in-time recovery preserve deleted objects so investigators can analyse them after the fact."),
    ],
}
