# -*- coding: utf-8 -*-
"""
Question bank for subject 31: CLD101 - Cloud Computing.
Category: Cloud, Cybersecurity & DevOps.

Topics:
  151: Cloud Models & Services
  152: AWS Core Services
  153: Azure & GCP Basics
  154: Cloud Storage & Databases
  155: Architecture & Cost Mgmt

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    151: [
        ("BEGINNER", "Which cloud service model provides virtualized computing resources such as virtual machines, storage and networking that the customer configures and manages?",
         ["IaaS", "PaaS", "SaaS", "FaaS"], "A",
         "IaaS (Infrastructure as a Service) delivers raw compute, storage and network resources that the customer manages."),
        ("BEGINNER", "Which cloud service model gives developers a managed platform where they deploy and run applications without managing the underlying servers?",
         ["IaaS", "PaaS", "SaaS", "DaaS"], "B",
         "PaaS (Platform as a Service) supplies a managed runtime and tooling so developers focus on application code."),
        ("BEGINNER", "Which cloud service model delivers fully ready-to-use software applications to end users over the internet?",
         ["IaaS", "PaaS", "SaaS", "BaaS"], "C",
         "SaaS (Software as a Service) provides complete applications such as web mail that users access with no installation."),
        ("BEGINNER", "Which cloud deployment model makes computing resources available to the general public on a pay-as-you-go basis?",
         ["private cloud", "hybrid cloud", "edge cloud", "public cloud"], "D",
         "A public cloud is operated by a provider and offered openly to any customer over the internet."),
        ("BEGINNER", "Which cloud deployment model uses infrastructure dedicated exclusively to a single organization?",
         ["private cloud", "hybrid cloud", "multi-cloud", "public cloud"], "A",
         "A private cloud is hosted on infrastructure reserved for one organization only."),
        ("BEGINNER", "Which deployment model combines on-premises infrastructure with public cloud resources to balance control and scale?",
         ["public cloud", "hybrid cloud", "sovereign cloud", "serverless"], "B",
         "A hybrid cloud links private and public environments so workloads can move between them."),
        ("BEGINNER", "Which deployment model describes an organization using more than one cloud provider at the same time?",
         ["single cloud", "community cloud", "multi-cloud", "fog cloud"], "C",
         "Multi-cloud means deliberately using several independent public cloud providers."),
        ("BEGINNER", "Which NIST cloud characteristic lets customers provision resources automatically without requiring human interaction with the provider?",
         ["measured service", "resource pooling", "rapid elasticity", "on-demand self-service"], "D",
         "On-demand self-service allows users to request resources through a self-service interface without manual provider action."),
        ("BEGINNER", "Which NIST cloud characteristic means capabilities are available over the network through standard mechanisms?",
         ["broad network access", "resource pooling", "rapid elasticity", "measured service"], "A",
         "Broad network access describes resources reachable over the network using standard protocols from various devices."),
        ("BEGINNER", "Which NIST cloud characteristic allows computing resources to scale out and in automatically to match demand?",
         ["resource pooling", "rapid elasticity", "measured service", "on-demand self-service"], "B",
         "Rapid elasticity lets capacity grow and shrink elastically, often automatically."),
        ("INTERMEDIATE", "A startup needs virtual machines where it controls the operating system, patches and installed software. Which model should it choose?",
         ["IaaS", "PaaS", "SaaS", "serverless"], "A",
         "IaaS gives the customer full control over the VM including its operating system and software."),
        ("INTERMEDIATE", "A team wants to deploy a web app using only a preconfigured runtime and database service, ignoring server administration. Which model fits best?",
         ["IaaS", "PaaS", "SaaS", "bare metal"], "B",
         "PaaS abstracts away servers and provides managed runtimes and databases for application deployment."),
        ("INTERMEDIATE", "An HR department needs a payroll application available immediately with no internal hosting or upgrades. Which model is most suitable?",
         ["IaaS", "PaaS", "SaaS", "DaaS"], "C",
         "SaaS delivers the finished payroll product over the internet with all maintenance handled by the vendor."),
        ("INTERMEDIATE", "A bank keeps customer records on-premises for compliance but wants to burst web traffic to the public cloud during peaks. Which deployment fits?",
         ["public cloud only", "private cloud only", "community cloud", "hybrid cloud"], "D",
         "A hybrid cloud keeps sensitive data in the private environment while scaling overflow to the public cloud."),
        ("INTERMEDIATE", "A retailer deliberately runs workloads on AWS, Azure and GCP to avoid depending on one vendor. Which strategy is this?",
         ["multi-cloud", "hybrid cloud", "private cloud", "fog computing"], "A",
         "Using several public providers at once is the definition of a multi-cloud strategy."),
        ("INTERMEDIATE", "Compared with IaaS virtual machines, what is the main advantage of a serverless function service?",
         ["full OS control", "no infrastructure and server management with pay-per-invocation billing", "guaranteed zero latency", "fixed capacity planning"], "B",
         "Serverless removes server administration and bills only for the compute consumed during each invocation."),
        ("INTERMEDIATE", "Which statement correctly distinguishes Function as a Service (FaaS) from other compute models?",
         ["it runs long-lived virtual machines", "it requires dedicated servers", "it executes single functions in response to events", "it only works with on-premises hardware"], "C",
         "FaaS runs event-driven functions that spin up on demand and scale automatically."),
        ("INTERMEDIATE", "In a SaaS arrangement, where does the customer responsibility for the underlying infrastructure end?",
         ["the customer manages the servers", "the customer manages the OS", "the customer manages the network", "the customer manages only its data and users"], "D",
         "With SaaS the provider manages everything below the data, so the customer is responsible only for its data and access."),
        ("INTERMEDIATE", "Under the shared responsibility model for IaaS, who is responsible for patching the guest operating system of a virtual machine?",
         ["the customer", "the cloud provider", "the hardware vendor", "the network operator"], "A",
         "For IaaS the customer owns the guest OS and must apply its patches, while the provider protects the host."),
        ("INTERMEDIATE", "Which service model places the least operational management burden on the customer?",
         ["IaaS", "SaaS", "PaaS", "managed hosting only"], "B",
         "SaaS shifts nearly all management to the provider, leaving the customer with the least operational work."),
        ("ADVANCED", "A healthcare company faces strict data residency regulations and must keep patient data inside its own country. Which approach best satisfies this?",
         ["use a dedicated private cloud or a cloud region located in that country", "use only public cloud in any region", "store data on employee laptops", "outsource to the cheapest provider"], "A",
         "A private cloud or a region physically located in the required country meets residency rules while still giving cloud benefits."),
        ("ADVANCED", "An organization runs 24x7 workloads yet its cloud bill keeps rising because VMs sit idle outside business hours. Which measure addresses this waste?",
         ["adding more instances", "right-sizing and stopping idle instances during off-peak periods", "moving everything to a single big VM", "disabling monitoring"], "B",
         "Right-sizing instances and shutting down idle ones reduces cost without losing capacity when needed."),
        ("ADVANCED", "A company has a predictable baseline workload plus occasional massive demand spikes. Which architecture is most cost-effective?",
         ["provision for peak capacity permanently", "use only on-premises hardware", "keep a baseline and scale elastically for the spikes", "disable auto scaling"], "C",
         "Elastic scaling lets the baseline run efficiently and adds capacity only during spikes."),
        ("ADVANCED", "Which scenario best justifies adopting a multi-cloud architecture despite its higher complexity?",
         ["a single app with trivial uptime needs", "eliminating all security controls", "reducing the number of cloud skills needed", "avoiding vendor lock-in and meeting provider-specific regulatory requirements"], "D",
         "Multi-cloud reduces dependence on one vendor and can satisfy regulations that vary by provider."),
        ("ADVANCED", "A company must run periodic batch analytics that produce sudden, short-lived CPU spikes. Which compute choice is most efficient?",
         ["serverless or elastic burst compute for the short jobs", "always-on dedicated servers", "a single oversized VM", "manual batch execution at night"], "A",
         "Serverless or burst compute charges only for the short period of activity, suiting spiky batch jobs."),
        ("ADVANCED", "Under the shared responsibility model for an IaaS virtual machine, which item is the provider responsible for?",
         ["physical security of the data center", "patching the guest OS", "securing customer passwords", "installing the customer application"], "B",
         "The provider owns the physical infrastructure, including data center security, hosts and the network."),
        ("ADVANCED", "A company migrates a legacy monolith to a managed PaaS platform. What is the primary benefit it gains?",
         ["more server control", "guaranteed identical performance", "reduced infrastructure operations so it can focus on application code", "removal of all security duties"], "C",
         "PaaS removes platform administration, letting the team concentrate on developing and deploying the application."),
        ("ADVANCED", "Which factor most directly causes slower response times in a cold serverless function start?",
         ["larger disk quota", "the number of database rows", "the DNS TTL", "initialization time when no warm instance exists"], "D",
         "A cold start delays the response because the platform must initialize the runtime before handling the request."),
        ("ADVANCED", "A fintech firm must keep core ledger workloads on its own hardware but use the public cloud for analytics. Which deployment model does this describe?",
         ["hybrid cloud", "pure public cloud", "pure private cloud", "edge computing"], "A",
         "Hybrid cloud spans private and public environments, letting the firm keep core workloads on-premises while using the cloud."),
        ("ADVANCED", "A customer wants to protect against a single cloud provider outage without rearchitecting to multi-cloud. What is the simplest mitigation?",
         ["disable redundancy", "store data only on-premises", "remove all backups", "use multiple regions and availability zones of the same provider"], "B",
         "Spreading workloads across regions and zones of one provider guards against localized failures without multi-cloud complexity."),
    ],
    152: [
        ("BEGINNER", "Which AWS service provides resizable virtual servers in the cloud?",
         ["EC2", "S3", "Lambda", "RDS"], "A",
         "Amazon EC2 offers resizable virtual machines that customers launch with chosen instance types."),
        ("BEGINNER", "Which AWS service is a highly durable object storage service for files and media?",
         ["EBS", "S3", "EFS", "Glacier only"], "B",
         "Amazon S3 stores unlimited objects and is AWS's core object storage service."),
        ("BEGINNER", "Which AWS service provides managed relational databases such as MySQL and PostgreSQL?",
         ["DynamoDB", "EC2", "RDS", "Redshift"], "C",
         "Amazon RDS is a managed relational database service supporting engines like MySQL and PostgreSQL."),
        ("BEGINNER", "Which AWS service runs code in response to events without provisioning servers?",
         ["EC2", "Elastic Beanstalk", "CloudFront", "Lambda"], "D",
         "AWS Lambda is the serverless compute service that executes functions triggered by events."),
        ("BEGINNER", "Which AWS service lets you manage users, groups, roles and permissions securely?",
         ["IAM", "CloudWatch", "Route 53", "SQS"], "A",
         "AWS Identity and Access Management (IAM) controls access to AWS resources."),
        ("BEGINNER", "Which AWS service provides an isolated virtual network where you define subnets and routes?",
         ["Direct Connect", "VPC", "CloudFront", "S3"], "B",
         "Amazon VPC creates a logically isolated section of the AWS cloud for your networking."),
        ("BEGINNER", "Which AWS service is a content delivery network that caches content close to users?",
         ["Route 53", "EC2", "CloudFront", "SNS"], "C",
         "Amazon CloudFront is AWS's CDN that accelerates content delivery via edge locations."),
        ("BEGINNER", "Which AWS service translates domain names into IP addresses?",
         ["CloudWatch", "IAM", "ElastiCache", "Route 53"], "D",
         "Amazon Route 53 is the AWS DNS and domain registration service."),
        ("BEGINNER", "Which AWS service is a fully managed NoSQL database built for key-value and document workloads?",
         ["DynamoDB", "Aurora", "Redshift", "RDS"], "A",
         "Amazon DynamoDB is a managed NoSQL database offering consistent single-digit millisecond access."),
        ("BEGINNER", "Which S3 storage class is the default for frequently accessed data?",
         ["S3 Standard", "S3 Glacier Deep Archive", "S3 One Zone-IA", "S3 Reduced Redundancy"], "B",
         "S3 Standard is designed for frequently accessed data with low latency and high durability."),
        ("INTERMEDIATE", "A team needs full control over the operating system, kernel and installed software of its compute instances. Which AWS service should it use?",
         ["Elastic Beanstalk", "EC2", "Lambda", "Fargate"], "A",
         "EC2 gives customers full control over the instance including the OS and kernel."),
        ("INTERMEDIATE", "Which AWS setup is best for hosting a static website with high availability and low latency?",
         ["a single EC2 instance", "S3 bucket with CloudFront in front", "DynamoDB table", "a VPC without internet access"], "B",
         "S3 serves static files durably and CloudFront caches them at edge locations for speed."),
        ("INTERMEDIATE", "A web app expects variable traffic and needs instances added and removed automatically. Which AWS feature provides this?",
         ["Route 53 failover", "S3 lifecycle rules", "EC2 Auto Scaling", "VPC peering"], "C",
         "EC2 Auto Scaling launches and terminates instances based on demand and configured policies."),
        ("INTERMEDIATE", "A company wants a fully managed PostgreSQL database with automated backups and failover. Which service fits best?",
         ["DynamoDB", "ElastiCache", "S3", "RDS"], "D",
         "Amazon RDS manages the database engine, backups, patching and failover."),
        ("INTERMEDIATE", "Which AWS service is best for decoupling microservices so producers and consumers can process messages independently?",
         ["SQS", "CloudFront", "Route 53", "EFS"], "A",
         "Amazon SQS is a managed message queue that decouples application components."),
        ("INTERMEDIATE", "Where should an application store database credentials and API keys securely?",
         ["in the source code", "AWS Secrets Manager or Parameter Store", "an S3 public bucket", "a README file"], "B",
         "Secrets Manager keeps credentials encrypted and centrally managed instead of exposing them in code."),
        ("INTERMEDIATE", "Which AWS service monitors resources and raises alarms based on metrics such as CPU utilization?",
         ["IAM", "Direct Connect", "CloudWatch", "Route 53"], "C",
         "CloudWatch collects metrics and triggers alarms when thresholds are crossed."),
        ("INTERMEDIATE", "An organization must archive old files that are rarely accessed at the lowest cost. Which S3 feature should it use?",
         ["S3 Transfer Acceleration", "S3 versioning only", "S3 cross-region replication only", "S3 lifecycle rules moving objects to Glacier"], "D",
         "Lifecycle policies automatically transition infrequently used objects to cheaper archival classes like Glacier."),
        ("INTERMEDIATE", "In a VPC, what distinguishes a public subnet from a private subnet?",
         ["a public subnet has a route to the internet gateway", "a public subnet has more CPUs", "a public subnet stores objects", "a public subnet cannot launch EC2 instances"], "A",
         "The presence of an internet gateway route makes a subnet public; without it the subnet is private."),
        ("INTERMEDIATE", "Why would you choose EBS volume storage over an EC2 instance store?",
         ["instance store is cheaper per second", "EBS data persists independently of the instance lifecycle", "EBS cannot be snapshotted", "instance store stores more data"], "B",
         "EBS volumes are network-attached and persist across instance stops and terminations, unlike ephemeral instance stores."),
        ("ADVANCED", "A company runs a steady 24x7 workload and wants to cut compute cost. Which purchasing option is most effective?",
         ["Reserved Instances or Savings Plans", "on-demand instances", "spot instances for the baseline", "increasing instance size"], "A",
         "Reserved Instances and Savings Plans trade commitment for significantly lower hourly rates on steady workloads."),
        ("ADVANCED", "To protect a stateless web tier against a single availability zone failure, which design is correct?",
         ["place all instances in one AZ", "run instances in multiple availability zones behind a load balancer", "disable load balancing", "use only one large instance"], "B",
         "Spreading instances across AZs with a load balancer keeps the tier available if one AZ fails."),
        ("ADVANCED", "Which AWS feature protects an S3 bucket against accidental deletion of data?",
         ["S3 Transfer Acceleration", "CloudFront cache", "S3 versioning", "VPC flow logs"], "C",
         "Versioning keeps previous versions of objects so accidental overwrites or deletes can be restored."),
        ("ADVANCED", "Which architecture provides a fully serverless REST API on AWS?",
         ["EC2 instances with an ELB", "a bare-metal server", "CloudFront with only static files", "API Gateway with Lambda functions backed by DynamoDB"], "D",
         "API Gateway handles routing and auth while Lambda runs the logic and DynamoDB stores the data."),
        ("ADVANCED", "What is the main benefit of configuring reserved concurrency on a Lambda function?",
         ["it caps concurrent invocations to control throttling and costs", "it increases the memory of every function", "it removes the need for IAM", "it speeds up cold starts indefinitely"], "A",
         "Reserved concurrency limits how many instances run at once, preventing runaway scaling and cost."),
        ("ADVANCED", "Which statement correctly describes an AWS security group?",
         ["it is a stateless network ACL for subnets", "it is a stateful instance-level firewall", "it encrypts all traffic", "it replaces IAM"], "B",
         "Security groups are stateful firewalls applied at the instance level; return traffic is allowed automatically."),
        ("ADVANCED", "Which option is the most effective way to reduce data egress costs when serving a global user base?",
         ["make the S3 bucket public", "increase EC2 instance sizes", "serve content through CloudFront edge caches", "use more AZs in one region"], "C",
         "CloudFront caches content at edge locations, so most requests are served without reaching the origin."),
        ("ADVANCED", "How do you scale read-heavy database workloads on Amazon RDS?",
         ["stop the database at night", "disable query logging", "add more AZs to the same instance", "create Read Replicas to offload SELECT traffic"], "D",
         "Read Replicas are asynchronous copies that serve read traffic, reducing load on the primary database."),
        ("ADVANCED", "Which combination is best for a cost-aware, fault-tolerant static asset delivery architecture?",
         ["S3 Standard with S3 Replication and CloudFront", "a single EC2 instance with a public IP", "an on-premises FTP server", "a Lambda function per request"], "A",
         "S3 gives durability, replication adds DR protection and CloudFront provides fast, cheap distribution."),
        ("ADVANCED", "Under IAM best practices, what does the principle of least privilege mean?",
         ["grant every user admin rights", "grant only the permissions needed to perform required tasks", "share one root account", "never use roles"], "B",
         "Least privilege limits access to exactly what each user or role needs, reducing blast radius."),
    ],
    153: [
        ("BEGINNER", "Which Azure service provides resizable virtual machines similar to AWS EC2?",
         ["Azure Virtual Machines", "Azure Blob Storage", "Azure Functions", "Azure SQL Database"], "A",
         "Azure Virtual Machines offers on-demand Windows and Linux virtual machines."),
        ("BEGINNER", "Which Azure service is the equivalent of AWS S3 for storing unstructured objects and blobs?",
         ["Azure Table", "Azure Blob Storage", "Azure DNS", "Azure VNet"], "B",
         "Azure Blob Storage stores large amounts of unstructured data such as files and images."),
        ("BEGINNER", "Which Azure service provides a managed relational database for SQL Server?",
         ["Azure Cosmos DB", "Azure Redis", "Azure SQL Database", "Azure Files"], "C",
         "Azure SQL Database is a fully managed relational database based on SQL Server."),
        ("BEGINNER", "Which Azure service runs serverless code in response to events?",
         ["Azure Virtual Machines", "Azure Front Door", "Azure CDN", "Azure Functions"], "D",
         "Azure Functions is the serverless compute service for event-driven functions."),
        ("BEGINNER", "Which Azure service manages identities and access for users and applications?",
         ["Microsoft Entra ID (Azure AD)", "Azure Monitor", "Azure Storage", "Azure DNS"], "A",
         "Microsoft Entra ID, formerly Azure Active Directory, provides identity and access management."),
        ("BEGINNER", "Which GCP service provides virtual machines that you can resize as needed?",
         ["Cloud Functions", "Compute Engine", "BigQuery", "App Engine"], "B",
         "Google Compute Engine offers resizable virtual machines on Google Cloud."),
        ("BEGINNER", "Which GCP service stores unstructured objects such as images and backups?",
         ["Cloud SQL", "Cloud Spanner", "Cloud Storage", "BigQuery"], "C",
         "Google Cloud Storage is GCP's scalable object storage service."),
        ("BEGINNER", "Which GCP service is the serverless compute option for event-driven functions?",
         ["Compute Engine", "Kubernetes Engine", "Cloud Run only", "Cloud Functions"], "D",
         "Cloud Functions executes single-purpose functions in response to events."),
        ("BEGINNER", "Which GCP service provides a fully managed Kubernetes environment?",
         ["Google Kubernetes Engine (GKE)", "Cloud SQL", "Compute Engine", "Cloud Storage"], "A",
         "GKE is Google's managed Kubernetes service for running containerized workloads."),
        ("BEGINNER", "What is an Azure region?",
         ["a single server in a data center", "a geographic area containing one or more data centers", "a virtual machine", "a type of network"], "B",
         "An Azure region is a set of data centers located within a geographic boundary."),
        ("INTERMEDIATE", "A company runs flexible batch jobs in GCP that can be interrupted. Which instance type is most cost-effective?",
         ["preemptible (spot) VMs", "sole-tenant nodes", "GPU instances for every job", "memory-optimized instances"], "A",
         "Preemptible VMs are significantly cheaper and fine for interruptible, stateless batch work."),
        ("INTERMEDIATE", "Which Azure service is best for hosting a web app while the platform manages scaling and patching?",
         ["Azure Virtual Machines", "Azure App Service", "Azure Blob Storage", "Azure DNS"], "B",
         "Azure App Service is a PaaS for hosting web apps with built-in scaling and management."),
        ("INTERMEDIATE", "Which GCP service is a serverless, fully managed data warehouse for petabyte-scale analytics?",
         ["Cloud SQL", "Datastore", "BigQuery", "Cloud Storage"], "C",
         "BigQuery is a serverless data warehouse with SQL analytics at massive scale."),
        ("INTERMEDIATE", "Which Azure service provides CI/CD pipelines for building and deploying applications?",
         ["Azure Front Door", "Azure Monitor", "Azure DNS", "Azure DevOps"], "D",
         "Azure DevOps includes pipelines for continuous integration and continuous delivery."),
        ("INTERMEDIATE", "Which GCP service runs containerized applications in a fully managed serverless environment?",
         ["Cloud Run", "Compute Engine", "Cloud Functions only", "Cloud Storage"], "A",
         "Cloud Run executes stateless containers that scale automatically without managing servers."),
        ("INTERMEDIATE", "What is the purpose of an Azure resource group?",
         ["a type of virtual machine", "a logical container for grouping related Azure resources", "a DNS zone", "a firewall rule"], "B",
         "Resource groups group related resources so they can be managed, monitored and deleted together."),
        ("INTERMEDIATE", "Which statement about GCP VPC networking is correct?",
         ["VPCs exist only inside one zone", "VPCs cannot be shared", "a single VPC network is global and spans all regions", "each VM gets its own private cloud"], "C",
         "GCP VPC networks are global, letting the same network span regions with subnets in each."),
        ("INTERMEDIATE", "What do Azure availability zones provide?",
         ["a global content delivery network", "a DNS service", "an identity service", "isolated data centers within a region for fault tolerance"], "D",
         "Availability zones are physically separate locations within a region that protect against datacenter failures."),
        ("INTERMEDIATE", "Which GCP service provides managed MySQL and PostgreSQL databases?",
         ["Cloud SQL", "BigQuery", "Cloud Spanner", "Firestore"], "A",
         "Cloud SQL offers fully managed relational databases compatible with MySQL and PostgreSQL."),
        ("INTERMEDIATE", "Which Azure service is a globally distributed NoSQL database with multiple consistency options?",
         ["Azure SQL Database", "Azure Cosmos DB", "Azure Table", "Azure Cache for Redis"], "B",
         "Cosmos DB is a multi-model, globally distributed NoSQL database service."),
        ("ADVANCED", "A company runs steady GCP workloads 24x7 and wants to lower cost. Which GCP pricing benefit applies automatically?",
         ["sustained use discounts for running VMs for a large fraction of the month", "no billing for data egress", "free GPU instances", "paying only for memory"], "A",
         "Sustained use discounts automatically reduce the cost of VMs run for most of a billing month."),
        ("ADVANCED", "Which Azure feature lets customers reuse existing Windows Server licenses to reduce VM cost?",
         ["Azure Spot VMs", "Azure Hybrid Benefit", "Azure Savings Plans only", "Azure Reserved IP"], "B",
         "Azure Hybrid Benefit applies existing on-premises Windows Server licenses to discounted Azure VM pricing."),
        ("ADVANCED", "Which GCP mechanism enforces restrictions such as allowing only certain regions for a project?",
         ["Cloud CDN", "Cloud SQL", "organization policies", "preemptible VMs"], "C",
         "Organization policies apply constraints across GCP resources, such as restricting allowed regions."),
        ("ADVANCED", "Which Azure tooling enforces corporate compliance by defining and auditing policy rules across subscriptions?",
         ["Azure CDN", "Azure Cosmos DB", "Azure Traffic Manager only", "Azure Policy with Azure Blueprints"], "D",
         "Azure Policy evaluates resources against defined rules, and Blueprints bundle reusable governance definitions."),
        ("ADVANCED", "Which GCP database provides strongly consistent global relational storage for a financial services app?",
         ["Cloud Spanner", "Firestore", "Bigtable", "Cloud Storage"], "A",
         "Cloud Spanner is a globally distributed relational database offering strong consistency at scale."),
        ("ADVANCED", "Which Azure networking pattern centralizes shared services with spoke workloads connecting to a hub?",
         ["a single flat subnet", "hub-and-spoke with VNet peering", "direct internet connections only", "Azure DNS zones only"], "B",
         "Hub-and-spoke uses VNet peering to route spokes through a central hub for shared security and services."),
        ("ADVANCED", "Which GKE feature automatically adds or removes nodes based on pending pod demand?",
         ["node pool versioning", "Cloud CDN", "cluster autoscaler", "preemptible billing"], "C",
         "The GKE cluster autoscaler resizes node pools so capacity matches current pod requirements."),
        ("ADVANCED", "Which Azure Blob Storage access tier is intended for data that is accessed rarely and kept for years?",
         ["Hot", "Cool", "Premium only", "Archive"], "D",
         "The Archive tier stores rarely accessed data at the lowest cost with delayed retrieval."),
        ("ADVANCED", "Which GCP networking feature lets a network team centrally manage subnets shared by many projects?",
         ["Shared VPC", "Cloud Interconnect", "Cloud NAT", "VPC flow logs"], "A",
         "Shared VPC allows a central host project to share its networking with multiple service projects."),
        ("ADVANCED", "Which Azure construct provides a standardized foundation of policy, security and networking for new workloads?",
         ["a single resource group", "Azure Landing Zones", "Azure Blob containers", "Azure Spot VMs"], "B",
         "Landing Zones are prescriptive reference architectures that give enterprise governance and networking at scale."),
    ],
    154: [
        ("BEGINNER", "What type of storage does Amazon S3 provide?",
         ["object storage", "block storage", "file storage", "in-memory cache"], "A",
         "S3 stores data as objects in buckets, which is the object storage model."),
        ("BEGINNER", "Which storage type is attached to a virtual machine and behaves like a raw disk?",
         ["object storage", "block storage", "file storage", "DNS storage"], "B",
         "Block storage such as EBS presents raw volumes that a VM formats and mounts like a disk."),
        ("BEGINNER", "Which AWS storage service provides a shared file system mountable by multiple instances?",
         ["S3", "DynamoDB", "EFS", "CloudFront"], "C",
         "Amazon EFS is a managed file system that many EC2 instances can mount concurrently."),
        ("BEGINNER", "What distinguishes a relational database from a NoSQL database?",
         ["NoSQL databases always require SQL", "relational databases cannot store data", "NoSQL databases are always slower", "relational databases use tables with defined schemas and SQL"], "D",
         "Relational databases organize data into tables with schemas and query it with SQL."),
        ("BEGINNER", "What is a primary key in a relational database?",
         ["a column that uniquely identifies each row", "a column with duplicate values", "a type of index on every table", "a database backup"], "A",
         "A primary key uniquely identifies every row in a table, preventing duplicates."),
        ("BEGINNER", "What is the main difference between a database and a data warehouse?",
         ["a data warehouse stores only text files", "a data warehouse is optimized for analytics on large historical datasets", "a database cannot store numbers", "a warehouse runs the application code"], "B",
         "Data warehouses are designed for analytical queries across large, consolidated datasets."),
        ("BEGINNER", "What is the purpose of a database backup?",
         ["to speed up queries", "to encrypt passwords", "to restore data after loss or corruption", "to create new databases"], "C",
         "Backups capture data so it can be recovered after failures or accidental deletion."),
        ("BEGINNER", "What is database replication?",
         ["deleting old records", "renaming tables", "compressing the database", "copying data to additional servers for availability and reads"], "D",
         "Replication maintains copies of data on other servers, improving availability and read performance."),
        ("BEGINNER", "Which language is used to query relational databases?",
         ["SQL", "HTML", "JSON", "YAML"], "A",
         "SQL (Structured Query Language) is the standard language for querying relational databases."),
        ("BEGINNER", "Which type of NoSQL database stores data as JSON-like documents?",
         ["relational databases", "document databases such as MongoDB", "data warehouses", "columnar OLAP only"], "B",
         "Document databases store flexible, JSON-like documents rather than fixed table rows."),
        ("INTERMEDIATE", "Which combination of S3 features best protects against accidental object deletion and manages data age?",
         ["versioning plus lifecycle rules", "only bucket encryption", "only a public bucket", "S3 Transfer Acceleration"], "A",
         "Versioning preserves deleted versions while lifecycle rules automatically archive or expire old objects."),
        ("INTERMEDIATE", "Which storage choice is correct when multiple application servers need to read and write the same files?",
         ["an S3 private bucket used as a disk", "a shared file system such as EFS", "a single EBS volume attached to one instance", "an in-memory cache"], "B",
         "EFS is a shared file system, whereas an EBS volume can normally attach to only one instance at a time."),
        ("INTERMEDIATE", "For a high-throughput key-value lookup with predictable low latency, which database fits best?",
         ["a relational database with joins", "a data warehouse", "DynamoDB", "a static S3 site"], "C",
         "DynamoDB is a NoSQL key-value database built for consistent low-latency lookups."),
        ("INTERMEDIATE", "Why does adding an index to a table usually speed up queries?",
         ["it duplicates every row", "it removes the primary key", "it disables caching", "it lets the database find rows without scanning the whole table"], "D",
         "An index is a sorted structure that lets the engine locate rows quickly instead of scanning everything."),
        ("INTERMEDIATE", "What does the ACID acronym describe?",
         ["transaction properties: Atomicity, Consistency, Isolation, Durability", "a type of disk", "a storage class", "an encryption algorithm"], "A",
         "ACID defines the reliability guarantees that relational transactions should provide."),
        ("INTERMEDIATE", "Which technique reduces load on a primary database by serving read queries from copies?",
         ["primary key reuse", "read replicas", "deleting indexes", "disabling the cache"], "B",
         "Read replicas are asynchronous copies that absorb SELECT traffic, protecting the primary."),
        ("INTERMEDIATE", "Why do applications typically use a connection pool?",
         ["it encrypts all data", "it creates backups automatically", "reusing database connections avoids the overhead of opening new ones", "it shrinks the database"], "C",
         "Connection pooling reuses established connections, cutting the cost of repeated setup and teardown."),
        ("INTERMEDIATE", "Which S3 storage class is the cheapest for data that is accessed at most once per year?",
         ["S3 Standard", "S3 Intelligent-Tiering", "S3 One Zone-IA", "S3 Glacier Deep Archive"], "D",
         "Glacier Deep Archive offers the lowest storage price for rarely accessed archival data."),
        ("INTERMEDIATE", "Why should data be encrypted at rest in cloud storage?",
         ["it protects the data if physical media or access controls are compromised", "it makes the data faster", "it reduces storage costs", "it is required for public buckets only"], "A",
         "Encryption at rest ensures that stored data stays unreadable without keys even if storage is breached."),
        ("INTERMEDIATE", "What does a backup retention policy control?",
         ["the number of CPUs", "how long backup copies are kept before they are removed", "the database schema", "the query language"], "B",
         "Retention rules define how long backups remain available for restore before expiring."),
        ("ADVANCED", "To guarantee database availability when an entire availability zone fails, which design is correct for RDS?",
         ["deploy Multi-AZ with automatic failover to a standby replica", "run the database on one EC2 instance", "disable automated backups", "put the DB in a single AZ"], "A",
         "Multi-AZ RDS maintains a standby in another AZ and fails over automatically."),
        ("ADVANCED", "Which statement about S3 consistency is correct today?",
         ["S3 is eventually consistent only", "S3 provides strong read-after-write consistency for all objects", "S3 never guarantees reads", "S3 consistency depends on the bucket name"], "B",
         "Since 2020, S3 offers strong read-after-write consistency for both new and overwritten objects."),
        ("ADVANCED", "How would you enable fast queries on a non-key attribute in DynamoDB?",
         ["add a second table with no key", "run full scans on every request", "create a global secondary index on that attribute", "disable the primary key"], "C",
         "A global secondary index lets you query by other attributes with its own key schema."),
        ("ADVANCED", "When a single database table grows too large for one node, which technique distributes rows across multiple nodes?",
         ["adding more columns", "turning off indexes", "storing data as JSON", "sharding (horizontal partitioning)"], "D",
         "Sharding splits rows across shards so each node stores only a subset of the data."),
        ("ADVANCED", "Which AWS option is most cost-effective for storing rarely accessed compliance records that must be kept for 7 years?",
         ["S3 Glacier with lifecycle transitions from Standard", "S3 Standard only", "EC2 instance storage", "an EBS volume per record"], "A",
         "Lifecycle rules move old objects to Glacier, giving cheap long-term archival storage."),
        ("ADVANCED", "A search-heavy application returns the same results repeatedly. Which pattern reduces database load?",
         ["querying without indexes", "cache-aside with a cache such as ElastiCache", "storing cache in the database", "disabling the primary key"], "B",
         "Cache-aside stores frequent query results in a cache and checks it before hitting the database."),
        ("ADVANCED", "Which pattern updates a data store automatically whenever a new object is uploaded to S3?",
         ["a cron job that polls manually", "RDS read replicas", "S3 event notifications triggering a Lambda function", "VPC flow logs"], "C",
         "S3 can publish events to Lambda on object creation, enabling event-driven data pipelines."),
        ("ADVANCED", "When running heavy analytics on terabytes of transactional history, which storage choice is most appropriate?",
         ["a transactional OLTP database", "a single CSV file", "an in-memory key-value cache", "a columnar data warehouse such as Redshift or BigQuery"], "D",
         "Columnar warehouses are optimized for scanning large analytical datasets efficiently."),
        ("ADVANCED", "What trade-off must be considered with cross-region database replication?",
         ["replication latency and cost versus faster regional recovery", "there are no trade-offs", "it reduces durability", "it prevents reads entirely"], "A",
         "Cross-region replication improves disaster recovery but adds latency and cost for copying data."),
        ("ADVANCED", "To serve billions of records with queries on multiple fields while keeping low latency, which database choice is sound?",
         ["a single-row relational table", "DynamoDB with secondary indexes or a globally distributed NoSQL database", "an FTP server", "a data warehouse for online traffic"], "B",
         "A NoSQL database with secondary indexes scales to large datasets while keeping query latency low."),
    ],
    155: [
        ("BEGINNER", "What is a microservice?",
         ["a small, independently deployable service that performs one function", "a single huge application", "a type of virtual machine", "a load balancer"], "A",
         "Microservices are small, independently deployable services that each handle a focused business function."),
        ("BEGINNER", "What is the main purpose of a load balancer?",
         ["storing backups", "distributing traffic across multiple servers", "compiling code", "encrypting the database"], "B",
         "A load balancer spreads incoming requests across healthy instances to share load and improve availability."),
        ("BEGINNER", "What does auto scaling allow a system to do?",
         ["scale only up to one server", "delete all backups", "automatically add or remove resources based on demand", "reduce monitoring"], "C",
         "Auto scaling adjusts capacity automatically to match current demand."),
        ("BEGINNER", "What is fault tolerance?",
         ["the speed of a hard disk", "the size of the database", "the number of users", "the ability to keep operating correctly when some components fail"], "D",
         "A fault-tolerant system continues to work even when part of it fails."),
        ("BEGINNER", "What does high availability (HA) mean?",
         ["systems remain accessible with minimal downtime over long periods", "a server with more RAM", "a public IP address", "a faster network"], "A",
         "High availability keeps services reachable by minimizing downtime, usually through redundancy."),
        ("BEGINNER", "What is the Recovery Time Objective (RTO)?",
         ["the number of backups", "the maximum acceptable time to restore a service after a disaster", "the size of a server", "the cost of a VM"], "B",
         "RTO defines how quickly a system must be restored after a disruption."),
        ("BEGINNER", "What is a Content Delivery Network (CDN)?",
         ["a database engine", "a virtual private network", "a distributed network of servers that caches content near users", "a type of firewall"], "C",
         "A CDN serves cached copies of content from edge servers close to the user for lower latency."),
        ("BEGINNER", "What is the main role of an API gateway?",
         ["a data warehouse", "a disk type", "a load balancer only for websites", "a single entry point that routes, secures and throttles API requests"], "D",
         "An API gateway fronts backend services, handling routing, authentication, rate limiting and monitoring."),
        ("BEGINNER", "What is monitoring in a cloud architecture?",
         ["collecting and analyzing metrics, logs and alerts about system health", "backing up the source code", "building the application", "paying the bill"], "A",
         "Monitoring gathers metrics and logs so operators can detect and react to problems."),
        ("BEGINNER", "What is the goal of cloud cost management?",
         ["spending as much as possible", "optimizing spending while maintaining required performance and availability", "hiding costs", "removing all resources"], "B",
         "Cost management aims to get the required performance for the lowest reasonable spend."),
        ("INTERMEDIATE", "Why should application services be designed to be stateless?",
         ["stateless services scale horizontally because any instance can serve any request", "they cannot handle failures", "they are harder to deploy", "they require a database on every node"], "A",
         "Stateless services keep no local state, so any instance can handle any request, enabling simple horizontal scaling."),
        ("INTERMEDIATE", "Which approach scales a web tier to handle 10x traffic?",
         ["increasing RAM on one server", "horizontal scaling by adding more instances behind a load balancer", "deleting instances", "disabling the load balancer"], "B",
         "Horizontal scaling adds instances and balances load across them, giving near-linear capacity growth."),
        ("INTERMEDIATE", "What is the purpose of autoscaling in a cloud architecture?",
         ["it automatically adds and removes compute capacity based on demand", "it permanently runs the largest possible fleet of servers", "it replaces the load balancer", "it keeps every instance in a single availability zone"], "A",
         "Autoscaling monitors utilization metrics and adjusts the number of instances so capacity matches demand without manual intervention."),
        ("INTERMEDIATE", "Which deployment strategy runs the new version alongside the old one and shifts traffic gradually?",
         ["in-place restart", "deleting the old version", "manual FTP upload", "blue-green deployment"], "D",
         "Blue-green deployment keeps two environments and shifts traffic between them for low-risk releases."),
        ("INTERMEDIATE", "Why do distributed systems use retries with exponential backoff?",
         ["it retries failed calls with increasing delays to avoid overwhelming a recovering service", "it retries instantly forever", "it gives up immediately", "it duplicates all requests"], "A",
         "Exponential backoff spreads retries out, giving the failing service time to recover without adding load."),
        ("INTERMEDIATE", "What is the purpose of a circuit breaker in a microservice architecture?",
         ["it encrypts all traffic", "it stops calls to a failing dependency to prevent cascading failures", "it caches static files", "it renames services"], "B",
         "A circuit breaker opens when a dependency fails, rejecting calls quickly so failures do not cascade."),
        ("INTERMEDIATE", "What makes an API operation idempotent?",
         ["it can never fail", "it always deletes data", "repeating the same request produces the same result as a single call", "it returns random values"], "C",
         "Idempotent operations return the same result no matter how many times they are retried, which is key for retries."),
        ("INTERMEDIATE", "Which practice directly reduces cloud spend for consistently over-provisioned instances?",
         ["buying the largest instances", "adding more monitoring alarms", "removing cost reports", "right-sizing instances to match actual utilization"], "D",
         "Right-sizing matches instance size to real usage so you stop paying for unused capacity."),
        ("INTERMEDIATE", "Why are cloud resources typically tagged?",
         ["tags group resources by cost center, environment or owner for tracking and billing", "tags speed up the CPU", "tags replace security groups", "tags are mandatory for encryption"], "A",
         "Tagging lets organizations allocate cost, manage environments and enforce policies by resource metadata."),
        ("INTERMEDIATE", "How do budgets and alerts help control cloud costs?",
         ["they delete all resources", "they warn teams before spending exceeds set thresholds", "they block internet access", "they slow the network"], "B",
         "Budgets notify stakeholders when spending approaches limits so corrective action can be taken early."),
        ("ADVANCED", "Which set of principles forms the AWS Well-Architected Framework?",
         ["Operational Excellence, Security, Reliability, Performance Efficiency and Cost Optimization", "Speed, Memory and Storage only", "a single design pattern", "one cloud provider only"], "A",
         "The five pillars guide architects in building secure, reliable and cost-efficient systems."),
        ("ADVANCED", "How should capacity be planned for a workload with a stable base and seasonal spikes?",
         ["reserve everything at peak", "buy nothing and hope", "run only spot instances", "use reserved capacity for the base and on-demand or spot for the spikes"], "B",
         "Reserving the predictable base and flexing the spikes with on-demand or spot keeps cost low and availability high."),
        ("ADVANCED", "Which architecture provides the lowest recovery time for a globally distributed application?",
         ["a single region with nightly backups", "one instance in one AZ", "active-active multi-region with automatic failover", "manual restoration from tape"], "C",
         "Active-active deployment serves traffic from multiple regions so failover is immediate when one region fails."),
        ("ADVANCED", "What is chaos engineering?",
         ["deleting the database by accident", "a compliance rule", "a backup strategy", "deliberately injecting failures in production to test resilience"], "D",
         "Chaos engineering intentionally introduces failures so teams discover and fix weaknesses before real outages."),
        ("ADVANCED", "For a workload with highly unpredictable, short-lived spikes, which compute choice usually offers the lowest cost?",
         ["serverless functions that scale to zero between invocations", "always-on large instances", "a dedicated physical server", "a permanently running cluster"], "A",
         "Serverless scales to zero when idle, so there is no cost between bursts of activity."),
        ("ADVANCED", "What is an error budget in SRE?",
         ["the cost of errors", "the allowed amount of downtime defined by a reliability target", "a security policy", "the number of developers"], "B",
         "An error budget is the acceptable failure margin implied by an SLO, guiding when to release versus focus on stability."),
        ("ADVANCED", "Which technique most directly reduces data egress costs for a media-heavy global application?",
         ["removing all caches", "streaming from a single origin", "caching content at edge locations with a CDN", "increasing instance sizes"], "C",
         "A CDN serves the bulk of requests from edge caches, drastically cutting origin egress traffic and cost."),
        ("ADVANCED", "Which migration strategy incrementally replaces parts of a legacy monolith with microservices?",
         ["a full rewrite overnight", "switching to a database without code", "disabling the legacy app", "the strangler fig pattern"], "D",
         "The strangler fig pattern gradually routes functionality to new services until the monolith is replaced."),
        ("ADVANCED", "What is the difference between showback and chargeback in FinOps?",
         ["showback reports costs to teams without billing them, while chargeback bills them directly", "they are the same thing", "showback deletes cost data", "chargeback hides costs"], "A",
         "Showback increases cost awareness by reporting, whereas chargeback actually transfers the cost to the consuming team."),
        ("ADVANCED", "An organization defines RPO as 15 minutes for its core database. What must the architecture guarantee?",
         ["the database must be restored in 15 minutes", "no more than 15 minutes of data can be lost in a disaster", "15 backups must exist", "the RTO is also 15 minutes"], "B",
         "RPO is the maximum acceptable data loss, so replication or frequent backups must keep losses within 15 minutes."),
    ],
}
