# -*- coding: utf-8 -*-
"""
Question bank for subject 45: CS101 - Fundamentals of Computing.
Category: Core Computer Science & Emerging Technologies.
Semester: 1.

Topics:
  221: Introduction to Computing
  222: Software & Operating Basics
  223: Internet & Web Basics
  224: Data Representation
  225: Computing Trends & Careers

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    221: [
        ("BEGINNER", "What is a computer?",
         ["An electronic device that processes data according to instructions", "A device that only stores books", "A type of television", "A calculator only"], "A",
         "A computer is an electronic machine that accepts, processes, stores, and outputs data based on programmed instructions."),
        ("BEGINNER", "Which of the following is a characteristic of a computer?",
         ["High speed and accuracy", "It cannot store data", "It never follows instructions", "It works only at night"], "A",
         "Computers process data at high speed with great accuracy and consistency."),
        ("BEGINNER", "The first generation of computers used which technology?",
         ["Vacuum tubes", "Transistors", "Integrated circuits", "Microprocessors"], "A",
         "First-generation computers relied on vacuum tubes for logic circuitry."),
        ("BEGINNER", "Which generation of computers introduced the microprocessor?",
         ["Fourth generation", "First generation", "Second generation", "Third generation"], "A",
         "Fourth-generation computers used microprocessors containing thousands of transistors on one chip."),
        ("BEGINNER", "What does the term 'hardware' refer to?",
         ["The physical components of a computer", "The programs that run on a computer", "Data files", "Internet connections"], "A",
         "Hardware is the tangible physical equipment of a computer system."),
        ("BEGINNER", "What does 'software' refer to?",
         ["The programs and instructions executed by a computer", "The physical chips", "The keyboard and mouse", "The power supply"], "A",
         "Software consists of programs and data that tell the hardware what to do."),
        ("BEGINNER", "Which of these is a computing device?",
         ["Smartphone", "Refrigerator only", "Television only", "Chair"], "A",
         "Smartphones are powerful computing devices; the others are not computers."),
        ("BEGINNER", "What is data?",
         ["Raw facts and figures without meaning", "Processed information", "A type of software", "A hardware device"], "A",
         "Data is raw, unprocessed facts that become information once organized and interpreted."),
        ("BEGINNER", "What is information?",
         ["Data that has been processed and given meaning", "Raw unprocessed facts", "A computer part", "A network cable"], "A",
         "Information results from processing data into a meaningful, useful form."),
        ("BEGINNER", "Which of the following is an example of a supercomputer?",
         ["A system used for large-scale scientific simulation", "A personal laptop", "A smartwatch", "A router"], "A",
         "Supercomputers perform extremely large and fast computations for science and research."),
        ("INTERMEDIATE", "What is the primary difference between a mainframe and a personal computer?",
         ["Mainframes handle massive concurrent workloads for many users", "Mainframes are smaller", "Personal computers never fail", "Mainframes cannot store data"], "A",
         "Mainframes are designed for high-throughput, multi-user enterprise processing."),
        ("INTERMEDIATE", "Which type of computer is designed to perform a specific dedicated function?",
         ["Embedded computer", "General-purpose computer", "Mainframe", "Personal computer"], "A",
         "Embedded systems run dedicated functions inside devices such as cars and appliances."),
        ("INTERMEDIATE", "In the evolution of computers, the second generation replaced vacuum tubes with:",
         ["Transistors", "Microprocessors", "Vacuum tubes", "Integrated circuits"], "A",
         "Second-generation computers used transistors, which were smaller and more reliable."),
        ("INTERMEDIATE", "Which of the following best defines the term 'generation' of computers?",
         ["A stage in computer evolution marked by the underlying technology", "The age of the computer", "The size of the screen", "The brand of the CPU"], "A",
         "Each generation is distinguished by the technology used for logic circuits and memory."),
        ("INTERMEDIATE", "What is the role of the operating system in a computing device?",
         ["To manage hardware and software resources", "To cool the processor", "To print documents", "To charge the battery"], "A",
         "The OS coordinates hardware, runs applications, and manages resources."),
        ("INTERMEDIATE", "Which device category does a laptop belong to?",
         ["Personal computer", "Supercomputer", "Mainframe", "Embedded system"], "A",
         "Laptops are portable personal computers."),
        ("INTERMEDIATE", "The CPU is composed mainly of which two units?",
         ["Control unit and ALU", "RAM and ROM", "Keyboard and mouse", "Modem and router"], "A",
         "The CPU contains the control unit and the arithmetic logic unit."),
        ("INTERMEDIATE", "Which of the following is a characteristic of embedded systems?",
         ["They perform limited, predefined tasks", "They replace all mainframes", "They require manual programming constantly", "They have no software"], "A",
         "Embedded systems run specialized software for a narrow, fixed set of tasks."),
        ("INTERMEDIATE", "Which of these is a type of computer based on size and capability?",
         ["Microcomputer", "Electric lamp", "Desk chair", "Power cable"], "A",
         "Microcomputers, minicomputers, mainframes, and supercomputers are classes by size and power."),
        ("INTERMEDIATE", "What is the main advantage of using a computer in business?",
         ["Efficient data processing and storage", "Eliminating all employees", "Guaranteed perfect decisions", "Lower electricity bills"], "A",
         "Computers process and store large volumes of data quickly and reliably."),
        ("ADVANCED", "Which characteristic best describes the third generation of computers?",
         ["Use of integrated circuits (ICs)", "Use of vacuum tubes", "Use of transistors only", "Use of cloud storage"], "A",
         "Integrated circuits packed many transistors on chips, shrinking size and cost."),
        ("ADVANCED", "What is the fundamental limitation of a general-purpose computer?",
         ["It executes only the instructions given in its software", "It cannot store data", "It cannot communicate", "It has no memory"], "A",
         "A computer's capabilities are bounded by the programs it runs."),
        ("ADVANCED", "Which of the following represents the correct order of the data processing cycle?",
         ["Input, processing, output, storage", "Output, storage, input, processing", "Storage, output, processing, input", "Processing, input, output, storage"], "A",
         "Data flows from input, through processing, to output, with storage supporting each step."),
        ("ADVANCED", "The concept of 'stored program' means that:",
         ["Instructions are stored in memory and executed by the CPU", "Programs are stored on paper", "Only data is stored", "Programs cannot be changed"], "A",
         "The stored-program concept lets instructions reside in memory for flexible execution."),
        ("ADVANCED", "Which factor most directly drives improvements in modern computer performance?",
         ["Increasing transistor density on chips", "Larger monitors", "Heavier chassis", "Longer cables"], "A",
         "More transistors per chip enable faster, more capable processors."),
        ("ADVANCED", "What is the main purpose of a supercomputer cluster?",
         ["To combine many computers for extremely high performance computing", "To reduce the number of users", "To replace printers", "To store paper files"], "A",
         "Clusters pool resources to solve problems requiring massive computation."),
        ("ADVANCED", "Which of the following is an example of a hybrid computing device?",
         ["A tablet combining laptop and smartphone features", "A simple calculator", "A mechanical typewriter", "An abacus"], "A",
         "Hybrid devices merge capabilities of two categories, such as tablets."),
        ("ADVANCED", "Why is the ALU essential to a computer?",
         ["It performs the arithmetic and logical operations required for computation", "It stores all files", "It displays images", "It connects to the internet"], "A",
         "Arithmetic and logical operations are the core of all computation."),
        ("ADVANCED", "What does 'multitasking' allow an operating system to do?",
         ["Run multiple programs seemingly at the same time", "Run only one program", "Delete programs", "Double the RAM"], "A",
         "Multitasking shares CPU time among programs so several appear to run simultaneously."),
        ("ADVANCED", "Which of the following correctly describes a quantum computer's difference from classical computers?",
         ["It uses qubits that exploit superposition and entanglement", "It uses vacuum tubes", "It is slower by design", "It cannot compute"], "A",
         "Quantum computers process information with qubits, enabling different computational approaches."),
    ],
    222: [
        ("BEGINNER", "Which of the following is system software?",
         ["Operating system", "Word processor", "Web browser", "Game"], "A",
         "The operating system manages hardware and supports application software."),
        ("BEGINNER", "Which of the following is application software?",
         ["Spreadsheet program", "Operating system", "Device driver", "Kernel"], "A",
         "Spreadsheet applications perform user tasks such as data analysis."),
        ("BEGINNER", "What is the role of the operating system kernel?",
         ["To manage core hardware and system resources", "To create documents", "To browse the web", "To edit photos"], "A",
         "The kernel is the core of the OS that manages hardware and processes."),
        ("BEGINNER", "Which software translates high-level code into machine code?",
         ["Compiler", "Word processor", "Web browser", "Media player"], "A",
         "A compiler translates entire high-level programs into machine code."),
        ("BEGINNER", "Which of the following is an example of an operating system?",
         ["Windows", "MS Word", "Excel", "Chrome"], "A",
         "Windows is an operating system; the others are applications."),
        ("BEGINNER", "What is the purpose of a device driver?",
         ["To let the OS communicate with a hardware device", "To create presentations", "To write documents", "To play music"], "A",
         "Device drivers translate OS commands for specific hardware."),
        ("BEGINNER", "Which software type controls the computer's basic operations?",
         ["Operating system", "Game software", "Drawing app", "Calculator"], "A",
         "The operating system controls basic operations like process and memory management."),
        ("BEGINNER", "What does the term 'user interface' refer to?",
         ["The way users interact with software", "The CPU design", "The power supply", "The hard disk"], "A",
         "The user interface is the means by which users interact with a program."),
        ("BEGINNER", "Which of the following is an example of open-source software?",
         ["Linux", "Microsoft Windows", "Adobe Photoshop", "SAP"], "A",
         "Linux is open source, with source code freely available."),
        ("BEGINNER", "What is a software license?",
         ["A legal agreement governing software use", "A hardware manual", "A type of processor", "A file format"], "A",
         "A software license defines how the software may be used and distributed."),
        ("INTERMEDIATE", "What is the main function of the file manager in an OS?",
         ["To organize and manage files and folders", "To compile programs", "To draw graphics", "To scan networks"], "A",
         "File managers let users create, move, copy, and delete files and folders."),
        ("INTERMEDIATE", "Which OS component schedules processes to run on the CPU?",
         ["Process scheduler", "Web browser", "Text editor", "Antivirus"], "A",
         "The scheduler allocates CPU time among running processes."),
        ("INTERMEDIATE", "What is the primary advantage of a GUI over a CLI?",
         ["It is easier for most users to learn", "It uses fewer resources always", "It is faster to type", "It requires no operating system"], "A",
         "Graphical interfaces use icons and windows, making them more approachable."),
        ("INTERMEDIATE", "What is the role of antivirus software?",
         ["To detect and remove malicious programs", "To manage disk space only", "To speed up the internet", "To create documents"], "A",
         "Antivirus software scans for and neutralizes malware."),
        ("INTERMEDIATE", "Which of these is a type of utility software?",
         ["Disk cleanup tool", "Web browser", "Presentation app", "Email client"], "A",
         "Utility software such as disk cleanup maintains the computer system."),
        ("INTERMEDIATE", "What is the difference between system software and application software?",
         ["System software runs the computer, while applications perform user tasks", "There is no difference", "Applications run the computer", "System software is user-made"], "A",
         "System software manages the system; applications serve user needs."),
        ("INTERMEDIATE", "Which file extension typically indicates a text document?",
         [".txt", ".exe", ".jpg", ".mp3"], "A",
         "The .txt extension denotes a plain text file."),
        ("INTERMEDIATE", "What does 'installing software' mean?",
         ["Copying the program and its files to the system so it can run", "Deleting the program", "Printing the manual", "Restarting the computer"], "A",
         "Installation places the program's files and configuration on the machine."),
        ("INTERMEDIATE", "Which of the following is a function of an operating system?",
         ["Memory management", "Creating music", "Editing video", "Drawing images"], "A",
         "Memory management is a core operating system function."),
        ("INTERMEDIATE", "What is the purpose of backup software?",
         ["To copy data for recovery in case of loss", "To delete old files", "To speed up the CPU", "To play media"], "A",
         "Backups preserve data so it can be restored after loss or corruption."),
        ("ADVANCED", "Which scheduling principle ensures that no process waits indefinitely for CPU time?",
         ["Starvation-free fairness", "Random scheduling", "Priority-only scheduling", "Unlimited waiting"], "A",
         "Fair scheduling policies prevent indefinite delay for any process."),
        ("ADVANCED", "What is a virtual machine?",
         ["A software emulation of a physical computer", "A physical server", "A backup tape", "A type of printer"], "A",
         "Virtual machines emulate hardware to run operating systems in isolation."),
        ("ADVANCED", "Why do operating systems use virtual memory?",
         ["To allow programs to use more memory than physically installed", "To save disk space only", "To reduce RAM cost", "To avoid process management"], "A",
         "Virtual memory uses disk space to extend the usable address space."),
        ("ADVANCED", "Which of the following best defines a process?",
         ["A program in execution", "A file on disk", "A hardware device", "A network protocol"], "A",
         "A process is an executing instance of a program."),
        ("ADVANCED", "What is the purpose of access control in an operating system?",
         ["To restrict who can access files and resources", "To speed up boot", "To manage the clock", "To compress files"], "A",
         "Access control enforces permissions on files and system resources."),
        ("ADVANCED", "Which OS mechanism allows multiple programs to share the CPU safely?",
         ["Multitasking with process isolation", "Running one program", "Deleting processes", "Disabling interrupts"], "A",
         "Multitasking and isolation let many programs share the CPU securely."),
        ("ADVANCED", "What is the main purpose of a system call?",
         ["To request services from the operating system kernel", "To display graphics", "To open the browser", "To format text"], "A",
         "System calls are the interface between programs and the kernel."),
        ("ADVANCED", "Which of these is a responsibility of the memory manager?",
         ["Allocating and deallocating memory to processes", "Compiling programs", "Scanning for viruses", "Rendering video"], "A",
         "Memory management handles allocation, tracking, and freeing of memory."),
        ("ADVANCED", "What is the key benefit of a modular operating system design?",
         ["Components can be updated and replaced independently", "It uses more memory", "It is harder to debug", "It runs slower"], "A",
         "Modularity simplifies maintenance and feature updates."),
        ("ADVANCED", "Which of the following best describes a real-time operating system?",
         ["An OS that guarantees timely response within strict deadlines", "An OS with no kernel", "A web browser", "A game engine"], "A",
         "Real-time operating systems prioritize predictable, timely task completion."),
    ],
    223: [
        ("BEGINNER", "What is the internet?",
         ["A global network of interconnected computers", "A single website", "A type of browser", "A hardware device"], "A",
         "The internet is a worldwide network linking millions of computers."),
        ("BEGINNER", "What does a web browser do?",
         ["Displays web pages from the internet", "Creates spreadsheets", "Compiles code", "Manages databases"], "A",
         "Browsers retrieve and display web content from servers."),
        ("BEGINNER", "What is a web page?",
         ["A document displayed in a browser", "A physical paper page", "A hard disk", "A network cable"], "A",
         "A web page is a document rendered by a browser."),
        ("BEGINNER", "Which of the following is a search engine?",
         ["Google", "Microsoft Word", "Excel", "Paint"], "A",
         "Google is a search engine used to find web content."),
        ("BEGINNER", "What does e-mail allow users to do?",
         ["Send and receive electronic messages", "Print documents", "Cool the computer", "Store hardware"], "A",
         "E-mail enables sending and receiving electronic messages over a network."),
        ("BEGINNER", "What does a URL specify for a resource on the web?",
         ["The address of a resource on the web", "A type of computer", "A programming language", "A file format"], "A",
         "A URL (Uniform Resource Locator) is the web address of a resource."),
        ("BEGINNER", "Which of the following is a web browser?",
         ["Chrome", "Windows", "Linux", "Excel"], "A",
         "Chrome is a web browser; the others are operating systems or applications."),
        ("BEGINNER", "What does the 'www' in a web address stand for?",
         ["World Wide Web", "World Web Windows", "Wide World Web", "Web Web Web"], "A",
         "www stands for the World Wide Web, the collection of linked documents."),
        ("BEGINNER", "Which of the following is used to access a website?",
         ["A URL entered into a browser", "A printer", "A scanner", "A speaker"], "A",
         "Typing a URL into a browser navigates to a website."),
        ("BEGINNER", "What is an e-mail address used for?",
         ["To identify a user for sending and receiving mail", "To locate a website", "To name a computer", "To store files"], "A",
         "An e-mail address uniquely identifies a mailbox for electronic mail."),
        ("INTERMEDIATE", "Which protocol is used to view web pages securely?",
         ["HTTPS", "FTP", "SMTP", "POP"], "A",
         "HTTPS encrypts web traffic, providing secure communication between browser and server."),
        ("INTERMEDIATE", "What does HTTP stand for?",
         ["HyperText Transfer Protocol", "High Transfer Text Protocol", "HyperText Transport Process", "High-level Text Transfer Program"], "A",
         "HTTP is the protocol that transfers hypertext over the web."),
        ("INTERMEDIATE", "Which of the following is a domain name?",
         ["example.com", "192.168.1.1", "http", "index.html"], "A",
         "A domain name such as example.com names a website on the internet."),
        ("INTERMEDIATE", "What is the role of a web server?",
         ["To store and deliver web pages to clients", "To cool the internet", "To print documents", "To scan networks"], "A",
         "Web servers host content and respond to browser requests."),
        ("INTERMEDIATE", "What does a search engine do?",
         ["Finds and ranks web pages relevant to a query", "Creates websites", "Sends e-mail", "Formats documents"], "A",
         "Search engines index pages and return ranked matches for queries."),
        ("INTERMEDIATE", "Which of the following describes the term 'browsing'?",
         ["Navigating and viewing web pages", "Programming websites", "Designing circuits", "Formatting disks"], "A",
         "Browsing is the activity of navigating between web pages."),
        ("INTERMEDIATE", "What is a hyperlink?",
         ["A clickable element that navigates to another resource", "A type of cable", "A storage device", "A password"], "A",
         "Hyperlinks connect web resources and enable navigation."),
        ("INTERMEDIATE", "Which protocol handles sending e-mail?",
         ["SMTP", "FTP", "DNS", "HTTP"], "A",
         "SMTP (Simple Mail Transfer Protocol) sends e-mail messages."),
        ("INTERMEDIATE", "What is the purpose of a domain name system (DNS)?",
         ["To translate domain names into IP addresses", "To send e-mails", "To store web pages", "To format disks"], "A",
         "DNS resolves human-readable domain names to numeric IP addresses."),
        ("INTERMEDIATE", "Which of the following is a popular video-sharing platform?",
         ["YouTube", "MS Word", "Excel", "Notepad"], "A",
         "YouTube is a platform for sharing and viewing videos."),
        ("ADVANCED", "What is the main purpose of internet cookies?",
         ["To store user state and preferences for a website", "To delete browsing data", "To speed up the modem", "To protect the CPU"], "A",
         "Cookies preserve session state and user preferences across visits."),
        ("ADVANCED", "Which technology keeps a web session active between requests?",
         ["Session management via cookies or tokens", "Rebooting the server", "Using a printer", "Disabling DNS"], "A",
         "Sessions track logged-in users using cookies, tokens, or server state."),
        ("ADVANCED", "What is a web cache used for?",
         ["To store copies of content for faster subsequent access", "To delete history", "To compress the disk", "To block viruses"], "A",
         "Caching stores frequently accessed content closer to the user to reduce load."),
        ("ADVANCED", "Which of the following is a security risk when using public Wi-Fi?",
         ["Eavesdropping on unencrypted traffic", "Faster downloads", "Longer battery life", "Better graphics"], "A",
         "Public networks can expose unencrypted traffic to attackers."),
        ("ADVANCED", "What does a firewall protect against on a network?",
         ["Unauthorized access to or from a network", "Power outages", "Hard disk wear", "Screen damage"], "A",
         "Firewalls filter traffic to block unauthorized access."),
        ("ADVANCED", "Which technology allows secure remote access over the internet?",
         ["VPN (Virtual Private Network)", "A larger monitor", "A printer", "A speaker"], "A",
         "VPNs create encrypted tunnels for secure remote connections."),
        ("ADVANCED", "What is the role of an internet service provider (ISP)?",
         ["To provide internet connectivity to customers", "To build websites", "To write software", "To manufacture computers"], "A",
         "ISPs supply the connection and access to the internet."),
        ("ADVANCED", "Why is HTTPS preferred over HTTP for online payments?",
         ["It encrypts the data between browser and server", "It loads pages faster", "It uses less data", "It hides the server address"], "A",
         "HTTPS encrypts transactions, protecting sensitive data from eavesdropping."),
        ("ADVANCED", "What does a browser's incognito mode primarily provide?",
         ["Local browsing history and cookies are not saved", "Complete anonymity on the internet", "Faster internet speeds", "Stronger passwords"], "A",
         "Incognito mode avoids saving local history and cookies, though it does not hide activity from ISPs."),
        ("ADVANCED", "Which of the following is a web standard that defines page structure?",
         ["HTML", "MP3", "PNG", "ZIP"], "A",
         "HTML (HyperText Markup Language) defines the structure of web pages."),
    ],
    224: [
        ("BEGINNER", "What is ASCII used for?",
         ["To represent characters as numbers in computers", "To compress images", "To connect networks", "To store audio"], "A",
         "ASCII assigns numeric codes to characters so computers can store and transmit text."),
        ("BEGINNER", "A single byte is made up of how many bits?",
         ["8", "4", "16", "32"], "A",
         "A byte consists of exactly 8 bits."),
        ("BEGINNER", "Which number system do computers use internally?",
         ["Binary", "Decimal", "Octal", "Hexadecimal"], "A",
         "Computers store and process data in binary using bits 0 and 1."),
        ("BEGINNER", "What is a bit?",
         ["The smallest unit of data, either 0 or 1", "A byte of data", "A character", "A pixel"], "A",
         "A bit is the smallest unit of digital data, holding a single 0 or 1."),
        ("BEGINNER", "What does 1 KB represent in computing?",
         ["1024 bytes", "1000 bytes only", "100 bytes", "8 bytes"], "A",
         "In binary computing, 1 KB equals 2^10 = 1024 bytes."),
        ("BEGINNER", "Which encoding scheme can represent characters of many languages using multiple bytes?",
         ["Unicode", "ASCII only", "Binary only", "EBCDIC only"], "A",
         "Unicode provides a universal mapping of characters across many languages."),
        ("BEGINNER", "In a digital image, what is the smallest element called?",
         ["The smallest element of a digital image", "A unit of sound", "A character", "A memory cell"], "A",
         "A pixel is the smallest controllable element in a digital image."),
        ("BEGINNER", "What does 'base 2' mean in the binary number system?",
         ["It uses two digits, 0 and 1", "It uses ten digits", "It uses eight digits", "It uses sixteen digits"], "A",
         "Base 2 uses only the digits 0 and 1."),
        ("BEGINNER", "What is the binary representation of the decimal number 5?",
         ["101", "110", "100", "111"], "A",
         "5 in decimal equals 4 + 1, which is 101 in binary."),
        ("BEGINNER", "How many bits does an ASCII character typically use?",
         ["7 or 8 bits", "16 bits", "32 bits", "4 bits"], "A",
         "Standard ASCII uses 7 bits, and extended ASCII uses 8 bits."),
        ("INTERMEDIATE", "How many bytes are in 1 MB?",
         ["1024 KB or about 1 million bytes", "100 bytes", "8 bytes", "1024 bytes only"], "A",
         "1 MB equals 1024 KB, roughly one million bytes."),
        ("INTERMEDIATE", "Which format represents colors using red, green, and blue values?",
         ["RGB", "ASCII", "UTF-8", "PNG only"], "A",
         "RGB is an additive color model using red, green, and blue components."),
        ("INTERMEDIATE", "What is the purpose of UTF-8 encoding?",
         ["To represent Unicode characters in a byte-oriented format", "To compress video", "To encrypt data", "To display images"], "A",
         "UTF-8 encodes Unicode characters using variable-length byte sequences."),
        ("INTERMEDIATE", "What is the decimal value of the binary number 1100?",
         ["12", "10", "14", "8"], "A",
         "1100 = 8 + 4 = 12."),
        ("INTERMEDIATE", "Which of the following stores audio data?",
         ["MP3 file", "JPEG file", "PNG file", "TXT file"], "A",
         "MP3 is an audio compression format that stores sound."),
        ("INTERMEDIATE", "How is an image represented in a computer?",
         ["As a grid of pixels with color values", "As a sequence of sounds", "As ASCII text", "As a printed photograph"], "A",
         "Digital images are stored as a matrix of pixels, each with color data."),
        ("INTERMEDIATE", "What does the term 'sampling rate' refer to in digital audio?",
         ["The number of sound samples taken per second", "The loudness of the sound", "The file size", "The number of channels"], "A",
         "Sampling rate measures how frequently the analog sound is captured as digital samples."),
        ("INTERMEDIATE", "What is 1 GB equal to?",
         ["1024 MB", "1024 bytes", "8 bits", "100 KB"], "A",
         "1 GB equals 1024 MB in binary computing."),
        ("INTERMEDIATE", "Which of these is an uncompressed image format?",
         ["BMP", "JPEG", "MP3", "ZIP"], "A",
         "BMP stores image data without compression."),
        ("INTERMEDIATE", "What does color depth determine in an image?",
         ["The number of distinct colors each pixel can display", "The image size in pixels", "The file name", "The viewing angle"], "A",
         "Color depth (bits per pixel) determines the range of representable colors."),
        ("ADVANCED", "An 8-bit color depth can represent how many distinct colors per pixel?",
         ["256", "8", "1024", "16"], "A",
         "Eight bits give 2^8 = 256 possible values per color channel."),
        ("ADVANCED", "What is the main advantage of lossy compression for images?",
         ["Much smaller file sizes with acceptable quality loss", "Perfect reconstruction of the original", "Faster printing", "Larger color depth"], "A",
         "Lossy formats like JPEG discard detail to achieve small sizes."),
        ("ADVANCED", "Which of the following is an example of lossless compression?",
         ["ZIP file compression", "JPEG photo compression", "MP3 audio compression", "Low-bitrate video"], "A",
         "Lossless compression such as ZIP preserves all original data exactly."),
        ("ADVANCED", "A 24-bit image uses how many bytes per pixel?",
         ["3 bytes", "1 byte", "8 bytes", "24 bytes"], "A",
         "24 bits equals 3 bytes, one byte each for red, green, and blue."),
        ("ADVANCED", "What is the fundamental trade-off in data compression?",
         ["Smaller size versus quality or fidelity", "Speed versus color", "Size versus resolution only", "Lossless is always smaller"], "A",
         "Compression trades file size against the fidelity of the represented data."),
        ("ADVANCED", "Which encoding is Unicode Transformation Format designed to handle all Unicode code points?",
         ["UTF-8 and UTF-16", "ASCII", "EBCDIC", "BCD"], "A",
         "UTF-8 and UTF-16 encodings cover the complete Unicode code point space."),
        ("ADVANCED", "If a monochrome image uses 1 bit per pixel, how many colors can it show?",
         ["2", "4", "8", "256"], "A",
         "One bit per pixel represents only two values: black and white."),
        ("ADVANCED", "What does 'resolution' of a display refer to?",
         ["The number of pixels in each dimension", "The color depth", "The refresh rate only", "The brightness"], "A",
         "Resolution describes the pixel count, such as 1920 x 1080."),
        ("ADVANCED", "Why is vector graphics more scalable than bitmap graphics?",
         ["They use mathematical shapes that can be scaled without loss", "They store more pixels", "They are always smaller", "They use only one color"], "A",
         "Vector images store geometric descriptions that resize cleanly at any size."),
        ("ADVANCED", "What is the role of a codec in multimedia?",
         ["To encode and decode audio or video data", "To connect the display", "To store text", "To control the mouse"], "A",
         "Codecs compress and decompress media streams for storage and playback."),
    ],
    225: [
        ("BEGINNER", "Which technology uses artificial intelligence to understand human language?",
         ["NLP (Natural Language Processing)", "A printer", "A router", "A monitor"], "A",
         "NLP enables computers to process and understand human language."),
        ("BEGINNER", "Which of the following is a cloud computing example?",
         ["Storing files in an online drive", "Printing a document", "Using a calculator", "Charging a phone"], "A",
         "Online storage services provide cloud-based file storage."),
        ("BEGINNER", "What is an IoT device?",
         ["A device connected to the internet that exchanges data", "A device that cannot connect", "A paper notebook", "A power socket only"], "A",
         "IoT (Internet of Things) devices connect to networks to share and receive data."),
        ("BEGINNER", "Which of the following is a career in information technology?",
         ["Software developer", "Chef", "Carpenter", "Nurse"], "A",
         "Software development is a core IT career."),
        ("BEGINNER", "What is artificial intelligence?",
         ["Machines performing tasks that normally require human intelligence", "Manual data entry", "A type of keyboard", "A spreadsheet"], "A",
         "AI systems mimic human cognitive functions such as learning and problem solving."),
        ("BEGINNER", "Which of the following is a popular cloud platform?",
         ["AWS (Amazon Web Services)", "Microsoft Word", "Photoshop", "Notepad"], "A",
         "AWS is a leading cloud computing platform."),
        ("BEGINNER", "What does 'digital transformation' mean?",
         ["Using digital technology to change business operations", "Digitizing paper by hand", "Replacing all computers", "Deleting data"], "A",
         "Digital transformation modernizes processes with digital technologies."),
        ("BEGINNER", "Which of the following is an example of automation?",
         ["A program that processes invoices automatically", "Typing invoices by hand", "Printing invoices once", "Mailing invoices"], "A",
         "Automation uses software to perform repetitive tasks without human effort."),
        ("BEGINNER", "What is the role of a data analyst?",
         ["To interpret data to support decisions", "To repair hardware only", "To design buildings", "To teach math"], "A",
         "Data analysts examine and interpret data to inform decision-making."),
        ("BEGINNER", "Which technology is used for secure, decentralized records?",
         ["Blockchain", "A calculator", "A scanner", "A printer"], "A",
         "Blockchain is a distributed ledger technology used for secure records."),
        ("INTERMEDIATE", "What is the primary purpose of machine learning?",
         ["To let systems learn patterns from data without explicit programming", "To replace all hardware", "To type faster", "To format documents"], "A",
         "Machine learning builds models that learn from data to make predictions."),
        ("INTERMEDIATE", "Which career focuses on protecting systems from cyber threats?",
         ["Cybersecurity analyst", "Graphic designer", "Librarian", "Translator"], "A",
         "Cybersecurity professionals defend systems against attacks."),
        ("INTERMEDIATE", "What is a 'smart home' example of?",
         ["IoT application", "Manual labor", "Traditional wiring", "Paper records"], "A",
         "Smart homes use connected IoT devices for automation."),
        ("INTERMEDIATE", "Which of the following best describes cloud storage?",
         ["Storing data on remote servers accessed via the internet", "Storing data on paper", "Storing data only in RAM", "Storing data on floppy disks"], "A",
         "Cloud storage keeps data on internet-accessible remote servers."),
        ("INTERMEDIATE", "What is big data characterized by?",
         ["Volume, velocity, and variety", "Small size and low speed", "Single type of data", "No storage needs"], "A",
         "Big data is defined by the three Vs: volume, velocity, and variety."),
        ("INTERMEDIATE", "Which technology connects physical devices to the internet?",
         ["Internet of Things (IoT)", "A printer cable", "A paper map", "A fax machine"], "A",
         "IoT links physical devices to the internet for data exchange."),
        ("INTERMEDIATE", "What is the role of a cloud engineer?",
         ["To design and manage cloud infrastructure", "To design furniture", "To teach accounting", "To repair roads"], "A",
         "Cloud engineers build and maintain cloud-based systems."),
        ("INTERMEDIATE", "Which of the following is a key concern with AI systems?",
         ["Bias in the data and decisions", "They run too slowly", "They cannot learn", "They use too little power"], "A",
         "AI can inherit bias from training data, raising fairness concerns."),
        ("INTERMEDIATE", "What does 'work from anywhere' commonly depend on?",
         ["Cloud and collaboration technologies", "Paper filing", "Fax machines", "Standalone computers only"], "A",
         "Remote work relies on cloud services and online collaboration tools."),
        ("INTERMEDIATE", "Which emerging field focuses on teaching machines to make decisions?",
         ["Artificial intelligence", "Bookkeeping", "Plumbing", "Carpentry"], "A",
         "AI focuses on machines that perform intelligent decision-making."),
        ("ADVANCED", "What is the primary benefit of serverless computing?",
         ["Scaling and billing are handled automatically per usage", "It requires physical servers on site", "It eliminates all code", "It is slower by design"], "A",
         "Serverless platforms automatically scale and bill by actual usage."),
        ("ADVANCED", "Which of the following is a challenge in adopting AI in industry?",
         ["Data quality, explainability, and regulation", "Too little data", "No available hardware", "Zero cost"], "A",
         "AI adoption faces challenges with data quality, explainable decisions, and regulations."),
        ("ADVANCED", "What is edge computing primarily about?",
         ["Processing data near the source instead of in distant data centers", "Storing everything in the cloud", "Using only mainframes", "Eliminating networks"], "A",
         "Edge computing reduces latency by processing data close to its origin."),
        ("ADVANCED", "Which skill is most important for a DevOps engineer?",
         ["Automation and collaboration across development and operations", "Only hardware repair", "Only graphic design", "Only typing speed"], "A",
         "DevOps combines automation with collaboration to deliver software reliably."),
        ("ADVANCED", "What does 'digital ethics' primarily address?",
         ["Responsible and fair use of technology", "Speeding up processors", "Reducing file sizes", "Improving monitor colors"], "A",
         "Digital ethics examines the moral implications of technology use."),
        ("ADVANCED", "Which trend most likely defines the future of computing?",
         ["AI, edge computing, and cloud integration", "Return to manual systems", "Smaller paper records", "Fewer connected devices"], "A",
         "Future computing integrates AI, edge, and cloud technologies."),
        ("ADVANCED", "What is the main role of a data scientist?",
         ["To extract insights from large datasets using statistics and ML", "To repair computers", "To design logos", "To manage schedules"], "A",
         "Data scientists combine statistics, programming, and domain knowledge to extract insights."),
        ("ADVANCED", "Which concern is central to AI-powered automation in workplaces?",
         ["Job displacement and retraining needs", "Fewer computers", "Slower internet", "Higher paper use"], "A",
         "Automation raises concerns about job displacement and the need for retraining."),
        ("ADVANCED", "What is the purpose of sustainability in computing (green IT)?",
         ["To reduce energy use and environmental impact", "To increase electricity bills", "To make computers heavier", "To use more paper"], "A",
         "Green IT minimizes computing's environmental footprint."),
        ("ADVANCED", "Which emerging technology is expected to enable immersive virtual experiences?",
         ["AR/VR and the metaverse", "Fax machines", "Paper maps", "Typewriters"], "A",
         "AR/VR and metaverse platforms create immersive digital experiences."),
    ],
}
