# -*- coding: utf-8 -*-
"""
Question bank for subject 8 - DBMS103 - MySQL (Category: Database Management).

Topics:
  36: MySQL Data Types & Tables
  37: MySQL Queries & Constraints
  38: Stored Procedures & Functions
  39: Triggers & Views
  40: MySQL Performance Tuning

Each topic has exactly 30 questions: 10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED.
"""

QUESTIONS = {
    36: [
        ("BEGINNER", "Which MySQL data type is used to store whole numbers?",
         ["INT", "VARCHAR", "DATETIME", "DECIMAL"], "A",
         "INT is the numeric data type that stores whole (integer) numbers, while VARCHAR, DATETIME and DECIMAL are not integer types."),
        ("BEGINNER", "Which data type stores variable-length character strings in MySQL?",
         ["CHAR", "VARCHAR", "TEXT FIXED", "BLOB"], "B",
         "VARCHAR stores variable-length character data and only uses as much storage as the string actually needs."),
        ("BEGINNER", "What is the default storage engine for MySQL tables in modern versions (5.5 and later)?",
         ["MyISAM", "MEMORY", "InnoDB", "ARCHIVE"], "C",
         "InnoDB became the default storage engine in MySQL 5.5 and offers transactions and row-level locking."),
        ("BEGINNER", "What does AUTO_INCREMENT do to a column?",
         ["It stores only dates", "It compresses the column", "It restricts values to even numbers",
          "It automatically generates a unique integer for each new row"], "D",
         "AUTO_INCREMENT assigns a sequential unique integer automatically when no explicit value is provided for the column."),
        ("BEGINNER", "Which data type is best for a fixed-length character field such as a 10-character code?",
         ["VARCHAR", "CHAR", "TEXT", "ENUM"], "B",
         "CHAR is a fixed-length type, so a CHAR(10) column always reserves 10 characters regardless of the stored value."),
        ("BEGINNER", "Which modifier prevents a numeric column from accepting negative values?",
         ["SIGNED", "UNSIGNED", "ZEROFILL", "FIXED"], "B",
         "UNSIGNED tells MySQL that the column may only hold non-negative numbers, which also doubles the upper positive range."),
        ("BEGINNER", "Which data type stores only the date portion with no time component?",
         ["DATETIME", "TIME", "DATE", "TIMESTAMP"], "C",
         "DATE stores values such as '2026-08-07' and contains neither a time-of-day nor a timezone component."),
        ("BEGINNER", "What does DECIMAL(10,2) represent in a column definition?",
         ["Ten integer digits and two decimal digits", "Ten decimal digits and two integer digits", "A 10-byte binary string",
          "Ten characters with two leading spaces"], "A",
         "DECIMAL(10,2) means the column can store up to 10 total digits with exactly 2 digits after the decimal point."),
        ("BEGINNER", "Which clause in a CREATE TABLE statement names the column that becomes the primary key?",
         ["CONSTRAINT", "KEY", "FOREIGN KEY", "PRIMARY KEY"], "D",
         "PRIMARY KEY is the clause that designates one or more columns as the unique identifier for each row."),
        ("BEGINNER", "Which data type stores both date and time values such as '2026-08-07 14:30:00'?",
         ["DATETIME", "DATE", "TIME", "YEAR"], "A",
         "DATETIME holds both a calendar date and a time of day, making it suitable for event timestamps without timezone conversion."),
        ("INTERMEDIATE", "What is the main difference between CHAR(10) and VARCHAR(10) in terms of storage?",
         ["VARCHAR stores data in binary format", "CHAR pads values with spaces to a fixed length while VARCHAR stores only the actual length",
          "CHAR can store up to 10 megabytes", "VARCHAR cannot be part of an index"], "B",
         "CHAR reserves the full declared width and pads shorter values with trailing spaces, while VARCHAR uses only the bytes actually needed."),
        ("INTERMEDIATE", "Which SQL statement would you use to add a new column to an existing table?",
         ["CREATE TABLE", "MODIFY COLUMN", "ALTER TABLE", "CHANGE TABLE"], "C",
         "ALTER TABLE is the statement that changes an existing table structure, for example adding, dropping or modifying columns."),
        ("INTERMEDIATE", "Why does INT UNSIGNED allow a larger maximum positive value than INT SIGNED?",
         ["It stores data in fewer bytes", "It uses two bytes less overhead",
          "It drops the sign bit, so the freed bit is available for a larger magnitude",
          "It uses compressed arithmetic"], "C",
         "Because the sign bit no longer has to encode a plus or minus, an unsigned integer can represent roughly twice the positive range of a signed one."),
        ("INTERMEDIATE", "How does TIMESTAMP differ from DATETIME regarding time zones?",
         ["TIMESTAMP is converted from and to UTC based on the session time zone, while DATETIME stores the literal value",
          "TIMESTAMP ignores time entirely", "DATETIME is always stored in UTC",
          "TIMESTAMP can only store years up to 1999"], "A",
         "TIMESTAMP values are stored internally in UTC and converted to the session time zone on retrieval, whereas DATETIME keeps whatever value was inserted."),
        ("INTERMEDIATE", "Which of these is a valid reason to use TEXT instead of VARCHAR?",
         ["TEXT columns are always faster", "The content may exceed the VARCHAR limit of 65,535 bytes",
          "VARCHAR cannot store letters", "TEXT is the only type that supports indexing"], "B",
         "VARCHAR values are limited to 65,535 bytes in total row context, while TEXT (TINYTEXT, TEXT, MEDIUMTEXT, LONGTEXT) supports larger payloads."),
        ("INTERMEDIATE", "What does an ENUM column do in MySQL?",
         ["It stores binary large objects", "It lets the column take only one of a predefined list of string values",
          "It automatically encrypts data", "It generates random numbers"], "B",
         "ENUM restricts a column to a specific set of allowed string values, and any attempt to store an unlisted value is rejected or ignored depending on SQL mode."),
        ("INTERMEDIATE", "How do you create a table whose primary key is composed of two columns?",
         ["Add a PRIMARY KEY constraint listing both column names", "Use two AUTO_INCREMENT columns",
          "Make the table use the MEMORY engine", "Define a separate table for the key"], "A",
         "A composite primary key is declared with a table-level constraint such as PRIMARY KEY (col1, col2) and requires that the combination of values is unique."),
        ("INTERMEDIATE", "Which numeric type should you choose for accurate monetary calculations?",
         ["FLOAT", "DOUBLE", "DECIMAL", "INT"], "C",
         "DECIMAL is an exact fixed-point type, so it avoids the rounding errors that binary floating-point types such as FLOAT and DOUBLE introduce."),
        ("INTERMEDIATE", "How do you set a DATETIME column to record the current time when a row is inserted?",
         ["Use DEFAULT CURRENT_TIMESTAMP", "Declare it UNSIGNED", "Give it a CHECK constraint",
          "Set the storage engine to CSV"], "A",
         "DEFAULT CURRENT_TIMESTAMP fills the column with the current timestamp at insert time automatically, and can be combined with ON UPDATE for changes."),
        ("INTERMEDIATE", "What happens to an existing table when you run ALTER TABLE ... DROP COLUMN col_name?",
         ["The column and all of its data are removed from the table",
          "Only the column definition is kept", "The table is renamed",
          "The column is moved to another table"], "A",
         "DROP COLUMN permanently removes the column and its stored values from the table, so any data in that column is lost."),
        ("ADVANCED", "Which storage engine is appropriate for a table that needs ACID transactions and foreign key enforcement?",
         ["MyISAM", "InnoDB", "MEMORY", "MERGE"], "B",
         "InnoDB supports transactions, row-level locking and foreign keys, whereas MyISAM does not provide ACID guarantees or enforce referential integrity."),
        ("ADVANCED", "Why is MyISAM sometimes chosen over InnoDB for read-heavy analytics tables?",
         ["It enforces foreign keys better", "It uses row-level locking for writes",
          "It is generally faster for full-table scans and offers compressed read-only tables",
          "It supports transactions"], "C",
         "MyISAM's table-level locking and compact storage can be faster for bulk reads and static data, at the cost of losing transactions and foreign keys."),
        ("ADVANCED", "What is the significance of the display width in INT(11) in older MySQL versions?",
         ["It limits the value to 11 digits", "It is the number of bytes stored",
          "It only affects display padding and does not restrict the stored value's range",
          "It selects the floating-point format"], "C",
         "The (11) in INT(11) was only a display width hint used with ZEROFILL and never limited the numeric range, and it is deprecated in MySQL 8.0."),
        ("ADVANCED", "Why can using VARCHAR(200) instead of a smaller size help performance in a very wide table?",
         ["VARCHAR consumes no storage at all", "Wide variable columns make rows larger and can push row size over limits or waste space in buffers",
          "VARCHAR is a native binary type", "Larger sizes enable compression automatically"], "B",
         "Excessive VARCHAR lengths can inflate row size, consume more memory in the buffer pool and reduce how many rows fit in an index page."),
        ("ADVANCED", "What happens when you insert a value that exceeds an UNSIGNED INT maximum in strict SQL mode?",
         ["The value is silently truncated to the maximum", "MySQL rounds to the nearest multiple of ten",
          "An error is raised and the statement fails",
          "The column is automatically changed to BIGINT"], "C",
         "In strict mode, out-of-range numeric values cause an error rather than being clamped, preventing silent data corruption."),
        ("ADVANCED", "Which MySQL data type is designed to store and query JSON documents directly?",
         ["BLOB", "JSON", "XML", "VARBINARY"], "B",
         "The JSON type validates stored JSON, stores it in a binary format and supports JSON path queries and indexes on generated columns."),
        ("ADVANCED", "What is a generated (virtual) column in MySQL?",
         ["A column stored only on disk in a separate file",
          "A column whose value is computed from an expression and may be indexed",
          "A column that randomly changes on each read",
          "A synonym for an ENUM column"], "B",
         "Generated columns compute their value from a deterministic expression, and VIRTUAL generated columns can be indexed to speed up JSON and derived-value lookups."),
        ("ADVANCED", "Why should a VARCHAR column that stores text with emojis use the utf8mb4 character set?",
         ["utf8mb4 is the only character set that exists", "It is faster than latin1 for numbers",
          "utf8mb4 supports supplementary characters including emojis, which plain utf8 (utf8mb3) cannot represent",
          "utf8mb4 halves the row size"], "C",
         "Emoji characters lie outside the Basic Multilingual Plane, so they require the 4-byte utf8mb4 encoding instead of the 3-byte utf8mb3."),
        ("ADVANCED", "In InnoDB, what is the practical benefit of defining the primary key explicitly instead of relying on an implicit one?",
         ["Explicit primary keys give the clustered index a logical order, improving point lookups and range scans",
          "Explicit primary keys disable the buffer pool", "Explicit primary keys allow table-level locking",
          "Explicit primary keys are required to use MyISAM"], "A",
         "InnoDB clusters data by the primary key, so an explicit, small and stable primary key yields efficient B-tree access and avoids hidden overhead."),
        ("ADVANCED", "Why might a very long VARCHAR column exceed the maximum row size of a table?",
         ["VARCHAR always counts its full declared length against the 65,535-byte row limit",
          "VARCHAR is stored in a separate table automatically",
          "VARCHAR cannot exceed 100 bytes", "VARCHAR requires two columns per value"], "A",
         "The declared VARCHAR length contributes to the row size limit even if the actual stored strings are short, so declaring several huge VARCHAR columns can make the table uncreatable."),
    ],

    37: [
        ("BEGINNER", "Which keyword retrieves every column from a table?",
         ["SELECT *", "SHOW ALL", "GET *", "USE *"], "A",
         "The asterisk in SELECT * is a wildcard that returns all columns of the selected table."),
        ("BEGINNER", "Which clause filters which rows a query returns?",
         ["GROUP BY", "WHERE", "ORDER BY", "HAVING"], "B",
         "WHERE evaluates a condition for each row and only rows matching the condition are included in the result."),
        ("BEGINNER", "Which constraint guarantees that a column value is both unique and never NULL?",
         ["DEFAULT", "CHECK", "PRIMARY KEY", "INDEX"], "C",
         "A PRIMARY KEY enforces uniqueness and implicitly disallows NULL values, uniquely identifying each row."),
        ("BEGINNER", "Which keyword sorts the rows of a result set?",
         ["SORT", "ORDER BY", "GROUP BY", "SORT BY"], "B",
         "ORDER BY sorts the returned rows by one or more columns, ascending by default."),
        ("BEGINNER", "What does the NOT NULL constraint on a column prevent?",
         ["Duplicate values", "Values larger than 255", "Inserting a row without a value for that column", "Indexed access"], "C",
         "NOT NULL rejects any insert or update that would leave the column without a value, so the column must always contain data."),
        ("BEGINNER", "What is a foreign key?",
         ["A key that encrypts the table", "A column that links a row to a row in another table to enforce referential integrity",
          "A key that compresses the data", "A synonym for the primary key"], "B",
         "A foreign key references the primary key of another table, ensuring that values in the column match an existing row in that table."),
        ("BEGINNER", "Which clause groups rows that share the same values of one or more columns?",
         ["GROUP BY", "WHERE", "LIMIT", "JOIN"], "A",
         "GROUP BY collapses rows with equal column values into groups, which is commonly used with aggregate functions such as COUNT."),
        ("BEGINNER", "What does LIMIT 5 do in a SELECT statement?",
         ["Returns at most 5 rows", "Returns rows 5 through 10", "Sorts 5 rows", "Deletes 5 rows"], "A",
         "LIMIT restricts the number of rows returned by the query to the specified count, here a maximum of 5."),
        ("BEGINNER", "Which operator lets you test whether a value is present in a given list?",
         ["BETWEEN", "IN", "LIKE", "EXISTS"], "B",
         "IN checks membership in a list, for example WHERE status IN ('active','pending')."),
        ("BEGINNER", "Which keyword removes a whole table including its structure from the database?",
         ["DELETE FROM", "DROP TABLE", "TRUNCATE TABLE", "REMOVE TABLE"], "B",
         "DROP TABLE deletes the table definition and all of its data, while DELETE and TRUNCATE only remove the rows."),
        ("INTERMEDIATE", "When is a DEFAULT constraint applied to a column?",
         ["When the table is created only", "When no explicit value is supplied for that column in an INSERT",
          "When the column is indexed", "When a NULL is explicitly inserted"], "B",
         "The DEFAULT value is used automatically whenever an INSERT does not provide a value for the column."),
        ("INTERMEDIATE", "What is the difference between WHERE and HAVING in a grouped query?",
         ["They are interchangeable", "WHERE filters individual rows before grouping, while HAVING filters groups after grouping",
          "HAVING runs before WHERE", "WHERE only works with indexed columns"], "B",
         "WHERE discards rows before GROUP BY runs, whereas HAVING filters the resulting groups, which is why it can reference aggregate results."),
        ("INTERMEDIATE", "What does ON DELETE CASCADE do for a foreign key?",
         ["It prevents deletion of the parent row", "It automatically deletes the referencing child rows when the parent row is deleted",
          "It renames the parent table", "It locks the parent table"], "B",
         "ON DELETE CASCADE propagates a parent deletion to child rows, deleting them automatically so no orphaned references remain."),
        ("INTERMEDIATE", "Which statement correctly creates a table with a two-column composite primary key?",
         ["CREATE TABLE t (a INT, b INT, PRIMARY KEY (a,b));",
          "CREATE TABLE t (a INT, b INT) WITH TWO KEYS;",
          "CREATE TABLE t (a INT PRIMARY KEY, b INT PRIMARY KEY);",
          "CREATE TABLE t (a INT, b INT, KEY b);"], "A",
         "A table-level PRIMARY KEY (a, b) constraint defines the pair of columns as the composite key, and only the whole pair must be unique."),
        ("INTERMEDIATE", "What is the effect of a UNIQUE constraint on a column that also allows NULLs?",
         ["NULLs are not allowed at all", "It rejects all values",
          "Multiple rows may hold NULL, but every non-NULL value must be distinct",
          "It turns the column into a primary key"], "C",
         "A UNIQUE constraint permits several NULL values (in MySQL) while guaranteeing that all concrete non-NULL values are unique."),
        ("INTERMEDIATE", "Which scenario would benefit from a CHECK constraint?",
         ["Restricting a rating column to values between 1 and 5",
          "Speeding up a SELECT with ORDER BY", "Auto-generating primary keys",
          "Storing binary images"], "A",
         "CHECK enforces a boolean condition on column values, such as rating BETWEEN 1 AND 5, and rejects inserts that violate it in MySQL 8."),
        ("INTERMEDIATE", "How would you return the three highest-priced products from the products table?",
         ["SELECT * FROM products ORDER BY price DESC LIMIT 3;",
          "SELECT * FROM products LIMIT 3 ORDER BY price;",
          "SELECT * FROM products WHERE MAX(price);",
          "SELECT * FROM products GROUP BY price LIMIT 3;"], "A",
         "ORDER BY price DESC sorts by price from highest to lowest and LIMIT 3 keeps only the top three rows."),
        ("INTERMEDIATE", "What is the difference between DELETE FROM t and TRUNCATE TABLE t?",
         ["DELETE removes the table structure, TRUNCATE keeps it", "TRUNCATE cannot be used on tables",
          "DELETE deletes rows one by one and fires triggers, while TRUNCATE quickly removes all rows and resets AUTO_INCREMENT",
          "They are identical in every way"], "C",
         "DELETE processes each row (running triggers) and can be rolled back, whereas TRUNCATE drops and recreates the storage quickly and resets the auto-increment counter."),
        ("INTERMEDIATE", "Which query returns each department name together with the number of employees in it?",
         ["SELECT dept, COUNT(*) FROM emp GROUP BY dept;",
          "SELECT dept, COUNT(*) FROM emp WHERE COUNT(*) > 0;",
          "SELECT dept, SUM(emp) FROM emp;",
          "SELECT COUNT(dept) FROM emp;"], "A",
         "GROUP BY dept groups employees per department and COUNT(*) counts the rows in each group, giving the employee total per department."),
        ("INTERMEDIATE", "Why is it a good idea to define an index on a foreign key column?",
         ["Indexes are required for every column", "It speeds up the lookups and join operations that use the foreign key",
          "It prevents NULLs in the column", "It automatically enforces the constraint"], "B",
         "The foreign key is used to look up matching rows in the parent table, and an index on it avoids full table scans during joins and constraint checks."),
        ("ADVANCED", "You run INSERT INTO t VALUES (1,2) and the primary key 1 already exists. Which statement updates the existing row instead of failing?",
         ["INSERT OR REPLACE", "INSERT INTO t VALUES (1,2) ON DUPLICATE KEY UPDATE b = 2;",
          "UPDATE ... INTO t", "MERGE VALUES (1,2);"], "B",
         "INSERT ... ON DUPLICATE KEY UPDATE detects the primary key or unique constraint conflict and performs the specified update instead of raising an error."),
        ("ADVANCED", "In MySQL 8, where does CHECK constraint validation actually occur for INSERT and UPDATE statements?",
         ["In the client application", "In the storage engine only", "In the MySQL server when the statement is executed",
          "During index defragmentation"], "C",
         "MySQL 8.0.16 and later enforce CHECK constraints in the server engine layer for both InnoDB and MyISAM, rejecting rows that fail the condition."),
        ("ADVANCED", "Which query lists departments having more than 50 employees?",
         ["SELECT dept, COUNT(*) FROM emp WHERE COUNT(*) > 50 GROUP BY dept;",
          "SELECT dept FROM emp GROUP BY dept HAVING COUNT(*) > 50;",
          "SELECT dept FROM emp HAVING dept > 50;",
          "SELECT dept FROM emp WHERE SUM(*) > 50;"], "B",
         "HAVING filters groups after aggregation, so COUNT(*) > 50 correctly selects departments whose employee count exceeds 50."),
        ("ADVANCED", "What is the effect of ON UPDATE CASCADE on a child table when a parent key value changes?",
         ["The child rows are deleted", "The child foreign key values automatically change to match the new parent value",
          "The update is rejected", "The child table is locked forever"], "B",
         "ON UPDATE CASCADE propagates the changed parent key value to every referencing child row, keeping referential integrity intact."),
        ("ADVANCED", "Which statement is valid for deleting rows from two related tables in a single DELETE statement?",
         ["DELETE a, b FROM a JOIN b ON a.id = b.aid WHERE a.date < '2020-01-01';",
          "DELETE FROM a AND b WHERE date < '2020-01-01';",
          "TRUNCATE a, b WHERE a.id = b.aid;",
          "DELETE a.id, b.id FROM a;"], "A",
         "MySQL supports multi-table DELETE with a join, letting one statement remove matching rows from both tables using the join condition."),
        ("ADVANCED", "A self-referencing foreign key is used to model which common scenario?",
         ["A table storing employee managers where the manager is also an employee in the same table",
          "Encrypting passwords", "Full-text search on documents",
          "Storing temporal versioning"], "A",
         "Self-referencing foreign keys point back at the same table's primary key, which is the standard way to model hierarchical data such as employee-manager relations."),
        ("ADVANCED", "Why might an index that exactly matches the WHERE clause columns still not be used by the optimizer?",
         ["Indexes can never be used", "Statistics may be outdated, or the optimizer estimates that a full scan is cheaper for the row count",
          "WHERE clauses disable indexes entirely", "Indexes only work on DATE columns"], "B",
         "The optimizer relies on table statistics and cost estimates, so it may skip an index when a scan is projected to be cheaper or when stats are stale."),
        ("ADVANCED", "What problem can a foreign key constraint with NO ACTION (the default RESTRICT behavior) cause?",
         ["It allows orphaned rows", "It blocks deleting a parent row that still has referencing children, which may require deleting children first",
          "It drops the parent row silently", "It changes column data types automatically"], "B",
         "RESTRICT/NO ACTION rejects the parent deletion when referencing rows exist, so you must remove or update the child rows before deleting the parent."),
        ("ADVANCED", "Which query pattern correctly uses a correlated subquery to find employees earning more than their department average?",
         ["SELECT * FROM emp e WHERE salary > (SELECT AVG(salary) FROM emp d WHERE d.dept = e.dept);",
          "SELECT * FROM emp WHERE salary > AVG(salary);",
          "SELECT * FROM emp GROUP BY dept HAVING salary > AVG(salary);",
          "SELECT dept FROM emp WHERE dept > AVG(salary);"], "A",
         "The correlated subquery recomputes the average for each employee's own department, so the outer WHERE compares against the right baseline."),
        ("ADVANCED", "You need a column that auto-fills with the string 'NEW' until an explicit value arrives. Which definition achieves this?",
         ["status VARCHAR(10) DEFAULT 'NEW'", "status VARCHAR(10) NOT NULL AUTO", "status VARCHAR(10) WITH VALUE 'NEW'",
          "status VARCHAR(10) CHECK status = 'NEW'"], "A",
         "DEFAULT 'NEW' supplies the value for rows that omit it, while an explicit insert value overrides the default."),
    ],

    38: [
        ("BEGINNER", "Which statement is used to create a stored procedure in MySQL?",
         ["CREATE PROCEDURE", "MAKE PROCEDURE", "DEFINE FUNCTION", "CREATE ROUTINE"], "A",
         "CREATE PROCEDURE defines a new stored procedure with a name, optional parameters and a body."),
        ("BEGINNER", "Why is DELIMITER used when creating a stored procedure in the mysql client?",
         ["To change the statement delimiter so semicolons inside the procedure body are not treated as end-of-statement",
          "To encrypt the procedure", "To limit the number of parameters",
          "To name the database"], "A",
         "Because the procedure body contains semicolons, the client delimiter is temporarily changed so the whole body is sent as one statement."),
        ("BEGINNER", "Which parameter mode passes a value INTO a stored procedure but cannot change it for the caller?",
         ["IN", "OUT", "INOUT", "VAR"], "A",
         "IN parameters are read-only inside the procedure, and changes to them are not visible to the caller."),
        ("BEGINNER", "Which keyword makes a stored function return a value?",
         ["EXIT", "RETURN", "OUTPUT", "SELECT"], "B",
         "RETURN immediately returns a scalar value from a stored function and is required in every function."),
        ("BEGINNER", "How do you call (execute) a stored procedure named sp_demo?",
         ["RUN sp_demo", "CALL sp_demo();", "EXECUTE ONLY sp_demo", "SELECT sp_demo();"], "B",
         "CALL is the statement that invokes a stored procedure and runs its body."),
        ("BEGINNER", "What is the main difference between a stored procedure and a stored function?",
         ["Functions return a value and are used inside expressions, while procedures may not return a value and are called with CALL",
          "Procedures are faster than functions",
          "Functions cannot have a body", "There is no difference"], "A",
         "Stored functions return a single value and can appear in SELECT expressions, whereas procedures are invoked with CALL and need not return a value."),
        ("BEGINNER", "Which construct wraps the executable statements of a stored routine body?",
         ["BEGIN ... END", "START ... STOP", "IF ... FI", "LOOP ... ENDLOOP"], "A",
         "The body of a stored routine is a compound statement delimited by BEGIN and END."),
        ("BEGINNER", "What does the command DELIMITER $$ do in the mysql client?",
         ["It changes the delimiter used to end statements to $$",
          "It doubles the precision of numbers", "It stops the server",
          "It creates two databases"], "A",
         "DELIMITER $$ tells the client to treat $$ as the end of a statement, allowing semicolons inside a routine body."),
        ("BEGINNER", "Which keyword declares a local variable inside a stored procedure?",
         ["VAR", "DECLARE", "CREATE VARIABLE", "SET VAR"], "B",
         "DECLARE introduces local variables at the start of a BEGIN ... END block, optionally with a default value."),
        ("BEGINNER", "Which SQL command removes a stored function from the database?",
         ["DELETE FUNCTION", "REMOVE FUNCTION", "DROP FUNCTION", "KILL FUNCTION"], "C",
         "DROP FUNCTION permanently deletes a stored function from the database, using its name and signature."),
        ("INTERMEDIATE", "In a stored procedure, what is the purpose of an OUT parameter?",
         ["It accepts input only", "It returns a value to the caller through the parameter rather than through a result set",
          "It holds the loop counter", "It names the procedure's schema"], "B",
         "An OUT parameter lets a procedure pass a result back to the caller in the variable supplied at CALL time."),
        ("INTERMEDIATE", "Which of these correctly calls a stored function named fn_tax in a SELECT?",
         ["CALL fn_tax(100);", "SELECT fn_tax(100);", "RUN fn_tax(100);", "EXEC fn_tax(100);"], "B",
         "Stored functions are invoked like built-in functions inside expressions, so SELECT fn_tax(100) returns the computed value."),
        ("INTERMEDIATE", "How is a local variable assigned a value inside a procedure?",
         ["With the SET statement", "With the DEFAULT clause", "With the LET keyword", "By typing it in the body"], "A",
         "SET assigns a value to a local or user variable, for example SET total = total + 1;."),
        ("INTERMEDIATE", "Which statement correctly shows a conditional action in a stored procedure?",
         ["IF price > 100 THEN SET flag = 1; END IF;",
          "WHEN price > 100 DO flag = 1;", "CASE price > 100 SET flag", "LOOP price > 100 flag = 1"], "A",
         "IF ... THEN ... END IF executes the statements inside only when the boolean condition is true."),
        ("INTERMEDIATE", "What does a cursor do inside a stored procedure?",
         ["It locks the whole table", "It lets the procedure iterate row by row over a result set",
          "It encrypts the result", "It prevents all queries"], "B",
         "Cursors allow row-by-row processing of a SELECT result set, usually paired with a loop and FETCH statements."),
        ("INTERMEDIATE", "A procedure declares PROCEDURE p(IN x INT, OUT y INT). Which is true?",
         ["x can be modified and seen by the caller, y cannot", "y is set inside the procedure and the caller reads it afterward",
          "Both parameters are read-only", "Neither parameter may be used"], "B",
         "IN x is read-only input, while OUT y is written inside the procedure and its value is returned to the caller."),
        ("INTERMEDIATE", "What happens if you call a stored procedure that does not exist?",
         ["MySQL silently ignores it", "MySQL creates it automatically", "MySQL raises an error such as 'PROCEDURE does not exist'",
          "The database is deleted"], "C",
         "Invoking an undefined procedure name causes an error because MySQL cannot find a matching routine in the database."),
        ("INTERMEDIATE", "Which pair of statements is used together to end a stored procedure definition cleanly in the client?",
         ["DROP and CREATE", "DELIMITER $$ ... DELIMITER ;", "BEGIN and END LOOP", "START and COMMIT"], "B",
         "The delimiter is changed before the CREATE so the body can contain semicolons, then restored to a semicolon afterward."),
        ("INTERMEDIATE", "What distinguishes a stored function that is marked DETERMINISTIC?",
         ["It always returns the same result for the same arguments",
          "It runs faster than other functions", "It cannot take parameters",
          "It is automatically dropped"], "A",
         "DETERMINISTIC declares that the function produces identical output for identical inputs, which the optimizer may use for caching."),
        ("INTERMEDIATE", "How does a stored procedure return a result set such as a filtered list of rows?",
         ["It cannot return rows", "By running a SELECT inside its body, whose result is sent to the caller",
          "By using a RETURN statement", "By writing to a file"], "B",
         "A SELECT executed inside a procedure emits its rows to the client, allowing the procedure to behave like a parameterized query."),
        ("ADVANCED", "Which of these is the correct skeleton for fetching every row of a cursor?",
         ["DECLARE c CURSOR FOR ...; OPEN c; LOOP FETCH c INTO ...; ... UNTIL done END LOOP; CLOSE c;",
          "FETCH ALL FROM c;", "SELECT c;", "OPEN c; SELECT c; CLOSE c;"], "A",
         "Cursor processing requires declaring it over a query, opening it, looping with FETCH until rows run out, then closing it."),
        ("ADVANCED", "Why do cursor loops in MySQL typically declare a handler such as DECLARE CONTINUE HANDLER FOR NOT FOUND?",
         ["To catch syntax errors", "To set a flag when FETCH exhausts the result set so the loop can terminate",
          "To raise exceptions on purpose", "To close the database connection"], "B",
         "When FETCH finds no more rows it triggers the NOT FOUND condition, and the handler sets a flag that the loop condition checks."),
        ("ADVANCED", "Which routine attribute is appropriate for a function that computes a date difference and depends on session variables?",
         ["DETERMINISTIC", "NOT DETERMINISTIC", "ATOMIC", "STATIC"], "B",
         "A function whose output varies with session state cannot be DETERMINISTIC, so it must be declared NOT DETERMINISTIC to avoid incorrect optimization."),
        ("ADVANCED", "What is a key reason to avoid deep recursion in MySQL stored procedures?",
         ["MySQL has a limited recursion depth and can raise error 1428 or consume excessive stack space",
          "Recursion is always faster", "Recursion requires extra disks",
          "Recursion disables transactions"], "A",
         "MySQL allows recursion only if binary logging is configured correctly and limits nesting, so uncontrolled recursion fails with errors."),
        ("ADVANCED", "Which statement allows a procedure to manage a multi-step operation as one unit that can be undone?",
         ["START TRANSACTION; ... COMMIT; or ROLLBACK;",
          "LOCK TABLES ONLY;", "BEGIN WORK WITH LOG;", "SAVEPOINT THE WHOLE JOB;"], "A",
         "START TRANSACTION begins a transaction, and COMMIT makes it permanent while ROLLBACK undoes all changes since it began."),
        ("ADVANCED", "Which system source can you query to see which stored procedures exist and their characteristics?",
         ["information_schema.ROUTINES", "mysql.users", "performance_schema.events", "sys.disk_usage"], "A",
         "information_schema.ROUTINES stores metadata about stored procedures and functions, including type, creator and definition."),
        ("ADVANCED", "How should dynamic SQL in a stored procedure be built to avoid SQL injection?",
         ["Concatenate user input directly into the query string",
          "Use prepared statements with placeholders and bind parameter values",
          "Disable all queries", "Store the query in a file"], "B",
         "Using PREPARE with ? placeholders and EXECUTE with bound values separates code from data, preventing injection through user-supplied text."),
        ("ADVANCED", "Why might a cursor be slower than a single set-based UPDATE for transforming 100,000 rows?",
         ["Cursors are always faster", "Row-by-row processing incurs per-row overhead in the client-server protocol and inside the server",
          "Set-based updates are not supported", "Cursors compress data"], "B",
         "Cursors process one row at a time, generating more round trips and more internal work, whereas a single UPDATE works on the whole set in one pass."),
        ("ADVANCED", "What is the best way to validate parameters inside a procedure and abort execution on bad input?",
         ["Use SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid parameter';",
          "Return NULL from the procedure", "Log to a file and continue",
          "Ignore the parameter"], "A",
         "SIGNAL raises a user-defined exception with a SQLSTATE and message, immediately stopping the procedure when validation fails."),
        ("ADVANCED", "A function returns a value for each employee. Where can this function legally be used?",
         ["Only inside other procedures", "Anywhere an expression is allowed, such as SELECT fn(salary)",
          "Only in triggers", "Only in the mysql client"], "B",
         "Stored functions can be used in expressions wherever built-in functions are allowed, including SELECT lists, WHERE and computed columns."),
    ],

    39: [
        ("BEGINNER", "What is a database trigger?",
         ["A query that runs manually", "A stored program that executes automatically in response to table events such as INSERT, UPDATE or DELETE",
          "A type of index", "A backup copy of a table"], "B",
         "A trigger is a stored routine MySQL runs automatically when a specified DML event occurs on a table."),
        ("BEGINNER", "Which three events can fire a MySQL trigger?",
         ["SELECT, SHOW, DESCRIBE", "INSERT, UPDATE, DELETE",
          "CREATE, DROP, ALTER", "LOCK, UNLOCK, COMMIT"], "B",
         "MySQL triggers fire only on data-changing statements: INSERT, UPDATE and DELETE."),
        ("BEGINNER", "What does the BEFORE keyword in a trigger definition mean?",
         ["The trigger runs after the row is committed", "The trigger runs before the triggering statement modifies the row",
          "The trigger runs once per day", "The trigger blocks the table"], "B",
         "BEFORE triggers execute before the row is changed, allowing the trigger to modify the NEW values before they are stored."),
        ("BEGINNER", "What is a view in MySQL?",
         ["A stored query that appears as a virtual table", "A copy of the data in another table",
          "An index on a table", "A backup file"], "A",
         "A view is a virtual table defined by a SELECT statement; it shows the query result each time it is used."),
        ("BEGINNER", "Which statement creates a new view named emp_view?",
         ["CREATE VIEW emp_view AS SELECT * FROM emp;",
          "MAKE VIEW emp_view;", "NEW TABLE emp_view;", "ADD VIEW emp_view;"], "A",
         "CREATE VIEW name AS select_statement defines the view by storing the query, not the data itself."),
        ("BEGINNER", "Can a trigger be created directly on a view in MySQL?",
         ["Yes, always", "No, MySQL does not support triggers on views",
          "Only on materialized views", "Only with a special flag"], "B",
         "MySQL does not support triggers on views; triggers are only allowed on base tables."),
        ("BEGINNER", "Which information_schema table stores trigger metadata?",
         ["information_schema.TRIGGERS", "information_schema.VIEWS", "information_schema.TABLES",
          "information_schema.INDEXES"], "A",
         "information_schema.TRIGGERS contains details of every trigger, including its event, timing and definition."),
        ("BEGINNER", "In a BEFORE INSERT trigger, which keyword gives access to the values being inserted?",
         ["OLD", "NEW", "CUR", "ROOT"], "B",
         "NEW refers to the row that will be inserted, so NEW.column can be read or modified in a BEFORE INSERT trigger."),
        ("BEGINNER", "In an AFTER DELETE trigger, which keyword gives access to the row that was just removed?",
         ["NEW", "OLD", "LAST", "REMOVED"], "B",
         "OLD holds the original values of the deleted row, which are no longer available in the table itself."),
        ("BEGINNER", "Which statement removes a trigger named trg_audit from the database?",
         ["DELETE TRIGGER trg_audit", "DROP TRIGGER trg_audit", "KILL TRIGGER trg_audit", "REMOVE TRIGGER trg_audit"], "B",
         "DROP TRIGGER trg_audit permanently removes the trigger; the schema must be included if it is not the default database."),
        ("INTERMEDIATE", "Which use case is a classic example of a BEFORE INSERT trigger?",
         ["Automatically setting or validating column values before the row is written",
          "Speeding up SELECT queries", "Encrypting the whole database",
          "Sharding tables"], "A",
         "BEFORE INSERT triggers run before storage, so they can normalize or validate data and adjust NEW values in place."),
        ("INTERMEDIATE", "What is a typical purpose of an AFTER DELETE trigger?",
         ["To archive or audit the deleted row into a history table",
          "To prevent the delete", "To renumber the table", "To create a backup index"], "A",
         "AFTER DELETE fires once the row is gone, and OLD lets the trigger copy that row into an audit or archive table."),
        ("INTERMEDIATE", "Which CREATE VIEW statement is syntactically correct?",
         ["CREATE VIEW high_sal AS SELECT name, salary FROM emp WHERE salary > 50000;",
          "CREATE VIEW high_sal OF emp;", "VIEW high_sal = SELECT * FROM emp;",
          "MAKE VIEW high_sal FROM emp;"], "A",
         "The view definition must follow CREATE VIEW name AS with a valid SELECT statement."),
        ("INTERMEDIATE", "When you UPDATE a row in a table and the UPDATE trigger fires, what does OLD represent?",
         ["The new values after the update", "The values of the row before the update was applied",
          "The row from another table", "Nothing at all"], "B",
         "In an UPDATE trigger, OLD contains the row as it existed before the change, while NEW contains the updated values."),
        ("INTERMEDIATE", "Which type of trigger body can contain multiple statements?",
         ["A single-statement body only", "A compound BEGIN ... END block with several statements",
          "Only stored functions", "Only SELECT statements"], "B",
         "Writing the trigger body as a BEGIN ... END compound block lets you include several statements, so DELIMITER changes are often needed."),
        ("INTERMEDIATE", "What is one limitation of MySQL triggers regarding tables?",
         ["They can run on any table including views", "Triggers cannot be defined on temporary tables",
          "They run on every event type", "They ignore the NEW row"], "B",
         "MySQL forbids triggers on temporary tables, and views are likewise not allowed, so only persistent base tables can carry triggers."),
        ("INTERMEDIATE", "How do you name a trigger that fires before a delete on table orders?",
         ["CREATE TRIGGER trg_orders_bd BEFORE DELETE ON orders", 
          "CREATE TRIGGER orders DELETE BEFORE", 
          "TRIGGER ON orders BEFORE DELETE", 
          "MAKE TRIGGER orders_bd"], "A",
         "The syntax CREATE TRIGGER name BEFORE DELETE ON orders requires the timing, the event and the target table in that order."),
        ("INTERMEDIATE", "Which of these correctly retrieves the list of views in a database?",
         ["SELECT * FROM information_schema.VIEWS WHERE TABLE_SCHEMA = 'mydb';",
          "SHOW TABLES WHERE TYPE = 'view';", "SELECT * FROM mysql.views;",
          "DESCRIBE VIEW mydb;"], "A",
         "information_schema.VIEWS lists every view along with its defining query, filtered by schema name."),
        ("INTERMEDIATE", "What does the trigger definition UPDATE OF column_name do in a BEFORE UPDATE trigger?",
         ["It updates the column automatically", "It restricts the trigger to fire only when that specific column changes",
          "It drops the column", "It renames the column"], "B",
         "The UPDATE OF clause limits the trigger to fire only when the named column is included in the UPDATE statement, avoiding wasted work."),
        ("INTERMEDIATE", "Which statement logs every change to an audit table from within an AFTER UPDATE trigger?",
         ["INSERT INTO audit_log (old_val, new_val) VALUES (OLD.x, NEW.x);",
          "SELECT old, new FROM audit;", "UPDATE audit SET x = NEW.x;",
          "COPY OLD INTO audit;"], "A",
         "An INSERT statement inside the trigger copies OLD and NEW values into the audit table, recording exactly what changed."),
        ("ADVANCED", "What does WITH CHECK OPTION do on a view?",
         ["It makes the view read-only", "It prevents INSERT and UPDATE statements that would make rows disappear from the view's result set",
          "It encrypts the view", "It caches the view's data"], "B",
         "WITH CHECK OPTION enforces the view's WHERE condition on inserts and updates, rejecting changes that would place a row outside the view."),
        ("ADVANCED", "What happens if a BEFORE UPDATE trigger sets a value and then another part of the statement changes the same column?",
         ["The later change wins because the trigger runs first and its NEW values are used for the final write",
          "The trigger is skipped", "Both values are concatenated",
          "MySQL raises a deadlock error"], "A",
         "BEFORE triggers run before the write, and any adjustments to NEW are what actually get stored when the row is finally written."),
        ("ADVANCED", "Why is it risky to create triggers that perform large amounts of work?",
         ["Triggers run on the original event thread, so heavy work increases the statement's latency and can slow writes",
          "Triggers never run", "Large triggers are rejected", "Triggers compress the data"], "A",
         "Trigger bodies execute synchronously inside the triggering statement, so expensive operations inside them add directly to every affected write's cost."),
        ("ADVANCED", "Which recursive or cascading behavior does MySQL prevent in triggers?",
         ["A trigger on table A that inserts into table B, which has its own triggers", "A trigger that references OLD in an INSERT trigger",
          "A trigger modifying the same table it is defined on, which could cause infinite recursion",
          "A trigger using stored functions"], "C",
         "A trigger that performs DML on its own table can fire itself again, so MySQL rejects such self-modifying triggers to avoid infinite recursion."),
        ("ADVANCED", "In a BEFORE INSERT trigger, how do you reject a bad row before it is stored?",
         ["By returning NULL", "Use SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid row';",
          "By deleting the row", "By closing the connection"], "B",
         "SIGNAL raises a user error that aborts the entire insert, so the offending row is never stored."),
        ("ADVANCED", "Which view characteristic makes it updatable through the view itself?",
         ["The view joins several tables", "The view maps each view row to a single base-table row with no aggregates or DISTINCT",
          "The view uses GROUP BY", "The view uses UNION"], "B",
         "A view is updatable when it is derived from one base table without aggregation, DISTINCT, GROUP BY or other constructs that hide the underlying row."),
        ("ADVANCED", "How do you obtain the exact SQL text that defined an existing trigger?",
         ["SELECT TRIGGER_BODY FROM information_schema.TRIGGERS;", "SHOW CREATE TRIGGER trigger_name;",
          "DESCRIBE TRIGGER trigger_name;", "EXPLAIN TRIGGER trigger_name;"], "B",
         "SHOW CREATE TRIGGER prints the complete CREATE TRIGGER statement for a given trigger, mirroring its stored definition."),
        ("ADVANCED", "Why are triggers considered a poor place to enforce complex business rules compared to application code?",
         ["Trigger behavior is implicit and can surprise developers, and debugging relies on inspecting hidden server-side code",
          "Triggers cannot run at all", "Triggers are always slower than apps",
          "Applications cannot see trigger results"], "A",
         "Because triggers fire invisibly inside the server, their logic is easy to overlook and hard to test, so complex rules are often clearer in application code."),
        ("ADVANCED", "Which statement correctly creates a view with WITH CHECK OPTION and a filter on sales?",
         ["CREATE VIEW big_sales AS SELECT * FROM sales WHERE amount > 1000 WITH CHECK OPTION;",
          "CREATE VIEW big_sales WITH CHECK FROM sales;",
          "CREATE VIEW big_sales AS SELECT * FROM sales CHECK OPTION;",
          "MAKE VIEW big_sales WITH CHECK;"], "A",
         "WITH CHECK OPTION must follow the view's SELECT clause, and it then rejects inserts or updates that would violate the amount > 1000 filter."),
        ("ADVANCED", "What is the main drawback of using a view to simplify every complex query in an application?",
         ["Views are always faster", "A view that joins many large tables can run slowly each time it is queried, since it is not materialized by default",
          "Views cannot be dropped", "Views consume extra disk space for data"], "B",
         "MySQL views are not materialized; the underlying query executes on every reference, so heavy views can become a performance bottleneck."),
    ],

    40: [
        ("BEGINNER", "What does the EXPLAIN statement do in MySQL?",
         ["It executes the query", "It shows how the optimizer plans to execute a query, including table access order and indexes used",
          "It deletes the query", "It counts rows in a table"], "B",
         "EXPLAIN reports the execution plan the optimizer chose, such as which tables, joins and indexes will be used."),
        ("BEGINNER", "What is a database index?",
         ["A copy of the whole database", "A data structure that speeds up lookups on certain columns",
          "A type of trigger", "A user account"], "B",
         "An index is an auxiliary structure such as a B-tree that lets MySQL find and sort rows much faster than scanning everything."),
        ("BEGINNER", "Which statement creates an index named idx_email on the email column of the users table?",
         ["CREATE INDEX idx_email ON users(email);",
          "ADD INDEX email TO users;", "INDEX users ON email;", "CREATE KEY email FROM users;"], "A",
         "CREATE INDEX idx_name ON table(column) is the standard syntax for adding an index to an existing table."),
        ("BEGINNER", "Which component of a table is itself the clustered index in InnoDB?",
         ["The primary key", "A secondary index", "The foreign key", "The AUTO_INCREMENT value"], "A",
         "In InnoDB, data rows are physically organized around the primary key, so the primary key is the clustered index."),
        ("BEGINNER", "What does the slow query log capture?",
         ["All queries", "Queries that take longer than a configured time threshold",
          "Queries that fail", "Only INSERT statements"], "B",
         "The slow query log records statements whose execution time exceeds the long_query_time setting, helping to find bottlenecks."),
        ("BEGINNER", "Which command shows the list of currently running connections and queries?",
         ["SHOW PROCESSLIST", "LIST QUERIES", "SHOW INDEXES", "STATUS RUN"], "A",
         "SHOW PROCESSLIST displays active connections and their current statements, useful for spotting long-running queries."),
        ("BEGINNER", "What is the purpose of the MySQL query cache (before it was removed in MySQL 8)?",
         ["To cache SELECT result sets so identical queries could be served without re-execution",
          "To store passwords", "To cache database backups",
          "To store table definitions"], "A",
         "The query cache stored the result of a SELECT keyed by its text, letting identical later queries return instantly until the underlying data changed."),
        ("BEGINNER", "Which type of index does MySQL use by default for the InnoDB storage engine?",
         ["Hash index", "B-tree index", "BitMap index", "R-tree index"], "B",
         "InnoDB indexes are B-tree based, which supports both equality and range searches efficiently."),
        ("BEGINNER", "Which operation does an index primarily speed up?",
         ["INSERT statements only", "Lookups and sorting in SELECT queries",
          "DELETE statements only", "User management"], "B",
         "Indexes accelerate search, filtering and ordering in queries, at the cost of extra write overhead on the indexed columns."),
        ("BEGINNER", "Which EXPLAIN column tells you the index actually selected by the optimizer?",
         ["possible_keys", "key", "rows", "filtered"], "B",
         "The key column names the index the optimizer chose, while possible_keys lists all candidate indexes considered."),
        ("INTERMEDIATE", "In EXPLAIN output, what does type = ALL indicate about a table access?",
         ["A full table scan, which usually means no useful index was used",
          "A primary key lookup", "An empty table", "An error"], "A",
         "type = ALL means MySQL will read every row of the table; it is often a performance warning unless the table is tiny."),
        ("INTERMEDIATE", "What is the difference between possible_keys and key in an EXPLAIN result?",
         ["They are always identical", "possible_keys lists indexes the optimizer could use, while key shows the one it actually chose",
          "key lists all indexes in the table", "possible_keys is always empty"], "B",
         "possible_keys enumerates candidates, and key reports the winner; when key is NULL but possible_keys is not, the optimizer decided against using an index."),
        ("INTERMEDIATE", "Why does column order matter in a composite index like (last_name, first_name)?",
         ["The index is most effective when the leftmost columns match the query conditions first",
          "Column order has no effect", "The rightmost column must be the primary key",
          "Only the second column is indexed"], "A",
         "A B-tree index on (a,b) supports searches on a, then on a and b; queries that skip the leading column cannot use the leftmost prefix."),
        ("INTERMEDIATE", "Why should you avoid adding an index to every column of a table?",
         ["Indexes never help queries", "Every extra index slows down INSERT, UPDATE and DELETE and consumes disk space",
          "MySQL only allows two indexes", "Indexes prevent NULLs"], "B",
         "Each index must be maintained on every write and occupy storage, so too many indexes degrade write performance without adding query value."),
        ("INTERMEDIATE", "What does 'Using filesort' mean in the Extra column of EXPLAIN?",
         ["MySQL must sort the result using an external sort operation because no index order matches the ORDER BY",
          "The query writes to a file on disk permanently",
          "The table is corrupted", "The query is deleted"], "A",
         "Using filesort indicates extra sorting work beyond the normal query, which may be avoidable by ordering through an index."),
        ("INTERMEDIATE", "What is a covering index?",
         ["An index that contains every column the query needs, so the table itself never has to be read",
          "An index covering all tables", "An index on text columns",
          "An index that hides data"], "A",
         "When all selected and filtered columns exist in one index, MySQL can answer the query entirely from the index pages, a big speed-up."),
        ("INTERMEDIATE", "Why is SELECT * often worse for performance than listing needed columns?",
         ["It returns extra unneeded data and can force reading full rows instead of a covering index",
          "The asterisk is invalid SQL", "It doubles the query cost",
          "It disables indexes completely"], "A",
         "Returning only the required columns reduces network and I/O and may let the optimizer use a covering index instead of the table."),
        ("INTERMEDIATE", "A query filters WHERE name LIKE '%smith%'. Why can MySQL not use a normal index for this?",
         ["A leading wildcard prevents the index from finding a starting prefix to scan",
          "LIKE never uses indexes", "The name column is too short",
          "Indexes only work on numbers"], "A",
         "With a leading % the search string has no fixed prefix, so a B-tree index cannot help; only LIKE 'smith%' can use an index."),
        ("INTERMEDIATE", "Why should a foreign key column usually have an index?",
         ["Indexes are mandatory", "It speeds up join lookups and the referential checks performed on the child column",
          "It stores the data", "It prevents the column from being NULL"], "B",
         "Indexing the foreign key column accelerates the lookups used to match parent rows during joins and constraint validation."),
        ("INTERMEDIATE", "What does a low cardinality value on an indexed column indicate?",
         ["The column has very few distinct values, so the index may not help much", "The column is empty",
          "The index is corrupted", "The column is very long"], "A",
         "Cardinality is the count of distinct values; low cardinality (like a gender column with two values) means an index rarely narrows the search."),
        ("ADVANCED", "What does the rows column in EXPLAIN represent?",
         ["The exact number of rows the query will return", "The optimizer's estimate of rows examined per table access",
          "The physical size of the table", "The number of indexes"], "B",
         "The rows estimate is a heuristic based on statistics and index cardinality, not an exact count, and helps spot scan sizes before running."),
        ("ADVANCED", "Why does wrapping an indexed column in a function, such as WHERE YEAR(birth_date) = 2000, prevent index usage?",
         ["The function must be computed for every row because the index stores raw values, not the transformed result",
          "MySQL bans all functions", "The optimizer ignores WHERE", 
          "Indexes cannot store dates"], "A",
         "Because the index holds the original column values, a function on the column forces MySQL to evaluate it per row, defeating the index."),
        ("ADVANCED", "Why was the query cache removed entirely in MySQL 8?",
         ["It was too fast", "It caused global mutex contention and was rarely a net win on multi-core systems",
          "It could not store numbers", "It was proprietary"], "B",
         "The query cache serialized access with a global lock, hurt scalability, and its hit rates were low, so MySQL 8 dropped it in favor of other caching."),
        ("ADVANCED", "Which tool shows the optimizer's actual cost calculations for a query?",
         ["EXPLAIN ANALYZE in MySQL 8", "SHOW ENGINE INNODB STATUS", "SHOW PROCESSLIST", "DESCRIBE TABLE"], "A",
         "EXPLAIN ANALYZE executes the query and reports actual timing and row counts per step, showing exactly where time is spent."),
        ("ADVANCED", "What is the purpose of running ANALYZE TABLE on a large InnoDB table after heavy changes?",
         ["It deletes old rows", "It updates optimizer statistics such as index cardinality so the optimizer picks better plans",
          "It rebuilds the entire database", "It encrypts the table"], "B",
         "ANALYZE TABLE refreshes the distribution statistics used by the optimizer, which prevents stale stats from producing poor query plans."),
        ("ADVANCED", "Why might a query with a range condition (WHERE id BETWEEN 1 AND 5000) switch to a full scan even with an index?",
         ["Because indexes are disabled for BETWEEN", "If the range covers most of the table, the optimizer estimates a scan is cheaper than random index reads",
          "Because BETWEEN is invalid SQL", "Because the table has no primary key"], "B",
         "When a large fraction of rows is selected, sequential reads outperform many random index lookups, so the optimizer chooses a scan."),
        ("ADVANCED", "How do you index a long TEXT column that cannot fit in an ordinary index?",
         ["Use a prefix index, e.g. INDEX (content(100)), indexing only the first 100 characters",
          "TEXT columns cannot be indexed", "Convert it to an ENUM",
          "Index the whole column with a hash"], "A",
         "Prefix indexes index only the leading characters of a string column, making them small enough to fit index page limits."),
        ("ADVANCED", "What is a common reason for locking waits and deadlocks in InnoDB under high concurrency?",
         ["Rows being accessed in inconsistent order across transactions while holding locks on them",
          "Too many indexes", "Slow SELECT queries", "The binary log being disabled"], "A",
         "When transactions lock rows in different orders, each can wait on the other's locks, producing deadlocks that InnoDB resolves by rolling one back."),
        ("ADVANCED", "Why does ORDER BY an indexed column with a small LIMIT often avoid a filesort?",
         ["MySQL can walk the index in sorted order and stop after LIMIT rows without sorting the whole result",
          "ORDER BY never sorts", "The limit disables ordering",
          "Indexes sort automatically at insert time"], "A",
         "If the index already yields rows in the requested order, the optimizer reads them directly from the index and stops at the limit."),
        ("ADVANCED", "A slow query report shows a SELECT that only reads 3 columns filtering 2 others. Which single change most likely fixes it?",
         ["Adding a composite covering index on the filtered and selected columns",
          "Dropping all indexes", "Switching to MyISAM", "Increasing the sort buffer"], "A",
         "A covering index on exactly the columns used lets the query run entirely from the index, avoiding table reads and often filesorts."),
    ],
}
