# -*- coding: utf-8 -*-
"""
Question bank for subject 32: CLD102 - Cybersecurity.
Category: Cloud, Cybersecurity & DevOps.

Topics:
  156: Security Fundamentals
  157: Threats & Vulnerabilities
  158: Identity & Access Management
  159: Malware & Defense
  160: Audits & Compliance

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    156: [
        ("BEGINNER", "Which three properties form the core of the CIA security triad?",
         ["Confidentiality, Integrity, Availability", "Confidentiality, Isolation, Authentication", "Centralization, Integrity, Availability", "Confidentiality, Integrity, Authorization"], "A",
         "The CIA triad consists of Confidentiality, Integrity and Availability, the three core goals of information security."),
        ("BEGINNER", "Which CIA goal ensures information cannot be modified by unauthorized parties?",
         ["Integrity", "Confidentiality", "Authentication", "Non-repudiation"], "A",
         "Integrity guarantees that data has not been altered or tampered with by unauthorized users."),
        ("BEGINNER", "Which technique is most commonly used to protect the confidentiality of data at rest?",
         ["Encryption", "A firewall", "A honeypot", "A load balancer"], "A",
         "Encryption transforms plaintext into ciphertext so that data at rest remains unreadable without the correct key."),
        ("BEGINNER", "Which principle grants users only the permissions required to perform their job?",
         ["Least privilege", "Separation of duties", "Defense in depth", "Fail open"], "B",
         "The principle of least privilege limits each user to the minimum access needed for their role."),
        ("BEGINNER", "What is the relationship between a threat and a vulnerability?",
         ["A threat is a weakness and a vulnerability is the attacker", "A threat is a potential danger that can exploit a vulnerability, which is a weakness", "They are the same concept", "A vulnerability is always accidental while a threat is always intentional"], "B",
         "A threat is a potential source of harm, while a vulnerability is a weakness that the threat can exploit."),
        ("BEGINNER", "Which strategy layers multiple independent security controls so that a single failure does not compromise the system?",
         ["Defense in depth", "Single point of failure", "Least privilege", "Fail closed"], "B",
         "Defense in depth uses overlapping controls so that even if one layer fails, other layers still protect the asset."),
        ("BEGINNER", "In risk management, which term refers to anything of value that requires protection?",
         ["An asset", "A threat actor", "A control", "An incident"], "C",
         "An asset is any resource of value to the organization, such as data, hardware, or reputation, that needs protection."),
        ("BEGINNER", "Which network device filters traffic based on rules such as source IP, port, and protocol?",
         ["A firewall", "A switch", "A repeater", "An access point"], "C",
         "A firewall inspects network traffic and allows or blocks it according to a defined set of security rules."),
        ("BEGINNER", "If risk is calculated as likelihood multiplied by impact, which action most directly reduces the risk score?",
         ["Reduce the likelihood or impact of a loss", "Increase the number of users", "Add more network bandwidth", "Disable logging"], "D",
         "Lowering either the likelihood or the impact of a negative event directly reduces the resulting risk score."),
        ("BEGINNER", "Which pair of terms best describes verifying who a user is versus what they are allowed to do?",
         ["Authentication and authorization", "Encryption and hashing", "Detection and response", "Auditing and logging"], "D",
         "Authentication verifies a user's identity, while authorization determines what actions that identity may perform."),
        ("INTERMEDIATE", "A hospital must keep patient records private but also available to doctors during outages. Which additional control best addresses availability without weakening confidentiality?",
         ["Redundant power, networking, and backup systems", "Deleting older patient records", "Sharing a single password among doctors", "Removing all audit logs"], "A",
         "Redundancy and reliable backups keep records available during outages while the data remains encrypted and private."),
        ("INTERMEDIATE", "An analyst finds that a terminated employee still has an active email account. Which control should have prevented this?",
         ["Promptly disabling accounts when an employee leaves", "Increasing the password length", "Adding more servers", "Using a stronger encryption algorithm"], "A",
         "Account lifecycle management, including immediate deprovisioning on termination, removes access when it is no longer needed."),
        ("INTERMEDIATE", "A company stores unencrypted backup tapes containing financial data. Which control best addresses this confidentiality risk?",
         ["Encrypt the tapes before storing them", "Label the tapes clearly", "Keep the tapes near the servers", "Delete the data after backing up"], "A",
         "Encrypting the tapes ensures that the financial data is unreadable even if the physical media is lost or stolen."),
        ("INTERMEDIATE", "A web application allows any user to view another user's profile by changing an ID in the URL. Which principle was violated?",
         ["Authorization and least privilege", "Authentication only", "Availability", "Encryption strength"], "B",
         "The application fails to check whether the logged-in user is authorized to access the requested profile, violating authorization."),
        ("INTERMEDIATE", "Which order correctly reflects the typical phases of a risk management process?",
         ["Identify, assess, treat, monitor", "Monitor, treat, assess, identify", "Assess, identify, monitor, treat", "Treat, monitor, identify, assess"], "B",
         "Risk management begins by identifying risks, then assessing them, then treating them, and finally monitoring the results."),
        ("INTERMEDIATE", "A security team implements biometrics, smart cards, and passphrases. Which security goal are they most directly strengthening?",
         ["Authentication of identities", "Network performance", "Data compression", "Physical cooling"], "B",
         "Requiring multiple verification factors strengthens authentication because an attacker must defeat each factor."),
        ("INTERMEDIATE", "A legacy server cannot be patched but must remain online. Which compensating control is most appropriate?",
         ["Isolate it behind a firewall segment and restrict allowed traffic", "Remove its audit logs", "Give every user administrative rights", "Connect it directly to the internet"], "C",
         "Isolating an unpatched system limits its exposure so an attacker who exploits it cannot easily reach the rest of the network."),
        ("INTERMEDIATE", "Which of the following is the best example of defense in depth?",
         ["A firewall, an intrusion detection system, host-based controls, and encryption used together", "A single strong password", "One antivirus product only", "Relying on a single firewall rule"], "C",
         "Defense in depth combines network, host, and data-layer controls so that multiple independent layers must be defeated."),
        ("INTERMEDIATE", "What is the primary purpose of a risk register?",
         ["To document identified risks, their likelihood, impact, and treatment plans", "To store backup tapes", "To log every keystroke", "To block phishing emails"], "D",
         "A risk register is a central document that records each identified risk and how the organization plans to manage it."),
        ("INTERMEDIATE", "A data breach occurred because backups were stored in the same building as the servers. Which part of the CIA triad was most affected?",
         ["Availability", "Confidentiality", "Integrity", "Non-repudiation"], "D",
         "Storing backups in the same location as the servers means a single disaster destroys both, threatening availability of data."),
        ("ADVANCED", "An organization must comply with GDPR while operating in a public cloud. Which design choice best supports data minimization and the right to erasure?",
         ["Storing only necessary personal data and designing deletion workflows", "Storing all data forever for analysis", "Copying data to many regions", "Encrypting data with a lost key"], "A",
         "Data minimization and deletion workflows ensure only required personal data is kept and can be removed on request."),
        ("ADVANCED", "An analyst values an asset at $500,000 with a 10% likelihood of loss in a year. What is the annualized loss expectancy (ALE)?",
         ["$50,000", "$5,000", "$500,000", "$500,000,000"], "A",
         "The ALE is calculated as the single loss expectancy multiplied by the annualized rate of occurrence, here $500,000 times 0.10 = $50,000."),
        ("ADVANCED", "Which approach best balances security and usability when implementing multi-factor authentication for a large workforce?",
         ["Phishing-resistant authenticators combined with self-service backup methods", "Requiring only passwords", "Using the same OTP for every site", "Forcing everyone to carry hardware tokens with no recovery"], "A",
         "Phishing-resistant authenticators with a practical recovery path provide strong security without making legitimate access impossible."),
        ("ADVANCED", "A zero-trust architecture differs from a traditional perimeter model primarily because it:",
         ["Assumes no implicit trust based on network location and verifies every request", "Trusts anything inside the office network", "Removes all authentication", "Relies only on a VPN at the edge"], "B",
         "Zero trust abandons the assumption that internal networks are safe and instead verifies every access request continuously."),
        ("ADVANCED", "Which statement best describes the shared responsibility model in cloud security?",
         ["The provider secures the infrastructure while the customer secures what they put in the cloud", "The provider secures everything", "The customer secures the physical datacenter", "No party has any security responsibilities"], "B",
         "Under the shared responsibility model, the provider protects the cloud itself while the customer protects workloads and data inside it."),
        ("ADVANCED", "Why might a security architect choose a fail-closed access control over fail-open?",
         ["To prevent unauthorized access when a control cannot verify a request", "To maximize convenience for users", "To reduce hardware costs", "To avoid maintaining logs"], "B",
         "Fail-closed denies access by default when verification fails, prioritizing confidentiality and security over convenience."),
        ("ADVANCED", "Which metric is most useful for measuring the effectiveness of a security awareness program?",
         ["The percentage of users who pass simulated phishing tests over time", "The number of servers", "The total network bandwidth", "The company's stock price"], "C",
         "Tracking simulated phishing failure rates over time shows whether user awareness and behavior are actually improving."),
        ("ADVANCED", "When designing a business continuity plan, which sequence is most appropriate?",
         ["Identify critical assets, define RTO and RPO, test and rehearse", "Test first, then define assets", "Buy insurance before identifying assets", "Document nothing until a disaster occurs"], "C",
         "A sound plan first identifies what must be protected, sets recovery time and point objectives, and then validates through testing."),
        ("ADVANCED", "A threat actor targets the confidentiality of data in transit. Which control is designed to counter this specific threat?",
         ["Transport layer encryption such as TLS", "Adding more RAM", "Using a longer hostname", "Defragmenting the disk"], "D",
         "Transport layer encryption such as TLS protects data while it travels across the network from interception or tampering."),
        ("ADVANCED", "Which statement correctly describes the relationship between risk and security controls?",
         ["Controls are implemented to reduce residual risk to an acceptable level", "Controls always eliminate all risk", "Risk is independent of controls", "Controls increase risk by adding complexity without benefit"], "D",
         "Controls manage risk by reducing likelihood or impact, leaving a manageable residual risk rather than eliminating risk entirely."),
    ],
    157: [
        ("BEGINNER", "What is phishing?",
         ["A social engineering attack that uses deceptive messages to trick victims into revealing information", "A hardware failure", "A type of encryption", "A backup strategy"], "A",
         "Phishing deceives users into divulging sensitive data such as passwords by sending messages that appear legitimate."),
        ("BEGINNER", "Which attack aims to make a service unavailable by overwhelming it with requests?",
         ["Denial-of-service", "SQL injection", "Phishing", "Man-in-the-middle"], "A",
         "A denial-of-service attack floods a service with traffic or requests until it can no longer respond to legitimate users."),
        ("BEGINNER", "What is a vulnerability in the context of cybersecurity?",
         ["A weakness that can be exploited to compromise a system", "A type of firewall", "A strong password", "A backup tape"], "A",
         "A vulnerability is a flaw or weakness in a system, process, or configuration that an attacker could exploit."),
        ("BEGINNER", "What is social engineering?",
         ["Manipulating people into performing actions or divulging information", "Designing user interfaces", "Compiling source code", "Encoding data"], "B",
         "Social engineering exploits human psychology rather than technical flaws to get people to reveal information or take harmful actions."),
        ("BEGINNER", "Which attack involves injecting malicious SQL code into an application query?",
         ["SQL injection", "ARP poisoning", "Smurf attack", "Teardrop attack"], "B",
         "SQL injection inserts malicious SQL into an application's query so the database executes unintended commands."),
        ("BEGINNER", "What is an exploit?",
         ["Code or a technique that takes advantage of a vulnerability", "A firewall rule", "An encryption key", "A type of backup"], "B",
         "An exploit is a specific piece of code or method that leverages a vulnerability to compromise a system."),
        ("BEGINNER", "Which attack is performed from many compromised machines at once?",
         ["A distributed denial-of-service attack", "A brute force attack on one host", "A phishing email", "A single packet sniffing session"], "C",
         "A DDoS attack uses a large number of compromised devices to flood a target with traffic from many sources simultaneously."),
        ("BEGINNER", "What is a zero-day vulnerability?",
         ["A vulnerability unknown to the vendor with no available patch", "A bug fixed on release day", "A misconfigured server", "An outdated firewall"], "C",
         "A zero-day is a vulnerability that is exploited before the vendor knows about it or can issue a fix."),
        ("BEGINNER", "What is a botnet?",
         ["A collection of compromised computers controlled remotely by an attacker", "A single infected laptop", "A type of firewall", "A wireless router"], "D",
         "A botnet is a network of infected machines that an attacker controls remotely, often used to launch DDoS attacks."),
        ("BEGINNER", "Which type of attack secretly intercepts and relays communication between two parties?",
         ["Man-in-the-middle", "Phishing", "Spam", "Key logging"], "D",
         "A man-in-the-middle attack positions the attacker between two parties so they can read and alter the traffic."),
        ("INTERMEDIATE", "An employee receives an email that appears to be from the CEO requesting urgent wire transfers. Which attack is this?",
         ["Business email compromise", "A distributed denial-of-service", "A man-in-the-middle", "A port scan"], "A",
         "Business email compromise impersonates a senior figure to trick staff into transferring money or data."),
        ("INTERMEDIATE", "A website stores passwords in plaintext and an attacker dumps the database. Which weakness was directly exploited?",
         ["The failure to hash stored passwords", "The use of TLS", "The length of the URL", "The size of the database"], "A",
         "Storing passwords as plaintext means a database breach instantly reveals every account's password to the attacker."),
        ("INTERMEDIATE", "An attacker changes a website's DNS record so users reach a malicious copy. Which attack is this?",
         ["DNS hijacking", "SQL injection", "Phishing via SMS", "Credential stuffing"], "A",
         "DNS hijacking redirects users to a fake site by tampering with the DNS resolution records."),
        ("INTERMEDIATE", "Which of the following is the best indicator that an email may be phishing?",
         ["The sender address differs slightly from the legitimate domain", "The email is sent during business hours", "The message contains a company logo", "The email was received from a colleague"], "B",
         "A sender address that differs subtly from the real domain, such as a misspelling, is a common sign of phishing."),
        ("INTERMEDIATE", "An attacker submits more data than a buffer can hold to run malicious code. Which attack is this?",
         ["A buffer overflow", "A ping sweep", "A DNS spoof", "A spear phishing email"], "B",
         "A buffer overflow occurs when data written past a buffer's boundary overwrites adjacent memory and can execute code."),
        ("INTERMEDIATE", "Which activity best describes a threat hunter's main task?",
         ["Proactively searching for signs of compromise in the environment", "Installing new firewalls", "Designing the company logo", "Writing end-user documentation"], "B",
         "Threat hunting actively looks for indicators of compromise that automated tools may have missed."),
        ("INTERMEDIATE", "A log review shows requests containing the string OR 1=1. Which attack was likely attempted?",
         ["SQL injection", "A buffer overflow", "A DDoS flood", "A man-in-the-middle"], "C",
         "SQL injection payloads often manipulate WHERE clauses with expressions such as OR 1=1 to bypass logic."),
        ("INTERMEDIATE", "Which vulnerability class allows an attacker to inject scripts into web pages viewed by other users?",
         ["Cross-site scripting (XSS)", "Denial of service", "DNS hijacking", "Physical tampering"], "C",
         "XSS lets an attacker inject client-side scripts that run in the browser of other users who view the affected page."),
        ("INTERMEDIATE", "An attacker exploits a flaw on one host and then uses that foothold to reach other systems. Which term describes this movement?",
         ["Lateral movement", "Phishing", "Egress filtering", "Data minimization"], "D",
         "Lateral movement is the technique of moving from one compromised system to others inside the network."),
        ("INTERMEDIATE", "Which sequence best represents the phases of a typical cyber kill chain?",
         ["Reconnaissance, weaponization, delivery, exploitation, and command and control", "Exploitation, patching, backup, recovery", "Delivery, design, testing, launch", "Coding, compiling, linking, executing"], "D",
         "The cyber kill chain describes an attack as progressing through reconnaissance, weaponization, delivery, exploitation, and command and control."),
        ("ADVANCED", "A zero-day exploit is being used in the wild while no patch exists. Which response is most appropriate?",
         ["Deploy compensating controls such as behavior detection and network segmentation", "Wait for the next software release", "Disable all user accounts", "Increase the password expiration period"], "A",
         "Without a patch, compensating controls reduce exposure by detecting the exploit's behavior and containing affected systems."),
        ("ADVANCED", "Which analysis technique examines the structure and behavior of a suspicious file without executing it?",
         ["Static analysis", "Dynamic analysis", "Fuzzing", "Packet capture"], "A",
         "Static analysis inspects a file's structure, strings, and code without running it, avoiding the risk of infection."),
        ("ADVANCED", "An attacker uses a compromised account to gain domain admin rights. Which controls would most directly limit this?",
         ["Privileged access management and monitoring of high-privilege accounts", "Shortening all passwords", "Removing the firewall", "Disabling audit logging"], "A",
         "Managing and monitoring privileged accounts prevents attackers from silently gaining and abusing elevated rights."),
        ("ADVANCED", "Which best practice most reduces the impact of a credential-stuffing attack?",
         ["Enforcing unique passwords and enabling multi-factor authentication", "Using the same password everywhere", "Increasing login timeout", "Deleting all user sessions hourly"], "B",
         "Unique passwords stop reused credentials from working across sites, and MFA blocks even valid passwords from being used alone."),
        ("ADVANCED", "A threat actor profiles a target using publicly available information. Which phase of the attack lifecycle does this represent?",
         ["Reconnaissance", "Exploitation", "Installation", "Action on objectives"], "B",
         "Reconnaissance is the early phase where attackers gather public information about a target to plan the attack."),
        ("ADVANCED", "Which of the following is an example of a supply chain attack?",
         ["Compromising a software update to distribute malware to downstream customers", "Phishing the CEO", "Port scanning a website", "Stealing a laptop"], "B",
         "A supply chain attack infects a trusted vendor or product, then spreads to every customer who uses that software or update."),
        ("ADVANCED", "Which MITRE ATT&CK technique is commonly used by attackers to maintain persistence on a host?",
         ["Creating scheduled tasks or registry run keys", "Changing the wallpaper", "Defragmenting the disk", "Renaming the computer"], "C",
         "Scheduled tasks and run keys survive reboots and restart the malicious code automatically, providing persistence."),
        ("ADVANCED", "Which detection method is most effective against previously unknown malware?",
         ["Behavior-based detection and sandboxing", "Signature matching only", "Reading the file extension", "Counting open ports"], "C",
         "Behavior-based detection and sandboxing observe what code does rather than matching known signatures, catching novel threats."),
        ("ADVANCED", "An attacker encrypts files and demands payment. Which two terms best describe this incident?",
         ["Ransomware and extortion", "Phishing and smishing", "DoS and DDoS", "Spoofing and sniffing"], "D",
         "Ransomware encrypts victim files and the attacker extorts payment to decrypt them."),
        ("ADVANCED", "Which control is most effective at preventing lateral movement within a network?",
         ["Micro-segmentation combined with least privilege across segments", "Removing antivirus", "A single shared admin account", "Allowing unrestricted internal traffic"], "D",
         "Micro-segmentation splits the network into small zones and enforces least privilege, so a breach cannot easily spread."),
    ],
    158: [
        ("BEGINNER", "What is authentication?",
         ["The process of verifying who a user is", "The process of backing up data", "The process of compressing files", "The process of encrypting email"], "A",
         "Authentication confirms a user's identity by checking evidence such as passwords, tokens, or biometrics."),
        ("BEGINNER", "What is authorization?",
         ["Determining what actions an authenticated user may perform", "Creating new user accounts", "Renewing a TLS certificate", "Scanning for malware"], "A",
         "Authorization decides which resources and actions an authenticated identity is permitted to access."),
        ("BEGINNER", "What is multi-factor authentication?",
         ["Requiring two or more independent types of evidence to verify identity", "Using one very long password", "Logging in twice a day", "Sharing passwords with coworkers"], "A",
         "MFA requires evidence from two or more categories, such as knowledge, possession, and inherence, to verify identity."),
        ("BEGINNER", "Which of the following is an example of a strong password policy?",
         ["Long, unique, and unpredictable passphrases", "Using your birth date", "Reusing the same password for all sites", "A four-digit PIN only"], "B",
         "Long and unique passphrases resist guessing and cannot be reused across accounts."),
        ("BEGINNER", "A password is a factor belonging to which category?",
         ["Something you know", "Something you have", "Something you are", "Somewhere you are"], "B",
         "Knowledge factors such as passwords and PINs are classified as something the user knows."),
        ("BEGINNER", "A fingerprint scan is a factor belonging to which category?",
         ["Something you are", "Something you know", "Something you have", "Something you remember"], "B",
         "Biometrics such as fingerprints belong to the inherence category, described as something you are."),
        ("BEGINNER", "A hardware security key is a factor belonging to which category?",
         ["Something you have", "Something you know", "Something you are", "Something you want"], "C",
         "Physical devices such as security keys fall under the possession category, something you have."),
        ("BEGINNER", "What is single sign-on (SSO)?",
         ["Authenticating once to gain access to multiple related systems", "Logging in with multiple passwords", "Signing documents digitally", "Sharing one account among users"], "C",
         "SSO lets a user authenticate a single time and then access multiple systems without re-entering credentials."),
        ("BEGINNER", "What is an access control list (ACL)?",
         ["A list of permissions attached to a resource", "A list of employees", "A network diagram", "A backup schedule"], "D",
         "An ACL specifies which subjects can access a resource and what operations they are allowed to perform."),
        ("BEGINNER", "What is an identity provider (IdP)?",
         ["A service that authenticates users and issues identity assertions", "A password manager", "A hardware firewall", "A load balancer"], "D",
         "An identity provider verifies users and issues claims or tokens that other applications trust."),
        ("INTERMEDIATE", "Which standard enables a user to log in to many sites using an existing identity such as Google or Microsoft?",
         ["OpenID Connect", "FTP", "SMTP", "RDP"], "A",
         "OpenID Connect builds on OAuth 2.0 to let relying parties verify a user's identity through an external provider."),
        ("INTERMEDIATE", "A user must enter a one-time code from a mobile app to log in. Which MFA factor does the phone app represent?",
         ["Something you have", "Something you know", "Something you are", "Someone you trust"], "A",
         "A code generated on a device the user possesses demonstrates the possession factor."),
        ("INTERMEDIATE", "Which attack is most directly prevented by multi-factor authentication?",
         ["A stolen password being used alone to log in", "A power outage", "A slow network", "Disk space exhaustion"], "A",
         "Even if a password is stolen, MFA blocks login because the attacker does not possess the additional factor."),
        ("INTERMEDIATE", "An employee is transferred between departments. Which IAM action must occur?",
         ["Update role memberships and adjust entitlements", "Delete the employee's records", "Reboot the server", "Change the department's email domain"], "B",
         "Role memberships and entitlements must be updated so the employee has access appropriate to the new department."),
        ("INTERMEDIATE", "Which term describes periodically verifying that a user's access is still needed?",
         ["Access recertification", "Password rotation", "Log retention", "Traffic shaping"], "B",
         "Access recertification reviews users and their entitlements to remove access that is no longer required."),
        ("INTERMEDIATE", "After a successful login, which mechanism carries the user's identity and attributes to the target application?",
         ["An identity token or assertion", "A network cable", "A MAC address", "A cookie from the browser cache only"], "B",
         "Tokens or assertions issued by the identity provider convey identity claims to the application after login."),
        ("INTERMEDIATE", "What is the primary purpose of single sign-on in an enterprise?",
         ["To reduce password fatigue and centralize authentication", "To encrypt all network traffic", "To block phishing emails", "To monitor disk usage"], "C",
         "SSO centralizes authentication so users remember fewer credentials and the organization can enforce consistent policies."),
        ("INTERMEDIATE", "Which concept requires two different people to be involved in approving a sensitive action?",
         ["Separation of duties", "Single sign-on", "Load balancing", "Password hashing"], "C",
         "Separation of duties spreads critical actions across multiple people to reduce fraud and accidental abuse."),
        ("INTERMEDIATE", "Which IAM practice automatically removes accounts when employees leave the company?",
         ["Automated deprovisioning", "Password expiration", "Session pooling", "Log archiving"], "D",
         "Automated deprovisioning revokes an ex-employee's accounts and entitlements promptly, preventing continued access."),
        ("INTERMEDIATE", "What does a session token represent after a successful login?",
         ["Proof that the user was authenticated for the current session", "The user's home address", "The server's IP address", "The user's search history"], "D",
         "A session token proves the user already authenticated and lets the application recognize them during the session."),
        ("ADVANCED", "Which scenario best demonstrates privilege escalation?",
         ["A standard user exploits a flaw to gain administrative rights", "A user changes their own password", "An admin installs a printer", "A user views their own files"], "A",
         "Privilege escalation occurs when an attacker or user obtains more privileges than they are entitled to."),
        ("ADVANCED", "When designing a role-based access control model, what is the correct first step?",
         ["Identify roles based on job functions, then assign permissions", "Assign permissions randomly", "Create every account as admin", "Remove all access control"], "A",
         "RBAC starts by defining roles from job functions and then grants each role the permissions its function needs."),
        ("ADVANCED", "Which attack involves using previously stolen username and password pairs against many websites?",
         ["Credential stuffing", "Man-in-the-middle", "DNS spoofing", "Port scanning"], "A",
         "Credential stuffing reuses leaked username and password combinations across many sites, exploiting password reuse."),
        ("ADVANCED", "Which MFA implementation is most resistant to phishing?",
         ["FIDO2/WebAuthn hardware authenticators", "SMS one-time codes", "Email one-time codes", "Security questions"], "B",
         "FIDO2/WebAuthn devices bind authentication to the specific site, so phishing sites cannot relay or replay the factor."),
        ("ADVANCED", "Which technique prevents password reuse across accounts while maintaining usability?",
         ["A password manager generating unique passwords", "Using the same password everywhere", "Writing passwords on sticky notes", "Shortening passwords to save time"], "B",
         "A password manager creates and stores a unique strong password per account, removing the need to remember each one."),
        ("ADVANCED", "In OAuth 2.0, what does the authorization code flow primarily protect against?",
         ["Exposing the access token to the browser and malicious scripts", "Slow network latency", "Disk corruption", "CPU overheating"], "B",
         "The authorization code flow keeps the access token away from the browser, so page scripts cannot steal it."),
        ("ADVANCED", "Which IAM design principle most reduces the blast radius of a compromised service account?",
         ["Scoping service accounts to least privilege and rotating their credentials", "Giving service accounts full admin rights", "Sharing one service account across all apps", "Never rotating credentials"], "C",
         "Least-privilege scoping limits what a stolen service account can do, and rotation shortens the window of misuse."),
        ("ADVANCED", "Which control prevents an attacker with a stolen admin session from acting indefinitely?",
         ["Session timeouts, reauthentication, and token revocation", "Longer passwords", "More memory", "A larger monitor"], "C",
         "Short session lifetimes, reauthentication, and revocation limit how long a stolen session token remains useful."),
        ("ADVANCED", "Which policy best enforces least privilege when granting cloud permissions?",
         ["Use fine-grained policies with a deny-by-default model", "Grant every user full admin access", "Allow all permissions to everyone", "Use a single shared root account"], "D",
         "Fine-grained, deny-by-default policies ensure users receive exactly the permissions required and nothing more."),
        ("ADVANCED", "Which approach correctly enforces separation of duties for wire transfers?",
         ["Require different users to initiate and approve each transfer", "Let one person do both steps", "Allow anyone to approve transfers", "Remove the approval step entirely"], "D",
         "Requiring different users for initiating and approving transfers prevents a single person from committing fraud."),
    ],
    159: [
        ("BEGINNER", "What is malware?",
         ["Software designed to harm or exploit systems", "A hardware upgrade", "A backup utility", "A network cable"], "A",
         "Malware is any software intentionally created to damage, disrupt, or gain unauthorized access to systems."),
        ("BEGINNER", "What is a computer virus?",
         ["Malware that replicates by infecting files or programs", "A self-replicating worm", "A firewall rule", "A type of encryption"], "A",
         "A virus attaches itself to legitimate files or programs and spreads when those hosts are executed."),
        ("BEGINNER", "What is a worm?",
         ["Self-replicating malware that spreads without user action", "A type of antivirus", "A password cracker", "A browser plugin"], "A",
         "A worm replicates itself across networks automatically, without needing to attach to a host file or be opened."),
        ("BEGINNER", "What is ransomware?",
         ["Malware that encrypts files and demands payment", "Software that blocks pop-ups", "A type of firewall", "A secure browser"], "B",
         "Ransomware encrypts the victim's data and demands a ransom payment to provide the decryption key."),
        ("BEGINNER", "What is a Trojan horse?",
         ["Malware disguised as legitimate software", "A hardware keylogger", "A router", "An encryption algorithm"], "B",
         "A Trojan disguises itself as a legitimate program to trick users into installing it, then performs malicious actions."),
        ("BEGINNER", "What is a rootkit?",
         ["Malware that hides its presence and allows continued access", "An ad blocker", "A packet filter", "A disk defragmenter"], "B",
         "A rootkit conceals its own presence and can grant attackers persistent privileged access to a system."),
        ("BEGINNER", "What is spyware?",
         ["Malware that secretly collects information about a user", "A firewall", "A VPN", "A password manager"], "C",
         "Spyware covertly monitors user activity and gathers information such as keystrokes and browsing habits."),
        ("BEGINNER", "What is adware?",
         ["Software that displays unwanted advertisements", "A type of backup", "A secure messaging app", "An email filter"], "C",
         "Adware bombards the user with unwanted ads and often tracks behavior to target those ads."),
        ("BEGINNER", "What is the main purpose of antivirus software?",
         ["To detect and remove malware", "To speed up the CPU", "To compress video files", "To manage printers"], "D",
         "Antivirus software scans for, detects, and removes malicious software to keep systems protected."),
        ("BEGINNER", "What is signature-based malware detection?",
         ["Matching files against a database of known malware patterns", "Analyzing disk fragmentation", "Measuring network speed", "Monitoring battery life"], "D",
         "Signature-based detection compares file content against a database of fingerprints of known malware."),
        ("INTERMEDIATE", "Which malware type spreads automatically across a network without attaching to a host file?",
         ["A worm", "A file infector virus", "A logic bomb", "A rootkit"], "A",
         "Worms self-propagate over networks on their own, unlike viruses that require a host file or user action."),
        ("INTERMEDIATE", "Which defense most reliably stops ransomware from encrypting backups?",
         ["Immutable or air-gapped backups", "Longer filenames", "A faster network card", "More RAM"], "A",
         "Immutable or air-gapped backups cannot be modified by ransomware, so data can always be restored."),
        ("INTERMEDIATE", "A program hides deep in the operating system to evade detection and keep access open. Which malware is this?",
         ["A rootkit", "Adware", "A screen saver", "A browser cookie"], "A",
         "Rootkits operate at privileged levels of the OS to hide their presence and maintain attacker access."),
        ("INTERMEDIATE", "Which technique do modern email gateways use to inspect suspicious attachments safely?",
         ["Sandboxing attachments in an isolated environment", "Printing them for review", "Renaming them", "Deleting them instantly"], "B",
         "Sandboxing executes attachments in an isolated environment to observe their behavior without risking the real network."),
        ("INTERMEDIATE", "Which of the following is the most effective user-level defense against malware?",
         ["Regular patching combined with security awareness", "Downloading software from any website", "Disabling the firewall", "Sharing passwords"], "B",
         "Patching closes vulnerabilities that malware exploits, while awareness prevents users from falling for malicious downloads."),
        ("INTERMEDIATE", "What does an endpoint detection and response (EDR) tool provide beyond traditional antivirus?",
         ["Continuous monitoring, behavioral analysis, and response capabilities", "Faster internet", "Better graphics", "More storage"], "B",
         "EDR continuously monitors endpoints, analyzes behavior, and enables investigation and response beyond signature scanning."),
        ("INTERMEDIATE", "Which behavior strongly suggests a host is part of a botnet?",
         ["Frequent outbound connections to a known command-and-control server", "A fast login screen", "Low CPU usage", "A quiet fan"], "C",
         "Regular connections to a command-and-control server are a hallmark of a machine participating in a botnet."),
        ("INTERMEDIATE", "Which defense is most effective against fileless attacks that run in memory?",
         ["Application whitelisting and monitoring of scripting engines", "Signature scanning of files on disk", "Defragmenting the disk", "Increasing swap space"], "C",
         "Fileless attacks leave no malicious file on disk, so allowlisting applications and monitoring script hosts stop them."),
        ("INTERMEDIATE", "Which step is the highest priority when responding to a ransomware infection?",
         ["Isolate affected hosts from the network", "Format the hard drive", "Email all employees", "Install a new browser"], "D",
         "Isolating infected hosts immediately limits how far the ransomware can spread to other systems and data."),
        ("INTERMEDIATE", "Which technique limits what fileless malware can do through PowerShell?",
         ["Restricting and logging PowerShell with Constrained Language Mode", "Deleting PowerShell", "Granting all users admin rights", "Disabling the firewall"], "D",
         "Constrained Language Mode restricts PowerShell capabilities and logging reveals malicious usage, hampering fileless attacks."),
        ("ADVANCED", "Which of the following best describes a polymorphic virus?",
         ["Malware that changes its code signature on every infection to evade detection", "A virus that never changes", "A virus that deletes itself", "A virus that only targets printers"], "A",
         "Polymorphic viruses mutate their code with each infection so signature-based detection cannot match them."),
        ("ADVANCED", "Which analysis technique runs a suspicious binary in an isolated virtual machine to observe its behavior?",
         ["Dynamic analysis", "Static analysis", "String extraction", "File renaming"], "A",
         "Dynamic analysis executes the sample in a controlled sandbox and records its runtime behavior safely."),
        ("ADVANCED", "When building a malware defense strategy, which order best reduces exposure?",
         ["Patch assets, restrict admin rights, enable application allowlisting, and deploy EDR", "Deploy EDR last after all malware is present", "Disable updates first", "Remove all security tools"], "A",
         "Patching and limiting privileges close the main infection routes before detection tools add visibility and response."),
        ("ADVANCED", "Which of the following is the strongest evidence that a machine is compromised?",
         ["A normal process spawning cmd or PowerShell and making network connections", "A blue desktop wallpaper", "Low disk usage", "A recent reboot"], "B",
         "Legitimate processes spawning command shells with network activity is a strong indicator of malicious code running."),
        ("ADVANCED", "Why is memory forensics important when analyzing an unknown malware sample?",
         ["It can reveal code and data that never touch the disk, such as decrypted payloads and injected code", "It is the only way to defragment the hard drive", "It speeds up the infected computer", "It replaces the need for network and host logs"], "A",
         "Memory forensics inspects a RAM image to recover artifacts like injected code, decrypted payloads, and running process details that never reach the disk."),
        ("ADVANCED", "Which technique prevents macro-based malware in Office documents?",
         ["Blocking macros from running unless signed by a trusted publisher", "Opening all documents in full screen", "Storing documents in the cloud", "Naming documents with .txt extensions"], "B",
         "Restricting macros to trusted signed publishers stops macro malware that arrives in ordinary Office files."),
        ("ADVANCED", "Which defense most effectively limits damage from a brand-new ransomware strain?",
         ["Robust offline backups and endpoint isolation capabilities", "A single antivirus signature", "Slower internet", "More monitors"], "C",
         "Offline backups let you restore data after encryption, and isolation stops the strain from spreading."),
        ("ADVANCED", "In an incident response for a Trojan downloader, which action should come last?",
         ["Restore from clean backups after containment and eradication", "Isolate the host", "Collect forensic evidence", "Disconnect from the network"], "C",
         "Recovery and restoration happen only after the malware is contained, evidence is collected, and it is eradicated."),
        ("ADVANCED", "Which detection method is best suited to stop a zero-day exploit chain?",
         ["Behavioral monitoring and exploit mitigation", "Updating signatures hourly", "Scanning filenames", "Counting running services"], "D",
         "Behavioral monitoring and exploit mitigations catch novel attack techniques that signatures cannot identify."),
        ("ADVANCED", "Which of these is a characteristic of a true fileless attack?",
         ["No malicious executable is written to disk; it runs in memory", "A large virus file is dropped to disk", "It only spreads by USB", "It requires administrator installation"], "D",
         "Fileless attacks execute directly in memory, leaving little or no trace on disk for signature scanners to find."),
    ],
    160: [
        ("BEGINNER", "What is an IT security audit?",
         ["A systematic review of security controls and compliance", "A hardware upgrade", "A marketing campaign", "A backup rotation"], "A",
         "A security audit evaluates whether an organization's controls, policies, and practices meet requirements."),
        ("BEGINNER", "What does compliance mean in cybersecurity?",
         ["Meeting the laws, regulations, and policies that apply to the organization", "Avoiding all software updates", "Using stronger passwords", "Deleting old logs"], "A",
         "Compliance means the organization satisfies the legal, regulatory, and internal security requirements that govern it."),
        ("BEGINNER", "What does GDPR primarily regulate?",
         ["The processing of personal data of individuals in the EU", "Network cable standards", "Server room temperature", "Email server capacity"], "A",
         "The General Data Protection Regulation governs how organizations collect, store, and process EU residents' personal data."),
        ("BEGINNER", "What is the purpose of an audit trail?",
         ["To record who did what and when for accountability", "To increase internet speed", "To compress files", "To block ads"], "B",
         "An audit trail provides a chronological record of actions and events so activity can be reviewed and traced."),
        ("BEGINNER", "What does HIPAA regulate?",
         ["The protection of health information in the US", "Credit card fees", "Cloud storage pricing", "Email spam filters"], "B",
         "HIPAA establishes requirements for protecting the privacy and security of protected health information in the US."),
        ("BEGINNER", "What does PCI DSS govern?",
         ["The security of cardholder data", "Server cooling", "Network cabling", "Software licensing"], "B",
         "The Payment Card Industry Data Security Standard mandates controls for any organization handling cardholder data."),
        ("BEGINNER", "What is an audit log?",
         ["A chronological record of events generated by a system", "A list of employee names", "A backup tape", "A firewall rule"], "C",
         "An audit log captures events such as logins, changes, and errors so they can be reviewed later."),
        ("BEGINNER", "What does SOX require of public companies?",
         ["Internal controls over financial reporting", "Faster backups", "More employees", "Shorter passwords"], "C",
         "The Sarbanes-Oxley Act requires public companies to establish and maintain effective internal controls over financial reporting."),
        ("BEGINNER", "What is a risk assessment?",
         ["The process of identifying and evaluating risks to the organization", "A performance review", "A software install", "A marketing survey"], "D",
         "A risk assessment identifies threats and vulnerabilities and evaluates the likelihood and impact of losses."),
        ("BEGINNER", "What does ISO/IEC 27001 specify?",
         ["Requirements for an information security management system", "Physical office layouts", "Recruitment policies", "Product packaging"], "D",
         "ISO/IEC 27001 defines the requirements for establishing, operating, and improving an ISMS."),
        ("INTERMEDIATE", "Which audit activity verifies that actual controls match documented policies?",
         ["Control testing", "Password resets", "Server reboots", "Software installation"], "A",
         "Control testing checks that the controls described in policy are actually implemented and working as intended."),
        ("INTERMEDIATE", "Which regulation most directly affects how a company stores European customers' personal data?",
         ["GDPR", "HIPAA", "SOX", "PCI DSS"], "A",
         "GDPR applies to the processing of personal data of EU individuals regardless of where the company is located."),
        ("INTERMEDIATE", "Which document defines the rules employees must follow regarding information security?",
         ["The security policy", "The marketing plan", "The employee directory", "The product roadmap"], "A",
         "The security policy sets out the expectations and rules for how information and systems must be protected."),
        ("INTERMEDIATE", "Which of the following is an example of an audit finding?",
         ["A server running unsupported software with known vulnerabilities", "A printer running low on ink", "A bright office", "A fast network"], "B",
         "An audit finding is a discovered issue such as unsupported software that must be corrected."),
        ("INTERMEDIATE", "Which standard is best suited to certify an organization's information security management system?",
         ["ISO/IEC 27001", "IEEE 802.11", "RFC 791", "HTML5"], "B",
         "ISO/IEC 27001 is the internationally recognized certification standard for information security management systems."),
        ("INTERMEDIATE", "What is the difference between a vulnerability scan and a penetration test?",
         ["A scan identifies known weaknesses while a pen test actively exploits them to assess real impact", "They are identical", "A pen test is faster than a scan", "A scan requires physical access"], "B",
         "Vulnerability scanning finds potential weaknesses, while penetration testing attempts to exploit them to prove impact."),
        ("INTERMEDIATE", "Which audit evidence is most reliable?",
         ["Raw logs with verifiable timestamps generated by the system", "A colleague's memory", "A verbal promise", "An untracked spreadsheet"], "C",
         "System-generated logs with verifiable timestamps are reliable, tamper-evident evidence for an audit."),
        ("INTERMEDIATE", "Which control would an auditor most likely expect for handling cardholder data?",
         ["Encrypting stored card data and restricting access", "Printing card numbers", "Posting card numbers on the wall", "Using no passwords"], "C",
         "PCI DSS requires stored cardholder data to be encrypted and access to it restricted to authorized personnel."),
        ("INTERMEDIATE", "Which activity is required for ongoing compliance rather than a one-time project?",
         ["Continuous monitoring and periodic reviews", "A single annual meeting", "One-time software purchase", "A single password reset"], "D",
         "Compliance is maintained through continuous monitoring, recurring reviews, and ongoing remediation."),
        ("INTERMEDIATE", "Which regulation grants individuals the right to request deletion of their personal data?",
         ["GDPR's right to erasure", "SOX", "PCI DSS", "HIPAA's billing rules"], "D",
         "Under GDPR, individuals can request that organizations erase their personal data, subject to legal limits."),
        ("ADVANCED", "Which of the following best describes a material control deficiency found during an audit?",
         ["A significant weakness that could allow a material misstatement or serious security failure", "A typo in a document", "A slow printer", "A minor cosmetic issue"], "A",
         "A material deficiency is serious enough that it could lead to a significant misstatement or unacceptable security risk."),
        ("ADVANCED", "During a penetration test, the client asks the tester to expand scope to the production billing system. What should the tester do first?",
         ["Confirm the scope change and obtain written authorization before proceeding", "Attack it immediately", "Refuse without discussing", "Ignore the request"], "A",
         "Expanding scope requires explicit written authorization so testing stays legal and within agreed boundaries."),
        ("ADVANCED", "Which practice best demonstrates evidence of compliance with ISO/IEC 27001?",
         ["Maintaining documented policies, controls, and audit records reviewed regularly", "Keeping no documentation", "Deleting all logs monthly", "Relying on verbal assurances"], "A",
         "ISO/IEC 27001 requires documented policies, implemented controls, and records that prove continuous compliance."),
        ("ADVANCED", "Which control best demonstrates that an organization can prove accountability for user actions?",
         ["Centralized logging with tamper-evident audit trails", "Deleting logs after a day", "Sharing accounts among staff", "Disabling access logs"], "B",
         "Tamper-evident, centralized audit trails show exactly who did what, which is essential for accountability."),
        ("ADVANCED", "An auditor finds that security patches are applied inconsistently. Which recommendation is most appropriate?",
         ["Implement a formal patch management program with SLAs and verification", "Ignore the finding", "Apply patches only when convenient", "Disable all updates"], "B",
         "A formal patch management program with defined timelines and verification ensures vulnerabilities are fixed consistently."),
        ("ADVANCED", "Which GDPR principle is directly supported by encrypting and pseudonymizing personal data?",
         ["Security of processing, also known as integrity and confidentiality", "Data portability", "Storage minimization only", "Transparency only"], "B",
         "Encryption and pseudonymization are technical measures that protect personal data, fulfilling the security-of-processing principle."),
        ("ADVANCED", "Which approach best prepares an organization for an external compliance audit?",
         ["Maintain evidence of continuous monitoring, documented policies, and periodic internal audits", "Hide all records", "Delay until the auditor arrives", "Conduct the audit for them"], "C",
         "Continuous monitoring, current documentation, and internal audits build the evidence an external auditor expects to see."),
        ("ADVANCED", "In a red team exercise, which outcome provides the most value to an organization?",
         ["Validated detection and response effectiveness against realistic attack paths", "A list of employee salaries", "A faster network", "A new logo"], "C",
         "A red team validates how well defenders detect and respond to realistic attacks, driving real security improvement."),
        ("ADVANCED", "Which of the following is the correct order for a typical internal audit?",
         ["Plan, gather evidence, test controls, report findings, track remediation", "Report, plan, test, gather, remediate", "Remediate, plan, report, test, gather", "Test, remediate, plan, gather, report"], "D",
         "An internal audit moves from planning through evidence collection, control testing, reporting, and finally remediation tracking."),
        ("ADVANCED", "Which statement about audit logs and legal requirements is correct?",
         ["Logs supporting compliance must be retained for the period defined by relevant regulations and standards", "Logs should be deleted immediately", "Log retention is always one day", "Logs are never required by law"], "D",
         "Regulations such as PCI DSS and GDPR require retaining audit logs for defined periods to support investigations and compliance."),
    ],
}
