# -*- coding: utf-8 -*-
"""
Question bank for subject 13: NET103 - Routing & Switching.
Category: Computer Networks.

Topics:
  61: Switching Basics & VLANs
  62: Routing & RIP
  63: OSPF & Link State
  64: BGP & EIGRP
  65: NAT & Network Devices

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    61: [
        ("BEGINNER", "At which OSI model layer does a standard Ethernet switch operate?",
         ["Layer 1", "Layer 2", "Layer 3", "Layer 4"], "B",
         "A standard Ethernet switch forwards frames based on MAC addresses, which places it at Layer 2 (Data Link) of the OSI model."),
        ("BEGINNER", "What does VLAN stand for in networking?",
         ["Variable Link Access Network", "Virtual Area Line Network", "Virtual Local Area Network", "Vendor Local Area Network"], "C",
         "VLAN stands for Virtual Local Area Network, which logically separates broadcast domains on a switch."),
        ("BEGINNER", "What is the default VLAN created on a typical managed switch?",
         ["VLAN 100", "VLAN 0", "VLAN 5", "VLAN 1"], "D",
         "VLAN 1 is the default VLAN on most managed switches and also carries management traffic by default."),
        ("BEGINNER", "How many bits are in a standard MAC address?",
         ["48", "32", "64", "16"], "A",
         "A MAC address is 48 bits long, usually written as twelve hexadecimal digits."),
        ("BEGINNER", "What does a switch do when it receives a frame whose destination MAC address is not in its MAC address table?",
         ["drops the frame", "floods the frame to all ports in the VLAN except the ingress port", "sends it to the router", "returns it to the sender"], "B",
         "An unknown unicast frame is flooded to every port in the VLAN other than the port it arrived on so the destination can respond."),
        ("BEGINNER", "Which port mode is used on a switch port that carries traffic for a single VLAN only?",
         ["trunk mode", "dynamic mode", "access mode", "promiscuous mode"], "C",
         "An access port belongs to a single VLAN and strips any VLAN tag before sending to the end device."),
        ("BEGINNER", "Which port type carries traffic for multiple VLANs between switches?",
         ["access port", "edge port", "uplink port", "trunk port"], "D",
         "A trunk port uses VLAN tagging so it can carry frames belonging to many VLANs across one link."),
        ("BEGINNER", "Which IEEE standard defines VLAN tagging on Ethernet frames?",
         ["IEEE 802.1Q", "IEEE 802.11", "IEEE 802.3", "IEEE 802.1X"], "A",
         "IEEE 802.1Q inserts a VLAN tag into the Ethernet frame so switches can identify the frame's VLAN."),
        ("BEGINNER", "What does a switch store in its MAC address table after learning a frame?",
         ["the source IP address and the port", "the source MAC address and the ingress port", "the destination MAC and the VLAN ID only", "the frame checksum"], "B",
         "The switch learns the source MAC address and records it along with the port on which it was received."),
        ("BEGINNER", "Which statement about a collision domain is true for a modern switched network?",
         ["every port shares one collision domain", "collisions are common on full-duplex links", "each switch port is its own collision domain", "switches never isolate collisions"], "C",
         "Each switch port on a full-duplex link forms its own collision domain, so frames no longer collide across ports."),
        ("INTERMEDIATE", "A switch learns MAC 00:11:22:33:44:55 on port 3. A frame now arrives destined to that MAC. How does the switch forward it?",
         ["flood it to all ports", "forward it out port 3 only", "broadcast it to the entire network", "drop it"], "C",
         "Since the MAC is already learned on port 3, the switch forwards the frame only out port 3."),
        ("INTERMEDIATE", "Two VLANs, 10 and 20, are configured on a single switch. A host in VLAN 10 sends a broadcast. What happens?",
         ["it reaches all hosts on the switch", "it is forwarded to the router first", "it only reaches hosts in VLAN 10", "it is dropped by the switch"], "D",
         "Broadcasts are confined to their own VLAN because each VLAN is a separate broadcast domain."),
        ("INTERMEDIATE", "How many bits of a 48-bit MAC address are used for the OUI (organizationally unique identifier)?",
         ["24", "16", "32", "48"], "A",
         "The first 24 bits of a MAC address form the Organizationally Unique Identifier assigned to the vendor."),
        ("INTERMEDIATE", "A switch has been running for an hour and its MAC table holds an entry for a PC that was then disconnected. What does the switch do?",
         ["keeps the entry forever", "ages the entry out after the aging timer expires", "reboots to clear it", "sends an ARP request"], "B",
         "MAC entries age out after a timeout (typically 300 seconds) so stale entries are removed automatically."),
        ("INTERMEDIATE", "Frames tagged by 802.1Q have a tag that increases the frame length by how many bytes?",
         ["2", "8", "4", "6"], "C",
         "The 802.1Q tag consists of a 2-byte Tag Protocol Identifier and a 2-byte Tag Control Information, adding 4 bytes."),
        ("INTERMEDIATE", "A host is plugged into an access port in VLAN 5 and another host into an access port in VLAN 6 on the same switch. Can the two hosts communicate directly without a router?",
         ["yes, VLANs never block traffic", "yes, because they share the switch", "only during the first 5 minutes", "no, because different VLANs are separate broadcast domains requiring routing"], "D",
         "Different VLANs are separate broadcast domains, so inter-VLAN traffic must be routed by a Layer 3 device."),
        ("INTERMEDIATE", "What does the MAC address FFFF.FFFF.FFFF represent?",
         ["the broadcast address", "a multicast group", "a unicast host address", "the switch's management address"], "A",
         "A MAC address with all bits set is the Layer 2 broadcast address, which is received by all hosts."),
        ("INTERMEDIATE", "Which VLAN should be reserved and not used for user data because it is present on all ports by default?",
         ["VLAN 4095", "VLAN 1", "VLAN 0", "the native VLAN 100"], "B",
         "VLAN 1 is present by default on all ports and is often the management VLAN, so it is best reserved and not used for user traffic."),
        ("INTERMEDIATE", "A switch must carry VLAN 10, 20 and 30 between two floors. What is the minimum number of physical links required if 802.1Q trunking is used?",
         ["three links, one per VLAN", "two links", "one trunk link", "four links"], "C",
         "A single trunk link can carry all VLANs at once because each frame is tagged with its VLAN ID."),
        ("INTERMEDIATE", "When two switches are connected by an 802.1Q trunk, how are frames from the native VLAN transmitted?",
         ["they are always dropped", "they are retagged", "they carry an extra tag", "they are sent untagged"], "D",
         "Frames of the native VLAN on an 802.1Q trunk are sent without a tag so legacy equipment can still understand them."),
        ("ADVANCED", "A network engineer must stop employees from connecting personal devices to unused wall ports in a conference room. Which solution is the best fit?",
         ["port security with a maximum MAC count", "storm control", "CDP shutdown", "802.1X port-based authentication"], "D",
         "802.1X authenticates each connected device against an AAA server, so unauthorized personal devices are denied network access."),
        ("ADVANCED", "Two switches are connected by two redundant links with spanning tree disabled. What is the most likely consequence?",
         ["frames loop endlessly and the network becomes unusable", "the switches load balance traffic", "the link bandwidth doubles", "MAC tables converge instantly"], "A",
         "Without a loop-avoidance protocol, broadcast frames circulate forever between the switches, exhausting bandwidth."),
        ("ADVANCED", "A network technician wants a switch port attached to a workstation to reach the forwarding state immediately after link up. Which spanning-tree tuning should be used?",
         ["increase the root diameter", "enable portfast on the access port", "lower the hello timer", "set the port to half duplex"], "B",
         "Portfast bypasses the spanning-tree listening and learning states so the access port forwards immediately."),
        ("ADVANCED", "In RSTP, which state replaces the traditional spanning-tree blocking state for a port that is not selected to forward?",
         ["listening", "learning", "discarding", "disabled"], "C",
         "RSTP collapses blocking, listening and disabled into a single discarding state to speed convergence."),
        ("ADVANCED", "Which type of traffic does storm control limit to protect switch resources?",
         ["only unicast frames", "only management frames", "only tagged frames", "broadcast, multicast and unknown unicast frames"], "D",
         "Storm control monitors broadcast, multicast and unknown unicast rates and suppresses them when they exceed a threshold."),
        ("ADVANCED", "A MAC flooding attack floods the switch with frames carrying random source MAC addresses. What is the goal of this attack?",
         ["fill the MAC address table so legitimate frames are flooded and can be sniffed", "force the switch to reboot", "change the native VLAN", "disable port security"], "A",
         "Once the MAC table is full, unknown frames are flooded to all ports, letting the attacker capture traffic."),
        ("ADVANCED", "On a trunk link, whose frames are transmitted without an 802.1Q tag by default on Cisco switches?",
         ["the highest numbered VLAN", "the native VLAN, which is VLAN 1 by default", "the management VLAN", "VLAN 4094"], "B",
         "Frames belonging to the configured native VLAN are sent untagged on an 802.1Q trunk, and that native VLAN is VLAN 1 by default."),
        ("ADVANCED", "What is the primary purpose of a private VLAN (PVLAN)?",
         ["increase trunk bandwidth", "provide routing between VLANs", "isolate ports within the same VLAN from each other while sharing an uplink", "tag frames with 802.1Q"], "C",
         "A PVLAN splits a broadcast domain into isolated sub-domains so members cannot talk to each other but can reach a common promiscuous port."),
        ("ADVANCED", "A router with a single physical interface must route between VLANs 10, 20 and 30 that all arrive on one trunk. Which configuration achieves this with minimal hardware?",
         ["a separate router interface per VLAN", "inter-VLAN routing with a switch virtual interface", "router-on-a-stick using subinterfaces", "policy routing per MAC"], "D",
         "Router-on-a-stick creates logical subinterfaces on one physical link, each tagged for a VLAN, minimizing hardware."),
        ("ADVANCED", "Which benefit does EtherChannel provide when four 1 Gbps links are bundled between two switches?",
         ["a single logical link of roughly 4 Gbps with redundancy", "four independent spanning-tree instances", "automatic VLAN tagging", "guaranteed delivery of every frame"], "A",
         "EtherChannel groups the four physical links into one logical link that can carry about 4 Gbps and keeps operating if a member link fails."),
    ],
    62: [
        ("BEGINNER", "Which device forwards packets between different IP networks based on Layer 3 information?",
         ["a switch", "a router", "a hub", "a bridge"], "B",
         "A router examines the destination IP address and forwards packets between networks at Layer 3."),
        ("BEGINNER", "What does a routing table contain?",
         ["MAC addresses of hosts", "DNS records", "routes to destination networks", "ARP caches"], "C",
         "A routing table stores entries that map destination networks to the next hop or interface used to reach them."),
        ("BEGINNER", "What is the term for the value a router uses to select the best path among several?",
         ["hop limit", "metric", "VLAN ID", "TTL"], "D",
         "The metric is a value assigned to a route that lets the router choose the lowest-cost best path."),
        ("BEGINNER", "What does the metric of a RIP route represent?",
         ["the number of hops", "the bandwidth of the link", "the delay in milliseconds", "the number of routers in the AS"], "A",
         "RIP's metric is a simple hop count, counting the routers a packet must pass through."),
        ("BEGINNER", "What is a next-hop router?",
         ["the router that owns the destination", "the first router along the path that a packet must be sent to", "the router with the lowest IP", "the default gateway of the source"], "B",
         "The next hop is the neighboring router to which the local router forwards a packet along the route."),
        ("BEGINNER", "Which routing protocol is a classic distance-vector protocol?",
         ["OSPF", "BGP", "RIP", "EIGRP"], "C",
         "RIP is the classic distance-vector protocol, building routes from vectors of distances to each network."),
        ("BEGINNER", "What is the default administrative distance of a directly connected route?",
         ["110", "1", "120", "0"], "D",
         "Directly connected routes have the best administrative distance of 0 because they are certain."),
        ("BEGINNER", "What does a static route require the administrator to manually define?",
         ["the destination network, the next hop or exit interface and the metric", "the route's bandwidth automatically", "the router's hostname", "the DNS server address"], "A",
         "A static route is manually entered with the destination network and the next hop or exit interface."),
        ("BEGINNER", "Which command shows a router's routing table on a Cisco device?",
         ["show interfaces", "show ip route", "show ip nat", "show vlan"], "B",
         "The command show ip route displays the routing table on a Cisco router."),
        ("BEGINNER", "What is the maximum hop count for a valid RIP route?",
         ["10", "32", "15", "255"], "C",
         "A route with a hop count of 16 is considered unreachable, so 15 is the maximum valid RIP metric."),
        ("INTERMEDIATE", "A packet arrives at a router whose routing table has no route matching the destination and no default route. What does the router do?",
         ["broadcasts the packet", "stores it for later", "drops it and sends an ICMP destination unreachable", "sends it to the MAC address of the source"], "C",
         "Without a matching route or default route the router drops the packet and returns ICMP Destination Unreachable."),
        ("INTERMEDIATE", "RIP advertisements are sent by default every how many seconds?",
         ["10", "120", "5", "30"], "D",
         "RIP broadcasts its full routing table to neighbors every 30 seconds by default."),
        ("INTERMEDIATE", "A router has a static route with administrative distance 1 and an OSPF route with administrative distance 110 to the same network. Which route is installed?",
         ["the static route is preferred because it has a lower administrative distance", "the OSPF route is always preferred", "both are installed", "the metric decides the winner instead"], "A",
         "The route with the lower administrative distance is installed first, so the static route wins over OSPF."),
        ("INTERMEDIATE", "RIP version 1 has a serious limitation compared with version 2. What is it?",
         ["it is too fast", "it does not carry subnet mask information, so VLSM is unsupported", "it requires authentication", "it uses TCP for updates"], "B",
         "RIPv1 is classful and cannot carry subnet masks, so it cannot support VLSM and CIDR."),
        ("INTERMEDIATE", "A router running RIPv2 is configured with passive-interface FastEthernet0/0. What is the effect?",
         ["RIP updates are disabled on all interfaces", "the router stops forwarding packets", "RIP advertises the network but does not send or receive updates on that interface", "RIP deletes all routes"], "C",
         "A passive interface is advertised to neighbors but does not send or process RIP updates on it."),
        ("INTERMEDIATE", "In RIP, which condition makes a route unreachable?",
         ["hop count equals 10", "the route is not refreshed for 30 seconds", "the router reboots", "hop count reaches 16"], "D",
         "A metric of 16 means infinity in RIP, making the route unreachable and removing it."),
        ("INTERMEDIATE", "A default route (0.0.0.0/0) on a stub router pointing to an ISP router represents what?",
         ["a gateway of last resort used when no more specific route matches", "the route to the local loopback", "the host route to the ISP's LAN", "a multicast route"], "A",
         "The default route acts as the gateway of last resort, catching packets for destinations with no specific route."),
        ("INTERMEDIATE", "Two routers advertise the same RIP route; one has hop count 2 and the other hop count 3. Which is installed?",
         ["the route with 3 hops because it is more specific", "the route with 2 hops because the metric is lower", "both routes are installed", "neither route is installed"], "B",
         "RIP chooses the route with the lowest hop count, so the 2-hop route is installed."),
        ("INTERMEDIATE", "What is split horizon used for in distance-vector routing?",
         ["doubling the update rate", "summarizing routes", "preventing loops by not advertising a route back out the interface it was learned on", "increasing the metric"], "C",
         "Split horizon stops a route learned on an interface from being advertised back out that same interface, preventing routing loops."),
        ("INTERMEDIATE", "A link fails and a RIP route is held in holddown. What does holddown do?",
         ["immediately switches to the best alternate route", "doubles the metric", "ignores all updates forever", "prevents regular updates from reinstating a flapping route for a set time"], "D",
         "Holddown keeps a failed route suppressed for a period so flapping routes do not bounce back and forth."),
        ("ADVANCED", "What is the term for the problem where two routers keep incrementing a route metric past the maximum during a loop?",
         ["broadcast storm", "MAC table overflow", "convergence time", "counting to infinity"], "D",
         "Counting to infinity occurs when a loop prevents convergence and the metric keeps climbing until it reaches 16 and the route is discarded."),
        ("ADVANCED", "A network engineer chooses RIPv2 for a small site with legacy equipment. Which RIPv2 feature can secure routing updates from spoofing?",
         ["MD5 authentication", "split horizon", "holddown timers", "passive interfaces"], "A",
         "RIPv2 supports MD5 authentication so routers verify updates and reject spoofed ones."),
        ("ADVANCED", "RIPv2 can be configured to aggregate several subnets into one entry. What is this called?",
         ["split horizon", "route summarization", "holddown", "poison reverse"], "B",
         "Route summarization lets RIPv2 advertise a single summarized prefix that represents several subnets, reducing table size."),
        ("ADVANCED", "RIPv2 sends its updates to which multicast address?",
         ["224.0.0.5", "255.255.255.255", "224.0.0.9", "239.255.255.250"], "C",
         "RIPv2 sends updates to the multicast group 224.0.0.9 so only RIP-enabled routers process them."),
        ("ADVANCED", "Which loop-prevention technique advertises a failed route with a metric of 16 (infinity) to actively poison it for neighbors?",
         ["split horizon", "triggered updates", "poison reverse", "holddown"], "D",
         "Poison reverse advertises the failed route back with a metric of 16 so neighbors immediately treat it as unreachable."),
        ("ADVANCED", "An organization is migrating from RIPv1 to RIPv2 so that subnet masks are exchanged. Which configuration change is required?",
         ["enable version 2 and ensure VLSM is configured on subinterfaces", "change the hello timer", "disable authentication", "remove all static routes"], "A",
         "Enabling RIPv2 on interfaces allows the protocol to carry subnet masks and therefore support VLSM."),
        ("ADVANCED", "What is the maximum number of hops a RIP network can span in a chain and still route correctly?",
         ["255", "15", "16", "30"], "B",
         "A network diameter beyond 15 hops is unreachable in RIP because 16 is infinity."),
        ("ADVANCED", "A company has a redundant backup WAN link and wants the backup default route to be used only when the RIP-learned default disappears. How is this achieved?",
         ["advertise both with equal metrics", "floating static route with a higher administrative distance", "holddown the primary route", "poison the backup route"], "C",
         "A floating static route has a higher administrative distance than RIP, so it is installed only when the RIP default route disappears."),
        ("ADVANCED", "Two RIP routers are misconfigured and keep advertising each other's routes back and forth, causing the metric to grow. What should be enabled to stop this?",
         ["larger holddown timer", "shorter update interval", "load balancing", "split horizon"], "D",
         "Split horizon prevents a route from being advertised back out the interface it was learned from, breaking the two-router loop."),
        ("ADVANCED", "A routing table must choose between a RIP route (AD 120) and an OSPF route (AD 110) to the same network with equal metrics. Which is installed and why?",
         ["OSPF, because its lower administrative distance is preferred", "RIP, because its metric is simpler", "both, for load balancing", "neither, because they conflict"], "A",
         "With different administrative distances, the router installs the route with the lower AD, so OSPF (110) beats RIP (120)."),
    ],
    63: [
        ("BEGINNER", "What type of routing protocol is OSPF?",
         ["distance vector", "link state", "path vector", "hybrid"], "B",
         "OSPF is a link-state protocol where each router builds a full map of the network topology."),
        ("BEGINNER", "What does each OSPF router flood to its neighbors to build the topology database?",
         ["its full routing table", "only its default route", "link state advertisements (LSAs)", "RIP updates"], "C",
         "OSPF routers exchange LSAs that describe their links so all routers build identical link-state databases."),
        ("BEGINNER", "What is the default administrative distance of OSPF on Cisco routers?",
         ["0", "1", "90", "110"], "D",
         "Cisco assigns OSPF the administrative distance 110, below RIP's 120 but above static and connected routes."),
        ("BEGINNER", "What is the OSPF cost of an interface with a bandwidth of 100 Mbps using the default reference bandwidth?",
         ["1", "10", "100", "1000"], "A",
         "Default cost is 100 Mbps divided by the interface bandwidth, so a 100 Mbps link has cost 1."),
        ("BEGINNER", "What does an area in OSPF represent?",
         ["a physical cable segment", "a subdivision of the network that limits the scope of LSAs and reduces routing information", "a group of routers running RIP", "a virtual private network"], "B",
         "Areas bound LSA flooding and database size, keeping OSPF scalable in large networks."),
        ("BEGINNER", "Which router ID selection order does Cisco OSPF use by default?",
         ["highest loopback address first, then highest active interface IP", "lowest IP address first", "the hostname", "the MAC address"], "C",
         "OSPF picks the highest loopback IP, then the highest active interface IP, as the router ID."),
        ("BEGINNER", "What is the default Hello interval for OSPF on a broadcast multiaccess network?",
         ["1 second", "5 seconds", "40 seconds", "10 seconds"], "D",
         "OSPF sends Hello packets every 10 seconds on broadcast networks and 30 seconds on non-broadcast links."),
        ("BEGINNER", "On a multi-access segment, which device is elected to reduce the number of adjacencies?",
         ["the designated router (DR)", "the root bridge", "the next-hop router", "the bootstrap router"], "A",
         "The DR and BDR form adjacencies with all routers on the segment, reducing LSA flooding and adjacency count."),
        ("BEGINNER", "Which OSPF neighbor state indicates that full adjacency has been established?",
         ["Two-Way", "Full", "Init", "Down"], "B",
         "The Full state means the two neighbors have synchronized their link-state databases."),
        ("BEGINNER", "Which OSPF network type uses a DR/BDR election?",
         ["point-to-point", "point-to-multipoint", "broadcast multiaccess", "virtual link"], "C",
         "Broadcast multiaccess networks such as Ethernet use a DR/BDR election to manage adjacencies."),
        ("INTERMEDIATE", "An OSPF interface cost is set to 100 manually while another path has cost 50. Which path does the router prefer?",
         ["the cost 100 path because it is larger", "both paths equally", "the cost 50 path because OSPF picks the lowest total cost", "the path advertised first"], "C",
         "OSPF sums interface costs along a path and always prefers the lowest total cost."),
        ("INTERMEDIATE", "A link fails between two OSPF routers. What does OSPF do immediately?",
         ["waits for the next RIP update", "sends triggered link-state updates to inform all routers quickly", "reboots the router", "switches to distance vector"], "D",
         "OSPF reacts to topology changes immediately by flooding new LSAs, so convergence is fast."),
        ("INTERMEDIATE", "An engineer wants to manually set the cost of a 1 Gbps link on a Cisco router. Which interface command applies a manual cost?",
         ["ip ospf cost 10", "bandwidth 100000", "cost ospf 10", "ip ospf priority 10"], "A",
         "The interface command ip ospf cost overrides the automatically computed cost."),
        ("INTERMEDIATE", "Two routers must form an OSPF adjacency but are configured with different MTUs. Which state are they likely stuck in?",
         ["Down", "Exstart", "Init", "Loading"], "B",
         "An MTU mismatch typically leaves the neighbor stuck in the Exstart state during database exchange."),
        ("INTERMEDIATE", "What is the purpose of the SPF algorithm in OSPF?",
         ["choose the MAC address", "build the neighbor table", "compute the shortest paths to all destinations in the network", "select the DR"], "C",
         "Dijkstra's SPF algorithm runs over the link-state database to compute shortest paths to every destination."),
        ("INTERMEDIATE", "A network has a fast 100 Mbps path with cost 1 and a backup 10 Mbps path with cost 10. Which path is used?",
         ["the 10 Mbps path", "both paths", "the path with the higher cost", "the 100 Mbps path because its cost is lower"], "D",
         "OSPF prefers the lower-cost path, so the 100 Mbps link is used."),
        ("INTERMEDIATE", "What happens when a router's Dead interval expires for a neighbor?",
         ["the neighbor is declared down and LSAs are re-flooded", "the neighbor becomes the DR", "the router ignores it", "the router's cost is doubled"], "A",
         "If no Hello is received before the Dead timer expires, the neighbor is considered down and the topology is updated."),
        ("INTERMEDIATE", "In a large OSPF network, why are areas used?",
         ["to reduce the number of MAC addresses", "to limit LSA flooding and shrink the link-state database", "to increase the hop count", "to improve RIP convergence"], "B",
         "Areas confine LSAs, so routers keep only their area's database and route to others through summaries."),
        ("INTERMEDIATE", "A new OSPF router joins a segment and receives a database description packet. What happens next?",
         ["it sends RIP updates", "it becomes the root", "it requests the missing LSAs using LSU/LSAck exchanges", "it stops sending Hellos"], "C",
         "After exchanging database descriptions, the router requests and receives the LSAs it lacks until its database matches."),
        ("INTERMEDIATE", "Which network type should be configured for a frame relay hub-and-spoke topology in OSPF?",
         ["broadcast", "point-to-point broadcast", "point-to-multipoint", "loopback"], "D",
         "Point-to-multipoint treats each spoke as a point-to-point link without needing a DR, suiting hub-and-spoke frame relay."),
        ("ADVANCED", "In multi-area OSPF, which LSA type carries external routes originated by an ASBR?",
         ["Type 1", "Type 2", "Type 4", "Type 5"], "D",
         "Type 5 LSAs are the AS external LSAs originated by an ASBR to describe routes redistributed from outside OSPF."),
        ("ADVANCED", "Which router floods a Type 1 router LSA describing its own links?",
         ["every OSPF router advertises its own Type 1 LSA", "only the DR advertises Type 1 LSAs", "only the ABR", "only the ASBR"], "A",
         "Every OSPF router originates a Type 1 router LSA that describes its own interfaces and neighbors."),
        ("ADVANCED", "A network spans two areas and must connect an area to the backbone. Which type of OSPF router performs this role?",
         ["ASBR", "ABR", "DR", "BDR"], "B",
         "An Area Border Router has interfaces in the backbone and in another area, summarizing routes between them."),
        ("ADVANCED", "Which command redistributes a static route into OSPF on a Cisco router?",
         ["router ospf", "ip ospf cost", "redistribute static subnets", "network 0.0.0.0"], "C",
         "In OSPF configuration, the redistribute static subnets command injects static routes as external routes."),
        ("ADVANCED", "Which OSPF area type blocks Type 4 and Type 5 LSAs and injects only a default route, with no external or inter-area routes?",
         ["backbone area", "totally stubby area", "normal area", "transit area"], "D",
         "A totally stubby area blocks Type 4, 5 and 3 (except default) LSAs, leaving only a default route to reach outside areas."),
        ("ADVANCED", "Two OSPF routers are configured with the same router ID. What is the consequence?",
         ["adjacencies fail because the router IDs are not unique", "they form a backup adjacency", "the DR is chosen faster", "nothing happens"], "A",
         "OSPF uses router IDs to identify neighbors, so duplicate IDs prevent adjacencies from forming correctly."),
        ("ADVANCED", "To run OSPF across a non-broadcast link that does not support multicast, which configuration is required?",
         ["RIP version 1", "manual neighbor statements or point-to-point network type", "an increased cost", "a static route"], "B",
         "On non-broadcast networks OSPF needs manually defined neighbors or the point-to-point type instead of multicast Hellos."),
        ("ADVANCED", "When MD5 authentication is configured for OSPF, which part of the packet verifies the sender?",
         ["the area ID", "the router ID", "the authentication field carrying a keyed digest", "the checksum"], "C",
         "OSPF's authentication field carries the MD5 digest so neighbors verify the origin of Hello and LSA packets."),
        ("ADVANCED", "A branch router connects only to the core and must reach only the core networks. To minimize its OSPF database, which area type is most appropriate?",
         ["backbone area 0", "a transit area", "an external area", "a stub area with a default route"], "D",
         "A stub area keeps only internal and default routes, minimizing database size for the branch."),
        ("ADVANCED", "What is the purpose of OSPF virtual links?",
         ["connect a discontiguous area to the backbone through a transit area", "replace the DR", "increase bandwidth", "set router priority"], "A",
         "Virtual links extend the backbone so an area without a direct backbone connection can still participate."),
    ],
    64: [
        ("BEGINNER", "What type of routing protocol is BGP?",
         ["link state", "path vector", "distance vector", "hybrid"], "B",
         "BGP is a path-vector protocol that carries the full AS path used to reach each prefix."),
        ("BEGINNER", "Between which entities does eBGP operate?",
         ["routers in the same AS", "hosts on a LAN", "routers in different autonomous systems", "switches on a trunk"], "C",
         "eBGP peers routers belonging to different autonomous systems, while iBGP runs within one AS."),
        ("BEGINNER", "Which TCP port does BGP use for its sessions?",
         ["53", "179", "110", "23"], "D",
         "BGP establishes TCP sessions on port 179 for reliable transport of routing information."),
        ("BEGINNER", "What does AS stand for in BGP?",
         ["autonomous system", "address segment", "application server", "access switch"], "A",
         "AS stands for autonomous system, a collection of networks under a single administrative domain."),
        ("BEGINNER", "What is the default administrative distance of iBGP on Cisco routers?",
         ["110", "200", "120", "90"], "B",
         "iBGP routes carry an administrative distance of 200 on Cisco routers, the highest of common protocols."),
        ("BEGINNER", "Which BGP version is in common use today?",
         ["BGP-1", "BGP-2", "BGP-4", "BGP-5"], "C",
         "BGP-4, with CIDR support, is the current standard version of BGP."),
        ("BEGINNER", "What does the BGP attribute AS_PATH contain?",
         ["the list of routers crossed", "the metric of the route", "the MAC addresses", "the sequence of AS numbers a route has traversed"], "D",
         "AS_PATH lists each AS the route passed through, and is used to detect and prevent loops."),
        ("BEGINNER", "How does BGP select a path when multiple paths to the same prefix exist?",
         ["it weighs attributes, preferring the highest weight, then local preference, then shortest AS path", "the lowest hop count", "the fastest interface speed", "the most recently received path"], "A",
         "BGP evaluates attributes in a specific order, starting with weight and local preference before AS path length."),
        ("BEGINNER", "A BGP router peers with a router belonging to a different AS. What is this peering called?",
         ["iBGP", "eBGP", "IBGP redistribution", "BGP federation"], "B",
         "Peering between routers in different autonomous systems is called eBGP (external BGP)."),
        ("BEGINNER", "On Cisco devices, what is EIGRP classified as?",
         ["a pure link-state protocol", "a path-vector protocol", "an advanced distance-vector protocol", "a static protocol"], "C",
         "EIGRP is an advanced distance-vector (hybrid) protocol that keeps neighbor and topology tables for fast convergence."),
        ("INTERMEDIATE", "A router prefers BGP path X with weight 200 over path Y with weight 100. Which BGP rule made this decision?",
         ["shorter AS_PATH", "higher weight", "lower MED", "longer AS path"], "C",
         "Weight is the first BGP attribute considered, and higher weight is preferred."),
        ("INTERMEDIATE", "Which components make up the EIGRP composite metric by default?",
         ["hop count only", "bandwidth only", "delay only", "bandwidth and delay"], "D",
         "By default EIGRP uses bandwidth and delay (with reliability, load and MTU as optional) in its composite metric."),
        ("INTERMEDIATE", "An ISP must prevent announcing private prefixes to the internet. Which BGP filter applies?",
         ["prefix lists with deny statements", "an AS-path prepend", "a longer hold timer", "a local preference of 0"], "A",
         "Prefix lists filter which routes are advertised or accepted, blocking private ranges from leaking."),
        ("INTERMEDIATE", "Why does an administrator use AS-path prepending?",
         ["to shorten the path", "to make a path look longer so it is less preferred, encouraging inbound traffic to use another path", "to add the MED", "to force a session reset"], "B",
         "Prepending repeats the AS number to inflate the path length, making the route less preferred for inbound traffic."),
        ("INTERMEDIATE", "What does the MED attribute do?",
         ["choose the best router ID", "signal how many hops remain", "inform peers of the preferred entry point into an AS", "set the session hold time"], "C",
         "The multi-exit discriminator tells external peers which entry link into an AS is preferred, with lower MED preferred."),
        ("INTERMEDIATE", "Which BGP message is used to actively check that a neighbor is still reachable?",
         ["Open", "Update", "Notification", "Keepalive"], "D",
         "BGP sends Keepalive messages (usually every 60 seconds) to maintain the session and verify liveness."),
        ("INTERMEDIATE", "When a full mesh of iBGP peers becomes impractical, what device reduces the number of iBGP sessions?",
         ["a route reflector", "a DR", "a BGP listener", "an ASBR"], "A",
         "Route reflectors allow iBGP clients to peer only with the reflector, avoiding a full mesh."),
        ("INTERMEDIATE", "Which command displays the EIGRP neighbor table on a Cisco router?",
         ["show ip eigrp topology", "show ip eigrp neighbors", "show eigrp routes", "show ip protocol"], "B",
         "The command show ip eigrp neighbors lists directly connected EIGRP peers and their state."),
        ("INTERMEDIATE", "Two eBGP neighbors are not directly connected. Which feature must typically be enabled so the session can cross multiple hops?",
         ["route reflection", "BGP synchronization", "ebgp-multihop", "next-hop-self"], "C",
         "eBGP normally expects directly connected peers; ebgp-multihop permits sessions across several hops."),
        ("INTERMEDIATE", "What does an EIGRP router do when its successor becomes unavailable?",
         ["drops the route permanently", "starts a new SPF run", "removes the route and waits for RIP", "queries neighbors for alternate paths using DUAL"], "D",
         "EIGRP uses DUAL to query neighbors and find an alternate loop-free path when the successor fails."),
        ("ADVANCED", "An enterprise receives routes from two ISPs. Which BGP mechanism best controls which outbound path traffic prefers?",
         ["MED from the ISP", "local preference set locally on the enterprise routers", "AS path prepending", "the weight attribute"], "D",
         "Local preference is set locally and applied to inbound-learned routes, controlling which ISP's path outbound traffic prefers."),
        ("ADVANCED", "An administrator must stop a specific prefix from being sent to a peer while keeping the session alive. Which filter is applied?",
         ["a route-map or prefix-list applied to the neighbor's outbound direction", "a shutdown of the interface", "a BGP reset", "a lower hold time"], "A",
         "Outbound route-maps or prefix lists selectively filter advertised prefixes without tearing down the session."),
        ("ADVANCED", "How is a BGP best path decided when two paths have equal weight, local preference and AS path length?",
         ["the path with the lowest weight", "the path with the lowest origin type (IGP preferred over EGP and incomplete)", "the path with the highest router ID", "the path learned most recently"], "B",
         "BGP compares origin types next, preferring IGP-learned routes over EGP and incomplete origins."),
        ("ADVANCED", "An engineer sets next-hop-self on an iBGP peer. What is the effect?",
         ["the eBGP next hop is preserved", "the route becomes external", "the next hop is changed to the local router so iBGP peers do not need a path to the external next hop", "the AS path is cleared"], "C",
         "next-hop-self rewrites the next hop to the local router, so iBGP peers only need a route to it."),
        ("ADVANCED", "Routes learned from one iBGP peer do not appear on other iBGP peers in the same AS. What is the reason?",
         ["eBGP is preferred", "the router ID is too low", "the MED is zero", "iBGP-learned routes are not re-advertised to other iBGP peers without a full mesh or route reflector"], "D",
         "iBGP routes are only re-advertised to eBGP peers; iBGP transit requires a full mesh or route reflection."),
        ("ADVANCED", "Which BGP attribute is compared after local preference and before MED?",
         ["AS path length", "router ID", "origin", "community"], "A",
         "After weight and local preference, BGP compares AS path length and prefers the shorter one."),
        ("ADVANCED", "What does the EIGRP active state indicate for a route?",
         ["the route is stable", "the router has lost its successor and is querying neighbors for an alternative", "the route is in holddown", "the route has no feasible distance"], "B",
         "An active route means the successor is gone and DUAL is querying neighbors to find a loop-free replacement."),
        ("ADVANCED", "Which EIGRP packet type is sent when a router first discovers a new neighbor?",
         ["Query", "Update with full table", "Hello", "Ack"], "C",
         "Hello packets are multicast every 5 seconds to discover and maintain neighbors in EIGRP."),
        ("ADVANCED", "When a new link with different bandwidth is added to an EIGRP router, what must be considered for the metric to be correct?",
         ["the hop count only", "the MTU size", "the router ID", "the delay and bandwidth of the slowest link in the path"], "D",
         "EIGRP's metric uses the minimum bandwidth and the cumulative delay along the whole path."),
        ("ADVANCED", "A network engineer must prefer a specific BGP path for outbound traffic only on one edge router. Which attribute is most appropriate?",
         ["weight", "local preference", "MED", "community"], "A",
         "Weight is local to the router where it is configured, making it ideal for per-router outbound preferences."),
    ],
    65: [
        ("BEGINNER", "What does NAT stand for?",
         ["Network Address Translation", "Network Access Technology", "Net Address Tagging", "Node Attribute Table"], "B",
         "NAT stands for Network Address Translation, which rewrites IP addresses in packet headers."),
        ("BEGINNER", "What is the main purpose of NAT?",
         ["encrypt traffic", "filter malware", "translate private IP addresses to public ones for internet access", "increase bandwidth"], "C",
         "NAT maps private internal addresses to public addresses so multiple devices can share a single public IP."),
        ("BEGINNER", "Which of the following IP addresses is a private (RFC 1918) address?",
         ["8.8.8.8", "172.20.10.5", "209.165.200.1", "192.168.1.10"], "D",
         "192.168.0.0/16 is a private block, so 192.168.1.10 is private, while the others are public."),
        ("BEGINNER", "Which type of NAT maps one private address to one public address?",
         ["static NAT", "dynamic NAT", "PAT", "overload"], "A",
         "Static NAT performs a fixed one-to-one mapping between a private and a public address."),
        ("BEGINNER", "What does PAT stand for?",
         ["Port Address Translation", "Public Address Tagging", "Packet Access Tool", "Proxy Access Translation"], "B",
         "PAT stands for Port Address Translation, also known as NAT overload, which shares one public IP using port numbers."),
        ("BEGINNER", "Which NAT translation type is also called NAT overload?",
         ["static NAT", "dynamic NAT", "PAT", "destination NAT"], "C",
         "PAT (NAT overload) multiplexes many private addresses onto one public address using unique port numbers."),
        ("BEGINNER", "What is the term for the private address used inside the network in a NAT table?",
         ["outside local", "public address", "external address", "inside local"], "D",
         "The inside local address is the private address of a device as seen from inside the network."),
        ("BEGINNER", "Which device traditionally performs NAT for a small office?",
         ["the border router or firewall", "the access switch", "the wireless controller", "the DNS server"], "A",
         "The edge router or firewall at the network boundary usually runs NAT."),
        ("BEGINNER", "What does an IP address of 0.0.0.0/0 represent in routing?",
         ["a broadcast", "a default route", "a multicast group", "a loopback"], "B",
         "0.0.0.0/0 is the default route that matches any destination not covered by a more specific route."),
        ("BEGINNER", "What is the maximum number of usable host addresses in a /24 subnet?",
         ["253", "256", "254", "255"], "C",
         "A /24 has 256 total addresses; subtract the network and broadcast addresses to leave 254 usable hosts."),
        ("INTERMEDIATE", "A router translates 192.168.1.10:5000 to 203.0.113.5:40001 using PAT. What is the public address 203.0.113.5 called?",
         ["inside local", "inside global", "outside local", "outside global"], "C",
         "The inside global address is the public address of the inside device as seen from the outside."),
        ("INTERMEDIATE", "A home network with one public IP serves 10 devices. Which NAT feature makes this possible?",
         ["static NAT", "dynamic NAT pools", "PAT/overload", "destination NAT"], "D",
         "PAT maps each device to a unique port on the single public address, allowing many devices to share it."),
        ("INTERMEDIATE", "Why is destination NAT (port forwarding) commonly used?",
         ["to allow external users to reach an internal server on a specific port", "to hide the inside address of clients", "to block outbound traffic", "to load balance between switches"], "A",
         "Destination NAT, often called port forwarding, forwards inbound traffic on a public port to a private server."),
        ("INTERMEDIATE", "An administrator configures a static NAT entry for a web server. Which mapping is used?",
         ["many-to-one", "one-to-one between the server's private IP and a fixed public IP", "many-to-many", "one-to-many"], "B",
         "Static NAT creates a permanent one-to-one binding so inbound and outbound traffic to the server is consistent."),
        ("INTERMEDIATE", "A dynamic NAT pool has 10 public addresses and 50 internal users. How many users can access the internet at the same time?",
         ["50", "all of them", "10, because each session needs a unique public address", "0"], "C",
         "Without PAT, each simultaneous session needs its own public address, so only 10 users can be translated at once."),
        ("INTERMEDIATE", "Which command on a Cisco router shows active NAT translations?",
         ["show ip route", "show ip nat translations", "show interfaces", "show vlan"], "D",
         "The command show ip nat translations lists the current address and port mappings in the NAT table."),
        ("INTERMEDIATE", "What is a main drawback of PAT for some applications?",
         ["protocols that embed IP addresses in the payload, like FTP or SIP, may break without ALG support", "it is slower than static NAT", "it requires a public IP per user", "it disables DNS"], "A",
         "PAT can break applications that carry IP addresses inside their payload unless an application-level gateway adjusts them."),
        ("INTERMEDIATE", "When an internal host initiates outbound traffic, NAT creates a translation. What happens to the reply traffic?",
         ["it is dropped", "the router looks up the translation and forwards the reply to the correct inside host", "it is broadcast", "it is sent to the gateway"], "B",
         "The return packet matches the translation entry, which restores the destination to the original inside address."),
        ("INTERMEDIATE", "What does the term outside local address represent in NAT?",
         ["the public address of the inside host", "the private address of the inside host", "the address of an outside host as seen from inside the network", "the server's public address"], "C",
         "The outside local address is the (usually private) address of an external host as it appears from inside the network."),
        ("INTERMEDIATE", "A small office wants all inside hosts to share the single public address assigned to the outside interface. Which command achieves this?",
         ["ip nat inside source static tcp 10.0.0.1 80 203.0.113.1 80", "ip nat pool SHARE 203.0.113.1 203.0.113.2 netmask 255.255.255.252", "ip nat outside source list 1 interface Gi0/1", "ip nat inside source list 1 interface Gi0/1 overload"], "D",
         "The inside source statement with the overload keyword makes the router PAT traffic through the interface's own public address."),
        ("ADVANCED", "An enterprise runs an FTP server behind NAT. Clients connect successfully but fail to transfer files. What is the most likely cause?",
         ["the server's IP is wrong", "DNS is broken", "the NAT pool is exhausted", "PAT/ALG is not handling the active FTP data channel that embeds the IP in the payload"], "D",
         "FTP embeds its data-channel IP in the control connection, so NAT must use an FTP ALG to rewrite it; otherwise file transfers fail."),
        ("ADVANCED", "A company must expose a single web server on the public IP but the public address is used by PAT for outbound. What is the best design?",
         ["a static one-to-one or port-forwarding translation with the appropriate inbound rule, keeping outbound PAT on a separate address", "disable NAT entirely", "give every client a public IP", "move the server to a different network"], "A",
         "Combining a dedicated translation for the server with PAT for clients keeps both inbound and outbound services working cleanly."),
        ("ADVANCED", "What is the purpose of NAT hairpinning?",
         ["to block inbound sessions", "to allow an inside host to reach another inside host through the router's public address", "to increase the NAT table size", "to clear translations"], "B",
         "Hairpinning lets internal users reach internal servers using the public address, looping the traffic back through the NAT device."),
        ("ADVANCED", "A dual-stack network using both IPv4 and IPv6 uses which NAT technique to translate between the two address families?",
         ["PAT overload", "static NAT", "NAT64", "dynamic pools"], "C",
         "NAT64 translates between IPv6 and IPv4 addressing, often with DNS64 to synthesize AAAA records."),
        ("ADVANCED", "What is a common risk of a large PAT translation table in a firewall?",
         ["CPU usage drops", "the public IP becomes private", "translation table exhaustion that drops new sessions", "VLANs stop working"], "D",
         "With many sessions, the NAT/PAT table can fill up, preventing new connections from being established."),
        ("ADVANCED", "An organization has 500 users but only 20 public addresses. Which translation strategy is most appropriate?",
         ["PAT/overload with the 20 addresses as a pool", "static NAT for all users", "a one-to-one dynamic pool without PAT", "destination NAT"], "A",
         "PAT lets many users share each public address, so 20 public addresses can support hundreds of concurrent users."),
        ("ADVANCED", "When does the outside global address of an inbound translation get created in a typical destination-NAT scenario?",
         ["when the server sends a reply", "after the router translates the destination of the inbound packet and then creates a session entry for the return traffic", "never", "only after a reboot"], "B",
         "The router translates the inbound destination and records the reverse mapping so return traffic is translated back correctly."),
        ("ADVANCED", "Which device class is commonly used as an ALG to support VoIP such as SIP behind NAT?",
         ["a plain L2 switch", "a repeater", "a session border controller or NAT-aware firewall", "a DNS server"], "C",
         "VoIP protocols embed IP and port data in their messages, so NAT-aware firewalls or SBCs are needed to rewrite them correctly."),
        ("ADVANCED", "Why must PAT translation entries include both IP address and port?",
         ["to reduce table size", "to support static NAT", "to bypass routing", "because the port is what uniquely distinguishes which inside host owns each session on the shared public IP"], "D",
         "With PAT, many sessions share one public IP, so the unique combination of IP and port identifies each inside host."),
        ("ADVANCED", "What happens to the checksum of a packet when NAT rewrites the IP address and port?",
         ["it must be recomputed because changing the fields invalidates the original checksum", "it stays the same", "it is ignored by routers", "the packet is dropped"], "A",
         "TCP and IP checksums cover the source and destination addresses and ports, so NAT must recompute them after translation."),
    ],
}
