# -*- coding: utf-8 -*-
"""
Question bank for subject 29: WEB104 - Mobile App Development.
Category: Web & Mobile Development.

Topics:
  141: Mobile App Basics
  142: Android Fundamentals
  143: iOS & Swift Basics
  144: Flutter & Dart
  145: Mobile UI & Deployment

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    141: [
        ("BEGINNER", "Which of the following is a key advantage of native mobile apps over web pages?",
         ["direct access to device hardware such as the camera and GPS", "no need for a backend server", "they never need updates", "they run in every browser"], "A",
         "Native apps can use device hardware like cameras, GPS and sensors through platform APIs, which web pages cannot do directly."),
        ("BEGINNER", "What does an app store such as the Google Play Store provide?",
         ["a tool for writing app code", "a marketplace to distribute and update apps", "an emulator for testing", "a cloud database"], "B",
         "App stores host, distribute and update mobile apps so users can install them in one place."),
        ("BEGINNER", "Which type of app runs inside a browser?",
         ["native app", "hybrid app", "web app", "compiled app"], "C",
         "A web app is accessed through a browser and does not need to be installed from an app store."),
        ("BEGINNER", "Which file format is commonly used to distribute an Android app?",
         ["EXE", "DWG", "IPA", "APK"], "D",
         "The APK (Android Package) is the installable format for Android apps distributed to devices."),
        ("BEGINNER", "What does the term native app mean?",
         ["an app built for a specific platform using its native tools and languages", "an app that runs only on the web", "an app written entirely in HTML and CSS", "an app that works without any code"], "A",
         "A native app is developed with the platform's own SDK and languages, such as Kotlin for Android or Swift for iOS."),
        ("BEGINNER", "Which operating system powers the iPhone?",
         ["Android", "iOS", "Windows", "Linux"], "B",
         "The iPhone runs on iOS, Apple's mobile operating system."),
        ("BEGINNER", "What does an API allow an app to do?",
         ["make the app run faster", "delete unnecessary files", "communicate with other software services", "prevent the phone from locking"], "C",
         "An application programming interface lets an app request data and functionality from other software services."),
        ("BEGINNER", "What is a common reason an app needs an Internet connection?",
         ["to display a local database", "to run the user interface", "to take screenshots", "to fetch data from a remote server"], "D",
         "Many apps fetch data, such as news or user accounts, from remote servers over the Internet."),
        ("BEGINNER", "Which of the following is an example of an emulator used in mobile development?",
         ["Android Studio's virtual device", "Microsoft Word", "Adobe Photoshop", "Excel"], "A",
         "Android Studio provides a virtual device emulator that simulates an Android phone for testing."),
        ("BEGINNER", "What is the main purpose of app notifications?",
         ["to increase battery life", "to inform users of events even when the app is not open", "to speed up the processor", "to store photos"], "B",
         "Notifications alert users to events from an app even when it is not currently open."),
        ("INTERMEDIATE", "Which type of mobile app generally offers the best performance and hardware access?",
         ["a native app", "a web app", "an SMS-based app", "a bookmarklet"], "A",
         "Native apps compile directly for the platform and can use its full APIs, giving the best performance and hardware access."),
        ("INTERMEDIATE", "What is a key trade-off of hybrid apps built with web technologies?",
         ["they cannot use the device camera", "they may have slower performance and limited native features", "they require a Mac to build", "they cannot access the Internet"], "B",
         "Hybrid apps rely on web rendering, which can be slower and less capable than native APIs for demanding features."),
        ("INTERMEDIATE", "A developer must build one codebase for Android, iOS and the web. Which approach fits best?",
         ["write separate native code per platform", "write an SMS gateway", "use a cross-platform framework such as Flutter or React Native", "install two operating systems"], "C",
         "Cross-platform frameworks compile a shared codebase to multiple targets, reducing duplicated work."),
        ("INTERMEDIATE", "Which activity best describes responsive design in a mobile context?",
         ["designing a fixed desktop layout", "blocking all resizing", "using only landscape orientation", "adapting the layout to different screen sizes"], "D",
         "Responsive design adjusts layout and content so an app looks correct across many screen sizes and orientations."),
        ("INTERMEDIATE", "Which service is commonly used to send push notifications in a mobile app?",
         ["Google's Firebase Cloud Messaging", "a spreadsheet program", "a file manager", "a password manager"], "A",
         "Firebase Cloud Messaging delivers push notifications to Android, iOS and web apps from a single service."),
        ("INTERMEDIATE", "Why might an app be rejected during app store review?",
         ["it has too many downloads", "it violates content or privacy guidelines", "it uses too little storage", "it runs on a Mac"], "B",
         "App stores enforce content, privacy and quality guidelines, so violations lead to rejection."),
        ("INTERMEDIATE", "What does versioning of a mobile app refer to?",
         ["the file size of the app", "the model of the phone", "tracking and numbering the releases of the app", "the screen resolution"], "C",
         "Version numbers identify each release so users and stores know which build of the app is installed."),
        ("INTERMEDIATE", "Which scenario best illustrates monetization through in-app purchases?",
         ["the app is free but offers digital items for payment", "the developer sells the phone", "the app only works offline", "the app has no users"], "D",
         "In-app purchases let users pay for digital goods or features inside a free app."),
        ("INTERMEDIATE", "What is a sandbox in the context of mobile apps?",
         ["a restricted environment that limits what an app can access", "a place to store backups", "a type of screen", "an antivirus program"], "A",
         "Mobile operating systems sandbox each app so it can only access its own data and approved system resources."),
        ("INTERMEDIATE", "Which statement about app data storage is correct?",
         ["apps cannot store data locally", "apps can store data locally in databases or files on the device", "all data must be stored in the app package", "data disappears as soon as the app is closed"], "B",
         "Mobile apps commonly persist data locally using databases, files or key-value stores on the device."),
        ("ADVANCED", "A startup must ship an app to both Android and iOS quickly with a small team. What is the most efficient strategy?",
         ["use a cross-platform framework to share most of the codebase", "build two entirely separate native apps", "write a web app and wrap it manually", "skip the app stores"], "A",
         "A cross-platform framework lets one team maintain a single shared codebase for both platforms, reducing cost and time."),
        ("ADVANCED", "An app crashes only on older devices with limited memory. What is the best first step?",
         ["buy new hardware", "analyze crash reports and reduce memory usage such as image sizes", "increase the app version number", "remove the app from the store"], "B",
         "Crash reports reveal the failing code, and reducing memory-heavy work such as oversized bitmaps fixes low-memory crashes."),
        ("ADVANCED", "Which approach best protects user data transmitted by a mobile app?",
         ["send passwords in plain text", "disable encryption", "use TLS/HTTPS for all network communication", "store passwords in a text file"], "C",
         "TLS/HTTPS encrypts traffic between the app and servers, protecting data from interception in transit."),
        ("ADVANCED", "A developer finds push notifications stop after the user clears the app from recent apps. What is the most likely cause?",
         ["the phone has no battery", "the notifications are scheduled at the wrong time", "the app icon is incorrect", "the background service was killed and is not rescheduled properly"], "D",
         "Killing a background service prevents it from delivering notifications, so the app must reschedule or rely on the push service after the process restarts."),
        ("ADVANCED", "Which strategy is best for offline-first data synchronization in a mobile app?",
         ["store data locally and sync with the server when connectivity is restored", "require a constant connection", "block all offline features", "re-download all data on every launch"], "A",
         "Offline-first apps save data locally and reconcile it with the server once a connection returns, keeping the app usable offline."),
        ("ADVANCED", "What is the main purpose of app signing in production distribution?",
         ["to make the app run faster", "to verify the identity of the developer and ensure the package is not tampered with", "to reduce the app size", "to enable encryption of photos"], "B",
         "App signing cryptographically proves who published the app and lets the platform detect modified or untrusted packages."),
        ("ADVANCED", "Why should an app follow the platform's design guidelines?",
         ["to make the code compile", "to avoid using the compiler", "to provide a consistent and familiar user experience", "to increase battery drain"], "C",
         "Following platform guidelines makes an app feel native and predictable, improving usability and user trust."),
        ("ADVANCED", "Which release channel should be used to test a new feature with a limited group before a full rollout?",
         ["production", "staging with no users", "alpha", "a beta or staged rollout track"], "D",
         "A beta or staged rollout reaches a controlled group of users so issues can be found before wide release."),
        ("ADVANCED", "A team needs to ship an update that fixes a critical bug. Which consideration matters most?",
         ["follow the store update process and release the fix to affected users quickly", "rewrite the whole app", "change the app icon", "remove all features"], "A",
         "A fast, focused fix released through the normal update channel minimizes user exposure to the bug."),
        ("ADVANCED", "How should an app handle a large image download to avoid memory problems?",
         ["load the full image into memory at once", "decode and downscale the image to the needed size and cache it", "avoid loading any images", "store the image as a string"], "B",
         "Downscaling decodes only the pixels actually needed and caching prevents repeated expensive loads, reducing peak memory."),
    ],    142: [
        ("BEGINNER", "Which language is one of the two primary languages recommended for native Android development?",
         ["Kotlin", "Swift", "Objective-C", "PHP"], "A",
         "Kotlin is Google's recommended language for modern Android development alongside Java."),
        ("BEGINNER", "In Android, what is an Activity?",
         ["a background process with no interface", "a single screen with a user interface", "a network request", "a database table"], "B",
         "An Activity represents a single screen with which the user can interact."),
        ("BEGINNER", "Which file declares the components and permissions of an Android app?",
         ["build.gradle", "colors.xml", "AndroidManifest.xml", "MainActivity.kt"], "C",
         "AndroidManifest.xml describes app components, permissions and other metadata to the Android system."),
        ("BEGINNER", "Which IDE is officially recommended for Android development?",
         ["NetBeans", "Eclipse only", "Xcode", "Android Studio"], "D",
         "Android Studio is the official IDE for building Android apps."),
        ("BEGINNER", "What is an Android Service?",
         ["a component that runs in the background without a user interface", "a screen for user input", "a type of notification", "a layout container"], "A",
         "A Service performs long-running background work without presenting a user interface."),
        ("BEGINNER", "Where are layout files such as activity_main.xml stored?",
         ["res/values", "res/layout", "res/drawable", "src/main/java"], "B",
         "XML layout files live in the res/layout directory of an Android project."),
        ("BEGINNER", "What does an Android emulator provide?",
         ["a real physical phone", "a simulated Android device for testing", "a web browser", "a cloud storage service"], "C",
         "An emulator simulates an Android device so developers can run and test apps without real hardware."),
        ("BEGINNER", "Which of the following is NOT a core Android app component?",
         ["Activity", "Service", "ContentProvider", "TextView"], "D",
         "The core components are Activity, Service, BroadcastReceiver and ContentProvider; TextView is a UI widget."),
        ("BEGINNER", "What is an Intent used for in Android?",
         ["to launch another activity or component", "to store app passwords", "to manage battery level", "to draw the interface"], "A",
         "An Intent is a message that requests an action, such as starting an Activity or Service."),
        ("BEGINNER", "Which file stores user-readable strings so they can be localized?",
         ["AndroidManifest.xml", "strings.xml", "colors.xml", "build.gradle"], "B",
         "strings.xml holds user-facing text, which makes localization easy by replacing the file per language."),
        ("INTERMEDIATE", "Which Android lifecycle method is called when an Activity becomes partially hidden by another activity?",
         ["onPause()", "onStop()", "onDestroy()", "onDetach()"], "A",
         "onPause() runs when an Activity loses focus but is still visible, such as when partially covered."),
        ("INTERMEDIATE", "Which method is called first when an Activity is being created?",
         ["onStart()", "onCreate()", "onResume()", "onRestart()"], "B",
         "onCreate() is the first callback invoked when an Activity is created, where initial setup is done."),
        ("INTERMEDIATE", "A developer wants to run a one-time network fetch when the Activity enters the foreground. Which callback is most appropriate?",
         ["onPause()", "onStop()", "onResume()", "onRestart()"], "C",
         "onResume() fires every time the Activity becomes interactive and visible in the foreground."),
        ("INTERMEDIATE", "What is the main purpose of onSaveInstanceState()?",
         ["to free memory", "to stop services", "to launch a new activity", "to preserve transient UI state across configuration changes"], "D",
         "onSaveInstanceState() stores temporary UI state so it can be restored when the Activity is recreated."),
        ("INTERMEDIATE", "In Kotlin, which keyword declares a variable whose value cannot be changed after assignment?",
         ["val", "var", "lateinit", "static"], "A",
         "val declares an immutable reference that can be assigned once, unlike var which is mutable."),
        ("INTERMEDIATE", "What does the ?. safe-call operator do in Kotlin?",
         ["throws if null", "calls a method only if the receiver is not null", "converts a type", "declares a nullable type"], "B",
         "The safe-call operator ?. performs the call only when the receiver is non-null, otherwise it returns null."),
        ("INTERMEDIATE", "A null pointer crash happens when reading a property. Which Kotlin issue most likely caused it?",
         ["smart cast", "data class", "the property was declared as a non-null type but was assigned null", "companion object"], "C",
         "Assigning null to a non-null type violates Kotlin's type system and causes a null pointer failure at runtime."),
        ("INTERMEDIATE", "Which view is best for displaying a long scrollable list of items?",
         ["TextView", "LinearLayout", "ScrollView with a fixed number of text views", "RecyclerView"], "D",
         "RecyclerView efficiently displays large lists by reusing views and lazy loading items."),
        ("INTERMEDIATE", "What does an explicit Intent specify in Android?",
         ["the exact component, such as a specific Activity class, that should receive the action", "the current battery level", "the model of the device", "the app icon color"], "A",
         "An explicit Intent names the precise target component, while an implicit Intent is resolved by the system from its action and data."),
        ("INTERMEDIATE", "Which component allows one app to expose structured data to other apps?",
         ["Activity", "ContentProvider", "Fragment", "Layout"], "B",
         "A ContentProvider shares structured data with other apps through a standard content URI interface."),
        ("ADVANCED", "A user reports that an app crashes only after the screen rotates. What is the most likely cause?",
         ["the Activity was recreated and code relied on stale references to the old instance", "the battery is low", "the screen size is wrong", "the app icon is corrupted"], "A",
         "Rotation recreates the Activity, so code holding references to the destroyed instance crashes when it runs again."),
        ("ADVANCED", "Which statement best describes app signing with a release keystore?",
         ["the signature proves the developer's identity and protects against tampering", "signing speeds up the build", "signing removes permissions", "signing is only for testing"], "B",
         "The release keystore signature authenticates the developer and lets Android reject modified packages."),
        ("ADVANCED", "What is the purpose of code shrinking and obfuscation such as R8 in a release build?",
         ["to make code compile faster", "to add new features", "to remove unused code and obscure names, making reverse engineering harder", "to translate the app to another language"], "C",
         "R8 removes dead code and renames symbols, which shrinks the APK and protects against easy reverse engineering."),
        ("ADVANCED", "Which best practice reduces memory pressure from large images in a RecyclerView?",
         ["decode images at the exact display size and reuse views", "load every image at full resolution", "keep all images in memory", "disable images entirely"], "D",
         "Decoding only the needed size and reusing item views cuts the memory each image consumes."),
        ("ADVANCED", "A developer releases an update but must keep the same package name. Why?",
         ["changing the package name creates a different app and breaks updates", "package names must be lowercase", "the store forces a new name", "the compiler refuses uppercase names"], "A",
         "The package name is the app's identity, so changing it makes the update look like a brand new app."),
        ("ADVANCED", "Which approach best avoids dropped frames during scrolling?",
         ["perform heavy work such as database queries on the main thread", "run network and heavy work off the main thread and keep the UI thread responsive", "use many nested layouts", "disable the scrollable view"], "B",
         "Off-loading heavy work from the main thread prevents it from blocking UI updates and causing dropped frames."),
        ("ADVANCED", "What is the recommended way to persist simple user settings that must survive restarts?",
         ["write them into the app logs", "store them with SharedPreferences or DataStore", "put them in the manifest", "recreate them on each launch"], "C",
         "SharedPreferences and DataStore persist key-value settings locally across app restarts."),
        ("ADVANCED", "Which scenario is a legitimate reason to use a WorkManager periodic task?",
         ["to keep an Activity alive", "to show a dialog", "to change the app icon", "to sync data in the background at intervals that survive process death"], "D",
         "WorkManager schedules reliable, battery-friendly background work that survives app restarts and process death."),
        ("ADVANCED", "Why should a release APK be built with minification enabled?",
         ["it reduces APK size and removes unused code", "it guarantees there are no crashes", "it makes debugging easier", "it is required for testing"], "A",
         "Minification removes unused classes and resources, producing a smaller and more secure release APK."),
        ("ADVANCED", "What is the correct way to handle a dangerous runtime permission in modern Android?",
         ["declare it in the manifest only", "declare it in the manifest and request it at runtime from the user", "request it at compile time", "never request permissions"], "B",
         "Dangerous permissions must be declared in the manifest and also requested from the user at runtime."),
    ],
    143: [
        ("BEGINNER", "Which language is the primary modern language for iOS development?",
         ["Swift", "Kotlin", "Java", "Python"], "A",
         "Swift is Apple's modern, primary language for iOS, macOS and other Apple platform apps."),
        ("BEGINNER", "Which IDE is used to develop iOS apps?",
         ["Android Studio", "Xcode", "Visual Studio Code", "Eclipse"], "B",
         "Xcode is Apple's IDE for building iOS, macOS and other Apple platform applications."),
        ("BEGINNER", "What is a ViewController in iOS?",
         ["a network request", "a database", "a component that manages a screen of content and its interactions", "a font"], "C",
         "A ViewController manages the content, layout and behavior of one screen of an app."),
        ("BEGINNER", "Which file format is used to distribute an iOS app?",
         ["APK", "IPA", "EXE", "JAR"], "D",
         "An IPA (iOS App Store Package) is the installable archive format for iOS apps."),
        ("BEGINNER", "What does the term app store refer to in iOS?",
         ["Apple's official marketplace for apps", "a cloud storage service", "a backup tool", "a programming language"], "A",
         "The App Store is Apple's official marketplace where users download and update iOS apps."),
        ("BEGINNER", "Which of these is a UI framework for building iOS interfaces?",
         ["SwiftUI", "Jetpack Compose", "Unity only", "Android XML"], "B",
         "SwiftUI is Apple's modern declarative framework for building iOS user interfaces."),
        ("BEGINNER", "What is an IBOutlet used for?",
         ["to connect a code property to a user interface element", "to fetch data from a server", "to declare a function", "to store passwords"], "C",
         "An IBOutlet links a property in code to a specific UI element so the code can read and update it."),
        ("BEGINNER", "Which statement about the iOS simulator is true?",
         ["it can fully test device-only hardware such as the camera", "it simulates iOS devices for testing but lacks some real hardware capabilities", "it is a physical phone", "it is a web server"], "D",
         "The simulator runs iOS software but cannot fully emulate real hardware such as the camera or motion sensors."),
        ("BEGINNER", "What does the acronym SDK stand for?",
         ["Software Development Kit", "System Data Kernel", "Source Distribution Kit", "Security Device Key"], "A",
         "SDK stands for Software Development Kit, a set of tools and libraries for building apps."),
        ("BEGINNER", "Which Swift type stores a whole number?",
         ["String", "Int", "Bool", "Void"], "B",
         "Int is Swift's type for whole numbers, while Double and Float store decimals."),
        ("INTERMEDIATE", "Which Swift keyword declares a constant whose value cannot change?",
         ["let", "var", "const", "static"], "A",
         "let declares an immutable constant in Swift, while var declares a mutable variable."),
        ("INTERMEDIATE", "Which syntax declares an optional integer in Swift?",
         ["var x: Int!", "var x: Int?", "var x: ?Int", "var x = Int?"], "B",
         "Appending ? to a type creates an optional, so var x: Int? can hold an Int or nil."),
        ("INTERMEDIATE", "What does optional chaining do in Swift?",
         ["it forces an optional to unwrap", "it converts an optional to a string", "it safely accesses a value only when the optional is not nil", "it removes all optionals from a program"], "C",
         "Optional chaining with ?. accesses a property or method only if the optional contains a value."),
        ("INTERMEDIATE", "In Swift, what does the ?? operator do?",
         ["declares a nullable type", "appends a string", "multiplies two numbers", "provides a default value when the left side is nil"], "D",
         "The nil-coalescing operator ?? returns the left value if it is non-nil, otherwise the right-hand default."),
        ("INTERMEDIATE", "Which is the correct way to declare a function in Swift?",
         ["func greet(name: String) -> String { return name }", "function greet(name)", "def greet(name):", "greet(name) {}"], "A",
         "Swift functions use the func keyword, labeled parameters and a -> return type."),
        ("INTERMEDIATE", "What is a struct in Swift?",
         ["a network request", "a value type that bundles related properties and methods", "an alias for a string", "a kind of button"], "B",
         "A struct is a value type grouping related data and behavior; instances are copied on assignment."),
        ("INTERMEDIATE", "Which SwiftUI modifier is used to add spacing around a view?",
         [".background()", ".foregroundColor()", ".padding()", ".cornerRadius()"], "C",
         "The padding() modifier adds space around a view, giving it clear spacing from surrounding content."),
        ("INTERMEDIATE", "What is a delegate in iOS development?",
         ["a design pattern where one object hands off tasks to another object", "a type of button", "a database table", "a color scheme"], "D",
         "Delegation lets one object act on behalf of another by sending it events, a core Cocoa pattern."),
        ("INTERMEDIATE", "Which method reloads the data shown in a UITableView?",
         ["reloadData()", "refreshView()", "updateRows()", "reloadAll()"], "A",
         "Calling reloadData() asks the table view to fetch its data source again and redraw its rows."),
        ("INTERMEDIATE", "Which of the following best describes an @IBAction?",
         ["a method that links code to a user interface event", "a constant value", "a data type", "a database query"], "B",
         "An @IBAction is a method wired in Interface Builder to run when the user triggers a UI event such as a tap."),
        ("ADVANCED", "An iOS app crashes with EXC_BAD_ACCESS after dismissing a view. What is the most likely cause?",
         ["accessing a freed or over-released object, such as a dangling reference", "the screen is too large", "the font is too big", "too many strings"], "A",
         "EXC_BAD_ACCESS typically means code accessed memory of an object that was already deallocated, a dangling reference."),
        ("ADVANCED", "What is the purpose of an app's bundle identifier in iOS?",
         ["it is the app's icon", "it uniquely identifies the app and is tied to signing and provisioning", "it sets the screen size", "it stores user passwords"], "B",
         "The bundle identifier uniquely names the app and is used in provisioning profiles and app signing."),
        ("ADVANCED", "Which statement about iOS app sandboxing is true?",
         ["apps can read any file on the device", "apps are restricted to their own container and must use system APIs to share data", "sandboxing only applies to games", "sandboxing was removed in iOS 15"], "C",
         "Each iOS app runs in a sandbox and can only access its own container, sharing data through approved APIs."),
        ("ADVANCED", "A release build crashes while the debug build works. What is the most likely difference?",
         ["debug builds are slower", "release builds strip debug symbols and apply optimizations that can change behavior", "release builds have more memory", "release builds skip the interface"], "D",
         "Release builds apply optimizations and remove debugging support, which can expose timing or lifetime bugs not seen in debug builds."),
        ("ADVANCED", "Why should sensitive data such as passwords be stored in the Keychain rather than UserDefaults?",
         ["the Keychain stores data encrypted and protected by the operating system", "UserDefaults is faster", "Keychain is easier to code", "UserDefaults cannot store strings"], "A",
         "The Keychain encrypts items and protects them at the OS level, unlike UserDefaults which stores plain data."),
        ("ADVANCED", "What is automatic reference counting (ARC) in Swift?",
         ["a garbage collector that runs periodically", "a compiler feature that manages object lifetime by counting strong references", "a network protocol", "a UI framework"], "B",
         "ARC tracks strong references to objects and releases them when the count reaches zero, managing memory automatically."),
        ("ADVANCED", "Which strategy best avoids retain cycles between Swift objects?",
         ["always use strong references", "never use classes", "use weak or unowned references where a cycle would otherwise form", "store everything in arrays"], "C",
         "Marking one side of a two-way reference as weak or unowned breaks the cycle so ARC can deallocate the objects."),
        ("ADVANCED", "How can an iOS app legally perform work while in the background?",
         ["run a never-ending timer", "use background tasks such as background fetch or short scheduled work", "play silent audio forever", "it is impossible"], "D",
         "iOS permits limited background activity through APIs such as background fetch and short background tasks for legitimate work."),
        ("ADVANCED", "Which service do developers use to upload and manage app releases for the App Store?",
         ["App Store Connect", "Google Play Console", "GitHub", "Slack"], "A",
         "App Store Connect is Apple's portal for uploading builds, managing app metadata and submitting to review."),
        ("ADVANCED", "Why should a UITableView reuse cells with dequeueReusableCell?",
         ["to increase battery drain", "to reuse existing cell objects and avoid allocating new ones during fast scrolling", "to change colors", "to store data"], "B",
         "Reusing cells avoids creating new views constantly, which keeps scrolling smooth and reduces memory pressure."),
    ],
    144: [
        ("BEGINNER", "Which language is used to write Flutter apps?",
         ["Dart", "JavaScript", "Swift", "Kotlin"], "A",
         "Flutter apps are written in Dart, a language created by Google."),
        ("BEGINNER", "What is a widget in Flutter?",
         ["a file type", "a reusable building block of the user interface", "a database", "a network request"], "B",
         "Everything in a Flutter interface is a widget, from layout containers to buttons and text."),
        ("BEGINNER", "Which of the following best describes Flutter?",
         ["a web server", "a cross-platform UI framework that compiles to native code", "an operating system", "a database engine"], "C",
         "Flutter is a cross-platform toolkit that compiles Dart into native code for Android, iOS and other targets."),
        ("BEGINNER", "Which function is required to start a Flutter app?",
         ["startApp()", "launch()", "initApp()", "main()"], "D",
         "Every Flutter app begins in main(), which calls runApp() to launch the widget tree."),
        ("BEGINNER", "What does hot reload do in Flutter?",
         ["it applies code changes to the running app quickly without a full restart", "it reboots the device", "it deletes the project", "it downloads updates"], "A",
         "Hot reload injects updated source into the running app so developers see changes almost instantly."),
        ("BEGINNER", "Which widget is commonly used to display text?",
         ["Text", "Image", "Icon", "Button"], "B",
         "The Text widget renders a string of characters on screen."),
        ("BEGINNER", "In Dart, which keyword declares a variable that can only be assigned once?",
         ["var", "final", "late", "dynamic"], "C",
         "final creates a variable assigned exactly once, whereas var declares a reassignable variable."),
        ("BEGINNER", "Which widget is commonly used to wrap a single child with padding or decoration?",
         ["Row", "Column", "ListView", "Container"], "D",
         "Container gives a child padding, margins, decoration and sizing options."),
        ("BEGINNER", "What is a StatelessWidget?",
         ["a widget that builds its interface once and has no mutable state", "a widget that never appears", "a widget for networking", "a widget with a built-in database"], "A",
         "A StatelessWidget renders fixed content and cannot change its internal state after being built."),
        ("BEGINNER", "Which widget arranges its children vertically?",
         ["Row", "Column", "Stack", "Wrap"], "B",
         "A Column places its children from top to bottom, while Row lays them out horizontally."),
        ("INTERMEDIATE", "What does setState() do in Flutter?",
         ["it marks the State object as dirty and triggers a rebuild of its widget", "it deletes the current state", "it starts a network request", "it stops the app"], "A",
         "setState() notifies the framework that the state changed, scheduling a rebuild of the widget."),
        ("INTERMEDIATE", "Which widget is best for a scrollable vertical list of widgets?",
         ["Column", "ListView", "Row", "Expanded"], "B",
         "ListView scrolls its children lazily, which is ideal for long vertical lists."),
        ("INTERMEDIATE", "In Dart, what is the difference between const and final?",
         ["there is no difference", "final is for numbers only", "const values are compile-time constants while final can be set once at runtime", "const can be reassigned"], "C",
         "const must be known at compile time, whereas final is assigned once and can hold a runtime value."),
        ("INTERMEDIATE", "Which widget is best for a horizontal row of equally sized children?",
         ["Column with Expanded children", "ListView", "Row with Expanded children", "Stack"], "D",
         "A Row with each child wrapped in Expanded distributes the available width equally among them."),
        ("INTERMEDIATE", "What does the async keyword indicate in Dart?",
         ["the function returns a Future and may perform asynchronous work", "the function is private", "the function never returns", "the function runs on a background thread only"], "A",
         "Marking a function async lets it use await and return a Future for asynchronous operations."),
        ("INTERMEDIATE", "Which keyword is used to wait for a Future to complete in Dart?",
         ["async", "await", "then only", "yield"], "B",
         "The await keyword suspends the function until the awaited Future completes, giving its result."),
        ("INTERMEDIATE", "What is a StatefulWidget?",
         ["a widget that never rebuilds", "a widget whose State can change and trigger rebuilds", "a widget used only for animations", "a widget with no build method"], "C",
         "A StatefulWidget owns mutable State that can be changed with setState() to trigger rebuilds."),
        ("INTERMEDIATE", "Which class is commonly used to navigate between screens in Flutter?",
         ["TextButton", "Navigator", "Scaffold", "Align"], "D",
         "The Navigator manages a stack of routes and pushes or pops screens for navigation."),
        ("INTERMEDIATE", "What is the purpose of the Expanded widget?",
         ["to make a child fill the remaining space in a Row or Column", "to add padding", "to round corners", "to hide a widget"], "A",
         "Expanded forces its child to fill the leftover space in a flex container such as Row or Column."),
        ("INTERMEDIATE", "Which code displays a SnackBar in Flutter?",
         ["call showSnackBar() on the ScaffoldMessenger", "call toast()", "call alert()", "call popup()"], "B",
         "ScaffoldMessenger.of(context).showSnackBar() displays a temporary SnackBar at the bottom of the screen."),
        ("ADVANCED", "A Flutter app drops frames when scrolling a large list. What is the most effective fix?",
         ["build items lazily with ListView.builder instead of creating all children at once", "increase the font size", "use a Column", "disable scrolling"], "A",
         "ListView.builder creates only visible items on demand, which keeps scrolling smooth for large lists."),
        ("ADVANCED", "What is the purpose of the pubspec.yaml file in a Flutter project?",
         ["to define app dependencies, assets and metadata", "to store user data", "to render the interface", "to compile Dart code"], "B",
         "pubspec.yaml declares packages, fonts, assets and other project settings used by the pub tool."),
        ("ADVANCED", "Which command builds an Android release APK from a Flutter project?",
         ["flutter run --debug", "flutter build apk --release", "flutter test", "flutter pub add"], "C",
         "flutter build apk --release produces an optimized, signed release APK for distribution."),
        ("ADVANCED", "What does the const keyword on a widget constructor enable?",
         ["runtime mutation", "automatic rebuilding", "compile-time constant widgets that can skip rebuild work", "network caching"], "D",
         "Const widgets are created once at compile time, so rebuilding them is almost free."),
        ("ADVANCED", "Which approach is best for managing app state across many screens in Flutter?",
         ["use a state management solution such as Provider or Riverpod", "store everything in local variables", "recreate the app each time", "use only StatelessWidgets"], "A",
         "A state management library centralizes shared state so multiple widgets can read and update it consistently."),
        ("ADVANCED", "What is the main benefit of the repository pattern in a Flutter app?",
         ["it makes the app prettier", "it separates data sources from the UI, making the code testable and maintainable", "it removes all classes", "it speeds up hot reload"], "B",
         "The repository pattern isolates data access behind one interface, simplifying testing and swapping data sources."),
        ("ADVANCED", "Which approach is recommended for periodic background work in Flutter?",
         ["keep the UI busy", "run a tight loop in main()", "use background isolates or WorkManager plugins for platform background tasks", "never perform background work"], "C",
         "Flutter apps delegate reliable periodic background work to platform APIs such as WorkManager or background isolates."),
        ("ADVANCED", "Why does Flutter compile Dart to native code for release builds?",
         ["it makes the code unreadable", "to allow web development", "to achieve native performance with ahead-of-time compilation", "to save disk space only"], "D",
         "Ahead-of-time compilation produces native machine code that runs much faster than an interpreted approach."),
        ("ADVANCED", "What commonly inflates the size of a Flutter Android app?",
         ["bundling many assets and not using app bundle shrinking", "too many comments", "short class names", "using English strings"], "A",
         "Large assets and uncompressed resources increase APK size, which shrinking and app bundles help reduce."),
        ("ADVANCED", "What is the purpose of integration tests in Flutter?",
         ["to check syntax", "to test the full app flow on a real device or emulator", "to format code", "to upload the app"], "B",
         "Integration tests run the complete app and verify user flows on a device or emulator."),
    ],
    145: [
        ("BEGINNER", "What does UI stand for in mobile development?",
         ["User Interface", "Universal Input", "User Integration", "Unit Interface"], "A",
         "UI stands for User Interface, the visual elements users see and interact with."),
        ("BEGINNER", "Which unit is commonly used for text size on Android?",
         ["dp", "sp", "px", "mm"], "B",
         "Text size uses sp (scale-independent pixels), which adapts to the user's font settings."),
        ("BEGINNER", "What is a wireframe in app design?",
         ["a compiled app", "a low-fidelity sketch of the app layout", "a database schema", "a test report"], "C",
         "A wireframe is a simple blueprint of an app's screens and layout before visual design."),
        ("BEGINNER", "Which of the following is an example of a navigation element in a mobile app?",
         ["a color", "a font", "a tab bar", "a padding value"], "D",
         "A tab bar lets users switch between major sections of an app, so it is a navigation element."),
        ("BEGINNER", "What is a responsive design goal for mobile apps?",
         ["the UI adapts to different screen sizes and orientations", "the app never changes layout", "the app runs on one device only", "the app ignores the screen size"], "A",
         "Responsive design makes the interface scale and rearrange to fit various screens and orientations."),
        ("BEGINNER", "Which store is used to distribute Android apps?",
         ["App Store", "Google Play", "npm", "GitHub"], "B",
         "Google Play is the primary official store for distributing Android apps."),
        ("BEGINNER", "What is an app icon?",
         ["a database", "a color", "the visual symbol that represents the app on the home screen", "a network address"], "C",
         "The app icon is the image users tap to open the app and it represents the app's identity."),
        ("BEGINNER", "What does a splash screen typically show?",
         ["the app's branding while it loads", "user passwords", "the database contents", "error logs"], "D",
         "A splash screen displays branding such as a logo while the app prepares its content."),
        ("BEGINNER", "Which interaction lets a user scroll a list?",
         ["a swipe or drag gesture", "a double tap", "a long press", "a pinch"], "A",
         "Scrolling is performed with a swipe or drag gesture across the touch screen."),
        ("BEGINNER", "What does the release process of a mobile app involve?",
         ["writing a new language", "building, testing, signing and submitting the app to a store", "deleting the code", "buying a phone"], "B",
         "Releasing an app requires building, testing, signing and submitting it to an app store for distribution."),
        ("INTERMEDIATE", "Which approach best handles a variety of Android screen sizes?",
         ["use responsive layouts with weights, constraints and dimension resources", "fix a single pixel size for everything", "use only one layout file", "require a minimum screen resolution"], "A",
         "Responsive layouts and resource qualifiers let the UI adapt to different screens cleanly."),
        ("INTERMEDIATE", "What is the role of a navigation drawer?",
         ["to show a loading bar", "to present a slide-out menu of navigation options", "to display notifications", "to save settings"], "B",
         "A navigation drawer is a slide-out panel that offers navigation between the main sections of an app."),
        ("INTERMEDIATE", "Which practice improves the accessibility of a mobile app?",
         ["adding text labels and ensuring sufficient color contrast", "making all text tiny", "removing all descriptions", "using only colors to convey meaning"], "C",
         "Labels and contrast help users with visual impairments understand and use the interface."),
        ("INTERMEDIATE", "What is A/B testing in the context of a mobile app?",
         ["testing on two phones at once", "comparing two versions of a feature to measure which performs better", "installing two apps", "writing two test cases"], "D",
         "A/B testing shows different users different versions and uses data to pick the better-performing one."),
        ("INTERMEDIATE", "What is a beta release used for?",
         ["testing a near-final version with a limited audience before the full release", "deleting old versions", "selling the app", "compressing files"], "A",
         "A beta release gathers feedback from a limited group to catch issues before the public release."),
        ("INTERMEDIATE", "Which tool helps track crashes in a released mobile app?",
         ["a text editor", "a crash reporting service such as Crashlytics", "a calendar app", "a font tool"], "B",
         "Crash reporting services collect stack traces from real users so developers can fix crashes."),
        ("INTERMEDIATE", "What does the term dark mode refer to?",
         ["an app that never opens", "a text-only design", "a color theme with light text on a dark background", "a night-time-only feature"], "C",
         "Dark mode uses light text and dark surfaces, which some users prefer and which can save battery on OLED screens."),
        ("INTERMEDIATE", "Why is it important to test an app on a real device before release?",
         ["real devices exercise actual hardware, sensors and performance", "real devices are free", "emulators are banned", "testing is optional"], "D",
         "Real hardware exposes issues with sensors, performance and gestures that emulators cannot fully replicate."),
        ("INTERMEDIATE", "Why should an app explain a permission request to the user?",
         ["to explain why the app needs the permission and build trust", "to make the app slower", "to hide features", "to show an advertisement"], "A",
         "Explaining the reason for a permission builds user trust and reduces the chance of denial."),
        ("INTERMEDIATE", "Which metric is most useful for measuring user retention?",
         ["the percentage of users who return to the app after a period", "the number of source files", "the app icon color", "the phone model used"], "B",
         "Retention measures whether users keep returning, which indicates the app delivers ongoing value."),
        ("ADVANCED", "An app works in portrait but breaks in landscape. What is the best approach?",
         ["provide adaptive layouts for both orientations and test configuration changes", "lock the app to portrait permanently", "ignore the problem", "add more advertisements"], "A",
         "Adaptive layouts and testing both orientations ensure the app works no matter how the user holds the device."),
        ("ADVANCED", "What is the purpose of a staged rollout in the Google Play Console?",
         ["to delete an app", "to gradually release an update to a percentage of users and limit risk", "to change the app name", "to increase prices"], "B",
         "A staged rollout exposes an update to a small percentage of users first, limiting the impact of problems."),
        ("ADVANCED", "Which statement about app store optimization (ASO) is correct?",
         ["it guarantees the top of the charts", "it only involves the icon", "it improves an app's visibility through its title, keywords and screenshots", "it is illegal"], "C",
         "ASO optimizes metadata such as the title, keywords and screenshots to improve search visibility."),
        ("ADVANCED", "What is the primary risk of shipping an app that logs sensitive data to the console?",
         ["it slows the app", "it increases the app size", "it is required by stores", "it can expose secrets or user data in logs and crash reports"], "D",
         "Sensitive data in logs may end up in crash reports and analytics, leaking credentials or user information."),
        ("ADVANCED", "How should a team decide whether to ship a new feature in a released app?",
         ["use feature flags to roll out and measure impact incrementally", "remove the app", "release everything at once without testing", "skip analytics"], "A",
         "Feature flags let a team enable a feature for a subset of users, measure it and roll back if needed."),
        ("ADVANCED", "What is the recommended way to handle app icons across devices?",
         ["one fixed size for all devices", "provide multiple densities using adaptive icons on Android and asset catalogs on iOS", "use one tiny image", "icons are not needed"], "B",
         "Adaptive icons and asset catalogs supply correctly scaled versions of the icon for each screen density."),
        ("ADVANCED", "Why should a UI be tested on devices with small screens?",
         ["it improves battery life", "it is optional", "small screens are still widely used and often expose layout overflow issues", "it reduces the code size"], "C",
         "Testing small screens catches layout overflow and usability problems that affect a large share of users."),
        ("ADVANCED", "What is the purpose of a privacy policy for a store-submitted mobile app?",
         ["it is only for lawyers", "it lets the app read the clipboard", "it discloses how user data is collected and used, and is often required by app stores", "it replaces the app icon"], "D",
         "A privacy policy explains data collection and usage, and stores often require one before approval."),
        ("ADVANCED", "What does the minSdkVersion setting control in an Android build?",
         ["the lowest Android version the app supports", "the highest Android version", "the app size", "the font scale"], "A",
         "minSdkVersion sets the oldest Android version on which the app is allowed to install and run."),
        ("ADVANCED", "Which release practice best catches device-specific issues before a wide launch?",
         ["skip the beta program", "run a staged beta program across diverse devices and respond to feedback", "release only to one phone model", "never test"], "B",
         "A diverse beta program surfaces device-specific bugs on many models and OS versions before the full launch."),
    ],
}
