# -*- coding: utf-8 -*-
"""
Question bank for subject 55: AI107 - Advanced Machine Learning.
Category: Artificial Intelligence & Data Science.
Semester: 7.

Topics (match question_catalog.py):
  271: Ensemble Methods
  272: Deep Neural Networks
  273: CNN & RNN Architectures
  274: Reinforcement Learning
  275: Transformers & Deployment

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    271: [
        ("BEGINNER", "What is an ensemble method?",
         ["Combining multiple models to improve predictions", "Training a single model", "Deleting models", "Using one dataset"], "A",
         "Ensembles aggregate multiple models for better performance."),
        ("BEGINNER", "What is bagging?",
         ["Training models on bootstrap samples and averaging predictions", "Training one model", "Boosting weights", "Deleting data"], "A",
         "Bagging reduces variance by combining diverse models."),
        ("BEGINNER", "What is boosting?",
         ["Sequentially training models to correct previous errors", "Training in parallel", "Averaging all models", "Deleting weak models"], "A",
         "Boosting focuses on hard-to-classify examples."),
        ("BEGINNER", "What is a random forest?",
         ["An ensemble of decision trees", "A single tree", "A clustering method", "A regression line"], "A",
         "Random forests average many trees."),
        ("BEGINNER", "What is a weak learner?",
         ["A model only slightly better than random", "A perfect model", "A deep network", "A database"], "A",
         "Weak learners are simple models with modest accuracy."),
        ("BEGINNER", "What is voting in ensemble learning?",
         ["Combining model predictions by majority or average", "Training one model", "Deleting models", "Selecting one model"], "A",
         "Voting aggregates the decisions of many models."),
        ("BEGINNER", "What is a base learner?",
         ["An individual model in an ensemble", "The final ensemble", "A dataset", "A label"], "A",
         "Base learners are the components of an ensemble."),
        ("BEGINNER", "What does random forest randomize?",
         ["Data samples and feature subsets for each tree", "Labels", "Final predictions", "Data sizes"], "A",
         "Randomness decorrelates the trees."),
        ("BEGINNER", "What is AdaBoost?",
         ["A boosting algorithm that reweights misclassified examples", "A clustering method", "A regression", "A single tree"], "A",
         "AdaBoost emphasizes examples previous models got wrong."),
        ("BEGINNER", "What is the main goal of ensembling?",
         ["Improving accuracy and robustness", "Reducing data", "Speeding training", "Deleting features"], "A",
         "Ensembles generally outperform single models."),
        ("INTERMEDIATE", "Which ensemble reduces variance by averaging trees?",
         ["Random forest (bagging)", "AdaBoost", "XGBoost only", "Stacking"], "A",
         "Random forests average many trees to lower variance."),
        ("INTERMEDIATE", "Which ensemble reduces bias by correcting errors?",
         ["Boosting", "Bagging", "Random forest", "Voting"], "A",
         "Boosting iteratively fixes previous mistakes."),
        ("INTERMEDIATE", "What is gradient boosting?",
         ["Adding models that fit the residuals of current predictions", "Averaging all models", "Clustering residuals", "Deleting errors"], "A",
         "Gradient boosting fits new models to residual errors."),
        ("INTERMEDIATE", "What is XGBoost known for?",
         ["Efficient, regularized gradient boosting", "Simple bagging", "Linear regression", "Kernel SVMs"], "A",
         "XGBoost is a fast, scalable boosting library."),
        ("INTERMEDIATE", "What is stacking?",
         ["Using a meta-model to combine base model predictions", "Averaging identical models", "Deleting models", "Training one model"], "A",
         "Stacking learns how to best combine base predictions."),
        ("INTERMEDIATE", "What does the diversity of base models contribute?",
         ["Different errors that can cancel out", "Identical outputs", "Less accuracy", "No effect"], "A",
         "Diversity makes ensembles more robust."),
        ("INTERMEDIATE", "Which sampling does bagging use?",
         ["Bootstrap sampling with replacement", "Stratified fixed sampling", "No sampling", "Sequential sampling"], "A",
         "Bootstrap samples vary the training data per model."),
        ("INTERMEDIATE", "What is hard voting?",
         ["Majority vote of class predictions", "Averaging probabilities", "Weighted regression", "Deleting votes"], "A",
         "Hard voting chooses the most common class."),
        ("INTERMEDIATE", "What is soft voting?",
         ["Averaging predicted probabilities", "Counting classes", "Choosing one model", "Deleting models"], "A",
         "Soft voting averages class probabilities."),
        ("INTERMEDIATE", "Why are random forests less prone to overfitting than single trees?",
         ["Averaging many decorrelated trees reduces variance", "They ignore data", "They use one tree", "They delete features"], "A",
         "Averaging smooths individual tree errors."),
        ("ADVANCED", "What is the key difference between bagging and boosting?",
         ["Bagging trains in parallel on samples; boosting trains sequentially on errors", "They are identical", "Bagging boosts weights", "Boosting averages samples"], "A",
         "Bagging reduces variance; boosting reduces bias."),
        ("ADVANCED", "What is the role of learning rate in boosting?",
         ["Shrinking each model's contribution to avoid overfitting", "Speeding data loading", "Setting cluster count", "Choosing features"], "A",
         "Smaller learning rates require more trees but generalize better."),
        ("ADVANCED", "What does AdaBoost's weight update emphasize?",
         ["Misclassified examples get higher weights", "Correct examples get higher weights", "All weights stay equal", "Weights are deleted"], "A",
         "Harder examples drive subsequent learners."),
        ("ADVANCED", "What is a limitation of AdaBoost with noisy data?",
         ["It can overemphasize outliers and overfit", "It ignores outliers", "It always generalizes", "It needs no learners"], "A",
         "Noise can misdirect AdaBoost's weighting."),
        ("ADVANCED", "What is the purpose of feature subsampling in random forests?",
         ["Decorrelating trees by using random feature subsets", "Deleting features", "Adding features", "Labeling data"], "A",
         "Feature randomness reduces correlation among trees."),
        ("ADVANCED", "Which boosting algorithm uses second-order gradients?",
         ["XGBoost", "AdaBoost", "Random forest", "Simple bagging"], "A",
         "XGBoost uses first and second derivatives for optimization."),
        ("ADVANCED", "What is the benefit of gradient boosting over random forest on some tasks?",
         ["It often achieves higher accuracy by correcting residuals", "It is always simpler", "It needs no tuning", "It ignores features"], "A",
         "Sequential residual fitting can yield better accuracy."),
        ("ADVANCED", "What is a meta-model in stacking?",
         ["The model that learns to combine base predictions", "A single base tree", "The dataset", "The label set"], "A",
         "The meta-model blends base learner outputs."),
        ("ADVANCED", "What is the main risk of overfitting in boosting?",
         ["Too many boosting rounds can memorize noise", "More trees reduce accuracy always", "Boosting cannot overfit", "No risk exists"], "A",
         "Excessive rounds lead to overfitting."),
        ("ADVANCED", "How does early stopping help boosted trees?",
         ["It halts training when validation performance stops improving", "It deletes trees", "It adds noise", "It slows training"], "A",
         "Early stopping controls boosting rounds."),
    ],
    272: [
        ("BEGINNER", "What is a neural network?",
         ["A model made of interconnected neurons that learns patterns", "A database", "A spreadsheet", "A decision tree"], "A",
         "Neural networks learn by adjusting connection weights."),
        ("BEGINNER", "What is a neuron in a neural network?",
         ["A computing unit that applies an activation to weighted inputs", "A data label", "A training file", "A cluster"], "A",
         "Neurons compute weighted sums and apply activations."),
        ("BEGINNER", "What is a layer in a neural network?",
         ["A group of neurons at the same depth", "A single weight", "A dataset", "A feature"], "A",
         "Layers organize neurons in sequence."),
        ("BEGINNER", "What does the input layer receive?",
         ["The features of the data", "The predictions", "The labels", "The errors"], "A",
         "The input layer consumes the data features."),
        ("BEGINNER", "What does the output layer produce?",
         ["The model's prediction", "The training data", "The weights", "The loss"], "A",
         "The output layer emits the final prediction."),
        ("BEGINNER", "What is an activation function?",
         ["A function that adds nonlinearity to the neuron output", "A data loader", "A loss function", "A cluster method"], "A",
         "Activations enable learning nonlinear patterns."),
        ("BEGINNER", "What is deep learning?",
         ["Training neural networks with many layers", "Training single neurons", "Using one hidden layer", "Clustering data"], "A",
         "Deep learning uses deep and wide network architectures."),
        ("BEGINNER", "What are weights in a neural network?",
         ["Learned parameters that scale inputs", "The data labels", "The training set", "The output classes"], "A",
         "Weights determine the influence of each input."),
        ("BEGINNER", "What is backpropagation?",
         ["The algorithm that computes gradients to update weights", "A data preprocessing step", "A clustering method", "A visualization tool"], "A",
         "Backpropagation propagates errors backward to update weights."),
        ("BEGINNER", "What is an epoch?",
         ["One full pass over the training data", "One neuron", "One weight", "One batch"], "A",
         "An epoch is a complete training data pass."),
        ("INTERMEDIATE", "Which activation is commonly used in hidden layers?",
         ["ReLU", "Softmax only", "Linear only", "No activation"], "A",
         "ReLU is efficient and widely used in hidden layers."),
        ("INTERMEDIATE", "Which loss is used for multi-class classification?",
         ["Categorical cross-entropy", "Squared error only", "Zero-one", "No loss"], "A",
         "Cross-entropy suits classification outputs."),
        ("INTERMEDIATE", "What is a batch in training?",
         ["A subset of data processed together", "A full dataset", "A single weight", "A layer"], "A",
         "Batches speed gradient updates."),
        ("INTERMEDIATE", "What is the role of dropout?",
         ["Randomly disabling neurons during training to prevent overfitting", "Adding neurons", "Deleting data", "Increasing layers"], "A",
         "Dropout regularizes neural networks."),
        ("INTERMEDIATE", "What is batch normalization?",
         ["Normalizing layer inputs to stabilize training", "Shuffling data", "Compressing models", "Deleting layers"], "A",
         "Batch normalization accelerates and stabilizes training."),
        ("INTERMEDIATE", "What is a hidden layer?",
         ["A layer between the input and output layers", "The input layer", "The output layer", "A data label"], "A",
         "Hidden layers compute intermediate representations."),
        ("INTERMEDIATE", "What does the softmax function produce?",
         ["A probability distribution over classes", "A binary output", "A single value", "A cluster label"], "A",
         "Softmax converts logits into probabilities."),
        ("INTERMEDIATE", "What is an optimizer's role?",
         ["To update weights to minimize the loss", "To load data", "To add layers", "To label data"], "A",
         "Optimizers such as Adam update weights."),
        ("INTERMEDIATE", "What is a loss function?",
         ["A measure of the difference between predictions and targets", "A dataset", "An activation", "A layer type"], "A",
         "Loss quantifies model error."),
        ("INTERMEDIATE", "What does the learning rate control?",
         ["How much weights change per update", "The dataset size", "The number of layers", "The label count"], "A",
         "Learning rate scales gradient updates."),
        ("ADVANCED", "What is the vanishing gradient problem?",
         ["Gradients become tiny in deep networks, slowing learning", "Gradients explode", "Data is missing", "Weights vanish"], "A",
         "Small gradients in early layers hinder training."),
        ("ADVANCED", "What is the exploding gradient problem?",
         ["Gradients grow very large, destabilizing training", "Gradients disappear", "Weights are fixed", "Data is lost"], "A",
         "Large gradients can cause unstable weight updates."),
        ("ADVANCED", "What is transfer learning?",
         ["Using a pretrained model and fine-tuning for a new task", "Training from scratch", "Deleting weights", "Clustering data"], "A",
         "Transfer learning leverages learned representations."),
        ("ADVANCED", "What is gradient clipping?",
         ["Limiting gradient magnitude to prevent explosions", "Deleting gradients", "Adding gradients", "Speeding data load"], "A",
         "Clipping stabilizes training."),
        ("ADVANCED", "What is the purpose of an embedding layer?",
         ["Mapping categorical or token data into dense vectors", "Clustering data", "Adding noise", "Reducing labels"], "A",
         "Embeddings represent discrete inputs numerically."),
        ("ADVANCED", "Which optimizer adapts per-parameter learning rates?",
         ["Adam", "Plain SGD", "Batch gradient descent", "Random search"], "A",
         "Adam combines momentum with adaptive learning rates."),
        ("ADVANCED", "What does weight initialization affect?",
         ["How well and how fast a network trains", "The dataset", "The labels", "The output classes"], "A",
         "Good initialization avoids symmetric or extreme weights."),
        ("ADVANCED", "What is the purpose of a validation set in deep learning?",
         ["To tune hyperparameters without using the test set", "To train the model", "To delete data", "To label examples"], "A",
         "Validation guides hyperparameter selection."),
        ("ADVANCED", "What does early stopping prevent?",
         ["Overfitting by halting training when validation stops improving", "Data loading", "Weight updates", "Feature selection"], "A",
         "Early stopping keeps the best validation model."),
        ("ADVANCED", "What is the purpose of regularization in deep networks?",
         ["To reduce overfitting by penalizing complexity", "To delete features", "To speed data loading", "To add labels"], "A",
         "Regularization improves generalization."),
    ],
    273: [
        ("BEGINNER", "What is a convolutional neural network (CNN)?",
         ["A network designed for grid-like data such as images", "A network for text only", "A regression model", "A clustering method"], "A",
         "CNNs exploit spatial structure in images."),
        ("BEGINNER", "What does a convolution layer do?",
         ["Applies filters to extract local features", "Adds neurons", "Deletes data", "Labels images"], "A",
         "Convolutions detect patterns such as edges."),
        ("BEGINNER", "What is a filter (kernel) in a CNN?",
         ["A small weight matrix that scans the input", "A data class", "A loss function", "An optimizer"], "A",
         "Filters extract localized features."),
        ("BEGINNER", "What is a feature map?",
         ["The output of a convolution applied to the input", "A data label", "A training epoch", "A weight value"], "A",
         "Feature maps encode detected patterns."),
        ("BEGINNER", "What is pooling?",
         ["Downsampling feature maps to reduce their size", "Adding neurons", "Increasing resolution", "Deleting filters"], "A",
         "Pooling reduces spatial dimensions and computation."),
        ("BEGINNER", "What is max pooling?",
         ["Taking the maximum value in each pooling window", "Taking the average", "Summing all values", "Deleting values"], "A",
         "Max pooling keeps the strongest activation."),
        ("BEGINNER", "What is an RNN?",
         ["A recurrent neural network for sequential data", "A network for images", "A clustering model", "A database"], "A",
         "RNNs process sequences with hidden state memory."),
        ("BEGINNER", "What does the hidden state of an RNN represent?",
         ["The memory of past inputs", "The final label", "The batch size", "The learning rate"], "A",
         "Hidden states carry information across time steps."),
        ("BEGINNER", "What is an LSTM?",
         ["A recurrent unit with gates to manage long-term memory", "A convolutional filter", "A pooling layer", "A decision tree"], "A",
         "LSTMs mitigate the vanishing gradient problem in sequences."),
        ("BEGINNER", "What is a sequence model used for?",
         ["Predicting outputs from ordered data such as time series", "Classifying images", "Clustering rows", "Formatting disks"], "A",
         "Sequence models handle temporal dependencies."),
        ("INTERMEDIATE", "Which operation slides a kernel across the input?",
         ["Convolution", "Pooling", "Flattening", "Softmax"], "A",
         "Convolution scans windows across the input."),
        ("INTERMEDIATE", "What does stride control in a convolution?",
         ["The step size of the kernel movement", "The number of filters", "The learning rate", "The batch size"], "A",
         "Larger strides reduce output size."),
        ("INTERMEDIATE", "What does padding do in a convolution?",
         ["Adds border values to preserve spatial dimensions", "Deletes pixels", "Increases the learning rate", "Adds labels"], "A",
         "Padding controls output size and edge information."),
        ("INTERMEDIATE", "What is a CNN usually followed by at the end?",
         ["Fully connected layers and softmax", "Another convolution", "Pooling only", "Clustering"], "A",
         "Dense layers perform the final classification."),
        ("INTERMEDIATE", "Which task is a CNN typically applied to?",
         ["Image classification", "Sorting a list", "Database queries", "File compression"], "A",
         "CNNs excel at computer vision tasks."),
        ("INTERMEDIATE", "What is the purpose of average pooling?",
         ["Taking the mean value in each pooling window", "Taking the maximum", "Deleting values", "Adding values"], "A",
         "Average pooling smooths feature maps."),
        ("INTERMEDIATE", "What is the vanishing gradient issue in plain RNNs?",
         ["Gradients shrink over long sequences, limiting memory", "Gradients grow", "Weights are deleted", "Data disappears"], "A",
         "Long sequences make backpropagation through time difficult."),
        ("INTERMEDIATE", "Which unit has input, forget, and output gates?",
         ["LSTM", "Perceptron", "k-means", "Linear regression"], "A",
         "LSTM gates control what to remember and forget."),
        ("INTERMEDIATE", "What does the forget gate in an LSTM decide?",
         ["Which past information to discard", "Which filters to use", "The batch size", "The learning rate"], "A",
         "Forgetting irrelevant memory helps long-term learning."),
        ("INTERMEDIATE", "What is a GRU?",
         ["A simplified recurrent unit with fewer gates than LSTM", "A convolutional filter", "A pooling layer", "A clustering model"], "A",
         "GRUs are a lightweight alternative to LSTMs."),
        ("ADVANCED", "What is a 1x1 convolution used for?",
         ["Changing the number of channels cheaply", "Increasing image size", "Adding labels", "Deleting filters"], "A",
         "1x1 convolutions adjust channel depth."),
        ("ADVANCED", "What is the receptive field of a CNN layer?",
         ["The input region that influences an output pixel", "The full dataset", "The batch size", "The learning rate"], "A",
         "Stacked layers grow the receptive field."),
        ("ADVANCED", "What is a residual connection?",
         ["Adding the layer input to its output to ease training", "Deleting layers", "Doubling weights", "Shuffling data"], "A",
         "Residuals help train very deep networks."),
        ("ADVANCED", "What does batch normalization inside a CNN do?",
         ["Normalizes activations to stabilize training", "Increases resolution", "Deletes channels", "Adds noise"], "A",
         "Normalization speeds and stabilizes convergence."),
        ("ADVANCED", "What is backpropagation through time (BPTT)?",
         ["Backpropagation applied to the unrolled RNN", "Forward-only training", "A clustering step", "Data augmentation"], "A",
         "BPTT computes gradients across time steps."),
        ("ADVANCED", "Why do attention mechanisms help RNNs?",
         ["They allow the model to focus on relevant time steps", "They delete time steps", "They add noise", "They slow training"], "A",
         "Attention improves long-range dependencies."),
        ("ADVANCED", "What is data augmentation in CNNs?",
         ["Generating varied training images via transformations", "Deleting images", "Reducing resolution", "Adding labels"], "A",
         "Augmentation reduces overfitting."),
        ("ADVANCED", "What is a pretrained CNN backbone?",
         ["A network trained on large data, reused for new tasks", "A random network", "A clustering model", "A database"], "A",
         "Pretrained backbones enable transfer learning."),
        ("ADVANCED", "What is the purpose of global average pooling?",
         ["Replacing flattening to reduce parameters", "Adding layers", "Increasing resolution", "Deleting filters"], "A",
         "Global average pooling condenses feature maps."),
        ("ADVANCED", "Which concept lets a CNN reuse the same filter across positions?",
         ["Weight sharing", "Pooling", "Flattening", "Dropout"], "A",
         "Weight sharing massively reduces parameters."),
    ],
    274: [
        ("BEGINNER", "What is reinforcement learning?",
         ["Learning by interacting with an environment to maximize reward", "Learning from labeled examples", "Learning from unlabeled data", "Deleting data"], "A",
         "RL agents learn from rewards and punishments."),
        ("BEGINNER", "What is an agent in reinforcement learning?",
         ["The learner that takes actions in an environment", "The dataset", "The reward", "The label"], "A",
         "The agent selects actions to influence the environment."),
        ("BEGINNER", "What is the environment in RL?",
         ["The world the agent interacts with", "The training data", "The model weights", "The loss function"], "A",
         "The environment responds to the agent's actions."),
        ("BEGINNER", "What is a reward?",
         ["A signal indicating how good an action was", "A data label", "A feature", "A weight"], "A",
         "Rewards guide the agent's learning."),
        ("BEGINNER", "What is an action in RL?",
         ["A choice the agent makes in the environment", "A neural layer", "A dataset", "A metric"], "A",
         "Actions move the agent through states."),
        ("BEGINNER", "What is a state in RL?",
         ["The current situation of the agent", "A saved model", "A weight", "A label"], "A",
         "States describe what the agent observes."),
        ("BEGINNER", "What is a policy?",
         ["A strategy mapping states to actions", "A dataset", "A reward", "A loss"], "A",
         "Policies determine which action the agent takes."),
        ("BEGINNER", "What is Q-learning?",
         ["A model-free algorithm that learns action values", "A clustering method", "A CNN", "A regression"], "A",
         "Q-learning updates Q-values from experience."),
        ("BEGINNER", "What is a Q-value?",
         ["The expected return of taking an action in a state", "The learning rate", "The batch size", "The reward only"], "A",
         "Q-values estimate action quality."),
        ("BEGINNER", "What does exploration mean in RL?",
         ["Trying new actions to discover better rewards", "Repeating the best action", "Deleting actions", "Formatting data"], "A",
         "Exploration balances learning with exploitation."),
        ("INTERMEDIATE", "What is an MDP?",
         ["Markov Decision Process, a formal RL framework", "A neural network", "A dataset", "A reward schedule"], "A",
         "MDPs formalize states, actions, and rewards."),
        ("INTERMEDIATE", "What is the discount factor in RL?",
         ["A value controlling the importance of future rewards", "The learning rate", "The batch size", "The number of episodes"], "A",
         "Discounting values near-term rewards more."),
        ("INTERMEDIATE", "What is the exploration-exploitation trade-off?",
         ["Balancing trying new actions with using known good ones", "Choosing the best model", "Deleting data", "Formatting drives"], "A",
         "Agents must explore to improve but exploit to gain reward."),
        ("INTERMEDIATE", "What is an episode in RL?",
         ["A complete run from start to terminal state", "A training epoch", "A weight update", "A data batch"], "A",
         "Episodes end at terminal states."),
        ("INTERMEDIATE", "What does the epsilon-greedy strategy do?",
         ["Mostly exploits but explores with probability epsilon", "Always explores", "Never explores", "Deletes actions"], "A",
         "Epsilon-greedy balances exploration and exploitation."),
        ("INTERMEDIATE", "What is temporal difference (TD) learning?",
         ["Updating estimates using predicted future values", "Deleting data", "Clustering states", "Formatting drives"], "A",
         "TD learning combines Monte Carlo and dynamic programming."),
        ("INTERMEDIATE", "What is the Bellman equation used for?",
         ["Relating value estimates of successive states", "Computing gradients", "Loading data", "Formatting disks"], "A",
         "The Bellman equation underpins value learning."),
        ("INTERMEDIATE", "What is a model-based RL approach?",
         ["Learning a model of the environment to plan", "Learning only from rewards", "Clustering states", "Deleting models"], "A",
         "Model-based agents predict environment dynamics."),
        ("INTERMEDIATE", "What is a model-free RL approach?",
         ["Learning directly from experience without an environment model", "Planning with a model", "Deleting experience", "Formatting drives"], "A",
         "Model-free methods like Q-learning need no model."),
        ("INTERMEDIATE", "What does the reward signal motivate?",
         ["The behavior the agent should maximize", "The dataset size", "The learning rate", "The model depth"], "A",
         "Rewards define the goal of the agent."),
        ("ADVANCED", "What is deep Q-learning (DQN)?",
         ["Using a deep network to approximate Q-values", "A decision tree", "A clustering method", "A linear model"], "A",
         "DQN scales Q-learning to large state spaces."),
        ("ADVANCED", "What is the purpose of an experience replay buffer?",
         ["Storing past transitions to decorrelate training samples", "Deleting old data", "Formatting drives", "Adding noise"], "A",
         "Replay stabilizes deep RL training."),
        ("ADVANCED", "What is a target network in DQN?",
         ["A slowly updated network used to stabilize targets", "The main policy", "A dataset", "A reward"], "A",
         "Target networks reduce training instability."),
        ("ADVANCED", "What are policy gradient methods?",
         ["Optimizing the policy directly with gradients", "Learning Q-values only", "Clustering states", "Deleting policies"], "A",
         "Policy gradients optimize action selection probabilities."),
        ("ADVANCED", "What is the goal of an RL agent in the long term?",
         ["Maximizing cumulative discounted reward", "Maximizing immediate reward only", "Minimizing exploration", "Deleting actions"], "A",
         "Long-term return guides optimal behavior."),
        ("ADVANCED", "What is actor-critic architecture?",
         ["Combining a policy actor with a value critic", "A single network", "A clustering model", "A database"], "A",
         "Actor-critic methods reduce variance in policy gradients."),
        ("ADVANCED", "What is the sparse reward problem?",
         ["Rewards appear rarely, making learning difficult", "Rewards appear always", "Rewards are deleted", "Rewards are random"], "A",
         "Sparse rewards slow credit assignment."),
        ("ADVANCED", "What is reward shaping?",
         ["Adding intermediate rewards to guide learning", "Deleting rewards", "Formatting drives", "Hiding rewards"], "A",
         "Shaping accelerates learning in sparse-reward tasks."),
        ("ADVANCED", "What is the value function of a state?",
         ["The expected return starting from that state", "The immediate reward", "The batch size", "The policy only"], "A",
         "Value functions estimate long-term worth."),
        ("ADVANCED", "What is the credit assignment problem?",
         ["Determining which actions caused a reward", "Assigning weights", "Formatting drives", "Deleting actions"], "A",
         "Credit assignment is central to RL learning."),
    ],
    275: [
        ("BEGINNER", "What is an attention mechanism?",
         ["A technique to focus on relevant parts of the input", "A data loader", "A clustering method", "A format command"], "A",
         "Attention weights the importance of input elements."),
        ("BEGINNER", "What is a transformer?",
         ["A model built on attention mechanisms", "A decision tree", "A clustering method", "A database"], "A",
         "Transformers rely on self-attention rather than recurrence."),
        ("BEGINNER", "What is self-attention?",
         ["Attention computed among the elements of one sequence", "Attention between two sequences", "A pooling layer", "A loss function"], "A",
         "Self-attention relates positions within a sequence."),
        ("BEGINNER", "What is a query in attention?",
         ["The vector used to search for relevant information", "The output label", "The batch size", "The learning rate"], "A",
         "Queries identify what to focus on."),
        ("BEGINNER", "What is a key in attention?",
         ["The vector matched against queries", "The reward", "The loss", "The dataset"], "A",
         "Keys are compared with queries to compute scores."),
        ("BEGINNER", "What is a value in attention?",
         ["The vector that carries the information to aggregate", "The label", "The weight", "The epoch"], "A",
         "Values are combined according to attention weights."),
        ("BEGINNER", "What is model deployment?",
         ["Making a trained model available to serve predictions", "Training the model", "Deleting the model", "Labeling data"], "A",
         "Deployment integrates the model into production."),
        ("BEGINNER", "What is an API endpoint in deployment?",
         ["A URL through which predictions are requested", "A training loop", "A dataset", "A weight"], "A",
         "Endpoints expose the model to clients."),
        ("BEGINNER", "What is model versioning?",
         ["Tracking different trained versions of a model", "Deleting models", "Merging models", "Labeling data"], "A",
         "Versioning enables rollback and reproducibility."),
        ("BEGINNER", "What is model monitoring?",
         ["Watching model performance in production", "Training the model", "Deleting the model", "Loading data"], "A",
         "Monitoring detects performance decay."),
        ("INTERMEDIATE", "What is multi-head attention?",
         ["Running several attention operations in parallel", "A single attention pass", "A pooling layer", "A loss function"], "A",
         "Multi-head attention captures diverse relationships."),
        ("INTERMEDIATE", "What is positional encoding in transformers?",
         ["Adding order information to token embeddings", "Deleting tokens", "Clustering tokens", "Formatting disks"], "A",
         "Transformers have no built-in order, so encodings add it."),
        ("INTERMEDIATE", "What is a large language model (LLM)?",
         ["A large transformer trained on vast text data", "A small classifier", "A clustering model", "A database"], "A",
         "LLMs generate and understand language."),
        ("INTERMEDIATE", "What is fine-tuning?",
         ["Adapting a pretrained model to a specific task", "Training from scratch", "Deleting weights", "Clustering data"], "A",
         "Fine-tuning transfers learned knowledge to new tasks."),
        ("INTERMEDIATE", "What is BERT?",
         ["A bidirectional transformer pretrained on text", "A convolutional network", "A clustering method", "A database"], "A",
         "BERT learns contextual word representations."),
        ("INTERMEDIATE", "What is GPT?",
         ["A generative pretrained transformer for text generation", "A clustering model", "A decision tree", "A database"], "A",
         "GPT generates coherent text autoregressively."),
        ("INTERMEDIATE", "What is a serving environment?",
         ["The infrastructure that hosts the deployed model", "The training data", "The test set", "The labels"], "A",
         "Serving environments run inference at scale."),
        ("INTERMEDIATE", "What is batch inference?",
         ["Generating predictions for a group of records at once", "Predicting one record", "Deleting records", "Training models"], "A",
         "Batch inference processes large sets efficiently."),
        ("INTERMEDIATE", "What is real-time inference?",
         ["Serving predictions immediately for individual requests", "Batch processing", "Offline analysis", "Deleting data"], "A",
         "Real-time inference supports interactive applications."),
        ("INTERMEDIATE", "What is a model registry?",
         ["A central store of model versions and metadata", "A confusion matrix", "A training log", "A dataset"], "A",
         "Registries manage the model lifecycle."),
        ("ADVANCED", "What is a transformer encoder?",
         ["The stack that processes inputs into contextual representations", "The output only", "A pooling layer", "A loss function"], "A",
         "Encoders build rich input representations."),
        ("ADVANCED", "What is a transformer decoder?",
         ["The stack that generates outputs from representations", "The input only", "A clustering model", "A database"], "A",
         "Decoders produce sequences token by token."),
        ("ADVANCED", "What is the softmax over attention scores used for?",
         ["Normalizing scores into attention weights", "Formatting disks", "Deleting scores", "Adding noise"], "A",
         "Softmax converts scores into a distribution."),
        ("ADVANCED", "What is tokenization in transformers?",
         ["Splitting text into tokens the model can process", "Clustering text", "Formatting disks", "Deleting words"], "A",
         "Subword tokenization balances vocabulary and size."),
        ("ADVANCED", "What is model drift?",
         ["A decline in model performance as data changes", "A training pause", "A weight update", "A data split"], "A",
         "Drift occurs when production data differs from training data."),
        ("ADVANCED", "What is data drift?",
         ["A change in the input data distribution over time", "A weight update", "A training loop", "A data split"], "A",
         "Data drift degrades model relevance."),
        ("ADVANCED", "What is concept drift?",
         ["A change in the relationship between inputs and outputs", "A data error", "A model weight", "A feature"], "A",
         "Concept drift invalidates learned patterns."),
        ("ADVANCED", "What does model retraining involve?",
         ["Re-fitting the model on updated data", "Deleting the model", "Freezing weights", "Loading one batch"], "A",
         "Retraining keeps models current."),
        ("ADVANCED", "What is a shadow deployment?",
         ["Running a new model alongside the old one without serving its outputs", "Deleting the old model", "Training offline", "Labeling data"], "A",
         "Shadow mode evaluates the new model safely."),
        ("ADVANCED", "What does monitoring latency measure in a deployed model?",
         ["The time taken to serve predictions", "The training time", "The data size", "The number of epochs"], "A",
         "Latency impacts user experience."),
    ],
}
