# -*- coding: utf-8 -*-
"""
Question bank for subject 43: ENG101 - Communication Skills & Technical English.
Category: Core Computer Science & Emerging Technologies.

Topics:
  211: English Grammar & Vocabulary
  212: Technical Writing
  213: Listening & Speaking
  214: Presentation & Group Discussion
  215: Professional Communication

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    211: [
        ("BEGINNER", "Which of the following words is a noun?",
         ["Beautiful", "Happiness", "Quickly", "Under"], "B",
         "'Happiness' names a thing or concept and is therefore a noun."),
        ("BEGINNER", "Identify the verb in the sentence: 'She writes reports.'",
         ["She", "writes", "reports", "the"], "B",
         "'Writes' expresses the action performed, making it the verb."),
        ("BEGINNER", "Which article is used before a word beginning with a vowel sound?",
         ["a", "an", "the always", "no article"], "B",
         "'An' is used before vowel sounds, such as 'an apple'."),
        ("BEGINNER", "What is the plural form of 'child'?",
         ["Childs", "Children", "Childes", "Childrens"], "B",
         "'Child' has the irregular plural 'children'."),
        ("BEGINNER", "Choose the correct past tense of 'go':",
         ["Goed", "Gone", "Went", "Goes"], "C",
         "'Go' is irregular; its simple past form is 'went'."),
        ("BEGINNER", "Which sentence is in the present continuous tense?",
         ["He plays football", "He is playing football", "He played football", "He will play football"], "B",
         "'Is playing' uses the present continuous structure am/is/are + -ing form."),
        ("BEGINNER", "Select the preposition in: 'The book is on the table.'",
         ["book", "is", "on", "table"], "C",
         "'On' shows the relationship of the book to the table, so it is a preposition."),
        ("BEGINNER", "Which word is an antonym of 'happy'?",
         ["Joyful", "Sad", "Cheerful", "Glad"], "B",
         "Antonyms are words with opposite meanings, so 'sad' opposes 'happy'."),
        ("BEGINNER", "Which word is a synonym of 'large'?",
         ["Small", "Tiny", "Big", "Narrow"], "C",
         "'Big' has a similar meaning to 'large', making it a synonym."),
        ("BEGINNER", "Identify the adjective in: 'The red car is fast.'",
         ["car", "red", "is", "fastly"], "B",
         "'Red' describes the noun 'car', so it is an adjective."),
        ("INTERMEDIATE", "Choose the correctly spelled word:",
         ["Recieve", "Receive", "Receeve", "Receve"], "B",
         "'Receive' follows the rule 'i before e except after c'."),
        ("INTERMEDIATE", "Select the sentence with correct subject-verb agreement:",
         ["The team are winning", "The list of items are long", "Each of the students has a book", "The children has gone home"], "C",
         "'Each' is singular, so it takes the singular verb 'has'."),
        ("INTERMEDIATE", "Which option correctly uses the future perfect tense?",
         ["I will finish the task", "I will have finished the task by noon", "I have finished the task", "I finished the task"], "B",
         "Future perfect uses 'will have + past participle' to describe completion before a future time."),
        ("INTERMEDIATE", "Identify the type of conjunction in: 'He studied hard but he failed.'",
         ["Coordinating", "Subordinating", "Correlative", "None"], "A",
         "'But' joins two independent clauses, so it is a coordinating conjunction."),
        ("INTERMEDIATE", "Which word is an example of a homophone for 'there'?",
         ["Their", "Thier", "Ther", "Thare"], "A",
         "'Their' sounds the same as 'there' but has a different meaning and spelling."),
        ("INTERMEDIATE", "Choose the sentence in the passive voice:",
         ["The dog bit the man", "The man was bitten by the dog", "The dog is biting", "The dog bites men"], "B",
         "Passive voice places the receiver of the action as the subject using 'was bitten'."),
        ("INTERMEDIATE", "Which of the following is a countable noun?",
         ["Milk", "Rice", "Apple", "Water"], "C",
         "'Apple' can be counted individually, while the others are uncountable."),
        ("INTERMEDIATE", "Fill in the blank: 'Neither of the answers ___ correct.'",
         ["are", "were", "is", "have been"], "C",
         "'Neither' is singular, so the singular verb 'is' is required."),
        ("INTERMEDIATE", "Which sentence correctly uses the past perfect tense?",
         ["She had left before I arrived", "She left before I arrived", "She has left before I arrived", "She leaves before I arrived"], "A",
         "Past perfect 'had left' shows an action completed before another past action."),
        ("INTERMEDIATE", "What is the correct comparative form of 'good'?",
         ["Gooder", "More good", "Better", "Best"], "C",
         "'Good' is irregular; its comparative form is 'better' and superlative 'best'."),
        ("ADVANCED", "Which sentence demonstrates correct use of the subjunctive mood?",
         ["If I was you, I would go", "I wish I were taller", "He wish he was rich", "If it was sunny, we play"], "B",
         "The subjunctive uses 'were' for hypothetical wishes and contrary-to-fact conditions."),
        ("ADVANCED", "Identify the dangling modifier in: 'Walking to the store, the rain began to fall.'",
         ["Walking to the store", "the rain", "began to fall", "to the store"], "A",
         "'Walking to the store' does not logically modify 'the rain', leaving the sentence illogical."),
        ("ADVANCED", "Which sentence contains a parallelism error?",
         ["She likes swimming, hiking, and to jog", "She likes swimming, hiking, and jogging", "He enjoys reading and writing", "They planned, executed, and reviewed the project"], "A",
         "The list mixes gerunds with an infinitive, breaking parallel structure."),
        ("ADVANCED", "Select the correctly punctuated sentence:",
         ["Its a beautiful day", "It's a beautiful day", "Its' a beautiful day", "Its a beautiful day."], "B",
         "'It's' is the contraction of 'it is', which is required here."),
        ("ADVANCED", "Which word correctly completes: 'The committee members ____ their reports yesterday.'",
         ["submits", "submitted", "submitting", "submit"], "B",
         "The past-time adverb 'yesterday' requires the simple past 'submitted'."),
        ("ADVANCED", "Which of the following sentences is correctly punctuated with a semicolon?",
         ["He works hard; however, he rarely succeeds", "He works hard, however, he rarely succeeds", "He works hard; however he rarely succeeds", "He works hard however; he rarely succeeds"], "A",
         "A semicolon correctly links independent clauses joined by 'however'."),
        ("ADVANCED", "Identify the redundant expression:",
         ["Free gift", "Small gift", "Important gift", "Expensive gift"], "A",
         "'Free gift' is redundant because a gift by definition is not paid for."),
        ("ADVANCED", "Which option uses 'its' correctly?",
         ["The dog wagged its tail", "The dog wagged it's tail", "Its a dog", "Its' tail wagged"], "A",
         "'Its' is the possessive pronoun; 'it's' is the contraction of 'it is'."),
        ("ADVANCED", "What is the function of an appositive in a sentence?",
         ["To rename or identify a noun", "To connect two clauses", "To show action", "To express surprise"], "A",
         "An appositive renames a nearby noun, for example 'My friend, a doctor, arrived'."),
        ("ADVANCED", "Which sentence correctly uses a restrictive relative clause?",
         ["The students who study regularly pass", "The students, who study regularly, pass", "The students who study regularly, pass", "The students, who study regularly pass"], "A",
         "A restrictive clause without commas defines which students pass."),
    ],
    212: [
        ("BEGINNER", "What is the purpose of an abstract in a technical report?",
         ["To summarize the main points concisely", "To list all references", "To provide a detailed index", "To give biographical details of the author"], "A",
         "An abstract gives a brief summary so readers quickly grasp the purpose, methods, and results."),
        ("BEGINNER", "Which document formally presents a problem and requests action or approval?",
         ["Report", "Memo", "Proposal", "Abstract"], "C",
         "A proposal formally requests approval, funding, or action for a project or idea."),
        ("BEGINNER", "What is the purpose of an executive summary?",
         ["A concise overview of a longer document for busy decision-makers", "A detailed technical appendix", "A list of abbreviations", "A cover page"], "A",
         "The executive summary condenses key findings and recommendations for quick reading."),
        ("BEGINNER", "Which of these is a standard section of a technical report?",
         ["Methodology", "Mythology", "Melody", "Memorandum"], "A",
         "Technical reports include sections such as introduction, methodology, results, and conclusion."),
        ("BEGINNER", "What is a memo typically used for?",
         ["Short internal business communication", "Publishing a research paper", "Writing a novel", "Submitting a patent"], "A",
         "Memos communicate brief internal messages within an organization."),
        ("BEGINNER", "What is the purpose of a cover letter in a job application?",
         ["To introduce the applicant and highlight relevant skills", "To list the company's products", "To submit a final report", "To record meeting minutes"], "A",
         "A cover letter introduces the candidate and connects their skills to the job requirements."),
        ("BEGINNER", "Which tense is most commonly used in a report's methods section?",
         ["Past tense", "Future tense", "Present perfect only", "Subjunctive"], "A",
         "Methods describe completed actions, so the past tense is standard."),
        ("BEGINNER", "What should a well-written introduction of a report provide?",
         ["Background, purpose, and scope of the work", "The complete data set", "The final recommendation only", "Personal opinions"], "A",
         "An introduction sets the context, states the purpose, and defines the scope."),
        ("BEGINNER", "Which of the following is a common referencing style in engineering?",
         ["IEEE", "MLA only", "APA only", "Chicago only"], "A",
         "IEEE style is widely used in engineering and technical publications."),
        ("BEGINNER", "What does 'proofreading' mean?",
         ["Checking for errors in spelling, grammar, and punctuation", "Writing a first draft", "Designing the layout", "Interviewing sources"], "A",
         "Proofreading is the final careful check for surface errors in a text."),
        ("INTERMEDIATE", "Which sentence is most appropriate for a formal technical report?",
         ["We have concluded that the system is unstable", "The system is, like, totally broken", "I guess the system fails a lot", "The thing doesn't work"], "A",
         "Formal technical writing uses precise, impersonal, complete sentences."),
        ("INTERMEDIATE", "Which section of a report interprets results and relates them to the hypothesis?",
         ["Discussion", "Methodology", "Abstract only", "References"], "A",
         "The discussion explains what the results mean and how they answer the research question."),
        ("INTERMEDIATE", "What is the primary purpose of citations in a technical document?",
         ["To credit sources and enable verification", "To increase the page count", "To decorate the text", "To replace the references list"], "A",
         "Citations give credit and let readers locate the original sources."),
        ("INTERMEDIATE", "Which of the following demonstrates concise technical writing?",
         ["The results indicate a 12 percent improvement", "In this particular instance, it was observed that there was a significant improvement", "It can be stated that the improvement was found to be significant", "Due to the fact that the results show improvement"], "A",
         "Concise writing removes unnecessary words while preserving meaning."),
        ("INTERMEDIATE", "What is the purpose of an appendix in a report?",
         ["To include supporting material such as raw data and detailed tables", "To state the main conclusions", "To introduce the topic", "To thank sponsors"], "A",
         "Appendices hold supplementary detail that would interrupt the main narrative."),
        ("INTERMEDIATE", "A 'white paper' is best described as:",
         ["An authoritative report presenting a problem and a proposed solution", "A casual blog post", "A personal diary", "A product price list"], "A",
         "White papers persuade and inform audiences about a technical topic or solution."),
        ("INTERMEDIATE", "Which type of chart is best for showing a trend over time?",
         ["Line chart", "Pie chart", "Bar chart with categories only", "Scatter plot of categories"], "A",
         "Line charts effectively display changes in values across a time axis."),
        ("INTERMEDIATE", "Which sentence is written in the passive voice?",
         ["The sample was heated to 100 C", "We heated the sample", "The technician heated the sample", "Heat the sample"], "A",
         "Passive voice places the object first, using 'was heated'."),
        ("INTERMEDIATE", "In technical writing, the term 'audience analysis' means:",
         ["Identifying the readers' knowledge and needs", "Counting readers", "Measuring page length", "Checking grammar only"], "A",
         "Audience analysis tailors content and tone to the readers' background and requirements."),
        ("INTERMEDIATE", "Which of the following is an example of a visual aid in a report?",
         ["A labeled diagram", "A topic sentence", "A footnote", "A table of contents"], "A",
         "Diagrams, graphs, and figures are visual aids that clarify complex information."),
        ("ADVANCED", "What is the main advantage of using the inverted pyramid structure in technical summaries?",
         ["It presents the most important information first", "It hides the conclusion", "It increases word count", "It eliminates all headings"], "A",
         "The inverted pyramid places key findings at the start, helping busy readers quickly."),
        ("ADVANCED", "Which sentence best avoids ambiguity in a technical instruction?",
         ["Press the red button located on the left panel", "Press the button", "Press something", "Activate the mechanism"], "A",
         "Precise instructions specify the exact action, object, and location."),
        ("ADVANCED", "When paraphrasing a source, the writer should:",
         ["Restate the idea in their own words and cite the source", "Copy the sentence exactly", "Change only one word", "Omit the citation"], "A",
         "Paraphrasing requires original wording with proper attribution to avoid plagiarism."),
        ("ADVANCED", "A technical report's 'scope' section clarifies:",
         ["The boundaries and limitations of the study", "The author's personal feelings", "The printing date", "The list of suppliers"], "A",
         "Scope defines what the report covers and, importantly, what it does not cover."),
        ("ADVANCED", "Which statement is a characteristic of strong report conclusions?",
         ["They directly answer the research question", "They introduce new data", "They repeat the introduction verbatim", "They express vague opinions"], "A",
         "Conclusions synthesize findings and answer the stated objectives without new material."),
        ("ADVANCED", "The purpose of an abstract and an executive summary differ because the executive summary:",
         ["Includes recommendations and more context for decision-making", "Is always one sentence", "Never appears in reports", "Replaces the references"], "A",
         "While the abstract summarizes, the executive summary adds recommendations aimed at decision-makers."),
        ("ADVANCED", "Which of the following is a best practice for writing headings in a technical document?",
         ["Use clear, parallel, descriptive headings", "Use very long sentences as headings", "Make every heading a question", "Use different fonts randomly"], "A",
         "Effective headings are concise, parallel, and descriptive so readers can scan quickly."),
        ("ADVANCED", "In a lab report, the 'results' section should:",
         ["Present data objectively without interpretation", "Explain why the results occurred", "List all equipment", "Include the hypothesis"], "A",
         "Results report what was observed; interpretation belongs in the discussion."),
        ("ADVANCED", "Which approach reduces plagiarism risk in a technical document?",
         ["Paraphrasing, quoting, and citing all borrowed ideas", "Only changing font style", "Using only the abstract", "Removing page numbers"], "A",
         "Proper citation of every borrowed idea, whether quoted or paraphrased, avoids plagiarism."),
        ("ADVANCED", "What is the role of a 'definition' in a technical document?",
         ["To clarify technical terms for the reader", "To decorate the page", "To lengthen the introduction", "To replace the conclusion"], "A",
         "Definitions explain unfamiliar terminology so the document is understandable."),
    ],
    213: [
        ("BEGINNER", "What is the main goal of active listening?",
         ["To fully understand the speaker's message", "To prepare the next reply", "To interrupt politely", "To judge the speaker"], "A",
         "Active listening focuses on understanding the message rather than merely waiting to speak."),
        ("BEGINNER", "Which of the following is a barrier to effective listening?",
         ["Distractions and noise", "Note-taking", "Maintaining eye contact", "Asking questions"], "A",
         "Noise and distractions prevent the listener from receiving the message clearly."),
        ("BEGINNER", "Non-verbal communication primarily includes:",
         ["Body language and facial expressions", "Grammar rules", "Punctuation marks", "Spelling"], "A",
         "Non-verbal cues such as posture, gestures, and expressions convey meaning without words."),
        ("BEGINNER", "What is the purpose of paraphrasing what a speaker said?",
         ["To confirm understanding", "To change the topic", "To end the conversation", "To speak louder"], "A",
         "Paraphrasing restates the message to check that the listener understood correctly."),
        ("BEGINNER", "In spoken English, what does intonation refer to?",
         ["The rise and fall of the voice", "The volume of writing", "The speed of typing", "The choice of vocabulary"], "A",
         "Intonation is the variation in pitch that conveys meaning and emotion."),
        ("BEGINNER", "Which of these is a good practice when speaking clearly?",
         ["Speaking at a moderate, steady pace", "Mumbling quickly", "Shouting continuously", "Speaking with food in the mouth"], "A",
         "Clear speech uses a moderate pace and proper articulation."),
        ("BEGINNER", "What does 'paralanguage' include?",
         ["Tone, pitch, and volume of speech", "Written grammar", "Spelling rules", "Punctuation"], "A",
         "Paralanguage refers to vocal features such as tone, pitch, and volume."),
        ("BEGINNER", "Which of the following is an example of a closed question?",
         ["Did you finish the task?", "What did you think about the task?", "How did you complete it?", "Why did you choose this method?"], "A",
         "A closed question expects a short, often yes-or-no answer."),
        ("BEGINNER", "What is the role of feedback in communication?",
         ["To show that the message was received and understood", "To end the conversation", "To increase noise", "To avoid eye contact"], "A",
         "Feedback confirms reception and understanding of the message."),
        ("BEGINNER", "Which of the following is a listening skill?",
         ["Paying attention to the speaker", "Interrupting often", "Checking the phone", "Changing the subject"], "A",
         "Attention and focus are core to effective listening."),
        ("INTERMEDIATE", "A teacher pauses after a key point in a lecture. The pause is best used by a listener to:",
         ["Consolidate and note the key idea", "Begin a side conversation", "Leave the room", "Stop taking notes"], "A",
         "Pauses give listeners time to process and record important information."),
        ("INTERMEDIATE", "Which listening barrier involves evaluating the speaker's appearance rather than the content?",
         ["Prejudice and bias", "Background noise", "Fast speech", "Poor lighting"], "A",
         "Prejudice leads listeners to judge the speaker instead of the message."),
        ("INTERMEDIATE", "The phrase 'Please speak a little more slowly' is an example of:",
         ["Requesting clarification", "Giving an order", "Making a joke", "Ending the conversation"], "A",
         "Such requests seek adjustment of delivery to improve comprehension."),
        ("INTERMEDIATE", "When answering a question, a strong spoken answer should be:",
         ["Relevant, structured, and concise", "Very long and repetitive", "Unrelated to the question", "Whispered"], "A",
         "Effective spoken answers directly address the question with clear structure."),
        ("INTERMEDIATE", "What is the main difference between hearing and listening?",
         ["Listening requires attention and interpretation", "Hearing requires attention", "They are identical", "Listening needs no brain"], "A",
         "Hearing is passive reception of sound; listening is an active mental process."),
        ("INTERMEDIATE", "Which of the following best describes 'empathetic listening'?",
         ["Understanding the speaker's feelings and perspective", "Interrupting with advice", "Listening only for facts", "Ending the talk early"], "A",
         "Empathetic listening seeks to understand the speaker's emotions and viewpoint."),
        ("INTERMEDIATE", "Using 'I-messages' in a conversation helps to:",
         ["Express feelings without blaming others", "Accuse the listener", "Hide emotions", "Increase conflict"], "A",
         "I-messages such as 'I feel frustrated' state feelings without blame."),
        ("INTERMEDIATE", "What is the recommended reaction when a speaker is too fast for you?",
         ["Politely ask them to slow down", "Shout to interrupt", "Stop listening", "Walk away"], "A",
         "Polite requests to slow down improve comprehension without breaking rapport."),
        ("INTERMEDIATE", "Which of these is a verbal communication element?",
         ["Choice of words", "Posture", "Eye contact", "Gesture"], "A",
         "Words are the verbal component; the others are non-verbal cues."),
        ("INTERMEDIATE", "A nod of the head while listening typically signals:",
         ["Agreement or encouragement to continue", "That the listener is bored", "That the speaker is wrong", "That the topic must change"], "A",
         "Nodding is a non-verbal cue indicating engagement and approval."),
        ("ADVANCED", "In a negotiation, active listening is most valuable because it:",
         ["Reveals the other party's priorities and builds trust", "Increases speaking time", "Hides information", "Reduces the need for questions"], "A",
         "Listening uncovers underlying interests, enabling mutually acceptable outcomes."),
        ("ADVANCED", "A speaker notices the audience glancing at watches. The most likely conclusion is that the speech is:",
         ["Too long or losing engagement", "Very engaging", "Too short", "Perfectly timed"], "A",
         "Audience restlessness signals the talk should be shortened or made more engaging."),
        ("ADVANCED", "Which technique can help overcome stage fright before speaking?",
         ["Practice and deep breathing", "Avoiding preparation", "Memorizing without meaning", "Speaking immediately"], "A",
         "Rehearsal and relaxation techniques reduce anxiety and improve delivery."),
        ("ADVANCED", "When someone asks a complex question, a strong listener should:",
         ["Clarify the question before answering", "Answer immediately with guesses", "Ignore the question", "Change the subject"], "A",
         "Clarifying ensures the answer actually addresses what was asked."),
        ("ADVANCED", "What is the value of summarizing a long discussion at its end?",
         ["It confirms agreements and next steps", "It wastes time", "It confuses participants", "It ends the meeting early"], "A",
         "Summaries lock in understanding, decisions, and action items."),
        ("ADVANCED", "In multicultural communication, which listening behavior helps avoid misunderstanding?",
         ["Checking for cultural differences in non-verbal cues", "Assuming universal meanings", "Ignoring body language", "Speaking louder"], "A",
         "Cultural awareness prevents misinterpretation of gestures and tone."),
        ("ADVANCED", "During a debate, listening carefully to the opponent before rebutting:",
         ["Strengthens the rebuttal with accurate points", "Weakens the argument", "Is unnecessary", "Prevents speaking"], "A",
         "Accurate listening lets the speaker address real claims rather than assumptions."),
        ("ADVANCED", "Which question type is best for drawing out detailed opinions?",
         ["Open-ended questions", "Yes/no questions", "Rhetorical questions", "Tag questions"], "A",
         "Open questions like 'How do you see this?' invite extended responses."),
        ("ADVANCED", "A listener who constantly interrupts is likely to:",
         ["Damage the speaker's trust and clarity", "Improve the flow", "Increase understanding", "Speed up decisions"], "A",
         "Interruptions frustrate speakers and cause information to be missed."),
        ("ADVANCED", "What is the best first step when you miss part of a speaker's message?",
         ["Politely ask them to repeat the missed part", "Guess the meaning", "Blame the speaker", "End the conversation"], "A",
         "Requesting repetition prevents costly misunderstandings."),
    ],
    214: [
        ("BEGINNER", "What is the first step in preparing a presentation?",
         ["Analyze the audience and purpose", "Design all slides", "Memorize the ending", "Print handouts"], "A",
         "Understanding the audience and objective shapes all subsequent preparation."),
        ("BEGINNER", "A good presentation should begin with:",
         ["An introduction that states the topic and purpose", "A long apology", "The final conclusion", "A complicated slide"], "A",
         "A clear introduction orients the audience to the topic and purpose."),
        ("BEGINNER", "What is the ideal number of main points for a short presentation?",
         ["Two to four", "Fifteen", "Twenty", "As many as possible"], "A",
         "A few clear points are easier for audiences to follow and remember."),
        ("BEGINNER", "Eye contact during a presentation helps to:",
         ["Connect with the audience", "Read notes secretly", "Avoid questions", "Speed up delivery"], "A",
         "Eye contact engages listeners and builds credibility."),
        ("BEGINNER", "In a group discussion, the first rule is to:",
         ["Listen to others before speaking", "Interrupt immediately", "Speak over everyone", "Change the topic"], "A",
         "Respecting others' turns is fundamental to productive group discussion."),
        ("BEGINNER", "What should a speaker do with their hands during a presentation?",
         ["Use natural gestures", "Keep them hidden", "Fidget continuously", "Point at everyone"], "A",
         "Natural, purposeful gestures reinforce the spoken message."),
        ("BEGINNER", "Which of the following is a purpose of a group discussion?",
         ["To explore a topic collaboratively", "To prove one person right", "To speak for the longest time", "To avoid listening"], "A",
         "Group discussions aim to share ideas and reach better conclusions together."),
        ("BEGINNER", "What is the purpose of a conclusion in a presentation?",
         ["To summarize key points and give a takeaway", "To introduce new topics", "To confuse the audience", "To extend the talk"], "A",
         "Conclusions reinforce the main message and leave a lasting impression."),
        ("BEGINNER", "Handouts in a presentation are used to:",
         ["Provide additional reference material", "Replace the speaker", "Confuse listeners", "Reduce preparation"], "A",
         "Handouts give the audience takeaway material they can study later."),
        ("BEGINNER", "What is the main advantage of using visual aids?",
         ["They make content easier to understand", "They hide the speaker", "They reduce preparation time", "They replace all words"], "A",
         "Visuals clarify complex information and keep the audience engaged."),
        ("INTERMEDIATE", "A slide with too much text is ineffective mainly because:",
         ["The audience reads instead of listening to the speaker", "It is too colorful", "It is too short", "It has no images"], "A",
         "Dense slides split attention away from the speaker's delivery."),
        ("INTERMEDIATE", "Which presentation opening technique grabs attention effectively?",
         ["Starting with a relevant question or surprising fact", "Apologizing for being unprepared", "Reading the agenda word by word", "Showing a blank slide"], "A",
         "A hook such as a question or statistic immediately engages the audience."),
        ("INTERMEDIATE", "During a group discussion, the role of a moderator is to:",
         ["Keep the discussion on topic and give fair turns", "Dominate the conversation", "Interrupt speakers", "Decide the answer alone"], "A",
         "A moderator facilitates balanced, focused participation."),
        ("INTERMEDIATE", "If you forget a point during a presentation, the best action is to:",
         ["Pause briefly, consult notes, and continue naturally", "Panic and stop", "End the presentation", "Apologize repeatedly"], "A",
         "A short pause to regain composure keeps the presentation professional."),
        ("INTERMEDIATE", "The 10-20-30 rule for presentations suggests:",
         ["10 slides, 20 minutes, 30-point minimum font", "30 slides, 10 minutes, 20-point font", "20 slides, 30 minutes, 10 slides", "10 minutes, 20 slides, 30 words"], "A",
         "This rule from Guy Kawasaki promotes simple, short, readable presentations."),
        ("INTERMEDIATE", "Which of the following best supports a claim in a group discussion?",
         ["Providing evidence and examples", "Raising your voice", "Repeating the claim", "Ignoring counterpoints"], "A",
         "Evidence and examples make contributions persuasive and credible."),
        ("INTERMEDIATE", "Answering a question you do not know during a presentation should be handled by:",
         ["Admitting you do not know and offering to follow up", "Making up an answer", "Ignoring the question", "Ending the Q&A"], "A",
         "Honesty builds credibility; a promise to follow up is professional."),
        ("INTERMEDIATE", "In a group discussion, 'active participation' means:",
         ["Contributing relevant ideas while listening to others", "Speaking continuously", "Only agreeing with everyone", "Remaining silent"], "A",
         "Balanced contributions that build on others' points define active participation."),
        ("INTERMEDIATE", "Transition phrases such as 'moving on to' help a presentation by:",
         ["Signaling topic changes clearly", "Adding unnecessary words", "Confusing the audience", "Increasing slide count"], "A",
         "Transitions guide listeners smoothly from one section to the next."),
        ("INTERMEDIATE", "Which of these is a good practice when delivering a presentation online?",
         ["Checking audio and visuals before starting", "Muting while speaking", "Showing unrelated content", "Ignoring the chat"], "A",
         "Technical checks and engaging with chat ensure a smooth virtual talk."),
        ("ADVANCED", "The 'tell them, tell them, tell them' presentation structure refers to:",
         ["Opening, developing, and concluding with the main message", "Repeating a single sentence", "Telling stories three times", "Speaking to three people"], "A",
         "This structure states the message in the intro, body, and conclusion for retention."),
        ("ADVANCED", "In a panel discussion, the best contribution is one that:",
         ["Adds a new perspective and responds to prior speakers", "Repeats earlier points", "Is completely unrelated", "Only criticizes"], "A",
         "Valuable panel input builds on previous remarks with fresh insight."),
        ("ADVANCED", "What is the key purpose of a Q&A session after a presentation?",
         ["To clarify doubts and deepen understanding", "To end the presentation", "To test the audience", "To display all slides again"], "A",
         "Q&A lets the audience resolve uncertainties about the presented content."),
        ("ADVANCED", "Which technique can a speaker use to pace a long presentation effectively?",
         ["Scheduling brief pauses between major sections", "Speaking continuously without breaks", "Rushing through slides", "Reading verbatim"], "A",
         "Pauses give the audience time to digest and the speaker time to refocus."),
        ("ADVANCED", "The main risk of memorizing an entire speech word-for-word is that the speaker:",
         ["Loses flexibility and may freeze on forgetting a phrase", "Sounds more natural", "Engages better", "Answers questions better"], "A",
         "Rote memorization makes delivery rigid and fragile under pressure."),
        ("ADVANCED", "In a group discussion evaluation, clarity of a candidate's points is judged by:",
         ["How logically and concisely the ideas are expressed", "How loudly they speak", "How often they speak", "How long they speak"], "A",
         "Logical, concise expression of ideas is the mark of clear communication."),
        ("ADVANCED", "When your idea is contradicted in a group discussion, the professional response is to:",
         ["Listen, evaluate the counterpoint, and respond with evidence", "Raise your voice", "Walk away", "Insult the speaker"], "A",
         "Engaging the counterargument calmly with evidence demonstrates maturity."),
        ("ADVANCED", "Which design principle keeps presentation slides effective?",
         ["Minimal text with strong visuals", "Maximum text in small fonts", "Many animations", "Random layouts"], "A",
         "Slides should support the speaker with simple visuals, not replicate the speech."),
        ("ADVANCED", "A strong presenter handles a hostile question by:",
         ["Staying calm and answering objectively", "Becoming defensive", "Avoiding eye contact", "Ending the session"], "A",
         "Professional composure and objective responses defuse hostility."),
        ("ADVANCED", "The primary difference between informing and persuading in a presentation is that persuasion:",
         ["Aims to change the audience's attitude or action", "Only shares facts", "Avoids evidence", "Never uses stories"], "A",
         "Persuasive talks seek to influence beliefs or behaviors, not just inform."),
    ],
    215: [
        ("BEGINNER", "What is the purpose of a professional e-mail subject line?",
         ["To summarize the e-mail's content clearly", "To be vague and mysterious", "To include personal greetings", "To hide the topic"], "A",
         "A clear subject line helps the recipient understand and prioritize the message."),
        ("BEGINNER", "Which salutation is appropriate in a formal business letter?",
         ["Dear Mr. Sharma", "Hey buddy", "Yo", "Hi pal"], "A",
         "Formal communication uses respectful salutations such as 'Dear Mr. Sharma'."),
        ("BEGINNER", "What is the primary purpose of an interview?",
         ["To assess the candidate's suitability for a role", "To test their typing speed", "To socialize", "To sell a product"], "A",
         "Interviews evaluate whether the candidate matches the job's requirements."),
        ("BEGINNER", "Which of the following is appropriate in a workplace e-mail?",
         ["A professional closing such as 'Best regards'", "Emoticons everywhere", "ALL CAPS text", "Informal slang"], "A",
         "Professional closures and tone maintain workplace etiquette."),
        ("BEGINNER", "What is a 'meeting agenda'?",
         ["A list of topics to be discussed", "A list of attendees only", "The meeting location", "The meeting minutes"], "A",
         "An agenda outlines the topics and order of a meeting."),
        ("BEGINNER", "What should a professional thank-you e-mail include?",
         ["Specific appreciation and a brief context", "Only a smiley", "Personal gossip", "Complaints"], "A",
         "A specific, gracious message strengthens professional relationships."),
        ("BEGINNER", "In business communication, 'netiquette' refers to:",
         ["Rules of polite online communication", "A networking device", "A type of letter", "Meeting etiquette only"], "A",
         "Netiquette is the set of accepted rules for respectful online interaction."),
        ("BEGINNER", "Which of the following is a professional phone call practice?",
         ["Introducing yourself at the start", "Eating while talking", "Speaking at maximum volume", "Not stating your purpose"], "A",
         "Introductions and clear purpose keep business calls professional."),
        ("BEGINNER", "What is the purpose of meeting minutes?",
         ["To record what was discussed and decided", "To set the agenda", "To list invitees", "To schedule the next meeting only"], "A",
         "Minutes document decisions and action items from a meeting."),
        ("BEGINNER", "Which phrase is appropriate to request a deadline extension professionally?",
         ["Please consider extending the deadline due to unforeseen delays", "I can't make it, too bad", "This is impossible", "Not my problem"], "A",
         "Politely explaining the reason requests an extension respectfully."),
        ("INTERMEDIATE", "A professional e-mail to a supervisor should be written in which tone?",
         ["Respectful and concise", "Very casual", "Demanding", "Emotional"], "A",
         "Respectful, concise writing reflects professionalism and clarity."),
        ("INTERMEDIATE", "What is the STAR method used for in interviews?",
         ["Situation, Task, Action, Result", "Start, Test, Apply, Review", "Study, Train, Act, Reflect", "Story, Talk, Answer, Report"], "A",
         "STAR structures behavioral answers around situation, task, action, and result."),
        ("INTERMEDIATE", "When declining an invitation politely, it is best to:",
         ["Thank the sender and give a brief reason", "Ignore the invitation", "Say yes and not attend", "Reply with a joke"], "A",
         "A gracious decline maintains goodwill and clear communication."),
        ("INTERMEDIATE", "In written business communication, using bullet points is effective for:",
         ["Improving readability of key points", "Hiding information", "Increasing formality only", "Replacing all paragraphs"], "A",
         "Bullets break complex information into scannable, clear items."),
        ("INTERMEDIATE", "What is the appropriate way to correct a colleague's error in e-mail?",
         ["Privately and constructively", "Publicly and harshly", "In a group chat loudly", "Never mention it"], "A",
         "Private, constructive feedback protects dignity and improves teamwork."),
        ("INTERMEDIATE", "During an interview, the candidate should prepare to:",
         ["Explain their skills with examples", "Talk only about salary", "Criticize previous employers", "Avoid questions"], "A",
         "Prepared examples demonstrate capability and fit."),
        ("INTERMEDIATE", "A 'reply all' e-mail is appropriate when:",
         ["All recipients genuinely need the response", "Only the sender needs it", "You want to spam", "You are unsure who should read it"], "A",
         "Reply all should be used only when every recipient needs the information."),
        ("INTERMEDIATE", "Which statement demonstrates professional e-mail etiquette for attachments?",
         ["Referencing the attachment in the body", "Sending files without any message", "Attaching very large files without warning", "Naming files randomly"], "A",
         "Mentioning the attachment helps recipients locate and open it."),
        ("INTERMEDIATE", "What is the purpose of a professional resume?",
         ["To summarize qualifications for a role", "To list personal hobbies only", "To describe the company", "To request a meeting"], "A",
         "A resume presents relevant education, skills, and experience to recruiters."),
        ("INTERMEDIATE", "In a meeting, the person who takes action items should:",
         ["Record them and report progress", "Forget them", "Argue about them", "Postpone indefinitely"], "A",
         "Action items with owners and deadlines drive follow-through."),
        ("ADVANCED", "When writing a resignation letter, it is best to:",
         ["Give notice, be gracious, and offer a smooth transition", "Criticize the company", "Leave immediately", "Avoid mentioning the date"], "A",
         "A professional resignation preserves relationships and ensures a smooth handover."),
        ("ADVANCED", "In a performance review conversation, the employee should:",
         ["Discuss achievements, challenges, and growth goals", "Blame colleagues", "Refuse feedback", "Remain silent"], "A",
         "Open dialogue about performance supports development and trust."),
        ("ADVANCED", "Which approach is most effective when negotiating a salary?",
         ["Presenting market data and your value", "Demanding a fixed figure", "Avoiding the topic", "Threatening to leave"], "A",
         "Data-backed, value-based negotiation is professional and effective."),
        ("ADVANCED", "The main advantage of 'inclusive language' in professional settings is that it:",
         ["Respects all individuals and avoids bias", "Is shorter", "Saves time", "Impresses managers only"], "A",
         "Inclusive language fosters respect and reduces discrimination."),
        ("ADVANCED", "A manager should deliver critical feedback in a way that is:",
         ["Specific, timely, and focused on behavior", "Vague and delayed", "Public and personal", "Written in anger"], "A",
         "Constructive feedback addresses observable behavior to improve performance."),
        ("ADVANCED", "What is the purpose of a 'thank you' note sent after an interview?",
         ["To reinforce interest and professionalism", "To ask about the salary again", "To request extra days off", "To complain about the process"], "A",
         "A prompt thank-you note reiterates interest and leaves a positive impression."),
        ("ADVANCED", "When writing a formal complaint e-mail, the tone should be:",
         ["Objective, factual, and respectful", "Angry and accusatory", "Threatening", "Sarcastic"], "A",
         "Factual, respectful complaints are taken more seriously."),
        ("ADVANCED", "The best way to handle an ambiguous instruction from a manager is to:",
         ["Ask clarifying questions", "Guess and proceed", "Ignore it", "Do the opposite"], "A",
         "Clarification prevents wasted effort and misunderstandings."),
        ("ADVANCED", "A professional 'out of office' message should include:",
         ["Return date and alternative contact", "Personal vacation photos", "Complaints", "Jokes"], "A",
         "Clear out-of-office messages manage expectations for colleagues and clients."),
        ("ADVANCED", "In cross-cultural business communication, the safest initial approach is to:",
         ["Use clear, formal, respectful language", "Use heavy slang", "Assume everyone shares your customs", "Avoid all formality"], "A",
         "Clear, respectful language minimizes cultural misinterpretation."),
    ],
}
