# -*- coding: utf-8 -*-
"""
Question bank for Subject 06 - DBMS101 - DBMS Fundamentals.
Category: Database Management
Topics: 26 ER Model, 27 Relational Model & Keys, 28 Normalization,
29 Transactions & Concurrency, 30 Indexing & Query Optimization.
Each topic: 10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED (30 per topic, 150 total).
"""

QUESTIONS = {
    26: [
        ("BEGINNER", "In an ER diagram, what does a rectangle represent?",
         ["An entity set", "An attribute", "A relationship set", "A key constraint"], "A",
         "A rectangle in the Chen ER notation represents an entity set, a collection of similar entities."),
        ("BEGINNER", "What symbol is used to represent an attribute in a standard Chen ER diagram?",
         ["An ellipse", "A rectangle", "A diamond", "A triangle"], "A",
         "Attributes are drawn as ellipses that connect to their entity via lines in Chen notation."),
        ("BEGINNER", "Which symbol in an ER diagram represents a relationship between entity sets?",
         ["A diamond", "A circle", "A square", "A hexagon"], "A",
         "A diamond shape is used to denote a relationship set connecting two or more entity sets."),
        ("BEGINNER", "An entity in an ER model is best described as:",
         ["A distinguishable object or thing about which data is stored",
          "A row inside a database table",
          "A constraint between two tables",
          "A query that returns data"], "A",
         "An entity is a distinct real-world object or concept that the database stores information about."),
        ("BEGINNER", "Which of the following is a valid example of an entity set in a library database?",
         ["Books", "Borrow dates", "Author names as text", "ISBN validation rules"], "A",
         "Books is an entity set, while borrow dates and author names are attributes and validation rules are constraints."),
        ("BEGINNER", "An attribute that can be divided into smaller meaningful parts is called:",
         ["A composite attribute", "A derived attribute", "A key attribute", "A multivalued attribute"], "A",
         "A composite attribute such as full address can be split into street, city and zip sub-parts."),
        ("BEGINNER", "What type of attribute can take on more than one value for a single entity?",
         ["A multivalued attribute", "A derived attribute", "A composite attribute", "A single-valued attribute"], "A",
         "A multivalued attribute such as phone_numbers holds a collection of values for one entity."),
        ("BEGINNER", "In an ER diagram, a double-bordered rectangle represents:",
         ["A weak entity set", "A strong entity set", "A derived entity set", "A composite entity set"], "A",
         "Weak entity sets are drawn with double borders because they cannot be identified without their owner."),
        ("BEGINNER", "The cardinality ratio for the relationship 'a student enrolls in many courses and a course has many students' is:",
         ["Many-to-many", "One-to-many", "One-to-one", "Many-to-one"], "A",
         "Multiple students can enroll in multiple courses, giving a many-to-many relationship."),
        ("BEGINNER", "Which of the following is an example of a derived attribute?",
         ["A person's age", "A person's date of birth", "A person's social security number", "A person's name"], "A",
         "Age is derived from the date of birth, so it is computed rather than stored directly."),
        ("INTERMEDIATE", "An employee works in exactly one department, but a department has many employees. What is the cardinality of this relationship from department to employee?",
         ["One-to-many", "Many-to-many", "One-to-one", "Zero-to-many"], "A",
         "Since one department has many employees but an employee belongs to one department, the ratio is one-to-many."),
        ("INTERMEDIATE", "Which situation requires modeling an entity as a weak entity set?",
         ["A room whose identity depends on the hotel it belongs to",
          "A customer who has a globally unique customer ID",
          "A product with a unique SKU",
          "A country with a primary key"], "A",
         "A weak entity like a hotel room has no sufficient attributes of its own and depends on its identifying owner."),
        ("INTERMEDIATE", "The double diamond symbol in an ER diagram is used to indicate:",
         ["An identifying relationship for a weak entity set",
          "A many-to-many relationship",
          "A derived relationship",
          "A ternary relationship"], "A",
         "A double diamond denotes the identifying relationship that links a weak entity set to its strong owner."),
        ("INTERMEDIATE", "A professor teaches many sections, but each section is taught by exactly one professor. The participation of section in 'teaches' is best described as:",
         ["Total participation", "Partial participation", "No participation", "Conditional participation"], "A",
         "Every section must have a professor, so the section side has total participation in the relationship."),
        ("INTERMEDIATE", "An entity set with no sufficient attributes to form a primary key is called:",
         ["A weak entity set", "A composite entity set", "A derived entity set", "An attribute-only set"], "A",
         "A weak entity set lacks enough attributes to form its own primary key and relies on its owner."),
        ("INTERMEDIATE", "In ER design, a multivalued attribute is best handled in a relational schema by:",
         ["Creating a separate relation for the attribute",
          "Storing all values in a single comma-separated column",
          "Making the attribute the primary key",
          "Deleting the attribute entirely"], "A",
         "Multivalued attributes are stored in their own relation whose key combines the entity key with the attribute value."),
        ("INTERMEDIATE", "A relationship that connects three entity sets is known as:",
         ["A ternary relationship", "A binary relationship", "A recursive relationship", "A composite relationship"], "A",
         "A ternary relationship involves three participating entity sets, such as Supplier-Part-Warehouse."),
        ("INTERMEDIATE", "A 'subclass' in an EER model, such as Salaried vs. Hourly employees, is captured using:",
         ["Specialization and generalization",
          "Weak entity sets only",
          "Multivalued attributes only",
          "Ternary relationships only"], "A",
         "Specialization/generalization hierarchies model subclasses that share attributes of a superclass."),
        ("INTERMEDIATE", "Which of these is a good reason to prefer a weak entity set over a multivalued attribute for storing a list?",
         ["When each list item has its own attributes, such as a room with a capacity and floor",
          "When the list must always be short",
          "When the list values are never queried",
          "When the list has only one value"], "A",
         "When each item carries its own descriptive attributes, modeling it as a weak entity set is appropriate."),
        ("INTERMEDIATE", "In mapping an ER diagram to relations, a one-to-many relationship is best represented by:",
         ["Adding the primary key of the 'one' side as a foreign key in the 'many' side",
          "Creating a separate relation with only the two keys",
          "Merging both entities into one relation",
          "Ignoring the relationship"], "A",
         "Placing the primary key of the one side into the many side relation as a foreign key captures one-to-many semantics."),
        ("ADVANCED", "In an ER design for a hospital, each patient has a record number that only makes sense within their doctor's practice. This suggests modeling Patient as:",
         ["A weak entity set identified by the doctor",
          "A strong entity set with an independent key",
          "A derived entity set",
          "An attribute of Doctor"], "A",
         "Because the record number is only meaningful per practice, Patient depends on Doctor and is a weak entity set."),
        ("ADVANCED", "You are mapping a many-to-many relationship with a descriptive attribute called since_date. The correct relational mapping is:",
         ["A separate relation with both entity keys plus since_date",
          "Add since_date to either entity relation",
          "Discard since_date to preserve normal form",
          "Store since_date only in the application layer"], "A",
         "A relationship relation containing both primary keys and the descriptive attribute since_date preserves the association."),
        ("ADVANCED", "A student entity has attributes student_id and email, and email can be used to look up the student. If email is chosen as the primary key, student_id becomes:",
         ["A candidate key that was not chosen",
          "A superkey",
          "A foreign key",
          "A composite attribute"], "A",
         "student_id and email are both candidate keys; the one not selected as primary key remains a candidate key."),
        ("ADVANCED", "An ER schema uses a relationship between 'Course' and 'Prerequisite-Course' where a course references itself. This is an example of:",
         ["A recursive relationship",
          "A weak relationship",
          "A ternary relationship",
          "A derived relationship"], "A",
         "A course being a prerequisite for another course of the same type is a recursive relationship on one entity set."),
        ("ADVANCED", "In ER-to-relational mapping, how should a one-to-one relationship between Entity A and Entity B with total participation on both sides be mapped?",
         ["Merge A and B into a single relation",
          "Keep two relations and ignore the relationship",
          "Always create a third relation for the relationship",
          "Store the relationship in both relations redundantly"], "A",
         "With total participation on both sides, merging into one relation is valid and avoids extra joins."),
        ("ADVANCED", "A superclass 'Vehicle' has subclasses 'Car' and 'Truck', and a vehicle can belong to both subclasses. This is best modeled using:",
         ["Overlapping specialization",
          "Disjoint specialization",
          "A weak entity set",
          "A multivalued attribute"], "A",
         "Overlapping specialization permits an entity to be a member of more than one subclass simultaneously."),
        ("ADVANCED", "When a weak entity set's owner is deleted, the weak entity should also be deleted. This requirement maps to which constraint on the relationship?",
         ["The identifying relationship must enforce on-delete cascade",
          "The relationship must be many-to-many",
          "The weak entity must have a global key",
          "No constraint is needed"], "A",
         "Cascading deletion through the identifying relationship preserves the dependency of the weak entity on its owner."),
        ("ADVANCED", "You have an ER model with a multivalued attribute 'skill_level' per employee. Which design fully normalizes this into relational tables?",
         ["A Skill table with (employee_id, skill_level) as a composite key",
          "A single Employee table storing skill_level in one column",
          "A skill_level column repeated for each employee row",
          "Storing skill_level in an XML column"], "A",
         "A separate Skill relation keyed by both employee_id and skill_level removes the multivalued attribute cleanly."),
        ("ADVANCED", "In an EER design, every Cashier is an Employee and every Employee is either Cashier or Manager, but never both. This is:",
         ["A disjoint, total specialization",
          "An overlapping, partial specialization",
          "A weak entity hierarchy",
          "A ternary relationship"], "A",
         "Each employee must be in exactly one subclass, which describes disjoint and total specialization."),
        ("ADVANCED", "Which normal form violation is prevented when a relationship with a multivalued attribute is split into a separate relation during ER mapping?",
         ["Violation of the atomicity (1NF) rule for attribute values",
          "Violation of the key uniqueness rule",
          "Violation of the referential rule",
          "Violation of the domain rule"], "A",
         "Storing multiple values in one column violates 1NF atomicity, which the separate relation avoids."),
    ],
    27: [
        ("BEGINNER", "In the relational model, a table is formally called a:",
         ["Relation", "File", "Record", "Graph"], "A",
         "The relational model calls a table a relation, made up of tuples and attributes."),
        ("BEGINNER", "A row of a relation is formally referred to as a:",
         ["Tuple", "Field", "Attribute", "Domain"], "A",
         "Each row is a tuple, an ordered collection of attribute values."),
        ("BEGINNER", "A column in a relational table represents a(n):",
         ["Attribute", "Tuple", "Relation", "Index"], "A",
         "A column corresponds to an attribute that describes one property of the entities in the relation."),
        ("BEGINNER", "Which key uniquely identifies each tuple in a relation?",
         ["Primary key", "Foreign key", "Candidate key is the only unique key", "Superkey is never unique"], "A",
         "The primary key is a chosen key whose value uniquely identifies each tuple in a relation."),
        ("BEGINNER", "A foreign key in table R references the primary key of table S to enforce:",
         ["Referential integrity", "Entity integrity", "Domain integrity", "Normalization"], "A",
         "Referential integrity ensures every foreign key value matches an existing primary key value in the referenced table."),
        ("BEGINNER", "Which constraint ensures that the primary key value is never NULL?",
         ["Entity integrity", "Referential integrity", "Domain integrity", "Check integrity"], "A",
         "Entity integrity requires that no part of a primary key can be NULL."),
        ("BEGINNER", "The set of all possible values that an attribute may take is called its:",
         ["Domain", "Tuple", "Relation", "Schema"], "A",
         "A domain is the pool of permissible values for an attribute, such as integers between 1 and 100."),
        ("BEGINNER", "The degree of a relation refers to:",
         ["The number of attributes", "The number of tuples", "The number of tables", "The number of foreign keys"], "A",
         "The degree of a relation is the count of its attributes (columns)."),
        ("BEGINNER", "The cardinality of a relation refers to:",
         ["The number of tuples", "The number of attributes", "The number of candidate keys", "The number of relations"], "A",
         "Cardinality counts the tuples (rows) currently present in a relation."),
        ("BEGINNER", "Which statement about a superkey is correct?",
         ["A superkey is any set of attributes that uniquely identifies a tuple",
          "A superkey must have exactly one attribute",
          "A superkey cannot contain a primary key",
          "A superkey is always minimal"], "A",
         "A superkey is any attribute set whose values uniquely distinguish tuples; it may contain extra attributes."),
        ("INTERMEDIATE", "A relation EMP(emp_id, dept_id) has emp_id as primary key and dept_id referencing DEPT. If a dept row is deleted while employees still reference it, inserting would be impossible. Which constraint was violated?",
         ["Referential integrity", "Entity integrity", "Domain integrity", "Tuple uniqueness"], "A",
         "Deleting the referenced department leaves dangling dept_id values, which violates referential integrity."),
        ("INTERMEDIATE", "Which of the following sets could be a valid superkey for a relation whose primary key is A, B?",
         ["A, B, C", "C", "B only is never a superkey here", "A and C"], "A",
         "A superkey must contain the primary key; A, B, C contains A and B and is therefore a superkey."),
        ("INTERMEDIATE", "A relation has candidate keys K1 and K2. Which statement is true?",
         ["Both K1 and K2 are superkeys",
          "Neither K1 nor K2 is a superkey",
          "Only the chosen primary key is a superkey",
          "K1 and K2 cannot coexist"], "A",
         "Every candidate key is a minimal superkey, so both K1 and K2 are superkeys."),
        ("INTERMEDIATE", "Which action may legally be performed on the relation that holds the referenced primary key when foreign key references exist?",
         ["Updating the referenced key with ON UPDATE CASCADE",
          "Deleting the referenced row while child rows remain",
          "Making the referenced key NULL",
          "Duplicating the referenced key value"], "A",
         "ON UPDATE CASCADE propagates key changes to dependent rows, preserving referential integrity."),
        ("INTERMEDIATE", "A primary key was chosen from among several candidate keys. The other candidate keys are known as:",
         ["Alternate keys", "Foreign keys", "Surrogate keys", "Composite keys"], "A",
         "Candidate keys not selected as the primary key are alternate keys."),
        ("INTERMEDIATE", "A relation STUDENT(student_id, course_id, grade) with (student_id, course_id) as the primary key has a primary key that is:",
         ["Composite", "Simple", "Surrogate", "Foreign"], "A",
         "A composite key uses two or more attributes; here student_id and course_id together form it."),
        ("INTERMEDIATE", "What does ON DELETE CASCADE on a foreign key accomplish?",
         ["Deleting a parent row automatically deletes referencing child rows",
          "Preventing deletion of any parent row",
          "Setting child keys to NULL on parent deletion",
          "Backing up the parent row before deletion"], "A",
         "CASCADE propagates the parent deletion to child rows that reference the deleted key."),
        ("INTERMEDIATE", "Referential integrity is violated when:",
         ["A foreign key value has no matching primary key value in the referenced table",
          "A foreign key value appears twice",
          "A primary key value is updated",
          "A relation has more than one foreign key"], "A",
         "A dangling foreign key with no matching referenced key breaks referential integrity."),
        ("INTERMEDIATE", "Which of these is a legal NOT NULL enforcement under entity integrity?",
         ["A primary key attribute must never contain NULL",
          "A foreign key may contain NULL",
          "A primary key may be NULL if unique",
          "Only one column of a primary key may be NULL"], "A",
         "Entity integrity forbids NULL in any attribute that is part of the primary key."),
        ("INTERMEDIATE", "The term 'relation schema' describes:",
         ["The structure of a relation including its attribute names and domains",
          "The current rows stored in the relation",
          "The physical disk layout of the table",
          "The query plan used to scan the table"], "A",
         "A relation schema names the relation, its attributes and their domains; it is the intension, not the extension."),
        ("ADVANCED", "Relation R has attributes A, B, C where AB is the primary key. Which functional dependency must hold?",
         ["A and B together determine C, but neither alone determines C necessarily",
          "A alone determines C",
          "B alone determines C",
          "C determines A"], "A",
         "With AB as the key, every other attribute is functionally determined by the pair AB."),
        ("ADVANCED", "You design a table with a composite primary key (order_id, item_no). A supplier key that depends only on item_no would cause:",
         ["A partial dependency, violating 2NF",
          "A transitive dependency, violating 3NF",
          "A multivalued dependency",
          "No normalization problem"], "A",
         "A non-key attribute depending on part of the composite key is a partial dependency, the 2NF violation."),
        ("ADVANCED", "To convert a recursive many-to-many relationship into tables, you must:",
         ["Create a relationship table with two foreign keys pointing to the same relation",
          "Create two identical copies of the relation",
          "Drop the relationship entirely",
          "Use a single self-referencing column"], "A",
         "A junction table holding two foreign keys both referencing the same table models the recursive association."),
        ("ADVANCED", "In a table Orders(customer_id, region), the foreign key customer_id references Customers. Adding a new order for a non-existent customer should be prevented by:",
         ["Referential integrity enforcement",
          "Entity integrity enforcement",
          "Domain enforcement",
          "Functional dependency enforcement"], "A",
         "Referential integrity rejects the insert because the customer_id has no matching Customers row."),
        ("ADVANCED", "Surrogate keys are often preferred over natural keys because:",
         ["They avoid key changes when natural business values are edited",
          "They always improve query speed",
          "They store less data than every natural key",
          "They remove the need for foreign keys"], "A",
         "Surrogate keys are stable and independent of changing business data, so references are not broken on edits."),
        ("ADVANCED", "A weak entity needs its owner's primary key to be fully identified. This principle appears in relational modeling as:",
         ["Propagating the owner's key into the weak entity's primary key as a foreign key",
          "Using a global surrogate key only",
          "Making the weak entity a view",
          "Storing the owner as an attribute of a different table"], "A",
         "The weak entity's key includes the owner's key, making the foreign key part of its primary key."),
        ("ADVANCED", "Given R(A, B, C) with FD A -> C and primary key AB, which normalization issue exists?",
         ["Partial dependency A -> C, so R is not in 2NF",
          "Transitive dependency, so R violates 3NF",
          "R is already in BCNF",
          "R violates 1NF"], "A",
         "C depends on A, only part of the key AB, which is a partial dependency violating 2NF."),
        ("ADVANCED", "Which technique preserves referential integrity when the referenced key is renamed?",
         ["ON UPDATE CASCADE propagates the new value to all foreign keys",
          "ON DELETE SET NULL only",
          "Restricting all updates to the referenced table",
          "Dropping all foreign key constraints"], "A",
         "ON UPDATE CASCADE automatically updates referencing rows when the parent key changes."),
        ("ADVANCED", "A relation must store 'employee depends on (spouse or children)' with potentially many values per employee. The cleanest relational design is:",
         ["A separate Dependents relation keyed by employee_id plus a dependant attribute",
          "A repeated column family inside the Employee row",
          "Storing dependants in a single delimited text column",
          "A multivalued attribute kept as-is"], "A",
         "Separating dependants into their own relation keeps values atomic and satisfies first normal form."),
        ("ADVANCED", "Which combination correctly describes key hierarchy in the relational model?",
         ["Every candidate key is a superkey, and the primary key is one candidate key",
          "Every superkey is a candidate key",
          "A primary key can never be a superkey",
          "Candidate keys are always foreign keys"], "A",
         "Candidate keys are minimal superkeys, and the chosen primary key is one of the candidate keys."),
    ],
    28: [
        ("BEGINNER", "Normalization is the process of:",
         ["Organizing data to minimize redundancy and avoid update anomalies",
          "Encrypting all sensitive table columns",
          "Increasing the number of tables in a schema",
          "Denormalizing data for faster reads"], "A",
         "Normalization structures relations to reduce redundancy and eliminate insertion, update and deletion anomalies."),
        ("BEGINNER", "Which normal form requires that every attribute value be atomic?",
         ["First normal form", "Second normal form", "Third normal form", "Boyce-Codd normal form"], "A",
         "1NF demands that each attribute holds a single atomic value with no repeating groups."),
        ("BEGINNER", "A functional dependency A -> B means:",
         ["Each value of A determines exactly one value of B",
          "B determines A",
          "A and B must be equal",
          "A must be unique in the relation"], "A",
         "A -> B states that any two tuples with the same A value must have the same B value."),
        ("BEGINNER", "Which of these is NOT a typical problem avoided by normalization?",
         ["Slower disk reads", "Insertion anomalies", "Update anomalies", "Deletion anomalies"], "A",
         "Normalization removes redundancy-driven anomalies; it does not directly speed up disk I/O."),
        ("BEGINNER", "A table violates 1NF if it contains:",
         ["A column storing multiple values such as 'red, blue'",
          "A primary key",
          "Two foreign keys",
          "An integer column"], "A",
         "Storing multiple values in a single column creates a repeating group that violates 1NF atomicity."),
        ("BEGINNER", "Second normal form (2NF) requires:",
         ["1NF plus no partial dependency of non-key attributes on a composite key",
          "No transitive dependencies",
          "Every determinant to be a candidate key",
          "All attributes to be foreign keys"], "A",
         "2NF removes partial dependencies where a non-key attribute depends on only part of a composite key."),
        ("BEGINNER", "Third normal form (3NF) removes:",
         ["Transitive dependencies on non-key attributes",
          "All foreign keys",
          "All composite keys",
          "All functional dependencies"], "A",
         "3NF eliminates transitive dependencies where a non-key attribute depends on another non-key attribute."),
        ("BEGINNER", "Which normal form states that for every functional dependency X -> Y, X must be a superkey?",
         ["Boyce-Codd normal form", "First normal form", "Second normal form", "Denormalized form"], "A",
         "BCNF requires every determinant to be a superkey, a stricter condition than 3NF."),
        ("BEGINNER", "An insertion anomaly is characterized by:",
         ["Being unable to add data because required fields are missing",
          "Deleting too many rows accidentally",
          "Updates taking a long time",
          "Queries returning duplicate rows"], "A",
         "Insertion anomalies occur when needed facts cannot be recorded without first adding unrelated data."),
        ("BEGINNER", "The primary purpose of using functional dependencies in normalization is to:",
         ["Understand which attributes determine others so relations can be decomposed safely",
          "Enforce access control on attributes",
          "Encrypt attribute values",
          "Index every attribute"], "A",
         "Functional dependencies guide decomposition by showing how attributes depend on keys."),
        ("INTERMEDIATE", "Relation R(A, B, C, D) with key AB and FD B -> D. Which normal form does R violate?",
         ["Second normal form", "First normal form", "Third normal form", "BCNF is satisfied"], "A",
         "D depends on B, which is part of the composite key AB, so the partial dependency violates 2NF."),
        ("INTERMEDIATE", "Relation R(A, B, C) with key A and FD B -> C. Which normal form does R violate?",
         ["Third normal form", "Second normal form", "First normal form", "No violation occurs"], "A",
         "C depends on B rather than on the key A, a transitive dependency that violates 3NF."),
        ("INTERMEDIATE", "A relation is in BCNF. Which statement must be true?",
         ["Every determinant is a superkey",
          "The relation has no candidate keys",
          "All attributes are atomic",
          "The relation has at most two columns"], "A",
         "BCNF requires each functional dependency determinant to be a superkey."),
        ("INTERMEDIATE", "To fix the relation R(A, B, C) with key AB and FD B -> C, the correct decomposition is:",
         ["R1(A, B) and R2(B, C)",
          "R1(A, C) and R2(B, C)",
          "R1(A, B, C) unchanged",
          "R1(A, B) only"], "A",
         "R1 holds the key AB and R2 captures the dependency B -> C, removing the partial dependency."),
        ("INTERMEDIATE", "Which of these schemas is in 2NF but NOT in 3NF?",
         ["R(A, B, C) with key A and FD B -> C",
          "R(A, B) with key AB",
          "R(A, B, C) with key A and FDs A -> B, A -> C",
          "R(A) with key A"], "A",
         "With key A and transitive FD B -> C, the relation satisfies 2NF but fails 3NF."),
        ("INTERMEDIATE", "A relation in 3NF can still violate BCNF when:",
         ["A candidate key's proper subset determines another attribute",
          "A non-key attribute depends on the full key",
          "All attributes are part of candidate keys",
          "The relation has no functional dependencies"], "A",
         "3NF tolerates dependencies whose left side is a subset of a key; BCNF does not, so such relations can fail BCNF."),
        ("INTERMEDIATE", "Decomposing a relation into 3NF must always be:",
         ["Lossless-join and dependency preserving if the synthesis algorithm is used",
          "Only lossless-join with dependencies possibly lost",
          "Lossy unless BCNF is used",
          "Impossible without dropping keys"], "A",
         "The 3NF synthesis algorithm guarantees both lossless joins and dependency preservation."),
        ("INTERMEDIATE", "Which schema is already in BCNF?",
         ["R(A, B, C) with key A and FDs A -> B and A -> C",
          "R(A, B, C) with key A and FD B -> C",
          "R(A, B, C) with key AB and FD B -> C",
          "R(A, B) with FD A -> B"], "A",
         "Every dependency in the first schema has A (the key) as its determinant, so BCNF holds."),
        ("INTERMEDIATE", "An update anomaly is best described as:",
         ["A change to one fact requiring many rows to be changed consistently",
          "A query returning an error",
          "A constraint rejecting a NULL value",
          "An index becoming fragmented"], "A",
         "Redundant data forces a single logical fact to be updated in many places, risking inconsistency."),
        ("INTERMEDIATE", "Given FDs AB -> C and C -> D with key AB, the relation is in:",
         ["2NF but not 3NF",
          "3NF but not BCNF",
          "BCNF",
          "Only 1NF"], "A",
         "Both A -> C and B -> C are absent, so no partial dependency; C -> D is transitive, violating 3NF."),
        ("ADVANCED", "Relation R(A, B, C, D) has FDs AB -> C and C -> D and key AB. Which dependency causes the 3NF violation and how is R decomposed?",
         ["C -> D is transitive, so split into R1(A, B, C) and R2(C, D)",
          "AB -> C is partial, so split into R1(A, B) and R2(B, C)",
          "No decomposition is needed",
          "Split into R1(A, D) and R2(B, C)"], "A",
         "C -> D is transitive because C is not a key; separating (C, D) removes the dependency."),
        ("ADVANCED", "Which relation satisfies BCNF despite having a non-trivial functional dependency?",
         ["R(A, B, C) with FDs A -> B and A -> C, key A",
          "R(A, B, C) with FD B -> C, key A",
          "R(A, B, C) with key AB and FD B -> C",
          "R(A, B, C) with FD C -> A and key B"], "A",
         "Every dependency has A as a superkey, so BCNF is satisfied by the first schema."),
        ("ADVANCED", "A relation R(A, B, C) has FDs A -> B and B -> C and key A. Which normal form does it violate?",
         ["3NF, because of the transitive dependency B -> C",
          "2NF, because of a partial dependency",
          "BCNF only, and 3NF holds",
          "It violates no normal form"], "A",
         "C depends transitively on A through B, so 3NF is violated."),
        ("ADVANCED", "Given FDs A -> B and B -> A on relation R(A, B), which statement is correct?",
         ["Both A and B are candidate keys and R is in BCNF",
          "Only A is a key, so R is in 1NF",
          "R cannot be in any normal form",
          "R must be decomposed into two relations"], "A",
         "A -> B makes A a key and B -> A makes B a key; each determinant is a key, so BCNF holds."),
        ("ADVANCED", "A lossless-join decomposition requires that the common attributes of the two schemas:",
         ["Form a superkey of at least one of the schemas",
          "Form a key of neither schema",
          "Be empty",
          "Be a foreign key in both"], "A",
         "Lossless joins need the intersecting attribute set to be a superkey of one side to rejoin tuples correctly."),
        ("ADVANCED", "Which statement distinguishes 3NF from BCNF accurately?",
         ["3NF allows a dependency whose left side is a proper subset of a candidate key; BCNF does not",
          "BCNF allows partial dependencies while 3NF removes them",
          "3NF requires every determinant to be a key",
          "BCNF only applies to relations with one key"], "A",
         "3NF is more lenient, permitting key-subset determinants, while BCNF requires all determinants to be superkeys."),
        ("ADVANCED", "Relation R(A, B, C) has key AB and FD B -> C. What is the correct BCNF decomposition?",
         ["R1(A, B) and R2(B, C)",
          "R1(A, C) and R2(B, C)",
          "R1(A, B) and R2(A, C)",
          "R1(A, B, C) cannot be decomposed"], "A",
         "R1 keeps the key AB, and R2 captures the dependency B -> C so B is a key there."),
        ("ADVANCED", "In a university schema, Student has FDs student_id -> name and dept_code -> dept_name. Where is the transitive dependency?",
         ["dept_name depends on dept_code, not on student_id directly",
          "name depends on dept_code",
          "student_id depends on dept_name",
          "There is no transitive dependency"], "A",
         "dept_name depends on dept_code, which is not a key, so student_id -> dept_name is transitive."),
        ("ADVANCED", "A lossy decomposition occurs when rejoining the decomposed relations:",
         ["Produces tuples that were not present in the original relation",
          "Produces exactly the original tuples",
          "Fails because of NULL keys",
          "Needs a sort that is too slow"], "A",
         "If the join yields extra spurious tuples, the decomposition is lossy rather than lossless."),
        ("ADVANCED", "Which FDs guarantee a relation R(A, B, C) is in BCNF with key A?",
         ["A -> B and A -> C only",
          "B -> C and C -> B",
          "A -> C and C -> A",
          "AB -> C"], "A",
         "With key A, only dependencies whose determinant is A keep the relation in BCNF."),
    ],
    29: [
        ("BEGINNER", "The ACID property that ensures a transaction is an indivisible all-or-nothing unit is:",
         ["Atomicity", "Consistency", "Isolation", "Durability"], "A",
         "Atomicity guarantees that either all transaction operations commit or none take effect."),
        ("BEGINNER", "Which ACID property ensures that committed data survives system crashes?",
         ["Durability", "Atomicity", "Isolation", "Consistency"], "A",
         "Durability guarantees committed changes persist even after a crash or power loss."),
        ("BEGINNER", "The isolation property of ACID means that:",
         ["Concurrent transactions should not interfere with each other's intermediate states",
          "Transactions must run one at a time",
          "Transactions can read uncommitted data freely",
          "All transactions must update the same data"], "A",
         "Isolation keeps each transaction's intermediate state hidden from other concurrent transactions."),
        ("BEGINNER", "Which ACID property ensures a transaction leaves the database in a valid state?",
         ["Consistency", "Atomicity", "Isolation", "Durability"], "A",
         "Consistency guarantees that a transaction moves the database from one valid state to another."),
        ("BEGINNER", "The process of temporarily halting a transaction to wait for another transaction to release a resource is handled by:",
         ["Locking", "Normalization", "Indexing", "Compaction"], "A",
         "Locking mechanisms let a transaction wait for a resource held by another transaction."),
        ("BEGINNER", "A transaction that completes all its steps and writes results to the database is said to:",
         ["Commit", "Abort", "Rollback", "Serialize"], "A",
         "Committing finalizes the transaction so its changes become durable."),
        ("BEGINNER", "Which isolation level allows a transaction to read data written by an uncommitted transaction?",
         ["READ UNCOMMITTED", "READ COMMITTED", "REPEATABLE READ", "SERIALIZABLE"], "A",
         "READ UNCOMMITTED permits dirty reads because it does not check for other transactions' uncommitted writes."),
        ("BEGINNER", "A dirty read occurs when a transaction reads:",
         ["Data written by a transaction that later aborts",
          "Only committed data",
          "Data that is NULL",
          "Data from an index scan"], "A",
         "Reading a value written by a still-uncommitted transaction that later rolls back is a dirty read."),
        ("BEGINNER", "The phenomenon where a transaction reads a value, and then the value is changed by another committed transaction before a re-read, is called a:",
         ["Non-repeatable read", "Dirty read", "Phantom read", "Lost update"], "A",
         "A non-repeatable read sees different values in two reads because another transaction committed in between."),
        ("BEGINNER", "Serializability means that the outcome of concurrent transactions is:",
         ["Equivalent to some serial execution of those transactions",
          "Always ordered by timestamps",
          "Independent of the schedule",
          "Determined by the database size"], "A",
         "A serializable schedule produces the same result as running the transactions one after another."),
        ("INTERMEDIATE", "Two transactions both read balance=100, each adds 50 and writes 200 instead of 150. This anomaly is:",
         ["Lost update", "Dirty read", "Phantom read", "Non-repeatable read"], "A",
         "Each transaction overwrites the other's write, so one committed update is lost."),
        ("INTERMEDIATE", "Which isolation level prevents dirty reads but still allows non-repeatable reads?",
         ["READ COMMITTED", "READ UNCOMMITTED", "SERIALIZABLE", "REPEATABLE READ"], "A",
         "READ COMMITTED avoids dirty reads yet permits another committed transaction to change a row between two reads."),
        ("INTERMEDIATE", "REPEATABLE READ prevents which anomaly but not phantom reads?",
         ["Non-repeatable reads", "Dirty reads only", "Lost updates", "Dirty writes"], "A",
         "REPEATABLE READ keeps re-reads stable but does not prevent new rows from appearing in a result set."),
        ("INTERMEDIATE", "A phantom read occurs when a transaction:",
         ["Runs the same query twice and sees new rows inserted by another committed transaction",
          "Reads a row twice and sees a changed value",
          "Reads an aborted transaction's data",
          "Overwrites another transaction's committed write"], "A",
         "Phantom reads involve new tuples appearing between two executions of the same query."),
        ("INTERMEDIATE", "Which statement about two-phase locking (2PL) is true?",
         ["It has a growing phase for acquiring locks and a shrinking phase for releasing them",
          "It requires all locks to be released before any is acquired",
          "It only uses shared locks",
          "It prevents all deadlocks automatically"], "A",
         "2PL divides a transaction into a growing phase of lock acquisition and a shrinking phase of release."),
        ("INTERMEDIATE", "A deadlock between two transactions is resolved by the DBMS by:",
         ["Aborting and rolling back one of the transactions",
          "Ignoring the locked resources",
          "Increasing the transaction timeout only",
          "Dropping the table that holds the lock"], "A",
         "The DBMS picks a victim transaction, aborts it and rolls back to break the deadlock cycle."),
        ("INTERMEDIATE", "Which isolation level provides the strongest guarantee and eliminates dirty, non-repeatable and phantom reads?",
         ["SERIALIZABLE", "READ COMMITTED", "REPEATABLE READ", "READ UNCOMMITTED"], "A",
         "SERIALIZABLE behaves like a serial execution and prevents all three read anomalies."),
        ("INTERMEDIATE", "Under strict two-phase locking, locks are released:",
         ["Only after the transaction commits or aborts",
          "Immediately after each operation",
          "Before any new lock is acquired",
          "Only when the buffer pool fills"], "A",
         "Strict 2PL holds all locks until commit or abort, preventing cascading aborts."),
        ("INTERMEDIATE", "If transaction T1 updates row R and T2 waits for R, then T1 waits for a resource held by T2, the system is in:",
         ["Deadlock", "Normal execution", "Commit", "Recovery"], "A",
         "Each transaction waits for a resource the other holds, forming a deadlock cycle."),
        ("INTERMEDIATE", "Under the SERIALIZABLE isolation level, the DBMS typically uses which locking scheme?",
         ["Strict two-phase locking",
          "No locking at all",
          "Optimistic versioning with no checks",
          "Shared locks only"], "A",
         "Strict two-phase locking with shared/exclusive locks yields serializable schedules."),
        ("ADVANCED", "In a banking system, T1 reads account A and T2 reads the same A, then both add 100 and write back. Which isolation level alone fully prevents the lost update?",
         ["SERIALIZABLE with proper lock durations",
          "READ UNCOMMITTED",
          "READ COMMITTED without locking writes",
          "REPEATABLE READ without update locks"], "A",
         "SERIALIZABLE serializes the read-modify-write cycle, preventing both lost updates."),
        ("ADVANCED", "A schedule S is conflict-serializable if:",
         ["Its conflicting operations can be reordered by swapping non-conflicting ones into a serial schedule",
          "It uses only shared locks",
          "All transactions commit at the same time",
          "It has no deadlocks"], "A",
         "Conflict serializability reorders non-conflicting operations to reach an equivalent serial schedule."),
        ("ADVANCED", "With snapshot isolation, a transaction's reads come from:",
         ["A versioned snapshot taken when the transaction began",
          "The live committed rows at read time",
          "The uncommitted buffer pool",
          "The redo log only"], "A",
         "Snapshot isolation reads a consistent historical version of the data from transaction start."),
        ("ADVANCED", "Under READ COMMITTED, a non-repeatable read can still happen because:",
         ["Another transaction may commit a change between the two reads",
          "The isolation level blocks all writes",
          "The transaction locks every row it touches",
          "The transaction reads only its own writes"], "A",
         "READ COMMITTED does not hold read locks, so a concurrent commit can change a value between reads."),
        ("ADVANCED", "A system detects a cycle in its wait-for graph. The appropriate immediate response is:",
         ["Abort a victim transaction and roll back its changes",
          "Upgrade all shared locks to exclusive locks",
          "Increase the isolation level to SERIALIZABLE",
          "Force a full database restart"], "A",
         "A cycle in the wait-for graph signals deadlock; choosing and aborting a victim resolves it."),
        ("ADVANCED", "Which scenario is the classic phantom-read failure under REPEATABLE READ?",
         ["The same SELECT range query returns more rows after another transaction inserts a matching row",
          "A committed row value changes between two reads",
          "A transaction reads an uncommitted aborting value",
          "Two transactions overwrite the same balance"], "A",
         "REPEATABLE READ locks existing rows but not gaps, so new rows can appear as phantoms."),
        ("ADVANCED", "In the write-ahead logging protocol, the log record must be written:",
         ["Before the corresponding data page is flushed to disk",
          "After the data page is written",
          "Only at checkpoint time",
          "Only during commit"], "A",
         "Write-ahead logging forces the log to disk before data pages so recovery can redo or undo changes."),
        ("ADVANCED", "Cascading aborts are avoided under which locking discipline?",
         ["Strict two-phase locking",
          "Basic two-phase locking",
          "Optimistic concurrency without validation",
          "READ UNCOMMITTED"], "A",
         "Strict 2PL releases locks only at commit, so no transaction reads uncommitted data and cascades aborts."),
        ("ADVANCED", "Given a wait-for graph with edges T1 -> T2 and T2 -> T1, the correct conclusion is:",
         ["A deadlock exists and one transaction must be aborted",
          "Both transactions will commit normally",
          "The schedule is serial",
          "The isolation level must be lowered"], "A",
         "A cycle in the wait-for graph means each waits on the other, so the DBMS must break the cycle."),
        ("ADVANCED", "Which of these pairs can occur in READ COMMITTED but never in SERIALIZABLE?",
         ["Non-repeatable read followed by a phantom read",
          "A dirty read of uncommitted data",
          "Reading a committed row",
          "A transaction that only performs SELECTs"], "A",
         "READ COMMITTED permits non-repeatable and phantom reads, while SERIALIZABLE prevents both."),
    ],
    30: [
        ("BEGINNER", "Which data structure is commonly used by databases to speed up point lookups by key value?",
         ["A B+ tree index", "A linked list", "A hash table is never used", "A binary tree is the only option"], "A",
         "B+ trees are the standard balanced index structure used for fast equality and range lookups."),
        ("BEGINNER", "A clustered index determines:",
         ["The physical order of rows on disk",
          "The logical order of rows in queries only",
          "The order of the redo log",
          "The number of secondary indexes"], "A",
         "A clustered index stores rows physically in key order, so there can be only one per table."),
        ("BEGINNER", "An index that does not affect the physical row order and references the clustered key is called:",
         ["A secondary index", "A clustered index", "A primary index", "A heap index"], "A",
         "Secondary (non-clustered) indexes store key-to-row pointers without reordering physical rows."),
        ("BEGINNER", "The purpose of a query plan (execution plan) is to:",
         ["Describe the steps the DBMS uses to execute a query",
          "Store the query text for reuse",
          "Encrypt the query result",
          "Lock all accessed tables"], "A",
         "An execution plan details access methods, join orders and operators the optimizer chose for a query."),
        ("BEGINNER", "Which part of the DBMS chooses how to execute a SQL query?",
         ["The query optimizer", "The lock manager", "The recovery manager", "The buffer manager"], "A",
         "The query optimizer selects access paths and join strategies that minimize estimated cost."),
        ("BEGINNER", "A full table scan is typically chosen when:",
         ["Most rows in the table must be read or the table is very small",
          "The query filters on a highly selective indexed column",
          "The table has a clustered index",
          "The query uses an exact primary key lookup"], "A",
         "When selectivity is low or the table is small, scanning all pages is cheaper than using an index."),
        ("BEGINNER", "Which index type is best suited for range queries such as age BETWEEN 20 AND 30?",
         ["A B+ tree index", "A bitmap on a wide value", "A hash index", "No index helps range queries"], "A",
         "B+ tree indexes keep keys in sorted order, enabling efficient ordered range scans."),
        ("BEGINNER", "A heap file organization stores rows:",
         ["In no particular order, appended as they arrive",
          "In sorted key order",
          "Grouped by index value",
          "Encrypted on disk"], "A",
         "Heap files append new tuples without ordering them by any key."),
        ("BEGINNER", "The cost of an index lookup usually depends most heavily on:",
         ["The height of the index tree and the number of matching rows",
          "The size of the SELECT list only",
          "The number of columns in the table",
          "The disk rotation speed only"], "A",
         "Tree height determines traversal cost and the matched row count determines how many pages are fetched."),
        ("BEGINNER", "What does an index on a table column NOT speed up?",
         ["Writing the same value to many rows that changes the indexed key",
          "Equality lookups on the indexed column",
          "Range scans on the indexed column",
          "Sorted retrieval on the indexed column"], "A",
         "Indexed key updates force index maintenance overhead, which can slow down writes."),
        ("INTERMEDIATE", "A query filters WHERE dept_id = 7 and dept_id is indexed but very few rows match. The optimizer most likely chooses:",
         ["An index scan returning only the matching rows",
          "A full table scan",
          "A merge join with no filter",
          "A hash index on every column"], "A",
         "High selectivity makes the index seek cheaper than reading every page of the table."),
        ("INTERMEDIATE", "Why does a clustered index on a composite key (a, b) also help queries filtering only on a?",
         ["The key order groups rows with the same a together, enabling a prefix range scan",
          "Because every secondary index is dropped",
          "Because a is always unique",
          "Because the table becomes a heap"], "A",
         "The leading column of a clustered index orders data, so prefix-only predicates still use the index."),
        ("INTERMEDIATE", "The optimizer compares two join plans and selects:",
         ["The one with the lower estimated total cost in I/O and CPU",
          "The plan with more hash operations",
          "The first plan generated",
          "The plan with the fewest output columns"], "A",
         "Cost-based optimization ranks plans by estimated resource usage and picks the cheapest."),
        ("INTERMEDIATE", "A query scans all 100 pages of a table for every join probe. This is an example of:",
         ["A nested-loop join with repeated full scans",
          "A merge join on sorted inputs",
          "A hash join",
          "An index-only join"], "A",
         "Nested-loop join probes the inner relation for each outer row, which can require repeated page scans."),
        ("INTERMEDIATE", "Hash joins are most efficient when:",
         ["Joining large, unsorted inputs on equality conditions",
          "Joining inputs that are already sorted",
          "Joining on non-equality conditions",
          "Joining single-row inputs"], "A",
         "Hash joins build and probe hash tables, excelling at large equi-joins without needing sorted data."),
        ("INTERMEDIATE", "An index-only scan (covering index) is possible when:",
         ["All columns needed by the query appear in the index",
          "The index is clustered on the primary key",
          "The table has no secondary indexes",
          "The query uses SELECT *"], "A",
         "A covering index holds every referenced column, so the query never reads the table pages."),
        ("INTERMEDIATE", "Which action could turn an otherwise selective index use into a full table scan?",
         ["Wrapping the indexed column in a function such as YEAR(order_date)",
          "Using an equality predicate on the column",
          "Using the leading index column in WHERE",
          "Keeping statistics up to date"], "A",
         "Applying a function to the column can block the optimizer from using the index on that column."),
        ("INTERMEDIATE", "Statistics about data distribution are used by the optimizer to:",
         ["Estimate selectivity and the number of matching rows",
          "Compress the index pages",
          "Decide the isolation level",
          "Choose the redo log size"], "A",
         "Histograms and cardinality estimates let the optimizer predict how many rows a filter returns."),
        ("INTERMEDIATE", "To speed up a query that filters on city and sorts by last_name, a useful index would be:",
         ["A composite B+ tree index on (city, last_name)",
          "A separate index only on last_name",
          "A hash index on city",
          "No index at all"], "A",
         "A composite index (city, last_name) satisfies the filter and provides sorted last_name order."),
        ("INTERMEDIATE", "Which of these is the correct B+ tree leaf behavior compared to a standard B-tree?",
         ["All leaves are linked together and contain actual data keys",
          "Leaves point only to parent nodes",
          "Data keys appear only in internal nodes",
          "Leaves are never visited during lookups"], "A",
         "B+ trees keep all actual keys in linked leaves, which simplifies ordered traversal."),
        ("ADVANCED", "A B+ tree with order 4 (max 4 pointers per node) stores 1,000,000 keys. Which factor most limits lookup cost?",
         ["The tree height, which grows as the log of the leaf count",
          "The number of leaf keys, which is irrelevant to height",
          "The total number of tables",
          "The disk page size being unlimited"], "A",
         "High fanout keeps B+ tree height small, so a lookup touches only a few levels."),
        ("ADVANCED", "Why are hash indexes unsuitable for the query WHERE salary >= 50000 ORDER BY salary?",
         ["Hash indexes preserve no ordering, so they cannot support range or sorted output",
          "Hash indexes cannot store numbers",
          "Hash indexes only support joins",
          "Hash indexes are always clustered"], "A",
         "Hash structures give O(1) equality lookups but no ordered access, so ranges and sorts need a B+ tree."),
        ("ADVANCED", "An optimizer sees WHERE a = 5 AND b = 7 on a two-column B+ tree index (a, b). It can:",
         ["Use the index to find exact matches without visiting the table",
          "Only use the index for column b",
          "Never use the composite index",
          "Fall back to a merge join"], "A",
         "Both equality predicates use the index's full key prefix, enabling precise index seeks."),
        ("ADVANCED", "A query joins Orders (large) and Customers (small) on customer_id with an index on Orders.customer_id. The best join strategy is usually:",
         ["Index nested-loop join reading Orders through the index for each Customer",
          "Hash join that builds on Orders",
          "Sort-merge join with no indexes",
          "Cartesian product followed by a filter"], "A",
         "Probing the indexed Orders table for each small Customer row avoids scanning the large table."),
        ("ADVANCED", "Under which condition would the optimizer still choose a full scan over an existing index?",
         ["The indexed column has low cardinality such that most rows match the filter",
          "The index has high selectivity",
          "The predicate uses equality on the leading column",
          "The table has a clustered primary key"], "A",
         "If the filter matches nearly all rows, reading the whole table sequentially is cheaper than random index I/O."),
        ("ADVANCED", "A covering index on (product_id, price) helps the query SELECT price FROM products WHERE product_id = 5 because:",
         ["Both columns are in the index, so table pages are never accessed",
          "The index is clustered on price",
          "product_id is the table's primary key only",
          "The optimizer disables table reads entirely"], "A",
         "With all required columns present, the index alone answers the query, avoiding heap lookups."),
        ("ADVANCED", "Two B+ tree indexes exist on (a, b) and on (b). A query filters WHERE b = 5 AND a = 10. Which is the best index choice?",
         ["(a, b), because equality on the leading column a allows a precise seek and b is still checked",
          "(b) alone, because b is the only filter",
          "Either index gives identical performance",
          "No index can be used"], "A",
         "The (a, b) index lets the optimizer seek on a = 10 and validate b = 5 within the matching range."),
        ("ADVANCED", "Bitmap indexes are most effective on columns that:",
         ["Have low cardinality such as gender or status",
          "Have a distinct value per row",
          "Store large text documents",
          "Are always NULL"], "A",
         "Bitmap indexes compress repetitive values well and support fast bitwise AND/OR for low-cardinality columns."),
        ("ADVANCED", "After heavy updates, the optimizer's cost estimate for using an index may become wrong because:",
         ["Outdated statistics misreport the number of distinct values and row counts",
          "The index files are always stored in memory",
          "Updates never change index structure",
          "The redo log prevents index reads"], "A",
         "Stale statistics lead to poor selectivity estimates and therefore suboptimal plans."),
        ("ADVANCED", "To diagnose a query that ignores a helpful index, the best first step is:",
         ["Examine the execution plan to see the chosen access path and estimated rows",
          "Rebuild the whole operating system",
          "Disable all other indexes",
          "Increase the buffer pool to infinite size"], "A",
         "Reading the plan reveals why the index was not chosen, such as a function on the column or stale stats."),
    ],
}
