# -*- coding: utf-8 -*-
"""
Question bank for subject 11: NET101 - Networking Fundamentals.
Category: Computer Networks.

Topics:
  51: OSI Model
  52: TCP/IP Model
  53: Physical Layer & Topologies
  54: Data Link Layer & MAC
  55: Error Detection & Correction

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    51: [
        ("BEGINNER", "Which layer of the OSI model provides services directly to end-user applications?",
         ["Application layer", "Data Link layer", "Transport layer", "Network layer"], "A",
         "The Application layer is the top OSI layer and is the interface that end-user software uses to access network services."),
        ("BEGINNER", "How many layers are defined in the OSI reference model?",
         ["5", "7", "6", "4"], "B",
         "The OSI reference model defines seven layers, from the Physical layer up to the Application layer."),
        ("BEGINNER", "Which OSI layer is responsible for routing packets between networks?",
         ["Session layer", "Transport layer", "Network layer", "Presentation layer"], "C",
         "The Network layer selects paths and routes packets from source to destination across networks."),
        ("BEGINNER", "At which OSI layer do Ethernet switches primarily operate?",
         ["Physical layer", "Application layer", "Session layer", "Data Link layer"], "D",
         "Ethernet switches forward frames based on MAC addresses, which is Data Link layer (layer 2) work."),
        ("BEGINNER", "Which OSI layer is responsible for end-to-end delivery and segmentation of data?",
         ["Transport layer", "Network layer", "Physical layer", "Presentation layer"], "A",
         "The Transport layer provides end-to-end communication, breaking data into segments and reassembling them."),
        ("BEGINNER", "Which OSI layer is responsible for converting data into a standard format, including encryption and compression?",
         ["Application layer", "Presentation layer", "Session layer", "Network layer"], "B",
         "The Presentation layer handles data translation, encryption and compression so that formats are standardized."),
        ("BEGINNER", "Which OSI layer establishes, manages and terminates communication sessions?",
         ["Physical layer", "Data Link layer", "Session layer", "Transport layer"], "C",
         "The Session layer sets up, coordinates and ends sessions between two communicating applications."),
        ("BEGINNER", "Which OSI layer deals with electrical, mechanical and physical transmission of raw bits?",
         ["Physical layer", "Application layer", "Network layer", "Session layer"], "D",
         "The Physical layer transmits raw bit streams over the transmission medium using electrical, optical or radio signals."),
        ("BEGINNER", "Which OSI layer ensures reliable transfer of frames between adjacent nodes and handles error detection?",
         ["Data Link layer", "Application layer", "Session layer", "Transport layer"], "A",
         "The Data Link layer frames data and provides error detection for the hop between directly connected nodes."),
        ("BEGINNER", "Which OSI layer deals with the syntax and semantics of data exchange between systems?",
         ["Network layer", "Presentation layer", "Transport layer", "Physical layer"], "B",
         "The Presentation layer standardizes the syntax and semantics so both systems interpret the data identically."),
        ("INTERMEDIATE", "A web browser displays a page that arrives as raw HTTP. Which OSI layers are involved in a typical HTTP request?",
         ["Application, Transport, Network, Data Link and Physical", "Only Application and Physical", "Only Network and Data Link", "Application and Session only"], "A",
         "An HTTP request travels down through Application, Transport, Network, Data Link and Physical layers on the sender and back up on the receiver."),
        ("INTERMEDIATE", "A network engineer uses Wireshark and sees a TCP segment. At which OSI layer was this segment created?",
         ["Network layer", "Transport layer", "Session layer", "Application layer"], "B",
         "TCP creates segments, and TCP is the Transport layer protocol in the OSI model."),
        ("INTERMEDIATE", "Data arrives corrupted and the receiver requests retransmission. Which layer is most directly responsible for recovery via retransmission?",
         ["Physical layer", "Data Link layer", "Transport layer", "Presentation layer"], "C",
         "The Transport layer provides reliable delivery and retransmits lost or corrupted segments when needed."),
        ("INTERMEDIATE", "A router must decide which interface to send a packet through. Which OSI layer performs this decision?",
         ["Data Link layer", "Physical layer", "Transport layer", "Network layer"], "D",
         "Routing decisions and packet forwarding are Network layer functions."),
        ("INTERMEDIATE", "Two applications want to keep an FTP login session alive across multiple exchanges. Which layer coordinates this conversation?",
         ["Session layer", "Physical layer", "Network layer", "Data Link layer"], "A",
         "The Session layer establishes and maintains the dialog state between the two applications."),
        ("INTERMEDIATE", "You upgrade a cable and the network speed increases from 100 Mbps to 1 Gbps. Which OSI layer was most affected?",
         ["Network layer", "Physical layer", "Session layer", "Application layer"], "B",
         "The cable carries the raw bit stream, so changes in transmission speed belong to the Physical layer."),
        ("INTERMEDIATE", "A compression service squeezes a file before it is sent over the network. Which OSI layer would normally do this?",
         ["Transport layer", "Data Link layer", "Presentation layer", "Session layer"], "C",
         "Compression is a presentation function that converts data into a more efficient format before transmission."),
        ("INTERMEDIATE", "Encryption for a VPN tunnel is applied before the data is handed to the session and transport layers. Which layer is responsible?",
         ["Physical layer", "Data Link layer", "Network layer", "Presentation layer"], "D",
         "The Presentation layer performs encryption and decryption as part of its data-transformation role."),
        ("INTERMEDIATE", "A frame fails a checksum at a switch. Which layer discarded the frame?",
         ["Data Link layer", "Application layer", "Transport layer", "Session layer"], "A",
         "Frame checksums are validated at the Data Link layer, which drops corrupted frames."),
        ("INTERMEDIATE", "Which layer pair interacts most directly with the concept of a socket (IP address plus port number)?",
         ["Physical and Session", "Network and Transport", "Data Link and Network", "Presentation and Application"], "B",
         "A socket is the combination of an IP address (Network layer) and a port number (Transport layer)."),
        ("ADVANCED", "A designer must guarantee reliable end-to-end delivery with sequencing while the network is unreliable. Which layer provides this and how?",
         ["The Transport layer, using connection-oriented delivery", "The Network layer, using best-effort forwarding", "The Physical layer, using bit timing", "The Application layer, using caching"], "A",
         "The Transport layer provides connection-oriented, reliable delivery with sequencing and acknowledgements."),
        ("ADVANCED", "A company encrypts data in the Presentation layer. Which attack class does this protect against at the Application layer?",
         ["MAC address spoofing", "eavesdropping on the wire", "IP address conflicts", "collision detection"], "B",
         "Presentation-layer encryption protects the application payload from being read by eavesdroppers."),
        ("ADVANCED", "Why is it valid for a router to function at only layers 1, 2 and 3 of the OSI model?",
         ["Because routers only understand MAC addresses", "Because it uses only physical signals", "Because routing requires only those layers, while upper-layer functions stay in end hosts", "Because the OSI model has exactly three usable layers"], "C",
         "Routers forward packets using layers 1-3; upper-layer services are provided by end hosts, not by forwarding devices."),
        ("ADVANCED", "During a DDoS attack, a firewall drops packets at layer 3. What is the immediate benefit for the network?",
         ["It guarantees application availability", "It reduces layer 4 connection setup", "It protects the OSI model itself", "It prevents harmful traffic from reaching higher layers"], "D",
         "Filtering at the Network layer stops attacking traffic before it consumes Transport or Application layer resources."),
        ("ADVANCED", "An architect needs to place a proxy that can inspect HTTPS content. Where must decryption occur?",
         ["In a middlebox acting on behalf of the Application layer", "In the Physical layer regenerating signals", "In the Data Link layer forwarding frames", "In a switch inspecting MAC addresses"], "A",
         "HTTPS inspection requires terminating and decrypting the TLS session, which is an Application-layer proxy function."),
        ("ADVANCED", "A developer says the app needs reliable delivery but the network is slow. Which OSI layer should absorb retransmission logic?",
         ["Physical layer", "Transport layer", "Session layer", "Presentation layer"], "B",
         "Retransmission and reliability logic belongs in the Transport layer, keeping applications simpler."),
        ("ADVANCED", "A technician notices packets are fragmented and later reassembled at the destination. Which layer is responsible for reassembly?",
         ["Application layer", "Session layer", "Network layer", "Physical layer"], "C",
         "The Network layer fragments large packets and the destination Network layer reassembles them."),
        ("ADVANCED", "Two sites use a WAN link where frames must be forwarded hop by hop. Which OSI layer handles this hop-by-hop delivery?",
         ["Transport layer", "Application layer", "Presentation layer", "Data Link layer"], "D",
         "Hop-by-hop frame delivery between adjacent nodes is the responsibility of the Data Link layer."),
        ("ADVANCED", "Why is layering valuable when troubleshooting a slow application?",
         ["It lets engineers isolate the problem to a single layer and test it independently", "It removes the need for protocols", "It makes all layers identical", "It eliminates hardware failures"], "A",
         "Layered design isolates functionality so problems can be localized and tested layer by layer."),
        ("ADVANCED", "Which statement best explains why the OSI model is a reference model rather than a working protocol suite?",
         ["It defines specific implementations that all vendors must use", "It is a conceptual framework that guides design; real systems like TCP/IP implement it only loosely", "It has been replaced by Ethernet", "It only describes physical media"], "B",
         "OSI is a conceptual reference framework; real-world suites such as TCP/IP map to it approximately but do not implement it exactly."),
    ],
    52: [
        ("BEGINNER", "Which protocol provides reliable, connection-oriented transport in the TCP/IP suite?",
         ["TCP", "UDP", "ICMP", "ARP"], "A",
         "TCP offers reliable, ordered delivery with acknowledgements and retransmission."),
        ("BEGINNER", "Which TCP/IP layer corresponds most closely to the OSI Physical and Data Link layers?",
         ["Transport layer", "Network Interface (Link) layer", "Internet layer", "Application layer"], "B",
         "The Link layer of the TCP/IP model covers the physical media and data link technologies such as Ethernet."),
        ("BEGINNER", "Which protocol is responsible for logical addressing and routing in the TCP/IP Internet layer?",
         ["TCP", "ARP", "IP", "UDP"], "C",
         "IP provides logical addressing and routing of datagrams in the Internet layer."),
        ("BEGINNER", "Which TCP/IP layer combines the functions of the OSI Application, Presentation and Session layers?",
         ["Transport layer", "Internet layer", "Network Access layer", "Application layer"], "D",
         "The Application layer of TCP/IP bundles the three top OSI layers into one."),
        ("BEGINNER", "Which protocol is commonly used to translate domain names to IP addresses?",
         ["DNS", "DHCP", "SMTP", "FTP"], "A",
         "DNS resolves human-readable host names into the IP addresses used by the Internet layer."),
        ("BEGINNER", "Which of the following is a Transport layer protocol in the TCP/IP model?",
         ["IP", "UDP", "ARP", "ICMP"], "B",
         "UDP is a Transport layer protocol that provides connectionless, best-effort delivery."),
        ("BEGINNER", "What is the data unit created by the TCP protocol called?",
         ["frames", "datagrams", "segments", "bits"], "C",
         "TCP creates segments from the application stream and passes them to the Internet layer for encapsulation."),
        ("BEGINNER", "Which protocol is used by routers to report delivery errors such as unreachable hosts?",
         ["TCP", "UDP", "ARP", "ICMP"], "D",
         "ICMP carries diagnostic and error messages such as destination unreachable and time exceeded."),
        ("BEGINNER", "Which TCP/IP protocol automatically assigns IP addresses to hosts on a network?",
         ["DHCP", "DNS", "HTTP", "FTP"], "A",
         "DHCP dynamically leases IP addresses and related configuration to hosts."),
        ("BEGINNER", "Which layer of the TCP/IP model is responsible for end-to-end communication between applications?",
         ["Internet layer", "Transport layer", "Link layer", "Physical layer"], "B",
         "The Transport layer provides end-to-end communication between applications through ports."),
        ("INTERMEDIATE", "A host sends a request to 8.8.8.8 and receives no reply. Which protocol would the host use to test reachability?",
         ["ping using ICMP", "ARP to find the MAC", "DHCP to get an address", "DNS to resolve the name"], "A",
         "The ping utility sends ICMP echo requests to test whether a remote host is reachable."),
        ("INTERMEDIATE", "An email client sends messages with SMTP and receives them with IMAP. Which TCP/IP layer do SMTP and IMAP belong to?",
         ["Internet layer", "Application layer", "Link layer", "Transport layer"], "B",
         "SMTP and IMAP are Application layer protocols that exchange mail content between clients and servers."),
        ("INTERMEDIATE", "A packet destined for another network must leave the local subnet. Which device forwards it at the Internet layer?",
         ["a switch", "a hub", "a router", "a repeater"], "C",
         "A router forwards packets between networks using Internet layer addressing and routing tables."),
        ("INTERMEDIATE", "A VoIP call needs low latency and tolerates some packet loss. Which transport protocol is the best fit?",
         ["TCP", "UDP", "ARP", "SMTP"], "D",
         "UDP avoids retransmission and handshake delays, keeping latency low for real-time voice traffic."),
        ("INTERMEDIATE", "A browser fetches a web page. Which sequence best describes the protocols involved?",
         ["HTTP over TCP over IP over Ethernet", "HTTP over UDP over IP over ATM", "SMTP over TCP over IP", "FTP over ICMP over IP"], "A",
         "HTTP rides on the reliable TCP transport, which is encapsulated in IP, which is carried by the Ethernet link."),
        ("INTERMEDIATE", "A file download must be complete and error-free. Which transport protocol is appropriate and why?",
         ["UDP, because it is faster without checks", "TCP, because it guarantees ordered, reliable delivery", "ARP, because it finds the gateway", "ICMP, because it reports errors"], "B",
         "TCP's acknowledgements and retransmission guarantee that the entire file arrives intact and in order."),
        ("INTERMEDIATE", "A network administrator sees repeated destination unreachable messages. Which protocol generated them?",
         ["TCP", "UDP", "ICMP", "DHCP"], "C",
         "ICMP destination unreachable messages are generated by routers when no route to a host exists."),
        ("INTERMEDIATE", "A workstation joins a network and receives an IP address, subnet mask and gateway automatically. Which protocol was used?",
         ["DNS", "HTTP", "ARP", "DHCP"], "D",
         "DHCP leases the IP configuration, including subnet mask and default gateway, to the workstation."),
        ("INTERMEDIATE", "When host A wants to reach host B on the same subnet, which two addresses are used at the Link layer?",
         ["B's MAC address and A's MAC address", "B's IP and A's MAC", "the router's MAC and B's IP", "only IP addresses"], "A",
         "On the same subnet the frame is delivered directly from A's MAC to B's MAC without involving a router."),
        ("INTERMEDIATE", "Which protocol is used to deliver a request from a web client to a web server on port 80?",
         ["DNS", "HTTP", "FTP", "SMTP"], "B",
         "HTTP carries web requests and responses between browsers and web servers on port 80."),
        ("ADVANCED", "An administrator must support both a reliable large file transfer and a latency-sensitive video stream over one link. Which transport strategy is best?",
         ["Use TCP for the file transfer and UDP for the video stream", "Use TCP for both", "Use UDP for both", "Use ICMP for both"], "A",
         "File transfer needs TCP's reliability while real-time video needs UDP's low latency."),
        ("ADVANCED", "A design decision: move from fixed IP addresses to DHCP. What is the key benefit and main risk?",
         ["No benefit, only added risk", "Automated addressing with simpler management, but the network depends on the DHCP server staying available", "DHCP removes the need for IP addresses", "DHCP eliminates routing entirely"], "B",
         "DHCP centralizes and automates IP assignment, but the network depends on the DHCP server being reachable."),
        ("ADVANCED", "A streaming server drops some UDP segments, yet playback continues. Why does the client remain functional?",
         ["UDP retransmits lost data instantly", "The video is decoded in order no matter what", "The application tolerates some loss and buffers data, while TCP-style retransmission would add unacceptable delay", "The Link layer corrects all losses"], "C",
         "Streaming applications absorb small losses with buffering; reliable retransmission would add too much latency."),
        ("ADVANCED", "During a DDoS flood, TCP SYN packets saturate a server. Which mitigation is a legitimate Internet-layer approach?",
         ["Raising the OSI model", "Switching to a hub", "Blocking the attack at the Internet layer with filtering before it reaches the server", "Rebooting the client"], "D",
         "Filtering malicious traffic at the Internet layer, typically on a firewall or router, protects upper-layer services."),
        ("ADVANCED", "Why does the TCP/IP model merge the OSI Presentation and Session layers into the Application layer?",
         ["Because in practice those functions are implemented by the application protocols themselves", "Because the OSI layers are obsolete", "Because it removes security", "Because there is no encryption in TCP/IP"], "A",
         "Internet applications bundle encryption, compression and session state into their own protocols."),
        ("ADVANCED", "A network uses RFC 1918 private addresses behind NAT. What problem does NAT solve?",
         ["It replaces routing entirely", "It lets many private hosts share a limited pool of public IP addresses", "It speeds up DNS", "It removes the need for DHCP"], "B",
         "NAT maps many private addresses to few public ones, conserving the limited IPv4 address space."),
        ("ADVANCED", "A packet's TTL field reaches zero and it is discarded. Which protocol reports this back to the sender?",
         ["ARP", "TCP", "ICMP", "DHCP"], "C",
         "ICMP time-exceeded messages inform the sender that the packet expired before reaching its destination."),
        ("ADVANCED", "An engineer chooses TCP for a chat application. What is the main reason this choice is justified?",
         ["TCP adds no overhead", "Chat messages must be delivered in order and without loss", "TCP is faster than UDP", "TCP can carry broadcast traffic"], "D",
         "The conversational ordering and reliability of TCP fit text chat well."),
        ("ADVANCED", "To make a home server reachable from the internet through NAT, which technique maps the public address to the private one?",
         ["Port forwarding", "MAC address cloning", "DNS caching", "IPv6 tunneling"], "A",
         "Port forwarding instructs the NAT device to send inbound traffic on a chosen port to the private server."),
        ("ADVANCED", "Why is IPv6 considered a long-term fix for address exhaustion rather than NAT?",
         ["IPv6 removes routing", "IPv6 offers a vast address space so private-to-public translation is not needed", "IPv6 is slower", "IPv6 cannot be routed"], "B",
         "The enormous IPv6 address space makes end-to-end addressing practical without translation."),
    ],
    53: [
        ("BEGINNER", "Which network topology connects every device to a single central hub or switch?",
         ["Star topology", "Bus topology", "Ring topology", "Mesh topology"], "A",
         "In a star topology all devices connect to one central hub or switch through point-to-point links."),
        ("BEGINNER", "In a bus topology, what connects all the devices to the shared backbone cable?",
         ["A central switch", "Drop lines off a single backbone", "A ring of cables", "Dedicated point-to-point links"], "B",
         "In a bus topology every device attaches to one common backbone cable through drop lines."),
        ("BEGINNER", "Which topology connects each device to exactly two neighbours, forming a loop?",
         ["Star", "Bus", "Ring", "Tree"], "C",
         "In a ring topology each device connects to two neighbours so data travels around a closed loop."),
        ("BEGINNER", "In a mesh topology, how are devices interconnected?",
         ["All through one hub", "On one backbone cable", "Every device connects directly to many or all other devices", "In a single loop"], "D",
         "A mesh topology provides direct links between devices, giving redundancy but high cabling cost."),
        ("BEGINNER", "What is the primary job of the Physical layer?",
         ["Transmitting raw bits over the medium", "Routing packets", "Detecting network errors end to end", "Addressing applications"], "A",
         "The Physical layer is responsible for transmitting raw bits across the transmission medium."),
        ("BEGINNER", "Which medium carries data as pulses of light?",
         ["Coaxial cable", "Optical fiber", "Twisted pair", "Cat6 cable"], "B",
         "Optical fiber transmits data as light pulses through glass or plastic strands."),
        ("BEGINNER", "Which transmission medium is a pair of thin copper wires twisted together, most commonly used for Ethernet?",
         ["Coaxial cable", "Fiber", "Unshielded twisted pair (UTP)", "Radio waves"], "C",
         "UTP cabling is the standard twisted-pair copper medium used for most Ethernet LANs."),
        ("BEGINNER", "Which device simply regenerates a weakened signal on a network?",
         ["Switch", "Router", "Firewall", "Repeater"], "D",
         "A repeater receives a weak signal and regenerates it so it can travel further."),
        ("BEGINNER", "What does the term bandwidth refer to in networking?",
         ["The maximum data rate of a link", "The physical length of a cable", "The number of devices on a network", "The IP address range"], "A",
         "Bandwidth is the maximum rate at which data can be transmitted over a link, measured in bits per second."),
        ("BEGINNER", "Which connector is most commonly associated with RJ-45 Ethernet UTP cabling?",
         ["BNC", "RJ-45", "SC", "F-type"], "B",
         "RJ-45 is the eight-pin modular connector used for UTP Ethernet cabling."),
        ("INTERMEDIATE", "A cable run of 300 meters is too long for 100BASE-TX, which is limited to 100 meters. Which medium would support this distance?",
         ["Single-mode fiber", "Cat5e UTP", "Thin coaxial cable", "Untwisted flat cable"], "A",
         "Single-mode fiber supports runs of many kilometers, far beyond the 100-meter UTP limit."),
        ("INTERMEDIATE", "Two switches connect without a crossover cable because the ports auto-negotiate. Which mechanism makes this possible?",
         ["The IP addressing scheme", "Auto-MDIX, which automatically detects and swaps the transmit and receive pairs", "The routing protocol", "The DNS configuration"], "B",
         "Auto-MDIX lets a port detect the cable wiring and swap pairs so crossover cables are unnecessary."),
        ("INTERMEDIATE", "A star topology fails at the central switch. What is the impact on the network?",
         ["Only one device is affected", "The entire star network loses connectivity", "Nothing changes", "The network becomes a mesh"], "C",
         "Because every device depends on the central switch, its failure disconnects the whole star network."),
        ("INTERMEDIATE", "A bus topology cable is cut at one point. What happens to the remaining devices?",
         ["All devices continue normally", "The network becomes a ring", "Devices on one side of the break keep working but the whole bus is effectively divided", "A repeater fixes it automatically"], "D",
         "A break in a bus divides the network; only the segment still connected to a terminator keeps functioning."),
        ("INTERMEDIATE", "You must connect two buildings 2 km apart with immunity to electrical interference. Which medium is the best choice?",
         ["Fiber optic cable", "Cat5e UTP", "Flat ribbon cable", "Plain telephone wire"], "A",
         "Fiber carries light, so it is immune to electromagnetic interference and reaches long distances."),
        ("INTERMEDIATE", "A technician hears about full-duplex operation. What does full duplex mean?",
         ["Data flows in only one direction", "Data can be sent and received simultaneously", "Only one station may transmit at a time", "Frames are broadcast to everyone"], "B",
         "Full duplex allows simultaneous two-way communication on a link."),
        ("INTERMEDIATE", "Half-duplex communication is best described as what?",
         ["Two-way simultaneous", "One-way only", "Two-way, but only one direction at a time", "No transmission allowed"], "C",
         "Half duplex allows transmission in both directions but only one direction at a time."),
        ("INTERMEDIATE", "A collision occurs when two stations transmit at the same time on a shared medium. Which technology resolves collisions on classic Ethernet?",
         ["CSMA/CD", "CSMA/CA", "FDM", "WDM"], "D",
         "CSMA/CD senses the medium and uses collision detection with backoff to handle simultaneous transmissions."),
        ("INTERMEDIATE", "What is the main reason twisted-pair cabling is twisted?",
         ["To reduce electromagnetic interference and crosstalk", "To make it cheaper", "To increase its length", "To allow full duplex"], "A",
         "Twisting pairs cancels interference and crosstalk between adjacent wires."),
        ("INTERMEDIATE", "In a physical star topology using a hub, how does the data flow differ from a switch?",
         ["A hub switches frames intelligently", "A hub broadcasts every signal to all ports like a shared bus", "A hub routes packets", "A hub filters by MAC address"], "B",
         "A hub repeats every incoming signal to all ports, behaving like a shared bus at the physical layer."),
        ("ADVANCED", "A design must give the highest availability with redundant paths between every pair of critical servers. Which topology should be chosen?",
         ["Full mesh", "Star with one hub", "Bus", "Single ring"], "A",
         "A full mesh provides direct redundant paths between every pair, so a single link failure rarely disconnects anyone."),
        ("ADVANCED", "A campus network uses a collapsed backbone where every building switch connects to one core switch. What is the single point of failure?",
         ["The building switches", "The core switch", "The end devices", "The physical cabling within buildings"], "B",
         "With a single core switch, its failure isolates every building connected to it."),
        ("ADVANCED", "Two switches advertise different duplex settings, causing late collisions. What is the correct fix?",
         ["Replace the cable", "Set both switch ports to the same forced duplex mode or correct the auto-negotiation", "Add a repeater", "Change the IP address"], "C",
         "Duplex mismatch must be resolved by matching the duplex settings on both ends of the link."),
        ("ADVANCED", "To support 10 Gbps over a 300-meter campus run, which fiber type is most appropriate?",
         ["Category 5 UTP", "Multimode fiber", "Single-mode fiber with 10GBASE-LR optics", "Coaxial cable"], "D",
         "Single-mode fiber supports 10 Gbps over distances far beyond multimode's limits."),
        ("ADVANCED", "An office must run a temporary gigabit link across an area with heavy machinery causing electrical noise. Which choice is most robust?",
         ["A shielded fiber connection", "Cat3 phone cable", "Untwisted ribbon cable", "A long parallel data cable"], "A",
         "Fiber is immune to electrical noise, making it the most robust choice in an electrically noisy area."),
        ("ADVANCED", "Why does IEEE 802.3 specify minimum and maximum Ethernet frame lengths?",
         ["To make cables cheaper", "To keep collision detection reliable over the maximum network diameter", "To reduce MAC addresses", "To support faster CPUs"], "B",
         "The minimum frame length guarantees the sender is still transmitting when a collision propagates back."),
        ("ADVANCED", "A growing company adds a second floor and needs isolated LANs that can still share one uplink. Which device combines them at layer 2?",
         ["A repeater", "A hub", "A managed switch with VLANs", "A modem"], "C",
         "A managed switch can create VLANs that isolate traffic while sharing the same physical uplink."),
        ("ADVANCED", "An engineer compares Cat6 with Cat5e for future proofing. What is the main advantage of Cat6?",
         ["It is shorter", "It supports higher frequencies and data rates with better crosstalk isolation", "It is wireless", "It uses a different connector"], "D",
         "Cat6 supports higher bandwidth with reduced crosstalk, making it ready for faster Ethernet standards."),
        ("ADVANCED", "A wireless deployment suffers interference in the 2.4 GHz band. Which strategy addresses the issue at the Physical layer?",
         ["Changing to the 5 GHz band or choosing a less congested channel", "Switching to a hub", "Increasing frame size", "Changing the IP subnet"], "A",
         "Moving to 5 GHz or a clearer channel reduces physical layer interference on the wireless medium."),
        ("ADVANCED", "Which statement correctly compares a logical ring topology with a physical star using Token Ring?",
         ["There is no difference", "The physical wiring is a star, but the token passes logically in a ring", "The ring is only physical", "Tokens are replaced by broadcasts"], "B",
         "Token Ring networks used star cabling at the physical layer while the token still circulated logically in a ring."),
    ],
    54: [
        ("BEGINNER", "What is the basic unit of data transmission at the Data Link layer?",
         ["Frame", "Packet", "Segment", "Datagram"], "A",
         "The Data Link layer encapsulates packets into frames for transmission between adjacent nodes."),
        ("BEGINNER", "Which address is used by the Data Link layer to identify devices on the same network segment?",
         ["IP address", "MAC address", "Port number", "Domain name"], "B",
         "MAC addresses uniquely identify devices on a LAN and are used by Data Link layer protocols."),
        ("BEGINNER", "How many bits does a standard MAC address contain?",
         ["32", "48", "64", "128"], "C",
         "A MAC address is 48 bits long, usually written as 12 hexadecimal digits."),
        ("BEGINNER", "Which device forwards frames based on MAC addresses?",
         ["Router", "Hub", "Repeater", "Switch"], "D",
         "A switch learns MAC addresses and forwards frames only toward the correct destination port."),
        ("BEGINNER", "What does MAC stand for in the term MAC address?",
         ["Media Access Control", "Message Authentication Code", "Memory Access Controller", "Medium Address Code"], "A",
         "In LAN addressing, MAC stands for Media Access Control, the sublayer that controls access to the medium."),
        ("BEGINNER", "Which protocol is used to discover the MAC address of a device given its IP address?",
         ["DHCP", "ARP", "DNS", "ICMP"], "B",
         "ARP resolves an IP address to the MAC address of a device on the same subnet."),
        ("BEGINNER", "What is the OUI portion of a MAC address used for?",
         ["Identifying the device's IP", "Identifying the manufacturer", "Encrypting the frame", "Routing the packet"], "C",
         "The first 24 bits of a MAC address, the OUI, identify the device's manufacturer."),
        ("BEGINNER", "Which Data Link layer protocol is the dominant technology for wired LANs?",
         ["PPP", "Token Ring", "Ethernet", "FDDI"], "D",
         "Ethernet is the dominant wired LAN technology, standardized by IEEE 802.3."),
        ("BEGINNER", "What does the Data Link layer add to a packet to create a frame?",
         ["A header and a trailer with a Frame Check Sequence", "Only an IP header", "A checksum in the segment", "Port numbers"], "A",
         "The Data Link layer adds a header and a trailer containing the FCS to form a frame."),
        ("BEGINNER", "Which of the following is a valid unicast MAC address?",
         ["00:1A:2B:3C:4D:5E", "192.168.1.10", "www.example.com", "Port 443"], "B",
         "00:1A:2B:3C:4D:5E is a 48-bit MAC address, while the others are IP, DNS and port identifiers."),
        ("INTERMEDIATE", "A switch receives a frame destined for a MAC address not in its MAC table. What does it do?",
         ["It floods the frame out of all ports except the receiving one", "It drops the frame", "It sends an ARP request", "It forwards it to the router"], "A",
         "For an unknown destination MAC the switch floods the frame to every port except the one it arrived on."),
        ("INTERMEDIATE", "Two stations on the same Ethernet segment transmit at the same moment and a collision occurs. Which mechanism makes them back off and retry?",
         ["CSMA/CA", "CSMA/CD with random backoff", "Token passing", "TDMA"], "B",
         "CSMA/CD detects the collision and has both stations wait a random backoff time before retrying."),
        ("INTERMEDIATE", "What happens to a MAC address table when a frame arrives with a previously unknown source address?",
         ["The entry is ignored", "The table is cleared", "The switch learns the source address and associates it with the ingress port", "The frame is dropped"], "C",
         "The switch dynamically learns the source MAC and records which port it came in on."),
        ("INTERMEDIATE", "A broadcast frame is sent to which destination address?",
         ["The source MAC", "A unicast MAC", "The multicast group address", "FF:FF:FF:FF:FF:FF"], "D",
         "A broadcast frame uses the all-ones address FF:FF:FF:FF:FF:FF so every host processes it."),
        ("INTERMEDIATE", "A laptop wants to send a packet to a host on a different subnet. What MAC address does the Ethernet frame use as its destination?",
         ["The default gateway's MAC address", "The destination host's MAC address", "The DHCP server's MAC", "A broadcast MAC"], "A",
         "Off-subnet traffic is sent to the default gateway's MAC, which then routes the packet onward."),
        ("INTERMEDIATE", "What is the primary difference between a hub and a switch at the Data Link layer?",
         ["A hub is faster", "A hub shares bandwidth with all ports while a switch forwards frames only to the destination port", "A switch broadcasts everything", "A hub learns MAC addresses"], "B",
         "A hub repeats traffic to all ports, while a switch uses its MAC table to forward only to the destination."),
        ("INTERMEDIATE", "In Ethernet, what is the purpose of the FCS (Frame Check Sequence) field?",
         ["To carry routing information", "To hold the source MAC", "To detect bit errors in the frame", "To set the priority"], "C",
         "The FCS is a CRC value that the receiver recomputes to detect transmission errors."),
        ("INTERMEDIATE", "A frame with a corrupted FCS is received by a switch. What does the switch do?",
         ["It repairs the frame", "It forwards it anyway", "It retransmits it", "It drops the frame"], "D",
         "A switch discards frames that fail the FCS check because they are assumed corrupted."),
        ("INTERMEDIATE", "Which mechanism prevents a Layer 2 switching loop in a network with redundant switches?",
         ["STP (Spanning Tree Protocol)", "ARP", "DHCP", "DNS"], "A",
         "Spanning Tree Protocol blocks redundant ports so no forwarding loop can form."),
        ("INTERMEDIATE", "A switch forwards a frame only out of the port where the destination MAC was learned. What is this called?",
         ["Broadcasting", "Unicast forwarding by MAC table lookup", "Flooding", "Half-duplex operation"], "B",
         "When the destination MAC is known, the switch forwards the frame only to that learned port."),
        ("ADVANCED", "A LAN has two switches connected by two cables, creating a loop. Which protocol state places the redundant port into blocking?",
         ["STP putting the port in the blocking state", "ARP resolving the loop", "DHCP avoiding it", "OSPF electing a route"], "A",
         "STP blocks redundant ports while leaving one path active, preventing broadcast storms from loops."),
        ("ADVANCED", "A network admin wants to separate four departments into isolated broadcast domains on one switch. Which feature should be used?",
         ["Router on a stick only", "VLANs with each department assigned its own VLAN", "A single flat network", "NAT"], "B",
         "Assigning each department its own VLAN creates separate broadcast domains on the same switch."),
        ("ADVANCED", "Why does Ethernet's minimum frame size depend on the maximum network diameter?",
         ["To guarantee collision detection within the round-trip time", "To make frames cheaper", "To allow longer cables", "To support more MAC addresses"], "C",
         "The sender must still be transmitting when a collision returns, so the minimum frame size is tied to the round-trip time."),
        ("ADVANCED", "An attacker sends frames with a forged source MAC address to redirect traffic. What is the name of this attack?",
         ["MAC spoofing", "IP spoofing", "DNS poisoning", "TCP hijacking"], "D",
         "MAC spoofing impersonates another device's MAC address to intercept or redirect frames."),
        ("ADVANCED", "A company enables port security on a switch port. What does it prevent?",
         ["Unauthorized devices connecting to an authorized port", "Routing between VLANs", "Broadcast storms", "Duplicate IP addresses"], "A",
         "Port security limits the MAC addresses allowed on a port, blocking unauthorized devices."),
        ("ADVANCED", "Which technique combines multiple physical links between two switches into one logical link for more bandwidth and redundancy?",
         ["EtherChannel / port aggregation", "VLAN trunking", "STP blocking", "MAC filtering"], "B",
         "EtherChannel bundles parallel links into a single logical link that appears as one path."),
        ("ADVANCED", "A VLAN trunk must carry frames from multiple VLANs between switches. Which tagging standard marks which VLAN a frame belongs to?",
         ["IEEE 802.1Q", "IEEE 802.3", "IEEE 802.11", "IEEE 802.1X"], "C",
         "IEEE 802.1Q adds a VLAN tag to frames so trunk links can carry multiple VLANs."),
        ("ADVANCED", "Why would an administrator disable auto-negotiation and force full duplex on both ends of a link?",
         ["To save power", "To fix duplex mismatch problems that auto-negotiation fails to resolve correctly", "To enable broadcast", "To reduce MAC table size"], "D",
         "Forcing the duplex on both ends eliminates the mismatches that auto-negotiation can cause."),
        ("ADVANCED", "When a switch receives a broadcast frame, how does it treat the frame?",
         ["It floods it to all ports except the receiving port", "It drops it", "It sends it to the router only", "It queues it for retry"], "A",
         "Broadcast frames are flooded to every port except the one they arrived on."),
        ("ADVANCED", "What is the benefit of store-and-forward switching over cut-through switching?",
         ["It is always faster", "It validates the FCS and drops corrupted frames before forwarding", "It requires no buffering", "It ignores VLAN tags"], "B",
         "Store-and-forward buffers the whole frame and checks the FCS before forwarding, so bad frames never pass through."),
    ],
    55: [
        ("BEGINNER", "Which technique detects an error by checking whether the number of 1-bits is even or odd?",
         ["Parity checking", "Encryption", "Compression", "Fragmentation"], "A",
         "Parity checking adds a bit that makes the total count of 1s even or odd so errors can be detected."),
        ("BEGINNER", "What does the FCS field in an Ethernet frame do?",
         ["Routes the frame", "Detects transmission errors in the frame", "Encrypts the payload", "Assigns IP addresses"], "B",
         "The FCS stores a checksum that the receiver verifies to detect errors in the frame."),
        ("BEGINNER", "Which of the following is an error detection method?",
         ["Checksum", "Routing", "Switching", "Addressing"], "C",
         "A checksum is a value computed from the data that lets the receiver detect errors."),
        ("BEGINNER", "What is the main difference between error detection and error correction?",
         ["They are the same", "Detection identifies a failure while correction repairs the damaged data", "Correction detects and detection repairs", "Neither exists"], "D",
         "Error detection only reports a failure, while error correction can repair the corrupted data without retransmission."),
        ("BEGINNER", "Which checksum-style technique adds up data units and stores the complement for verification?",
         ["The Internet checksum", "STP", "ARP", "DNS"], "A",
         "The Internet checksum sums 16-bit words and stores the one's complement so receivers can verify the header."),
        ("BEGINNER", "A parity bit is added to a group of bits. What is the parity bit's purpose?",
         ["To increase speed", "To make the total number of 1s even (or odd) so errors can be detected", "To encrypt the data", "To route the data"], "B",
         "The parity bit forces an even (or odd) count of 1s, allowing single-bit errors to be detected."),
        ("BEGINNER", "Which protocol relies on acknowledgements and retransmission when an error is detected?",
         ["UDP", "TCP", "ICMP", "ARP"], "C",
         "TCP uses ACKs and retransmits segments that are lost or fail their checksum."),
        ("BEGINNER", "What happens when a UDP datagram fails its checksum at the receiver?",
         ["The receiver retransmits it", "The receiver requests a resend", "The receiver silently discards it", "The receiver corrects it"], "D",
         "UDP provides no recovery, so a datagram that fails the checksum is simply discarded."),
        ("BEGINNER", "Which method can both detect AND correct single-bit errors?",
         ["Hamming code", "Simple parity", "A checksum", "An ACK timer"], "A",
         "Hamming codes add redundant bits that pinpoint which bit is wrong so it can be corrected."),
        ("BEGINNER", "In CRC (Cyclic Redundancy Check), what is the generator polynomial used for?",
         ["To encrypt frames", "To compute a remainder that detects burst errors in a frame", "To route packets", "To assign MAC addresses"], "B",
         "The generator polynomial is divided into the frame so the remainder reveals transmission errors."),
        ("INTERMEDIATE", "Using even parity, a sender transmits the 7 data bits 1011001. What parity bit should be added?",
         ["0", "1", "2", "3"], "A",
         "The data has four 1s, which is already even, so the parity bit must be 0 to keep the total even."),
        ("INTERMEDIATE", "A receiver using odd parity gets data 1100100 with parity bit 0. An error is detected. Which statement is true?",
         ["The data has an even number of 1s so no error exists", "Odd parity fails because the data has four 1s and the 0 parity bit makes the total even, not odd", "The parity bit is always correct", "The error is corrected automatically"], "B",
         "Four 1s plus a 0 parity bit gives an even total, which violates odd parity, so an error is detected."),
        ("INTERMEDIATE", "Given the two 4-bit chunks 1001 and 0110, what is their bitwise XOR checksum?",
         ["0001", "0111", "1111", "1100"], "C",
         "XORing 1001 and 0110 bit by bit yields 1111, which is the combined checksum value."),
        ("INTERMEDIATE", "A CRC of 16 bits is computed for a frame. How does the receiver verify the frame?",
         ["It re-encrypts the frame", "It divides the received frame plus CRC by the generator polynomial and checks that the remainder is zero", "It compares the IP header", "It asks the sender to resend"], "D",
         "If the division leaves no remainder, the frame is assumed error-free; a nonzero remainder means corruption."),
        ("INTERMEDIATE", "A single parity bit can detect which type of errors?",
         ["Errors affecting an odd number of bits", "Any burst error", "All errors", "Errors affecting an even number of bits"], "A",
         "A parity bit catches only errors that flip an odd number of bits; even-count errors go undetected."),
        ("INTERMEDIATE", "Why is CRC preferred over a simple checksum on Ethernet frames?",
         ["CRC is easier to compute", "CRC reliably detects burst errors, which are common on real links", "CRC is smaller", "CRC can correct errors"], "B",
         "CRC detects multi-bit burst errors effectively, making it stronger than a simple additive checksum."),
        ("INTERMEDIATE", "A Hamming code is designed to correct single-bit errors. What does the receiver do when the calculated syndrome is nonzero?",
         ["It drops the frame", "It requests retransmission", "It flips the bit indicated by the syndrome to correct the error", "It ignores the error"], "C",
         "The syndrome identifies the exact bit position that is wrong, which the receiver flips to correct it."),
        ("INTERMEDIATE", "What is the minimum Hamming distance needed to correct all single-bit errors?",
         ["1", "4", "2", "3"], "D",
         "A Hamming distance of at least 3 is required to correct single-bit errors because 2t+1 with t equal to 1 gives 3."),
        ("INTERMEDIATE", "Which error detection mechanism protects the IPv4 header itself?",
         ["Internet checksum", "CRC", "Parity bit", "Hamming code"], "A",
         "The IPv4 header carries a 16-bit checksum computed over the header so routers can detect corruption."),
        ("INTERMEDIATE", "A TCP receiver's computed checksum does not match the segment. What does it do?",
         ["It corrects the data", "It discards the segment and triggers retransmission", "It forwards anyway", "It increases the window size"], "B",
         "TCP discards corrupt segments and relies on the sender to retransmit them."),
        ("ADVANCED", "A one-way link has a high bit error rate and no retransmission channel. Which scheme is appropriate?",
         ["Forward Error Correction using a code like Hamming or Reed-Solomon", "Increasing the TCP window", "Adding a longer checksum only", "Using higher-layer ARQ"], "A",
         "FEC adds redundancy so the receiver can repair errors locally without asking for retransmission."),
        ("ADVANCED", "For CRC, a generator polynomial written as x^3 + x + 1 corresponds to which binary bit pattern?",
         ["1001", "1011", "1101", "1110"], "B",
         "The polynomial x^3 + x + 1 maps to binary 1011, one bit for each present power term."),
        ("ADVANCED", "A satellite link has 500 ms latency and uses ARQ. Which improvement reduces the cost of retransmission?",
         ["Using a longer cable", "Using go-back-N or selective repeat with a large window", "Removing error detection", "Switching to a hub"], "C",
         "A large sliding window keeps many frames in flight so the sender is not idle while waiting for ACKs."),
        ("ADVANCED", "You must detect corruption of up to 3 consecutive bits in a 32-bit frame. What property must your CRC generator polynomial have?",
         ["It must be prime", "Its degree must be at least 3 so it can detect that burst length, and it must be chosen so the remainder is never zero for a valid frame", "It must be odd", "It must be shorter than the frame"], "D",
         "A CRC detects a burst of length equal to or less than the polynomial's degree, so the degree must cover the burst length."),
        ("ADVANCED", "A data center link has a low error rate and overhead must be minimized. Which approach gives the least overhead?",
         ["A short CRC that only detects errors, relying on upper-layer retransmission", "A Hamming code that corrects every bit", "Reed-Solomon on every frame", "Triple modular redundancy on the wire"], "A",
         "When errors are rare, a cheap detection-only CRC with upper-layer retransmission wastes less bandwidth than heavy FEC."),
        ("ADVANCED", "Why is the Internet checksum a weaker choice than CRC for a noisy link?",
         ["It is slower", "It is a sum-based scheme that can miss systematic errors like transposed 16-bit words, while CRC detects burst errors", "It cannot detect parity errors", "It is longer"], "B",
         "Additive checksums can cancel out in symmetrical corruptions, whereas CRC catches burst errors far more reliably."),
        ("ADVANCED", "In a Hamming code with 4 data bits, how many parity bits are needed to correct single-bit errors?",
         ["2", "3", "4", "1"], "C",
         "The inequality 2^r >= m + r + 1 gives r equal to 3 for m equal to 4, so 3 parity bits are needed."),
        ("ADVANCED", "A protocol uses selective repeat ARQ with a window size of 4. Why is this more efficient than stop-and-wait on a high-latency link?",
         ["It sends no data", "It keeps multiple frames in flight so the sender does not idle while waiting for each ACK", "It reduces the frame size", "It removes the need for CRC"], "D",
         "Keeping several frames in flight uses the link's capacity during the long round-trip time."),
        ("ADVANCED", "Which statement correctly justifies placing CRC at the Data Link layer instead of higher layers?",
         ["Link-layer CRC catches errors before they waste bandwidth and CPU on upper-layer processing", "The Network layer cannot detect errors", "CRC is only used at the Application layer", "Higher layers never detect errors"], "A",
         "Checking at the Data Link layer discards corrupt frames early, saving upper-layer work and bandwidth."),
        ("ADVANCED", "A 10 Gbps link sends 1500-byte frames and one frame in a million is corrupted. If only stop-and-wait ARQ is used, what dominates the performance impact?",
         ["The checksum computation", "The round-trip time stall waiting for retransmission, since only one frame is in flight", "The CRC polynomial degree", "The MAC address length"], "B",
         "Stop-and-wait idles the link for a full round trip on every retransmission, which dominates at high speed."),
    ],
}
