# -*- coding: utf-8 -*-
"""
Question bank for subject 30: WEB105 - Web Technologies & APIs.
Category: Web & Mobile Development.

Topics:
  146: HTTP & REST
  147: JSON & AJAX
  148: Web Storage & Cookies
  149: WebSockets & Real-time
  150: Web Security

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    146: [
        ("BEGINNER", "What does the acronym HTTP stand for?",
         ["Hypertext Transfer Protocol", "Hypertext Terminal Processing", "High Transfer Text Protocol", "Hyperlink Transport Protocol"], "A",
         "HTTP stands for Hypertext Transfer Protocol, the foundation protocol used to request and transfer web resources."),
        ("BEGINNER", "Which HTTP method is used to retrieve a resource from a server?",
         ["POST", "GET", "PUT", "DELETE"], "B",
         "GET is a safe, read-only method designed to fetch a resource without changing server state."),
        ("BEGINNER", "Which HTTP method is commonly used to submit form data that creates a new resource?",
         ["GET", "HEAD", "POST", "TRACE"], "C",
         "POST sends data in the request body and is the standard method for creating or submitting new resources."),
        ("BEGINNER", "What does the status code 404 indicate?",
         ["The request succeeded", "The server had an internal error", "The resource was not found", "The client is unauthorized"], "C",
         "Status code 404 Not Found means the server could not locate the requested resource."),
        ("BEGINNER", "Which status code range represents successful responses?",
         ["100-199", "200-299", "300-399", "400-499"], "B",
         "The 2xx range, starting at 200 OK, signals that the request was received and processed successfully."),
        ("BEGINNER", "Which HTTP method is typically used to update an existing resource?",
         ["GET", "DELETE", "PUT", "POST"], "C",
         "PUT is intended to replace or update a resource at a known URI with the payload provided."),
        ("BEGINNER", "What does the 'REST' in REST API stand for?",
         ["Representational State Transfer", "Remote Event System Transfer", "Resource Entity State Testing", "Representative Server Technology"], "A",
         "REST stands for Representational State Transfer, an architectural style for designing networked APIs."),
        ("BEGINNER", "Which HTTP method removes a resource from the server?",
         ["POST", "PUT", "PATCH", "DELETE"], "D",
         "DELETE is the HTTP method designed to remove the resource identified by the request URI."),
        ("BEGINNER", "What is a URL?",
         ["A type of server software", "A unique address used to locate a resource on the web", "A programming language", "A database format"], "B",
         "A URL (Uniform Resource Locator) uniquely identifies and addresses a web resource."),
        ("BEGINNER", "Which HTTP header is commonly used to send authentication credentials?",
         ["Accept", "Content-Type", "Authorization", "Cache-Control"], "C",
         "The Authorization header carries credentials such as tokens or basic auth data for a request."),
        ("INTERMEDIATE", "A client calls GET /users/42 and receives a JSON object. What best describes this design?",
         ["State-changing RPC", "A RESTful read operation that returns a representation", "A file download", "A session handshake"], "B",
         "GET on a specific resource URI is a read-only REST operation returning that resource's representation."),
        ("INTERMEDIATE", "Which HTTP method should be used to partially update an existing resource?",
         ["PATCH", "PUT", "POST", "DELETE"], "A",
         "PATCH applies a partial modification, unlike PUT which replaces the whole resource."),
        ("INTERMEDIATE", "What does the 201 status code specifically signal?",
         ["The resource was moved", "The resource was created", "The request is invalid", "The server is too busy"], "B",
         "201 Created indicates the request succeeded and a new resource was created as a result."),
        ("INTERMEDIATE", "An API returns 401 to a request with no token. What is the problem?",
         ["The resource does not exist", "The client is not authenticated", "The server crashed", "The request timed out"], "B",
         "401 Unauthorized means the request lacks valid authentication credentials."),
        ("INTERMEDIATE", "Which status code indicates the client was authenticated but lacks permission?",
         ["401", "403", "404", "410"], "C",
         "403 Forbidden means the server understood the request but refuses to authorize it."),
        ("INTERMEDIATE", "A mobile app polls for updates every second. Which HTTP response header should it respect?",
         ["Cache-Control", "Set-Cookie", "Content-Language", "Server"], "A",
         "Cache-Control instructs the client how long a response may be cached, reducing unnecessary requests."),
        ("INTERMEDIATE", "What does it mean when an HTTP response includes the header Location: /orders/7?",
         ["The response body is a redirect target", "The client should request /orders/7 to find the created resource", "The server moved permanently", "The request is forbidden"], "B",
         "The Location header indicates where a newly created resource can be found, commonly used with 201 Created."),
        ("INTERMEDIATE", "Which status code is returned when a request method is not allowed on a URI?",
         ["405", "400", "500", "302"], "A",
         "405 Method Not Allowed is returned when the resource exists but does not support the requested method."),
        ("INTERMEDIATE", "What is the primary purpose of the HTTP HEAD method?",
         ["To delete a resource", "To retrieve headers only, without the body", "To upload a file", "To establish a secure connection"], "B",
         "HEAD behaves like GET but returns only the response headers, which is useful for checking existence or metadata."),
        ("INTERMEDIATE", "In REST, what is an idempotent method?",
         ["A method that always returns an error", "A method whose repeated identical calls have the same effect as a single call", "A method that requires authentication", "A method that changes state on every call"], "B",
         "Idempotent methods such as GET, PUT and DELETE produce the same server state no matter how many times they are repeated."),
        ("ADVANCED", "An API allows DELETE /users/7 to be retried safely without side effects. Which property does this demonstrate?",
         ["Idempotency", "Latency", "Caching", "Session state"], "A",
         "Repeating an idempotent DELETE leaves the server in the same state, making retries safe after timeouts."),
        ("ADVANCED", "Which of these best follows RESTful resource naming conventions?",
         ["/getAllUsers", "/users/7/orders", "/updateUser?id=7", "/createOrder"], "B",
         "RESTful design uses noun-based hierarchical URIs such as /users/7/orders to represent related resources."),
        ("ADVANCED", "A developer returns HTTP 200 with an error object in the body when validation fails. Why is this a poor design?",
         ["It is faster than 400", "It hides the failure from clients and monitoring tools that rely on status codes", "It makes the server stateful", "It prevents caching entirely"], "B",
         "Using 200 for failures defeats status-code signalling, making errors harder to detect and handle programmatically."),
        ("ADVANCED", "Which HTTP mechanism allows a client to retry a failed request and avoid creating duplicate orders?",
         ["Idempotency keys sent in headers", "Changing GET to POST", "Increasing the timeout", "Disabling compression"], "A",
         "An idempotency key lets the server recognize and deduplicate repeated POST attempts for the same logical operation."),
        ("ADVANCED", "What does the 429 status code indicate and what header should the server send with it?",
         ["A server crash, Retry-After", "Rate limiting exceeded, Retry-After", "Resource not found, Cache-Control", "Bad request, Location"], "B",
         "429 Too Many Requests signals rate limiting and Retry-After tells the client when it may try again."),
        ("ADVANCED", "What is the difference between PUT and PATCH?",
         ["PUT is always unsafe and PATCH is safe", "PUT replaces the entire resource while PATCH applies a partial update", "PATCH replaces the entire resource while PUT applies a partial update", "They are identical in every framework"], "B",
         "PUT sends a complete replacement representation while PATCH sends only the fields to be changed."),
        ("ADVANCED", "Which strategy best improves the performance of a chat API that clients poll every 5 seconds?",
         ["Returning 404 for empty polls", "Using long polling, SSE, or WebSockets instead of frequent polling", "Making GET requests idempotent", "Adding more query parameters"], "B",
         "Long polling or push technologies avoid wasteful repeated requests by delivering updates as they occur."),
        ("ADVANCED", "Which HTTP cache-control directive prevents any intermediate cache from storing a response?",
         ["no-store", "no-transform", "max-age=0", "must-revalidate"], "A",
         "no-store tells caches not to persist the response at all, which is essential for sensitive data."),
        ("ADVANCED", "When designing versioned REST APIs, which approach is generally recommended?",
         ["Changing resource semantics in place", "Adding the version in the URI such as /v1/users", "Returning a random error", "Deleting old endpoints immediately"], "B",
         "URI versioning such as /v1/users lets older clients keep working while new versions are introduced."),
        ("ADVANCED", "An API exposes /orders and /orders/{id}. Which HTTP method pairs are the most RESTful for list and detail views?",
         ["GET on both, plus POST and PUT", "POST for list and DELETE for detail", "HEAD only", "Any method works equally"], "A",
         "GET lists resources, POST creates, and GET with an id retrieves or PUT/PATCH updates a single resource."),
    ],
    147: [
        ("BEGINNER", "What does JSON stand for?",
         ["JavaScript Object Notation", "Java Standard Object Names", "JavaScript Output Network", "JQuery Serialized Object Naming"], "A",
         "JSON stands for JavaScript Object Notation, a lightweight text format for data interchange."),
        ("BEGINNER", "Which of the following is valid JSON?",
         ["{'name': 'Ada'}", "{'name': \"Ada\"}", "{\"name\": \"Ada\"}", "{name: \"Ada\"}"], "C",
         "JSON requires double-quoted property names and string values, so {\"name\": \"Ada\"} is valid."),
        ("BEGINNER", "What does the JavaScript method JSON.parse do?",
         ["Turns an object into a string", "Converts a JSON string into a JavaScript value", "Sends a request to a server", "Encodes data as base64"], "B",
         "JSON.parse converts a valid JSON string into its corresponding JavaScript object or value."),
        ("BEGINNER", "What does the JavaScript method JSON.stringify do?",
         ["Converts a JavaScript value into a JSON string", "Parses a JSON string", "Compresses an object", "Validates form input"], "A",
         "JSON.stringify serializes a JavaScript value into a JSON-formatted string for transmission or storage."),
        ("BEGINNER", "What does AJAX stand for?",
         ["Asynchronous JavaScript and XML", "Active Java Application eXchange", "Automatic JSON and XML", "Asynchronous JSON and XML"], "A",
         "AJAX stands for Asynchronous JavaScript and XML, a technique for updating pages without full reloads."),
        ("BEGINNER", "Which JavaScript object is used to make an HTTP request?",
         ["XMLHttpRequest", "JSONParser", "Document", "HTMLElement"], "B",
         "XMLHttpRequest is the traditional browser object used to perform asynchronous HTTP requests."),
        ("BEGINNER", "Which newer fetch-based API is commonly used for AJAX requests in modern JavaScript?",
         ["fetch()", "request()", "retrieve()", "transfer()"], "A",
         "fetch() is the modern promise-based API for making network requests in the browser."),
        ("BEGINNER", "Which MIME type should a server set for JSON responses?",
         ["text/html", "application/json", "text/plain", "image/png"], "B",
         "application/json is the correct MIME type signalling that the response body is JSON."),
        ("BEGINNER", "In JSON, how are arrays represented?",
         ["With parentheses ()", "With angle brackets <>", "With square brackets []", "With curly braces {}"], "C",
         "JSON arrays are ordered lists enclosed in square brackets, such as [1, 2, 3]."),
        ("BEGINNER", "Which property of AJAX means the page continues responding while a request is in flight?",
         ["Synchronous", "Asynchronous", "Idempotent", "Serialized"], "B",
         "Asynchronous execution lets JavaScript keep running and handle the response later instead of blocking."),
        ("INTERMEDIATE", "What does JSON.parse('{\"a\":1}') return in JavaScript?",
         ["A string", "An object with property a equal to 1", "An array", "null"], "B",
         "JSON.parse builds a real JavaScript object, so the result has a numeric property a of 1."),
        ("INTERMEDIATE", "What happens when JSON.parse is called on the string '{\"a\":}'?",
         ["Returns null", "Returns an empty object", "Throws a SyntaxError because the JSON is invalid", "Returns undefined"], "C",
         "A missing value after the colon is invalid JSON, so JSON.parse throws a SyntaxError."),
        ("INTERMEDIATE", "What is the difference between XMLHttpRequest with async true and async false?",
         ["No difference", "async true is blocking, false is non-blocking", "async true is non-blocking, false blocks the page until completion", "async controls compression"], "C",
         "async true lets the page continue working, while async false freezes script execution until the response arrives."),
        ("INTERMEDIATE", "In a fetch chain, which method converts the response body into a JSON object?",
         ["response.text()", "response.json()", "response.parse()", "response.format()"], "B",
         "response.json() reads the body stream and parses it as JSON, returning a promise of the resulting value."),
        ("INTERMEDIATE", "How do you check whether a fetch request succeeded with status 200-299?",
         ["Using response.ok", "Checking response.url", "Using response.type", "Comparing response.headers"], "A",
         "response.ok is true whenever the HTTP status is in the successful 200-299 range."),
        ("INTERMEDIATE", "What is a common cause of JSON.parse throwing while fetching data?",
         ["The server returned non-JSON, such as an HTML error page", "The connection was too slow", "The data was too large", "The browser is offline"], "A",
         "If the server returns an HTML error page instead of JSON, parsing it throws a SyntaxError."),
        ("INTERMEDIATE", "How does jQuery's $.ajax with dataType 'json' differ from a plain GET?",
         ["It automatically parses the JSON response into a JavaScript object", "It always uses POST", "It disables caching", "It returns a string always"], "A",
         "jQuery inspects the dataType setting and automatically parses the response body into an object."),
        ("INTERMEDIATE", "What does CORS stand for and why is it relevant to AJAX?",
         ["Cross-Origin Resource Sharing, which governs browser requests between origins", "Common Origin Request System", "Central Online Resource Service", "Cross-Opening Response Standard"], "A",
         "CORS is a browser security mechanism that controls whether scripts on one origin may fetch resources from another."),
        ("INTERMEDIATE", "Which of these is the correct JSON representation of a list of names?",
         ["[\"Ana\", \"Ben\", \"Cara\"]", "{\"Ana\", \"Ben\", \"Cara\"}", "(\"Ana\", \"Ben\", \"Cara\")", "\"Ana\", \"Ben\", \"Cara\""], "A",
         "A JSON array of strings uses square brackets with each value double-quoted and comma-separated."),
        ("INTERMEDIATE", "What does fetch('url').then(r => r.json()) accomplish?",
         ["Sends the body as JSON", "Fetches the URL and parses the JSON response", "Compresses the response", "Cancels the request"], "B",
         "fetch starts the request and the .json() call parses the resolved response body into a JavaScript value."),
        ("ADVANCED", "A fetch to another origin fails in the browser even though curl works. What is the most likely cause?",
         ["The server lacks CORS headers for browser requests", "The URL has a typo", "The client is offline", "HTTP is disabled"], "A",
         "Browsers enforce CORS, so without the correct Access-Control-Allow-Origin header the response is blocked."),
        ("ADVANCED", "What happens to a fetch promise when the server responds with status 500?",
         ["It rejects immediately", "It resolves because the request completed; the caller must check response.ok", "It retries automatically", "It returns null"], "B",
         "fetch only rejects on network failure, so an HTTP 500 still resolves and the caller must inspect the status."),
        ("ADVANCED", "Which header must the server send for a browser to allow a cross-origin POST with Content-Type application/json?",
         ["Access-Control-Allow-Origin", "Set-Cookie", "Retry-After", "X-Requested-With"], "A",
         "Access-Control-Allow-Origin authorizes the browser to expose the response to the requesting origin."),
        ("ADVANCED", "Why do many APIs use JSON over XML?",
         ["JSON is smaller and easier to parse in JavaScript", "XML is faster to transmit", "JSON requires more libraries", "XML is more secure by default"], "A",
         "JSON's compact syntax and native JavaScript parsing make it lighter and simpler than XML for most APIs."),
        ("ADVANCED", "What is the difference between JSON.stringify on an object containing a function and one without?",
         ["Functions are serialized normally", "Functions are omitted because JSON has no function type", "Functions become strings", "The object becomes null"], "B",
         "JSON has no function representation, so JSON.stringify silently drops function properties."),
        ("ADVANCED", "Which server-side technique lets a long AJAX request appear to 'hang' until new data arrives?",
         ["Long polling", "Synchronous XMLHttpRequest", "Cookie flashing", "Document fragments"], "A",
         "Long polling keeps the connection open until the server has new data to send, then immediately reopens it."),
        ("ADVANCED", "How should a page gracefully degrade when JSON.parse of a fetched response fails?",
         ["Let the error propagate uncaught", "Wrap parsing in a try/catch and show a fallback message or state", "Reload the page", "Return 500 to the user"], "B",
         "Catching the parse error and showing fallback UI keeps the application usable when data is malformed."),
        ("ADVANCED", "What is the primary benefit of sending JSON over a compact binary protocol like Protocol Buffers?",
         ["Binary is always safer", "JSON is human-readable and works everywhere without a schema step", "Binary cannot be cached", "JSON transfers faster in all cases"], "B",
         "JSON's human-readable format and universal support trade size for simplicity and debuggability."),
        ("ADVANCED", "When uploading a large file via AJAX, which object reports upload progress?",
         ["XMLHttpRequest.upload", "document.readyState", "navigator.onLine", "history.state"], "A",
         "XMLHttpRequest.upload exposes progress events so the UI can show upload completion percentages."),
        ("ADVANCED", "Which pattern sends a fallback request when a cross-origin JSONP-style callback would be blocked?",
         ["Using fetch with CORS headers negotiated by the server", "Increasing the timeout", "Switching to FTP", "Disabling JavaScript"], "A",
         "Proper CORS support from the server is the modern replacement for workarounds like JSONP callbacks."),
    ],
    148: [
        ("BEGINNER", "What is a cookie in web development?",
         ["A small piece of data stored in the browser by a website", "A hardware device", "A type of database", "A server log file"], "A",
         "A cookie is a small text record that a server stores in the browser, associated with that domain."),
        ("BEGINNER", "Which web API stores key-value data with no expiration in the browser?",
         ["sessionStorage", "localStorage", "cookies", "indexedDB"], "B",
         "localStorage persists data indefinitely until it is explicitly removed by script or the user."),
        ("BEGINNER", "Which web API stores data for the lifetime of a single browser tab?",
         ["localStorage", "sessionStorage", "Service Worker", "WebSQL"], "B",
         "sessionStorage scopes data to one tab and clears it when that tab closes."),
        ("BEGINNER", "Which HTTP header is used to send a cookie back to the server?",
         ["Set-Cookie", "Cookie", "Authorization", "Accept-Language"], "B",
         "The Cookie request header carries stored cookie values back to the server on subsequent requests."),
        ("BEGINNER", "Which HTTP header is used by the server to store a cookie in the browser?",
         ["Set-Cookie", "Cookie", "Location", "Content-Disposition"], "A",
         "The server sends Set-Cookie in its response to instruct the browser to store the cookie."),
        ("BEGINNER", "What is the approximate default storage limit for localStorage in modern browsers?",
         ["About 1 KB", "About 5-10 MB", "About 1 GB", "Unlimited"], "B",
         "Most browsers cap localStorage at roughly 5-10 MB per origin."),
        ("BEGINNER", "Which of the following data is best suited for localStorage?",
         ["The user's session token", "Passwords", "Small non-sensitive preferences", "Server database backups"], "C",
         "localStorage is appropriate for small, non-sensitive preferences because it is accessible to any script on the origin."),
        ("BEGINNER", "What does the JavaScript statement localStorage.setItem('theme', 'dark') do?",
         ["Deletes the theme key", "Stores the value dark under the key theme", "Sends theme to the server", "Creates a cookie"], "B",
         "setItem stores a string value under the given key in localStorage."),
        ("BEGINNER", "Which JavaScript call retrieves the value stored under a localStorage key?",
         ["localStorage.getItem('theme')", "localStorage.getValue('theme')", "localStorage.fetch('theme')", "localStorage.read('theme')"], "A",
         "getItem returns the string stored for the given key, or null if the key does not exist."),
        ("BEGINNER", "What happens to cookies when the user closes the browser?",
         ["All cookies always remain", "Session cookies are usually deleted, but cookies with an Expires or Max-Age may persist", "Cookies move to the server", "Cookies double in size"], "B",
         "Session-only cookies die with the session, while persistent cookies survive because they carry an expiry."),
        ("INTERMEDIATE", "How much data can a single cookie typically hold?",
         ["About 4 KB", "About 5 MB", "About 64 KB", "Unlimited"], "A",
         "Individual cookies are limited to roughly 4 KB, far less than localStorage."),
        ("INTERMEDIATE", "What happens when localStorage is accessed in a private or incognito browsing mode?",
         ["It always works normally", "It may throw a SecurityError or fail to persist", "It stores data on the server", "It converts data to cookies"], "B",
         "Some browsers restrict storage in private mode, causing access attempts to throw or silently not persist."),
        ("INTERMEDIATE", "Why is a session token safer in an HttpOnly cookie than in localStorage?",
         ["HttpOnly cookies cannot be read by JavaScript, reducing XSS theft", "Cookies are encrypted by default", "localStorage is server-side", "HttpOnly cookies never expire"], "A",
         "An HttpOnly cookie is invisible to document.cookie and script, so stolen-script attacks cannot read the token."),
        ("INTERMEDIATE", "Which attribute of a cookie restricts it to HTTPS connections only?",
         ["Secure", "Domain", "Path", "SameSite"], "A",
         "The Secure attribute makes the browser send the cookie only over encrypted HTTPS connections."),
        ("INTERMEDIATE", "Which cookie attribute limits the cookie to a specific URL path?",
         ["Max-Age", "Path", "Priority", "Domain"], "B",
         "The Path attribute restricts the cookie so it is only sent for requests under that path."),
        ("INTERMEDIATE", "What does the cookie attribute SameSite=Lax prevent?",
         ["Cross-site requests sending the cookie except for top-level navigation", "All cookie storage", "Secure-only transmission", "JavaScript reading cookies"], "A",
         "SameSite=Lax blocks the cookie on cross-site subrequests while still allowing top-level navigations."),
        ("INTERMEDIATE", "In what order should localStorage and sessionStorage be used for the same data?",
         ["They share the same storage and cannot both be used", "sessionStorage for tab-local data, localStorage for data that should survive tab closing", "localStorage always, sessionStorage never", "sessionStorage always, localStorage never"], "B",
         "Choose sessionStorage when data belongs to one tab and localStorage when data should persist across sessions."),
        ("INTERMEDIATE", "What does the Size QuotaExceededError signal?",
         ["The server is full", "The browser storage quota has been exceeded", "The page is too large", "A network error"], "B",
         "QuotaExceededError is thrown when writing would push the origin past its storage limit."),
        ("INTERMEDIATE", "What happens to a cookie with both Expires and Max-Age attributes?",
         ["Expires wins in all browsers", "Max-Age takes precedence where supported", "Both are ignored", "The browser crashes"], "B",
         "The Max-Age attribute takes precedence over Expires in browsers that support it."),
        ("INTERMEDIATE", "How can a website read a cookie set for a parent domain like example.com from sub.example.com?",
         ["It cannot be done", "By setting the cookie Domain attribute to example.com", "By using localStorage", "By setting HttpOnly"], "B",
         "A cookie with Domain=example.com is shared across all subdomains including sub.example.com."),
        ("ADVANCED", "Why is storing sensitive data like passwords in localStorage considered risky?",
         ["localStorage is server-side", "Any script running on the origin can read it, and it survives until explicitly removed", "localStorage encrypts data", "localStorage expires every hour"], "B",
         "localStorage is readable by any script on the origin and persists, so a single XSS can exfiltrate it."),
        ("ADVANCED", "Which cookie flag protects against CSRF attacks by restricting cross-site sending?",
         ["HttpOnly", "SameSite", "Max-Age", "Domain"], "B",
         "SameSite prevents the browser from sending the cookie on cross-site requests, blocking many CSRF attacks."),
        ("ADVANCED", "What is the difference between the Path and Domain cookie attributes?",
         ["Domain controls which hosts receive the cookie, Path controls which URL prefixes", "They are identical", "Path controls hosts, Domain controls URLs", "Both are deprecated"], "A",
         "Domain restricts the cookie to a host or subdomains, while Path restricts it to URL prefixes on that host."),
        ("ADVANCED", "A multi-tab application needs shared real-time state that survives reloads. Which option is best?",
         ["sessionStorage", "localStorage combined with storage events", "An in-memory variable", "A hidden input field"], "B",
         "localStorage plus the 'storage' event synchronizes values across tabs and survives page reloads."),
        ("ADVANCED", "What does the 'storage' event fire and where?",
         ["In all other tabs of the same origin when localStorage changes", "In the tab that made the change", "On the server", "In the console only"], "A",
         "The storage event fires in other tabs/windows of the same origin, letting them react to the change."),
        ("ADVANCED", "Which attribute must a cookie have to be inaccessible to document.cookie?",
         ["Secure", "HttpOnly", "SameSite", "Path=/"], "B",
         "HttpOnly removes the cookie from the JavaScript cookie view, protecting it from XSS reads."),
        ("ADVANCED", "What is the primary trade-off between cookies and localStorage for storing small data?",
         ["Cookies are larger", "Cookies are sent with every HTTP request, increasing traffic, while localStorage stays on the client", "localStorage is sent with every request", "They are identical"], "B",
         "Every cookie is transmitted on each request to its domain, so localStorage avoids that overhead for client-only data."),
        ("ADVANCED", "What is the danger of using JSON.parse directly on data read from localStorage?",
         ["Malformed or tampered data can throw or produce unexpected values", "localStorage stores binary only", "It is always safe", "The parse happens on the server"], "A",
         "localStorage data is user-modifiable, so parsing untrusted JSON requires validation and error handling."),
        ("ADVANCED", "Which cookie flag is most effective at blocking third-party tracking across sites?",
         ["HttpOnly", "Secure", "SameSite=Strict", "Max-Age=0"], "C",
         "SameSite=Strict stops the cookie from being sent on any cross-site request, limiting cross-site tracking."),
        ("ADVANCED", "To invalidate a session on logout, what is the correct cookie approach?",
         ["Set the cookie value to the same token", "Set Max-Age=0 or an Expires in the past so the browser deletes it", "Remove the Domain attribute", "Increase the Path value"], "B",
         "Expiring the cookie immediately, with Max-Age=0 or a past Expires, removes it from the browser."),
    ],
    149: [
        ("BEGINNER", "What is a WebSocket?",
         ["A full-duplex communication channel over a single TCP connection", "A type of HTTP request", "A database protocol", "A CSS framework"], "A",
         "WebSockets provide a persistent, full-duplex channel where both client and server can send messages anytime."),
        ("BEGINNER", "Which protocol does a WebSocket URL beginning with wss:// use?",
         ["Plain HTTP", "A secure TCP connection with TLS", "FTP", "SMTP"], "B",
         "wss:// is the secure WebSocket scheme, using TLS encryption over the underlying TCP connection."),
        ("BEGINNER", "How does WebSocket communication compare with HTTP?",
         ["Both close after one response", "WebSocket keeps the connection open for two-way exchange, unlike request-response HTTP", "HTTP is full-duplex", "WebSocket only sends one message"], "B",
         "HTTP follows a request-response cycle, while WebSockets hold an open bidirectional channel."),
        ("BEGINNER", "Which JavaScript API creates a WebSocket connection?",
         ["new WebSocket(url)", "new Socket(url)", "connect(url)", "fetchSocket(url)"], "A",
         "The WebSocket constructor, new WebSocket(url), opens a connection to the given endpoint."),
        ("BEGINNER", "What does the abbreviation SSE stand for in web real-time technology?",
         ["Server-Sent Events", "Secure Socket Exchange", "Serialized Stream Engine", "Server State Extension"], "A",
         "SSE stands for Server-Sent Events, a one-way push channel from server to client over HTTP."),
        ("BEGINNER", "Which direction of communication does Server-Sent Events support?",
         ["Bidirectional", "Server-to-client only", "Client-to-server only", "Neither direction"], "B",
         "SSE pushes data from server to client; the client cannot stream messages back over the same channel."),
        ("BEGINNER", "Which built-in JavaScript object is used with Server-Sent Events?",
         ["EventSource", "WebSocket", "XMLHttpRequest", "Worker"], "A",
         "EventSource is the browser API that listens to an SSE stream pushed by the server."),
        ("BEGINNER", "What protocol does SSE use for its underlying connection?",
         ["A custom binary protocol", "Standard HTTP", "SMTP", "UDP"], "B",
         "SSE runs over ordinary HTTP, making it simple to deploy and compatible with existing proxies."),
        ("BEGINNER", "Which HTTP upgrade request header is used to initiate a WebSocket handshake?",
         ["Upgrade", "Sec-WebSocket-Key", "Connection", "Accept"], "C",
         "The Upgrade header tells the server to switch protocols, along with a 101 Switching Protocols response."),
        ("BEGINNER", "What response status code completes a successful WebSocket handshake?",
         ["200", "101", "301", "404"], "B",
         "Status 101 Switching Protocols confirms the connection is being upgraded to WebSocket."),
        ("INTERMEDIATE", "Which method sends a message over an open WebSocket connection?",
         ["socket.send('hi')", "socket.write('hi')", "socket.emit('hi')", "socket.post('hi')"], "A",
         "WebSocket's send() transmits a text or binary message to the server once the connection is open."),
        ("INTERMEDIATE", "What does the WebSocket event open represent?",
         ["The connection failed", "The handshake completed and messages can be exchanged", "The server closed the socket", "A message was received"], "B",
         "The open event fires when the handshake finishes, marking the connection ready for use."),
        ("INTERMEDIATE", "How can the client know when the server closed a WebSocket connection?",
         ["The close event", "The error event", "The message event", "The open event"], "A",
         "The close event fires whenever the connection terminates, whether initiated by either side."),
        ("INTERMEDIATE", "Which of the following is a typical use case for WebSockets?",
         ["A live chat application", "A static documentation page", "A one-time form submission", "A plain image gallery"], "A",
         "Live chat needs low-latency two-way updates, which is exactly what WebSockets provide."),
        ("INTERMEDIATE", "What content type must a server stream for Server-Sent Events?",
         ["text/event-stream", "application/json", "text/html", "image/gif"], "A",
         "The SSE response uses the text/event-stream content type to signal the event stream format."),
        ("INTERMEDIATE", "What happens if a WebSocket connection drops on a flaky network?",
         ["The connection never reconnects", "The browser fires close and the app must reconnect", "Data is silently lost", "The server restarts"], "B",
         "The close event fires and the application is responsible for reconnecting and resynchronizing state."),
        ("INTERMEDIATE", "What is a heartbeat in a WebSocket application?",
         ["A periodic ping message to detect dead connections", "A chat emoji", "A CSS animation", "A database backup"], "A",
         "Heartbeats send periodic small messages so either side can detect when a connection has silently died."),
        ("INTERMEDIATE", "Why is a single WebSocket better than polling for a stock ticker?",
         ["WebSocket is slower", "It pushes updates instantly with no repeated request overhead", "It uses less CPU on the server", "It is more secure"], "B",
         "A persistent socket delivers updates as they happen, avoiding the latency and traffic of repeated polls."),
        ("INTERMEDIATE", "Which scenario best fits Server-Sent Events over WebSockets?",
         ["A bidirectional game", "One-way notification feeds like news tickers or activity streams", "File uploads", "Database queries"], "B",
         "SSE is ideal for one-way server pushes such as notifications, where client-to-server traffic is minimal."),
        ("INTERMEDIATE", "How do WebSocket frames differ from full HTTP messages?",
         ["Frames are lightweight messages over a persistent connection instead of full request-response cycles", "Frames are larger", "Frames replace the TCP layer", "Frames are unencrypted"], "A",
         "WebSocket messages travel as small frames over one open connection, avoiding HTTP header overhead per message."),
        ("ADVANCED", "A chat app's WebSocket server crashes mid-session. What must the client implement?",
         ["Reconnection with a resume or resync strategy", "Nothing, the connection recovers itself", "A full page reload", "A DNS change"], "A",
         "Clients should auto-reconnect and reconcile missed messages to stay consistent after server outages."),
        ("ADVANCED", "Why might a company choose SSE over WebSockets for a notification feed?",
         ["SSE is full-duplex and faster", "SSE reconnects automatically via HTTP and works through more proxies", "SSE supports binary uploads", "SSE does not need a server"], "B",
         "SSE has built-in auto-reconnection over ordinary HTTP, which works with far more infrastructure than WebSockets."),
        ("ADVANCED", "What is a common scaling challenge when many WebSocket connections share one server?",
         ["Each open socket holds a persistent connection, so memory and connections grow per user", "CPU never grows", "Disks fill with logs", "TLS is disabled"], "A",
         "Persistent connections consume server resources per socket, requiring careful load balancing and sticky sessions."),
        ("ADVANCED", "Which strategy handles a WebSocket flood of messages overwhelming a client's UI?",
         ["Rendering every message as fast as possible", "Batching and throttling UI updates or applying backpressure", "Closing the socket", "Ignoring all messages"], "B",
         "Throttling or batching prevents layout thrash and keeps the interface responsive under high message rates."),
        ("ADVANCED", "In a multi-server WebSocket deployment, how should a message be routed to a specific connected user?",
         ["A shared pub/sub layer such as Redis broadcasts or routes to the server owning that socket", "Each server holds all sockets", "The database sends the message", "Polling every server"], "A",
         "A pub/sub broker lets any server publish messages that reach the server currently holding the target connection."),
        ("ADVANCED", "What is the main reason WebSockets and SSE are typically preferred over long polling today?",
         ["Long polling reconnects more often and uses more overhead for each update", "Long polling is full-duplex", "Long polling is secure by default", "Long polling has no latency"], "A",
         "Long polling opens a fresh request for every update, while sockets and SSE maintain one efficient connection."),
        ("ADVANCED", "How does backpressure work when a server sends messages faster than the client can process them?",
         ["The server pauses or buffers until the client catches up", "Messages are dropped silently", "The socket reopens", "The client restarts"], "A",
         "Applying backpressure lets the sender slow down, preventing memory exhaustion and data loss."),
        ("ADVANCED", "Which option correctly secures a WebSocket connection?",
         ["Always use wss:// with TLS and validate origins", "Using ws:// over HTTP", "Sending passwords in the URL", "Disabling heartbeat"], "A",
         "TLS (wss://) encrypts frames and origin checks prevent cross-site hijacking of sockets."),
        ("ADVANCED", "What is the typical maximum practical message size to send over a WebSocket in one frame?",
         ["No limit at all", "A few MB at most, with large payloads chunked or streamed", "50 bytes", "Exactly 1 GB"], "B",
         "Very large single messages can stall the connection, so chunks and streams are used for big payloads."),
        ("ADVANCED", "What does an event ID in an SSE stream enable?",
         ["The client to resume from the last processed event after a reconnect", "The server to reject events", "Encryption of events", "Compression of events"], "A",
         "Last-Event-ID lets a reconnecting client tell the server which event it last received so nothing is missed."),
    ],
    150: [
        ("BEGINNER", "What does XSS stand for?",
         ["Cross-Site Scripting", "Extra Secure System", "XML Site Syntax", "Cross-Site Sending"], "A",
         "XSS stands for Cross-Site Scripting, an attack that injects malicious scripts into web pages."),
        ("BEGINNER", "Which attack tricks a user into executing unwanted actions on a site where they are authenticated?",
         ["CSRF", "SQL injection", "Phishing via email", "Denial of service"], "B",
         "CSRF (Cross-Site Request Forgery) forges requests so the victim's browser performs actions they did not intend."),
        ("BEGINNER", "What is the purpose of HTTPS?",
         ["To make pages load faster", "To encrypt traffic between the browser and server", "To store cookies", "To compress images"], "B",
         "HTTPS uses TLS to encrypt data in transit, protecting it from eavesdropping and tampering."),
        ("BEGINNER", "Which type of attack targets database queries by injecting malicious input?",
         ["SQL injection", "XSS", "CSRF", "Phishing"], "C",
         "SQL injection occurs when user input is placed directly into SQL queries without sanitization."),
        ("BEGINNER", "What is CORS in the context of web security?",
         ["A mechanism controlling cross-origin resource access in browsers", "A database engine", "A CSS layout technique", "A password manager"], "A",
         "CORS (Cross-Origin Resource Sharing) governs which origins a browser allows a page to access."),
        ("BEGINNER", "What does 'sanitizing' user input mean?",
         ["Cleaning and validating input to remove dangerous content", "Encrypting the input", "Compressing the input", "Sending input to the server"], "A",
         "Sanitization strips or escapes dangerous characters so the input cannot inject scripts or SQL."),
        ("BEGINNER", "Which of the following is a strong password characteristic?",
         ["Using only your birth year", "Being short and easy to remember", "A long mix of letters, numbers and symbols", "Using the word password"], "C",
         "Length and variety make passwords hard to guess, especially when combined with other measures."),
        ("BEGINNER", "What is the primary purpose of input validation?",
         ["Rejecting data that does not meet expected rules before it is used", "Making the page prettier", "Speeding up the server", "Reducing the number of files"], "A",
         "Validation ensures incoming data matches expected formats and ranges, preventing malformed or malicious values."),
        ("BEGINNER", "Which HTTP response header is used by a server to allow a specific origin?",
         ["Access-Control-Allow-Origin", "Set-Cookie", "Content-Type", "Location"], "A",
         "Access-Control-Allow-Origin tells the browser which origin is permitted to read the response."),
        ("BEGINNER", "What is a security vulnerability?",
         ["A weakness in a system that can be exploited", "A type of virus", "A performance improvement", "A programming language"], "A",
         "A vulnerability is any flaw an attacker can exploit to compromise a system."),
        ("INTERMEDIATE", "A page inserts user comments directly into HTML with innerHTML. What attack is it vulnerable to?",
         ["SQL injection", "Stored XSS", "CSRF", "DNS rebinding"], "B",
         "Persisting unescaped user HTML leads to stored XSS because any viewer's browser executes the injected script."),
        ("INTERMEDIATE", "Which encoding strategy defeats XSS when inserting text into HTML?",
         ["HTML-escaping characters like < and > before output", "Using innerHTML", "Upper-casing the input", "Sending it to the console"], "A",
         "Escaping angle brackets and quotes prevents injected content from being treated as markup."),
        ("INTERMEDIATE", "How does a CSRF token protect a form?",
         ["The server validates a per-session unpredictable token included in the request", "The token hides the form", "The token compresses data", "The token speeds up the request"], "A",
         "A unique per-session token proves the request came from the real form, since attackers cannot guess it."),
        ("INTERMEDIATE", "What does SameSite=Strict do on a cookie?",
         ["It blocks the cookie from being sent on cross-site requests", "It makes the cookie bigger", "It encrypts the cookie", "It deletes the cookie"], "A",
         "SameSite=Strict prevents the browser from sending the cookie on any cross-site request, blocking CSRF."),
        ("INTERMEDIATE", "What does SQL injection 'SELECT * FROM users WHERE id = 1 OR 1=1' demonstrate?",
         ["The query returns all users because the condition is always true", "The query fails with a syntax error", "The database shuts down", "The query is optimized"], "A",
         "OR 1=1 makes the WHERE clause always true, returning every row when input is concatenated unsafely."),
        ("INTERMEDIATE", "What is the correct mitigation for SQL injection?",
         ["Parameterized queries or prepared statements", "Escaping the entire query", "Using more indexes", "Disabling the database"], "A",
         "Parameterized statements separate data from SQL structure, so injected text cannot change the query."),
        ("INTERMEDIATE", "Which Content Security Policy goal directly mitigates XSS?",
         ["Restricting which scripts a page may load and execute", "Speeding up page loads", "Compressing images", "Caching fonts"], "A",
         "CSP blocks inline and untrusted scripts, so injected script tags fail to execute."),
        ("INTERMEDIATE", "What does the HTTP Strict Transport Security header enforce?",
         ["Browsers only connect to the site over HTTPS", "Cookies are deleted", "JavaScript is disabled", "Forms are encrypted"], "A",
         "HSTS tells browsers to use HTTPS exclusively, preventing downgrade attacks."),
        ("INTERMEDIATE", "What is the risk of allowing a page to be embedded in any site's iframe?",
         ["Clickjacking, where attackers overlay UI to trick clicks", "Faster loading", "Better SEO", "Stronger encryption"], "A",
         "Without X-Frame-Options or CSP frame-ancestors, attackers can iframe the page and trick users into clicks."),
        ("INTERMEDIATE", "Which header helps prevent MIME-sniffing attacks?",
         ["X-Content-Type-Options: nosniff", "Set-Cookie", "Server", "Accept-Encoding"], "A",
         "nosniff tells browsers to honor declared MIME types instead of guessing, blocking some content confusion."),
        ("ADVANCED", "An authenticated bank form lacks a CSRF token and uses no SameSite cookie. What single mitigation is most effective?",
         ["Adding a per-session CSRF token or SameSite=Strict cookie", "Adding more colors to the form", "Renaming the submit button", "Increasing the timeout"], "A",
         "A per-session token or a strict SameSite cookie prevents forged cross-site submissions."),
        ("ADVANCED", "Why does output encoding alone not fully protect against XSS in all contexts?",
         ["Contexts like attribute values, URLs and JSON require different encoding rules", "Encoding slows the server", "Encoding deletes data", "Encoding only works on GET requests"], "A",
         "Each injection context needs its own escaping, so one universal encoding can miss attribute or URL sinks."),
        ("ADVANCED", "What is the difference between reflected and stored XSS?",
         ["Stored XSS persists on the server and affects all viewers, reflected only triggers when crafted input is used", "They are identical", "Reflected XSS is stored in the database", "Stored XSS never executes"], "A",
         "Reflected XSS bounces input back in one response, while stored XSS is saved and served to many users later."),
        ("ADVANCED", "A developer disables CORS checks and sets Access-Control-Allow-Origin: * with credentials. What is the danger?",
         ["Any origin could read credentialed responses, enabling data theft", "The site loads faster", "Cookies become invalid", "The server restarts"], "A",
         "Wildcard CORS with credentials lets any malicious site read responses that rely on the user's session."),
        ("ADVANCED", "What is clickjacking and which header directly defends against it?",
         ["UI overlay trickery defeated by X-Frame-Options: DENY", "A type of phishing email", "A SQL injection variant", "A brute-force attack"], "A",
         "X-Frame-Options: DENY (or a CSP frame-ancestors directive) stops the page from being framed and overlaid."),
        ("ADVANCED", "Why are security headers like CSP and HSTS often inspected by automated scanners?",
         ["Missing headers reveal misconfiguration and increased attack surface", "Headers speed up pages", "Headers reduce file size", "Headers improve SEO"], "A",
         "Scanners flag missing headers because their absence widens the attack surface for known attacks."),
        ("ADVANCED", "What is the correct order for handling untrusted input?",
         ["Validate on the server, then encode on output", "Trust all client input", "Encode first and skip validation", "Never validate"], "A",
         "Server-side validation rejects bad data and output encoding neutralizes the data that is legitimately rendered."),
        ("ADVANCED", "Which practice best protects sensitive tokens that must be sent with API requests?",
         ["Storing tokens in HttpOnly Secure SameSite cookies and relying on CSRF protections", "Placing tokens in URLs", "Hard-coding tokens in scripts", "Logging tokens to the console"], "A",
         "HttpOnly Secure SameSite cookies keep tokens out of script reach and cross-site traffic, with CSRF defenses layered on top."),
        ("ADVANCED", "What is the danger of logging raw user input without sanitization?",
         ["Log injection lets attackers forge or corrupt log entries", "Logs get shorter", "Logs become encrypted", "Logs are deleted"], "A",
         "Unescaped input with newlines can inject fake log lines, misleading monitoring and forensics."),
        ("ADVANCED", "A site must load scripts only from its own domain and never inline. Which policy expresses this?",
         ["Content-Security-Policy: default-src 'self'; script-src 'self'", "X-Content-Type-Options: nosniff", "Accept: text/html", "Cache-Control: no-cache"], "A",
         "That CSP directive blocks external and inline scripts while permitting same-origin scripts only."),
    ],
}
