# -*- coding: utf-8 -*-
"""
Question bank for subject 38: CORE103 - Software Engineering.
Category: Core Computer Science & Emerging Technologies.

Topics:
  186: SDLC & Models
  187: Requirements & Design
  188: Testing & Quality Assurance
  189: Design Patterns
  190: Agile & Project Management

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    186: [
        ("BEGINNER", "What does the abbreviation SDLC stand for?",
         ["Software Development Life Cycle", "System Design Logic Cycle", "Software Design and Language Code", "Standard Data Link Control"], "A",
         "SDLC stands for Software Development Life Cycle, the process used to plan, build and maintain software."),
        ("BEGINNER", "Which is typically the first phase of the SDLC?",
         ["Coding", "Requirements gathering", "Testing", "Deployment"], "B",
         "The SDLC begins with gathering and analyzing requirements to understand what the system must do."),
        ("BEGINNER", "What is a feasibility study in the SDLC?",
         ["A study of the project's technical and economic viability", "A test of the final product", "A review of the code quality", "A list of programming languages used"], "A",
         "A feasibility study assesses whether the project is technically, economically and operationally achievable."),
        ("BEGINNER", "Which SDLC model proceeds through phases in a strict linear sequence?",
         ["Waterfall", "Spiral", "Scrum", "Prototyping"], "D",
         "The waterfall model completes each phase fully before moving to the next, in a strict linear order."),
        ("BEGINNER", "In which SDLC phase is the system's architecture and design documented?",
         ["Design phase", "Maintenance phase", "Analysis phase", "Deployment phase"], "A",
         "The design phase translates requirements into the technical architecture and detailed design of the system."),
        ("BEGINNER", "What is a deliverable of the requirements analysis phase?",
         ["A requirements specification document", "A compiled executable", "A user manual", "A test report"], "B",
         "The analysis phase produces a requirements specification that formally documents what the system must do."),
        ("BEGINNER", "Which model is also commonly called the sequential or linear model?",
         ["Waterfall model", "Spiral model", "RAD model", "V-model"], "C",
         "The waterfall model is also called the sequential or linear model because phases follow one after another."),
        ("BEGINNER", "What is the main purpose of the maintenance phase in the SDLC?",
         ["To fix defects and make enhancements after release", "To write initial requirements", "To install development tools", "To design the database schema"], "D",
         "The maintenance phase keeps the deployed system working by fixing defects, patching and adding enhancements."),
        ("BEGINNER", "Which document describes what the system must do for the user?",
         ["Software requirements specification", "Hardware manual", "Test data file", "Compile log"], "A",
         "The software requirements specification (SRS) describes the functional and non-functional behavior the system must exhibit."),
        ("BEGINNER", "Which artifact is produced at the end of the coding phase?",
         ["Source code and compiled executables", "A feasibility report", "A project charter", "A database backup"], "B",
         "The coding phase produces the actual source code and compiled executables of the system."),
        ("INTERMEDIATE", "A project has stable and well-understood requirements. Which SDLC model is most appropriate?",
         ["Spiral", "Waterfall", "Incremental", "Extreme Programming"], "C",
         "The waterfall model suits projects with stable, clearly defined requirements because it has no room for late changes."),
        ("INTERMEDIATE", "In which phase are defects corrected after the software has been released to users?",
         ["Design phase", "Testing phase", "Maintenance phase", "Analysis phase"], "D",
         "Post-release defect correction and updates happen in the maintenance phase of the SDLC."),
        ("INTERMEDIATE", "What is a major drawback of the pure waterfall model?",
         ["It is too fast for large teams", "It makes changing requirements late in the cycle difficult and costly", "It requires no documentation", "It cannot handle any risk"], "A",
         "Because each phase must finish before the next, accommodating requirement changes after a phase is very expensive."),
        ("INTERMEDIATE", "Which document describes how the system will be implemented rather than what it will do?",
         ["The design document", "The user story", "The acceptance criteria", "The release notes"], "B",
         "The design document explains the technical implementation, including architecture, modules and interfaces."),
        ("INTERMEDIATE", "Which model delivers the system in small functional pieces that are each completed in turn?",
         ["Waterfall", "Incremental model", "Formal model", "Big bang model"], "C",
         "The incremental model builds and delivers the system in functional increments, each adding working capability."),
        ("INTERMEDIATE", "What does a software requirements specification (SRS) describe?",
         ["The internal code structure", "The hardware requirements only", "The functional and non-functional requirements of the system", "The marketing plan"], "D",
         "An SRS documents both functional requirements and non-functional constraints such as performance and security."),
        ("INTERMEDIATE", "Which SDLC activity estimates cost, schedule and risk before development begins?",
         ["Feasibility study", "Code review", "Beta testing", "Deployment"], "A",
         "The feasibility study evaluates cost, schedule and risk to determine whether development should proceed."),
        ("INTERMEDIATE", "In which model do the phases repeat in cycles, each producing an improved version of the system?",
         ["Iterative model", "Waterfall model", "Formal model", "Big bang model"], "B",
         "The iterative model repeats the phases in cycles, refining the system with each iteration."),
        ("INTERMEDIATE", "Which model combines prototyping with risk assessment through repeated cycles?",
         ["Waterfall", "Spiral model", "Coding and fixing model", "V-model"], "C",
         "The spiral model repeats cycles that combine prototyping, risk analysis and development to manage uncertainty."),
        ("INTERMEDIATE", "In which SDLC phase is the finished system checked to verify that it meets the stated requirements?",
         ["Requirements phase", "Design phase", "Testing phase", "Coding phase"], "D",
         "The testing phase verifies that the built system behaves according to the requirements specification."),
        ("ADVANCED", "What do the four quadrants of the spiral model represent?",
         ["Planning, risk analysis, engineering and customer evaluation", "Analysis, design, coding and testing", "Input, process, output and storage", "Budget, staff, tools and schedule"], "B",
         "Each spiral loop goes through planning, risk analysis, engineering and customer evaluation before the next cycle."),
        ("ADVANCED", "A team must build a high-risk banking system whose requirements are unclear. Which model is most appropriate?",
         ["Waterfall", "Spiral model", "Big bang model", "V-model"], "A",
         "The spiral model is risk-driven, so it is well suited to large, high-risk projects with evolving requirements."),
        ("ADVANCED", "Which model emphasizes mapping verification and validation activities directly to each development stage?",
         ["The waterfall model", "The prototyping model", "The V-model", "The big bang model"], "D",
         "The V-model pairs each development stage with a corresponding verification activity, forming a V shape."),
        ("ADVANCED", "What is the primary trade-off of the V-model?",
         ["It is entirely documentation-free", "It gives strong verification but is still sequential and rigid to change", "It requires no testing", "It cannot handle large teams"], "C",
         "The V-model strengthens verification and validation but keeps the rigid sequential structure that resists late changes."),
        ("ADVANCED", "A startup needs a working banking app quickly and requirements will keep evolving. Which approach is best?",
         ["Waterfall", "Big bang model", "Agile or iterative development", "Formal specification model"], "C",
         "Agile and iterative approaches deliver working software quickly and absorb changing requirements across iterations."),
        ("ADVANCED", "What distinguishes incremental delivery from iterative development?",
         ["They are identical in all respects", "Incremental delivers functional pieces while iterative refines the whole system through cycles", "Incremental never produces working software", "Iterative delivers all features in one release"], "B",
         "Incremental delivery adds functional pieces over time, while iterative development cycles through the entire system refining it repeatedly."),
        ("ADVANCED", "What is a primary weakness of the waterfall model on large projects?",
         ["It provides no documentation", "Problems are discovered late because testing happens only near the end", "It cannot work with any team size", "It produces too many releases"], "D",
         "Because testing is deferred to the end, defects and requirement mismatches surface very late and are costly to fix."),
        ("ADVANCED", "In the V-model, what does the right-hand side of the V represent?",
         ["The coding activities", "The verification and validation activities mapped to each development stage", "The hardware components", "The maintenance tasks only"], "C",
         "The right side of the V lists the verification and validation tests that correspond to each left-side development stage."),
        ("ADVANCED", "Which model uses risk analysis as the core driver at every cycle?",
         ["Waterfall", "Spiral model", "Big bang model", "V-model"], "B",
         "The spiral model evaluates risk at the start of every loop and uses it to guide the next engineering effort."),
        ("ADVANCED", "Which scenario best fits a prototyping-based SDLC approach?",
         ["Requirements are fully fixed and signed off", "The user cannot articulate requirements and needs to see a working model early", "The project has a strict fixed budget and no changes", "The system is trivial and built in one day"], "A",
         "Prototyping lets users react to a tangible early model, which is ideal when requirements are vague or hard to express."),
    ],
    187: [
        ("BEGINNER", "What is a functional requirement?",
         ["A statement of what the system must do", "A statement of system speed limits", "A hardware purchase order", "A testing schedule"], "A",
         "A functional requirement describes a specific behavior or function the system must perform."),
        ("BEGINNER", "What is a non-functional requirement?",
         ["A feature list for a new module", "A constraint on quality attributes such as performance, security or usability", "A description of user roles", "A database table design"], "B",
         "Non-functional requirements specify quality attributes and constraints such as performance, security and reliability."),
        ("BEGINNER", "Who is a stakeholder in a software project?",
         ["Only the developers", "Any person or group with an interest in the system's outcome", "Only the end users", "Only the project manager"], "C",
         "Stakeholders are all parties affected by or interested in the system, including users, managers and regulators."),
        ("BEGINNER", "What is a use case?",
         ["A description of how an actor achieves a goal with the system", "A type of database index", "A programming function", "A network protocol"], "D",
         "A use case describes a sequence of interactions through which an actor achieves a specific goal with the system."),
        ("BEGINNER", "What does SRS stand for?",
         ["Software Requirements Specification", "System Resource Sharing", "Standard Reference System", "Software Routing Service"], "A",
         "SRS stands for Software Requirements Specification, the formal document of the system's requirements."),
        ("BEGINNER", "Which UML diagram shows how actors interact with system functions?",
         ["Use case diagram", "Sequence diagram", "Deployment diagram", "Component diagram"], "B",
         "A use case diagram depicts actors, use cases and the relationships that show how users interact with the system."),
        ("BEGINNER", "What is a requirement traceability matrix?",
         ["A table linking requirements to their design, tests and code", "A list of hardware suppliers", "A schedule of project meetings", "A record of server addresses"], "C",
         "A traceability matrix maps each requirement to the design elements, test cases and code that satisfy it."),
        ("BEGINNER", "What does a class diagram show?",
         ["The classes in the system and their relationships", "The physical network layout", "The sequence of screen clicks", "The database passwords"], "D",
         "A class diagram shows the system's classes, their attributes and operations, and the associations between them."),
        ("BEGINNER", "What is a user story in agile requirements?",
         ["A short statement of a feature from the user's perspective", "A complete technical design", "A legal contract", "A database backup file"], "A",
         "A user story is a brief, from-the-user perspective description of a feature, usually in the form As a role, I want feature."),
        ("BEGINNER", "What does an entity-relationship diagram (ERD) model?",
         ["The entities in a system and how they relate", "The user interface layout", "The compile order of files", "The project budget"], "B",
         "An ERD models entities, their attributes and the relationships among them, typically for database design."),
        ("INTERMEDIATE", "The requirement states the system shall process a payment in under 3 seconds. What type of requirement is this?",
         ["Functional", "Performance", "Usability", "Legal"], "C",
         "Processing in under 3 seconds is a measurable performance constraint, which makes it a non-functional requirement."),
        ("INTERMEDIATE", "The requirement states the system shall allow users to log in with an email and password. What type of requirement is this?",
         ["Non-functional", "Security", "Functional", "Aesthetic"], "D",
         "Describing a concrete behavior the system must provide makes this a functional requirement."),
        ("INTERMEDIATE", "Which technique is commonly used to elicit requirements directly from end users?",
         ["Interviews and workshops", "Compiling the code", "Database indexing", "Server installation"], "A",
         "Interviews, workshops and questionnaires gather requirements directly from stakeholders through conversation."),
        ("INTERMEDIATE", "The requirement states the system shall not share user data with third parties. How is this best classified?",
         ["A functional feature", "A non-functional or regulatory constraint", "A user story", "A design pattern"], "B",
         "Data-sharing restrictions are constraints on behavior governed by policy or law, so they are non-functional requirements."),
        ("INTERMEDIATE", "Which artifact describes the characteristics and goals of a typical user of the system?",
         ["A persona", "A use case", "A class diagram", "A test plan"], "A",
         "A persona is a fictional but realistic profile of a typical user, used to guide design and requirements decisions."),
        ("INTERMEDIATE", "A use case typically includes which essential elements?",
         ["An actor and a goal", "A compiler and a linker", "A server and a database", "A budget and a schedule"], "B",
         "A use case describes an actor who interacts with the system to achieve a particular goal."),
        ("INTERMEDIATE", "What does an activity diagram model?",
         ["The workflow or process flow of activities", "The physical location of servers", "The password strength rules", "The pricing of the product"], "C",
         "An activity diagram models the flow of activities and decisions in a business process or use case."),
        ("INTERMEDIATE", "What does validating requirements mean?",
         ["Checking that the requirements meet the actual needs of the stakeholders", "Compiling the requirements into code", "Deleting unused requirements", "Formatting the document"], "D",
         "Validation confirms the requirements truly reflect what stakeholders need, rather than just checking internal consistency."),
        ("INTERMEDIATE", "Which of the following is a measurable requirement?",
         ["The system should be user friendly", "The page shall load in under 2 seconds", "The system should be fast", "The design should be modern"], "A",
         "A page load time under 2 seconds is concrete and measurable, unlike vague statements such as fast or user friendly."),
        ("INTERMEDIATE", "What is a scenario in requirements analysis?",
         ["A specific example describing how the system behaves in a given situation", "A hardware specification", "A project cost estimate", "A programming language choice"], "B",
         "A scenario is a concrete, step-by-step example of system behavior that helps clarify ambiguous requirements."),
        ("ADVANCED", "A requirement says the system should be easy to use. Why is this requirement problematic?",
         ["It is perfectly clear", "It is not measurable or testable", "It is too technical", "It is a functional requirement"], "B",
         "Easy to use cannot be measured objectively, so it cannot be verified by a test; it needs concrete acceptance criteria."),
        ("ADVANCED", "Two stakeholders demand conflicting requirements for the same feature. What is the best approach?",
         ["Implement both exactly", "Prioritize and negotiate a trade-off with the stakeholders", "Ignore both requirements", "Randomly choose one"], "A",
         "Conflicting requirements are resolved through prioritization and negotiation so stakeholders agree on a trade-off."),
        ("ADVANCED", "What is a key benefit of a requirement traceability matrix?",
         ["It reduces the need for testing", "It links requirements to design, tests and code so changes can be assessed", "It removes all bugs", "It automatically writes code"], "D",
         "Traceability shows how every requirement is satisfied, making impact analysis and verification of changes easier."),
        ("ADVANCED", "Requirements keep changing on a project. Which practice helps manage this most effectively?",
         ["Freezing all requirements forever", "Agile backlog management with short iterations and continuous prioritization", "Writing a single 500-page specification", "Skipping requirement reviews"], "C",
         "Short iterations with a continuously reprioritized backlog let the team adapt as requirements evolve."),
        ("ADVANCED", "What is the difference between verification and validation?",
         ["They are the same thing", "Verification checks the product against the specification, while validation checks it against user needs", "Validation checks only code style", "Verification is done only by users"], "B",
         "Verification asks did we build the product right, while validation asks did we build the right product."),
        ("ADVANCED", "Which diagram best captures the interactions over time within a single use case?",
         ["A sequence diagram", "A class diagram", "A deployment diagram", "A component diagram"], "A",
         "A sequence diagram shows the order of messages exchanged between objects over time for one scenario."),
        ("ADVANCED", "The requirement says the system shall support 10,000 concurrent users. What type of requirement is this?",
         ["A functional requirement", "A capacity or performance constraint", "A user story", "A design pattern"], "B",
         "Supporting a specific number of concurrent users is a measurable capacity constraint, so it is non-functional."),
        ("ADVANCED", "What is the main value of building a prototype during requirements analysis?",
         ["It replaces all documentation", "It clarifies ambiguous requirements through early user feedback", "It eliminates the need for testing", "It writes the final code"], "C",
         "A prototype lets users react to a concrete model early, which clarifies unclear requirements before full development."),
        ("ADVANCED", "Which statement best defines a functional requirement?",
         ["A statement of what the system must do", "A statement of how fast the system should run", "A statement of the project budget", "A statement of the marketing plan"], "B",
         "Functional requirements define the specific functions and behaviors the system must provide to its users."),
        ("ADVANCED", "In an agile project, when are detailed requirements finalized?",
         ["All at the very start of the project", "Continuously refined throughout iterations rather than all up front", "Only at the final release", "Never; requirements are not tracked"], "A",
         "Agile projects refine requirements iteratively, detailing items just before they are developed rather than up front."),
    ],
    188: [
        ("BEGINNER", "What is the primary purpose of software testing?",
         ["To find defects and verify that the software meets its requirements", "To write documentation", "To compile the code faster", "To sell the product"], "A",
         "Software testing aims to uncover defects and confirm that the software behaves as required."),
        ("BEGINNER", "What is a test case?",
         ["A set of input values, execution conditions and expected results used to verify behavior", "A programming language", "A type of database", "A user account"], "B",
         "A test case specifies the inputs, conditions and expected outcome used to check a particular behavior."),
        ("BEGINNER", "Which testing level verifies individual functions or modules in isolation?",
         ["Unit testing", "System testing", "Acceptance testing", "Load testing"], "C",
         "Unit testing verifies the smallest testable parts, such as individual functions or classes, in isolation."),
        ("BEGINNER", "Which type of testing is performed by end users to confirm the system meets their needs before release?",
         ["Acceptance testing", "Unit testing", "Compiler testing", "White-box testing"], "D",
         "Acceptance testing is carried out by users to confirm the system satisfies the agreed requirements."),
        ("BEGINNER", "What is a defect in software testing?",
         ["A flaw in the code that causes incorrect behavior", "A fast computer", "A type of network cable", "A user's password"], "A",
         "A defect is a flaw in the code or logic that produces incorrect or unexpected behavior."),
        ("BEGINNER", "Which testing verifies that integrated modules work correctly together?",
         ["Integration testing", "Unit testing", "Alpha testing", "Installation testing"], "B",
         "Integration testing checks that combined modules interact and exchange data correctly."),
        ("BEGINNER", "What does black-box testing focus on?",
         ["The internal code structure", "The external behavior without knowledge of internals", "The compiler options", "The database schema"], "C",
         "Black-box testing treats the software as a box and tests behavior based on inputs and outputs only."),
        ("BEGINNER", "What does white-box testing examine?",
         ["The internal structure and logic of the code", "Only the user interface", "The network bandwidth", "The product price"], "D",
         "White-box testing examines internal code paths, branches and conditions to ensure they are exercised."),
        ("BEGINNER", "What is regression testing?",
         ["Retesting to ensure that new changes did not break existing functionality", "Testing the product's price", "Testing the user manual", "Installing the software"], "A",
         "Regression testing reruns existing tests after changes to confirm previously working behavior still works."),
        ("BEGINNER", "Which test type verifies the complete system as a whole?",
         ["System testing", "Unit testing", "Module testing", "Patch testing"], "B",
         "System testing verifies the entire integrated system against the requirements in a realistic environment."),
        ("INTERMEDIATE", "A developer wants to verify a login function in isolation before integrating it. Which test is best?",
         ["A system test", "A unit test", "An acceptance test", "A load test"], "C",
         "A unit test verifies a single function or module in isolation, which fits a login function before integration."),
        ("INTERMEDIATE", "After integrating several modules, which test should the team run to check they work together?",
         ["Unit testing", "Integration testing", "Acceptance testing", "Static analysis"], "D",
         "Integration testing specifically checks that combined modules interact and exchange data correctly."),
        ("INTERMEDIATE", "Which test confirms the delivered system satisfies the expectations of end users?",
         ["Unit testing", "Acceptance testing", "Compiler testing", "Boundary testing"], "A",
         "Acceptance testing is performed by users to confirm the system meets their needs before it is released."),
        ("INTERMEDIATE", "What is equivalence partitioning in testing?",
         ["Dividing input data into classes expected to be treated the same way", "Splitting the team into pairs", "Partitioning the hard drive", "Dividing the budget evenly"], "B",
         "Equivalence partitioning groups inputs into classes that the system should handle identically, so one test per class suffices."),
        ("INTERMEDIATE", "What is boundary value analysis?",
         ["Testing at the edges of valid and invalid input ranges", "Testing random values in the middle", "Testing only the default values", "Testing values far outside all ranges"], "C",
         "Boundary value analysis tests inputs at the minimum and maximum edges of ranges, where defects are most common."),
        ("INTERMEDIATE", "Which type of testing checks that a recent fix did not break previously working features?",
         ["Regression testing", "Alpha testing", "Mutation testing", "Recovery testing"], "D",
         "Regression testing reruns existing tests to ensure new changes have not broken existing functionality."),
        ("INTERMEDIATE", "Which test approach examines the internal paths and branches of the code?",
         ["Black-box testing", "White-box testing", "Acceptance testing", "Usability testing"], "A",
         "White-box (structural) testing examines internal code paths, branches and conditions to ensure coverage."),
        ("INTERMEDIATE", "A tester verifies behavior using only inputs and outputs without seeing the code. This is which approach?",
         ["Black-box testing", "White-box testing", "Mutation testing", "Statement testing"], "B",
         "Black-box testing derives tests from the specification and observed behavior, ignoring the internal implementation."),
        ("INTERMEDIATE", "What is a stub in integration testing?",
         ["A placeholder for a module that has not been implemented yet", "A type of test report", "A database trigger", "A hardware device"], "C",
         "A stub is a minimal placeholder that simulates a missing module so that other modules can be tested."),
        ("INTERMEDIATE", "What does code coverage measure?",
         ["The percentage of code executed by the test suite", "The number of users", "The memory used by tests", "The speed of the compiler"], "D",
         "Code coverage measures how much of the program's code is exercised by the tests, helping find untested areas."),
        ("ADVANCED", "In test-driven development (TDD), when are the tests written?",
         ["After all the code is finished", "Before the implementation code", "Only during maintenance", "At the very end of the project"], "B",
         "TDD writes a failing test first, then the minimum code to pass it, then refactors, repeating the cycle."),
        ("ADVANCED", "A module works after a fix, but an unrelated module now fails. What kind of defect was introduced?",
         ["A regression defect", "A syntax defect", "A usability defect", "A design defect"], "A",
         "When a change to one area breaks functionality elsewhere that previously worked, it is a regression defect."),
        ("ADVANCED", "With limited testing resources, how should a team prioritize which features to test first?",
         ["Test in alphabetical order", "Use risk-based testing that focuses on the most critical and failure-prone features", "Test only trivial features", "Skip testing entirely"], "D",
         "Risk-based testing allocates effort to features with the highest business impact and greatest failure risk first."),
        ("ADVANCED", "What is the main purpose of exploratory testing?",
         ["To follow a fixed script for every case", "To discover unexpected defects through unscripted, session-based exploration", "To replace all automated tests", "To test only documentation"], "C",
         "Exploratory testing combines test design and execution, letting testers probe for defects beyond predefined scripts."),
        ("ADVANCED", "Which testing strategy is most appropriate for finding vulnerabilities in an API?",
         ["Security and penetration testing", "Unit testing alone", "Regression testing only", "Manual acceptance testing"], "B",
         "Security and penetration testing actively attempt to exploit weaknesses to uncover vulnerabilities in the API."),
        ("ADVANCED", "What does a test plan typically define?",
         ["The scope, strategy, resources and schedule of the testing effort", "The color scheme of the UI", "The product price", "The office layout"], "A",
         "A test plan documents the testing scope, strategy, resources, responsibilities and schedule for a project."),
        ("ADVANCED", "What does continuous integration encourage teams to do?",
         ["Commit code changes rarely and in huge batches", "Integrate and run automated builds and tests frequently", "Never run tests", "Build only at the end of the project"], "D",
         "Continuous integration promotes frequent commits with automated builds and tests to detect problems early."),
        ("ADVANCED", "Which scenario is best suited to automated testing?",
         ["A one-off manual data entry task", "Repetitive regression tests with stable, expected outputs", "Exploratory usability sessions", "A single visual inspection"], "C",
         "Automation pays off for repetitive regression tests with predictable expected results that must be rerun often."),
        ("ADVANCED", "What is the difference between a defect and a failure?",
         ["A defect is a fault in the code, while a failure is the observable incorrect behavior it causes", "They are identical", "A failure exists only in hardware", "A defect exists only in the database"], "B",
         "A defect is the underlying fault in the code, and a failure is the externally observable incorrect behavior it produces."),
        ("ADVANCED", "Achieving 100 percent branch coverage guarantees what?",
         ["The software has no bugs", "Every decision path has been executed at least once, but not that the code is defect-free", "All requirements are correct", "The tests can never be deleted"], "A",
         "Branch coverage ensures every branch was taken at least once, yet passing paths can still contain logic errors."),
    ],
    189: [
        ("BEGINNER", "What is a design pattern?",
         ["A reusable solution to a common design problem", "A programming language", "A type of database", "A hardware device"], "A",
         "A design pattern is a proven, reusable template for solving a recurring design problem in software."),
        ("BEGINNER", "Which pattern ensures that a class has only one instance?",
         ["Singleton", "Observer", "Decorator", "Factory"], "B",
         "The Singleton pattern restricts a class to a single instance and provides global access to it."),
        ("BEGINNER", "Which pattern creates objects without specifying the exact class to instantiate?",
         ["Factory pattern", "Adapter pattern", "Proxy pattern", "Command pattern"], "C",
         "The Factory pattern centralizes object creation so callers do not need to know the concrete class."),
        ("BEGINNER", "What is the Observer pattern used for?",
         ["Notifying dependent objects when the state of another object changes", "Creating a single instance", "Making two interfaces compatible", "Wrapping network traffic"], "D",
         "The Observer pattern defines a one-to-many dependency where observers are notified of state changes."),
        ("BEGINNER", "Which pattern encapsulates a request as an object?",
         ["Command pattern", "Singleton pattern", "Composite pattern", "Strategy pattern"], "A",
         "The Command pattern turns a request into an object so it can be stored, passed and executed later."),
        ("BEGINNER", "What is the Adapter pattern used for?",
         ["Making two incompatible interfaces work together", "Ensuring a single instance", "Creating objects in batches", "Sorting arrays"], "B",
         "The Adapter pattern converts the interface of a class into another interface the client expects."),
        ("BEGINNER", "Which pattern adds new responsibilities to an object dynamically without subclassing?",
         ["Decorator pattern", "Singleton pattern", "Template pattern", "Flyweight pattern"], "C",
         "The Decorator pattern wraps an object with additional behavior, adding responsibilities at runtime."),
        ("BEGINNER", "What is the Strategy pattern?",
         ["A pattern for swapping interchangeable algorithms at runtime", "A pattern for database access", "A pattern for drawing windows", "A pattern for logging errors"], "D",
         "The Strategy pattern defines a family of interchangeable algorithms and lets the client select one at runtime."),
        ("BEGINNER", "To which category does the Singleton pattern belong?",
         ["Creational", "Structural", "Behavioral", "Architectural"], "A",
         "Singleton is a creational pattern because it controls how objects are created and ensures one instance."),
        ("BEGINNER", "Which pattern provides a simplified interface to a complex subsystem?",
         ["Facade pattern", "Builder pattern", "Iterator pattern", "State pattern"], "B",
         "The Facade pattern exposes a simple interface that hides the complexity of a larger subsystem."),
        ("INTERMEDIATE", "A configuration manager must have exactly one instance shared across the application. Which pattern should be used?",
         ["Singleton", "Observer", "Decorator", "Composite"], "C",
         "The Singleton pattern guarantees a single shared instance, ideal for a global configuration manager."),
        ("INTERMEDIATE", "A report module must support exporting to PDF, Excel and CSV with easily switchable formats. Which pattern fits best?",
         ["Strategy", "Singleton", "Adapter", "Facade"], "D",
         "The Strategy pattern lets each export format be an interchangeable algorithm selected at runtime."),
        ("INTERMEDIATE", "Objects of several related types must be created based on a type parameter. Which pattern is most appropriate?",
         ["Factory Method", "Observer", "Proxy", "Singleton"], "A",
         "Factory Method (or a simple factory) selects and creates the appropriate class from a type parameter."),
        ("INTERMEDIATE", "A UI button must notify several components when clicked without coupling them to the button. Which pattern helps?",
         ["Observer", "Decorator", "Adapter", "Composite"], "B",
         "The Observer pattern lets the button notify multiple subscribed components without knowing them."),
        ("INTERMEDIATE", "Which pattern lets a request be stored as an object and later replayed or undone?",
         ["Command", "Strategy", "Factory", "Facade"], "C",
         "The Command pattern encapsulates a request as an object, enabling queuing, logging and undo support."),
        ("INTERMEDIATE", "A legacy system exposes a different interface than the new client expects. Which pattern bridges them?",
         ["Adapter", "Singleton", "Decorator", "Builder"], "D",
         "The Adapter pattern translates the legacy interface into the interface the new client expects."),
        ("INTERMEDIATE", "Which pattern adds responsibilities to an object dynamically without modifying its class?",
         ["Decorator", "Factory", "Singleton", "Observer"], "A",
         "The Decorator pattern wraps objects to add behavior dynamically without subclassing."),
        ("INTERMEDIATE", "Which pattern separates the construction of a complex object from its final representation?",
         ["Builder", "Singleton", "Adapter", "State"], "B",
         "The Builder pattern constructs complex objects step by step, allowing different representations of the same process."),
        ("INTERMEDIATE", "Which pattern defines a one-to-many dependency so that when one object changes, many are updated?",
         ["Observer", "Singleton", "Facade", "Factory"], "C",
         "The Observer pattern maintains a one-to-many dependency and notifies all dependents of state changes."),
        ("INTERMEDIATE", "All database access should flow through a single simplified entry point. Which pattern provides this?",
         ["Facade", "Decorator", "Singleton", "Command"], "D",
         "The Facade pattern offers a single, simplified interface that hides the complexity of the underlying subsystem."),
        ("ADVANCED", "An editor must support undo and redo of user actions. Which pattern is most appropriate?",
         ["Command", "Singleton", "Observer", "Flyweight"], "B",
         "The Command pattern stores each action as an object with execute and undo methods, enabling undo and redo."),
        ("ADVANCED", "A document consists of nested groups where each group can contain text or other groups. Which pattern fits best?",
         ["Composite", "Singleton", "Adapter", "Template"], "A",
         "The Composite pattern treats individual parts and whole groups uniformly in a tree structure."),
        ("ADVANCED", "A chat service must broadcast a message to all connected users. Which pattern is the best fit?",
         ["Observer", "Singleton", "Factory", "Proxy"], "D",
         "The Observer pattern lets the chat server notify all subscribed users when a message arrives."),
        ("ADVANCED", "What is a common drawback of the Singleton pattern?",
         ["It always speeds up code", "It introduces global state that makes testing and concurrency harder", "It creates too many instances", "It prevents all object creation"], "C",
         "Singleton introduces hidden global state, which complicates testing and can create concurrency issues."),
        ("ADVANCED", "A sorting utility must allow callers to plug in different algorithms such as quicksort or mergesort. Which pattern is best?",
         ["Strategy", "Singleton", "Composite", "State"], "B",
         "The Strategy pattern lets callers select interchangeable sorting algorithms at runtime."),
        ("ADVANCED", "Which pattern lets a client work with a remote service as if it were local while hiding network details?",
         ["Proxy", "Observer", "Factory", "Facade"], "A",
         "A proxy stands in for the real object, handling network or security details transparently to the client."),
        ("ADVANCED", "An object must change its behavior completely when its internal state changes. Which pattern is most suitable?",
         ["State", "Singleton", "Adapter", "Command"], "D",
         "The State pattern lets an object change its behavior when its state changes by delegating to a state object."),
        ("ADVANCED", "A UI needs logging and access-control checks added dynamically around operations without changing them. Which pattern combination fits?",
         ["Decorator and Command", "Singleton and Observer", "Flyweight and Proxy", "Factory and Template"], "C",
         "The Command pattern wraps each operation, while the Decorator pattern adds logging and access control dynamically."),
        ("ADVANCED", "A game character must behave differently when powered up, normal or weakened. Which pattern is most appropriate?",
         ["State", "Singleton", "Adapter", "Composite"], "B",
         "The State pattern lets the character switch behaviors by changing its current state object."),
        ("ADVANCED", "Which pattern is best for building complex objects step by step with different possible representations?",
         ["Builder", "Singleton", "Observer", "Flyweight"], "A",
         "The Builder pattern constructs complex objects step by step so the same process can produce different representations."),
    ],
    190: [
        ("BEGINNER", "What is Agile software development?",
         ["An iterative approach that emphasizes collaboration, flexibility and customer feedback", "A strictly sequential process", "A hardware design method", "A database model"], "A",
         "Agile development delivers value in small increments with constant collaboration and adaptability to change."),
        ("BEGINNER", "What is a sprint in Scrum?",
         ["A fixed-length iteration in which work is completed", "A type of bug", "A design document", "A hardware component"], "B",
         "A sprint is a time-boxed iteration, usually 1 to 4 weeks, during which the team completes a set of work."),
        ("BEGINNER", "What is the main responsibility of a Scrum Master?",
         ["Facilitating the process and removing impediments", "Writing all the code", "Setting the product price", "Doing the final testing alone"], "C",
         "The Scrum Master facilitates Scrum practices and helps the team remove obstacles that slow it down."),
        ("BEGINNER", "What is a product backlog?",
         ["A prioritized list of features and tasks for the product", "A list of company employees", "A database of customers", "A record of failed builds"], "D",
         "The product backlog is the prioritized list of features, enhancements and fixes that define the product's work."),
        ("BEGINNER", "What is a daily stand-up meeting?",
         ["A short daily meeting where team members sync on progress and blockers", "A long weekly design review", "A monthly budget meeting", "A performance review"], "A",
         "A stand-up is a brief daily sync where each member reports progress, plans and impediments."),
        ("BEGINNER", "What does a burndown chart show?",
         ["The amount of remaining work over the course of a sprint", "The number of employees", "The network traffic", "The product price"], "B",
         "A burndown chart plots remaining work against time to show whether the team is on track."),
        ("BEGINNER", "What does MVP stand for in product development?",
         ["Minimum Viable Product", "Most Valuable Program", "Main Version Path", "Minimum Vendor Price"], "C",
         "An MVP is the smallest version of a product that still delivers value and can be tested with users."),
        ("BEGINNER", "What is a sprint retrospective?",
         ["A meeting to reflect on the past sprint and improve the process", "A code compilation", "A client demo only", "A database backup"], "D",
         "The retrospective is a team meeting to review what went well, what did not and how to improve."),
        ("BEGINNER", "What is team velocity in Scrum?",
         ["The amount of work a team completes in a sprint", "The speed of the build server", "The number of employees", "The project budget"], "A",
         "Velocity measures how much work a team completes per sprint, used to plan future sprints."),
        ("BEGINNER", "What is the definition of done in Scrum?",
         ["The set of criteria an item must meet to be considered complete", "The day the project starts", "The final payment", "The login screen"], "B",
         "The definition of done is a shared checklist that an increment must satisfy before it is considered finished."),
        ("INTERMEDIATE", "Who is responsible for owning and prioritizing the product backlog?",
         ["The Product Owner", "The Scrum Master", "The developers", "The CEO"], "C",
         "The Product Owner owns the backlog and decides the priority and value of each item."),
        ("INTERMEDIATE", "A user story is commonly written in which format?",
         ["As a role, I want feature so that benefit", "In binary code", "As a legal contract", "As a database query"], "D",
         "The standard user story format captures the role, the desired feature and the benefit it provides."),
        ("INTERMEDIATE", "A stakeholder asks to add a feature in the middle of a sprint. What should the team do?",
         ["Add it to the product backlog for a future sprint", "Stop everything and implement it now", "Quietly ignore it", "Delete the sprint backlog"], "A",
         "Mid-sprint scope changes are deferred to the backlog so the current sprint goal stays stable."),
        ("INTERMEDIATE", "What does a Kanban board visualize?",
         ["The workflow and work in progress across stages", "The employee salaries", "The network architecture", "The product pricing"], "B",
         "A Kanban board visualizes the flow of work through stages and limits work in progress to improve flow."),
        ("INTERMEDIATE", "What is the main difference between Scrum and Kanban?",
         ["Scrum uses time-boxed sprints, while Kanban uses continuous flow", "Kanban has fixed-length sprints", "Scrum has no roles", "Kanban uses a product owner only"], "C",
         "Scrum organizes work into fixed-length sprints, whereas Kanban is a continuous flow system with no sprint boundaries."),
        ("INTERMEDIATE", "What is story point estimation?",
         ["A relative measure of the effort or complexity of a backlog item", "A count of the pages in a story", "A price in dollars", "The number of users"], "D",
         "Story points are a relative unit for estimating the effort and complexity of backlog items."),
        ("INTERMEDIATE", "Which artifact lists the work the team has committed to deliver in the current sprint?",
         ["The sprint backlog", "The product roadmap", "The release notes", "The annual report"], "A",
         "The sprint backlog contains the selected product backlog items and the tasks for the current sprint."),
        ("INTERMEDIATE", "A product owner reprioritizes features based on new customer feedback. Where does this activity take place?",
         ["Backlog refinement", "The daily stand-up", "Code compilation", "Deployment"], "B",
         "Backlog refinement (grooming) is where the product owner and team clarify and reprioritize backlog items."),
        ("INTERMEDIATE", "What is the purpose of a sprint review?",
         ["To demonstrate completed work and gather stakeholder feedback", "To write the user manual", "To install servers", "To calculate salaries"], "C",
         "In the sprint review the team demonstrates what was completed and collects feedback from stakeholders."),
        ("INTERMEDIATE", "Which metrics best track progress toward a release in an agile project?",
         ["Velocity and burndown charts", "The number of offices", "The CPU temperature", "The email count"], "D",
         "Velocity and burndown charts show how much work is being completed and how much remains before release."),
        ("ADVANCED", "A team consistently overcommits and misses its sprint goals. What is the best adjustment?",
         ["Reduce sprint scope to match the team's proven capacity based on past velocity", "Promise even more work", "Eliminate the sprint goal", "Stop using the backlog"], "B",
         "Planning sprints using historical velocity gives a realistic scope the team can actually complete."),
        ("ADVANCED", "When is it appropriate to change the sprint goal?",
         ["Only rarely, with the full team and stakeholders agreeing on a significant impediment", "Every day", "Whenever one developer requests it", "Never under any circumstances"], "A",
         "The sprint goal should be changed only when a major impediment requires it, with the whole team and stakeholders in agreement."),
        ("ADVANCED", "How can a retrospective best support a geographically distributed team?",
         ["Scheduled, facilitated sessions using shared tools so everyone can contribute", "Skipping it because remote teams cannot meet", "Holding it only by email", "Limiting it to managers"], "D",
         "Structured, time-boxed retrospective sessions with collaborative tools help remote team members participate equally."),
        ("ADVANCED", "A project has extremely volatile requirements. Which approach is the best fit?",
         ["Agile with short iterations", "A fixed five-year waterfall plan", "A big bang delivery", "No requirements at all"], "C",
         "Short agile iterations let the team respond quickly as requirements change, rather than locking scope up front."),
        ("ADVANCED", "How does agile estimation differ from traditional waterfall estimation?",
         ["Agile uses relative and iterative estimation, while waterfall relies on detailed up-front estimates", "Agile never estimates", "Waterfall never estimates", "They are identical in approach"], "B",
         "Agile refines estimates iteratively using relative measures, whereas waterfall attempts detailed estimates before development."),
        ("ADVANCED", "A stakeholder demands a fixed deadline and fixed scope. What trade-off does agile typically force?",
         ["The team must trade scope or quality, as in the project management triangle", "Nothing needs to change", "Only the budget can change", "The deadline is always achievable"], "A",
         "With fixed time and scope, the team must sacrifice scope, quality or cost because all cannot remain fixed."),
        ("ADVANCED", "What is the purpose of the definition of ready?",
         ["Criteria that ensure a backlog item is clear and refined enough to start work", "A checklist for releasing to production", "A list of required servers", "A requirement for daily meetings"], "B",
         "The definition of ready confirms an item is detailed and refined enough for the team to begin work on it."),
        ("ADVANCED", "Management wants phase-gate approvals in an otherwise agile program. What is the key conflict?",
         ["Phase-gate approvals clash with iterative delivery and continuous feedback", "They speed up all iterations", "They remove the need for a product owner", "They replace the definition of done"], "C",
         "Fixed phase-gates assume sequential completion, which conflicts with agile's continuous, incremental delivery."),
        ("ADVANCED", "Which statement best describes a product owner's authority?",
         ["The product owner prioritizes the backlog but does not dictate technical implementation", "The product owner writes all the code", "The product owner sets the team's salaries", "The product owner approves every line of code"], "D",
         "The product owner owns priorities and value, while the team owns how the work is implemented technically."),
        ("ADVANCED", "Velocity is stable, but the defect rate is rising. What is the best next step for the team?",
         ["Allocate time for refactoring and paying down technical debt in upcoming sprints", "Release immediately", "Ignore the defects", "Reduce testing effort"], "A",
         "Investing in refactoring and technical debt reduction improves code quality and prevents further defect growth."),
    ],
}
