# -*- coding: utf-8 -*-
"""
Question bank for subject 20: OS105 - Modern Operating Systems.
Category: Operating Systems & System Programming.

Topics:
  96: Windows Architecture
  97: Windows Process & Memory
  98: Windows Security & Registry
  99: Mobile & macOS Operating Sys
  100: Virtualization & Containers

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    96: [
        ("BEGINNER", "Which component of Windows abstracts hardware differences so the OS runs on diverse hardware platforms?",
         ["Hardware Abstraction Layer (HAL)", "Plug and Play Manager", "Object Manager", "Win32k.sys"], "A",
         "The HAL hides hardware-specific details from the kernel so the same kernel code runs across many hardware platforms."),
        ("BEGINNER", "In which mode do the Windows kernel and its device drivers execute?",
         ["user mode", "kernel mode", "compatibility mode", "protected mode"], "B",
         "The kernel and drivers run in kernel mode, which gives direct access to hardware and privileged instructions."),
        ("BEGINNER", "What is the name of the executable image of the core Windows executive and kernel?",
         ["kernel32.dll", "ntdll.dll", "ntoskrnl.exe", "winlogon.exe"], "C",
         "ntoskrnl.exe is the main kernel image that provides the executive services and the kernel layer."),
        ("BEGINNER", "Which Windows environment subsystem provides the classic Win32 application programming interface?",
         ["WSL", "POSIX", "OS/2", "Win32"], "D",
         "The Win32 subsystem is the primary environment subsystem that Win32 applications are written against."),
        ("BEGINNER", "What does an application use to request services from the Windows kernel?",
         ["system calls", "API drivers", "shared memory only", "COM objects"], "A",
         "User-mode programs make system calls to request kernel services such as file I/O and process creation."),
        ("BEGINNER", "Which component implements the graphics and window management portion on the kernel-mode side of Windows?",
         ["GDI driver", "win32k.sys", "csrss.exe", "explorer.exe"], "B",
         "win32k.sys is the kernel-mode component that implements the window manager and graphics device interface."),
        ("BEGINNER", "Which of the following runs in user mode?",
         ["the HAL", "the process manager", "the Windows API DLLs", "the I/O manager"], "C",
         "API DLLs such as kernel32.dll execute in user mode while the HAL, process manager and I/O manager are kernel-mode."),
        ("BEGINNER", "What is the primary role of the Windows executive services layer?",
         ["providing the graphical interface", "managing user passwords", "providing high-level OS services built on the kernel", "compiling user programs"], "D",
         "The executive implements high-level services such as process, memory and I/O management on top of the kernel."),
        ("BEGINNER", "Which Windows process is the user-mode root of the Win32 subsystem and manages console windows?",
         ["csrss.exe", "smss.exe", "lsass.exe", "services.exe"], "A",
         "csrss.exe is the Client/Server Runtime Subsystem that handles console windows and Win32 base services."),
        ("BEGINNER", "What protects kernel-mode code from being modified by user-mode programs?",
         ["User Account Control", "privilege separation between user and kernel mode", "the registry", "system restore"], "B",
         "Separating user and kernel modes means user code cannot execute privileged instructions or touch kernel memory."),
        ("INTERMEDIATE", "When a user-mode program needs hardware access, which order does the request typically follow?",
         ["directly to the hardware", "through the registry then the CPU", "user-mode API, system call, kernel executive, driver, and then the hardware", "through explorer.exe then the HAL"], "C",
         "Requests flow from a user API through a system call into the executive, which dispatches to the appropriate driver."),
        ("INTERMEDIATE", "Why does Windows run most system-critical code in kernel mode?",
         ["it speeds up user interface rendering", "it simplifies debugging", "it reduces memory usage", "kernel mode is needed for privileged operations such as direct hardware and memory control"], "D",
         "Only kernel mode can execute privileged instructions and access protected memory needed to manage the system."),
        ("INTERMEDIATE", "What happens when a user-mode thread executes a privileged instruction?",
         ["a processor exception or trap is raised, handled by the kernel", "the instruction executes normally", "the system reboots", "the thread is silently ignored"], "A",
         "The CPU raises a trap that transfers control to the kernel, which can then handle or reject the operation."),
        ("INTERMEDIATE", "Which of these components is part of the Windows executive layer?",
         ["thread scheduling", "the process and thread manager", "interrupt dispatch", "exception dispatching"], "B",
         "The process and thread manager is an executive component, while scheduling and interrupt handling live in the kernel."),
        ("INTERMEDIATE", "What is the purpose of the Object Manager in Windows?",
         ["to draw windows on screen", "to compress files", "to manage named kernel objects and maintain a uniform namespace", "to enforce file permissions only"], "C",
         "The Object Manager tracks kernel objects such as processes, files and devices and gives them a common naming scheme."),
        ("INTERMEDIATE", "A hardware device needs immediate attention; which mechanism lets the kernel respond quickly?",
         ["polling every second", "the desktop heap", "interrupt handling via the kernel's interrupt dispatch", "user-mode timers"], "D",
         "Interrupts let devices signal the kernel immediately, and the kernel's interrupt dispatch handles them promptly."),
        ("INTERMEDIATE", "Which layer translates processor-specific operations such as cache and interrupt management into generic routines?",
         ["the Hardware Abstraction Layer (HAL)", "win32k.sys", "the session manager", "the security reference monitor"], "A",
         "The HAL abstracts platform-specific CPU details so the kernel can use generic interfaces."),
        ("INTERMEDIATE", "Which process is responsible for starting the Windows session and creating the subsystem processes at boot?",
         ["winlogon.exe", "smss.exe (Session Manager)", "svchost.exe", "taskmgr.exe"], "B",
         "smss.exe is the Session Manager that starts the Win32 subsystem and Winlogon during boot."),
        ("INTERMEDIATE", "Why are most kernel-mode components compiled into a single file rather than spread across many DLLs?",
         ["because DLLs cannot be loaded in kernel mode", "for faster startup of user programs", "a monolithic kernel reduces inter-component call overhead and simplifies boot", "because the filesystem requires it"], "C",
         "Keeping core kernel components in ntoskrnl.exe avoids expensive cross-module calls and simplifies boot time."),
        ("INTERMEDIATE", "In modern Windows, what is the typical entry point for a user-mode system call?",
         ["a direct hardware instruction", "the registry", "a COM object", "the system service dispatch table reached through ntdll"], "D",
         "ntdll provides stubs that invoke the system service dispatch table in the kernel for each system call."),
        ("ADVANCED", "A driver must respond to a time-critical hardware event with minimal delay. What is the most appropriate mechanism?",
         ["polling in a user-mode loop", "a background registry scan", "an interrupt service routine or deferred procedure call at the appropriate IRQL", "a Windows service timer"], "D",
         "ISRs and DPCs give drivers the low-latency response hardware events require, unlike timers or polling."),
        ("ADVANCED", "Why can Win32 subsystem processes such as csrss.exe not be safely terminated at runtime?",
         ["it manages console handling and critical base API services used by many processes", "it holds the registry hive", "it is the only process with kernel access", "it is protected by the file system"], "A",
         "Terminating csrss.exe breaks the Win32 base services that the rest of the system depends on, destabilizing Windows."),
        ("ADVANCED", "During a Windows crash, what file captures kernel memory so the issue can be debugged?",
         ["pagefile.sys", "MEMORY.DMP", "winlogon.exe", "ntuser.dat"], "B",
         "A memory dump file such as MEMORY.DMP records the state of kernel memory at the time of the crash for analysis."),
        ("ADVANCED", "Which design change in modern Windows reduces the attack surface by isolating critical processes from each other?",
         ["enabling compatibility mode", "running everything in kernel mode", "process isolation and services running in separate sessions and containers", "disabling the scheduler"], "C",
         "Isolating processes and services limits what an attacker can reach if one component is compromised."),
        ("ADVANCED", "What is the primary function of the Session Manager (smss.exe) during boot?",
         ["rendering the login screen", "managing paging files", "running user applications", "creating the initial session and starting the Win32 subsystem and Winlogon"], "D",
         "smss.exe initializes the system session and launches the subsystem and login components during boot."),
        ("ADVANCED", "A developer loads a kernel driver and the machine bluescreens immediately. What is the most likely cause?",
         ["the driver ran in kernel mode and executed an invalid operation, crashing the whole system", "the driver was compiled in user mode", "the registry is corrupt", "the HAL is missing"], "A",
         "Kernel-mode faults are fatal, so an invalid driver operation brings down the entire system."),
        ("ADVANCED", "Which statement best describes how system calls are dispatched on modern x64 Windows?",
         ["each call is handled by a separate DLL", "calls go through the kernel only at boot", "the syscall instruction transfers control to the system service dispatch table in the kernel", "calls are emulated by the CPU"], "B",
         "On x64 the syscall instruction jumps directly into the kernel's service dispatch table, avoiding an interrupt handler."),
        ("ADVANCED", "Why is the Hardware Abstraction Layer considered essential for server and OEM deployments?",
         ["it speeds up the GUI", "it stores user passwords", "it lets one binary of Windows run across CPUs with different timer and interrupt behavior", "it handles networking"], "C",
         "The HAL abstracts platform differences so a single Windows build works on a wide range of hardware."),
        ("ADVANCED", "In a system where a misbehaving driver corrupts memory, why does Windows generally crash rather than just failing that driver?",
         ["because drivers are optional", "because kernel memory corruption can affect any process and the system cannot guarantee safe continuation", "because the scheduler stops", "because the registry is erased"], "D",
         "Corrupted kernel memory makes further operation unreliable, so a bugcheck is the safe response."),
        ("ADVANCED", "What does the Memory Manager contribution to the executive provide that is essential for every process?",
         ["private virtual address spaces and paged virtual memory", "the graphical desktop", "kernel symbol files", "the boot menu"], "A",
         "The Memory Manager gives each process an isolated virtual address space backed by physical memory and the paging file."),
    ],
    97: [
        ("BEGINNER", "What is the basic unit of execution scheduled by the Windows kernel?",
         ["thread", "process", "session", "job"], "A",
         "Threads are the schedulable units, while a process is a container for resources and threads."),
        ("BEGINNER", "Which term describes a container holding a virtual address space and the threads that run within it?",
         ["module", "process", "job object", "file mapping"], "B",
         "A process provides the virtual address space, resources and security context for its threads."),
        ("BEGINNER", "What does the Windows scheduler decide?",
         ["which colors to display", "how to partition the disk", "which thread runs next on a processor", "which files to defragment"], "C",
         "The scheduler selects which thread should execute next on each available processor."),
        ("BEGINNER", "What is a handle in Windows?",
         ["a kernel password", "an opaque reference to a kernel object such as a process or file", "a block of memory", "a system call"], "D",
         "A handle is an opaque value that lets a process reference a kernel object without direct pointer access."),
        ("BEGINNER", "Which API function creates a new process in the Win32 API?",
         ["CreateProcess", "StartThread", "NewProc", "MakeProcess"], "A",
         "CreateProcess is the Win32 function that creates a new process and its primary thread."),
        ("BEGINNER", "What is the primary difference between a stack and a heap?",
         ["stack is shared between threads", "a stack is per-thread and automatic while the heap is shared memory that must be managed", "they are identical", "the heap is faster"], "B",
         "Each thread has its own automatic stack, while the heap is shared and requires explicit allocation and freeing."),
        ("BEGINNER", "Which file extensions are used for a Windows executable or DLL?",
         ["EXE only", "BIN", "EXE and DLL", "TMP"], "C",
         "Both EXE and DLL files use the PE format and are the standard executable images on Windows."),
        ("BEGINNER", "What happens to a process when its last thread finishes?",
         ["it continues running", "it becomes a zombie until reboot", "the process terminates and its resources are released", "it is suspended"], "D",
         "When the final thread exits, the process terminates and its resources are reclaimed by the system."),
        ("BEGINNER", "Which Windows mechanism lets two processes share a region of memory efficiently?",
         ["memory-mapped files", "the registry", "the clipboard", "environment variables"], "A",
         "Memory-mapped files let multiple processes map the same region of memory into their address spaces."),
        ("BEGINNER", "What is the virtual address space of a process?",
         ["the amount of RAM installed", "the range of addresses the process can reference, backed by RAM or paging storage", "the hard disk space", "the CPU cache"], "B",
         "A process can reference addresses within its virtual address space, which is backed by physical memory and the paging file."),
        ("INTERMEDIATE", "A program reserves a large region of virtual memory but has not yet used it. How does Windows avoid allocating physical memory immediately?",
         ["compress memory to disk", "reserve memory only and commit pages on demand", "allocate the full region as RAM", "disable paging"], "C",
         "Windows uses reserved-then-committed memory so physical pages are only allocated when first accessed."),
        ("INTERMEDIATE", "Which Windows component translates virtual addresses to physical addresses?",
         ["the scheduler", "winlogon", "the registry", "the memory manager and page tables"], "D",
         "The memory manager maintains page tables that map each process's virtual pages to physical frames."),
        ("INTERMEDIATE", "When physical RAM runs low, what does Windows typically do?",
         ["trim working sets and write pages to the paging file", "shut down applications", "reboot the machine", "increase the processor speed"], "A",
         "The memory manager trims process working sets and pages out less-used data to relieve memory pressure."),
        ("INTERMEDIATE", "What is the paging file used for in Windows?",
         ["To store memory pages temporarily moved out of physical RAM", "To hold user documents", "To store device drivers", "To keep the registry"], "A",
         "The paging file backs virtual memory by holding pages that have been evicted from physical RAM, freeing memory for other uses."),
        ("INTERMEDIATE", "Which structures describe a thread's state, stack and context and are maintained by the system?",
         ["a TEB only", "the PEB", "a thread control block and the thread environment block (TEB)", "a job object"], "C",
         "The kernel tracks each thread with a control block and user-mode data in the TEB."),
        ("INTERMEDIATE", "Which value determines how often a thread gets the CPU relative to others at the same base priority?",
         ["its token", "its stack size", "its handle", "its dynamic priority, which the scheduler boosts based on activity"], "D",
         "The scheduler adjusts dynamic priorities so interactive threads get CPU sooner than idle ones."),
        ("INTERMEDIATE", "A process allocates a large buffer with VirtualAlloc but never touches most of it. What is the expected behavior?",
         ["only the touched pages are committed to physical memory", "all of it is forced into RAM", "the buffer is written to the registry", "the system reserves extra RAM"], "A",
         "Committed pages become resident only on first access, so untouched portions consume little physical memory."),
        ("INTERMEDIATE", "Which Windows feature randomizes where executables and DLLs load in memory to thwart attacks?",
         ["BitLocker", "ASLR (Address Space Layout Randomization)", "the paging file", "NTFS"], "B",
         "ASLR randomizes image base addresses so exploits cannot rely on fixed addresses."),
        ("INTERMEDIATE", "What is the purpose of the Process Environment Block (PEB)?",
         ["storing kernel objects", "scheduling threads", "holding user-mode process data such as image path, environment and loader data", "managing the registry"], "C",
         "The PEB is a user-mode structure containing process-wide information such as the module list and environment."),
        ("INTERMEDIATE", "Which statement about threads sharing the same process is correct?",
         ["they each get a separate address space", "they cannot run concurrently", "they share the process address space but have their own stack and registers", "they must run on different CPUs"], "D",
         "Threads in one process share the address space and resources while keeping private stacks and register state."),
        ("ADVANCED", "A server needs to run thousands of concurrent tasks cheaply. What is the most efficient Windows approach?",
         ["create a dedicated process per task", "increase the pagefile", "use the thread pool and I/O completion ports", "disable memory-mapped files"], "D",
         "A thread pool with I/O completion ports scales to many concurrent operations without a thread per task."),
        ("ADVANCED", "Why is a context switch more expensive than a simple function call?",
         ["the kernel must save registers, switch address spaces if needed, and update scheduler state", "because the CPU reboots", "because the registry is accessed", "because the hard disk spins up"], "A",
         "A context switch involves privileged work to save the outgoing thread's state and restore the next thread's state."),
        ("ADVANCED", "An application must pass a large data buffer between two processes without copying it twice. Which technique is best?",
         ["write it to a file and read it back", "use a shared memory-mapped file region", "send it through the clipboard", "store it in the registry"], "B",
         "A shared memory-mapped file lets both processes access the same pages, avoiding extra data copies."),
        ("ADVANCED", "What is the main risk of a process whose committed virtual memory grows without bound?",
         ["it gets faster", "it becomes unkillable", "the paging file and physical memory can be exhausted, causing system-wide slowdown or failure", "its threads are suspended"], "C",
         "Unbounded commits exhaust memory and paging space, which can destabilize the entire system."),
        ("ADVANCED", "Which mechanism prevents one process from corrupting another process's address space?",
         ["software protection", "per-process virtual address spaces enforced by page tables", "the registry", "the firewall"], "D",
         "Each process has its own page tables, so its addresses do not map to another process's physical memory."),
        ("ADVANCED", "A thread calls ExitThread; what immediately happens?",
         ["the thread terminates and its objects and stack are cleaned up when its handles close", "the whole process exits", "the system reboots", "the thread sleeps forever"], "A",
         "ExitThread ends the calling thread, and the kernel cleans up its resources once all handles are closed."),
        ("ADVANCED", "Which scenario best explains 'thrashing'?",
         ["a CPU overheating", "heavy swapping in which the system spends more time moving pages than doing useful work", "a network outage", "a driver signing issue"], "B",
         "Thrashing occurs when the working sets exceed physical memory and the system continuously pages data in and out."),
        ("ADVANCED", "To maximize throughput for a CPU-bound workload on a many-core machine, what does the scheduler try to maintain?",
         ["one thread per process", "cache locality by keeping threads on the same processor when possible", "equal CPU counts", "a single queue"], "C",
         "Keeping threads on the same processor preserves warm caches and reduces migration overhead."),
        ("ADVANCED", "A background process must do work every 30 minutes without keeping a thread always resident. What is the most efficient mechanism?",
         ["an infinite loop thread", "a busy-wait timer", "a dedicated GPU process", "wait timers that wake only when needed"], "D",
         "Waitable timers let the thread sleep and be woken by the kernel only when the work is due."),
        ("ADVANCED", "Which statement about the Thread Environment Block (TEB) is correct?",
         ["it stores per-thread user-mode data such as the stack base and thread-local storage", "it is shared by all processes", "it is stored on the heap", "it contains the kernel scheduler queue"], "A",
         "The TEB holds thread-local user-mode information like stack limits and the thread-local storage array."),
    ],
    98: [
        ("BEGINNER", "Which registry hive contains settings specific to the current logged-in user?",
         ["HKEY_CURRENT_USER", "HKEY_LOCAL_MACHINE", "HKEY_CLASSES_ROOT", "HKEY_DYN_DATA"], "A",
         "HKEY_CURRENT_USER stores per-user configuration such as desktop settings and application preferences."),
        ("BEGINNER", "Which registry hive stores machine-wide configuration?",
         ["HKEY_CURRENT_USER", "HKEY_LOCAL_MACHINE", "HKEY_CURRENT_CONFIG", "HKEY_USERS"], "B",
         "HKEY_LOCAL_MACHINE holds settings that apply to the entire machine regardless of the logged-in user."),
        ("BEGINNER", "What is a registry hive?",
         ["a type of virus", "a set of registry keys, subkeys and values backed by a file such as SAM or SOFTWARE", "a user profile", "a type of DLL"], "C",
         "A hive is a logical group of registry data persisted to a backing file on disk."),
        ("BEGINNER", "Which tool is used to edit the registry on Windows?",
         ["explorer.exe", "taskmgr.exe", "cmd.exe", "regedit.exe"], "D",
         "regedit.exe is the registry editor that displays and modifies registry keys and values."),
        ("BEGINNER", "What is an Access Control List (ACL) used for?",
         ["granting or denying users access to objects such as files and registry keys", "listing installed programs", "storing passwords in plain text", "managing IP addresses"], "A",
         "ACLs define which users or groups may access an object and what operations they may perform."),
        ("BEGINNER", "Which account has the most privileges on a Windows machine by default?",
         ["Guest", "Administrator", "Standard User", "Network Service"], "B",
         "The Administrator account has the broadest privileges, including changing system-wide settings."),
        ("BEGINNER", "What is the purpose of User Account Control (UAC)?",
         ["to speed up login", "to replace the firewall", "to prompt for consent or credentials when a program needs administrator privileges", "to manage updates"], "C",
         "UAC asks for confirmation or credentials before allowing a process to run with elevated privileges."),
        ("BEGINNER", "Which Windows service authenticates users and grants them access tokens?",
         ["explorer", "LSA (Local Security Authority)", "spooler", "search"], "D",
         "The Local Security Authority authenticates users and creates the security tokens they use for access checks."),
        ("BEGINNER", "What is a security identifier (SID)?",
         ["a unique value that identifies a user, group or computer account", "a password", "a MAC address", "a registry value"], "A",
         "A SID uniquely identifies an account within a Windows domain or local machine."),
        ("BEGINNER", "Which statement about the SAM database is correct?",
         ["it stores the registry editor", "it stores local user account and password hash information", "it is a web browser", "it manages GPU drivers"], "B",
         "The Security Accounts Manager stores local user accounts, groups and password hashes."),
        ("INTERMEDIATE", "A standard user needs to run an installer that requires elevation. What does UAC do?",
         ["blocks it forever", "runs it without privileges", "displays a consent prompt so an administrator can approve or credentials can be supplied", "silently elevates every time"], "C",
         "UAC shows a consent or credential prompt, and only then does the process run elevated."),
        ("INTERMEDIATE", "Which registry data type stores a 32-bit integer?",
         ["REG_SZ", "REG_BINARY", "REG_EXPAND_SZ", "REG_DWORD"], "D",
         "REG_DWORD is the registry type for a 32-bit integer value."),
        ("INTERMEDIATE", "What is the difference between a DACL and a SACL?",
         ["a DACL controls access permissions while a SACL controls auditing", "they are identical", "a SACL stores passwords", "a DACL is only for the registry"], "A",
         "A DACL grants or denies access, while a SACL specifies which accesses are audited in the security log."),
        ("INTERMEDIATE", "Why should critical secrets such as passwords not be stored in the registry as plain text?",
         ["the registry is too slow", "plain text secrets can be read by any process with read access, so they should be protected or stored elsewhere", "the registry cannot store text", "because regedit is slow"], "B",
         "Storing secrets in plain text lets any process with registry read access exfiltrate them."),
        ("INTERMEDIATE", "Which mechanism does Windows use to grant a process the rights associated with its logged-in user?",
         ["the clipboard", "environment variables", "an access token that carries the user's privileges and group memberships", "the desktop wallpaper"], "C",
         "Each process has an access token describing the user and groups, which the security subsystem checks."),
        ("INTERMEDIATE", "Which registry path is typically used by a Windows service to store its settings?",
         ["HKCR", "HKCU Software only", "HKLM Hardware", "HKLM System CurrentControlSet Services"], "D",
         "Service configuration lives under HKLM System CurrentControlSet Services on the local machine."),
        ("INTERMEDIATE", "What is the primary purpose of combining a SACL with security event logging?",
         ["auditing who attempted to access an object and whether they succeeded", "speeding up the hard drive", "defragmenting keys", "caching login passwords"], "A",
         "SACL entries trigger audit events that record successful and failed access attempts for review."),
        ("INTERMEDIATE", "Which feature signs kernel drivers to prevent untrusted code from loading?",
         ["UAC", "driver signature enforcement and Secure Boot", "the registry", "Task Manager"], "B",
         "Driver signature enforcement and Secure Boot require kernel drivers to be signed by a trusted publisher."),
        ("INTERMEDIATE", "Why is it dangerous to grant a standard user membership in the Administrators group?",
         ["they cannot log in", "their programs will not run", "malware running as that user gains administrator-level control of the machine", "the registry is deleted"], "C",
         "Membership in Administrators gives any code running as that user full control over the machine."),
        ("INTERMEDIATE", "What does the registry's Last Known Good Configuration store?",
         ["the last password", "the user's last document", "a backup of all files", "the last successful boot configuration, used to recover from bad changes"], "D",
         "The Last Known Good configuration captures the settings from the last successful boot for recovery."),
        ("ADVANCED", "Malware adds an autostart entry to persist after reboot. Which registry location is most likely used?",
         ["HKCR dot exe", "HKEY_DYN_DATA", "HKLM SAM", "the Run and Services keys under the current user or machine hive"], "D",
         "Run keys and service definitions are common persistence points that the system loads at login or boot."),
        ("ADVANCED", "When a process tries to open a file, in what order does the security check occur?",
         ["the reference monitor checks the requested access against the object's DACL using the caller's token", "the file is opened then checked", "the registry is consulted first", "no check occurs"], "A",
         "The Security Reference Monitor validates the caller's token against the object's DACL before access is granted."),
        ("ADVANCED", "Why is a token associated with a process rather than with the code that runs?",
         ["code is not secure", "privileges must be tied to the user context that started the process, not to the code", "because tokens are files", "because the scheduler requires it"], "B",
         "Access decisions are based on the user who launched the process, so the token reflects that user context."),
        ("ADVANCED", "Which approach best protects registry configuration for a critical service?",
         ["give Everyone full control", "disable the service", "restrict the ACL to the service account and administrators, and back up the hive", "store passwords in the key"], "C",
         "Restricting the ACL minimizes who can alter the service settings, and backups enable recovery."),
        ("ADVANCED", "What is the effect of marking an ordinary program to always 'Run as administrator'?",
         ["it weakens the program", "it forces the program to always run elevated, increasing risk if the program is exploited", "it deletes the registry", "it blocks the program"], "D",
         "Always running elevated means a compromise of that program immediately yields full system privileges."),
        ("ADVANCED", "During an investigation, where should an analyst look first to confirm which programs run at login?",
         ["Run keys, the Startup folder, and scheduled tasks", "the Recycle Bin", "the paging file only", "the boot menu"], "A",
         "Run registry keys, the Startup folder and scheduled tasks are the standard places autostart entries are registered."),
        ("ADVANCED", "Why does Windows restrict access to the SAM hive even to administrators?",
         ["to save disk space", "to prevent offline password hash extraction by users who are not the system account", "to speed up boot", "to reduce CPU load"], "B",
         "The SAM contains password hashes, so only the system account can read it to prevent credential theft."),
        ("ADVANCED", "A security engineer wants to know which user attempted to delete a sensitive registry key. What must be configured?",
         ["UAC", "BitLocker", "a SACL audit entry on the key plus the security audit policy", "the paging file"], "C",
         "Auditing the key with a SACL entry and enabling the audit policy records deletion attempts in the event log."),
        ("ADVANCED", "Which statement about the built-in local Administrator account is most accurate for hardened systems?",
         ["everyone should use the default Administrator always", "it should be left unchanged", "the built-in Administrator should be renamed and disabled, and local accounts limited", "it is required for updates"], "D",
         "Renaming and disabling the built-in Administrator reduces the risk of credential-based attacks against a known account."),
        ("ADVANCED", "How does the Security Reference Monitor relate to other components?",
         ["it centralizes access checks so all objects are validated against the caller's token and the object's ACL", "it draws windows", "it schedules threads", "it compresses the registry"], "A",
         "The reference monitor is the single point through which all object access checks pass, enforcing consistent security."),
    ],
    99: [
        ("BEGINNER", "Which kernel forms the foundation of both iOS and macOS?",
         ["XNU", "Linux", "MS-DOS", "FreeBSD userland only"], "A",
         "XNU is Apple's hybrid kernel derived from Mach and BSD that powers both iOS and macOS."),
        ("BEGINNER", "Which company develops the Android operating system?",
         ["Apple", "Google", "Microsoft", "IBM"], "B",
         "Android is developed by Google, built on a Linux kernel and a large app ecosystem."),
        ("BEGINNER", "What is the primary user interface framework for iOS apps?",
         ["UIKit", "Win32", "Cocoa", "GTK"], "C",
         "UIKit provides the views, controls and lifecycle support that iOS apps are built with."),
        ("BEGINNER", "What file format packages a macOS application so it can be moved as one unit?",
         ["APK", "an app bundle", "exe", "deb"], "D",
         "A macOS app is distributed as a .app bundle containing the executable, resources and metadata."),
        ("BEGINNER", "Which layer in iOS handles low-level networking and Unix services?",
         ["Darwin", "Cocoa Touch", "Media", "Core Services"], "A",
         "Darwin, the core OS layer, provides Unix services and networking underneath the higher iOS layers."),
        ("BEGINNER", "Which language is Apple's recommended modern language for iOS and macOS development?",
         ["Swift", "COBOL", "JavaScript", "PHP"], "B",
         "Swift is Apple's modern, type-safe language designed for building apps across its platforms."),
        ("BEGINNER", "What is an Android APK?",
         ["a backup", "a theme", "the package format containing an app's code and resources", "a virus"], "C",
         "An APK is the installable package that bundles an Android app's code, assets and manifest."),
        ("BEGINNER", "Which component of Android executes an app's compiled code?",
         ["the HAL", "the launcher", "the notification bar", "the ART (Android Runtime)"], "D",
         "ART is the Android Runtime that compiles and executes the bytecode of installed apps."),
        ("BEGINNER", "What does app sandboxing do on iOS and macOS?",
         ["restricts each app to its own container and limited system resources", "lets apps access everything", "speeds up the GPU", "removes security checks"], "A",
         "Sandboxing confines each app to its own container so it cannot access other apps' data."),
        ("BEGINNER", "Which type of memory management is used by Swift's ARC?",
         ["manual memory allocation only", "automatic reference counting that frees objects when their references drop to zero", "garbage collection", "no memory management"], "B",
         "ARC inserts retain and release operations so objects are deallocated automatically when no references remain."),
        ("INTERMEDIATE", "A developer wants to run native C code on Android for performance. Which toolchain is used?",
         ["Xcode", "Visual Studio", "the Android NDK (Native Development Kit)", "Cocoa"], "C",
         "The NDK lets developers compile native C and C++ libraries for use in Android apps."),
        ("INTERMEDIATE", "What happens to an iOS app that enters the background for an extended period?",
         ["it keeps running forever", "it is deleted", "it slows down the device", "it is suspended and may be terminated by the system to reclaim memory"], "D",
         "iOS suspends background apps and terminates them under memory pressure to keep the device responsive."),
        ("INTERMEDIATE", "Which Android component is an activity?",
         ["a single focused screen the user interacts with", "a background service", "a content provider", "an intent filter"], "A",
         "An activity represents one user-facing screen with its own layout and lifecycle."),
        ("INTERMEDIATE", "What is the purpose of Android's Binder IPC?",
         ["rendering graphics", "enabling efficient inter-process communication between apps and system services", "managing the battery", "compiling apps"], "B",
         "Binder provides the fast, kernel-mediated channel that apps and system services use to talk to each other."),
        ("INTERMEDIATE", "Which macOS technology lets multiple tasks run concurrently with low overhead?",
         ["Grand Central Dispatch (GCD)", "the Finder", "Spotlight", "Time Machine"], "C",
         "GCD manages thread pools and dispatch queues so work can run concurrently with little overhead."),
        ("INTERMEDIATE", "What is FileVault on macOS?",
         ["a file compression tool", "a web browser", "a developer framework", "full-disk encryption for the startup volume"], "D",
         "FileVault encrypts the startup volume so data is unreadable without the proper credentials."),
        ("INTERMEDIATE", "Which component handles permission requests for sensitive resources on macOS?",
         ["the TCC (Transparency, Consent, and Control) framework", "the Dock", "Safari", "the App Store"], "A",
         "TCC prompts users and grants or denies apps access to resources like camera, microphone and files."),
        ("INTERMEDIATE", "What is the primary role of an Android app's manifest file?",
         ["styling the UI", "declaring components, permissions, and features the app requires", "storing user data", "signing the app"], "B",
         "The manifest declares the app's components, required permissions and features to the system."),
        ("INTERMEDIATE", "Which statement about the iOS app lifecycle is correct?",
         ["apps can run unlimited work in the background", "apps receive events like launch, resign active, and terminate, and should save state at transitions", "apps never terminate", "apps control the kernel"], "C",
         "Apps move through defined lifecycle states and must persist state because they can be suspended or terminated."),
        ("INTERMEDIATE", "Why does Android typically run each app in its own Linux process?",
         ["to reduce RAM", "to speed up the UI", "to save battery", "isolation and security between apps"], "D",
         "Separate processes keep apps isolated so one app cannot read another app's memory or data."),
        ("ADVANCED", "A messaging app needs to receive notifications while closed. What is the recommended mobile approach?",
         ["run a polling thread forever", "keep the screen on", "use the platform push service such as APNs or FCM rather than a persistent background socket", "disable the radio"], "D",
         "Platform push services deliver messages efficiently without a battery-draining persistent connection."),
        ("ADVANCED", "Why do iOS background tasks have strict time limits?",
         ["background execution drains battery and memory, so the OS bounds it to keep the device responsive", "to increase CPU speed", "to prevent file writes", "to simplify code signing"], "A",
         "Limiting background work preserves battery life and keeps the device responsive for the user."),
        ("ADVANCED", "Which strategy reduces an Android app's memory footprint when the OS kills its process?",
         ["ignore it", "save instance state and restore it on recreation", "increase the heap", "disable background data"], "B",
         "Persisting instance state lets the app recreate its UI after the process is killed and restarted."),
        ("ADVANCED", "What is the key difference between a virtual machine and a container in backend deployments?",
         ["none", "containers run without an OS", "a VM virtualizes hardware with its own OS while a container shares the host kernel and isolates processes", "a VM is always faster"], "C",
         "VMs include a full guest OS, whereas containers share the host kernel and isolate processes and namespaces."),
        ("ADVANCED", "A macOS app must perform a long computation without freezing the UI. What is the appropriate pattern?",
         ["run it on the main thread", "sleep the main thread", "run it on the main thread after a delay", "dispatch the work to a background queue via GCD and update the UI on the main queue"], "D",
         "Moving heavy work off the main thread keeps the UI responsive, and UI updates must return to the main thread."),
        ("ADVANCED", "Which statement best describes iOS app memory management with ARC?",
         ["ARC inserts retain and release calls at compile time, so objects are freed when no strong references remain", "ARC runs a garbage collector at runtime", "ARC disables memory management", "ARC is only for games"], "A",
         "ARC adds automatic retain and release at compile time so memory is reclaimed based on reference counts."),
        ("ADVANCED", "Why does Android require apps to declare permissions in the manifest?",
         ["to increase app size", "so users can review and grant access to sensitive resources at install or runtime", "to improve compile speed", "to satisfy app store screenshots"], "B",
         "Declaring permissions lets users make informed decisions about the sensitive data an app may access."),
        ("ADVANCED", "Which is the main reason a sandboxed iOS app cannot modify another app's container?",
         ["the container is read-only", "filesystem access is limited by the kernel to the app's own sandbox", "apps are too small", "the App Store blocks it"], "C",
         "The kernel enforces each app's sandbox, restricting filesystem access to the app's own container."),
        ("ADVANCED", "For a crash reporter, why is symbolication necessary?",
         ["to encrypt logs", "to compress reports", "to hide internal names", "to map crash stack addresses back to readable function names in the app binary"], "D",
         "Symbolication converts raw memory addresses in a crash log into readable function and line information."),
        ("ADVANCED", "Which approach best manages the interaction between a UI thread and a slow network call in Android?",
         ["perform the call off the main thread, such as with a coroutine or async task, and post results back to the main thread", "block the main thread", "call twice", "use a broadcast"], "A",
         "Offloading network work avoids blocking the UI, and posting results back to the main thread updates the UI safely."),
    ],
    100: [
        ("BEGINNER", "What is a hypervisor?",
         ["software that creates and runs virtual machines", "a web server", "a firewall", "a database"], "A",
         "A hypervisor is the software layer that creates and manages virtual machines on a host."),
        ("BEGINNER", "Which type of hypervisor runs directly on the hardware?",
         ["Type 2", "Type 1 (bare-metal)", "Type 3", "hosted"], "B",
         "A Type 1 hypervisor runs directly on the hardware without a host operating system."),
        ("BEGINNER", "Which product is a Type 1 hypervisor?",
         ["VirtualBox", "VMware ESXi", "Wine", "Docker Desktop only"], "C",
         "VMware ESXi is a bare-metal Type 1 hypervisor, while VirtualBox is a hosted Type 2 hypervisor."),
        ("BEGINNER", "What is the main benefit of virtualization?",
         ["faster networks", "running multiple isolated operating systems on one physical host", "free RAM", "better graphics"], "D",
         "Virtualization lets many isolated guest OSes share a single physical server."),
        ("BEGINNER", "What is a container?",
         ["a lightweight, isolated environment that shares the host OS kernel", "a physical server", "a virtual machine", "a hard drive"], "A",
         "Containers package an application with its dependencies and share the host kernel for isolation."),
        ("BEGINNER", "Which tool is the most common container runtime?",
         ["MySQL", "Docker", "Apache", "Nginx"], "B",
         "Docker is the most widely used container runtime and image tooling ecosystem."),
        ("BEGINNER", "What is the difference between a Docker image and a running container?",
         ["An image is a read-only template while a container is a live, writable instance created from it", "An image is a running process", "A container is stored only on the registry", "There is no difference"], "A",
         "A Docker image is an immutable template of layers, and a running container is a writable instance that executes from that template."),
        ("BEGINNER", "What is a virtual machine's disk file often called?",
         ["a container layer", "an image tag", "a registry", "a virtual disk, such as VMDK, VHDX or VDI"], "D",
         "A VM stores its virtual hard drive in a file format like VMDK, VHDX or VDI."),
        ("BEGINNER", "Which file describes how to build a Docker image?",
         ["Dockerfile", "Docker.conf", "docker.ini", "Docker.ps1"], "A",
         "A Dockerfile contains the instructions that build and configure a Docker image."),
        ("BEGINNER", "What is a container image layer?",
         ["a kind of network", "a read-only filesystem layer that builds on previous layers", "a VM snapshot", "a load balancer"], "B",
         "Images are built from stacked read-only layers, each representing a step in the build process."),
        ("INTERMEDIATE", "Which Linux kernel feature isolates and limits resources such as CPU, memory and devices for containers?",
         ["SELinux only", "AppArmor", "cgroups", "systemd"], "C",
         "Control groups (cgroups) allocate and limit CPU, memory and device resources for container processes."),
        ("INTERMEDIATE", "Which Linux feature gives a container its own view of processes and network?",
         ["namespaces", "the scheduler", "iptables", "the page cache"], "D",
         "Namespaces isolate process, network, mount and other views so containers appear to have their own system."),
        ("INTERMEDIATE", "What is the difference between a virtual machine and a container?",
         ["a VM has its own OS and kernel while a container shares the host kernel", "containers are slower", "VMs are lighter", "there is no difference"], "A",
         "VMs each run a full guest OS, while containers share the host kernel and isolate only the application environment."),
        ("INTERMEDIATE", "What does it mean to horizontally scale a containerized application?",
         ["Increasing the number of running instances to handle more load", "Increasing the memory of a single instance", "Shrinking the image size", "Moving the app to a bigger node"], "A",
         "Horizontal scaling adds more replicas of an application to spread load across nodes, whereas vertical scaling enlarges one instance."),
        ("INTERMEDIATE", "Which feature lets you move a VM's state to another host with little downtime?",
         ["a container image", "live migration or a snapshot", "a Dockerfile", "a registry push"], "C",
         "Live migration transfers a running VM to another host with minimal interruption, and snapshots capture state for rollback."),
        ("INTERMEDIATE", "What is Docker Hub?",
         ["a hypervisor", "a container runtime", "a VPN", "a public registry where container images are stored and shared"], "D",
         "Docker Hub is a hosted registry service for publishing and pulling public container images."),
        ("INTERMEDIATE", "Why are containers generally more efficient than VMs at running many instances?",
         ["containers share the host kernel and start faster with less overhead", "containers use more RAM", "VMs have no kernel", "containers cannot run Linux"], "A",
         "Sharing the host kernel removes the per-instance OS overhead, so containers start quickly and use fewer resources."),
        ("INTERMEDIATE", "What is a Docker volume?",
         ["a temporary directory", "persistent storage that survives container recreation", "a network interface", "a CPU allocation"], "B",
         "Volumes provide durable storage that remains available even after a container is recreated."),
        ("INTERMEDIATE", "Which of the following is a Type 2 hypervisor?",
         ["Xen", "KVM", "VirtualBox", "Nutanix AHV"], "C",
         "VirtualBox runs as a hosted application on top of an existing operating system, making it a Type 2 hypervisor."),
        ("INTERMEDIATE", "What is a snapshot of a VM?",
         ["a backup of a single file", "a saved state of the VM's disks and memory that can be reverted to", "a compressed image", "a network rule"], "D",
         "A snapshot captures the VM's disk and optionally memory state so it can be restored later."),
        ("ADVANCED", "A cloud provider wants strong isolation between many containers sharing one kernel. Which feature is critical?",
         ["the Dockerfile", "image tagging", "port forwarding", "user namespaces and seccomp to limit the blast radius"], "D",
         "User namespaces and seccomp reduce kernel attack surface, limiting damage if one container is compromised."),
        ("ADVANCED", "Which mechanism lets a hypervisor overcommit memory safely?",
         ["ballooning and page sharing, where guests return unused pages", "disabling swap", "increasing vCPU count", "using more NICs"], "A",
         "Balloon drivers reclaim unused guest memory and page sharing deduplicates identical pages to enable overcommit."),
        ("ADVANCED", "What is a nested virtualization concern for security teams?",
         ["it is always safe", "a guest hypervisor requires host CPU virtualization extensions and adds complexity and risk", "it doubles the kernel", "it is illegal"], "B",
         "Nesting depends on virtualization extensions and adds another layer whose escaping could compromise the host."),
        ("ADVANCED", "Why is a stateless container preferable for horizontal scaling?",
         ["it is smaller", "it is faster", "state in ephemeral layers is lost on restart, so scaling adds replicas and stores data externally", "it uses more memory"], "C",
         "Stateless containers are interchangeable, so replicas can be added and removed without data loss."),
        ("ADVANCED", "Which practice best describes immutable infrastructure?",
         ["updating servers in place", "patching live VMs", "restarting services nightly", "never modifying running instances and replacing them with new images"], "D",
         "Immutable infrastructure treats servers as disposable, replacing them with freshly built images instead of patching."),
        ("ADVANCED", "An administrator runs a privileged container. What is the security implication?",
         ["the container escapes many restrictions and can access host kernel resources, so it must be trusted", "it is perfectly safe", "it gets a new kernel", "it cannot access the network"], "A",
         "Privileged mode disables many container isolation barriers, granting the container deep host access."),
        ("ADVANCED", "Which approach reduces VM image sprawl and speeds up provisioning?",
         ["copying full VMDKs each time", "using templates, thin provisioning, and a shared image library", "increasing RAM", "using more vCPUs"], "B",
         "Templates and thin provisioning reuse a shared base and allocate space only as needed, cutting sprawl."),
        ("ADVANCED", "When a Dockerfile uses several layers and you change only the final RUN line, what happens on rebuild?",
         ["all layers rebuild", "cached earlier layers are reused and only the changed layer is rebuilt", "the image is deleted", "the container restarts"], "C",
         "Docker caches unchanged layers and rebuilds only from the first changed instruction onward."),
        ("ADVANCED", "Which Kubernetes object defines the desired number of identical container replicas?",
         ["a Service", "a ConfigMap", "a Volume", "a Deployment"], "D",
         "A Deployment manages a replica set that keeps the specified number of identical pods running."),
        ("ADVANCED", "What is the primary reason to combine VMs and containers in one architecture?",
         ["VMs provide strong isolation and hardware abstraction while containers add density and fast scaling", "containers cannot run Linux", "VMs are cheaper", "containers provide isolation from the host"], "A",
         "Using both layers lets teams get VM-grade isolation where needed and container density and speed elsewhere."),
    ],
}
