# -*- coding: utf-8 -*-
"""
Question bank for subject 1: PROG101 - C Programming.
Category: Programming & Software Development.

Topics:
  1: Fundamentals of C
  2: Control Structures & Loops
  3: Functions & Recursion
  4: Pointers & Memory Management
  5: Arrays & Strings

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    1: [
        ("BEGINNER", "Which keyword declares a double-precision floating point variable in C?",
         ["double", "float", "long double", "int"], "A",
         "double is the C keyword for a double-precision floating-point type, typically 8 bytes."),
        ("BEGINNER", "What is the name of the function at which every C program begins execution?",
         ["start", "main", "begin", "entry"], "B",
         "Execution of a C program always begins in the function named main."),
        ("BEGINNER", "Which of the following is a valid C identifier?",
         ["2score", "score value", "_score", "int"], "C",
         "_score is valid because identifiers must start with a letter or underscore and contain no spaces or reserved words."),
        ("BEGINNER", "Which symbol must end every statement in C?",
         [".", ",", ";", ":"], "D",
         "A semicolon terminates each C statement, including declarations and expression statements."),
        ("BEGINNER", "What does the %f format specifier print in C?",
         ["a floating-point number", "an integer", "a character", "a memory address"], "A",
         "%f tells printf to print a floating-point value in decimal notation."),
        ("BEGINNER", "Which data type is typically used to store a single character?",
         ["int", "char", "float", "double"], "B",
         "char is the C data type designed to hold one character, stored as its ASCII code."),
        ("BEGINNER", "Which header file declares printf and scanf?",
         ["stdlib.h", "string.h", "stdio.h", "math.h"], "C",
         "stdio.h (standard input/output) declares the printf and scanf functions."),
        ("BEGINNER", "Which operator compares two values for equality in C?",
         ["=", "!=", "!", "=="], "D",
         "The == operator tests whether two operands are equal, while a single = is assignment."),
        ("BEGINNER", "Which of the following is a comment in C?",
         ["// this is a comment", "/* this is a comment", "# this is a comment", "REM this is a comment"], "A",
         "The // prefix starts a single-line comment, which is ignored by the compiler."),
        ("BEGINNER", "What does the sizeof operator return?",
         ["the address of a variable", "the size in bytes of a type or variable", "the number of elements in an array", "the length of a string"], "B",
         "sizeof evaluates to the size in bytes of its operand, whether a type or a variable."),
        ("INTERMEDIATE", "Consider int x = 7, y = 2; what is the value of x % y in C?",
         ["3", "2", "1", "0"], "C",
         "The modulo operator returns the remainder of integer division, and 7 divided by 2 leaves a remainder of 1."),
        ("INTERMEDIATE", "Consider double result = 5.0 / 2; what value is stored in result?",
         ["2", "2.0", "3", "2.5"], "D",
         "Because 5.0 is a double, the division is performed in floating point and the exact result 2.5 is stored."),
        ("INTERMEDIATE", "Consider int a = 10, b = 3; what is the value of a / b in C?",
         ["3", "3.33", "4", "2"], "A",
         "Integer division truncates the fractional part, so 10 / 3 evaluates to 3."),
        ("INTERMEDIATE", "Consider int x = 5; x += 3; what is the final value of x?",
         ["5", "8", "3", "15"], "B",
         "The compound assignment x += 3 is shorthand for x = x + 3, so x becomes 8."),
        ("INTERMEDIATE", "What is the value of the expression 3 + 4 * 2 in C?",
         ["14", "20", "11", "9"], "C",
         "Multiplication has higher precedence than addition, so 4 * 2 is computed first and the result is 11."),
        ("INTERMEDIATE", "Consider int x = 5; int y = x++; what is the value of y after the assignment?",
         ["6", "4", "7", "5"], "D",
         "The postfix ++ operator returns the original value 5 first, then increments x, so y is 5."),
        ("INTERMEDIATE", "Consider int x = 5; int y = ++x; what is the value of y after the assignment?",
         ["6", "5", "7", "4"], "A",
         "The prefix ++ operator increments x to 6 first, then yields that new value, so y is 6."),
        ("INTERMEDIATE", "Which operator returns the remainder of integer division in C?",
         ["/", "%", "*", "&"], "B",
         "The % operator computes the remainder of dividing two integers."),
        ("INTERMEDIATE", "Consider int x = 5.9; what is the value stored in x?",
         ["6", "5.9", "5", "0"], "C",
         "Converting a floating-point value to an int truncates the fractional part, so x holds 5."),
        ("INTERMEDIATE", "Consider float f = 5 / 2; what value is stored in f?",
         ["2", "2.5", "0.5", "2.0"], "D",
         "Both operands are ints, so 5 / 2 performs integer division yielding 2, which is then widened to 2.0 for the float."),
        ("ADVANCED", "Which of the following expressions may evaluate differently on a 32-bit system versus a 64-bit system?",
         ["sizeof(char*)", "sizeof(char)", "sizeof(short)", "sizeof(int)"], "A",
         "The size of a pointer depends on the target architecture, commonly 4 bytes on 32-bit and 8 bytes on 64-bit."),
        ("ADVANCED", "What does the expression 2 + 3 * 2 - 4 / 2 evaluate to in C?",
         ["10", "6", "4", "8"], "B",
         "With operator precedence, 3 * 2 is 6 and 4 / 2 is 2, so the result is 2 + 6 - 2 = 6."),
        ("ADVANCED", "On a system where int is 32 bits, what happens when the signed int 2147483647 is increased by 1?",
         ["-2147483648", "2147483648", "undefined behaviour", "0"], "C",
         "Signed integer overflow is undefined behaviour in C, so no reliable result can be assumed."),
        ("ADVANCED", "Consider int x = 10 at file scope and int x = 20 inside main. What does printf('%d', x) print inside main?",
         ["10", "30", "20", "undefined"], "D",
         "The local declaration shadows the global variable inside main, so the local value 20 is printed."),
        ("ADVANCED", "You need a type whose only meaningful values are RED, GREEN and BLUE. Which approach is best in C?",
         ["enum Color { RED, GREEN, BLUE };", "#define RED 0", "char color = 'r';", "struct Color { int red; };"], "A",
         "An enum groups the named constants into one type, giving the compiler a way to reason about the values."),
        ("ADVANCED", "What is the value of int y = x + x++ when x is 5?",
         ["10", "undefined behaviour", "11", "12"], "B",
         "Reading x and modifying x++ in the same expression without a sequence point is undefined behaviour in C."),
        ("ADVANCED", "Which expression toggles (flips) bit 3 of an int variable named flags?",
         ["flags |= 8", "flags &= 8", "flags ^= 8", "flags <<= 3"], "C",
         "Bitwise XOR with a mask containing a 1 at bit 3 flips exactly that bit while leaving others unchanged."),
        ("ADVANCED", "Given #define SQUARE(x) x * x, what does SQUARE(2 + 3) evaluate to?",
         ["25", "12", "13", "11"], "D",
         "Macro arguments are substituted textually, giving 2 + 3 * 2 + 3, which evaluates to 11, not 25."),
        ("ADVANCED", "Which storage class gives a variable static storage duration but makes it visible only within the file where it is declared?",
         ["static", "extern", "register", "auto"], "A",
         "At file scope, static gives a variable internal linkage so it is not visible to other translation units."),
        ("ADVANCED", "On a little-endian machine, how are the bytes of an int holding 0x00000001 stored in memory?",
         ["00 00 00 01", "01 00 00 00", "00 00 01 00", "00 00 00 00"], "B",
         "Little-endian storage places the least significant byte first, so 0x01 is written to the lowest address."),
    ],
    2: [
        ("BEGINNER", "Which keyword makes a decision in a C program based on a condition?",
         ["if", "while", "for", "switch"], "A",
         "The if statement evaluates a condition and decides whether a block of code executes."),
        ("BEGINNER", "Which loop guarantees that its body executes at least once?",
         ["while", "do-while", "for", "switch"], "B",
         "The do-while loop checks its condition after the body, so the body always runs at least once."),
        ("BEGINNER", "Which loop is most natural when the number of iterations is known in advance?",
         ["while", "do-while", "for", "goto"], "C",
         "The for loop packs initialization, condition and update into one header, making fixed counts clear."),
        ("BEGINNER", "Which statement immediately terminates a loop?",
         ["continue", "return", "break", "exit"], "D",
         "The break statement stops execution of the innermost loop or switch immediately."),
        ("BEGINNER", "Which statement skips the rest of the current iteration and jumps to the next one?",
         ["continue", "break", "goto", "return"], "A",
         "continue abandons the remaining body of the current iteration and moves on to the next loop iteration."),
        ("BEGINNER", "How does C treat a condition in an if statement?",
         ["zero", "nonzero", "one always", "-1 always"], "B",
         "In C any nonzero value is true and zero is false, so the condition simply needs a nonzero result."),
        ("BEGINNER", "Which of the following is valid if statement syntax in C?",
         ["if x > 0 { }", "if (x > 0) { }", "if x > 0 then { }", "if [x > 0] { }"], "C",
         "The condition must be enclosed in parentheses and the controlled block follows in braces."),
        ("BEGINNER", "When does the code in an else block execute?",
         ["always runs", "runs when the condition is false", "runs only if no if exists", "runs when the condition is true"], "D",
         "The else block runs when the preceding if condition evaluates to false."),
        ("BEGINNER", "Which operator performs logical AND in C?",
         ["&&", "||", "!", "&"], "A",
         "&& is the logical AND operator, returning true only when both operands are true."),
        ("BEGINNER", "Which loop checks its condition at the top, before the body runs?",
         ["for", "while", "do-while", "switch"], "B",
         "A while loop evaluates its condition first, so the body may never execute if the condition is false initially."),
        ("INTERMEDIATE", "How many times does the body of for (int i = 0; i < 3; i++) execute?",
         ["2", "4", "3", "infinite"], "C",
         "The loop runs for i equal to 0, 1 and 2, which is 3 iterations in total."),
        ("INTERMEDIATE", "How many times does a while loop run when x starts at 0 and the condition is x < 5 with x incremented once per pass?",
         ["4", "6", "infinite", "5"], "D",
         "x takes the values 0 through 4 while the condition holds, giving exactly 5 iterations."),
        ("INTERMEDIATE", "How many times does printf run given an outer loop of 2 iterations and an inner loop of 3 iterations?",
         ["6", "5", "8", "9"], "A",
         "The inner loop runs 3 times for each of the 2 outer iterations, so printf executes 2 * 3 = 6 times."),
        ("INTERMEDIATE", "What is printed by switch (x) when x is 2 and the case 2 branch prints the word two?",
         ["one", "two", "other", "one two"], "B",
         "The switch matches x to case 2, which prints the word two and then hits its break."),
        ("INTERMEDIATE", "Consider int x = 0; do { x++; } while (x < 5); What is the final value of x?",
         ["4", "6", "5", "0"], "C",
         "x is incremented until it reaches 5, at which point the condition x < 5 becomes false."),
        ("INTERMEDIATE", "When is the body of if (a > 5 && b < 3) executed?",
         ["when at least one is true", "when a > 5 is false", "when b >= 3", "when both are true"], "D",
         "The && operator requires both conditions to be true for the whole condition to be true."),
        ("INTERMEDIATE", "Consider int y = (x > 0) ? x : -x; with x = -4. What is y?",
         ["4", "-4", "0", "8"], "A",
         "Since -4 is not greater than 0, the ternary selects the false branch -x, which is 4."),
        ("INTERMEDIATE", "What grade is printed when score is 85 with score >= 90 giving A, score >= 80 giving B and otherwise C?",
         ["A", "B", "C", "F"], "B",
         "85 fails the first branch but satisfies score >= 80, so the grade B is printed."),
        ("INTERMEDIATE", "In for (i = 0; i < 10; i++) with break when i == 3, how many iterations occur?",
         ["10", "3", "4", "0"], "C",
         "The loop runs for i = 0, 1, 2 and 3, and break stops it at the start of the fourth iteration."),
        ("INTERMEDIATE", "In for (i = 0; i < 5; i++) with continue when i == 2, how many times does printf in the body run?",
         ["5", "3", "2", "4"], "D",
         "The iteration where i is 2 is skipped by continue, so printf runs for the other 4 values."),
        ("ADVANCED", "In nested if-else statements, which if does an else bind to?",
         ["the nearest unmatched if", "the first if in the file", "the last if in the file", "the if with braces"], "A",
         "An else attaches to the nearest preceding if that does not already have an else, which is the dangling else rule."),
        ("ADVANCED", "When branching on many distinct integer constant values, which construct is usually clearest and most efficient?",
         ["a long if-else chain", "a switch statement", "a while loop", "a function pointer array"], "B",
         "A switch maps many distinct constant cases cleanly and can be compiled into efficient jump tables."),
        ("ADVANCED", "What happens in while (i < 10) { printf('%d', i); } when i is 0 and never changes inside the body?",
         ["prints 10 times", "prints 9 times", "runs forever", "crashes immediately"], "C",
         "Because i is never incremented, the condition stays true and the loop never terminates."),
        ("ADVANCED", "Why is if (p != NULL && *p == 10) safe even when p is NULL?",
         ["&& always evaluates both sides", "*p is never checked", "short-circuit evaluation stops if p is NULL", "NULL dereference is caught automatically"], "D",
         "Logical && short-circuits: if p is NULL the second operand is never evaluated, so *p is not dereferenced."),
        ("ADVANCED", "How many iterations does for (i = 0, j = 10; i < j; i++, j--) perform?",
         ["5", "10", "6", "infinite"], "A",
         "Each iteration moves i up and j down, and i < j holds for 5 passes before the boundaries cross."),
        ("ADVANCED", "In a switch, what happens if a case is reached and no break appears before the next case label?",
         ["jumps to default", "execution falls through to the next case", "skips all remaining cases", "terminates the program"], "B",
         "Without a break, control falls through and continues executing the statements of subsequent cases."),
        ("ADVANCED", "In which situation is goto considered a reasonable choice in C?",
         ["replacing every loop", "as a goto for every early return", "error handling and cleanup in deeply nested loops", "never acceptable in C"], "C",
         "goto is occasionally the clearest way to jump to shared cleanup code when unwinding from deeply nested loops."),
        ("ADVANCED", "In nested loops, what does break inside the inner loop do?",
         ["the whole program", "all nested loops", "only the outer loop", "only the inner loop"], "D",
         "break terminates the innermost loop containing it, leaving any outer loops to continue running."),
        ("ADVANCED", "In C99 and later, a variable declared in the init part of a for loop goes out of scope where?",
         ["at the end of the for loop", "at the end of the function", "at the end of the file", "never goes out of scope"], "A",
         "The loop variable is scoped to the for statement itself, so it is not visible after the loop ends."),
        ("ADVANCED", "Inside a do-while loop, what does a continue statement do?",
         ["skips the condition check", "jumps to the condition check", "restarts the loop body from the start", "is a syntax error in do-while"], "B",
         "In a do-while loop continue jumps to the condition evaluation, which may then terminate the loop."),
    ],
    3: [
        ("BEGINNER", "Which keyword declares a function that returns no value?",
         ["void", "int", "null", "empty"], "A",
         "void is used as the return type of a function that produces no result."),
        ("BEGINNER", "If a function is defined after the point where it is called, what must appear before the call?",
         ["the function body must be inline", "a prototype (declaration) must appear before the call", "the function must be named main", "no declaration is ever needed"], "B",
         "A function prototype tells the compiler the return type and parameters before the function is used."),
        ("BEGINNER", "What are the values passed into a function called?",
         ["return values", "arguments (parameters)", "global variables", "labels"], "C",
         "Values passed to a function are its arguments, matching the parameters declared in the definition."),
        ("BEGINNER", "What does the return statement do?",
         ["prints a value", "ends the whole program", "sends a value back to the caller and exits the function", "restarts the function"], "D",
         "return hands a value back to the caller and immediately stops execution of the function."),
        ("BEGINNER", "What is a recursive function?",
         ["a function that calls itself", "a function with no parameters", "a function that returns void", "a function declared inside another"], "A",
         "Recursion is the technique where a function calls itself to solve a smaller version of the same problem."),
        ("BEGINNER", "What stops a recursive function from calling itself forever?",
         ["the recursive call", "the base case", "the parameter list", "the return type"], "B",
         "The base case is a condition that returns directly without recursing, terminating the chain of calls."),
        ("BEGINNER", "Which of the following shows the correct syntax for a function definition?",
         ["function name() { }", "return_type { }", "return_type name(params) { }", "name(params) return_type { }"], "C",
         "A C function definition starts with the return type, then the name, parameters, and a body in braces."),
        ("BEGINNER", "What happens if a function declared to return int reaches its end without a return statement?",
         ["returns 0 automatically", "returns void", "results in undefined behaviour", "returns the last expression value"], "D",
         "Falling off the end of a non-void function without returning is undefined behaviour in C."),
        ("BEGINNER", "What are local variables in C?",
         ["variables declared inside a function, accessible only there", "variables declared at file scope", "variables passed by the caller", "constants defined with #define"], "A",
         "A local variable is declared inside a function and is only accessible within that function."),
        ("BEGINNER", "Which keyword makes a local variable keep its value between calls to the same function?",
         ["extern", "static", "register", "const"], "B",
         "static local variables retain their value across function calls because they live for the whole program."),
        ("INTERMEDIATE", "Consider int add(int a, int b) { return a + b; } What does add(3, 4) return?",
         ["12", "34", "7", "1"], "C",
         "The function adds its two arguments, so 3 + 4 evaluates to 7."),
        ("INTERMEDIATE", "When a function receives an int by value and modifies it, what happens to the caller's variable?",
         ["the caller's variable changes to the new value", "the address is copied and modified", "the caller's variable is unchanged", "compilation fails"], "D",
         "C passes arguments by value, so the function changes only its local copy, never the caller's variable."),
        ("INTERMEDIATE", "What does factorial(4) return when factorial(n) is n times factorial(n - 1) and factorial(0) is 1?",
         ["24", "16", "8", "12"], "A",
         "factorial(4) expands to 4 * 3 * 2 * 1, which equals 24."),
        ("INTERMEDIATE", "What does fibonacci(5) return when fibonacci(0) is 0 and fibonacci(1) is 1?",
         ["8", "5", "3", "13"], "B",
         "The Fibonacci sequence 0, 1, 1, 2, 3, 5 has 5 as its sixth term, which is fibonacci(5)."),
        ("INTERMEDIATE", "A function returns int and executes return 3.7; What value does the caller receive?",
         ["3.7", "4", "3", "0"], "C",
         "The double 3.7 is implicitly converted to int by truncation, so the caller receives 3."),
        ("INTERMEDIATE", "Which of the following is a correct prototype for a function f that takes two ints and returns a float?",
         ["float f(int, int);", "int f(float, float);", "f(float, int);", "float f(int);"], "D",
         "A prototype states the return type, the name and the parameter types, so float f(int, int); matches the description."),
        ("INTERMEDIATE", "What does power(2, 3) return when power(x, n) is x times power(x, n - 1) and power(x, 0) is 1?",
         ["8", "6", "9", "16"], "A",
         "power(2, 3) multiplies three factors of 2, giving 2 * 2 * 2 = 8."),
        ("INTERMEDIATE", "What is printed by this code: int g = 5; void f(void) { g = 10; } int main(void) { f(); printf('%d', g); return 0; }",
         ["5", "10", "0", "undefined"], "B",
         "The function f assigns 10 to the global g, and main prints the updated global value 10."),
        ("INTERMEDIATE", "What does f(-3) return for int f(int x) { if (x < 0) return 0; return x * 2; }?",
         ["-6", "6", "0", "undefined"], "C",
         "Because -3 is less than 0, the early return 0 executes and the caller receives 0."),
        ("INTERMEDIATE", "Which of the following correctly calls a function named print_square with the argument 4?",
         ["print_square 4;", "print_square();", "square(4);", "print_square(4);"], "D",
         "A function call uses the function name followed by parentheses containing the arguments."),
        ("ADVANCED", "What happens when a recursive function has no base case?",
         ["stack overflow, causing the program to crash", "the function returns 0", "the recursion stops automatically", "the program prints an error and continues"], "A",
         "Endless recursion keeps pushing new stack frames until memory runs out, causing a stack overflow and crash."),
        ("ADVANCED", "What is tail recursion?",
         ["recursion with two base cases", "the recursive call is the very last operation", "recursion using a while loop", "a function that returns void"], "B",
         "In tail recursion the recursive call is the final operation, which some compilers can optimize into a loop."),
        ("ADVANCED", "If a function contains a static int counter, how many distinct counter variables exist across three calls?",
         ["a new variable per call", "three separate variables", "one variable shared across calls", "a variable stored on the heap"], "C",
         "A static local is created once and shared across all calls, so only a single counter exists."),
        ("ADVANCED", "Compared with an iterative loop, what is a typical downside of a deeply recursive solution?",
         ["recursion is always faster", "recursion cannot compute sums", "recursion requires pointers", "recursion uses more stack memory for each call"], "D",
         "Every recursive call pushes a new frame on the stack, so deep recursion consumes significantly more memory."),
        ("ADVANCED", "You want to pass one function as an argument to another function in C. What do you pass?",
         ["a function pointer", "a copy of the function", "the function name as a string", "a void pointer"], "A",
         "Functions can be passed indirectly through function pointers, which store the address of the function."),
        ("ADVANCED", "Which signature correctly allows a function to swap two int values in the caller's scope?",
         ["void swap(int a, int b)", "void swap(int *a, int *b)", "int swap(int a, int b)", "void swap(int **a, int *b)"], "B",
         "Passing pointers to the two variables lets the function write through them and modify the originals."),
        ("ADVANCED", "What does sum(5) return when sum(n) is n + sum(n - 1) and sum(0) is 0?",
         ["10", "20", "15", "5"], "C",
         "sum(5) evaluates to 5 + 4 + 3 + 2 + 1 + 0, which equals 15."),
        ("ADVANCED", "A function returns a pointer to a local variable declared inside it. Why is this dangerous?",
         ["the value is copied safely", "the compiler warns but it is always safe", "the variable moves to the heap", "the address becomes invalid after return, causing undefined behaviour"], "D",
         "The local variable is destroyed when the function returns, leaving the pointer dangling and its use undefined."),
        ("ADVANCED", "Why is it good practice to pass a large struct by const pointer rather than by value?",
         ["avoid copying the whole struct and prevent accidental modification", "allow changing the caller's data", "store the struct on the heap", "allow the function to return the pointer"], "A",
         "A const pointer avoids copying the entire struct and guarantees the function cannot modify the original."),
        ("ADVANCED", "For computing x raised to n quickly with large n, which recursive strategy is most efficient?",
         ["linear recursion decrementing n by 1", "divide-and-conquer squaring that halves n each step", "always using a for loop", "computing the factorial first"], "B",
         "Exponentiation by squaring halves n each recursion level, reducing the work to about log2(n) multiplications."),
    ],
    4: [
        ("BEGINNER", "Which operator returns the memory address of a variable?",
         ["&", "*", "->", "."], "A",
         "The address-of operator & produces the memory address where a variable is stored."),
        ("BEGINNER", "Which operator is used to dereference a pointer to access the value it points to?",
         ["&", "*", "->", "!"], "B",
         "The indirection operator * follows a pointer to access the value stored at the address it holds."),
        ("BEGINNER", "How do you declare a pointer to an integer in C?",
         ["int ptr;", "int *ptr;", "ptr int;", "int &ptr;"], "C",
         "A pointer declaration uses * before the name, so int *ptr; declares ptr as a pointer to int."),
        ("BEGINNER", "What value does a pointer variable store?",
         ["a copy of the value", "a function", "the memory address of a variable", "a string literal"], "D",
         "A pointer stores the memory address of another variable rather than a normal data value."),
        ("BEGINNER", "What does NULL represent in C?",
         ["a pointer that points to nothing", "a value of 1", "an empty string", "a pointer to the first byte of memory"], "A",
         "NULL is a special pointer value that indicates the pointer is not pointing to any valid object."),
        ("BEGINNER", "Which function allocates memory on the heap in C?",
         ["new", "malloc", "create", "allocate"], "B",
         "malloc allocates a block of memory from the heap and returns a pointer to it."),
        ("BEGINNER", "Which function releases memory that was previously allocated on the heap?",
         ["delete", "dispose", "free", "release"], "C",
         "free returns a previously malloc-ed block to the heap so the memory can be reused."),
        ("BEGINNER", "What is a dangling pointer?",
         ["a pointer to a constant", "a pointer that points to memory that has been freed or destroyed", "a null pointer", "a pointer to a pointer"], "D",
         "A dangling pointer still holds an address, but the object it referenced has been freed or destroyed."),
        ("BEGINNER", "Which header file must be included to use malloc and free?",
         ["stdlib.h", "stdio.h", "string.h", "math.h"], "A",
         "stdlib.h declares the memory allocation functions malloc and free."),
        ("BEGINNER", "What does int **ptr represent?",
         ["a pointer to a char", "a pointer to a pointer to an int", "an array of two ints", "a function pointer"], "B",
         "Two stars mean ptr holds the address of a pointer that points to an int, i.e. a pointer to a pointer."),
        ("INTERMEDIATE", "Consider int x = 5; int *p = &x; *p = 10; What is the value of x?",
         ["5", "0", "10", "undefined"], "C",
         "Dereferencing p writes 10 through the pointer, and p points to x, so x becomes 10."),
        ("INTERMEDIATE", "Consider int a[] = {1, 2, 3}; int *p = a; What does *(p + 1) evaluate to?",
         ["1", "3", "0", "2"], "D",
         "Pointer arithmetic advances by the element size, so p + 1 points to a[1], which is 2."),
        ("INTERMEDIATE", "How many bytes does int *p = malloc(5 * sizeof(int)); request when int is 4 bytes?",
         ["20", "5", "40", "10"], "A",
         "Each int is 4 bytes and there are 5 of them, so the allocation requests 5 * 4 = 20 bytes."),
        ("INTERMEDIATE", "If p points to the start of an array, what does p + 2 point to?",
         ["arr[0]", "arr[2]", "arr[3]", "the byte after the array"], "B",
         "Adding 2 advances the pointer by two elements, so p + 2 points to the element at index 2."),
        ("INTERMEDIATE", "What happens if you dereference a NULL pointer in C?",
         ["returns 0", "returns NULL", "undefined behaviour, typically a crash", "is always safe"], "C",
         "Dereferencing NULL is undefined behaviour and in practice usually causes a segmentation fault."),
        ("INTERMEDIATE", "Consider int x = 5; int *p = &x; int *q = &x; *p = 9; printf('%d', *q); What is printed?",
         ["5", "0", "8", "9"], "D",
         "Both pointers refer to the same variable x, so assigning through p also changes what q reads."),
        ("INTERMEDIATE", "Consider int x = 3; int *p = &x; int **pp = &p; What does **pp evaluate to?",
         ["3", "the address of p", "the address of x", "a compilation error"], "A",
         "Dereferencing twice follows pp to p and then p to x, yielding the value 3."),
        ("INTERMEDIATE", "What does it mean when malloc returns NULL?",
         ["the memory is zeroed", "allocation failed; the program should handle it", "the pointer points to garbage", "the program must call free"], "B",
         "A NULL result from malloc means the requested memory could not be allocated and should be handled."),
        ("INTERMEDIATE", "How does calloc differ from malloc?",
         ["calloc is faster than malloc", "calloc never fails", "calloc zero-initializes the allocated memory", "calloc allocates on the stack"], "C",
         "calloc allocates memory and initializes every byte to zero, whereas malloc leaves the memory uninitialized."),
        ("INTERMEDIATE", "When a function receives an int * and assigns *ptr = 42, what is the effect on the caller?",
         ["only a copy is modified", "the caller sees no change", "the program crashes", "the caller's variable is modified"], "D",
         "Writing through the pointer changes the object the caller passed, since the pointer still targets it."),
        ("ADVANCED", "A program allocates memory with malloc but loses the only pointer to it without calling free. What is the result?",
         ["the allocated block becomes unreachable and is never freed, wasting memory", "the program crashes immediately", "the memory is returned to the stack", "the compiler reclaims it automatically"], "A",
         "Losing the last pointer to allocated memory without freeing it is a memory leak that wastes heap space."),
        ("ADVANCED", "What happens if the same pointer is passed to free twice?",
         ["is always safe", "causes undefined behaviour", "reallocates the block", "returns the memory to the heap safely"], "B",
         "Freeing a block twice corrupts the heap allocator state and is undefined behaviour in C."),
        ("ADVANCED", "After free(p) is called, why is using p again unsafe?",
         ["the pointer becomes NULL automatically", "the memory is still valid", "using the pointer after free is undefined behaviour", "free reallocates it"], "C",
         "free makes the block available for reuse, so accessing it through the stale pointer is undefined behaviour."),
        ("ADVANCED", "What happens when pointer arithmetic moves a pointer beyond the bounds of its array?",
         ["wraps around safely", "always yields a valid pointer", "is undefined behaviour", "returns NULL"], "D",
         "Computing an address outside the array bounds is undefined behaviour and must be avoided."),
        ("ADVANCED", "Where in memory does a malloc-allocated block live?",
         ["the heap", "the stack", "the register file", "the code segment"], "A",
         "malloc draws memory from the heap, a dynamic region separate from the function call stack."),
        ("ADVANCED", "Why must the old pointer be considered invalid after a successful realloc?",
         ["the old pointer remains valid", "the block may move and the old pointer becomes invalid", "realloc never fails", "realloc requires free first"], "B",
         "realloc may move the block to a new address, making the previously returned pointer stale."),
        ("ADVANCED", "Why is casting the result of malloc optional in C?",
         ["the cast is required in C", "C does not allow void* conversions", "in C a void* converts implicitly to any object pointer type, so the cast is optional", "malloc returns a char pointer"], "C",
         "malloc returns void*, and in C that converts implicitly to any object pointer type without a cast."),
        ("ADVANCED", "What happens if you compare two pointers that point into different arrays using relational operators?",
         ["compares their addresses correctly", "is always true", "is undefined behaviour", "is a syntax error"], "D",
         "Relational comparisons of pointers to different arrays are undefined behaviour, although equality checks are allowed."),
        ("ADVANCED", "Which function signature best communicates that it creates an array of n ints that the caller must eventually free?",
         ["int *make_array(int n);", "void make_array(int n, int out);", "int make_array(int *n);", "char *make_array(int n);"], "A",
         "Returning an int* shows the caller receives heap memory and is responsible for calling free on it."),
        ("ADVANCED", "Forgetting to free a small allocation inside a long-running loop leads to what?",
         ["the program speeds up", "memory usage grows steadily and may exhaust memory", "the program crashes immediately", "the block is freed automatically"], "B",
         "Each iteration leaks another block, so memory usage climbs until the program runs out of memory."),
    ],
    5: [
        ("BEGINNER", "What is the index of the first element in a C array?",
         ["0", "1", "-1", "2"], "A",
         "Array indexing in C starts at zero, so the first element is at index 0."),
        ("BEGINNER", "Which of the following declares an array of 5 integers?",
         ["int arr(5);", "int arr[5];", "array arr[5];", "int[5] arr;"], "B",
         "Square brackets after the name with a size give int arr[5]; which holds 5 int elements."),
        ("BEGINNER", "How is the end of a string marked in C?",
         ["with a newline character", "with a space", "with a null character", "with a zero-length array"], "C",
         "C strings are terminated by a null character whose value is zero."),
        ("BEGINNER", "Which function from string.h returns the length of a string?",
         ["strlen", "strcpy", "strcmp", "strcat"], "D",
         "strlen counts characters until the null terminator and returns that count."),
        ("BEGINNER", "Which function copies one string into another?",
         ["strcpy", "strcat", "strlen", "strchr"], "A",
         "strcpy copies the source string, including its null terminator, into the destination."),
        ("BEGINNER", "How many bytes does the string literal used in char s[] = 'C'; occupy?",
         ["1", "2", "3", "4"], "B",
         "The one visible character plus the null terminator gives a total of 2 bytes."),
        ("BEGINNER", "Which function compares two strings lexicographically in C?",
         ["strcat", "strlen", "strcmp", "sprintf"], "C",
         "strcmp compares two strings character by character and returns a value indicating their order."),
        ("BEGINNER", "If s is a properly terminated string, where does printf('%s', s) stop printing?",
         ["the first null character", "the first space", "the end of the array always", "the first newline"], "D",
         "%s prints characters until it reaches the null terminator, which signals the end of the string."),
        ("BEGINNER", "How do you access the third element of int arr[10]?",
         ["arr[2]", "arr[3]", "arr[1]", "arr[4]"], "A",
         "The third element is at index 2 because indices start at 0."),
        ("BEGINNER", "Which statement about array bounds in C is correct?",
         ["the compiler rejects out-of-bounds code", "C performs no automatic bounds checking at runtime", "arrays check bounds only in debug builds", "bounds are checked by the hardware automatically"], "B",
         "C does not automatically check array indices, so out-of-bounds access is the programmer's responsibility."),
        ("INTERMEDIATE", "Consider int a[] = {10, 20, 30, 40}; What is a[1] + a[2]?",
         ["30", "40", "50", "70"], "C",
         "a[1] is 20 and a[2] is 30, so their sum is 50."),
        ("INTERMEDIATE", "What is printed by this code: int a[] = {1, 2, 3, 4}; int s = 0; for (int i = 0; i < 4; i++) s += a[i]; printf('%d', s);",
         ["24", "12", "9", "10"], "D",
         "The loop adds 1, 2, 3 and 4 together, producing a total of 10."),
        ("INTERMEDIATE", "Consider char s[10] = 'Hi'; What does strlen(s) return?",
         ["2", "10", "3", "1"], "A",
         "strlen counts the two characters H and i, ignoring the array size and the null terminator."),
        ("INTERMEDIATE", "What risk exists when copying a large string into a small buffer with strcpy?",
         ["it is always safe", "it may overflow the destination buffer, corrupting memory", "it pads with zeros", "it truncates automatically"], "B",
         "strcpy does not check the destination size, so a source longer than the buffer causes a buffer overflow."),
        ("INTERMEDIATE", "What does strcmp('abc', 'abd') return?",
         ["0", "1", "a negative value", "an undefined value"], "C",
         "The strings match until 'c' versus 'd', and since 'c' is less than 'd', strcmp returns a negative value."),
        ("INTERMEDIATE", "In int m[2][3], which element does m[1][2] refer to?",
         ["first row, third column", "second row, second column", "first row, second column", "second row, third column"], "D",
         "The first index selects row 1 (the second row) and the second index selects column 2 (the third column)."),
        ("INTERMEDIATE", "When an array is passed to a function, what happens to its type?",
         ["it decays to a pointer, so sizeof inside the function reports the pointer size", "it is copied entirely", "it becomes a string", "it doubles in size"], "A",
         "Array parameters decay to pointers, so the function sees no size information about the original array."),
        ("INTERMEDIATE", "Consider char s[] = 'hello'; What does sizeof(s) give?",
         ["5", "6", "10", "4"], "B",
         "The array holds the five letters plus the null terminator, so sizeof(s) is 6."),
        ("INTERMEDIATE", "Given char *p = 'hello';, is it safe to execute p[0] = 'H';?",
         ["it works and prints Hello", "it is a compile error", "it is undefined behaviour because string literals may be read-only", "it changes the literal globally"], "C",
         "String literals may live in read-only memory, so modifying one through a pointer is undefined behaviour."),
        ("INTERMEDIATE", "A loop counts characters while the current character is not the null terminator. What does the counter equal at the end?",
         ["the length of the string", "the size of the array", "the number of spaces", "the memory address"], "D",
         "Stepping through until the null terminator yields exactly the number of characters in the string."),
        ("ADVANCED", "For holding many short strings, which storage arrangement typically uses less memory?",
         ["an array of pointers such as char *names[]", "a two-dimensional char array such as char names[][20]", "a single char array", "an array of structs"], "A",
         "An array of pointers stores each string exactly once, while a 2D char array reserves the full width for every row."),
        ("ADVANCED", "For a row-major 2D array with rows rows and cols columns, which expression locates element m[i][j]?",
         ["base + (j * rows + i)", "base + (i * cols + j)", "base + (i * rows + j)", "base + i * j"], "B",
         "Row-major layout skips i full rows of cols elements and then j elements, giving base + (i * cols + j) elements."),
        ("ADVANCED", "Which declaration creates a modifiable array containing the text hello?",
         ["char *p = 'hello';", "char *p = malloc(5);", "char s[] = 'hello';", "static char *p = 'hello';"], "C",
         "char s[] = 'hello'; copies the characters into a writable local array, unlike a pointer to a literal."),
        ("ADVANCED", "What can happen when code writes past the last valid index of an array?",
         ["it is caught by the compiler", "the extra data is stored in a safe area", "the array grows automatically", "it can overwrite adjacent memory, causing undefined behaviour"], "D",
         "Out-of-bounds writes can corrupt neighboring data on the stack or heap, which is undefined behaviour."),
        ("ADVANCED", "What does %s do if the char array it is given has no null terminator?",
         ["prints until it finds a null character, potentially overrunning the array if none exists", "always stops after the array size", "prints exactly one character", "prints only the first word"], "A",
         "printf prints on until it finds a null terminator, so a missing one causes it to read past the array."),
        ("ADVANCED", "Which parameter declaration correctly receives a 2D array of ints with a fixed number of columns?",
         ["int m[][]", "int m[][COLS]", "int *m[]", "int m[ROWS][]"], "B",
         "The column count must be given so the compiler can compute row offsets, as in int m[][COLS]."),
        ("ADVANCED", "Inside void f(int a[]) { }, what does sizeof(a) report?",
         ["the number of elements", "the array size in bytes", "the size of a pointer", "a compile error"], "C",
         "The parameter decays to a pointer, so sizeof(a) returns the pointer size rather than the array size."),
        ("ADVANCED", "Which description best fits a robust string-copy function?",
         ["it should assume the destination is large enough", "it should check for NULL arguments and copy at most n characters safely", "it should always use strcpy", "it should return void"], "D",
         "A safe copy function verifies its arguments and uses a bound such as n to avoid overflowing the destination."),
        ("ADVANCED", "While traversing a 2D array with a pointer, what must you add to move from the first element of one row to the first of the next?",
         ["add the number of columns", "add 1", "add sizeof(int)", "add the number of rows"], "A",
         "Each row is cols elements long, so adding cols to the pointer steps to the start of the next row."),
        ("ADVANCED", "Consider char s[] = 'hello'; After swapping s[0] with s[4], which character is now at index 0?",
         ["h", "e", "o", "l"], "B",
         "s[0] is h and s[4] is o, so after the swap the first position holds the letter o."),
    ],
}
