# -*- coding: utf-8 -*-
"""
Question bank for subject 3: PROG103 - Java Programming.

Topics:
  11: Java Basics & Variables
  12: Control Flow & Loops
  13: Object Oriented Programming
  14: Java Collections Framework
  15: Exception Handling & Streams

Each topic has exactly 30 questions: 10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED.
"""

QUESTIONS = {
    11: [
        ("BEGINNER", "What does the acronym JVM stand for in the Java platform?",
         ["Java Virtual Machine", "Java Variable Manager", "Java Version Module", "Just-in-time Virtual Method"], "A",
         "JVM stands for Java Virtual Machine, the engine that executes Java bytecode."),
        ("BEGINNER", "Which tool compiles Java source code (.java) into bytecode (.class) files?",
         ["java", "javac", "jar", "javadoc"], "B",
         "The javac compiler translates .java source files into portable .class bytecode files."),
        ("BEGINNER", "Which of the following is a primitive data type in Java?",
         ["String", "Scanner", "char", "ArrayList"], "C",
         "char is a primitive type in Java; String, Scanner, and ArrayList are reference types."),
        ("BEGINNER", "Which primitive type stores a single Unicode character in Java?",
         ["boolean", "byte", "char", "int"], "C",
         "char stores a single 16-bit Unicode character in Java."),
        ("BEGINNER", "What is the size in bits of the int primitive type in Java?",
         ["8", "16", "64", "32"], "D",
         "The int type in Java is a 32-bit signed two's-complement integer."),
        ("BEGINNER", "What is the default value of an uninitialized int instance field in Java?",
         ["0", "null", "undefined", "1"], "A",
         "Instance fields of type int are initialized to 0 by the JVM before the constructor runs."),
        ("BEGINNER", "Which operator computes the remainder of an integer division in Java?",
         ["/", "%", "&", "#"], "B",
         "The modulo operator % returns the remainder of a division, such as 7 % 3 giving 1."),
        ("BEGINNER", "Which keyword is used to declare a constant variable in Java?",
         ["constant", "static", "final", "const"], "C",
         "The final keyword makes a variable immutable so its value cannot be reassigned after initialization."),
        ("BEGINNER", "What is the data type of the expression 5 > 3 in Java?",
         ["int", "boolean", "double", "byte"], "B",
         "Relational operators such as > always evaluate to a boolean result, true or false."),
        ("BEGINNER", "Which primitive type can store only the values true or false?",
         ["boolean", "int", "char", "float"], "A",
         "The boolean type represents logical values and can only hold true or false."),
        ("INTERMEDIATE", "Given int x = 10; double y = 3.0; what is the value of x / y?",
         ["3", "3.33", "3.3333333333333335", "4"], "C",
         "Because y is a double, x is promoted to double before division, producing the double result 3.3333333333333335."),
        ("INTERMEDIATE", "What is the value of int result = 17 % 5;?",
         ["3", "2", "12", "3.4"], "B",
         "17 divided by 5 leaves a remainder of 2, so the modulo operator yields 2."),
        ("INTERMEDIATE", "What happens when you compile byte b = 5; byte c = b + 1;?",
         ["It compiles and c stores 6", "It fails to compile because b + 1 is an int and cannot be assigned to byte without a cast",
          "It compiles but throws an exception at runtime", "It compiles and c stores 51"], "B",
         "Binary arithmetic promotes byte operands to int, so b + 1 is an int and needs an explicit cast to fit a byte."),
        ("INTERMEDIATE", "Why does long seconds = 1234567890123; fail to compile?",
         ["The value exceeds the long range", "The literal is treated as an int and is too large without the L suffix",
          "long variables cannot store negative numbers", "Numbers with more than 10 digits are invalid literals"], "B",
         "An integer literal without a suffix is an int, and 1234567890123 overflows the int range, so the L suffix is required."),
        ("INTERMEDIATE", "What is the value of x after this code runs? int x = 5; x++;",
         ["5", "6", "4", "55"], "B",
         "The post-increment operator adds 1 to x, changing its value from 5 to 6."),
        ("INTERMEDIATE", "Given int a = 5; int b = a++; what are the values of a and b?",
         ["a is 6, b is 5", "a is 5, b is 6", "a is 6, b is 6", "a is 5, b is 5"], "A",
         "In a++ the expression evaluates to the old value 5 before the increment, so b is 5 and a becomes 6."),
        ("INTERMEDIATE", "What is the value of total after this code? int total = 10; total += 5;",
         ["5", "15", "105", "10"], "B",
         "The compound assignment operator += adds 5 to the current value, giving total = 15."),
        ("INTERMEDIATE", "What is the result of the expression 'A' + 1 in Java?",
         ["A1", "66", "65", "Compilation error"], "B",
         "The char 'A' is promoted to its numeric Unicode value 65, and 65 + 1 equals the int 66."),
        ("INTERMEDIATE", "What is the value of the expression 7 / 2 * 2.0 in Java?",
         ["7.0", "6.0", "7", "6.5"], "B",
         "Integer division 7 / 2 truncates to 3, then 3 is promoted to double and multiplied by 2.0 giving 6.0."),
        ("INTERMEDIATE", "Which of the following is a valid variable declaration following the camelCase convention?",
         ["int myVariableName;", "int MyVariableName;", "int my_variable_name;", "int myvariable name;"], "A",
         "camelCase, as in myVariableName, is the Java convention for naming local variables, and spaces are not allowed in identifiers."),
        ("ADVANCED", "What is the output of this code? Integer a = 127; Integer b = 127; System.out.println(a == b);",
         ["true", "false", "Compilation error", "It throws NullPointerException"], "A",
         "The Integer cache reuses instances from -128 to 127, so both variables reference the same cached object and == returns true."),
        ("ADVANCED", "What is the output of this code? Integer a = 128; Integer b = 128; System.out.println(a == b);",
         ["true", "false", "Compilation error", "It throws a NumberFormatException"], "B",
         "128 is outside the Integer cache range of -128 to 127, so autoboxing creates two distinct objects and == compares references."),
        ("ADVANCED", "Given int x = 5; System.out.println(x == 5 ? \"yes\" : \"no\"); what is printed?",
         ["yes", "no", "true", "false"], "A",
         "The condition x == 5 is true, so the ternary operator evaluates to the first branch and prints 'yes'."),
        ("ADVANCED", "What does the volatile keyword guarantee for a shared variable in a multi-threaded program?",
         ["Atomic updates for compound operations", "That reads and writes always see the latest value from main memory",
          "That the variable is immutable", "That the variable is visible only inside its thread"], "B",
         "volatile prevents caching of the variable in thread-local storage so every read sees the latest write."),
        ("ADVANCED", "In which memory area of the JVM are instance variables stored?",
         ["The stack", "The heap", "The method area", "The program counter register"], "B",
         "Objects and their instance fields live on the heap, while local variables and references live on the stack."),
        ("ADVANCED", "Which sequence correctly represents the widening primitive conversions in Java?",
         ["double -> float -> long -> int -> short -> byte", "byte -> short -> int -> long -> float -> double",
          "int -> long -> byte -> double -> short -> float", "float -> double -> int -> long -> byte -> short"], "B",
         "Widening goes from smaller to larger types: byte, short, int, long, float, and finally double."),
        ("ADVANCED", "Why does double d = 0.1 + 0.2; fail to produce exactly 0.3?",
         ["Because double is limited to 7 significant digits", "Because 0.1 and 0.2 cannot be represented exactly in binary floating point",
          "Because + is not defined for doubles", "Because the variables are truncated to int before addition"], "B",
         "Floating-point values like 0.1 and 0.2 have infinite binary representations, so the sum is a close approximation rather than exactly 0.3."),
        ("ADVANCED", "What is printed by this code? String a = new String(\"java\"); String b = \"java\"; System.out.println(a == b);",
         ["true", "false", "java", "It throws an exception"], "B",
         "new String creates a distinct object, so a and b refer to different instances and reference equality via == is false."),
        ("ADVANCED", "What is the value of x after executing int x = 8 >> 1;?",
         ["4", "16", "8", "2"], "A",
         "The right shift operator moves each bit one position right, which divides 8 by 2 to give 4."),
        ("ADVANCED", "What is the value of x after executing int x = 1 << 4;?",
         ["4", "8", "16", "32"], "C",
         "Shifting 1 left by 4 positions multiplies it by 2 four times, giving 16."),
    ],
    12: [
        ("BEGINNER", "Which keyword begins a conditional block in Java?",
         ["switch", "loop", "if", "while"], "C",
         "The if keyword introduces a conditional statement that executes a block when its boolean expression is true."),
        ("BEGINNER", "Which control structure executes a block repeatedly while a condition is true?",
         ["if", "switch", "for-each", "while"], "D",
         "A while loop repeats its body as long as the boolean condition evaluates to true."),
        ("BEGINNER", "Which loop is guaranteed to execute its body at least once?",
         ["for", "do-while", "while", "foreach"], "B",
         "A do-while loop checks its condition after running the body, so the body always executes at least once."),
        ("BEGINNER", "Which loop is best suited when the number of iterations is known in advance?",
         ["while", "do-while", "for", "switch"], "C",
         "A for loop with init, condition, and update clauses is ideal for counting a known number of iterations."),
        ("BEGINNER", "Which keyword immediately exits the current loop in Java?",
         ["continue", "return", "break", "exit"], "C",
         "The break statement terminates the enclosing loop or switch and transfers control to the statement after it."),
        ("BEGINNER", "Which keyword skips the current iteration and moves to the next one in a loop?",
         ["break", "continue", "skip", "next"], "B",
         "The continue statement skips the rest of the current iteration and jumps to the loop's next iteration."),
        ("BEGINNER", "Which operator checks whether two values are equal in a condition?",
         ["=", "==", "equals", "<>"], "B",
         "The double equals operator == compares two values for equality, while a single = is assignment."),
        ("BEGINNER", "What does the && operator do in a boolean condition?",
         ["It evaluates to true only if both operands are true", "It evaluates to true if either operand is true",
          "It negates the operand", "It performs bitwise XOR"], "A",
         "The logical AND operator && is true only when both of its operands are true."),
        ("BEGINNER", "What is the syntax of the ternary conditional operator in Java?",
         ["condition ? valueIfTrue : valueIfFalse", "condition : valueIfTrue ? valueIfFalse",
          "valueIfTrue ? valueIfFalse : condition", "condition ?? valueIfTrue"], "A",
         "The ternary operator evaluates the condition and returns the first value if true, otherwise the second."),
        ("BEGINNER", "Which statement allows execution to branch to a case label based on a value?",
         ["if-else", "switch", "do", "while"], "B",
         "A switch statement selects one of several case blocks by matching the value of its selector expression."),
        ("INTERMEDIATE", "How many times does this loop body execute? for (int i = 0; i < 3; i++) {}",
         ["2", "3", "4", "0"], "B",
         "The loop runs while i is 0, 1, and 2, which is three iterations before i becomes 3 and stops."),
        ("INTERMEDIATE", "What is the final value of i after this code? int i = 0; while (i < 5) { i++; }",
         ["4", "5", "6", "3"], "B",
         "The loop stops when i reaches 5 because the condition i < 5 becomes false at that point."),
        ("INTERMEDIATE", "What does this code print? int i = 0; do { i++; } while (i < 0); System.out.println(i);",
         ["0", "1", "It prints nothing", "It throws an exception"], "B",
         "The do-while body runs once before the condition is checked, so i becomes 1 and the loop ends."),
        ("INTERMEDIATE", "What is the output of this switch statement given int x = 2; switch (x) { case 1: System.out.print(\"A\"); case 2: System.out.print(\"B\"); case 3: System.out.print(\"C\"); }?",
         ["BC", "B", "ABC", "C"], "A",
         "Without break statements, execution falls through from case 2 to case 3, printing 'BC'."),
        ("INTERMEDIATE", "How many total iterations occur for the nested loops for (int i = 0; i < 3; i++) { for (int j = 0; j < 2; j++) {} }?",
         ["5", "6", "3", "9"], "B",
         "The outer loop runs 3 times and the inner loop runs 2 times for each, giving 3 x 2 = 6 total iterations."),
        ("INTERMEDIATE", "What is the index of the last character in the String \"hello\"?",
         ["5", "4", "6", "0"], "B",
         "String indices are zero-based and length() returns 5, so the last character is at index 4."),
        ("INTERMEDIATE", "What does this loop print? for (int i = 0; i < 5; i++) { if (i == 2) continue; System.out.print(i); }",
         ["01234", "0134", "0124", "01"], "B",
         "When i equals 2 the continue skips the print, so the output is the digits 0, 1, 3, 4 as '0134'."),
        ("INTERMEDIATE", "Why does the condition x > 0 && y / x > 1 never throw ArithmeticException when x is 0?",
         ["Because division is not supported for integers", "Because && short-circuits and skips the right side when x > 0 is false",
          "Because the JVM silently ignores the error", "Because y is always positive"], "B",
         "The && operator short-circuits: if the left operand is false, the right operand is never evaluated."),
        ("INTERMEDIATE", "Which loop is correct for iterating over all elements of an array named scores?",
         ["for (int score : scores) {}", "for (score : scores) {}", "for (int score; scores) {}", "for (scores : int score) {}"], "A",
         "The enhanced for loop syntax for (int score : scores) iterates over each element of the array in order."),
        ("INTERMEDIATE", "What is the value of count after this code? int count = 0; for (int i = 1; i <= 4; i += 2) { count++; }",
         ["2", "4", "3", "1"], "A",
         "i takes the values 1 and 3 before becoming 5, so the loop runs twice and count is 2."),
        ("ADVANCED", "What happens if you try to modify a List while iterating it with an enhanced for loop?",
         ["It compiles and works silently", "It throws a ConcurrentModificationException at runtime",
          "It throws a compile-time error", "The modification affects only the next iteration"], "B",
         "The enhanced for loop uses a fail-fast iterator that detects structural modification and throws ConcurrentModificationException."),
        ("ADVANCED", "What is the output of this code? for (int i = 0; i < 5; i--) { if (i == -2) break; System.out.print(i); }",
         ["54321", "0", "01234", "0-1"], "B",
         "The loop starts at 0, prints 0, then decrements; the break at i == -2 exits before printing -1 or -2."),
        ("ADVANCED", "What does this code print? int i = 3; while (i-- > 0) { System.out.print(i); }",
         ["210", "3210", "320", "21"], "A",
         "The post-decrement i-- evaluates the old value 3, 2, 1 as conditions and leaves i at 2, 1, 0 for printing, giving '210'."),
        ("ADVANCED", "Which type of value can a switch statement test using modern Java, beyond int and String?",
         ["Only boolean", "Enums", "Only double", "Only long"], "B",
         "Since Java 7 String is allowed and switch has always supported char, byte, short, int, and enum constants."),
        ("ADVANCED", "What is the purpose of a labeled break statement in Java?",
         ["To exit a single if block", "To exit an outer loop from inside a nested loop",
          "To skip the current iteration of an outer loop", "To declare a loop variable"], "B",
         "A labeled break terminates the named enclosing loop, allowing control to leave a nested loop structure entirely."),
        ("ADVANCED", "Which loop always executes its body at least once and checks the condition afterward?",
         ["for", "while", "do-while", "enhanced for"], "C",
         "The do-while loop evaluates its condition after the body, guaranteeing the body runs once even if the condition is false."),
        ("ADVANCED", "What is the final value of i in this code? int i; for (i = 0; i < 10; i += 2) {}",
         ["10", "9", "8", "12"], "A",
         "i increments by 2 each pass and the loop stops when i reaches 10, because the condition i < 10 fails at 10."),
        ("ADVANCED", "What is the output of this code? int x = 5; if (x % 2 == 0) { System.out.println(\"even\"); } else { System.out.println(\"odd\"); }",
         ["even", "odd", "5", "Nothing is printed"], "B",
         "Since 5 % 2 equals 1, the if condition is false and the else branch prints 'odd'."),
        ("ADVANCED", "Which of these expressions evaluates to true?",
         ["!(5 > 3)", "(4 == 5) || (2 < 3)", "(1 == 1) && (2 == 3)", "(7 < 2) && (3 > 1)"], "B",
         "The OR operator is true when either operand is true, and since 2 < 3 is true the whole expression is true."),
        ("ADVANCED", "Why is it recommended to declare loop variables such as i inside the for statement?",
         ["To make the variable global", "To limit its scope to the loop and avoid accidental reuse and collisions",
          "To improve garbage collection performance", "To allow the loop to be nested deeper"], "B",
         "Block-scoped loop variables are inaccessible outside the loop, preventing accidental modification elsewhere in the method."),
    ],
    13: [
        ("BEGINNER", "Which keyword is used to define a new class in Java?",
         ["new", "class", "interface", "object"], "B",
         "The class keyword introduces a class definition that can contain fields, constructors, and methods."),
        ("BEGINNER", "Which operator creates a new object in Java?",
         ["new", "create", "make", "this"], "A",
         "The new operator allocates an object on the heap and invokes its constructor."),
        ("BEGINNER", "What is a constructor in Java?",
         ["A method that is called automatically when an object is created", "A method that sorts data",
          "A keyword that deletes objects", "A variable shared by all instances"], "A",
         "A constructor is a special method, named after the class, that initializes a newly created object."),
        ("BEGINNER", "Which keyword declares a member that belongs to the class rather than to instances?",
         ["instance", "static", "global", "shared"], "B",
         "The static keyword makes a field or method shared by all instances and accessible through the class name."),
        ("BEGINNER", "Which keyword is used to make one class inherit from another class?",
         ["implements", "extends", "inherits", "super"], "B",
         "The extends keyword establishes an inheritance relationship, letting a subclass reuse parent behavior."),
        ("BEGINNER", "What kind of methods can an interface declare by default?",
         ["Concrete methods with full bodies", "Abstract methods without a body",
          "Private methods only", "Static variables only"], "B",
         "Traditionally an interface declares abstract methods that implementing classes must provide bodies for."),
        ("BEGINNER", "What is encapsulation in object-oriented programming?",
         ["Bundling data and the methods that operate on it while hiding internal details",
          "Allowing a class to have many constructors", "Storing data in a database",
          "Reusing code through inheritance"], "A",
         "Encapsulation combines state and behavior in a class and uses access modifiers to hide internal implementation."),
        ("BEGINNER", "Which access modifier makes a field accessible only within the same class?",
         ["public", "protected", "private", "package"], "C",
         "The private modifier restricts access so only methods of the declaring class can read or modify the field."),
        ("BEGINNER", "What is polymorphism in Java?",
         ["The ability of a method to have different behavior based on the actual object type",
          "Storing many values in one variable", "The speed of the garbage collector",
          "Converting a char to an int"], "A",
         "Polymorphism lets a single method name behave differently depending on the runtime type of the object it is called on."),
        ("BEGINNER", "Which method does System.out.println automatically call to print an object?",
         ["print", "toString", "hashCode", "display"], "B",
         "The println method calls toString() on the object to obtain its textual representation."),
        ("INTERMEDIATE", "In the code Animal a = new Dog(); which constructor is invoked?",
         ["Animal only", "Dog then implicitly Animal", "Animal then Dog", "Neither constructor"], "B",
         "Creating a Dog runs the Dog constructor, which implicitly calls super() to run the Animal constructor first."),
        ("INTERMEDIATE", "What is the difference between method overloading and method overriding?",
         ["Overloading has the same name and different parameters in the same class; overriding redefines a parent method in a subclass",
          "Overloading redefines parent methods; overriding has different parameter lists",
          "They are the same concept", "Overloading requires interfaces and overriding requires abstract classes"], "A",
         "Overloading uses distinct parameter lists within one class, while overriding redefines an inherited method with the same signature."),
        ("INTERMEDIATE", "Why can this call fail to compile: this.setName(\"Ada\"); called inside a constructor before the first statement?",
         ["Because setName is private", "Because this() must be the first statement in a constructor and anything else before it is illegal",
          "Because Ada is not a String", "Because constructors cannot call methods"], "B",
         "A constructor call, this() or super(), must be the very first statement; any other code before it is a compile error."),
        ("INTERMEDIATE", "Why can you not instantiate an abstract class?",
         ["Because abstract classes have no constructors", "Because an abstract class can have abstract methods without bodies, so an instance would be incomplete",
          "Because abstract classes are final", "Because the compiler cannot find their package"], "B",
         "An abstract class may declare abstract methods with no implementation, making it incomplete and unsuitable for instantiation."),
        ("INTERMEDIATE", "What does a default method in an interface allow?",
         ["Interfaces to provide a concrete method body that implementing classes inherit unless they override it",
          "Classes to have multiple inheritance of state", "Interfaces to declare private fields",
          "Methods to be called without creating objects"], "A",
         "A default method gives interfaces a concrete implementation so existing classes need not be changed when a new method is added."),
        ("INTERMEDIATE", "What does the super keyword refer to inside a subclass?",
         ["The current object", "The immediate parent class instance and its members",
          "A static method", "The garbage collector"], "B",
         "super lets a subclass access the constructor, methods, and fields of its immediate parent class."),
        ("INTERMEDIATE", "Why must equals() and hashCode() be overridden together for HashMap usage?",
         ["Because the hash code decides the bucket and equals decides which stored value matches the key",
          "Because equals sorts the map", "Because hashCode must always return 0",
          "Because both methods must be private"], "A",
         "HashMap locates a bucket with hashCode() and finds the exact entry with equals(), so inconsistent implementations break lookups."),
        ("INTERMEDIATE", "Given add(2) and add(2.5) where both methods exist, which overload is chosen for add(2)?",
         ["The double version because double is wider", "The int version because int matches the argument exactly without conversion",
          "Both methods run", "The compiler reports an error"], "B",
         "Java selects the most specific matching overload, so an int argument uses the int parameter version."),
        ("INTERMEDIATE", "Which statement about static methods and polymorphism is true?",
         ["Static methods are resolved at compile time based on the reference type and are not overridden polymorphically",
          "Static methods can be overridden like instance methods", "Static methods are always abstract",
          "Static methods run only in the garbage collector"], "A",
         "Static methods are bound at compile time to the declared reference type, so calling them through a subclass reference does not use dynamic dispatch."),
        ("INTERMEDIATE", "Which access modifier allows access from any class in the same package?",
         ["private", "protected", "public", "package-private"], "D",
         "A member with no modifier is package-private and is accessible only from classes in the same package."),
        ("ADVANCED", "Which principle states that an object of a subclass should be substitutable for an object of its superclass?",
         ["The Liskov Substitution Principle", "The Single Responsibility Principle",
          "The Open-Closed Principle", "The Dependency Inversion Principle"], "A",
         "The Liskov Substitution Principle says a program should work with any subclass wherever its base type is expected."),
        ("ADVANCED", "Two interfaces both declare a default method with the same signature and a class implements both. What must the class do?",
         ["It must override the conflicting default method", "It must remove one interface",
          "It must declare the class abstract", "Nothing, the compiler picks the first interface"], "A",
         "When default methods conflict, the implementing class must explicitly override the method to resolve the ambiguity."),
        ("ADVANCED", "What is a covariant return type in an overridden method?",
         ["Returning a subclass type instead of the parent return type", "Returning the same primitive",
          "Returning a String always", "Returning void"], "A",
         "An override may narrow the return type to a subclass of the original return type, which is allowed since Java 5."),
        ("ADVANCED", "Why is this override illegal? public void display() in the subclass when the parent declares protected void display()?",
         ["Because the subclass must use a private modifier", "Because the override reduces visibility from protected to public in the wrong direction",
          "Because the return type must change", "Because display is final"], "A",
         "Overrides cannot reduce visibility, but here public increases it; the compile error is because the access is invalid."),
        ("ADVANCED", "Which statement about a final class is true?",
         ["A final class cannot be subclassed", "A final class cannot have methods",
          "A final class is always abstract", "A final class can only be instantiated once"], "A",
         "The final modifier on a class prevents inheritance, so no other class can extend it."),
        ("ADVANCED", "Why is composition often preferred over inheritance for code reuse?",
         ["Because composition avoids tight coupling and lets behavior change at runtime by swapping components",
          "Because inheritance is slower in the JVM", "Because composition always uses fewer bytes",
          "Because inheritance cannot use interfaces"], "A",
         "Composition builds flexible behavior by containing objects, avoiding rigid hierarchies and fragile inheritance coupling."),
        ("ADVANCED", "Why can a subclass not directly access a private field of its parent class?",
         ["Because private members are not inherited and are visible only inside the declaring class",
          "Because the field is copied", "Because the field is static",
          "Because the compiler renames private fields"], "A",
         "Private members are visible only within their declaring class, so a subclass must use public or protected accessors instead."),
        ("ADVANCED", "What is the output of this code? Animal a = new Dog(); System.out.println(a instanceof Dog);",
         ["true", "false", "Compilation error", "It throws ClassCastException"], "A",
         "The object stored in a was created as a Dog, so the instanceof check returns true regardless of the reference type."),
        ("ADVANCED", "What is an anonymous inner class?",
         ["A class without a name defined inline, often to implement an interface or extend a class on the spot",
          "A class with no methods", "A class that extends Object only",
          "A class that is never instantiated"], "A",
         "Anonymous inner classes are declared and instantiated in one expression, useful for short one-off implementations."),
        ("ADVANCED", "What does the @FunctionalInterface annotation guarantee?",
         ["That the interface has exactly one abstract method and is suitable for lambda expressions",
          "That the interface has no methods", "That the interface is compiled to bytecode",
          "That the interface is public"], "A",
         "@FunctionalInterface signals that the interface declares a single abstract method, the target of a lambda expression."),
    ],
    14: [
        ("BEGINNER", "Which collection interface represents an ordered sequence that allows duplicate elements?",
         ["Set", "Map", "List", "Queue"], "C",
         "A List is an ordered collection that permits duplicate elements and is accessed by index."),
        ("BEGINNER", "Which collection interface does not allow duplicate elements?",
         ["List", "Set", "Map", "Iterator"], "B",
         "A Set is a collection that contains no duplicate elements, enforcing uniqueness of its members."),
        ("BEGINNER", "Which collection interface stores key-value pairs?",
         ["Set", "List", "Map", "Queue"], "C",
         "A Map associates unique keys with values, allowing lookup of a value from its key."),
        ("BEGINNER", "What internal structure backs an ArrayList in Java?",
         ["A resizable array", "A linked list of nodes", "A hash table", "A binary tree"], "A",
         "ArrayList stores its elements in a dynamic, growable array that can be resized when full."),
        ("BEGINNER", "Which method adds an element to the end of a List?",
         ["push", "add", "put", "append"], "B",
         "The add(E element) method appends the element to the end of a List."),
        ("BEGINNER", "Which method removes all elements from a collection?",
         ["delete", "removeAllElements", "clear", "reset"], "C",
         "The clear() method removes every element from the collection, leaving it empty."),
        ("BEGINNER", "Which class is a hash-table-based Map that permits one null key and many null values?",
         ["HashMap", "TreeMap", "Hashtable", "LinkedHashSet"], "A",
         "HashMap allows a single null key and multiple null values, unlike Hashtable which forbids nulls."),
        ("BEGINNER", "Which method returns the number of elements in a collection?",
         ["length", "count", "size", "capacity"], "C",
         "The size() method returns the number of elements currently stored in the collection."),
        ("BEGINNER", "Which class implements the List interface using doubly linked nodes?",
         ["ArrayList", "LinkedList", "HashSet", "Vector"], "B",
         "LinkedList stores each element in a node linked to its neighbors, giving efficient insertions at either end."),
        ("BEGINNER", "Which interface defines the natural ordering of objects for sorting?",
         ["Comparator", "Comparable", "Iterator", "Runnable"], "B",
         "Implementing Comparable gives a class a natural ordering through its compareTo method used by sorting utilities."),
        ("INTERMEDIATE", "What happens when you add a duplicate element to a HashSet?",
         ["It replaces the old element", "It is ignored and add returns false",
          "It throws an exception", "It is added after the old element"], "B",
         "A Set rejects duplicates, so add returns false and the set remains unchanged."),
        ("INTERMEDIATE", "What does HashMap.get(key) return when the key does not exist?",
         ["0", "An empty string", "null", "It throws an exception"], "C",
         "If a key is absent, the get method returns null rather than raising an error."),
        ("INTERMEDIATE", "Which statement is required for Collections.sort(list) to compile?",
         ["The elements must implement Comparable or a Comparator must be supplied",
          "The list must be empty", "The list must be a LinkedList",
          "The elements must be Strings"], "A",
         "Collections.sort needs a natural ordering from Comparable or an explicit Comparator to determine element order."),
        ("INTERMEDIATE", "Which collection is generally more efficient for frequent insertions in the middle of a large sequence?",
         ["ArrayList", "LinkedList", "HashSet", "TreeMap"], "B",
         "LinkedList only relinks neighbor pointers for middle insertions, while ArrayList shifts many elements."),
        ("INTERMEDIATE", "How does TreeMap order its keys?",
         ["By insertion order", "By the natural ordering of the keys or a provided Comparator",
          "Randomly", "By hash code order"], "B",
         "TreeMap maintains keys in sorted order according to their natural ordering or the supplied Comparator."),
        ("INTERMEDIATE", "What happens when you remove an element from a List while iterating with an enhanced for loop?",
         ["Nothing special", "ConcurrentModificationException is thrown",
          "The element is silently skipped", "The list is cleared"], "B",
         "The for-each iterator detects the structural modification and throws ConcurrentModificationException."),
        ("INTERMEDIATE", "Why must the equals() and hashCode() methods be consistent for HashMap keys?",
         ["Because the hash code picks the bucket and equals finds the exact key, so inconsistency breaks lookups",
          "Because equals must always return false", "Because hashCode must return the key length",
          "Because both must be final"], "A",
         "HashMap uses hashCode to locate the bucket and equals to compare keys, so they must agree for correct behavior."),
        ("INTERMEDIATE", "What does PriorityQueue.poll() return when the queue is a min-heap?",
         ["The largest element", "The smallest element",
          "The most recently added element", "null always"], "B",
         "By natural ordering, a PriorityQueue places the smallest element at the head, so poll returns it first."),
        ("INTERMEDIATE", "What happens when you call add() on a list returned by Arrays.asList(...)?",
         ["It works normally", "It throws UnsupportedOperationException because the view has a fixed size",
          "It returns false", "It sorts the list"], "B",
         "Arrays.asList returns a fixed-size view backed by the array, so adding elements is unsupported."),
        ("INTERMEDIATE", "Which of these correctly iterates over a Map<String, Integer> called scores?",
         ["for (String k : scores.keySet()) {}", "for (String k : scores) {}", "for (Integer v : scores.keySet()) {}", "for (Map m : scores) {}"], "A",
         "keySet() returns the keys, and the enhanced for loop iterates over them to access each entry."),
        ("ADVANCED", "Which Map implementation preserves the insertion order of its entries?",
         ["HashMap", "LinkedHashMap", "TreeMap", "Hashtable"], "B",
         "LinkedHashMap maintains a doubly linked list of entries, so iteration follows insertion order."),
        ("ADVANCED", "What is required of objects stored in a TreeSet?",
         ["They must implement Comparable or a Comparator must be supplied",
          "They must override finalize", "They must be serializable",
          "They must be Strings"], "A",
         "TreeSet orders elements by natural ordering, so elements need Comparable or a comparator must be provided."),
        ("ADVANCED", "What does fail-fast mean for a collection iterator?",
         ["It throws ConcurrentModificationException as soon as the collection is modified during iteration",
          "It fails only when out of memory", "It caches results to avoid exceptions",
          "It terminates the JVM"], "A",
         "A fail-fast iterator checks the collection's modification count and throws an exception if a structural change occurs during iteration."),
        ("ADVANCED", "Which interface would you implement with a lambda to sort a List of custom objects without changing their class?",
         ["Comparable", "Comparator", "Iterator", "Cloneable"], "B",
         "Comparator defines external comparison logic and can be supplied as a lambda to sorting methods."),
        ("ADVANCED", "What is the behavior of WeakHashMap with respect to its keys?",
         ["Entries are removed automatically when their keys become only weakly reachable",
          "Keys are never removed", "It throws exceptions for weak keys",
          "It orders keys by strength"], "A",
         "WeakHashMap uses weak references for keys so the garbage collector can reclaim them, removing the corresponding entries."),
        ("ADVANCED", "Which Map is most efficient when keys are a small fixed set of enum constants?",
         ["HashMap", "EnumMap", "TreeMap", "WeakHashMap"], "B",
         "EnumMap is implemented as a single array indexed by ordinal, giving very fast and compact access for enum keys."),
        ("ADVANCED", "What does CopyOnWriteArrayList guarantee for iterators?",
         ["Thread-safe iteration that never throws ConcurrentModificationException because iterators see a snapshot",
          "O(1) random writes", "Sorted iteration order",
          "That elements are never copied"], "A",
         "CopyOnWriteArrayList copies the underlying array on every write, so iterators operate on a stable snapshot."),
        ("ADVANCED", "What happens if you insert a null key into a TreeMap?",
         ["It works normally", "It throws NullPointerException because compareTo(null) fails",
          "The null key sorts first", "It replaces the smallest key"], "B",
         "TreeMap orders keys by comparison, and comparing with null throws NullPointerException."),
        ("ADVANCED", "What does Collections.unmodifiableMap(map) return?",
         ["A new mutable map", "A read-only view of the original map",
          "A copy that still allows changes", "A sorted map"], "B",
         "unmodifiableMap wraps the map so all modification methods throw UnsupportedOperationException, leaving the original intact."),
        ("ADVANCED", "Why does ArrayList grow by approximately 50 percent of its current capacity instead of by a fixed small number?",
         ["Because growing the array requires copying, and amortizing the cost keeps append operations near O(1)",
          "Because the JVM requires exactly 50 percent growth", "Because smaller growth wastes less memory always",
          "Because ArrayList cannot exceed a fixed size"], "A",
         "Doubling the size roughly halves the average number of copies per insertion, giving amortized constant-time appends."),
    ],
    15: [
        ("BEGINNER", "Which keyword manually throws an exception in Java?",
         ["throw", "throws", "try", "raise"], "A",
         "The throw statement explicitly raises an exception object, such as throw new IllegalArgumentException();."),
        ("BEGINNER", "Which block of a try-catch-finally structure always executes?",
         ["try", "catch", "finally", "unless"], "C",
         "The finally block runs regardless of whether an exception was thrown or caught, making it ideal for cleanup."),
        ("BEGINNER", "What is the common superclass of all exceptions and errors in Java?",
         ["Exception", "Throwable", "Error", "Object"], "B",
         "Throwable is the root of the hierarchy, with Exception and Error as its two main subclasses."),
        ("BEGINNER", "Which keyword in a method signature declares that the method may throw a checked exception?",
         ["throw", "throws", "catch", "finally"], "B",
         "The throws clause lists exceptions a method might throw, informing callers to handle them."),
        ("BEGINNER", "What is a checked exception?",
         ["An exception the compiler forces the programmer to handle or declare",
          "An exception that is always ignored", "An exception thrown only by the garbage collector",
          "An exception that cannot be caught"], "A",
         "Checked exceptions are verified at compile time; the code must catch them or declare them in a throws clause."),
        ("BEGINNER", "Which block contains the code that handles an exception?",
         ["try", "catch", "finally", "throw"], "B",
         "A catch block receives the thrown exception and contains the recovery or reporting logic."),
        ("BEGINNER", "What exception is thrown by int x = 10 / 0; in Java?",
         ["NullPointerException", "ArithmeticException", "ArrayIndexOutOfBoundsException", "NumberFormatException"], "B",
         "Integer division by zero throws ArithmeticException at runtime."),
        ("BEGINNER", "What does the parameter of a catch block represent?",
         ["The class being compiled", "The thrown exception object",
          "The loop counter", "The return value of the try block"], "B",
         "The catch parameter holds the exception instance that was thrown, giving access to its message and stack trace."),
        ("BEGINNER", "A try block must be followed by what?",
         ["Only a finally block", "A catch and/or finally block",
          "A throw statement", "A return statement"], "B",
         "The try block must be paired with at least one catch block or a finally block, or both."),
        ("BEGINNER", "When does a NullPointerException occur?",
         ["When calling a method on a null reference", "When dividing by zero",
          "When a file is missing", "When a cast is illegal"], "A",
         "A NullPointerException is thrown when a program attempts to use a reference that points to null."),
        ("INTERMEDIATE", "What is the purpose of a multi-catch block in Java 7?",
         ["It lets one catch block handle multiple exception types separated by a vertical bar",
          "It catches every exception in the JVM", "It catches checked and unchecked exceptions differently",
          "It removes the need for finally"], "A",
         "Multi-catch syntax such as catch (IOException | SQLException e) handles several exception types with one block."),
        ("INTERMEDIATE", "What is the output of this code? try { return 1; } finally { System.out.print(\"finally\"); }",
         ["finally", "1", "finally1", "Nothing"], "A",
         "The finally block executes before control leaves the method, so 'finally' is printed even though the try returns."),
        ("INTERMEDIATE", "What does try-with-resources require from a resource class?",
         ["It must implement the AutoCloseable interface", "It must extend Thread",
          "It must be a String", "It must define a static main method"], "A",
         "Try-with-resources automatically closes resources that implement AutoCloseable or its subinterface Closeable."),
        ("INTERMEDIATE", "What is the value produced by the lambda (x) -> x * 2 when passed the integer 5?",
         ["25", "10", "7", "2"], "B",
         "The lambda multiplies its argument by 2, so applying it to 5 yields 10."),
        ("INTERMEDIATE", "What does this stream pipeline do? list.stream().filter(n -> n > 0).collect(Collectors.toList());",
         ["It sums all positive numbers", "It creates a new list containing only the positive numbers",
          "It sorts the numbers in place", "It removes the first element"], "B",
         "filter keeps only elements satisfying the predicate and collect gathers them into a new List."),
        ("INTERMEDIATE", "What does the map operation do in a Stream pipeline?",
         ["It transforms each element into another element using the provided function",
          "It removes duplicates", "It sorts the stream", "It terminates the stream"], "A",
         "map applies a function to every element, producing a new stream of transformed results."),
        ("INTERMEDIATE", "Which of these is a terminal operation on a Stream?",
         ["filter", "map", "forEach", "limit"], "C",
         "forEach is a terminal operation that triggers processing and consumes the elements, whereas filter, map, and limit are intermediate."),
        ("INTERMEDIATE", "What happens to a checked exception thrown inside a method when the method does not catch or declare it?",
         ["The code does not compile", "It is ignored at runtime", "The method returns null",
          "It becomes an Error"], "A",
         "Checked exceptions must be caught or declared, so failing to do so is a compile-time error."),
        ("INTERMEDIATE", "In a multi-catch block, which catch must appear first when catching Exception and a subclass such as IOException?",
         ["The subclass IOException must be caught first", "The superclass Exception must be caught first",
          "The order does not matter", "Only IOException can be caught"], "A",
         "A catch for a subclass must precede the superclass catch, otherwise the subclass handler would be unreachable."),
        ("INTERMEDIATE", "How do you safely handle a missing value returned by Optional.ofNullable(x)?",
         ["Call get() without checks", "Use orElse or isPresent to handle the empty case",
          "Throw a RuntimeException directly", "Ignore it"], "B",
         "Optional's orElse and orElseGet provide defaults, and isPresent guards against operating on absent values."),
        ("ADVANCED", "What does the reduce operation in a Stream compute given (a, b) -> a + b as the accumulator?",
         ["The sum of all elements in the stream", "The maximum element",
          "The number of elements", "The first element"], "A",
         "reduce folds the stream by repeatedly applying the accumulator, so adding each element yields the total sum."),
        ("ADVANCED", "Why does this pipeline print nothing? list.stream().filter(n -> n > 0).map(n -> n * 2);",
         ["Because intermediate operations are lazy and are not executed without a terminal operation",
          "Because filter removes all elements", "Because map always fails",
          "Because the stream is empty"], "A",
         "Streams are lazy; intermediate operations only build a pipeline that runs when a terminal operation is invoked."),
        ("ADVANCED", "What risk arises when using parallel streams on a mutable shared collection?",
         ["Data races and inconsistent results because operations run concurrently",
          "The stream never terminates", "Memory is always exhausted",
          "The compiler rejects the code"], "A",
         "Parallel streams split work across threads, so mutating shared state without synchronization causes race conditions."),
        ("ADVANCED", "How do you create a custom checked exception in Java?",
         ["By extending the Exception class and defining constructors",
          "By extending RuntimeException only", "By implementing the Runnable interface",
          "By throwing the Error class"], "A",
         "Extending Exception makes the custom type checked, and constructors typically forward the message to the superclass."),
        ("ADVANCED", "What does initCause() achieve in exception handling?",
         ["It attaches the underlying exception that caused the current one, preserving the root cause",
          "It creates a new exception", "It deletes the stack trace",
          "It converts a checked exception into unchecked"], "A",
         "initCause links a cause to an exception, so the original problem can be preserved and printed during diagnosis."),
        ("ADVANCED", "What is the result of list.stream().distinct().sorted().limit(3).collect(Collectors.toList()) on [3, 1, 3, 2, 1]?",
         ["[3, 1, 2]", "[1, 2, 3]", "[1, 2]", "[2, 1, 3]"], "B",
         "distinct leaves [3, 1, 2], sorted yields [1, 2, 3], and limit(3) keeps all three of them."),
        ("ADVANCED", "What does the method reference String::toUpperCase represent?",
         ["A lambda that calls toUpperCase on the given String argument",
          "A constructor reference", "A static field reference",
          "A class literal"], "A",
         "String::toUpperCase is a bound style of method reference equivalent to the lambda s -> s.toUpperCase()."),
        ("ADVANCED", "Why does the body of a lambda commonly use a try-catch for checked exceptions?",
         ["Because many functional interfaces like Function declare no checked exceptions in their abstract method",
          "Because lambdas cannot call methods", "Because catch blocks are illegal in lambdas",
          "Because checked exceptions are always thrown"], "A",
         "Functional interfaces declare their abstract method without throws, so lambdas must handle checked exceptions locally."),
        ("ADVANCED", "In a try-with-resources statement with two resources opened in order, in what order are they closed?",
         ["The second resource is closed before the first, in reverse order of opening",
          "The first resource closes first", "They close at the same time",
          "Only the first resource closes"], "A",
         "Resources are closed in the reverse order in which they were opened, like nested stack unwinding."),
        ("ADVANCED", "What does Collectors.joining(\", \") produce when applied to a Stream of Strings?",
         ["A single String that concatenates the elements separated by a comma and space",
          "A List of joined strings", "A comma-separated integer sum",
          "An empty Optional"], "A",
         "Collectors.joining accumulates the stream elements into one String with the specified delimiter between them."),
    ],
}
