# -*- coding: utf-8 -*-
"""
Question bank for subject 21: AI101 - Artificial Intelligence Basics.
Category: Artificial Intelligence & Data Science.

Topics:
  101: AI & Intelligent Agents
  102: Search Algorithms
  103: Knowledge Representation
  104: Intro to Machine Learning
  105: AI Ethics & Applications

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    101: [
        ("BEGINNER", "In computing, what do the letters AI stand for?",
         ["Artificial Intelligence", "Automated Input", "Advanced Internet", "Algorithmic Interface"], "A",
         "AI is the standard acronym for Artificial Intelligence, the study of machines that perform tasks that typically require human intelligence."),
        ("BEGINNER", "Which discipline is the parent field of artificial intelligence?",
         ["Mechanical Engineering", "Computer Science", "Biology", "Astronomy"], "B",
         "AI is a subfield of computer science, although it draws ideas from psychology, linguistics and mathematics."),
        ("BEGINNER", "Which option best describes an intelligent agent?",
         ["a database for storing sensor logs", "a web browser extension", "an entity that perceives its environment and acts to achieve goals", "a compiler optimization pass"], "C",
         "An intelligent agent perceives its environment through sensors and acts on it through actuators to pursue its goals."),
        ("BEGINNER", "In the agent-environment loop, what does the agent send back to the environment?",
         ["percepts", "raw sensor data", "goal statements", "actions"], "D",
         "The agent acts on the environment by performing actions produced by its actuators."),
        ("BEGINNER", "What is a percept in agent terminology?",
         ["the input an agent receives from its sensors at an instant", "the agent's internal state", "the agent's reward signal", "the agent's action history"], "A",
         "A percept is the current sensor reading that the agent uses to decide its next action."),
        ("BEGINNER", "Which of the following is an example of an intelligent agent?",
         ["a pocket calculator", "a self-driving car's control system", "a text file", "a keyboard"], "B",
         "A self-driving car senses the road and acts on it, satisfying the definition of an intelligent agent."),
        ("BEGINNER", "What is the role of sensors in an agent?",
         ["to perform actions", "to compute rewards", "to gather information about the environment", "to communicate with humans"], "C",
         "Sensors let the agent perceive the state of its environment so it can choose appropriate actions."),
        ("BEGINNER", "A thermostat that turns heating on or off based on temperature readings is best described as:",
         ["a utility-based agent", "a goal-based agent", "an uncertain agent", "a simple reflex agent"], "D",
         "A thermostat maps its current temperature percept directly to an action, the hallmark of a simple reflex agent."),
        ("BEGINNER", "What is the central goal of artificial intelligence?",
         ["building systems that perform tasks that typically require human intelligence", "replacing all human jobs", "increasing database sizes", "removing errors from code"], "A",
         "AI seeks to build systems that carry out tasks that normally require human intelligence, such as perception and reasoning."),
        ("BEGINNER", "Which of the following is a typical example of an AI application?",
         ["a hardware firewall", "a spelling and grammar assistant that suggests corrections", "a file compressor", "a BIOS"], "B",
         "A spelling and grammar assistant performs a language task normally done by humans, a classic AI application."),
        ("INTERMEDIATE", "A robot vacuum explores a room and maps obstacles while cleaning. Which agent capability is being demonstrated?",
         ["complete self-awareness", "perception and planning", "wireless charging", "cloud storage"], "B",
         "The robot perceives obstacles with its sensors and plans a cleaning route, combining perception and planning."),
        ("INTERMEDIATE", "An agent keeps a model of the world and chooses actions that lead to a goal state. What type of agent is this?",
         ["a simple reflex agent", "a random agent", "a goal-based agent", "a passive database"], "C",
         "A goal-based agent maintains a model of the world and searches for actions that reach a desired goal state."),
        ("INTERMEDIATE", "A temperature-sensing agent decides actions using the single rule 'if temperature > 25 then turn on fan'. What kind of behaviour does this show?",
         ["learning from experience", "probabilistic inference", "deep reasoning", "reflex (condition-action) behaviour"], "D",
         "The agent uses a fixed condition-action rule, so it behaves as a reflex agent rather than reasoning or learning."),
        ("INTERMEDIATE", "Which pair correctly matches a sensing task with its typical sensor?",
         ["obstacle detection - lidar", "text colour - keyboard", "sound level - camera", "air pressure - microphone"], "A",
         "Lidar measures distances and is a standard sensor for obstacle detection in robotic agents."),
        ("INTERMEDIATE", "A chatbot that answers questions by retrieving pre-written answers without remembering past turns is best described as:",
         ["a learning agent", "a memoryless (stateless) reactive agent", "a deep Q-network", "a planning agent"], "B",
         "Because it keeps no memory of previous turns, the chatbot is a stateless reactive agent."),
        ("INTERMEDIATE", "An agent's utility function measures what?",
         ["how fast the processor runs", "the size of its memory", "how good a given state is for the agent", "the number of sensors"], "C",
         "A utility function assigns a numeric score to states so the agent can compare how desirable they are."),
        ("INTERMEDIATE", "If an agent acts, observes the result, and adjusts its future behaviour to maximise rewards, which property is it displaying?",
         ["hard-coding", "actuation", "immutability", "learning"], "D",
         "Improving behaviour based on the outcomes of past actions is exactly what it means for an agent to learn."),
        ("INTERMEDIATE", "A chess-playing program that only reacts to the current board with a precomputed move table would be classified as:",
         ["a table-driven reflex agent", "a fully rational planner", "an unsupervised learner", "a conversational agent"], "A",
         "Using a lookup of condition-action pairs indexed by the current percept is the table-driven reflex design."),
        ("INTERMEDIATE", "Which of the following best matches the idea of a rational agent?",
         ["one that always does nothing", "one that chooses actions expected to maximise its performance measure", "one that acts randomly", "one that follows only stored patterns"], "B",
         "Rationality means selecting the action expected to best achieve the agent's performance measure."),
        ("INTERMEDIATE", "An agent with four sensors that each report one bit has how many distinct percepts at any instant?",
         ["4", "16", "2", "8"], "C",
         "Four binary sensors combine to give 2 raised to the power 4, which is 16 distinct percept combinations."),
        ("ADVANCED", "An e-commerce recommendation agent that adapts its suggestions based on past purchases is an example of:",
         ["a purely reflexive agent", "a static lookup table", "a learning agent that improves from experience", "a model-free firewall"], "C",
         "The agent changes its behaviour using past interactions, which is the defining trait of a learning agent."),
        ("ADVANCED", "Why is the PEAS description useful when designing an agent?",
         ["it defines the programming language", "it forces the designer to describe Performance measure, Environment, Actuators and Sensors", "it removes the need for sensors", "it guarantees optimal behaviour"], "D",
         "PEAS stands for Performance, Environment, Actuators and Sensors, the four aspects that fully specify an agent's task."),
        ("ADVANCED", "For a fully observable, deterministic environment, which agent design is usually the simplest that works?",
         ["a reflex agent with a condition-action rule for each percept", "a multi-agent simulator", "an evolutionary population", "a reinforcement learner"], "A",
         "When each percept fully determines the correct action, a simple condition-action reflex agent suffices."),
        ("ADVANCED", "A delivery robot must decide routes, avoid pedestrians and recharge itself. Which set of design decisions best addresses this?",
         ["ignore pedestrians to save time", "model the world, plan routes, and combine goals with a utility function", "use only a fixed lookup table", "delete the recharge rule"], "B",
         "Conflicting goals such as speed, safety and battery life are best balanced with a model-based planner and a utility function."),
        ("ADVANCED", "A system tracks a user's health data and alerts a doctor if risk rises. Which concern is most critical for this agent?",
         ["the font of the alerts", "the agent's learning rate", "trustworthiness and safety of its recommendations", "the number of buttons on the screen"], "C",
         "A health-alerting agent must be safe and trustworthy because an incorrect recommendation can harm the user."),
        ("ADVANCED", "Why does a rational agent need a performance measure?",
         ["to decide when to turn off", "to debug its sensors", "to choose its sensors", "to evaluate how well different actions achieve success"], "D",
         "A performance measure lets the agent compare the outcomes of candidate actions and pick the best one."),
        ("ADVANCED", "A stock-trading agent trades millions of times per day and learns from each outcome. Which architecture best supports continuous improvement?",
         ["a learning agent with a critic that updates a performance element", "a fixed reflex rule base", "a static database", "a random number generator"], "A",
         "A learning agent uses a critic to evaluate outcomes and updates its performance element accordingly."),
        ("ADVANCED", "Which statement about the environment in PEAS is correct?",
         ["it describes only the agent's brain", "it is the context in which the agent operates and which the agent senses and affects", "it is the set of actuators", "it is the reward function"], "B",
         "The environment is everything outside the agent that the agent perceives and acts upon."),
        ("ADVANCED", "An agent that operates in an environment where it has incomplete information must be able to:",
         ["always act optimally without sensing", "maintain a belief or model and reason under uncertainty", "ignore new percepts", "rely on a single fixed rule"], "C",
         "Under partial observability the agent must keep beliefs about the hidden state and reason under uncertainty."),
        ("ADVANCED", "When two intelligent agents cooperate to lift a heavy object, which branch of AI focuses on such interaction?",
         ["knowledge representation alone", "computer vision", "natural language generation", "multi-agent systems"], "D",
         "Multi-agent systems study how multiple agents interact, cooperate and compete to solve shared problems."),
    ],
    102: [
        ("BEGINNER", "What does BFS stand for?",
         ["Breadth-First Search", "Binary File System", "Best-First Search", "Backward-Facing Search"], "A",
         "BFS stands for Breadth-First Search, which explores a graph level by level."),
        ("BEGINNER", "Which data structure is used by Breadth-First Search to manage frontier nodes?",
         ["a stack", "a queue", "a heap", "a linked hash map"], "B",
         "BFS uses a queue so that nodes are expanded in first-in, first-out order."),
        ("BEGINNER", "What is the goal of an uninformed (blind) search algorithm?",
         ["to use domain knowledge to prune nodes", "to find a solution path without using domain-specific heuristics", "to prove a theorem", "to train a classifier"], "C",
         "Uninformed search finds solutions using only the problem definition, with no heuristic guidance."),
        ("BEGINNER", "Which data structure does Depth-First Search rely on?",
         ["a queue", "a min-heap", "a priority queue", "a stack"], "D",
         "DFS uses a stack so it always explores the most recently discovered node first."),
        ("BEGINNER", "What does a heuristic function h(n) estimate in informed search?",
         ["the cost from node n to the goal", "the number of goals in the map", "the memory used by the frontier", "the depth of the tree"], "A",
         "A heuristic h(n) estimates the remaining cost from node n to the goal state."),
        ("BEGINNER", "What is the key idea behind Greedy Best-First Search?",
         ["expanding nodes with the largest g-cost", "always expanding the node with the smallest h(n) value", "expanding nodes in random order", "expanding the deepest node first"], "B",
         "Greedy Best-First Search always expands the node whose heuristic h(n) is smallest."),
        ("BEGINNER", "What property ensures an admissible heuristic never overestimates?",
         ["it is always equal to zero", "it returns the exact cost", "it never overestimates the true cost to reach the goal", "it ignores the goal"], "C",
         "Admissibility requires h(n) to never exceed the true cost from n to the goal."),
        ("BEGINNER", "In tree search, what is the branching factor b?",
         ["the depth of the goal", "the number of goals", "the number of solutions", "the maximum number of successors of any node"], "D",
         "The branching factor b is the maximum number of successors a node can generate."),
        ("BEGINNER", "What is the time complexity of BFS on a graph with branching factor b and solution depth d?",
         ["O(b^d)", "O(d)", "O(b*d)", "O(log d)"], "A",
         "BFS expands O(b^d) nodes because the tree grows by a factor of b per level up to depth d."),
        ("BEGINNER", "What is the key difference between tree search and graph search?",
         ["tree search is always faster", "graph search keeps track of visited states to avoid revisiting them", "graph search uses heuristics", "tree search stores all nodes in a stack"], "B",
         "Graph search maintains a closed set of visited states so it never expands the same state twice."),
        ("INTERMEDIATE", "Consider the tree where A has children B and C, and B has child D. In what order does BFS first expand the nodes?",
         ["A, D, B, C", "A, B, C, D", "A, C, B, D", "D, B, C, A"], "B",
         "BFS expands level by level: first A, then its children B and C, then the next level containing D."),
        ("INTERMEDIATE", "A binary tree has a goal at the deepest level. Which order does DFS expand nodes?",
         ["level by level", "in a single path all the way down before backtracking", "in decreasing g-cost order", "randomly"], "C",
         "DFS follows one branch as deep as possible before backtracking to explore sibling branches."),
        ("INTERMEDIATE", "For an admissible heuristic in A*, why is optimality guaranteed?",
         ["it reduces the branching factor to one", "it guarantees the goal is always at depth one", "it always expands the deepest node first", "it guarantees the first goal node popped from the frontier is optimal"], "D",
         "Because an admissible heuristic never overestimates, the first goal popped by A* has the optimal path cost."),
        ("INTERMEDIATE", "In A*, the evaluation function f(n) = g(n) + h(n). What does g(n) represent?",
         ["the actual cost of the path from the start to node n", "the heuristic estimate to the goal", "the depth of the tree", "the number of visited states"], "A",
         "g(n) is the known cost of the best path found so far from the start node to n."),
        ("INTERMEDIATE", "Start node S has h = 10 and g = 0. Its child T has h = 5 and g = 4. What is f(T) in A*?",
         ["15", "9", "10", "4"], "B",
         "f(T) is g(T) + h(T), which is 4 + 5 = 9."),
        ("INTERMEDIATE", "A search that expands nodes in order of their path cost g(n) rather than depth is called:",
         ["Breadth-First Search", "Depth-First Search", "Uniform-Cost Search", "Greedy Best-First Search"], "C",
         "Uniform-Cost Search expands the node with the smallest g(n), making it optimal for weighted graphs."),
        ("INTERMEDIATE", "In DFS on a very deep or infinite tree, what is the main risk?",
         ["running out of memory in the queue", "not finding the shallowest goal first", "wasting time storing every visited node", "getting stuck going down an unbounded path without finding the goal"], "D",
         "DFS can descend an infinitely deep branch forever, so it is not complete on infinite state spaces."),
        ("INTERMEDIATE", "In A*, node P has f = 8, node Q has f = 10 and node R has f = 9. Which node is expanded next?",
         ["P", "Q", "R", "all at once"], "A",
         "A* always expands the frontier node with the smallest f value, so P is chosen next."),
        ("INTERMEDIATE", "For finding the SHORTEST path in an unweighted graph, which algorithm is guaranteed to work?",
         ["Depth-First Search", "Breadth-First Search", "Greedy Best-First Search with any heuristic", "Random Search"], "B",
         "BFS expands level by level, so the first goal it reaches in an unweighted graph is via a shortest path."),
        ("INTERMEDIATE", "A heuristic h is consistent if it satisfies which inequality for every node n and its successor n'?",
         ["h(n) = g(n)", "h(n) >= c(n,n')", "h(n) <= c(n,n') + h(n')", "h(n) = c(n,n') * h(n')"], "C",
         "Consistency requires that the drop in h along an edge never exceeds the edge cost, so h(n) <= c(n,n') + h(n')."),
        ("ADVANCED", "An 8-puzzle heuristic counts misplaced tiles. This heuristic is admissible because:",
         ["it overestimates the true cost", "it ignores the start state", "each misplaced tile must move at least once, so it never overestimates the true moves", "it returns the optimal solution directly"], "C",
         "Every misplaced tile needs at least one move, so the count never exceeds the true number of moves required."),
        ("ADVANCED", "For the 8-puzzle, the Manhattan distance heuristic is preferred over misplaced-tiles because:",
         ["it is easier to compute", "it is inadmissible", "it is faster", "it is more informed and never overestimates, so A* expands fewer nodes"], "D",
         "Manhattan distance sums the grid moves for each tile, giving a tighter admissible estimate that prunes more of the search."),
        ("ADVANCED", "In a large map with a high branching factor, A* may exhaust memory. Which technique addresses this?",
         ["Iterative-Deepening A* (IDA*)", "increasing the branching factor", "switching to random sampling", "removing the heuristic"], "A",
         "IDA* repeats depth-limited searches with increasing f-cost limits, using only linear memory."),
        ("ADVANCED", "Why is BFS inappropriate for a graph with billions of nodes and an unknown deep goal?",
         ["it never terminates", "it requires a heuristic", "its frontier grows exponentially with depth, consuming huge memory", "it only works on trees"], "C",
         "BFS stores every node at the current depth, and that frontier grows exponentially as depth increases."),
        ("ADVANCED", "With a consistent heuristic, how many times does A* graph search expand each state?",
         ["an infinite number of times", "zero times", "once", "exactly twice"], "C",
         "Consistency ensures a state is reached optimally the first time, so it is expanded at most once."),
        ("ADVANCED", "Which search strategy combines the low memory of DFS with the optimality of BFS for shortest paths in unweighted graphs?",
         ["Greedy Best-First", "Uniform-Cost with a heap", "Bidirectional search", "Iterative Deepening DFS (IDDFS)"], "D",
         "IDDFS repeatedly runs depth-limited DFS with increasing limits, giving BFS-like optimality with linear memory."),
        ("ADVANCED", "A navigation app that must return the fastest route in real time would most likely use:",
         ["A* with an admissible heuristic like travel-time estimates", "pure DFS", "pure BFS on the whole map", "a random walk"], "A",
         "A* guided by a travel-time heuristic focuses the search on promising routes, making it fast in practice."),
        ("ADVANCED", "You have an admissible but very weak heuristic that is often zero. What happens to A*?",
         ["it becomes greedy", "it degrades toward Dijkstra's algorithm, expanding many more nodes", "it crashes", "it becomes inadmissible"], "B",
         "When h is close to zero, f is dominated by g, so A* behaves like Dijkstra and expands many nodes."),
        ("ADVANCED", "If a heuristic is admissible but inconsistent, a standard A* graph search may:",
         ["find an optimal solution faster", "use less memory", "re-open already-closed nodes and potentially lose optimality", "terminate immediately"], "C",
         "An inconsistent heuristic can cause nodes in the closed set to need re-expansion, so the graph search must re-open them to stay optimal."),
        ("ADVANCED", "In an enormous state space where exhaustive search is impossible, which approach is often taken?",
         ["always using exhaustive DFS", "avoiding any search", "restricting to depth 1", "using heuristic approximations such as hill climbing that sacrifice completeness for speed"], "D",
         "Hill climbing and other local search trade completeness and optimality for tractability in huge spaces."),
    ],
    103: [
        ("BEGINNER", "What is knowledge representation in AI?",
         ["the encoding of information about the world so a program can reason with it", "the storage of photos on a disk", "the layout of a web page", "the speed of a processor"], "A",
         "Knowledge representation is the way facts about the world are encoded so that a program can use them for reasoning."),
        ("BEGINNER", "Which of the following is a fact expressed in propositional logic?",
         ["Open the window", "It is raining", "Please stop", "Do it now"], "B",
         "A proposition is a declarative sentence that is either true or false, such as 'It is raining'."),
        ("BEGINNER", "Which symbol represents logical AND in propositional logic?",
         ["OR", "NOT", "AND (conjunction)", "IMPLIES"], "C",
         "The conjunction operator AND is true only when both of its operands are true."),
        ("BEGINNER", "What does a knowledge base contain?",
         ["the hardware devices", "a collection of sentences that represent known facts", "the compiled program", "the user password"], "D",
         "A knowledge base stores a set of sentences that represent what the system believes about the world."),
        ("BEGINNER", "In logic, what does entailment (KB |= sentence) mean?",
         ["the knowledge base logically implies the sentence", "the sentence is false", "the sentence contradicts the KB", "the sentence is random"], "A",
         "Entailment means that every model in which the knowledge base is true also makes the sentence true."),
        ("BEGINNER", "Which representation is a simple graph-based structure of nodes connected by edges?",
         ["a stack", "a semantic network", "a register file", "a priority queue"], "B",
         "A semantic network represents concepts as nodes and their relationships as labelled edges."),
        ("BEGINNER", "What is an ontology in knowledge representation?",
         ["a formal specification of concepts and relationships in a domain", "a programming language", "a data compression tool", "a type of neural network"], "C",
         "An ontology formally defines the concepts, properties and relations that exist in a particular domain."),
        ("BEGINNER", "Which of the following is a common knowledge representation scheme?",
         ["a keyboard", "a CPU cache", "a router", "semantic networks"], "D",
         "Semantic networks, frames, rules and logic are all widely used knowledge representation schemes."),
        ("BEGINNER", "What does a rule 'IF X THEN Y' express?",
         ["a conditional relationship: if X holds, then Y follows", "that Y is always false", "that X is a number", "that Y happened before X"], "A",
         "A production rule states that when the premise X is true, the conclusion Y can be derived."),
        ("BEGINNER", "Which logic extends propositional logic with variables and quantifiers?",
         ["propositional logic", "first-order logic", "boolean algebra", "fuzzy sets"], "B",
         "First-order logic adds objects, variables, functions and the quantifiers forall and exists."),
        ("INTERMEDIATE", "Which of these is a well-formed first-order logic sentence?",
         ["Tall(y) and Short", "forall x Student(x) implies Likes(x, Coffee)", "Student", "forall"], "C",
         "A well-formed first-order sentence combines a quantifier, a variable, and predicates such as Student(x) and Likes(x, Coffee)."),
        ("INTERMEDIATE", "A knowledge base contains 'Cat(Fluffy)'. To conclude 'Mammal(Fluffy)' you need:",
         ["a negation", "a rule such as forall x Cat(x) implies Mammal(x)", "a random number", "a question mark"], "B",
         "A general rule that every cat is a mammal lets inference derive the new fact Mammal(Fluffy)."),
        ("INTERMEDIATE", "Which of the following is a sound inference rule?",
         ["guessing", "flipping a coin", "ignoring the premises", "modus ponens"], "D",
         "Modus ponens, from P and P implies Q we derive Q, always preserves truth and is therefore sound."),
        ("INTERMEDIATE", "What is the difference between soundness and completeness of an inference algorithm?",
         ["soundness means it derives only true conclusions; completeness means it can derive every entailed sentence", "they are the same thing", "soundness concerns speed", "completeness concerns memory"], "A",
         "A sound algorithm never derives false conclusions, while a complete algorithm derives every sentence entailed by the knowledge base."),
        ("INTERMEDIATE", "In a semantic network, what do the links typically represent?",
         ["relationships between concepts", "electrical wires", "menu items", "binary numbers"], "B",
         "Edges in a semantic network label relationships such as 'is-a' or 'has-part' between concepts."),
        ("INTERMEDIATE", "A decision tree represents knowledge as:",
         ["a single equation", "a linked list of characters", "a series of attribute tests leading to decisions", "a queue of actions"], "C",
         "A decision tree routes a case through attribute tests until a leaf gives the decision."),
        ("INTERMEDIATE", "The AND-OR graph is a representation used for:",
         ["training neural networks", "compressing images", "sorting arrays", "expressing decomposable problems where subgoals combine"], "D",
         "In an AND-OR graph, AND nodes require all subgoals while OR nodes require at least one, supporting problem decomposition."),
        ("INTERMEDIATE", "A frame in frame-based representation contains:",
         ["slots with values describing an object", "random tokens", "a compiled binary", "a list of colours"], "A",
         "A frame is a record-like structure whose slots hold attributes and values describing an object or class."),
        ("INTERMEDIATE", "Which representation is best suited for representing imprecise terms like 'tall' or 'hot'?",
         ["propositional logic", "fuzzy logic", "first-order logic", "bitmaps"], "B",
         "Fuzzy logic allows degrees of membership so that imprecise terms like 'tall' can be represented continuously."),
        ("INTERMEDIATE", "In first-order logic, what does the existential quantifier exist x mean?",
         ["for all x", "for no x", "there exists an x such that", "x is false"], "C",
         "The existential quantifier states that there is at least one object x satisfying the formula."),
        ("ADVANCED", "A knowledge base has many rules and you want a reasoning method guaranteed not to make false conclusions. Which property matters most?",
         ["completeness alone", "speed alone", "soundness", "memory usage"], "C",
         "Soundness guarantees that every derived conclusion is a logical consequence of the knowledge base."),
        ("ADVANCED", "Why is forward chaining well-suited to rule-based systems?",
         ["it works backwards from the goal", "it never uses rules", "it requires no facts", "it starts from known facts and applies rules to derive new facts"], "D",
         "Forward chaining begins with known facts and fires rules to generate new facts, matching how data-driven systems work."),
        ("ADVANCED", "A diagnostic expert system that starts with a hypothesis and searches rules backward for supporting evidence uses:",
         ["backward chaining", "forward chaining", "random sampling", "genetic algorithms"], "A",
         "Backward chaining works from a goal backwards through rules to find the facts that would prove it."),
        ("ADVANCED", "Your representation must reason with certainty levels because sensor data is noisy. Which approach is appropriate?",
         ["pure propositional logic", "probabilistic reasoning such as Bayesian networks", "deterministic grammars", "fixed lookup tables"], "B",
         "Bayesian networks model uncertain dependencies between variables and support probabilistic inference."),
        ("ADVANCED", "In a semantic network, the 'is-a' link mainly expresses:",
         ["a temporal relation", "a part-whole physical relation", "a class-inclusion relation (generalization)", "a numerical order"], "C",
         "The is-a link states that an individual belongs to a class, supporting inheritance of properties."),
        ("ADVANCED", "A description-logic-based ontology such as OWL is most useful when you need:",
         ["bit-level arithmetic", "a faster sort", "a way to draw graphs", "automatic classification and shared semantics of a domain"], "D",
         "Description logics support automated classification and give the domain a shared, machine-readable meaning."),
        ("ADVANCED", "The frame problem in AI refers to:",
         ["the difficulty of representing what stays UNCHANGED when an action occurs", "the problem of opening windows", "a memory leak in recursion", "the frame rate of a video"], "A",
         "The frame problem is the challenge of efficiently representing the many things that do not change after an action."),
        ("ADVANCED", "Which reasoning approach lets an expert system derive conclusions even when the exact truth of premises is uncertain?",
         ["modus tollens only", "probabilistic or fuzzy inference with degrees of belief", "binary logic", "exhaustive enumeration"], "B",
         "Probabilistic and fuzzy inference propagate degrees of belief so conclusions can be drawn from uncertain premises."),
        ("ADVANCED", "A rule base contains 'Bird(Tweety)', 'NotFlies(Tweety)' and a default that birds fly. The need to prefer one conclusion over another is handled by:",
         ["syntax errors", "compiling faster", "default logic or non-monotonic reasoning", "larger memory"], "C",
         "Default logic lets a conclusion be retracted when new information contradicts it, which is non-monotonic reasoning."),
        ("ADVANCED", "The main advantage of declarative knowledge over a hard-coded program is that:",
         ["it runs faster", "it requires no facts", "it is easier to update and reason about independently of the program logic", "it removes the need for inference"], "D",
         "Declarative knowledge separates facts from the inference engine, so knowledge can be added or changed without rewriting code."),
    ],
    104: [
        ("BEGINNER", "What is machine learning primarily about?",
         ["building systems that learn patterns from data and improve with experience", "writing fixed rules by hand", "building faster CPUs", "managing databases"], "A",
         "Machine learning builds models that infer patterns from data and improve as they see more examples."),
        ("BEGINNER", "Which type of learning uses labelled data (input-output pairs)?",
         ["unsupervised learning", "supervised learning", "reinforcement learning only", "genetic programming"], "B",
         "Supervised learning trains on examples that include both input features and known correct outputs."),
        ("BEGINNER", "In supervised learning, what is the label?",
         ["the input feature", "the known correct output for a training example", "the weight of a neuron", "the learning rate"], "C",
         "A label is the known correct answer paired with an input in a labelled training dataset."),
        ("BEGINNER", "Which learning type groups data without any labels?",
         ["supervised learning", "semi-supervised learning", "reinforcement learning", "unsupervised learning (clustering)"], "D",
         "Unsupervised learning finds structure in unlabelled data, and clustering is its most common form."),
        ("BEGINNER", "What is a training set?",
         ["the data used to teach the model", "the final deployment logs", "the test for the user", "the weight matrix"], "A",
         "The training set is the portion of data the model learns from during training."),
        ("BEGINNER", "What is the role of the test set?",
         ["to train the model", "to evaluate how well the trained model generalizes to unseen data", "to store backups", "to label data"], "B",
         "The test set measures performance on data the model never saw during training."),
        ("BEGINNER", "Which of these is a classification task?",
         ["predicting a house price", "predicting whether an email is spam or not", "grouping customers by similarity", "finding frequent items"], "C",
         "Predicting a discrete category such as spam or not spam is a classification task."),
        ("BEGINNER", "Which of these is a regression task?",
         ["classifying images", "detecting fraud with categories", "predicting tomorrow's temperature as a number", "clustering news"], "D",
         "Regression predicts a continuous numeric value, such as a temperature reading."),
        ("BEGINNER", "What is overfitting?",
         ["the model memorizes the training data and fails on new data", "the model learns nothing", "the model trains too quickly", "the dataset is too large"], "A",
         "Overfitting means the model fits the training data too closely and does not generalize to new data."),
         ("BEGINNER", "What is feature engineering?",
          ["selecting or creating input variables that help a model learn patterns", "deleting the training data", "increasing the learning rate", "hardcoding model predictions"], "A",
          "Feature engineering transforms raw data into informative inputs, giving the model the attributes it needs to learn patterns."),
        ("INTERMEDIATE", "A dataset has 1000 labelled emails and you train a model that assigns each to spam or not spam. This is an example of:",
         ["regression", "binary classification", "clustering", "dimensionality reduction"], "B",
         "Assigning each email to one of two discrete classes is binary classification."),
        ("INTERMEDIATE", "In k-nearest neighbours, which parameter controls how many neighbours vote on the prediction?",
         ["the learning rate", "the epoch count", "the value of k", "the batch size"], "C",
         "The parameter k sets how many of the closest training examples vote on a new prediction."),
        ("INTERMEDIATE", "A model gets 99% accuracy on training data but only 60% on test data. The most likely problem is:",
         ["underfitting", "missing test data", "too few epochs", "overfitting"], "D",
         "The large gap between training and test accuracy is the classic signature of overfitting."),
        ("INTERMEDIATE", "For a regression problem, which metric measures the average squared prediction error?",
         ["mean squared error (MSE)", "accuracy", "precision", "recall"], "A",
         "MSE averages the squared differences between predicted and actual values."),
        ("INTERMEDIATE", "For classification, the fraction of correct predictions out of all predictions is called:",
         ["loss", "accuracy", "variance", "bias"], "B",
         "Accuracy is the proportion of predictions the model got right."),
        ("INTERMEDIATE", "In gradient descent, what does the learning rate control?",
         ["the number of features", "the size of each update step to the model's parameters", "the size of the dataset", "the number of neighbours"], "C",
         "The learning rate scales how much the parameters move in each gradient step."),
        ("INTERMEDIATE", "A clustering algorithm assigns each point to the nearest of k centroids. Which algorithm is this?",
         ["linear regression", "decision tree", "logistic regression", "k-means"], "D",
         "K-means iteratively assigns points to the nearest centroid and recomputes the centroids."),
        ("INTERMEDIATE", "In reinforcement learning, what does the agent receive after each action?",
         ["a reward signal", "a labelled example", "a validation set", "a gradient"], "A",
         "The environment returns a reward that tells the agent how good the action was."),
        ("INTERMEDIATE", "A model with high variance most likely has what property?",
         ["it is too simple", "it fits training data too closely and changes a lot with new data", "it always predicts the mean", "it never trains"], "B",
         "High variance means the model reacts strongly to particular training samples and does not generalize steadily."),
        ("INTERMEDIATE", "Which of the following is a supervised learning model?",
         ["k-means clustering", "association rule mining", "a decision tree trained on labelled data", "autoencoders"], "C",
         "A decision tree trained with input-output pairs is a supervised model."),
        ("ADVANCED", "Your model performs well on training data but poorly on validation data. Which of these is the BEST first remedy?",
         ["increase model complexity", "train longer without changes", "simplify the model or add regularization", "delete the validation set"], "C",
         "Overfitting is best countered by simplifying the model or adding regularization to reduce variance."),
        ("ADVANCED", "A dataset has 100,000 features but very few samples. Which technique can help?",
         ["increasing epochs", "adding more noise", "adding more layers", "feature selection or regularization"], "D",
         "With many features and few samples, feature selection and regularization prevent the model from overfitting."),
        ("ADVANCED", "Why is k-fold cross-validation better than a single train/test split?",
         ["it uses multiple folds so every sample is used for both training and validation, giving a more reliable estimate", "it is faster to run", "it needs no data", "it removes the need for features"], "A",
         "Cross-validation cycles each fold through validation, so the performance estimate uses all the data."),
        ("ADVANCED", "In reinforcement learning, the exploration-exploitation trade-off means the agent must:",
         ["always exploit", "balance trying new actions (explore) with using known good ones (exploit)", "never explore", "randomly reset"], "B",
         "The agent must explore to discover good actions while exploiting what it already knows works."),
        ("ADVANCED", "Which best describes the bias-variance trade-off?",
         ["increasing variance always lowers bias and vice versa; the goal is the sweet spot that minimizes total error", "high bias and high variance are the same", "the trade-off only applies to unsupervised learning", "there is no trade-off"], "C",
         "Bias and variance tend to move in opposite directions, and the best model balances both to minimize total error."),
        ("ADVANCED", "A bank wants to minimize missed fraud cases (false negatives). Which metric should they prioritize?",
         ["accuracy", "precision", "F1 only", "recall (sensitivity)"], "D",
         "Recall measures the fraction of actual fraud cases that are caught, so maximizing it reduces missed fraud."),
        ("ADVANCED", "A learning curve shows training error staying low while test error stays high. This indicates:",
         ["overfitting (high variance)", "underfitting", "an unbalanced class", "a bug in the loader"], "A",
         "A persistent gap between low training error and high test error is the sign of overfitting."),
        ("ADVANCED", "A dataset with 99% non-spam and 1% spam makes accuracy misleading because:",
         ["accuracy is always correct", "a model predicting only the majority class still scores 99%, hiding poor minority performance", "the model cannot train", "the test set is unused"], "B",
         "With imbalanced classes, predicting the majority class gives high accuracy while failing on the minority."),
        ("ADVANCED", "The primary purpose of regularization such as L2 in a linear model is to:",
         ["increase training accuracy", "speed up data loading", "penalize large weights to prevent overfitting", "add more training data"], "C",
         "L2 regularization adds a penalty on large weights, keeping the model simple and reducing overfitting."),
        ("ADVANCED", "A model trained on historical housing data performs badly in a new city. The most likely cause is:",
         ["the model is too small to run", "feature distribution shift: the new city differs from the training distribution", "the model lacks GPU", "the data had no labels"], "D",
         "When the test data comes from a different distribution than the training data, the model no longer generalizes."),
    ],
    105: [
        ("BEGINNER", "What is the main goal of AI ethics?",
         ["ensuring AI systems are fair, transparent, accountable and beneficial to society", "making AI faster", "reducing AI memory", "publishing research"], "A",
         "AI ethics focuses on fairness, transparency, accountability and the overall benefit of AI to society."),
        ("BEGINNER", "If an AI hiring tool is biased against a group of applicants, which ethical concern is being violated?",
         ["bias and fairness", "processing speed", "storage cost", "network latency"], "B",
         "Treating one group unfairly violates the ethical principle of fairness."),
        ("BEGINNER", "What does algorithmic bias refer to?",
         ["when an algorithm's results systematically favour or harm certain groups", "when an algorithm runs slowly", "when data is encrypted", "when a model is too deep"], "C",
         "Algorithmic bias is a systematic, unfair preference for or against certain groups in the algorithm's results."),
        ("BEGINNER", "Which of these is a well-known application area of AI?",
         ["natural language processing", "a screwdriver", "a filing cabinet", "a power outlet"], "D",
         "Natural language processing, along with vision and robotics, is a major AI application area."),
        ("BEGINNER", "Why is transparency important in AI?",
         ["so users and auditors can understand how decisions are made", "so the code runs faster", "so the model uses less memory", "so the dataset is bigger"], "A",
         "Transparency lets people understand and inspect how an AI system reaches its decisions."),
        ("BEGINNER", "What is a common privacy risk of AI systems that process personal data?",
         ["the data may be misused or leaked", "the data is always deleted", "the data grows slower", "the data is public"], "B",
         "AI systems that store personal data can leak or misuse it if privacy is not protected."),
        ("BEGINNER", "Which technology powers chatbots like ChatGPT?",
         ["database replication", "virtual reality headsets", "large language models", "cryptographic hashing"], "C",
         "Large language models are trained on text and generate the conversational responses of modern chatbots."),
        ("BEGINNER", "What does accountability in AI require?",
         ["that someone can be held responsible for the system's behaviour", "that the model is fast", "that data is free", "that the UI is pretty"], "D",
         "Accountability means clear assignment of responsibility for an AI system's actions and outcomes."),
        ("BEGINNER", "Which of the following is an AI application in healthcare?",
         ["disease detection from medical images", "a paper notebook", "a refrigerator", "a washing machine"], "A",
         "AI systems analyse medical images to help detect diseases such as tumours."),
        ("BEGINNER", "What is deepfake technology used for?",
         ["creating realistic but fake media, which raises misuse concerns", "compressing videos", "backing up files", "wifi routing"], "B",
         "Deepfakes generate convincingly realistic but fake audio or video, raising authenticity and misuse concerns."),
        ("INTERMEDIATE", "A self-driving car must choose between harming a pedestrian or its passenger in an unavoidable crash. Which area of AI ethics deals with this?",
         ["model explainability", "moral decision-making (ethical dilemmas)", "data storage", "network security"], "B",
         "Such unavoidable-harm choices are moral dilemmas studied in the ethics of autonomous systems."),
        ("INTERMEDIATE", "An AI that denies loans using data that correlates with race is demonstrating:",
         ["high accuracy", "good generalization", "disparate impact (bias)", "fast training"], "C",
         "Denying loans based on a proxy for race harms one group and is an example of disparate impact."),
        ("INTERMEDIATE", "To make a model's decisions explainable to a user, which technique is appropriate?",
         ["using SHAP or LIME to explain predictions", "encrypting the weights", "removing labels", "increasing epochs"], "D",
         "SHAP and LIME are post-hoc tools that explain which features drove a particular prediction."),
        ("INTERMEDIATE", "A healthcare AI suggests a wrong diagnosis because it was trained only on one region's patients. This is a problem of:",
         ["lack of generalizability and fairness across groups", "slow inference", "low memory", "visual rendering"], "A",
         "Training on a narrow population makes the model fail on other groups, a fairness and generalization problem."),
        ("INTERMEDIATE", "Which privacy technique adds noise to data so that individual records cannot be identified?",
         ["data encryption at rest only", "differential privacy", "web caching", "lossless compression"], "B",
         "Differential privacy adds calibrated noise so queries reveal trends without exposing individuals."),
        ("INTERMEDIATE", "An AI system that generates news articles indistinguishable from human writing raises what concern?",
         ["misinformation and authenticity", "database size", "battery life", "screen resolution"], "C",
         "Realistic machine-written articles can spread misinformation and blur what is authentic."),
        ("INTERMEDIATE", "Why might an audit of an AI system be required before deployment in banking?",
         ["to verify fairness, safety and compliance with regulations", "to increase the number of users", "to reduce the file size", "to change the logo"], "D",
         "Regulations require proof that credit and lending systems are fair, safe and compliant."),
        ("INTERMEDIATE", "What does 'human-in-the-loop' mean in AI systems?",
         ["a human reviews or intervenes in the AI's decisions", "humans never interact with AI", "only AI makes decisions", "a human controls the power supply"], "A",
         "Human-in-the-loop keeps a person involved in reviewing or overriding AI decisions."),
        ("INTERMEDIATE", "A recommendation system that only shows content similar to what you already watch may create:",
         ["a faster network", "a filter bubble (echo chamber)", "better battery life", "more storage"], "B",
         "Narrow personalization can trap users in a filter bubble that hides opposing or diverse content."),
        ("INTERMEDIATE", "Which principle states that AI should be developed for the benefit of all people?",
         ["beneficence", "efficiency", "speed", "profit maximization"], "C",
         "Beneficence is the ethical principle of acting for the good and well-being of others."),
        ("ADVANCED", "A hospital deploys a diagnostic AI whose outcomes differ across ethnic groups. The most responsible next step is:",
         ["ignore the difference", "deploy anyway to save time", "conduct a fairness audit, retrain with balanced data and monitor outcomes", "delete the model"], "C",
         "A fairness audit identifies the cause, balanced retraining reduces bias, and ongoing monitoring prevents relapse."),
        ("ADVANCED", "A social media platform's engagement-maximizing AI contributes to the spread of harmful content. This is an example of:",
         ["overfitting", "hardware failure", "correct labelling", "misaligned incentives (unintended social harm)"], "D",
         "Optimizing purely for engagement can produce harmful social outcomes the designers did not intend."),
        ("ADVANCED", "Under the principle of meaningful human control, an autonomous weapon system should:",
         ["keep a human accountable for decisions on the use of force", "always operate without humans", "ignore override commands", "only act at night"], "A",
         "Meaningful human control requires that humans remain responsible and able to override lethal decisions."),
        ("ADVANCED", "A company wants to use customer data to train a model. Which practice respects user autonomy?",
         ["secretly collecting data", "obtaining informed consent and allowing opt-out", "selling data without notice", "encrypting the model only"], "B",
         "Informed consent and the option to opt out give users control over how their data is used."),
        ("ADVANCED", "Which strategy best addresses the risk that an AI trained on historical data encodes past discrimination?",
         ["debiasing the data and auditing outcomes across groups", "increasing the dataset size", "using only the newest model", "removing all features"], "C",
         "Debiasing the training data plus auditing results across groups actively counteracts historical discrimination."),
        ("ADVANCED", "A financial model must explain why a loan was denied to satisfy regulations. Which approach is most defensible?",
         ["deploying an opaque deep network with no explanation", "refusing to explain", "ignoring the request", "using interpretable models or post-hoc explanation methods validated for fidelity"], "D",
         "Interpretable models or fidelity-validated explanations satisfy the legal right to an explanation."),
        ("ADVANCED", "When an AI system makes an error that harms a patient, which ethical requirement applies?",
         ["clear accountability and liability mechanisms for the harm", "deleting the logs", "blaming the patient", "hiding the error"], "A",
         "Clear accountability and liability rules determine who is responsible when an AI harms someone."),
        ("ADVANCED", "A government uses facial recognition for mass surveillance. Which concern is most directly raised?",
         ["the models are too large", "civil liberties and privacy of citizens", "the frame rate is low", "the servers are slow"], "B",
         "Mass surveillance with facial recognition threatens citizens' privacy and civil liberties."),
        ("ADVANCED", "To prevent an LLM from producing dangerous instructions, which mitigation is commonly used?",
         ["removing all parameters", "disabling networking", "red-teaming, safety fine-tuning and output filtering", "increasing the context window"], "C",
         "Red-teaming finds harmful outputs, safety fine-tuning reduces them, and filtering blocks remaining ones."),
        ("ADVANCED", "The best way to operationalize ethical principles in an AI product lifecycle is to:",
         ["write them once and never revisit", "embed them in a design-time and runtime governance process with audits", "document them but ignore them", "leave them to the end users"], "D",
         "Ethical principles only take effect when embedded in ongoing governance with audits at design and runtime."),
    ],
}
