# -*- coding: utf-8 -*-
"""
Question bank for subject 19: OS104 - System Programming.
Category: Operating Systems & System Programming.

Topics:
  91: System Calls & Libraries
  92: Signals & IPC
  93: Interrupts & Exceptions
  94: Device Drivers
  95: Assemblers & Compilers

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    91: [
        ("BEGINNER", "Which mechanism allows a user program to request services from the operating system kernel?",
         ["a system call", "a library function", "a device driver", "a shell script"], "A",
         "A system call is the programmed interface through which a user process asks the kernel to perform privileged operations."),
        ("BEGINNER", "Which header file on Linux declares common POSIX system calls such as read and write?",
         ["unistd.h", "stdio.h", "stdlib.h", "math.h"], "B",
         "unistd.h declares POSIX system call prototypes such as read, write, open, close and fork."),
        ("BEGINNER", "What does the fork system call do?",
         ["terminates the current process", "creates a new process as a copy of the calling process", "loads a new program into the current process", "changes the current working directory"], "C",
         "fork creates a child process that is a near-identical copy of the calling parent process."),
        ("BEGINNER", "Which system call replaces the current process image with a new program?",
         ["fork", "clone", "execve", "wait"], "D",
         "execve loads a new executable into the current process, replacing its previous code and data."),
        ("BEGINNER", "What is a library in the context of system programming?",
         ["a set of precompiled routines that programs can link against", "a hardware device for storage", "a kernel module", "a command-line utility"], "A",
         "A library is a collection of precompiled functions that application programs can reuse by linking against it."),
        ("BEGINNER", "What does the open system call return on success?",
         ["a pointer", "a file descriptor", "a FILE structure", "a device number"], "B",
         "open returns a non-negative integer file descriptor that identifies the opened file to later calls."),
        ("BEGINNER", "Which library implements the standard C functions that wrap low-level system calls on Linux?",
         ["libc", "libm", "libpthread", "libz"], "C",
         "libc provides the standard C library functions, including wrappers around most Linux system calls."),
        ("BEGINNER", "What does the stat system call retrieve?",
         ["information about a file such as size and permissions", "the contents of a file", "the number of running processes", "the kernel version"], "D",
         "stat returns a struct with metadata about a file, including its size, owner and permissions."),
        ("BEGINNER", "What is errno in C system programming?",
         ["a global variable that records the error number of the last failed system call", "a file containing error messages", "a signal number", "a return code from main"], "A",
         "errno is set by system calls and library functions to an error number describing why the last operation failed."),
        ("BEGINNER", "Which tool can be used to trace which system calls a program makes?",
         ["strace", "gcc", "make", "grep"], "B",
         "strace intercepts and records the system calls and signals of a running process."),
        ("INTERMEDIATE", "A program calls read with a buffer, count and file descriptor. What does read return when it reaches the end of the file?",
         ["-1", "0", "1", "the buffer address"], "C",
         "A read that returns 0 indicates that end-of-file was reached and no more data is available."),
        ("INTERMEDIATE", "A process calls fork and then prints its PID. How many times is the print statement executed?",
         ["once", "twice", "four times", "zero times"], "D",
         "After a successful fork both the parent and child continue execution, so the statement runs once in each process."),
        ("INTERMEDIATE", "Why is the result of write sometimes less than the requested count?",
         ["the buffer was too small", "write may be interrupted or the device may accept only part of the data", "the file descriptor is invalid", "the kernel always pads the output"], "A",
         "write can perform a partial transfer, so robust programs must loop until the full count is written or an error occurs."),
        ("INTERMEDIATE", "A program opens a file, then calls close on its descriptor. What happens if it reads from the descriptor afterwards?",
         ["the read returns stale data", "the read returns the cached contents", "the read fails with EBADF", "the read reopens the file"], "B",
         "Using a closed file descriptor is invalid and the read fails with the EBADF error indicating a bad descriptor."),
        ("INTERMEDIATE", "Which flag combination passed to open creates the file if it does not exist?",
         ["O_RDONLY", "O_CREAT", "O_TRUNC", "O_APPEND"], "C",
         "O_CREAT tells open to create the file when it does not already exist."),
        ("INTERMEDIATE", "What does the wait system call allow a parent process to do?",
         ["sleep until any child process terminates and obtain its status", "pause all children", "resume a stopped child", "kill all children"], "D",
         "wait blocks the parent until a child terminates and returns that child's status for inspection."),
        ("INTERMEDIATE", "How does a system call transfer control from user mode to kernel mode?",
         ["through a software trap instruction such as syscall", "by calling a normal function", "by raising a hardware interrupt to the CPU", "through a device driver callback"], "A",
         "A trap or syscall instruction switches the CPU into kernel mode and jumps to the kernel's system call handler."),
        ("INTERMEDIATE", "What is the main difference between a system call and a library function call?",
         ["library calls run in user mode while system calls enter the kernel", "system calls run in user mode", "library calls are always slower", "there is no difference"], "B",
         "A library function executes in user space, while a system call switches the processor into kernel mode."),
        ("INTERMEDIATE", "A program wants the highest speed by avoiding per-call overhead. What buffering approach is most common in libc?",
         ["using buffered I/O via FILE* streams", "calling read for every byte", "using direct memory-mapped registers", "opening the file many times"], "C",
         "stdio functions such as fread buffer data internally, reducing the number of expensive system calls."),
        ("INTERMEDIATE", "What happens if a process ignores the return value of a system call that can fail?",
         ["nothing, return values are optional", "the failure goes unnoticed, potentially corrupting program logic", "the kernel terminates the process", "the compiler warns but it is always safe"], "D",
         "System calls report errors through their return value and errno, so ignoring them can hide failures that later cause incorrect behavior."),
        ("ADVANCED", "Why must a multithreaded program use the per-thread variants of errno?",
         ["errno is a thread-local value so each thread sees its own error without interference", "errno is shared to coordinate errors", "errno is stored in the kernel", "errno is disabled in threads"], "A",
         "On Linux errno is thread-local, so concurrent threads do not clobber each other's error codes."),
        ("ADVANCED", "A server wants to handle many concurrent clients without one thread per client. Which combination is most scalable?",
         ["blocking I/O with one thread per connection", "nonblocking descriptors combined with poll or epoll", "spawning a fork per client", "sleeping between accept calls"], "B",
         "Nonblocking descriptors with an event loop such as epoll allow a single thread to multiplex thousands of connections."),
        ("ADVANCED", "Why might a file write that succeeds not be durable across a sudden power loss?",
         ["the data may still be sitting in the kernel page cache", "the file was opened read-only", "write always writes to disk immediately", "the data is lost because the buffer is in user space"], "C",
         "The kernel buffers written data in the page cache and flushes it later, so fsync is needed to force it to disk."),
        ("ADVANCED", "A library must be used by many programs without copying its code into each executable. Which approach is most appropriate?",
         ["a static library", "a shared library", "a header-only library", "a command-line script"], "D",
         "A shared library is linked at runtime and shared in memory by many processes, saving disk and memory."),
        ("ADVANCED", "What is the purpose of the mmap system call in high-performance file I/O?",
         ["it maps a file directly into the process address space, letting reads and writes go through normal memory", "it copies the file into the page cache", "it locks the file against other processes", "it increases the file descriptor limit"], "A",
         "mmap places the file contents in the process's virtual memory, so the kernel manages paging without explicit read and write calls."),
        ("ADVANCED", "Why is execve never expected to return on success?",
         ["the calling process image is replaced, so there is no code left to continue", "the kernel queues the return", "execve always fails", "the process is automatically killed"], "B",
         "On success execve replaces the entire process image, so the old program no longer exists and control never returns to it."),
        ("ADVANCED", "A system call is interrupted by a signal and returns -1 with errno set to EINTR. What should a robust program do?",
         ["retry the system call", "treat it as a fatal error", "ignore the return value", "reboot the machine"], "C",
         "EINTR means the call was interrupted before completing, so the correct response is usually to retry it."),
        ("ADVANCED", "What is the key advantage of system calls such as sendfile for network file transfer?",
         ["data is copied between file and socket in the kernel without user-space copying", "it uses slower buffered I/O", "it compresses data during transfer", "it requires the CPU to copy every byte twice"], "D",
         "sendfile copies data directly between file descriptors inside the kernel, avoiding the expensive round trip through user buffers."),
        ("ADVANCED", "Why does a setuid program need careful handling of environment variables?",
         ["an untrusted environment can be used to influence library loading or execution, leading to privilege escalation", "environment variables speed up the program", "the kernel requires environment variables", "setuid programs cannot read the environment"], "A",
         "A privileged process that loads libraries based on environment variables such as LD_PRELOAD can be exploited to run attacker code."),
        ("ADVANCED", "What does lseek allow a program to do on a file descriptor?",
         ["move the file offset to a given position for the next read or write", "set the file permissions", "truncate the file", "change the file owner"], "B",
         "lseek changes the current file offset, allowing random access to different positions within a file."),
    ],
    92: [
        ("BEGINNER", "What is a signal in Unix system programming?",
         ["an asynchronous notification sent to a process", "a hardware error", "a library function", "a file format"], "A",
         "A signal is a software notification delivered asynchronously to a process to inform it of an event."),
        ("BEGINNER", "What happens to a process when it receives SIGINT from the terminal?",
         ["it is terminated by default", "it continues running", "it is paused", "it ignores the signal"], "B",
         "SIGINT, generated by pressing Ctrl-C, terminates the receiving process by default."),
        ("BEGINNER", "Which system call installs a custom signal handler in a C program?",
         ["signal", "kill", "raise", "alarm"], "C",
         "The signal function registers a handler function that will be invoked when the specified signal arrives."),
        ("BEGINNER", "What does SIGKILL do to a process?",
         ["it can be caught but ignored", "it terminates the process and cannot be caught or ignored", "it pauses the process", "it prints a warning"], "D",
         "SIGKILL forcibly terminates a process and cannot be caught, blocked or ignored by the process."),
        ("BEGINNER", "What is an IPC mechanism?",
         ["a way for processes to communicate and share data", "a network protocol", "a debugging tool", "a scheduling algorithm"], "A",
         "Inter-process communication (IPC) refers to the mechanisms by which processes exchange data and synchronize."),
        ("BEGINNER", "Which simple IPC mechanism transmits a stream of bytes between two processes?",
         ["a pipe", "a register", "a signal mask", "a page table"], "B",
         "A pipe provides a unidirectional byte stream connecting two processes."),
        ("BEGINNER", "What is a shared memory segment?",
         ["memory that multiple processes map and access concurrently", "memory only the kernel uses", "a file on disk", "a network buffer"], "C",
         "Shared memory is a region of memory mapped into the address space of multiple processes so they can share data."),
        ("BEGINNER", "Which function is used by a process to send a signal to another process?",
         ["kill", "wait", "exec", "fork"], "D",
         "The kill system call sends a specified signal to a process or process group."),
        ("BEGINNER", "What does a message queue provide?",
         ["a linked-list based mechanism to send structured messages between processes", "a high-speed network", "a shared register bank", "a backup service"], "A",
         "A message queue lets processes exchange discrete messages of data through kernel-managed queues."),
        ("BEGINNER", "What does SIGSEGV indicate?",
         ["an invalid memory access, typically a segfault", "a normal program exit", "a keyboard interrupt", "an arithmetic error"], "B",
         "SIGSEGV is sent when a process accesses memory it is not allowed to access, causing a segmentation fault."),
        ("INTERMEDIATE", "A pipe is created between a parent and child. What must the parent do to write to the child?",
         ["close the read end and write to the write end", "close the write end and read from the read end", "fork again", "open a new file"], "C",
         "Each process closes the end it does not use; the parent closes the read end and writes to the write end."),
        ("INTERMEDIATE", "A process installs a handler for SIGINT and then presses Ctrl-C. What runs?",
         ["the custom handler instead of the default action", "the default handler", "nothing", "the shell's handler"], "D",
         "When a signal has a custom handler installed, that handler is invoked in place of the default action."),
        ("INTERMEDIATE", "Why must a signal handler avoid calling most library functions?",
         ["signal handlers are restricted to async-signal-safe functions to avoid corrupting state", "library functions are too slow", "the kernel blocks all calls", "handlers run in kernel mode"], "A",
         "Only async-signal-safe functions may be called from a signal handler because the handler may interrupt any point of the program."),
        ("INTERMEDIATE", "A process wants the kernel to send it SIGALRM after 5 seconds. Which system call does it use?",
         ["alarm", "sleep", "pause", "timerfd"], "B",
         "alarm arranges for the kernel to deliver SIGALRM to the process after the specified number of seconds."),
        ("INTERMEDIATE", "Two processes share a memory segment but see inconsistent data. What is missing?",
         ["synchronization, such as a semaphore or mutex", "larger memory", "a faster CPU", "more system calls"], "C",
         "Without synchronization primitives, concurrent access to shared memory can produce race conditions and inconsistent data."),
        ("INTERMEDIATE", "What does SIGCHLD tell a parent process?",
         ["that a child process has terminated or stopped", "that a child was created", "that the parent has no children", "that the disk is full"], "D",
         "The kernel sends SIGCHLD to a parent when one of its children terminates, stops, or resumes."),
        ("INTERMEDIATE", "What is a named pipe, also called a FIFO?",
         ["a pipe that exists in the filesystem and can be opened by unrelated processes", "a pipe only the kernel can use", "a socket on a remote host", "a special device for printing"], "A",
         "A FIFO is a named pipe that appears as a file and allows communication between unrelated processes."),
        ("INTERMEDIATE", "How does a process temporarily prevent a signal from being delivered?",
         ["by blocking it with sigprocmask or sigaction mask", "by changing its priority", "by closing a file descriptor", "by forking a child"], "B",
         "A process can block selected signals so they are deferred until the mask is changed again."),
        ("INTERMEDIATE", "What is a semaphore used for in IPC?",
         ["synchronizing access to a shared resource", "storing large files", "compressing data", "naming processes"], "C",
         "A semaphore is a counter used to control access to a shared resource and coordinate concurrent processes."),
        ("INTERMEDIATE", "A server wants to receive one of several signals and act on each appropriately. Which function lets it install distinct handlers?",
         ["sigaction", "signal", "sigprocmask", "raise"], "D",
         "sigaction gives detailed control, allowing a distinct handler to be installed for each signal."),
        ("ADVANCED", "Why are condition variables superior to spin-waiting on a shared flag for thread synchronization?",
         ["they block the waiter and let the CPU do useful work instead of busy-waiting", "they always run faster", "they avoid the operating system entirely", "they remove the need for locks"], "A",
         "Condition variables park waiting threads, letting the scheduler run other work rather than burning CPU in a spin loop."),
        ("ADVANCED", "A process blocks SIGTERM, then unblocks it later. What happens to a SIGTERM that arrived while blocked?",
         ["it is delivered as soon as the signal is unblocked", "it is lost permanently", "it is ignored forever", "it crashes the process immediately"], "B",
         "Blocked signals are pending and are delivered once the process unblocks them."),
        ("ADVANCED", "Why is it dangerous to read errno inside a signal handler?",
         ["errno is not guaranteed to be async-signal-safe and may be overwritten by the interrupted code", "errno is always zero in handlers", "signals cannot access errno", "errno lives in the kernel"], "C",
         "A signal handler may interrupt code that just set errno, and the handler's own calls could change it, so handlers should save and restore errno."),
        ("ADVANCED", "A real-time signal is preferable over SIGUSR1 when what property is needed?",
         ["real-time signals are queued and carry an integer value, so none are lost", "real-time signals are faster", "real-time signals require no handler", "real-time signals only work for the root user"], "D",
         "Standard signals can be coalesced and carry no data, whereas real-time signals are queued and deliver an attached value."),
        ("ADVANCED", "What is the primary risk when using a shared memory segment that is not protected by a mutex or semaphore?",
         ["data races that produce corrupted or inconsistent values", "the segment fills the disk", "the kernel panics", "the network becomes congested"], "A",
         "Unsynchronized concurrent access lets multiple processes race, corrupting shared data."),
        ("ADVANCED", "A child writes a large amount of data to a pipe while the parent sleeps. What happens when the pipe buffer fills?",
         ["the child's write blocks until the parent reads", "the child is killed", "the data is dropped", "the pipe grows unboundedly"], "B",
         "Writes to a full pipe block, waiting until the reading process drains some data and makes space."),
        ("ADVANCED", "What is a deadlock in the context of IPC synchronization?",
         ["two or more processes each wait forever for a resource held by the other", "a process that is too slow", "a signal that is ignored", "a message that is too large"], "C",
         "Deadlock occurs when every participant holds a resource another needs, so all wait indefinitely."),
        ("ADVANCED", "Why might a programmer prefer mmap-based shared memory over System V shared memory?",
         ["POSIX shm is file-based, easier to manage, and integrates with standard file APIs", "System V shm is faster", "mmap cannot be shared", "POSIX shm is always secure"], "D",
         "POSIX shared memory uses named files, is simpler to control, and interoperates cleanly with ftruncate and mmap."),
        ("ADVANCED", "Which issue can arise when a handler is invoked from inside a library that is not reentrant?",
         ["the library's internal state may be corrupted because the handler runs in the middle of its work", "the library gains extra privileges", "the library deletes the signal", "the handler never executes"], "A",
         "If a signal interrupts a non-reentrant library function and the handler calls it again, the internal state can be corrupted."),
        ("ADVANCED", "A system call returns -1 with errno EAGAIN while acquiring a System V semaphore. What does this mean?",
         ["the semaphore operation could not complete without blocking and nonblocking mode was requested", "the semaphore is corrupt", "the process has no memory", "the kernel has crashed"], "B",
         "EAGAIN indicates the operation could not proceed immediately and blocking was disabled via IPC_NOWAIT."),
    ],
    93: [
        ("BEGINNER", "What is an interrupt?",
         ["an event that temporarily halts the CPU to handle a high-priority task", "a compiler warning", "a type of process", "a network packet"], "A",
         "An interrupt is a hardware or software event that causes the CPU to pause current work and run a handler."),
        ("BEGINNER", "What is an exception in the context of a CPU?",
         ["a synchronous event generated by the executing instruction, such as a fault or trap", "a software bug that always crashes", "a user-mode function call", "a device malfunction"], "B",
         "An exception is a synchronous event raised by the currently executing instruction, including faults, traps and aborts."),
        ("BEGINNER", "What does an interrupt handler do?",
         ["it services the interrupt and restores the interrupted context", "it deletes the interrupted process", "it compiles the program", "it prints an error message"], "C",
         "The interrupt handler deals with the cause of the interrupt, then returns control to the interrupted code."),
        ("BEGINNER", "What is the interrupt vector table?",
         ["a table mapping each interrupt or exception to the address of its handler", "a table of running processes", "a list of device drivers", "a cache of files"], "D",
         "The interrupt descriptor or vector table stores the entry point of the handler for every interrupt and exception."),
        ("BEGINNER", "Which of the following is an example of a synchronous exception?",
         ["a page fault", "a keyboard press", "a timer tick", "a network packet arrival"], "A",
         "A page fault is triggered synchronously by an instruction that references an unmapped page."),
        ("BEGINNER", "What is a trap instruction?",
         ["an instruction that deliberately transfers control to the operating system", "an instruction that halts the CPU", "an instruction that multiplies", "an instruction that prints"], "B",
         "A trap is an instruction that intentionally causes an exception so a program can request kernel services."),
        ("BEGINNER", "What is an interrupt latency?",
         ["the time between when an interrupt occurs and when its handler begins executing", "the time a process spends sleeping", "the size of an interrupt packet", "the number of interrupts per second"], "C",
         "Interrupt latency measures the delay from the interrupt request until the handler starts running."),
        ("BEGINNER", "What is a hardware interrupt driven by?",
         ["a physical device such as a keyboard, disk or timer", "a software instruction", "a process schedule", "a compiler decision"], "D",
         "Hardware interrupts are generated by devices to signal the CPU that they need attention."),
        ("BEGINNER", "What happens to the CPU when an interrupt fires?",
         ["it saves the current context and jumps to the handler", "it reboots", "it empties all registers", "it stops forever"], "A",
         "The CPU saves the interrupted state and transfers control to the appropriate interrupt handler."),
        ("BEGINNER", "What is a software interrupt?",
         ["an interrupt triggered by an instruction, such as a system call or breakpoint", "an interrupt from the power supply", "an interrupt that never runs", "a type of virus"], "B",
         "Software interrupts are raised programmatically by instructions like syscall or int to invoke kernel services."),
        ("INTERMEDIATE", "Why is it important that interrupt handlers be fast?",
         ["long handlers delay other interrupts and increase system latency", "handlers use the network", "the CPU forgets the context", "long handlers delete the process"], "C",
         "A slow handler blocks the CPU from servicing other interrupts, hurting responsiveness and throughput."),
        ("INTERMEDIATE", "A divide-by-zero operation causes which type of exception?",
         ["a fault", "a nonmaskable interrupt", "a device interrupt", "a trap"], "D",
         "Divide-by-zero is a synchronous fault generated by the arithmetic instruction that attempted the division."),
        ("INTERMEDIATE", "When a page fault occurs, what does the handler usually do?",
         ["it loads the required page from disk and resumes the faulting instruction", "it kills the process", "it ignores the fault", "it resets the CPU"], "A",
         "The page fault handler brings the needed page into memory and lets the faulting instruction be retried."),
        ("INTERMEDIATE", "Why do modern kernels split interrupt processing into top-half and bottom-half work?",
         ["to keep critical handler work short and defer heavy work to a safer context", "to run handlers in parallel", "to disable interrupts completely", "to save memory"], "B",
         "The top half performs minimal urgent work while the bottom half runs later with interrupts enabled to finish the task."),
        ("INTERMEDIATE", "What is a maskable interrupt?",
         ["an interrupt that can be disabled by the CPU using a flag such as IF", "an interrupt that always runs", "an interrupt with no handler", "an interrupt from the timer"], "C",
         "A maskable interrupt can be temporarily disabled by clearing the interrupt flag so the CPU ignores it."),
        ("INTERMEDIATE", "What is a non-maskable interrupt (NMI) typically used for?",
         ["serious conditions like hardware failures that must be handled immediately", "regular timer ticks", "keyboard input", "ordinary file I/O"], "D",
         "NMIs cannot be blocked and are reserved for critical events such as memory errors and watchdogs."),
        ("INTERMEDIATE", "What is the difference between a fault and a trap?",
         ["a fault reports an error and re-executes the instruction, while a trap is a deliberate jump to the handler", "a fault is always fatal", "a trap cannot be handled", "there is no difference"], "A",
         "Faults are often recoverable and the instruction is retried, whereas traps transfer control intentionally for system calls."),
        ("INTERMEDIATE", "Which mechanism delivers a device interrupt to the correct handler?",
         ["the interrupt vector table indexed by the interrupt number", "a global variable", "a scheduler", "the file system"], "B",
         "Each interrupt number points into the interrupt vector table to find the handler registered for that device."),
        ("INTERMEDIATE", "Why must a kernel disable interrupts while updating critical structures?",
         ["to prevent concurrent modification by interrupt handlers", "to increase speed", "to allow more interrupts", "to save disk space"], "C",
         "Disabling interrupts stops handlers from running during the critical section, preventing races on shared kernel data."),
        ("INTERMEDIATE", "What is the purpose of an interrupt request (IRQ) line?",
         ["a hardware line a device uses to signal the CPU that it needs service", "a line of source code", "a kernel log", "a network address"], "D",
         "Devices assert IRQ lines to interrupt the CPU and request that their handler be invoked."),
        ("ADVANCED", "Why might nested interrupts be dangerous?",
         ["a second interrupt can re-enter a handler before the first finishes, corrupting stack and state", "nested interrupts are always fatal", "they run too slowly", "they waste disk space"], "A",
         "Nested interrupts re-enter the handler stack and risk corrupting shared state, so kernels often mask interrupts during handlers."),
        ("ADVANCED", "What is a spurious interrupt?",
         ["an interrupt with no real source, often due to electrical noise or line glitches", "an interrupt that runs twice", "a software trap", "an interrupt with a high priority"], "B",
         "A spurious interrupt is a stray signal with no actual device request, which the handler must acknowledge and ignore."),
        ("ADVANCED", "Why do operating systems use an interrupt priority scheme?",
         ["to let urgent devices preempt lower-priority handlers", "to make all interrupts equal", "to disable the timer", "to save memory"], "C",
         "Priority levels allow a higher-priority device interrupt to preempt a lower-priority handler in progress."),
        ("ADVANCED", "How does an edge-triggered interrupt differ from a level-triggered one?",
         ["edge-triggered responds to a change in signal level while level-triggered responds to the level being active", "edge-triggered is slower", "level-triggered cannot be handled", "there is no difference"], "D",
         "Edge triggering reacts on the signal transition, while level triggering reacts while the signal remains asserted."),
        ("ADVANCED", "What problem can occur if a shared interrupt line handler does not check which device asserted the interrupt?",
         ["it may service the wrong device or miss a device that needs service", "the kernel crashes", "the CPU overheats", "the system reboots"], "A",
         "On shared IRQ lines the handler must query each device to find the real source, otherwise requests can be mishandled."),
        ("ADVANCED", "What is the role of the interrupt controller (such as an APIC)?",
         ["it collects device interrupts and forwards them to the CPU with priority and routing information", "it stores the file system", "it schedules processes", "it compiles the kernel"], "B",
         "The interrupt controller aggregates, prioritizes and routes interrupts from many devices to the CPU."),
        ("ADVANCED", "Why should time-critical driver work avoid running in the top half?",
         ["the top half runs with interrupts disabled and must be minimal to keep latency low", "the top half has too much memory", "the top half is user mode", "the top half cannot access registers"], "C",
         "Top-half code runs with interrupts masked, so heavy work there blocks all other interrupts and raises system latency."),
        ("ADVANCED", "What is an exception frame?",
         ["the saved register context pushed when an exception occurs so the handler can restore it", "a window on screen", "a network packet", "a data structure for files"], "D",
         "The CPU pushes the exception frame containing the saved state, which the handler pops when returning."),
        ("ADVANCED", "A machine check exception (MCE) most commonly signals what?",
         ["a hardware error such as uncorrectable memory corruption", "a normal system call", "a keyboard event", "a page allocation"], "A",
         "A machine check exception indicates a detected hardware error, such as a memory or bus failure, that needs handling."),
        ("ADVANCED", "Why do real-time systems often require predictable interrupt latency?",
         ["tasks must respond to external events within hard deadlines, so worst-case latency must be bounded", "to reduce electricity use", "to make the GUI prettier", "to store more data"], "B",
         "Real-time workloads need guaranteed worst-case response times, making bounded and predictable interrupt latency essential."),
    ],
    94: [
        ("BEGINNER", "What is a device driver?",
         ["a kernel module that controls a hardware device", "a user application", "a file format", "a network protocol"], "A",
         "A device driver is software that gives the kernel a uniform interface to a specific hardware device."),
        ("BEGINNER", "Which part of the operating system talks directly to hardware devices?",
         ["the kernel's device drivers", "the shell", "the compiler", "the assembler"], "B",
         "Device drivers run in the kernel and communicate directly with the hardware they control."),
        ("BEGINNER", "What is an I/O port?",
         ["an address through which the CPU communicates with a device", "a network socket", "a serial port", "a memory buffer"], "C",
         "An I/O port is a numbered address used by the CPU to send commands and data to a device."),
        ("BEGINNER", "What is memory-mapped I/O?",
         ["a scheme where device registers appear as memory addresses accessed with normal loads and stores", "I/O done by the GPU", "I/O over the network", "I/O that uses no CPU"], "D",
         "In memory-mapped I/O, device control registers are assigned addresses in the memory space and accessed like ordinary memory."),
        ("BEGINNER", "What is the primary interface a driver provides to user-space applications?",
         ["special files under /dev plus ioctl, read and write calls", "a web page", "a GUI window", "an email account"], "A",
         "Drivers expose device files in /dev that applications access through standard file operations and ioctl."),
        ("BEGINNER", "What is a character device?",
         ["a device that transfers data one character or byte at a time", "a device that stores blocks", "a device with no output", "a network device"], "B",
         "Character devices handle data as a byte stream, such as keyboards, serial ports and terminals."),
        ("BEGINNER", "What is a block device?",
         ["a device that reads and writes data in fixed-size blocks, such as a disk", "a device that prints text", "a device with no storage", "a sound card"], "C",
         "Block devices transfer data in fixed-size blocks and are typically used for storage such as disks."),
        ("BEGINNER", "Which command lists the block devices attached to a Linux system?",
         ["lsblk", "grep", "make", "top"], "D",
         "lsblk lists information about all available block devices in a readable tree format."),
        ("BEGINNER", "What does the ioctl system call allow an application to do?",
         ["send device-specific control commands to a driver", "compile a program", "create a file", "start a server"], "A",
         "ioctl lets user programs issue device-specific operations that do not fit into standard read or write."),
        ("BEGINNER", "What is a kernel module?",
         ["a loadable unit of kernel code, such as a driver, that can be inserted at runtime", "a user script", "a configuration file", "a shell command"], "B",
         "A kernel module is a piece of kernel code that can be loaded and unloaded dynamically, commonly a device driver."),
        ("INTERMEDIATE", "Why must device drivers be extra careful about memory safety?",
         ["a bug in a driver runs in kernel mode and can crash the whole system", "drivers run in user mode", "drivers are always safe", "bugs only affect one process"], "C",
         "Driver code executes with kernel privileges, so a single memory error can corrupt the kernel and crash the entire system."),
        ("INTERMEDIATE", "What is a device tree?",
         ["a data structure describing the hardware attached to a system, used during boot", "a folder of drivers", "a scheduling queue", "a file system index"], "D",
         "The device tree describes hardware components and how they are connected, letting the kernel probe and configure devices."),
        ("INTERMEDIATE", "Which method lets the CPU avoid repeatedly polling a device for completion?",
         ["interrupt-driven I/O", "busy polling", "sleeping forever", "blocking the network"], "A",
         "With interrupt-driven I/O the device interrupts the CPU when done, instead of the CPU constantly checking status."),
        ("INTERMEDIATE", "What is DMA (direct memory access)?",
         ["a mechanism where hardware transfers data to memory without CPU involvement", "a scheduling algorithm", "a type of driver", "a security protocol"], "B",
         "DMA lets a device move data directly between itself and memory, freeing the CPU for other work."),
        ("INTERMEDIATE", "What is the major and minor number of a device file?",
         ["the major identifies the driver and the minor identifies the specific device instance", "the size and speed", "the owner and group", "the read and write counts"], "C",
         "The major number selects which driver handles the device, while the minor number identifies a particular instance."),
        ("INTERMEDIATE", "A driver needs to handle high data throughput. Which transfer method is most efficient?",
         ["DMA with interrupts", "polling one byte at a time", "reading via a web server", "using a shell script"], "D",
         "DMA moves large blocks directly between device and memory, minimizing CPU involvement and yielding high throughput."),
        ("INTERMEDIATE", "What is a driver's probe function?",
         ["a routine that checks whether the device is present and initializes it", "a routine that deletes the driver", "a routine that compiles the kernel", "a routine that prints logs"], "A",
         "The probe function verifies a device exists at a given address and sets up the driver for it."),
        ("INTERMEDIATE", "Why might a driver register an interrupt handler?",
         ["to be notified asynchronously when the device completes an operation", "to make the device faster", "to log all reads", "to disable the device"], "B",
         "Registering an interrupt handler lets the kernel call the driver when the device signals completion."),
        ("INTERMEDIATE", "What is the purpose of the open method in a character driver?",
         ["to set up per-open state when a user opens the device file", "to start the computer", "to load the kernel", "to create a new device"], "C",
         "The driver's open callback runs when an application opens the device node, allowing it to initialize state."),
        ("INTERMEDIATE", "What typically happens when a driver performs a read the user did not expect?",
         ["the driver returns an error such as EINVAL or EFAULT", "the kernel crashes", "the device explodes", "nothing, the call is ignored"], "D",
         "A well-behaved driver validates requests and returns an appropriate error code when a request is invalid."),
        ("ADVANCED", "Why is it dangerous for a driver to trust pointers passed from user space?",
         ["it must validate them with copy_from_user and access_ok to avoid security holes", "user pointers are always valid", "it can ignore them", "the kernel validates them automatically"], "A",
         "User-space pointers may be invalid or malicious, so drivers must copy data through safe kernel APIs to avoid exploitation."),
        ("ADVANCED", "What is a race condition in a device driver?",
         ["concurrent access to shared driver state without locking, producing incorrect behavior", "a fast device", "a slow device", "a driver with no bugs"], "B",
         "Without proper locking, concurrent operations can interleave and corrupt driver state, causing bugs."),
        ("ADVANCED", "What is the purpose of a workqueue or tasklet in a driver?",
         ["to defer work that cannot be done in an interrupt context to a safer execution context", "to speed up the disk", "to replace the scheduler", "to encrypt data"], "C",
         "Deferred work mechanisms move non-urgent processing out of interrupt context where sleeping and most APIs are forbidden."),
        ("ADVANCED", "Why should a driver use a completion mechanism rather than a busy-wait loop?",
         ["it lets the waiting task sleep and the CPU do useful work until the device signals completion", "it makes the code shorter", "it avoids using memory", "it is required by the compiler"], "D",
         "Completions put the waiting thread to sleep, so CPU cycles are not wasted polling for device completion."),
        ("ADVANCED", "What is a common cause of driver-initiated system crashes?",
         ["dereferencing NULL or invalid pointers, or corrupting kernel memory", "using too much RAM", "printing logs", "opening the device"], "A",
         "Drivers run in kernel space, so invalid pointer dereferences corrupt the kernel and cause a panic."),
        ("ADVANCED", "Why might a driver need to map a device's memory into the kernel address space?",
         ["to access memory-mapped device registers through normal pointers", "to make the device invisible", "to increase file size", "to speed up the network"], "B",
         "Mapping device memory lets the driver read and write device registers with ordinary load and store instructions."),
        ("ADVANCED", "What is the typical consequence of a driver calling a sleeping function from an interrupt handler?",
         ["undefined behavior and a likely kernel crash, since interrupt context cannot sleep", "the function executes normally", "the device resets", "the interrupt is ignored"], "C",
         "Interrupt context cannot block or sleep, so calling a sleeping API there corrupts the kernel and usually crashes it."),
        ("ADVANCED", "What is the purpose of a character device's llseek method?",
         ["to change the file position used by subsequent reads and writes", "to open the device", "to release the device", "to poll the device"], "D",
         "The llseek method moves the file offset within the device so applications can access different positions."),
        ("ADVANCED", "What does it mean for a driver to be reentrant?",
         ["it can safely be called by multiple processes or interrupt contexts at the same time", "it runs only once", "it cannot be loaded", "it ignores interrupts"], "A",
         "A reentrant driver can have multiple active invocations, so it must protect shared state with appropriate locking."),
        ("ADVANCED", "Why do kernel drivers prefer the kernel's allocation APIs over user-space style allocation?",
         ["they provide kernel-appropriate flags like GFP_KERNEL and interrupt-safe variants", "they are faster", "they never fail", "they use less memory"], "B",
         "Kernel allocation functions accept flags controlling behavior such as whether the caller may sleep, matching the execution context."),
    ],
    95: [
        ("BEGINNER", "What is an assembler?",
         ["a program that translates assembly language into machine code", "a compiler for high-level languages", "a linker", "a debugger"], "A",
         "An assembler converts human-readable assembly language instructions into binary machine code."),
        ("BEGINNER", "What is a compiler?",
         ["a program that translates a high-level language into machine code or an intermediate representation", "a program that runs assembly", "a type of processor", "a memory allocator"], "B",
         "A compiler transforms a high-level source language into a lower-level form such as machine code."),
        ("BEGINNER", "What is an assembly language instruction such as MOV or ADD called in relation to the CPU?",
         ["a mnemonic", "a constant", "a variable", "a label"], "C",
         "Mnemonics are the short symbolic names used in assembly language for machine instructions."),
        ("BEGINNER", "What does a linker do?",
         ["it combines object files and libraries into a final executable", "it translates source into assembly", "it runs the program", "it tests the program"], "D",
         "The linker resolves references between object files and libraries, producing the final executable."),
        ("BEGINNER", "What is a lexer or scanner in a compiler?",
         ["the stage that breaks source text into tokens", "the stage that optimizes code", "the stage that runs the program", "the stage that loads libraries"], "A",
         "The lexical analyzer reads the source characters and groups them into meaningful tokens."),
        ("BEGINNER", "What is a parser in a compiler?",
         ["the stage that builds a syntax tree from the token stream", "the stage that prints errors", "the stage that links objects", "the stage that executes code"], "B",
         "The parser consumes the tokens and constructs a parse tree according to the grammar of the language."),
        ("BEGINNER", "What is a symbol table in an assembler or compiler?",
         ["a structure recording identifiers, labels and their attributes", "a table of interrupts", "a memory allocation table", "a disk layout"], "C",
         "A symbol table stores information about every identifier and label, such as its type and address."),
        ("BEGINNER", "What does the lex phase of a classic two-pass assembler do?",
         ["it assigns addresses to labels and expands instructions", "it executes the program", "it loads the program", "it debugs the program"], "D",
         "The first pass scans the source, computes the address of each label and fills in the symbol table."),
        ("BEGINNER", "What is an opcode?",
         ["The part of a machine instruction that specifies the operation to be performed", "A high-level keyword", "A data type", "A linker option"], "A",
         "The opcode is the field of a machine instruction that tells the CPU which operation, such as add or load, to execute."),
        ("BEGINNER", "Which phase of a compiler checks that variables are declared before use?",
         ["semantic analysis", "lexing", "linking", "execution"], "B",
         "Semantic analysis verifies that expressions and uses of identifiers are meaningful and type-correct."),
        ("INTERMEDIATE", "Why does a classic assembler need two passes over the source?",
         ["labels can be used before they are defined, so addresses must be computed in a first pass", "to make the code faster", "to check spelling", "to save memory"], "C",
         "Since a label may be referenced before its definition, the first pass computes addresses and the second pass generates code."),
        ("INTERMEDIATE", "What is a relocation entry in an object file?",
         ["information about addresses that must be adjusted when the file is linked at a different base address", "a symbol table entry", "an error message", "a debug note"], "D",
         "Relocations record where a link-time address fixup is required so the final executable can be placed in memory correctly."),
        ("INTERMEDIATE", "What is the difference between compilation and interpretation?",
         ["compilation translates the whole program ahead of time, while interpretation executes source statement by statement", "compilation runs faster always", "interpretation never errors", "there is no difference"], "A",
         "A compiler translates the full program into a native or intermediate form before execution, whereas an interpreter executes source directly."),
        ("INTERMEDIATE", "What is the purpose of intermediate code generation in a compiler?",
         ["to provide a language- and machine-independent representation that eases optimization and retargeting", "to make the source unreadable", "to run the program", "to delete temporary files"], "B",
         "A common intermediate representation lets optimizations be shared and lets the same front end target many back ends."),
        ("INTERMEDIATE", "Which statement about labels in assembly is true?",
         ["a label is a symbolic name for an address, and forward references require a two-pass approach", "labels cannot be referenced", "labels are machine instructions", "labels hold data"], "C",
         "Labels name addresses, and because they may be referenced before definition, a two-pass process resolves them."),
        ("INTERMEDIATE", "What does the .text section of an object file contain?",
         ["the executable machine code", "initialized data", "the symbol table", "the header"], "D",
         "The .text section holds the program's executable instructions."),
        ("INTERMEDIATE", "What is the main job of the code generator phase?",
         ["to translate the intermediate representation into target machine instructions", "to tokenize the source", "to link libraries", "to test the program"], "A",
         "The code generator maps the intermediate representation to actual instructions of the target processor."),
        ("INTERMEDIATE", "Why do assemblers convert labels into numeric addresses?",
         ["the CPU can only execute numeric addresses and opcodes", "labels are easier for the CPU", "the CPU ignores labels", "labels are machine code"], "B",
         "Machine instructions require numeric operands, so labels must be resolved to concrete addresses."),
        ("INTERMEDIATE", "What is a macro in assembly language?",
         ["a named block of instructions that is expanded at each point of use during assembly", "a system call", "a data type", "a memory address"], "C",
         "A macro is expanded textually at each invocation, generating the same sequence of instructions each time."),
        ("INTERMEDIATE", "What happens during the linking phase when a symbol is undefined?",
         ["the linker reports an error and cannot produce the executable", "the linker creates it", "the program runs anyway", "the symbol is ignored"], "D",
         "If a referenced symbol has no definition, the linker fails with an undefined reference error."),
        ("ADVANCED", "What is the purpose of the register allocation phase in a compiler?",
         ["to map the many temporary values of a program onto the limited number of CPU registers", "to delete registers", "to slow the program", "to add new instructions"], "A",
         "Register allocation decides which values live in registers and which must be spilled to memory, greatly affecting speed."),
        ("ADVANCED", "What does an optimizing compiler do with a loop whose result is unused?",
         ["it may eliminate the loop entirely as dead code", "it always keeps it", "it doubles it", "it converts it to a function"], "B",
         "Dead code elimination removes computations whose results are never used, so the loop may vanish."),
        ("ADVANCED", "Why might a compiler reorder instructions that do not appear to be related?",
         ["to increase instruction-level parallelism and hide memory latency", "to confuse readers", "to reduce file size", "to break the program"], "C",
         "Instruction scheduling reorders independent operations to overlap latency and improve pipeline utilization."),
        ("ADVANCED", "What is an assembler directive?",
         ["an instruction to the assembler itself, such as reserving data or setting an origin, not executed by the CPU", "a CPU instruction", "a system call", "an interrupt"], "D",
         "Directives tell the assembler how to build output, such as reserving storage, without producing executable machine code."),
        ("ADVANCED", "What is the risk of relying on an uninitialized local variable in compiled code?",
         ["it holds an unpredictable value, making behavior undefined", "it always holds zero", "it holds the stack base", "it cannot be read"], "A",
         "Reading an uninitialized local is undefined, since it contains whatever garbage was on the stack."),
        ("ADVANCED", "How does a just-in-time (JIT) compiler differ from a traditional compiler?",
         ["it compiles code at runtime rather than ahead of execution, enabling profile-based optimization", "it runs slower", "it never optimizes", "it produces only assembly"], "B",
         "A JIT compiles methods when they are about to run, allowing it to optimize based on actual runtime behavior."),
        ("ADVANCED", "What does the -O2 flag typically tell a C compiler to do?",
         ["apply a standard set of optimizations that improve speed without breaking semantics", "disable all checks", "add debugging symbols only", "compile without a linker"], "C",
         "The -O2 level enables a well-tested optimization suite that speeds up the generated code."),
        ("ADVANCED", "Why is peephole optimization valuable?",
         ["it replaces short sequences of generated code with faster equivalents after code generation", "it rewrites the parser", "it speeds up the lexer", "it removes the linker"], "D",
         "Peephole optimization inspects small windows of generated instructions and substitutes better ones, improving efficiency cheaply."),
        ("ADVANCED", "What is the danger of signed integer overflow being treated as an optimization opportunity?",
         ["compilers may assume overflow never happens and transform code in ways that surprise developers", "the program always works", "overflow is always caught", "the CPU handles it perfectly"], "A",
         "Because overflow is undefined, compilers can assume it does not occur and may remove or alter code that relies on wrapping behavior."),
        ("ADVANCED", "What is a cross-compiler?",
         ["a compiler that runs on one platform but produces code for a different target platform", "a compiler that runs only on Windows", "a compiler with no optimizer", "a compiler that interprets source"], "B",
         "A cross-compiler builds binaries for a target machine that differs from the machine the compiler runs on."),
    ],
}
