# -*- coding: utf-8 -*-
"""
Question bank for subject 33: CLD103 - DevOps & CI/CD.
Category: Cloud, Cybersecurity & DevOps.

Topics:
  161: DevOps Principles & CI/CD
  162: Git & Version Control
  163: Docker & Containers
  164: Kubernetes
  165: Monitoring & Logging

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    161: [
        ("BEGINNER", "What does the acronym CI stand for in DevOps?",
         ["Continuous Integration", "Central Information", "Code Interface", "Continuous Inference"], "A",
         "CI refers to Continuous Integration, the practice of automatically merging and testing code changes frequently."),
        ("BEGINNER", "What does the acronym CD stand for in the CI/CD pipeline?",
         ["Continuous Deployment", "Code Delivery", "Central Deployment", "Continuous Debugging"], "B",
         "CD stands for Continuous Deployment (or Continuous Delivery), the automated release of validated code."),
        ("BEGINNER", "What is the primary goal of a DevOps culture?",
         ["reducing collaboration between teams", "breaking silos between development and operations teams", "eliminating all testing", "removing version control"], "C",
         "DevOps aims to break down silos and promote collaboration between development and operations teams."),
        ("BEGINNER", "What is the main benefit of automated testing in a CI/CD pipeline?",
         ["It catches defects early before they reach production", "It removes the need for version control", "It slows down the build process", "It replaces the developer's work entirely"], "A",
         "Automated testing runs every time code changes, so defects are found quickly and inexpensively before a release."),
        ("BEGINNER", "What is the main purpose of a version control system?",
         ["tracking changes to files over time", "compiling source code", "deploying applications", "writing documentation"], "A",
         "A version control system records changes to files, allowing history tracking and collaboration."),
        ("BEGINNER", "What does the term pipeline refer to in DevOps?",
         ["the sequence of automated steps from code commit to deployment", "a network cable", "a database schema", "a chat channel"], "B",
         "A pipeline is the automated sequence of stages such as build, test and deploy that code passes through."),
        ("BEGINNER", "Which practice involves automatically building and testing every change pushed to a shared repository?",
         ["manual deployment", "continuous integration", "code review only", "scheduled maintenance"], "C",
         "Continuous integration automatically builds and tests each change merged into the shared repository."),
        ("BEGINNER", "Which environment is typically used for running automated integration tests?",
         ["staging environment", "production environment", "a test or staging environment isolated from production", "the developer laptop only"], "D",
         "Integration tests run in dedicated test or staging environments that mirror production but are isolated from it."),
        ("BEGINNER", "What is infrastructure as code (IaC)?",
         ["writing hardware specifications", "managing infrastructure through machine-readable definition files", "physically installing servers", "using a spreadsheet to track servers"], "A",
         "Infrastructure as code provisions and manages infrastructure through declarative, version-controlled definition files."),
        ("BEGINNER", "Which of the following is a core DevOps principle?",
         ["automation of repetitive tasks", "manual error-prone deployments", "avoiding monitoring", "discouraging feedback"], "B",
         "Automating repetitive tasks is a core DevOps principle that improves speed, consistency and reliability."),
        ("INTERMEDIATE", "A developer pushes a change to the main branch. In a proper CI setup, what should happen automatically?",
         ["the code is merged into production instantly", "the change triggers an automated build and test run", "the change is ignored until the next release", "the developer must manually compile it"], "A",
         "In CI, every push to the shared branch automatically triggers a build and test run to catch problems early."),
        ("INTERMEDIATE", "Which stage in a typical CI/CD pipeline catches coding mistakes before deployment?",
         ["automated testing", "user acceptance testing only", "manual release notes", "database backup"], "B",
         "Automated tests run early in the pipeline to detect defects before the code moves toward deployment."),
        ("INTERMEDIATE", "What is the main difference between continuous delivery and continuous deployment?",
         ["deployment to production is fully automated in continuous deployment", "continuous delivery removes all tests", "continuous deployment uses no pipeline", "they are exactly the same thing"], "C",
         "Continuous delivery stops at a deployable artifact awaiting a manual release, while continuous deployment pushes every change to production automatically."),
        ("INTERMEDIATE", "A build fails in the pipeline. What is the correct response under a DevOps philosophy?",
         ["the team stops committing to the branch", "the team fixes the failing build as a priority", "the failure is ignored for a week", "the test is deleted from the suite"], "D",
         "Fixing the failing build as a priority keeps the main branch green and prevents cascading integration problems."),
        ("INTERMEDIATE", "Which of the following best describes a blue-green deployment?",
         ["two identical environments, one active and one idle, enabling instant rollback", "painting the servers blue", "deploying only at night", "a single environment with no backup"], "A",
         "Blue-green deployment runs two identical environments and switches traffic between them for zero-downtime rollback."),
        ("INTERMEDIATE", "What is the purpose of a rollback strategy in a deployment pipeline?",
         ["to revert to the previous known-good version if a release fails", "to permanently erase old versions", "to speed up the build", "to delete the logs"], "B",
         "A rollback strategy lets the team quickly restore the previous stable version when a release introduces problems."),
        ("INTERMEDIATE", "Why is it important to keep the CI build fast?",
         ["slow builds discourage frequent integration and delay feedback", "fast builds consume more electricity", "fast builds skip testing", "slow builds are more reliable"], "C",
         "A fast build provides quick feedback, encouraging developers to integrate small changes frequently."),
        ("INTERMEDIATE", "Which artifact is typically produced by a build stage in CI?",
         ["a compiled, versioned artifact ready for release", "a list of users", "a backup tape", "a marketing plan"], "D",
         "The build stage produces a compiled, versioned artifact that downstream stages can test and deploy."),
        ("INTERMEDIATE", "What is a feature flag used for in continuous delivery?",
         ["toggling features on or off at runtime without redeploying", "flagging files as read-only", "highlighting bugs in the IDE", "naming release branches"], "A",
         "Feature flags allow features to be enabled or disabled at runtime, enabling safe progressive rollouts."),
        ("INTERMEDIATE", "Which metric best indicates how quickly a change reaches production?",
         ["deployment frequency", "the number of coffee breaks", "the size of the codebase", "the age of the servers"], "B",
         "Deployment frequency measures how often changes are released, a key DevOps delivery metric."),
        ("ADVANCED", "A team wants zero-downtime releases for a web service. Which deployment strategy best supports this while allowing instant rollback?",
         ["a rolling deployment with canary analysis", "replacing the production server without backups", "deploying directly over the live server", "shutting down the service during release"], "A",
         "A rolling deployment updates instances gradually, and canary analysis lets traffic shift only while metrics look healthy."),
        ("ADVANCED", "Which property makes a CI/CD pipeline most resilient to a failing stage?",
         ["each stage is idempotent and can be re-run safely", "stages depend on manual steps", "the pipeline deletes artifacts on failure", "stages never produce logs"], "B",
         "Idempotent stages that can be safely re-run let teams recover from failures without manual cleanup or rework."),
        ("ADVANCED", "A developer commits frequently but the team only integrates with the main branch every month. What problem does this cause?",
         ["integration conflicts and late discovery of defects", "faster deployments", "cleaner commit history", "fewer build failures"], "C",
         "Rare integration causes merge conflicts and delays discovery of integration defects, violating CI best practice."),
        ("ADVANCED", "In a shift-left testing strategy, what is the emphasis?",
         ["catching defects as early as possible in the development lifecycle", "testing only in production", "postponing all tests", "relying solely on manual QA"], "D",
         "Shift-left testing moves testing earlier in the lifecycle so defects are found and fixed cheaply."),
        ("ADVANCED", "Which approach describes a canary release?",
         ["rolling out a new version to a small subset of users before full rollout", "deploying the new version to everyone at once", "keeping two permanent versions forever", "releasing only the documentation"], "A",
         "A canary release routes a small percentage of traffic to the new version first and expands it as confidence grows."),
        ("ADVANCED", "Why is treating servers as cattle rather than pets important in DevOps?",
         ["servers should be disposable and easily replaced, not hand-configured and irreplaceable", "cattle are more reliable than servers", "it reduces the need for automation", "it makes servers slower"], "B",
         "Treating servers as cattle means they are reproducible and disposable, so any instance can be replaced automatically."),
        ("ADVANCED", "Which SRE-style SLO consideration is most appropriate for a mission-critical API?",
         ["an error budget based on a measurable availability target such as 99.9 percent", "a guarantee of zero downtime with no measurement", "measuring only the uptime of the marketing site", "tracking only developer happiness"], "C",
         "An SLO defines a quantifiable availability target, and the error budget guides how much unreliability is acceptable."),
        ("ADVANCED", "A security check in the CI/CD pipeline reports a vulnerable dependency. What is the correct action?",
         ["fail the build and require the dependency to be patched before release", "ship it and fix it later", "delete the dependency check", "ignore the warning"], "D",
         "A security gate should fail the build so vulnerable dependencies are patched before code reaches production."),
        ("ADVANCED", "Which workflow best supports trunk-based development?",
         ["short-lived feature branches merged into main frequently", "long-lived branches that never merge", "one giant release branch per year", "no branch merging at all"], "A",
         "Trunk-based development keeps feature branches short-lived and merges them to main frequently to reduce conflict."),
        ("ADVANCED", "Why should deployment credentials be stored in a secrets manager rather than in the repository?",
         ["committing secrets exposes them to anyone with repository access and increases breach risk", "secrets are easier to type this way", "repositories cannot store files", "it makes builds slower"], "B",
         "Storing credentials in a secrets manager keeps them out of version control and restricts access at runtime."),
    ],
    162: [
        ("BEGINNER", "Which command creates a new Git repository in the current directory?",
         ["git init", "git start", "git new", "git create"], "A",
         "git init initializes a new Git repository in the current directory."),
        ("BEGINNER", "Which command stages changes to be committed?",
         ["git commit", "git add", "git push", "git status"], "B",
         "git add stages changes, moving them into the index so they can be committed."),
        ("BEGINNER", "Which command records staged changes into the repository history?",
         ["git add", "git push", "git commit", "git log"], "C",
         "git commit captures the staged changes with a message, creating a permanent entry in history."),
        ("BEGINNER", "Which command uploads local commits to a remote repository?",
         ["git pull", "git fetch", "git push", "git clone"], "D",
         "git push transfers local commits to the configured remote repository."),
        ("BEGINNER", "What is the default name of the first branch in Git?",
         ["master", "dev", "test", "feature"], "A",
         "Git historically names the default branch master, though main is now also common."),
        ("BEGINNER", "Which command shows the working directory and staged changes status?",
         ["git status", "git diff", "git branch", "git stash"], "B",
         "git status displays which files are modified, staged or untracked."),
        ("BEGINNER", "What does git clone do?",
         ["copies a repository into a new local directory", "deletes a repository", "merges two branches", "creates a commit"], "C",
         "git clone downloads a full copy of a repository, including its history, into a new directory."),
        ("BEGINNER", "Which command fetches and merges changes from the remote into the current branch?",
         ["git pull", "git push", "git add", "git commit"], "D",
         "git pull fetches remote changes and merges them into the current branch."),
        ("BEGINNER", "How do you view the commit history in Git?",
         ["git log", "git add", "git init", "git remote"], "A",
         "git log lists the commit history in reverse chronological order."),
        ("BEGINNER", "What is a commit in Git?",
         ["a snapshot of the project at a point in time", "a deleted file", "a network request", "a configuration file"], "B",
         "A commit is a snapshot of the tracked files, saved with metadata such as the author and message."),
        ("INTERMEDIATE", "After git add app.py, which command records the staged change with the message adding login?",
         ["git commit -m 'adding login'", "git push -m 'adding login'", "git save -m 'adding login'", "git branch -m 'adding login'"], "A",
         "git commit -m records the staged change with the given message in one command."),
        ("INTERMEDIATE", "What is the main difference between git merge and git rebase?",
         ["merge preserves a merge commit; rebase rewrites history by replaying commits", "merge deletes the branch", "rebase cannot be undone", "merge only works offline"], "B",
         "git merge creates a merge commit joining histories, while git rebase replays commits onto another base."),
        ("INTERMEDIATE", "You started editing config.py, but want to discard the changes. Which command restores it?",
         ["git checkout -- config.py", "git commit config.py", "git push config.py", "git add config.py"], "C",
         "git checkout -- restores the working file to its last committed state, discarding uncommitted edits."),
        ("INTERMEDIATE", "Which command creates a new branch named feature and switches to it immediately?",
         ["git checkout -b feature", "git branch -d feature", "git commit -b feature", "git merge feature"], "D",
         "git checkout -b both creates the branch and checks it out in a single step."),
        ("INTERMEDIATE", "Two developers both modify the same line and then try to merge. What is the result?",
         ["a merge conflict", "the merge always succeeds", "the file is deleted", "Git refuses to push forever"], "A",
         "Conflicting changes to the same line produce a merge conflict that must be resolved manually."),
        ("INTERMEDIATE", "What is the purpose of git stash?",
         ["saving uncommitted changes temporarily so you can switch work", "deleting the repository", "creating a backup server", "listing remote branches"], "B",
         "git stash saves uncommitted changes aside and restores a clean working directory for another task."),
        ("INTERMEDIATE", "Which command shows the differences between the working directory and the last commit?",
         ["git diff", "git status", "git add", "git log"], "C",
         "git diff without arguments shows unstaged changes between the working tree and the index."),
        ("INTERMEDIATE", "What does git revert HEAD do?",
         ["creates a new commit that undoes the last commit's changes", "deletes the last commit from history", "rebases the branch", "pushes the branch"], "D",
         "git revert creates a new commit that reverses the changes of the specified commit, preserving history."),
        ("INTERMEDIATE", "Which command permanently removes a branch called old-feature?",
         ["git branch -d old-feature", "git stash old-feature", "git log old-feature", "git fetch old-feature"], "A",
         "git branch -d deletes a branch once it has been merged, while -D forces deletion."),
        ("INTERMEDIATE", "Which command downloads remote commits into a local tracking branch without merging?",
         ["git fetch", "git pull", "git push", "git commit"], "B",
         "git fetch downloads remote refs and objects but does not merge them into the working branch."),
        ("ADVANCED", "A hotfix branch must be based on a released commit that is several commits behind main. Which approach cleanly brings it up to date?",
         ["git checkout hotfix; git rebase main", "git push hotfix --force", "git stash and drop the branch", "git revert main"], "A",
         "Rebasing the hotfix branch onto main replays its commits on top of the latest main for a linear history."),
        ("ADVANCED", "A developer pushed a commit containing a secret. What is the safest way to remove it from history?",
         ["rotate the secret and rewrite history with git filter-repo or filter-branch", "delete the file locally and commit", "rename the commit message", "leave the secret in the history"], "B",
         "The exposed secret must be revoked, and history should be rewritten to purge it from all commits."),
        ("ADVANCED", "Which situation makes a force push to a shared branch most dangerous?",
         ["it overwrites commits that other developers may already have", "it is always harmless", "it deletes local files", "it slows the network"], "C",
         "Force pushing replaces remote commits, discarding work others may have based on those commits."),
        ("ADVANCED", "What is the recommended approach when resolving a merge conflict in a shared feature branch?",
         ["commit the resolved files, then continue and merge", "delete the conflicting files", "force push before merging", "ignore the conflict and push"], "D",
         "The correct flow is to edit the conflicting files, mark them resolved, commit, and then complete the merge."),
        ("ADVANCED", "Which Git feature allows several commits on a feature branch to be squashed into one before merging?",
         ["git rebase -i", "git status", "git stash", "git clone"], "A",
         "git rebase -i (interactive) can squash, reorder and edit commits before they are merged."),
        ("ADVANCED", "In which scenario is cherry-picking a commit appropriate?",
         ["applying a specific commit's change to a different branch", "deleting all branches", "renaming a repository", "compressing the working tree"], "B",
         "git cherry-pick applies a single commit's change to the current branch, useful when the full merge is not wanted."),
        ("ADVANCED", "A pull request shows merge conflicts on the target branch. What is the correct first step?",
         ["merge or rebase the latest target branch into the feature branch", "force push the feature branch", "delete the target branch", "ignore the conflicts"], "C",
         "Bringing the feature branch up to date with the target branch resolves most conflicts before review."),
        ("ADVANCED", "Which practice best protects the main branch in a team repository?",
         ["requiring pull request reviews and passing CI before merge", "allowing direct pushes without review", "merging untested code", "disabling branch protection"], "D",
         "Branch protection rules that require reviews and green CI prevent broken or unreviewed code from reaching main."),
        ("ADVANCED", "Why is amending a commit that has already been pushed to a shared branch problematic?",
         ["rewriting the pushed commit changes history for all collaborators", "it deletes the repository", "it slows down cloning", "it is perfectly safe always"], "A",
         "Amending rewrites the commit, so anyone who already pulled the old version has diverged history."),
        ("ADVANCED", "To trace which commit introduced a regression, which Git command is most useful?",
         ["git bisect", "git add", "git remote", "git init"], "B",
         "git bisect performs a binary search over history to find the commit that introduced a bug."),
    ],
    163: [
        ("BEGINNER", "What is a Docker container?",
         ["a lightweight, isolated runtime environment for an application", "a physical server", "a database index", "a network switch"], "A",
         "A Docker container packages an application with its dependencies into a lightweight isolated runtime."),
        ("BEGINNER", "What is the main purpose of containerization?",
         ["packaging an application with its dependencies so it runs the same anywhere", "speeding up the CPU", "storing large databases", "replacing the operating system"], "A",
         "Containerization bundles an application and its dependencies so it behaves identically across different environments."),
        ("BEGINNER", "Which command builds a Docker image from a Dockerfile?",
         ["docker build", "docker run", "docker push", "docker pull"], "C",
         "docker build reads a Dockerfile and produces an image from its instructions."),
        ("BEGINNER", "Which command starts a container from an image?",
         ["docker run", "docker build", "docker save", "docker inspect"], "D",
         "docker run starts a container from an image, executing its default command."),
        ("BEGINNER", "What is the default registry where Docker images are pulled from?",
         ["Docker Hub", "Maven Central", "PyPI", "npm Registry"], "A",
         "Docker Hub is Docker's default public image registry for pulling and pushing images."),
        ("BEGINNER", "What is a Dockerfile?",
         ["a text file with instructions to build a Docker image", "a log of container starts", "a configuration for the host OS", "a list of running containers"], "B",
         "A Dockerfile is a declarative script whose instructions build a Docker image layer by layer."),
        ("BEGINNER", "Which command lists running containers?",
         ["docker ps", "docker ls", "docker show", "docker list"], "C",
         "docker ps lists the containers that are currently running."),
        ("BEGINNER", "Which command removes a container?",
         ["docker rm", "docker kill", "docker rmi", "docker stop"], "D",
         "docker rm removes a stopped container, while docker rmi is used to remove images."),
        ("BEGINNER", "What is Docker Compose used for?",
         ["defining and running multi-container applications", "compiling source code", "backing up the host", "monitoring the network"], "A",
         "Docker Compose defines multi-container applications in a YAML file and manages them together."),
        ("BEGINNER", "What does the EXPOSE instruction in a Dockerfile do?",
         ["documents the port the container listens on", "installs software", "runs a command", "copies files"], "B",
         "EXPOSE declares which ports the container's application listens on for documentation."),
        ("INTERMEDIATE", "In a Dockerfile, which instruction copies files from the build context into the image?",
         ["COPY", "RUN", "CMD", "WORKDIR"], "A",
         "COPY copies files or directories from the build context into the image filesystem."),
        ("INTERMEDIATE", "Which Dockerfile instruction runs a command at image build time, such as installing packages?",
         ["RUN", "CMD", "ENTRYPOINT", "FROM"], "B",
         "RUN executes commands while building the image, committing the result as a new layer."),
        ("INTERMEDIATE", "Which instruction defines the command executed when a container is started?",
         ["CMD", "ADD", "EXPOSE", "COPY"], "C",
         "CMD specifies the default command executed when a container starts from the image."),
        ("INTERMEDIATE", "What is the difference between CMD and ENTRYPOINT in a Dockerfile?",
         ["CMD sets the default command, while ENTRYPOINT defines the fixed base command that runs", "they are identical", "ENTRYPOINT is only for volumes", "CMD cannot be overridden"], "D",
         "CMD provides the default command that can be overridden, while ENTRYPOINT fixes the base command that always runs."),
        ("INTERMEDIATE", "Which command publishes a container's port to the host machine?",
         ["docker run -p 8080:80 image", "docker run -d image", "docker exec -it image", "docker build image"], "A",
         "docker run -p maps a host port to the container port, making the service reachable."),
        ("INTERMEDIATE", "What happens to a container's filesystem when the container is removed?",
         ["changes are lost unless a volume or image layer preserves them", "the data is saved automatically", "the host disk is wiped", "the container restarts"], "B",
         "Container writes are ephemeral, so removed containers lose data unless stored in a volume or committed to an image."),
        ("INTERMEDIATE", "Which flag keeps a container running in the background?",
         ["docker run -d", "docker run -t", "docker run -p", "docker run -e"], "C",
         "The -d flag detaches the container, letting it run in the background."),
        ("INTERMEDIATE", "Which command enters a running container's shell?",
         ["docker exec -it container bash", "docker start container", "docker ps container", "docker pull container"], "D",
         "docker exec -it runs an interactive shell inside a running container."),
        ("INTERMEDIATE", "Which command uploads a local image to a registry?",
         ["docker push", "docker pull", "docker save", "docker commit"], "A",
         "docker push uploads a tagged image to a configured registry such as Docker Hub."),
        ("INTERMEDIATE", "Which Dockerfile instruction changes the working directory for subsequent commands?",
         ["WORKDIR", "RUN", "ENV", "LABEL"], "B",
         "WORKDIR sets the current directory for subsequent RUN, CMD and COPY instructions."),
        ("ADVANCED", "A production image must be as small as possible. Which Dockerfile strategy best achieves this?",
         ["use a multi-stage build that copies only the compiled artifact into a minimal runtime image", "install everything in one layer", "use the base OS with all build tools", "store source code in the image"], "A",
         "Multi-stage builds compile in a builder image and copy only the needed artifact into a slim final image."),
        ("ADVANCED", "Why is running containers as root a security risk?",
         ["a compromised container gains full host privileges", "root users cannot access the network", "root containers cannot write logs", "it slows the container"], "B",
         "Root inside a container can lead to host compromise, so production images should run with a non-root user."),
        ("ADVANCED", "Which practice best preserves database state across container restarts?",
         ["storing data in a named volume", "writing data to the container filesystem", "deleting the volume on restart", "storing data in the image"], "C",
         "Named volumes persist independently of the container, so database data survives restarts and re-creation."),
        ("ADVANCED", "A team must keep secrets out of their image. Which approach is correct?",
         ["pass secrets via environment variables or mounted secret files at runtime", "hard-code them in the Dockerfile", "commit them in the image", "embed them in a config layer"], "D",
         "Providing secrets at runtime through environment variables or secret mounts keeps them out of the image layers."),
        ("ADVANCED", "Which scenario best justifies using a named volume?",
         ["persisting database data that must survive container recreation", "temporary caching only", "reading the source code", "storing build artifacts that are disposable"], "A",
         "Named volumes persist data independently of the container lifecycle, ideal for database state."),
        ("ADVANCED", "A multi-stage build compiles a Go binary. What does the final stage typically contain?",
         ["only the compiled binary and the minimal runtime needed", "the full toolchain and sources", "all build dependencies", "the entire base image"], "B",
         "The final stage includes only the runtime dependencies and the compiled binary, keeping the image small."),
        ("ADVANCED", "Why is it important to pin base image versions in a Dockerfile?",
         ["unpinned tags like latest can change and break builds unexpectedly", "pinned images are always smaller", "pinning reduces disk usage", "it improves the network speed"], "C",
         "Pinning an image digest or tag ensures reproducible builds by avoiding unexpected base image changes."),
        ("ADVANCED", "What is the main purpose of a container registry vulnerability scan?",
         ["detecting known vulnerabilities in base images and dependencies", "increasing the image size", "renaming containers", "optimizing the Dockerfile syntax"], "D",
         "Registry scans compare image layers against vulnerability databases to surface known CVEs before deployment."),
        ("ADVANCED", "Which architecture best describes container orchestration of microservices?",
         ["managing many containers across hosts with scheduling, scaling and networking", "running all services in one container", "deploying only on laptops", "using a single VM per service"], "A",
         "Orchestration platforms schedule, scale and network many containers across a cluster of hosts."),
        ("ADVANCED", "Why should you use .dockerignore in a Docker project?",
         ["to exclude unnecessary files from the build context, shrinking and securing the build", "to ignore container logs", "to disable Docker entirely", "to rename the image"], "B",
         "A .dockerignore excludes secrets, build artifacts and caches from the build context, reducing image bloat."),
    ],
    164: [
        ("BEGINNER", "What is the role of the control plane in a Kubernetes cluster?",
         ["it manages and coordinates the worker nodes and maintains the cluster's desired state", "it runs all the application workloads", "it stores container images", "it provides DNS for the internet"], "A",
         "The control plane makes scheduling and cluster-wide decisions and keeps the actual state aligned with the desired state."),
        ("BEGINNER", "What is a pod in Kubernetes?",
         ["the smallest deployable unit that wraps one or more containers", "a physical server", "a database table", "a container registry"], "B",
         "A pod is the smallest deployable unit in Kubernetes, wrapping one or more containers sharing resources."),
        ("BEGINNER", "What is a Kubernetes node?",
         ["a worker machine that runs pods", "a type of container", "a deployment manifest", "a secret"], "C",
         "A node is a worker machine in the cluster where pods are scheduled and run."),
        ("BEGINNER", "Which tool is the command-line interface for interacting with a Kubernetes cluster?",
         ["kubectl", "docker", "git", "npm"], "D",
         "kubectl is the standard command-line tool for talking to the Kubernetes API server."),
        ("BEGINNER", "What does a Kubernetes Deployment resource manage?",
         ["the desired state of stateless application replicas", "database backups", "user accounts", "network switches"], "A",
         "A Deployment declares a desired number of replicas and keeps the actual state in line with it."),
        ("BEGINNER", "What is a Kubernetes Service used for?",
         ["providing a stable network endpoint to a set of pods", "storing secrets", "scheduling batch jobs", "backing up the cluster"], "B",
         "A Service gives pods a stable virtual IP and DNS name that routes traffic to them."),
        ("BEGINNER", "What is a Kubernetes cluster?",
         ["a set of worker nodes plus a control plane", "a single container", "a Docker image", "a version control branch"], "C",
         "A cluster combines a control plane and worker nodes that together run containerized workloads."),
        ("BEGINNER", "Which command deploys a manifest to the cluster?",
         ["kubectl apply -f manifest.yaml", "kubectl delete -f manifest.yaml", "kubectl get pods", "kubectl describe node"], "D",
         "kubectl apply sends the resource defined in the manifest to the cluster."),
        ("BEGINNER", "Which command lists the pods running in the default namespace?",
         ["kubectl get pods", "kubectl run pods", "kubectl exec pods", "kubectl apply pods"], "A",
         "kubectl get pods lists the pods in the current namespace."),
        ("BEGINNER", "What does Kubernetes do when a pod crashes?",
         ["restarts or reschedules it to maintain the desired state", "deletes the whole cluster", "ignores the failure", "shuts down the node"], "B",
         "Kubernetes controllers detect crashed pods and restart or reschedule them to meet the desired state."),
        ("INTERMEDIATE", "A web app is served by 3 replicas behind a Service. What does the Service route traffic to?",
         ["all healthy pods matching its selector", "only the first pod created", "the control plane", "a random node"], "A",
         "A Service uses a label selector to route traffic to all healthy pods that match its selector."),
        ("INTERMEDIATE", "How does horizontal pod autoscaling (HPA) decide to add replicas?",
         ["by comparing observed metrics such as CPU utilization against a target", "by counting the number of users in the database", "by the time of day only", "by random selection"], "B",
         "The HPA scales replicas when observed resource usage, like CPU, exceeds a configured target."),
        ("INTERMEDIATE", "Which resource maps a container port to a stable cluster-wide address so the app is reachable?",
         ["a Service of type ClusterIP or LoadBalancer", "a ConfigMap", "a Pod", "a Secret"], "C",
         "Services expose pods at stable addresses such as ClusterIP within the cluster or LoadBalancer externally."),
        ("INTERMEDIATE", "What is the purpose of a liveness probe in Kubernetes?",
         ["detecting and restarting a container that is stuck or unhealthy", "scaling up replicas", "storing configuration", "scheduling batch jobs"], "D",
         "Liveness probes restart containers that stop responding so unhealthy pods are replaced automatically."),
        ("INTERMEDIATE", "What is the purpose of a readiness probe?",
         ["indicating whether a pod is ready to receive traffic", "checking the Kubernetes version", "deleting old replicas", "backing up logs"], "A",
         "Readiness probes tell Kubernetes whether a pod can accept traffic, preventing requests to unready pods."),
        ("INTERMEDIATE", "Which command scales a deployment named web to 5 replicas?",
         ["kubectl scale deployment web --replicas=5", "kubectl get deployment web", "kubectl exec web --replicas=5", "kubectl describe web --replicas=5"], "B",
         "kubectl scale changes the replica count of a deployment to the specified number."),
        ("INTERMEDIATE", "What is a ConfigMap used for in Kubernetes?",
         ["storing non-sensitive configuration data separate from containers", "storing encrypted passwords", "running cron jobs", "allocating IP addresses"], "C",
         "ConfigMaps hold non-confidential configuration that pods can consume as files or environment variables."),
        ("INTERMEDIATE", "What is a Secret resource used for?",
         ["storing sensitive data such as passwords and tokens", "storing public logs", "defining container images", "managing namespaces"], "D",
         "Secrets store sensitive values like passwords and tokens, which pods can consume securely."),
        ("INTERMEDIATE", "Which resource creates a stable DNS name for an external database service?",
         ["an ExternalName or Endpoints Service", "a Deployment", "a ReplicaSet", "a Namespace"], "A",
         "An ExternalName service maps a DNS name to an external service, or Endpoints can point at external IPs."),
        ("INTERMEDIATE", "What happens during a rolling update of a Deployment?",
         ["pods are replaced gradually so the app stays available", "all pods are terminated at once", "the cluster restarts", "the manifest is deleted"], "B",
         "A rolling update replaces old pods with new ones incrementally, maintaining availability."),
        ("ADVANCED", "Why might a pod be stuck in a Pending state?",
         ["the scheduler could not find a node with enough resources", "the pod is healthy", "the image was built locally", "the pod finished its work"], "A",
         "Pending means the pod has not been scheduled, often because no node has sufficient CPU, memory or storage."),
        ("ADVANCED", "What does the scheduler do in Kubernetes?",
         ["chooses which node each unscheduled pod should run on", "runs the container runtime", "stores image layers", "manages DNS records"], "B",
         "The scheduler places unscheduled pods onto nodes that satisfy their resource and affinity constraints."),
        ("ADVANCED", "A stateful application requires persistent storage and stable identity. Which workload is most appropriate?",
         ["a StatefulSet", "a Deployment", "a DaemonSet", "a ConfigMap"], "C",
         "StatefulSets give pods stable identity and persistent volumes, suited for databases and stateful services."),
        ("ADVANCED", "Which resource runs a pod on every node in the cluster, such as a logging agent?",
         ["a DaemonSet", "a Job", "a Service", "a ReplicaSet"], "D",
         "DaemonSets guarantee one pod runs on every (or selected) node, ideal for agents like log collectors."),
        ("ADVANCED", "What is the purpose of resource requests and limits in a pod spec?",
         ["they inform the scheduler about needs and cap the resources a container may use", "they name the containers", "they set the image tag", "they control the namespace"], "A",
         "Requests guide scheduling by declaring needs, while limits cap a container's maximum resource use."),
        ("ADVANCED", "Which Kubernetes feature is best for storing a database password consumed by a pod?",
         ["a Secret mounted as a volume or environment variable", "a ConfigMap", "a Service", "a NodePort"], "B",
         "Secrets store sensitive values and can be exposed to pods via volumes or environment variables."),
        ("ADVANCED", "How does a HorizontalPodAutoscaler interact with a Deployment?",
         ["it updates the Deployment's replica count based on metrics", "it replaces the Deployment with a pod", "it deletes old pods", "it changes the container image"], "C",
         "The HPA controller reads metrics and adjusts the Deployment replica count to meet the configured target."),
        ("ADVANCED", "An operator wants to run a one-off batch computation to completion. Which workload is correct?",
         ["a Job", "a StatefulSet", "a DaemonSet", "a Service"], "D",
         "Jobs run pods to completion for one-off batch work, unlike long-running workloads."),
        ("ADVANCED", "What is the purpose of pod anti-affinity rules?",
         ["spreading replicas across nodes to increase fault tolerance", "forcing all replicas onto one node", "attaching volumes", "hiding the pod IP"], "A",
         "Anti-affinity rules separate replicas across nodes so a node failure does not take down the whole service."),
        ("ADVANCED", "During a rollout, a new pod repeatedly fails readiness checks. What does Kubernetes do?",
         ["stops the rollout and keeps the old version running", "deletes the whole deployment", "ignores the failure", "restarts all nodes"], "B",
         "If new pods never become ready, the rolling update stalls, preserving the previous stable revision."),
    ],
    165: [
        ("BEGINNER", "What is the main purpose of application monitoring?",
         ["observing system health, performance and errors in real time", "editing configuration files", "compiling source code", "backing up the database"], "A",
         "Monitoring collects metrics, logs and traces to track the health and performance of systems."),
        ("BEGINNER", "What is a metric in monitoring?",
         ["a numeric measurement such as CPU usage or latency", "a text document", "a deployment script", "a container image"], "B",
         "Metrics are numeric measurements sampled over time, such as CPU utilization or request latency."),
        ("BEGINNER", "Which open-source tool is commonly used for collecting and querying metrics?",
         ["Prometheus", "Notepad", "Excel", "VLC Player"], "C",
         "Prometheus is a popular open-source monitoring and alerting tool for time-series metrics."),
        ("BEGINNER", "What is a log in the context of monitoring?",
         ["a timestamped record of an event or message from a system", "a network password", "a configuration file", "a CPU register"], "D",
         "Logs are timestamped records of events, errors and messages produced by applications and systems."),
        ("BEGINNER", "Which tool is widely used for centralized log aggregation and searching?",
         ["Elastic Stack (ELK)", "Photoshop", "Windows Notepad", "GIMP"], "A",
         "The Elastic Stack (Elasticsearch, Logstash, Kibana) is commonly used to aggregate and search logs."),
        ("BEGINNER", "What does an alert in a monitoring system do?",
         ["notifies operators when a threshold or condition is met", "restarts the monitoring server", "deletes old logs", "compiles the application"], "B",
         "Alerts notify engineers when monitored values cross configured thresholds or conditions."),
        ("BEGINNER", "What does the term uptime refer to in monitoring?",
         ["the percentage of time a service is operational and available", "the number of log entries", "the disk space used", "the number of containers"], "C",
         "Uptime measures the proportion of time a service remains available to its users."),
        ("BEGINNER", "Which metric typically indicates how fast a web server responds?",
         ["latency", "database size", "login count", "network subnet"], "D",
         "Latency measures the time a server takes to respond, directly reflecting responsiveness."),
        ("BEGINNER", "What is a dashboard in a monitoring tool?",
         ["a visual panel displaying key metrics and graphs", "a container registry", "a source file", "a backup schedule"], "A",
         "A dashboard presents live charts and panels so operators can observe metrics at a glance."),
        ("BEGINNER", "Which component in the Prometheus architecture periodically pulls metrics from targets?",
         ["the Prometheus server", "Kibana", "the Kubernetes scheduler", "Grafana only"], "B",
         "The Prometheus server scrapes (pulls) metrics from instrumented targets on a schedule."),
        ("INTERMEDIATE", "A service's error rate spikes to 15 percent. Which alert level best matches a severe outage?",
         ["a critical alert requiring immediate response", "an info message", "a debug log", "a silent ignore"], "A",
         "A critical alert fires when an outage-level condition, like a high error rate, needs immediate attention."),
        ("INTERMEDIATE", "In Prometheus, which query expression selects all HTTP requests with a status of 500?",
         ["http_requests_total{status='500'}", "SELECT FROM http", "count(status)", "status == 500"], "B",
         "PromQL label matchers like {status='500'} filter time series to those with that label value."),
        ("INTERMEDIATE", "What is the primary difference between logs and metrics?",
         ["logs are discrete events with detail, while metrics are numeric aggregates over time", "logs are always secret", "metrics are text documents", "there is no difference"], "C",
         "Logs capture individual events with rich context, while metrics are numeric measurements aggregated over time."),
        ("INTERMEDIATE", "Which tool is commonly paired with Prometheus to build dashboards and charts?",
         ["Grafana", "Excel", "Pandoc", "WinZip"], "D",
         "Grafana is the standard visualization layer paired with Prometheus to build dashboards."),
        ("INTERMEDIATE", "What does RED stand for in the RED monitoring method?",
         ["Rate, Errors, Duration", "Random, Error, Deploy", "Restart, Eject, Delete", "Request, Execute, Debug"], "A",
         "RED focuses on Rate, Errors and Duration for monitoring request-driven services."),
        ("INTERMEDIATE", "Which metric is the classic four golden signals of Google SRE?",
         ["latency, traffic, errors and saturation", "cpu, ram, disk and network", "uptime, users, costs and tickets", "builds, tests, commits and merges"], "B",
         "The four golden signals are latency, traffic, errors and saturation."),
        ("INTERMEDIATE", "What is a trace in distributed tracing?",
         ["the end-to-end path of a request across multiple services", "a type of log line", "a metric label", "a container name"], "C",
         "A trace follows a single request through every service it touches, showing timing at each step."),
        ("INTERMEDIATE", "What does a histogram metric in Prometheus record?",
         ["the distribution of observed values across predefined buckets", "only the maximum value", "the number of unique users", "the current log file size"], "D",
         "A histogram counts observations into predefined value buckets, capturing the distribution of a metric."),
        ("INTERMEDIATE", "Which monitoring approach is best for detecting that a service is fully down?",
         ["a black-box probe that checks external availability of the service", "reading the source code", "counting the pods manually", "viewing the README"], "A",
         "Black-box monitoring probes the service from the outside, detecting outages that internal metrics miss."),
        ("INTERMEDIATE", "What is the purpose of a monitoring retention policy?",
         ["controlling how long metrics and logs are stored", "increasing storage forever", "deleting the cluster", "slowing down queries"], "B",
         "Retention policies control storage duration, balancing data availability against disk cost."),
        ("ADVANCED", "A dashboard shows average latency is healthy, yet users report slow pages. Why might averages hide the problem?",
         ["averages mask outliers, such as slow tail latency for a small percentage of requests", "averages are always wrong", "the dashboard is broken", "users are mistaken"], "A",
         "Mean latency hides long tail outliers, so percentiles like p95 or p99 expose the real user experience."),
        ("ADVANCED", "Why should alerts be based on page-level or user-level signals rather than raw host metrics alone?",
         ["user-visible signals capture actual impact, while host metrics can miss application-level failures", "host metrics are useless", "alerts are always manual", "page-level data is never collected"], "B",
         "User-level signals reflect real impact, while a healthy host can still be serving errors or broken pages."),
        ("ADVANCED", "In Prometheus, what is the purpose of recording rules?",
         ["precomputing expensive queries and storing them as new series", "storing log files", "naming containers", "scheduling pods"], "C",
         "Recording rules evaluate complex PromQL queries periodically and store the results as new time series."),
        ("ADVANCED", "What is the main risk of alerting on raw CPU thresholds for a web service?",
         ["noisy false positives that do not reflect user-visible impact", "alerts always fire correctly", "the server shuts down", "metrics are not collected"], "D",
         "Raw CPU thresholds often alert on benign spikes while missing application-level failures users actually experience."),
        ("ADVANCED", "A service emits thousands of logs per second. Which practice is most appropriate for managing log volume?",
         ["using structured logging with levels and sampling or filtering at ingestion", "logging everything twice", "disabling all logs", "storing logs in memory only"], "A",
         "Structured logging with levels and ingestion filtering keeps log volume manageable while retaining useful detail."),
        ("ADVANCED", "Which approach best supports correlating a failing request across many microservices?",
         ["distributed tracing with a shared trace ID propagated through every service", "reading each service log independently", "comparing disk sizes", "restarting services"], "B",
         "A shared trace ID ties the request path together across services, enabling end-to-end correlation."),
        ("ADVANCED", "Why should a monitoring system have a separate alerting path from its data storage?",
         ["alerting must survive the data store going down or being unavailable", "it is cheaper to share one path", "storage never fails", "alerts should reuse dashboards only"], "C",
         "An independent alerting path keeps notifications flowing even when metric storage fails or is unreachable."),
        ("ADVANCED", "A sudden drop in requests could indicate an outage or a genuine decline in traffic. What is the best way to distinguish these?",
         ["correlate the drop with upstream traffic, error rates and synthetic probes", "assume it is an outage", "ignore the change", "restart the database"], "D",
         "Correlating with other signals distinguishes a real outage from an expected traffic decline."),
        ("ADVANCED", "Which metric best detects an overloaded queue where workers cannot keep up?",
         ["queue depth, which grows when consumption is slower than production", "the queue name", "the worker count", "the queue version"], "A",
         "Growing queue depth signals that work is arriving faster than workers can process it."),
        ("ADVANCED", "What is the recommended way to handle alerts that fire during a known, scheduled maintenance window?",
         ["suppress or mute the alerts for that window while ensuring the service is genuinely down as planned", "ignore alerts forever", "delete the monitoring system", "hide the dashboard"], "B",
         "Suppressing alerts during a planned maintenance window avoids paging operators for expected downtime."),
    ],
}
