# -*- coding: utf-8 -*-
"""
Question bank for subject 46: CORE106 - Compiler Design.
Category: Core Computer Science & Emerging Technologies.

Topics:
  226: Lexical Analysis
  227: Syntax Analysis & Parsing
  228: Semantic Analysis & Symbol Table
  229: Intermediate Code & Code Generation
  230: Code Optimization

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    226: [
        ("BEGINNER", "What is the primary task of the lexical analysis phase of a compiler?",
         ["To read the source character stream and group it into tokens", "To verify that the program is syntactically correct", "To generate optimized machine code", "To allocate registers for variables"], "A",
         "The lexical analyzer scans the raw source characters and groups them into meaningful tokens that the parser consumes."),
        ("BEGINNER", "In compiler terminology, what is a token?",
         ["A single byte of the source file", "A classified lexeme together with its token type", "A machine instruction emitted by the code generator", "A memory address in the symbol table"], "B",
         "A token is a lexeme paired with its token type, such as an identifier, keyword, or operator."),
        ("BEGINNER", "What is a lexeme?",
         ["The name of the grammar production used", "The line number where a symbol appears", "The actual sequence of characters in the source that matches a pattern", "The final machine code for a statement"], "C",
         "A lexeme is the concrete character string in the input that a pattern matches, such as the letters forming a variable name."),
        ("BEGINNER", "Which of the following is typically recognized as a distinct token type in a programming language?",
         ["Whitespace", "Comments", "Indentation", "Keywords"], "D",
         "Keywords such as if, while and return are reserved and recognized as their own token types by the scanner."),
        ("BEGINNER", "Which tool is commonly used to generate a lexical analyzer from a set of regular expressions?",
         ["Lex (or Flex)", "Yacc (or Bison)", "GCC", "Make"], "A",
         "Lex and Flex generate a scanner in C from regular expression pattern specifications."),
        ("BEGINNER", "What does a lexical analyzer typically do with whitespace and comments in the source?",
         ["It stores them in the symbol table", "It passes them to the parser as tokens", "It ignores or skips them and returns the next meaningful token", "It converts them into machine code"], "C",
         "Whitespace and comments carry no meaning to the parser, so the scanner usually skips them and emits only meaningful tokens."),
        ("BEGINNER", "Which formal language is the basis for describing the patterns that tokens must match?",
         ["Context-free grammars", "Regular expressions", "Turing machines", "Attribute grammars"], "B",
         "Regular expressions describe the regular languages accepted by the finite automata used to build scanners."),
        ("BEGINNER", "To which component does the lexical analyzer pass the stream of tokens it produces?",
         ["The optimizer", "The assembler", "The symbol table", "The parser"], "D",
         "The parser consumes the token stream produced by the lexer to build the syntactic structure of the program."),
        ("BEGINNER", "What marker is usually used to signal the end of the input to a scanner?",
         ["A semicolon", "A newline character", "The end-of-file (EOF) indicator", "A backslash"], "C",
         "The scanner recognizes an end-of-file condition to know when all tokens have been produced."),
        ("BEGINNER", "Which of the following is a typical pattern for an identifier token in many languages?",
         ["A sequence of digits only", "A letter followed by letters, digits, or underscores", "A single punctuation character", "Any binary number"], "B",
         "Identifiers usually begin with a letter and continue with letters, digits, or underscores."),
        ("INTERMEDIATE", "Consider the regular expression (ab)*c. Which of the following strings is matched by this pattern?",
         ["ababab", "abca", "abc", "cba"], "C",
         "(ab)*c requires any number of 'ab' pairs followed by a final 'c'; 'abc' is exactly one 'ab' followed by 'c'."),
        ("INTERMEDIATE", "What does the maximal munch rule state in lexical analysis?",
         ["The shortest matching pattern is always chosen", "When several patterns match a prefix, the longest match is chosen", "The first pattern in the specification always wins", "Patterns never overlap"], "B",
         "Maximal munch selects the longest prefix that any pattern matches, so the input is scanned left to right greedily."),
        ("INTERMEDIATE", "For the input 'ifx', where 'if' is a keyword and identifiers match [a-z]+, what token does maximal munch produce?",
         ["The keyword if", "Two separate identifiers", "A lexical error", "The identifier ifx"], "D",
         "Maximal munch matches the longest prefix, which is the whole word 'ifx', so it becomes an identifier rather than the keyword 'if'."),
        ("INTERMEDIATE", "How does a scanner usually decide that the input 'while' is a keyword rather than an identifier?",
         ["By checking only its first letter", "By counting its characters", "By looking the complete word up in a reserved-word table after it is recognized as an identifier", "By reading the next line of code"], "C",
         "The scanner first recognizes the word as an identifier and then consults the reserved-word table to see if it is a keyword."),
        ("INTERMEDIATE", "Which data structure is most commonly used to implement a DFA-based scanner?",
         ["A transition table indexed by state and input symbol", "A parse tree", "A hash table of tokens", "A doubly linked list"], "A",
         "A transition table stores the next state for every state and input symbol, which makes DFA simulation fast and compact."),
        ("INTERMEDIATE", "In a lexer, what is the purpose of a lookahead character?",
         ["To distinguish patterns that begin identically by examining extra input", "To speed up the symbol table lookup", "To compress the source file", "To decide the endianness of the target machine"], "A",
         "A single character of lookahead lets the scanner disambiguate tokens such as '=' versus '=='."),
        ("INTERMEDIATE", "When a scanner encounters a character that matches no pattern, what happens?",
         ["It is ignored silently", "A lexical error is reported", "It is converted into a keyword", "It is stored in the symbol table"], "B",
         "An unmatched character triggers a lexical error message, often giving the offending character and its position."),
        ("INTERMEDIATE", "Why is a deterministic finite automaton (DFA) preferred over an NFA for implementing a scanner?",
         ["A DFA accepts more languages than an NFA", "NFAs cannot represent tokens", "DFAs require fewer states than NFAs by definition", "A DFA has exactly one transition per input symbol from each state, making it faster and simpler to simulate"], "D",
         "Because a DFA has a unique next state for each symbol, its simulation is linear and simpler than backtracking over an NFA."),
        ("INTERMEDIATE", "What is recorded in the symbol table when the scanner recognizes an identifier token?",
         ["The complete source file", "The token type and the lexeme, or a pointer to it", "The optimized machine code", "The compiler version number"], "B",
         "For identifiers, the lexer records the lexeme and its token type so later phases can attach attributes such as type and value."),
        ("INTERMEDIATE", "A scanner that must report accurate error positions needs to track which of the following?",
         ["The number of tokens produced", "The number of registers in the target machine", "The current line number, incremented whenever a newline is seen", "The size of the symbol table"], "C",
         "Counting newline characters lets the scanner report the line number where each token or error occurs."),
        ("ADVANCED", "In C, the input 'a>>b' should be lexed as 'a', '>>', 'b'. Which rule guarantees the two greater-than signs are combined into one token?",
         ["The shortest match rule", "The maximal munch rule", "The leftmost derivation rule", "The precedence rule"], "B",
         "Maximal munch combines the two '>' characters into the single '>>' token because that is the longest matching prefix."),
        ("ADVANCED", "In C, the expression 'x*y' can mean multiplication or a pointer declaration. Why can the lexer not decide this alone?",
         ["Because the scanner lacks the parser's context, such as whether 'x' names a type", "Because lexers cannot read more than one character", "Because multiplication is illegal in C", "Because the symbol table is empty during lexing"], "A",
         "Whether 'x*y' is multiplication or a declaration depends on parser context like whether 'x' is a typedef, so the lexer alone cannot decide."),
        ("ADVANCED", "Which technique can reduce the number of states in a generated DFA scanner?",
         ["Adding more lookahead", "Replacing the DFA with an NFA", "Increasing the number of token types", "DFA minimization by merging indistinguishable states"], "D",
         "DFA minimization merges states that are indistinguishable with respect to accepting behavior, producing a smaller equivalent automaton."),
        ("ADVANCED", "In a generated scanner, when two patterns match the same longest input prefix, how is the conflict typically resolved?",
         ["Randomly", "An error is always raised", "The pattern listed first in the specification has priority", "The shorter pattern wins"], "C",
         "Tools such as Lex resolve ties by giving priority to the pattern that appears earliest in the specification."),
        ("ADVANCED", "Why is a table-driven DFA scanner often preferred over a large hand-written case statement?",
         ["It uses less source code at runtime", "It is automatically generated from regular expressions and easier to maintain", "Hand-written scanners can never fail", "It avoids the need for a symbol table"], "B",
         "Generator tools produce table-driven scanners from regular expressions, which keeps the code maintainable and less error-prone."),
        ("ADVANCED", "What is the purpose of start conditions in a tool like Flex?",
         ["They set the size of the output buffer", "They define the target machine", "They enable context-dependent scanning where different rule sets apply in different scanner states", "They enable the scanner to call the parser"], "C",
         "Start conditions let the scanner switch between rule sets, which is useful for handling strings, comments, and other context-sensitive input."),
        ("ADVANCED", "Why do string literals and character literals usually need special handling in the scanner?",
         ["They are always single characters", "They contain escape sequences and may span multiple lines, so a dedicated routine processes them", "They are handled by the optimizer", "They are converted to numbers"], "B",
         "String scanning requires escape sequence handling and end-of-line rules, so dedicated routines manage them apart from normal tokens."),
        ("ADVANCED", "A compiler reports 'unexpected character' errors with source positions. What does the scanner need to implement this accurately?",
         ["A random number generator", "The target machine's instruction set", "A profiler", "A line and column counter updated as input is consumed"], "D",
         "Tracking the current line and column lets the scanner pinpoint exactly where a lexical error occurred."),
        ("ADVANCED", "In languages with significant indentation such as Python, the lexical analyzer must synthesize what kind of tokens?",
         ["INDENT and DEDENT tokens that represent indentation level changes", "Newline tokens for every character", "Return tokens", "Comment tokens that are passed to the parser"], "A",
         "Python's lexer inserts INDENT and DEDENT tokens when the indentation level changes so the parser can enforce block structure."),
        ("ADVANCED", "Which design choice best explains why most production compilers keep the lexer and parser as separate phases?",
         ["A single phase is impossible to write", "The lexer must run after code generation", "Separation simplifies each component and allows scanner-specific optimizations such as a dedicated tokenizer", "Separating them makes the compiler slower by design"], "C",
         "Separating lexical and syntactic analysis keeps each phase simple and allows the scanner to be tuned independently, such as by DFA minimization."),
    ],
    227: [
        ("BEGINNER", "What is the main responsibility of the syntax analysis (parsing) phase of a compiler?",
         ["To check that the token stream conforms to the grammar of the language", "To perform type checking", "To generate assembly code", "To compress the source code"], "A",
         "The parser takes the token stream from the lexer and determines whether it can be derived from the grammar, building a parse tree."),
        ("BEGINNER", "Which formal system is used to describe the syntactic structure of a programming language?",
         ["Regular expressions", "Context-free grammars", "Finite automata", "Boolean algebra"], "B",
         "Context-free grammars specify the recursive structure of statements and expressions in a programming language."),
        ("BEGINNER", "In a context-free grammar, which of the following is a nonterminal?",
         ["An identifier such as 'x'", "A keyword such as 'if'", "A symbol like <expression> that is defined by a production", "A punctuation mark such as ';'"], "C",
         "Nonterminals are the grammar symbols that appear on the left side of productions, such as <expression>."),
        ("BEGINNER", "What is a parse tree?",
         ["A table of symbol addresses", "A list of machine instructions", "A graph of program dependencies", "A tree showing how a sentence is derived from the grammar"], "D",
         "A parse tree shows the derivation of a sentence, with leaves labeled by terminals and internal nodes by nonterminals."),
        ("BEGINNER", "Which of the following is a top-down parsing technique?",
         ["Recursive descent parsing", "LR parsing", "SLR parsing", "Shift-reduce parsing"], "A",
         "Recursive descent is a top-down approach that expands nonterminals to match the input, while LR techniques are bottom-up."),
        ("BEGINNER", "Which of the following is a bottom-up parsing technique?",
         ["Recursive descent parsing", "LR parsing", "LL(1) parsing", "Predictive parsing"], "B",
         "LR parsers build the parse tree from the leaves upward using shift and reduce actions."),
        ("BEGINNER", "In a grammar, what does the start symbol represent?",
         ["A terminal like ';'", "The end of input marker", "The highest-level construct from which all sentences derive", "A lexical error"], "C",
         "The start symbol is the nonterminal from which every valid sentence of the language is derived."),
        ("BEGINNER", "Which of the following is a terminal symbol in a grammar for a language?",
         ["<statement>", "<expression>", "<program>", "The keyword 'while'"], "D",
         "Terminals are the actual tokens such as keywords and operators, whereas angle-bracket names denote nonterminals."),
        ("BEGINNER", "What is the typical output produced by the syntax analysis phase?",
         ["A parse tree or abstract syntax tree", "A symbol table", "Three-address code", "A register allocation"], "A",
         "The parser produces a parse tree, which may be condensed into an abstract syntax tree for later phases."),
        ("BEGINNER", "What does the '1' in LL(1) stand for?",
         ["The number of passes over the source", "One lookahead symbol used to choose productions", "The number of start symbols", "The length of the longest token"], "B",
         "In LL(1), the parser uses one lookahead token to decide which production to apply in a leftmost derivation."),
        ("INTERMEDIATE", "Consider the grammar E -> E + T | T ; T -> id. Which transformation makes it suitable for a top-down LL parser?",
         ["Adding more lookahead symbols", "Applying the longest match rule", "Eliminating left recursion", "Replacing terminals with nonterminals"], "C",
         "Left recursion such as E -> E + T causes infinite recursion in top-down parsers, so it must be eliminated first."),
        ("INTERMEDIATE", "What is left factoring used for?",
         ["To remove left recursion", "To convert the grammar to Chomsky normal form", "To add new terminals", "To factor out a common prefix so the parser can defer choosing a production"], "D",
         "Left factoring extracts a common prefix so the parser can delay its decision until enough input has been read."),
        ("INTERMEDIATE", "In LL(1) parsing, what do FIRST sets help the parser decide?",
         ["Which production to apply based on the first token of the input", "How many registers to use", "Where to insert error recovery", "The order of symbol table entries"], "A",
         "FIRST(A) gives the terminals that can begin a string derived from A, so the parser picks the production whose FIRST set contains the lookahead."),
        ("INTERMEDIATE", "What does FOLLOW(A) represent in predictive parsing?",
         ["The first terminal derived from A", "The terminals that can legally appear immediately after A", "The nonterminals derived from A", "The last token of the entire program"], "B",
         "FOLLOW(A) is the set of terminals that can appear immediately to the right of A in any sentential form."),
        ("INTERMEDIATE", "In shift-reduce parsing, what does the 'reduce' action do?",
         ["Reads the next input token", "Rejects the input", "Replaces the right side of a production on the stack with its left-side nonterminal", "Moves the parse tree to the optimizer"], "C",
         "A reduce action pops the right-hand side of a production from the stack and pushes the left-hand nonterminal, recognizing the rule."),
        ("INTERMEDIATE", "Given the grammar S -> a S b | empty, which of the following strings is generated?",
         ["abb", "ba", "aaab", "aabb"], "D",
         "Applying S -> a S b twice and then the empty production yields 'aabb'."),
        ("INTERMEDIATE", "When an LL(1) parser has two productions for the same nonterminal with overlapping FIRST sets, what is the result?",
         ["The grammar is not LL(1) and the parse table has conflicts", "The parser automatically chooses the shorter production", "The grammar becomes ambiguous", "An LR parser is needed"], "A",
         "Overlapping FIRST sets cause multiple table entries for the same cell, meaning the grammar cannot be parsed deterministically by LL(1)."),
        ("INTERMEDIATE", "What is the purpose of panic-mode error recovery in a parser?",
         ["To optimize the generated code", "To discard tokens until a synchronization point is found so parsing can continue", "To pause the compiler for debugging", "To expand macros"], "B",
         "Panic mode skips input tokens until a statement boundary or sync token is found, allowing the parser to recover and continue."),
        ("INTERMEDIATE", "In bottom-up parsing, what does the 'shift' action do?",
         ["Reduces a production immediately", "Pushes the next input symbol onto the parser stack", "Pops the stack", "Terminates the parse"], "C",
         "A shift action reads the next input token and pushes it onto the stack without reducing anything yet."),
        ("INTERMEDIATE", "Which grammar class can be parsed by an LR(0) parser?",
         ["Only regular grammars", "Only ambiguous grammars", "Every context-free grammar", "The subclass of grammars whose canonical collection of LR(0) items has no conflicts"], "D",
         "LR(0) parsers require that no state contain both shift and reduce, or two reduce, actions; only conflict-free grammars qualify."),
        ("ADVANCED", "A parser generator reports a shift-reduce conflict. What does this mean?",
         ["The grammar is not LR and the tool cannot decide between shifting and reducing in some state", "The grammar is ambiguous beyond repair", "The parser stack overflowed", "The lexer produced an invalid token"], "A",
         "A shift-reduce conflict means a state in the LR automaton can legally shift and reduce on the same lookahead, so the grammar is not LR."),
        ("ADVANCED", "How is the classic 'dangling else' ambiguity usually resolved in a grammar?",
         ["By deleting the else keyword", "By matching each else with the nearest unmatched if", "By associativity rules alone", "By using a separate lexer pass"], "B",
         "Most languages resolve dangling else by binding each else to the closest preceding unmatched if, which is the standard convention."),
        ("ADVANCED", "Which parser construction generates parse tables from a canonical collection of LR(1) items?",
         ["LL(1) table construction", "Operator precedence parsing", "Canonical LR(1) parser construction", "Recursive descent"], "C",
         "Canonical LR(1) parsers are built from sets of LR(1) items that include full lookahead information."),
        ("ADVANCED", "What is the main trade-off between canonical LR(1) and SLR parsers?",
         ["SLR accepts more grammars", "Canonical LR(1) tables are usually smaller", "SLR is always ambiguous", "Canonical LR(1) handles more grammars but produces much larger parse tables"], "D",
         "Canonical LR(1) accepts a larger class of grammars but its tables can be huge; SLR and LALR reduce table size at some cost in coverage."),
        ("ADVANCED", "A grammar has multiple reductions possible in one LR state on the same lookahead. What kind of conflict is this?",
         ["A reduce-reduce conflict", "A shift-shift conflict", "A lexical conflict", "A type conflict"], "A",
         "When two productions can both be reduced in a state on the same lookahead, the parser cannot decide which rule applies."),
        ("ADVANCED", "Which technique merges states of a canonical LR(1) automaton to shrink the parse table?",
         ["LL(1) prediction", "LALR(1) state merging", "Left factoring", "Bottom-up error recovery"], "B",
         "LALR(1) merges states that share the same LR(0) core but differ only in lookaheads, greatly reducing table size."),
        ("ADVANCED", "In operator-precedence parsing, how is the precedence and associativity of operators specified?",
         ["By the order of tokens in the lexer", "By the parse tree depth", "By declaring precedence and associativity, typically in the parser generator", "By the number of operands"], "C",
         "Tools like Yacc let the user declare precedence and associativity so the parser generator can resolve expression ambiguities."),
        ("ADVANCED", "Why do most production compilers use LALR parsers generated by tools such as Yacc rather than hand-written recursive descent for expressions?",
         ["LALR grammars cannot have conflicts", "Recursive descent cannot parse arithmetic", "Yacc-generated parsers never fail", "LALR parsers are table-driven, fast, and can handle large grammars with manageable tables"], "D",
         "LALR tables are compact and fast, and generator tools automate table construction, making them ideal for complex languages."),
        ("ADVANCED", "What is the purpose of synchronization tokens in syntax error recovery?",
         ["They give the parser a known boundary, like a semicolon, to resume parsing after an error", "They mark the start of the program", "They tell the lexer to ignore input", "They optimize the parse table"], "A",
         "Synchronization tokens such as semicolons delimit statements, so the parser can skip erroneous input until the next boundary."),
        ("ADVANCED", "A compiler must report multiple syntax errors in one pass. Which error recovery strategy best supports this?",
         ["Terminating at the first error", "Using phrase-level or panic-mode recovery so parsing continues after each error", "Ignoring all errors", "Running the parser backward"], "B",
         "Phrase-level and panic-mode recovery allow the parser to resume after an error and report further errors in the same pass."),
    ],
    228: [
        ("BEGINNER", "What is the primary purpose of semantic analysis in a compiler?",
         ["To check that the program obeys language rules such as type compatibility", "To build the parse tree", "To convert tokens to three-address code", "To minimize register usage"], "A",
         "Semantic analysis checks context-sensitive rules like type compatibility and scope, which parsing alone cannot verify."),
        ("BEGINNER", "What data structure records information about identifiers such as their type and scope?",
         ["A parse tree", "The symbol table", "A transition table", "An abstract syntax tree"], "B",
         "The symbol table maps identifiers to their attributes, including type, scope, and address."),
        ("BEGINNER", "What is type checking?",
         ["Measuring the size of the source file", "Counting the number of tokens", "Verifying that operations are applied to operands of compatible types", "Compressing identifiers"], "C",
         "Type checking ensures each operator is used with operands whose types are allowed by the language."),
        ("BEGINNER", "Which of the following is an attribute commonly stored in the symbol table for a variable?",
         ["The color of the editor", "The compiler version", "The number of lines in the file", "Its data type and storage address"], "D",
         "The symbol table stores attributes such as type, storage class, and address for each declared identifier."),
        ("BEGINNER", "What is a scope in programming languages?",
         ["The region of the program in which a declaration of a name is visible", "The size of the symbol table", "The depth of the parse tree", "The length of the identifier"], "A",
         "A scope defines the textual region where a particular binding of a name is active and visible."),
        ("BEGINNER", "In semantic analysis, what is a type error?",
         ["A missing semicolon", "An operation applied to operands whose types are incompatible", "An identifier that is too long", "A comment in the code"], "B",
         "A type error occurs when, for example, a string is added to an integer, which the language rules forbid."),
        ("BEGINNER", "What does the attribute grammar formalism add to a context-free grammar?",
         ["New terminal symbols", "New parser states", "Semantic attributes and rules attached to productions", "New tokens for the lexer"], "C",
         "Attribute grammars attach attributes and semantic rules to grammar productions, formalizing the semantic analysis."),
        ("BEGINNER", "Which phase of compilation uses the symbol table most heavily to resolve identifier references?",
         ["Lexical analysis", "Code optimization", "Parsing", "Semantic analysis"], "D",
         "Semantic analysis consults the symbol table to check declarations, scopes, and types of every identifier reference."),
        ("BEGINNER", "What is the role of a declared type for a variable?",
         ["It determines the set of values and operations allowed on that variable", "It decides the editor font", "It sets the length of its name", "It determines the color of syntax highlighting"], "A",
         "A variable's type defines its legal values and the operations that can be performed on it."),
        ("BEGINNER", "What happens when a program uses a variable that has not been declared?",
         ["It is automatically created", "The semantic analyzer reports an undeclared identifier error", "It is treated as an integer", "The parser adds it to the grammar"], "B",
         "Using an undeclared identifier is a classic semantic error reported during symbol table lookup."),
        ("INTERMEDIATE", "In a block-structured language, which structure is commonly used to implement scoped symbol tables?",
         ["A single flat array", "A linked list of tokens", "A stack of symbol tables, one per block", "A parse tree"], "C",
         "Block structure pushes a new symbol table on entry to a block and pops it on exit, letting inner scopes shadow outer ones."),
        ("INTERMEDIATE", "Consider int x = 5; float y = 2.5; x = y;. In a language with strict type checking, what is the likely result?",
         ["A parse error", "No error at all", "A lexical error", "A type mismatch warning or error for assigning a float to an int"], "D",
         "Strict type checkers flag assigning a float to an int unless an explicit conversion is used."),
        ("INTERMEDIATE", "What is coercion in the context of type checking?",
         ["The implicit conversion of a value from one type to another", "The forced deletion of a variable", "The merging of two scopes", "The renaming of an identifier"], "A",
         "Coercion happens when the compiler silently converts an int to a float in an expression such as 3 + 2.5."),
        ("INTERMEDIATE", "Which of the following best describes static versus dynamic scope?",
         ["Static scope uses runtime lookup and dynamic scope uses compile-time lookup", "Static scope resolves names by textual nesting; dynamic scope resolves them by the call chain at runtime", "They are identical", "Static scope only applies to classes"], "B",
         "Lexical (static) scope binds names by program text structure, while dynamic scope looks up names through the execution call stack."),
        ("INTERMEDIATE", "In a symbol table, what does a 'hole' (or null) entry indicate?",
         ["An optimized variable", "A register allocation", "A slot that does not currently hold a valid identifier", "A parse tree node"], "C",
         "A hole is an empty slot in a symbol table bucket that can hold new entries."),
        ("INTERMEDIATE", "Which type-checking approach checks the types of an entire expression tree before any code generation?",
         ["Lazy checking", "Incremental checking", "Runtime checking", "Static type checking at compile time"], "D",
         "Static type checking inspects the type of every subexpression during semantic analysis, before runtime."),
        ("INTERMEDIATE", "What is the purpose of declaring a variable's type before use in languages like C?",
         ["So the compiler can allocate storage and check operations at compile time", "To make the program longer", "To satisfy the lexer", "To create a parse tree"], "A",
         "Type declarations let the compiler allocate storage and statically verify that operations are type-safe."),
        ("INTERMEDIATE", "What does the phrase 'type checking is part of semantic analysis' imply about the parser?",
         ["The parser performs type checking", "The parser only verifies syntax, and semantic analysis verifies type correctness", "Type checking happens in the lexer", "Type checking is unnecessary"], "B",
         "Parsing establishes structure; semantic analysis then applies context-sensitive checks such as type compatibility."),
        ("INTERMEDIATE", "In a language that allows shadowing, what does the name 'x' refer to inside an inner block that declares its own 'x'?",
         ["The outer x", "Both x's", "The inner x, which hides the outer declaration", "An error"], "C",
         "Shadowing lets an inner declaration hide the outer one, so references to 'x' in the inner block use the inner binding."),
        ("INTERMEDIATE", "Which of the following is a semantic check performed during declaration processing?",
         ["Checking balanced parentheses", "Matching begin-end tokens", "Counting loop iterations", "Detecting duplicate declarations in the same scope"], "D",
         "Semantic analysis rejects redeclaring the same name in the same scope, reporting a duplicate declaration error."),
        ("ADVANCED", "A compiler uses a symbol table where the same name in different scopes coexists. Which approach correctly handles this?",
         ["Nested symbol tables linked by a scope stack so the most recent declaration wins", "A single global table with no scoping", "Renaming every variable", "Deleting outer declarations"], "A",
         "A scope stack links nested tables, so lookups search from the innermost scope outward."),
        ("ADVANCED", "What is the difference between overloaded functions and functions with identical signatures?",
         ["They are identical", "Overloading lets multiple functions share a name when their parameter lists differ", "Overloading always causes a compile error", "Overloading happens only at runtime"], "B",
         "Overloading permits several functions to share a name as long as their signatures differ enough to disambiguate calls."),
        ("ADVANCED", "In a language with structural versus nominal typing, what distinguishes the two approaches?",
         ["Nominal typing compares structures and structural typing compares names", "They are the same", "Nominal typing uses declared type names, while structural typing compares type shapes", "Structural typing is only for records"], "C",
         "Nominal typing relies on the declared names of types, whereas structural typing accepts any value whose shape matches."),
        ("ADVANCED", "How does a compiler typically use the type attribute stored in the symbol table?",
         ["To indent the source code", "To name the output file", "To choose the editor theme", "To compute the size and alignment of the variable and to validate operations"], "D",
         "The stored type gives the size, alignment, and allowed operations, driving both checking and layout."),
        ("ADVANCED", "What is an inference rule in a type system such as the one used for the expression e1 + e2?",
         ["If e1 and e2 are both numeric, the addition is numeric", "Any addition is a string", "Addition is always an error", "The result type depends on the operator's precedence"], "A",
         "A typing rule states the conditions under which a construct is well typed and what type it produces."),
        ("ADVANCED", "In a language with generics, why must type parameters be checked at compile time?",
         ["To slow the compiler", "To guarantee that generic code is instantiated only with type-safe arguments", "To increase runtime flexibility", "Because generics have no semantics"], "B",
         "Compile-time checking of generic arguments ensures the instantiated code respects the type constraints of the generic declaration."),
        ("ADVANCED", "A large codebase has the same identifier declared at several nesting levels. What data structure minimizes lookup cost?",
         ["A linear scan of all tables", "A parse tree", "A hash table per scope, chained into a scope stack", "A single array of all names"], "C",
         "A hash table per scope gives constant average lookup, and the scope stack restricts search to visible scopes."),
        ("ADVANCED", "Why is it important for a compiler to report the line number where an undeclared identifier appears?",
         ["It makes the compiler slower", "It is required by the lexer", "It increases code size", "It lets the programmer locate and fix the error quickly"], "D",
         "Accurate source positions for semantic errors greatly speed debugging and are essential in real compilers."),
        ("ADVANCED", "What is the role of synthesized attributes in an attribute grammar for type checking?",
         ["They propagate type information from a node's children so parent types can be computed", "They mark unused variables", "They list the keywords of the language", "They record the parse table"], "A",
         "Synthesized attributes flow type information upward from the leaves so each parent node's type can be derived."),
        ("ADVANCED", "In a compiler, how is the address attribute of a variable determined during semantic analysis?",
         ["By the lexer", "By assigning an offset within the activation record during compilation", "By the parse tree depth", "By the operating system"], "B",
         "Semantic analysis lays out locals by allocating offsets in the function's activation record, recorded in the symbol table."),
    ],
    229: [
        ("BEGINNER", "What is three-address code?",
         ["An intermediate representation where each instruction has at most three operands and one operator", "A machine language for ARM", "A high-level scripting language", "A type of syntax tree"], "A",
         "Three-address code represents operations as x = y op z, with at most three operands per instruction."),
        ("BEGINNER", "What is the purpose of generating intermediate code?",
         ["To make programs run slower", "To provide a machine-independent representation that eases optimization and retargeting", "To replace the symbol table", "To compress the source code"], "B",
         "Intermediate code decouples the front end from the back end, easing optimization and porting to new machines."),
        ("BEGINNER", "Which of the following is an example of a three-address code instruction?",
         ["a = b + c * d", "while (i < n) { ... }", "t1 = a + b", "move ax, bx"], "C",
         "'t1 = a + b' is a simple three-address instruction with one operation and at most three operands."),
        ("BEGINNER", "Which of the following is a typical intermediate code representation used by compilers?",
         ["Machine code", "Assembly directives", "Source text", "Abstract syntax trees and three-address code"], "D",
         "Abstract syntax trees and three-address code are common intermediate representations between parsing and code generation."),
        ("BEGINNER", "In code generation, what does the term 'register' refer to?",
         ["A small high-speed storage location inside the CPU used to hold temporary values", "A line in the source file", "A symbol table entry", "A network address"], "A",
         "Registers are fast CPU storage locations that temporary values and variables may be assigned during code generation."),
        ("BEGINNER", "What is the main task of the code generation phase?",
         ["Reading the source file", "Translating the intermediate representation into target machine code or assembly", "Building the parse tree", "Type checking"], "B",
         "Code generation maps the intermediate representation to instructions of the target machine."),
        ("BEGINNER", "Which of the following is produced by the code generation phase?",
         ["Tokens", "A parse tree", "Target machine code or assembly language", "A symbol table"], "C",
         "The output of code generation is target code, usually assembly or machine instructions."),
        ("BEGINNER", "What does a temporary variable in three-address code represent?",
         ["A permanent global variable", "A constant in the source", "A comment", "An unnamed storage location that holds the result of an intermediate computation"], "D",
         "Temporaries such as t1 hold the results of subexpressions until they are consumed by later instructions."),
        ("BEGINNER", "Which instruction form is NOT typical of three-address code?",
         ["A single expression combining three operators in one line", "t = a + b", "if x < y goto L", "t = -a"], "A",
         "Three-address code limits each statement to one operation, so a line combining three operators is not typical."),
        ("BEGINNER", "What is the purpose of a jump (goto) instruction in intermediate code?",
         ["To declare variables", "To transfer control to a labeled instruction, used for implementing loops and conditionals", "To add two numbers", "To allocate registers"], "B",
         "Unconditional and conditional jumps implement the control flow of if-else and loop constructs."),
        ("INTERMEDIATE", "Consider the expression a = b * c + d. How is this translated into three-address code?",
         ["a = b * c + d", "t1 = b * c; t2 = t1 + d; a = t2", "t1 = b + c; a = t1 * d", "a = b; a = a + d"], "B",
         "Each operation becomes its own instruction: t1 = b * c, t2 = t1 + d, and finally a = t2."),
        ("INTERMEDIATE", "What does a basic block represent in intermediate code?",
         ["A function declaration", "A sequence of instructions with a single entry and single exit", "A register", "A parse tree"], "D",
         "A basic block is a maximal sequence of consecutive instructions entered only at the top and exited only at the bottom."),
        ("INTERMEDIATE", "In three-address code, what is a label used for?",
         ["To mark a target for jump instructions", "To name a temporary variable", "To store a constant", "To denote a lexical token"], "A",
         "Labels give names to instruction positions so jumps can transfer control to them."),
        ("INTERMEDIATE", "How is the if-else statement if (x > 0) then s1 else s2 represented in intermediate code?",
         ["A single arithmetic instruction", "A conditional jump to a label, then jumps around the else branch", "A function call", "A return statement"], "B",
         "The condition is tested with a conditional jump, and unconditional jumps skip the false branch."),
        ("INTERMEDIATE", "Which of the following intermediate representations is closest to the machine level?",
         ["An abstract syntax tree", "A symbol table", "Quadruples or three-address code", "A regular expression"], "C",
         "Three-address code (quadruples) is a low-level, machine-like representation that code generation can translate directly."),
        ("INTERMEDIATE", "What does register allocation attempt to minimize in generated code?",
         ["The number of source lines", "The number of parse errors", "The size of the symbol table", "The number of memory accesses by keeping values in registers"], "D",
         "Good register allocation keeps frequently used values in registers, reducing costly memory traffic."),
        ("INTERMEDIATE", "Why is intermediate code beneficial for a compiler that must target several machines?",
         ["Only the back end needs to be rewritten for each new target machine", "Each machine needs a new front end", "The source language changes per machine", "There is no benefit"], "A",
         "A common intermediate representation means only the code generator changes when retargeting to a new architecture."),
        ("INTERMEDIATE", "What is an address descriptor in register allocation?",
         ["A type of symbol", "A record of the locations, such as registers or memory, where a value currently resides", "A parse tree node", "A jump target"], "B",
         "Address descriptors track where each variable's value is stored, guiding when loads and stores are needed."),
        ("INTERMEDIATE", "In translating 'x = y * 2' to target code, why might a compiler prefer a shift instruction?",
         ["Because shifting is less portable", "Because multiplication is impossible", "Because a shift-left by one computes y*2 more cheaply on many machines", "Because the result is always zero"], "C",
         "On many CPUs a left shift by one is faster than a general multiply, so compilers may replace x = y * 2 with x = y << 1."),
        ("INTERMEDIATE", "What is the role of a spill in register allocation?",
         ["To merge two registers", "To duplicate code", "To add a new basic block", "To move a value from a register to memory when registers are exhausted"], "D",
         "When there are more live values than registers, the compiler spills some values to memory, which may increase memory traffic."),
        ("ADVANCED", "A program uses a variable that is live across a large loop. Why should the compiler prefer placing it in a register?",
         ["Register storage avoids repeated loads and stores in the loop, speeding up execution", "Registers have more capacity than memory", "Memory is faster than registers", "It makes the code easier to read"], "A",
         "Keeping a loop variable in a register eliminates memory access on each iteration, dramatically improving performance."),
        ("ADVANCED", "Which technique recomputes a common subexpression result stored in a temporary, instead of recalculating it?",
         ["Peephole optimization", "Common subexpression elimination", "Dead code removal", "Register renaming"], "B",
         "Common subexpression elimination replaces a repeated computation with a reference to a previously computed temporary."),
        ("ADVANCED", "What does the term 'liveness analysis' determine in code generation?",
         ["How long the program runs", "How many instructions exist", "Which variables hold values that are still needed later", "How many registers the CPU has"], "C",
         "Liveness analysis finds the program points where a variable's value is still needed, guiding register reuse."),
        ("ADVANCED", "Why is the choice of intermediate representation important for an optimizing compiler?",
         ["It changes the source language", "It affects only the lexer", "It is invisible to the optimizer", "A rich IR exposes optimization opportunities such as invariants and aliasing to the optimizer"], "D",
         "A well-designed IR preserves information the optimizer needs, such as control flow and data dependencies."),
        ("ADVANCED", "In instruction selection, what problem does tree-pattern matching help solve?",
         ["Choosing target instructions that cover a syntax-tree node pattern at the lowest cost", "Counting registers", "Generating symbols", "Minimizing source size"], "A",
         "Tree-pattern matching selects optimal instruction sequences by covering IR trees with target-machine instruction patterns."),
        ("ADVANCED", "A compiler generates code for a loop body. Which instruction scheduling concern is most important?",
         ["Color of the registers", "Hiding memory latency and avoiding pipeline stalls", "Keeping the symbol table small", "Reducing the number of labels"], "B",
         "Instruction scheduling reorders instructions to hide memory latency and keep the CPU pipeline full."),
        ("ADVANCED", "What is the function of an instruction selector in a retargetable compiler?",
         ["It parses the source", "It manages the symbol table", "It maps intermediate instructions to target machine instruction patterns", "It runs the program"], "C",
         "The instruction selector translates each IR construct into a sequence of target-machine instructions."),
        ("ADVANCED", "Which of the following best describes 'spilling' in the context of register allocation with limited registers?",
         ["Duplicating basic blocks", "Reordering instructions", "Merging functions", "Choosing variables to keep in memory rather than registers when registers run out"], "D",
         "Spilling selects the least costly variables to store in memory when the number of simultaneously live values exceeds registers."),
        ("ADVANCED", "Why might a compiler produce a conditional move instead of a conditional branch?",
         ["Conditional moves avoid branch mispredictions on modern processors", "Conditional branches are illegal", "Conditional moves use less memory", "Conditional moves always run faster than any branch"], "A",
         "A conditional move computes both outcomes and selects one, eliminating the branch and its potential misprediction penalty."),
        ("ADVANCED", "In translating array access a[i] to target code, what must the code generator compute?",
         ["The size of the program", "The address of element i using the base address, index, and element size", "The type of the array name", "The number of elements"], "B",
         "Array indexing requires computing base + i * element_size, an address calculation the generator emits explicitly."),
    ],
    230: [
        ("BEGINNER", "What is the goal of code optimization in a compiler?",
         ["To improve the efficiency of the generated code without changing its meaning", "To make the source code longer", "To add more comments", "To slow down execution for debugging"], "A",
         "Optimization aims to make programs faster, smaller, or use less energy while preserving observable behavior."),
        ("BEGINNER", "Which of the following is a local optimization?",
         ["Global data flow analysis", "Constant folding within a basic block", "Loop invariant code motion", "Register allocation across functions"], "B",
         "Constant folding, such as replacing 2 * 3 with 6, is performed within a single basic block, making it a local optimization."),
        ("BEGINNER", "What is constant folding?",
         ["Folding the source file", "Removing unused variables", "Computing constant expressions at compile time", "Renaming constants"], "C",
         "Constant folding evaluates expressions like 3 + 4 * 2 at compile time, replacing them with their constant result."),
        ("BEGINNER", "What is dead code?",
         ["Code that contains errors", "Code that is too long", "Code that runs slowly", "Code that can never be executed or whose result is never used"], "D",
         "Dead code is unreachable or has no effect on the program's output, so it can be safely removed."),
        ("BEGINNER", "What does common subexpression elimination (CSE) remove?",
         ["Repeated computations of the same expression", "All comments", "All loops", "All function calls"], "A",
         "CSE computes an expression once and reuses the result, eliminating duplicate calculations."),
        ("BEGINNER", "What is loop invariant code motion?",
         ["Copying code into a loop", "Moving code that does not change in each iteration outside the loop", "Deleting loops", "Inlining loops"], "B",
         "Expressions whose operands never change within the loop are hoisted above it so they execute only once."),
        ("BEGINNER", "Which of the following is a global optimization that considers the whole function?",
         ["Constant folding", "Basic block construction", "Global common subexpression elimination across basic blocks", "Tokenization"], "C",
         "Global optimizations use data flow analysis across the function, such as global CSE or constant propagation."),
        ("BEGINNER", "What is the purpose of data flow analysis in optimization?",
         ["To parse the program", "To generate tokens", "To manage the stack", "To collect facts about how values flow through the program, such as reaching definitions"], "D",
         "Data flow analysis gathers facts like which definitions reach a use, providing the information optimizations need."),
        ("BEGINNER", "What does peephole optimization operate on?",
         ["A short window of adjacent instructions", "The whole program at once", "The source code text", "The symbol table"], "A",
         "Peephole optimization examines a small sliding window of adjacent instructions and replaces inefficient sequences."),
        ("BEGINNER", "Why must an optimizer preserve the meaning of the program?",
         ["To make the compiler faster", "Because changing behavior would make the compiled program incorrect", "To reduce code size", "To satisfy the lexer"], "B",
         "Any optimization that alters the observable behavior of the program is invalid, so correctness is paramount."),
        ("INTERMEDIATE", "Consider the code x = a * b; y = a * b;. Which optimization replaces the second multiplication?",
         ["Constant folding", "Loop unrolling", "Common subexpression elimination", "Dead code elimination"], "C",
         "CSE computes a * b once into a temporary and reuses it for y, saving a multiplication."),
        ("INTERMEDIATE", "In a loop, the expression i * 4 is recomputed each iteration but i never changes. Which optimization applies?",
         ["Peephole optimization", "Constant folding", "Strength reduction", "Loop invariant code motion"], "D",
         "Since i * 4 is invariant within the loop, it is hoisted outside so it is computed only once."),
        ("INTERMEDIATE", "What is strength reduction?",
         ["Replacing an expensive operation with a cheaper equivalent one", "Deleting weak loops", "Increasing code size", "Adding redundant computations"], "A",
         "Strength reduction replaces expensive operations such as x * 2 with cheaper ones like a left shift."),
        ("INTERMEDIATE", "Consider the code if (DEBUG) { print(x); } where DEBUG is always false. Which optimization removes the print call?",
         ["Loop unrolling", "Dead code elimination after constant propagation", "Register allocation", "Peephole optimization"], "B",
         "Constant propagation turns DEBUG to false, making the block unreachable, and dead code elimination removes it."),
        ("INTERMEDIATE", "What does loop unrolling do?",
         ["It removes a loop entirely", "It merges two loops", "It replicates the loop body multiple times to reduce loop overhead", "It makes loops infinite"], "C",
         "Unrolling duplicates the body so each iteration does more work and the loop control overhead is paid less often."),
        ("INTERMEDIATE", "Which of the following best describes 'reaching definitions'?",
         ["The last line of the program", "The start of a function", "The number of basic blocks", "The set of assignment statements whose values could reach a given program point"], "D",
         "A definition reaches a point if there is a path along which it is not overwritten, information used by many optimizations."),
        ("INTERMEDIATE", "A variable is assigned but never read after that assignment. Which optimization removes the assignment?",
         ["Dead store elimination", "Constant folding", "Loop unrolling", "Instruction scheduling"], "A",
         "Dead store elimination removes assignments whose values are never used."),
        ("INTERMEDIATE", "What is a live variable?",
         ["A variable currently being printed", "A variable whose value may still be used later in the program", "A variable in a comment", "A constant"], "B",
         "A variable is live at a point if its value could still be read along some path from that point."),
        ("INTERMEDIATE", "Which data flow analysis computes the set of variables live at each point?",
         ["Constant propagation", "Type checking", "Liveness analysis", "Parsing"], "C",
         "Liveness analysis determines which variables hold values needed later, guiding register allocation."),
        ("INTERMEDIATE", "Consider x = 5; if (x > 0) { y = x + 1; }. Which optimization simplifies this?",
         ["Loop invariant code motion", "Function inlining", "Peephole optimization", "Constant propagation and folding"], "D",
         "Propagating x = 5 lets the compiler simplify x > 0 to true and y = 5 + 1 to y = 6 at compile time."),
        ("ADVANCED", "Why is alias analysis important for optimizations such as common subexpression elimination?",
         ["Without knowing whether two pointers may refer to the same location, reordering or eliminating memory accesses may be unsafe", "It makes the compiler slower", "It reduces the number of registers", "It changes the source language"], "A",
         "If two pointers may alias the same memory, their accesses cannot be freely reordered or eliminated without risking incorrect behavior."),
        ("ADVANCED", "Which optimization technique breaks a long loop into smaller pieces that execute in parallel?",
         ["Loop fusion", "Loop distribution or fission", "Constant folding", "Peephole optimization"], "B",
         "Loop fission splits a loop into several loops, which can expose parallelism or improve cache behavior."),
        ("ADVANCED", "What is the main benefit of function inlining?",
         ["It increases code size for no reason", "It removes the call overhead and enables further optimizations within the caller", "It makes the program harder to read", "It always reduces code size"], "C",
         "Inlining eliminates call overhead and lets the caller's optimizer see the body, but it can bloat code if overused."),
        ("ADVANCED", "A hot loop repeatedly accesses an array in column order while the array is stored row-major. Which transformation is most relevant?",
         ["Strength reduction", "Constant propagation", "Function inlining", "Loop interchange to improve cache locality"], "D",
         "Loop interchange reorders nested loops so memory accesses follow the storage order, greatly improving cache hit rates."),
        ("ADVANCED", "What is the purpose of an optimizer's control flow graph (CFG)?",
         ["It represents basic blocks and the jumps between them, providing the framework for global optimizations", "It stores the tokens", "It is the symbol table", "It describes the grammar"], "A",
         "The CFG models the function as blocks and edges, which data flow and many global optimizations operate on."),
        ("ADVANCED", "Why must the compiler be careful when hoisting an invariant expression out of a loop?",
         ["It is always illegal", "The expression might fault, such as dividing by zero or dereferencing a null pointer, on paths that never execute", "It slows the loop", "It changes the token stream"], "B",
         "Hoisting a potentially faulting operation could introduce an error on a path where the loop body never ran, so safety must be checked."),
        ("ADVANCED", "Which of the following is an example of a 'peephole' transformation?",
         ["Global register allocation", "Replacing the sequence x = 0; x = x + 1 with x = 1", "Building the CFG", "Inlining a function"], "C",
         "Peephole optimization examines adjacent instructions, such as a store followed by an add, and replaces the redundant pair."),
        ("ADVANCED", "What does tail call optimization do?",
         ["It inlines all recursive calls", "It unrolls the loop", "It removes the return statement", "It reuses the caller's stack frame for a tail-recursive call, avoiding stack growth"], "D",
         "Tail call optimization turns a tail-recursive call into a jump reusing the frame, keeping the stack bounded."),
        ("ADVANCED", "An optimizer wants to prove that a pointer p never points into a particular array region. What does it need?",
         ["Point-to or alias analysis that computes the set of locations p may reference", "A larger symbol table", "More registers", "A new lexer"], "A",
         "Points-to analysis determines which memory locations a pointer may reference, enabling safe optimization of memory accesses."),
        ("ADVANCED", "In an optimizing compiler, what is the role of the 'use-def' chain?",
         ["It lists all keywords", "It links each use of a variable to the definitions that may reach it, supporting transformations", "It builds the parse tree", "It schedules instructions"], "B",
         "Use-def chains connect each use to its reaching definitions, a cornerstone data structure for optimizations like copy propagation."),
    ],
}
