# -*- coding: utf-8 -*-
"""
Question bank for subject 5 - PROG105 - JavaScript (Programming & Software Development).
Topics: 21 JS Fundamentals & Variables, 22 Functions & Scope, 23 DOM & Events,
24 ES6 & Arrays, 25 Async JavaScript.
Each topic has exactly 30 questions: 10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED.
"""

QUESTIONS = {
    21: [
        ("BEGINNER", "Which keyword declares a constant that cannot be reassigned in JavaScript?",
         ["const", "let", "var", "static"], "A",
         "const creates a binding that cannot be reassigned after its initial value is set."),
        ("BEGINNER", "What does console.log(typeof 42) output?",
         ["integer", "number", "float", "numeric"], "B",
         "The typeof operator returns the string 'number' for numeric primitives such as 42."),
        ("BEGINNER", "Which operator performs a strict equality comparison in JavaScript?",
         ["=", "==", "===", "!=="], "C",
         "=== compares both value and type without performing any type coercion."),
        ("BEGINNER", "What is the result of 5 === '5'?",
         ["true", "false", "NaN", "undefined"], "B",
         "Strict equality compares value and type, and a number is never strictly equal to a string."),
        ("BEGINNER", "Which of the following is a primitive data type in JavaScript?",
         ["object", "array", "string", "function"], "C",
         "Strings are primitives, while objects, arrays and functions are reference types."),
        ("BEGINNER", "What does the let keyword do when used to declare a variable?",
         ["Declares a block-scoped variable that can be reassigned", "Declares a constant that cannot change", "Creates a global-only variable", "Defines a named function"], "A",
         "let declares a block-scoped and mutable variable, unlike const which cannot be reassigned."),
        ("BEGINNER", "What is the value of 10 % 3?",
         ["1", "3", "0.33", "7"], "A",
         "The modulo operator returns the remainder of 10 divided by 3, which is 1."),
        ("BEGINNER", "Which statement correctly describes strict mode in JavaScript?",
         ["It disables all error reporting", "It prevents any use of functions", "It converts JavaScript into Java", "It enables stricter parsing and throws errors for unsafe syntax"], "D",
         "Strict mode changes how the engine behaves, throwing errors for silent mistakes and unsafe syntax."),
        ("BEGINNER", "What does typeof null return?",
         ["null", "undefined", "boolean", "object"], "D",
         "A historical quirk makes typeof null report 'object' instead of 'null'."),
        ("BEGINNER", "Which of these is a valid JavaScript variable name?",
         ["2ndName", "my-name", "class", "_total"], "D",
         "Identifiers must start with a letter, underscore or dollar sign, so _total is valid."),
        ("INTERMEDIATE", "What is the result of 0.1 + 0.2 === 0.3 in JavaScript?",
         ["false", "true", "undefined", "NaN"], "A",
         "Floating point cannot represent 0.1 and 0.2 exactly, so their sum is not exactly 0.3."),
        ("INTERMEDIATE", "What does the unary plus operator do to the string '5' in the expression +'5'?",
         ["It concatenates it with an empty string", "It converts the string to the number 5", "It throws a TypeError", "It returns the string '5' unchanged"], "B",
         "The unary plus coerces its operand to a number, turning the string '5' into the number 5."),
        ("INTERMEDIATE", "What does Boolean('0') evaluate to?",
         ["false", "null", "true", "0"], "C",
         "Any non-empty string, including '0', is truthy, so Boolean('0') returns true."),
        ("INTERMEDIATE", "What is the output of console.log(2 + 3 * 4)?",
         ["20", "24", "9", "14"], "D",
         "Multiplication has higher precedence than addition, so the expression evaluates as 2 + 12, which is 14."),
        ("INTERMEDIATE", "What is the output of console.log(typeof undefined)?",
         ["null", "object", "undefined", "number"], "C",
         "typeof undefined returns the string 'undefined', matching the type of that value."),
        ("INTERMEDIATE", "What is the output of console.log('5' + 2)?",
         ["7", "3", "'52'", "NaN"], "C",
         "When one operand is a string, the + operator concatenates, producing the string '52'."),
        ("INTERMEDIATE", "What is the output of console.log(3 > 2 > 1)?",
         ["false", "true", "NaN", "1"], "A",
         "3 > 2 evaluates to true, then true > 1 coerces true to 1, and 1 > 1 is false."),
        ("INTERMEDIATE", "What is the output of console.log(NaN === NaN)?",
         ["true", "false", "NaN", "undefined"], "B",
         "NaN is never equal to itself, so NaN === NaN is false."),
        ("INTERMEDIATE", "What happens when you write let x = 1; let x = 2; in the same scope?",
         ["The second declaration overrides the first silently", "Only the first declaration is kept", "It creates two separate variables", "A SyntaxError is thrown for redeclaring a let variable"], "D",
         "let does not allow redeclaration in the same scope, so the code throws a SyntaxError."),
        ("INTERMEDIATE", "What is the output of console.log(typeof ('5' - 1))?",
         ["number", "string", "NaN", "object"], "A",
         "The subtraction operator coerces the string '5' to a number, so the result 4 has type number."),
        ("ADVANCED", "What happens when you access a let-declared variable before its declaration statement executes?",
         ["A ReferenceError is thrown because of the temporal dead zone", "undefined is returned", "null is returned", "The variable is implicitly declared as global"], "A",
         "Variables declared with let exist in the temporal dead zone until their declaration runs, so accessing them throws a ReferenceError."),
        ("ADVANCED", "Given const obj = { a: 1 }; which of the following is allowed?",
         ["Reassigning obj to a new object", "Mutating the property with obj.a = 2", "Deleting the object itself", "Declaring const obj again in the same scope"], "B",
         "const prevents reassignment of the binding but does not freeze the object, so property mutation is allowed."),
        ("ADVANCED", "What is the output of console.log(parseInt('10', 2))?",
         ["10", "NaN", "2", "0"], "C",
         "parseInt with radix 2 parses the binary string '10' into the decimal number 2."),
        ("ADVANCED", "What is the output of console.log(String(undefined))?",
         ["null", "'undefined'", "NaN", "undefined"], "D",
         "String(undefined) returns the string 'undefined', the textual representation of that value."),
        ("ADVANCED", "What is the type of the literal 10n?",
         ["number", "integer", "bignum", "bigint"], "D",
         "The n suffix denotes a BigInt, whose typeof is 'bigint'."),
        ("ADVANCED", "What is the output of console.log(Symbol('id') === Symbol('id'))?",
         ["true", "false", "NaN", "TypeError"], "B",
         "Every call to Symbol creates a unique value, so two symbols with the same description are never equal."),
        ("ADVANCED", "Which of the following values is falsy in JavaScript?",
         ["[]", "{}", "0n", "'false'"], "C",
         "BigInt zero (0n) is falsy, while empty arrays, empty objects and the string 'false' are all truthy."),
        ("ADVANCED", "What does Object.keys({ b: 1, a: 2, 10: 'x' }) return?",
         ["['10', 'b', 'a']", "['b', 'a', '10']", "['a', 'b', '10']", "['b', '10', 'a']"], "A",
         "Integer-like keys are ordered numerically first, so '10' precedes the string keys 'b' and 'a'."),
        ("ADVANCED", "What is the output of console.log(null == undefined)?",
         ["false", "true", "TypeError", "NaN"], "B",
         "null and undefined are loosely equal to each other, though not to any other value."),
        ("ADVANCED", "What is the output of console.log(5 & 3)?",
         ["8", "2", "1", "6"], "C",
         "The bitwise AND of 5 (101) and 3 (011) is 001, which equals 1 in decimal."),
    ],
    22: [
        ("BEGINNER", "Which keyword is used to declare a function in JavaScript?",
         ["function", "def", "func", "fn"], "A",
         "The function keyword begins a standard function declaration in JavaScript."),
        ("BEGINNER", "What does a function return if it has no return statement?",
         ["null", "0", "undefined", "NaN"], "C",
         "A function without an explicit return statement returns undefined."),
        ("BEGINNER", "Which of the following creates a function expression?",
         ["function greet() {}", "def greet():", "function: greet {}", "const greet = function () {};"], "D",
         "Assigning an anonymous function to a variable creates a function expression."),
        ("BEGINNER", "What is a callback function?",
         ["A function that returns a callback object", "A function passed as an argument to another function", "A function that can only be called once", "A built-in browser function"], "B",
         "A callback is a function passed into another function and invoked later."),
        ("BEGINNER", "What is the output of calling greet() when greet is defined as function greet() { return 'hi'; }?",
         ["'hi'", "undefined", "null", "0"], "A",
         "The function explicitly returns the string 'hi'."),
        ("BEGINNER", "Which statement about function declarations and hoisting is correct?",
         ["They are only hoisted when declared with const", "They cannot be used before they are defined", "They are hoisted to the top of their scope and can be called earlier", "They must always be used as expressions"], "C",
         "Function declarations are fully hoisted, so they can be called before their definition in the source."),
        ("BEGINNER", "What is the purpose of the return keyword?",
         ["To stop the function and send a value back to the caller", "To restart the function", "To log a value to the console", "To declare a variable"], "A",
         "return ends execution of the function and hands its value back to the caller."),
        ("BEGINNER", "Where does a variable declared with var outside any function live?",
         ["Inside the nearest block", "Inside a module only", "In the local scope of the script", "In the global scope"], "D",
         "A var declared at the top level lives in the global scope."),
        ("BEGINNER", "What is a parameter in JavaScript?",
         ["A value used to destroy a function", "A placeholder listed in the function definition that receives arguments", "A keyword that ends a loop", "A built-in array method"], "B",
         "Parameters are the named placeholders in a function signature that receive the passed arguments."),
        ("BEGINNER", "What happens if you call a function that expects 3 arguments with only 1?",
         ["A SyntaxError is thrown", "The missing parameters become undefined", "The function returns NaN automatically", "The extra calls are queued"], "B",
         "JavaScript does not enforce arity, so missing arguments are simply assigned undefined."),
        ("INTERMEDIATE", "What is a closure in JavaScript?",
         ["A function that retains access to its outer lexical scope even after the outer function returns", "A function that is immediately garbage collected", "An object that stores only primitive values", "A syntax error thrown at runtime"], "A",
         "A closure combines a function with the scope where it was defined, keeping outer variables alive."),
        ("INTERMEDIATE", "function outer() { let x = 10; return function () { return x; }; } What does outer()() return?",
         ["undefined", "10", "NaN", "ReferenceError"], "B",
         "The returned inner function closes over x, so calling outer()() returns 10."),
        ("INTERMEDIATE", "if (true) { var a = 5; } console.log(a); What is the output?",
         ["ReferenceError", "undefined", "5", "null"], "C",
         "var is function-scoped, not block-scoped, so a is still accessible after the if block."),
        ("INTERMEDIATE", "function outer() { let msg = 'hi'; function inner() { return msg; } return inner(); } What does outer() return?",
         ["undefined", "null", "TypeError", "'hi'"], "D",
         "inner can read msg through lexical scope, so outer() returns the string 'hi'."),
        ("INTERMEDIATE", "sayHi(); function sayHi() { return 'hello'; } Why does this code not throw an error?",
         ["Because functions are expressions", "Because var hoists the return value", "Because the declaration is hoisted to the top of the scope", "Because the engine runs the file twice"], "C",
         "Function declarations are hoisted entirely, making sayHi available before its source line."),
        ("INTERMEDIATE", "console.log(f); const f = function () {}; What is the output?",
         ["undefined", "ReferenceError", "null", "NaN"], "B",
         "A const function expression is not initialized until its line runs, so accessing it earlier hits the temporal dead zone."),
        ("INTERMEDIATE", "function greet(name = 'World') { return 'Hello, ' + name; } What does greet() return?",
         ["'Hello, undefined'", "'Hello, null'", "'Hello'", "'Hello, World'"], "D",
         "When no argument is passed, the default parameter 'World' is used."),
        ("INTERMEDIATE", "What is the main purpose of an immediately invoked function expression (IIFE)?",
         ["To create a private scope and avoid polluting the global scope", "To make code run slower", "To force a function to return a promise", "To replace classes entirely"], "A",
         "An IIFE runs immediately and keeps its variables in their own scope, off the global object."),
        ("INTERMEDIATE", "What is the output of console.log(typeof function () {})?",
         ["object", "undefined", "function", "callable"], "C",
         "typeof reports the string 'function' for all function values."),
        ("INTERMEDIATE", "function sum() { return arguments.length; } What does sum(1, 2, 3) return?",
         ["3", "undefined", "0", "NaN"], "A",
         "arguments.length reflects the number of arguments actually passed, which is 3."),
        ("ADVANCED", "const obj = { val: 42, get() { return this.val; } }; What does obj.get() return?",
         ["undefined", "the window object", "42", "TypeError"], "C",
         "When a method is invoked as obj.get(), this is bound to obj, so this.val is 42."),
        ("ADVANCED", "const obj = { val: 42, get: () => this.val }; What does obj.get() return in a module?",
         ["42", "undefined", "NaN", "TypeError"], "B",
         "Arrow functions do not bind their own this; they capture this from the enclosing scope, which is not obj."),
        ("ADVANCED", "In strict mode, what is this inside a plain regular function called without any object?",
         ["The window object", "undefined", "null", "The function itself"], "B",
         "In strict mode, standalone function calls receive undefined as this."),
        ("ADVANCED", "In sloppy (non-strict) mode, what is this inside a standalone regular function call?",
         ["undefined", "null", "the function's prototype", "the global object"], "D",
         "In sloppy mode a standalone call binds this to the global object, which is window in browsers."),
        ("ADVANCED", "What does fn.call(target) do?",
         ["It clones fn into a new array", "It calls fn asynchronously", "It removes fn from memory", "It calls fn with this set to target"], "D",
         "Function.prototype.call invokes the function immediately with the given object as this."),
        ("ADVANCED", "What does const bound = fn.bind(obj); create?",
         ["A new array", "A new function with this permanently set to obj", "A Promise wrapper", "A copy of obj"], "B",
         "bind returns a new function whose this is fixed to obj whenever it is called."),
        ("ADVANCED", "for (var i = 0; i < 3; i++) { setTimeout(function () { console.log(i); }, 0); } What is printed?",
         ["0 1 2", "1 2 3", "3 3 3", "0 0 0"], "C",
         "The single var i is shared by all callbacks and ends at 3, so every callback prints 3."),
        ("ADVANCED", "for (let i = 0; i < 3; i++) { setTimeout(function () { console.log(i); }, 0); } What is printed?",
         ["0 1 2", "3 3 3", "1 2 3", "undefined"], "A",
         "Each iteration of let creates its own binding, so every callback captures a distinct i."),
        ("ADVANCED", "let x = 10; function f(x) { return x + 1; } What does f(5) return?",
         ["11", "10", "6", "NaN"], "C",
         "The parameter x shadows the outer x, so the function uses the passed value 5 and returns 6."),
        ("ADVANCED", "What does the following code print? let g = (function () { let count = 0; return function () { count += 1; return count; }; })(); console.log(g()); console.log(g());",
         ["1 then 2", "0 then 1", "1 then 1", "undefined twice"], "A",
         "The IIFE returns a closure that keeps count alive and increments it on each call, printing 1 then 2."),
    ],
    23: [
        ("BEGINNER", "What does document.getElementById('title') return when no element has that id?",
         ["null", "undefined", "an empty object", "a SyntaxError"], "A",
         "getElementById returns null when no element with the given id exists."),
        ("BEGINNER", "Which property sets or returns the plain text content of an element?",
         ["innerHTML", "textContent", "className", "src"], "B",
         "textContent handles the text inside an element without parsing HTML."),
        ("BEGINNER", "Which method attaches an event handler to an element?",
         ["attachHandler", "onEvent", "addEventListener", "bindEvent"], "C",
         "addEventListener registers a listener for a specified event on the target element."),
        ("BEGINNER", "What does document.querySelector('p') return?",
         ["An array of all p elements", "The first p element in the document", "All paragraphs joined as a string", "The number of p elements"], "B",
         "querySelector returns the first matching element for the given CSS selector."),
        ("BEGINNER", "What does the Document Object Model (DOM) represent?",
         ["A database of browser settings", "A compiled binary of the script", "A tree structure of the page's elements", "A network protocol"], "C",
         "The DOM is an object tree representing the document that scripts can manipulate."),
        ("BEGINNER", "Which property references the direct parent node of an element?",
         ["childNodes", "siblingElement", "rootNode", "parentElement"], "D",
         "parentElement points to the immediate parent element in the tree."),
        ("BEGINNER", "What does document.createElement('li') accomplish?",
         ["Creates a new li element in memory", "Adds an li to the page immediately", "Deletes an existing li", "Selects the last li"], "A",
         "createElement builds a new element in memory that you later insert into the document."),
        ("BEGINNER", "Which event type fires when a user clicks on an element?",
         ["keydown", "load", "submit", "click"], "D",
         "The click event is dispatched after a user activates an element with the mouse."),
        ("BEGINNER", "What does the innerHTML property allow you to do?",
         ["Read or set the HTML markup inside an element", "Only read plain text", "Change the browser URL", "Set CSS variables"], "A",
         "innerHTML reads or writes the raw HTML markup contained by the element."),
        ("BEGINNER", "Which method removes a child element from the DOM?",
         ["delete()", "discard()", "removeChild()", "hide()"], "C",
         "removeChild removes a specified child node from its parent."),
        ("INTERMEDIATE", "When you click a button inside a div, and both have click handlers, which handler runs first in the bubbling phase?",
         ["The button's handler", "The div's handler", "Both run simultaneously", "Neither runs"], "A",
         "In the bubbling phase, the innermost target's handler fires first, then the event bubbles up to ancestors."),
        ("INTERMEDIATE", "What is event propagation?",
         ["The speed at which a script runs", "The way events move through the DOM tree between the target and the document", "A method for sending data to a server", "The order in which styles are applied"], "B",
         "Propagation describes how an event travels from the root down to the target and then bubbles back up."),
        ("INTERMEDIATE", "Which method stops an event from bubbling to parent elements?",
         ["event.stopPropagation()", "event.preventDefault()", "event.stop()", "event.halt()"], "A",
         "stopPropagation halts the event from traveling further through the DOM."),
        ("INTERMEDIATE", "Inside an event handler, what does event.target refer to?",
         ["The element that the listener was attached to", "The element on which the event originally occurred", "The parent of the clicked element", "The window object"], "B",
         "target is the deepest element where the event actually happened, which may differ from the listener."),
        ("INTERMEDIATE", "In a form submit handler, what does event.preventDefault() accomplish?",
         ["It stops the event from bubbling", "It reloads the page", "It prevents the default form submission and page reload", "It disables the form forever"], "C",
         "preventDefault cancels the browser's default action, here the submission of the form."),
        ("INTERMEDIATE", "What is the difference between event.currentTarget and event.target?",
         ["They are always identical", "currentTarget is the element the listener is attached to, while target is where the event happened", "target is only for mouse events", "currentTarget refers to the window only"], "B",
         "currentTarget is the element whose listener is executing, while target is the originating element."),
        ("INTERMEDIATE", "Why would you prefer addEventListener over assigning onclick?",
         ["addEventListener is faster", "onclick works in every browser", "addEventListener removes the need for functions", "addEventListener lets you register multiple listeners for the same event"], "D",
         "addEventListener supports several listeners on one element, while onclick overwrites previous ones."),
        ("INTERMEDIATE", "Why must you pass the same function reference to removeEventListener that was used in addEventListener?",
         ["Because it recompiles the handler", "Because the DOM stores only strings", "Because listeners are matched by reference identity", "Because anonymous functions are always removed"], "C",
         "removeEventListener only removes a listener that matches the exact same function object."),
        ("INTERMEDIATE", "What is the correct sequence to add a new paragraph to the body?",
         ["Create the element, then append it", "Append first, then create the element", "Write HTML directly into the URL", "Use alert() to insert nodes"], "A",
         "You create a node with createElement and then insert it with appendChild."),
        ("INTERMEDIATE", "What is the effect of element.classList.add('active')?",
         ["It replaces all existing classes with 'active'", "It deletes the class list", "It selects all elements named active", "It appends 'active' to the element's class list"], "D",
         "classList.add inserts the class without touching other classes already present."),
        ("ADVANCED", "Why is event delegation efficient for lists with many dynamically added items?",
         ["A single listener on a parent handles events from all children, including future ones", "It creates a new listener for every child automatically", "It disables all child events", "It uses the capture phase to skip the DOM"], "A",
         "Delegation attaches one handler to an ancestor and uses target to respond, so new children need no listeners."),
        ("ADVANCED", "How does event.stopImmediatePropagation() differ from stopPropagation()?",
         ["It only stops capture", "It also prevents other listeners on the same element from running", "It reverses the event order", "It is identical to stopPropagation"], "B",
         "stopImmediatePropagation stops bubbling and cancels the remaining listeners on the current element."),
        ("ADVANCED", "With addEventListener('click', handler, true) on a parent, when does handler run?",
         ["During the bubbling phase", "Only after all children finish", "During the capture phase, before the child's handler", "After the event has ended"], "C",
         "The third argument true registers the listener for the capture phase, so it runs before target handlers."),
        ("ADVANCED", "Which API approach is ideal for creating a brand-new element with attributes and then inserting it?",
         ["document.write with inline HTML", "createElement combined with setAttribute and appendChild", "console.log to build nodes", "window.open to create nodes"], "B",
         "createElement builds the node, setAttribute configures it, and appendChild inserts it into the DOM."),
        ("ADVANCED", "What is the key difference between the click event and the mousedown event?",
         ["click fires on key press", "mousedown fires after the mouse is released", "click fires after press and release, while mousedown fires immediately on press", "They are identical events"], "C",
         "mousedown triggers the instant a button is pressed, while click fires later after release on the same element."),
        ("ADVANCED", "In a keydown handler, which property contains the actual character of the pressed key?",
         ["event.type", "event.target", "event.value", "event.key"], "D",
         "event.key holds the character or key name produced by the pressed physical key."),
        ("ADVANCED", "How do you make an event listener run exactly once and then remove itself?",
         ["Pass the { once: true } option to addEventListener", "Call removeEventListener inside a setTimeout", "Use event.stopPropagation()", "Set the handler to null"], "A",
         "The once option automatically removes the listener after it fires a single time."),
        ("ADVANCED", "When does the DOMContentLoaded event fire compared to the load event?",
         ["After all images and stylesheets finish loading", "Before the HTML is parsed", "Only in service workers", "As soon as the HTML is fully parsed, before external resources finish"], "D",
         "DOMContentLoaded fires when the document structure is parsed, while load waits for all resources."),
        ("ADVANCED", "What is a key difference between getElementsByClassName and querySelectorAll?",
         ["querySelectorAll returns a static NodeList while getElementsByClassName returns a live collection", "getElementsByClassName is always empty", "querySelectorAll only matches ids", "There is no difference"], "A",
         "The live HTMLCollection updates as the DOM changes, while the static NodeList does not."),
        ("ADVANCED", "During a bubbling click on a child, what does event.currentTarget equal inside the parent's handler?",
         ["The child that was clicked", "The parent element the listener is attached to", "The document root", "undefined"], "B",
         "currentTarget always equals the element whose listener is running, which here is the parent."),
    ],
    24: [
        ("BEGINNER", "const nums = [1, 2, 3]; nums.push(4); What is nums.length?",
         ["3", "4", "5", "TypeError"], "B",
         "const only prevents reassignment of the variable, not mutation of the array, so push works and length becomes 4."),
        ("BEGINNER", "What does the arrow function const add = (a, b) => a + b; return when called as add(2, 3)?",
         ["5", "23", "undefined", "NaN"], "A",
         "The concise body implicitly returns the expression a + b, which is 5."),
        ("BEGINNER", "Which ES6 feature lets you unpack values from arrays or objects into variables?",
         ["spread operator", "template literals", "classes", "destructuring"], "D",
         "Destructuring assigns selected values to variables using syntax like const { a } = obj."),
        ("BEGINNER", "What does the spread operator (...) do when applied to an array?",
         ["Deletes the array", "Sorts the array", "Expands the array into its individual elements", "Duplicates the array into a string"], "C",
         "Spread unpacks an iterable into individual elements for use in calls, arrays or literals."),
        ("BEGINNER", "What is the value of the template literal `Hello ${'World'}`?",
         ["'Hello World'", "'Hello ${World}'", "undefined", "'HelloWorld'"], "A",
         "Template literal interpolation replaces ${...} with the evaluated value, giving 'Hello World'."),
        ("BEGINNER", "Which array method returns a new array after transforming each element?",
         ["forEach", "map", "filter", "reduce"], "B",
         "map runs a function on each element and returns a new array of the results."),
        ("BEGINNER", "Which array method returns a new array containing only elements that pass a test?",
         ["filter", "map", "push", "join"], "A",
         "filter keeps the elements for which the callback returns a truthy value."),
        ("BEGINNER", "Which array method reduces an array to a single accumulated value?",
         ["concat", "some", "flat", "reduce"], "D",
         "reduce walks the array and folds it into one value using an accumulator."),
        ("BEGINNER", "What is the default parameter syntax in ES6?",
         ["function f(a, b: 5) {}", "function f(a = default) {}", "function f(a := 5) {}", "function f(a, b = 5) {}"], "D",
         "Default parameters are written with = in the signature, so b becomes 5 when omitted."),
        ("BEGINNER", "What does [1, 2, 3].includes(2) return?",
         ["false", "2", "true", "undefined"], "C",
         "includes returns true when the array contains the given value."),
        ("INTERMEDIATE", "const arr = [1, 2, 3]; arr = [4, 5]; What happens?",
         ["The array becomes [4, 5]", "A TypeError is thrown because const cannot be reassigned", "arr becomes undefined", "The second value is ignored"], "B",
         "Reassigning a const variable is illegal and throws a TypeError at runtime."),
        ("INTERMEDIATE", "const m = new Map(); const key = { id: 1 }; m.set(key, 'found'); What does m.get(key) return?",
         ["undefined", "NaN", "found", "a new map"], "C",
         "Map keys work by reference, so the same object key retrieves the stored value 'found'."),
        ("INTERMEDIATE", "What is the result of [1, 2, 3, 4].filter(n => n % 2 === 0)?",
         ["[1, 3]", "[2, 4]", "[1, 2, 3, 4]", "[]"], "B",
         "filter keeps only even numbers, so the result is [2, 4]."),
        ("INTERMEDIATE", "What is the result of [1, 2, 3].map(x => x * 2).filter(x => x > 3)?",
         ["[2, 4, 6]", "[2, 4]", "[6]", "[4, 6]"], "D",
         "map produces [2, 4, 6], then filter keeps only values greater than 3, giving [4, 6]."),
        ("INTERMEDIATE", "What is the result of [1, 2, 3, 4].reduce((acc, n) => acc + n, 0)?",
         ["10", "24", "4", "undefined"], "A",
         "reduce starts the accumulator at 0 and adds every element, ending at 10."),
        ("INTERMEDIATE", "const { a, b } = { a: 1, b: 2 }; What is the value of b?",
         ["2", "1", "undefined", "NaN"], "A",
         "Destructuring assigns the property b to the variable b, which holds 2."),
        ("INTERMEDIATE", "function total(...args) { return args.length; } What does total(1, 2, 3, 4) return?",
         ["undefined", "4", "1", "NaN"], "B",
         "The rest parameter collects all arguments into an array, and its length is 4."),
        ("INTERMEDIATE", "const a = [1, 2]; const b = [...a]; b.push(3); What is a now?",
         ["[1, 2, 3]", "[3]", "[]", "[1, 2]"], "D",
         "Spread creates a shallow copy, so mutating b does not change the original a."),
        ("INTERMEDIATE", "const f = (x) => { x * 2; }; What does f(4) return?",
         ["8", "4", "undefined", "NaN"], "C",
         "A block body requires an explicit return, so the function returns undefined."),
        ("INTERMEDIATE", "What is the value of the template literal `2 + 3 = ${2 + 3}`?",
         ["'2 + 3 = 5'", "'2 + 3 = 23'", "'5'", "'2 + 3 = ${2 + 3}'"], "A",
         "The embedded expression 2 + 3 evaluates to 5 and is interpolated into the string."),
        ("ADVANCED", "What is the result of [10, 9, 1].sort() in JavaScript?",
         ["[1, 10, 9]", "[1, 9, 10]", "[10, 1, 9]", "[9, 10, 1]"], "A",
         "The default sort converts values to strings, so 10 sorts before 9 lexicographically."),
        ("ADVANCED", "What does [1, 2, 2, 3].reduce((acc, n) => acc + (n % 2), 0) evaluate to?",
         ["3", "1", "8", "2"], "D",
         "Odd numbers add 1 and evens add 0, and there are two odd values, 1 and 3, so the total is 2."),
        ("ADVANCED", "const s = new Set([1, 1, 2, 3, 3]); What is s.size?",
         ["5", "4", "3", "2"], "C",
         "A Set stores only unique values, so the size is 3 for 1, 2 and 3."),
        ("ADVANCED", "What is the result of Array.from('abc')?",
         ["['a', 'b', 'c']", "'abc'", "[3]", "['abc']"], "A",
         "Array.from converts iterables, including strings, into an array of their characters."),
        ("ADVANCED", "const [first, ...rest] = [1, 2, 3, 4]; What are first and rest?",
         ["first is [1], rest is [2, 3, 4]", "first is 1, rest is [4]", "first is 1, rest is [2, 3, 4]", "first is 4, rest is [1, 2, 3]"], "C",
         "Destructuring assigns the first element to first and collects the remaining elements into rest."),
        ("ADVANCED", "What does Array.isArray(null) return?",
         ["true", "false", "TypeError", "null"], "B",
         "null is not an array, so Array.isArray returns false."),
        ("ADVANCED", "console.log(dbl(2)); const dbl = (x) => x * 2; What is the output?",
         ["4", "undefined", "ReferenceError", "NaN"], "C",
         "Arrow functions are not hoisted like declarations, and the const access before initialization throws a ReferenceError."),
        ("ADVANCED", "What is the result of [1, [2, [3, 4]]].flat(2)?",
         ["[1, 2, [3, 4]]", "[1, [2, [3, 4]]]", "[[1, 2, 3, 4]]", "[1, 2, 3, 4]"], "D",
         "flat with depth 2 flattens both nesting levels, producing [1, 2, 3, 4]."),
        ("ADVANCED", "const a = { x: 1 }; const b = { ...a, y: 2 }; What does b contain?",
         ["{ x: 1 }", "{ x: 1, y: 2 }", "{ y: 2 }", "{ x: 2, y: 2 }"], "B",
         "Object spread copies the x property and adds y, yielding { x: 1, y: 2 }."),
        ("ADVANCED", "Which statement about array mutation is correct?",
         ["sort mutates the original array, while map returns a new array", "map mutates the original array", "slice mutates the original array", "filter changes the original in place"], "A",
         "sort modifies the array in place, whereas map and filter return new arrays."),
    ],
    25: [
        ("BEGINNER", "What is a Promise in JavaScript?",
         ["A synchronous data type", "A CSS property", "An object representing the eventual result of an asynchronous operation", "A function that blocks the main thread"], "C",
         "A Promise wraps an async task and lets you handle its eventual success or failure."),
        ("BEGINNER", "What does the fetch() API return?",
         ["A Promise", "A string of JSON", "A callback object", "An HTML element"], "A",
         "fetch returns a Promise that resolves with a Response object when the request completes."),
        ("BEGINNER", "Which keyword pauses an async function until a Promise settles?",
         ["wait", "await", "pause", "hold"], "B",
         "await suspends the async function until the awaited Promise resolves or rejects."),
        ("BEGINNER", "What does promise.then(cb) arrange to happen?",
         ["cb runs immediately", "cb runs only if the promise rejects", "cb runs after the promise fulfills", "cb cancels the promise"], "C",
         "then registers a callback that executes when the promise is fulfilled."),
        ("BEGINNER", "What is a callback function in asynchronous programming?",
         ["A function that always runs synchronously", "A built-in browser API", "A way to declare constants", "A function passed as an argument to run later when an operation completes"], "D",
         "Callbacks let code respond later, after an asynchronous operation finishes."),
        ("BEGINNER", "What does setTimeout(fn, 1000) do?",
         ["Runs fn 1000 times", "Runs fn after a delay of about 1000 milliseconds", "Runs fn instantly", "Cancels fn after 1 second"], "B",
         "setTimeout schedules fn to run after the specified delay in milliseconds."),
        ("BEGINNER", "What is the event loop responsible for?",
         ["Managing how callbacks and tasks are queued and executed on the single thread", "Rendering CSS", "Compiling the code to Java", "Saving data to the disk"], "A",
         "The event loop coordinates the task and microtask queues so async code runs smoothly."),
        ("BEGINNER", "What are the three states of a Promise?",
         ["open, closed and waiting", "start, run and stop", "idle, busy and done", "pending, fulfilled and rejected"], "D",
         "A promise starts pending and settles into either fulfilled or rejected."),
        ("BEGINNER", "Which method handles a rejected Promise?",
         ["promise.then", "promise.catch", "promise.retry", "promise.finally"], "B",
         "catch registers a handler that runs when the promise is rejected."),
        ("BEGINNER", "What does Promise.all([p1, p2, p3]) do?",
         ["Resolves when all three promises have fulfilled", "Resolves with the first settled promise", "Cancels all three promises", "Returns the last promise only"], "A",
         "Promise.all waits for every promise and rejects early if any one rejects."),
        ("INTERMEDIATE", "console.log('a'); setTimeout(() => console.log('b'), 0); console.log('c'); What is the order of output?",
         ["a, c, b", "a, b, c", "b, a, c", "c, b, a"], "A",
         "Synchronous logs print first, then the timed callback runs after the current call stack clears."),
        ("INTERMEDIATE", "What happens to a Promise that is created but never settled?",
         ["It resolves to undefined", "It rejects with an error", "It throws immediately", "It remains pending forever"], "D",
         "A promise with neither resolve nor reject called stays in the pending state indefinitely."),
        ("INTERMEDIATE", "Promise.resolve(5).then(n => n * 2).then(n => n + 1) What value reaches the final then?",
         ["10", "5", "11", "6"], "C",
         "The value flows through each then: 5 becomes 10, then 10 becomes 11."),
        ("INTERMEDIATE", "What does Promise.resolve(7) return?",
         ["The number 7 directly", "A fulfilled promise holding the value 7", "A rejected promise", "undefined"], "B",
         "Promise.resolve wraps the value in an already fulfilled promise."),
        ("INTERMEDIATE", "If an error is thrown inside a .then handler, where does it go?",
         ["It is silently ignored", "It propagates to the next .catch in the chain", "It crashes the process immediately", "It resolves the next then"], "B",
         "Rejections and thrown errors in a chain flow down to the nearest subsequent catch."),
        ("INTERMEDIATE", "What does an async function always return?",
         ["A string", "The resolved value directly", "A Promise", "undefined"], "C",
         "Every async function returns a Promise, even if you return a plain value."),
        ("INTERMEDIATE", "async function f() { try { await Promise.reject('boom'); } catch (e) { return e; } } What will f() ultimately resolve to?",
         ["'boom'", "undefined", "a rejected promise", "null"], "A",
         "The try/catch catches the rejection and returns its value, so f resolves with 'boom'."),
        ("INTERMEDIATE", "new Promise(r => r()).then(() => console.log('m')); console.log('s'); What is the order of output?",
         ["m then s", "s then m", "s only", "m only"], "B",
         "Promise callbacks are microtasks that run after the synchronous log, so 's' prints first."),
        ("INTERMEDIATE", "const slow = new Promise(r => setTimeout(() => r('slow'), 2000)); const fast = new Promise(r => setTimeout(() => r('fast'), 1000)); Promise.race([slow, fast]) resolves with what?",
         ["'slow'", "an array of both", "'fast'", "undefined"], "C",
         "race settles with the first promise to settle, which is fast after 1 second."),
        ("INTERMEDIATE", "async function f() { let a = await task1(); let b = await task2(); } How do the two awaits execute?",
         ["In parallel at the same time", "task2 always runs first", "They are cancelled", "Sequentially, task2 starts only after task1 finishes"], "D",
         "Each await suspends the function, so task2 begins only after task1 resolves."),
        ("ADVANCED", "console.log('a'); Promise.resolve().then(() => console.log('b')); setTimeout(() => console.log('c'), 0); console.log('d'); What is the output order?",
         ["a, d, b, c", "a, b, c, d", "a, b, d, c", "a, d, c, b"], "A",
         "Sync code prints a and d first, the Promise microtask prints b next, and the timer callback prints c last."),
        ("ADVANCED", "Why do Promise callbacks run before a setTimeout(fn, 0) callback in the same turn?",
         ["Because timers are microtasks", "Because promise callbacks are queued as microtasks, which are drained before macrotasks", "Because setTimeout runs on another thread", "Because promises execute synchronously"], "B",
         "After each task, the event loop drains the microtask queue before processing the next macrotask."),
        ("ADVANCED", "What happens if you use await inside a regular non-async function?",
         ["The function becomes async automatically", "It waits without blocking", "A SyntaxError is thrown", "It returns a promise"], "C",
         "The await keyword is only valid inside functions declared with async, otherwise it is a syntax error."),
        ("ADVANCED", "new Promise((resolve) => { console.log('exec'); resolve(); }); When does the executor run?",
         ["When the promise is awaited", "After all other code runs", "Only when .then is called", "Immediately and synchronously when the promise is created"], "D",
         "The executor function runs synchronously at construction time, not later."),
        ("ADVANCED", "const p = Promise.all([Promise.reject('x'), Promise.resolve(1)]); What happens?",
         ["It resolves with 1", "It rejects with 'x' immediately", "It stays pending", "It resolves with ['x', 1]"], "B",
         "Promise.all rejects as soon as any input promise rejects, using that first rejection reason."),
        ("ADVANCED", "How does Promise.allSettled behave when one of its promises rejects?",
         ["It rejects with the first error", "It cancels the others", "It waits for all and reports each with a status of fulfilled or rejected", "It returns undefined"], "C",
         "allSettled never rejects; it resolves with an array of result objects describing each outcome."),
        ("ADVANCED", "What is the advantage of promise chaining with then over nesting callbacks?",
         ["It flattens the flow and centralizes error handling with catch", "It runs all callbacks in parallel", "It avoids using promises entirely", "It makes code run twice as fast"], "A",
         "Chaining keeps operations at one level and routes every error to a single catch."),
        ("ADVANCED", "new Promise((resolve) => { resolve(1); resolve(2); }); What value does the promise fulfill with?",
         ["2", "undefined", "both 1 and 2", "1"], "D",
         "A promise settles only once; the first resolve call wins and later ones are ignored."),
        ("ADVANCED", "What does response.json() return in a typical fetch chain?",
         ["A Promise resolving to the parsed body", "The raw JSON text synchronously", "An HTML document", "A callback function"], "A",
         "json() is asynchronous and returns a Promise that resolves with the parsed JSON value."),
        ("ADVANCED", "Promise.resolve().then(() => console.log(1)); Promise.resolve().then(() => console.log(2)); What is the output?",
         ["2 then 1", "only 1", "1 then 2", "only 2"], "C",
         "Microtasks run in FIFO order, so the first registered then callback logs 1 before the second logs 2."),
    ],
}
