# -*- coding: utf-8 -*-
"""
Question bank for subject 57: CORE111 - Professional Ethics & IPR.
Category: Core Computer Science & Emerging Technologies.

Topics:
  281: Professional Ethics
  282: Intellectual Property Rights
  283: Cyber Law & Data Privacy
  284: Corporate Responsibility
  285: Case Studies & Codes

Each topic: 30 questions (10 BEGINNER, 10 INTERMEDIATE, 10 ADVANCED).
"""

QUESTIONS = {
    281: [
        ("BEGINNER", "What is professional ethics in the context of computing?",
         ["A set of moral principles guiding behaviour in the profession", "A programming language", "A type of database", "A networking protocol"], "A",
         "Professional ethics provides the moral principles that guide responsible behaviour in a profession."),
        ("BEGINNER", "Which principle means software professionals should avoid harming users through their work?",
         ["Do no harm", "Always maximise profit", "Never document code", "Hide security flaws"], "A",
         "Avoiding harm is a foundational duty of engineering and computing professionals."),
        ("BEGINNER", "Which of the following is a widely recognised code of ethics for computing professionals?",
         ["ACM Code of Ethics", "A restaurant menu", "A shipping manifest", "A passport stamp"], "A",
         "The ACM Code of Ethics outlines the responsibilities of computing professionals to society."),
        ("BEGINNER", "What does confidentiality mean in a professional context?",
         ["Protecting private information entrusted to you", "Sharing passwords publicly", "Copying files freely", "Publishing all emails"], "A",
         "Confidentiality obliges professionals to keep sensitive information private and secure."),
        ("BEGINNER", "What is a conflict of interest?",
         ["A situation where personal interests could influence professional judgement", "A runtime error", "A compiler warning", "A DNS failure"], "A",
         "A conflict of interest arises when personal or financial interests may bias professional decisions."),
        ("BEGINNER", "Which behaviour is an example of professional integrity?",
         ["Being honest about what you have and have not done", "Faking test results", "Taking credit for others' work", "Hiding bugs"], "A",
         "Integrity means honesty and consistency between one's stated values and actual conduct."),
        ("BEGINNER", "Why should a professional stay updated with new technologies?",
         ["Competence requires keeping skills and knowledge current", "It is required only on Fridays", "To look busy", "To avoid meetings"], "A",
         "Maintaining competence means learning continuously because technology evolves quickly."),
        ("BEGINNER", "What does accountability mean for a software professional?",
         ["Accepting responsibility for the outcomes of your work", "Deleting error logs", "Blaming others", "Ignoring failures"], "A",
         "Accountability is owning the consequences, both good and bad, of your professional actions."),
        ("BEGINNER", "Which action best reflects fairness toward colleagues and users?",
         ["Treating all people equitably and without discrimination", "Rewarding only your friends", "Withholding information", "Overcharging clients"], "A",
         "Fairness demands equitable, non-discriminatory treatment of everyone involved."),
        ("BEGINNER", "Which statement best describes a profession's duty to society?",
         ["Weighing public interest alongside client and employer interests", "Serving only yourself", "Ignoring the public", "Maximising personal gain only"], "A",
         "Professionals have a duty to consider the public interest, not only their own or their employer's benefit."),
        ("INTERMEDIATE", "A colleague asks you to approve a test report that you know omits a real failure. What is the ethical action?",
         ["Refuse to sign it and report the omission honestly", "Sign it to be helpful", "Ignore the request", "Hide the report"], "A",
         "Approving a knowingly false report violates honesty and integrity, so it must be declined."),
        ("INTERMEDIATE", "A manager pressures you to ship code with a known security vulnerability to meet a deadline. What should you do?",
         ["Refuse to ship knowingly unsafe code and raise the risk to the appropriate person", "Ship it silently", "Quit without discussion", "Deny the vulnerability exists"], "A",
         "Shipping knowingly unsafe code harms users, so the professional duty is to refuse and escalate."),
        ("INTERMEDIATE", "A developer discovers they accidentally introduced a bug that briefly exposed user data. Which action is ethical?",
         ["Disclose the incident promptly and work to fix it", "Delete the logs", "Keep it secret", "Blame the database"], "A",
         "Prompt disclosure and remediation honour honesty and protect affected users."),
        ("INTERMEDIATE", "Which situation is a clear conflict of interest for a software consultant?",
         ["Recommending a product from a company where they hold stock", "Charging for extra work", "Documenting decisions", "Using open-source tools"], "A",
         "Recommending products that enrich you personally compromises objective professional advice."),
        ("INTERMEDIATE", "A team's code passes tests but uses an accessibility-hostile design. Which ethical consideration applies?",
         ["Fairness and inclusion demand the system be usable by people with disabilities", "Tests are the only concern", "Accessibility is irrelevant", "Users should adapt"], "A",
         "Professional ethics includes fairness and inclusion, making accessibility a genuine ethical obligation."),
        ("INTERMEDIATE", "Which response is most ethical when your employer asks you to collect user data without consent?",
         ["Explain the legal and ethical problems and refuse to proceed", "Collect it because you are asked", "Anonymise it then pretend", "Charge extra for the data"], "A",
         "Collecting data without consent breaches privacy ethics and law, so refusing and explaining is correct."),
        ("INTERMEDIATE", "Which behaviour demonstrates honesty in reporting project progress?",
         ["Reporting real completion status even when it is behind schedule", "Claiming the work is done before it is", "Understating effort", "Omitting stalled tasks"], "A",
         "Accurate progress reporting lets stakeholders make informed decisions instead of being misled."),
        ("INTERMEDIATE", "A free tool you built accidentally erases users' files. What is the ethical first response?",
         ["Pause distribution, warn users and release a fixed version", "Do nothing", "Charge users for the fix", "Deny the tool caused it"], "A",
         "When software harms users, halting distribution, warning users and fixing it is the responsible course."),
        ("INTERMEDIATE", "Which principle is most relevant when deciding whether to reuse code from another project?",
         ["Respecting licences and giving proper attribution", "Ignoring licences", "Copying without credit", "Removing licence headers"], "A",
         "Licences legally govern reuse, so respecting terms and attribution is an ethical and legal duty."),
        ("INTERMEDIATE", "A new hire is asked to silently install surveillance software on office laptops. Which consideration matters most?",
         ["Whether the monitoring is lawful, disclosed and proportional", "Whether it is easy to install", "Whether it is cheap", "Whether it is fast"], "A",
         "Monitoring must be lawful, transparent and proportionate to be ethical."),
        ("ADVANCED", "Which action best models responsible disclosure when you find a serious vulnerability in a widely used product?",
         ["Notify the vendor privately, allow a fix window, then publish after coordination", "Publish the exploit immediately", "Sell the vulnerability silently", "Keep it a secret forever"], "A",
         "Coordinated disclosure gives vendors time to fix the flaw before details are made public."),
        ("ADVANCED", "An engineer is asked to write a review praising a product that actually underperforms. What is the ethical response?",
         ["Give an honest, evidence-based assessment", "Write the praise to please the client", "Refuse to engage at all", "Exaggerate the numbers"], "A",
         "Honest assessment protects the public even when the truth is inconvenient."),
        ("ADVANCED", "Which decision path best resolves an ethical dilemma involving conflicting duties to employer and users?",
         ["Weigh the risks to all stakeholders and escalate through the proper channels", "Always obey the employer", "Always favour the users blindly", "Flip a coin"], "A",
         "Stakeholder analysis and escalation help balance competing duties in an ethical dilemma."),
        ("ADVANCED", "A developer realises their algorithm disproportionately rejects qualified applicants from one demographic. Which duty applies?",
         ["The duty to avoid bias and to audit for fairness and transparency", "The duty to deploy fast", "The duty to hide the effect", "The duty to ignore statistics"], "A",
         "Fairness and transparency require auditing algorithms for discriminatory impact."),
        ("ADVANCED", "Which practice most strengthens ethical decision-making within a development team?",
         ["Creating a code of conduct and a confidential reporting channel", "Never discussing ethics", "Deciding issues privately", "Punishing honest reports"], "A",
         "Explicit codes and safe reporting channels institutionalise ethical behaviour."),
        ("ADVANCED", "An AI system gives no explanation for decisions that affect users. Which ethical principle is most compromised?",
         ["Transparency and explainability", "Throughput", "Latency", "Aesthetics"], "A",
         "Without explanations, users cannot understand or challenge decisions that affect them."),
        ("ADVANCED", "Which behaviour is most consistent with the principle of public good over personal gain?",
         ["Choosing to fix a dangerous bug that affects many users rather than a profitable pet feature", "Prioritising the profitable feature", "Ignoring the bug", "Charging users for the fix"], "A",
         "Serving the public good means prioritising harm reduction over personal profit."),
        ("ADVANCED", "A vendor offers you a gift to influence your choice of technology for a client. What is the ethical response?",
         ["Decline the gift and disclose the offer to your client", "Accept it quietly", "Accept it and choose the vendor", "Accept it only if small"], "A",
         "Declining and disclosing prevents undue influence and preserves professional independence."),
        ("ADVANCED", "Which approach best balances innovation with the ethical duty of care?",
         ["Building safety checks and impact assessments into the development process", "Moving fast and ignoring risks", "Deferring all safety", "Hiding known issues"], "A",
         "Embedding safety and impact review into development prevents harm without stopping innovation."),
        ("ADVANCED", "When asked to certify a product you did not fully test, what is the most professional response?",
         ["Decline to certify beyond the evidence and explain the gap", "Certify it anyway", "Certify with a false date", "Decline and refuse all communication"], "A",
         "Certification must match the evidence; certifying untested claims misleads the public."),
    ],
    282: [
        ("BEGINNER", "Which type of IP protects inventions with a technical solution?",
         ["Patent", "Trademark", "Trade secret", "Copyright"], "A",
         "A patent grants exclusive rights over an invention that is novel, inventive and industrially applicable."),
        ("BEGINNER", "Which form of IP protects original creative works such as books, music and software?",
         ["Copyright", "Patent", "Trademark", "Domain name"], "A",
         "Copyright protects original expressions such as literary, musical and artistic works including code."),
        ("BEGINNER", "Which IP right protects brand names, logos and slogans that identify a business?",
         ["Trademark", "Patent", "Copyright", "Trade secret"], "A",
         "Trademarks distinguish the goods or services of one business from those of others."),
        ("BEGINNER", "Which type of IP protects confidential business information such as formulas and recipes?",
         ["Trade secret", "Patent", "Copyright", "Geographical indication"], "A",
         "Trade secrets protect confidential information that gives a business a competitive edge, like the Coca-Cola formula."),
        ("BEGINNER", "How long does copyright protection typically last for a work created by an individual?",
         ["The life of the author plus a set number of years (usually 50-70)", "One year", "Five minutes", "Ten days"], "A",
         "Copyright generally lasts for the author's lifetime plus a statutory term, commonly 50 or 70 years."),
        ("BEGINNER", "Which of the following is NOT generally protected by copyright?",
         ["An idea or fact", "A song", "A book", "A photograph"], "A",
         "Copyright protects expressions, not ideas or facts themselves."),
        ("BEGINNER", "What does the term 'fair use' or 'fair dealing' generally permit?",
         ["Limited use of copyrighted work for purposes such as education or criticism", "Unlimited copying for profit", "Free redistribution of any software", "Bypassing all rights"], "A",
         "Fair use allows limited unlicensed uses such as criticism, comment, teaching and research under certain conditions."),
        ("BEGINNER", "Which international convention harmonises patent protection across member countries?",
         ["The Paris Convention", "The Geneva Accords", "The Kyoto Protocol", "The Helsinki Declaration"], "A",
         "The Paris Convention established common rules for industrial property including patents across member states."),
        ("BEGINNER", "Which organisation administers international copyright treaties such as the Berne Convention?",
         ["WIPO", "FIFA", "ISO only", "WTO only"], "A",
         "The World Intellectual Property Organization (WIPO) administers treaties including the Berne Convention."),
        ("BEGINNER", "Which of the following can be patented?",
         ["A new, non-obvious and useful invention", "A mathematical formula in isolation", "A law of nature", "A mere idea"], "A",
         "Patents cover inventions that are new, non-obvious and useful; abstract ideas and laws of nature are excluded."),
        ("INTERMEDIATE", "A student copies a diagram from a textbook into their report. Which practice keeps them legally safe?",
         ["Citing the source and relying on fair use for academic purposes", "Copying without attribution", "Scanning it upside down", "Tracing it by hand"], "A",
         "Proper citation plus fair use for academic purposes protects the student from infringement."),
        ("INTERMEDIATE", "Which action would likely infringe the copyright of a software library?",
         ["Copying and redistributing the library's code without respecting its licence", "Reading its documentation", "Installing it via a package manager", "Calling its documented API"], "A",
         "Redistribution beyond the licence's terms is infringement; normal installation and API use are fine."),
        ("INTERMEDIATE", "A startup uses a competitor's unpatented formula they discovered independently. What is the legal situation?",
         ["They are free to use it because trade secrets protect only confidential misappropriation, not independent discovery", "They must pay royalties", "They must publish it", "They must trademark it"], "A",
         "Trade secret law protects against misappropriation, but independent development of the same information is lawful."),
        ("INTERMEDIATE", "Which scenario describes patent infringement?",
         ["Making and selling a product that falls within the claims of an in-force patent", "Reading a patent document", "Attending a patent seminar", "Publishing an article about a patent"], "A",
         "Infringement occurs when someone makes, uses or sells a patented invention without authorisation."),
        ("INTERMEDIATE", "A team finds an open-source library with a copyleft licence. What must they understand?",
         ["Derivative works must typically be released under the same licence", "They can keep their code fully proprietary", "The licence has no conditions", "They must pay money"], "A",
         "Copyleft licences such as GPL require derivative works to be distributed under compatible open terms."),
        ("INTERMEDIATE", "Why do companies often rely on trade secrets instead of patents?",
         ["Trade secrets never expire and require no public disclosure", "Trade secrets are always published", "Patents last forever", "Trade secrets are cheaper to register everywhere"], "A",
         "Trade secrets remain protected indefinitely as long as they stay secret, whereas patents expire after disclosure."),
        ("INTERMEDIATE", "A developer leaves a company with proprietary source code in memory. Which concern is most important?",
         ["They must not disclose or reuse trade secrets belonging to the former employer", "They must delete their memories", "They can publish the code freely", "They must file a patent"], "A",
         "Former employees are bound by confidentiality obligations not to disclose the employer's trade secrets."),
        ("INTERMEDIATE", "Which is the correct order for protecting an invention with a patent?",
         ["File a patent application with a description and claims, then get it examined and granted", "Sell it first, then apply", "Publish it first, then apply", "Trademark it first, then apply"], "A",
         "Patents require a complete application with claims that are examined before grant."),
        ("INTERMEDIATE", "What does a trademark search help a new business avoid?",
         ["Accidentally choosing a mark that conflicts with an existing registered mark", "Writing code", "Hiring employees", "Paying taxes"], "A",
         "A trademark search reveals conflicting marks so the business avoids infringement and rebranding costs."),
        ("INTERMEDIATE", "Which statement about software licensing is correct?",
         ["Licences grant specific rights and permissions; using software without the required licence may infringe copyright", "Licences do not matter", "All software is free", "Licences only apply to hardware"], "A",
         "Software is protected by copyright, and licences define the permitted uses."),
        ("ADVANCED", "A company reverse-engineers a rival's product to build a compatible one. Which legal analysis matters most?",
         ["Whether reverse engineering breaches the licence, contract or relevant trade-secret laws", "Whether the rival will notice", "Whether the colours match", "Whether the team is fast"], "A",
         "Reverse engineering is evaluated against licence terms and trade-secret law, not just market behaviour."),
        ("ADVANCED", "A researcher combines two patented components into a new product. What must be assessed?",
         ["Whether the combination falls within the claims of existing patents and needs licences", "Whether the parts are shiny", "Whether the product is heavy", "Whether the name is catchy"], "A",
         "Combining patented parts can still infringe if the combination is covered by existing patent claims."),
        ("ADVANCED", "Which strategy best balances open-source contribution with protecting a company's core advantage?",
         ["Publishing non-core modules openly while keeping differentiating algorithms as trade secrets", "Publishing all code", "Open-sourcing nothing", "Ignoring licences"], "A",
         "Strategic open sourcing builds goodwill while trade secrecy protects the real competitive edge."),
        ("ADVANCED", "Why do patents require an inventor to disclose the invention fully in the application?",
         ["The disclosure enriches public knowledge in exchange for the temporary monopoly", "It speeds up the trademark office", "It hides the invention", "It prevents all competition forever"], "A",
         "The patent bargain trades public disclosure for a limited exclusive right, advancing the public knowledge."),
        ("ADVANCED", "Which scenario most clearly constitutes trade-secret misappropriation?",
         ["An ex-employee shares a secret formula obtained under a signed NDA with a competitor", "An employee learns general industry skills", "A rival independently invents the formula", "A journalist reports a public patent"], "A",
         "Breaching an NDA by sharing the secret acquired in confidence is classic misappropriation."),
        ("ADVANCED", "A startup must choose between patenting and keeping a process secret. Which factor most favours a patent?",
         ["The process is easy to reverse-engineer from the final product", "The process is impossible to detect", "The process is a marketing phrase", "The process changes every month"], "A",
         "If rivals could reverse-engineer the innovation, a patent gives enforceable protection; otherwise secrecy may work."),
        ("ADVANCED", "Which analysis determines whether a new app infringes a competitor's design patent?",
         ["Comparing the claimed design features of the patent with the app's visual appearance", "Comparing the app's memory usage", "Counting the app's downloads", "Reading the app's reviews"], "A",
         "Design patent infringement is judged by whether the accused design is substantially the same as the claimed design."),
        ("ADVANCED", "A company hires a developer who brings code written for their previous employer. Which practice is correct?",
         ["Ensure any reuse is licensed or rewritten, and respect the previous employer's rights", "Silently reuse it", "Rename the variables", "Publish the old employer's code"], "A",
         "Reusing a former employer's code may violate copyright and confidentiality, so compliance must be ensured."),
        ("ADVANCED", "Which factor most determines the value of a patent portfolio for a technology company?",
         ["The breadth and enforceability of claims covering real products and competitors", "The number of pages in each patent", "The font of the documents", "The colour of the cover"], "A",
         "Claim breadth and enforceability over actual products drive a portfolio's strategic value."),
        ("ADVANCED", "A team unknowingly infringes a patent held by a competitor. Which is the most responsible response?",
         ["Conduct a freedom-to-operate review, seek legal advice and adjust the design or licence", "Ignore the patent", "Stop all work", "Sue first without analysis"], "A",
         "A freedom-to-operate analysis identifies exposure early, allowing design changes or licensing before it grows costly."),
    ],
    283: [
        ("BEGINNER", "Which law primarily governs cybercrime and electronic transactions in India?",
         ["The Information Technology Act, 2000", "The Companies Act", "The Motor Vehicles Act", "The Indian Penal Code only"], "A",
         "The IT Act, 2000 is India's primary legislation covering electronic records, cybercrime and e-commerce."),
        ("BEGINNER", "What does GDPR stand for?",
         ["General Data Protection Regulation", "Global Data Processing Rule", "General Digital Privacy Right", "Global Data Protection Registry"], "A",
         "GDPR is the European Union's data protection regulation governing personal data handling."),
        ("BEGINNER", "Which term describes personally identifiable information such as name, email or phone number?",
         ["Personal data", "Metadata only", "Compiled binaries", "Network packets"], "A",
         "Personal data is any information relating to an identified or identifiable person."),
        ("BEGINNER", "How is a data breach best defined in cyber security?",
         ["Unauthorised access to or disclosure of data", "A scheduled backup", "A software update", "A password reset"], "A",
         "A data breach is an incident where data is accessed or disclosed without authorisation."),
        ("BEGINNER", "Which principle of data protection means collecting only the data you actually need?",
         ["Data minimisation", "Data duplication", "Data hoarding", "Data deletion"], "A",
         "Data minimisation requires collecting and keeping the minimum amount of personal data needed."),
        ("BEGINNER", "What is informed consent in the context of personal data?",
         ["Permission given knowingly and freely after clear explanation of how data will be used", "A signature obtained by trickery", "Default opt-in with no explanation", "Buying a data licence"], "A",
         "Informed consent means users understand what they agree to and freely choose to permit it."),
        ("BEGINNER", "Which of the following is an example of sensitive personal data?",
         ["Health records", "A shirt colour", "A favourite movie", "The weather"], "A",
         "Health information is classified as sensitive personal data requiring heightened protection."),
        ("BEGINNER", "Which body typically handles complaints about data protection violations in the EU under GDPR?",
         ["A national data protection authority", "The local fire department", "The electricity board", "The postal service"], "A",
         "Each EU state has a data protection authority that supervises GDPR compliance and complaints."),
        ("BEGINNER", "Which act protects personal data in India and is modelled on GDPR principles?",
         ["The Digital Personal Data Protection Act", "The Copyright Act", "The RTI Act", "The Competition Act"], "A",
         "India's Digital Personal Data Protection Act sets rules for processing personal data with consent and purpose limits."),
        ("BEGINNER", "Which right lets a person request that an organisation delete their personal data?",
         ["The right to erasure or right to be forgotten", "The right to a free laptop", "The right to skip work", "The right to unlimited data"], "A",
         "The right to erasure lets individuals ask organisations to delete their personal data under certain conditions."),
        ("INTERMEDIATE", "An app secretly shares user location with advertisers without disclosure. Which data-protection principle is violated?",
         ["Lawfulness, transparency and consent", "Data speed", "Data colour", "Data volume"], "A",
         "Processing without disclosure and consent breaches lawful, transparent and consent-based processing."),
        ("INTERMEDIATE", "Which action does GDPR require when a serious personal-data breach occurs?",
         ["Notify the supervisory authority within 72 hours and affected individuals when risk is high", "Delete all backups", "Wait for a year", "Never mention it"], "A",
         "GDPR mandates prompt breach notification to the authority and, where risk is high, to affected people."),
        ("INTERMEDIATE", "A company stores user data for marketing after the user cancels their account. Which right is relevant?",
         ["The right to erasure and objection to processing", "The right to free shipping", "The right to a refund in cash", "The right to view advertisements"], "A",
         "Former users can exercise erasure and objection rights to stop processing after the relationship ends."),
        ("INTERMEDIATE", "Which practice best satisfies the GDPR principle of purpose limitation?",
         ["Using collected data only for the stated, documented purpose", "Selling data to any buyer", "Combining data for new hidden uses", "Keeping data forever"], "A",
         "Purpose limitation requires data be used only for the specific purpose for which it was collected."),
        ("INTERMEDIATE", "What is the role of a Data Protection Officer (DPO)?",
         ["To oversee data protection compliance within an organisation", "To delete all servers", "To answer customer calls", "To design marketing banners"], "A",
         "A DPO monitors compliance, advises on data protection and liaises with supervisory authorities."),
        ("INTERMEDIATE", "Which scenario most clearly triggers a GDPR breach notification?",
         ["A hacker exfiltrates customer personal data from the database", "A font update fails", "A printer jams", "An email is misspelled"], "A",
         "Unauthorised access to personal data is a reportable breach under GDPR."),
        ("INTERMEDIATE", "Which of the following is a lawful basis for processing personal data under GDPR?",
         ["Consent, contract, legal obligation, legitimate interest, vital interest or public task", "Being curious", "Having the data", "Paying for a licence"], "A",
         "GDPR permits processing only under recognised lawful bases such as consent or legitimate interest."),
        ("INTERMEDIATE", "A website's cookie banner is designed to make accepting cookies easier than declining. Which principle does this undermine?",
         ["Freely given, informed consent", "Fast loading", "Good typography", "Colour contrast"], "A",
         "Manipulative design undermines the freeness and informed nature of consent required by privacy law."),
        ("INTERMEDIATE", "Which measure best protects personal data stored in a cloud database?",
         ["Encryption at rest, access controls and regular audits", "Leaving it unencrypted", "Sharing the admin password", "Storing a copy on a USB drive"], "A",
         "Encryption, access control and audits are the core safeguards for stored personal data."),
        ("INTERMEDIATE", "What does 'data portability' allow a user to do under GDPR?",
         ["Receive their data in a structured, machine-readable format and transfer it", "Duplicate their data into all databases", "Buy additional data", "Sell their data to competitors"], "A",
         "Portability gives users their data in a usable format so they can move services."),
        ("ADVANCED", "A company processes personal data under 'legitimate interest' but the user objects. What must the company demonstrate?",
         ["That its interests outweigh the user's rights and freedoms, with a documented balancing test", "That the user agreed in a past email", "That it is profitable", "That the user complained"], "A",
         "Under legitimate interest, the controller must show the balancing test weighs in its favour when a user objects."),
        ("ADVANCED", "Which practice best enables GDPR compliance when sharing personal data with a third-country vendor?",
         ["Using adequacy decisions, standard contractual clauses or equivalent safeguards", "Sending data without contracts", "Hiding the transfer", "Using unencrypted email"], "A",
         "Cross-border transfers require approved safeguards such as SCCs to maintain GDPR-level protection."),
        ("ADVANCED", "Which design approach best satisfies privacy by design in a new app?",
         ["Building in data minimisation, access controls and user consent from the start", "Adding privacy features after launch", "Collecting everything first", "Using default-on tracking"], "A",
         "Privacy by design embeds protection into the product architecture rather than bolting it on later."),
        ("ADVANCED", "An employer monitors all employee communications without any policy or notice. Which concern is most serious?",
         ["The monitoring likely breaches data-protection law and employment-privacy rights", "The emails are slow", "The inbox is full", "The calendar is crowded"], "A",
         "Undisclosed, disproportionate monitoring violates data protection and privacy expectations."),
        ("ADVANCED", "Which measure most reduces the risk posed by a data breach if the database is stolen?",
         ["Encrypting the database and limiting what personal data is stored", "Backing up the plaintext", "Storing passwords in a text file", "Making the database public"], "A",
         "Encryption and minimisation make a stolen database far less dangerous to data subjects."),
        ("ADVANCED", "Why does GDPR treat biometric data with special care?",
         ["It is sensitive data whose misuse can uniquely and irreversibly identify and harm people", "It looks interesting", "It is easy to store", "It has no legal meaning"], "A",
         "Biometrics are irreplaceable identifiers, so GDPR classifies them as sensitive with strict safeguards."),
        ("ADVANCED", "Which of the following best supports a defensible data retention policy?",
         ["Documented retention periods tied to business need and legal requirements", "Keeping everything forever", "Deleting randomly", "Storing all data in one place"], "A",
         "Purpose-based retention schedules balance business need with legal and privacy obligations."),
        ("ADVANCED", "An AI system trains on scraped personal data without consent. Which principle is most at risk?",
         ["Lawful basis and fairness of processing", "Processing speed", "Model size", "Deployment cost"], "A",
         "Training on scraped data without a lawful basis undermines the fairness and lawfulness of processing."),
        ("ADVANCED", "Which organisational response best demonstrates accountability under GDPR?",
         ["Maintaining records of processing, doing privacy impact assessments and documenting decisions", "Deleting all paperwork", "Never logging data use", "Relying on verbal promises"], "A",
         "Accountability requires documented records, PIAs and decisions that prove compliance."),
        ("ADVANCED", "What is the maximum fine tier for serious GDPR violations?",
         ["Up to 4 percent of global annual turnover or 20 million euros, whichever is higher", "A small warning", "A refund of fees", "A discount on licences"], "A",
         "GDPR's upper fine tier is 4 percent of global turnover or 20 million euros, whichever is greater."),
    ],
    284: [
        ("BEGINNER", "What is corporate responsibility (CSR)?",
         ["A company's duty to act ethically and consider social and environmental impacts", "A marketing slogan", "A tax reduction scheme", "A building design"], "A",
         "CSR means companies should behave ethically and contribute positively to society and the environment."),
        ("BEGINNER", "Which term describes the practice of reporting environmental, social and governance performance?",
         ["ESG reporting", "Profit forecasting", "Inventory counting", "Payroll processing"], "A",
         "ESG reporting discloses a company's environmental, social and governance impacts to stakeholders."),
        ("BEGINNER", "What does corporate governance refer to?",
         ["The system by which companies are directed and controlled", "The office furniture", "The company logo", "The annual party"], "A",
         "Corporate governance is the framework of rules and practices guiding how a company is run."),
        ("BEGINNER", "Which stakeholder group directly owns a company?",
         ["Shareholders", "The weather", "Competitors only", "The printer company"], "A",
         "Shareholders hold ownership stakes in the company through their shares."),
        ("BEGINNER", "What is sustainability in a corporate context?",
         ["Meeting present needs without compromising the ability of future generations to meet theirs", "Maximising profits this quarter", "Minimising salaries", "Using unlimited resources"], "A",
         "Sustainability balances economic, social and environmental needs for the long term."),
        ("BEGINNER", "Which of the following is an example of an environmental responsibility?",
         ["Reducing a company's carbon footprint", "Shortening meetings", "Renaming products", "Changing the logo colour"], "A",
         "Lowering carbon emissions is a concrete environmental responsibility of organisations."),
        ("BEGINNER", "What is the purpose of a corporate code of conduct?",
         ["To set out the ethical standards expected of employees and leadership", "To increase file size", "To replace the constitution", "To advertise products"], "A",
         "A code of conduct formalises the ethical behaviour expected across the organisation."),
        ("BEGINNER", "Which group includes employees, customers, suppliers, community and shareholders?",
         ["Stakeholders", "Programmers only", "Auditors only", "Competitors only"], "A",
         "Stakeholders are all parties affected by or interested in a company's activities."),
        ("BEGINNER", "What is the 'triple bottom line'?",
         ["Measuring profit, people and planet", "Three bank accounts", "Three product lines", "Three factories"], "A",
         "The triple bottom line evaluates a company's economic, social and environmental performance."),
        ("BEGINNER", "Which of the following is an example of social responsibility by a company?",
         ["Running an ethical supply-chain programme that protects workers", "Discarding old stock in a river", "Exploiting cheap labour", "Hiding safety risks"], "A",
         "Protecting workers in the supply chain is a clear social responsibility action."),
        ("INTERMEDIATE", "A company discovers its supplier uses child labour. Which action reflects genuine corporate responsibility?",
         ["Investigate, suspend the supplier and enforce corrective measures", "Ignore it to keep costs low", "Double the orders", "Publicly deny it"], "A",
         "Responsible companies act on supplier misconduct rather than look away for profit."),
        ("INTERMEDIATE", "Which practice best demonstrates a company taking accountability for a product defect?",
         ["Issuing a recall, fixing the fault and communicating transparently", "Hiding the recall", "Blaming customers", "Waiting for lawsuits"], "A",
         "Proactive recall and transparency show genuine accountability to affected users."),
        ("INTERMEDIATE", "A firm claims to be green but quietly ignores pollution at its factory. What is this called?",
         ["Greenwashing", "Recycling", "Carbon offsetting", "Eco-labelling"], "A",
         "Greenwashing is misleadingly presenting an environmentally responsible image while acting otherwise."),
        ("INTERMEDIATE", "Which action best shows a company respecting its employees as stakeholders?",
         ["Providing fair wages, safe conditions and open communication", "Paying minimum effort", "Silencing feedback", "Layoffs without notice"], "A",
         "Fair treatment and safety are core expectations of employee stakeholder relations."),
        ("INTERMEDIATE", "What is the main purpose of an independent board of directors in governance?",
         ["To oversee management and protect shareholder and stakeholder interests", "To approve all salaries of competitors", "To design ads", "To file tax returns only"], "A",
         "Independent boards provide oversight that checks management power and protects stakeholders."),
        ("INTERMEDIATE", "Which of the following is an example of governance failure?",
         ["Managers falsifying financial statements to inflate share price", "Holding an annual general meeting", "Publishing annual reports", "Electing an audit committee"], "A",
         "Falsified accounts are a classic governance failure that misleads investors and regulators."),
        ("INTERMEDIATE", "A company's data breach affects millions of users. Which stakeholder communication is most responsible?",
         ["Prompt, honest disclosure with guidance for affected users", "Silence", "Denying it happened", "Blaming the users"], "A",
         "Honest, timely disclosure respects affected stakeholders and regulatory duties."),
        ("INTERMEDIATE", "Which approach best reflects the stakeholder model of a company?",
         ["Balancing the interests of all affected groups rather than shareholders alone", "Serving only shareholders", "Ignoring all groups", "Serving only management"], "A",
         "The stakeholder model weighs the legitimate interests of every affected party."),
        ("INTERMEDIATE", "Why do many companies publish annual sustainability reports?",
         ["To be transparent with stakeholders about environmental and social performance", "To increase storage costs", "To avoid audits", "To advertise discounts"], "A",
         "Sustainability reporting provides transparency and accountability to interested stakeholders."),
        ("INTERMEDIATE", "A supplier's factory has unsafe working conditions. Which action by the buyer company is most responsible?",
         ["Audit the factory, require corrective action and stop orders if needed", "Keep ordering because it is cheap", "Rename the supplier", "Ignore the conditions"], "A",
         "Auditing and enforcing improvement shows the buyer takes supply-chain responsibility seriously."),
        ("ADVANCED", "Which governance structure most reduces the risk of executives hiding misconduct?",
         ["An independent audit committee with whistle-blower protections", "A single all-powerful CEO", "No internal controls", "Oral-only reporting"], "A",
         "Independent oversight and safe reporting channels make misconduct harder to conceal."),
        ("ADVANCED", "A company must cut costs and considers closing a plant that employs an entire town. Which approach best balances responsibilities?",
         ["Engaging stakeholders, seeking alternatives and planning a responsible transition", "Closing abruptly", "Hiding the plan", "Laying off everyone overnight"], "A",
         "Responsible transition planning weighs community impact and stakeholder communication."),
        ("ADVANCED", "Which analysis framework helps a company evaluate its true social impact beyond profit?",
         ["Stakeholder and ESG impact assessments covering economic, social and environmental effects", "A quick profit calc", "A brand survey", "A payroll check"], "A",
         "ESG and stakeholder assessment give a complete picture of a company's real impact."),
        ("ADVANCED", "A technology firm's AI product is found to discriminate. Which action best reflects accountability?",
         ["Pause the product, fix the bias and disclose the findings", "Deny the findings", "Rename the model", "Blame the users"], "A",
         "Pausing, fixing and disclosing is genuine accountability for algorithmic harm."),
        ("ADVANCED", "Why might a company adopt an ethical supply-chain policy even when it raises costs?",
         ["It protects the brand, reduces legal risk and aligns with stakeholder expectations", "It lowers quality", "It is required by law everywhere", "It reduces all costs"], "A",
         "Ethical sourcing is a long-term investment in trust and risk reduction despite short-term cost."),
        ("ADVANCED", "Which practice best prevents corruption in corporate procurement?",
         ["Transparent bidding, conflict-of-interest declarations and independent audits", "Secret deals", "Personal favours", "Cash payments"], "A",
         "Transparency and independent oversight are the standard defences against procurement corruption."),
        ("ADVANCED", "A company quietly uses cheap components that fail after the warranty. Which stakeholder is most harmed?",
         ["Customers who depend on the product's reliability", "The marketing team", "The office plants", "The shareholders only"], "A",
         "Hidden quality cuts harm customers who rely on the product, violating their trust."),
        ("ADVANCED", "Which reporting practice best demonstrates genuine commitment to sustainability rather than greenwashing?",
         ["Publishing verifiable targets, metrics and independent verification of results", "Posting vague eco slogans", "Framing one tree photo", "Releasing no data"], "A",
         "Measurable, verified targets separate real sustainability from image-driven claims."),
        ("ADVANCED", "When a company's short-term profit conflicts with the community's long-term wellbeing, what does good governance require?",
         ["Considering the wider impact and seeking a responsible balance with stakeholder input", "Always choosing profit", "Always choosing the community blindly", "Deferring the decision forever"], "A",
         "Good governance weighs long-term social impact against short-term gain through stakeholder engagement."),
        ("ADVANCED", "Which combination best builds a culture of corporate responsibility?",
         ["Leadership commitment, enforceable codes, incentives and transparent reporting", "A single slogan", "Fear of the CEO", "Mandatory overtime"], "A",
         "Responsibility is sustained by leadership, codes, incentives and transparency working together."),
    ],
    285: [
        ("BEGINNER", "Which of the following is a classic case of corporate fraud involving falsified accounts?",
         ["Enron", "A coffee machine", "A traffic light", "A pocket calculator"], "A",
         "Enron is a landmark case of accounting fraud that collapsed after falsified financial reports were exposed."),
        ("BEGINNER", "Which case led to the Sarbanes-Oxley Act requiring stronger corporate governance?",
         ["Enron and WorldCom", "The Merger of two car brands", "A trademark dispute over a shoe", "A minor fine for littering"], "A",
         "The Enron and WorldCom scandals triggered SOX, which tightened financial reporting and accountability."),
        ("BEGINNER", "What is the main purpose of a professional code of conduct?",
         ["To set the standards of ethical behaviour for practitioners in a field", "To increase licence fees", "To replace the law", "To decorate office walls"], "A",
         "A code of conduct codifies the ethical standards professionals are expected to uphold."),
        ("BEGINNER", "Which of the following is a famous case about unauthorized data collection by a social network?",
         ["The Cambridge Analytica case involving Facebook data", "The toaster recall", "A parking ticket", "A paint colour dispute"], "A",
         "Cambridge Analytica is a widely studied case of unauthorised harvesting of personal data."),
        ("BEGINNER", "Which organisation maintains the Software Engineering Code of Ethics?",
         ["ACM and IEEE", "The World Bank", "UNESCO only", "The Olympic Committee"], "A",
         "The ACM and IEEE jointly maintain the Software Engineering Code of Ethics and Professional Practice."),
        ("BEGINNER", "What is the main ethical duty illustrated by the Volkswagen emissions scandal?",
         ["Avoiding deception about product performance", "Designing sporty cars", "Cutting production costs", "Increasing advertising"], "A",
         "Volkswagen deceived regulators and buyers about emissions, violating honesty and public trust."),
        ("BEGINNER", "Which term describes revealing wrongdoing inside an organisation to outsiders or authorities?",
         ["Whistle-blowing", "Networking", "Outsourcing", "Benchmarking"], "A",
         "Whistle-blowing is exposing misconduct that the organisation fails to correct internally."),
        ("BEGINNER", "In a code of ethics, what does 'public interest' primarily require of professionals?",
         ["Prioritising the wellbeing of the public in their decisions", "Maximising personal salary", "Pleasing the loudest client", "Avoiding all work"], "A",
         "Public interest means professionals weigh the impact of their work on society as a whole."),
        ("BEGINNER", "Which of the following cases involved the theft of trade secrets by departing employees?",
         ["The Waymo vs Uber self-driving trade-secret lawsuit", "A library fine", "A rebranding of a soft drink", "A stadium naming deal"], "A",
         "Waymo accused Uber of using self-driving trade secrets taken by a departing engineer."),
        ("BEGINNER", "Which document typically defines the expectations of ethical behaviour for employees of a company?",
         ["Employee code of conduct", "The product manual", "The building lease", "The parking policy only"], "A",
         "The employee code of conduct sets out the ethical and behavioural expectations in the workplace."),
        ("INTERMEDIATE", "In the Volkswagen case, which ethical failure was most central?",
         ["Engineers and managers colluded to defeat emissions testing", "The cars were too fast", "The logo was confusing", "The dealerships were small"], "A",
         "Deliberately circumventing emissions tests is deception of regulators and the public."),
        ("INTERMEDIATE", "Which response is most ethical when you observe a colleague taking credit for another's work?",
         ["Raise the issue through proper channels and support the wronged colleague", "Stay silent", "Also take credit", "Post about it online"], "A",
         "Addressing unfair credit through proper channels upholds fairness and integrity."),
        ("INTERMEDIATE", "In the Cambridge Analytica case, what was the key ethical breach?",
         ["Personal data was harvested without users' meaningful consent and used for targeting", "The data was stored in the cloud", "The software was written in Python", "The ads were colourful"], "A",
         "The core wrong was collecting personal data beyond users' expectations and consent."),
        ("INTERMEDIATE", "Which whistle-blowing scenario is most justified ethically?",
         ["Disclosing a genuine public-safety hazard after internal channels failed", "Leaking private jokes", "Revealing salaries out of spite", "Posting trade secrets for fame"], "A",
         "Disclosure is most justified when it prevents serious harm and internal remedies have been exhausted."),
        ("INTERMEDIATE", "Which step should a professional take before publicly blowing the whistle on misconduct?",
         ["Report internally first and follow documented escalation paths", "Go straight to the press", "Tell everyone on social media", "Remain silent forever"], "A",
         "Internal reporting first respects the organisation's processes and often resolves the issue without publicity."),
        ("INTERMEDIATE", "In a case where a company faked test data, which principle did the engineers most directly violate?",
         ["Honesty and integrity in reporting results", "Punctuality", "Dress code", "Team size"], "A",
         "Falsifying test data is a direct violation of honesty and scientific integrity."),
        ("INTERMEDIATE", "A code review finds a developer copied code without licence. Which action is most appropriate?",
         ["Remove or licence the code and notify the affected team", "Leave it because it works", "Hide it in another file", "Blame the compiler"], "A",
         "Unlicensed code is a legal and ethical problem that must be resolved promptly."),
        ("INTERMEDIATE", "Which ethical principle is most relevant to the Theranos blood-testing scandal?",
         ["The duty not to deceive patients about the validity of medical results", "The duty to raise prices", "The duty to brand well", "The duty to hire many people"], "A",
         "Theranos misled patients with unreliable results, violating honesty and safety duties."),
        ("INTERMEDIATE", "What is the purpose of ethics case studies in professional training?",
         ["To practise reasoning about realistic dilemmas before facing them", "To memorise company names", "To learn marketing", "To earn certificates faster"], "A",
         "Case studies let professionals rehearse ethical reasoning in realistic, low-stakes situations."),
        ("INTERMEDIATE", "Which of the following best describes the ethical lesson of the Theranos scandal?",
         ["Claims about product performance must be validated by independent, honest testing", "Marketing must be loud", "Investors should never ask questions", "Testing is optional"], "A",
         "Theranos shows that unverified performance claims can cause real harm and must be independently validated."),
        ("ADVANCED", "In the Enron case, what role did auditors play in the ethical failure?",
         ["They failed to question irregular accounting, undermining their independence", "They improved the software", "They designed the building", "They set the share price"], "A",
         "Compromised auditor independence allowed the fraud to go undetected, a key governance lesson."),
        ("ADVANCED", "Which governance change directly resulted from the Enron and WorldCom scandals?",
         ["The Sarbanes-Oxley Act requiring internal controls and executive certification", "A ban on all mergers", "Mandatory open offices", "A freeze on executive pay forever"], "A",
         "SOX mandated stronger internal controls, independent audits and CEO certification of financial statements."),
        ("ADVANCED", "Which ethical framework best explains the decision to recall a dangerous product proactively?",
         ["Utilitarianism, which weighs overall public benefit against the company's cost", "A pure profit test", "A marketing plan", "A personal preference"], "A",
         "A recall prioritises the greatest good for the many, a hallmark of utilitarian reasoning."),
        ("ADVANCED", "Which analysis distinguishes a justified whistle-blower from a malicious leaker?",
         ["The severity of the harm, the motive and whether internal channels were tried", "The leaker's job title", "The length of the document", "The day of the week"], "A",
         "Justified whistle-blowing is driven by harm prevention, honest motive and exhausted internal remedies."),
        ("ADVANCED", "In the Waymo vs Uber case, which process failure enabled the alleged trade-secret theft?",
         ["Weak onboarding and due-diligence controls when the engineer was hired", "Too many meetings", "Fast cars", "Bright logos"], "A",
         "The case highlighted how weak hiring controls let protected material move between companies."),
        ("ADVANCED", "Which response best demonstrates applying a code of ethics to an ambiguous real-world dilemma?",
         ["Document the dilemma, consult the code and seek guidance from peers or ethics bodies", "Flip a coin", "Follow the loudest opinion", "Ignore the issue"], "A",
         "Structured consultation with the code and experienced peers yields defensible ethical decisions."),
        ("ADVANCED", "Which ethical lesson is most directly drawn from the Cambridge Analytica case for developers?",
         ["Data collection design must respect consent even when profitable", "APIs should be faster", "Ads should be bigger", "Users are responsible for everything"], "A",
         "The case taught that technical convenience must never override user consent and privacy."),
        ("ADVANCED", "When two code-of-conduct clauses conflict, which method best resolves the dilemma?",
         ["Weighing the underlying values such as public safety against confidentiality case by case", "Following the alphabet", "Choosing randomly", "Ignoring the conflict"], "A",
         "Ethical reasoning ranks underlying values to resolve conflicts between competing clauses."),
        ("ADVANCED", "Which outcome of the Theranos case best illustrates corporate accountability?",
         ["Executives faced criminal charges and the company collapsed after the fraud was exposed", "The company won an award", "The product was renamed", "The investors apologised"], "A",
         "Criminal accountability and collapse show that sustained deception has serious consequences."),
        ("ADVANCED", "Which case most clearly demonstrates the ethical duty of transparency in AI deployment?",
         ["The rejection of automated decision tools that could not be explained to those affected", "A faster sorting algorithm", "A new colour scheme", "A smaller server"], "A",
         "Demands for explainable, transparent AI decisions stem from the ethical duty to not harm users invisibly."),
    ],
}
